### ISSUE TITLE
Fractional shading surface transmittance schedule gives strange results (but not always)

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#10022]
Issue overview
--------------
Effort to correct shading surface control using EMS via #10008 identified an issue with shading surface control when the transmittance schedule is a fraction (e.g. 0.8). See discussion on that PR for synopsis. One test file looks reasonable, the other does not.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Actually, the strange results happen with a fractional transmittance schedule (e.g. 0.8) even with a simple schedule and no Python or EMS.

**Comment by mjwitte** [comment]
Here's a simple case based on the 1ZoneUncontrolled Geometry. First add an overhang, then add a scheduled vertical south shading surface.

![image](https://github.com/NREL/EnergyPlus/assets/4991075/00c762ac-f74a-46b0-9c3a-13c2cdee9e9e)

![image](https://github.com/NREL/EnergyPlus/assets/4991075/2f3707d2-4f9b-4d15-8217-1d77753ec9b3)

The orange lines for Overhang+Scheduled South Shade should never be higher than the blue lines for OverhangOnly. The first day is a winter day where the overhang only has a small impact. The summer day is where the problem can be seen clearly. Diffuse results seem reasonable, but for the sunlit fraction which impacts the beam results, it appears that shading from the overhang gets overlooked when the south shade with fractional transmittances shades the same surface.

**Comment by RKStrand** [comment]
@rraustad @mjwitte Are either one of you planning to look at/fix this? If yes, great! If not, I might.

**Comment by mjwitte** [comment]
@RKStrand Yes, I've been looking at it. Silly me, I thought yesterday that I had figured out the overlapping shadows algorithm and knew how to fix it.
