### ISSUE TITLE
EMS cannot control the air flow rate of the second `AirloopHVAC` object

### ISSUE THREAD

**Issue by luzechao** [NREL/EnergyPlus#10038]
Issue overview
--------------
The second `AirloopHVAC` object has a `AirLoopHVAC:OutdoorAirSystem`, a `Fan:VariableVolume`, a cooling coil and a heating coil. I tried to use EMS to control the Air Mass Flow Rate of the outdoor air controller or control the fan air mass flow rate, but none of these  works. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows 11
 - Version of EnergyPlus (if using an intermediate build, include SHA): EnergyPlus 22.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here) [in.txt](https://github.com/NREL/EnergyPlus/files/11533941/in.txt)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lgu1234** [comment]
@luzechao I added two more output variables in your defect file using Chicago weather:
  Output:Variable,*,Air System Outdoor Air Limiting Factor,Hourly;
  Output:Variable,DOAS Outdoor Air Inlet,System Node Mass Flow Rate,Hourly;

After checking outputs, I found EMS does work. Enclosed is a screen shot with a part of outputs:

![EMS](https://github.com/NREL/EnergyPlus/assets/5970656/bb935943-56d4-4d29-bbba-4d6c6a76b270)

Here are description of Air System Outdoor Air Limiting Factor:

4 = Mixed Air Flow Outdoor air flow rate is limited by the current mixed air flow rate.
9 = Energy Management System An EnergyManagementSyste:Actuator has overridden the outdoor
air flow rate.

The code has restriction for EMS override: If the mixed airflow rate is less than the EMS flow rate, the mixed airflow rate is used:

    if (this->EMSOverrideOARate) {
        this->OAMassFlow = this->EMSOARateValue;
        this->OALimitingFactor = OALimitFactor::EMS;
    }

    // Don't let OA flow be > mixed air flow.
    // Seems if RAB (return air bypass) that this should be don't let OA flow be > design supply flow but that causes other issues
    if (this->MixMassFlow < this->OAMassFlow) {
        this->OAMassFlow = this->MixMassFlow;
        this->OALimitingFactor = OALimitFactor::MixedAir;
    }

Hope this helps.

**Comment by luzechao** [comment]
Thanks! It helped a lot. It's good to know that I can output the limiting factor.
