### ISSUE TITLE
DDY file to epJSON with ConverterInputFormat

### ISSUE THREAD

**Issue by AlejandroCampoy** [NREL/EnergyPlus#10037]
Issue overview
--------------
DDY files use the same standard as IDF files. Therefore, I guess converting them to epJSON (or json) should be possible. My objective is to work with json for IDF and DDY files and with CSV for EPW files (they are more "generic" formats).

However, this transformation is not possible in practice. If I try to use the **ConverterInputFormat** from DDY to epJSON, it tells me that the format must be IDF. If I change the format to IDF beforehand, I get the following:

```bash
$ <root> - Missing required property 'Building'.
<root> - Missing required property 'GlobalGeometryRules'.
Errors occurred when validating input file. Preceding condition(s) cause termination.
Input file conversion failed: | 1/1 | USA_PA_Pittsburgh-Allegheny.County.AP.725205_TMY3.idf
```

Do you think it is possible that the **ConverterInputFormat** was compatible with DDY files? I know that I can rewrite DDY designdays and location in JSON format manually, but I think it could be a good idea to automatize this process.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu 22.04 LTS
 - Version of EnergyPlus (if using an intermediate build, include SHA): 23.1.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
If you make a copy of the ddy file, paste in a Building and a GlobalGeometry object from an idf example file, and save as *.idf it will convert successfully.

**Comment by mjwitte** [comment]
@Myoldmopar @JasonGlazer This does raise the question of working with epJSON fragments. There are only two `\required-object` tags: `Building` and `GlobalGeometryrules` in the IDD. Every field in `Building` has a default, and every field in `GlobalGeometryRules` could have a default. What would the implications be if we didn't require these objects?

**Comment by JasonGlazer** [comment]
I think if we defaulted the field values (and changed the code to use them without being read) then `Building` and `GlobalGeometryRules` would not need to be required but we would have to check the code carefully since those input objects have been required for so long some other dependency may exist. It would also make sense to add a warning message for a empty file.

**Comment by jasondegraw** [comment]
@mjwitte @JasonGlazer One bit of precedent has been set with `AirflowNetwork:SimulationControl`. Every field has a default and it is created if needed (with all the default values). This is a different situation, but I'd think the same thing would work (at least for `Building`, since it already has a default for everything).

**Comment by AlejandroCampoy** [comment]
> If you make a copy of the ddy file, paste in a Building and a GlobalGeometry object from an idf example file, and save as *.idf it will convert successfully.

Hi @mjwitte,
The problem here is that I want to automate the process of reading from DDY and adapting the _DesignDay_ and _Location_ information depending on the weather I am using, using Python. It is true that the idea you propose would be effective, but it would be less automatic.

**Comment by JasonGlazer** [comment]
@AlejandroCN7 you should be able to automate that part of the process in Python by simply appending to the DDY file the Building and GlobalGeometry input objects. I would probably rename the original DDY file also.

**Comment by AlejandroCampoy** [comment]
@JasonGlazer I am developing [Sinergym](https://github.com/ugr-sail/sinergym). I would like to convert DDY files directly to JSON without appending the Building and GlobalGeometry manually in order to the users can set up the weather they want without modify their own DDY files.

**Comment by jmarrec** [comment]
`GlobalGeometryRules` is such a source of confusion/errors for users that I would suggest we retain it as being mandatory.

For this specific issue - using ConvertInputFormat to convert a DDY to epJSON - how about we address it by filtering out the errors related to `Building` and `GlobalGeometryRules` being missing when the file being presented has the `.ddy` extension?
