### ISSUE TITLE
Incorrect Reporting for Outside Face Surface Heat Flux for Interzone Partitions

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#10089]
Issue overview
--------------
A user posted a comment on #8234 that mentioned what appeared to be a similar problem in that heat storage was building up over time when it should not have.  Essentially, when looking at the heat storage in a wall (difference between the inside face conduction heat flux and the outside face conduction heat flux), over an annual simulation, the sum of the heat storage should be relatively small.  The user was seeing a trend that consistently increased over time.  This seemed similar to #8234, but it is actually a completely different problem.  #8234 is specific to the finite difference solution scheme whereas this problem relates back to a reporting issue in the heat balance.  As they are two completely separate issues, this defect is being separated out for clarity.  The user's post on unmet hours can be found here:

https://unmethours.com/question/93625/infinite-heat-stored-in-ceiling/

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Innovationtablet** [comment]
I've been troubleshooting this a bit and as far as I can tell, the issue appears to affect *Interior* Surfaces and not *Exterior* Surfaces.

https://drive.google.com/file/d/14Po2rHAU3um73sJEok9cl0lXGqHwX1QV/view?usp=sharing
https://drive.google.com/file/d/137TnU6xcxblRmcEfT0CV2_eQAPb82D7C/view?usp=drive_link

**Comment by Innovationtablet** [comment]
I've been troubleshooting this a bit and as far as I can tell, the issue appears to affect *Interior* Surfaces and not *Exterior* Surfaces.

https://drive.google.com/file/d/14Po2rHAU3um73sJEok9cl0lXGqHwX1QV/view?usp=sharing
https://drive.google.com/file/d/137TnU6xcxblRmcEfT0CV2_eQAPb82D7C/view?usp=drive_link
