### ISSUE TITLE
Las Vegas Specification: the idf transition from version 4 to version 23 

### ISSUE THREAD

**Issue by sogol-karami** [NREL/EnergyPlus#10100]
Issue overview
--------------
Hi, 
I wanted to simulate the cooling load for a medium office at Las Vegas, the specification file which I found from this link " https://www.energy.gov/eere/buildings/existing-commercial-reference-buildings-constructed-or-after-1980 " is on version 4, so for simulation I need to update the file from 4 to 5, 5 to 6, ... and reach to 23. as a result I used transition but I see an error which says : 
Transition Starting
 Conversion 4.0 => 5.0
 Processing Old IDD -- V4-0-0-Energy+.idd
 Processing New IDD -- V5-0-0-Energy+.idd
 Enter "diff" for differences only, "full" for full idf outputs
-->full
 Will create new full IDFs
 Enter "yes" for including units on output lines, "no" for no units inclusion
-->yes
 Will create new IDF lines with units where applicable
 Enter "yes" for preserving blanks in default fields, "no" to fill those fields
 with defaults
-->yes
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 Enter input file name, with path
-->"C:\Users\Diamond\Desktop\transition\BenchmarkMediumOfficeNewV1.2_4.0_3B_USA_NV_LAS_VEGAS.idf"
 Processing IDF -- "C:\Users\Diamond\Desktop\transition\BenchmarkMediumOfficeNewV1.2_4.0_3B_USA_NV_LAS_VEGAS.idf"
 File not found="C:\Users\Diamond\Desktop\transition\BenchmarkMediumOfficeNewV1.
 2_4.0_3B_USA_NV_LAS_VEGAS.idf"
 Enter input file name, with path 
and it could not find the file. could you please help me? 
Thanks.

**Comment by jmarrec** [comment]
The link you shared has two versions: 1.3 which is energyplus v5.0, and 1.4 which is E+ v7.2. Why do you chose to not use any of these two (realistically pick the 1.4 (v7.2) one...) and go to the "An archive of past reference buildings files" page one to pick 1.2 at energyplus v4.0 instead? Do you specifically need the older one?

**Comment by jmarrec** [comment]
I'm going to close this issue for lack of activity.
