### ISSUE TITLE
EnergyPlus Calculation Crashes Inconsistently for  AirLoopHVAC:UnitarySystem with no heating coil

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#10118]
Issue overview
--------------
In the IDF file attached to this ticket, there are multiple AirLoopHVAC:UnitarySystem objects with no heating coil specified.  Originally I have the IDF file in EnergyPlus 9.5 format. When I run the IDF with the release version of EnergyPlus 9.5 with EPLaunch, most of the times it will crash, but sometimes it will run successfully.  So I downloaded the source code of EnergyPlus 9.5 and tried to run the IDF in debug mode in Visual Studio. It always fails at the following line of code:
https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/UnitarySystem.cc#L9654
I think it failed because the HeatCoilOutletNodeNum is 0, and in fact the unitary system does not have a heating coil at all. 

Then I updated the IDF file to version 23.1 and with release version of 23.1, I tried multiple times and the simulation always run successfully. However, when I ran the IDF in debug mode with 23.1 source code, it again reliably fails at the same line of code:
https://github.com/NREL/EnergyPlus/blob/b7a30cf169f81fec733cee276d77bb4b8152dc64/src/EnergyPlus/UnitarySystem.cc#L9936

Looking through the code,  in a different place the same quantity is calculated in a different way:
https://github.com/NREL/EnergyPlus/blob/b7a30cf169f81fec733cee276d77bb4b8152dc64/src/EnergyPlus/UnitarySystem.cc#L8333
In this block of code, it first calculates the CoolingOnlySensibleOutput based on Zone Node and the Cooling Coil Outlet Node, then the if statement below will add the heating coil load only when a heating coil exists.  

My questions are:

1. Is there an explanation of why EnergyPlus 9.5 release does not fail consistently?
2. With Version 23.1, the release version seems like always run successfully, is that expected given the that the source code really did not change?
3. To avoid potential crashes, I think the code at line 9936 should be written the same way as in line 8333. Can you confirm?

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10, version)
 - Version of EnergyPlus (EnergyPlus 9.5 and 23.1)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Defect file added (1. [EnergyPlus9.5 IDF](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/DesigndayCalc_V950.idf), 2. [EnergyPlus23.1 IDF](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/DesigndayCalc_V23.1.idf))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Yes this is a bug. That code assumes a heating coil is present. The code in the EMS function was recently fixed and was missed in the other location. The work around would be to add a heating coil and schedule it always off.

**Comment by TiejunWu** [comment]
@rraustad  Thanks for confirming the bug.  Any explanation to the randomness of  EnergyPlus 9.5 release failure? When it fails could it be that the EnergyPlus process is trying to access a memory address that is not allocated to it by the operating system? When it runs successfully, I guess that the memory address pointed to by the heating coil inlet and outlet node number just happen to be allocated to the EnergyPlus process, though they may have garbage data?

**Comment by rraustad** [comment]
@TiejunWu if the heating coil is not present then the inlet/outlet node will be 0 and an array access violation will occur. I am not sure how the release version could work in some cases and fail in others. I have made the correction to code and am working on fixing up a unit test before I commit the branch.
