### ISSUE TITLE
Air Distribution Unit (ADU) simple air leakage model uses a constant leakage flow rate regardless of the air terminal type

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#10110]
Issue overview
--------------
Air Distribution Unit (ADU) simple air leakage model uses a constant leakage flow rate regardless of the air terminal type. The upstream air-leakage mass flow rate calculation should be proportional to the maximum available flow for CV air terminal types. The current code results in a higher leakage rate than the user-specified fraction for a CV system.

### Details
Some additional details for this issue (if relevant):
 - Platform (Any, [07b51a2](https://github.com/NREL/EnergyPlus/commit/07b51a2c1ca55df2ec5ff297ef9514aa5ce4236a))
 - Version of EnergyPlus (if using an intermediate build, include SHA)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
See current and expected supply air flow rates based on a defect file for an AirLoop serving a single zone.

![ADU_LeakageModel](https://github.com/NREL/EnergyPlus/assets/5805126/6387143e-f99c-492e-a2f6-ac4817155eea)

**Comment by Nigusse** [comment]
Current code:
`
MassFlowRateUpStreamLeakMax = max(state.dataDefineEquipment->AirDistUnit(AirDistUnitNum).UpStreamLeakFrac * 
                                                                 state.dataLoopNodes->Node(InNodeNum).MassFlowRateMax * DesFlowRatio, 0.0);
`

This code should have been:

`
 MassFlowRateUpStreamLeakMax = max(state.dataDefineEquipment->AirDistUnit(AirDistUnitNum).UpStreamLeakFrac *
                                                                  state.dataLoopNodes->Node(InNodeNum).MassFlowRateMaxAvail * DesFlowRatio, 0.0);
`

Air Distribution Unit inlet node's maximum mass flow rate can differ from the maximum available. The maximum available flow rate is set based on the `Minimum Turndown Ratio` specified at `SetpointManager:WarmestTemperatureFlow` object but the current code calculates upstream leakage rate based on the Maximum Flow, which is often different from the maximum available flow.

**Comment by rraustad** [comment]
It looks to me like you can remove all references to DesFlowRatio elsewhere in code and simply use:

    state.dataDefineEquipment->AirDistUnit(AirDistUnitNum).UpStreamLeakFrac * state.dataLoopNodes->Node(InNodeNum).MassFlowRateMaxAvail
