### ISSUE TITLE
error in the quickstart web page

### ISSUE THREAD

**Issue by rleriche** [NREL/EnergyPlus#10132]
Issue overview
--------------
There is a small error on the quickstart web page

### Details
in page https://energyplus.net/quick-start#cli
the example of additional output given, "Output:Variable,*,Boiler Gas Energy,daily;" should be "Output:Variable,*,Boiler NaturalGas Energy,daily;"

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
I will fix this as part of https://github.com/NREL/EnergyPlus/pull/9925.
