### ISSUE TITLE
mac zsh kills ReadVarsESO

### ISSUE THREAD

**Issue by crossingchen** [NREL/EnergyPlus#10130]
Issue overview
--------------
I'm trying to run `ReadVarsESO eplusout.rvi` in `/Applications/EnergyPlus-9-5-0/PostProcess/ReadVarsESO` folder for my model in a terminal and got `zsh: killed     ReadVarsESO`. I copied the .rvi and .eso file into this folder.

I did some research and added the folder `/Applications/EnergyPlus-9-5-0/PostProcess` to my path but that did not fix the issue.

I also tried adding execute access `chmod u+x {/Applications/EnergyPlus-9-5-0/PostProcess/ReadVarsESO}` as per this post, https://discussions.apple.com/thread/253726078. It did not work.

Some other post on the apple community mentioned "executable isn't signed", https://discussions.apple.com/thread/254010763. Could this be the issue?

### Details
Some additional details for this issue (if relevant):
 - Platform, MacOS 13.4.1 (c) (22F770820d), Macbook Air M1 Chip
 - Version of EnergyPlus, 9.5.0

**Comment by jmarrec** [comment]
* Fixed via https://github.com/NREL/EnergyPlus/pull/9676

 so v22.2.0 and above. You should be able to use the ReadVarEso from the latest release to post process your 9.5.0 files.
