### ISSUE TITLE
`Coil:Heating:DX:MultiSpeed` Resistive Defrost Heater Capacity input affects results when Defrost Strategy is not Resistive

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#10182]
Issue overview
--------------
In the following IDF file that has a `Coil:Heating:DX:MultiSpeed` object, if you change the "Resistive Defrost Heater Capacity" input from Autosize to 200 to 2000, the Heating Coil Defrost Electricity Energy output changes. According to [the documentation](https://bigladdersoftware.com/epx/docs/22-2/input-output-reference/group-heating-and-cooling-coils.html#field-resistive-defrost-heater-capacity-1), "This numeric field defines the capacity of the resistive defrost heating element in Watts. **This input field is used only when the selected defrost strategy is resistive (see input field Defrost Strategy above)**." In this file, the Defrost Strategy is ReverseCycle, so it should not affect results.

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/12469905/in.idf.txt)

When using a `Coil:Heating:DX:SingleSpeed` object instead, the "Resistive Defrost Heater Capacity" input is correctly ignored.

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus Version 23.1.0-87ed9199d4

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
The difference seems to be caused by the single speed coil only checking if the strategy is ReverseCycle:

https://github.com/NREL/EnergyPlus/blob/f1db7f411c004a7e0122a0cf77bc9c03d3a59183/src/EnergyPlus/DXCoils.cc#L11187C27-L11187C27

While the multispeed coil checks if the strategy is ReverseCycle **and the control is OnDemand**:

https://github.com/NREL/EnergyPlus/blob/f1db7f411c004a7e0122a0cf77bc9c03d3a59183/src/EnergyPlus/DXCoils.cc#L13814-L13815

https://github.com/NREL/EnergyPlus/blob/f1db7f411c004a7e0122a0cf77bc9c03d3a59183/src/EnergyPlus/DXCoils.cc#L14029-L14030

**Comment by shorowit** [comment]
[This commit](https://github.com/NREL/EnergyPlus/commit/82a5cd2618dfd5f2514d5747405676262f52db48) is what changed the behavior to what I described right above. Prior to the commit, both the single speed and multispeed coils only checked whether the strategy is ReverseCycle.

**Comment by shorowit** [comment]
Any thoughts on this, @rraustad?

**Comment by rraustad** [comment]
These coils have 2 choices for defrost strategy and 2 choices for defrost control. Resistive defrost strategy should only work with Timed defrost control. ReverseCycle defrost strategy should work with either Defrost Control choice.

    A6 , \field Defrost Strategy
       \type choice
       \key ReverseCycle
       \key Resistive
       \default ReverseCycle
    A7 , \field Defrost Control
       \type choice
       \key Timed
       \key OnDemand
       \default Timed

I don't think code should check whether OnDemand is used with ReverseCycle.

    if (thisDXCoil.DefrostStrategy == StandardRatings::DefrostStrat::ReverseCycle &&
        thisDXCoil.DefrostControl == StandardRatings::HPdefrostControl::OnDemand) {

             ReverseCycle  Resistive
    Timed        OK           OK
    OnDemand     OK           NA
