### ISSUE TITLE
Outdated End Use Subcategory list in IORef

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#10195]
Issue overview
--------------
In the IORef documentation, the `Output:Meter` section Table 5.3 listed the following list:
![image](https://github.com/NREL/EnergyPlus/assets/64040111/3bf50fa0-2b1d-487b-9011-69bd4e1449d0)

However, according to the source code, the correct list items should be as follows: 
https://github.com/NREL/EnergyPlus/blob/95d720e4406dff5c2eb680c8ac45bf6ee92cc32a/src/EnergyPlus/OutputProcessor.cc#L215-L228
Here is what is shown in an example Tabular output, which agrees with the "Displace Name" list in the source code:
![image](https://github.com/NREL/EnergyPlus/assets/64040111/a9f0e031-fab8-4034-acb2-41917480cd2e)

So there a few changes are suggested to made to IORef Table 5.3 list:
1. In general, it is suggested to use "Display Names" that match the tabular report.	
2. For a few items, a space is needed for each to separate the names with two words: e.g. “InteriorEquipment” -> “Interior Equipment”; “ExteriorEquipment” -> “Exterior Equipment”; “HeatRejection” -> “Heat Rejection”; “HeatRecovery” -> “Heat Recovery”; “WaterSystems” -> “Water Systems”.
3.	A few names are different: “Humidifier” -> “Humidification”; “Cogeneration” -> “Generators”.
4.	For a couple of items, a space is needed, and also the names are different: “InteriorLights” -> “Interior Lighting”; “ExteriorLights” -> “Exterior Lighting”.
5.	“DHW” is no longer in use --- this is being fixed in PR #10011 (addressing original report in Issue #9143).
6.	The orders in the IORef could be made better aligned with the code or the html report.

The issue will involve documentation changes, that will be added to PR #10011 to address two issues together.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): All
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #10011
