### ISSUE TITLE
Zero DistrictHeatingSteam for ExteriorLightsAndEq.idf in eplusout.sql

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/EnergyPlus#10190]
Issue overview
--------------

The idf contains:
```
  Exterior:FuelEquipment,
    OutsideSteamEq,          !- Name
    DistrictHeatingSteam,    !- Fuel Use Type
    ON,                      !- Schedule Name
    1000;                    !- Design Level {W}
```

`eplustbl.htm`: Table "Annual and Peak Values - Other" shows, e.g., "ExteriorEquipment:DistrictHeatingSteam=31.54".

`eplusout.sql`: Table "TabularDataWithStrings", shows:
![image](https://github.com/NREL/EnergyPlus/assets/8516790/bbfba018-1c62-491b-bdce-b15c9ca3d68e)

I'd expect "RowName=Exterior Equipment" to be non-zero. (District Heating Water appears to correctly have 31.54.)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/10000s/10190/mcve.idf
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I can reproduce with a minimal file.

```

  Exterior:FuelEquipment,
    OutsideSteamEq,          !- Name
    DistrictHeatingSteam,    !- Fuel Use Type
    AlwaysOn,                !- Schedule Name
    1000;                    !- Design Level {W}

  Exterior:FuelEquipment,
    OutsideWaterEq,          !- Name
    DistrictHeatingWater,    !- Fuel Use Type
    AlwaysOn,                !- Schedule Name
    1000;                    !- Design Level {W}
```

![image](https://github.com/NREL/EnergyPlus/assets/5479063/0266d3f3-8a28-417c-bcfd-bc8ac1458a3a)

![image](https://github.com/NREL/EnergyPlus/assets/5479063/3920785d-6b5a-426b-9d7f-920ae92ee00f)

**Comment by jmarrec** [comment]
I found the root cause, you won't believe it, it's just a typo: https://github.com/NREL/EnergyPlus/pull/9260#discussion_r1319884218
