### ISSUE TITLE
ERL Variable "Year" returns the EPW Year, cannot access Calendar Year 

### ISSUE THREAD

**Issue by mrks-g** [NREL/EnergyPlus#10210]
Issue overview
--------------
Environment runperiod year is not correct in simulation. 
It seem that the Energyplus API does not return the correct value for the set runperiod for some reason.

### Details

I am using sinergym and transferred the issue to here according to the contributor. See [here](https://github.com/ugr-sail/sinergym/issues/359) for details. 

in `synergym.envs.eplus_env` line 301 the simulation is started with:

```
self.energyplus_simulator.start(
            building_path=eplus_working_building_path,
            weather_path=eplus_working_weather_path,
            output_path=eplus_working_out_path)
```
and I can verify that the runperiod of the `eplus_working_building_path` is set correctly as: 

![image](https://github.com/NREL/EnergyPlus/assets/144018508/871b86ac-023e-4bc6-a6ef-42a9916d7dba)

BUT uppon the simulation having been started I can verify that the year was not set correctly (2008 instead of 2018) by: 

`self.energyplus_simulator.exchange.year(self.energyplus_simulator.energyplus_state)` which returned 2008.

Day and Month are set correct.

Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
@mrks-g thanks for reporting this.  I looked over your ticket on sinergym.  It's a little difficult to diagnose exactly what is going on without an actual EnergyPlus input file.  Sinergym must provide an EnergyPlus input file in the workflow, could you attach that to this issue so I can debug it?

Without a file, I can only guess really.  EnergyPlus will do some adjustments to the run period settings if there are incompatible inputs, such as a start weekday that doesn't match the year.  I don't _think_ that is what is happening here, but it's hard to tell.  Is there anything coming out in the EnergyPlus error file that would help diagnose this?

**Comment by mrks-g** [comment]
@Myoldmopar thanks for the reply. 

here is the epJSON, that should help. 

[HVACTemplate-5ZoneVAVWaterCooled.zip](https://github.com/NREL/EnergyPlus/files/12561105/HVACTemplate-5ZoneVAVWaterCooled.zip)

**Comment by jmarrec** [comment]
I knew I had run into this before, I left a note on https://github.com/jmarrec/OpenStudio_to_EnergyPlusAPI/blob/main/OpenStudio_to_EnergyPlusAPI.ipynb

> Year is bogus, seems to be reading the weather file year instead..

https://github.com/NREL/EnergyPlus/blob/2ad5b542c761abde2179225b08ce7af0b94a5d3b/src/EnergyPlus/RuntimeLanguageProcessor.cc#L182

https://github.com/NREL/EnergyPlus/blob/2ad5b542c761abde2179225b08ce7af0b94a5d3b/src/EnergyPlus/WeatherManager.cc#L2102

This is indeed read directly from the EPW (`WYear` parameter of `WeaterManager::InterpretWeatherDataLine`)

**Comment by jmarrec** [comment]
Should we change this to `state.dataGlobal->CalendarYear` ? I don't think it's useful to report the EPW year... but if it is, we could add another variable for it

**Comment by mrks-g** [comment]
I think it is more important that the simulation uses the correct runperiod of the EP input file, including the year component.

**Comment by jasondegraw** [comment]
I wouldn't characterize the current behavior as a bug or bogus. It is working as intended. The `CalendarYear` variable was added to track the year of the simulation, but the `Year` name was already taken and accessible via EMS, so the decision was made to leave EMS as-is to avoid breaking anything for anyone that was using `Year` and expecting the year from the weather file.

It makes sense to make `CalendarYear` available via the API, but it doesn't follow that we should change `Year` to be the calendar year. It's been this way a long time, and it's a breaking change that's going to be easy to miss. My preference would be to add an additional `calendar_year` (or whatever) accessor.

**Comment by mrks-g** [comment]
Makes sense. Still I do not get how the simulation ends up in year 2008 using the attached weather file. There is no 2008 definition anywhere. 
[AUT_WI_Wien-Innere.Stadt.110340_TMYx.2007-2021_day_const_temp_Random_1.0_0.0_0.001.zip](https://github.com/NREL/EnergyPlus/files/12582684/AUT_WI_Wien-Innere.Stadt.110340_TMYx.2007-2021_day_const_temp_Random_1.0_0.0_0.001.zip)

**Comment by jmarrec** [comment]
You haven't looked far enough. Starts at 2021 a lot, then you get some 2015, 2012, and 2008
![Screenshot_20230912_075941_Chrome.jpg](https://github.com/NREL/EnergyPlus/assets/5479063/d7bf183f-1ab6-4eaa-b279-f6925e249c72)

**Comment by mrks-g** [comment]
okay, got it. I thought this is taken by comment 1 in the header of the epw file. Now I recognized that the epw file has only in 2008  entries for the october which was my runperiod.
