### ISSUE TITLE
Daylighting:Controls Issue IDD

### ISSUE THREAD

**Issue by Dani-FREE** [NREL/EnergyPlus#10266]
Issue overview
--------------
In IDD file, Field N24 in Daylighting:Controls requires fix of Field Name from "Fraction of **Zone** Controlled by Reference Point 9" to "Fraction of **Lights** Controlled by Reference Point 9". This will make modifications on relevant packages like EPPY more straightforward. The rest of the fraction fields have the same structure, except Point 9.

**Comment by jmarrec** [comment]
Point 6 has the same issue. I'm just going to quick fix this, because if it takes less than a minute we should just do it.
