### ISSUE TITLE
Green facade python plugin

### ISSUE THREAD

**Issue by piotre13** [NREL/EnergyPlus#10263]
Dear all,
I'm implementing a python plugin for the estimation of the heat balance of green facades. This plugin is inspired by the actual eco-roof component but for vertical surfaces. I have a doubt about which could be the exact moment to call the function I'm implementing. The model I'm writing simply calculates the net solar radiation, the net longwave radiation, and the heat balance of the vegetation canopy. I'm trying to understand at which simulation point among the possible ones I should call my calculation and to which parameter I should add them, any suggestions?
Thanks a lot

**Comment by jmarrec** [comment]
Question would be best asked on unmethours.com. Thank you.
