### ISSUE TITLE
Reduce minimum outdoor dry-bulb temperature for compressor operation

### ISSUE THREAD

**Issue by paul-caicedo** [NREL/EnergyPlus#10264]
Issue overview
--------------
Some cold climate heat pumps can operate below -20°C. For example, this [unit](https://backend.daikincomfort.com/docs/default-source/product-documents/residential/submittal/fdmq12rvju-rxl12qmvju9a-submittal-v7.pdf) from Daikin works in heating mode from -25°C to 18.3°C.

It would be helpful to extend the range of the outdoor dry-bulb temperature for compressor operation to cover these units.

### Details
 - Any OS
 - EnergyPlus V23.1

**Comment by rraustad** [comment]
I don't see a minimum outdoor dry-bulb temperature for compressor operation that limits operation to -20C, just a suggested default. Could you be more specific? Maybe provide an example file that shows the problem.

**Comment by paul-caicedo** [comment]
Minimum outdoor dry-bulb [temperature](https://bigladdersoftware.com/epx/docs/23-1/input-output-reference/group-hvac-templates.html#field-heat-pump-heating-minimum-outdoor-dry-bulb-temperature-1) for compressor operation 
"The minimum value **must be** greater than or equal to -20 °C"

**Comment by rraustad** [comment]
I see. That's in the documentation for HVAC Template heat pump objects. Have you tried an input lower than -20 C and you get an  error? If so, please upload the input file here. I don't see a limit in code, except if that field is left blank, in that case the min limit is -25 C. So if something is not working as intended then please provide a test file so we can track this down.
