### ISSUE TITLE
Zone temperature drops below setpoint even if autosized supplemental coil present

### ISSUE THREAD

**Issue by yujiex** [NREL/EnergyPlus#10273]
Issue overview
--------------
In the example file "US+SF+CZ4A+hp+crawlspace+IECC_2006_VRF.idf", when the VRF system capacity is 3000W (AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl field Rated Evaporative Capacity {W}), and the heating coil rated heating capacity is 10023W. A supplemental coil is present and autosized. The zone temperature drops below setpoint when the outdoor is above 0C. As a result, the predicted heating load (output "predicted sensible load to heating setpoint heat transfer rate") is also very large when outdoor temperature is above 0C.

<img width="585" alt="image" src="https://github.com/NREL/EnergyPlus/assets/13421161/8bb7e395-0fb8-470e-896b-3e469c28031c">

Attempted fixing it by removing the following hardcoded limitation on the fan speed ratio.

```
     FanSpdRatioMin = min(max(OAMassFlow / Garate, 0.65), 1.0); // ensure that coil flow rate is higher than OA flow rate
```

This resolved the zone temperature problem, which also resolved the predicted heating load issue. But the fan air mass flow still do not behave as expected

<img width="1189" alt="image" src="https://github.com/NREL/EnergyPlus/assets/13421161/44c9b162-30da-45e3-b0a5-39beb16eb508">

It seems the problem is an instance of the issue #10282, where the supplemental coil is turned off at 0C.

<img width="633" alt="image" src="https://github.com/NREL/EnergyPlus/assets/13421161/ec88803c-4d66-4a49-88a2-80ba5a2feac5">

After adding this field explicitly in the idf.

```
 ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
    TU1,                     !- Zone Terminal Unit Name
    …    
    Coil:Heating:Electric,   !- Supplemental Heating Coil Object Type
    TU1 Supp Heating Coil,   !- Supplemental Heating Coil Name
    50,                      !- Maximum Supply Air Temperature from Supplemental Heater {C}
    ;                          !- Maximum Outdoor Dry-Bulb Temperature for Supplemental Heater Operation  <-- add this
```
The problem of zone temperature, predicted heating load, and air mass flow is resolved

<img width="1212" alt="image" src="https://github.com/NREL/EnergyPlus/assets/13421161/12c5213d-8bb1-4e0a-8c0f-69fdfca5ecd5">

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac 13.5)
 - Version of EnergyPlus (23.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
This usually means the zone temperature cannot be controlled to the temperature set point. I assume the zone temperature fell below the set point. Can you plot the zone temperature? If fan speed is causing this issue then it would be nice to see the air flow rate as well.

**Comment by yujiex** [comment]
Thanks @rraustad . The zone temperature is like this. I'll rerun and output the air flow rate

Before the fix, zone temperature can get to below 15C

![image](https://github.com/NREL/EnergyPlus/assets/13421161/0007e0dc-15e6-4686-866c-6c58fe544395)

After the fix, zone temperature is around 22.22 for the whole period
![image](https://github.com/NREL/EnergyPlus/assets/13421161/e24949e1-5387-4f4e-9ca7-63a57728f283)

**Comment by yujiex** [comment]
@rraustad TU supply air mass flow is like this

![image](https://github.com/NREL/EnergyPlus/assets/13421161/9fabce44-a172-459a-8f01-c255be70c668)

**Comment by yujiex** [comment]
Hi @rongpengzhang. Do you recall what the 0.65 in the following line of code is for? It's near the beginning of the function `ControlVRFIUCoil`. I have not been able to locate the documentation or description for it. 

```
FanSpdRatioMin = min(max(OAMassFlow / Garate, 0.65), 1.0); // ensure that coil flow rate is higher than OA flow rate
```

There seem to be some interactions between this line of code and some modifications I did earlier that limits terminal unit capacity to not exceed condenser capacity. It would be nice if you could help me understand what this line of code is doing. Thanks.
