### ISSUE TITLE
Simple EMS actuator : is it a bug?

### ISSUE THREAD

**Issue by qqq000feel** [NREL/EnergyPlus#10279]
[slowheattest_2files.zip](https://github.com/NREL/EnergyPlus/files/13170517/slowheattest_2files.zip)

Issue overview
--------------
I am studying simple EMS script. 
(please take a look attached IDF file)

I have a problem with the 'program5' of EMS:Program class.

As you can see, I made very simple 'schedule value' actuator, named 'actuHeatsp'. It controls the Schedule:Constant object named 'heatsp'.

At the end of the 'program5' script, I set the actuator's value to 'newtemp' variable(global).

When I run the IDF file, there were no severe errors or EMS errors, but the actuator 'actuHeatsp' doesn't control the 'heatsp' schedule. 
This simple line didn't work at all with my original EMS script : [ SET actuHeatsp = newtemp ]

However, I changed the line like this, the actuator started to work.
[ SET actuHeatsp = (newtemp+1)-1 ]

As you can see, the value is same with original script line. (+1-1 = 0)

Is this just a bug? or did I miss something?

### Details
Some additional details for this issue (if relevant):
 - Platform : Windows11
 - Version of EnergyPlus : V23.1
 - Helpdesk ticket number : #16509

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jcyuan2020** [comment]
This was confirmed to be still the case in v23.2 (Helpdesk ticket 16509). One additional note is that it does not need to be `newtemp+1)-1` to make the difference---simply adding a bracket like `SET actuHeatsp = (newtemp)` would make the difference as well. So it looks that any kind of operation on the right side would have the effect.

**Comment by qqq000feel** [comment]
> This was confirmed to be still the case in v23.2 (Helpdesk ticket 16509). One additional note is that it does not need to be `newtemp+1)-1` to make the difference---simply adding a bracket like `SET actuHeatsp = (newtemp)` would make the difference as well. So it looks that any kind of operation on the right side would have the effect.

Thanks. Your simple solution is nice.
