### ISSUE TITLE
WindowMaterial:Shade eio output write-out CSV format typo

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#10286]
Issue overview
--------------
It was reported by a user that in the EIO report there is a column shift occurred between the header and the actual information:
![image](https://github.com/NREL/EnergyPlus/assets/64040111/d0ed0e26-1449-4e8b-b656-07c3152a6a5d)

After examining the source code, this was found to be caused by a formatting typo in the source code:
https://github.com/NREL/EnergyPlus/blob/d07d7ad64207285b241ab79b67b66ed98e2db594/src/EnergyPlus/WindowManager.cc#L7405-L7409

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): at least since v9.4, till v23.2
 - Helpdesk Ticket Number: 16512

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/10000s/10286/10286_in.idf))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
@jcyuan2020 Looks like this issue should be closed?

**Comment by jcyuan2020** [comment]
> @jcyuan2020 Looks like this issue should be closed?

Actually, I quickly checked and it seems the problematic code typo is still there. I will just post a one-liner fix for this.

**Comment by shorowit** [comment]
> Actually, I quickly checked and it seems the problematic code typo is still there. I will just post a one-liner fix for this.

Oh, sorry. I saw the commit referenced above and assumed it was merged in. Thanks for double-checking.
