### ISSUE TITLE
Using EMS actuator on a material

### ISSUE THREAD

**Issue by piotre13** [NREL/EnergyPlus#10293]
Dear all,
I'm developing a python plugin for green facades that performs some heat balance calculations and needs to impose the calculated values inside energyplus. I've seen that I cannot use as actuator variables like "Surface Outside Face Solar Radiation Heat Gain Rate Per Area". Therefore i want to change the solar absorptance of the material composing the outside layer of a surface. At this point, my question is: how can I change the absorptance value of a material making sure that it is changed only for the specific surface I'm taking into consideration?
Thanks

**Comment by mjwitte** [comment]
Option 1 - Make a unique material name for each surface and control Surface Property Solar Absorptance
Option 2 - Make a set of Construction objects that have different outside material layers for each of the desired solar absorptance values and use the Surface Construction State EMS actuator (this has several steps to use it, so refer to the EMS guide).

For future support requests, please see [EnergyPlus User Support options.](https://energyplus.net/support-training)
