### ISSUE TITLE
libgcc_s.1.1.dylib dependency is back on mac x86_64

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#10306]
Issue overview
--------------

This library wasn't needed on 23.1.0 (and 22.2.0), as this was addressed - and tested! - as part of 
* https://github.com/NREL/EnergyPlus/pull/9676
* https://github.com/NREL/EnergyPlus/pull/9682

Seems like it's back on 23.2.0 on the x86 installer. My guess is that the Github Actions runners got a new version of something, because it's still fine on my M1 mac (where, mind you, it's actually needed too)

Found this on:
* https://github.com/NREL/OpenStudio/issues/5050

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Intel Mac x86_64
 - Version of EnergyPlus (if using an intermediate build, include SHA): 23.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Related? https://github.com/actions/runner-images/issues/6866

**Comment by kbenne** [comment]
I feel like we still need to patch OpenStudio to include the library in the short term, then address this at the EnergyPlus level for the next EnergyPlus release. What do you think @jmarrec ?

**Comment by jmarrec** [comment]
Fixed via #10412
