### ISSUE TITLE
Hot water loop with SwimmingPool:Indoor does not turn on when the heating capacity of the heat source is insufficient

### ISSUE THREAD

**Issue by keigo-nomura** [NREL/EnergyPlus#10317]
A bug related to SwimmingPool:Indoor. When the heating capacity of the heat source (e.g., boiler) is insufficient, it can happen that the hot water loop (boiler and pump) does not turn on even if the pool water temperature is below the setpoint. Please refer to my Answer in the Unmethours link below for more details.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus: V23-2-0
 - Unmethours link: [Indoor Swimming Pool temperature](https://unmethours.com/question/97426/indoor-swimming-pool-temperature/) (Please refer to my Answer.)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([5ZoneSwimmingPool_rev.idf](https://drive.google.com/drive/folders/1Dim8U27m8EyoeYcsT9cVuItWsSrwrIPT?usp=sharing)) (V23-2-0)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@keigo-nomura Thanks for posting this bug.  I believe that I have identified the source of this bug and have a potential solution that will fix the problem.
