### ISSUE TITLE
Python Plugin - interpreter and external libraries

### ISSUE THREAD

**Issue by piotre13** [NREL/EnergyPlus#10316]
Dear all,
I'm using the python plugin feature of Eplus, I was wondering what happens when i want to test and input file that requires a python plugin using the classic EPlaunch? which will be the python interpreter, and the search paths? how can i specify these information for the run?

**Comment by jmarrec** [comment]
I'm not sure I follow the question? The Python Plugin is standadalone, regardless of whether you are launching the simulation from the EnergyPlus (.exe) CLI directly or from EPLaunch.  Inside the IDF, the PythonPlugin:Instance defines the python module name, and the [PythonPlugin:SearchPaths](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-python-plugins.html#subsec:plugin-search-paths) is here to tweak the search paths.
The python interpreter is ALWAYS the one that E+ packages.

Perhaps you are using the EnergyPlus Python API? Meaning you use your system python to call E+?

**Comment by piotre13** [comment]
Thanks for the answer, i have three cases right now:
1- launching energyplus through API and yes it uses my system  or env python
2- launching eplus from a PC where no system python was installed before installing eplus and yes it uses the embedded eplus python interpreter
3- on my personal PC even launching from eplus directly it does not use an embedded python interpreter (in the eplus folded is not present) but directly links to my system python

Thus, one of my question now is : the embedded python interpreter is always installed? or it is installed only if no global python interpreter is found? in second place the embedded python interpreter does come with a package manager engine (e.g. pip)? how can i deal with external python libraries (e.g. installing them) that are not present in the python_standard_lib folder?

**Comment by jmarrec** [comment]
1. the embedded python interpreter is always installed? 
    * yes
2. in second place the embedded python interpreter does come with a package manager engine (e.g. pip)? how can i deal with external python libraries (e.g. installing them) that are not present in the python_standard_lib folder?
    * We do not bundle pip.
    * Ensure you have the same python version installed on your system (3.8.x currently), and install the missing packages
        * Option 1: install them outside E+ and modify your plugin file to append `sys.path` to find the packages (eg: `import sys; sys.path.append('/home/julien/.pyenv/versions/3.8.13/lib/python3.8/site-packages')`)
        * Option 2: install them inside the python_standard_lib directly, via `python -m pip install --target=/path/to/EnergyPlus/python_standard_lib`

**Comment by Myoldmopar** [comment]
I would reiterate that the most flexible way to proceed with EnergyPlus and Python is to call using the API from your own Python environment.  With 24.1 coming out, we have completed fleshing out all the callbacks so that they match the same calling points as the plugin system (user defined components were missing, but are done now).  Calling with this way, you can set up a Python virtual environment super easily and pip install whatever you like, and call EnergyPlus from outside.  Thanks for your interest!
