### ISSUE TITLE
The Following Output has been Changed/Removed and Docs Were Not Updated: "Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate"

### ISSUE THREAD

**Issue by chriswmackey** [NREL/EnergyPlus#10315]
Issue overview
--------------
I have spent the last several hours trying to construct the heat transfer balance of solar/conduction through windows of my E+ simulation. At the very least, I can say that the E+ docs are incorrect/out-of-date with regards of how to do this. In a worst-case scenario, it might be currently impossible to understand the E+ heat transfer balance calculation through windows using the currently available outputs.

### Details
[This section of the EnergyPlus Docs](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-thermal-zone-description-geometry.html#surface-window-net-heat-transfer-rate-j) is pretty clear that the full heat transfer through windows involves a few terms including "Short-wave radiation from zone transmitted back out the window". Looking later through that part of the docs, you will find the following output described, which is supposed to tell you this portion of solar energy reflected back out the windows:

[Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate [W]](https://bigladdersoftware.com/epx/docs/23-2/input-output-reference/group-thermal-zone-description-geometry.html#surface-window-shortwave-from-zone-back-out-window-heat-transfer-rate-w)

However, no matter what settings I use with different specifications of Fenestration Surfaces, I cannot get this output to appear in the RDD of my simulation. Moreover, none of the E+ outputs that I see in the RDD look like they will tell me this back-reflected portion of solar, though I have been able to deduce that it's probably around ~6% of the transmitted solar.

I see that this "Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate" output must have been around 5 years ago when @mjwitte referenced it in this unmethours post:
https://unmethours.com/question/33458/heat-balance-of-a-thermal-zone/

So I assume that the output was either renamed or removed. If it was just renamed, it would be great to have the E+ docs updated with the new name. If it was removed, it would be really nice to have some recommendation for getting this back-reflected solar since I'm not really able to get an understanding of the full heat transfer balance without it.

Thank you, as always.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
This output is still in the code by the same name, but it (and many other outputs) is not created unless this input is present: `Output:Diagnostics, DisplayAdvancedReportVariables;`

**Comment by chriswmackey** [comment]
Thank you, @mjwitte . Sorry to have opened an issue about this and you are correct that using `DisplayAdvancedReportVariables` has enabled me to see this output. I'm still struggling to figure out where a few hundred kWh of solar is going in each month of my simulation but I will open an issue on unmethours for this since it is the more appropriate platform.

**Comment by chriswmackey** [comment]
FYI @mjwitte , I posted the main question that I am trying to answer with this output here on Unmethours:
https://unmethours.com/question/97631/help-with-constructing-the-simplest-load-balance-with-energyplus/

If you find the time, I would really appreciate your insight since I know you have helped on a lot of other questions related to the EnergyPlus load balance calculation.

Thanks, as always, for all of your help and support.

**Comment by mjwitte** [comment]
@chriswmackey No problem. It's an obscure feature designed to minimize the rdd and some internal processing for rarely used outputs, and to occasionally challenge users.
