### ISSUE TITLE
EMS cannot override Headered Pumps Head correctly

### ISSUE THREAD

**Issue by keigo-nomura** [NREL/EnergyPlus#10318]
When we try to override Pump Pressure Rise of HeaderedPumps:VariableSpeed or HeaderedPumps:ConstantSpeed with any value by EMS, Pump Electricity Rate becomes almost 0 W, probably because Pump Pressure Rise becoms almost 0 Pa.
Please refer to the Unmethours link below for more details.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus: V23-2-0
 - Unmethours link: [EMS cannot override Headered Pumps Head correctly](https://unmethours.com/question/97640/ems-cannot-override-headered-pumps-head-correctly/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (Please refer to the unmethours link above.)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lgu1234** [comment]
@keigo-nomura I am unable to download the test file in the Unmethours link. Please upload the test file in the Github. Thanks.
