### ISSUE TITLE
Get the outputs related to E+ objects

### ISSUE THREAD

**Issue by s-martiz** [NREL/EnergyPlus#10354]
Dear EnergyPlus community,

I am a recent user of EnergyPlus. I have a fairly simple question: How can I obtain the list of outputs related to a specific object in EnergyPlus? Currently, I am using ChatGPT to achieve my goals.
Here is an example query: "What are the EnergyPlus outputs related to the object: WindowShadingControl?"
For information, I primarily use EnergyPlus with Python via the eppy package.

Best regards,
Simon

**Comment by bbrangeo** [comment]
You can look here https://energyplus.net/assets/nrel_custom/pdfs/pdfs_v22.1.0/TipsAndTricksUsingEnergyPlus.pdf, page 57. You need to add the following line to the OUTPUT class: Output:VariableDictionary,IDF; all possible outputs will then be available in the generated .rdd file when the simulation is launched.

<img width="780" alt="output" src="https://github.com/NREL/EnergyPlus/assets/769760/ad8497ca-a02e-4844-92bc-4a114d7ad017">
