### ISSUE TITLE
Regarding moisture addition to a zone from people (moisture/person/per day value) 

### ISSUE THREAD

**Issue by sajithnrel** [NREL/EnergyPlus#10392]
I need to verify the moisture addition form people to the occupied zone when only the people object is activated 
--------------
I am modelling a zone within the standard prototype building provided by PNNL. Its essentially a chamber within the main building. At the moment I have shut down the rest of the loads and turning on the moisture gain from people only. 

The IDF attached here has everything setup. On the variable outputs I am specifically looking at the: 
"CHAMBER:Zone Mean Air Humidity Ratio [kgWater/kgDryAir](Hourly)"
Chamber volume is: 24.15 m3
Therefore air mass is: 29.77 kg
Through this I calculate the moisture addition at the end. 

The concern is the moisture/person/per day seems high as 2.4 kg when the average temperature is around 30 C. 
The objective of this request is to find how EnergyPlus calculates the moisture addition exactly. 
(IDF file, schedule file, weather file is in the zipped folder) 
[IECC_standard_room_people_humidity.zip](https://github.com/NREL/EnergyPlus/files/14168804/IECC_standard_room_people_humidity.zip)

### Details
Some additional details for this issue (if relevant):
 - Windows 
 - Version of EnergyPlus 22.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Here's the source code:
https://github.com/NREL/EnergyPlus/blob/1c077127679cd0d4cec0be80aeae8b739a1873c4/src/EnergyPlus/InternalHeatGains.cc#L7360-L7395

Also see the Engineering Reference "Heat Gain from People".

**Comment by sajithnrel** [comment]
Hi all, I wanted to specifically know the source equations used to calculate the moisture inputs when the number of people, activity level, and sensible heat gain fraction is defines. In other words, where there equations come from (report/paper/ASHRAE standard)

**Comment by mjwitte** [comment]
From the comments in the same function.
https://github.com/NREL/EnergyPlus/blob/1c077127679cd0d4cec0be80aeae8b739a1873c4/src/EnergyPlus/InternalHeatGains.cc#L7335-L7346

And the reference in the Engineering Reference:
Average adjusted metabolic rate (Carrier 1965b) is . . .
Carrier Air Conditioning Company. 1965b. Handbook of Air Conditioning System Design, pp
1-100, Table # 48. New York: McGraw Hill.

**Comment by Myoldmopar** [comment]
@sajithnrel, looks like your IDF is set up OK, where the chamber zone has no extra moisture sources.  In your people object, you are using a sensible fraction of 0.5.  Did you get that from an example file or is that an intentional value?

**Comment by sajithnrel** [comment]
> @sajithnrel, looks like your IDF is set up OK, where the chamber zone has no extra moisture sources. In your people object, you are using a sensible fraction of 0.5. Did you get that from an example file or is that an intentional value?

It is an intentional value to define a constant. I wanted to test the moisture/person/day that constantly adds for few days. So I set the sensible fraction to a constant.

**Comment by sajithnrel** [comment]
> From the comments in the same function.
> 
> https://github.com/NREL/EnergyPlus/blob/1c077127679cd0d4cec0be80aeae8b739a1873c4/src/EnergyPlus/InternalHeatGains.cc#L7335-L7346
> 
> And the reference in the Engineering Reference: Average adjusted metabolic rate (Carrier 1965b) is . . . Carrier Air Conditioning Company. 1965b. Handbook of Air Conditioning System Design, pp 1-100, Table # 48. New York: McGraw Hill.

I am specifically looking at the line 5480 of ZoneTempPredictorCorrector.cc 
Real64 LatentGainPeople = (((11.0 / 6.0) * CC + AA) * zone.ZoneMeasuredHumidityRatio - BB - CC * DD) * H2OHtOfVap;

I wanted to know the source of this equation.

**Comment by Myoldmopar** [comment]
Based on the inputs you've given in your input file, ~2 kg of moisture added per person per day makes sense:

- Input of sensible heat fraction = 0.5
- Input of activity level, or people total heat gain = 108 W/person
- Thus the latent rate portion is = 108 W/person * 0.5 = 54 W/person
- For a whole day, the latent gain is: 54 W/person * 24 h/day * 3600 s/h = 4665600 J/day/person = 4.6656 MJ/day/person
- Looking up a rough `h_fg` at standard conditions = 2.44 MJ/kg
- Dividing these converts the latent heat gain to moisture rate, so
  - Moisture added per day per person = 4.6656 MJ/day/person ÷ 2.44 MJ/kg = ~~2 kg/day/person

I could be missing something still, so let me know if you see something wrong with that.

**Comment by mjwitte** [comment]
> I am specifically looking at the line 5480 of ZoneTempPredictorCorrector.cc
Real64 LatentGainPeople = (((11.0 / 6.0) * CC + AA) * zone.ZoneMeasuredHumidityRatio - BB - CC * DD) * H2OHtOfVap;
I wanted to know the source of this equation.

That's part of the hybrid zone model that tries to match the simulation conditions with measured data. See HybridModel:Zone. So that's not relevant to a standard simulation.

**Comment by sajithnrel** [comment]
> > I am specifically looking at the line 5480 of ZoneTempPredictorCorrector.cc
> > Real64 LatentGainPeople = (((11.0 / 6.0) * CC + AA) * zone.ZoneMeasuredHumidityRatio - BB - CC * DD) * H2OHtOfVap;
> > I wanted to know the source of this equation.
> 
> That's part of the hybrid zone model that tries to match the simulation conditions with measured data. See HybridModel:Zone. So that's not relevant to a standard simulation.

Thank you for your guidance on this while this section discusses the sensible gain, it doesn't indicate how latent gain leads to calculation of moisture input and how it sets up the moisture ratio. Are there any further indication on that?

**Comment by sajithnrel** [comment]
> Based on the inputs you've given in your input file, ~2 kg of moisture added per person per day makes sense:
> 
> * Input of sensible heat fraction = 0.5
> * Input of activity level, or people total heat gain = 108 W/person
> * Thus the latent rate portion is = 108 W/person * 0.5 = 54 W/person
> * For a whole day, the latent gain is: 54 W/person * 24 h/day * 3600 s/h = 4665600 J/day/person = 4.6656 MJ/day/person
> * Looking up a rough `h_fg` at standard conditions = 2.44 MJ/kg
> * Dividing these converts the latent heat gain to moisture rate, so
>   
>   * Moisture added per day per person = 4.6656 MJ/day/person ÷ 2.44 MJ/kg = ~~2 kg/day/person
> 
> I could be missing something still, so let me know if you see something wrong with that.

Thank you! I addition, Is there any source material (publication) on this calculation which shows how EnergyPlus uses it?

**Comment by Myoldmopar** [comment]
The amount of moisture from people, equipment, ventilation, and infiltration are all combined to calculate a new moisture level in the space.  This humidity is used as the input for the HVAC treating the space, such that DX coils will dehumidify the air, etc.  There's nothing specific to how E+ treats the people humidity, and there's no model for it as a function of a person or anything like that.  It's simply based on user inputs just like equipment moisture gain.  If you think the people moisture gain is too high, simply adjust the total activity rate or sensible heat fraction on the people input objects, and it will result in less humidity in the space.

**Comment by sajithnrel** [comment]
> The amount of moisture from people, equipment, ventilation, and infiltration are all combined to calculate a new moisture level in the space. This humidity is used as the input for the HVAC treating the space, such that DX coils will dehumidify the air, etc. There's nothing specific to how E+ treats the people humidity, and there's no model for it as a function of a person or anything like that. It's simply based on user inputs just like equipment moisture gain. If you think the people moisture gain is too high, simply adjust the total activity rate or sensible heat fraction on the people input objects, and it will result in less humidity in the space.

Thank you very much for this clarification. It is fully resolved.
