### ISSUE TITLE
Addition of CO2 to a zone from people: EnergyPlus analytical method 

### ISSUE THREAD

**Issue by sajithnrel** [NREL/EnergyPlus#10398]
I needed to pin point the CO2 addition for people. Is this based on an analytical equation in EnergyPlus? 
I will appreciate guidance on this. 
--------------
Please change this line to a description of the defect, with useful supporting information including how the issue was found, conditions that trigger this defect, workarounds for users of the current version, and a clear description of how to validate that a fix is complete for this defect.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
It's a user input. From the I/O Reference:

1.14.2.1.11 Field: Carbon Dioxide Generation Rate
This numeric input field specifies carbon dioxide generation rate per person with units of m3/s-W. The
total carbon dioxide generation rate from this object is:
Number of People * People Schedule * People Activity * Carbon Dioxide Generation Rate. The default
value is 3.82E-8 m3/s-W (obtained from ASHRAE Standard 62.1-2007 value at 0.0084 cfm/met/person
over the general adult population). The maximum value can be 10 times the default value.

**Comment by sajithnrel** [comment]
I have a short extended question related to the CO2 balance equation used in a zone. What is the method used in EnergyPlus? 

Is it as same as indicated in the link below: 
https://www.engineeringtoolbox.com/pollution-concentration-rooms-d_692.html 

I appreciate your guidance
