### ISSUE TITLE
Long elapsed times are not recorded correctly

### ISSUE THREAD

**Issue by keigo-nomura** [NREL/EnergyPlus#10399]
Issue overview
--------------
EnergyPlus shows the Elapsed Time at the end of the err file after the simulation. However, the display upper limit appears to be 24 hours. For example, if the actual elapsed time is 50 hr 00 min 00.00 sec, the elapsed time is displayed as 02 hr 00min 00.00sec (i.e., 50hr - 24hr - 24hr = 2hr) in the err file.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus: in any version
 - Unmethours link or helpdesk ticket number: [Long elapsed times are not recorded correctly](https://unmethours.com/question/97115/long-elapsed-times-are-not-recorded-correctly/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Interesting, I guess no one expected sim times to exceed 24 hours.

Anyways, this line is guilty: https://github.com/NREL/EnergyPlus/blob/1edbc139a626db0739f4b27ab3c023a1e697862f/src/EnergyPlus/UtilityRoutines.cc#L591

Along with this routine which discards the day completely: 

https://github.com/NREL/EnergyPlus/blob/1edbc139a626db0739f4b27ab3c023a1e697862f/src/EnergyPlus/UtilityRoutines.cc#L455-L486
