### ISSUE TITLE
V23-1-0-Energy+.idd missing from 24.1 Windows installer

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#10401]
Issue overview
--------------
I just ran IDFVersionUpdater from the 24.1 test release  

EnergyPlus-24.1.0-62e0cab924-Windows-x86_64.exe

and got the messages:

![rRtZG9UMs9OcZdyP](https://github.com/NREL/EnergyPlus/assets/2582150/e9fa9dc4-04e7-4053-88c8-8c51e0618b0e)

Sure enough the file:

V23-1-0-Energy+.idd

was missing from the install. Probably should check if it missing from other platforms installers also.

### Details
Some additional details for this issue (if relevant):
 - Windows 10 (Operating system, version)
 - 24.1 62e0cab924(if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Fixed by @Myoldmopar via https://github.com/NREL/EnergyPlus/commit/152522da2b0b5cca4f106349d1ccd30cbcd5ec16
