### ISSUE TITLE
e+ crashed while running with version 23.1.0

### ISSUE THREAD

**Issue by 7everglow7** [NREL/EnergyPlus#10421]
Issue overview
--------------
Please change this line to a description of the defect, with useful supporting information including how the issue was found, conditions that trigger this defect, workarounds for users of the current version, and a clear description of how to validate that a fix is complete for this defect.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)
![image](https://github.com/NREL/EnergyPlus/assets/100946596/36de45d5-cbab-4fdc-a9d6-546f27d0fee3)

**Comment by Myoldmopar** [comment]
@7everglow7 could you provide your input file, and any associated external/weather files?  Also, could you try updating your input file to version 23.2 and seeing if the issue has already been fixed before we do much investigation?  Thanks!

**Comment by 7everglow7** [comment]
> @7everglow7 could you provide your input file, and any associated external/weather files? Also, could you try updating your input file to version 23.2 and seeing if the issue has already been fixed before we do much investigation? Thanks!

these are my testfiles, could you please try to analyze them at this version?
[testfile.zip](https://github.com/NREL/EnergyPlus/files/14489183/testfile.zip)

**Comment by jmarrec** [comment]
@7everglow7 I used 23.1.0 on Ubuntu to run your file and I do not get a crash. Instead I get a **lot** of geometry errors.

The last fatal is `CheckConvexity: Surface="SURFACE-82-H-4" is non-planar`, but this is only one of MANY non planar surfaces.

How I ran your file:

```shell
/usr/local/EnergyPlus-23-1-0/energyplus -w CHN_Shanghai.Shanghai.583620_CSWD.epw -d out-ori qingchang-using-bb.idf
```

Here is the eplusout.err: [eplusout.err.txt](https://github.com/NREL/EnergyPlus/files/14494369/eplusout.err.txt)


Fix your geometry issues, then if you still get a crash we can reopen this issue.

**Comment by 7everglow7** [comment]
> @7everglow7 I used 23.1.0 on Ubuntu to run your file and I do not get a crash. Instead I get a **lot** of geometry errors.
> 
> The last fatal is `CheckConvexity: Surface="SURFACE-82-H-4" is non-planar`, but this is only one of MANY non planar surfaces.
> 
> How I ran your file:
> 
> ```shell
> /usr/local/EnergyPlus-23-1-0/energyplus -w CHN_Shanghai.Shanghai.583620_CSWD.epw -d out-ori qingchang-using-bb.idf
> ```
> 
> Here is the eplusout.err: [eplusout.err.txt](https://github.com/NREL/EnergyPlus/files/14494369/eplusout.err.txt)
> 
> Fix your geometry issues, then if you still get a crash we can reopen this issue.
I tried to fix the geometry, but this time it stopped running with an unfinished err file. Is this because of warning logs? These are my new files generated by eppy in python.
[test_vented-modified.zip](https://github.com/NREL/EnergyPlus/files/14506908/test_vented-modified.zip)

**Comment by 7everglow7** [comment]
> @7everglow7 I used 23.1.0 on Ubuntu to run your file and I do not get a crash. Instead I get a **lot** of geometry errors.
> 
> The last fatal is `CheckConvexity: Surface="SURFACE-82-H-4" is non-planar`, but this is only one of MANY non planar surfaces.
> 
> How I ran your file:
> 
> ```shell
> /usr/local/EnergyPlus-23-1-0/energyplus -w CHN_Shanghai.Shanghai.583620_CSWD.epw -d out-ori qingchang-using-bb.idf
> ```
> 
> Here is the eplusout.err: [eplusout.err.txt](https://github.com/NREL/EnergyPlus/files/14494369/eplusout.err.txt)
> 
> Fix your geometry issues, then if you still get a crash we can reopen this issue.
I tried to fix the geometry, but this time it stopped running with an unfinished err file. Is this because of  warning logs? These are my new files generated by eppy in python.
[test_vented-modified.zip](https://github.com/NREL/EnergyPlus/files/14506908/test_vented-modified.zip)
