### ISSUE TITLE
Fatal error in heating and cooling loads during sizing run

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/EnergyPlus#10464]
Issue overview
--------------
This error is coming up on some models in the openstudio-standards CI with the latest develop branch of OpenStudio and EnergyPlus 24.1.
```
[openstudio.model.Model] The run did not finish and had following errors: DualSetPointWithDeadBand: Unanticipated combination of heating and cooling loads - report to EnergyPlus Development Team  occurs in Zone=F2 N1 APARTMENT ZN During Warmup, Environment=RUN PERIOD 1, at Simulation time=01/01 00:00 - 00:10  LoadToHeatingSetPoint=-N0AN, LoadToCoolingSetPoint=-N0AN  Zone Heating Set-point=21.70  Zone Cooling Set-point=24.40  Zone TempDepZnLd=-N0AN  Zone TempIndZnLd=-N0AN  Zone ThermostatSetPoint=21.70\
Program terminates due to above conditions.
```
 The tests are passing in OS v3.7.0.

.idf and .epw file to replicate:
[error.zip](https://github.com/NREL/EnergyPlus/files/14951657/error.zip)

To narrow things down, I made a copy of the model in E+ 23.2 and then forward translated it, which runs fine.
The difference is in the new curve name fields attached to the HeatExchanger:AirToAir:SensibleAndLatent object. The default curve tables from OpenStudio seem to be causing the issue. Related OpenStudio PR: https://github.com/NREL/OpenStudio/pull/5099.

### Details
Some additional details for this issue:
 - Windows
 - OpenStudio develop (pre v3.8 release)
 - E+ 24.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by alexanderjanusz** [comment]
Hi - I also experienced this error.  I found it's due to having an HRV with 0% Sens/Lat effectiveness (ie putting in placeholder). I could circumvent/eliminate the error by removing HRV, or setting effectiveness to normal numbers (70% sens/60% Lat).

Oddly, the error is flagged/occurs in a zone adjacent to the conditioned zone, rather than directly in the zone.

VERSION
>       !IDD_Version 24.1.0
>       !IDD_BUILD 9d7789a3ac

ERROR
>          ** Severe  ** DualSetPointWithDeadBand: Unanticipated combination of heating and cooling loads - report to EnergyPlus Development Team
>          **   ~~~   ** occurs in Zone=TWRA_RESIDENTIALUNIT_1 During Warmup, Environment=SUMMER EXTREME, at Simulation time=07/22 00:00 - 00:10
>          **   ~~~   ** LoadToHeatingSetPoint=-N0AN, LoadToCoolingSetPoint=-N0AN
>          **   ~~~   ** Zone Heating Set-point=18.00
>          **   ~~~   ** Zone Cooling Set-point=24.00
>          **   ~~~   ** Zone TempDepZnLd=740.81
>          **   ~~~   ** Zone TempIndZnLd=-N0AN
>          **   ~~~   ** Zone ThermostatSetPoint=24.00
>          **  Fatal  ** Program terminates due to above conditions.
