### ISSUE TITLE
UnitarySystem does not control properly when using a water heating coil as a supplemental heating coil

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#10478]
Issue overview
--------------
A user file uses a water coil as the supplemental heating coil and the code does not call this object when there is no supplemental heating coil load. The result is nonsense.

HelpDesk ticket 16574

AirLoopHVAC:UnitarySystem,
    Zone or System Name Advanced Dehumidification System,  !- Name
    load,                    !- Control Type
    CoolReheat,              !- Dehumidification Control Type
    Fan:VariableVolume,      !- Supply Fan Object Type
    BLOWTHROUGH,             !- Fan Placement
    Coil:Heating:Electric,   !- Heating Coil Object Type
    Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit,  !- Cooling Coil Object Type
    LatentOrSensibleLoadControl,  !- Latent Load Control
    Coil:Heating:Water,      !- Supplemental Heating Coil Object Type

![image](https://github.com/NREL/EnergyPlus/assets/5778156/6cf3e9ba-3546-4ba7-8c71-19406518b1d8)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added ([HelpDesk-16574-advanced_dehumidification-24_1.idf.txt](https://github.com/NREL/EnergyPlus/files/15099547/HelpDesk-16574-advanced_dehumidification-24_1.idf.txt))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mattdoiron** [comment]
I think we're seeing the same issue. We see supplementary hydronic heating coils not being controlled at all and doing things like directly fighting the cooling coil and overheating zones. We're seeing it on both unitary systems as well as PTHP systems and it happens in v23.1, v23.2 and v24.1.
