### ISSUE TITLE
Make sure that CO2 and GenContam are handled by all components

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#10473]
Issue overview
--------------
1. While reviewing another PR, noticed that `GenContam` isn't getting passed through by variable speed coils, only `CO2` is.
https://github.com/NREL/EnergyPlus/blob/378844d64bd81314354a7f30ab5fb3a9c2afa18d/src/EnergyPlus/VariableSpeedCoils.cc#L8358-L8360

2. While working on #10348 noticed this for SpaceHVAC:ZoneEqupimentMixer.
https://github.com/NREL/EnergyPlus/blob/378844d64bd81314354a7f30ab5fb3a9c2afa18d/src/EnergyPlus/DataZoneEquipment.cc#L1839-L1850

3. Need to check the entire code base to make sure that `CO2` and `GenContam` are being calculated and/or passed through as needed.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mjwitte I don't know if you planned to grab this one or not, but I have started looking at this and trying to track down any other places where this is an issue.  If you were planning on working on this, let me know soon so that I can stand down and not invest more in this.  Thanks!

**Comment by mjwitte** [comment]
@RKStrand Go for it.
