### ISSUE TITLE
How to Convert Documents to Markdown Format While Retaining Formulas?

### ISSUE THREAD

**Issue by GudaoStudio** [NREL/EnergyPlus#10471]
Hello everyone,
I have a question while trying to localize documents and create a knowledge base (in Chinese). Currently, the publicly available documents support HTML and PDF formats, but I am looking for a format that is easier to edit and manipulate. Is there a way to reconstruct the documents to obtain the Engineering Reference, Input Output Reference, and other documents in markdown format? I have tried to convert all HTML files into markdown format, which was almost successful, but at the cost of losing nearly all the formulas.
I would appreciate any advice or tips from anyone so that I can complete this task.

best.
zhengrong

**Comment by jmarrec** [comment]
The latex sources are inside the "doc" subfolder of this repo. 

https://github.com/NREL/EnergyPlus/tree/develop/doc
