### ISSUE TITLE
Typo in Electricity:HVAC [J](Hourly) meter output variable in meter.csv

### ISSUE THREAD

**Issue by Sashadf1** [NREL/EnergyPlus#10488]
Issue overview
--------------

When loading AnnualRunMeter.csv into a pandas dataframe for post-processing energy modeling results, I tried to index a column titled Electricity:HVAC [J](Hourly)

```python
meter_df["Electricity:Facility [kWh](Hourly)"] = meter_df["Electricity:Facility [J](Hourly)"]*2.77778e-7
meter_df["Electricity:Building [kWh](Hourly)"] = meter_df["Electricity:Building [J](Hourly)"]*2.77778e-7
meter_df["Electricity:Plant [kWh](Hourly)"] = meter_df["Electricity:Plant [J](Hourly)"]*2.77778e-7
meter_df["Electricity:HVAC [kWh](Hourly)"] = meter_df["Electricity:HVAC [J](Hourly)"]*2.77778e-7
```

The following KeyError was thrown.

```
KeyError: 'Electricity:HVAC [J](Hourly)'
```

Printing out column titles by executing meter_df.columns revealed that the issue is caused by a typo in the dataframe column header specifically for Electricity:HVAC [J] (Hourly). There is an erroneous extra space after the parentheses closing "Hourly" and the end of the string. This seems to be a problem with E+ output reporting code because I did not modify the meter.csv at all before loading it into the pandas dataframe, and the error occurs for multiple separate E+ runs. I don't know if this error is occurring for the last meter variable in the meter.csv file, or specifically for the Electricity:HVAC variable.

Workarounds for users are manually changing the title of the meter column in the csv or other post-processing tool.

Validate that a fix is complete by opening meter.csv and confirming the typo no longer appears.

![image](https://github.com/NREL/EnergyPlus/assets/65982698/f4e0d217-071d-429c-a910-a83669d0df13)

### Details
Operating System: 64-bit operating system, x64-based processor
EnergyPlus v23.2.0

**Comment by jmarrec** [comment]
When opening issues, it's always much appreciated if you can provide an IDF to reproduce (ideally a minimum complete verifiable example (MCVE)). That avoids us having to guess how we can trigger the same conditions.

Anyways, I tested with 5ZoneAirCooled.idf. The issue is just that `ReadVarsEso` is adding an extra space at the end of each line in the eplusout.csv.

**You do not get that problem if instead of relying on ReadVarsEso you use the newer OutputControl:Files**

```
  OutputControl:Files,
    Yes;                     !- Output CSV
```

**Comment by jmarrec** [comment]
I'm tempted to say just "Won't fix". ReadVarsEso is a historical fortran utility, replaced with a native C++ capability (OutputControl:Files), and you can easily work around it if you need to anyways.

```python
df = pd.read_csv('eplusout.csv')
df.columns = df.columns.str.strip() # ReadVarsEso straps an extra space at the end of the line
```

Or even just do it once and for all in text mode before reading it

```python
from pathlib import Path
out_file = Path('eplusout.csv')
out_file.write_text("\n".join([x.strip() for x in out_file.read_text().splitlines()])
df = pd.read_csv(out_file)
```

@Myoldmopar Is it worth tweaking ReadVarsEso?

**Comment by Sashadf1** [comment]
Ok thanks for specifying the workarounds.
