### ISSUE TITLE
Unable to build EnergyPlus (Win x64 Visual Studio 2022)

### ISSUE THREAD

**Issue by simularis** [NREL/EnergyPlus#10480]
Issue overview
--------------
Unable to build EnergyPlus (Win x64 Visual Studio 2022)

Following the build instructions on the wiki, I used CMake to configure and generate a Visual Studio solution. Then in Visual Studio, switched to Release x64 and tried to build the EnergyPlus project. On the embedded_epjson_source project, I got this compiler error.

```
4>------ Build started: Project: embedded_epjson_source, Configuration: Release x64 ------
4>Generating ../Products/Energy+.schema.epJSON
4>Generating the epJSON schema!
4>Building Custom Rule C:/EnergyPlus/idd/CMakeLists.txt
4>Generating embedded/EmbeddedEpJSONSchema.cc
4>Generating the **embedded** epJSON schema
4>EmbeddedEpJSONSchema.cc
4>C:\EnergyPlus\build\idd\embedded\EmbeddedEpJSONSchema.cc(114678,67): fatal  error C1060: compiler is out of heap space
4>Done building project "embedded_epjson_source.vcxproj" -- FAILED.
```

I tried all the variations on adding a `/Zm` compiler option based on some articles, but nothing changed.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 11 Pro, version 10.0.22631 Build 22631, x64-based PC
 - Version of EnergyPlus: develop branch, SHA1 = 420a1ac
 - Compiler: Microsoft Visual Studio Community 2022 Version 17.6.2

**Comment by mjwitte** [comment]
@simularis I just compiled a release build successfully with

- Microsoft Visual Studio Community 2022 (64-bit) - Version 17.9.6 with no special compiler options
- same branch and commit
- Windows 11 Pro
- Cmake version 3.28.1

What's your cmake version?

**Comment by simularis** [comment]
CMake version 3.26.4. I could try updating that.

Also wondering if I need to configure Visual Studio installer options related to CLang? There are a couple of components available which I do not have installed:

- C++ Clang Compiler for Windows (15.0.1) [8.27 GB]
- MSBuild Support for LLVM (clang-cl) toolset [574 KB]

**Comment by simularis** [comment]
Also, I tried a Debug/Win32 configuration, and that compiled okay without any changes to CMake.

**Comment by mjwitte** [comment]
> CMake version 3.26.4. I could try updating that.
> 
> Also wondering if I need to configure Visual Studio installer options related to CLang? There are a couple of components available which I do not have installed:
> 
> * C++ Clang Compiler for Windows (15.0.1) [8.27 GB]
> * MSBuild Support for LLVM (clang-cl) toolset [574 KB]

No, this compiler should be fine

Visual C++ 2022   00482-90000-00000-AA083
Microsoft Visual C++ 2022

**Comment by simularis** [comment]
Installed CMake 3.29.2. Looking for differences, I see only subtle changes to the project file. With CMake 3.29.2, there are some lines like this:

```<ScanSourceForModuleDependencies>false</ScanSourceForModuleDependencies>```

Update: EnergyPlus now compiles successfully. Oddly enough, even if I reinstall CMake 3.26.4, I can no longer reproduce the error. Thanks for the help.
