### ISSUE TITLE
Propose to add an "indoor Wet-bulb Globe Temperature" report variable

### ISSUE THREAD

**Issue by yujiex** [NREL/EnergyPlus#10504]
Issue overview
--------------
The indoor wet-bulb globe temperature (WBGT) is a measure of indoor heat stress as it affects humans.
We propose to add it as a report variable to EnergyPlus to help quantify the thermal resilience of buildings.

It is calculated as follows

WBGT = 0.7*WBT + 0.3*OT

where 
WBT is the zone air wet-bulb temperature already calculated in EnergyPlus
OT is the zone operative temperature, which is the average of the Zone Mean Air Temperature and the Zone Mean Radiant Temperature already calculated in EnergyPlus.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by LaurenFerguson11** [comment]
Is zone air wet-bulb temperature already calculated in energyplus? It's not in the input/output reference?

**Comment by mjwitte** [comment]
> Is zone air wet-bulb temperature already calculated in energyplus? It's not in the input/output reference?

No, it is not. If the zone is conditioned, then it's available for the zone air node, at the HVAC timestep.
`Output:Variable,*,System Node Wetbulb Temperature,hourly; !- HVAC Average [C]`
