### ISSUE TITLE
"Zone Exterior Windows ..." output variables confusingly take a `Space` name

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#10552]
Issue overview
--------------
The IDF linked below, which has a Space in it, has three EMS Sensors referencing output variables. The output variable `Zone People Occupant Count` takes a Zone name while the two `Zone Exterior Windows ...` output variables throw an error with a Zone name. For example:

```
   ** Severe  ** Invalid Output:Variable or Output:Meter Index Key Name =ZONE - SPACE 101
   **   ~~~   ** For Output:Variable or Output:Meter = ZONE EXTERIOR WINDOWS TOTAL TRANSMITTED BEAM SOLAR RADIATION RATE
   **   ~~~   ** Entered in EnergyManagementSystem:Sensor=EMS_SPACE_101_TRANS_BEAM_RAD_SENSOR_1
   **   ~~~   ** Unique Key Name not found.
```

The simulation is successful if the Space name ("Space 101") is provided as the key instead.

Is that intentional or a bug? It's definitely confusing that a "Zone ..." output variable doesn't take a Zone name. I couldn't find anything in the documentation about this.

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - EnergyPlus 24.1
 - Related to https://unmethours.com/question/99208/ems-sensor-for-zone-exterior-windows-total-transmitted-beam-solar-radiation-rate/?answer=99234#post-id-99234

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] [Defect file](https://github.com/user-attachments/files/15649789/in.idf.txt)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Technically, the key for this (and several other related output variables) is the enclosure name. That changed back when air thermal boundaries were added in https://github.com/NREL/EnergyPlus/pull/7455.

FYI if such a question arises in the future, you can reference SetupOutputVariables.csv which resides in the EnergyPlus root install folder.

![image](https://github.com/NREL/EnergyPlus/assets/4991075/281c5929-a6f3-42c0-860d-0527eb8552ed)

The following output variables should all be changed to "Enclosure ...":

"Zone Windows Total Transmitted Solar Radiation Rate"
"Zone Exterior Windows Total Transmitted Beam Solar Radiation Rate"
"Zone Interior Windows Total Transmitted Beam Solar Radiation Rate"
"Zone Exterior Windows Total Transmitted Diffuse Solar Radiation Rate"
"Zone Interior Windows Total Transmitted Diffuse Solar Radiation Rate"
"Zone Windows Total Transmitted Solar Radiation Energy"
"Zone Exterior Windows Total Transmitted Beam Solar Radiation Energy"
"Zone Interior Windows Total Transmitted Beam Solar Radiation Energy"
"Zone Exterior Windows Total Transmitted Diffuse Solar Radiation Energy"
"Zone Interior Windows Total Transmitted Diffuse Solar Radiation Energy"

And that will require doc updates and adding these to the transition report variables file.

**Comment by mjwitte** [comment]
So, one might ask what are enclosure names. It could be a zone name, it could be a space name, or it could be an auto-generated name. Check the "Input Verification and Results Summary" "Space Summary" subtable.   

If zones and spaces are 1:1 and there are no Construction:AirBoundary surfaces, then enclosure names will be zone names.
From 5ZoneAirCooled:
![image](https://github.com/NREL/EnergyPlus/assets/4991075/c03e2542-7fd8-443b-b006-0c618bfe187e)

If zones and spaces are 1:1 but there are air boundaries that combine 2 or more spaces/zones into an enclosure, then some enclosure names will be auto-assigned.
From 5ZoneAirCooled_AirBoundaries.idf
![image](https://github.com/NREL/EnergyPlus/assets/4991075/9d2a5d8f-c2d8-4c48-93ef-c7a97925b5c9)

If spaces are fully enclosed without air boundaries then enclosure names will be space names. But if spaces have only floors, then they will be combined into a larger enclosure. If the floor-based spaces cover the entire zone, then the zone name will be the enclosure name. ~5ZoneAirCooled_AirBoundaries.idf~ 5ZoneAirCooledWithSpacesTable.idf  has all of these flavors:
![image](https://github.com/NREL/EnergyPlus/assets/4991075/538d33f0-d2c4-4c53-bc8d-b6cb81112bc5)

**Comment by rraustad** [comment]
Shouldn't there be a "Solar Enclosure 2" name for Space 3?

**Comment by mjwitte** [comment]
> Shouldn't there be a "Solar Enclosure 2" name for Space 3?

For which file? The rules are 
* If the enclosure contains a single space, then the space name is the enclosure name. 
* If the enclosure contains all of the spaces within a zone, then the enclosure name is the zone name. 
* If the enclosure contains one or more spaces that do not comprise a single zone (could be less than a zone, or contains parts of multiple zones, or contain multiple complete zones). then it's names "Enclosure N".

**Comment by shorowit** [comment]
Shouldn’t there be different names based on context? E.g., “Zone Windows …” vs “Space Windows …” vs “Enclosure Windows …”

**Comment by mjwitte** [comment]
> Shouldn’t there be different names based on context? E.g., “Zone Windows …” vs “Space Windows …” vs “Enclosure Windows …”

Presently, the values are only computed for enclosures, same as "Enclosure Mean Radiant Temperature".

**Comment by shorowit** [comment]
Thanks @RKStrand!
