### ISSUE TITLE
`Site:Location` should not be overridden by weather file

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#10579]
Issue overview
--------------
As described [in the Site:Location documentation](https://bigladdersoftware.com/epx/docs/24-1/input-output-reference/group-location-climate-weather-file-access.html#sitelocation):

> The location class describes the parameters for the building’s location. Only one location is allowed. **Weather data file location, if it exists, will override any location data in the IDF.** Thus, for an annual simulation, a Location does not need to be entered."

This doesn't make any sense to me. There are legitimate situations where a user has entered a `Site:Location` that significantly deviates from the weather station. An obvious example is that the building's site is at a high elevation in the mountains, but the nearest weather station is at lower elevation. Or the building is in one time zone but the nearest weather station is just over the state's border in another time zone.

I agree that `Site:Location` should be allowed to be omitted, such that the weather file data is used, _but if the `Site:Location` is provided, it should take precedence over the weather file_.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Given the long history of the current behavior, I would suggest adding a field to Site:Location to optionally override the epw location.

**Comment by RKStrand** [comment]
@mjwitte I was thinking the same thing as I read this.  A new field in the Site:Location syntax that allows one to override the epw file seems like a good solution.
