### ISSUE TITLE
energyplus IDF editor

### ISSUE THREAD

**Issue by ky5944** [NREL/EnergyPlus#10580]
The idf editor won't open, reinstalling it doesn't help, I'd like to know what's the reason, I'd be grateful for a reply.
[Uploading picture.docx…]()

**Comment by mjwitte** [comment]
More information, please.
What operating system?
What version of EnergyPlus?
There is no attached picture, it just links back to the issue page.

**Comment by ky5944** [comment]
The system is windows

> 请提供更多信息。什么操作系统？什么版本的 EnergyPlus？没有附加图片，它只是链接回问题页面。

I apologize for getting back to you so late. Thank you so much for getting back to me.
The system is windows
Version is 23-2.0
[picture.docx](https://github.com/user-attachments/files/15935683/picture.docx)
i don't know how to provide a picture, anyway it's just that the idf editor software can't open it

**Comment by mjwitte** [comment]
What version of Windows? 11, 10, ?
It just freezes like that? Is there no popup saying why it failed?

**Comment by ky5944** [comment]
> 什么版本的 Windows？11, 10, ?

My computer is Win10 and yes, the editor just doesn't prompt, it stays on a blank screen, I've tried reinstalling it but it still won't open!

**Comment by JasonGlazer** [comment]
You might want to try a fix using Regedit described here:

https://unmethours.com/question/65395/idf-editor-not-working/

**Comment by ky5944** [comment]
> You might want to try a fix using Regedit described here:
> 
> https://unmethours.com/question/65395/idf-editor-not-working/

Thank you very much. it's working. thanks a lot！！！
