### ISSUE TITLE
openstudio plugin

### ISSUE THREAD

**Issue by ky5944** [NREL/EnergyPlus#10590]
After modeling in SketchUp using the plugin, I exported the IDF to EnergyPlus for simulation. The simulation runs, but the error log shows that my zone is not fully enclosed and that there is an edge connected to multiple surfaces. What causes this issue? During modeling, I first drew the floor plan and then used the "Create Space from Diagram" tool. I am not a professional in this field and would like to get an explanation from an expert.
![71MLGQ_~DPG4RE M$E62IN](https://github.com/NREL/EnergyPlus/assets/173480242/949a25d2-1132-4024-8348-07cddf007aa2)

**Comment by jmarrec** [comment]
You should ask on unmethours.com, and attach your model.

But check carefully your geometry, you probably have duplicated surfaces or something.

**Comment by ky5944** [comment]
Thank you very much.I'll try
