### ISSUE TITLE
Documentation typo in 1.5.16 SimulationControl

### ISSUE THREAD

**Issue by Sashadf1** [NREL/EnergyPlus#10606]
Issue overview
Change "Or the user might have all flow rates and equipment sizes already specified and desire an annual weather without any preceding sizing calculations." to instead say "Or the user might have all flow rates and equipment sizes already specified and desire an annual weather simulation without any preceding sizing calculations."

TLDR there is a missing "simulation" noun.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus - 24.1

**Comment by mjwitte** [comment]
@Sashadf1 Please add additional documentation issues as comments #10605
