### ISSUE TITLE
AFN fan array bounds error with multiple airloops

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#10630]
Issue overview
--------------
User file fails with 
```
   ** Severe  ** AirflowNetwork: The airflow direction is opposite to the intended direction (from node 1 to node 2) in AirflowNetwork:Distribution:Linkage = ZONECONNECTIONDUCT_UNIT1_ZN2_RETURN LINKAGE
   **   ~~~   **  Environment=ANNUAL, at Simulation time=01/04 12:00 - 12:10
   **   ~~~   ** The sum of the airflows entering the zone is greater than the airflows leaving the zone (e.g., wind and stack effect).
   **   ~~~   ** Please check wind speed or reduce values of "Window/Door Opening Factor, or Crack Factor" defined in AirflowNetwork:MultiZone:Surface objects.
```

Tried to debug this, but hit an array bounds error here, because both fans have airloop=1, so the for loop exits, leaves `FanNum=3` but there's only 2 fans, so array bounds exceeded. This for loop to look for a matching fan is fragile, and this pattern appears several times.
https://github.com/NREL/EnergyPlus/blob/18f5c3fb9b5068e6123a09ad3ee542b24b09beff/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L8889-L8894

So, why are both `DisSysCompCVFData(FanNum).AirLoopNum=1`? The problem is this function, which was added in #7884 . The logic here ends up setting all fans to the same airloop number.
https://github.com/NREL/EnergyPlus/blob/18f5c3fb9b5068e6123a09ad3ee542b24b09beff/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L10101-L10117

Later on in the simulation, airloopnum is set properly in `Solver::validate_distribution`
https://github.com/NREL/EnergyPlus/blob/18f5c3fb9b5068e6123a09ad3ee542b24b09beff/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L10485-L10486

But `validate_distribution` isn't called until later for some reason.
https://github.com/NREL/EnergyPlus/blob/18f5c3fb9b5068e6123a09ad3ee542b24b09beff/src/EnergyPlus/AirflowNetwork/src/Solver.cpp#L278-L287

In #10372, code was added so that all airloop fans know what airloop they are on, so perhaps the fix is to grab this from the fan data?
https://github.com/NREL/EnergyPlus/pull/10372/files#diff-737f152cfc96fe6b347b1793b736ad42fc93d2f282532c533c6212d073edcda7R1355

### Details
Some additional details for this issue (if relevant):
 - Platform Win11
 - Version of EnergyPlus v24.2-https://github.com/NREL/EnergyPlus/commit/18f5c3fb9b5068e6123a09ad3ee542b24b09beff
 - Helpdesk ticket number 16731

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Also, why doesn't AirflowNetwork_MultiAirLoops.idf trip on this? It has 2 airloops and 2 fans, but one is Fan:Constantvolume and one is Fan:OnOff. The user file has 2 Fan:OnOff.

**Comment by lgu1234** [comment]
@mjwitte I am going to take a look.

**Comment by lgu1234** [comment]
@mjwitte I checked Lines 8889 to 8894 in Solver and found DisSysCompCVFData(FanNum).AirLoopNum are correct>
![AirLoopNum](https://github.com/user-attachments/assets/1c59b017-ad97-4dbd-8ca4-dd78312b1fae)

**Comment by lgu1234** [comment]
@mjwitte I also tried to debug the program and found a Fatal Error to terminate the program.

![FatalError](https://github.com/user-attachments/assets/1839c6e0-a227-43e4-8912-6007401c588e)

No duplication of fan array bounds error is found.

**Comment by lgu1234** [comment]
@mjwitte  Logic in void Solver::assign_fan_airloop() has a problem to setup both numbers = 1 of DisSysCompCVFData(k).AirLoopNum. I am going to solve this issue.
