### ISSUE TITLE
`HeatPump:AirToWater:FuelFired:Heating` curves not using two independent temperature variables

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/EnergyPlus#10665]
Issue overview
--------------

Take "Normalized Capacity Function of Temperature Curve Name" for example. The idd and example idf file both suggest that the object supports a bivariate function (i.e., of outdoor air temperature and water temperature). But if you output "Performance Curve Input Variable 1 Value" and "Performance Curve Input Variable 2 Value", the values are the same at each timestep. It appears that perhaps water temperature is being used as both inputs.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/10000s/10665
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Do you have a reproducer please?

Because code inspection seem to think everything's fine:

https://github.com/NREL/EnergyPlus/blob/2fda8439ae032225cedf71bb35b606d648f45983/src/EnergyPlus/PlantLoopHeatPumpEIR.cc#L2720-L2739
