### ISSUE TITLE
Transition created duplicate ZoneHVAC:TerminalUnit:VariableRefrigerantFlow object

### ISSUE THREAD

**Issue by yujiex** [NREL/EnergyPlus#10746]
Issue overview
--------------
The v24.1 to 24.2 transition code will create one more copy of `ZoneHVAC:TerminalUnit:VariableRefrigerantFlow` when the `Supply Air Fan Object Type` is already `Fan:SystemModel`

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac 13.5.2)
 - Version of EnergyPlus (24.2)
 - Unmethours link or helpdesk ticket number
 - defect file
[US+SF+CZ5B+hp+slab+IECC_2021_VRFPhysics_v2_hrdsize_V2310.idf.zip](https://github.com/user-attachments/files/17050248/US%2BSF%2BCZ5B%2Bhp%2Bslab%2BIECC_2021_VRFPhysics_v2_hrdsize_V2310.idf.zip)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I think I'm still hitting this
