### ISSUE TITLE
EnergyPlus 24.2 material error for residential model w/ Kiva custom blocks

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#10766]
Issue overview
--------------
We use Kiva in all of our residential models and the E+ 24.2 release (but not the IO Freeze release) produces an error for every model.

```
** Severe  ** Did not find matching material for Foundation:Kiva="FOUNDATION KIVA 1", Custom Block Material Name, missing material = EXTERIOR VERTICAL INS
```

The material does exist in the model. So it is probably a bug related to https://github.com/NREL/EnergyPlus/pull/10720.

Example file to reproduce:
[in.idf](https://github.com/user-attachments/files/17134789/in.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@shorowit Any idea what's different about the Kiva specs in the defect file vs the Kiva example file(s)?

**Comment by shorowit** [comment]
It looks like it's because we use Kiva custom blocks, I don't see them used in any of the example files.

![image](https://github.com/user-attachments/assets/f47fdbb7-db65-49cb-a3e9-734346a0dde2)
