### ISSUE TITLE
'Invalid Output Variable or Meter Name' in Meter:Custom results in no meter output

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#10771]
Issue overview
--------------
In 23.1, a Meter:Custom with a mix of valid and invalid meter names would report the results from just the valid meters. In 24.1, no output for the custom meter is reported.

I added the following to the 5ZoneAirCooled.idf example file from both 23.1 and 24.1:
```
  Output:Meter,Cooling:Electricity,Timestep;
  Output:Meter,HeatRejection:Electricity,Timestep;
  Output:Meter,CoolingHVAC:Electricity,Timestep;
  Meter:Custom,
    CoolingHVAC:Electricity,                !- Name
    Electricity,                            !- Resource Type
    ,                                       !- Key Name 1
    Cooling:Electricity,                    !- Output Variable or Meter Name 1
    ,                                       !- Key Name 2
    HeatRejection:Electricity;              !- Output Variable or Meter Name 2
```
That file has no heat rejection equipment so the 'HeatRejection:Electricity' meter is invalid. Indeed both models generate the following warnings: 
```
   ** Warning ** Meter:Custom="COOLINGHVAC:ELECTRICITY", invalid Output Variable or Meter Name="HEATREJECTION:ELECTRICITY".
   **   ~~~   ** ...will not be shown with the Meter results.
   ** Warning ** Output:Meter: invalid Key Name="HEATREJECTION:ELECTRICITY" - not found.
```
In the 23.1 run, the meter output exists for the valid meter names. The 24.1 run, however, does not contain any output for the custom meter.

23.1 output csv:
![image](https://github.com/user-attachments/assets/a15cd945-e8d1-4981-a5a8-e8d825163501)
23.1 output sql:
![image](https://github.com/user-attachments/assets/254b2979-97df-42c4-b81b-c848dce3488c)

24.1 output csv:
![image](https://github.com/user-attachments/assets/dbc98b85-e67b-4d46-b94d-b8f0459db2fc)
24.1 output sql:
![image](https://github.com/user-attachments/assets/18a96e62-e7a0-46db-aa88-5c4ec76bde2f)

The previous functionality is important for automatically creating custom meters that give meaningful output without prior knowledge of what specific outputs are available (e.g. for stock modeling).

Possibly caused by recent Ouput Processor refactors: https://github.com/NREL/EnergyPlus/pull/10384

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA): 24.1
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)
 
[5ZoneAirCooled_23_1.idf.txt](https://github.com/user-attachments/files/17156601/5ZoneAirCooled_23_1.idf.txt)
[5ZoneAirCooled_24_1.idf.txt](https://github.com/user-attachments/files/17156602/5ZoneAirCooled_24_1.idf.txt)

**Comment by amirroth** [comment]
I must have "broken" this in [this PR](https://github.com/NREL/EnergyPlus/pull/10384) (although in my defense, I would say that the previous silent failure implementation is more accurately characterized as "broken"). I think I know how to "fix" this. Will try to get this done in the next day.

**Comment by amirroth** [comment]
Question: what is the desired behavior here? Should a custom meter basically skip any meter or variable with a problem? Or should it only skip meters and variables that don't exist but barf on other errors, like meters or variables that have mis-matching types?

**Comment by eringold** [comment]
IMO the previous behavior was useful to create a custom meter that include meters that may exist, such as to collect all HVAC equipment energy without having to know if e.g. heat rejection equipment existed in that model. I think having the custom measure fail for mismatched types would be fine. 

>I would say that the previous silent failure implementation is more accurately characterized as "broken"

I think that warning message is ambiguous: will the invalid meter not be shown with the custom meter results, or will the the entirety of the custom meter not be shown? I had interpreted it as the former.

**Comment by amirroth** [comment]
> IMO the previous behavior was useful to create a custom meter that include meters that may exist, such as to collect all HVAC equipment energy without having to know if e.g. heat rejection equipment existed in that model. I think having the custom measure fail for mismatched types would be fine.

That makes sense. I can do that. And I agree that there is a case for ignoring a missing variable/meter and not a malformed one.

**Comment by amirroth** [comment]
@eringold, I can't actually test this locally because of some `energyplus` build issue with tk/tcl, but `energyplus_test` builds and runs. Can you see if this fixes your issue? Also, for some reason I am unable to add you as a reviewer. 🤷

**Comment by eringold** [comment]
@amirroth I built and tested locally, and the issue is fixed. Thanks for your attention to this!
