### ISSUE TITLE
Null Value for field !- Basin Heater Setpoint Temperature {C} Causes Error

### ISSUE THREAD

**Issue by Ski90Moo** [NREL/EnergyPlus#10824]
Issue overview
--------------
Field 30 (!- Basin Heater Setpoint Temperature {C}) of the object AirConditioner:VariableRefrigerantFlow causes the following error when left as the default (null) value:

severe error=<root>[AirConditioner:VariableRefrigerantFlow][VRF System][basin_heater_setpoint_temperature] - "0" - Expected number greater than or equal to 2.000000

From the InputOutput reference: "This set point temperature must be greater than or equal to 2◦C, and the default value is 2◦C if this
field is left blank."

It appears the default value is 0, not 2 as the InputOutput reference indicates.  Recommend updating the default value to 2.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) Windows 11
 - Version of EnergyPlus (if using an intermediate build, include SHA) 24.1
 - See also: https://github.com/NREL/OpenStudio/issues/5297

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)  IDF file: 
[in.txt](https://github.com/user-attachments/files/17782925/in.txt)
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
The defect file does have a zero in this field:
```
  0,                                      !- Basin Heater Capacity {W/K}
  0,                                      !- Basin Heater Setpoint Temperature {C}
  ,                                       !- Basin Heater Operating Schedule Name
```
If blank, EnergyPlus runs without error. So, this appears to be just an OpenStudio issue.

**Comment by Ski90Moo** [comment]
Ok, this seems to be a forward translator issue.

**OSM input file:**
[OS Example10-VRF_004-Default.txt](https://github.com/user-attachments/files/17807256/OS.Example10-VRF_004-Default.txt)
  0,                                      !- Basin Heater Capacity {W/K}
  ,                                       !- Basin Heater Setpoint Temperature {C}
  ,                                       !- Basin Heater Operating Schedule
**resulting IDF input file:**
[in.txt](https://github.com/user-attachments/files/17807264/in.txt)
  0,                                      !- Basin Heater Capacity {W/K}
  0,                                      !- Basin Heater Setpoint Temperature {C}
  ,                                       !- Basin Heater Operating Schedule Name

**resulting severe error:**

** Severe  ** <root>[AirConditioner:VariableRefrigerantFlow][VRF System][basin_heater_setpoint_temperature] - "0" - Expected number greater than or equal to 2.000000
