### ISSUE TITLE
When using pyenergyplus to run (via run_energyplus), PythonPlugin initializations errors lead to hang

### ISSUE THREAD

**Issue by TShapinsky** [NREL/EnergyPlus#10842]
Issue overview
--------------
If an error is thrown during the initialization of a PythonPlugin (this could be an import error or an error in the constructor of the plugin) an error is printed, but the function call never exits, it just hangs forever.

I'm happy to add example files if needed, but this should hopefully be pretty straightforward to recreate.

### Details
Some additional details for this issue (if relevant):
 - Debian Bookworm
 - 24.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added : https://github.com/NREL/EnergyPlusDevSupport/commit/4a6027ab293f4d697b60a71e106aa7a83e4a89d3
 - [x] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Generally speaking, it'd be great if you could indeed add example files (ideally a Minimum Complete Verifiable Example), especially if you already have them, as it's always better than having to figure it out.

In this specific case, I already created my own MCVE so all good.
