### ISSUE TITLE
Runaway temperature error from chiller condenser flow control changes

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/EnergyPlus#10858]
Issue overview
--------------
#10511 introduced chiller variable flow controls for condenser loops.

Transitioning an older model with a variable speed cooling tower tower will now cause the condenser loop to have runaway plant temperatures during design sizing, causing the simulation to error out. It seems related to setting flow rates in
[src/EnergyPlus/ChillerElectricEIR.cc](https://github.com/NREL/EnergyPlus/pull/10511/files#diff-d8f99e744e707434b744c235c5f8691bd25f8ff856238d302009d93db305ff96).

A necessary but insufficient test of a fix would be that a model with chiller and variable cooling tower on a condenser loop from E+24.1.0 could be transitioned to E+ 24.2.0 and still produce a valid model.

### Details
 - Platform Windows 10
 - Version of EnergyPlus with failure 24.2.0 (issue not present in 24.1.0)

### Checklist
 - [ ] Defect file [transition_test.zip](https://github.com/user-attachments/files/18156823/transition_test.zip) (the file is in 24.1.0. transition to 24.2.0 to replicate the error).
 - [ ] Ticket added to EnergyPlus Defect Complexity (Github Project)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lymereJ** [comment]
I ran the defect file on 8f663214bff926f06b0fcff7afba077c5ff153aa which is from #10591 which merged before #10511 and I'm also getting the error so I assume that whatever is triggering the plant to overheat is not related to the changes in #10511. I'll keep looking.

**Comment by mdahlhausen** [comment]
> I ran the defect file on [8f66321](https://github.com/NREL/EnergyPlus/commit/8f663214bff926f06b0fcff7afba077c5ff153aa) which is from #10591 which merged before #10511 and I'm also getting the error so I assume that whatever is triggering the plant to overheat is not related to the changes in #10511. I'll keep looking.

Thanks for checking. I assumed it was that PR since it was recent and touched that part of code, but should have confirmed.
