### ISSUE TITLE
The GroundHeatExchanger:Surface model can become unstable and lead to hard fortran crashes.  It may be related to conduction transfer function calculations associated with the Construction, where thick, heavy layers can cause problems w... (CR #7860)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#2640]
###### Added on 2009-09-08 19:55 by @lklawrie
--
#### Description
Non convergence in solving Ground Heat Exchanger
and fatal error.

Input file: 7860-
Weather File: Vienna

2009-09-22 ESL:

I downloaded the defect file, and ran it with current starteam (but with Chicago weather) and it hard-crashed.  The error came around line 1200 in the Surface-GHX module where the CTFs are used to calculate the lower heat transfer rate.  This is quite odd, because I was under the impression that if the CTFs were generated at all, they were fully safe for calculations (not divergent).  

The GHX construction is two identical layers, each 0.5m.  This 1.0m layer construction is pushing the limits of the CTFs, and I am actually surprised they were generated at all for this heavy layer of (assuming) soil.  

I went in and trimmed down the layer thicknesses from 0.5 to 0.4 to 0.1m, and each time the simulation ran further than before with different errors. 

--Base: hard crash
--0.4m: new flow resolver errors, heat pump divergence, property routines out of bounds, as best I can tell these are still byproducts of funny behavior from the GHX
--0.1m: flow resolver errors are in place, but everything else has calmed down, no further warnings or errors (aside from (location object .NE. weather file))

It seems when the GHX is working correctly the heat pump also works properly so the problem is *probably* in the GHX model.

LKL, 25 Sep 2009 -- unfortunately, this now crashes at line 1053 in Surface Ground Heat Exchanger.

2010-01-08 ESL:
Divergence is hard to debug in the code.  The GHX uses a form of transfer functions to handle the transient heat transfer around the source.  The calculations in the code are large array operations, which are very nice looking, but very hard to debug when divergence starts occurring.
Since the model works so well in other cases, I have assumed that the model itself is fine, and input is the culprit.

Test 1: Take GHX, Construction, and Materials from GHX example file and put it in defect file
  Result 1: Works great

Test 2: Take example file and change material thickness from 0.1m to 0.5m (0.5m is thickness in defect file)
  Result 2: Crash

Test 3: Take defect file and trim back material thickness from 0.5 to 0.1
  Result 3: Works great

Thus, the wall thickness is a problem.  However, it could be a problem with a combination of material properties, such as m*cp, or t*rho.  

Tests 4 and 5: Modify cp and rho in a similar way as thickness in the defect file
  Results 4 and 5: These changes do not allow it to run

So thickness is the prominent issue here.

Check to see if a single layer on the top or bottom is the actual issue, not the total thickness:

Tests 6 and 7: Have an unbalanced construction of 0.1m top and 0.5m bottom, and vice versa
  Results 6 and 7: Crash in both cases, it is not a one-sided issue.

So, the total thickness is the problem, and probably the only means of handling this is offering a warning if the user's construction is higher than this value.  I thought that CTFs were reliably convergent if they can be initially generated, but apparently once the source is placed in there, it is complicated.  The CTF engine successfully calculates the transfer function values for this construction, yet when they are used in the GHX model, they crash.

2010-02-25 ESL:  
Although a warning could be offered for a set thickness, this is not quite the best solution.  It would be nice to detect problems in the QTF calculations instead of just throwing a warning.  I'll point this to RS in hopes he would be the fastest at determining if there is a problem in the implementation, or detecting errors in the current run before it crashes.

RKS 2010.03.17
The problems with the CTF calculations in very limited situations is a known problem.  This and another CR will be fixed when the work on a UIUC FY2010 task is complete.  It is anticipated that this work will be ready for the Fall 2010 release of EnergyPlus.  Input files for this CR will be used along with many other test input files to verify that a true fix has been achieved.

LKL 2011.10.05
This one still crashes.  Uploaded updated file to V7.

Code it is crashing on is a bit cryptic:
Line 1271ff:
  SurfaceGHEQTF(SurfaceGHENum)%QtopConstCoef = SUM(SurfaceGHEQTF(SurfaceGHENum)%CTFout * &
                                           SurfaceGHEQTF(SurfaceGHENum)%TtopHistory - &
                                           SurfaceGHEQTF(SurfaceGHENum)%CTFcross * &
                                           SurfaceGHEQTF(SurfaceGHENum)%TbtmHistory + &
                                           SurfaceGHEQTF(SurfaceGHENum)%CTFflux * &
                                           SurfaceGHEQTF(SurfaceGHENum)%QtopHistory + &
                                           SurfaceGHEQTF(SurfaceGHENum)%CTFSourceOut * &
                                           SurfaceGHEQTF(SurfaceGHENum)%QsrcHistory)

but all the things in this expression are arrays.  I did not look at each individual but would be a bit questionable as to what it did (vector multiplies subtracts, etc).  And to figure it out, I thnk, would require each term individually?  This is the code in the regular source and it doesn't crash, but it just seems unclear.

Well, it's still a hard crash. I unrolled the equations like above into do loops.  The file is actually going out of control calculating the flux term (CalcSourceFlux).  Maybe this will help Rick or Edwin sort it out.

LKL 2011.10.23
Ran V7 file with Miami weather -- did not crash which lends credence to the idea that it's not a CTF problem but rather a calc of the surface ground heat exchanger. I'm going to assign it back to Edwin.

--
External Ref: ticket 1455
Last build tested: `09.09.03 V4.0.0.015`

**Comment by rglazer2** [comment]
Reran defect file in v8.4 with Vienna weather and it no longer crashes. Fatal Error is created instead saying that ground heat exchanger did not converge.
