### ISSUE TITLE
Utilize the resource fork on the Macintosh instead of using GraphHints.csv (CR #8087)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#2864]
###### Added on 2010-04-14 06:35 by @JasonGlazer
--
#### Description
see email to Kyle Benne on April 13 2010

--
Last build tested: `10.04.13 V5.0.0.030`

**Comment by Myoldmopar** [comment]
@kbenne I'm closing this as I think it is not relevant to address.  Feel free to reopen if you disagree.
