### ISSUE TITLE
Match IO Reference groups/organization to IDD \Group... for \group Node-Branch Management and \group Air Distribution (CR #8089)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#2866]
###### Added on 2010-04-14 08:04 by Don Shirey
--
#### Description
14-Apr-2010

Under CR 7932, the IO Ref content for Duct was moved out of Group - Pumps.

Shirey suggested it be moved to \group Node-Branch Management... which Linda did.

However, another option was moving it to \group Air Distribution

After Linda moved the IO Ref content for Duct to Group - Node-Branch Management, which matches its \group as defined in the IDD......   she noted that in the IDD, under \group Node-Branch Management, the following objects are included:

\group Node-Branch Management
Branch
BranchList
Connector:Splitter
Connector:Mixer
ConnectorList
NodeList
OutdoorAir:Node
OutdoorAir:NodeList
Pipe:Adiabatic
Pipe:Adiabatic:Steam
Pipe:Indoor
Pipe:Outdoor
Pipe:Underground
Duct

This IDD "grouping" matches the IO Ref table of contents grouping, with the following exceptions:

In the IO Ref table of contents, Connector:Splitter and Connector:Mixer are in Group -- Plant-Condenser Flow Control (along with TemperingValve).

Also in the IO Ref table of contents, OutdoorAir:Node and OutdoorAir:NodeList are in Group -- AirDistribution

So, should the IDD groupings and IO Ref Table of Contents groupings match each other?  Probably so to avoid confusion for users.  If so, some decisions need to be made regarding Connector:Splitter, Connector:Mixer, OutdoorAir:Node and OutdoorAir:NodeList

MJW 11 Apr 2012
Not sure this is worth doing now.  Checking with LKL and BG.

--
Last build tested: `10.04.13 V5.0.0.030`

**Comment by Myoldmopar** [comment]
Not going to worry about aligning the idd and io ref order. Closing.
