### ISSUE TITLE
SimHVAC: Max Iteration errors when HX used in OA system and Controller input set to BypassWhenOAFlowGreaterThanMinimum. (CR #8123)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#2900]
###### Added on 2010-05-21 06:46 by @rraustad
--
#### Description
20 Oct 2010 RAR

Revised synopsis to more accurately reflect the root cause of this CR.

SimHVAC: Max Iteration errors can occur in a VAV system when the supply air temperature is not maitained within a tight temperature tolerance and VAV dampers can modulate to meet the zone load. This rare occurance can cause the new mixed air temperature to slightly change which in turn can again cause the VAV dampers to select a new zone air flow rate.  One example is when the heating coil, cooling coil, and mixer are temperature set poins use the same value. If the cooling coil is scheduled off and this set point is above the heating coil outlet air set point, the mixed air damper may not be able to modulate enough to meet this set point and the resulting temperature is between the temperature where the mixed air damper can control to and the heaitng coil outlet air set point temperature.  

Original Synopsis:
SimHVAC: Max Iteration errors when HX used in OA system and Controller input set to BypassWhenOAFlowGreaterThanMinimum.  

User file shows many SimHVAC iteration warnings, HX flow mismatch warnings, and a few DX coil iteration exceeded for sensible PLR warnings. Good file to delve into causes for max iteration errors. Also review of HX Bypass logic in MixedAir.f90.

Defect File: 8123-XcelAshland_ProposedFinalRFC.idf
Weather File: USA_WI_Phillips-Price.County.AP.726468_TMY3.epw

--
#### Further Details for Users
This specific problem is not directly related to the HX. The supply air temperature appears to be in a floating condition. When the VAV dampers respond to the air flow to meet the zone load, the supply air flow rate is affected which changes the mixed air temperature. This directly affects the supply air temperature and the VAV dampers again try to adjust to meet the zone load.

--
#### Workaround
No specific solution at this time. The remedy may be related to holding the supply air temperature at some fixed value (i.e., heating and cooling coils active at all times and maintaining the same supply air temperature set point).

--
Last build tested: `10.04.26 V5.0.0.031 - Release`

**Comment by mjwitte** [comment]
The max iterations were due to a reset of the minimum outdoor air flow rate using an incorrect value of the airloop minimum OA flow rate. BypassWhenOAFlowGreaterThanMinimum currently shuts off the economizer whenever a heating coil is active (as described in the I/O Ref, but this may be changed shortly) and reset the controller min OA flow rate.  But the min OA flow rate it was grabbing was based on OAMinFrac multiplied by the air loop _design_ flow rate instead of the _current_ air  loop flow rate.

**Comment by Myoldmopar** [comment]
Closed via #5182
