### ISSUE TITLE
Tabular data is stored as text in the current SQLite database output. (CR #8153)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#2930]
###### Added on 2010-06-21 10:22 by @kbenne
--
#### Description
Tabular data is stored as text in the current SQLite database output.  Ideally, numbers would be stored as numbers and text would be stored as text.  Unfortunately, the tabular data is handled in a generic fashion, therefore the database has to have the ability to handle any type of data that is passed to it.  Giving the tabular data an affinity for numeric data causes the sqlite engine to raise an exception when processing very large numbers.  This arises for example with surface names from OpenStudio that sometimes look like very large numbers in scientific notation.  To avoid this problem a decision was made to store all tabular data as text.  

Ideally there should be unique database tables for all of the tabular data and the data should be typed appropriately.  The very large number of tables in addition to the user defined tables makes this change request difficult.  Another option would be to gracefully handle the exception raisded by sqlite or modify the sqlite behavior from within the engine.

--
Last build tested: `10.06.03 V6.0.0.002`

**Comment by mjwitte** [comment]
@kbenne @mbadams5 Is this issue moot now?

**Comment by mbadams5** [comment]
I'm going to close this for now. SQLite stores everything as text within the engine regardless. Changing the type to [integer or real changes the affinity](https://www.sqlite.org/datatype3.html#expraff), which is useful for comparisons but EnergyPlus doesn't do many (if any) of them. This would also require a massive change to the Tabular Data table. Unless this becomes an issue for more users and current OpenStudio, I don't think this should be undertaken at this point. Maybe during another Outputs overhaul (like adding JSON outputs) this could be considered at that point.
