### ISSUE TITLE
Engineering Reference section for Thermal Comfort Models (Fanger, Pierce, KSU) need documentation update, and equation review.  The equations in the code are different from the current documentation. (CR #8220)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#2996]
## 
#### Description

BAN [Sep 10, 2010]
This defects or engineering documentation update need was noted while working on CR8084.   

The engineering reference has never been updated for all code modifications made probably since the first implementations.  Some equation are completely different or to say the least the coefficients of some of the equation have changed due to either units change or replaced with new equations. Eng. Ref. documentation is outdated with respect to the existing code.  Several folks may be responsible for making documentation changes since various folks have made changes over time.
## 

Last build tested: `10.08.30 V6.0.0.014`

**Comment by RKStrand** [comment]
Lots of changes made to this section to correct the issues. There were a lot of problems here--equations that were not correct, typos, bad formatting, etc.  Documentation looks a lot better and the errors have now been corrected.  All of the equations are now identical to the source code.

**Comment by Myoldmopar** [comment]
Closed via #6317
