### ISSUE TITLE
The Input Output reference documentation lacks description or explanation regarding the PMV and PPD variables calculations and the two levels of reporting (comfort reporting and comfort control) available. (CR #8222)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#2998]
## 
#### Description

BAN [Sep 10, 2010]
These defects or documentation updates need were noted while working on CR8084.

The IO reference documentation lacks description or explanation regarding the PMV and PPD variables calculations and the two levels of reprting (comfort reprting and comfort control) available.  

Tthere is no statement in the "Thermal Comfort Setpoints" section of the Fanger model (in the IO reference) that discusses how the PMV and PPD values are calculated, that is whether it is using zone time step (average) value or recent system time step values for zone air temperature and humidity ratio. 

Also, the "FangerPMV" and "FangerPPD" are reported as "people" object outputs and the descriptions given for these two output variables is not indicative that there are two types of reports, one with Thermal Comfort Setpoints defined (uses a system time step values) and the other reporting for thermal comfort uncontrolled case (which uses zone time step average values) for the calculation of "FangerPMV" and "FangerPPD".

This defect might also apply to the other two (Pierce, and KSU) thermal comfort control model as well.
## 

Last build tested: `10.08.30 V6.0.0.014`

**Comment by RKStrand** [comment]
@Nigusse Before I start working on this, I just want to make sure I fully understand the problem as you see it.  So, I am going to try to restate what you said--could you please review this and either let me know that I have understood or not?  Thanks!

1. You are talking specifically about the section titled Thermal Comfort Setpoints that is listed as section 1.35.12 starting on page 1620 in V9.1 of the IO Reference. In addition, there are report variables described in sections 1.13.1.2.27 and 1.13.1.2.28 on page 474 in V9.1 of the IO Reference that will also need some improvement.

2. Section 1.35.12 is pretty brief and does not mention how PMV or PPD are calculated.  While you are not asking for equations here (something that is in the Engineering Reference--I can at least add a reference to that document as I make changes here), you feel like there needs to be some mention of whether the calculation of PMV and PPD use zone time step (averaged) values or system time step level values for zone air temperature and humidity.  In fact, Section 1.35.12 AND the documentation for report variable "Zone Thermal Comfort Fanger Model PMV" (and PPD) found in Section 1.13.1.2.27 (and .28) need to explain which values are being user.  Basically, the documentation needs to clarify in these two places that when the zone is "uncontrolled" (or floating) that the reports will show values based on the values at the zone time step and when the zone is using thermostatic controls that the values shown for PMV and PPD are based on the system time step level.

3. Based on what I am seeing in the documentation and the IDD, the only comfort controls for E+ are based on the Fanger model.  I do not see anything related to the Pierce or KSU models.  So, the only changes that are needed are for the Fanger model.

Do you agree with these three points?  Did I miss anything?  Thanks!

**Comment by Nigusse** [comment]
@RKStrand That sounds correct to me, long time to remember all the details. I am not asking for equations in the IO reference. If remember correctly I felt the information that I found is not detailed enough to explain how those two reporting variables different. Any explanation without adding equation but pointing how these report variables actually calculated may help. Regarding item(3), you are right there is no control option for these two comfort models.

**Comment by Myoldmopar** [comment]
Closed via #7307
