### ISSUE TITLE
The field Minimum Indoor Temperature in the object ZoneVentilation:WindandStackOpenArea was corrected to work properly. (CR #8371)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3146]
## 
#### Description

[BAN 31-March-2011].
Confirmed the defect.  The Minimum Indoor Air Temperature input variable in "ZoneVentilation:WindandStackOpenArea" object was not assigned to the correct value during get input.  Now this defect has been corrected and verified.

3/29/11 L. Gu

Corrected variable name to read the input.

A test file was uploaded. Chicago weather file can be used.
## 
#### Further Details for Users

The Minimum Indoor Air Temperature input variable in "ZoneVentilation:WindandStackOpenArea" object was not assigned to the correct value during get input.  Now this defect has been corrected.
## 

External Ref: Ticket 3940
Addressed in `11.04.03 V6.0.0.035` by @lgu1234
Last build tested: `11.03.27 V6.0.0.034`

**Comment by keigo-nomura** [comment]
Was this really resolved?
Some users face this issue with EnergyPlus v8.9.0 and v9.4.0.
[https://unmethours.com/question/68023/minimum-indoor-temperature-in-zoneventilationwindandstackopenarea-does-not-work/?comment=77966#post-id-77966](url)

**Comment by Ski90Moo** [comment]
It appears this is still an issue.  I simulated a simple, single zone with electrical heat.  When the window open area fraction is set to zero, the zone maintains set point.  When the window open area fraction is set to 1, the zone goes below both the window opening temperature and the zone heating setpoint temperature.  
![2023-02-25 (1)](https://user-images.githubusercontent.com/69771412/221391031-48c6e586-468a-4c4f-a0da-5ef7a204b36d.png)

![2023-02-25 (2)](https://user-images.githubusercontent.com/69771412/221391035-88f1457d-4158-4f62-b554-e5c1aebccac5.png)

Here is the idf: 
[in.txt](https://github.com/NREL/EnergyPlus/files/10832895/in.txt)

**Comment by lgu1234** [comment]
@Ski90Moo I am going to take a look. Is it possible to upload a test file the weather file name (if available in EnergyPlus.net)? If possible, please also tell me the output variables and time in the csv file.

Thanks.

**Comment by Ski90Moo** [comment]
@lgu1234 The test idf file is uploaded in my previous post (see "in.txt").  The weather file is La Grande Muni Ap, Oregon, USA, downloaded from energyplus.net.  The output variables and time is shown in the DView snapshots above (March 9th).

**Comment by lgu1234** [comment]
@Ski90Moo I tried to repeat what you got. Unfortunately, I am unable to do it after I changed report frequency to "timestep". Enclosed are my input file and output on Mar. 9.

![Mar9](https://user-images.githubusercontent.com/5970656/223218272-fdce2666-c604-4304-8111-85c3a1af8e1a.png)



[9856.txt](https://github.com/NREL/EnergyPlus/files/10902380/9856.txt)

**Comment by Ski90Moo** [comment]
@lgu1234 I downloaded your idf file and I can confirm I get the same results as you do.  The problem is that your model has zero natural ventilation in the entire 8760 hours of simulation.  There is clearly something wrong with the file.  

Alternatively, if I set the report frequency to timestep on my OpenStudio file, I get this:
![2023-03-06 (1)](https://user-images.githubusercontent.com/69771412/223313417-ab5afd0e-8a1a-4902-b765-f5ed118ab14e.png)

**Comment by lgu1234** [comment]
@Ski90Moo Please upload your input file.

**Comment by Ski90Moo** [comment]
Hello @lgu1234 can you send me the eplusout.sql file?

**Comment by Ski90Moo** [comment]
@lgu1234 this is the .sql output from your idf file above.  You can see that there is no natural ventilation all year:
![2023-03-09 (13)](https://user-images.githubusercontent.com/69771412/224127969-aade3be6-9540-4581-ade3-82f579ae0c89.png)

**Comment by lgu1234** [comment]
@Ski90Moo I know I may use different test file and got different results. That is why I need your input file to confirm your findings. Please upload your file.

**Comment by Ski90Moo** [comment]
> @lgu1234 The test idf file is uploaded in my previous post (see "in.txt"). The weather file is La Grande Muni Ap, Oregon, USA, downloaded from energyplus.net. The output variables and time is shown in the DView snapshots above (March 9th).

@lgu1234 my input file is attached to my original post
