### ISSUE TITLE
It has been suggested that cross platform utilities should not use the  ApplicationData folder, rather they should use an EnergyPlus subfolder. (CR #8424)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3199]
## 
#### Description

Looking at the cross-platform utilities, they are getting their application data -- from the ApplicationData folder.  Suggest they get them from an EnergyPlus subfolder.

(Not sure how the "installing user" vs "all users" works here -- nor how things work on Mac or Linux).

Windows Install could make this folder (I think).  And have default files put there.
Should we consider putting some of the other registry keys there too?  Or is that too much to expect of the VB utilities?

(so, after this is done, we either need a new CR for install or reassign this to me for the installer).
## 

Last build tested: `11.05.18 V7.0.0.015`

**Comment by Myoldmopar** [comment]
New cross platform utilities are starting to do this better on their own.  Marking this closed.
