### ISSUE TITLE
Suggested change to current design of the electric load center dispatch to not assume battery draw capacity is less than the max power that the generators can dispatch.  The battery should be able to occasionally provide more power that... (CR #8436)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3211]
###### Added on 2011-06-23 14:29 by Brent Griffith
--
#### Description
Current design of the electric load center dispatch assumes batter draw capacity is less than the max power out that is dispatchable among the generators.  

Need a comprehensive review of how TotalPowerRequest is filled when there is battery interactions. 

Defect file:  8436_Refcase1.idf  --  shows the storage discarge limited to 125,000W which is the sum of the wind turbines, not the limit on the batter discharge.

--
#### Workaround
artifically increase the values in the Rated Electric Power Output field in the ElectricLoadCenter:Generators object

--
External Ref: user Florita
Last build tested: `11.06.23 V7.0.0.016`

**Comment by EnergyArchmage** [comment]
Closed via #5437
