### ISSUE TITLE
Suggest including some guidelines on compiling EnergyPlus (CR #8457)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3231]
###### Added on 2011-06-29 12:59 by @lklawrie
--
#### Description
Need Suggestion CR to put compilation directions into Module Developer's guide.

Thanks, Linda. I resolved the issue.  When I started the project , I did not pay attention and selected server version instead of Console application. 

LKL 9 Oct 2013
Edwin, I should have given this to Luigi.  This will be an important thing in the c++ version.  Too late for the Fortran version (to do more than I already do in the source readme)

--
External Ref: email from Mahabir Bhandari
Last build tested: `11.06.23 V7.0.0.016`

**Comment by Myoldmopar** [comment]
CMake has helped address this, and the instructions are pretty good in the GitHub README.  We'll provide a separate task for overhauling the module developer's guide.  Closing this.
