### ISSUE TITLE
Zone and system sizing in EnergyPlus is generally based on calculations of air system flow rates, these might need to be revised to be based on calculations of load to handle certain unusual situations. (CR #8557)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3331]
## 
#### Description

Forked from CR 8178

[05Oct2010 FB]

Why do the 2 cases - coincident / noncoincident produce such different sizing inputs for the chilled water coil?

The design inlet air temperature for the cooling coil is basicall the system cooling design mixed air temperatute (MAT).
In this case (100% outside air) this is just the system cooling design outside air temperature (OAT) which obviously
crucially depends on the time of the peak and the design day outside air temperatute at the time of the peak.

The coincident case is obtaining the cooling design OAT from the summer design day. The noncoincident case is 
obtaining the cooling design OAT from the winter design day. 

Why is this? In the zone sizing calcs the peak cooling is chosen from the winter design day. This is due to:

a) the peak is chosen based on flow rate, not load.

b) the user's input is defective. The zone cooling design supply temperature is 18C. The heating/cooling
zone setpoint is 25C for the summer design day, 20C for the winter design day. Thus even though the summer
 design day has larger cooling loads, the small delta T in the winter gives the winter design day a larger 
peak cooling air flow rate.

c) the system noncoincident calculation simply adds up the zone peaks (chosen by flowrate and hence
from the winter DD) and gets the design MAT from the flow-weighted average MAT of the zones at the
time and the DD of the zone peaks.

d) the coincident calc looks at all the DDs, adds the zone flows at the same timestep, and chooses a peak based
 on the central sensible cooling demand. This includes the ventilation load and thus can produce a very
different result in terms of time-of-peak tha for the noncoincident calc. In this case the demand is ventilation
dominated and the concident calculation chooses the summer design day at the peak OAT.

So there is an inconsistency in the zone / system sizing calulations in the use of flowrate or load to choose
the peak and the time of the peak.

What if we change the zone sizing calcs to use the load instead of the flowrate in choosing the peaks? The calc then
(in this case) chooses the summer design day, and the coincident system results look a lot better.

But they are still quite different from the coincident results. Namely, the noncoincident design MAT is
~24C, the coincident is 31C.

This is because the zone cooling design flows and loads peak at startup, when the OAT is ~24C, whereas
the coincident central system cooling demand, which includes the 100% OA load, peaks in the afternoon
when the OAT is hottest.

The resulting system design cooling air flow rates are almost equal for coincident and noncoincident, but
the design central cooling water flow rate and the central design cooling capacity are 2X bigger for
coincident versus noncoincident (the opposite of the usual case!).

Suggestions: 

1) possibly change the zone sizing calc to select on load, not flow rate. In most cases this won't
change anything, but it will prevent some pathological cases such as this defect file fro choosing
the wrong design day.

2) Always use coincident from 100% outside air sizing, since noncoincident is not choosing a peak
timestep taking ventilation load into account.

3) Coincident sizing - the time of the max air flow rate may not coincide with the time of the max
cooling demand. Shouldn't we save the max flow & time and the max cooling demand and time?

4) Noncoincident - same thing. Shouldn't we use the coincident max cooling demand & time, as
well as the noncoincident design flow.

Or would there be much difference if we forced the user to use flat thermostat schedules.
# 

So CR 8178 did a variant of 2). Remaining issues are:

a) think about implementing 1)

b) suggestion 3) also raises an important issue. What, for instance, should a cooling coil be
sized on - the max flow with coincident load; or the max load with coincident flow. Or the
noncoincident max flow and max load - but does that make any sense? 

---

MJW 21 Mar 2012
Trying to refresh my mind with all the considerations here.  Seems that the only way to fully capture the max coil load is to walk through each design day with the stored zone flow rates and return temps and compute the coil entering conditions and figure out the peak entering enthalpy(?) x flow and design off that.  Leaving enthalpy is fixed by the sizing:system inputs, so this should result in the max coinicident coil load.
## 
#### Fix

The ôtime of airflow peakö vs ôtime of coil peakö can occur at separate times but this is ignored by Ideal Loads. The ZoneHVAC coil capacity "time of peak" entering conditions are currently based on the time of the zone space sensible peak whereas the AirloopHVAC coil capacity "time of peak" entering conditions are currently based on time of sensible ra/oa mix peak. One method can lead to undersized coil capacity while the other method can lead to undersized airflow. The capacity of the cooling coil may also be undersized in humid climates since the time of the coil peak for both ZoneHVAC and AirloopHVAC ignore the latent effect of the entering coil conditions. The only solution is to find both the time of the airflow peak and a separate time for the coil peak. This is discussed in \EnergyPlus-Dev\Collaborative Developments\Equipment Sizing Issues\Pre-NFP_Autosizing_CoilPeak_AssigningLoads_DOA_FanHt.docx
## 

External Ref: Forked from 8178
Last build tested: `11.09.24 V7.0.0.023`

**Comment by mjwitte** [comment]
@wfbuhl Is this issue (from 2010) being addressed with your current sizing work?

**Comment by Myoldmopar** [comment]
@wfbuhl Is this issue (from 2010) being addressed with your current sizing work?

**Comment by wfbuhl** [comment]
_"So CR 8178 did a variant of 2). Remaining issues are:_

_a) think about implementing 1)_

_b) suggestion 3) also raises an important issue. What, for instance,
should a cooling coil besized on - the max flow with coincident load; or
the max load with coincident flow. Or thenoncoincident max flow and max
load - but does that make any sense?"_

a) We have done nothing about implementing 1), other than think about it.
b) For central cooling coils, this has been dealt with in a previous sizing
upgrade. Nothing has been done for zone coils.

Fred

**Comment by Myoldmopar** [comment]
Lots of improvements over the years, this has most likely been addressed by now.  Closing.
