### ISSUE TITLE
The figure art that helps describes the ZoneHVAC:OutdoorAirUnit model in the Input/Output Reference is not clear and has errors.  See the version in the Engineering Reference for a corrected version. (CR #8608)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3381]
###### Added on 2011-10-20 12:52 by Brent Griffith
--
#### Description
the figures for zoneHVAC:OutdoorAirUnit are not adequate.  The node naming is not clear.  

[BG 10-03-2012]  the figure in I/O ref, Figure 97 in version 7.2 doc, still shows problems.  The figure in Eng. Ref did get corrected, Figure 300 in Version 7.2 docs

--
Last build tested: `11.10.19 V7.0.0.027`

**Comment by Myoldmopar** [comment]
Closed via #5402
