### ISSUE TITLE
Speed up ConvertESOMTR? (CR #8617)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3390]
###### Added on 2011-10-26 15:50 by @mjwitte
--
#### Description
MJW 26 Oct 2011
For large output, such as an annual run with hourly output, ConvertESOMTR takes quite a while (10-20 seconds) to process.

[LKL 11/5/2011]
FYI - Ticket 8398 has been my hallmark.
Took about 35 sec to process -- I reduced that by 15%.

I compared the vb app on the same file -- seemed like it took (wall clock time) about that same 35 sec.

On another machine -- i got about 40% speed up/time reduction.

MJW 21 Mar 2012
Was unassigned - assigning to LKL - still an issue?

LKL 9 Oct 2013
I tried various things -- will give it back to Jason. Attachment is my benchmark file for timings.

--
Last build tested: `11.10.19 V7.0.0.027`

**Comment by Myoldmopar** [comment]
2011 improvement was sufficient.
