### ISSUE TITLE
The plant solver sometimes has problems detecting when it is sufficiently converged and needs to be improved.  When modeling complex plant systems, care should be taken to ensure that the solution is converged. (CR #8650)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3423]
## 
#### Description

Changes made for CR 8641 corrected one use of MinPlantSubIterations.  Additional testing shows that now results show dependence on the value of MinPlantSubIterations which is currently set to 2. Ran test suite with MinPlantSubIterations set to 3 and got some significant diffs. 

Some example files with disturbing results from this testing include:

5ZoneDetailedIceStorage.idf
5ZoneElectricBaseboard.idf
5ZoenIceStorage.idf
5ZoneSupRetPlanRAB.idf
5ZoneSupRetPlenVSATU.idf
5ZoneVAV-ChilledWaterStorage-Mixed.idf
5ZoneWarmestVFD.idf
5ZoneWaterCooled_HighRHControl.idf
5ZoneWaterCooled_MultizoneAVerageRHControl.idf
5ZoneWAtercooled_MultizoneMinMAxRHControl.idf
5ZoneWLHPPlantLoopTower.idf
CompSetPtControl.idf
DisplacementVent_1ZoneOffice.idf
EMSDemandManager_LargeOffice.idf
FreeCoolingChiller.idf
HeatPumpWaterHeater.idf
HeatPumpWaterToAirWithRHControl.idf
HeatRecoveryElectricChiller.idf
HVACTemplate-5ZoneVAVFanPowered.idf
HVACTemplate-5ZoneWaterCooled.idf
MicroCoGeneration.idf
PlantPresssure_PumpCurve.idf
PondGroundHeatExchanger.idf
SeriesActiveBranch.idf
SolarCollectorFlatPlateWater.idf
Supermarket_DetailedWAterCondenser.idf
Supermarkete_waterCondenser.idf
WaterSideEconomizer_Integrated.idf
WaterSideEconomizer_NonIntegrated.idf

 Need to review and rework how the plant detects when no more interations are needed because it does not appear to be working well.  Needs more diagnostics and investigation.    

[BG 11-21-2011]  interim changes were made to expose the iteration limits to the user in new feilds for ConvergenceLimits.  This is a stop gap, the convergence detection needs to be improved.  leaving open and setting to defect.
## 
#### Further Details for Users

The ConvergenceLimits objects now contains fields for minimum and maximum plant sub iterations.  This is especially important for complex plant systems which include those with inter-connected loops, common pipes, heat recovery, and on-site generators.Convergence of plant models can be investigated by varying the value for the minimum plant iterations and examing how results change. Increase the minimum and maximum limits until the change in results is small for your purposes.
## 

Last build tested: `11.11.15 V7.0.0.035`

**Comment by mjwitte** [comment]
@EnergyArchmage Is this still relevant?
