### ISSUE TITLE
Review and update soil properties in Eng Ref and other docs (CR #8678)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3451]
###### Added on 2011-12-06 12:09 by @mjwitte
--
#### Description
MJW 06 Dec 2011
User questioned the soil property data in the Earth Tube section of the Engineering Ref.  Ticket dialog shown below.  Probably worth finding some alternate source of data and update this.  May also apply to Slab and Basement preprocessor doc and underground pipess?  In v7 docs, the original table in question is found in the Eng Ref, pdf p. 1110.

Ooi Koon Beng Posted on: 05 Dec 2011 01:43 AM
==========================================================

According to the 1991 ASHRAE Handbook of HVAC Applications(Table 4, pp. 11.4), the following values are recommended under different conditions.Soil conditionks (W/m░C)?s x 10-7(m2/s)Heavy soil, saturated2.429.04Heavy soil, damp solid masonry1.306.45Heavy soil, dry0.8655.16Light soil, damp--Light soil, dry0.3462.80
The above is on page 1008 of the v6 Engineering Reference. It shows that as the soil gets wetter, the thermal diffusivity increase and suggests that the thermal diffusivity of water is more than 2.80 x 10-7 m2/s. the lesser data for dry soils in the above table. 
However, the thermal diffusivity of water is only about 1.4 x 10-7 m2/sec and the standard thermal diffusivity used for the undisturbed Ground temperatures in the stat and .ddy files is 0.002322 m2/day or 0.2688 m2 x 10-7 m2/s or one quarter that of water. These contradict the conclusion in the above paragraph. 
i do not have a copy of the ASHRAE Handbook of HVAC Applications and so i am writing this mail. Sorry for the inconvenience
best regardsooi

Michael J. Witte Posted on: 06 Dec 2011 01:04 PM
==========================================================
The numbers you quote below from 1991 ASHRAE are the thermal conductivity values, not the thermal diffusivity.

I no longer have the 1991 handbook, so I cannot verify the data.  The newer handbooks are organized differently, so I cannot locate the equivalent table.  To add more confusion, from the geothermal energy chapter, properties for soil thermal diffusivity in (m2/day) range from 0.042 to 0.14 with lower water content showing higher diffusivities.  I would suggest you find an alternate source of data.

--
External Ref: Ticket 5122
Last build tested: `11.11.20 V7.0.0.036`

**Comment by mjwitte** [comment]
@mmatts Is this something you could address?

**Comment by mitchute** [comment]
@mjwitte yes, I can take care of it.

**Comment by mitchute** [comment]
![file000](https://cloud.githubusercontent.com/assets/2985979/12176804/cdde8986-b52e-11e5-9e44-7b0cac29b897.jpeg)
Table 4, pg. 11.4 ASHRAE Applications Handbook (SI). 1991.

![file001](https://cloud.githubusercontent.com/assets/2985979/12176920/784d505a-b52f-11e5-98ed-68f41a93840f.jpeg)

|  |  | 5% | 5% | 10% | 10% | 15% | 15% | 20% | 20% |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Soil Type | Dry Density | k [W/m-K] | alpha [m2/s] | k [W/m-K] | alpha [m2/s] | k [W/m-K] | alpha [m2/s] | k [W/m-K] | alpha [m2/s] |
| Coarse   100% Sand | 1922 | 2.77 | 1.34E-06 | 2.94 | 1.24E-06 | 3.29 | 1.18E-06 |  |  |
|  | 1602 | 1.90 | 1.18E-06 | 2.34 | 1.18E-06 | 2.51 | 1.08E-06 | 2.68 | 8.82E-07 |
|  | 1281 | 1.38 | 1.18E-06 | 1.56 | 9.14E-07 | 1.56 | 8.06E-07 | 1.47 | 6.99E-07 |
| Fine Grain   100% Clay | 1922 | 1.21 | 5.91E-07 | 1.21 | 4.84E-07 | 1.64 | 5.70E-07 |  |  |
|  | 1602 | 0.95 | 5.70E-07 | 0.95 | 4.73E-07 | 1.12 | 4.73E-07 | 1.21 | 5.16E-07 |
|  | 1281 | 0.69 | 4.84E-07 | 0.74 | 4.62E-07 | 0.81 | 4.73E-07 | 0.87 | 4.09E-07 |

Table 3.3 pg. 26 ASHRAE Ground Source Heat Pumps--Design of Geothermal Systems for Commercial and Institutional Buildings. 1997.

![capture](https://cloud.githubusercontent.com/assets/2985979/12177072/09656064-b530-11e5-8c1b-1bbcab26423e.PNG)

| Soils |  | kg/m3 | W/m-K | m^2/s |
| --- | --- | --- | --- | --- |
| Heavy clay | 15% water | 1922 | 1.558 | 5.914E-07 |
|  | 5% water | 1922 | 1.212 | 6.452E-07 |
| Light clay | 15% water | 1281 | 0.865 | 4.624E-07 |
|  | 5% water | 1281 | 0.692 | 4.839E-07 |
| Heavy sand | 15% water | 1922 | 3.115 | 1.129E-07 |
|  | 5% water | 1922 | 2.596 | 1.344E-06 |
| Light sand | 15% water | 1281 | 1.558 | 8.065E-07 |
|  | 5% water | 1281 | 1.385 | 9.677E-07 |

Table 4, pg. 34.6 ASHRAE Applications Handbook (SI). 2015.

It looks like the soil property values in the Engineering Reference are have a few mistakes. I propose updating it with the above two SI tables. That OK with you @Myoldmopar and @mjwitte?

**Comment by mjwitte** [comment]
Sounds reasonable.

**Comment by Myoldmopar** [comment]
Yeah, that would be great.

**Comment by Myoldmopar** [comment]
Closed via #5401
