### ISSUE TITLE
Construction:InternalSource field Temperature Calculation Requested After Layer Number does not calculate a temperature for output. (CR #8705)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3478]
###### Added on 2012-01-05 08:50 by @mjwitte
--
#### Description
MJW 05 Jan 2012
From user . . .
"Regarding radiant low temperature hydronic systems, I have a question about the temperature calculation defined in the 'Construction:InternalSource' object.

There seems to be no effect of requesting temperature calculations at different layers when the location of the source is not altered at the same time (i.e. it seems that the field 'Temperature Calculation Requested After Layer Number' does not have any effect on the output variable 'Source Location Temperature')."

My reponse after searching source code and testing an exmaple file with advanced report variables turned on just to be sure . . .

"The input field for 'Temperature Calculation Requested After Layer Number' impacts the "User Loc Internal Temp QTF" values reported in the eio output if the Output:Constructions, Constructions; report is requested. But I do not see this input being used to generate an output variable."

So . . .

1.  Is this temperature being calculated somewhere and we just need a setupoutput call?  Should probably include the layer number in the output variable name, e.g. "Surface with Source Temperature after Layer <n>"?

2.  I/O Ref does not document the existing output variable for Construction:InternalSource "Source Location Temperature".  

3.  And this should probably be changed to "Surface with Source Source Location Temperature"  - ooh Source Source doesn't work - what else . . . check with Bereket for suggested renaming.

Inputs: 8705-*
Weather: Chicago

Verification instructions:  There should be a new output variable that give a different result from the exisiting Source Location Temperature output.

--
External Ref: Ticket 5248
Last build tested: `11.12.19 V7.1.0.001`

**Comment by mjwitte** [comment]
Closed via #5810
