### ISSUE TITLE
Documentation - ZoneHVAC:LowTemperatureRadiant:ConstantFlow Pump Flow Rate Schedule Name - clarify this is a multiplier. (CR #8744)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3517]
###### Added on 2012-02-09 13:32 by @mjwitte
--
#### Description
MJW 09 Feb 2012
User was getting no heating or cooling output from ZoneHVAC:LowTemperatureRadiant:ConstantFlow.
Had entered a Pump Flow Rate Schedule which was always 0.000225.  Deleted this schedule reference and then the radiant started working.

ZoneHVAC:LowTemperatureRadiant:ConstantFlow
Pump Flow Rate Schedule Name is describe like this in I/O Ref:

This field modifies the maximum flow rate of water through the radiant system in m3/sec. This
input is ôoptionalö. If the user does not enter a schedule, the flow rate through the radiant
system is assumed to be constant during all hours that it is operating based on the value
entered in the previous input field. Note that the values for this schedule must be between
zero and one.

Based on user's idf, it appears that this schedule is a multiplier times design flow rate, not a schedule of flow rates in m3/s.

A quick check of source code shows it is used as a multiplier times the design flow rate - but the logic isnt' completely clear to me - so needs review.

The IDD notes kind of say this, but not directly:
   A6 , \field Pump Flow Rate Schedule Name
        \note Modifies the Rated Flow Rate of the pump on a time basis
        \note the default is that the pump is ON and runs according to its other
        \note operational requirements specified above.  The schedule is for special
        \note pump operations.
  

I/O ref and IDD notes should say that this schedule is used as a multiplier times the Rated Flow Rate.  (assuming I'm understanding this correctly).

--
External Ref: Ticket 5305
Last build tested: `12.01.31 V7.1.0.003`

**Comment by mjwitte** [comment]
This was addressed at some point already.  I/O Ref field description includes "The values in this schedule are multipliers on the previous field – Rated Flow Rate." and IDD has

```
   A6 , \field Pump Flow Rate Schedule Name
        \note Modifies the Rated Flow Rate of the pump on a time basis
        \note the default is that the pump is ON and runs according to its other
        \note operational requirements specified above.  The schedule is for special
        \note pump operations. Values here are between 0 and 1 and are multipliers
        \note on the previous field (Rated Flow Rate).
```

Closing.
