### ISSUE TITLE
Changing order of window constructions in IDF can change results for windows with spectral data and between-glass shades. (CR #8793)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3566]
## 
#### Description

TH 3/23/2012

Reported from Mehry (COMFEN developer) - 

We just found out that there is a possible bug in Eplus which might affect the COMFEN results. We need help fixing this problem. I have created a simple idf to demonstrate this problem:
1) COMFEN zone with 2 windows on the facade
2) One window with no shading, the other with an in-between venetian blind
3) I created 2 idf files with this model. The only difference is the order of glazing system construction, unshaded and shaded, in the idf file.
4) We get different annual energy results and that's (I believe) due to difference in GLASS SHGC and Glass Visible Transmittance. I checked the Table.csv output file. It is in the exterior fenestration table.
5) I tried in-between shade, I see differences also. Some times the difference is small and we don't see the effect on annual data but in some cases we do.
6) Another test I did was for one window on the facade. I change thed order of shaded, unshaded construction. I see different GLASS SHGC and Glass Visible Transmittance values in the 2 cases but it is not reflected in the annual values, may be because the effect is too small. I guess that's why it was undetected.
7) I tried the case with 2 windows on the facade, one unshaded and the other with exterior blind (instead of in-between blind). I changed the order of construction but did not see any change in glass calculated properties and therefore annual numbers. So may be we conclude that it happens only for in-between blind case?
I remember, a few years ago, when we were still using the spreadsheet version of COMFEN, I reported that when I change the order of windows on the facade, sometimes the total energy values changed. At the time, the Eplus group thought it could be some initialization issue, since we did 4 cases in a loop. In the new COMFEN, we do each case as an independent run. So we thought the problem went away. Although this recent discovery might be something altogether different.

Defect files: 8793 - *

LKL 28 Mar 2012 - Note that this input file does not have the construction layers "like" the example file for between glass blinds.  HOWEVER, even when those are used -- there are still differences.  Very strange.  Almost like it's expecting a certain order -- which doesn't make sense.  When the order is identical, the numbers are identical.  

Adding two more files -- the example between glass with blinds with shaded vs non-shaded different order.  Results are the same!  (Yea...)  

successively removed from the two original files:
frames - still diffs
daylighting - still diffs
spectral data from glass layer -- no diffs.

Begs the question whether this would happen for any shaded construction using spectral data.  I would assume it is unexpected.

TH 4/14/2012
The problem is due to the same glass with full spectral data is used for windows with between-glass shade and windows without between-glass shade. Create two separate glasses for use in two different types of windows would not cause the problem.

The code to address CR 8206 (allow the use of spectral glass for between-glass shade) basically converts the full spectral glass to average spectral glass for windows with between-glass shade. 

LKL 4/22/2012
Tianzhen -- I don't understand your workaround -- can you detect this in the code and provide appropriate severe/fatal?

MJW 15 Aug 2012
What is current status?  From v7.1 featurechanges:
5/16/2012   TH  BugFix  CR8793  Added warning messages when glazing with full spectral data is used for windows with between-glass shade or blind.
## 
#### Workaround

The problem is due to the same glass with full spectral data being used for windows with between-glass shade and windows without between-glass shade. To eliminate the problem, create two separate glass materials, one for each types of window.
## 

Last build tested: `12.03.17 V7.1.0.005`

**Comment by Myoldmopar** [comment]
@hongtz68 Could you take a pass over this issue and see if you feel it has been addressed with the warnings that were added previously, or if it still needs work? If it is complete, could you close the issue?
