### ISSUE TITLE
HVACTemplate:Plant:Chiller produces IPLV warnings because the range of temperatures allowed in the default curve objects is smaller than required for the IPLV calculations. (CR #8818)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3591]
## 
#### Description

MJW 18 Apr 2012
   *\* Warning *\* Chiller:Electric:EIR = MAIN CHILLER:  Integrated Part Load Value (IPLV) cannot be calculated.
   *\*   ~~~   *\*  Check limits in Cooling Capacity Function of Temperature Curve , Curve Type = BIQUADRATIC, Curve Name = MAIN CHILLER RECIPCAPFT
   *\*   ~~~   *\*  Check limits in EIR Function of Temperature Curve, Curve Type = BIQUADRATIC, Curve Name = MAIN CHILLER RECIPEIRFT

MJW 04 Sep 2013
Tried all three chiller types (centrifugal, screw, and recip.) with DisplayAllWarnings, and all of the water cooled chillers produce this warning:
   *\* Warning *\* Chiller:Electric:EIR = MAIN CHILLER:  Integrated Part Load Value (IPLV) calculated is not at the AHRI test condition.
   *\*   ~~~   *\*  Check limits in Cooling Capacity Function of Temperature Curve, Curve Type = BIQUADRATIC, Curve Name = MAIN CHILLER RECIPCAPFT
   *\*   ~~~   *\*  Check limits in EIR Function of Temperature Curve, Curve Type = BIQUADRATIC, Curve Name = MAIN CHILLER RECIPEIRFT

The air cooled centrifugal and recip produce no warnings, but the air cooled screw throws this warning:
   *\* Warning *\* GetElectricEIRChillerInput: Chiller:Electric:EIR="MAIN CHILLER"
   *\*   ~~~   *\* Energy input ratio as a function of temperature curve output is not equal to 1.0 (+ or - 10%) at reference conditions.
   *\*   ~~~   *\* Curve output at reference conditions = 0.871

So, that needs to be addressed also.

MJW 04 Sep 2013
Also, from an e-mail from PC Thomas on 20 Jun 2011:
We have discovered a bug in the HVACTemplate object for chiller. Regardless of what condenser type is selected, when expanded, the CentCapFT refers to (CCAPT3) which is the equivalent of HERM-CENT-CAP-FT in DOE-2.1E.

In our opinion, we believed that this is incorrect because cooling capacity of air-cooled is expressed as a function of ambient drybulb as opposed to Entering Condenser Water Temperature which is the case for water-cooled chiller.

Back in DOE2.1E, CapFT has been expressed of type BI-QUADRATIC-T. This brings us to the next question:
can the CoeffConv utility allows us to convert BI-QUADRATIC-T curve from DOE2 to EnergyPlus?

We have attached the three curves for a generic air-cooled chiller for your reference. 

$ Air-cooled condenser curves; 200 ton centrifugal                              ERV     52
$LIBRARY-ENTRY CentChlrAirCoolCap-fCHW&OAT     CURVE-FIT       Chiller          ERV     53
  TYPE=BI-QUADRATIC-T  INPUT-TYPE=COEFFICIENTS                                  ERV     54
  COEF=(-1.38147235,  0.10363493,  -0.00103756,                                 ERV     55
         0.00368918, -0.00006936,   0.00002531)  ..                             ERV     56
$LIBRARY-ENTRY CentChlrAirCoolEIR-fCHW&OAT     CURVE-FIT       Chiller          ERV     57
  TYPE=BI-QUADRATIC-T  INPUT-TYPE=COEFFICIENTS                                  ERV     58
  COEF=(-0.40465072,  0.03093917, -0.00029274,                                  ERV     59
         0.00840319,  0.00002946, -0.00010866)  ..                              ERV     60
$LIBRARY-ENTRY CentChlrAirCoolEIR-fPLR         CURVE-FIT       Chiller          ERV     61
  TYPE=QUADRATIC  INPUT-TYPE=COEFFICIENTS                                       ERV     62
  COEF=( 0.24258000,  0.41468000,  0.34273973)  ..                              ERV     63
## 

Last build tested: `12.04.17 V7.1.0.008`

**Comment by jmarrec** [comment]
I've used the chiller "ElectricEIRChiller York YT 1758kW/6.28COP/Vanes" from the `chillers.idf` DataSet.

I'm getting this warning :

```
** Warning ** GetElectricEIRChillerInput: Chiller:Electric:EIR="CH-1"
**   ~~~   ** Energy input ratio as a function of temperature curve output is not equal to 1.0 (+ or - 10%) at reference conditions.
**   ~~~   ** Curve output at reference conditions = 0.862
```

**Comment by mjwitte** [comment]
@jmarrec Do your chiller reference temperatures match what is in the dataset file?  The reference temperatures vary quite a bit in the dataset.

```
  Chiller:Electric:EIR,
    ElectricEIRChiller York YT 1758kW/6.28COP/Vanes,  !- Name
    1758300,                 !- Reference Capacity {W}
    6.28,                    !- Reference COP {W/W}
    6.67,                    !- Reference Leaving Chilled Water Temperature {C}
    29.44,                   !- Reference Entering Condenser Fluid Temperature {C}
    0.07571,                 !- Reference Chilled Water Flow Rate {m3/s}
    0.09464,                 !- Reference Condenser Fluid Flow Rate {m3/s}
    ElectricEIRChiller York YT 1758kW/6.28COP/Vanes CAPFT,  !- Cooling Capacity Function of Temperature Curve Name
    ElectricEIRChiller York YT 1758kW/6.28COP/Vanes EIRFT,  !- Electric Input to Cooling Output Ratio Function of Temperature Curve Name
    ElectricEIRChiller York YT 1758kW/6.28COP/Vanes EIRFPLR,  !- Electric Input to Cooling Output Ratio Function of Part Load Ratio Curve Name
```

**Comment by jmarrec** [comment]
I've literally just used the Chiller:Electric:EIR and its three curves from the dataset (except that I filled the nodes connections)

**Comment by jmarrec** [comment]
Have you made any progress on this? Any tips on how to correct it quickly?
Thanks

**Comment by mjwitte** [comment]
One option would be to plot the curve and find the correct reference temperatures that results in a curve value of 1.0.

**Comment by jmarrec** [comment]
@myoldmopar instead of wontfix, we could update all chiller reference temperatures to match the curves that the chiller uses.
What do you think?

**Comment by Myoldmopar** [comment]
I think that would be great, and to be honest, this is one issue that we definitely went back and forth on keeping open or marking wont-fix.  If you want to take this on as one of your defects, it would be OK with me.
