### ISSUE TITLE
In Engineering Ref, Hot Water Baseboard Heater with Radiation and Convection, Simulation and Control, the equation for Ta,out is old. (CR #8852)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3625]
## 
#### Description

MJW 08 May 2012
In Engineering Ref, Hot Water Baseboard Heater with Radiation and Convection, Simulation and Control, the equation for Ta,out is old.

This change was made in the model
9/1/2010, DHK, BugFix, CR8080/8126, Added a linear equation to estimate air mass flow rate as it varies along variation of baseboard heating capacity

But the docs were not changed to match.  In current source, see code starting at line 902 of BaseboardRadiatorWater.f90.

Current equation is
Ta, out = q/(2 mdotwater \* Cp,a)+Ta,in

Based on the code, I think it should be
Ta,out = Q/(mdotAIR \* Cp,a)+Ta,in

where mdotAIR = 0.0062 + 2.75e-05\* Q
## 

External Ref: Ticket 5798, CR8080/8126
Last build tested: `12.04.25 V7.1.0.009`

**Comment by RKStrand** [comment]
@mjwitte @axelstudios I am currently looking at this issue.  Based on the the Version 8.5.0 documentation, I feel that this issue has already been resolved?  In the current documentation (page 955, Section 15.4 Baseboard Heaters), I do not see the "current equation" of: 
Ta, out = q/(2 mdotwater \* Cp,a)+Ta,in
Rather, I see the docs matching the code.  See three lines after Equation (15.654) for an unnumbered equation that matches the mdotAIR equation shown above.  This then is used in Equation (15.661) exactly as shown above in the Ta,out equation.
So, is this already fixed or am I missed something glaringly obvious?

**Comment by mjwitte** [comment]
@RKStrand FYI, all of the issues originated by @axelstudios are imports from StarTeam, so they've been around a while.  Here is what it was in the v7.1 docs when this issues was first posted.
![image](https://cloud.githubusercontent.com/assets/4991075/15615622/1104426a-2405-11e6-9ce0-34fa3d19e964.png)

So, looks like this was fixed, probably when some other changes were made to the baseboard model.  Yes, here in #5214 and some other changes here in #5419 .  So, closing this.

**Comment by mjwitte** [comment]
Unless you want to reopen this and clean up the formatting in the current section.

**Comment by RKStrand** [comment]
@mjwitte Well, I'm up for it if there is clean up that needs to be done.  I need to package together a variety of doc mods to make an equivalent low complexity bug.  So, if you want to reopen this and give me a task, that sounds good to me.

**Comment by Myoldmopar** [comment]
Closed via #6318
