### ISSUE TITLE
The description in the Input Ouput Reference for the Lights object needs to be revised to update the table that recommends values for fractional splits.  ASHRAE Research Project 1282 generated new data for this. (CR #8877)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3650]
###### Added on 2012-06-08 09:57 by @mjwitte
--
#### Description
MJW 08 Jun 2012
From user . . .
Q2) How does the table in the io ref

Table 13. Approximate values of Return Air Fraction, Fraction Radiant and Fraction Visible for overhead fluorescent lighting for different luminaire configurations. These values assume that no light heat goes into an adjacent zone. Source: Lighting Handbook: Reference & Application, 8th Edition, Illuminating Engineering Society of North America, New York, 1993, p. 355.

compare to

Table 3 in chapter 18.6 2009 ASHRAE HOF  (this table is attached to the CR and in GARD's Defect\...8877 folder)

--------------------------------
The ASHRAE table references a paper "Fisher and Chantrasrisalai 2006" which Dan Fisher acknowledges to be one of his.  Dan has graciously offered to update the I/O Ref table.

duplicate of  8903

[BG 9-24-2012] Made and effort to do this using the full RP report.  However, could not reconcile the numbers in the time available.  The fractions appear to add up to more than 1.0 and the ranges are somewhat difficult to work with in a document table.

--
External Ref: Ticket 5960
Last build tested: `12.05.31 V7.1.0.012-release`

**Comment by mjwitte** [comment]
Perhaps a better source is available now?

**Comment by JasonGlazer** [comment]
The ASHRAE 1282-RP report has a final table that is what is used in the HOF:

![1282-table12](https://cloud.githubusercontent.com/assets/2582150/12266009/316305b0-b906-11e5-8db0-6a6f605b160c.png)

Which does not break out to return air fraction and fraction convected. But the detailed tables from the same report do include it. Here is one for recessed fluorescent.

![1282-table4](https://cloud.githubusercontent.com/assets/2582150/12266113/ee113b32-b906-11e5-8f72-69743fa0a67b.png)

Similar tables for downlights, non inceiling luminaires, air flow rates, return air configurations, floor finishes, supply air temperatures, room air temperatures. My instinct is that we should include all of the tables to give users the best information about the values to use.

**Comment by mjwitte** [comment]
That's fine, but these values don't translate directly into EnergyPlus inputs.

**Comment by JasonGlazer** [comment]
Here is what I am proposing:

> Approximate values of Return Air Fraction, Fraction Radiant and Fraction Visible are given in 
> Table 14 for overhead fluorescent lighting for a variety of luminaire configurations. The data 
> is based on ASHRAE 1282-RP "Lighting Heat Gain Distribution in Buildings" by Daniel E. 
> Fisher and Chanvit Chantrasrisalai.

and replace the existing table with the following table:

![newlightingtable](https://cloud.githubusercontent.com/assets/2582150/12276644/83445308-b93c-11e5-9dc9-58592eeba2ef.png)

And delete Figure 51 titled "Overhead luminaire configurations" since they no longer correspond with table.

**Comment by Myoldmopar** [comment]
Closed via #5413
