### ISSUE TITLE
The Appendix G post processor can have problems if not all the tabular output files have the same content in terms of tables.  If one of the models runs quite differently and some tables are not created, the post processor will not work. (CR #8885)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3658]
###### Added on 2012-06-19 14:22 by @JasonGlazer
--
#### Description
Glazer - 2012-June 19

Help ticked 6008

The four files were automatically generated but because zone cooling was not needed in a zone for a certain orientation the tables were not identical. The averaging process made a mess or the result file.

See 

8885-*

--
Last build tested: `12.05.31 V7.1.0.012-release`

**Comment by JasonGlazer** [comment]
Produces same problem with most recent version of AppGPostProcessor
