### ISSUE TITLE
The I/O reference description of the QuadraticLinear curve object has errors. The equation itself as shown has several problems.  First, it has too many terms (no x^3 term in this equation).  Second, the "output" should be something lik... (CR #8908)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3681]
###### Added on 2012-07-18 10:41 by @RKStrand
--
#### Description
The equation itself as shown has several problems.  First, it has too many terms (no x^3 term in this equation).  Second, the "output" should be something like "z" rather than "y" since "y" is one of the terms on the right hand side of the equation.

--
Last build tested: `12.07.18 V7.2.0.001`

**Comment by mjwitte** [comment]
Closed via #5352
