### ISSUE TITLE
Surface out of bounds issues can occur with internal mass surfaces under some situations - possibly due to thin metal layer in the construction. (CR #8933)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3706]
## 
#### Description

From ticket:
2) When I run the model with 2010 weather, however, it crashes with the error message below. The crash occurs when the heating system is OFF and there is no cooling system for that zone

*\* Severe *\* Temperature (low) out of bounds [-355.06] for zone="EASTENDRMS", for surface="INTERNALMASS_EASTENDRMS"
*\* ~~~ *\* Environment=EASTLANSINGMI, at Simulation time=08/05 18:30 - 18:31
*\* ~~~ *\* Zone="EASTENDRMS", Diagnostic Details:
*\* ~~~ *\* ...Internal Heat Gain [11.000] W/m2
*\* ~~~ *\* ...Infiltration/Ventilation [7.623E-002] m3/s
*\* ~~~ *\* ...Mixing/Cross Mixing [0.000] m3/s
*\* ~~~ *\* ...Zone is part of HVAC controlled system.

LKL 02 Jul 2012 (ticket reply)
Well, I know what the problem is but I have no work around.

The construction for this internal mass starts cycling between odd temperatures (+200, -400). I tried adding multiple internal mass objects of lesser area, that did not help.

I tried a different material in the construction (I think it was the same as construction 15 -- it behaved better). As in, it converged on a reasonable temperature.

User reply 03 Jul 2012
Got the file to run
1. I revised the definition of the internal mass construction so that it had two materials
2. Reversed the materials in the adjacent ôprevious reversedö material
3. Revised the thickness of both materials
4. IDF attached
After thinking about it, I realized that the thickness change affected more walls than I intended, but since itÆs not a ôrealö building at this point (ItÆ s an example for a paper), I left it as is.

MJW 17 Aug 2012
The user's revised  file still has temp out of bounds, but it does complete:
   ************\*  *\* Severe  *\* Temperature (low) out of bounds for zone=EASTENDRMS for surface=INTERNALMASS_EASTENDRMS
   ************\*  *\*   ~~~   *\*   This error occurred 219 total times;
   ************\*  *\*   ~~~   *\*   during Warmup 0 times;
   ************\*  *\*   ~~~   *\*   during Sizing 0 times.
   ************\*  *\*   ~~~   *\*   Max=-127.855641 C  Min=-165.674808 C

Assigning to RKS per conf call discussion on 8/15.

Inputs:  8933-*
Weather: 8933-USA_MI_East_Lansing_589331_2010_amy.epw
## 

External Ref: Ticket 6125
Last build tested: `12.07.18 V7.2.0.001`

**Comment by RKStrand** [comment]
@mjwitte Well, this is still crashing, but there are no think metal layers in this file.  There are a lot of other errors that will take some time to sort out.  At this point, I'm not sure what specifically is causing the crash.
