### ISSUE TITLE
Piping System programming code re-calculates solar data that should already be available as weather data within E+.  The model should be reprogrammed to use solar data already calculated elsewhere. (CR #8977)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3750]
## 
#### Description

The piping system code re-calculates a number of solar data that should already be available as weather data within E+.  The code is in the EvaluateGroundSurfaceTemperature routine (~ line 4255 at the time of this writing).

The solar data calculations should be removed and replaced with lookups from DataEnvironment...or wherever the data is held.  

There will most likely be small diffs due to different calculation algorithms, but they should be insignificant in overall effect.

_Addendum_: 2013-01-17 ESL:
Some other minor improvements could be made to the piping system module along with this:
1) Ensure report variables are properly formatted: new Trench Ground Heat Exchanger mass flow rate should be capitalized
2) Force an update of the basement cell temperatures...wouldn't make a difference for calculations, but better for reporting than just leaving the initial gradient.  Could use either the actual basement temperature...or an initial value of zero to be clear.
3) Change code/IDD moisture values so they are percent and not fraction
4) Verify time units going into the farfield temperature routine...they may be wrong
5) In the IDD, radial mesh count shouldn't have a max value
6) Fix an axial problem: Either force >=2 axial cells in the IDD, or fix the code to allow a single axial cell.
## 

Last build tested: `12.09.05 V7.2.0.004`

**Comment by mjwitte** [comment]
@mitchute @Myoldmopar Not sure if anything in this issue is still relevant.
