### ISSUE TITLE
Suggestion to improve sizing algorithms to be able to account for the interactions between multiple HVAC systems where one system may counteract the zone's conditioning needs and increase loads (such as non-neutral DOAS). (CR #8997)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3770]
###### Added on 2012-09-25 09:45 by Brent Griffith
--
#### Description
Follow on from CR 8910, where a non-neutral, dedicated outdoor air system can add significant loads that are not included in sizing calculations.   

There is a need to improve the sizing routines to handle situations where there is multiple types of zone equipment and some are not actually conditioning the zone but adding to the zone loads.  Currently, only neutral SAT DOAS systems can be modeled well using autosizing.  If a DOAS is allowed to operate at cold or hot temperatures, and it is sequenced #1, then it can easily happen that the equipment #2 is not sized large enough to handle the loads from the DOAS.  

This may need to become an enhancement list item if it turns out to be a large effort.

--
#### Fix
The proposed solution is discussed in C:\EnergyPlus-Dev\Collaborative Developments\Equipment Sizing Issues/ Pre-NFP_Autosizing_CoilPeak_AssigningLoads_DOA_FanHt.docx

--
Last build tested: `12.09.20 V7.2.0.005`

**Comment by mjwitte** [comment]
The primary goal of this issue was addressed via #5002.  Closing.
