### ISSUE TITLE
EP-Compare shows some botched characters on non-Windows environment.  The root of the problem is that the strings are hard-coded with the \r\n code.  This is Windows lingo for newline.  For other OSs, this shows up as a missing symbol. (CR #9017)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3790]
## 
#### Description

[ESL 2012-10-09] EP-Compare shows some botched characters on non-Windows environment.  The root of the problem is that the strings are hard-coded with the \r\n code.  This is Windows lingo for newline.  For other OSs, this shows up as a missing symbol.

grep reveals there are two instances of this character combo:
MainWindow.rbfrm:76:         InitialValue    =   "test value\r\n"
ManageFilesWindow.rbfrm:247:      Text            =   "The top file in the list is used as the baseline file. Drag files to change order.\r\n"
## 
#### Fix

[ESL 2012-10-09] There are two possible fixes.  One is that the label strings do not need a line termination character.  The second changes the \r\n to a portable string.  From a quick search, it appears realbasic contains a EndOfLine character which I would expect to be OS-portable.  If that won't work, I think the label needs to be set at run-time so OS checking can be done.
## 

Last build tested: `12.10.05 V7.2.0.006-Release`

**Comment by Myoldmopar** [comment]
@JasonGlazer I couldn't find the source for this in the repo.  Could you post your latest version of the source and then one of us can try to address this tiny thing?
