### ISSUE TITLE
The AirLoopHVAC Heat Recovery Bypass Status report does not correspond to the heat exchanger operation. (CR #9030)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3803]
###### Added on 2012-10-24 12:23 by @rraustad
--
#### Description
I need someone who will actually review the results. Pay close attention to the AirloopHVAC report variables Outdoor Air Economizer Status, Heat Recovery Bypass Status, and Heat Recovery Heating Coil Was Active Status (new) reports. Compare these to the heat exchanger bypass flow (HX is bypassed) and heating/cooling rate (HX not bypassed). Also note the supply air temp and set points at the heating coil outlet node and if heating coil is active (or if it would be active if heat recovery was disabled). This one is tricky.

User file shows discrepancies in the output.

The air loop economizer flag seems to be working, however, the supply air bypass flow report does not line up with the heat recovery bypass status report.

  Output:Variable,PSZ_1:4_HeatRecovery,Heat Recovery Supply Air Bypass Mass Flow,detailed;
 Output:Variable,PSZ_1:4,AirLoopHVAC Outdoor Air Economizer Status,detailed;
 Output:Variable,PSZ_1:4,AirLoopHVAC Heat Recovery Bypass Status,detailed;

  ! turn on OA heat exchanger any time heating is active and user requests the special bypass control
  IF(OAController(OAControllerNum)%HeatRecoveryBypassControlType == BypassWhenOAFlowGreaterThanMinimum)THEN
    IF(AirLoopControlInfo(AirLoopNum)%HeatingActiveFlag)
      AirLoopControlInfo(AirLoopNum)%HeatRecoveryBypass = .FALSE.
  END IF

This code should have also reset the report variable to 0 as this:
  ! turn on OA heat exchanger any time heating is active and user requests the special bypass control
  IF(OAController(OAControllerNum)%HeatRecoveryBypassControlType == BypassWhenOAFlowGreaterThanMinimum)THEN
    IF(AirLoopControlInfo(AirLoopNum)%HeatingActiveFlag)THEN
      AirLoopControlInfo(AirLoopNum)%HeatRecoveryBypass = .FALSE.
      OAController(OAControllerNum)%HeatRecoveryBypassStatus = 0
    END IF
  END IF

Defect file: 9030*
Weather: attached ... LOCATION,RIYADH,-,SAU,IWEC Data,404380,24.70,46.80,3.0,612.0

--
#### Workaround
This status flag was not getting set to 0 when the air loop heating coil was active. Use the Air Loop Heating Coil* report variables to indicate when this flag should have been set to 0.

--
External Ref: Ticket 6543
Addressed in `12.11.25 V8.0.0.001` by @rraustad
Last build tested: `12.10.05 V7.2.0.006-Release`

**Comment by mjwitte** [comment]
Tested with 7.2.0 and 8.3.0 and verified that the bypass mass flow rate and bypass status are now consistent with each other.
