### ISSUE TITLE
DX heat pumps autosize the DX heating coil to be equal to the DX cooling coil capcity. Allow a sizing factor to be used to properly size the DX heating coil. (CR #9063)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3835]
###### Added on 2012-11-14 09:05 by @rraustad
--
#### Description
[14 Nov 2012 RAR]

Sizing Committee suggested that a sizing factor be allowed for DX heat pumps.

DX heat pumps autosize the DX heating coil to be equal to the DX cooling coil capcity. Allow a sizing factor to be used to properly size the DX heating coil.
The VRF heating coil model inputs allow a sizing factor to be used. Expand this methodology to other DX heating coils.

As a reminder for futuer work, the DX heat pump is sized to meet the cooling load which can severely undersize the heat pump for colder climates.

--
External Ref: Sizing Committee
Last build tested: `12.10.05 V7.2.0.006-Release`

**Comment by mjwitte** [comment]
@rraustad As of v8.3.0, has scalable sizing been implemented everywhere now for dx heating coils?  If so, please close this issue.

**Comment by Myoldmopar** [comment]
@rraustad Can you confirm whether this has been addressed fully or not?  If so, can you close this?

**Comment by rraustad** [comment]
This was a reminder to address all DX systems to allow a heating coil sizing ratio. This was never addressed. Since UnitarySystem (and VRF) does have this input, this can be closed?

```
AirLoopHVAC:UnitarySystem,
  N1 , \field DX Heating Coil Sizing Ratio
   \type real
   \default 1.0
   \minimum> 0
   \note Used to adjust heat pump heating capacity with respect to DX cooling capacity
   \note used only for heat pump configurations (i.e., a cooling and DX heating coil is used).
```
