### ISSUE TITLE
Syncronize Ref Bldg models with latest version (CR #9077)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3849]
###### Added on 2012-11-30 15:52 by Brent Griffith
--
#### Description
NREL updated the DOE Commercial Reference Building models.  A subset have been included in E+ test suite and example files.  With the recent update, there is now a need to re-syncronize the models to reflect the changes that have been made. 

The DOE Commercial Reference Buildings website has some updates to include files compatible with the most recent version of EnergyPlus (7.2):

http://www1.eere.energy.gov/buildings/commercial/ref_buildings.html

A few other changes were made to the models, as well, as listed here:

http://apps1.eere.energy.gov/buildings/publications/pdfs/commercial_initiative/refbldgs_changes_v40tov70.pdf

--
Last build tested: `12.11.25 V8.0.0.001`

**Comment by Myoldmopar** [comment]
@EnergyArchmage Worth pursuing?

**Comment by EnergyArchmage** [comment]
I think it is a good suggestion, but more of a luxury to pursue given limited resources. I will lower priority tag.  There are work-arounds in the old files that can now be removed to improve the files.  But there is also value in leaving them unmodified for regression testing across versions, so close it if you want.
