### ISSUE TITLE
Coil Performance outputs for sizing are not documented in Output Details document. (CR #9138)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3909]
###### Added on 2013-02-19 11:54 by @lklawrie
--
#### Description
See CR9136, CR9137 for further details.

--
External Ref: ticket 7077
Last build tested: `13.02.09 V8.0.0.004`

**Comment by mjwitte** [comment]
Not really clear what this was going for.  A sample line has been added to OutputDetailsAndExamples.

**Comment by Myoldmopar** [comment]
Closed via #5402
