### ISSUE TITLE
Remove string compares from CalcSystemEnergyUse (CR #9158)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3929]
###### Added on 2013-03-01 09:42 by @JasonGlazer
--
#### Description
2013-March-01 Glazer

Found that string compares in CalcSystemEnergyUse were taking up a signficant time. Since OSU/Edwin is going to be working on this code, you may want to wait until that is checked in to remove the string compares. You said in Feb 27 email :

It's not quite as straightforward as I would like it to be
to get rid of the strings and replace with numeric equivalent.

Already found that OutdoorAir:Mixer and
AirLoopHVAC:OutdoorAirSystem are assigned the same
OAMixer_Num as the component integer equivalent.

(not to mention that the two equipments aren't unique in
assignment across the board)

LKL 9 Oct 2013
Edwin, another for you.

--
Last build tested: `13.02.09 V8.0.0.004`

**Comment by Myoldmopar** [comment]
This was tuned, it appears as per @DeadParrot based on the wording, during some of the performance improvements.  Here's the comment I mean: https://github.com/NREL/EnergyPlus/blob/7d148e7b460747bf462f17c45102329e1c07a9b8/src/EnergyPlus/SystemReports.cc#L3336.  I'll close this as it appears it's already fixed.
