### ISSUE TITLE
EPDrawGUI does not run on MacOS. (CR #9193)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3964]
## 
#### Description

2013-April Glazer
When Eric Bonnema tries EPDrawGUI he gets the error. See attached screen shot
## 

Last build tested: `13.04.03 V8.0.0.007`

**Comment by Myoldmopar** [comment]
@JasonGlazer @kbenne Can you confirm this is still a defect?

**Comment by JasonGlazer** [comment]
It would be easier to answer for sure if I saw the screen shot that was referenced. Maybe @mjwitte might be able to find it and add it to the issue?

**Comment by Myoldmopar** [comment]
Hmmm, I have a feeling deep in my gut that the screenshot is long gone.  But maybe not...

I assumed it was just:

``` C++
TEST( Issue, 3964 ) {
  bool success = OpenAppOnPlatform( "EPDraw", "MacOS" );
  if ( success ) {
    issues.close( 3964 );
  } else {
    issues.comment ( 3964, "Still a problem" );
  }
}
```

**Comment by mjwitte** [comment]
@JasonGlazer Looks like you posted the original CR on 2013-04-08, so maybe you have an e-mail with the screenshot?

**Comment by JasonGlazer** [comment]
I did find an email from before that date related to EPDrawGUI
![screen shot 2013-04-04 at 11 42 36 am-1](https://cloud.githubusercontent.com/assets/2582150/8086060/1b02ed1e-0f59-11e5-8f35-d8b9fe6190dc.png)

**Comment by JasonGlazer** [comment]
I don't remember working on this, unless it was an installer issue that @kbenne fixed, I would assume it still broken.

**Comment by Myoldmopar** [comment]
OK, yeah, I just noticed it and remembered that you guys (@kbenne) _had_ addressed some Mac installer/real-basic issues not too long ago.

**Comment by kbenne** [comment]
Just checked.  It is still broken as it sits in build support and presumably that is the reason it is not installed in the package.  When I try to launch it I don't get the error dialog, I get nothing..

**Comment by Myoldmopar** [comment]
Thanks @kbenne, that's what I was looking for.  I'll be done with this now and maybe it can be addressed.  Although, if it hasn't been included in the package in a while, and there isn't anyone demanding it, maybe we pull it out of the package and just make it available elsewhere?  

That's probably a bigger discussion...............for not here.

**Comment by JasonGlazer** [comment]
I haven't touched that code in a while but my guess is that it is not looking properly for the MacOS equivalent to the EPlusDrw.dll.

**Comment by JasonGlazer** [comment]
@Myoldmopar @kbenne @mjwitte @mbadams5 

I have been looking into this some and realize that I will probably need an updated version of the EPDraw library for the latest version of EnergyPlus on MacOS. The library is called libepdraw.dylib and the one I have is five years old. I guess it is possible that nothing has changed related to drawing DXF files in the last five years but if a newer one was available that would be better. It is also possible that we will need to tweak that to make it work the GUI. I did not find that the Windows build creates the EPlusDraw.dll anywhere but maybe I am not enabling all the options. Do any of you know where to find the source and how to build libepdraw.dylib?
