### ISSUE TITLE
EnergyPlus plant loop variable speed pumps should allow min flow sizing using absolute flow values or "fraction-of-max" values (CR #9209)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3980]
###### Added on 2013-04-29 15:10 by @mjwitte
--
#### Description
MJW 29 Apr 2013
CR9205 revealed that HeaderedPumps:VariableSpeed allows the user to enter a fraction of full flow as the min flow rate, but Pump:VariableSpeed requires a flow rate (m3/s) for the min flow specification.  Would be nice to allow either min fraction or min flow in both pump types.

2013-09-23 ESL:
This has been implemented and tested, but to avoid messing up docs and IDD changes at the last minute it was not pushed in.  Just need to write docs and push it in.

--
External Ref: CR9205
Last build tested: `13.04.15 V8.0.0.007-Release`

**Comment by Myoldmopar** [comment]
Closed via #5281
