### ISSUE TITLE
Branch pumps show problems with autosizing. They do not track the flow rate size of a companion device on the branch. (CR #9215)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3986]
###### Added on 2013-05-06 12:17 by @mjwitte
--
#### Description
From user ticket:
I have noticed a possible (I've been wrong before!) issue with the
autosizing of branch pumps:
When using the HVACTemplate for Chilled Water Loop,
If you use 'PumpPerChiller' or 'PumpPerTower' you get a pump that is
half the size it should be.

I have two chillers each with 0.5 sizing factor, and two Cooling
Towers with the same sizing factor.

In the attached file, when I use PumpPerChiller, I get two branch
pumps with a flow rate of 87.6 GPM each and one 350.5 GPM secondary pump

When I only change 'PumpPerChiller' to 'TwoHeaderedPumps' I get a
headered primary pump of 350.5 total GPM and single secondary pump of 350.5 gpm

In all of the above the reference evaporator flow rate for each
chiller was 175.3 gpm.

MJW 06 May 2013
Several test files based on the user file (all HVACTemplate), 1 chiller, 2 chillers 50-50, 2 chillers 25-75, 3 chillers 25-30-70.  The branch pumps appear to be getting sized to the companion chiller flow divided by the number of parallel pumps (chillers).  So, the 1 chiller with branch pump gets sized OK, but all of the others do not.  Also, added one primary-only case to be sure that's not a factor (the others are all primary-secondary.)

Inputs: 9215-*
Weather: None - design days

Verification instructions:  After fix, check the eio output.  The autosized CHW BRANCH PUMP flow rates should match their respective chiller autosized Reference Chilled Water Flow Rate.

--
External Ref: Ticket 7343
Last build tested: `13.04.30 V8.0.0.008 - rerelease`

**Comment by EnergyArchmage** [comment]
I have seen this in the test suite and noticed that my curren rewrite of plant sizings corrected a sizing problem.  This should be fixed by plant coincident sizing feature
