### ISSUE TITLE
The program was improved to properly size reheat coils for VAV air terminal units with normal damper heating action. (CR #9216)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3987]
###### Added on 2013-05-06 13:13 by @mjwitte
--
#### Description
[BG 10-15-2013] check in source code change on 10/14.  Reverted the initial changes related to removing ReheatMult term, then addressed CR9216 in a different way.
1. Split ReheatMult into two separate terms ReheatAirFlowMult and ReheatLoadMult.  For Reverse action dampers, the two are the same (as before).  For Normal action, ReheatLoadMult = 1.0. This allows selectively removing the term on loads while retaining it on flows.

2. correct/revise the logic that sets value for ReheatMult.
        2.a correct mistake for Reverse with reheat max limit
        2.b add logical cases for Normal action.

MJW 11 Oct 2013
There are some problems with the fix.
For reverse action dampers (without a reheat airflow limit specified), the reheat coils are too small.  I wasn't expecting these to change at all.  See new test files 
9216-ExerciseHVAC2B-Solution-810-004-exp (and 006), the reheat coils are way smaller than before and there are unmet loads (e.g. 01/07 in the hourly output).
Also, in the original test files which have a central heating coil, the coil max water flow rate doesn't match the controller max water flow rate (this may be due to the other heating coil sizing CR):
 Component Sizing Information, Coil:Heating:Water, AIR LOOP - 1|HC2T-1, Design Size Maximum Water Flow Rate [m3/s], 6.48436E-004
 Component Sizing Information, Controller:WaterCoil, AIR LOOP - 1|HC2T-1, Maximum Actuated Flow [m3/s], 9.73822E-004

MJW 06 May 2013
1.  User complained about reheat coil sizing - large water-side deltaT and seemingly random coil UA values vs coil design load.  For example, the first two coils from the user's file:

THERMAL ZONE - 1 - 1 (WEST)|VAVR-1, Reheat Coil Sizing Air Volume Flow Rate [m3/s], 0.21804
THERMAL ZONE - 1 - 1 (WEST)|VAVR-1(11)|HEATINGCOILWATERAUTOSIZEUFACT, Design Coil Load [W], 3672.57870
Maximum Water Flow Rate [m3/s], 5.26483E-005, U-Factor Times Area Value [W/K], 181.79217

THERMAL ZONE - 1 - 2 (NORTH)|VAVR-1, Reheat Coil Sizing Air Volume Flow Rate [m3/s], 0.21804
THERMAL ZONE - 1 - 2 (NORTH)|VAVR-1(4)|HEATINGCOILWATERAUTOSIZEUFACT, Design Coil Load [W], 3672.58748
Maximum Water Flow Rate [m3/s], 5.26484E-005, U-Factor Times Area Value [W/K], 121.88877

Air flow rate, design coil load, and max water flow rate are nearly identical for these two coils but the UA for one is 182 and the other is 122?

2.  Turns out in the code, the coil load is being adjusted prior to the UA calculation by a reheat coil sizing multiplier which is not reported. For this file (normal action damper), the multiplier on UA is the terminal unit max air flow rate (the cooling max airflow) divided by the reheat sizing airflow rate. So, there is an intentional scaling happening in the UA values, and it's related to the max flow rates of the zone terminal units. The design coil load is reported prior to this scaling, the reported UA includes the impact of this scaling. See HVACWaterCoilComponent.f90.

Starting at line 2922, DesMassFlow, DesCoilLoad, and DesWaterVolFlow all get scaled by TermUnitSizing(CurZoneEqNum)%ReheatMult.  This appears to be after the design coil load and max water flow rate have been reported (ReportSizingOutput), but before the UA calculations are done.  The logic is convoluted with all the different blocks for different coil locations, so I'm not sure if these adjusted numbers end up in the coil data structure or not.

3.  So, where does TermUnitSizing(CurZoneEqNum)%ReheatMult get set?  In HVACSingleDuctSystem.f90, starting at line 2016.  First it comes up with the air flow rate to use for the reheat coil sizing.  The logic here seems reasonable at first glance - but should be reviewed carefully.  The section seems to be taking into account reverse/normal damper and if there is a limit on MaxAirVolFlowRateDuringReheat.

Then starting at line 2048, there is a section that calculates ReheatMult which seems to do this all over again, but gets it wrong for normal action because it assumes full terminal unit supply flow for that case (seems like there's a missing IF).  But it's not clear that ReheatMult should even be used?  Confused.

4.  See Workaround (on Solution tab of this CR).

5. There are other things that don't make sense here.  How can these two zones have the same design coil load and reheat coil sizing airflow rates when the terminal unit flow rates differ by almost 1.5x?  Is this just being reported too early before the adjustments?  Does the design coil load include the impact of the supply air temp upstream of the reheat coil?

6.  Conclusions:
a.  ReheatMult was added by FB on 4/27/2012  as part of CR8807 work (which had many checkins).  Seems like this section of code needs a third case to use minflow if the damper is normal action.
b.  Some other changes related to CR8807 were checked in by BG on 5/14/2012  This added and moved some of the airflow calcs related to reheat coil sizing, but I can't tell if this cause any problems or not.

So, assigning this to Fred for starters.

Inputs:  9216-*, also a spreadsheet showing some of the values as the user reported it and other info
Weather: None, design days only

Verification instructions:  Not completely sure what the right answer is here.  Doesn't seem right that two 

[16Sep2013 FB]

The ReheatMult was intended only to apply to reverse action terminal unit dampers. For "normal" action,
the ReheatMult should be 1. The logic for setting the ReheatMult was messed up; "normal" was treated
as reverse action with the maximum cooling air flow rate as the max. The reason the 2 UAs were different
for virtually the same design heating load was that the design cooling loads were different, and hence the
max cooling air flow rate. Thus the ReheatMults were different. Which is should not have happened.

Why is there a ReheatMult? I believe the logic was the following. For reheat coils, we were sizing the
heating coils (the UA and water flow rate) on the design zone heating loads. But for reverse action, the
actual air flow rate at maximum heating would be the air flow rate when the damper was fully open or
open to the heating flow max. That is, ithe air flow rate would not be the design heating flow rate.

So in calculating the coil UA, it was thought that it would be useful to use the actual max flow rate; thus
the ReheatMult was calculated and used to multiply the air flow rate (but not the load or the water
flow rate) for the reheat coil UA calculation. This seemed to work, but at some point some cases
occured in which the UA calc failed. In a fairly hasty decision, it (I) decided to apply the reheat mult
to the other inputs for the UA calc: HW flow rate and design heating load. Since all the inputs were now
compatible, the UA calc failures disappeared. However I failed to realize that I was then ending up with
a too large UA which would affect the HW outlet temps (note the modified flows and load are only used
for the UA calculation; the HW design flow was never changed by ReheatMult).

So one question is, do we need ReheatMult at all? The answer is, I don't really know. What I do remember is
that the UA must be calculated using compatible HW and air flow rates, and compatible design load. Since UA
more or less scales with the design load (assuming fixed design inlet and outlet temperatures) it seems
that we should leave the UA calculation alone (no ReatMult) if we are picking a good design load. The only
effect of higher air flow rates would be that the zone air inlet tempeature would be lower than the design
inlet temperature, which seems acceptable.

The final issue that needs to be addressed, which we have screwed up in the past, is dealing with low or
zero zone design heating loads. Right now we calculate design heating flow rate from the design zone
heating and the design zone air inlet temperature. If this flow rate is less han the min flow fraction we
reset the design heating flow rate to the minimum and calculate the design load and hence the design HW
flow rate using the new flow rate. I think this will be OK in most cases. As always, the user should choose
good zone sizing inputs (and system sizing inputs) which it is a pleasure to note that this defect input does do.

So our fix is to remove all code releated to ReheatMult. The HW flow rate calc has been altered slightly:

          CoilInTemp = TermUnitFinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTempTU
          DesMassFlow = StdRhoAir *   &
                               TermUnitSizing(CurZoneEqNum)%AirVolFlow
          DesZoneHeatLoad = CalcFinalZoneSizing(CurZoneEqNum)%DesHeatLoad * CalcFinalZoneSizing(CurZoneEqNum)%HeatSizingFactor
          ZoneDesTemp = CalcFinalZoneSizing(CurZoneEqNum)%ZoneTempAtHeatPeak
          ZoneDesHumRat = CalcFinalZoneSizing(CurZoneEqNum)%ZoneHumRatAtHeatPeak
          ! the coil load is the zone design heating load plus (or minus!) the reheat load
          DesCoilLoad = DesZoneHeatLoad + PsyCpAirFnWTdb(ZoneDesHumRat, 0.5d0*(CoilInTemp+ZoneDesTemp)) &
                           * DesMassFlow * (ZoneDesTemp-CoilInTemp)

......

            Sys(SysNum)%MaxReheatWaterVolFlow = DesCoilLoad / &
                                                  ( PlantSizData(PltSizHeatNum)%DeltaT * &
                                                   Cp * rho )

The defect file looks good now. The code needs to be tested further for mild climates and for
reverse action cases. That's what I am doing now. 

==================================================================

I'm in the process of checking in changes to HVACSingleDuctSystem and HVACWaterCoilComponent to deal with these 2 CRs. Both have to do with sizing hot water coils. CR9216 is mainly about reheat coils, CR9268 concerns central system heating coils.

CR9216
The problem here was that reheat coil UAs for "normal" action VAV dampers (fixed minimum flow during heating) were being calculated at the maximum zone design flow rate. This was easy enough to fix, but I also messed about with the whole calculation and would like some feedback.

The reheat coils are now sized in a very straightforward manner. The coil design UA and max hot water flow rate are sized from a design load which is the sum of the zone design heating load plus the reheat load. The reheat load calculated using an air flow rate which is the zone design heating flow rate or the minimum zone flow rate, whichever is bigger. The delta T is the difference between the zone temperature during the zone sizing calculation and the design coil inlet temperature. Here is the code:

CoilInTemp = TermUnitFinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTempTU
DesMassFlow = StdRhoAir *   &
  TermUnitSizing(CurZoneEqNum)%AirVolFlow
DesZoneHeatLoad = CalcFinalZoneSizing(CurZoneEqNum)%DesHeatLoad * &
  CalcFinalZoneSizing(CurZoneEqNum)%HeatSizingFactor
ZoneDesTemp = CalcFinalZoneSizing(CurZoneEqNum)%ZoneTempAtHeatPeak
ZoneDesHumRat = CalcFinalZoneSizing(CurZoneEqNum)%ZoneHumRatAtHeatPeak
! the coil load is the zone design heating load plus (or minus!) the reheat load
DesCoilLoad = DesZoneHeatLoad + PsyCpAirFnWTdb(ZoneDesHumRat, &
  0.5d0*(CoilInTemp+ZoneDesTemp)) &
   * DesMassFlow * (ZoneDesTemp-CoilInTemp)

This works fairly well, but we are definitely getting more hours of heating setpoint unmet. For instance,
the large office reference building is giving 50 hours heating unmet in the annual run versus 41 in version 8.0. Basically, the coil UAs are smaller, the hot water max flow is smaller, and the zone warms up more slowly at morning start up. I am tempted to use

CoilInTemp = TermUnitFinalZoneSizing(CurZoneEqNum)%DesCoolCoilInTempTU

instead of

CoilInTemp = TermUnitFinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTempTU

even though there isn't much justification for it. What are these temperatures?
TermUnitFinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTempTU is the user specified (in Sizing:System) "Central Heating Design Supply Air Temperature".
TermUnitFinalZoneSizing(CurZoneEqNum)%DesCoolCoilInTempTU is the
"Central Cooling Design Supply Air Temperature". In a typical input the central heating design supply temperature might be 16.7 and the cooling 12.8, so the reheat coils will be sized modestly larger using the cooling value

So, what do you all (who have read this far) think? Is this a fudge worth doing? A more extreme change would be to use the design heating mixed air temperature, which would assume that the reheat coils need to do all of the heating in case the central cooling coil fails.

Fred

I would say no to switching the inlet temps used for the reheat coil.  The system design heating supply temp is the right one to use.  If that fails to be enough, then some other issue is going on - is the supply air really being maintained at the temp, or morning recovery needs to start sooner, or . . .    (Mike)

Fred,

I'd stick to your current solution.

CR9216:

>>Use
CoilInTemp = TermUnitFinalZoneSizing(CurZoneEqNum)%DesCoolCoilInTempTU
instead of
CoilInTemp = TermUnitFinalZoneSizing(CurZoneEqNum)%DesHeatCoilInTempTU

[LS] We have a similar issue in Trace sizing. Users will complain doing it either way, depending on their application. Trace currently uses DesCoolCoilInTempTU for the reheat coil design entering db but many users complain that this oversizes their reheat coils when they meant to use the upstream preheat coil to do most of the heating, especially at morning startup. The way E+ does it now (even though it causes more unmet loads in some of your files) is much more preferable.

>> A more extreme change would be to use the design heating mixed air temperature, which would assume that the reheat coils need to do all of the heating in case the central cooling coil fails.

[LS] This would be the least preferable option since it could oversize the reheat coils significantly.

Perhaps in a future version we could add more options for heating coil sizing to give the users a better choice if they don't like our defaults.
 
Lawrence Scheier

--
#### Workaround
Set the Damper Heating Action to *reverse*, and set the Maximum Flow Fraction During Reheat to match the Minimum Air Flow Fraction.

--
External Ref: Ticket 7387, CR8807
Addressed in `13.10.16 V8.1.0.007` by Brent Griffith
Last build tested: `13.04.30 V8.0.0.008 - rerelease`

**Comment by mjwitte** [comment]
Verified fix by comparing 5ZoneAirCooled reheat coil sizing with Normal and Reverse action in v8.0.0 and v8.3.0.
