### ISSUE TITLE
The documentation for complex fenestration systems was revised to include the correct figure art for shading device multipliers. (CR #9222)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#3993]
###### Added on 2013-05-13 10:15 by @vidanovic
--
#### Description
Change definition of opening multipliers in I/O reference.  Change figure which representes opening multipliers into correct one.

--
Addressed in `13.07.03 V8.1.0.002` by @vidanovic
Last build tested: `13.04.30 V8.0.0.008 - rerelease`

**Comment by mjwitte** [comment]
Confirmed that multiple new figures replaced the old figure.
