### ISSUE TITLE
Output Variables with identical names but different units are now shown as such in the .rdd file (CR #9244)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4015]
###### Added on 2013-06-12 11:56 by @lklawrie
--
#### Description
No new .rdd entries are posted for output variables of same name but different units.

--
Addressed in `13.07.03 V8.1.0.002` by @lklawrie
Last build tested: `13.06.11 V8.1.0.001`

**Comment by mjwitte** [comment]
Made a combined example file with two ElectricLoadCenters by combining ShopWithPVandBattery and ShopWithPVandStorage.  This fails with a fatal error claiming it can't find one of the storage objects. So, can't really confirm this fix.  Posting a new issue #4921 to fix the fatal error and will confirm the output variables (and or change the name of one) there.
