### ISSUE TITLE
DElight daylighting does not recognize external shading devices. Suggestion is that documentation make that clear. (CR #9275)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4046]
###### Added on 2013-07-31 09:19 by @mjwitte
--
#### Description
MJW 31 Jul 2013
From e-mails

MJW 24 Jul 2013
The biggest difference with the DElight daylighting is that is doesn't support external shading (ignores it - I think simply because the information isn't part of what's passed to the DElight module - Rob Hitchcock would know more).  So, I don't know if these models have external shades/overhangs, but those would get missed.

BG 29 Jul 2013
But DElight is still not worth using for most projects (e.g.
it doesnÆt know about external shading surfaces & light
shelf results are way off)

JG 29 Jul 2013
I did not realize that DElight could not be used with external shading surfaces. The opening paragraph in the IOref on DElight does not mention that limit. It just talks about not working with dynamic shading controls.

--
Last build tested: `13.07.24 V8.1.0.003`

**Comment by mjwitte** [comment]
This needs a few test cases to confirm if exterior shading is ignored - both self-shading from the building and from shading surfaces.  A warning could be added to check if there are any shading surfaces and there is DElight daylighting then throw a severe to caution the user.

**Comment by JasonGlazer** [comment]
Ran tests by adding exterior shading to one of the DElighting example files and saw no difference in energy consumption for that zone or change in daylighting multiplier. 

Files put in: 

https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/4000s/4046

**Comment by mjwitte** [comment]
Tested with existing DElight example files - no warning.  Added various types of shading surfaces (one type only, in separate files) and warning appeared.

**Comment by mjwitte** [comment]
Closed via #5425 and #5444
