### ISSUE TITLE
HVAC diagram fails with an ERV system (CR #9282)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4053]
###### Added on 2013-08-16 12:53 by @mjwitte
--
#### Description
MJW 16 Aug 2013
HVAC diagram fails on ERV.  Error message in svg file is:

Error: No node connection found after the following object: ERV EXHAUST FAN

Inputs: Use example file HVACStandAloneERV_Economizer
Weather: Chicago.

--
External Ref: Ticket 8457
Last build tested: `13.07.24 V8.1.0.003`

**Comment by Myoldmopar** [comment]
Duplicate of #3630
