### ISSUE TITLE
I/O Ref list of reports for Output:Table:SummaryReports does not include LEED summary, Object Count Summary, and Component Cost Economics Summary reports (CR #9291)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4062]
###### Added on 2013-08-22 09:25 by @mjwitte
--
#### Description
MJW 22 Aug 2013
I/O Ref list of reports for output:table:predefined does not include LEED summary, Object Count Summary, and Component Cost Economics Summary reports

Also, need to check output details and examples . . . arrrgh.

--
External Ref: Ticket 8472
Last build tested: `13.07.24 V8.1.0.003`

**Comment by Myoldmopar** [comment]
Closed via #5402
