### ISSUE TITLE
HVACTemplates - add hot water preheat coil as an option (CR #9326)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4097]
###### Added on 2013-10-03 12:15 by @mjwitte
--
#### Description
MJW 03 Oct 2013
Current preheat coil options are only Gas, Electric, or None.  HVACTemplate:System:VAV, ConstantVolume, and DualDuct

--
Last build tested: `13.10.03 V8.1.0.005`

**Comment by mjwitte** [comment]
See #4890 - looks like the code is there, just not documented.
