### ISSUE TITLE
Reverse DD Testing Failure - HeatPumpWaterToAirWithRHControl (CR #9339)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4110]
###### Added on 2013-10-14 09:42 by @lklawrie
--
#### Description
Diffs within range

--
Last build tested: `13.10.11 V8.1.0.006`

**Comment by rraustad** [comment]
Found a few water to air related variables that needed resetting on begin environment. Compared the example file with one that had the design days in reverse order.

---

heatpumpwatertoairwithrhcontrol_new.csv
vs
heatpumpwatertoairwithrhcontrol_switched_new.csv

All Records are Equal.    576 records compared

**Comment by mjwitte** [comment]
@Myoldmopar When's the last time we ran a full reverse design day suite to see if there are more?

**Comment by rraustad** [comment]
PR #5707

**Comment by Myoldmopar** [comment]
Closed via #5707   right?

**Comment by rraustad** [comment]
Correct, PR #5707 is the fix for #4110.
