### ISSUE TITLE
Documentation is lacking some RDD excerpts for ElectricLoadCenter:Distribution - the text has definitions for these. (CR #9342)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4113]
###### Added on 2013-10-16 13:02 by @lklawrie
--
#### Description
User says:
The list of whole-building summary output variables is shown as:

HVAC,Average,Total Electric Power Produced [W]
HVAC,Sum,Total Electric Energy Produced [J]
HVAC,Average,Total Electric Power Purchased [W]
HVAC,Sum,Total Electric Energy Purchased [J]
HVAC,Average,Total Building Electric Demand [W]
HVAC,Average,Total HVAC Electric Demand [W]
HVAC,Average,Total Electric Demand [W]

However, the field descriptions shown immediately below this list total 10 output variables.

Looks like the RDD snippet above is missing the following report variable names:

Total Electric Energy Surplus [J]
Net Electric Power Purchased [W]
Net Electric Energy Purchased [J]

This might well have been corrected in the IO Reference during the massive output variable renaming completed for version 8.0.

In addition, is Total Electric Power Surplus [W] an output variable (companion to Total Electric Energy Surplus [J] output variable)?

In V8.0 documentation, this is still the case.

also the definition of Electric Load Center Requested Electric Power (appears to be in red, not black)

--
External Ref: ticket 7293
Last build tested: `13.10.16 V8.1.0.007`

**Comment by mjwitte** [comment]
This raises the question of whether we want to continue including the rdd fragments?  @Myoldmopar ?

**Comment by EnergyArchmage** [comment]
Closed via #5437
