### ISSUE TITLE
Water heater sizing was extended to allow autosizing of tank volume ad heat capacity for stand-alone tanks not connected to a plant loop. (CR #9356)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4127]
###### Added on 2013-10-24 16:26 by Brent Griffith
--
#### Description
user was trying to autosize tank volume for a water heater that was not connected to plant.  No warning was produced and bad results obtained.  The sizing was originally planned for plant-connected tanks but it seems reasonable to extend it to include draws at the tank.  Either need to add this functionality or add warnings and clarify in documentation.  

quotes from ticket 

" I did read through the I/O and definitely feel
that something should be added to the documentation under the "Design Mode"
field for PeakDraw. An error would be useful as well.

Is it difficult to implement autosizing for the simple case? It seems to
make sense for consistency. I am working on an Appendix G model where all
the baseline equipment is required to be "autosized."

> I am sorry, but the "PeakDraw" volume autosizing is only implemented for
> plant-connected water heaters. This is pretty clear in the I/O reference
> for the field called Time Storage Can Meet Peak Draw. I see there is no
> warning issued about the situation which may be a good idea to add. In this
> case, the flows are prescribed and there is nothing unkown. If you have all
> the scheduled uses then you know the draws and can calculate a volume for
> the input. The autosizing is intended to be useful when the draws are not
> known, like if they were from heating coils or something else with a size
> that is not known at the outset.  "

[BG 11-4-2013] checked in source code to address.

--
External Ref: Ticket 5881
Addressed in `13.11.20 V8.1.0.009 - rerelease` by Brent Griffith
Last build tested: `13.10.18 V8.1.0.008`

**Comment by mjwitte** [comment]
Verified with v8.3.0 using an autosized version of WaterHeaterStandalone.
