### ISSUE TITLE
ZoneHVAC:UnitVentilator only operates when there is a thermostat load. It needs a continuous fan option to provide the required ventilation. (CR #9360)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4131]
###### Added on 2013-10-25 12:58 by Brent Griffith
--
#### Description
the ZoneHVAC unit ventilator needs its control logic reworked.  here is a list of issues. 
1. Unit ventilator fan won't run unless there is a load from the thermostat.  A ventilator should always ventilated regardless of the current load, or else rename the component

2. User tried SingleHeatingOrCooling thermostat type in an attempt to force the unit to run at all times. This resulted in poor control, and lots of downstepping (down to 1 minute time steps) - probably oscillating between heating and cooling control - not sure.

3. Unit seems to behave ok with dual setpoint thermostat.

4. With SingleHeatingSetpoint thermostat, meets heating setpoints fine, but never runs to bring in ventilation air during warmer weather.

Need to really define what *should* a unit ventilator do, and then revise coded logic to do that.

--
External Ref: ticket 275
Last build tested: `13.10.18 V8.1.0.008`

**Comment by Myoldmopar** [comment]
Already done.
