### ISSUE TITLE
Coefficients in the cross ventilation model should be updated. (CR #9381)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4152]
###### Added on 2013-11-13 01:24 by @hongtz68
--
#### Description
Guilherme and Nick made some modifications to the coefficients in the cross ventilation model updated in EnergyPlus 8.1.

TH 11/25/2013
only changes are the following in RoomAirModelCrossVent.f90:

  REAL(r64),PARAMETER  :: Cjet1 = 1.873d0      ! First correlation constant for the jet velocity
  REAL(r64),PARAMETER  :: Cjet2 = 0.243d0      ! Second correlation constant for the jet velocity
  REAL(r64),PARAMETER  :: Crec1 = 0.591d0      ! First correlation constant for the recirculation velocity
  REAL(r64),PARAMETER  :: Crec2 = 0.070d0      ! Second correlation constant for the recirculation velocity
  REAL(r64),PARAMETER  :: CjetTemp = 0.849d0   ! Correlation constant for the jet temperature rise
  REAL(r64),PARAMETER  :: CrecTemp = 1.385d0   ! Correlation constant for the recirculation temperature rise
  REAL(r64),PARAMETER  :: CrecFlow1 = 0.415d0  ! First correlation constant for the recirculation flow rate
  REAL(r64),PARAMETER  :: CrecFlow2 = 0.466d0  ! Second correlation constant for the recirculation flow rate

--
Addressed in `Next Build` by @hongtz68
Last build tested: `13.10.18 V8.1.0.008`

**Comment by Myoldmopar** [comment]
Not sure how to validate anything here to get it verified.  It's been in there working for a while now.  I'll close this.  @hongtz68, if you have any additional thoughts or work you'd like me to perform, just let me know.
