### ISSUE TITLE
IDF Editor - In validity checks, add check for a required field that is blank (CR #9389)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4160]
###### Added on 2013-11-21 08:33 by @mjwitte
--
#### Description
MJW 21 Nov 2013
User had some blank required fields that were not flagged by the IDF Editor validity check.  I think this should be safe to add as another check - both the colored cell and the validity check report.

(I realize this might not happen in current IDF Editor, but it would be a good capability to have in the new one if it supports validity checks.)

Can test with any file, just find a required field (blue field name) and delete the value in it, or make a new object - look for colored cells and run the View --> validity check and see if the blank required fields are reported.

--
External Ref: Ticket 8677
Last build tested: `13.11.20 V8.1.0.009 - rerelease`

**Comment by Myoldmopar** [comment]
Hey @JasonGlazer if this is relatively simple, it would be nice to address for 8.4.  If not, just change/remove the milestone.

**Comment by JasonGlazer** [comment]
@Myoldmopar @mjwitte I agree, it would be good to get this one done.

**Comment by mjwitte** [comment]
Closed via [EnergyPlusBuildSupport #15](https://github.com/NREL/EnergyPlusBuildSupport/pull/15)
