### ISSUE TITLE
uninitialized variables cause problems for open source user (CR #9393)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4164]
###### Added on 2013-11-29 15:28 by @lklawrie
--
#### Description
From user:
Yesterday I downloaded the source code of v8.1.

I compiled it with gfortran 4.7.2.

When testing my compile, the program crashed, even with the example idfs (segmentation fault).

So I added the -fbounds-check flag and got:

At line 8816 of file OutputProcessor.f90

Fortran runtime error: Index '538976288' of dimension 1 of array 'ddvariabletypes' above upper bound of 1000

Initializing the Next variable in the VariableTypeForDDOutput structure appears to solve the problem:

INTEGER :: Next =0 ! Next variable of same name (different units)

Could you please confirm whether this is the proper solution?

There appear to be a similar problem with the RecurringErrors variable. Did you used a sort of -finit-integer=0 flag?

Edwin -- you might check the Linux gfortran? I think the windows gfortran that I'm using is at least 4.8

--
External Ref: ticket 8875
Addressed in `Next Build` by @lklawrie
Last build tested: `13.11.20 V8.1.0.009 - rerelease`

**Comment by Myoldmopar** [comment]
The Next variable is indeed initialized to zero now.  Closing.  Pretty soon, when we get the compiler warnings cleaned up, we'll be able to make sure uninitialized variables and other issues are noted right away in CI.
