### ISSUE TITLE
Environment:Site Horizontal Infrared Radiation Rate per Area [W/m2] does not interpolate weather file correctly. (CR #9394)

### ISSUE THREAD

**Issue by axelstudios** [NREL/EnergyPlus#4165]
###### Added on 2013-12-06 12:59 by @rraustad
--
#### Description
[RAR 6 Dec 2013]
Environment:Site Horizontal Infrared Radiation Rate per Area [W/m2] does not interpolate weather file correctly. If 4 time steps per hour are used, this report appears very sporatic and only lines up with the weather file data on the hour. See attachments.

Debugging shows that the first hour Site Horizontal Infrared Radiation Rate per Area variable (LastHrHorizIRSky) is not updated and the interpolation is always using the data at hr=24 which leads to the sawtooth pattern (i.e., always interpolating with hr=24 and hr=i).

Adding this at line 3253 of WeatherManager.f90 corrects the problem.
      LastHrHorizIRSky=Wthr%HorizIRSky(Hour)

--
External Ref: Ticket 8861
Addressed in `Next Build` by @rraustad
Last build tested: `13.11.20 V8.1.0.009 - rerelease`

**Comment by mjwitte** [comment]
Ran with v8.1.0.009 and v8.3.0 and verified this has been fixed.
