### ISSUE TITLE
Minimum outdoor temp for multispeed HP too high at -20C

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4174]
Ticket 9044: In Unitary Equipment> Air Loop HVAC: Unitary Heat Pump: Air To Air: Multispeed, there is an input required for "Minimum Outdoor Dry-Bulb Temperature for Compressor Operation". The lower limit on this range is -20 C. Many mini split heat pumps, such as Mitsubishi FE12NA and Fujitsu 12RLS, now have the capability to operate down to -30C and below. Can this limit be lowered so that these units can be modeled correctly?

MSZ-FE12NA
Heating
Maximum
Indoor: 80ºF (27ºC) DB, 67ºF (19ºC) WB, Outdoor: 75ºF (24ºC) DB, 65ºF (18ºC) WB
Minimum
Indoor: 70ºF (21ºC) DB, 60ºF (16ºC) WB, Outdoor: -13ºF (-25ºC) DB, -15ºF (-26ºC) WB**

**Comment by nmerket** [comment]
#4383 is the pull request
