### ISSUE TITLE
Tabular Output and Coil Load

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#4183]
@Myoldmopar and @JasonGlazer cooling coils within four pipe fan coils do not seem to report their design coil load properly, although this information is correctly reported in the eio.  See screenshots and defect file in the shared resources.

https://drive.google.com/folderview?id=0B6AYyX2ggNyBTXlvSUxnYWpYakk&usp=sharing

This issue came up on the CBECC project because they are running sizing runs then extracting the E+ autosizes and hard sizing the idf.  This is a fairly common thing to do, and something OpenStudio aspires to automate.  Despite my reservations and cautions the CBECC team is mining the sizing values from the sql database, as opposed to the eio file because like many people, the developers find the eio difficult to parse.  

The following issue in the CBECC tracking system provides a little more context.  https://code.google.com/p/cbecc/issues/detail?id=334&can=1&q=eio&colspec=ID%20Type%20SubType%20Reporter%20Status%20Priority%20Owner%20Summary

Presently sizing information is available in tabular data, the sql ComponentSizes table, and the eio.  The eio data is comprehensive and reliable, however not particularly user friendly.  The ComponentSizes table in sql is sadly neglected and incomplete.  The tabular data (often viewed as html) is in the sql database and the comprehensiveness seems to be almost on par with eio, but it seems the eio remains the authoritative source of sizing info.  So I'm wondering how established members (@mjwitte) of the E+ team feel about this subject.  Where do we officially go for sizing values?  Can the other sources be deprecated to eliminate confusion and focus resources?  Perhaps this is a topic for output redesign which I believe @hongtz68 (that is Tianzhen's username I hope) is in charge of?

![tabular](https://f.cloud.github.com/assets/707488/2306074/d87b8c1a-a278-11e3-80c5-910981b5778a.png)

![eio](https://f.cloud.github.com/assets/707488/2306075/de7be010-a278-11e3-94ff-15c66ed1b638.png)

**Comment by Myoldmopar** [comment]
Likely this has been addressed in the new detailed coil reports.  @kbenne feel like confirming?  I'm going to close because I believe it is done, but feel free to reopen.
