### ISSUE TITLE
Update DCV documentation to make it clear that VRP is not CO2 based

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#4186]
The IOref says

"EnergyPlus can model CO2-based DCV by the ventilation rate procedure (VRP) defined in ASHRAE Standard 62.1-2007/2010 for single and multiple path systems, and the indoor air quality procedure (IAQP) defined in Standard 62."

This implies that VRP is based on tracking CO2 but I do not believe it is.

**Comment by lgu1234** [comment]
The Eng. Ref was revised and uploaded. @JasonGlazer accepted the revision. This issue is closed.

**Comment by lgu1234** [comment]
@JasonGlazer Could you close this issue?
