### ISSUE TITLE
Text files: Special character encoding causes unintentional diffs

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#4215]
There are a lot of special characters (e.g., the copyright at the bottom of the page, and almost every double quote in the IDD) in source files that cannot be read by many non-Windows editors (including eclipse). For me, this means that every time I save a file, these characters are all converted to meaningless symbols and cause unintentional diffs in version control.

Has the team encountered this in the past? If not, I suggest we standardize on something like UTF-8 for all file encoding.

**Comment by Myoldmopar** [comment]
Current findings:

```
src/EnergyPlus/DataStringGlobals.in.cc:35:  std::string const UpperCase( "ABCDEFGHIJKLMNOPQRSTUVWXYZ���������������������������" );
src/EnergyPlus/DataStringGlobals.in.cc:37:  std::string const AccentedUpperCase( "���������������������������" );
src/EnergyPlus/DataStringGlobals.in.cc:39:  std::string const AllCase( "��������������������������������������������������������ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz" );
src/EnergyPlus/EnergyPlusPgm.cc:129:    //      Laboratories for Materials Testing and Research (EMPA), Division 175, Überlandstrasse 129, CH-8600 Dübendorf,
src/EnergyPlus/EnergyPlusPgm.cc:133:    //      by Guilherme Carrilho da Graça and Paul Linden of the Department of Mechanical and Aerospace
src/EnergyPlus/SolarShading.cc:1924:                ShowContinueError( "...these Tilt > 120°, (area=[" + RoundSigDigits( HorizAreaSum, 2 ) + "] m2) will be used." );
src/EnergyPlus/SwimmingPool.cc:69:  // 4. Smith, C., R. Jones, and G. Löf (1993). Energy Requirements and Potential Savings for Heated
src/EnergyPlus/SwimmingPool.cc:778:     //  4. Smith, C., R. Jones, and G. Löf (1993). Energy Requirements and Potential Savings for Heated
testfiles/ZoneCoupledGroundHTBasement.idf:114: ! Denver Centennial  Golden   N_CO_USA Annual Heating 99.6%, MaxDB=-18.8°C
testfiles/ZoneCoupledGroundHTBasement.idf:146: ! Denver Centennial  Golden   N_CO_USA Annual Cooling (DB=>MWB) .4%, MaxDB=33°C MWB=15.7°C
```

The first three of these have to stay in, but I'll clean up the rest to close this issue.

**Comment by nealkruis** [comment]
Thanks @Myoldmopar! Any thoughts on using @mbadams5 suggestion [here](https://github.com/NREL/EnergyPlus/issues/4215#issuecomment-41934481) for those lines?

**Comment by Myoldmopar** [comment]
@nealkruis In @mbadams5 recommendation, he actually put the character in there still, just in a comment at the end of the line.  I'm inclined to leave those remaining lines alone for now, since it should be rare that anyone will modify that file.

**Comment by nealkruis** [comment]
I was thinking we could replace the character with a description in the comment instead. But your point is valid, this file won't be changing often. Your approach sounds good to me.

**Comment by nealkruis** [comment]
Several non-ascii characters are still floating around in OutputReportTabular.cc (search for ö and °). In fact, doing a search for � in my source files returns 368 results in 16 files (using Atom with UTF-8 encodings).

**Comment by Myoldmopar** [comment]
I think all this has settled down so I'm going to close it.  I do have a branch locally that will test for any invalid characters on CI, but I haven't pushed it yet.  So it should be even more stable soon.
