### ISSUE TITLE
Engineering Reference Figure 119 Needs to be Updated

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#4247]
Figure 119 in the Engineering Reference (page numbered 384 or page 411 of the document) is out of date.  It shows a link between the zone equipment and the condenser loop as "future".  Well, 2003 called and it wants us to know that link exists so it should not be labeled as future anymore.  Someone might have to track down the original version of this figure (Strand UIUC might have it?) or recreate this and update appropriately.

**Comment by RKStrand** [comment]
This is now Figure 9.1, page 470 of the V8.7 PDF

**Comment by RKStrand** [comment]
Image that needs to be updated is image1957.svg.png

**Comment by RKStrand** [comment]
Image was recreated from scratch as older versions with the individual pieces separated out were not found.  New diagram updates the connections and gives the overall diagram a fresher, more colorful look.

**Comment by Myoldmopar** [comment]
Closed via #6300
