### ISSUE TITLE
No Statement in I/O Ref that Surfaces are Modeled as Planes with No Thickness

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4256]
I/O Ref does not state anywhere that surfaces are modeled as planes with no thickness for geometry or shading purposes.  I reviewed the v8.1 I/O Ref and looked at introduction sections as well as Specifying Building Envelope and Thermal Zone Description/Geometry and could not find any explanation about this.  Helpdesk Ticket 2448

**Comment by Myoldmopar** [comment]
@jasondegraw noted that interzone surfaces can be separated to imply thickness.

**Comment by mjwitte** [comment]
Closed via #5352
