### ISSUE TITLE
PV with battery storage operation scheme -- need better explanation of storage rules

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4273]
User confused as to why supposed surplus generated power is not going to recharge storage batteries.  MJW suggested that there needs to be a better explanation of what the storage rules are.  Looking at the I/O Ref I could not find an explanation as to these rules.  Seems to me they should be either in the introductory section for Electric Load Centers or in the section on ElectricLoadCenter:Storage.
Helpdesk Ticket 8245
User test files
20130619_NIST NZE House_DD.idf

20130619_NIST NZE House_Base_DD.idf

20130619_NIST NZE House_Track_DD.idf

**Comment by EnergyArchmage** [comment]
Closed via #5437

Added more inputs for storage control and discuss them in I/O ref
