### ISSUE TITLE
How to model AppG Supply Air Temp Reset

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4275]
Would be good to add as a section to the Compliance doc.
Helpdesk Ticket 2199

**Comment by jmarrec** [comment]
I decided to put it in the Tips and Tricks and added: HW LWT Reset, ChW LWT Reset, AirLoopHVAC SAT Reset, and Cooling Tower Reset. I added a reference to that in the compliance doc.
