### ISSUE TITLE
Multiple year RunPeriod tabular results

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#4284]
When running a multiple year simulation for ground loop heat exchangers (see RunPeriod field named "Number of Times Runperiod to be Repeated") the tabular reports show the totals over the entire run period. This probably does not make sense since the idea of running multiple years is because the ground needs to reach a steady annual cycle. Instead only the last year of the simulation when multiple years are requested should be reported. It might make sense to make this an option so that reporting could be for only the last year or for all years cumulatively. Any test file when changing the  RunPeriod field named "Number of Times Runperiod to be Repeated" to a value 2 or greater should show this problem.

**Comment by JasonGlazer** [comment]
According to the IDD, RunPeriod, Environment, and Annual are synonymous.

I verified this,using any of these just results in a single result at the end of the simulation.

**Comment by JasonGlazer** [comment]
@mjwitte In testing the routine that zeros the accumulation arrays, I have noticed that the same file run for one year and running for three years and only using the last year of results, give similar but not exactly the same results in the tabular reports. Is that reasonable or should I expect the results to be exactly the same? I am using 5ZoneAirCooled.idf as the basis of my testing.

**Comment by mjwitte** [comment]
I would expect a small difference in the first week of January due to different wall history in the first year (repeated Jan 1) vs the later years where it just continues from Dec 31.  I would expect years 2 and up to agree with each other exactly.

**Comment by JasonGlazer** [comment]
I think the day of the week also changes since Jan 1 follows the day of week from Dec 31. I am comparing only the last year with a simulation lasting only one year and finding differences. Not sure what should be considered reasonable differences.

**Comment by JasonGlazer** [comment]
@mjwitte @Myoldmopar The tabular report called "Energy Meters" is very closely tied to the energy meters themselves. I cannot reset to zero the variables used without affecting the results that are reported in the MTR file which, when requested, are for the entire runperiod. I have not been touching the MTR file or the ESO file. I could make some additional elements in the MeterType to accumulate and do max and min for the last year of the simulation only but it seems to be adding code that is very redundant. Another instance of lines in UpdateMeter(). So I want your opinions, do I

a) leave the Energy Meters tabular report alone and do not show only the last year?

b) change the results in the MTR file when someone wants a result for a runperiod that is more than a year so that it reflects only the last year?

c) add new elements to the MeterType and new lines to UpdateMeter() to have a new set of accumulating values that are only for the last year of a multiple year runperiod?

After laying these options out, I think I am going to go with the (c) option after all. It accomplishes the goal of fixing the issue and will not impact the MTR reporting. Please let me know if you disagree.

**Comment by mjwitte** [comment]
@JasonGlazer Regarding the day of week, there is a field in RunPeriod that controls this "Increment Day of Week on repeat".  Setting that to No may remove some of the differences.

My expectation for repeated runperiod would be that the mtr and eso files would report the first repetition, reset, then report the second repetition, etc.  Regardless of the reporting frequency.

What happens currently when you have multiple runperiods (say, Jan, Apr, Jul)?  Do the max/min values reset?  

More flexibility may be required later when multi-year (not repeating, just longer) runperiods support is added.  Regardless, the I/O Ref and IDD notes for Runperiod "Number of Times Runperiod to be Repeated" should explain what will happen with reporting.

**Comment by JasonGlazer** [comment]
@mjwitte I changed the "Increment Day of Week on repeat" to No and the magnitude of the differences is much smaller, thanks. This is issue is specifically about the tabular reports and not the MTR and ESO files, if we want to change their behavior, maybe we need to post another issue.

**Comment by mjwitte** [comment]
But all outputs need to be consistent with each other.  The only thing that would change in the MTR and ESO files is the max/min values, correct?

**Comment by Myoldmopar** [comment]
Closed with #5256
