### ISSUE TITLE
Headered pumps on branches with nothing else on branch should be illegal

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4288]
Transitioned user file to v8.1 and ran simulation but got fatal error as follows:

   ** Warning ** GetZoneEquipmentData1: ZoneHVAC:EquipmentList = VAV 1-1EQUIPMENT
   **   ~~~   ** ...zero assignments for Zone Equipment Cooling Sequence=1, apparent gap in sequence assignments in this equipment list.
   ** Severe  ** GetZoneEquipmentData1: ZoneHVAC:EquipmentList = VAV 1-1EQUIPMENT
   **   ~~~   ** ...multiple assignments for Zone Equipment Heating or No-Load Sequence=1, must be 1-1 correspondence between sequence assignments and number of equipments.
   ** Severe  ** GetZoneEquipmentData1: ZoneHVAC:EquipmentList = VAV 1-1EQUIPMENT
   **   ~~~   ** ...multiple assignments for Zone Equipment Cooling Sequence=2, must be 1-1 correspondence between sequence assignments and number of equipments.
   ** Warning ** GetZoneEquipmentData1: ZoneHVAC:EquipmentList = VAV 1-1EQUIPMENT
   **   ~~~   ** ...zero assignments for Zone Equipment Heating or No-Load Sequence=2, apparent gap in sequence assignments in this equipment list.
   ** Warning ** GetZoneEquipmentData1: ZoneHVAC:EquipmentList, duplicate items NOT CHECKED due to previous errors.
   **  Fatal  ** GetZoneEquipmentData1: Errors found in getting Zone Equipment input.

Ticket says that Branch ST-1 should be Passive rather than Active.  Made that chnage and reran and got same fatal errors as before.  Branch ST-1 has a Water Heater on it while Branch MP-9 has a headered pump.  Errors do not say anything about only headered pump on a branch being illegal.

Helpdesk Ticket 1813
User file
Haywood Elec Chiller DB Merge_Update.idf

**Comment by Myoldmopar** [comment]
@mjwitte Do you know anything about this one?  The errors described in the comment above seem to have a lot of issues with ZoneHVAC equipment lists.  Nothing to do with headered pumps.  I looked at the input file, and the headered pump is on the plant supply inlet branch.  It looks fine.

**Comment by mjwitte** [comment]
There is a headered pump that is on one of the parallel branches with nothing else, 
  Branch,
    SP-1 Branch,             !- Name
    autosize,                !- Maximum Flow Rate {m3/s}
    ,                        !- Pressure Drop Curve Name
    HeaderedPumps:ConstantSpeed,  !- Component 1 Object Type
    SP-1,                    !- Component 1 Name
    SP-1 Inlet,              !- Component 1 Inlet Node Name
    SP-1 Outlet,             !- Component 1 Outlet Node Name
    Active;                  !- Component 1 Branch Control Type

But this file has so many other problems and this was so long ago, I'm just going to close this issue.
