### ISSUE TITLE
Request for Variable Airflow DOAS

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4289]
User is trying to use HVACTemplate to model a variable airflow DOAS.  The v8.1 I/O Ref says that the HVACTemplate:System:DedicatedOutdoorAir object only allows constant volume outdoor air.  Comment is made in the ticket that it would be good to add this option to the HVACTemplate object.  V8.1 does not allow it.  User could have used ZoneHVAC:OutdoorAirUnit object which does allow for variable outdoor airflow.  But since this Helpdesk Ticket addresses the need to add the variable outdoor airflow option to HVACTemplate and it has not been done, I guess this issue has not been addressed.  This may be more of an enhancement than an issue.

Helpdesk Ticket 8525
No test file

**Comment by Myoldmopar** [comment]
This can be done now, closing.
