### ISSUE TITLE
DOAS unbalanced exhaust warning

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4293]
Comment is made in the ticket about the warning 
   ** Warning ** In AirLoopHVAC DOAS AIR LOOP there is unbalanced exhaust air flow.
   **   ~~~   **  During Warmup, Environment=PHILADELPHIA INTERNATIONAL AP ANNUAL HEATING, at Simulation time=01/15 01:25 - 01:30
   **   ~~~   **   Unless there is balancing infiltration / ventilation air flow, this will result in
   **   ~~~   **   load due to induced outdoor air being neglected in the simulation.
Same warning is still in v8.1.  Not clear to me from what is said in the ticket as to what was suppose to change??

3/12/2014 - MJW - If the error message is still there, then need a CR

Helpdesk Ticket 5451

Example file
New Building.idf

**Comment by mjwitte** [comment]
Reviewing the comments in the helpdesk ticket, the warning is being triggered by a tiny negative value for AirLoopFlow(AirLoopNum).SupFlow in ZoneEquipmentManager::CalcZoneMassBalance.

**Comment by mjwitte** [comment]
The small imbalance is coming from the fan coil units - the fancoil inlet (zone exhaust node) mas flow rate is slightly greater than the fan coil outlet flow rate (zone inlet node).  The defect file uses CyclingFan control for the fan coil units, changing this to ConstantFanVariableFlow eliminates the error.  Next step - look at the cycling fan flows in the fan coil unit.

**Comment by Myoldmopar** [comment]
Closed via #5422
