### ISSUE TITLE
Dangling ZoneHVAC:Baseboard:RadiantConvective:Electric with no ZoneHVAC:EquipmentConnections doe not give error

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4295]
This doesn't produce any warning or error that the baseboard is not being read - other than "there are 2 unused objects" which kind of get lost in the shuffle.

User references a dropbox where idf file can be found but not available any more.  Don't know what version of EnergyPlus he was using???

Helpdesk Ticket 8972

**Comment by mjwitte** [comment]
Opened a new issue #4787, so this one can be closed.
