### ISSUE TITLE
IDF Editor problem with trailing space

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4301]
In the original file (v8.1.0.009), there is a trailing space in the Material object name after "Construction" and before ",".

 ! Materials
 !- Material: defaultMat Type: Concrete
 Material, defaultMat_0.35_defaultConstruction , !- Material name 

This is confusing the IDF Editor. If you delete the extra space before the comma (or in IDF Editor in the Material object, delete the trailing space in the name) then the problem will stop. IDF Editor should ignore and strip trailing spaces like this, but apparently is not. We will try to fix this for the next version.

Helpdesk Ticket 9096

User idf file
temp.idf

**Comment by mjwitte** [comment]
Closed via [EnergyPlusBuildSupport #15](https://github.com/NREL/EnergyPlusBuildSupport/pull/15)
