### ISSUE TITLE
ZoneHVAC:LowTemperatureRadiant:Electric object discussion in I/O Ref currently describes hydronic configuration

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4303]
One of the input fields for object = ZoneHVAC:LowTemperatureRadiant:Electric is:

 Field: Surface Name or Radiant Surface Group Name
 This field is the name of the surface (Ref: BuildingSurface) or surface list (Ref:
 ZoneHVAC:LowTemperatureRadiant:SurfaceGroup) in which the hydronic tubing is
 embedded/contained. This specification attaches the source or sink from the radiant system  to a particular surface and the contribution of the system to the heat balances of that surface.   If this field is a surface list, then the source or sink is attached to all of the surfaces in the list  with the radiant system surface group defining the breakdown of how flow rate is split  between the various surfaces. Only base surfaces (e.g. BuildingSurface:Detailed) are valid.   Window/Door surfaces and Internal Mass are not valid surface types for embedded radiant  systems

Might consider clarifying the Field: Surface Name or Radiant Surface Group Name input field description for object = ZoneHVAC:LowTemperatureRadiant:Electric and the "Flow Fraction" input field description for object = ZoneHVAC:LowTemperatureRadiant:SurfaceGroup for "electric" configuration ... currently they describe the hydronic configuration.

Helpdesk Ticket 9391
No user idf file

**Comment by rraustad** [comment]
Documentation updated with #5958.

**Comment by Myoldmopar** [comment]
OK, since this was completed with the merged #5958, I'll close this and the Pivotal ticket.
