### ISSUE TITLE
Need definition of Calculated Design Load, User Design Load, Average Number of Occupants and Nominal Number of Occupants in docs

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4307]
Cannot find explanation of these terms and user is confused.

Rich says:
Calculated Design Load - load calculated by the program
 User Design Load - load calculated by the program and adjusted for user inputs (e.g. sizing factor)
 These should be the same if the sizing factor (and any other scalable inputs, I'm not sure of all possible) is 1

 Average Number of Occupants - the average number of occupants during the simulation based on the occupancy schedule
 Nominal Number of Occupants - the number of occupants based on the inputs in the people object
 These should be the same if the occupancy schedules are 1 at all times

Helpdesk Ticket 9390
No test files

**Comment by jmarrec** [comment]
The Output:Table:SummaryReports has a subsection for HVAC Sizing Summary [here](https://bigladdersoftware.com/epx/docs/9-0/input-output-reference/output-table-summaryreports.html#hvac-sizing-summary) that does explain this:

> Note: values listed as “calculated” are the unaltered result of the zone or system sizing calculations, using the design sizing period weather and schedules specified in the input. Values listed as “user specified” are either the calculated values modified by global or zone sizing factors or values specified with the flow/zone or flow/system design air flow method.

The same can be found in the "Output Details and Examples" under the HVAC Sizing Summary [here](https://bigladdersoftware.com/epx/docs/9-0/output-details-and-examples/eplustbl-lt-ext-gt.html#hvac-sizing-summary)

(A git log showed it was added in 2016 by Matt Larson in https://github.com/NREL/EnergyPlus/commit/4defe01a48f1df9de23e3adfd9f2e324ecf4659e#diff-0ddc3e6e2c8f2f4d30f5ef55c066d101R1261)

I think that's enough, closing. Feel free to reopen if you disagree
