### ISSUE TITLE
PsyVFnTdbWPb behavior varies with error reporting

### ISSUE THREAD

**Issue by DeadParrot** [NREL/EnergyPlus#4313]
In PsyVFnTdbWPb the adjustment of the of a negative V value only occurs if ```EP_psych_errors``` is defined, which looks like a bug. I assume the ```V = 0.83;``` line should be after the ```#endif``` and I've made that change in the Objexx_Performance branch.

```cpp
if ( V < 0.0 ) {
#ifdef EP_psych_errors
  ...
   V = 0.83;
#endif
}
```

Comments or confirmation?

**Comment by mjwitte** [comment]
This went in with #4349
