### ISSUE TITLE
SHDGSS odd code

### ISSUE THREAD

**Issue by DeadParrot** [NREL/EnergyPlus#4314]
This code in SHDGSS seems odd/inefficient and possibly not as intended:

``` cpp
NVR = HCNV( 1 );
for ( N = 1; N <= NumVertInShadowOrClippedSurface; ++N ) {
   for ( M = 1; M <= NVR; ++M ) {
      if ( std::abs( HCX( M, 1 ) - HCX( N, NS3 ) ) > 6 ) continue;
      if ( std::abs( HCY( M, 1 ) - HCY( N, NS3 ) ) > 6 ) continue;
      HCX( N, NS3 ) = HCX( M, 1 );
      HCY( N, NS3 ) = HCY( M, 1 );
   }
}
```

`( N, NS3 )` is fixed in the M loop so the effect is just to assign those HCX/Y elements for the last M that gets past the `abs` checks. If it really needs the last one (doubt it) you could loop in reverse and then break. If it needs any then you can break after the assignments.

Can someone who better understands the intent comment?

**Comment by jmarrec** [comment]
This has been rewritten: https://github.com/NREL/EnergyPlus/blob/0c9b8c4944b5f06edb000bf0d766f067830af0ae/src/EnergyPlus/SolarShading.cc#L6005-L6022
