### ISSUE TITLE
Radiant floor never turns on with ZoneHVAC:LowTemperatureRadiant:ConstantFlow 

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4318]
Last response to user by MJW on 23 April 2014 

Yes, a change request will result which should be fixed by next release.
 Mike

Response by Rich on 1 April 2014 

I think my first assessment was incorrect (it's not the plant). What I am seeing is a serial model where heating is initialized first and then cooling. It appears that since this is a heating and cooling radiant system, and the fact that it is in heating mode, the system is being turn off because cooling mode initialized the water flow rate to 0 (after heating mode water flow rate was correctly initialized).

 I suggest trying this:

 1) run your simulation and see if cooling operation works as expected. I think it should if I have assessed this correctly.
 2) then remove the cooling High Water Temperature Schedule Name (leave it blank)
 , !- Cooling High Water Temperature Schedule Name
 this essentially disables cooling mode for this radiant system.

 then see if the system operates in heating mode

 Since I did try this and I see that heating mode is now working (turned on at 1/21 8:10 AM), my only suggestion is to use a heating only radiant system until we get this fixed.

Helpdesk Ticket  9223

User files 
Radiant Floor Heaters w Boiler_BPT.idf
Radiant Floor Heaters w Boiler_BPT.rvi

**Comment by pyment** [comment]
Can you give me your user files. Radiant floor heater w boiler? pls

**Comment by mjwitte** [comment]
defect files may be found in https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles
If you don't have access to that, please e-mail me directly.

**Comment by Nigusse** [comment]
Is anybody working on this bug?

**Comment by mjwitte** [comment]
I think @RKStrand may be planning to tackle this one, but I'm not sure.

**Comment by RKStrand** [comment]
Yes, I am…soon.

**Comment by mjwitte** [comment]
Closed via #5694
