### ISSUE TITLE
ZoneHVAC:HighTemperatureRadiant - No radiant receiving surfaces and no radiant to people

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4324]
MJW comment
So, looks like this needs a fix?

RHH comment
Looks like I/O Ref needs to also explain what happens.

User came across a file where NO surfaces were defined to accept the "Fraction of Input Converted to Radiant Energy", and the "Fraction of Radiant Energy Incident on People" is also set to zero:

 ZoneHVAC:HighTemperatureRadiant,
 HG:G1, !- Name
 PLANT1.EQUIP, !- Availability Schedule Name
 G1, !- Zone Name
 autosize, !- Maximum Power Input {W}
 Electricity, !- Fuel Type
 1, !- Combustion Efficiency
 0.5, !- Fraction of Input Converted to Radiant Energy
 0, !- Fraction of Input Converted to Latent Energy
 0, !- Fraction of Input that Is Lost
 MeanAirTemperature, !- Temperature Control Type
 1, !- Heating Throttling Range {deltaC}
 PurchaseRTEMP1, !- Heating Setpoint Temperature Schedule Name
 0; !- Fraction of Radiant Energy Incident on People

He  thought maybe the radiant energy might be equally distributed to the zone surfaces for this case where no specific "receiving" surfaces were defined. But I could not find anything in the Input Output Reference or Engineering Reference which described what happens when "Fraction of Input Converted to Radiant Energy" is greater than ZERO but no "receiving" surfaces are defined and "Fraction of Radiant Incident on People" is 0.

The ERR file shows:

 ** Warning ** Fraction of radiation distributed to surfaces sums up to less than 1 for HG:G1
 ** ~~~ ** As a result, some of the radiant energy delivered by the high temp radiant heater will be lost.
 ** ~~~ ** Occurs for ZoneHVAC:HighTemperatureRadiant = HG:G1
 ** Warning ** Fraction of radiation distributed to surfaces sums up to less than 1 for HG:HH
 ** ~~~ ** As a result, some of the radiant energy delivered by the high temp radiant heater will be lost.
 ** ~~~ ** Occurs for ZoneHVAC:HighTemperatureRadiant = HG:HH

 Assuming that since no "receiving" surfaces have been specified, and "Fraction of Radiant Energy Incident on People" is set to zero, then ALL of the "Fraction of Input Converted to Radiant Energy " (0.5) is considered "Lost"... that is, the convective portion is modeled but the radiant fraction is lost (not transferred to any zone surfaces... energy is consumed to create this radiant energy fraction but its impact on the zone heat balance is "lost").

 Please let me know if my understanding is correct.

Helpdesk Ticket  9387

User files
in.idf
in.err
in.epw

**Comment by RKStrand** [comment]
@BobHenninger @mjwitte So, what are your thoughts on what should be fixed here?  I could clarify this in the documentation making this a purely documentation bug fix.  EnergyPlus does throw a warning to let the user know what is going on, but I am open to modifying this and making code changes if you all think something else should happen.

**Comment by mjwitte** [comment]
@RKStrand Is the energy truly lost?  Or is any non-distributed radiant fraction added to convective instead?  If this is as stated above, then it should be a severe, and the error message should report the fractions "distributed to surfaces sums up to 0.0 and . . . to People is 0.0.  100% of the radiant energy . . . will be lost."  _OR_ change the code to throw any undistributed radiant onto all the surfaces or add to convective.

**Comment by RKStrand** [comment]
@mjwitte Yes, it is truly a loss.  I feel like this situation is clearly a user error/oversight and needs to be fixed.  I think that it was a warning initially to be a little less strict and still give the user some indication that something was up.  I think now that isn't good enough if we are talking about a loss of energy.  I think the most appropriate thing now is to up this to a severe error and add more details to the error message as you have suggested.  We shouldn't make assumptions as to what the user might have wanted or how to correct a user error.  I'll proceed on this basis.

**Comment by mjwitte** [comment]
Closed via #5830
