### ISSUE TITLE
ZoneCapacitanceMultiplier:ResearchSpecial - Ability to apply to specific zones

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4326]
User states that the multipliers in the ZoneCapacitanceMultiplier:SpecialResearch  object are applied to all zones. Suggestion is made that a Code revision is needed to apply multipliers to a single zone or a group.

Helpdesk Ticket  9054
No user file

**Comment by Myoldmopar** [comment]
This has been addressed; closing.
