### ISSUE TITLE
Unitary heat pump minimum temp limit should be lowered

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4327]
User requests:
In Unitary Equipment> Air Loop HVAC: Unitary Heat Pump: Air To Air: Multispeed, there is an input required for "Minimum Outdoor Dry-Bulb Temperature for Compressor Operation". The lower limit on this range is -20 C. Many mini split heat pumps, such as Mitsubishi FE12NA and Fujitsu 12RLS, now have the capability to operate down to -30C and below. Can this limit be lowered so that these units can be modeled correctly?

Comment by MJW
The hard limit check should probably be removed from the getinput? If not, it looks like the error message looks like it is incomplete - doesn't say the minimum limit is -20C . . .

Helpdesk Ticket  9044
No user file

**Comment by mjwitte** [comment]
Multispeed heat pump minimum was removed in #4174 This issue should consider removing the min limit from all heat pump parent and coil objects.  There is a bit of a mix now.  Another helpdesk ticket 10345 has asked for this.

**Comment by mjwitte** [comment]
@rraustad @lgu1234 Any objection to removing all minimum limits on heat pumps for the minimum entering air temperature for compressor operation?

**Comment by rraustad** [comment]
The only thing that would concern me is if the performance curves cover the range. If not, the performance is fixed below the curve's minimum OAT. This also applies with the existing limit so no objection.

**Comment by Myoldmopar** [comment]
@rraustad @ejhw Is this still an issue?  If not, could we close it?

**Comment by ejhw** [comment]
@nmerket Do you know the status of this?

**Comment by nmerket** [comment]
@ejhw No, this is the first I've seen of this. Seems like it would be easy enough to fix.

**Comment by ejhw** [comment]
Looks like @rraustad made the [change for multispeed coils](https://myvpn.nrel.gov/NREL/EnergyPlus/pull/4383/,DanaInfo=github.com,SSL+files). Can someone check if this also need to be done for single speed and variable speed DX heating coils?

**Comment by rraustad** [comment]
I no longer see a test for a hard-coded limit in DXCoils. It would have been right here below Number(5). I also searched the rest of the code and didn't find anything. The user can now change the idd as they so choose.

```
//Set minimum OAT for heat pump compressor operation
DXCoil( DXCoilNum ).MinOATCompressor = Numbers( 5 );

DXCoil( DXCoilNum ).OATempCompressorOn = Numbers( 6 );
```

Closing issue.

**Comment by ejhw** [comment]
The `Minimum Outdoor Dry-Bulb Temperature for Compressor Operation` input's `\minimum` field in the idd was removed for the multispeed DX coil, so I'd suggest we do the same for all the other instances of that field (looking at the 8.3 release idd):
- `ZoneHVAC:PackagedTerminalHeatPump,` (-20)
- `Coil:Heating:DX:SingleSpeed,` (-20)
- `Coil:Heating:DX:MultiSpeed,` (no minimum)
- `Coil:Heating:DX:VariableSpeed,` (-50)
- `AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed,` (no minimum)
- `WaterHeater:HeatPump,` (5)

_edited to add reference to the `\minimum` field_

**Comment by rraustad** [comment]
But the compressor should be off below a minimum temperature limit to protect the compressor (oil migration). The issue here is whether we hard-code a limit or let the idd set that limit (\minimum>x). We chose to let the idd set that limit. This field should not be removed from compression systems. If I did that for multispeed coils, then shame on me.

**Comment by lgu1234** [comment]
The Coil:Heating:DX:MultiSpeed object has a filed of Minimum Outdoor Dry-Bulb Temperature for Compressor Operation as N1. The value check was removed from the code. The idd sets the limit.

**Comment by ejhw** [comment]
@lgu1234, I do not see a `\minimum` in the 8.3 idd:

```
Coil:Heating:DX:MultiSpeed,
       \memo Direct expansion (DX) heating coil (air-to-air heat pump) and compressor unit
       \memo (includes electric or engine-driven compressor and outdoor fan), multi-speed
       \memo (or variable-speed), with defrost controls. Requires two to four sets
       \memo of performance data and will interpolate between speeds.
       \min-fields 40
  ...
  N1 , \field Minimum Outdoor Dry-Bulb Temperature for Compressor Operation
       \type real
       \default -8.0
       \units C
```

@rraustad, I'm fine having a minimum in the idd, but it is difficult to anticipate and keep track of technologies that push the limit lower. For example, there are some mini-split heat pump units that do not have a hard minimum outdoor temperature: ["cold climate Mitsubishi Hyperheats are rated down to -13°F and we’ve seen them running at temperatures below -20°F."](http://www.greenbuildingadvisor.com/blogs/dept/guest-blogs/minisplit-heat-pumps-and-zero-net-energy-homes). CO<sub>2</sub> heat pumps may be another example. Sure, users can modify the idd, but some might not know that that's a possibility.

**Comment by mjwitte** [comment]
@ejhw I think what you meant to say was that we should remove the minimum limit in the IDD (and source if there), not remove the "Minimum Outdoor Dry-Bulb Temperature for Compressor Operation" field, correct?

**Comment by ejhw** [comment]
@mjwitte Ah, yes, sorry that's what I meant to say.

If we want to retain a `\minimum` field in the idd, here is a strawman proposal:
- `ZoneHVAC:PackagedTerminalHeatPump,` (-20)
- `Coil:Heating:DX:SingleSpeed,` (-20)
- `Coil:Heating:DX:MultiSpeed,` (-50)
- `Coil:Heating:DX:VariableSpeed,` (-50)
- `AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed,` (-50)
- `WaterHeater:HeatPump,` (-50)

**Comment by rraustad** [comment]
The issue here is the performance curves which use a minimum temperature limit on OAT. The curves just maintain a constant output below the minimum temperature limit without the user realizing. Maybe the fix here is something other than \minimum>x in the idd, for example, if the curves are found to extrapolate, or are requesting output out of range of temperatures, then warn the user.

**Comment by ejhw** [comment]
> if the curves are found to extrapolate, or are requesting output out of range of temperatures, then warn the user.

I like that idea.
