### ISSUE TITLE
HVACTemplate Constant Volume system - fatal error with heat recovery and no cooling coil, economizer and preheat coil inputs ignored

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4328]
MJW response to user:

 As the warning message says, the simulation is missing a set point
  manager. This is a problem with the HVACTemplate.
 
  The cooling supply temperature setpoint manager is not being written to
  the expidf because this system is specified with no cooling coil. Is that
  what you intended?
 
  Also, the heating coil controls do not look correct. You have specified a
  FixedSetpoint of 40.5C for the heating coil. As specified this system will
  deliver 40.5C supply air whenever the heating coil schedule is active.
  There is no real control here. Since you've also specified a control zone
  name, I wonder if you intended toe select "ControlZone" instead of
  "FixedSetpoint".
 
  HVACTemplate:System:ConstantVolume,
  CAV_System_1, !- Name
  <snip>
  Gas, !- Heating Coil Type
  Warehouse HVAC, !- Heating Coil Availability Schedule Name
  FixedSetpoint, !- Heating Coil Setpoint Control Type
  Thermal Zone: D100D211D212, !- Heating Coil Control Zone name
  40.5556, !- Heating Coil Design Setpoint {C}

Question is:  If there is no cooling setpoint manager, what should the heat recovery setpoint be.  HVACTemplate need to cover for this situation.

Helpdesk Ticket  9021

User file
baseline.idf
baseline-addedSP.idf

**Comment by mjwitte** [comment]
Also discovered that this template does not honor the user input for economizer type.  The economizer was always set to noeconomizer unless there was heat recovery, and even then it was forced to differential drybulb or differential enthalpy depending on the heat recovery type.

**Comment by mjwitte** [comment]
Also discovered that this system type was missing all of the code to generate a preheat coil.

**Comment by Myoldmopar** [comment]
Closed with #4892
