### ISSUE TITLE
Add Humidifier as valid component to OA Subsystem 

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4329]
MJW comment  13 Jan 2014
MixedAir.f90 supports a fixed list of equipment types. The humidifier should be added to this list. And I'm not sure that the documentation even shows an explicit list of supported equipment types - this should be added if it's not there.

User request
User asks if it is possible to model a humidifier:steam:electric object as part of
 the outdoor air system? I am getting an error when attempting to run
 my model. I have attached a schematic of how the system is composed.
 Please let me know if you think this is feasible.

MJW comment to user
No, the humidifier object is not currently supported in the OA system equipment list. You will need to place the humidifier in the main branch after the OA subsystem. I will submit a change request to have this added.

Helpdesk Ticket  8991
No user idf file
CRSchematic.pdf

**Comment by mjwitte** [comment]
Closed via #5477
