### ISSUE TITLE
Multi-threaded runs - delete openmp environment variables 

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4335]
MJW comment 19 May 2014
See below, openmp environment variables still show in source code (and batch files? and threading object?) but that code have been gone since v8.0. Clean out the other vestiges?

MJW comment 16 May 2014
The OpenMP code was removed in version 8.0. It was only implemented in a small portion of the code and provided very little benefit. In fact, for smaller simulations it caused extra overhead that slowed down the simulation. I suppose we should consider cleaning out the environment variables.

User question
> I would be grateful for advice on the multi-threaded version of
 > EnergyPlus. (I am installing the application on a Linux Intel 64
 > system on behalf of HPC Wales.) I have installed both the free binary
 > version and the open-source version of 8.1.0 009, and have run them
 > with OMP_NUM_THREADS=2 and EP_OMP_NUM_THREADS=2, but I cannot see any
 > evidence that two threads are being used. On inspection of the source
 > code, I can see where these environment variables are being used to
 > initialize the threading in SimulationManager.f90, but I can't see
 > that they are used elsewhere in the source code and I can't find any
 > OpenMP directives, for example.
 > Could you please advise on whether either of the two versions that I
 > have downloaded supports multi-threading?

Helpdesk Ticket 9425
No user idf files

**Comment by Myoldmopar** [comment]
Closed via #5812
