### ISSUE TITLE
Eng. Ref. calculation revisions for Fanger PMV (Ticket 9598)

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4341]
Eng. Ref. does not include changes to the Fanger model based on ASHRAE 55 updates. See pg. 1195 of V8.1 Eng. Ref. and subroutine CalcThermalComfortFanger in ThermalComfort.cc

**Comment by RKStrand** [comment]
@rraustad @mjwitte Just to clarify this...are you saying that the Engineering Reference and the code match but that the equation E+ is using is not the same as the Fanger model as updated by the latest ASHRAE Standard 55?  If so, this is no longer a "documentation sources" issue but rather an actual code "bug".  Just checking as I want to make sure this is classified correctly before I get too far.  Thanks!

**Comment by mjwitte** [comment]
@RKStrand Don't know for sure.  Have you looked at the original helpdesk ticket?

**Comment by rraustad** [comment]
I believe it was just that the Eng Ref didn't get updated with new equations. I didn't go through everything, but here is one example. The commented line is in the 8.4 Eng. Ref on Pg 1160 (9 lines up from the bottom of page), the new equation should have replaced this one.

line 788 ThermalComfort.cc
// RadHeatLoss = RadSurfEff_CloBodyRat_SkinEmiss_StefanBoltz_ &   !original
//                            (AbsCloSurfTemp**4 - AbsRadTemp**4) ! Heat loss by radiation

// following line is ln 480 in ASHRAE 55 append. D
RadHeatLoss = 3.96 \* CloBodyRat \* ( pow_4( AbsCloSurfTemp \* 0.01 ) - pow_4( AbsRadTemp \* 0.01 ) );

**Comment by RKStrand** [comment]
@rraustad Ok, I see and understand what you are saying now.  It does look like simply a documentation issue.  I will check the other equations in the Eng Ref for Fanger also to make sure there aren't any other issues like this one.  Thanks for clarifying this.

**Comment by mjwitte** [comment]
Closed via #5506
