### ISSUE TITLE
 PsyPsatFnTemp -- Bad input temperature=NAN - Severe error encountered

### ISSUE THREAD

**Issue by krishnan-gowri** [NREL/EnergyPlus#4351]
While updating the baseboard water heater sizing code, there is a new fatal error in the psychrometry routine encountered.  Any suggestion/reason why this did not occur in the released Fortran source but occurs now in the C++ version?

** Severe  ** PsyPsatFnTemp -- Bad input temperature=NAN
   **   ~~~   **  Routine=CorrectZoneHumRat, During Warmup, Environment=CHICAGO_IL_USA ANNUAL HEATING 99% DESIGN CONDITIONS DB, at Simulation time=01/21 00:00 - 00:10
   **  Fatal  **  Program terminates due to preceding conditions.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=PsyPsatFnTemp -- Bad input temperature=NAN
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.

**Comment by mjwitte** [comment]
@krishnan-gowri Is this still an issue?  Do you have a defect file that reproduces the problem?

**Comment by krishnan-gowri** [comment]
This issue can be closed, it was caused by an uninitialized temperature value in the water heater sizing code.  This was fixed before the code was checked-in.

-krishnan

**Comment by mjwitte** [comment]
@krishnan-gowri Thanks.  Closed.
