### ISSUE TITLE
False component sizing report from plant equipment

### ISSUE THREAD

**Issue by krishnan-gowri** [NREL/EnergyPlus#4354]
Some plant equipment such as boilers and chillers report a false value for both Design Size and User-Specified values. A statement that assigns temporary design size value to the corresponding array cause the issue since the size subroutine is called more than once. The design size value is in place to the array, so that the model recognizes it as a hard-size value by the user. The temporary design size value needs to be appropriately assigned to the array only the field is hard-sized.  
Note that the current code doesn't affect numeric results of the plant equipment. Proper values will be reported after this change is made.

**Comment by Myoldmopar** [comment]
This was cleaned up with the sizing simulation work.  Closing this and deleting the branch.
