### ISSUE TITLE
ASHRAE_2013_OtherMonthly_DesignConditions.csv Missing Data

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#4362]
The ASHRAE_2013_OtherMonthly_DesignConditions.csv file that was distributed with EnergyPlus 8.1.0-009 in the Preprocess\WeatherConverter directory does not contain data for columns DE to FL for rows 5570 to 6448. Note to see the column labels, open the file in a spreadsheet. The version of the file that was distributed with 8.0.0 does not have as many rows. When I spot checked some WMO# that are missing columns in the 8.1 version with the 8.0 version, they had the additional columns. This was related to helpdesk ticket 9684.

**Comment by mjwitte** [comment]
ASHRAE_2013_OtherMonthly_DesignConditions.csv updated, courtesy of LKL.  
https://github.com/NREL/EnergyPlusBuildSupport/commit/02a316a32dfc3c586c00d0fdb23f419ca91ccd7e

@Myoldmopar Would be good for this to get on the change list.
