### ISSUE TITLE
DesignSpecification:OutdoorAir - Outdoor Air Flow per Person field used when when Flow/Area

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#4378]
The two test files are the same except that the DesignSpecification:OutdoorAir Outdoor Air Flow per Person field is blank in one (which would default to 0.00944) and set to a very small number in the other. But the Outdoor Air Method is  set to Flow/Area in both files. That setting should mean that Outdoor Air Flow per Person field is ignored but if you look at the Zone Ventilation Parameters table of the Std62 report you will see that they are being included in the breathing zone outdoor air flow. This is definitely a bug related to the sizing:system and may be a problem related to controller:mechancialventilation.

Maybe @hongtz68 can help figure this out.

**Comment by Myoldmopar** [comment]
Closed via #4689
