### ISSUE TITLE
GLHE works on condenser loop but not on plant loop

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4385]
Ticket 9725

From user:
Heatpump:WatertoWater:EquationFit not being activated

I'm attaching two files. Both use a geothermal loop to provide source water for water to water heat pumps.

In the first file, the geothermal well is located on a PlantLoop, and the source side nodes for the water to water heat pumps are connected to this PlantLoop. In this file, the water to water heat pumps do not operate.

In the second file, the geothermal well is located in a CondenserLoop, and the source side nodes for the water to water heat pumps are connected to this CondenserLoop. In this file, the water to water heat pumps operate.

It is my understanding that in the current Version of EnergyPlus (V8.1.0.009), PlantLoops and CondenserLoops are essentially the same. I would like to request that water to water heat pumps be allowed to connect the source side nodes to PlantLoops. If this is not possible, please provide the user with a severe error if a water to water heat pump is connected on the source side to a PlantLoop.

------------------------
I compared the two files and the only differences are condenserloop-->plantloop and condenserequipmetoperationschemes--->plantequip.....  So, it seems like this should work, but the plantloop version does not.

Two test files added.

**Comment by EnergyArchmage** [comment]
I am working on this issue,  may be the water-to-water models are missing a call to PullCompInterconnectTrigger.

**Comment by mjwitte** [comment]
@EnergyArchmage 4972 defect files PlantModel6 and PlantModel6-CondenserLoop crash with an array bounds error.
