### ISSUE TITLE
Question about Material:RoofVegetation Object and HeatBalanceAlgorithm choice

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4392]
Helpdesk Ticket 9621

MJW Comment to user question
Should probably add this equation to the Engineering Ref:

Here is the equation in the source code for sigmaf as a function of LAI:
 sigmaf = 0.9d0 - 0.7d0*exp(-0.75d0*LAI) ! Fractional veg cover based on (2) from FASST TR-04-25
 ! Formula for grasses modified to incorporate limits from
 ! Table 1 for sigmaf_max and min (0.20 to 0.9)

User Questions
> To whom it may concern,
 > Hi,
 > This is Hoda Ganji, Researcher and graduate student
 > from master of "Energy and Architecture", university of Tehran,
 > Tehran, Iran. Currently, I am working on a paper for "Building and
 > Environment" Journal and I have a few questions about the object
 > "Material:RoofVegetation":
 > 1-     According
 > to the InputOutputReference, at "HeatBalanceAlgorithm" part,
 > it seems reasonable to use "CombinedHeatAndMoistureFiniteElement" for
 > Material:RoofVegetation in order to calculate the effect of moisture
 > in the
 > air gap layer between the exterior envelope and the green layer.
 > However,
 > according to the EngineeringRefrence, the calculations for
 > Material:RoofVegetation is based upon CTF (ConductionTransferFunction)
 > not
 > CHAMFE. Now, my question is would there be any problem if I select
 > CombinedHeatAndMoistureFiniteElement?

 The Material:RoofVegetation model only makes a sensible heat connection with the rest of the model, so connecting it to HAMT will not accomplish anything. The soil moisture and evaporation are all part of the green roof energy balance, but it does not transmit moisture to the building surface below.

 > I mean, do these calculations work only if CTF is selected or can they
 > still be
 > applied in CHAMFE situation?
 > 2-     My
 > other question is that In InputOutputRefrence, it has been mentioned
 > that for Field: Leaf Area Index: 
 > At the present time the fraction vegetation cover is
 > calculated directly from LAI (Leaf Area Index) using an empirical
 > relation. The
 > user may find it necessary to increase the specified value of LAI in
 > order to represent
 > high fractional coverage of the surface by vegetation.
 > Thus, although "fraction vegetation cover" is
 > quite a consequential variable, there is no need to calculate it
 > separately,
 > right? The text says that it is possible to increase the specified LAI
 > value
 > in order to represent high fractional coverage. Now, how much should I
 > add
 > to LAI value if the fraction coverage is relatively high?

**Comment by Myoldmopar** [comment]
Fixed by #5198
