### ISSUE TITLE
interzone surface material checks fail for a single pane of glass with asymmetrical properties (different front/back side properties).

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4397]
Helpdesk Ticket 9441

Log of User and MJW comments

Here is an exemple,

 It’s some testing I’ve done in order to model reflective heat shield in a greenhouse.
 Even if it’s not the model I retain, it’s possible to see how implementing such a situation.

 Florian

> After other testing, I can simulate defining two different
> constructions. I have a warning message, but not a fatal error.
> 
> The results should be correct this way, but there is still a problem
> if the user define the Outside Boundary Condition as zone and let E+
> defining the surface in the other zone : reversing the layer will not
> respect the back face and front face property.
> 
> Florian

 Thank you for pointing this out. The case of a single layer of glass with asymmetrical properties is a special case that was not considered when implementing the interzone surface checks and the automated interzone surface creation. We will need to add some special logic for this. It would be helpful if you would reply and attach your working idf (the one with two different constructions that gives a warning).
 Thanks,
 Mike

User IDF file
Modele2ZonesEcran.idf

**Comment by RKStrand** [comment]
@mjwitte Looking at this now after finally getting the user IDF to work (some special characters and other issues were causing a crash).  Note that the error is actually only a warning message so I think it actually runs the file properly, just complains about it.  Right now, all it does is check to see if the material names line up.  There is no checking regarding properties.  So, regarding multi-pane interzone windows, if they have different properties on front/back that is not being checked.  That could get a bit tricky but I'll see what I can do.

**Comment by mjwitte** [comment]
Closed via #7487
