### ISSUE TITLE
Re:Update docs - ZoneHVAC:LowTemperatureRadiant:SurfaceGroup - can doors really not be selected?

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4398]
Helpdesk Ticket 9453

Log of User and MJW comments

Thanks Mike and Rick, that's what I was hoping to hear!
 We'll pass your advice on to our concerned user.
 Andy

Here is Rick's reply. We will post an issue to update the documentation accordingly. Mike
 -------------------------------------------
Looking at the code, it appears that the only things that are specifically forbidden with internal source/sinks are: windows and stuff with movable insulation. My guess is that the documentation is warning against some of those other things just to avoid problems. For example, a door could end up being very lightweight—something that has caused some problems numerically in certain situations. So, if Andy isn’t getting any errors and the results look believable, then go with it. As far as the code is concerned, what he is doing is allowed despite what the documentation says.

 Michael J. Witte, GARD Analytics, Inc.

I will ask the radiant surface expert.
 Mike

 > It has recently come to our attention that the mechanism we
 > implemented in DesignBuilder to allow doors (called sub-surfaces in
 > DB) be used as radiant source surfaces is not valid according to the
 > documentation which states. 
 > 
 > ------------------------------------
 > Field: Surface Name
 > This field is the name of a surface in the zone being conditioned by
 > the radiant system. Only
 > base surfaces (walls, roofs, floors) are valid. Window/Door surfaces
 > and Internal Mass are
 > not valid surface types for embedded radiant systems.
 > ------------------------------------
 > 
 > Could you please confirm that the documentation is up to date and that
 > there is a good reason for not allowing doors (sub surfaces) to have
 > radiant sources?
 > 
 > Reasons we are questioning this are:
 > 
 > a) EnergyPlus doesn't throw as much as a warning about it.
 > 
 > b) Our results generated when using sub surfaces as radiant sources
 > give perfectly believable results.
 > 
 > Thanks for any light you can shed.
 > 
 > Andy Tindale

**Comment by mjwitte** [comment]
This was previously addressed.  Current I/O Ref field description says "This field is the name of a surface in the zone being conditioned by the radiant system. Base surfaces (e.g., BuildingSurface:Detailed), door surfaces and internal mass are valid. Window surfaces are not valid surface types for embedded radiant systems."  And the IDD object-list reference RadiantSurfaceNames is assigned to the appropriate surface types. Closing.
