### ISSUE TITLE
EMS should warn if an actuator is defined but never used

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4404]
Seems EMS code could be scanned to look for any unused actuators and issue a warning?
 Michael J. Witte on 03 June 2014 08:41 PM

Posted on: 30 May 2014 05:05 PM
I think the problem is with the spelling of the actuator name and the variable name in the programs. For example:

 EnergyManagementSystem:Actuator,
 Evaperator_OutTemp, !- Name

 set Evaporator_OutTemp=Tw1_Evap-CoolingLoad/4200/Evaporator_Mass, !- A5

 EnergyPlus EMS is not able to distinguish whether a variable name that is not matched anywhere is intended to be a new variable or is a misspelling, so it will not warn. Also, if an actuator is never set in a program, then the actuator value will always be zero. It might be possible to warn about this, but EMS currently does not. So, first step is to check the spelling of every actuator variable name in the program snippets.

 Mike

 > Mr(Ms),I have encountered a problem when using
 > PlantComponent:UserDefined of EnergyPlus v8.0.I try to use it to build
 > a custom chiller, which is a preliminary step of a bigger plan.
 > Problem: I've already read through the "EMS_Application" pdf file, and
 > I've followed the instructions to establish actuators and sensors in
 > EMS, and put values in them. But it seemed that neither the plant loop
 > or the condenser loop worked when I started the simulation
 > progress(mass flow rates in both loops were zero, but air system
 > worked fine). Debug: 1，I've tried to replace the component with
 > Chiller:ConstantCOP, and the whole system worked very well, which
 > indicated that the problem was in EMS settings.2， I also realized
 > that even though in EMS program the value "7.22" had been put into
 > "Outlet Temperature" actuator of Evaporator plant connection, the
 > sensor I established at the outlet node of the component showed the
 > value of zero. 3，I send the idf file along with this email. 
 > It's my first attempt to use this part, I am pretty sure that a stupid
 > mistake must be made somewhere, but I really need some guidance, would
 > you please help me out? Perhaps some instructions if it troubled too
 > much?Thank you very much.
 > 
 > Adam Wang--------------------------------

User files
ElectricChiller.idf

**Comment by EnergyArchmage** [comment]
Building off of code developed for issue #4943, I am able to scan the list of used actuators and check the new initialization flag.  Here is a sample warning message produced by a quick test, from existing example file EMSDemandManager_LargeOffice (which really does have an unused actuator.)

   *\* Warning *\* checkForUnusedActuatorsAtEnd: Unused EMS Actuator detected, suggesting possible unintended programming error or spelling mistake.
   *\*   ~~~   *\* Check Erl programs related to EMS actuator variable name = HEATSYS1_BOILER_SETPOINT
   *\*   ~~~   *\* EMS Actuator type name = SYSTEM NODE SETPOINT
   *\*   ~~~   *\* EMS Actuator unique component name = HEATSYS1 SUPPLY EQUIPMENT OUTLET NODE
   *\*   ~~~   *\* EMS Actuator control type = TEMPERATURE SETPOINT

There will be one big warning message like this for each of the unused actuators.

**Comment by Myoldmopar** [comment]
Closed via #5660
