### ISSUE TITLE
Absorption Chiller Plant with blank water flow rate field

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4406]
Helpdesk Ticket 9431

Really need to disallow blank water flow rate field - throw a warning or default to autosize or something.
 Michael J. Witte on 16 May 2014 10:14 PM

Log of User and MJW comments
You cooling towers are also slightly different between the two simulations (capacity specs). Please make the suggested changes in the absorption chiller file and if that still does not work, please send the updated file.
 Mike

 > Dear Mike,
 > 
 > Thanks a lot for your help.
 > 
 > I have attached the electric chiller version of the model for your
 > reference. This is a small model of what I am actually doing with a
 > much
 > more complicated building. So any input from you helps.
 > 
 > Regards
 > Amir
 > 
 > On Sat, May 17, 2014 at 2:43 AM, EnergyPlus Support <
 > support@energyplus.helpserve.com> wrote:
 > 
 > > > I am able to define a chilled water loop using
 > chiller:electric:eir,
 > > > but when I use chiller:absorption the output has zero cooling. I
 > have
 > > > tested several examples and the result is the same. I am beginning
 > to
 > > > suspect the software. Please advise. I have attached a minimal
 > model
 > > > for your reference.
 > >
 > > 1. The water flow rates in the absorption chiller were blank. This
 > > defaults to zero. Need to put in "autosize".
 > > 2. With the chiller autosized, the simulation fails with an
 > overheated
 > > condenser loop.
 > > 3. The tower is autosizing to zeroes. Not sure why yet.
 > > 4. The setpointmanager for the condenser loop (Plant Loop 1) uses
 > the
 > > Medium Office ClgSetp schedule. Seems like the wrong values for
 > condenser
 > > water setpoint.
 > >
 > > Main problem was #1. Perhaps you can figure it out from there. If
 > not,
 > > please reply with our fixed idf, and it would be helpful to see the
 > > electric chiller version as well (to compare).
 > > Mike
  > >
 > > Michael J. Witte, GARD Analytics, Inc.

User files
esay-compression.idf

**Comment by JasonGlazer** [comment]
The test file "easy-compression.idf"  in EnergyPlusDevSupport was not the correct file, since it did not use an absorption chiller. I found the original help desk ticket and added the file that did have the absorption chiller called "easy-4.idf". Even after upgrading the file, it still had multiple problems so instead created a new test file called "IndirectAbsorptionChiller_wBlankWaterFlowRate.idf" that demonstrates the problem. During the summer design day, the BIG CHILLER with zeroed water flow rates shows no operation.
