### ISSUE TITLE
Accumulated output variable and meters need to reset to zero at end of warmup when ReportDuringWarmup is active

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4410]
Helpdesk Ticket 9250

Needs an issue posted - reset accumulated output variables and meters at end of warmup.
 Michael J. Witte on 29 March 2014 12:38 AM

On Fri, Mar 28, 2014 at 5:28 PM, EnergyPlus Support <
support@energyplus.helpserve.com> wrote:

 > The values in the ABUPS table are correct. The values in the meter file
 > are incorrect because ReportDuringWarmup is active. If you turn that off,
 > the values agree.
 >
 > Given how the output processor is structured I can see why it would work
 > this way, because the "annual" values do match the sum of hourly values
 > across the whole run period (including the values reported during warmup).
 > But this should probably be changed so that any accumulated output
 > variables and meters are all reset to zero after warmup - regardless of the
 > ReportDuringWarmup setting. Or at a minimum it should generate a warning.
 >
 > Mike
 >
 >
 > > Jeremiah,
 > >
 > > The DistrictCooling numbers seems the same to me. 11284379222 J from
 > > the meter file when converted into GJ is 11.28 which matches the value
 > > shown in the ABUPS table.
 > >
 > > The DistrictHeating HVAC value difference I do not understand.I will
 > > try to figure out what is going on by looking at the source code.
 > >
 > > Jason

User files
R9-YurtOffice.idf

**Comment by JasonGlazer** [comment]
@mjwitte @Myoldmopar EnergyPlus has many flags as you know. I am going to need to add a routine to zero the meter and variable accumulation when ReportDuringWarmup is active. Any recommendation on which flag or combination of flags makes the most sense?

**Comment by JasonGlazer** [comment]
Already mostly complete so it should be able to be in EnergyPlus 8.4

**Comment by mjwitte** [comment]
Closed via #5072
