### ISSUE TITLE
Docs not consistent with what code is doing for "Difference Schedule"

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4414]
Helpdesk Ticket 9427

Posted on: 19 May 2014 07:56 PM
I was referring to the SizingPeriod:DesignDay object, where there 
 might be "difference Schedule" usage.

 e.g. the field :Dry-Bulb Tmperature Range Modifier Type and subsequent
 field: Dry-Bulb Temperature Range Modifier Day Schedule Name

 Or Humidity Condition type and WetBulbProfileDifferenceSchedule.

 (Hopefully, these are already consistent in the SizingPeriod:DesignDay object)

 That is, where we have a "difference schedule", the Sky Temperature 
 object should follow the same rules.
 Linda 

Posted on: 19 May 2014 06:26 PM
Yes, if you confirm what I am seeing, then the documentation needs to be changed to reflect what the source code is actually doing.

 Linda responded last Tuesday with “I would want it to be consistent with the other "difference schedule" actions -- such as in the Design Day definition.”. Not sure exactly what is meant by this… I assume that the Design Day definition also has a difference schedule offset input, and she suggests that the source code for that offset be consistent with the one that I am finding in the WeatherProperty:SkyTemperature object. For example, if the equation is “Y= X - OffsetScheduleValue”, the this should be consistent for both the “Design day definition” (Linda) and the “WeatherProperty:SkyTemperature” object. It might be confusing if the equation was “Y = X + Offset” for some objects and “Y = X – Offset” for other objects.

 From: EnergyPlus Support [mailto:energyplus-support@gard.com]
 Sent: Monday, May 19, 2014 2:11 PM
 To: Don Shirey
 Subject: [EnergyPlus #9427]: WeatherProperty:SkyTemperature object

 So, it sounds like we just want to change the docs to match what the code is doing? And also need to verify what DifferenceScheduleDewPointValue value is doing as well, in object WeatherProperty:SkyTemperature.
 Mike

Posted on: 13 May 2014 09:48 PM
It sounds like you've already figured out what the code does...

 I would want it to be consistent with the other "difference schedule" actions -- such as in the Design Day definition.
 Linda 

Posted on: 12 May 2014 04:56 PM
In the IO reference, it says:

 Field: Calculation Type
 Allowable entries here are: ScheduleValue, DifferenceScheduleDryBulbValue, or DifferenceScheduleDewPointValue. In each case the following field must specify a valid
 schedule name. ScheduleValue - the values in the schedule are used as the sky temperature. DifferenceScheduleDryBulbValue - the values in the schedule are used as a
 difference to the drybulb temperature value (+values would then be greater than the drybulb temperature, -values would then be less than the drybulb temperature) for the resulting sky
 temperature value. DifferenceScheduleDewPointValue - the values in the schedule are used as a difference to the dewpoint temperature value (+values would then be greater than
 the dewpoint temperature, -values would then be less than the dewpoint temperature) for the resulting sky temperature value.

 I was trying to use the "DiffferenceScheduleDryBulbValue" type... with sky temperature 6 degrees C below the outdoor dry bulb temperature.

 I entered a Compact:schedule with value of -6, per the guidance above. However, it looks like the "Site Sky Temperature" output variable is 6C higher than the outdoor dry-bulb temperature... instead of 6C below.

 So, I changed the schedule value to +6, and the "Site Sky Temperature" output variable shows 6C below the outdoor dry-bulb temperature.

 Please see attached IDF and weather file.

 Please test and confirm my suspicion that the IO Ref text is backwards from what is actually being done in source code.... else correct me in my interpretation of the text writeup.

 Thanks,
Don Shirey

User files
in.epw
in26_Sky TempMode.idf

**Comment by jmarrec** [comment]
https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/WeatherManager.cc#L3653:L3661

It does `Value - ScheduleValue`, which happens to already be the same as what's done in the `SizingPeriod:DesignDay`, so confirmed it's the doc that need to change, not the code.
See #7015 

> Field: Dry-Bulb Temperature Range Modifier Type
> 
> If you specify DifferenceSchedule in this field, then you need to create a day schedule that specifies a number to be subtracted from dry-bulb maximum temperature for each timestep in the day. Note that numbers in the delta schedules cannot be negative as that would result in a higher maximum than the maximum previously specified.
