### ISSUE TITLE
Green roof simulation stability check suggests using 120 timesteps per hour

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4418]
Helpdesk Ticket 9038

Ecoroof stability check needs better documentation - looks to me like there's a certain minimum depth at which 60 timesteps become insufficient and you should switch to the simple method? Also, the error check needs to check and not tell you to use something greater than 60.  This could just be some updates to the error message.

User file Green roof simulation.idf - can run with any epw to see the error.

 Michael J. Witte on 23 January 2014 08:15 PM

Well, that's interesting. Clearly the error needs to check against the maximum possible number of timesteps. Is this important? I'm not really sure. The simulation will run even though this stability test fails. Here is the test:

 !This loop outputs the minimum number of time steps needed to keep the solution stable
 !The equation is minimum timestep in seconds=161240*(2)**(-2.3))*(Total thickness of the soil)**2.07

 This test is only used when the Moisture Diffusion Calculation Method = Advanced. If I am following this correctly, this problem occurs when the Material:RoofVegetation Thickness goes below a certain value. So, for thinner soil layers, you should probably switch to the Simple moisture diffusion calculation method.

 Mike

> I am simulating a green roof and I get this severe error:
 > ............
 > Program Version,EnergyPlus-Windows-64 8.1.0.008, YMD=2014.01.23
 > 11:04,IDD_Version 8.1.0.008
 > 
 > ** Severe ** CalcEcoRoof: Too few time steps per hour for stability.
 > ** ~~~ ** ...Entered Timesteps per hour=[60], Change to some value
 > greater than [120] for assured stability.
 > ..........
 > 
 > The program tells me to increase the time steps but the maximum value
 > I can introduce is 60. Could you please help me?
 > 
 > Thank you very much.

**Comment by Myoldmopar** [comment]
Fixed by #5198
