### ISSUE TITLE
Surface Window Front and Back Face Temperature report zeroes for plain windows - output not set up correctly

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4420]
Helpdesk Ticket 9049

Zone,Average,Surface Window Front Face Temperature Layer 1 [C]
 Zone,Average,Surface Window Back Face Temperature Layer 1 [C]

 These should only get setup for windows which are Construction:ComplexFenestrationState, unless we can figure out how to report these for all window types. It appears there are values of thetas that are the layer-by-layer temps in the standard window model. See also Ticket 9013

 Michael J. Witte on 28 January 2014 10:06 PM (Edited by Michael J. Witte on 28 January 2014 10:09 PM)

Posted on: 28 January 2014 10:04 PM

I have confirmed that these output variables for front and back face layer temperatures are only active when using complex fenestration (Construction:ComplexFenestrationState). They should not even appear in the output for other window types. I will submit a request to get this fixed. For standard windows, you can use these output:variables to report the innermost and outermost glass face temperature.

 Surface Inside Face Temperature [C]
 Surface Outside Face Temperature [C]

 Mike

> > I try to run EP in the basic case ( A room with 1 window+Venetian
> > blind on the west wall).Some output variables can be figured out
> > but
> > "Surface Window Front and back Face Temperature" show "0 value" in
> > anytime. I don't know how to show the true values of them.
> 
> Which type of window model are you using? I am not sure these
> variables are active for all of the window models. It would be helpful
> to see your idf file to confirm.
> 
> Mike

Naparat
User
Posted on: 26 January 2014 08:03 AM

I try to run EP in the basic case ( A room with 1 window+Venetian blind on the west wall).Some output variables can be figured out but "Surface Window Front and back Face Temperature" show "0 value" in anytime. I don't know how to show the true values of them.

User files
01clear6mm_1.idf

**Comment by mjwitte** [comment]
Came up again in helpdesk ticket 11027.  Adding priority to get this fixed.

**Comment by RKStrand** [comment]
Just verified that this is still a bug.  Will be working to fix it for the upcoming release.

**Comment by Myoldmopar** [comment]
Closed via #7474
