### ISSUE TITLE
Problems with LowTemperatureRadiant and <blank> tube length

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4425]
Helpdesk Ticket 3956

User had a blank for tubing length, yet the IDD says autosize or minimum>0 ??

 N2 , \field Hydronic Tubing Length
 \note (total length of pipe embedded in surface)
 \units m
 \minimum> 0
 \autosizable

 ZoneHVAC:LowTemperatureRadiant:VariableFlow,
 sporthalle FH, !- Name
 HeatingPlantOnSched, !- Availability Schedule Name
 sporthalle, !- Zone Name
 509647, !- Surface Name or Radiant Surface Group Name
 0.013, !- Hydronic Tubing Inside Diameter {m}
 , !- Hydronic Tubing Length {m}
 Richard Raustad on 11 March 2011 02:18 PM
 

User:
Eh, about the LowTemperatureRadiant, I find that I made a stupid fault. I forgot to set the Tubing length.Sorry to trouble you.

**Comment by wfbuhl** [comment]
I'll do this

**Comment by wfbuhl** [comment]
The default is simply HydrRadSys().TotalSurfaceArea / 0.15 . This default can be set without a sizing run, so autosize may be inappropriate. Or just not call CheckZoneSizing for this input. I guess I'll do that.

**Comment by mjwitte** [comment]
Closed via #5196 (which was merged on Sep 15, 2016)
