### ISSUE TITLE
Boiler "Design Water Outlet Temperature" confusing - update docs or delete field entirely

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4431]
Helpdesk Ticket 6893

Should probably add something to I/O ref about the boiler design water outlet temp being nearly useless, or make it autosizeable so it grabs the plant sizing water outlet temp?

 Michael J. Witte on 21 January 2013 06:58 PM

Boiler "Design Water Outlet Temperature" seems rather pointless, should probably remove it

  Michael J. Witte on 07 May 2014 04:26 PM

From: EnergyPlus Support [mailto:energyplus-support@gard.com]
 Sent: 21 January 2013 18:57
 To: Andy Tindale

> 1. Also for Boiler:HotWater, could you explain how these temperatures are used in simulations?
> - Design Water Outlet Temperature. Under what circumstances would this be given a value other than "Autosize"?

 Autosize would be a nice option for this field, but it's not even autosizeable. This field is somewhat pointles, it's only purpose is for calculating a Cp value to autosize boiler capacity from design deltaT (sizing:plant) and boiler design flow rate. I suppose if user were putting two boilers in series, they might set one boiler to output at a lower temp than the second boiler, but it will have a negligible impact on the simulation.

> - Water Outlet Upper Temperature Limit

 This is used to cap the output from the boiler when the boiler is operating at less than the design flow rate, or when the return water temperature is warm. Similar to the lower temp limit on chillers.

 Mike

**Comment by Myoldmopar** [comment]
Closed via #6816
