### ISSUE TITLE
AirTerminal:SingleDuct:ConstantVolume:FourPipeInduction needs better error message when mixer name left blank

### ISSUE THREAD

**Issue by BobHenninger** [NREL/EnergyPlus#4438]
Helpdesk Ticket 8952
User did not specify a Zone Mixer Name for AirTerminal:SingleDuct:ConstantVolume:FourPipeInduction units (left that field blank) and this is the entire error message that resulted, so user couldn't tell what the problem was:

   **  Fatal  ** SimAirLoopMixer: Mixer not found=

 Richard Raustad on 26 December 2013 03:14 AM
Code implies mixer is not required so this may be a problem (i.e., search for YesNo in HVACSingleDuctInduc.f90).

1.  Is the Zone Mixer Name really required?  IDD doesn't show it as a required field.

2.  If it is required, then IDD should be tagged that way.  That's probably an adequate fix, but the object getinput should probably be trapping this as well.

User files
Base_Modell_Office_MSW.idf

**Comment by wfbuhl** [comment]
It needs a mixer:

  SimAirMixer( IndUnit( IUNum ).MixerName, IndUnit( IUNum ).Mixer_Num );

The name should be required in the IDD.

**Comment by mjwitte** [comment]
@wfbuhl Thanks for confirming that the mixer is required.  Do you want to fix, or shall I?  Waiting, of course until after the big new feature push this week.

**Comment by wfbuhl** [comment]
I can do it
