### ISSUE TITLE
User file with AFN fails with iteration error in 64-bit but not in 32-bit

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4449]
Ticket 6712
This has been lingering for a while, since v7.2, this user's file completes on 32-bit windows, but fails with this fatal error in 64-bit version:
   ** Severe  ** Too many iterations (SOLVZP) in Airflow Network simulation
   ** Warning ** AirflowNetwork: SOLVER, Changing values for initialization flag, Relative airflow convergence, Absolute airflow convergence, Convergence acceleration limit or Maximum Iteration Number may solve the problem.
   **   ~~~   **  Environment=EX, at Simulation time=01/09 07:30 - 07:45
   **   ~~~   ** ..Iterations=500, Max allowed=500
   **  Fatal  ** AirflowNetwork: SOLVER, The previous error causes termination.

Same behavior seen in v8.1.  
v8.2 (Aug 26 source) 64-bit fails with same error - have not built a 32-bit exe to see if it behaves differently.

**Comment by jasondegraw** [comment]
For version 8.3.3-c673d878f0, both 64 and 32 bit versions (both release and debug) fail to converge at the same time/date, so I'm going  to close this.
