### ISSUE TITLE
Chiller:Electric:EIR still delivering chilled water when shut off due to zero condenser loop flow

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4453]
Helpdesk ticket 9704
User file has a fancoil unit with a water cooled Chiller:Electric:EIR. This file happens to have a flow rate schedule on the condenser water pump that is all zeros.  This results in zero chiller heat transfer reported and zero chiller power consumed, but the chilled water coil is merrily providing cooling and the chiller ChW inlet and outlet nodes show flow and show that the chiller is operating - but it's not.

**Comment by EnergyArchmage** [comment]
it may be that the apparent cooling is really coming from changes in plant loop volume's heat capacity.  

turn on advanced report variables and check value of Plant Supply Side Lumped Capacitance Temperature, if the temperature is changing that could be the source of cooling

**Comment by lgu1234** [comment]
I am going to take a look. Thanks for a good suggestion.

**Comment by lgu1234** [comment]
I fixed the chiller code to ensure no mass flow rates in both evaporator and condenser and outlet node conditions are equal to inlet node conditions. However, zone still receives small amount of cooling.

**Comment by lgu1234** [comment]
The revised code of ChillerElectricEIR was committed.

**Comment by EnergyArchmage** [comment]
I did a code review of https://github.com/NREL/EnergyPlus/commit/666529b28c8bd40a2bb4c959a3b86e5febd69c95  comparing to develop.  And these changes seem okay.  Pathological case of no condenser flow is more robust.

**Comment by lgu1234** [comment]
@EnergyArchmage Thanks for your review. I ran all example input files last week and found differences in an example input file: 5ZoneVAV-ChilledWaterStorage-Mixed_DCV_MaxZd.idf.

**Comment by mjwitte** [comment]
@lgu1234 What is the status of this?  I see a branch, but there is no pull request.

**Comment by lgu1234** [comment]
@mjwitte I fixed the code of ChillerElectricEIR. @EnergyArchmage reviewed my changes. He was Ok with the changes. Then I debugged the code again and found update of water coil outlet node was not performed, after plant is converged. I think I may close this issue and make a pull request. Then a new issue may be created to address node updates

**Comment by mjwitte** [comment]
@lgu1234 #4920 was merged by @Myoldmopar Can this issue be closed now?  Have you posted a new follow-up issue?

**Comment by lgu1234** [comment]
@mjwitte I think this issues should be closed. Please close it. I am going to make a new follow-up issue.

**Comment by lgu1234** [comment]
A new follow-up issue is #4931
