### ISSUE TITLE
Missing testfiles

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4470]
@Nigusse @rraustad @lgu1234 @mjwitte

The CI machines are reporting [problems with a couple files](http://nrel.github.io/EnergyPlusBuildResults/EnergyPlusTeam-14297e7281b3b0b77a341b881e9c20f87f89a78d-x86_64-MacOS-10.9-clang.html#test).  Basically it is complaining because it couldn't find 5ZoneWaterCooled_BaseboardScalableSizing or FanCoilAutoSizeScalableSizing.  These were added to the CMakeLists file in commit 37e011758e0fbee3b34dc93abc4d614121ae2ddf.  However, the idfs were never actually added to the repository.  Thus, the CI machines try to run those files, but they aren't found.  These files need to be added.

**Comment by mjwitte** [comment]
@lefticus @Myoldmopar Is this still an open issue?

**Comment by Myoldmopar** [comment]
Nope.
