### ISSUE TITLE
Disable popup dialog on Windows release after exception and add traceback

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4471]
Using the default cmake build options with VS12 on windows, if the exe crashes, it throws up a dialog box which halts everything, preventing a batch file from moving on to the next simulation.  The fortran exe's would dump a traceback and exit so the batch could move on.

**Comment by mjwitte** [comment]
Pop-up dialog has been fixed, traceback has not been added yet.  Leaving this open since dialog about traceback is here, but lowering priority.

**Comment by Myoldmopar** [comment]
We'll try to handle traceback later, closing this.
