### ISSUE TITLE
Sizing:System new fields need defaults to prevent fatal error from transition for new scalable sizing

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4484]
When transitioning from v8.1 to v8.2, transition adds new fields at the end of sizing:system

    ,                        !- Cooling Design Capacity Method
    ,                        !- Cooling Design Capacity {W} {m3/s}
    ,                        !- Cooling Design Capacity Per Floor Area {W/m2}
    ,                        !- Fraction of Autosized Cooling Design Capacity {-}
    ,                        !- Heating Design Capacity Method
    ,                        !- Heating Design Capacity {W} {m3/s}
    ;                        !- Heating Design Capacity Per Floor Area {W/m2}

which result in a fatal error:
   ** Severe  ** Sizing:System = VAV SYS 1
   **   ~~~   ** Input for Cooling Design Capacity Method = COOLINGDESIGNCAPACITY
   **   ~~~   ** Blank field not allowed for Cooling Design Capacity {W}
   ** Severe  ** Sizing:System = VAV SYS 1
   **   ~~~   ** Input for Heating Design Capacity Method = HEATINGDESIGNCAPACITY
   **   ~~~   ** Blank field not allowed for Heating Design Capacity {W}
   **  Fatal  ** Sizing:System: Errors found in getting input. Program terminates.

So, add \default autosize to the Cooling Design Capacity Method (and Heating) fields.

**Comment by mjwitte** [comment]
@Myoldmopar Not sure of the status here if all the loose ends are tied up.  Upping priority to make sure this is working right.

**Comment by mjwitte** [comment]
@Myoldmopar Can this issue be closed?

**Comment by Myoldmopar** [comment]
Yeah, this was addressed already.
