### ISSUE TITLE
Remove support for obsolete load management options in HVACTemplate:Plant objects

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4493]
Currently HVACTemplate:Plant:* objects have input for Load Distribution Scheme that have choices of Sequential, Uniform, and Optimal.  These are really just a pass-through to the plantloop and condenserloop object, so I could add the new keywords as choices in the IDD.

@Myoldmopar  If you don't object, I'm going to add the correct new key choices to the IDD (to match what's in the plantloop and condenserloop objects) as part of my expand objects update.  And I will change expandobjects to accept any of those, including the old sequential.

This issue will remain open until after v8.2 release to add a new transition rule to convert any old Sequential or Uniform inputs to SequentialLoad and UniformLoad, unless you want to bite the bullet and to that for this round.

**Comment by mjwitte** [comment]
@Myoldmopar Working on this cleanup that requires a transition rule.  What is our current process for new transition rules?

**Comment by mjwitte** [comment]
Notes to self here:  Only one HVACTemplate example file has the load distribution fields included:
HVACTemplate-5ZoneUnitarySystem.idf has four occurrences of "Sequential".

**Comment by Myoldmopar** [comment]
Closed with #4930

**Comment by Myoldmopar** [comment]
Wait, what transition rule?  It looked like it just changed the ExpandObjects code and an out of date example file?

**Comment by mjwitte** [comment]
@Myoldmopar Transition from the old Sequential and Uniform keywords was never done for HVACTemplate objects.

**Comment by Myoldmopar** [comment]
Aaaah OK, I'll add that in a separate branch, please hold.  And yeah, this is the first transition rule for this cycle, so I might make a change or two...

**Comment by Myoldmopar** [comment]
OK, so @mjwitte, I will go back and update the transition rules for 8.1 to 8.2 like [so](https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/CreateNewIDFUsingRulesV8_2_0.f90#L370). Do I also need to put something special in the current 8.3 to 8.4 to catch previously missed versions?

**Comment by mjwitte** [comment]
Thanks. Yes.

<div>-------- Original message --------</div><div>From: Edwin Lee notifications@github.com </div><div>Date:06/29/2015  3:58 PM  (GMT-05:00) </div><div>To: NREL/EnergyPlus EnergyPlus@noreply.github.com </div><div>Cc: "Michael J. Witte" mjwitte@gard.com </div><div>Subject: Re: [EnergyPlus] Remove support for obsolete load management options
  in HVACTemplate:Plant objects (#4493) </div><div>
</div>OK, so @mjwitte, I will go back and update the transition rules for 8.1 to 8.2 like so. Do I also need to put something special in the current 8.3 to 8.4 to catch previously missed versions?
