### ISSUE TITLE
Example file test error

### ISSUE THREAD

**Issue by krishnan-gowri** [NREL/EnergyPlus#4497]
When I open HospitalLowEnergy.idf from the example files folder in IDF editor, save it and run, I get the following error for DOAS systems:
Program Version,EnergyPlus, Version 8$.2.0, YMD=2014.09.26 08:38,IDD_Version 8.2.0
   *\* Severe  *\* Sizing:System="DOAS2", invalid data.
   *\*   ~~~   *\* ... incorrect System Outdoor Air Method="".
   *\*   ~~~   *\* ... valid values are ZoneSum or VentilationRateProcedure.
   *\* Severe  *\* Sizing:System="DOAS1", invalid data.
   *\*   ~~~   *\* ... incorrect System Outdoor Air Method="".
   *\*   ~~~   *\* ... valid values are ZoneSum or VentilationRateProcedure.
   *\* Severe  *\* Sizing:System="AHU3", invalid data.
   *\*   ~~~   *\* ... incorrect System Outdoor Air Method="".
   *\*   ~~~   *\* ... valid values are ZoneSum or VentilationRateProcedure.
   *\* Severe  *\* Sizing:System="DOAS5", invalid data.
   *\*   ~~~   *\* ... incorrect System Outdoor Air Method="".
   *\*   ~~~   *\* ... valid values are ZoneSum or VentilationRateProcedure.
   *\* Severe  *\* Sizing:System="DOAS4", invalid data.
   *\*   ~~~   *\* ... incorrect System Outdoor Air Method="".
   *\*   ~~~   *\* ... valid values are ZoneSum or VentilationRateProcedure.
   *\* Severe  *\* Sizing:System="DOAS6", invalid data.
   *\*   ~~~   *\* ... incorrect System Outdoor Air Method="".
   *\*   ~~~   *\* ... valid values are ZoneSum or VentilationRateProcedure.
   *\*  Fatal  *\* Sizing:System: Errors found in getting input. Program terminates.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=6
   ..... Last severe error=Sizing:System="DOAS6", invalid data.
   ************\* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************\* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************\* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************\* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 6 Severe Errors.
   ************\* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 6 Severe Errors; Elapsed Time=00hr 00min  2.00sec

**Comment by krishnan-gowri** [comment]
I am encountering a similar problem with zone sizing object when using the version updater to upgrade a V7.0 IDF to V8.2.  Can some one verify if the transition program is working correctly for zone sizing?

**Comment by mjwitte** [comment]
@krishnan-gowri I haven't heard of any issues with that.  Please e-mail me a sample idf that shows the problem.

**Comment by krishnan-gowri** [comment]
Attached is the v810 IDF file and the error message below for the 8.20 updated file.  The IDF editor shows the fields that have not been mapped to the new IDD.

-krishnan

Program Version,EnergyPlus, Version 8.2.6-7a3291d661, YMD=2015.02.27 13:01,IDD_Version 8.2.6
   ************* IDF Context for following error/warning message:
   ************* Note -- lines truncated at 300 characters, if necessary...
   *************    826   Sizing:Zone,
   ************* indicated Name=aim0014
   ************* Only last 6 lines before error line shown.....
   *************    827     aim0014,                 !- Zone or ZoneList Name
   *************    828     14,                      !- Zone Cooling Design Supply Air Temperature Input Method
   *************    829     50,                      !- Zone Cooling Design Supply Air Temperature {C}
   *************    830     0.008,                   !- Zone Cooling Design Supply Air Temperature Difference {deltaC}
   *************    831     0.004,                   !- Zone Heating Design Supply Air Temperature Input Method
   *************    832     SZ DSOA aim0014,         !- Zone Heating Design Supply Air Temperature {C}
   ** Severe  ** IP: IDF line~832 Invalid Number in Numeric Field#3 (Zone Heating Design Supply Air Temperature), value=SZ DSOA AIM0014, in SIZING:ZONE=AIM0014
   ************* IDF Context for following error/warning message:
   ************* Note -- lines truncated at 300 characters, if necessary...
   *************   1217   Sizing:Zone,
   ************* indicated Name=aim0277
   ************* Only last 6 lines before error line shown.....
   *************   1218     aim0277,                 !- Zone or ZoneList Name
   *************   1219     14,                      !- Zone Cooling Design Supply Air Temperature Input Method
   *************   1220     50,                      !- Zone Cooling Design Supply Air Temperature {C}
   *************   1221     0.008,                   !- Zone Cooling Design Supply Air Temperature Difference {deltaC}
   *************   1222     0.004,                   !- Zone Heating Design Supply Air Temperature Input Method
   *************   1223     SZ DSOA aim0277,         !- Zone Heating Design Supply Air Temperature {C}
   ** Severe  ** IP: IDF line~1223 Invalid Number in Numeric Field#3 (Zone Heating Design Supply Air Temperature), value=SZ DSOA AIM0277, in

Krishnan Gowri, Ph.D., LEED AP
Principal Engineer – Buildng Performance Analysis
MOBILE +1 425 273-0190

**Comment by mjwitte** [comment]
Turns out the v810 idf file was partially 8.2.0 but not fully 8.2.0. The file was likely transitioned from 8.1.0 to an intermediate development version and needed to be retransitioned back from clean 8.1.0.  Common problem with partial transition utilities being released during development cycles.
