### ISSUE TITLE
EIO Surface Details Alignment problem

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4509]
The alignment for the surface details report in the EIO is off, for at least the units column headers. Excel file showing this is in DevSupport.  

When I look at the file, the main header and values seem to be aligned, but the units are off.  Should be easy enough to fix this....probably [here](https://github.com/NREL/EnergyPlusTeam/blob/f14e14ca0bcf869700eaf3f83e20a37284e0a7e3/src/EnergyPlus/OutputReports.cc#L1702).

**Comment by mjwitte** [comment]
@Myoldmopar This is still off in 8.2.9.  Again, could fix easily but will cause eio diffs.

**Comment by mjwitte** [comment]
Addressed in #5123.  Tested for all three flavors of Output:Surfaces:List with Details, Vertices, and DetailsWithVertices.

**Comment by mjwitte** [comment]
Closed vis #5123
