### ISSUE TITLE
EnergyPlus.f90 appears in source

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4510]
There are lots of [places](https://github.com/NREL/EnergyPlusTeam/search?q=energyplus.f90) in the code where ```EnergyPlus.f90``` still appears.  There may be other random references to FORTRAN in there that we could clean up over time, but this would be one big quick fix to clean up a bunch of references.  

Maybe I'll assign @mmatts since he brought it up :wink:.  OK, I did.  But I can certainly do it or help do it or whatever.

**Comment by mjwitte** [comment]
@mmatts @Myoldmopar Has this been addressed?  If so, please add a reference to the pull request(s) and close this issue.

**Comment by mmatts** [comment]
@mjwitte I think all that is left are references to FORTRAN within comments. I'd say it's done for now. @Myoldmopar your thoughts?

**Comment by Myoldmopar** [comment]
Yeah, let's call this done.  @mmatts Can you reference the pull request where you had cleaned up some of this?

**Comment by mmatts** [comment]
PR #4551
