### ISSUE TITLE
Update Pipe:Underground object documentation to refer to correct ground surface temperature object

### ISSUE THREAD

**Issue by mmatts** [NREL/EnergyPlus#4526]
K-A fields in the Pipe:Underground IO Ref section refer to the "GroundTemperature:Surface" object when they should refer to the Site:GroundTemperature:Shallow object. Update docs to reflect this.

**Comment by Myoldmopar** [comment]
@mmatts Could you address this tiny doc fix?

**Comment by Myoldmopar** [comment]
Fixed with #5100
