### ISSUE TITLE
IDF Editor IDD Version number format

### ISSUE THREAD

**Issue by krishnan-gowri** [NREL/EnergyPlus#4528]
Currently when files are created/saved from IDF Editor, the Version Identifier is included as 8.2; when this is compared to IDD version number 8.2.0, a warning is posted in the .err file as having incompatible IDD.  I guess the literal version number comparison and inconsistent number format in IDF Editor may be causing this warning.

**Comment by mjwitte** [comment]
@krishnan-gowri I cannot reproduce this, even with v8.2.0 (before Update 1).  I think this was relaxed at some point along the way.
