### ISSUE TITLE
Need docs and example file for Add DOA to zonal units capability to packaged water-to-air heat pumps

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4530]
This feature was added after v8.1.0.009 release but prior to moving to C++ and github. An example file and doc changes got lost in the shuffle.  These changes relate to 

AirTerminal:SingleDuct:InletSideMixer and AirTerminal:SingleDuct:SupplySideMixer which both have this pair of fields:

   A2, \field ZoneHVAC Terminal Unit Object Type
       \required-field
   A3, \field ZoneHVAC Terminal Unit Name
       \required-field

These fields should be changed to be \type choice (with keys for the currently supported equipment types) and corresponding \object-list for the name field.

The I/O Ref currently states:
Field: ZoneHVAC Terminal Unit Object Type
The type of zone AC unit to which this terminal unit will be connected. Currently only ZoneHVAC:FourPipeFanCoil can be used.

So, this needs to be changed to include newly supported equipment.
(This documents an e-mail discussion with @wfbuhl on 14 Oct 2014)

**Comment by Myoldmopar** [comment]
@wfbuhl This is still an issue (at least the IDD field stuff).  Would you be able to address this?

**Comment by wfbuhl** [comment]
Yes

**Comment by wfbuhl** [comment]
The example files are already there. Changing IDD to use choice field and \object-list. Updating the IO Ref. Branch will be Issue4530UpdateIDDandIORefDOAToZonalUnits.

**Comment by wfbuhl** [comment]
This is pushed up and a pull request issued

**Comment by mjwitte** [comment]
Closed via #5180
