### ISSUE TITLE
v8.2.0 Installer Issues

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4532]
1. Some example files still say version 8.1 in the idf file. (imf files and ones that were new since v8.1, and ??)

2. AbsorptionChiller_Macro.imf has this line at the top:
##fileprefix <needs path from install>
the installer is supposed to replace this with the install path, e.g.:
##fileprefix C:\EnergyPlusV8-2-0\ExampleFiles\

3.  VB runtime library components are missing on some machines (maybe missing on all clean machines that haven't had an earlier install of EnergyPlus which used to copy these into the system folders).

**Comment by mjwitte** [comment]
@kbenne @Myoldmopar 
1. old version numbers have been addressed.  
2. AbsorptionChiller_Macro.imf installs with the fileprefix line commented out !##fileprefix <needs path from install> (v8.2.9) - Do we plan to change that?
3. missing VB components have been addressed.
4.  New item - found some of the example files have old output:preprocessor messages that can probably be removed.

```
MicroCogeneration.idf
  Output:PreprocessorMessage,
    EPXMLPreProc2,           !- Preprocessor Name
    warning,                 !- Error Severity
    Problem with the width for requested floor area and,  !- Message Line 1
    perimeter depth.  Reduced perimeter depth from 4.57,  !- Message Line 2
    to 3.656 to accomodate perimeter and core layout;  !- Message Line 3

MovableIntInsulationSimple.idf
  Output:PreprocessorMessage,
    Conversion 8.1 => 8.1.0.004,  !- Preprocessor Name
    Warning,                 !- Error Severity
    rvi file associated with this input is being processed. Review for accuracy.;  !- Message Line 1

_1a-Long0.0.idf
  Output:PreprocessorMessage,
    Conversion V7 to V7.1,   !- Preprocessor Name
    Warning,                 !- Error Severity
    SizingPeriod:DesignDay object="LONDON/GATWICK Modified Ann Clg .4% Condns DB=>MWB",  !- Message Line 1
    Solar Model Indicator="Schedule",  !- Message Line 2
    does not use Sky Clearness but prior input was not blank. Copied to new field.;  !- Message Line 3

I can do these if you like, but it will cause err diffs, so don't want to clutter up CI results.
```

**Comment by Myoldmopar** [comment]
@mjwitte For the macro file, I don't plan to manipulate the installer to overwrite the file prefix line.  I'll add the preprocessor messages into the issue for 8.4.0 and close this one.  If you feel differently, just re-open.
