### ISSUE TITLE
Coil:Cooling:DX:MultiSpeed requires Waste Heat Function of Temperature Curve Name when it should not

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4536]
Helpdesk ticket 9914
For Coil:Cooling:DX:MultiSpeed, the I/O Ref states:

Field: Speed <x> Waste Heat Function of Temperature Curve Name
The name of a biquadratic performance curve (ref: Performance Curves) that parameterizes
the variation of the waste heat recovery as a function of outdoor dry-bulb temperature and the
entering coil dry-bulb temperature at Speed <x>. The output of this curve is multiplied by the
rated waste heat fraction at specific temperature operating conditions (i.e., at temperatures
different from the rating point). The curve is normalized to a value of 1.0 at the rating point.
When the fuel type is electricity, this field can remain blank since it is ignored by the program
in this instance.

Currently it appears that this curve name(s) cannot be left blank.  It should at least match what is stated above.  Next, if nothing is connected to the parent unit waste heat nodes, then all the waste heat fields should be optional.  Third, it seems this curve could always be optional and simply use the flat waste heat fraction.

A defect file has been commited that uses electricity and has these curve names blank.  If we just change to match current I/O Ref, this file should run error free.

**Comment by mjwitte** [comment]
@lgu1234 Do you plan to address this issue?

**Comment by Myoldmopar** [comment]
@lgu1234 Do you plan to address this issue?

**Comment by lgu1234** [comment]
Yes.

**Comment by lgu1234** [comment]
@mjwitte I made 3 steps to fix this issue. This fix allows blank curve names of waste heat functions of two coil types: Coil:Heating:DX:MultiSpeed and Coil:Cooling:DX:MultiSpeed, when fuel type is electricity.

Then I will create an issue to address the second request: if nothing is connected to the parent unit waste heat nodes, then all the waste heat fields should be optional.

**Comment by mjwitte** [comment]
Closed via #5144
