### ISSUE TITLE
Add a flow fraction schedule to AirTerminal:SingleDuct:Uncontrolled

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4537]
Reference user question on unmethours: "How to trim down air flow at night for a make up air unit in OpenStudio?"

https://unmethours.com/question/449/how-to-trim-down-air-flow-at-night-for-a-make-up-air-unit-in-openstudio/

Adding a flow fraction schedule to AirTerminal:SingleDuct:Uncontrolled would give a lot of flexibility for cases such as this and should be a fairly simple addition with no transition requirement.

**Comment by Myoldmopar** [comment]
This can be done now; closing.
