### ISSUE TITLE
I/O Ref - DesignSpecification:ZoneHVAC:Sizing is misplaced

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4545]
Helpdesk Ticket 9927

In EnergyPlus 8.2, a new object "DesignSpecification:ZoneHVAC:Sizing" was added. In IDF Editor, the object shows up in the group "HVAC Design Objects", however, in I/O Reference document, it is placed in the group "Zone Forced Air Units". This creates some confusion for people to find the documentation.

Also noticed there are several occurences of "DesignSpecificationZoneHVACSizing" which should be "DesignSpecification:ZoneHVAC:Sizing".

**Comment by Myoldmopar** [comment]
Fixed by #5198
