### ISSUE TITLE
Missing run-time files for EP-Launch and IDF Editor with Windows v8.2.0 Installer 

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4547]
Helpdesk tickets 9893, 9908, 9926, 9932, 9934, 9936

Several users have run into missing file errors when trying to run EP-Launch and IDF Editor on Windows with v8.2.0.  File names include MSINET.OCX, ComDlg32.OCX, vsflex7L.ocx, MSCOMCTL.OCX

These are run-time files required by VB6.0 which were previously included in the EnergyPlus installer.  @kbenne Suggested directing user to Visual Basic 6.0 SP6 run-time files

http://support2.microsoft.com/kb/290887

but this is not sufficient (or maybe not relevant).  Per @JasonGlazer "that doesn't include vsflex7l.ocx. That is from a third party plug-in called VSFlexGrid that is used with IDF Editor.  This component cannot be found from a reputable vendor anymore." And MSINET.OCX is the file that allows EP-Launch to check the internet for updates.

Any system which had EnergyPlus v8.1.0 or prior installed will likely have these files and not have a problem with v8.2.0.  (In future we need to be sure to test the installer on a clean Windows system.)

Workaround:  Presently advising users to install v8.1.0 next to v8.2.0.

**Comment by fireattack** [comment]
msinet.ocx is still missing for 8.3 release.

**Comment by bachc** [comment]
Tried the 8.3.3 installer (EnergyPlus-8.3.3-c673d878f0-Windows-x86_64.exe on Windows 8.1 enterprise, 64 bit Intel i7) and am missing MSCOMCTL.OCX when attempting to run EP-Launch. I think this issue might not (yet) be closed.

**Comment by MikeBarcl** [comment]
I also had this issue when installing 8.5 and 8.6 recently. The work around of installing 8.2 first worked for me though.  
workaround mentioned here ... https://github.com/NREL/EnergyPlus/issues/5105
