### ISSUE TITLE
AirTerminal:SingleDuct:ConstantVolume:CooledBeam Active/Passive has very little impact

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4548]
Helpdesk ticket 9935

From user:  "I've run a model using the AirTerminal:SingleDuct:ConstantVolume:CooledBeam object and when I compare the difference between Active and Passive cooled beam type the results are exactly the same.

 The only change in the idf was the Cooled Beam Type field (Active or Passive). Attached is the Active example model.

 How EnergyPlus code deals with these two options? 
 Is there any other field related with the Cooled Beam Type that also requires to be changed accordingly?"

Reply:  " I see how changing just the Active/Passive field does nothing. Then I tried setting this field to "autocalculate":

 Field: Coefficient of Induction Kin (Kin)
 The coefficient of induction Kin in the above equations. The default is 2.0 for active beams and 0.0 for passive beams.

 The eio outputs indeed report 0.0 for the passive case and 2.0 for the active case, but the change in results is very tiny. I will post an issue to at least beef up the Input Output Reference and determine if the model is functioning as expected."
1.  I/O Ref implies that this field will override the Kin input:
   Field: Cooled Beam Type
   Two types of units are modeled: Active or Passive. In the active unit, primary air is supplied through the beam, inducing some secondary zone air into contact with the coil. This unit acts as an active convector. The passive unit is simply a passive, finned convector. Primary air is supplied through a normal diffuser.
2.  Kin input appears to have little effect on results.

test files checked in.

**Comment by Myoldmopar** [comment]
@EnergyArchmage With your recent work on beams, can you comment on whether there really is an issue here or if it can be closed?
