### ISSUE TITLE
User file fails with NAN in predicted load

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4557]
Helpdesk ticket 9913
This ticket has various issues going on, but after fixing some earlier problems, the file now fails with this error:

   ** Severe  ** DualSetPointWithDeadBand: Unanticipated combination of heating and cooling loads - report to EnergyPlus Development Team
   **   ~~~   ** occurs in Zone=OFFICES During Warmup, Environment=SUMMER DESIGN DAY IN BAD AXE MI JUL, at Simulation time=07/15 05:03 - 05:05
   **   ~~~   ** LoadToHeatingSetPoint=NAN, LoadToCoolingSetPoint=NAN
   **   ~~~   ** Zone Heating Set-point=21.70
   **   ~~~   ** Zone Cooling Set-point=23.30
   **   ~~~   ** Zone TempDepZnLd=NAN
   **   ~~~   ** Zone TempIndZnLd=NAN
   **   ~~~   ** Zone ThermostatSetPoint=0.00
   **  Fatal  ** Program terminates due to above conditions.

Running v8.2.0 64-bit on Win 8.1

**Comment by mjwitte** [comment]
Also helpdesk ticket 10301, use file showing similar symptom.

**Comment by mjwitte** [comment]
@rraustad So, the divide by zero error occurs in DXCoils.cc CalcMultiSpeedDXCoilCooling (currently line 9807):  hDelta = TotCapLS / AirMassFlow;
Because the incoming massflows are not consistent.  AirMassFlow is >0 when this routine is entered, but MSHPMassFlowRateLow and MSHPMassFlowRateHigh are both zero.  At the same time CompOn=0 but CycRatio = 1.0.  With CycRatio > 0.0, for this particular case AirMassFlow gets set to MSHPMassFlowRateLow (which is zero) and then is used to check airflow/capacity and is used in a denominator.

So, seems we should trap this right at the top of CalcMultiSpeedDXCoilCooling and if AirMassFlow>0 but MSHPMassFlowRateLow  and MSHPMassFlowRateHigh are zero, then stop, leave, or set MSHPMassFlowRateLow=AirMassFlow and MSHPMassFlowRateHigh=AirMassFlow?

I realize this doesn't really solve the issue of what it means to use setpoint based controls with a multispeed coil (is this even a valid combination - how do you determine flow rate?), but it protects against divide by zero.

**Comment by rraustad** [comment]
MSHPMassFlowRateLow and High need to be set by the parent each time the child is called if the speed changes. If these are 0 while flow is non-zero, that's a bug. This is done in SetOnOffMassFlowRate or  some similar routine (e.g. SetVSHPAirFlow in Furnaces).

**Comment by rraustad** [comment]
CompOn = 0? This subroutine doesn't act on CompOn? Should have bypassed calcs to a coil off condition if CompOn is actually used for this child.

**Comment by rraustad** [comment]
How did you find this? Somehow break when NAN is first found? I'd hate to think it was single stepping through the code.

**Comment by mjwitte** [comment]
@rraustad Well, you had already started pointing in the right direction, but yes it took a while. There was a lot of single-stepping, adding watches, and adding breaks and conditional breaks, then working back up the logic to add earlier breaks.  I wish I knew how to break on NAN - is that possible?

**Comment by DeadParrot** [comment]
@mjwitte The debug build on Linux should be trapping NANs with the `feenableexcept` setup and the `-fsignaling-nans`. That should let you backtrace in gdb to find the cause.

If you are on VC then someone needs to add the equivalent `_controlfp` setup.
