### ISSUE TITLE
HPWH coil removing heat from tank

### ISSUE THREAD

**Issue by ejhw** [NREL/EnergyPlus#4558]
Affects plant-loop connected heat pump water heaters (HPWH) but not HPWHs with scheduled draws (Use Flow Rate Fraction Schedule). Shows up in 8.2, but not 8.1. We confirmed that this was a byproduct of the fix to #4455. Might be related to updating of tank source side inlet/outlet temperatures.

The HeatPumpWaterHeater.idf example file has five HPWHs, in different configurations:
1.	Zone 5    - HPWH using mixer/splitter nodes to blend outdoor air with zone air
2.	Zone 4    - HPWH without mixer/splitter nodes using only zone air
3.	Outdoors  - HPWH located outdoors and not connected to a plant loop
4.	Scheduled - HPWH using scheduled ambient conditions
5.	Plant     - HPWH located outdoors and connected to a plant loop which serves zone 1-5 reheat coils and the main heating coil in the air loop.

Only (5) shows a difference in energy usage between E+ v8.1 and v8.2. I believe this is because it is the only HPWH connected to a loop via Use Side Inlet/Outlet Nodes, as opposed to a “Use Flow Rate Fraction Schedule.” Because we use a DHW loop in BEopt (as would most models doing detailed DHW simulations), this bug affects our HPWH results: 
•	~50% increase in heat pump coil heating energy
•	~50% increase in heat pump coil electricity use 
•	Minor change in heat pump COP (as expected due to lower tank temperatures)
•	~50% lower system COP
OpenStudio measures written by PSD use DHW plant loops, so this would affect OpenStudio projects as well.

To confirm that this bug affects plant-loop-connected HPWHs, I made a copy of the Zone4HeatPumpWaterHeater from the example file (“Zone4bHeatPumpWaterHeater”) and connected it to a DHW loop with the exact same draw profile as the Zone4HeatPumpWaterHeater (see attached HeatPumpWaterHeater_V810.idf and HeatPumpWaterHeater_V820.idf). Confirming the hot water draws are identical:
![wh use side mass flow rate](https://cloud.githubusercontent.com/assets/1276021/4772884/c96c7f8a-5b9c-11e4-8664-08db0044aace.png)

Results for the scheduled Zone4HPWH are identical between 8.1 and 8.2:
![zone 4 tank temps](https://cloud.githubusercontent.com/assets/1276021/4772897/d1063eb6-5b9c-11e4-92d0-477f144a8548.png)
![zone 4 coil water heating](https://cloud.githubusercontent.com/assets/1276021/4772909/e704b8a0-5b9c-11e4-9208-155767f06e30.png)

But in v8.2, the plant-loop-connected Zone4bHPWH shows sagging tank temperatures and much more water heating energy:
![zone 4b tank temps](https://cloud.githubusercontent.com/assets/1276021/4772913/f19bc3b2-5b9c-11e4-8981-283a305aeea6.png)
![zone4b coil water heating](https://cloud.githubusercontent.com/assets/1276021/4773741/1a9a3c9a-5ba6-11e4-8767-924f04cbe579.png)

Here is a table summarizing totals for the four days in the example file. As you can see, the results for the scheduled Zone4HPWH are consistent from 8.1 to 8.2, but the plant-loop-connected Zone4bHPWH actually has negative net Source Side Heat Transfer for the four days.
![8 1 8 2 zone4 zone4b table](https://cloud.githubusercontent.com/assets/1276021/4773786/67350f6c-5ba6-11e4-913e-a3a08b775a40.png)

The negative source side heat transfer rate in the 8.2 Zone4bHPWH run can be seen below. Manually calculating the source side heat transfer rate using mCpΔT agrees with the reported value, more or less. It looks like the problem is that with a plant-loop-connected HPWH, the coil removes a lot of heat from the tank at the beginning of each cycle, before recovering with either the element and heat pump, or heat pump alone.
![hpwh negative source hx](https://cloud.githubusercontent.com/assets/1276021/4773792/7f0b7e3c-5ba6-11e4-8300-eb69d8cdf3e6.png)
![zone 4b source side temps and coil and element heating](https://cloud.githubusercontent.com/assets/1276021/4773793/84780bc4-5ba6-11e4-915b-fd0c19e63ac9.png)

**Comment by nmerket** [comment]
@EnergyArchmage have you been able to look into this energy balance problem or do you know when you will be able to?

I still maintain that this is a **new and separate issue** from the one addressed here. If it needs resolving (I'm not convinced it's more than a reporting idiosyncrasy) it should be spun off as a new GitHub issue.

**Comment by jasondegraw** [comment]
@nmerket If this issue is done, can you close it?

**Comment by andregama1987** [comment]
Hello,

(sorry in advance for the English)

So I have the following scheme,

1) Boiler----Pump1-----Plate Heat Exchanger----Boiler 
2) Plate Heat Exchanger-------Pump2------Water Tank--------Plate Heat Exchanger 
3) Water Tank------3 way Valve-----Showers------Pump3------Water Tank

only heat is exchange not water (unless shower)

I am new in the modeling, can any one please guide me.

Do I have to create 3 water plant loop, and go from there?

I´m using Openstudio 1.7.5 and Energyplus 8.3

Thanks for the help

**Comment by ejhw** [comment]
@andregama1987, try posting your question to https://unmethours.com/questions/. This is not an appropriate place for it.
