### ISSUE TITLE
EvaporativeFluidCooler:TwoSpeed getinput is overly strict and halts with false error

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4560]
Helpdesk ticket 9966

Issue A:  User file with EvaporativeFluidCooler:TwoSpeed fails with this error:

   *\* Severe  *\* EvaporativeFluidCooler:TwoSpeed "CSHQA MAIN TOWER". Evaporative fluid cooler UA at low fan speed must be less than the evaporative fluid cooler UA at high fan speed.
   *\*  Fatal  *\* InitEvapFluidCooler: Program terminated due to previous condition(s).

but the user is specifying design capacities, so this should not occur.  

Issue B:  Various attempts to resolve this error resulted in other somewhat strict fatal errors, such as "   *\* Severe  *\* EvaporativeFluidCooler:TwoSpeed = "CSHQA MAIN TOWER", invalid data for "Low Speed User Specified Design Capacity", entered value <= 0.0, but must be > 0 for Performance Input Method = "USERSPECIFIEDDESIGNCAPACITY".

Overall the input options for capacity are confusing and excess inputs (e.g. value or "autosize") in a field that is not being used by the current input method should result in warnings not fatal errors.  Getinput for this object needs a review and needs test files for each method using both hard values and autosize/autocalculate to make sure the logic all flows correctly.

**Comment by jmarrec** [comment]
+1 I came on github to report this issue, I see it's been flagged before.

I have entered Autosize and AUtocalculate for High/Low fan speed U-factor times area value.

**Comment by mjwitte** [comment]
Cannot reproduce these errors with version 9.0.0-d79a0f2f2c It appears this may have been fixed in #4756.

**Comment by mjwitte** [comment]
Strike that past comment, this issue is still open. Defect files were failing due to other problems. Fixed files still show fluid cooler errors. Updated defect files added to EnergyPlusDevSupport\DefectFiles...

**Comment by jmarrec** [comment]
@mjwitte existing test files won't load in energyplus 9.0.1 while the Version shows 9.0. Some kind of a parsin error, starts with 
```
   ** Severe  ** Line: 6391 Index: 6 - Error parsing "FenestrationSurface:Detailed". Error in following line.
   ** Severe  ** ~~~     -4.93280002412701,11.3294358961986,
   ** Severe  ** Line: 6391 Index: 12 - "2.6416" is not a valid Object Type.
   ** Severe  ** Line: 6407 Index: 6 - Error parsing "FenestrationSurface:Detailed". Error in following line.
   ** Severe  ** ~~~     0,-0.887743053930268,
```

I added two new test files to `EnergyPlusDevSupport/DefectFiles/4000s/4560` (called `test900.idf` and `test910.idf`), which I built by making a a simple model and copying over the EvaporativeFluidCooler:TwoSpeed from the existing IssueA file. Trying to test #7149 (which failed)

**Comment by mjwitte** [comment]
@jmarrec The older transitions are all broken in the v9.0.1 release. See https://github.com/NREL/EnergyPlus/issues/7010.

**Comment by jmarrec** [comment]
I didn't update them myself, they were already listed at 9.0 on EnergyPlusDevSupport though. I guess you did update them with a broken Transition utility then. We could pull the 8.2 version and redo the transition if need be, but I don't think it's necessary really.
