### ISSUE TITLE
Coil:Heating:DX:MultiSpeed Defrost Bug

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#4563]
from @jonwinkler,

I encountered a potential bug in EnergyPlus 8.2. If you diff the two attached IDFs, you’ll see they’re identical with the exception of the defrost strategy implemented by the heat pump. The file giving me the error is using Resistive defrost, which throws the following error:

```
** Severe  ** SizeDXCoil Coil:Heating:DX:MultiSpeed DX HEATING COIL
   **   ~~~   ** ... DataConstantUsedForSizing and DataFractionUsedForSizing used for autocalculating Speed 1 Gross Rated Heating COP [W] must both be greater than 0.
```
 
Changing the defrost strategy to `ReverseCycle` fixes the error. The cause of the error was challenging to track down because we don’t use autosizing in our simulations.

**Comment by lgu1234** [comment]
The bug was fixed on 1/22/15.I am going to make a pull request
