### ISSUE TITLE
Cooling airflow rate being used in heating mode for variable speed cooling coils

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#4564]
from @jonwinkler,

The attached two IDFs are identical with the exception of the cooling coil type. 1.idf uses the `Coil:Cooling:DX:SingleSpeed` and 1_var_speed.idf uses `Coil:Cooling:DX:VariableSpeed`. A gas furnace and the `AirLoop:UnitaryHeatCool` object are used in both files.

The issue is with the heating air flow rate. When the variable speed cooling coil is used, the cooling airflow rate is being used in heating mode. The heating airflow rate specified in the unitary object is not being used. In the attached Excel files I’ve highlighted several hours when the runtime fraction of the heating coil equals 1. You’ll see in 1_var_speed.xlsx that the airflow rate is equal to the cooling air flow rate. The results are correct in 1.xlsx.

This has a significant impact on the fan energy. Please let me know if you want to discuss.

(I’ve also attached a schedule file you’ll need to run the simulations. The path in the IDFs will have to be updated accordingly.)

**Comment by rraustad** [comment]
SetVSHPAirFlow(
if ( HeatingLoad && ( Furnace( FurnaceNum ).FurnaceType_Num == UnitarySys_HeatCool ) ) {
  CompOnMassFlow = Furnace( FurnaceNum ).CoolMassFlowRate( Furnace( FurnaceNum ).NumOfSpeedCooling );
  CompOnFlowRatio = Furnace( FurnaceNum ).MSCoolingSpeedRatio( Furnace( FurnaceNum ).NumOfSpeedCooling );

This works just fine when cooling and heating flow rates are the same!

**Comment by rraustad** [comment]
Same logic in PTHP at line 6434.

**Comment by rraustad** [comment]
How do I make a pull request from here?

**Comment by nmerket** [comment]
@rraustad Have you made these changes on a branch? Once it's on a branch it's pretty easy to start a pull request.

**Comment by rraustad** [comment]
I just got confused last night. PR's are made from the branch, not the issue description. I made a PR last night.

**Comment by nmerket** [comment]
Thanks!
