### ISSUE TITLE
EP-Launch fails with network drives

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4572]
According to @ebonnema, EP-Launch fails hard when trying to run a file on a network drive.  I'm not sure why, nor have I validated this, but something to note.  In the example they were trying, it was trying to pull the weather file from a network folder.

**Comment by Myoldmopar** [comment]
@ebonnema Have you encountered this issue again since the last time you commented?

**Comment by bonnema** [comment]
No.

**Comment by Myoldmopar** [comment]
I'm going to close this as we haven't encountered this issue before or after this incident.
