### ISSUE TITLE
SurfaceContaminantSourceAndSink:Generic:PressureDriven crash

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4581]
Helpdesk ticket 9989
User file with SurfaceContaminantSourceAndSink:Generic:PressureDriven  in v8.0 generates contaminants but zone contaminant concentration is zero (possibly a user input problem, but can't tell for sure).  in v8.1 and 8.2, this file crashes in setup of internal gains (same structure tracks contaminants as well as gains).  

Once the crash is fixed, if the zone contaminant concentration is still reporting zero, then there may be more to fix.

Run defect file with Chicago TMY3 weather.

**Comment by lgu1234** [comment]
The bug is fixed. No more crash. The output file also shows contaminant values.
 No differences were found by running 4 example input files with contaminant simulations.
A pull request was created a while ago.
