### ISSUE TITLE
Turn off echo of input lines to audit output file by default - add diagnostic option to activate

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4589]
Currently,  by default, the audit output file contains a line-by-line echo if the input idf file. As an I/O efficiency measure, it has been suggested that the echo be off by default with an input switch to turn it on if desired.

When echo is off, put a message in the audit output file saying 
"Echo of input lines is off. May be activated with Output:Diagnostics, DisplayInputInAudit;"

**Comment by JasonGlazer** [comment]
Accepted as fixed on February 5, 2015
