### ISSUE TITLE
Adaptive convection hard crash

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4591]
The input file that demonstrates this may be sensitive, so I'm not posting it just yet.  But it is crashing on [this line](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ConvectionCoefficients.cc#L8287).  ```DeltaTemp``` is used multiple times inside ```pow()``` calls, and most times it is passed through ```std::abs``` first, but the second instance it isn't.  ```DeltaTemp``` is coming in negative, so it is crashing.  I can try just making it absolute value, but I haven't looked at the reference yet (though it is right there in the function, nice!).

**Comment by lgu1234** [comment]
I just committed my changes a while ago for review and comments.

Here is what I changed:

Mathematically, pow(-200,1/3) is accepted. However, the C++ program does not accept and create NAN. I made the numerical calculation the same as mathematical calculation.

I added two IsNan functions to try to catch inside surface temperature calculations and convective coefficient calculations.

**Comment by mjwitte** [comment]
@lgu1234 I understand how this returns the "correct" result of the equation, but do we want to return a negative value for Hc?  Does that get checked later and get reset to lower limit value?

**Comment by lgu1234** [comment]
@Myoldmopar I tried to update the old branch to perform testing. Unfortunately, I was not able to update the old branch with develop. That was why I created a new branch to perform bug fix.

**Comment by lgu1234** [comment]
@mjwitte Yes. Here is a line code to check min value in EvaluateIntHcModels (second last line) :

line:
		if ( tmpHc < AdaptiveHcInsideLowLimit ) tmpHc = AdaptiveHcInsideLowLimit;

The value of AdaptiveHcInsideLowLimit is 0.5. 

Therefore, the program automatically catch strange values and assign it to the min value. I am not sure it is right value, but it makes the program run to completion.
