### ISSUE TITLE
Sizing:System  N18, \field Fraction of Autosized Design Cooling Supply Air Flow Rate

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#4599]
I believe in the Sizing:System idd entry, N13 and N18 are duplicates.  N18 should probably be "Fraction of Autosized Design *Heating* Supply Air Flow Rate"

**Comment by rraustad** [comment]
@mjwitte merged to develop on 2/1/2015
https://github.com/NREL/EnergyPlus/pull/4642
