### ISSUE TITLE
error tolerance of EnergyPlus

### ISSUE THREAD

**Issue by rbuffat** [NREL/EnergyPlus#4613]
I try to generate a python library to create idf files from the specification: https://github.com/rbuffat/pyidf

In this process, I found some issues I lack the knowledge how to handle them:

The head in the file Energy+.idd defines \maximum< and \minimum> as field level comments. However, in some cases there is a \minimum >0  and \maximum <0 present. I converted them and made a PR: 
https://github.com/rbuffat/EnergyPlus/commit/9660b238be47a6587fc2bbb840152775cdba3821
however some test fails. Thus my question is if Energyplus uses the idd file to generate the input code how much tolerance is there when the comments differ from the specification? Thus is  \minimum >0  \minimum 0 or  \minimum>0?

In the Example file /usr/local/EnergyPlus-8-2-0/ExampleFiles/BasicsFiles/Exercise1A.idf there is the following object: 
```
  GlobalGeometryRules,
    UpperLeftCorner,         !- Starting Vertex Position
    Counterclockwise,        !- Vertex Entry Direction
    WorldCoordinateSystem;   !- Coordinate System
```

however, in the idd for GlobalGeometryRules the accepted values for field "Coordinate System" are specified as:
```
  A3, \field Coordinate System
...
      \type choice
      \key Relative
      \key World
      \key Absolute
```
This is relevant for reading existing files to know how to convert them to the specified keys. Is it known how tolerant EnergyPlus is (substring matching)?

In the idd header it says for the comment choice to be of type alpha:
```
!  \type            Type of data for the field -
!                     alpha       (arbitrary string),
!                     choice      (alpha with specific list of choices, see
!                                 \key)
```

However for following fields choice is a number:
```
 WindowMaterial:Screen->Angle of Resolution for Screen Transmittance Output Map 
 GroundHeatTransfer:Slab:Insulation->IVINS: Flag: Is there vertical insulation 
 HeaderedPumps:VariableSpeed->Total Rated Flow Rate 
 HeaderedPumps:VariableSpeed->Total Rated Flow Rate 
 HeaderedPumps:VariableSpeed->Total Rated Flow Rate 
 Refrigeration:System->Number of Compressor Stages 
 ElectricLoadCenter:Transformer->Phase 
```

Thus I assume Energyplus can handle numbers as choice type and the the documentation should be changed.

**Comment by mjwitte** [comment]
@rbuffat Comments regarding \required-field and \default have been added in #5817.  Other issues (duplicate field names, special characters, spaces before < and >) have been previously corrected.

**Comment by rbuffat** [comment]
@mjwitte thanks for the update
