### ISSUE TITLE
Misc documentation issues - Dec 2014

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4615]
- [x] From unmethours question 1620
https://unmethours.com/question/1620/what-types-of-energyplus-models-benefit-from-using-multiple-threads/

Need to revise the I/O Ref (and IDD and elsewhere?) documentation for ProgramControl to state this is currently disabled.

- [x] OutputDetails and Examples mentions this, but it does still show in the eio output, so this can stand as-is. But there is a formatting problem in OutputDetailsAndExamples.md near line 620:
Add \`\`\` on the line after the 999

- [x] Again in OutputDetailsandExamples, line 2745 needs a closing  \]</div>

DXF created from EnergyPlus
999
Program Version,EnergyPlus, &lt;version&gt;

- [x] In the IDD, capitalize first memo line and add second memo line:
ProgramControl,
       \memo Used to support various efforts in time reduction for simulation including threading
       \memo This object is currently disabled.

**Comment by mjwitte** [comment]
- [x] Input Output Reference, Chiller:Electric:EIR 
  Field: Heat Recovery Side Inlet Node --> Heat Recovery Inlet Node Name
  same for Outlet - check all other field names for consistency with IDD

**Comment by mjwitte** [comment]
- [x] Interface Developers Guide, section on "Licensing" is out of date, link is broken.  
  (Also, need to review/revise/delete Appendix G in the Module Developer Guide. - This has already been deleted, however there are still references to Appendix G in the document, but Module Developers Guide needs a major rewrite - so leave for now).

**Comment by mjwitte** [comment]
- [x] Input Output Reference, variable definitions for the various "Setpoint Not Met" output variables contain typos:  OutputControl:ReportingTolrances --> OutputControl:ReportingTolerances

**Comment by mjwitte** [comment]
- [x] In "AirflowNetwork:MultiZone:Zone" or "AirflowNetwork:MultiZone:Surface" the rules under "Modulation of Openings" show some boxes that are unknown characters.  In v8.2 docs, these showed as box, but in v8.3 docs they show as bold commas.  The first one should be if  <=, the next one is correct as < [ ] <, and the third one should be >=.  (remember that the < > symbols need to be &lt; and &gt; actually &le; will make a lessthatorequal sign, same with ge
- [x] Also, after the condition, before "Multiplication factor =" this used to be an arrow symbol prior to v8.3 and is now an accented e.  Replace this with "then" and add "If" before each condition.

**Comment by JasonGlazer** [comment]
- [x] In the IORef in the section on Output:Table:SummaryReports under Zone Component Load Summary the language under the "Heating Peak Conditions" bullet is incorrect. It should read:

"Contains the time of the peak load and the outside dry bulb and wet bulb temperatures as well as the outside humidity ratio for that time. It also shows the zone temperature and relative humidity and humidity ratio for that time."

**Comment by mjwitte** [comment]
- [x] From unmet hours question 1742
  https://unmethours.com/question/1742/heat-recovery-chiller-staging-in-energyplus
  It would be really helpful if this was clarified in the Engineering Reference section on "Hot Water Heat Recovery from Chillers", since the heat recovery condenser bundle is treated differently than the standard demand/supply side components

Add these sentences at the end of the first paragraph:
Note that the heat recovery side of the chiller is placed on the demand-side of a heat recovery loop which will typically supply a hot water storage tank. Heat recovery is a passive benefit when the chiller is dispatched for cooling.  The standard plant controls cannot dispatch the chiller based on a heat recovery requirement.

**Comment by mjwitte** [comment]
Helpdesk ticket 9835
I/O Ref and IDD notes are unclear for cooling towers, use of the term "closed-circuit" seems wrong in the IDD notes for CoolingTower:SingleSpeed, CoolingTower:TwoSpeed and CoolingTower:VariableSpeed:Merkel since these are direct-contact wet towers.  Check introductions in the I/O Ref and update IDD and I/O Ref as needed.
- [x] I/O Ref, under CoolingTower:VariableSpeed:Merkel, replace "closed-circuit" with "open wet" in the second sentence.
- [x] IDD for all CoolingTower:\* objects, same, replace "closed-circuit" with "open wet".  Except for CoolingTower:VariableSpeed, in the first line add "open wet": This open wet tower model . . .

**Comment by Myoldmopar** [comment]
Closed with #5047
