### ISSUE TITLE
WindowMaterial:Blind:EquivalentLayer used in a plain window Construction should be fatal error

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4625]
Helpdesk ticket 10100
User added a WindowMaterial:Blind:EquivalentLayer material layer to a plain window Construction.  This should be illegal.  *:EquivalentLayer materials should only be valid in a Construction:EquivalentLayer. Additional test file(s) should be made to test trap for all *EquivalentLayer types.

**Comment by Nigusse** [comment]
Invalid Equivalent Layer Window material layers in plain windows are trapped and fatal the the IDF. Six equivalent layer window material layers group were identified and checked. Three defect files were created two test all possible cases. It was determined that all possible cases were trapped and the test cases will be fatal. Diffs are not expected from this fix and no diffs were found.

**Comment by Nigusse** [comment]
Added unit test for issue #4625.
