### ISSUE TITLE
SetpointManager:OutdoorAirReset only works in one direction

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4627]
Helpdesk ticket 10103
User complained that this setpoint manager was always setting to 23C

SetpointManager:OutdoorAirReset,
    AH B01-01 Temp Aria Mandata Manager,  !- Name
    Temperature,             !- Control Variable
    21,                      !- Setpoint at Outdoor Low Temperature {C}
    21,                      !- Outdoor Low Temperature {C}
    25,                      !- Setpoint at Outdoor High Temperature {C}
    32,                      !- Outdoor High Temperature {C}
    AH B11-01 UTA Post Riscaldo Air Outlet Node;  !- Setpoint Node or NodeList Name

SetpointManager:OutdoorAirReset apparently works in only one direction. This setpoint manager expects the Setpoint at Outdoor Low Temperature to be higher than the Setpoint at Outdoor High Temperature.  If you reverse these two values, then the manager works as expected.  When the Setpoint at Outdoor Low Temperature is the lower value, the manager silently uses the average of the two values.

Seems it should work either way, or at least throw a severe error if it's going to just use a constant value.  Quick check of I/O Ref didn't see any mention of this.  Engineering Ref does show this will happen, but why?

**Comment by rglazer2** [comment]
@mjwitte If you simply remove the check for Setpoint at Outdoor Low Temperature to be higher than the Setpoint at Outdoor High Temperature on line 4534 in SetPointManager.cc, and then run EP, eventually the simulation will call abort(). As mentioned above, should we leave alone the check and just make it throw a severe error? Or something else?

**Comment by mjwitte** [comment]
@rglazer2 Not sure.  What's in the error output in that case?

**Comment by rglazer2** [comment]
@mjwitte The error file doesn't seem to show any fatal errors in that case. There are several warnings shown, and then the last lines of the error files are: 
   ************\* Testing Individual Branch Integrity
   ************\* All Branches passed integrity testing
   ************\* Testing Individual Supply Air Path Integrity
   ************\* All Supply Air Paths passed integrity testing
   ************\* Testing Individual Return Air Path Integrity
   ************\* All Return Air Paths passed integrity testing
   ************\* No node connection errors were found.
   ************\* Beginning Simulation

**Comment by mjwitte** [comment]
@rglazer2 So, where is abort being called from?

**Comment by rglazer2** [comment]
@mjwitte I'm not sure, it seems to be getting through SetPointManager.cc just fine from setting up some break points. It is some time later in the simulation that abort is called.

**Comment by rglazer2** [comment]
@mjwitte Any update on whether this should just throw a severe error, or if something else needs to be fixed?

**Comment by mjwitte** [comment]
@rglazer2 I'd like it to work in both directions, but we can't have it causing problems.  It's possible the defect file has other problems.  I can try to make a different test file and see if I get the same result.  Please push this branch up so I can run some simulations with the modified code.

**Comment by rglazer2** [comment]
@mjwitte After removing the requirement for SetTempAtOutLow > SetTempAtOutHigh in SetPointManager.cc:4534, and running it again, it eventually will abort because of an array issue at SolarShading.cc:2813.

**Comment by rglazer2** [comment]
@mjwitte On the new test file you sent me it seems to work just fine when i remove the SetTempAtOutLow > SetTempAtOutHigh requirement. The result ranges from 80-90 instead of a constant 85. Do you think the old test file had some other issues or is something else going on here?

**Comment by mjwitte** [comment]
@rglazer2 The original defect file probably had other issues.  Let's use the new test file to complete this, and I can revisit the original defect file once the code for this is finalized.

**Comment by Myoldmopar** [comment]
Closed with #5275
