### ISSUE TITLE
Add reporting of design sensible and latent coil loads next to the current rated/nominal capacities

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4628]
Reference unmethours 1980
https://unmethours.com/question/1980/thermal-load-in-data-center/

Sizing output (eio and tables) report the nominal or rated capacities for cooling and heating coils.  Water coils report a design coil load (assuming this is total, but the output is not clear).  All coils should report the design sensible and latent (for cooling coils) load that was used as the basis for sizing the coil along with the current nominal/rated values.

**Comment by Myoldmopar** [comment]
We think this new coil sizing details report covers this so I'm closing it.
