### ISSUE TITLE
Meter:Custom crash with mismatched resource type

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4631]
Helpdesk ticket 10106
User file crashing with this object
Meter:Custom,
	Panel HB,
	Electricity,
	GM WR EF-1 Exhaust Fan,
	Fan Electric Energy,
	Kitchen Hood EF-3 Exhaust Fan,
	Fan Electric Energy,
	CUST 213 EF-4 Exhaust Fan,
	Fan Electric Energy,
	CUST 112 EF-4 Exhaust Fan,
	Fan Electric Energy,
	FC-5-1A,
	Zone VRF Air Terminal Total Heating Energy,
	FC-5-1B,
	Zone VRF Air Terminal Total Heating Energy,
	FC-5-1A,
	Zone VRF Air Terminal Total Cooling Energy,
	FC-5-1B,
	Zone VRF Air Terminal Total Cooling Energy;

because Zone VRF Air Terminal Total Cooling Energy (and Heating) are not electricity variables.  Not 100% sure that's the real problem.  Tried to reproduce this by breaking one of the custom meteres in 5ZoneAirCooled and got an appropriate error message.
   ** Severe  ** Meter:CustomDecrement="MYBUILDINGOTHER", invalid specification to Source Meter Name="ELECTRICITY:BUILDING".
   **   ~~~   ** ..Variable=SPACE5-1 LIGHTS 1:Lights Radiant Heating Energy
   **  Fatal  ** UpdateMeterReporting: Previous Meter Specification errors cause program termination.

So, there may be more to this than the resource type mismatch..

**Comment by JasonGlazer** [comment]
@DeadParrot @Myoldmopar Any hints on diagnosing this assertion failure:

EnergyPlus Starting
EnergyPlus, Version 8.2.8-adb310b7db, YMD=2015.01.29 08:44
Processing Data Dictionary
Processing Input File
Initializing Simulation
Reporting Surfaces
Assertion failed: contains( i ), file I:\epRepo\EnergyPlus\third_party\ObjexxFCL\src\ObjexxFCL/FArray1.hh, line 1133

**Comment by mjwitte** [comment]
@JasonGlazer My approach is to comments out these lines in EnergyPlusPgm.cc

//#ifdef _WIN32
//	SetErrorMode(SEM_NOGPFAULTERRORBOX);
//	_CrtSetReportMode(_CRT_ASSERT, _CRTDBG_MODE_DEBUG);
//	_CrtSetReportMode(_CRT_ERROR, _CRTDBG_MODE_DEBUG);
#//endif

This restores the crash/debug dialog box.  Rebuild, then run in debug mode and when this comes up hit the ??? button and then tell it to break and you'll get the call stack to find out where the bad array index is coming from.  

@kbenne Can we put a def around this block so it is not used when doing debug builds?

**Comment by Myoldmopar** [comment]
That's usually when I run it in a debugger and run it until it gets there then look back at the stack trace to see where it actually went awry.

**Comment by mjwitte** [comment]
@Myoldmopar On Windows because we took away the popup crash dialog, even in the VS debugger, it just reports the assertion failure and exits, so without the change I noted above, you can't get the stack trace.

**Comment by JasonGlazer** [comment]
@mjwitte Thanks, commenting out the specific assertion worked too so that I could get a call stack

**Comment by mjwitte** [comment]
@JasonGlazer But how do you know you're there at the time the assertion failed?

**Comment by JasonGlazer** [comment]
I guess I don't know for sure but the file crashes when it is commented out.

**Comment by EnergyArchmage** [comment]
oh fantastic, thank you mike for this trick.    I have been cursing crashes at FArray1.hh line 1133 to no end and never found a way to get any information about it in the VS debugger.  This should be a big timesaver.

**Comment by kbenne** [comment]
@JasonGlazer 

"This restores the crash/debug dialog box. Rebuild, then run in debug mode and when this comes up hit the ??? button and then tell it to break and you'll get the call stack to find out where the bad array index is coming from."

I believe I added the lines you are referring to in response to Mike asking for the program to fail without launching a dialog.  In support of batch scripts and similar automated workflows.  It seems reasonable to use a definition to bring the dialog back in debug builds.  Is there consensus between the folks in this thread to do that?

**Comment by lgu1234** [comment]
Mike:

 

Is it possible that we can open the popup crash dialog on my local code?

 

Thanks.

 

Gu

**Comment by DeadParrot** [comment]
@kbenne I concur on enabling the dialog in a debug build if that is necessary for VS to give a backtrace. The error dialogs can be disabled in Windows separately.

For gdb the trick is to do a `break _assert` (or whatever the assert macro is defined to in that version of g++), run the debug build to the assert fail point, and then do `bt` to get the backtrace.

@EnergyArchmage if you have further troubles getting a backtrace don't hesitate to complain. If you are cursing the FArrays (they aren't really to blame) remember that they are catching bugs that Fortran often missed (even with debug builds).

**Comment by mjwitte** [comment]
@kbenne I say yes, please.  When I asked for the dialog to be suppressed, I did not understand the ramifications in the VS debugger.

**Comment by kbenne** [comment]
I don't think I did either.
