### ISSUE TITLE
Comment shows incorrect units for PsyCpAirFnWTdb

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4632]
User notes that line 316 of Psychrometrics.hh should be

// This function provides the heat capacity of air {kJ/kg-C} as function of humidity ratio.

instead of

// This function provides the heat capacity of air {J/kg-C} as function of humidity ratio.

User has verified the result against published values for Cp of air and it also computes the same as another algorithm ...which also has units of kJ/kg-C. I think it's just a typo in the comment line.

Hopefully it's just a matter of fixing the comment, but we should confirm that calling routines are expecting kJ/kg-C.

**Comment by Myoldmopar** [comment]
For reference, I am finding 351 calls to this function.  So we probably won't be able to spot check them all...I'll comment on which ones I check, and update the text in the source comment, and close this one unless I find a problem.

**Comment by Myoldmopar** [comment]
Adding a call to `PsyCpAirFnWTdb` in `SimulationManager` with reasonable values gives this:

```
Processing Data Dictionary
Processing Input File
1004.86
Initializing Simulation
Reporting Surfaces
```

Standard values of air for specific heat are approximately 1.0 kJ/kg-K. ([source](http://www.engineeringtoolbox.com/air-specific-heat-capacity-d_705.html))

So this function is return J/kg-K, as the comment suggests, not kJ as the user noted.  This is a non-issue, and I am closing it.
