### ISSUE TITLE
Controller:OutdoorAir Field: Minimum Fraction of Outdoor Air Schedule Name

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#4633]
I have reviewed the source code pertaining to "Minimum Fraction of Outdoor Air Schedule Name" and made observations in actual simulations that are at least worth some discussion, if not considered a bug.  My investigation has been motivated by the way in which OpenStudio handles ventilation and the ControllerOutdoorAir.  First it should be noted that when OpenStudio creates an outdoor air system the Controller:OutdoorAir object will always reference a Controller:MechanicalVentilation object which in turn references a DesignSpecificationOutdoorAir object that ultimately defines the ventilation for the attached zones.  That is to say OpenStudio puts the mechanical ventilation controller in charge, and therefore overpowering the minimums in the oa controller itself.  This was by design to support DCV as well as the other calculation methods offered by the mechanical ventilation controller such as VentilationRateProcedure, IndoorAirQualityProcedure, ProportionalControl, and IndoorAirQualityProcedureGenericContaminant.  One complication with this strategy is that the E+ promoted method of turning off mechanical ventilation during night cycle or off hours, that is using the Controller:OutdoorAir "Minimum Outdoor Air Schedule Name", is powerless to turn things off against the mechanical ventilation controller.  This is consistent with the documentation about mechanical ventilation controller so no issue there.  OpenStudio has acknowledged the limited power of min oa schedule, and as a result promoted using the max oa fraction schedule to get things turned off instead.  I tested this guidance on a single zone system I believed to see it working.  https://drive.google.com/drive/#folders/0B6AYyX2ggNyBajM5a29JYTlyNnM/0B6AYyX2ggNyBRW9SUmJWN0ZIcWc  Turns out it doesn't work that well, despite the evidence I thought I had in the linked idf.  Doesn't work at all for multi zone vav systems.  Not a big deal actually.  (Except I have given bad advice) The documentation doesn't indicate that it would work, and after reviewing the source code I can't see any reason to expect it would.  

I think everything I have noted so far is within spec of the documentation and although it might not be exactly how I would like things, seems ok.  (I would like max oa fraction to have enough power to turn off even minimums coming from the mechanical ventilation controller.)  What I think is an issue is this.  The min oa schedule is read here, https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/MixedAir.cc#L4013.  Then a few lines later the fraction signal is converted to a flow, https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/MixedAir.cc#L4039.  So far so good.  But, then just a few more lines later if we have fixed minimum and no cycling fan, the max fraction gets completely blown away https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/MixedAir.cc#L4055.  That is even without the presence and complication of ControllerMechanicalVentilation, the max oa fraction is extremely weak and totally ineffective at clamping down the damper in fixed minimum cases.  Perhaps this is a matter of interpretation or opinion.  But that doesn’t really seem right to me.  The max oa fraction has the power to pull below the proportional minimum (OASignal * OAController( OAControllerNum).MixMassFlow), but not fixed minimum (OAController( OAControllerNum).MinOAMassFlowRate * MinOASchedVal).  It seems inconsistent and poorly documented at best.  Im curious what the consensus of the team is here.  Is this a bug or maybe just something that could be documented a little better?

There are two tangental issues that I am left wondering about.  I might unpack these separately, but in short.  Why did the single zone idf file I linked seem to be impacted by the max oa fraction?  Reviewing the source code, it seems that would be the case only if you had cycling fan, thereby blocking https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/MixedAir.cc#L4058.  But this was not a cycling fan.  Closer inspection of the linked example reveals that while the oa rates are very near zero during hours when max oa fraction schedule is zero, but actually not exactly zero.  I really can’t explain that, but for now I consider this a distraction.  The other issue that I’m wondering about is if you do have a Controller:MechanicalVentilation how do you get flow off during off hours?  You might think the oa schedule in the referenced DesignSpecificationOutdoorAir object would do the trick, but I quickly tested that I found it not to be the case.  I might review that more in the future, for now I don’t really care.  What does work is scheduling the mechanical ventilation controller off during off hours, and setting min oa schedule.  You would expect this and I have verified that it does in fact work.

**Comment by mjwitte** [comment]
@kbenne It's been a while since you originally posted this, and I'm trying to sort through the best way forward.  Is it correct to say that one or both of these two changes would address the problem?
1. Use the schedule in DesignSpecification:OutdoorAir to modify the flow rates calculated by Controller:MechanicalVentilation.  _This one is relatively benign, but may surprise some users if they have the schedule specified, even though it currently has no impact for this controller._
2.  For Controller:OutdoorAir, allow Maximum Fraction of Outdoor Air Schedule to be king - even it it's lower than any or all other OA flow rates.  _This one could be problematic for users who expect the current behavior where the min overrides this._

**Comment by mjwitte** [comment]
@kbenne I would like to address this for the bugfix release.  Any opinion on this?  Do 1, 2, both, neither, something else?
@rraustad @Myoldmopar Any comments?

It's been a while since @kbenne originally posted this, and I'm trying to sort through the best way forward.  Is it correct to say that one or both of these two changes would address the problem?
1. Use the schedule in DesignSpecification:OutdoorAir to modify the flow rates calculated by Controller:MechanicalVentilation.  _This one is relatively benign, but may surprise some users if they have the schedule specified, even though it currently has no impact for this controller._
2.  For Controller:OutdoorAir, allow Maximum Fraction of Outdoor Air Schedule to be king - even it it's lower than any or all other OA flow rates.  _This one could be problematic for users who expect the current behavior where the min overrides this._

**Comment by kbenne** [comment]
Hmmm tough call.

Ideally I'd go for long term option 3. Combine Controller:OutdoorAir with ControllerMechanicalVentilation. But I think that is horrifically painful to the point that I don't even think I could get behind it. Plus that alone doesn't really solve the exact issue, although I do feel like it would clear up tension between the two.

So back in reality I think both of your options fit the bill and I am torn. 

Option 1 is nice because it fits with what OpenStudio is trying to sell and that is design OA spec (attached to space in OS) is your single point of entry for defining ventilation rates. The downside is that you could end up needing to edit a bunch of these if each space has a different OA spec, and all you want to do is turn off ventilation at night. You lose central control.

Option 2 is good because it gives you centralized control. And it also fits with my original intuition about how I expect things to work, even though my expectations were proven wrong. That is not knowing better I would expect max fraction to be king. 

In the end I don't know that you can really spring a change of behavior as significant as option 2. I guess I have to put my vote in - Option 1.

**Comment by mjwitte** [comment]
Regarding Option 2 - the current check of Maximum Fraction of Outdoor Air Schedule is too early for it to be king.  The current order of final max/min checks in MixedAir::CalcOAController is:
1.  Apply Minimum Fraction of Outdoor Air Schedule
2.  Apply Maximum Fraction of Outdoor Air Schedule (and warn if Minimum Fraction schedule is > Maximum Fraction schedule)
3.  Apply Ventilation:Mechanical flow rate as the minimum
4.  Apply sum of zone exhaust flows as the minimum
5.  If Minimum Limit Type=FixedMinimum, apply Min OA Flow Rate \* Min OA Schedule as the minimum (note this is the only place that FixeMinimum is applied and it's ignored for cycling fan)
6.  Apply current mixed air flow rate as the maximum
7.  Apply Max OA Flow rate as the maximum (unless using high humidity control then it can be higher)
8.  Apply demand limiter flow rate as the actual OA flow rate
9.  Apply EMS override as the actual OA flow rate

For 2. Maximum Fraction of Outdoor Air Schedule to be king, it needs to be after 8.  Is that what we want?  Is that what users expect?
@rraustad @wfbuhl @EnergyArchmage @Myoldmopar

**Comment by pachi** [comment]
I find option 1 more predictable, in the "do what I mean" sense, as the DesignSpecification:OutdoorAir restraints are generally higher level from the designer point of view. In contrast, option 2 looks too clever, as it implies a compound rule (in case of inconsistency between schedules, choose the most restrictive flow) in a situation that just may be an oversight from the designer.

As this kind of consistency problems (breaking explicit rules) can happen in more places, couldn't it be interesting to log warnings about them somewhere?.

**Comment by Myoldmopar** [comment]
@mjwitte So #5627 is merged, but it said it only partially addresses this bug.  I should leave this open, yes?

**Comment by mjwitte** [comment]
@Myoldmopar Correct, #5627 is groundwork.  A new PR will actually address the issues here.

**Comment by Myoldmopar** [comment]
Closed via #5794
