### ISSUE TITLE
Missing ElectricLoadCenter:Distribution object should produce error message if generators are present

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4639]
Helpdesk ticket 10119
User file has several Generator:Photovoltaic, PhotovoltaicPerformance:Simple, ElectricLoadCenter:Generators, ElectricLoadCenter:Inverter:Simple.  User could not understand why the PV generator output variables were not in the rdd output.  Turns out the file had no ElectricLoadCenter:Distribution object, so the generators aren't even gotten.  File runs with no errors.  Seems this should produce a severe error if not fatal.

**Comment by EnergyArchmage** [comment]
Closed via #5437
