### ISSUE TITLE
Upper limit on WindowMaterial:SimpleGlazingSystem U-Factor is inconsistent

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4643]
Helpdesk ticket 10120
User notes that WindowMaterial:SimpleGlazingSystem U-Factor maximum is 7.0, but the reported U-Factor in output is never more than 5.828.  ASHRAE Standard 90.1-2007, skylight U value should be 6.64 W/m2K, since the building locates in climate zone 4B and the skylight is with curb.

In the Input Output Reference, 

Field: U-Factor
This field describes the value for window system U-Factor, or overall heat transfer coefficient. Units are in W/m2·K. This is the rated (NFRC) value for U-factor under winter heating conditions. The U-factor is assumed to be for vertically mounted products. Although the maximum allowable input is U-7.0 W/m2·K, the effective upper limit of the glazings generated by the underlying model is around U-5.8 W/m2·K.

So, why is't the max limit for this input 5.828?  And is there a way for the model to allow higher u-factor values?

**Comment by jeannieboef** [comment]
My two cents:
I've just opened my WINDOW 7.2 and created an assembly with U-6.143 as follows...

1000 x 1000 mm
Frame: U-6.980 W/m2-K (all round), edge correlation Class 1, from  Arasteh,1989 for frame u-values from 1.9 to 0.4 Btu/(h ft2 ºF), i.e. u-values of up to 11 W/m2-K!!! for an aluminium frame without thermal break.
Uedge: 5.913
Glass: single pane, Ucenter 5.913, SHGC 0.861, from CLEAR_3.DAT

If I had to use the value of 11 W/m2K for the frame, I could get U-7.0 for the assembly.

**Comment by xwanguk** [comment]
The frame's U-value of 11 W/m2K will give total thermal resistance of 0.091 m2K/W. Back to EnergyArchmage's concerns, all standard total surface resistance (interior plus exterior) would normally be around 0.15, such as ASHRAE 90.1 0.12+0.03=0.15 and CIBESE 0.13+0.04=0.17. This may defer in different  countries, however 0.091 would still be very hard to achieve. In other words, it is difficult for window frame  to reach a U-value of more than 6W/m2K, unless you use very high (higher than standard) surface coefficients.

**Comment by xwanguk** [comment]
Oh, yes, metal frame, aluminium for example, with 3D fins can have enhanced thermal coefficient, which leads to a much smaller exterior surface resistance, therefore 11 W/m2K could be possible.

**Comment by mjwitte** [comment]
This relates to #6530

**Comment by shorowit** [comment]
With regard to the original question of modeling a **skylight** with a U-factor of 6.64 W/m2K, it may be that it should be entered as 6.64/1.2 = 5.53 W/m2K, which is below the upper limit of the SimpleGlazingSystem model. See https://github.com/NREL/EnergyPlus/issues/8102.
