### ISSUE TITLE
User file with adaptive convection zero deltaT warnings in v8.1 has fatal NaN errors in v8.2

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4646]
Helpdesk ticket 9833
User asked for an explanation of warnings like this (v8.1)
   ** Warning ** CalcBeausoleilMorrisonMixedAssistedWall: Convection model not evaluated (would divide by zero)
   **   ~~~   ** The temperature difference between surface and air is zero
   **   ~~~   ** Occurs for zone named = ZONE
   **   ~~~   ** Convection surface heat transfer coefficient set to 9.999 [W/m2-K] and the simulation continues

Testing the same file with v8.2.0 (and v8.2.5) it fails with different errors:
   ** Warning ** Inside surface heat balance did not converge with Max Temp Difference [C] =NAN vs Max Allowed Temp Diff [C] =2.000000E-003
   **   ~~~   **  Environment=RUN PERIOD 1, at Simulation time=04/11 16:27 - 16:30
   ** Severe  ** SingleHeatCoolSetPoint: Unanticipated combination of heating and cooling loads - report to EnergyPlus Development Team
   **   ~~~   ** occurs in Zone=LOWER ZONE Environment=RUN PERIOD 1, at Simulation time=04/11 16:24 - 16:27
   **   ~~~   ** LoadToHeatingSetPoint=NAN, LoadToCoolingSetPoint=NAN
   **   ~~~   ** Zone TempDepZnLd=6846.39
   **   ~~~   ** Zone TempIndZnLd=NAN
   **   ~~~   ** Zone ThermostatSetPoint=22.00
   **  Fatal  ** Program terminates due to above conditions.

It's a rather simple idf with three nearly identical zones stacked on top of each other, controlled to 22C at all times, with adiabatic top and bottom surfaces and interzone surfaces between the layers.

Tests were run with Chicago weather (but probably should be Toronto).

**Comment by lgu1234** [comment]
I ran the input file using the fix from #4591. The program ran to completion without errors.
