### ISSUE TITLE
Modify the "IP: Possible incorrect IDD File" error message

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4647]
Unmethours Question 2213
https://unmethours.com/question/2213/possible-incorrect-idd-file/?answer=2215#post-id-2215

In these error messages, the suggestion of "Possible incorrect IDD File" is misleading:

Program Version,EnergyPlus-Windows-64 8.1.0.009, YMD=2014.12.30 01:21,IDD_Version 8.1.0.009
   ** Severe  ** IP: IDF line~9077 Object=CONTROLLER:MECHANICALVENTILATION, name=CONTROLLER MECHANICAL VENTILATION 1, Required Field=[Zone 1 Name] was blank.
   ** Warning ** IP: Note -- Some missing fields have been filled with defaults. See the audit output file for details.
   ** Severe  ** IP: Possible incorrect IDD File
   **   ~~~   ** IDD Version:"IDD_Version 8.1.0.009"

May be better to say "Possible incorrect IDF version"?

**Comment by mjwitte** [comment]
And there are times where this (or a similar) error about possible incorrect version is misleading.  Need to come up with some test files to show.

**Comment by mjwitte** [comment]
One is where you have too many fields in an object - which could mean a run-on object in the idf, or a bad IDD file.  If the IDD version matches the EnergyPlus version, then it seems the idf should be blamed.

**Comment by rglazer2** [comment]
@mjwitte Could you elaborate more on what needs to be done for this? Do you want me to create new error messages or just modify the one that is already showing? Other than the one you mentioned about too many fields in an object, are there any other errors which need to be addressed?

**Comment by mjwitte** [comment]
@rglazer2 So, you can edit the top of the IDD file to trick EnergyPlus into thinking it's a different version from the program.  I thought that would generate a warning, but it didn't.

IDD file: !IDD_Version 7.3.0
ERR file:  Program Version,EnergyPlus, Version 8.3.0-6d97d074ea, YMD=2015.09.14 19:23,IDD_Version 7.3.0

But no warnings here.  My thought for this was to test if the IDD_Version (major.minor, e.g. 8.3) matches the program version, then include the part about "Possible incorrect IDD file" only if the IDD version doesn't match the program version.  You can see just below this error is a block of code that tests the idf version and adds a continueerror.  You could add a similar block to test the IDD version.

**Comment by mjwitte** [comment]
Closed via #5292
