### ISSUE TITLE
Removing unused/mislabeled flow rate fields in GroundHeatExchanger:Vertical

### ISSUE THREAD

**Issue by mmatts** [NREL/EnergyPlus#4660]
While working on the NFP for the slinky GHX model, I found that the current GHX model has one field that is mislabeled and another which is not used. The max flow rate variable here: https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/GroundHeatExchangers.cc#L765, is not used and the design flow rate, here; https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/GroundHeatExchangers.cc#L756, is labled as the max flow rate in the idd.

**Comment by mmatts** [comment]
@Myoldmopar I think I have this issue cleaned up here: c0e3dedfe73c6b27c2a9143ce5d170e35b4a739f. I didn't see any diffs on my machine. We'll see what CI comes back with.

**Comment by mjwitte** [comment]
@mmatts Can this issue be closed?

**Comment by mitchute** [comment]
@mjwitte Yes.

**Comment by shorowit** [comment]
FYI, the Rules8-2-0-to-8-3-0.xls transition program also has a bug related to this issue. The transition program removes the "Design Flow Rate" field, whereas best I can tell from looking at the 8.3 IDD, the "Maximum Flow Rate" field was removed and the "Design Flow Rate" field was moved to the location of where the "Maximum Flow Rate" field was.

Anyway, not sure if the E+ team cares about fixing old transition programs but wanted to make the issue known.

**Comment by mjwitte** [comment]
@mmatts Please confirm if this is a real issue.  If so, should open a new one.

**Comment by mitchute** [comment]
Looks like there are some errors in it. I'll open a new issue.
