### ISSUE TITLE
SetupEMSActuator is missing duplicates

### ISSUE THREAD

**Issue by DeadParrot** [NREL/EnergyPlus#4662]
SetupEMSActuator attempts to find duplicate actuators by comparing three identifying strings but a case-sensitive comparison is done between uppercased strings and stored (non-uppercased) strings so the duplicates (if not uppercase in the calling routine) are missed. This bug was carried over from the Fortran by the C++ conversion.

Beyond fixing the string comparison, @mjwitte notes that maybe the actuators should only be set up for supply side components so a broader look at this is needed.

[Discussed with @mjwitte, @Myoldmopar, and @EnergyArchmage.]

**Comment by mjwitte** [comment]
Example file HospitalLowEnergy shows duplicate actuators in the edd output for the chillers (and possibly others).

**Comment by JasonGlazer** [comment]
@mjwitte , @Myoldmopar @EnergyArchmage I am not sure I understand exactly what this issue is. Could you provide a little more information about the problem. I have inserted:

Output:EnergyManagementSystem,
    Verbose,                   !- Actuator Availability Dictionary Reporting
    NotByUniqueKeyNames,       !- Internal Variable Availability Dictionary Reporting
    ErrorsOnly;                !- EMS Runtime Language Debug Output Level

Into the HospitalLowEnergy.idf file and it doesn't seem to be producing any errors or duplicate messages related to chillers in the EDD file. Maybe I just understand what the issue is. Could someone forward the email discussion that prompted posting this issue.

**Comment by DeadParrot** [comment]
@JasonGlazer HospitalLowEnergy only shows the duplicate EMS errors if the bug is fixed, which we didn't do yet. The bug is that the SetupEMSActuator functions look for duplicates by comparing the stored actuator strings to upper case versions of the "new" actuator strings but those stored strings are not the uppercased versions. I noticed this bug while writing faster versions (those linear duplicate scans are a big performance drag for some EMS cases) and I was going to fix it but @mjwitte noted that fixed behavior may be finding duplicates that should be ignored ("Sounds like maybe these should be set up only for components on supply sides?"). The others can elaborate on this behavioral change.

**Comment by mjwitte** [comment]
@JasonGlazer There are duplicate rows in the edd from HospitalLowEnergy, e.g.

```
Line 5758 EnergyManagementSystem:Actuator Available,COOLSYS1 CHILLER,Plant Component Chiller:Electric:ReformulatedEIR,On/Off Supervisory,[W]

Line 6300 EnergyManagementSystem:Actuator Available,COOLSYS1 CHILLER,Plant Component Chiller:Electric:ReformulatedEIR,On/Off Supervisory,[W]
```

My understanding is that this should only show once.  @EnergyArchmage is that correct?

So, we need code to catch the duplicates, but then we need to fix why the duplicate is occurring in the first place.  If I remember correctly.  I will put the original e-mail discussion below.

**Comment by mjwitte** [comment]
@DeadParrot Jan 7, 2015
It looks like the SetupEMSActuator functions have a bug: they look for
duplicates by comparing the stored actuator strings to upper case versions
of the "new" actuator strings but those stored strings are not the
uppercased versions. I assume the intent is to treat these 3 strings for
each actuator as case insensitive. If so, they should either be stored as
uppercase and compared case-sensitively or stored as-is and compared
case-insensitively to the as-is new actuator strings. Can you confirm that
this is a bug?

With the faster version I'm testing that fixes this I am finding duplicates
in the first case I tried (HospitalLowEnergy) so they may be widespread. If
that is true then I'm wondering what the impact has been with duplicates
sneaking in.

We could fix the current version and deal with the blowback separately from
the later introduction of a faster version. (The linear search through all
the existing actuators with 3 string comparisons per shows up on some
profiles. I'm experimenting with an unordered_set lookup structure that
should be faster.)

@EnergyArchmage Jan 9, 2015
As for the old behavior in Fortran, the user's strings would get uppercased
when reading in the IDF.  And we usually did a case-insensitive compare that
would upper case both arguments (SameString func).  So for now I would think
storing and comparing in all uppercase is the way to go.  

@DeadParrot Jan 9, 2015
Thanks for the background but I'm not sure the Fortran was doing the uppercasing you describe. I'm seeing some duplicates reported with the revised case-insensitive comparisons that the Fortran version doesn't pick up so I want to be sure whether this is a bug carried over from the Fortran or whether something is wrong in the duplicate check logic.

For HospitalLowEnergy (which is fairly consistent in 8.1 and 8.2) the duplicates the revised C++ finds are these 3 (2nd error lines added by me to help debug):
```
   ** Severe  ** Duplicate actuator was sent to SetupEMSActuator.
   **   ~~~   ** Actuator variable type = Plant Component Chiller:Electric:ReformulatedEIR ; name = COOLSYS1 CHILLER ; control = On/Off Supervisory
   ** Severe  ** Duplicate actuator was sent to SetupEMSActuator.
   **   ~~~   ** Actuator variable type = Plant Component Chiller:Electric:ReformulatedEIR ; name = CONDENSERLOOP CHILLER ; control = On/Off Supervisory
   ** Severe  ** Duplicate actuator was sent to SetupEMSActuator.
   **   ~~~   ** Actuator variable type = Plant Component HeatExchanger:FluidToFluid ; name = CONDENSERLOOP HX ; control = On/Off Supervisory
```
Can someone confirm whether those are indeed duplicates. I see them as PlantEquipmentList items, part of a branch, and as their own items. I'm not sure why that makes them duplicates. If they aren't then perhaps the comparison case issues masked something wrong with the duplicate detection logic? I don't want to "fix" one issue but create a lot of false positive errors.

@mjwitte Jan 9, 2015
I reviewed the Fortran code yesterday, and the strings that appear in the call are mixed case hard strings in the calling routines for object type and actuatorname.  Only the objectname has been pushed to uppercase from input.  I may not be following the logic correctly, but here's what I see.

From EMSManager.f90

SUBROUTINE SetupEMSRealActuator(cComponentTypeName, cUniqueIDName, cControlTypeName, cUnits, lEMSActuated, rValue )

  UpperCaseObjectType   = MakeUpperCase(cComponentTypeName)
  UpperCaseObjectName   = MakeUpperCase(cUniqueIDName)
  UpperCaseActuatorName = MakeUpperCase(cControlTypeName)

So, the arguments are pushed to uppercase for checking for duplicates.  This is fine, but later on when a new actuator is set, the base arguments are used, not the uppercase ones:

    ActuatorVariableNum = numEMSActuatorsAvailable
    EMSActuatorAvailable(ActuatorVariableNum)%ComponentTypeName = cComponentTypeName
    EMSActuatorAvailable(ActuatorVariableNum)%UniqueIDName      = cUniqueIDName
    EMSActuatorAvailable(ActuatorVariableNum)%ControlTypeName   = cControlTypeName
    EMSActuatorAvailable(ActuatorVariableNum)%Units             = cUnits
    EMSActuatorAvailable(ActuatorVariableNum)%Actuated         => lEMSActuated  ! Pointer assigment
    EMSActuatorAvailable(ActuatorVariableNum)%RealValue        => rValue        ! Pointer assigment
    EMSActuatorAvailable(ActuatorVariableNum)%PntrVarTypeUsed  = PntrReal

Seems the above block of code should be using the uppercase versions.

Checking the edd output from v8.1 for HospitalLowEnergy (after adding an Output:Energymanagementsystem object) shows this for Coolsys1 Chiller:

Line 5758
EnergyManagementSystem:Actuator Available,COOLSYS1 CHILLER,Plant Component Chiller:Electric:ReformulatedEIR,On/Off Supervisory,[W]

and Line 6300
EnergyManagementSystem:Actuator Available,COOLSYS1 CHILLER,Plant Component Chiller:Electric:ReformulatedEIR,On/Off Supervisory,[W]

IDF and Edd attached.  My guess is that even though this creates two actuators, that the chiller will use the last one and the first will never be used, so it may not cause errors, just extra clutter in the data, but I'm not completely sure about that.

@EnergyArchmage Jan 9, 2015
Okay sorry I was thinking of user input, not the making of actuators to become available.

I think these are indeed duplicates that are being caught and handled.  The plant code for these supervisory actuators is throwing a setup for each loop that the chiller is connected to (chilled water and condenser).  OSU threw these component level on/off actuators in but I am not sure how they work. 

@mjwitte Jan 9, 2015
Sounds like maybe these should be set up only for components on supply sides?

@Myoldmopar Please review and comment (as you were likely part of implementing these plant On/Off Supervisory actuators).

**Comment by EnergyArchmage** [comment]
Yes we need to trap duplicates or at least in the end have only one unique EMS actuator available to use.  I have dim recollection that Linda I did something here so the behavior used to be O.K. but I forget the details.  

It is (much) easier to trap duplicates in this central place than it is to make sure the dups never get called.  A chiller will get initialized from both its chilled water connection and its condenser loop connnection, for example.  That could require yet-another-large sweep across plant components.  And you probably have to add a query to see if the actuator is already there, so it isn't going to save much.
Sorry we were so sloppy with case, SameString() bred bad habits (since it would upper case and trim its arguments).

**Comment by EnergyArchmage** [comment]
"Seems the above block of code should be using the uppercase versions."
Um I suspect the reason the storage was being done in mixed case is so that the text output is more readable.  Preserving case helped the look of the EDD report of available actuators.

**Comment by JasonGlazer** [comment]
Thanks. I see the duplicate and plan on just storing the value in all upper case so that it will find it.
