### ISSUE TITLE
Heat Pump Water Heater stratified tank energy not balancing

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#4665]
Looking at the accounting of energy over the course of one day (Jan 14) in the defect file, which is a modified test file to use a stratified tank:

![fig1](https://cloud.githubusercontent.com/assets/5325034/5713341/429d892a-9a78-11e4-9fb9-bc967beb6805.png)

When I total up the following outputs:
 - ZONE4HPWHTANK:Water Heater Heat Loss Energy [J]
 - ZONE4HPWHTANK:Water Heater Source Side Heat Transfer Energy [J]
 - ZONE4HPWHTANK:Water Heater Use Side Heat Transfer Energy [J]

There is 1.09 kWh more that enters in from the source side than exits from the use side or other losses.

My initial thought was that this is due to the average temperature of the tank at the end of the day being different. Looking at tank temperatures over the same time frame:

![fig2](https://cloud.githubusercontent.com/assets/5325034/5713382/e71a014a-9a78-11e4-9a02-7bde8b0f799d.png)

It looks like the tank is a little bit *cooler* at the end of the day than at the beginning: 4.25 &deg;C less. That means that there is then a total of 2.96 kWh unaccounted for over the course of a day.

This issues also seemed to exist in 8.1. It was discovered while fixing #4558.

**Comment by nmerket** [comment]
Defect file posted to
https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/4000s/4665

**Comment by Myoldmopar** [comment]
@nmerket Has this been fixed already with all the other HPWH work?

**Comment by Myoldmopar** [comment]
(If so, please close it @nmerket)

**Comment by nmerket** [comment]
I'll check into it and see if this is still happening. I think I fixed this problem.

**Comment by nmerket** [comment]
Still seeing this in a `develop` build. I think it has to do with the way the use side heat transfer output variable is calculated for stratified tanks.
