### ISSUE TITLE
ZoneEarthtube does not report leaving air humidity ratio and appears to apply outdoor humrat in the zone moisture balance

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4671]
Helpdesk ticket 10192
User asked how to report the leaving wet bulb temperature for a ZoneEarthtube object.  Review of the code appears that the leaving humidity ratio is calculated but not saved and not used in the zone moisture balance.  In CalcPredictedHumidityRatio and CorrectZoneHumRat, the earth tube mass flow (EAMFL) is used in a term that sums up infiltration and ventilation mass flow and is multiplied by the outdoor humidity ratio.

**Comment by RKStrand** [comment]
@mjwitte I agree with your comments and assessment above.  It looks like the humidity ratio is calculated and not saved...which is only a problem when there is condensation inside the earth tube.  Of course, that would be a helpful thing to know as well (condensation, when, how much, etc.), but that is a potential enhancement to try to track the condensation, etc.
To resolve this bug, I will add humidity ratio as a variable that is tracked and reported.  I will also add the leaving wet bulb temperature as a report variable as well.  Finally, I will modify the zone moisture heat balance to use the correct humidity value.  Plus the usual unit test and updated docs to reflect the new output variables.

**Comment by rraustad** [comment]
Closed via #6184.
