### ISSUE TITLE
AirLoopHVAC:UnitarySystem with heating coil but blank heating supply flow fields does not heat

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4672]
Helpdesk ticket 10183
User file appeared to be fine, cooled to setpoint, but would not heat - ever.  Tracked it down to airlfow rate fields all being blank:

AirLoopHVAC:UnitarySystem,
    Air Loop Unitary HeatCool,  !- Name
    Load,                    !- Control Type
    Block1:Zone1,            !- Controlling Zone or Thermostat Location
    None,                    !- Dehumidification Control Type
    2,                       !- Availability Schedule Name
    Air Loop Unitary HeatCool Mixed Air Outlet,  !- Air Inlet Node Name
    Air Loop Supply Side Outlet 1,  !- Air Outlet Node Name
    Fan:ConstantVolume,      !- Supply Fan Object Type
    Air Loop Unitary HeatCoolSupply Fan,  !- Supply Fan Name
    BlowThrough,             !- Fan Placement
    2,                       !- Supply Air Fan Operating Mode Schedule Name
    Coil:Heating:Electric,   !- Heating Coil Object Type
    Air Loop Unitary HeatCoolElectric Heating Coil,  !- Heating Coil Name
    1,                       !- DX Heating Coil Sizing Ratio
    Coil:Cooling:DX:TwoSpeed,!- Cooling Coil Object Type
    Air Loop Unitary HeatCoolDX Cooling Coil TwoSpeed,  !- Cooling Coil Name
    No,                      !- Use DOAS DX Cooling Coil
    2,                       !- DOAS DX Cooling Coil Leaving Minimum Air Temperature {C}
    SensibleOnlyLoadControl, !- Latent Load Control
    ,                        !- Supplemental Heating Coil Object Type
    ,                        !- Supplemental Heating Coil Name
    ,                        !- Supply Air Flow Rate Method During Cooling Operation
    ,                        !- Supply Air Flow Rate During Cooling Operation {m3/s}
    ,                        !- Supply Air Flow Rate Per Floor Area During Cooling Operation {m3/s-m2}
    ,                        !- Fraction of Autosized Design Cooling Supply Air Flow Rate
    ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Cooling Operation {m3/s-W}
    ,                        !- Supply air Flow Rate Method During Heating Operation
    ,                        !- Supply Air Flow Rate During Heating Operation {m3/s}
    ,                        !- Supply Air Flow Rate Per Floor Area during Heating Operation {m3/s-m2}
    ,                        !- Fraction of Autosized Design Heating Supply Air Flow Rate
    ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Heating Operation {m3/s-W}
    ,                        !- Supply Air Flow Rate Method When No Cooling or Heating is Required
    ,                        !- Supply Air Flow Rate When No Cooling or Heating is Required {m3/s}
    ,                        !- Supply Air Flow Rate Per Floor Area When No Cooling or Heating is Required {m3/s-m2}
    ,                        !- Fraction of Autosized Design Cooling Supply Air Flow Rate
    ,                        !- Fraction of Autosized Design Heating Supply Air Flow Rate
    ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Cooling Operation {m3/s-W}
    ,                        !- Design Supply Air Flow Rate Per Unit of Capacity During Heating Operation {m3/s-W}

Need a warning or severe for this condition.  Seems if a heating coil is specified, then heat supply air flow rate specs should be required.  Likewise if a cooling coil is specified, then cooling flow rate specs should be required.

**Comment by rraustad** [comment]
Added warnings:

   *\* Severe  *\* AirLoopHVAC:UnitarySystem = AIR LOOP UNITARY HEATCOOL
   *\*   ~~~   *\* Input for Cooling Supply Air Flow Rate Method is blank.
   *\*   ~~~   *\* Blank field not allowed when cooling coil is present.
   *\* Severe  *\* AirLoopHVAC:UnitarySystem = AIR LOOP UNITARY HEATCOOL
   *\*   ~~~   *\* Input for Heating Supply Air Flow Rate Method is blank.
   *\*   ~~~   *\* Blank field not allowed when heating coil is present.

**Comment by rraustad** [comment]
PR #5179

**Comment by rraustad** [comment]
Complete. See #5179

**Comment by mjwitte** [comment]
Closed via #5179
