### ISSUE TITLE
Duplicate DegToRad in DataGlobals should be removed

### ISSUE THREAD

**Issue by mmatts** [NREL/EnergyPlus#4674]
In DataGlobals: https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DataGlobals.cc#L65-66

DegToRad should be removed since it is not used.

**Comment by mmatts** [comment]
Fixed here: b0fe8d12d25f029adaa896c369bfdaf98395bf2e

**Comment by mmatts** [comment]
@Myoldmopar could you head up the review team to make sure this doesn't break E+?

**Comment by Myoldmopar** [comment]
Forget E+, I'm worried about _the internet_...

**Comment by Myoldmopar** [comment]
Fixed in #4675
