### ISSUE TITLE
HPWH/Stratified Tank idd changes

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#4682]
- [ ] max number of stratified nodes = 12
 - [ ] minimum air inlet temperature = -5 &deg;C
 - [ ] decide on and set a maximum air inlet temperature and enforce it.

**Comment by nmerket** [comment]
@ejhw @jmaguire1

**Comment by jmaguire1** [comment]
We can set a hard maximum in the .idd, but we also want to have the maximum air inlet temperature as an input to the WaterHeater:HeatPump object in case the user wants to implement something lower (for example, some manufacturers have 120 F as the max and others have 110 F)

**Comment by ejhw** [comment]
Note that changes 2 and 3 above should be made for both PumpedCondenser (mixed tank) and WrappedCondenser (stratified tank) types of HPWH.

**Comment by nmerket** [comment]
Combining into pull request #4698
