### ISSUE TITLE
Wrapped condenser hpwh model

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#4683]
Rename existing `WaterHeater:HeatPump` to `WaterHeater:HeatPumpPumpedCondenser`. Create a new idf object for residential heat pump water heaters called `WaterHeater:HeatPumpWrappedCondenser`. The new object will be different in the following ways:

 - `WaterHeater:HeatPumpWrappedCondenser` will only be compatible with a `WaterHeater:Stratified` tank (and `WaterHeater:HeatPumpPumpedCondenser` will only be compatible with a `WaterHeater:Mixed` tank)
 - Inputs relating to condenser water pumping will be removed.
 - Add inputs relating to the location of the condenser on the tank and change heat transfer calculation to allow for a distribution of heat to come in across several nodes.
 - Include warnings if the timestep is too long for reasonable results. Also, warn if not using subhourly draw profiles.

**Comment by nmerket** [comment]
@ejhw @jmaguire1

**Comment by Myoldmopar** [comment]
@nmerket This is the HPWH new feature work, right?  I don't mind if you make GitHub issues for the work, but I also don't mind if you don't.  You can use Pivotal for planning/tracking, and then just create a branch/pull request sooner rather than later to have conversations about specific code.  Whatever works best for you is fine.

**Comment by nmerket** [comment]
Yes, this is. Good point. Maybe I’ll do this more in pull request form.

On Jan 22, 2015, at 11:19 AM, Edwin Lee <notifications@github.com<mailto:notifications@github.com>> wrote:


@nmerket<https://github.com/nmerket> This is the HPWH new feature work, right? I don't mind if you make GitHub issues for the work, but I also don't mind if you don't. You can use Pivotal for planning/tracking, and then just create a branch/pull request sooner rather than later to have conversations about specific code. Whatever works best for you is fine.

**Comment by Myoldmopar** [comment]
Whatever works best for you.  I don't want to add any hindrance to productivity without cause.

**Comment by nmerket** [comment]
As @Myoldmopar pointed out this might be easier to do from a pull request, so we'll be having this conversation over at #4698 instead.
