### ISSUE TITLE
Chilled water tank control issue

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4685]
The documentation for the chilled water tank implies that the unit should ride through the deadband in a hysteresis fashion, staying on/off through the deadband before switching state.  The model does not appear to do that and instead just rides at one end of the deadband, switching on and off at that end.  

I will supply a defect file demonstrating this, and the expected output shortly.

**Comment by Myoldmopar** [comment]
Taking the 5ZoneVAV-ChilledWaterStorage-Mixed example file, and running annual, the tank never seems to get to the top of the deadband.  It goes **into** the deadband, but does not ride it all the way through.  Here is a sampling.

![image](https://cloud.githubusercontent.com/assets/849824/5928707/728f89bc-a63a-11e4-94d4-2787b46216a9.png)

This isn't conclusive yet, as that particular example file may be set up to control that way on purpose.  But it is where I will begin.  I will upload to DevSupport as I work on mods to the file to demonstrate the issue.

**Comment by Myoldmopar** [comment]
OK, so I changed the test file so that the source (charging) side is _always_ available.  The tank should still float in the deadband, this change just means it is able to request flow whenever it needs to.  The tank simply shouldn't need to unless it is leaving the deadband.  Unfortunately this isn't happening:

![image](https://cloud.githubusercontent.com/assets/849824/6026087/cc81d6dc-ab94-11e4-8d9f-9ae6a9d7d7cd.png)

Instead, the requested flow is jumping all over in order to keep the tank right at the lower end of the deadband.  Still working...

**Comment by Myoldmopar** [comment]
Seems like we should be hitting [this line](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WaterThermalTanks.cc#L7518) during a major portion of this run so that the tank will float up.  (Setpoint is 7.5, deadband is 2.5)

Digging in now to figure out why it's not hitting this line.

**Comment by Myoldmopar** [comment]
Initial testing didn't reveal an immediate fix.  A couple notes that might change as I dig in deeper and understand it better:
- Seems that the chilled water tank only goes into float mode if the tank is _below_ the setpoint temperature (see [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WaterThermalTanks.cc#L5271)).  I'm not assuming this is a bug yet, just me still getting more exposed to how the model works.
- There is [a comment block](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WaterThermalTanks.cc#L5216-L5217) that indicates the chilled water section should work differently between cycling and modulating.  This will be including as I investigate further.

**Comment by Myoldmopar** [comment]
A little confused; [this line](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WaterThermalTanks.cc#L5275) isn't hit during a debugging session all the way through the design days, even though the tank is a chilled water tank, the tank temperature is clearly below the deadband temperature, the tank mode _should_ be either float or cool, time remaining should be > 0, and this _is_ a mixed tank.  This should be the full set of conditions necessary to make it into that block, so I'm going to have to dig further to find out why that's not being hit.

**Comment by Myoldmopar** [comment]
OK, so the code is treating the deadband as going from (setpoint minus deadband delta) to (setpoint) so for this file the deadband is 5 to 7.5.  Which helps explain why the tank is staying at 7.5  It is staying at the top of the deadband and doesn't oddly stay pegged at the bottom end.  

The tank seems to request cooling on a modulate basis, as evident by the varying flow rate and fixed tank temperature in the [comment above](https://github.com/NREL/EnergyPlus/issues/4685#issuecomment-72702296).  I'm currently looking at whether the tank can do cycling or not.  If it can't right now, maybe that's the whole issue keeping it from performing the type of control being requested.

**Comment by Myoldmopar** [comment]
Took a while to get back to this, but I'm on it again.  Re-running the same file showed different results, but it appears due to a transition problem maybe?  I'll start back re-running transition to 8.3 and see what I can get.

**Comment by Myoldmopar** [comment]
OK, I might actually be close to a fix now.  Testing currently and will post more info when I look over the results.

**Comment by Myoldmopar** [comment]
So, the deadband temperature was being specified as always `SetPoint - DeadbandDelta`.  However, it seems as though the logic for chilled water tanks was implemented assuming the deadband would be the other way.  I added code to assign the deadband temperature as `SetPoint + DeadbandDelta` for chilled water tanks.  Here is the result:

![image](https://cloud.githubusercontent.com/assets/849824/7683755/57d6e038-fd3e-11e4-9bcd-a63bac1807a8.png)

Gah, the picture export is a bit fuzzy.  I might post a zoomed in version.  But anyway, the tank appears to float up and down through the deadband range much better, as expected, as opposed to staying fixed at one end of the deadband.

@EnergyArchmage Do you have any comment on this change?

**Comment by Myoldmopar** [comment]
@mjwitte @EnergyArchmage 

So the documentation does imply this should be the right fix.  The chilled water control algorithm [here](http://bigladdersoftware.com/epx/docs/8-3/engineering-reference/water-thermal-tanks.html#chilled-water-tank-control-algorithm) says that "the setpoint **plus** deadband is the cut-in temperature."

**Comment by EnergyArchmage** [comment]
Change looks good to me.   subtle one, good catch.
