### ISSUE TITLE
IDFVersionUpdater error

### ISSUE THREAD

**Issue by mbadams5** [NREL/EnergyPlus#4686]
I get the following error on Mac OSX 10.9 when attempting to use IDFVersionUpdater...

You can’t open the application “IDFVersionUpdater” because PowerPC applications are no longer supported.

https://www.pivotaltracker.com/story/show/86638582

**Comment by kbenne** [comment]
@mbadams5 and @JasonGlazer this might be my problem.  No doubt an installation issue.

**Comment by JasonGlazer** [comment]
@kbenne  If you need me to recompile IDFVersionUpdater using different switches, let me know.

**Comment by nmerket** [comment]
I can second this one. I'm getting the same error on OS X 10.9.

**Comment by nxtruong** [comment]
Same error. I think you need to recompile it for x86 instead of ppc.

**Comment by JasonGlazer** [comment]
Fixed this issue with checkin of revised source code and executables to:

EnergyPlusBuildSupport/src/IDFVersionUpdater
EnergyPlusBuildSupport/bin/IDFVersionUpdater

Hopefully it will make it into the next release.
