### ISSUE TITLE
HPWH fan not autosizing

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4693]
Previous user file shows correct results after correcting #4558. During verification of these chagnes, the HPWH fan was found to not autosize nor report to the eio file. See defect file #4693 (previously #4455 with these report variables added):
Output:Variable, HPWHDXCoil, Cooling Coil Runtime Fraction, Detailed;
Output:Variable, HPWHDXCoil, Cooling Coil Total Cooling Rate, Detailed;
Output:Variable, HPWH Fan, Fan Runtime Fraction, Detailed;
Output:Variable, HPWH Outdoor Air Inlet Node, System Node Standard Density Volume Flow Rate, Detailed;
Output:Variable, HPWHDXCoilAirOutletNode, System Node Standard Density Volume Flow Rate, Detailed;
Output:Variable, HPWHOutdoorAirOutletNode, System Node Standard Density Volume Flow Rate, Detailed;

**Comment by lgu1234** [comment]
Verified the fix and unit test.
