### ISSUE TITLE
WaterHeater:HeatPump misleading error message about priority

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4695]
Helpdesk ticket 10206
From user post . . .
```
** Severe ** WaterHeater:HeatPump = BLOCK1:ZONE1 HP WATER HEATER:
** ~~~ ** Heat pump water heaters must have lower priorities than all other equipment types in a ZoneHVAC:EquipmentList.
** Fatal ** Errors found in getting WaterHeater:HeatPump input. Preceding condition causes termination.
...Summary of Errors that led to program termination:
..... Reference severe error count=1
..... Last severe error=WaterHeater:HeatPump = BLOCK1:ZONE1 HP WATER HEATER:
```
Actually, I did put WaterHeater:HeatPump (BLOCK1:ZONE1 HP WATER HEATER) at the lowest priority than all other equipment types in ZoneHVAC:EquipmentList (please refer to below extract of idf file).
```
ZoneHVAC:EquipmentList,
Block1:Zone1 Equipment, !- Name
ZoneHVAC:Baseboard:RadiantConvective:Electric, !- Zone Equipment 1 Object Type
Block1:Zone1 Electric Radiator, !- Zone Equipment 1 Name
1, !- Zone Equipment 1 Cooling Sequence
1, !- Zone Equipment 1 Heating or No-Load Sequence
WaterHeater:HeatPump, !- Zone Equipment 2 Object Type
Block1:Zone1 HP Water Heater, !- Zone Equipment 2 Name
3, !- Zone Equipment 2 Cooling Sequence
3, !- Zone Equipment 2 Heating or No-Load Sequence
ZoneHVAC:AirDistributionUnit, !- Zone Equipment 3 Object Type
Block1:Zone1 Single Duct CAV Reheat ADU, !- Zone Equipment 3 Name
2, !- Zone Equipment 3 Cooling Sequence
2; !- Zone Equipment 3 Heating or No-Load Sequence
```
----------------------------------
The error message can be worded more clearly to specify that the heat pump water heater should have heating and cooling sequence number 1.  Also, it seems this could be a sever but not fatal.
No test file from the user, should be able to create one easy enough

**Comment by nmerket** [comment]
The [code that checks this](https://github.com/NREL/EnergyPlus/blob/b5d65e9c71fc9f1db7dda067c865b6fde819d5f9/src/EnergyPlus/WaterThermalTanks.cc#L3698-L3702) actually goes through each piece of equipment in the zone equipment list and checks to see if the equipment has a lower priority number than the HPWH. In other words, it's doing what it says it's doing and not expecting the equipment number to be strictly 1. I'd be interested to see an idf that causes this error.

**Comment by nmerket** [comment]
Okay, just re-read that along with the I/O Reference. It's confusing in the code as well. So, it looks like the HPWH needs to have the lowest _sequence number_ which is actually the highest _priority_. I think that's what @mjwitte was getting at.

**Comment by mjwitte** [comment]
@nmerket The problem is that the "priority" terminology is ambiguous.  That's why the field names were changed to "sequence number", but the code still uses the term "priority".  For this purpose, 1 is the lowest priority - meaning it's run first, then the next equipment, etc.  The 4695 defect file (stored in your favorite repo) produces the error with v8.3.0.  Working on a v8.3.4 version.

Looking at this today, I would make this a warning that says something like

```
** Warning ** WaterHeater:HeatPump = BLOCK1:ZONE1 HP WATER HEATER 
** ~~~ ** Heat pump water heaters should be simulated first, before other space conditioning equipment.
** ~~~ ** Poor temperature control may result if the Heating/Cooling sequence number is not 1 in the ZoneHVAC:EquipmentList.
```

**Comment by nmerket** [comment]
Right, the whole lowest/highest priority is confusing. That error message sounds like a better explanation. I'll make the change.
