### ISSUE TITLE
Build flags don't work when using Intel compiler on Linux

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#4697]
Hit this when building on Peregrine at NREL:

Scanning dependencies of target sqlite
[  1%] Building C object third_party/SQLite/CMakeFiles/sqlite.dir/sqlite3.c.o
icc: error #10236: File not found:  '/Qdiag-disable:1786,2259'
icc: error #10236: File not found:  '/DVC_EXTRALEAN'
icc: error #10236: File not found:  '/DWIN32_LEAN_AND_MEAN'
icc: error #10236: File not found:  '/DNOMINMAX'
icc: error #10236: File not found:  '/W0'
/home/dmacumbe/energyplus/third_party/SQLite/sqlite3.c(46945): warning #810: conversion from "char *" to "int" may lose significant bits
      if( (enc & SQLITE_UTF16_ALIGNED)!=0 && 1==(1&SQLITE_PTR_TO_INT(pVal->z)) ){

**Comment by macumber** [comment]
Also might want to set these properties on the EnergyPlus target

http://www.cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html 
http://www.cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD_REQUIRED.html

**Comment by DeadParrot** [comment]
I shared a revised CMake compiler flags file with @kbenne that supports Intel C++ on Linux.

As for the sqlite3 warnings, that code has some weaknesses but seems to work so I wouldn't worry about it.

**Comment by mbadams5** [comment]
@Myoldmopar This issue it still valid. I actually have a branch on my computer to fix this.

**Comment by macumber** [comment]
This was required for building on Peregrine
