### ISSUE TITLE
Idd errors popping up

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4700]
They popped up randomly in the CLI branch, and now they are appearing in develop with the CLI branch merged in.  The errors are seen [here](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-adb310b7db0b5add4e930d9fad75dced9ac22c04-x86_64-Linux-Ubuntu-14.04-gcc-4.8-IntegrationCoverage-Debug.html)  Basically the error message is:

```
ERROR: Could not find input data dictionary: /home/nrelci/ci/builds/EP-adb310b7db-x86_64-G4.8ICD/build/Products/energyplus-8.2.8+/Energy+.idd.
Type 'energyplus --help' for usage.
Test Failed
```

It seems super random, and @kbenne was brainstorming that maybe it has something to do with how the CLI is accessing the IDD in conjunction with the highly parallel runs of CI.  I'm going to assign this to @nealkruis first to get thoughts and discussion going so we can figure out if something more sinister is going on.

**Comment by kbenne** [comment]
is that "energyplus-8.2.8+" supposed to be there?

**Comment by nealkruis** [comment]
All of the parent directories are given weird characters at the end:
- `energyplus-8.2.8+`
- `energyplus-8.2.8|`
- `energyplus-8.2.8[NON-XML-CHAR-0x12]`
- `energyplus-8.2.8 ` <- trailing space

@mbadams5 is this possibly related to the extra path character you were showing me yesterday?

**Comment by nealkruis** [comment]
This also only happens for the integration coverage tests. It could be a problem on the CI side. @lefticus any thoughts?

**Comment by mjwitte** [comment]
@Myoldmopar This can be closed, correct?

**Comment by Myoldmopar** [comment]
Yes, thanks.

On Mon, Feb 9, 2015 at 9:03 AM, Michael J. Witte <notifications@github.com>
wrote:

> @Myoldmopar <https://github.com/Myoldmopar> This can be closed, correct?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NREL/EnergyPlus/issues/4700#issuecomment-73534345>.
>



-- 
Edwin Lee, PhD
Engineer, Commercial Buildings Research Staff
National Renewable Energy Laboratory
