### ISSUE TITLE
AirloopHVAC:UnitarySystem autosizing incorrect for heating only systems when using FlowPerHeatingCapacity

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4702]
Cut-n-paste error in HVACUnitarySystem::SizeUnitarySystem subroutine:
(these would probably crash the program)

if ( UnitarySystem( UnitarySysNum ).RequestAutoSize ) {
if ( CurOASysNum > 0 ) {
<snip>
   } else if ( UnitarySystem( UnitarySysNum ).HeatCoilExists && ! UnitarySystem( UnitarySysNum ).CoolCoilExists ) {
<snip>
	} else if ( SELECT_CASE_var == FlowPerHeatingCapacity ) {
               <snip>
		SupTemp = FinalSysSizing( CurSysNum ).PrecoolTemp;
		SupHumRat = FinalSysSizing( CurSysNum ).PrecoolHumRat;
                <snip>
		OASysEqSizing( CurOASysNum ).AirVolFlow = SysCoolingFlow;
		OASysEqSizing( CurOASysNum ).DesCoolingLoad = HeatCapAtPeak;

<snip>
if ( CurSysNum > 0 ) {
<snip>
} else if ( UnitarySystem( UnitarySysNum ).HeatCoilExists && ! UnitarySystem( UnitarySysNum ).CoolCoilExists ) {
	{ auto const SELECT_CASE_var( UnitarySystem( UnitarySysNum ).HeatingSAFMethod );
<snip>
	} else if ( SELECT_CASE_var == FlowPerHeatingCapacity ) {
<snip>
		SysHeatingFlow = HeatCapAtPeak * UnitarySystem( UnitarySysNum ).MaxCoolAirVolFlow;

should be:
SupTemp = FinalSysSizing( CurSysNum ).PreheatTemp;
SupHumRat = FinalSysSizing( CurSysNum ).PreheatHumRat;
OASysEqSizing( CurOASysNum ).AirVolFlow = SysHeatingFlow;
OASysEqSizing( CurOASysNum ).DesHeatingLoad = HeatCapAtPeak;
SysHeatingFlow = HeatCapAtPeak * UnitarySystem( UnitarySysNum ).MaxHeatAirVolFlow;

**Comment by rraustad** [comment]
Workaround:
Use heating and cooling system with cooling system scheduled off.

**Comment by rraustad** [comment]
Just documenting this before moving on.....

Defect file 4702:

CoolingTower:TwoSpeed,
  autosize,                         !- Low Fan Speed Fan Power {W}

Transition error from 8.2 to 8.3:

Program Version,Conversion 8.2 => 8.3
   *\* Severe  *\* Out of range value Numeric Field#7 (Low Fan Speed Fan Power), value=0.00000, range={>0.0}, in CoolingTower:TwoSpeed=Heat Pump Loop Tower

8.3 IDD:

CoolingTower:TwoSpeed,
  N7 , \field Low Fan Speed Fan Power
       \required-field
       \type real
       \units W
       \minimum> 0.0
       \autocalculatable

**Comment by mjwitte** [comment]
The transition problem has been fixed. #4456

**Comment by rraustad** [comment]
PR https://github.com/NREL/EnergyPlus/pull/5209

**Comment by mjwitte** [comment]
Closed via #5209
