### ISSUE TITLE
VRF example file, VariableRefrigerantFlow_5Zone, not showing OA in outdoor air summary in html file.

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4706]

**Comment by rraustad** [comment]
@mjwitte do you get notified when I post an issue?

**Comment by rraustad** [comment]
I don't see VRF in the list of equipment types at line 3995 in SystemReports.cc

// first deal with any (and all) Zone Forced Air Units that might have outside air.
<snip>
if ( SELECT_CASE_var == WindowAC_Num ) { // Window Air Conditioner
} else if ( ( SELECT_CASE_var == PkgTermHPAirToAir_Num ) || ( SELECT_CASE_var == PkgTermACAirToAir_Num ) || ( SELECT_CASE_var == PkgTermHPWaterToAir_Num ) ) {
} else if ( SELECT_CASE_var == FanCoil4Pipe_Num ) {
} else if ( SELECT_CASE_var == UnitVentilator_Num ) {
} else if ( SELECT_CASE_var == PurchasedAir_Num ) {
} else if ( SELECT_CASE_var == ERVStandAlone_Num ) {

**Comment by mjwitte** [comment]
@rraustad Any kind of block like that is a problem when new equipment is added - because how does a developer know it's there?

**Comment by rraustad** [comment]
Maybe I should add else if's for all zone equipment types and then a final else that fatals out?  A developer would have to include their equipment one way or another.

**Comment by mjwitte** [comment]
@rraustad That might be OK, but that becomes a line of dead code that never gets touched under normal circumstances.  @Myoldmopar We had a discussion about this type of internal developer check, but I don't remember what we concluded - some type of assert?

**Comment by rraustad** [comment]
@Myoldmopar see https://github.com/NREL/EnergyPlus/pull/4707/files

**Comment by rraustad** [comment]
@Myoldmopar merged on 2/20/2015.
https://github.com/NREL/EnergyPlus/pull/4707#event-239140960
