### ISSUE TITLE
OutputVariables missing from EMS Sensor A3 Field

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#4708]
Working on a 8.2 IDF I noticed that the OutputVariables listed in the RDD file are not listed in the *Output:Variable or Output:Meter Name* drop-down field which only shows the OutputMeter names listed in the MDD file.

**Comment by mjwitte** [comment]
@MatthewSteen Thanks.  This needs an IDD change.  
From
  A3 ; \field Output:Variable or Output:Meter Name
       \required-field
       \type external-list
       \external-list autoRDDvariable
       \external-list autoRDDmeter

to
  A3 ; \field Output:Variable or Output:Meter Name
       \required-field
       \type external-list
       \external-list autoRDDvariableMeter

**Comment by MatthewSteen** [comment]
Thanks that worked. Is there a way to also display meters or is this field destined for a change to a string input?

**Comment by mjwitte** [comment]
@MatthewSteen That change should display both variables and meters.  Same as for Output:Table:Timebins  Or am I misunderstanding your question?

**Comment by MatthewSteen** [comment]
No, that did it, just missed seeing the meter names on my first pass/search. Thanks!

**Comment by mjwitte** [comment]
@MatthewSteen Are you planning to make a branch to fix this, or shall I?

**Comment by MatthewSteen** [comment]
@mjwitte I'll give it a shot.
