### ISSUE TITLE
Suggestion: Add Additional Options for EMS:OutputVariable Field A3

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#4709]
It would be helpful to add all the options for the **Type of Data in Variable** field to for example enable reporting of peak demand by end use instead of limiting to Averaged and Summed data. 

Similar to the options available for the **Aggregation Type for Variable or Meter** field in the `Output:Table:Monthly` object.

**Comment by EnergyArchmage** [comment]
Sorry, this is not clear to me.  Those other options generally involve relationships between two variables and don't really apply to just one.  The aggregations involved here are for detailed, timestep, hourly, daily, monthly, runperiod timeseries reporting intervals.  

If I understand the question behind this, the solution is to use both Output:Table:Monthly and the EnergyManagementSystem:OutputVariable so as to get these sort of aggregations on a custom EMS output variable.

**Comment by mjwitte** [comment]
@MatthewSteen Does the reply by @EnergyArchmage adequately address this issue?

**Comment by MatthewSteen** [comment]
I was hoping to use these objects to create a table of peak demand by end use for LEED reporting since the LEED Summary incorrectly reports these values at the building's peak (#4588). I've since found this information, albeit somewhat burried, in the Energy Meters standard report.
