### ISSUE TITLE
Fan:ZoneExhaust Balanced Exhaust Fraction causing negative zone air mass balance

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4711]
Original complaint from users:

The following summary looks at something strange regarding an exhaust fan object impacting a zone’s moisture balance. To isolate this strange behavior, we looked at a single design day with a constant ambient 100°F dry-bulb and 77°F dewpoint in Miami. The figures below are based on outputs at the timestep level (not averaged for the hour). Note that we are simulating based on a 5 minute timestep.  
The model with the Fan:ZoneExhaust object is showing unrealistically low dewpoints in the Sales Zone (where the exhaust fan is located). Figure 1 shows that the Sales Zone dewpoint at 7am starts to drop  which is exactly the same time the SalesZone:Exhaust:Schedule turns the exhaust fan on. I should note that this  SalesZone:Exhaust:Schedule also controls mixing between the Refrigeration Zone and Sales Zone. The Refrigeration zone will correctly maintain a lower dewpoint due to latent case credits from refrigerated cases and walkins. Exhaust fan and mixing objects copied below.
It makes sense for the Sales Zone dewpoint to begin to reduce starting at 7am when the mixing object starts pulling in lower dewpoint air from the Refrigeration Zone. Yet it is unrealistic that the Sales Zone dewpoint (blue line) to drop below the Refrigeration Zone dewpoint (red line). This additional drying is not from the RTU serving both the Sales and Refrigeration zones because the supply air dewpoint is greater than both zone dewpoints (purple line). 
Figure 2 shows running the exact same model but eliminating the exhaust fan object. We did leave in the mixing object. These dewpoints look more realistic with the Sales Zone maintaining ~60°F, just above the RTU supply air dewpoint at ~57°F and Refrigeration Zone dewpoint at ~56°F. How is the exhaust fan object impacting the moisture balance?

Diagnosis:
So, finally made time to dig into this.  Took out the EMS, took out the refrigeration, expectation is that with/without exhaust should produce exactly the same results, since exhaust flow rate is less than the OA flow rate to this RTU and there is no heat recovery and no economizer.  More digging, looking at flow rates - the return flow rate from the sales zone is identical in the two runs - this should not be.  Return flow is supposed to be reduced by the exhaust flow. Oh, because of this:

    Exhaust_Fan_Always_Balanced;  !-Balanced Exhaust Fraction Schedule Name

Which, apparently is not working as advertised.  If it's going to not reduce return air flow, then the flow on the exhaust node should be reduced accordingly. If the balanced schedule is deleted, then the dewpoint goes back to where it's expected (well, still not identical, but only slightly lower now, so much better).

So, the short-term workaround is to turn off the balancing - it's not really necessary for this equipment configuration.  It would be useful for a system with heat recovery where the return air is useful, or if the OA flow rate in the RTU was getting increased because of the exhaust fan operation.

**Comment by Myoldmopar** [comment]
@mjwitte, glancing through, I didn't see Figures 1 and 2.

**Comment by mjwitte** [comment]
@Myoldmopar Sorry - copied a paragraph and decided the figures weren't needed.  Will edit.

**Comment by mjwitte** [comment]
![image](https://cloud.githubusercontent.com/assets/4991075/6028079/54fd92c8-abac-11e4-8224-3e59f68480c7.png)
Figure 1. With Exhaust Object

**Comment by mjwitte** [comment]
![image](https://cloud.githubusercontent.com/assets/4991075/6028087/631e9bcc-abac-11e4-9da3-7b0b9a8aa9b0.png)
Figure 2. No Exhaust Object

**Comment by mjwitte** [comment]
Defect files are up in Devsupport.  These run with Miami TMY3.  Also need to cover some other cases - such as when the exhaust flow is greater than the min OA.  Without balancing, this should cause the OA flow to increase to match (as long as exhaust flow is not > max OA).  Then need another case where exhaust flow exceeds max OA and generates unbalanced exhaust flow warnings.  Then these two cases should have increasing fractions of balancing in the exhaust fan and see how the system responds.
