### ISSUE TITLE
Rainfall in EnergyPlus

### ISSUE THREAD

**Issue by lklawrie** [NREL/EnergyPlus#4714]
There are three methods dealing with rainfall/liquid precipitation in EnergyPlus:
1) liquid precipitation amounts on the epw files (for older files, uses present weather and a set of 3mm - as I remember)
2) Site:Precipitation object
3) RoofIrrigation (for Ecoroof). - Irrigation is not exactly rainfall but perhaps should be integrated.

Site:Precipitation is used in the WaterUse:RainCollector object (that is the precipitation feeds that object).
Site:Precipitation is also used in Material:RoofVegetation (but Material:RoofVegetation does not use precip from the epw file if these is not Site:Precipitation object) *MJW 17 Feb 2022*

Liq Precip on the weather file ~~currently only sets the "israining" flag which, in turn, changes the convection coefficient (outside) if the surface is wet.~~ is not used for anything. (see [below](https://github.com/NREL/EnergyPlus/issues/4714#issuecomment-409303076).)

Suggestion is that these should be integrated.

Possibly, the Site:Precipitation object will be more detailed than amounts from the hourly weather file. Ergo, perhaps the Site:Precipitation values should override any values from the weather file.  On the other hand, if there is no Site:Precipitation object, then values from the weather file should feed the WaterUse:RainCollector object.  Not sure where the RoofIrrigation object fits into the scheme of things.

**Comment by mjwitte** [comment]
Related to #4153.  Also, Site:Preciptation feed the ecoroof, rainfall in the epw file does not.  Ref. helpdesk ticket 11702.

**Comment by mjwitte** [comment]
As of [this commit](https://github.com/NREL/EnergyPlusArchive/commit/15bb22b4d121c4a8c185243334b253bdbc8b6770) in April 2012, the liquid precipitation amounts in the epw file are not use for anything. Code was researched in response to [Unmethours 33199](https://unmethours.com/question/33199/precipitation-epw-vs-siteprecipitation/).
