### ISSUE TITLE
Version error message

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4718]
I was running a slightly out-of-date defect file with current code and got this error:
```
Version in IDF="8.2" not the same as expected="8.2"
```
Right.

**Comment by kbenne** [comment]
No doubt gremlins of the third digit gaining significance.

**Comment by mjwitte** [comment]
@Myoldmopar Can this issue be closed?

**Comment by Myoldmopar** [comment]
I verified that the version check functionality is only checking the major/minor version, not the iteration # at all anymore.  I extracted out that function from the code, hardwired the version to match as "8.4.0" and ran the following cases:
- "8.4.0": Pass, no problem
- "8.4.1": Pass, no problem
- "8.5.0": Fail, issue warning

We aren't using iteration numbers in the idfs right now anyway, but either way, this looks like it was fixed.  Closing.
