### ISSUE TITLE
gfortran Linux package

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4722]
On a fresh Ubuntu 8.2, user @nllong found that the libgfortran dependency was unmet.  Installing gfortran remedied it, but it should be fixed.  Google indicates that gfortran has trouble making actual static binaries on Ubuntu, so @kbenne said packaging the runtime shouldn't be too hard.

**Comment by kbenne** [comment]
@nllong what program did you see this with?  It looks like they are all statically linked to runtime.

**Comment by kbenne** [comment]
I think I see, it might be expand objects.
