### ISSUE TITLE
Zone sizing plus ICS solar collector crash due to unallocated collector data

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4723]
Helpdesk ticket 10273
User file crashes when zone sizing is active, because the collectors have not been gotten when CalcPassiveExteriorBaffleGap is called.

**Comment by Nigusse** [comment]
If ICS collector data is not allocated, then the collector parameters (water temperature and bottom loss U-value) required will be reset to default values. Testing the defect IDF shows that the crash issue has been resolved.

https://www.pivotaltracker.com/story/show/90049048

**Comment by Nigusse** [comment]
@jasondegraw Added unit test to verify the fix.
