### ISSUE TITLE
Add a warmup flag as a built in variable to EMS

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#4734]
Some dynamic controls that would be simulated in EMS (especially those based on using random numbers) cause convergence errors in if they are part of the warmup period. Adding a flag variable to indicate when warmup is happening would allow EMS controls to behave in a simpler way during warmup and possibly avoid convergence errors.

**Comment by EnergyArchmage** [comment]
I can take this one.  2 second job.

**Comment by JasonGlazer** [comment]
Can think of any other EnergyPlus internal variables that would make sense to expose to EMS users?

**Comment by EnergyArchmage** [comment]
completed this and made a pull request on branch 4743-EMS-warmup-flag.  I don't know what to do with the word doc snippet that accompanys code change.

**Comment by JasonGlazer** [comment]
Docs go in:

https://github.com/NREL/EnergyPlusBuildSupport/tree/master/docs/src/mods/for_2015_03_release

**Comment by Myoldmopar** [comment]
Closed with #4743
