### ISSUE TITLE
Add a tabular report that shows energy consumption by component 

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#4737]
We should add a tabular report that reports out the annual electric and natural gas (or other fossil fuel) consumption of each and every component/object organized by meter. We already have the "Energy Meter" report that shows this by meter but it would be good to go the next step and see a report that shows all individual annual energy consumption of the components that are on each meter (each fan, each light, each pump, each chiller, etc..)

https://unmethours.com/question/3065/is-there-a-standard-report-to-output-a-breakdown-of-all-electricity-end-use-items/

The challenge of this report would be how to format it to show the large amount of information densely so it doesn't go on for many pages.

**Comment by mjwitte** [comment]
@JasonGlazer Does the new Output:Table:Annual  meet this need?

**Comment by JasonGlazer** [comment]
Certainly one approach would be to create a new Output:Table:Annual report for every type of object that consumes energy. That would result in lots of individual tables.  I guess I was envisioning something that looked like the meter report but under each entry would have an indented list of all the components that contributed to that meter and their individual contributions.
