### ISSUE TITLE
AirLoopHVAC:UnitarySystem - sensible part-load ratio calculation failed warning with gas or electric heating coil using set point based control

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4738]
RegulaFalsi routine needs to pass coil load for proper convergence

In UnitarySystem:GasElecHeatingCoilResidual:

SimulateHeatingCoilComponents( UnitarySystem( UnitarySysNum ).HeatingCoilName, FirstHVACIteration, _, UnitarySystem( UnitarySysNum ).HeatingCoilIndex, _, _, FanOpMode, PartLoadFrac );

should be changed to:

CoilLoad = UnitarySystem( UnitarySysNum ).DesignHeatingCapacity * PartLoadFrac;

SimulateHeatingCoilComponents( UnitarySystem( UnitarySysNum ).HeatingCoilName, FirstHVACIteration, CoilLoad, UnitarySystem( UnitarySysNum ).HeatingCoilIndex, _, _, FanOpMode, PartLoadFrac );

**Comment by rraustad** [comment]
This issue was fixed Feb 20 for V8.2 with the "68304232-1e)-Move-parent-object-sizing-calcs-to-a-common-routine (rraustad)"
I remember doing this and wanted to document the change with an issue.

Fixed at line 1968 here https://github.com/NREL/EnergyPlus/commit/01891ab3af6a54fa74a2f0faeeb9b851d8774a9b

So should I create a unit test or mark this fixed and move on?

**Comment by mjwitte** [comment]
@rraustad At this point, if it's already in develop as part of another fix, I'd say it's done.  But you should reference this issue in the pull request that contained the fix.

**Comment by rraustad** [comment]
See https://github.com/NREL/EnergyPlus/pull/4753.
