### ISSUE TITLE
Basement test file drags down CI

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4759]
Per @mbadams5, the ```LgVAVwithBasement``` test file is a massive bottleneck in CI testing.  The rest of the tests have long completed and this file churns on for a long time.  Improving the speed here would go a long way to helping every CI run.

Perhaps the file can be tuned by better initial condition specification so it reaches convergence sooner, or loosening convergence criteria or simply limiting iterations.  It might cost a little on "accuracy", but it's just an example file so it shouldn't be a problem.

**Comment by mjwitte** [comment]
@Myoldmopar Or do as LKL used to do and don't re-run basement (which isn't changing) but rather put the intermediate file in the test folder and re-run basement only for release tests or if it's been modified.  Could do the same for slab.

**Comment by Myoldmopar** [comment]
That would be interesting.  Definitely a challenge with the automated side of things.  A fresh build is done for each new commit, so CMake won't be aware that things did or didn't change.  Something to keep in mind though since it is essentially wasted build/run time.

**Comment by mjwitte** [comment]
@Myoldmopar I understand all that, but we've gone round this circle before and just hoped the CI would be fast enough to keep up.  I don't think it's worth investing time in speeding up the basement simulation.  Maybe CI could do a quick diff on the basement source for working branches vs develop - if no diff then run LgVAVwithBasement_Quick, otherwise run  LgVAVwithBasement.

**Comment by Myoldmopar** [comment]
I guess the only additional thing I'll say for now is that I'd like to deprecate the external Basement and Slab utilities _relatively_ soon, whatever that means.  We now have the integrated option that is faster and more convenient, and not in FORTRAN.  All reasons to move to the new one.  I will be considering a task to provide a "transition" from the external tools to the internal tools.  It might not be 100% transition-able, but if we can get users 75% of the way there in an automated fashion, and then provide them with much improved runtime, I think it would be awesome.  

Aaaanyway.  I'm not going to spend any time on this right now.  CI is running great thanks to @mbadams5 contributing some additional Windows support.

**Comment by Myoldmopar** [comment]
So for release, it is desired to leave the file in current state.  For testing, we could consider cutting down the basement max iterations to a single year, or two, or three, just not ten.  If we could configure the file with CMake at configure-time with an appropriate number of max years, it would help speed up CI, but still leave the file in proper form for users with the release.  It would show diffs though, in CI.  

We could also add an environment flag for Basement and Slab to respond to which is set by the robots for "quick run" where it internally sets the max years at 1...or 2 or 3.  This way the input file would stay the same, it's just that during testing of the file by CI, it would improve runtime.  And since this could be done on both normal commits and packages, there wouldn't be diffs anymore.  This seems like a quick and easy solution.

What do you think @mjwitte @kbenne @lefticus @mbadams5?
