### ISSUE TITLE
Allow OtherSideCoefficients as outside boundary condition for the AirflowNetwork model

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#4775]
The AirflowNetwork model allows surfaces to be exposed to either outside or a thermal zone. The other outside boundary conditions are not allowed. This issue allows OtherSideCoefficients as outside boundary condition used in the AirflowNetwork.

**Comment by lgu1234** [comment]
Uploaded revised files: AirflowNetworkBalanceManager.cc
Added a unit test file
Uploaded a test file in EnergyPlusDevSupport
No differences were found in example files using the AFN model

**Comment by jasondegraw** [comment]
Fixed by #4786
