### ISSUE TITLE
ConstrNumBack not initialized in complex glazing

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#4777]
current develop crashes with debug builds on complex glazing files.  

![complexglazingcrash](https://cloud.githubusercontent.com/assets/8754769/6557108/25ced394-c638-11e4-81d8-cd40f2d0432f.PNG)

the tests files that are affected include:
CmplxGlz_Daylighting_SouthVB45deg, CmplxGlz_MeasuredDeflectionAndShading, CmplxGlz_SchedSurfGains, CmplxGlz_SingleZone_Deflection, CmplxGlz_SingleZone_DoubleClearAir, CmplxGlz_SingleZone_Vacuum, CmplxGlz_SmOff_IntExtShading

**Comment by mjwitte** [comment]
@Myoldmopar Why aren't these showing as failures in the integration debug coverage CI reports?

**Comment by Myoldmopar** [comment]
I don't know.  I haven't seen them on my own machine either.

**Comment by EnergyArchmage** [comment]
I would suspect the difference is that I was not overriding to run Design Days only.  CI machines rarely run RunPeriods and probably this is an explanation for why these don't show up there.
