### ISSUE TITLE
User file with ideal loads fails with NAN error in surface heat balance which trickles into fatal thermostat error

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4791]
helpdesk ticket 10301
   ** Warning ** Inside surface heat balance did not converge with Max Temp Difference [C] =NAN vs Max Allowed Temp Diff [C] =1.000000E-002
   **   ~~~   **  Environment=ZWICKAU, at Simulation time=02/14 15:03 - 15:06
   ** Severe  ** DualSetPointWithDeadBand: Unanticipated combination of heating and cooling loads - report to EnergyPlus Development Team
   **   ~~~   ** occurs in Zone=00%GROUNDFLOOR:LIVING%ROOM Environment=ZWICKAU, at Simulation time=02/14 15:00 - 15:03
   **   ~~~   ** LoadToHeatingSetPoint=NAN, LoadToCoolingSetPoint=NAN
   **   ~~~   ** Zone Heating Set-point=20.00
   **   ~~~   ** Zone Cooling Set-point=26.00
   **   ~~~   ** Zone TempDepZnLd=NAN
   **   ~~~   ** Zone TempIndZnLd=NAN
   **   ~~~   ** Zone ThermostatSetPoint=0.00
   **  Fatal  ** Program terminates due to above conditions.

ITA_Milano-Malpensa.160660_IGDG.epw

**Comment by mjwitte** [comment]
@Myoldmopar Please run this defect file on Linux to see if it will throw an exception when the NANs first appear.

**Comment by mjwitte** [comment]
@lgu1234 Just realized this file has adaptiveconvection and the problem goes away if that is removed.  So this is probably a duplicate of #4591 and #4646.

**Comment by mjwitte** [comment]
@lgu1234 @EnergyArchmage This file starts failing in CalcBeausoleilMorrisonMixedAssistedWall with these arguments (from an error message added to debug this)
   **   ~~~   ** CalcBeausoleilMorrisonMixedAssistedWall NaN detected.  Hc: NAN DeltaTemp: -2.6399 Height: 0.5057 SurfTemp: 17.3600 SupplyAirTemp: 35.0000 AirChangeRate: 73.2693

The equation here is
```
			Hc = std::pow( std::sqrt( pow_6( 1.5 * std::pow( std::abs( DeltaTemp ) / Height, OneFourth ) ) + std::pow( 1.23 * pow_2( DeltaTemp ), OneSixth ) ) + pow_3( ( ( SurfTemp - SupplyAirTemp ) / std::abs( DeltaTemp ) ) * ( -0.199 + 0.190 * std::pow( AirChangeRate, 0.8 ) ) ), OneThird ); //Tuned pow_6( std::pow( std::abs( DeltaTemp ), OneThird ) ) changed to pow_2( DeltaTemp )
```
This is the Beausoleil Morrison Mixed Assisted Wall equation
![image](https://cloud.githubusercontent.com/assets/4991075/6654004/ffb7e4f0-ca76-11e4-8be9-1ff1dfb48cc7.png)

There are two issues here.  Here's the original FORTRAN equation:
```
    Hc =   (  ((  ((1.5d0 * (( ABS(DeltaTemp)/Height)**OneFourth))**6)            &
             + ((1.23d0*( (ABS(DeltaTemp))**OneThird)**6) )**OneSixth)**0.5d0   &
             + (( ((SurfTemp -  SupplyAirTemp)/ABS(DeltaTemp)) *(-0.199d0 + 0.190d0*(AirChangeRate**0.8d0) ) )**3) ))**OneThird
```
The second line is wrong, should be (I think)
```
             + (1.23d0*(ABS(DeltaTemp)**OneThird))**6) )**0.5d0   &

```
But the real problem is with this term:
```
pow_3( ( ( SurfTemp - SupplyAirTemp ) / std::abs( DeltaTemp ) ) * ( -0.199 + 0.190 * std::pow( AirChangeRate, 0.8 ) )

with SurfTemp=17.3600   SupplyAirTemp = 35.0000  and AirChangeRate = 73.2693 this term evaluates to -55219 and Hc = -18402 (when computed in a spreadsheet).
```
Seems this term needs to check for a combination of high AirChangeRate and high SurfTemp-SupplyAirTemp.

**Comment by lgu1234** [comment]
@mjwitte Thanks for letting me know. I found 5 functions using BeausoleilMorrison methods have problems with negative values. I fixed this problems with #4591. The function should have a solution with pow(-200, 1/3) mathematically. However, C++ program fails. I should be able to commit it Monday morning. It may fix all 3 issues.

**Comment by lgu1234** [comment]
The existing code in CalcBeausoleilMorrisonMixedAssistedWall

		if ( ( DeltaTemp != 0.0 ) && ( Height != 0.0 ) ) {
			Hc = std::pow( std::sqrt( pow_6( 1.5 * std::pow( std::abs( DeltaTemp ) / Height, OneFourth ) ) + std::pow( 1.23 * pow_2( DeltaTemp ), OneSixth ) ) + pow_3( ( ( SurfTemp - SupplyAirTemp ) / std::abs( DeltaTemp ) ) * ( -0.199 + 0.190 * std::pow( AirChangeRate, 0.8 ) ) ), OneThird ); //Tuned pow_6( std::pow( std::abs( DeltaTemp ), OneThird ) ) changed to pow_2( DeltaTemp )
		} else {

My fix for #4591 

		if ( ( DeltaTemp != 0.0 ) && ( Height != 0.0 ) ) {
			powVa;lue =  std::sqrt( pow_6( 1.5 * std::pow( std::abs( DeltaTemp ) / Height, OneFourth ) ) + std::pow( 1.23 * pow_2( DeltaTemp ), OneSixth ) ) + pow_3( ( ( SurfTemp - SupplyAirTemp ) / std::abs( DeltaTemp ) ) * ( -0.199 + 0.190 * std::pow( AirChangeRate, 0.8 ) ) );			Hc = std::pow( std::abs( powValue, OneThird ) ) ;
		if ( powValue < 0.0 ) {


                 }

		} else {

**Comment by lgu1234** [comment]
if ( powValue < 0.0 ) {
               Hc = -Hc

             }

Then the program ran to completion without any errors.

**Comment by lgu1234** [comment]
@mjwitte I thought it last night. The main cause is negative value from ((SurfTemp -  SupplyAirTemp)/ABS(DeltaTemp)), so that the value is negative in the std::pow( value, OneThird ). It is mathematically feasible. Unfortunately, it is not feasible numerically. I think we may have 3 choices:

The first choice is to make numerically feasible (same as mathematically feasible solution). This is what I suggested yesterday.
The second choice to make abs value for both: (ABS(SurfTemp -  SupplyAirTemp)/ABS(DeltaTemp)).
The third choice is to allow the equation as is and fail it when (SurfTemp -  SupplyAirTemp) < 0. In other words, the equation only works at certain conditions.

Here is my suggestion. We may accept the first choice for the time being. We will contact the author to understand the equation limitation, then make changes.

**Comment by mjwitte** [comment]
@lgu1234 Perhaps @EnergyArchmage can offer some advice.  Regarding the (SurfTemp-SupplyAirTemp) it appears that the sign is supposed to be significant, positive for Assisted Wall and negative for Opposing Wall (Engineering Ref. v8.2, pdf p. 113.)

There is also the issue that the term with the 1.23 does not appear to match the equations as shown in the engineering reference and in the original thesis.  
http://www.esru.strath.ac.uk/Documents/PhD/beausoleil-morrison_thesis.pdf

If I'm following correctly, this

```
std::pow( 1.23 * pow_2( DeltaTemp ), OneSixth )
```
should be
```
pow_6( 1.23) * pow_2( DeltaTemp )
```

This term appears in several of the adaptive convection functions.

**Comment by lgu1234** [comment]
Here is my version based on the equation on page 81 (thesis):

			Hn = std::pow( pow_6( 1.5 * std::pow( std::abs( DeltaTemp ) / Height, OneFourth )  + ( 1.23 * std::pow( DeltaTemp, OneThird ) ) ), OneSixth ); //Tuned pow_6( std::pow( std::abs( DeltaTemp ), OneThird ) ) changed to pow_2( DeltaTemp )

**Comment by mjwitte** [comment]
@lgu1234 I believe there must be two pow_6 functions (
```
 Hn = std::pow( 
(pow_6( 1.5 * std::pow( std::abs( DeltaTemp ) / Height, OneFourth ))  + 
pow_6( 1.23 * std::pow(std::abs( DeltaTemp), OneThird ) )
, OneSixth ); 
```

**Comment by EnergyArchmage** [comment]
If I remember correctly, the original thesis had an error in the equation.  A later document had it differently.  But anyway, that entire IBM correlation here is suspect and it may be better to not select a safer correlation to use for adaptive convection algorithm in that case.

**Comment by mjwitte** [comment]
@lgu1234 @EnergyArchmage  OK, if that's the case we need to update the documentation to match.  In either case, for this release, we can implement only the fix to stop the NANs.  And have a followup issue to review the correlation and replace it or update the docs.

**Comment by lgu1234** [comment]
@mjwitte I agree to stop NANs for this release. Then we should have an issue to talk. I think the effort may be more than a bug fix.

**Comment by lgu1234** [comment]
@mjwitte @EnergyArchmage I am going to update the BeausoleilMorrison equations in Eng. Ref. based on E+ code if mismatch is found.
