### ISSUE TITLE
EP-Launch single file transition menu option does not work with iteration builds

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4793]
EP-Launch single file transition menu option doesn't work with iteration builds, because it's still under the old mindset that 8.2.9 means this is a flavor of version 8.2 rather than a preliminary 8.3, so it's looking for transition Transition-V8-1-0-to-V8-2-0.exe

@Myoldmopar @kbenne The transition utilities packaged with the iteration builds have been names Transition-V8-2-0-to-V8-3-0.exe  Should we be calling that Transition-V8-2-0-to-V8-2-9.exe or the like to help clarify that it is interim, not final 8-2-0 to 8-3-0?

Either way, if EP-Launch detects that the patch number is >0 (e.g. 8.2.3) then look for for Transition-V8-2-0-to-V8-3-0 or Transition-V8-2-0-to-V8-2-3.

**Comment by mjwitte** [comment]
This is related to #4780

**Comment by Myoldmopar** [comment]
At our last meeting, we decided to move farther away from creating iteration builds. So I'm closing this, with the hope that soon we can formalize the transition stuff and testing procedures so that iteration builds are more reliable and useful.
