### ISSUE TITLE
Add LCCusePriceEscalationDataSet2014.idf  based on NIST data on life cycle costs

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#4796]
Based on the latest data available, the ENCOST14.TXT file from NIST, create the LCCusePriceEscalationDataSet2014.idf file and include it with the EnergyPlus distribution in the DataSet file. The file contains the LifeCycleCost:UsePriceEscalation objects for electricity and fuels for different parts of the country to be used when applying the life cycle cost method with EnergyPlus. The file for each year has been included for 2010, 2011 and 2012 for the last several versions of EnergyPlus. Also add the previously developed 2013 file which is missing from the 8.2.0 release. To create the file use the ENCOST14.TXT file received from NIST and the ConverrtENCOSTtoEnergyPlusLifeCycleCost.xls spreadsheet developed to create the IDF file. Update the documentation if required and include the reference to the proper version of the NIST Handbook 135 supplement.

**Comment by Myoldmopar** [comment]
Closed via #4881
