### ISSUE TITLE
Autosized Evaporative Condenser Pump Rated Power Consumption causes error

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#4802]
Setting the Evaporative Condenser Pump Rated Power Consumption in the Coil:Cooling:DX:SingleSpeed to autosize generates a severe error:

   ** Severe  ** GetDXCoils: Coil:Cooling:DX:SingleSpeed="FURNACE ACDXCOIL 1", invalid
   **   ~~~   ** ...Evaporative Condenser Pump Rated Power Consumption cannot be < 0.0.
   **   ~~~   ** ...entered value=[-99999.00].

Even though it is an allowed option in the IDD file.

To reproduce this, start with FurnaceWithDXSystem.idf and replace the first Coil:Cooling:DX:SingleSpeed with:

  Coil:Cooling:DX:SingleSpeed,
    Furnace ACDXCoil 1,      !- Name
    FanAndCoilAvailSched,    !- Availability Schedule Name
    25000,                   !- Gross Rated Total Cooling Capacity {W}
    0.75,                    !- Gross Rated Sensible Heat Ratio
    3.0,                     !- Gross Rated Cooling COP {W/W}
    1.3,                     !- Rated Air Flow Rate {m3/s}
    ,                        !- Rated Evaporator Fan Power Per Volume Flow Rate {W/(m3/s)}
    DX Cooling Coil Air Inlet Node,  !- Air Inlet Node Name
    Heating Coil Air Inlet Node,  !- Air Outlet Node Name
    WindACCoolCapFT,         !- Total Cooling Capacity Function of Temperature Curve Name
    WindACCoolCapFFF,        !- Total Cooling Capacity Function of Flow Fraction Curve Name
    WindACEIRFT,             !- Energy Input Ratio Function of Temperature Curve Name
    WindACEIRFFF,            !- Energy Input Ratio Function of Flow Fraction Curve Name
    WindACPLFFPLR,           !- Part Load Fraction Correlation Curve Name
    0.0,                      !- Nominal Time for Condensate Removal to Begin
    0.0,                      !- Ratio of Initial Moisture Evaporation Rate and Steady State Latent Capacity
    0.0,                      !- Maximum Cycling Rate
    0.0,                      !- Latent Capacity Time Constant
    Split TSW Cooling Coil Condenser Inlet,    !- Condenser Air Inlet Node Name
    AirCooled,                !- Condenser Type
    0.0,                      !- Evaporative Condenser Effectiveness
    ,                         !- Evaporative Condenser Air Flow Rate
    autosize,                      !- Evaporative Condenser Pump Rated Power Consumption
    0.0,                      !- Crankcase Heater Capacity
    10.0;                     !- Maximum Outdoor DryBulb Temperature for Crankcase Heater Operation

OutdoorAir:Node,          
    Split TSW Cooling Coil Condenser Inlet,    !- Name
    -1.0;                     !- Height Above Ground

**Comment by Myoldmopar** [comment]
@Nigusse Could you address this?

**Comment by Nigusse** [comment]
yes.

**Comment by Nigusse** [comment]
Closed #4802

**Comment by mjwitte** [comment]
@Nigusse Which pull request addressed this?

**Comment by Nigusse** [comment]
#5117

**Comment by Nigusse** [comment]
@mjwitte This pull request was merged into develop by @Myoldmopar.   Fix evaporator condenser pump autosizing #5117.

**Comment by mjwitte** [comment]
@Nigusse Thanks for adding the cross-reference.
