### ISSUE TITLE
SwimmingPool:Indoor, Pool Heating System Maximum Water Flow Rate is taken as mass flow rate

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#4805]
In SwimmingPool:Indoor, Pool Heating System Maximum Water Flow Rate (m3/s) is taken as mass flow rate (kg/s). You can check it in the sample file, where 0,1m3/s is used as input and 0,1kg/s is shown in results as "Indoor Pool Inlet Water Mass Flow Rate [kg/s]" (and Temperature does not reach setpoint).

I've reviewed the source code but I cannot find the problem, since WaterMassFlowRateMax is multiplied by density in line 633: Pool( PoolNum ).WaterMassFlowRateMax = Pool( PoolNum ).WaterVolFlowMax * Density;

**Comment by mjwitte** [comment]
In reviewing this issue, found that the output variables for Indoor Pool Makeup Water Rate and Indoor Pool Makeup Water Volume are actually reporting mass flow instead of volume flow.  These need to be corrected to report volume flow.

**Comment by Myoldmopar** [comment]
Closed with #5028
