### ISSUE TITLE
Mismatch of BeausoleilMorrison convection equations between Eng. Ref and code

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#4806]
@mjwitte found mismatch of BeausoleilMorrison convection equations between Eng. Ref and code. Eng. Ref needs to be updated based on the code.

**Comment by lgu1234** [comment]
Assign it to Bereket for verification to ensure equations listed in Engineering Reference are the same in the code. I modified the first two equation in the Eng. Ref. Please check 6 equations in the following member functions in ConvectionCOefficients.cc:

CalcBeausoleilMorrisonMixedAssistedWall
CalcBeausoleilMorrisonMixedOpposingWall
CalcBeausoleilMorrisonMixedStableFloor
CalcBeausoleilMorrisonMixedUnstableFloor
CalcBeausoleilMorrisonMixedStableCeiling
CalcBeausoleilMorrisonMixedUnstableCeiling

The revised file is available in Pivotal Tracker and EnergyPlusBuildSupport.

**Comment by Nigusse** [comment]
The equations were verified and the equations in the code and consistent with the attached document.  This bug issue was marked as complete in pivotal but not in github.  I will close bug issue #4806.

**Comment by Nigusse** [comment]
Closed #4806.
