### ISSUE TITLE
Multi year run periods work, but docs need updating

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4815]
@nllong found that custom range run periods work, but the documentation doesn't do justice for how to manipulate the weather files appropriately.  I'll try to post a MWE and multiyear weather file to demonstrate.  Basically you have to update the DATA PERIODS carefully.

**Comment by Myoldmopar** [comment]
This will be resolved with a project next year.

**Comment by brianlball** [comment]
@Myoldmopar any updates on this issue?

**Comment by Myoldmopar** [comment]
This was thoroughly improved with the new run period work; closing this issue.
