### ISSUE TITLE
Climatic Data Summary report missing ASHRAE climate zone, description, CDD, HDD

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#4820]
The Climatic Data Summary report in the tabular results summary should have lines that say "ASHRAE Climate Zone", "ASHRAE Description", "Standard Cooling Degree-Days", and Standard Heating Degree-Day"s that are based on the lines from the STAT file:

 - Climate type "3C" (ASHRAE Standard 196-2006 Climate Zone)**
 -   65 annual (standard) heating degree-days (10°C baseline)
 -   79 annual (standard) cooling degree-days (18.3°C baseline)

That should say "3C", "Warm-Marine",65, and 79 respectively.

This example is from USA_CA_San.Francisco.Intl.AP.724940_TMY3.stat file.

Linda Lawrie found a fix to the routine in the Fortran version based on the line

    if (INDEX(lineIn,'ASHRAE Standards') > 0) lineType=AshStdLine

which should should say:

    if (INDEX(lineIn,'ASHRAE Standard') > 0) lineType=AshStdLine

In OutputReportTabular.f90. The converted line in C++ continues to have say error.

**Comment by JasonGlazer** [comment]
The HDD/CDD portion of the issue may be working already.

**Comment by lklawrie** [comment]
Suggestion?  Seems like an error - the ASHRAE Standard part at least.

**Comment by mjwitte** [comment]
@lklawrie Good point.  Placed on v8.4.0 priority list.
