### ISSUE TITLE
ZoneHVAC:WaterToAirHeatPump does not run when autosized and using Sizing:System.

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#4824]
Found that ZoneHVAC:WaterToAirHeatPump with variable speed coils will not run when the input file has Sizing:System object and SimulationControl is set to Do System Sizing Calculation.  There are flaws in the following program logic in PackageTerminalHeatPump.cc that show up with system sizing.

		if ( ! SysSizingCalc && MySizeFlag( PTUnitNum ) ) {
			SizePTUnit( PTUnitNum );
			MySizeFlag( PTUnitNum ) = false;
		}

		if ( ( PTUnit( PTUnitNum ).DXCoolCoilType_Num == Coil_CoolingWaterToAirHPVSEquationFit || PTUnit( PTUnitNum ).DXCoolCoilType_Num == Coil_CoolingAirToAirVariableSpeed ) && ( 0 == PTUnit( PTUnitNum ).NumOfSpeedCooling ) ) {

 Defect file created from example file ZoneVSWSHP_wDOAS.idf by simply adding a System:Sizing object and setting Do System Sizing Calculation to YES.  Compare defect file 4824_ZoneVSWSHP_wDOAS.idf to example file ZoneVSWSHP_wDOAS.idf, they should run the same but do not.  

The only workaround appears to be hard sizing air system and not using Sizing:System.

**Comment by Myoldmopar** [comment]
So is this a straightforward change that we can make a quick branch and address?  Seems pretty big.

**Comment by EnergyArchmage** [comment]
No it isn't easy, initial attempts at a simple fix have failed.  I plan to do an interim fix to be able to continue with a specific study now underway. So I should have a proposed fix soon, but it won't smallish.

**Comment by mjwitte** [comment]
@rraustad Thoughts?

<div>-------- Original message --------</div><div>From: Brent Griffith <notifications@github.com> </div><div>Date:03/25/2015  2:57 PM  (GMT-06:00) </div><div>To: NREL/EnergyPlus <EnergyPlus@noreply.github.com> </div><div>Subject: Re: [EnergyPlus] ZoneHVAC:WaterToAirHeatPump does not run when
  autosized and using Sizing:System. (#4824) </div><div>
</div>No it isn't easy, initial attempts at a simple fix have failed. I plan to do an interim fix to be able to continue with a specific study now underway. So I should have a proposed fix soon, but it won't smallish.

**Comment by rraustad** [comment]
This appears to be legacy code (using Blame shows no changes near this code) so I'd say the addition of a system sizing object had never been tested. Kinda hard to believe, but that's all I have at this point.
I wonder if simply removing the ! SysSizingCalc from the test would help (I assume that was tried)? Do the zone models get called during system sizing? Does @EnergyArchmage new sizing addition call the zone models repeatedly during sizing? If so, sizing the PTUnits would have to wait until that's done? I see some new arrays that are now in the zone model sizing routines, these would have to be allocated by the time zone models are sized. The zone models get called at some point before the zone sizing arrays have been filled otherwise the !SysSizingCalc or other similar wait flag wouldn't be needed. I'd have to run it to know more.

**Comment by rraustad** [comment]
I removed ! SysSizingCalc from if ( ! SysSizingCalc && MySizeFlag( PTUnitNum ) ) {
 and got passed PTUnit sizing with a crash somewhere in the plant?

 Component Sizing Information, Fan:OnOff, ZONE 1 FAN, Design Size Maximum Flow Rate [m3/s], 1.18419
 Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Total Cooling Capacity [W], 38262.10105
 Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Air Flow Rate [m3/s], 2.13742
 Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Water Flow Rate [m3/s], 2.16106E-003
 Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP COOLING MODE, Design Size Rated Sensible Cooling Capacity [W], 28709.99951
 Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Nominal Heating Capacity [W], 38262.10105
 Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Air Flow Rate [m3/s], 1.60262
 Component Sizing Information, COIL:HEATING:WATERTOAIRHEATPUMP:VARIABLESPEEDEQUATIONFIT, SYS 1 HEAT PUMP HEATING MODE, Design Size Rated Water Flow Rate [m3/s], 1.62034E-003
 Component Sizing Information, Coil:Heating:Gas, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 16004.35904
 Component Sizing Information, Coil:Heating:Gas, HEAT PUMP DX SUPP HEATING COIL 1, User-Specified Nominal Capacity [W], 32000.00000
 Component Sizing Information, Fan:ConstantVolume, SUPPLY FAN 1, Design Size Maximum Flow Rate [m3/s], 6.25000E-002
 Component Sizing Information, Fan:ConstantVolume, SUPPLY FAN 1, User-Specified Maximum Flow Rate [m3/s], 6.25000E-002
 Component Sizing Information, CondenserLoop, CHILLED WATER CONDENSER LOOP, Condenser Loop Volume [m3], 4.50000

**Comment by rraustad** [comment]
It looks like it should have been ! ZoneSizingCalc instead. But then zone equipment does not get called during zone sizing (and does during system sizing) so it shouldn't matter. I can recall why that flag was there but I do remember it was needed for something. So I would say replace SysSizingCalc with ZoneSizingCalc and wait for the bug to show up.

**Comment by rraustad** [comment]
Point this at Slinky HX developer.
After making above change (!ZoneSizingCalc) this defect file crashes here since LNTTS() is not allocated:
line 1962 GroundHeatExchanger
		if ( LnTTsVal <= LNTTS( 1 ) ) {

I don't understand this, don't G-functions get calculated for the vertical HX model?

	void 
	GLHEVert::calcGFunctions()
	{
		// Nothing to see here. Move along.
		// Just a stub out for future work. 
	}

	//******************************************************************************

	void 
	GLHESlinky::calcGFunctions()
	{
		// SUBROUTINE INFORMATION:
		//       AUTHOR:          Matt Mitchell
		//       DATE WRITTEN:    February, 2015
		//       MODIFIED         na
		//       RE-ENGINEERED    na

		// PURPOSE OF THIS SUBROUTINE:
		// calculates g-functions for the slinky ground heat exchanger model
<snip>
		// Allocate and setup g-function arrays
		GFNC.allocate( NPairs );
		LNTTS.allocate( NPairs );

**Comment by Myoldmopar** [comment]
For vertical ground heat exchangers, the g-function values are directly
entered on input, so they don't need any calculation.

For slinky ground heat exchangers, the g-function values are calculated
based on other inputs.

I'm not sure right now why that error is occurring, just explaining the
g-function difference. @mmatts?

**Comment by rraustad** [comment]
Yes, in GetInput

verticalGLHE( GLHENum ).LNTTS.dimension( verticalGLHE( GLHENum ).NPairs, 0.0 );
verticalGLHE( GLHENum ).GFNC.dimension( verticalGLHE( GLHENum ).NPairs, 0.0 );

But these are not the ones used in GLHEBase::interpGFunc which is getting called with the defect file but not in GSHP-GLHE.

**Comment by mmatts** [comment]
@EnergyArchmage @rraustad @Myoldmopar @mjwitte 

The original input file must have been a little older. We deprecated an unused field from the vertical GHX object and that wasn't updated here. I corrected it and pushed to the EPDev Repo [here](https://github.com/NREL/EnergyPlusDevSupport/commit/4f55a64e8f4125697f48f2c14142c3a72e00da20).

It has already been corrected in develop... so I'm guessing this can be closed unless there's another issue. Once the defect file was corrected, it ran to completion on my machine.

**Comment by EnergyArchmage** [comment]
oh sorry, it was an 8.2 file I think.  But this whole Ground HX tangent isn't related to the issue.

**Comment by EnergyArchmage** [comment]
a working fix was drafted out in branch Zone-VS-WSHP-system-sizing-draft and pushed up.

**Comment by mjwitte** [comment]
Closed via #5178
