### ISSUE TITLE
Relax fatal error for DX coil zero capacity or flow rate add more sizing output

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4826]
DX coils (cooling and heating) will cause a fatal error if the capacity or flow rate is <= 0.0.  These should just be warnings.  Not sure if this was done to prevent divide by zero errors in the calc routines, so it may require more code than simply commenting out these blocks
				if ( ErrorsFound ) {
					ShowFatalError( "Preceding condition causes termination." );
				}

It would also be helpful for the dx heating coil (and others?) to report more sizing info including the design inlet and outlet air conditions to help diagnose why a coil may have sized to zero, for example.

**Comment by rraustad** [comment]
PR #4834
