### ISSUE TITLE
Central dx heating coil sizes to zero if cooling coils have not sized yet

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4827]
Defect file has dx heating coil (in a coilsystem:heating:dx) before the dx cooling coil on an airloop.  This results in the dx heating coil sizing to zero, because the heating coil wants to size itself by default to match the cooling coil capacity.   I was expecting the dx heating coil to size itself based on the sizing:system heating supply temp since it's not part of a heatpump unitary system.

**Comment by rraustad** [comment]
So you wanted the heating coil sized differently, and using a different air flow rate. Yes you could put a DX coil in an air loop and only operate it for heating. And same for a DX cooling coil. Regardless, this is a computer simulation so it should work. I've been backing out the limitations we've been applying to HP's so users can do whatever they choose. DX heating coils have been a thorn in the recent past.

**Comment by rraustad** [comment]
I immediately thought UnitarySystem...this is CoilSystem:Heating:DX

Coil sized to 0 since capacity was calculated as a negative value. Inlet temp was 19C.

This deserves a warning:
Sizing:System,            
    PSZ-AC:1,                 !- AirLoop Name
    -15.0,                    !- Central Heating Design Supply Air Temperature

Changing SAT to 40 C yields:
 Component Sizing Information, Coil:Heating:DX:SingleSpeed, PSZ-AC:1_UNITARY_PACKAGE_DX_HPHT, Design Size Gross Rated Heating Capacity [W], 47997.25969

**Comment by mjwitte** [comment]
@rraustad Back in v8.1 (which this analysis is using at the moment) changing SAT to 40 still resulted in a zero size coil.  I guess I did not run that case with v8.2.x  So, this has already been fixed in v8.2.0 and beyond.  @JasonGlazer FYI.

**Comment by rraustad** [comment]
You don't think a warning would be helpful when heating SAT is below entering air temp (which user has little control over)?

**Comment by mjwitte** [comment]
@rraustad That could be covered as part of #4826
