### ISSUE TITLE
Installer overwrites existing DLLs and OCX even if they are newer

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4828]
Helpdesk ticket #10308
User says:

During installation the latest v8.2.0-Update-1.2 installer will overwrite some shared files if they are already installed. For example, gswdll32.dll is overwritten with a older version if it is already installed and this will break other programs that may require a newer version. (For example ArcGIS 10.2.2.) The newer version seems to work fine with EnergyPlus.

Request: the installer should update files if necessary but not downgrade them to older versions if they are already installed.

This is on Windows 7 x64.

**Comment by mjwitte** [comment]
@kbenne For v8.3, perhaps the installer can skip these if already present.

**Comment by kbenne** [comment]
Ok  I'll give it a go.

**Comment by mjwitte** [comment]
@kbenne Thanks.
@JasonGlazer Are you set up to test the installer on a clean Windows machine?  We'll need to test that is does install these when needed.  I assume the install log will show that it did not install when present (on my machine).

**Comment by JasonGlazer** [comment]
@mjwitte Yes, I have a virtual machine with Window 8.1 64bit that is as if it was just installed.

**Comment by kbenne** [comment]
@JasonGlazer can you give this a try?

https://drive.google.com/file/d/0B6AYyX2ggNyBLWg4OHBUSFNFNnc/view?usp=sharing

**Comment by mjwitte** [comment]
@kbenne I installed this on my unclean machine and it runs.  I forgot that we don't get an install log (or is there one hidden somewhere?) so I can't tell if it copied over any dlls or not.  Was this a release build of EnergyPlus?  I'm guessing not.

**Comment by kbenne** [comment]
It was a debug build of energyplus.  I'm not sure about a log.  I'll look into it.

**Comment by JasonGlazer** [comment]
@kbenne and @mjwitte  

After installing it on a clean Window 8.1 64bit. Installation went without a problem. 

When I try to run any simulation I get a crash message when using EP-Launch. When I try to run using RunEPlus I get a message that says "The program can't start because MSCCP120D.dll is missing from your computer. Try reinstalling the program to fix the problem."

IDF Editor open fine. IDF Version Updater opens ok but I could not run it because I had no older files on the VM.

**Comment by JasonGlazer** [comment]
Sorry it is "MSVCP120D.dll"

**Comment by kbenne** [comment]
thats a debug dll.  try the real package that just came off the robot.  https://github.com/NREL/EnergyPlus/releases/tag/v8.3.0-RC2

**Comment by JasonGlazer** [comment]
Using another clean VM. RC2 worked much better. I was able to use EP-Launch to run several simulations. I used IDF Version Updater to convert a file from 8.2 to 8.3 and then ran the 8.3 file. IDF Editor opened fine.
