### ISSUE TITLE
ExpandObjects can't find Energy+.idd on Linux

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4840]
Ref: Helpdesk: 10323

On Linux

Energy+.ini file doesn't appear to be created, so ExpandObjects can't find Energy+.idd.  I verified on 8.2.  Need to verify on 8.3, and address it.  Might be a matter of converting from runenergyplus to the command line interface.

**Comment by Myoldmopar** [comment]
So as I mentioned in the initial comment, this might just be the catalyst needed to remove the `runenergyplus` script on Linux.  The `runenergyplus` script still isn't able to get `ExpandObjects` working, but calling `EnergyPlus -x` works fine.  This is simply the opportunity to push closer toward command line operations, _especially_ on Linux.

**Comment by mjwitte** [comment]
@Myoldmopar So, just noticed on Windows, when running a user file, the same warnings about expandobjects not finding the IDD.  Doesn't happen when I run an example file.  

```
   ** Warning ** Output:PreprocessorMessage="ExpandObjects" has the following Warning condition:
   **   ~~~   ** Cannot find Energy+.idd as specified in Energy+.ini.
   ** Warning ** Output:PreprocessorMessage="ExpandObjects" has the following Warning conditions:
   **   ~~~   ** Since the Energy+.IDD file cannot be read no range or choice checking was
   **   ~~~   ** performed.
```

Maybe this should fork over to a separate issue.

**Comment by mjwitte** [comment]
It shouldn't need the ini file, it should look in the current working directory and find it, at least when run with ep-launch on windows.
