### ISSUE TITLE
Clarify report titles and add more explanation for table sizing reports

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4846]
The sizing reports, such as HVAC Sizing Summary can be confusing, especially to new users, e.g. 
https://unmethours.com/question/4116/ideal-air-loads-in-open-studio/

Initial suggestions:
1.  In Report: HVAC Sizing Summary, the subtable titles "Zone Cooling" and "Zone Heating" should be changed to "Zone Sensible Cooling" and "Zone Sensible Heating".
2.  In Report: HVAC Sizing Summary, add a footnote to the two Zone subtables that states "The Design Load is the zone sensible load only.  It does not include any system effects or ventilation loads."
3.  Add more explanation for this report in Output Details and Examples.
4.  Reorder the sizing reports to be adjacent to each other.  This one should come before the Component Sizing Summary.  The ordering of all of the table outputs should be reviewed.

**Comment by JasonGlazer** [comment]
@mjwitte What kind of additional explanation in Output Details were you thinking about?

**Comment by mjwitte** [comment]
@JasonGlazer For the Zone Cooling/Heating sizing reports, explain what each column (or group of columns) mean, especially the difference between "calculated" and "user" values.  Similar for other sizing reports.

**Comment by JasonGlazer** [comment]
@mjwitte Do you know if there is documentation anywhere that talks about that which I could repurpose in the Output Details docs?

**Comment by mjwitte** [comment]
Not sure.  It _should_ be covered in the I/O Ref sizing section or Engineering Ref, but it's possible that terminology is not consistent.  I'd have to look.

**Comment by JasonGlazer** [comment]
@mjwitte Concerning the original issue (4) about the order of the reports, since the HVAC Sizing Summary is a "predefined" report and the Component Sizing Summary report is not a "predefined" report they cannot be listed too close to one another without some significant recoding. The HVAC Sizing Summary can be before Climatic Data Summary or after LEED Summary. Which would be better?

**Comment by JasonGlazer** [comment]
@mjwitte I found the following:

https://energyplus.net/sites/default/files/docs/site_v8.3.0/InputOutputReference/06-StandardOutputReports/#hvac-sizing-summary

I can copy it over to the Output Details docs. I think it covers the issues raised.

**Comment by mjwitte** [comment]
The text from the I/O Ref is a start, but it could be shortened when it's adjacent to an example output.  And it never says the design load is the sensible zone load.  The note is useful.

Regarding the placement of the reports, you're saying that the Component Sizing Summary cannot go later?  That's a level of detail that seems like it should come after the HVAC Sizing Summary, but it sounds like this is not possible.

**Comment by JasonGlazer** [comment]
Currently the order of reports is closely tied to whether the report is one of the "predefined" ones or not. We could add an new feature issue if you think that would be useful to have the order of reports more definable.

**Comment by mjwitte** [comment]
No, I don't think we need to be able to specify the order of reports.  I'm not following what if "predefined" and what is not.  Aren't all Output:Table:SummaryReports predefined?  How do I know which is which?

**Comment by JasonGlazer** [comment]
I just added #4935 to address the reordering of reports in general as a future suggested feature. It is unfortunately more complicated to reorder the reports than it would appear to be.

**Comment by mjwitte** [comment]
@Myoldmopar Would you be willing to review and merge this one?

**Comment by Myoldmopar** [comment]
Sure, I'll do it.

**Comment by Myoldmopar** [comment]
Fixed with #4937
