### ISSUE TITLE
Scheduled Surface Gains Error

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4847]
@vidanovic reported:

---

When I run EnergyPlus 8.2.0 with Scheduled Surface Gains, following error pops-up:

```
   ** Warning ** ProcessScheduleInput: Schedule:File="NCORE_LIGHT_SCH" 8760 records had errors - these values are set to 0.
   **   ~~~   ** Use Output:Diagnostics,DisplayExtraWarnings; to see individual records in error.
```

I have run same file in EnergyPlus 8.1.0 and that message was not there.

---

I'll upload defect and support files when I receive them.

**Comment by mjwitte** [comment]
@vidanovic Have you confirmed that this issue is still present in current code?  If so, please send me defect files and/or add them to EnergyPlusDevSupport.

**Comment by vidanovic** [comment]
Seems like some formatting problem in schedule files. I have just created simple schedule surface gains example and it did work. So this is not an issue in current code.
