### ISSUE TITLE
ZoneHVAC:OutdoorAirUnit does not autosize child objects correctly

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4854]
Similar problems to what was fixed for the standalone ERV in #4668 

The fans report sizing more than once, the HX has the wrong flow rate, the DX coil has the wrong flow rate and probably the wrong design supply conditions, don't know about other types of equipment - lots of possibilities on this one.

**Comment by rraustad** [comment]
Should probably review all zone equipment sizing routines on this round to catch any others that size themselves within the parent and then the child sizes once the child component is first called. New flag (ZoneEqSizing.DesignSizeFromParent) added by Mike will probably fix all these.

**Comment by mjwitte** [comment]
BTW this is another case where none of the example files included an autosized object for ZoneHVAC:OutdoorAirUnit.  Same was (still is?) true for the ERV.

**Comment by rraustad** [comment]
Non-standard code autosizes all OA units at once:

for ( SizeComp = 1; SizeComp <= NumOfOAUnits; ++SizeComp ) {
    for ( CompNum = 1; CompNum <= OutAirUnit( OAUnitNum ).NumComponents; ++CompNum ) {

Not sure why it's set up this way, might have to revise to size specific OA unit each call.

UPDATE: the outer loop does nothing (SizeComp is not used within the inner loop).

**Comment by rraustad** [comment]
Why the heck is the OA unit sizing water flow rate, steam flow rate, max fan flow rate ???
UPDATE: the OA unit needs to pass max/min water flow rate to ControlCompOutput so this information is needed for water coils

There are only 2 autosizable inputs in this object. SA and EX flow. Once the flow rate is passed to the child, the child should size itself.

From the defect file:

! <Zone Sizing Information>,,,,,,, Calc Outdoor Air Flow Rate {m3/s}
 Zone Sizing Information, BASEMENT,,,,,,, 0.85413

! <Component Sizing Information>, Component Type, Component Name, Input Field Description, Value
 Component Sizing Information, ZoneHVAC:OutdoorAirUnit, BASEMENT_OUTAIRUNIT, Design Size Outdoor Air Flow Rate [m3/s], 0.85413
 Component Sizing Information, ZoneHVAC:OutdoorAirUnit, BASEMENT_OUTAIRUNIT, Design Size Exhaust Air Flow Rate [m3/s], 0.85413
 Component Sizing Information, HeatExchanger:AirToAir:SensibleAndLatent, BASEMENT_HX, Nominal Supply Air Flow Rate [m3/s], 1.82755 (can't size HX flow)
 Component Sizing Information, Coil:Cooling:DX:SingleSpeed, BASEMENT_DXCOIL, Design Size Rated Air Flow Rate [m3/s], 0.85413
 Component Sizing Information, Coil:Cooling:DX:SingleSpeed, BASEMENT_DXCOIL, Design Size Gross Rated Total Cooling Capacity [W], 25458.37279
 Component Sizing Information, Coil:Cooling:DX:SingleSpeed, BASEMENT_DXCOIL, Design Size Gross Rated Sensible Heat Ratio, 0.64680
! <DX Cooling Coil Standard Rating Information>, Component Type, Component Name, Standard Rating (Net) Cooling Capacity {W}, Standard Rated Net COP {W/W}, EER {Btu/W-h}, SEER {Btu/W-h}, IEER {Btu/W-h}
 DX Cooling Coil Standard Rating Information, Coil:Cooling:DX:SingleSpeed, BASEMENT_DXCOIL, 24862.0, 4.33, 14.77, 14.87, 14.96
 Component Sizing Information, Coil:Heating:Gas, BASEMENT_GASHT, Design Size Nominal Capacity [W], 50081.12963
 Component Sizing Information, Fan:ConstantVolume, BASEMENT_OA_FAN, Design Size Maximum Flow Rate [m3/s], 0.85413
 Component Sizing Information, Fan:ConstantVolume, BASEMENT_EXH_FAN, Design Size Maximum Flow Rate [m3/s], 0.85413

**Comment by rraustad** [comment]
Comparison of V8.3 and the new V8.4, Only moderate changes to the mostly non-autosized example file. There were changes to DX coil sizing since the coil now uses the OA unit flow rate to size capacity.

Note this is hourly reporting so simultaneous cooling and heating is possible. I have not test detailed.

No changes to this zone for these select variables:

![outdoorairunit1](https://cloud.githubusercontent.com/assets/5778156/9648297/283bf324-51b5-11e5-9b0a-654e9f217ae6.png)

And moderate changes to these variables, presumably due to the change in autosized coil capacity.

![outdoorairunit2](https://cloud.githubusercontent.com/assets/5778156/9648306/3ad36170-51b5-11e5-8ea2-345d345fbd92.png)

**Comment by rraustad** [comment]
Complete. See PR https://github.com/NREL/EnergyPlus/pull/5166

**Comment by mjwitte** [comment]
Closed via #5166
