### ISSUE TITLE
VRF IO Ref documentation shows incorrect values for schedule priority control 

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4858]
IO Ref V8.3:
Field: Thermostat Priority Schedule Name

This alpha field identifies the schedule used when the previous field is set to Scheduled. Schedule values of 0 denote cooling mode while values of 1 denote heating mode. Any other values will force the system off.

Source Code for HVACVariableRefrigerantFlow.cc

} else if ( SELECT_CASE_var == ScheduledPriority ) {
    if ( GetCurrentScheduleValue( VRF( VRFCond ).SchedPriorityPtr ) == 0 ) {
        HeatingLoad( VRFCond ) = true;
        CoolingLoad( VRFCond ) = false;
    } else if ( GetCurrentScheduleValue( VRF( VRFCond ).SchedPriorityPtr ) == 1 ) {
        HeatingLoad( VRFCond ) = false;
        CoolingLoad( VRFCond ) = true;
    } else {
        HeatingLoad( VRFCond ) = false;
        CoolingLoad( VRFCond ) = false;
    }

0 denotes heating, not cooling. Could change either the code or the documentation. Probably documentation for those legacy input files that use this input.

**Comment by rraustad** [comment]
PR #5142

**Comment by Myoldmopar** [comment]
Closed with #5142
