### ISSUE TITLE
HVACTemplate does not create schedule type limits if TSTAT is missing

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4860]
User file shows this error:
 *\* Warning *\* ProcessScheduleInput: Schedule:Compact="HVACTEMPLATE-ALWAYS 4", Schedule Type Limits Name="HVACTEMPLATE ANY NUMBER" not found -- will not be validated

Possibly due to HVACTemplate:Thermostat object missing.

**Comment by mjwitte** [comment]
If there is no HVACTemplate:Thermostat object, then expandobjects shouldn't be writing the Always 4 Schedule.

**Comment by Myoldmopar** [comment]
Closed with #4917.
