### ISSUE TITLE
Unitary System not working with Variable Speed DX coil model

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#4861]
Failed attempt to change medium office reference building MZ-VAV AHU from using CoilSystem with Two Speed DX coil model to using Unitary System with Variable DX coil model (and SetPoint Control Type).   The cooling coil never provides any cooling and there are no useful error messages.  The same Coil:Cooling:DX:VariableSpeed object does work when using the CoilSystem wrapper, but not when using the AirLoopHVAC:UnitarySystem wrapper.  SetPoint Control Type was used in the Unitary.  

The Unitary System appears to run, but it never actually does cooling at the coil and the air handler has convergence problems.  

Two defect files will be uploaded, one shows the coil model working with CoilSystem, and the other shows it not working with UnitarySystem.  Cooling should come on for the Unitary System and probably operate similiar to the CoilSystem.

**Comment by EnergyArchmage** [comment]
defect files commited to \EnergyPlusDevSupport\DefectFiles\4000s\4861,  use Atlanta weather.

**Comment by EnergyArchmage** [comment]
Fixes for this are sitting on the branch called Zone-VS-WSHP-system-sizing-draft.   That branch started out for separate zone unit defect, but other draft defect fixes like this one have now been mingled in there.

**Comment by rraustad** [comment]
Cooling coil now operates the same as one configured in the air loop as CoilSystem.
![4861_results_vscoil](https://cloud.githubusercontent.com/assets/5778156/9504734/32004256-4c0c-11e5-945f-3de40e63d940.png)

**Comment by rraustad** [comment]
Complete. See https://github.com/NREL/EnergyPlus/pull/5147

**Comment by mjwitte** [comment]
Closed via #5147
