### ISSUE TITLE
EnergyPlus executable is downcased

### ISSUE THREAD

**Issue by nllong** [NREL/EnergyPlus#4863]
On linux the executable for EnergyPlus is now all lower case. It used to be EnergyPlus. This causes issues with case sensitive operating systems when they are calling the program. This appears to be a flapping change as I had some code awhile back to deal with this, then commented it out.

https://github.com/NREL-cookbooks/energyplus/blob/master/providers/default.rb#L89-L90

![image](https://cloud.githubusercontent.com/assets/1907354/7241703/9ec22844-e778-11e4-9dbc-b40acac65ba7.png)

**Comment by axelstudios** [comment]
I was talking with @kbenne about this earlier.

**Comment by nealkruis** [comment]
@nllong there should be a symlink with the original upper case pointing to the new lower case executable. I added the [build command](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CMakeLists.txt#L612) for it, but I don't know if it made it into the install script.

**Comment by axelstudios** [comment]
:+1:

**Comment by Myoldmopar** [comment]
@nealkruis Didn't this get addressed?  (@kbenne)

**Comment by nealkruis** [comment]
It looks like @nllong changed [his source](https://github.com/NREL-cookbooks/energyplus/blob/cd27286227708639c857cdd9abb552ea525d1d39/providers/default.rb#L89) to conform. I also don't know what the expected "fix" is for this, unless the symlinks aren't working.

**Comment by nllong** [comment]
we don't need to fix this on e+ side.

**Comment by nealkruis** [comment]
@Myoldmopar I'm closing this.

**Comment by Myoldmopar** [comment]
Hooray!  Also, @nealkruis, note the [change](https://github.com/NREL/EnergyPlus/commit/7c629655210502521e98cd934241d8e2d35fefc2) I made to fix the man page installation [issue](https://github.com/NREL/EnergyPlus/issues/4925) here that will drop in before release with #5198.

**Comment by nealkruis** [comment]
@Myoldmopar looks good.
