### ISSUE TITLE
Markdown Documentation Work

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4870]
There are some remaining issues with the markdown based documentation that should be resolved to make a fully-polished final product:
- [ ] Scan through encyclopedic reference to clean up remaining tables/styles
- [ ] Lock down at 8.2, move to energyplus.net.  Update Markdown with recent additions
- [ ] Adjust 'prettify' so that idf snippets are colored appropriately (either nicely or not at all)
- [ ] Investigate lazy-loading mathjax for faster loads
  - [ ] If lazy-loading works, look into making a single large doc
  - [ ] if lazy-loading doesn't work, look into splitting the IO and EngRef down to smaller pieces
- [ ] Fix up table of contents, possibly with a scrollbar, or just more intelligently
- [ ] Add IORef landing page
- [ ] Investigate better search options (maybe)
- [ ] Generate PDFs:
  - [ ] Merge IO and EngRef pieces if possible
  - [ ] Static table of contents
  - [ ] Add Cover page -- probably on the html side so that it doesn't botch links in the pdf
  - [ ] Think about solution to search
  - [ ] Bookmarks in the final pdf
- [ ] Wiki cheat sheet for markdown stuff
- [ ] Divide the source files so that each file is small enough to display on github (e.g.most of the I/O ref docs say "(Sorry about that, but we can't show files that are this big right now.)" (MJW)
- [ ] Find a solution for full preview of working branch docs on Windows (MJW)

**Comment by mjwitte** [comment]
@Myoldmopar @kbenne When I look at the docs using the Chrome Markdown Preview extension, it reveals a bunch of extended characters that don't show up in standard text modes.  For example, 01a-InputOutputReference.md looks like this.

![image](https://cloud.githubusercontent.com/assets/4991075/7298748/34d21e1e-e997-11e4-8d25-bcd78b6985be.png)

Looking at the file in hex mode, there are a bunch of seemingly random C2 A0 combinations (that show as A-circumflex space) and the apostrophes and quotes are all two or three hex codes.  They display OK in the text editor as fancy apostrophe and smart quotes, but long-term, do we want these?  Or can we replace them with simple apostrophe and quote?

**Comment by Myoldmopar** [comment]
I've been flushing them out as I encounter them.  There were some that were causing the build process to flat out fail, and those were cleaned out right away.  After that, when I encounter one, I just do a whole doc search and replace with a decent replacement character and move on.  I've had issues, however, with this, where doing this search and replace causes other issues.  But yes, I'm antsy to clean it all out.

**Comment by mjwitte** [comment]
@Myoldmopar @mmatts @kbenne Figured out what the Chrome extension is tripping up on with displaying certain equations.  It's getting confused by underscores - probably trying to interpret them as the markdown tag instead of letting them flow into the equation interpreter.  So, putting a backslash in front of every underscore allows the Chrome extension to display the equation.  Not sure if this is a good thing and it might mess up other tools?  Oh, nevermind, pasting that into the MathJax demo displays all the underscores instead of making subscripts.

**Comment by mjwitte** [comment]
There's an open issue for this at Markdown Preview, so will wait and see if they fix it.
https://github.com/volca/markdown-preview/issues/21

**Comment by Myoldmopar** [comment]
Copying info into semi-duplicate #4900.  Will link back to here as needed.
