### ISSUE TITLE
User file crashes in AirflowNetwork CalcWindPressureCoeffs with array bounds error

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4875]
Helpdesk ticket 10436
Crashes on line 3874 of AirflowNetworkBalanceManager.cc

**Comment by lgu1234** [comment]
I ran the defect file. Here are error messages before crash:

   *\* Severe  *\* AirflowNetwork:MultiZone:Zone Name, duplicate name=THERMAL ZONE 2
   *\* Severe  *\* GetAirflowNetworkInput: AirflowNetwork:MultiZone:Surface object, Surface Name = JAZ3
   *\*   ~~~   *\* ..Zone for inside surface must be defined in a AirflowNetwork:MultiZone:Zone object.  Could not find Zone = THERMAL ZONE 3
   *\* Severe  *\* GetAirflowNetworkInput: AirflowNetwork:MultiZone:Surface object, Surface Name = PORZ3
   *\*   ~~~   *\* ..Zone for inside surface must be defined in a AirflowNetwork:MultiZone:Zone object.  Could not find Zone = THERMAL ZONE 3

After I changed one of AirflowNetwork:MultiZone:Zone duplicated names from THERMAL ZONE 2
to THERMAL ZONE 3, the program ran to completion.

I will add a fatal error when the duplicate name is caught.

**Comment by mjwitte** [comment]
@lgu1234 How did you see these error messages?  My err output file was empty.

**Comment by lgu1234** [comment]
@mjwitte I used the program on my computer based on my local branch, not the public release version. I don't know why they behave differently.

I made a reply in HelpDesk and did not change status. Will my reply be sent to a user?

**Comment by mjwitte** [comment]
@lgu1234 Yes, thanks!

**Comment by Myoldmopar** [comment]
@lgu1234 Could you investigate this again to see if you can reproduce the problem?

**Comment by lgu1234** [comment]
@Myoldmopar Let me take a look at it.

**Comment by lgu1234** [comment]
@Myoldmopar The previous bug fix already issued a fatal error. No more crash. The current error messages are clear enough to help a user to fix an input error. No more effort is needed. I close this issue.

**Comment by lgu1234** [comment]
@Myoldmopar It is OK with release version. However, it crashed in debug. Therefor, this issue still needs to be addressed.

**Comment by jasondegraw** [comment]
Addressed in #5183
