### ISSUE TITLE
The zip files of extra transition programs need updating for v8.3

### ISSUE THREAD

**Issue by jburek** [NREL/EnergyPlus#4878]
I have version 8.3 of Energy plus. 
I couldn't update .idf files (8.0 and 5.0) to 8.3. I checked for add -ons but only found add ons for 8.2.
To be more specific I tried to update .idf files from http://energy.gov/eere/downloads/reference-buildings-building-type-warehouse-0

and  

http://www.energycodes.gov/commercial-prototype-building-models

I would appreciate very much your help on this.
Jasmina

**Comment by mjwitte** [comment]
@jburek Thanks for pointing out that the zip file on the helpdesk should be updated.  For now, the v8.2 zip has all the pieces you need, combined with the Transition-V8-2-0-to-V8-3-0 pieces which are included in the v8.3.0 installer.

http://energyplus.helpserve.com/Knowledgebase/Article/View/86/46/windows---programs-for-converting-older-version-idf-files-to-current-or-intermediate-versions

**Comment by kbenne** [comment]
@mjwitte who should be assigned this issue?  me?

**Comment by mjwitte** [comment]
@Myoldmopar @kbenne We may want to consider adding archives of the historic transition programs to the release page.

**Comment by mjwitte** [comment]
@kbenne Probably you.  Ultimately these transition pieces should become available as needed without any manual steps involved to post an updated archive.  Where and how that happens is up to you and @Myoldmopar .  The download area on the helpdesk can then have a link pointing to the appropriate place.

**Comment by jburek** [comment]
Thank you. It worked :+1:

**Comment by Myoldmopar** [comment]
OK, I think we are locked in with Transition at this point, right @mjwitte?

@kbenne @mjwitte So I can build the full set of transition binaries for Linux easily, Windows slightly less easily, and Mac not easily at all.  Yet...   I am getting a Mac, and a years supply of Mac-flavored kool-aid, next week, so I'll be able to support all three platforms shortly.

I'll build the Linux version and zip them up and send them along.  Perhaps @kbenne can do the Mac similarly?  @mjwitte Maybe you already have the Windows version ready as well.

**Comment by mjwitte** [comment]
That depends, #5136 requires another transition rule.  Need to decide if we're going to get that in for v8.4 or let it ride.

**Comment by mjwitte** [comment]
Now that the installers include all transition from Transition-V7-2-0-to-V8-0-0 forward, I will update the notes on the helpdesk download and close this issue.  @Myoldmopar The Linux and Mac installers include the same set of transitions from v7.2 forward, correct?

**Comment by Myoldmopar** [comment]
https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/CMakeLists.txt#L119-L121

7.2.0 to current, yes.

**Comment by mjwitte** [comment]
Knowledgebase [download descriptions](http://energyplus.helpserve.com/Knowledgebase/List/Index/46/converting-older-version-files) were updated.  Closing.
