### ISSUE TITLE
  adibatic exterior walls and extract data to use in matlab

### ISSUE THREAD

**Issue by CheyenneBerlin** [NREL/EnergyPlus#4882]
Hey,
I have some questions working with EnergyPlus, Open Studio and SketchUp, I'm trying to get my first project done, but its taking quite a while...
i try to figure out how to make two of my exterior walls adiabatic, is that possible?
And I would like to make my own graphes regarding the temperatur in the diffrent themal zones, how can I extract these data from OpenStudio or the EnergyPus Plugin?

Thanks for the help,
Cheyenne

**Comment by MatthewSteen** [comment]
@CheyenneBerlin this isn't the place for questions, it's for submitting bugs or feature requests with the development team. Please ask questions on the [UnmetHours](https://unmethours.com/questions/) site.
