### ISSUE TITLE
WaterToAirHP results SHR > 1.0 when air inlet Humidity ratio less than design supply value

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#4893]
This bug issue is related to bug issue # 4567, pivotal tracker # 90946736 and PR #4836.  

This bug issue addresses the sensible heat ratio greater than 1.0 due to large difference between equipment entering air humidity ratio and the user specified design supply air humidity ratio leaving the equipment.  In this particular PSZ-WSHP example IDF, the zone had zero design load, and the equipment entering air humidity ratio was about 0.005 kg/kg and the user specified supply air humidity ratio was about 0.0075 kg/kg. The defect file is PipingSystem_Underground_FHX.idf and the weather file was Denver, Colorado.

**Comment by Nigusse** [comment]
@mjwitte @rraustad The way forward for this bug issue is to add check for each cooling coil sizing calculation in request sizing (RequestSizing) and other ZoneHVAC sizing routines similar to the fix applied to ZoneHVAC:WaterToAirHeatPump equipment sizing calculation. The fix applied to resolve the SHR > 1.0 problem was to limit the supply condition as follows: 
    SupTemp = min( MixTemp, SupTemp );
    SupHumRat = min( MixHumRat, SupHumRat );

The RequestSizing routine captures most of the cases and I have to lookout for some of the ZoneHVAC equipment individually.  Please let me know your thoughts.

**Comment by mjwitte** [comment]
If @rraustad agrees, that seems like a better place to trap for this than zone sizing calcs that were originally proposed (if I am remembering correctly).

**Comment by rraustad** [comment]
We did discuss this and I am OK with implementing in the parent or RequestSizing routine. I'm not sure I like the use of SupHumRat=min(MixHumRat,SupHumRat) since that could change the users input of supply humrat (and potential reported value). I would rather see the mixed air condition adjusted as MixHumRat = max(MixHumRat,SupHumRat). I'll discuss with Bereket during the correction of this issue and test reporting implications at the same time.

**Comment by rraustad** [comment]
Bereket convinced me to use SupHumRat=min(MixHumrat,SupHumRat). It doesn't matter in either case since we're only adjusting the enthalpy calculation to be purely sensible when deltaW should be 0.

**Comment by Nigusse** [comment]
@mjwitte @rraustad I committed the initial code fix. We expect a cooling sizing related parameters diffs depending on the user specified outlet conditions.  I will review this results to check how this fix impacts the cooling sizing results.

**Comment by rraustad** [comment]
Bereket, did you run the test suite? I see strange results (crashes, diff's in coil capacity that don't make sense) that would have shown up in a test suite run. 

Generally, I think after Amir's email of OS issues, we need to enforce test suite runs (or get CI to do it) before we make changes to code.

**Comment by Nigusse** [comment]
I am running the test suite on CI machine.

**Comment by Nigusse** [comment]
What do you mean "before we make changes to code"? See the latest run, it has only 3 files showing sizing diffs. Any ways I will review those three example files as a verification. We always do CI machine run before pull request.

**Comment by rraustad** [comment]
"before we commit code to the develop branch"

I am looking at the 90946736_SHRgt1_4567 branch and the CI results. I see now, I was looking at the CI results from 2 days ago before you fixed something. These results do look better.

The EMSThromochromicWindow file shows 2 water coils where capacity increased about 3%. I would expect this if there were an issue with delta W since adjusting the SA humrat downward would increase delta H. What I did not expect was to see the SHR decrease. I wonder in that calculation which humrat is used.

**Comment by Nigusse** [comment]
I am going to review the diffs in the three test files to find the cause of these diffs.

**Comment by rraustad** [comment]
A clean CI result with all tests passing does not mean there are no diffs in the results. It only means the eio, err, audit files, and some others, have not changed. But this does not mean the csv file did not change. I think this may be the reason something slipped by us (Amir's email regarding OS) so we need to figure out a way to document the diffs with each commit. The CI machine does not do that now. So until that time, running the test suite on a local machine and checking for diff's is the only way we can be sure there are no unexpected changes to the code.

**Comment by Nigusse** [comment]
I agree. For this bug fix the changes in the csv files will be due to change in sizing results only.

**Comment by Nigusse** [comment]
@Myoldmopar @mjwitte @rraustad The regression results shows diffs in the eio files for two DX cooling coils out of the five DX cooling coils in the example files, but I was expecting to see cooling sizing variables diffs for the five DX cooling coils in the two example files. The two example files were EMSThermochromicWindow.idf and ThermochromicWindow.idf.  I run the two example files in debug mode and stepped through the code and found out that all the five DX cooling coils produced diffs, because in the five DX coils the inlet humidity ratio was less than user specified design supply humidity ratio. This fix assigns the lower humidity ratio as the design supply humidity ratio as follows:
SupHumRat = min( MixHumRat, SupHumRat ); 

Diffs were expected for two example files because the site location used was Las Vegas, where the outside air is drier ( in all cases the inlet humidity ratio was less than 0.00836 kg/kg) compared to the design Humidity Ratio of 0.0085 kg/kg specified for each coil.

My question is, does the CI machine regression test show only sample diffs of similar sizing variables or all diffs of the sizing variables?

**Comment by mjwitte** [comment]
@Nigusse My understanding is that the CI is simply doing a text diff on the eio output.  So every change in any value should be reflected in the diff outputs regardless of magnitude and it should show for every file that's part of the test suite.

**Comment by Nigusse** [comment]
Now I see identical results in the CI and my local machine. The difference being the CI machine runs for for design day and my local machine was run what was specified in the test file, which was weather file run.

**Comment by mjwitte** [comment]
@Nigusse OK, but that shouldn't alter the sizing calcs reported in the eio.

**Comment by Nigusse** [comment]
@mjwitte I agree that should not change the sizing calculation results.  I was wrong. I was looking at the change in supply air humidity ratio and the capacity calculated right after that. But the total cooling capacity is recalculated again if that capacity results in "flow to capacity ratio" out of bound. And the capacity is recalculated using the VolFlow and "flow to capacity ratio" limits. If the supply air humidity ratio change due to this fix requires "flow to capacity ratio" reset to the limit, then we end up in the same capacity even if the supply air humidity ratio was reset to a lower value resulted in capacity change. 

The three DX cooling coils did not show diffs in eio file for the two example files simply because the total cooling capacity was adjusted due to "flow to capacity ratio" out of bound. Otherwise, all the three DX cooling coils inlet humidity ratio was lower than the design supply air humidity ratio and humidity ratio reset was applied.  Using the "flow to capacity ratio" limits to adjust capacity may result in the same capacity even if the supply air humidity ratio was reset to a lower value. So, resetting the supply design humidity ration may not necessarily change the sizing results. 

Now, I see consistent results between the CI and my local machines. I run entire EnergyPlus test suite in my local machine to check the CSV files that I did not brake any thing else.  I found diffs only the three test files consistent with the CI machine sizing calculation diffs noted.

I have added two unit tests for system and zone equipment; each has a DX and a chilled water cooling coils sizing calculation test. The unit tests have passed in debug and release mode, also passed individual and total unit test run.

I will merge my latest code fix with develop shortly.

**Comment by mjwitte** [comment]
@Nigusse Thanks for the explanation.

**Comment by Nigusse** [comment]
Pushed the latest code to remote branch. I do expect the same sizing calculation results diffs previously reported by CI machine and I expect the new unit tests added to pass without any issue.

**Comment by rraustad** [comment]
Replaced with #5012

**Comment by mjwitte** [comment]
No, this is the issue that is addressed by PR #5012.  Will review and merge this week.

**Comment by mjwitte** [comment]
Closed via #5012
