### ISSUE TITLE
High Speed UA autosizing sizing fatal out for FluidCooler:TwoSpeed

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#4895]
High Speed UA autosizing sizing fatal out when the Performance Input Method is UFactorTimesAreaAndDesignWaterFlowRate for FluidCooler:TwoSpeed

**Comment by Nigusse** [comment]
This bug issue corrects fatal out problem when High Speed UA parameter is auto-sized and the performance input method is UFactorTimesAreaAndDesignWaterFlowRate for FluidCooler:TwoSpeed.

Adding the following statement eliminates the problem:
if ( SimpleFluidCooler( FluidCoolerNum ).HighSpeedFluidCoolerUA == AutoSize ) {
     SimpleFluidCooler( FluidCoolerNum ).HighSpeedFluidCoolerUAWasAutoSized = true;
}

A unit test case has been created for this bug and it is ready for reviewing and merging into develop.

**Comment by mjwitte** [comment]
EvaporativeFluidCooler:TwoSpeed has a similar issue in #4560

**Comment by Nigusse** [comment]
@mjwitte I run into this problem when working on another project.
