### ISSUE TITLE
Some equations aren't rendering

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4899]
As I've scrolled through, I've found a few equations that aren't rendering in the docs.  It's likely just something got escaped an extra time or something during one of the automated passes through the docs.  The ones I've seen have had the dollar signs surrounding the equation content, which should make them pretty easy to find.  Just need to spend a few minutes slogging through and cleaning them up.  Or if a pattern is found that is causing the problem, it might be a simple `sed` to get them cleaned up.

**Comment by JasonGlazer** [comment]
@Myoldmopar I am not sure if this one is still supposed to be open now that we have switched to LaTex.

**Comment by Myoldmopar** [comment]
We'll get errors now if an equation won't render.  And we'll be going through the docs over time to clean up all visual issues.  So this can be closed.
