### ISSUE TITLE
Consider Markdown paragraph structure

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4901]
The Markdown might benefit from splitting paragraphs into single lines of code.  This might make working with it a little simpler.  As long as you don't put an extra line break in there, it is equivalent in Markdown.  For example:

```
This is a really long paragraph.  It has lots of sentences.  In fact, it has another one.
```

is equivalent to:

```
This is a really long paragraph.  
It has lots of sentences.  
In fact, it has another one!
```

But if you put extra line breaks, it will assume new paragraphs:

```
This is the first paragraph.

And another paragraph.

In fact, another one!
```

This process can be automated pretty well if it is determined to be a beneficial improvement.

**Comment by JasonGlazer** [comment]
@Myoldmopar I am closing this one since we aren't using markdown anymore.
