### ISSUE TITLE
AirTerminal:SingleDuct:SeriesPIU:Reheat deprecated field still required

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#4902]
AirTerminal:SingleDuct:SeriesPIU:Reheat and AirTerminal:SingleDuct:ParallelPIU:Reheat input field A11 for Hot Water or Steam Inlet Node Name is shown as deprecated. This is true only for the parallel version of this object. Simple fix is to copy 4 lines of code in GetInput and apply to series version. InitPIU also shows a comment where the steam coil steam inlet node is not explicitly initialized based on coil type. At line 705:

//plant upgrade note? why no separate handling of steam coil? add it ?

Not sure if this needs addressing or not, create test file to be sure (other issues with steam coils may become evident).

**Comment by Nigusse** [comment]
I am addressing this issue. Do we need to to remove the deprecated fields from these objects ? @Myoldmopar @mjwitte  or just keep it as is for now.  If removed I need to prepare transition rules.

**Comment by mjwitte** [comment]
Remove, please.  These fields have been \deprecated as far back as v4.0 (didn't look further).

**Comment by mjwitte** [comment]
And while you're at it (either in this issue or a separate one), we should remove similar deprecated fields from:
AirTerminal:SingleDuct:ConstantVolume:FourPipeInduction
AirTerminal:SingleDuct:ConstantVolume:Reheat
AirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan
AirTerminal:SingleDuct:VAV:HeatAndCool:Reheat

**Comment by Nigusse** [comment]
I will issue a separate bug item to remove deprecated fields from these four objects.

**Comment by Nigusse** [comment]
@Myoldmopar I have transition rule prepared for this bug fix.  Where should this transition Rules Spreadsheets (Rules8-4-0-to-8-5-0.xls) go?  I see last release in the build remote branch.

**Comment by mjwitte** [comment]
@Nigusse the rules file is already in develop, so it should be in your branch in 
src/Transition/InputRulesFiles//Rules8-4-0-to-8-5-0.xls

**Comment by Nigusse** [comment]
Ok. @mjwitte Thanks.

**Comment by Nigusse** [comment]
Updated the transition rules spreadsheet file for the series and parallel PIU objects and added the transition rule to the Fortran file "CreateNewIDFUsingRulesV8_5_0". I think this are the only changes I need to make.  Let see what the CI machine does. The 11 example files failed are due to transition only and the other failure is the unit test.  @mjwitte @Myoldmopar Do I need to make any other changes?

**Comment by mjwitte** [comment]
The HVACTemplate processor will need to be modified (epfilter.f90).  I can do that if you want.  Shouldn't be hard - just find the lines that produce the deleted fields and delete them.

**Comment by mjwitte** [comment]
Closed via #5408
