### ISSUE TITLE
Added regeneration air heating coils autosizing calculation in Dehumidifier:Desiccant:System 

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4904]
Helpdesk Ticket 10446

User is questioning the balanced flow presumption in this model.  It appears the the desiccant wheel calculations assume balance flow, but the actual flows through the regen side of the wheel, including the regen fan and heating coil do not appear to match (often zero and or reduced according to the load).  Not clear if this is a reporting issue or a deeper problem.  Also, the DesiccantDehumidifierWithCompanionCoil example file shows very little regen heating coil operation as-is.  Made a different version of this with much higher latent loads in order to get more operation from the desiccants.  At first glance, the OA desiccant system appears to be operating as expected, but if you look at the inlet conditions to the other desiccant it appears that the node conditions are being overwritten.  REGEN COIL INLET NODE:System Node Temperature [C] is defined as an outdoor air node in the idf, and it starts out matching the OA temperature, but later on in the simulation it is reporting a node temperature that matches the desiccant system setpoint temperature.
## Background

_From User:_
I am using desiccant (Dehumidifier:Desiccant:system) in my model. It requires heating object for the regeneration side and I used electric heating coil for that. But when I put the heating coil at the autosizing conditioning, the mass flow rate at the regeneration side become zero. The regeneration mass flow rate have some value only when I put some number for heating coil sizing. Also, the mass flow rate strongly depend upon the sizing number of heating coil. However, it was clearly mentioned that process and regeneration flow rate in HeatExchanger:Desiccant:BalanceFlow will be same.

So can you please tell me that on which parameter the regeneration air flow rate is depend and how can I control that? How can I size the heating coil for the regeneration purpose?

_Reply:_
The RegenFan flow rate will control the regen air flow. In your model that is autosized, but the parent desiccant system is hard-sized. I suspect that the regen fan is sizing to some other flow rate (something which may need a fix). For now, if you specify the desired flow rate in the regen fan, it should give you the desired flow rate.

> How can I size the heating coil for the regeneration purpose?
> Thank you

But the regen heating coil will know nothing about this flow rate (specified in the regen fan) during the sizing stage. So, you may need to hard-size the electric heating coil as well. I will post a bug report to check if all of the sizing flow correctly from the parent desiccant system to the child objects.

_From User:_
I think there is no impact of Regen Fan input (flow rate) on regen air flow rate. I am still getting the variation on regeneration side air flow rate (you can check it in the variable output file). And I am not able to understand why regeneration air flow rate is varied and it different from process air flow rate when EnergyPlus literature saying that the process and regeneration side will have the same air flow rate.

I did some deep calculation and found that there is no use of regeneration air flow rate on heat and mass balance calculation for the desiccant heat exchanger. The model uses only process side air flow rate. However, the heating coil heating rate is calculated by using regeneration air flow rate which is not fundamentally correct.

_Reply:_
Looking at the example file for this, I see some concerns. One thing I see in the example file, is that the required dehumidification load for the Desiccant 1 system is very small, so the dehumidifier is not actively requesting regen heat most of the time. If you report at the detailed (HVAC timestep) frequency, you can see that the unit is only on for a few timesteps. If you increase the latent load in the zones, then the unit runs continuously and the regen flow rate matches the prcoess flow rate. But the regen heating coil for this system is hardly operating, because somehow it's inlet condition is being set to its outlet condition (that should not be happening). And I will also check to see what is being used for the flow rate in the HX calculation.

**Comment by Nigusse** [comment]
@mjwitte I started investigating his defect using the defect file DesiccantDehumidifierWithCompanionCoil with high humidity load.  It appears to me it is working correctly.  I also looked at the the inlet conditions of the regeneration air stream of the Desiccant System on the main branch. The REGEN COIL INLET NODE:System Node Temperature [C] is behaving per the design.  When there is de-humidification load and the companion DX cooling coil is active, then the condenser is providing recovered heat to preheat the outdoor air entering the condenser upto the design setpoint of 46.11C.  The outside air node when there is a companion DX cooling coil with a condenser heat recovery is the condenser air inlet node.  In this case it is "Condenser Inlet Node".  The "REGEN COIL INLET NODE" and "Condenser Inlet Node" match the outside air temperature when dehumidification is not required.

I will modify the example file regeneration heating coils to autosize and see if there is any unusual or suspicious thing. I am not sure if there is anything else I need to investigate further.

**Comment by mjwitte** [comment]
OK.  Is autosizing of the regen fan working ok?

**Comment by Nigusse** [comment]
The reg fans are autosized to the system sizing flow rates of the Airloop branch. This is OK if the desiccant dehumidifier is on the main airloop branch but not when the desiccant in on outdoor air system. I will look into this more deep.  

Reg heating coils sizing looks incorrect. The reason appears to be that the design input temperatures are based on information from the system sizing parameters, which is not appropriate for re-generator coil.  The sizing calculation assumes that the coil design outlet temperature as the preheat or heating supply air temperature. The re-generator heating coil inlet design temperature can be that of a mixed air if the desiccant dehumidifier is on the main airloop branch. The regenerator heating coils should be sized to different supply air temperature than coils on main airloop branch?  This information is not available in gas or electric heating coils.

**Comment by Nigusse** [comment]
The regeneration fan are autosized to the maximum air loop flow rates for both in the primary and the outdoor air systems.  I think this is OK. 

There are a few issues for adding regeneration heating coil sizing that needs to be agreed on:
(1) Design Inlet air temperature ( this depends on the desiccant system entering regeneration air node or where the desiccant system is placed)
(2) Design outlet air temperature ( No information available in the heating coils that can be used for sizing reg coils).  I am proposing to use the "Regeneration Inlet Air Setpoint Temperature" as the design outlet air temperature for reg coils from the "Dehumidifier:Desiccant:System" object.  But this is a temporary solution and can be documented in the IDD and IO ref.  
(3) Design Air Flow Rate (will use the same flow rate as coils in the air loops)

@mjwitte @EnergyArchmage @Myoldmopar Would you please comment on this approach?

**Comment by Nigusse** [comment]
@mjwitte I created a defect IDF for desiccant regeneration heating coils using a hot water coil.  I see the same coil auto-sizing problem as in the gas and electric heating coil.  The same proposed fix can be extended to the hot water and steam heating coils as well.

**Comment by mjwitte** [comment]
@Nigusse I'm ok with just about any approach that can be documented clearly _and_ gives the user some control  We may need to add a new field for "Regeneration Air Heater Design Inlet Air Temperature"?  While this is typically drawing from the outdoor air, it could be taking air from anywhere.

**Comment by Nigusse** [comment]
I have almost finalized the fix but we can still modify it if needed.  Here is the approach I have taken in fixing the problem:
(1) "Design Inlet Air Temperature" is outdoor air temperature if the desiccant is on the primary air loop, or else if on outdoor air system the it takes the return air temperature. By the way the water coil sizing calculation also requires design inlet humidity ratio.
(2) "Design Outlet Air Temperature" is re-generator air set point temperature.

If we want to auto-sizing based on user specified inputs then we need to add three new input fields to the "Dehumidifier:Desiccant:System" object:  Below are the suggested input fields:
(1) Regeneration Air Heater Design Inlet Air Temperature
(2) Regeneration Air Heater Design Inlet Air Humidity Ratio
(3) Regeneration Air Heater Design Outlet Air Temperature

If you agree with the proposed new fields to be added I can go ahead and modify the code first thing in morning. It is good also to think default values as well. @mjwitte for your input?

**Comment by mjwitte** [comment]
@Nigusse I'm OK with the proposed approach without any new fields.  @Myoldmopar @rraustad would you agree?

**Comment by Nigusse** [comment]
While working on Idd update, I see two input fields "Nominal Air Flow Rate" and "Nominal Air Face Velocity" in the "HeatExchanger:Desiccant:BalancedFlow:PerformanceDataType1" object as autosizable.  But the code does not support and it fatal out.  So I am removing them.

**Comment by mjwitte** [comment]
@Nigusse Our goal is for everything to be autosizable, so please post a new issue for the broken autosizable fields, or expand the scope of this issue.

**Comment by Nigusse** [comment]
@mjwitte OK. I will post a new issue. By the way, there is no autosizing calculation method for this object in the first place.

**Comment by mjwitte** [comment]
Closed via #5472
