### ISSUE TITLE
Documentation issues - May 2015

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4906]
Helpdesk ticket 10478
- [x] Input Output Reference does not state what the defaults are for solar/visible/thermal absorptance (ref. all Material:\* objects)

**Comment by mjwitte** [comment]
Helpdesk ticket 10479
- [x] "C:\EnergyPlusV8-3-0\ExampleFiles\AdvancedOutput\ExerciseOutput1 Instructions.pdf" is damaged and will not open.  Was damaged in 8.2 package also.  8.1 copy is OK.

**Comment by mjwitte** [comment]
Helpdesk ticket 10481
- [x] Noticed this in the IDD for WindowMaterial:Glazing:EquivalentLayer,
  A2 , \field Optical Data Type
       \required-field
       \type choice
       \key SpectralAverage
       \key Spectral (not supported now)
  This key should be deleted and replace with a \note, and may as well default to SpectralAverage and need to check getinput and docs (yeah, this is not exactly a documentation issue, but seems to fit in here).

**Comment by rraustad** [comment]
Helpdesk ticket 10164 (PR #4908)
- [x] A sentence in the help for "Rated Total Heating Capacity Sizing Ratio" says:  "When the heating capacity is not autosized, the rated total heating capacity will be equal to the sum of the terminal unit heating coil size. "  It doesn't seem logical as it would imply that the input for heating capacity would be redundant.

Suggested revision:

Field: Rated Heating Capacity Sizing Ratio

 This numeric field defines the ratio of gross heating to gross cooling capacity. The model assumes that when used, this value will be greater than 1. A similar input is available in the ZoneHVAC:TerminalUnit:VariableRefrigerantFlow object. When the heating capacity is autosized, if this field is non-blank, this ratio is used to scale the heating capacity to the gross rated total cooling capacity regardless of the value entered in the terminal unit objects. When the heating capacity is not autosized, the gross rated heating capacity will be equal to the value specified in the Gross Rated Heating Capacity input field and this value will be compared to the sum of the terminal unit heating coil size. If these values are more than 10% different, a warning will be issued when Output:Diagnostics, DisplayExtraWarnings; is included in the input file. If this field is blank and the terminal unit sizing ratio input is also blank, then the heating capacity sizing ratio is assumed to be 1. If this field is not blank and the heating capacity sizing ratio in the terminal unit object(s) is blank, then this ratio also applies to each heating coil. If this field is not blank and the heating capacity sizing ratio in the terminal units is also not blank, then the terminal unit heating coil capacity sizing ratio input applies to each heating coil.

**Comment by mjwitte** [comment]
Helpdesk ticket 10475
- [x] The equation for airflownetwork crack flow is somehwat hidden in the Input Output Reference.  Engineering Reference says
  "The Input Output Reference provides the relationship between airflow and pressure for the most of the components (Ref. AirflowNetwork Model). The relationship between airflow and pressure for the AirflowNetwork:Multizone:Component:DetailedOpening, AirflowNetwork:Multizone:Component:SimpleOpening, and
  AirflowNetwork:Multizone:Component:HorizontalOpening objects are provided in detail in this reference."

The equation for crack flow is shown in the I/O Ref under AirflowNetwork:Multizone:Surface, Field: Window/Door Opening Factor, or Crack Factor and under AirflowNetwork:MultiZone:Surface:Crack and AirflowNetwork:MultiZone:Component:ZoneExhaustFan and OK, so there are several flavors and most of them are spelled out in each airflow network component.  I was going to suggest that these all belong in the Engineering Referece, but perhaps it would be better just to add the equations that govern when an opening is closed in the I/O Ref under AirflowNetwork:MultiZone:SimpleOpening and DetailedOpening.

**Comment by mjwitte** [comment]
Integrate command-line interface documentation into main doc system.  Current documentation for CLI is here:
- The man page is here: https://github.com/NREL/EnergyPlus/blob/develop/doc/man/energyplus.1 ... although that's only useful on Unix...but don't all our users use Unix?
-  An instructional page is here: https://github.com/NREL/EnergyPlus/blob/develop/doc/running-energyplus-from-command-line.md ... this is probably the best page
- Finally the usage is compiled and presented to the user in the case of a "-h" argument, or invalid arguments, here: https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CommandLineInterface.cc#L131

Probably add the instructional page to either Getting Started or Auxiliary Programs and reference it in the other?

MJW (June 2015): Given the controversy over this (see comments below), for now, just do this:
- [x] In InterfaceDeveloper.md, under the heading Running EnergyPlus, replace the first paragraph with:
  EnergyPlus is written in C++ and runs as a console application. More explicit details on running EnergyPlus are available in a separate document (Running EnergyPlus in Auxiliary Programs document). Optional command-line arguments are available (energyplus --help, or man energyplus on Linux systems). The following files are used to run EnergyPlus:
- [x] In the Auxiliary Programs document, under the heading Running EnergyPlus by Hand, replace the first sentence with a new paragraph:
  EnergyPlus runs as a console application with optional command line arguments. The arguments may be listed by typing `energyplus --help` (Windows OS) or `man energyplus` (Linux OS). For more information about the command line interface, see https://github.com/NREL/EnergyPlus/blob/develop/doc/running-energyplus-from-command-line.md. The remainder of this section describes running EnergyPlus in legacy mode (i.e. no command-line arguments) on Windows OS.

**Comment by Myoldmopar** [comment]
Yeah, the [Running Console Applications](https://github.com/NREL/EnergyPlus/blob/develop/doc/src/docs/AuxiliaryPrograms/AuxiliaryPrograms.md#running-console-applications) section seems like the best fit, with a new section called "Taking advantage of the command line interface"

**Comment by mjwitte** [comment]
- [x] For the ZoneCapacitanceMultiplier:ResearchSpecial object   the IDD says that the first input is 
  "Temperature Capacity Multiplier" while the I/O Ref says that its "Sensible Heat Capacity Multiplier".  Modify I/O Ref to match IDD.

**Comment by mjwitte** [comment]
- [x] Site:HeightVariation, Wind Speed Profile Boundary Layer Thickness, IDD says \minimum> 0.0, 

but I/O Ref says: "This field can be set to zero to turn off all wind dependence on height."

Seems the "set to zero" comment belongs in the first and last fields, based on the IDD, and not in the second field.

```
Site:HeightVariation,
       \unique-object
       \memo This object is used if the user requires advanced control over height-dependent
       \memo variations in wind speed and temperature.  When this object is not present, the default model
       \memo for temperature dependence on height is used, and the wind speed is modeled according
       \memo to the Terrain field of the BUILDING object.
  N1 , \field Wind Speed Profile Exponent
       \note Set to zero for no wind speed dependence on height.
       \type real
       \default 0.22
       \minimum 0.0
  N2 , \field Wind Speed Profile Boundary Layer Thickness
       \type real
       \units m
       \default 370.0
       \minimum> 0.0
  N3 ; \field Air Temperature Gradient Coefficient
       \note Set to zero for no air temperature dependence on height.
       \type real
       \units K/m
       \default 0.0065
       \minimum 0.0
```

**Comment by nealkruis** [comment]
@mjwitte @Myoldmopar I agree that the Auxiliary Programs is probably the best place for the CLI documentation in its current structure. Though logically it is not a great fit. @kbenne and I discussed revamping the Getting Started documentation to include the CLI information (and make it platform agnostic--merge it with the [Unix getting started text files](https://github.com/NREL/EnergyPlusBuildSupport/blob/master/release/Mac/EnergyPlus%20Quick%20Start%20Guide.rtf)). This is something we can address later--though hopefully soon.

**Comment by Myoldmopar** [comment]
@nealkruis Sounds good to me.  Would you then recommend leaving the CLI doc as a small standalone piece of the package until the Getting Started guide can get revamped?

**Comment by nealkruis** [comment]
Others may want to weigh in, but that sounds like a good plan to me.

**Comment by mjwitte** [comment]
@nealkruis @Myoldmopar As it stands currently, the CLI is invisible to most users.  Unless someone is tasked with re-writing Getting Started before the fall release, I would suggest that the CLI doc at least be added to the main doc sources.  It could just be the same md doc added into the GettingStarted folder with a mention and a link thrown into the main Getting Started doc.

**Comment by kbenne** [comment]
I don't know, I imagine those who care and know what to do with it will be most comfortable with `man energyplus` or `energyplus --help`.  If they are not then CLI is probably not for them.  But perhaps better advertising is in order.  All out copying of the help or man page to a third location seems redundant to me.

**Comment by mjwitte** [comment]
This was prompted by a helpdesk question from a user trying to follow the main readme instruction #10 under Windows:  "Or enter command line arguments in the Command Arguments field to specify the locations of files."  I searched the repo looking for docs on the CLI so I could point the user to it, and couldn't find it.  From my perspective, all docs belong together, so it seems logical that this file be moved in with the other docs:
https://github.com/NREL/EnergyPlus/blob/develop/doc/running-energyplus-from-command-line.md

**Comment by kbenne** [comment]
How about an addition to the readme pointing them to man and --help for details?  My concern is the documentation being out of date in one of the numerous locations.  If someone writes build rules to assemble the getting started doc using material from the man page then I am less opposed.  All out copying or worse copying and then tweaking is not a good idea.
