### ISSUE TITLE
Increase visibility of transition tools

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#4907]
https://unmethours.com/question/4978/why-are-the-older-energyplus-idf-update-files-not-included-in-distribution/

I can think of some cool ideas to make this more visible.  Will add some more information here shortly.

**Comment by mjwitte** [comment]
@Myoldmopar @kbenne Not sure what your ideas are here, but one suggestion is to make the IDFVersionUpdater a separate install package.  I've gone to keeping a side folder that's not under any particular release of EnergyPlus where I keep a fully set of transition files.  Then I can just add to it with each release and I don't end up with multiple copies of the older transition programs.

**Comment by Myoldmopar** [comment]
See also #4878.

**Comment by mjwitte** [comment]
As discussed in #4878 the transition programs from v7.2.0 forward are now part of the install packages.  Closing.
