### ISSUE TITLE
System with electric preheat coil generates incorrect zero design load warning about Coil:Heating:Water

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4910]
This is an HVACTemplate test file with four VAV systems, each using one of four preheat coil options (none, hotwater, electric, and gas).  

   *\* Warning *\* The design coil load is zero for Coil:Heating:Water VAV SYS 2-ELECPRHT HEATING COIL
   *\*   ~~~   *\* The autosize value for maximum water flow rate is zero
   *\*   ~~~   *\* To change this, input a value for UA, change the heating design day, or lower
   *\*   ~~~   *\*   the system heating design supply air temperature

The coil named in the warning is a Coil:Heating:Electric and it does not have a zero design load
 Component Sizing Information, Coil:Heating:Electric, VAV SYS 2-ELECPRHT PREHEAT COIL, Design Size Nominal Capacity [W], 1366.39972

Possible that something is not being reset in the heating coil sizing routine, or the logic is flawed for simulations with a mix of heating coil types.

**Comment by rraustad** [comment]
V8.4 results:

err:
    *\* Warning *\* The design coil load is zero for Coil:Heating:Water VAV SYS 2-ELECPRHT HEATING COIL
    *\*   ~~~   *\* The autosize value for maximum water flow rate is zero
    *\*   ~~~   *\* To change this, input a value for UA, change the heating design day, or lower
    *\*   ~~~   *\*   the system heating design supply air temperature

expidf:
    Coil:Heating:Water,
      VAV Sys 2-ElecPrHt Heating Coil,                         !- Name

eio:

```
Component Sizing Information, Coil:Heating:Water, VAV SYS 2-ELECPRHT HEATING COIL, Design Size Design Coil Load [W], 0.00000
Component Sizing Information, Coil:Heating:Water, VAV SYS 2-ELECPRHT HEATING COIL, Design Size Maximum Water Flow Rate [m3/s], 0.00000
Component Sizing Information, Coil:Heating:Water, VAV SYS 2-ELECPRHT HEATING COIL, Design Size U-Factor Times Area Value [W/K], 1.00000
```

Now there is an electric heating coil in the OA system named:

```
AirLoopHVAC:OutdoorAirSystem:EquipmentList,
  VAV Sys 2-ElecPrHt OA System Equipment,                  !- Name
  Coil:Heating:Electric,                                   !- Component Object Type
  VAV Sys 2-ElecPrHt Preheat Coil,                         !- Component Name
```

This coil does have capacity:

```
Component Sizing Information, Coil:Heating:Electric, VAV SYS 2-ELECPRHT PREHEAT COIL, Design Size Nominal Capacity [W], 1366.39972
```

The confusion may be the air loop name:

```
AirLoopHVAC,
  VAV Sys 2-ElecPrHt,                                      !- Name
```

So I don't think there is a real problem here.

**Comment by mjwitte** [comment]
@rraustad Thanks.  Upon re-reading the initial issue description, the coil names are clearly different "heating coil" vs "preheat coil".  Closing this.
