### ISSUE TITLE
Unitary system won't autos size variable speed heatpump DX coil

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#4916]
Around line 3238 in HVACUnitarySystem.cc the unitary system needs to get teh child VS coil heating capacity.  

this sha shows the change needed
343d0c750ef9443bf1be332210aff456df5d2f10

**Comment by kbenne** [comment]
@EnergyArchmage I'm assuming you initiated this off of the UnmetHours [issue](https://unmethours.com/question/4984/modeling-self-contained-units-with-a-variable-speed-heat-pump/) and corresponding Yahoo Group topic.  Is that correct?  I was going to prepare an example file to submit with my bug report, but it seems you may have this under control.

**Comment by EnergyArchmage** [comment]
no not really, when I saw those I was reminded to log issues I have been finding and fixing while working on a study using this type of equipment.  I had independently run into lots of little problems and had to push through with source code changes to get the study going.  I filed this Issue as follow up. 

The setpoint control in unitary system raised in that unmet hours issue is seperate I think, and still broken. I have only gotten Load type control to work, as for single zone, but at this point I still use CoilSystem for VS coil in a MSVAV .  I haven't fixed all the issues I have run into.

**Comment by kbenne** [comment]
@EnergyArchmage do you want me to put together a bug report?

**Comment by EnergyArchmage** [comment]
sure.  All my files are huge and won't make good defect files.

**Comment by Myoldmopar** [comment]
@EnergyArchmage Is this included in the fixes in PR #5101 ?

**Comment by EnergyArchmage** [comment]
yes

**Comment by mjwitte** [comment]
Closed via #5178
