### ISSUE TITLE
InputOutputReference document description of the object heatPump:WaterToWater:EquationFit:Heating does not entirely reflect the later EnergyPlus versions

### ISSUE THREAD

**Issue by JacobLindblom** [NREL/EnergyPlus#4924]
The InputOutputReference document description of object heatPump:WaterToWater:EquationFit:Heating has a Field: Rated Heating COP . However the later EnergyPlus versions have replaced the COP field with a field for Rated Heating Power Consumption and five new fields for Heating Compressor power Coefficients.
The Engineering Reference document also seems to have the same problem.

**Comment by Myoldmopar** [comment]
Closed via #5424
