### ISSUE TITLE
EnergyPlus can't be installed on Ubuntu 14.04 if /usr/local/share/man/man1/ does not exist.

### ISSUE THREAD

**Issue by tsnouidui** [NREL/EnergyPlus#4925]
On Linux 64 (Ubuntu), EnergyPlus-8.3.0 relies on the directory /usr/local/share/man/man1 to be installed. If the directory doesn't exist then the installation will fail. If the directory is manually created, then the installation will successfully complete but EnergyPlus will still fail to install because of wrong symbolic links. See the email thread below to reproduce the problem.

Thierry

---

Does any of you succeed in installing the latest release of  EnergyPlus on Ubuntu 14.04?

When I tried to install it using the binaries on 

https://github.com/NREL/EnergyPlus/releases/download/v8.3.0/EnergyPlus-8.3.0-6d97d074ea-Linux-x86_64.sh

I got 

---

Extracting, please wait...
Unpacking to directory /usr/local was successful.
## mv: cannot move '/usr/local/EnergyPlus-8-3-0/energyplus.1' to '/usr/local/share/man/man1/': Not a directory

then I manually created the directory "man1" (which I believe I shouldn't) and tried again. 

This time I got 

---

Extracting, please wait...
Unpacking to directory /usr/local was successful.
## Symbolic links were successful.

But when I tried to start EnergyPlus I got 

---

thierry@srgbcvtb2:~/Downloads$ EnergyPlus
ERROR: Could not find input data dictionary: /home/thierry/Downloads/Energy+.idd.
## Type 'energyplus --help' for usage.

EnergyPlus was basically looking for the IDD at the wrong place.

Are those issues known?

Thanks!

**Comment by Myoldmopar** [comment]
.......I'm concerned as to why it thinks the idd is in your Downloads folder.
- Did you use sudo to get privileges to install into root folders?
- Did you use the default install path and symlink path?

**Comment by tsnouidui** [comment]
Yes to both questions.

**Comment by Myoldmopar** [comment]
And `which energyplus` finds the /usr/local/ version?

**Comment by tsnouidui** [comment]
which EnergyPlus returns following

thierry@srgbcvtb2:~/Downloads$ which EnergyPlus
/usr/local/bin/EnergyPlus

**Comment by kbenne** [comment]
In any case this IDD thing is a separate issue from the man page thing, and I think related to the CLI.

**Comment by tsnouidui** [comment]
I "cd" to another directory and tried to start E+ from there. It seems to me like the start script searches for the IDD in the current directory...
Thanks!
Thierry

**Comment by Myoldmopar** [comment]
I'm concerned these details are at least _slightly_ intertwined, @kbenne, I think if the installation went correctly, the CLI wouldn't have as much trouble.  I'm going to ask a few more questions.  But I'll tag @nealkruis since this may involve the CLI (addressed as a separate issue).

What's the output of `file /usr/local/bin/EnergyPlus`

Also, what about the output of `which energyplus` noting the lower case EnergyPlus.

**Comment by tsnouidui** [comment]
file /usr/local/bin/EnergyPlus returns following
thierry@srgbcvtb2:~$ file /usr/local/bin/EnergyPlus 
/usr/local/bin/EnergyPlus: symbolic link to `/usr/local/EnergyPlus-8-3-0/energyplus'

which energyplus returns nothing...

**Comment by Myoldmopar** [comment]
OK. That's helpful.  I'll try to work things out on a fresh 14.04 image.
