### ISSUE TITLE
PIU secondary air inlet temperature always 0 C when drawing air from return plenum

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4926]
Helpdesk Ticket 10494
From user:
In the EnergyPlus example "5ZoneAirCooledConvCoefPIU.idf". Space1-1 has series PIU and Space 4-1 has parallel PIU, both are drawing air from return plenum. From simulation results, I can see that both PIU secondary air inlet temperature kept at 0 C all the time. I suppose their temperature value should be same as the return plenum outlet temperature.

This is the only example with PIU drawing air from return plenum, so I am not sure if this is a problem with the example IDF file or an EnergyPlus bug.

**Comment by mjwitte** [comment]
The reported value is indeed zero.  This could just be a reporting issue, with the PIU receiving air at the proper condition, but can't tell that without more digging.

**Comment by TiejunWu** [comment]
I checked the simulation results, looks like the 0 C inlet temperature propagated downstream and affected the downstream nodes.

**Comment by wfbuhl** [comment]
Oh ugh. Let me know if you want help. I'm probably culpable for this.

Fred

**Comment by mjwitte** [comment]
@wfbuhl Initial review of the code reveals some significant gaps.
1.  ZoneTempPredictorCorrector::CalcZoneComponentLoadSums has code to add ADU leakage airflows into the return plenum heat balance, but no mention of the PIU induced air flows.
2.  Likewise for ZoneContaminantPredictorCorrector::CorrectZoneContaminants
3.  ZonePlenum::InitAirZoneReturnPlenum sets the massflow rates on the induced nodes (seems correct) because the PIU will set mass flows on the secondary inlet nodes:
`ZoneRetPlenCond( ZonePlenumNum ).InducedMassFlowRate( NodeNum ) = Node( InducedNode ).MassFlowRate`
4. ZonePlenum::CalcAirZoneReturnPlenum sets the plenum outlet mass flow equal to the sum of the plenum inlet flows less the induced mass flow.  I guess this happens because the return air flow rates include the induced air flow (because the PIU secondary node is not connected to a zone exhaust node).
5. In ZonePlenum.cc ZoneRetPlenCond( ZonePlenumNum ).InducedTemp is initialized to zero, but never set to anything else, then used to set the conditions on the induced air nodes.  Same for other node properties.
6.  I can't find any place that the induced air flow impacts the plenum conditions, but I guess that happens via the increased flow in the return air nodes and the reduced plenum outlet node flow, so this is probably ok.
7.  So, perhaps all that is missing is setting the induced conditions (5 above) at the right place.

**Comment by wfbuhl** [comment]
It seems like I checked the air balances but never checked the
temperatures. Or it got lost somewhere. I'll take a look at the code and
see if everything else looks OK.

Fred

**Comment by wfbuhl** [comment]
It looks like ZoneRetPlenCond( ZonePlenumNum ).InducedTemp( IndNum ) etc
never get set to anything in CalcAirZoneReturnPlenum.
In UpdateAirZoneReturnPlenum these (unset)  values are passed along quite
nicely to the induced air nodes. I think that  ZoneRetPlenCond(
 ).InducedTemp( ) should be set to ZoneRetPlenCond(  ).ZoneTemp  and the
same for HumRat and Enthalpy.

Fred

**Comment by mjwitte** [comment]
@wfbuhl Thanks for checking that.  I came to a similar conclusion.  A fix is here #5009 , see if it looks OK.

**Comment by Myoldmopar** [comment]
Closed with #5009.
