### ISSUE TITLE
ThermalStorage:Ice:Detailed curve types

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#4929]
In the IDD for ThermalStorage:Ice:Detailed, the fields named "Discharging Curve Object Type" and "Charging Curve Object Type" list Curve:QuadraticLinear and Curve:CubicLinear as valid keys.  The example file [5ZoneDetailedIceStorage.idf](https://github.com/NREL/EnergyPlus/blob/develop/testfiles/5ZoneDetailedIceStorage.idf#L3123) however lists the curve type as "QuadraticLinear" dropping the "Curve:"  This seems to be what EnergyPlus wants.  Using "Curve:QuadraticLinear" although valid with the IDD results in the following EnergyPlus error.

`** Severe  ** ThermalStorage:Ice:Detailed: Discharge curve type not valid, type=CURVE:QUADRATICLINEAR`

**Comment by mjwitte** [comment]
@kbenne It's unusual to ask for curve object type in the first place.  Most (all?) other components just ask for the curve name. Simplest solution is to change the field names and keep the existing short keys (Curve Object Type --> Curve Type); Option B is to change the source to accept the longer key and (B1 - accept both, or B2 add a transition rule to move older short keys to the new longer one); Option C is to drop the fields altogether (also requires a transition rule).

**Comment by kbenne** [comment]
You have a more global view of IDD consistency so I defer to you.  For what it's worth I like Option C and in fact this is how it is in the OpenStudio model.  The curve type field is not introduced until we translate to idf.  That said I don't know if it is worth a transition to go back now.

**Comment by mjwitte** [comment]
For now, fixing the keys in the IDD to match current source in #5352 .  Will leave this issue open to possibly remove the field altogether in a future release.

**Comment by mjwitte** [comment]
The "... Curve Object Type" fields in ThermalStorage:Ice:Detailed need to be kept, because they cause a change in the independent variables used to evaluate the curve. #6879 suggests changing the key choices for these fields and adding documentation.  Closing this issue.
