### ISSUE TITLE
False EMS sensor error appears when adding one more EMS output variable object

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4941]
Helpdesk ticket 10501
User file runs fine but one additional EnergyManagementSystem:OutputVariable object causes a fatal error in a seemingly unrelated EMS sensor object:

   *\* Severe  *\* Invalid Output:Variable or Output:Meter Name =SYSTEM NODE TEMPERATURE
   *\*   ~~~   *\* Entered in EnergyManagementSystem:Sensor=HHW_RETT
   *\*   ~~~   *\* Output:Variable Name not found
   *\*  Fatal  *\* Errors found in processing Energy Management System input. Preceding condition causes termination.

**Comment by mjwitte** [comment]
Appears to be related to total number of available output variables plus sensors and actuators and EMS output variables.

**Comment by mjwitte** [comment]
The source of the problem is in FindItemInSortedList.  The sort is using different rules than the search and the search is tripping on S_CCFrac which sorts after SYSTEM NODE TEMPERATURE, but the search expects it to be before.

Until the function is fixed, the workaround is to remove the underscore from the Name field in this object:
EnergyManagementSystem:OutputVariable,
    SCCFrac,                !- Name
    S_CCFrac,                !- EMS Variable Name
    Averaged,                !- Type of Data in Variable
    SystemTimestep;          !- Update Frequency

This gets past the error with the defect file in its current state.  The safest workaround is to remove underscore from all EnergyManagementSystem:OutputVariable name fields.

**Comment by mbadams5** [comment]
@mjwitte Are you talking about [this](https://github.com/NREL/EnergyPlus/blob/5de76a72808723b57712ca38aff849d1cdd4d75b/src/EnergyPlus/SortAndStringUtilities.cc#L51) when you say "sort" and [this](https://github.com/NREL/EnergyPlus/blob/5de76a72808723b57712ca38aff849d1cdd4d75b/src/EnergyPlus/InputProcessor.cc#L3475) when you say "search"?

**Comment by mjwitte** [comment]
@mbadams5 Yes.  The sort is using < to compare, and the search is using lessthani()  They disagree on the order of these strings:
                "SYSTEM NODE TEMPERATURE",
                "SYSTEM NODE WETBULB TEMPERATURE",
                "S_CCFRAC",

lessthani() was introduced as part of a speedup change, but the sort wasn't changed to match.

**Comment by mbadams5** [comment]
@mjwitte It seems like this is a difference between case sensitive and case insensitive sort/search at first glance.

This looks like a good opportunity to refactor to use std::sort() and std::binary_search() instead of these custom functions :smiley: Maybe i'll try something this weekend...

**Comment by mjwitte** [comment]
Closed via #5084
