### ISSUE TITLE
VRF with water cooled condenser does not pass hard flow rates to plant loop

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4942]
Helpdesk ticket 10498
User file with hard values for VRF condenser water flow rate, results in zero autosized flow for the tower loop.  If the VRF water flow rates are autosized, then the tower loop sizes OK.

**Comment by rraustad** [comment]
- moved RegisterPlantCompDesignFlow outside of if( autosize)
- revised other logic based on possibility that user sized VRF cooling cap > heating cap

Results after correction show condenser water flow rate (previously 0):

![4942-results](https://cloud.githubusercontent.com/assets/5778156/9483851/a8b16780-4b72-11e5-8f24-c9c3920b95ed.png)

**Comment by rraustad** [comment]
PR #5145

**Comment by rraustad** [comment]
This is ready for review and commit.

**Comment by mjwitte** [comment]
Closed via #5145
