### ISSUE TITLE
Diffuse solar shading changes if the transmittance schedule changes during the year vs constant all year

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4944]
Helpdesk ticket 10499
User was comparing diffuse solar on a shaded window with a fixed shade (no transmittance schedule), no shading surface at all, and a seasonal shade (transmittance schedule = 1 in winter, = 0 in summer).

For the seasonal shade, the seasons with transmittance = 1 match the no shade case exactly.
But the summer with transmittance = 0 compared to the fixed shade case shows the beam matches exactly but the diffuse is significantly different.  The diffuse is close to the fixed shade case, but not exactly.

Added another case with the transmittance schedule = 0 year-round and now the summer results match the fixed shade case.

And another case with transmittance schedule = 0 thru Sep 30, then = 1 for the rest of the year yields a different result for June.

Defect files have Timestep shading calcs and DetailedSkyDiffuse options set, but other options show similar results.

See output for ZN001:WALL-SOUTH:WIN001:Surface Outside Face Incident Sky Diffuse Solar Radiation Rate per Area [W/m2](Hourly)
Happened to choose June 16 to look at but other summer dates show similar results.

**Comment by JasonGlazer** [comment]
@mjwitte @EnergyArchmage @Myoldmopar The Surface Outside Face Incident Sky Diffuse Solar Radiation output variable corresponds with QRadSWOutIncidentSkyDiffuse(). The differences seem to trace to a line that computes this based on AnisoSkyMult() which is calculated in two different routines if shading transmittance varies or not. The equation is identical and the values are different at a specific timestep only for DifShdgRatioIsoSky() and DifShdgRatioHoriz() variables. The larger difference is with the DifShdgRatioIsoSky() array which is also calculated almost identically in two places depending on if it is done once at the beginning or if it done throughout the simulation. The calculation is the ratio of WithShdgIsoSky() and WoShdgIsoSky(). The values for these are very different (by several orders of magnitude) for the two test files that should not be showing any differences. These are calculated in for the non-varying case at:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L8340-L8386

and for the varying case at:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L3608-L3624

It seems (although I may be wrong) that the constant case is calculating across the hemisphere which make sense for the diffuse calculations but the time varying case is not computing across the hemisphere. So do you think the code should be computing WithShdgIsoSky() and WoShdgIsoSky() across the hemisphere even in the time varying case?

**Comment by JasonGlazer** [comment]
@EnergyArchmage I think you are the person who added the code for the varying shading over time. I would really appreciate it if you could take a look at my previous comment and see if you have any advice. Thanks.

**Comment by JasonGlazer** [comment]
@EnergyArchmage this is the issue we talked briefly about at lunch. If you could look at my Dec 11 note maybe I could get going on this again.

**Comment by Myoldmopar** [comment]
Closed via #5741
