### ISSUE TITLE
VRF defrost power calculation problems

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#4950]
While conducting a study of VRF systems, the following issues where found in VRF defrost power calculations.  The model is not useable for defrost systems based on reverse cycle. 
1.  "Reverse cycle" and "timed" are not supported in code logic.  Defrost power always comes out zero.  the following is around line 760 in HVACVariableRefrigerantFlow.cc, but there is no logic to handle the case of Timed control. 

if ( VRF( VRFCond ).DefrostStrategy == ReverseCycle && VRF( VRFCond ).DefrostControl == OnDemand )
1. OnDemand power calculation is missing run time fraction term and does not agree with engineering reference.  Found that when using Reverse cycle with On Demand, the defrost power was too high, even higher that the normal VRF heating power consumption.  Defrost power should be well below heating power, maybe less than 10%.   The engineering reference includes a RTF term, but the code does not have that term.
   
   // this next equation is missing RTF term that shows in Eng Ref
   
   VRF( VRFCond ).DefrostPower = DefrostEIRTempModFac \* ( VRF( VRFCond ).HeatingCapacity / 1.01667 ) \* FractionalDefrostTime;

**Comment by rraustad** [comment]
The defrost code was carried over from Coil:Heating:DX:SingleSpeed. I see the same issue over there.
if ( DXCoil( DXCoilNum ).DefrostStrategy == ReverseCycle && DXCoil( DXCoilNum ).DefrostControl == OnDemand ) {

**Comment by rraustad** [comment]
@EnergyArchmage, is it appropriate to use a 1 if the defrost EIR modifier schedule is blank, or should E+ force the use of a modifier schedule to vary the defrost power with outdoor conditions?

if ( VRF( VRFCond ).DefrostStrategy == ReverseCycle ) {

LoadDueToDefrost = ( 0.01 \* FractionalDefrostTime ) \* ( 7.222 - OutdoorDryBulb ) \* ( VRF( VRFCond ).HeatingCapacity / 1.01667 );

if ( VRF( VRFCond ).DefrostEIRPtr > 0 ) {
  DefrostEIRTempModFac = CurveValue( VRF( VRFCond ).DefrostEIRPtr, max( 15.555, InletAirWetBulbC ), max( 15.555, OutdoorDryBulb ) );
} else {
  DefrostEIRTempModFac = 1.0;
}

**Comment by rraustad** [comment]
Results of Reverse/Timed defrost.

DefrostPower = DefrostEIRTempModFac \* ( VRF( VRFCond ).HeatingCapacity / 1.01667 ) \* FractionalDefrostTime \* VRFHeatingRTF;

DefrostEIRTempModFac = 1 (biquadratic curve set to always be 1)
FractionalDefrostTime = 0.058333

![vrf_defrostpower](https://cloud.githubusercontent.com/assets/5778156/9384143/53fad7bc-471c-11e5-9fc0-89b3938cc74f.png)

**Comment by rraustad** [comment]
Another view of timed defrost using reverse cycle.
![vrf_defrostpower2](https://cloud.githubusercontent.com/assets/5778156/9416125/aff97ece-4811-11e5-8b35-b9c08d55165b.png)

**Comment by rraustad** [comment]
I got rid of using 1 if DefrostEIR curve is missing. Its still a required input with ReverseCycle is selected. The user can put a 1 in the constant term, with the rest 0, if they don't want to vary defrost power with outdoor conditions.

**Comment by rraustad** [comment]
See PR #5135

**Comment by EnergyArchmage** [comment]
I think using DefrostEIRTempModFac = 1.0 is okay there.

**Comment by rraustad** [comment]
I found 1 place where defrost needed to be modified.
HeatingPLR += ( LoadDueToDefrost \* HeatingPLR ) / TotalCondHeatingCapacity;

I don't think this needs iteration since we didn't iterate before. But that also doesn't mean we did it right before.

New figures. Only the top one changed. And from what it appears, this looks more realistic (small defrost power compared to heating capacity). Uses same DefrostEIRTempModFac = 1 curve.

![vrfdefrost](https://cloud.githubusercontent.com/assets/5778156/9455422/0c992e16-4a99-11e5-90f5-722963af7366.png)

**Comment by rraustad** [comment]
Here's another figure to ponder and supports not letting DefrostEIRTempModFac curve name input be blank? Not sure what to make of this one. Below the minimum PLR, RTF<1 and the condenser cycles. Here the ratio of defrost power to heating rate is about 33%. Does that make sense?

![vrfdefrostfraction](https://cloud.githubusercontent.com/assets/5778156/9456089/263008f6-4aa1-11e5-8c23-3df4455c1618.png)

**Comment by EnergyArchmage** [comment]
fixed with pull request #5135
