### ISSUE TITLE
Track and warn when water use equipment cannot meet the target supply temperature

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4954]
Example, plant loop serving WaterUse:Equipment via WaterUse:Connections.  WaterUse:Equipment loads are specified as flow rates and a target hot water supply temperature schedule.  If the plant supplies hot water at a lower temperature, there is no compensation, no warnings, no accounting of unmet load, just less heating energy consumed.  Need to make a side-by-side example with some detailed output (such as Water Use Connections Plant Hot Water Energy) to illustrate the problem.  

From the Input Output Reference for WaterUse:Equipment:
_. . . the WaterUse:Equipment object will attempt to meet a scheduled target temperature at the tap by mixing hot and cold water flows. If the hot water flow is not hot enough, or if the flow is limited by plant loop constraints, the result is a cooler mixed water temperature and the target temperature will not be met._

Suggest new output variables for WaterUse:Equipment:

Water Use Equipment Target Water Temperature Not Met Time [hr]
Water Use Equipment Heating Rate Not Met [W]
Water Use Equipment Heating Energy Not Met [J]

And add reporting of the hours and energy not met in the ABUPS table report.

**Comment by mjwitte** [comment]
Reference [Unmethours 11294](https://unmethours.com/question/11294/how-to-model-condensing-gas-fired-dhw-tank-in-energyplus/?comment=11331#comment-11331)
Similar output variables would be useful for the WaterHeater:\* objects as well.

**Comment by jmarrec** [comment]
+1

**Comment by mjwitte** [comment]
Superceded by #7133.
