### ISSUE TITLE
Documentation issues - June 2015

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4956]
- [x] Helpdesk Ticket 10523
  Engineering Reference section for Combustion Turbine Chiller states "Three sets of coefficients are required to model the open centrifugal chiller as discussed in the section, titled, ‘Electric Chiller Based on BLAST Centrifugal Chiller Model’."
  This should read " . . . 'Electric Chiller Model Based on Fluid Temperature Differences'."
- [x] Similar change also needed under Engine Driven Chiller, search for "BLAST Centrifugal" to find these two places.

**Comment by mjwitte** [comment]
Helpdesk Ticket 10533
There is a NOTE immediately prior to the example specification... which reads:

Note: the air-to-air heat pump's fan, cooling coil, heating coil and supplementary heating coil must be connected in the air loop according to the configuration
shown above (Figure 118) for the blow-through fan configuration. The only other valid configuration is with a draw-through fan placement, where the fan is
located between the DX heating coil and the supplementary heating coil. In addition, the volumetric air flow rate specified in the direct air unit for the controlling
zone should properly reflect the fractional volumetric air flow rate specified in the heat pump object.
- [x] The last sentence should be omitted. The "fraction of volumetric flow to controlling zone" input field in this heat pump object was removed many years ago.

**Comment by mjwitte** [comment]
- [x] Input Output Reference, Controller:MechanicalVentilation, last paragraph before Field: Name is formatted as a heading instead of plain text.

**Comment by mjwitte** [comment]
- [x] Helpdesk ticket 10527
  In the IDD for ZoneHVAC:EquipmentList, the \keys for Zone Equipment 1 Object Type (and 2-18) are missing
  `\key ZoneHVAC:EvaporativeCoolerUnit`

**Comment by mjwitte** [comment]
- [ ] In the IDD, GroundHeatExchanger:Vertical, Maximum Length of Simulation needs units.  From the I/O Ref:
Field: Maximum Length of Simulation
This numeric field contains the maximum number of years of simulation to be carried out.

**Comment by mjwitte** [comment]
- [x] In the IDD, GroundHeatExchanger:Vertical, Maximum Length of Simulation needs units.  From the I/O Ref:
  Field: Maximum Length of Simulation
  This numeric field contains the maximum number of years of simulation to be carried out.
  @mmatts Please confirm that this input is in years.

**Comment by mitchute** [comment]
@mjwitte [Years](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/GroundHeatExchangers.cc#L1412) is correct.

**Comment by mjwitte** [comment]
Closed via #5065
