### ISSUE TITLE
prototype warehouse buildings vs reference warehouse buildings

### ISSUE THREAD

**Issue by jburek** [NREL/EnergyPlus#4961]
I get different output filesfrom EnergyPlus using prototype building files vs. reference buildings (for warehouses). I have trouble understanding why this 2 output files are different. I would like to modify the reference building model for warehouse (size of the warehouse, location, and machinery) and have an output as in prototype building.
I wanted to use EnergyPlus Example File Generator since this one gives an option to model both refrigerated and non-refrigerated warehouse, but it's also not working. 
How can I change the output files of reference building files. Where can I  change the size of the warehouse in reference building files? How can I model conveyors in Energy Plus?
Thank you very much for your help.
Jasmina

**Comment by mjwitte** [comment]
@jburek Please post questions of this nature a unmethours.com or energyplus.helpserve.com  Github issues are for reporting bugs or posting specific suggestions for minor improvements.
