### ISSUE TITLE
ZoneHVAC:Baseboard:RadiantConvective:Water requesting flow at some times when scheduled off

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4962]
Helpdesk ticket 10529
Used the HVAC Template object to define a PTAC for each zone, with a baseboard heater for each zone. By default, the type of baseboard heater given by the expander is "ZoneHVAC:Baseboard:RadiantConvective:Water", and the fraction radiant is 0. 

When I ran the simulation for design days. I noticed that the hot water plant loop pump was running for some hours during the summer design day and heated up the water in the loop. Closer look at the result shows that several of the baseboard heaters had water flow during some hours in the summer design day. Which violates the availability schedule assigned to these baseboard heaters. Also even though these baseboard heater has hot water flow through them, their capacity is 0.

Then I manually changed the baseboard heater to "ZoneHVAC:Baseboard:Convective:Water", and everything looked Ok. Baseboard heater did not operate during the summer design day.

---

Appears that the water flow rate request is not being set to zero when it should be.  There are some hours mid-day that have zero flow, but then the flow starts up again.  See PERIMETER_BOT_ZN_2 BASEBOARD HW INLET:System Node Mass Flow Rate as an example.

**Comment by mjwitte** [comment]
Also helpdesk ticket 10706.  Adding defect file from that ticket. In this one, the hw loop operates ok during cool weather, but as it gets warmer, the pump is running at random times with zero output from the baseboard heat.  Every time the pump runs, the loop temp gets warmer and warmer until it's near 100C and throwing glycol warnings.  Then when the baseboard heat comes back on, it all goes back to normal.

**Comment by Nigusse** [comment]
@mjwitte CalcHWBaseboard() routine does not set the branch inlet node water mass flow rate to zero when the baseboard is off for any reason.  This would be the first round of fix, or this may resolve defect fully.

**Comment by Myoldmopar** [comment]
Closed via #5416
