### ISSUE TITLE
Heat pump air supply temperature exceeding maximum

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#4975]
From @jonwinkler

I uncovered a E+ bug related to the supply air temperature for single stage heat pumps. Attached are associated IDF and hourly output files. The ‘Maximum Supply Air Temperature for Supplemental Heat’ field in the AirLoopHVAC:UnitaryHeatPump:AirToAir is set to 40.55°C (105°F) and clearly this is being exceeded when the supplemental heater turns on (first graph below). This field appears to be operating correctly for the AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed object (second graph below).
## Hourly Results – Single Stage Heat Pump (AirLoopHVAC:UnitaryHeatPump:AirToAir)

![single_stage](https://cloud.githubusercontent.com/assets/5325034/8240611/2b23f7ce-15c1-11e5-835b-64416c065a57.jpeg)
## Hourly Results – Two Stage Heat Pump (AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed)

![two_stage](https://cloud.githubusercontent.com/assets/5325034/8240627/4921da84-15c1-11e5-9690-c97ba9d0e6d4.jpeg)

**Comment by nmerket** [comment]
Added defect files at
https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/4000s/4975

**Comment by nmerket** [comment]
@jonwinkler @ejhw

I just ran the defect file in 8.4 and I'm not seeing this problem:

![index](https://cloud.githubusercontent.com/assets/5325034/8886266/58159018-321c-11e5-8183-584b37298a46.png)

(Grey is the times when the supply temperature is greater than the max supply temperature.)

I'm not seeing any supplemental heating. Am I missing something?

**Comment by mjwitte** [comment]
@jonwinkler @ejhw @nmerket Also, I see that the original defect file has hourly output variables so, the occurrence of high supply temp and sup heat operation may not be conincident.  Use "detailed" reporting frequency to see every individual HVAC time step.

**Comment by nmerket** [comment]
@jonwinkler Can you let me know if I'm okay to close this ticket out?

**Comment by jonwinkler** [comment]
@nmerket It looks like you can.

**Comment by nmerket** [comment]
Thanks.
