### ISSUE TITLE
Reporting of the Coincident Building Heating/Cooling Load

### ISSUE THREAD

**Issue by rongpengzhang** [NREL/EnergyPlus#4984]
The time-step whole building heating/cooling load can be reported by setting up two meters, i.e., HeatingCoils:EnergyTransfer and CoolingCoils:EnergyTransfer, respectively. In the current version EnergyPlus, 20 types of heating equipment are included in the HeatingCoils:EnergyTransfer calculation and 15 types of cooling equipment are included in the CoolingCoils:EnergyTransfer calculation. However, some equipment may be missing.

**Comment by rongpengzhang** [comment]
Fixed in Branch #5191.

**Comment by Myoldmopar** [comment]
Closed via PR #5191
