### ISSUE TITLE
Chiller:ConstantCOP problems - autosizing is broken and incorrect SequentialLoad operation

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4991]
Helpdesk ticket 10577
From user:
I am modeling an office building that uses multi chillers working in SequentialLoad mode. But I found it seemed not working well because the chillers apart from the last one did not generate cooling power (always 0). However, when checking the same model in E+ V8.1.0.009, I can see all chillers work in order.

Attached is a picture detailing the result comparison coming from the model that uses only two chillers, where I give their names Chiller No.1 (first to operate) and Chiller No.2 (last to operate), using E+ V8.1.0.009 and V8.3.0.001 respectively. When E+ V8.3 is used, the first chiller does not operate at all, the last chiller works to the maximum power for some time. In E+ V8.1 I can see first chiller operates with the second chiller operated to provide axillary power.

When using E+ V8.3, if more than two chillers modeled in SequentialLoad mode, it is found only the last one operates.

Reply:
Definitely a bug there. There are bigger problems than just the load sequencing - the condenser loop and towers are all sized to zero flow in v8.3 (not so in v8.1 and v8.2). Have you tried this with another type of chiller, such as Chiller:Electric:EIR?

User:
chiller types other than ConstantCOP are all working

**Comment by mjwitte** [comment]
More complaints about Chiller:ConstantCOP in helpdesk ticket 10634.  This autosizing is broken for this chiller. With hard sizes it will work, but any autosized values in this chiller do not get sized (no entries in the eio sizing output).  The first defect file has hard-sized capacity but autosized flow rates.  The second defect file is fully autosized.  Based on the first defect file, this broke in v8.3, but was not found because none of the regression files have an autosized Chiller:ConstantCOP.  Need to add one, or modify AirCooledElectricChiller.idf or BaseBoardElectric.idf to be autosized.

**Comment by MatthewSteen** [comment]
This object is useful for certain LEED modeling scenarios with central plants serving multiple buildings (http://www.usgbc.org/sites/default/files/DES%20Guidance.pdf). As a workaround the capacity and flow rates can be hard-sized to artificially high values.

**Comment by Nigusse** [comment]
This bug issue is addressed in bug issue #6010.

**Comment by mjwitte** [comment]
Closed via #6012
