### ISSUE TITLE
 Missing MSINET.OCX for EP-Launch and IDF Editor with Windows v8.3.3 Installer

### ISSUE THREAD

**Issue by fireattack** [NREL/EnergyPlus#4993]
Related: #4547

The run-time files mentioned there, at least MSINET.OCX, are still missing from the newest Win x64 installer. It's supposed already fixed accordind to #4547.

**Comment by mjwitte** [comment]
@fireattack  What operating system are you on?  64-bit or 32-bit OS?  The v8.3 64-bit installer has been tested on a clean Win 8.1 machine and the required files were all installed.  We need to figure out what is different.  Have you tried running the installer "as administrator"?

**Comment by fireattack** [comment]
@mjwitte weird, I tried to fix this problem by installing old version (8.2) first (it did the trick), and now I can't reproduce this bug at all. I uninstalled all the versions (with deleting all the runtime files) and then reinstall 8.3.3, it just works fine. 

I believe I just encounter something unusual.

Thank you!
