### ISSUE TITLE
Documentation Issues - June 2015 Part 2

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#4997]
- [x] I/O Ref, Generator:MicroCHP, some equations are not rendered in the pdf.

**Comment by mjwitte** [comment]
- [x] I/O Ref, Generator:MicroCHP, this link leads to an empty page in IE, and Chrome warns there may be malware
  IEA/ECBCS Annex 42 – see www.cogen-sim.net.

possible alternates are
http://www.ecbcs.org/annexes/annex42.htm
http://iea-annex54.org/annex42/index.html

@EnergyArchmage ?

**Comment by mjwitte** [comment]
- [x] I/O Ref the definitions of these output variables all have a simple equation with _(T - T)_ with no subscripts.  Prior to the output variable name changes, there weren't even equations.  So need to add subscripts for clarity (check source code to be certain):

Zone,Average,Surface Outside Face Thermal Radiation to Air Heat Transfer Coefficient [W/m2-K]
Zone,Average,Surface Outside Face Thermal Radiation to Sky Heat Transfer Coefficient [W/m2-K]
Zone,Average,Surface Outside Face Thermal Radiation to Ground Heat Transfer Coefficient [W/m2-K]

**Comment by mjwitte** [comment]
- [x] I/O Ref, Timestep object overview, table about demand window.  "Demanh" --> "Demand"

**Comment by mjwitte** [comment]
- [x] I/O Ref, ZoneHVAC:UnitVentilator, the Supply Air Fan Operating Mode Schedule is missing, copy from ZoneHVAC:UnitHeater.  Also, the control logic needs editing to explain what happens in the two different fan modes.

**Comment by mjwitte** [comment]
Combine with #4956

**Comment by rglazer2** [comment]
@EnergyArchmage What would you suggest as a replacement for the broken link?

**Comment by rglazer2** [comment]
@mjwitte Where can I find the source files to determine the subscripts for the equations in the Zone,Average,Surface Outside Face Thermal Radiation sections?

**Comment by mjwitte** [comment]
@rglazer2 You can search the source code for the variable name, e.g. "Surface Outside Face Thermal Radiation to Air Heat Transfer Coefficient" and you will find a SetupOutputVariable function which assigns a variable to that name.

**Comment by mjwitte** [comment]
Closed via #5065
