### ISSUE TITLE
Verify and possibly update definition of leeward for exterior convection coefficients

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5000]
As an outcome of current ASHRAE Std 140 development work, it has been noted that EnergyPlus uses a test of angle >100degrees to determine if a surface is windward or leeward.   The same test is used for all exterior convection algorithms that are sensitive to wind direction.  However, Yazdanian and Klems (1994, p.4) indicate their data tabulations correspond to “windward and leeward hemispheres”, interpretable as leeward being definable as > 90 degrees from normal wind incidence.  If this interpretation is correct, then should EnergyPlus be changed to use >90 degrees, and should this apply to all convection models or just for DOE-2 and MoWiTT.

**Comment by Myoldmopar** [comment]
Magic issue #5000!

**Comment by RKStrand** [comment]
@mjwitte @Myoldmopar Ok, so the documentation agrees with the code as far as the >100 degrees test, but I have to say that I find no logical reason why 100 is used as the cutoff.  >90 seems more rational as per Yazdanian and Klems.  While someone might argue that we should handle anything related to Walton with the >100 cutoff and DOE-2 and MoWiTT with a cutoff of >90, the reality is that only the Sparrow, DOE-2, and MoWiTT models use this check as far as I can tell.  Why use different values for the windward cutoff?  Seems like >90 has clear logical reasoning while >100 seems strange.  Planning on changing this to use >90 for all models and let the convection fall where it may.

**Comment by mjwitte** [comment]
Closed via #7458

**Comment by RKStrand** [comment]
Thanks, Mike!

On Aug 25, 2019, at 7:19 AM, Michael J. Witte <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed via #7458<https://github.com/NREL/EnergyPlus/pull/7458>
