### ISSUE TITLE
Battery won't charge at max rate

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5004]
I haven't dug into this yet, but here is what I know.  As reported by a colleague here.

> I took a fairly simple example file and added PV and a battery--the resulting .idf is attached. As seen below, for some reason, the load center will export to the grid on some occasions when there is still room left in the battery and when the max. charging limit (10^9 Watts in this case) has not yet been hit.
> ![image](https://cloud.githubusercontent.com/assets/849824/8431597/cb8757bc-1ef7-11e5-9cc0-68cfbaeeee38.png)

(click on the image to see it full-size)

**Comment by EnergyArchmage** [comment]
Is there a defect file for this?

**Comment by EnergyArchmage** [comment]
Closed via #5437
