### ISSUE TITLE
I can't populate the "Water" column in the "Operating Cash Flow by Category table

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/EnergyPlus#5006]
I'm trying to add lifecycle costs to my simulation for water consumption. I was able to do it treating water as a fuel, but then it shows up in the "Energy" column instead of the "Water" column in the "Operating Cash Flow by Category (Without Escalation) table. 

Screenshots and additional description are on this unmet hours post
https://unmethours.com/question/8522/water-lifecycle-costs-in-energyplus/

**Comment by JasonGlazer** [comment]
Added defect file:

https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5006

**Comment by mjwitte** [comment]
Close via #5994
