### ISSUE TITLE
ZoneCrossMixing does not allow overlapping zones

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5007]
ZoneCrossMixing does not allow a given zone to cross-mix with more than one other zone.  This prevents, for example, a core zone from cross-mixing with multiple perimeter zones.
1. The I/O Ref does not mention this at all.
2. The Engineering Ref briefly says "No more than one ZoneCrossMixing object can be used for any receiving zone."
3.  This is checked in HeatBalanceAirManager::GetSimpleAirModelInputs.  The code loops over all the crossmixing objects and if overlapping zones are found, the schedules are tested to see if the overlapping cross-mixing occurs in the same hour. This allows a zone to cross-mix with zone A for some hours and zone B for other hours as long at there is never an hour where both are active at the same time.
4.  Why this limitation is in place has never been clear to me. On the surface, it seems like this should not be a big problem to superimpose multiple cross-mixing flows on the zone air balance.  But there must have been some problem that cause this check to be added.  If we can figure out how to remove the limitation, that would be the best solution overall.  if not, it needs to be documented better in the I/O Ref.
@macumber FYI

**Comment by macumber** [comment]
Thanks @mjwitte !  I had no idea about this limitation

**Comment by mjwitte** [comment]
@wfbuhl @lgu1234 Does one of you remember why overlapping cross-mixing objects are not allowed?

**Comment by macumber** [comment]
Does this limit apply to overlapping mixing objects as well?

**Comment by mjwitte** [comment]
@macumber No. You can mix and match ZoneMixing objects as much as you want.

**Comment by lgu1234** [comment]
@mjwitte When I looked at FY14 new feature items, a task of "cross mixing, multiple in zones" is listed. Unfortunately, it was dropped. It is obvious that we should be able to remove the restriction.

**Comment by lgu1234** [comment]
@mjwitte I am handling this issue to remove overlapping restriction. Here are a couple of issues I need your advice.
1. Do we allow multiple objects to have the same source and receiving zones? The current code does not allow. I prefer not allow too.
2. If not allowed, do we allow two objects by switching source and receiving zones? The current code allows when Delta Temperature > 0, because both objects will not be activated at the same time. I think to keep this option.

**Comment by mjwitte** [comment]
> Do we allow multiple objects to have the same source and receiving zones? The current code does not allow. I prefer not allow too.

I would say, yes, allow this.  Users may have reasons to connect the same two zones in different ways, representing different connections or different schedules. @lgu1234 Why do you prefer not to allow it?

**Comment by lgu1234** [comment]
@mjwitte OK to allow multiple objects for the same zones. This process is consistent with other simple airflow objects, such as infiltration, ventilation and mixing. The reason for me not to prefer is that it may have possible abuse, since no error check will be performed.

**Comment by mjwitte** [comment]
I don't think the potential problems will be any greater than already exist for ZoneMixing.

**Comment by Myoldmopar** [comment]
Closed via #5698
