### ISSUE TITLE
Venting Availability Schedule does not work properly in the AFN model

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#5021]
Venting Availability Schedule does not work properly when a AFN surface is set to ZoneLevel control.

Ticket 10615

One odd result I've noticed about the AFN settings: when you try to set behavior at the zone level, those settings do not always seem to transfer to the surfaces in the zone, even if the surface is set to ZoneLevel control. And the result can be strange, like windows being available for opening when the schedule says they are not.

In the attached, take a look at the zone "sala de aula." It's AFN object is controlled by temp, with a constant setpoint of 21, value of 1 for the minimum venting open factor but otherwise defaults for the temp and enthalpy difference lower and upper limits, and an availability schedule called "Aula people schedule."

Now check out two windows in that zone: "Aula window 1" and "Aula window 2". Window 1 is set to ZoneLevel control. Window 2 is set to temperature control, with the exact same settings used for the zone. They two should therefore be controlled the same then, right? 

That doesn't happen. What happens is that Window 1 is always available, even when the availability schedule says it should be. The availability schedule works for Window 2. You can see in the attached AFNsurfaceHeritabilityDemo.csv that Window 2 is available when the schedule is positive-valued, but Window 1 is available even when the schedule value is 0.

I believe the issue is on line 924 of AirflowNetworkBalanceManager.cc, which says:

if ( NumAlphas == 4 && ( ! lAlphaBlanks( 4 ) ) ) {

That worked when the availability schedule was the last field, but now more alpha fields have been added the input spec for AirflowNetwork:MultiZone:Zone. There is the "Single Sided Wind Pressure Coefficient Algorithm" (SSWPCA) and the "Occupant Ventilation Control Name." 

The code needs to be changed to NumAlphas >= 4.

I removed the "Standard" entry from the SSWPCA field in the corrected version AFNsurfaceHeritabilityDemo_correct.csv attached and the problem was solved. It's worth noting that "Standard" is automatically added in as default now by IDF Editor, so every user would have this problem unless they specifically know to blank the SSWPCA field.

Let me know what you think. Oh, I ran it in San Francisco.

**Comment by jasondegraw** [comment]
Closed by #5161
