### ISSUE TITLE
Crash with missing AirflowNetwork:MultiZone:Zone object

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5029]
Helpdesk ticket 10619
User file crashing with empty err file.  Running in debug build reveals these errors:
   *\* Severe  *\* GetAirflowNetworkInput: For an AirflowNetwork Simulation, at least one AirflowNetwork:MultiZone:Zone object is required but none were found.
   *\* Severe  *\* GetAirflowNetworkInput: AirflowNetwork:MultiZone:Surface object, Surface Name = PAROESTEZN1TERREO
   *\*   ~~~   *\* ..Zone for inside surface must be defined in a AirflowNetwork:MultiZone:Zone object.  Could not find Zone = ZN1TERREO THERMAL ZONE THERMAL ZONE THERMAL ZONE
   *\* Severe  *\* GetAirflowNetworkInput: AirflowNetwork:MultiZone:Surface object, Surface Name = PARNORTEZN1TERREO 1
   *\*   ~~~   *\* ..Zone for inside surface must be defined in a AirflowNetwork:MultiZone:Zone object.  Could not find Zone = THERMAL ZONE 1 THERMAL ZONE THERMAL ZONE
   *\* Severe  *\* GetAirflowNetworkInput: AirflowNetwork:MultiZone:Surface object, Surface Name = PARLESTEZN1TERREO 2
   *\*   ~~~   *\* ..Zone for inside surface must be defined in a AirflowNetwork:MultiZone:Zone object.  Could not find Zone = THERMAL ZONE 2 THERMAL ZONE THERMAL ZONE

**Comment by jasondegraw** [comment]
Closed with #5148
