### ISSUE TITLE
Autosized cooling tower reports capacity smaller than chiller capacity

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5032]
User file shows reported size of the cooling tower is smaller than that of the chiller, in Equipment Summary report for Central Plant:
Chilled:Electric:EIR nominal capacity = 976kW
CoolingTower:SingleSpeed nominal capacity = 919kW

**Comment by jmarrec** [comment]
Is there a defect file for this?

**Comment by mjwitte** [comment]
I found the e-mail thread about this and #5033 . idf files were requested but apparently never received. Closing both.
