### ISSUE TITLE
Add design approach deltaT as user input for cooling tower sizing

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5034]
Energy efficiency of the chilled water plant can be improved by sizing a cooling tower (heat rejection plant) to work at wider than normal design conditions.  Being able to autosize cooling towers by describing the approach delta t is an excellent way of achieving this.

**Comment by mjwitte** [comment]
This may be a duplicate of #5020 (just noticed this)

**Comment by Nigusse** [comment]
I agree with Mike. This has been addressed in #5020.

**Comment by jasondegraw** [comment]
Based upon the discussion here, I'm going to close this as addressed.
