### ISSUE TITLE
VRF simulation crashes when VRF terminal unit is not listed in a ZoneTerminalUnitList. 

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#5037]
Test for 0 index needed in 2 places (new IF checks):
One for cooling coil (line 2282 of HVACVariableRefrigerantFlow.cc):
if ( VRFTU( VRFTUNum ).TUListIndex > 0 && VRFTU( VRFTUNum ).IndexToTUInTUList > 0 ) {
    TerminalUnitList( VRFTU( VRFTUNum ).TUListIndex ).CoolingCoilAvailSchPtr( VRFTU( VRFTUNum ).IndexToTUInTUList ) = GetDXCoilAvailSchPtr( DXCoolingCoilType, cAlphaArgs( 12 ), errFlag );
}

One for heating coil (line 2329):
if ( VRFTU( VRFTUNum ).TUListIndex > 0 && VRFTU( VRFTUNum ).IndexToTUInTUList > 0 ) {
    TerminalUnitList( VRFTU( VRFTUNum ).TUListIndex ).HeatingCoilAvailSchPtr( VRFTU( VRFTUNum ).IndexToTUInTUList ) = GetDXCoilAvailSchPtr( DXHeatingCoilType, cAlphaArgs( 14 ), errFlag );
}

**Comment by EnergyArchmage** [comment]
seem like a duplicate of #4952 (?)

**Comment by rraustad** [comment]
Test for 0 index needed in 2 places (new IF checks):

 One for cooling coil (line 2282 of HVACVariableRefrigerantFlow.cc):
 if ( VRFTU( VRFTUNum ).TUListIndex > 0 && VRFTU( VRFTUNum ).IndexToTUInTUList > 0 ) {
 TerminalUnitList( VRFTU( VRFTUNum ).TUListIndex ).CoolingCoilAvailSchPtr( VRFTU( VRFTUNum ).IndexToTUInTUList ) = GetDXCoilAvailSchPtr( DXCoolingCoilType, cAlphaArgs( 12 ), errFlag );
 }

One for heating coil (line 2329):
 if ( VRFTU( VRFTUNum ).TUListIndex > 0 && VRFTU( VRFTUNum ).IndexToTUInTUList > 0 ) {
 TerminalUnitList( VRFTU( VRFTUNum ).TUListIndex ).HeatingCoilAvailSchPtr( VRFTU( VRFTUNum ).IndexToTUInTUList ) = GetDXCoilAvailSchPtr( DXHeatingCoilType, cAlphaArgs( 14 ), errFlag );
 }

**Comment by rraustad** [comment]
Closing this issue since it duplicates previous.
