### ISSUE TITLE
HPWH Stratified Tank performance is slow

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5039]
When working with PR #4698, I found that the code runs pretty dang slow on my debug build.  In release it isn't too bad, but after talking with @nmerket, it seems that there is definite room for investigating some improvements.  This issue is simply a follow-on from that PR to remember to investigate that issue in the future.

**Comment by nmerket** [comment]
@DeadParrot In all your free time, is there any way you could take a look at this and tell me where the hot spots are? [this is a good test file to use](https://github.com/NREL/EnergyPlus/blob/develop/testfiles/WaterHeaterHeatPumpWrappedCondenser.idf).

**Comment by DeadParrot** [comment]
@nmerket I will run it through the profiler and post the results.

**Comment by DeadParrot** [comment]
@nmerket That case doesn't run for me with current develop (running against an 8.3.3 installation). I get:

```
Program Version,EnergyPlus, Version 8.3.4-beb553b6cd, YMD=2015.08.17 21:31,IDD_Version 8.3.3
   ** Severe  ** IP: IDF line~279 Did not find "WaterHeater:HeatPump:WrappedCondenser" in list of Objects
   ** Severe  ** Out of range value Numeric Field#32 (Number of Nodes), value=12.00000, range={>=1 and <=10}, in WATERHEATER:STRATIFIED=WATER HEATER TANK
   ** Severe  ** IP: IDF line~373 Did not find "Coil:WaterHeating:AirToWaterHeatPump:Wrapped" in list of Objects
   ** Severe  ** IP: Out of "range" values found in input
   ** Severe  ** IP: Possible incorrect IDD File
   **   ~~~   ** IDD Version:"IDD_Version 8.3.3"
   **   ~~~   ** Version in IDF="8.3" not the same as expected="8.3"
   **   ~~~   ** Possible Invalid Numerics or other problems
```

**Comment by mjwitte** [comment]
@DeadParrot Should work with current develop. Looks like the IDD file may be out of date.

**Comment by DeadParrot** [comment]
@mjwitte Thanks. If 8.3.3 is too old I'll build a package of current develop and run against that.

**Comment by mjwitte** [comment]
@DeadParrot That will work, or you can simply update the IDD with the one that gets built when you build EnergyPlus.  On Windows that shows up in Build\Products when you build EnergyPlus in VS.

**Comment by nmerket** [comment]
@DeadParrot yes, this was a fairly recent addition, so it may not be in your build yet.

**Comment by DeadParrot** [comment]
@mjwitte @nmerket OK, if swapping in the IDD will suffice I'll go with that. I'll get that running this AM.

**Comment by DeadParrot** [comment]
@nmerket so the time is spent in `CalcWaterThermalTankStratified` and there is certainly room in there for traditional performance tuning but I would start with the big offenders, which are the sneaky temporary arrays. The profile was indicating heap allocation going on in there and at first glance I didn't see it. But then I noticed the member array use (which should also be eliminated) and then I saw these lines:

``` cpp
Tank.Node.TempSum() += Tank.Node.Temp() * dt;
Tank.Node.TempAvg() = Tank.Node.TempSum() / SecInTimeStep;
```

The right-hand-side whole array operations generate temporary arrays. Rewriting these as loop operations will eliminate the heap allocation and member array use. That, removing all the member array use (Temp(), SavedTemp(), TempAvg(), TempSum(), ...), and doing some traditional tuning should improve the performance but probably not by even 2X. Let me know if pointers on any of this are needed.

Note that I have methods such as scaled_assign and scaled_add in the Vector classes for just such usage to avoid temporaries but not in the Array classes yet. If you are interested in using template magic to enable array expressions that don't generate temporaries the Blitz++ library is pretty interesting. The compilation speed hit is pretty bad, though.

**Comment by Myoldmopar** [comment]
> Let me know if pointers on any of this are needed.

Oh gawd no, no pointers, please no poi.... oh wait, you mean pointers like **tips**, not **memory addresses**.  OK, cool.  You can calm down, @jasondegraw and @amirroth and @mbadams5, we're OK.

:wink:

**Comment by nmerket** [comment]
@DeadParrot I wanted to pick your brain again on this issue. I removed the array operations a while ago and we did see a pretty good speed up. I have some ideas around increasing the internal time step for this function (the `dt` constant) to speed things up but was wondering if there are any other low hanging fruit I'm missing that could make this run faster before I start changing things that will alter results.

**Comment by DeadParrot** [comment]
@nmerket Sure, I will fire the lastest code up in the profiler and have a look.

**Comment by nmerket** [comment]
Terrific, thank you.

**Comment by EnergyArchmage** [comment]
I agree that increasing the inside integeration timestep is worth investigating.   It would be a potent accuracy vs. speed knob if made an input.
