### ISSUE TITLE
.gitignore file list

### ISSUE THREAD

**Issue by krishnan-gowri** [NREL/EnergyPlus#5044]
*.rc is included in this list and it affects the win32 zlib1.rc being dropped while cloning/recreating the repository.  Not sure if anyone else had this problem.

**Comment by Myoldmopar** [comment]
Interesting, @krishnan-gowri.  I don't use Windows, and I hadn't heard of anyone else with this problem.  I'll try to verify this with @tsnouidui or @mwetter since the external interface is the reason zlib is in there.  I'm open to removing it from the .gitignore file for sure.

**Comment by Myoldmopar** [comment]
Opened a PR #5045 to be reviewed.

**Comment by Myoldmopar** [comment]
@krishnan-gowri So I checked, and on my machine it pulls that rc file down successfully.  The index takes precedence over the gitignore file if a file was already existing in the repo.  Maybe I'm just not clear of your workflow where you are seeing this problem.

Are you seeing this issue when cloning?  Or something else?  And also, what Git client are you using?

**Comment by Myoldmopar** [comment]
And for kicks, @krishnan-gowri, I checked this on Win7 using Git for Windows, and did a fresh clone of EnergyPlus.  The rc file is in there.  If you could help by providing some more helpful info, it would help me help you.

**Comment by krishnan-gowri** [comment]
The problem will be seen only if you create a repository with the cloned source.  Our internal development team ran into this problem when we created an internal repository from the 'develop' branch.

**Comment by Myoldmopar** [comment]
Interesting.  OK, I'm going to merge.  It's not necessary to have it in gitignore anyway, if someone tries to add files unintentionally it will show up in the pull request review anyway.
