### ISSUE TITLE
HVAC Sizing Summary: Thermostat Setpoint Temperature at Peak Load = 0 for ThermostatSetpoint:DualSetpoint 

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#5048]
UnmetHours question "Thermostat setpoint at peak load is 0"

Thermostat set point temperatures are calculated in CalcZoneAirTempSetPoints and stored in TempZoneThermostatSetPoint( ActualZoneNum ). TempZoneThermostatSetPoint( ActualZoneNum ) is used to report the zone set point temperature in the HVAC Sizing Summary. This variable is not set for a dual set point thermostat since it is not yet known what the zone load is (i.e., cooling or heating).

Adding one line of code near the end of CalcPredictedSystemLoad corrects the problem (around line 3220).

ZoneSetPointLast( ZoneNum ) = ZoneSetPoint;
TempZoneThermostatSetPoint( ZoneNum ) = ZoneSetPoint; (new line of code)

However, there are also initializations of this variable in InitZoneAirSetPoints for EMS, comfort control, and other control types that shouldn't be overridden by this new line of code.

Reviewing the calling structure, it appears that InitZoneAirSetPoints gets called every time while the other subroutines get called sequentially through an iteration based on "UpdateType" (which should? give priority to setting TempZoneThermostatSetPoint in InitZoneAirSetPoints except when UpdateType =  iGetZoneSetPoints  and now when UpdateType = iPredictStep). 

The question is, whether or not setting this variable in CalcPredictedSystemLoad will mess anything up for input files which use EMS, or comfort control, or ???.

I wonder if the initialization of TempZoneThermostatSetPoint could/should be instead done in InitZoneAirSetPoints so the EMS and other overrides will have priority at all times.

```
ManageZoneAirUpdates(
int const UpdateType, // Can be iGetZoneSetPoints, iPredictStep, iCorrectStep
Real64 & ZoneTempChange, // Temp change in zone air btw previous and current timestep
bool const ShortenTimeStepSys, bool const UseZoneTimeStepHistory,
Real64 const PriorTimeStep
)
{
if ( GetZoneAirStatsInputFlag ) {
    GetZoneAirSetPoints();
    GetZoneAirStatsInputFlag = false;
}

   ( RR *** TempZoneThermostatSetPoint gets set here *** )
InitZoneAirSetPoints(); 

{ auto const SELECT_CASE_var( UpdateType );
if ( SELECT_CASE_var == iGetZoneSetPoints ) {

          ( RR *** TempZoneThermostatSetPoint gets set here ***)
    CalcZoneAirTempSetPoints(); 

} else if ( SELECT_CASE_var == iPredictStep ) {

            ( RR *** and now TempZoneThermostatSetPoint gets set here as well *** )
    PredictSystemLoads( ShortenTimeStepSys, UseZoneTimeStepHistory, PriorTimeStep );

} else if ( SELECT_CASE_var == iCorrectStep ) {
    CorrectZoneAirTemp( ZoneTempChange, ShortenTimeStepSys, UseZoneTimeStepHistory, PriorTimeStep );
} else if ( SELECT_CASE_var == iRevertZoneTimestepHistories ) {
    RevertZoneTimestepHistories();
} else if ( SELECT_CASE_var == iPushZoneTimestepHistories ) {
    PushZoneTimestepHistories();
} else if ( SELECT_CASE_var == iPushSystemTimestepHistories ) {
    PushSystemTimestepHistories();
}}
```

}

**Comment by rraustad** [comment]
PR #5140

**Comment by rraustad** [comment]
Kyle, assigning to you since no others were involved in the creation of this issue. I think I overstated the problem in the description a month ago and it turns out that only a single line of code was needed.

**Comment by kbenne** [comment]
got it.
