### ISSUE TITLE
Unit tests not finding IDD on Windows VS build

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5051]
@mbadams5 @kbenne EnergyPlusFixture is expecting the IDD to be in the same directory as energyplus_tests.exe which is either Products\Debug or Products\Release, but the generated IDD is up a level in Products.

**Comment by mbadams5** [comment]
@mjwitte I thought I tested on my Windows VM and I know it works on the Windows CI. I'll look into it though and I know how to fix it.
