### ISSUE TITLE
cmake project using out of date policy

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#5054]
CMake Warning (dev) at CMakeLists.txt:105 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/CompilerFlags.cmake:9 (IF):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:133 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by jmarrec** [comment]
This has been fixed 3 years ago in e27c441129dff74acde41a96136e10eea0b0389a, see current develop also: [CMakeLists.txt#L5:L7](https://github.com/NREL/EnergyPlus/blob/develop/CMakeLists.txt#L5:L7)
