### ISSUE TITLE
WaterToAirHeatPumpSimple unit test writes to FOR17.dat file or console output on windows

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5057]
On Windows, when running all tests in energyplus_tests.exe, some sizing output is written to FOR17.dat
 Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:EQUATIONFIT, , Design Size Rated Air Flow Rate [m3/s], 0.20000
 Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:EQUATIONFIT, , Design Size Rated Total Cooling Capacity [W], 3891.20691
 Component Sizing Information, COIL:COOLING:WATERTOAIRHEATPUMP:EQUATIONFIT, , Design Size Rated Sensible Cooling Capacity [W], 2508.96671

When the tests are filtered to run only the WaterToAirHeatPump test, the same output goes to the console, not to FOR17.dat Should be going to eio output?

**Comment by jmarrec** [comment]
I would reckon this is no longer the case. I can't see any mention of FOR17 anywhere in the codebase (`grep -Ri "FOR17"` returns nada).

**Comment by mjwitte** [comment]
Not necessarily, that's an automatic file name when unit 17 is opened. I'll see if I can reproduce with current code.

**Comment by mjwitte** [comment]
Cannot reproduce with current develop. Closing.
