### ISSUE TITLE
ReadVarsESO not found through CLI

### ISSUE THREAD

**Issue by mbadams5** [NREL/EnergyPlus#5058]
When I run EnergyPlus through the CLI on Mac and pass in '-r' to "Run ReadVarsESO after simulation" it doesn't actually find the ReadVarsESO executable. I get the following error...

ERROR: Could not find ReadVarsESO executable: /Applications/EnergyPlus-8-3-0/ReadVarsESO.

That isn't the correct path for the ReadVarsESO executable, which is in PostProcess. If I create a symlink in the location where EnergyPlus is expecting the executable, I get the following error message instead...

sh: /Applications/EnergyPlus-8-3-0/ReadVarsESO: cannot execute binary file

I will also say the CLI is very finicky about where it is run from since it will sometimes work perfectly and other times it hangs while at "Processing Input File" until I hit ctrl-c to break the execution.

**Comment by nealkruis** [comment]
The first thing is definitely a problem and I'll fix it ASAP. With the simlink, do you need to make the link executable? It seems to work for me.

![screen shot 2015-07-30 at 2 30 24 pm](https://cloud.githubusercontent.com/assets/1964570/8994277/a0b2266a-36c7-11e5-8215-54e9271786d7.png)

**Comment by nealkruis** [comment]
@mbadams5 @kbenne so this problem isn't caught in the system tests because the "Products" directory structure on the CI is not the same as it is in the installed packages. Is there anything we can do to make the two structures more similar?

**Comment by kbenne** [comment]
@nealkruis is it the debug / release sub folder that is causing problems?

**Comment by nealkruis** [comment]
No. It's the fact that all of the executables on the CI are placed in the Products directory, and not in the respective "PreProcess" and "PostProcess" directories.

**Comment by kbenne** [comment]
ah.  yes we could make the structure match. Frankly id rather see the install structure flattened, but that might get us in trouble

**Comment by nealkruis** [comment]
If I search for ReadVars in "[EXE_DIR]" and "[EXE_DIR]/PostProcess" that should cover both the packaged installs and the development testing environment. Does that seem reasonable? 

Eventually we should probably build CSV writing into the actual EnergyPlus executable and deprecate ReadVarsESO altogether. (This might be one of my top feature requests)

**Comment by kbenne** [comment]
@nealkruis yes.

**Comment by nealkruis** [comment]
@kbenne in the meantime, it is probably good to consider mimicking the structure of the installer package as much as possible in the CI so that we can make sure there aren't other similar bugs. 

Can we do that with relatively little effort and without messing other things up?

**Comment by nealkruis** [comment]
@mbadams5 changed the name since I imagine this problem exists on all platforms as long as ReadVars is in the PostProcess directory.

**Comment by mbadams5** [comment]
@nealkruis honestly the symlink was just to see if I could get it working in the location EnergyPlus was expecting. If you update EnergyPlus to look in the right spots or change the directory structure, that is the better approach. So don't worry about my symlink comment.

**Comment by kbenne** [comment]
@nealkruis we can have the build output mirror the install layout. Feels a little atypical to me, but I guess what is mostly atypical is spreading the executables around to various directories in the first place. Take a look at [this](https://github.com/NREL/EnergyPlus/blob/16dbf1db652d8ab5af7057462b456eeb815e6ad4/CMakeLists.txt#L118) which can be set on a per target basis.
