### ISSUE TITLE
EvaporativeCooler:Indirect:ResearchSpecial does not report Primary Air Flow autosize result

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5061]
Example file DirectIndirectEvapCoolers has autosized EvaporativeCooler:Indirect:ResearchSpecial objects. These do not report a primary flow rate size, but they do report non-zero secondary flow rates.

**Comment by Nigusse** [comment]
@mjwitte @Myoldmopar I run the example file "DirectIndirectEvapCoolers.idf " using the latest develop code.  Below is sample sizing results from the EIO file. I see the "Primary Air Design Flow Rate" value reported. I am not sure what is missing here.  

 Component Sizing Information, EvaporativeCooler:Indirect:ResearchSpecial, FURNACE_PACU_CAV:1_OAINDRDD EVAP COOLER, Design Size Secondary Fan Flow Rate [m3/s], 0.27249
 Component Sizing Information, EvaporativeCooler:Indirect:ResearchSpecial, FURNACE_PACU_CAV:1_OAINDRDD EVAP COOLER, Primary Air Design Flow Rate [m3/s], 0.27249
 Component Sizing Information, EvaporativeCooler:Indirect:ResearchSpecial, FURNACE_PACU_CAV:1_OAINDRDD EVAP COOLER, Secondary Air Design Flow Rate [m3/s], 0.27249

**Comment by mjwitte** [comment]
@Nigusse As noted a while back, I think #5136 addressed both this and #5060.  Thanks for confirming this one.  Would you please confirm #5060 as well?
