### ISSUE TITLE
Bad links in Documentation

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5064]
A quick pass over the docs found a few bad links.  Here is a list of those found, both successful and failure.  Scroll right if needed to see status.  Because of [this](https://github.com/holman/ama/issues/305), the links to the bad lines show up in `blame` view.  

| Filename | Line# | URL | Status |
| --- | --- | --- | --- |
| Acknowledgements.md | [15](https://github.com/NREL/EnergyPlus/blame/develop/doc/src/docs/Acknowledgements/Acknowledgements.md#L15) | http://www.cecer.army.mil | FAILED |
| 01d-InputOutputReference.md | 18491 | http://www.epa.gov/iaq/schooldesign/saves.html | SUCCESS |
| 01a-InputOutputReference.md | 3022 | http://www.energyplus.gov | SUCCESS |
| AuxiliaryPrograms.md | 125 | http://www.energyplus.gov | SUCCESS |
| AuxiliaryPrograms.md | [3821](https://github.com/NREL/EnergyPlus/blame/develop/doc/src/docs/AuxiliaryPrograms/AuxiliaryPrograms.md#L3821) | http://www.greenhouse.gov.au/buildings/code.html | FAILED |
| AuxiliaryPrograms.md | 8124 | http://www.adobe.com/svg | SUCCESS |
| Tips_and_Tricks_Using_EnergyPlus.md | 38 | http://www.energyplus.gov | SUCCESS |
| Tips_and_Tricks_Using_EnergyPlus.md | 237 | http://apps1.eere.energy.gov/buildings/energyplus/openstudio.cfm | SUCCESS |
| 13c-EncyclopaedicRefs.md | 5786 | http://simulationresearch.lbl.gov | SUCCESS |
| 13f-EncyclopaedicRefs.md | [1775](https://github.com/NREL/EnergyPlus/blame/develop/doc/src/docs/EngineeringReference/13f-EncyclopaedicRefs.md#L1775) | http://dx.doi.org/10.1016/j.buildenv.2012.08.024 | FAILED |
| 13f-EncyclopaedicRefs.md | 1777 | http://escholarship.org/uc/item/3sx6n876 | SUCCESS |
| OutputDetailsAndExamples.md | 8559 | http://www.sqlite.org/sqlite.html | SUCCESS |
| ExternalInterfaces_Application_Guide.md | 1311 | http://simulationresearch.lbl.gov/bcvtb/releases/1.0.0/doc/manual/index.xhtml | SUCCESS |

Some fixes might be just updating, while others might need a note that says "This isn't available anymore".

**Comment by mjwitte** [comment]
Here's one for CERL
http://www.erdc.usace.army.mil/Locations/ConstructionEngineeringResearchLaboratory.aspx
