### ISSUE TITLE
Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit inside AirLoopHVAC:UnitarySystem

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#5067]
A Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit instance placed inside of AirLoopHVAC:UnitarySystem _with_ setpoint control option turned on does not work. That is to say the coil appears to be non participating. This is possibly a sizing issue where the component is not given any capacity, but I have not confirmed. Defect file has been uploaded.

UnmetHours [Post](https://unmethours.com/question/4984/modeling-self-contained-units-with-a-variable-speed-heat-pump/)

**Comment by EnergyArchmage** [comment]
I concur, ran into this during a recent study and reverted to CoilSystem approach. 

Also likely related to #4861 (where VS DX coil has same problem).

**Comment by EnergyArchmage** [comment]
Also, this can be affected by #4915 when mixing coil types in the same input file.

**Comment by rraustad** [comment]
@kbenne I don't see a defect file for this.

**Comment by kbenne** [comment]
@rraustad that's because I forgot to push it. Here it is now.

https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5067

**Comment by rraustad** [comment]
Cooling coil is now operating (and from what I can tell, correctly now).
There is something going on in this file that doesn't meet the zone temperature set point "perfectly". Since this is a huge file, I believe the zone temp control issue is elsewhere.

The coil (1.5MW) is turning on now which meets the problem statement.

![5067_defectfile_modifiedrunperiod](https://cloud.githubusercontent.com/assets/5778156/9504584/681a32e4-4c0b-11e5-84cc-091d8a1a88b6.png)

**Comment by rraustad** [comment]
I am still trying to figure out if it is the UnitarySystem causing this or something else. When I single step the UnitarySystem, the load met equals the requested load, so I don't think it's the UnitarySystem. I did notice that when the HVAC time step is less than the Zone time step, the predicted load looks strange. The figure below shows the zone predicted load at a detailed time step. The red circles denotes the predicted load at the zone time step. I would think the predictions would be smother than they appear.

![predictoratreducedtimesteps](https://cloud.githubusercontent.com/assets/5778156/9611613/9c6f3eca-50ae-11e5-8e39-3fc9df9cc9c5.png)

**Comment by mjwitte** [comment]
@rraustad Why does the predicted load matter when using setpoint control in the unitary system?

**Comment by rraustad** [comment]
This test is using LoadBased control ( 5067). The SP models are working well now. I wanted to see if I broke anything and am checking to see if 4861 is also fixed (I think it is).

I inadvertently deleted the last comment. The issue I see is when the HVAC time step is less than the Zone time step. For some reason Predictor does not result in a smooth transition between predictions at the zone time step. The figure below shows the detailed time step predicted load (blue line), with red circles denoting the prediction at the zone time step. I added in the Zone Air System Sensible Cooling Rate to show a time when the simulation downshifts and the UnitarySystem cannot meet the load. However, when I single step at this time, the system is meeting the load to within 1 W.

This is a different issue than what is described in 5067 and 4861. I'm just documenting what I found while investigating poor zone temperature control for 4861..

![predictoratreducedtimesteps](https://cloud.githubusercontent.com/assets/5778156/9612060/63adc6bc-50b1-11e5-8e19-5d9a6471bfbc.png)

**Comment by rraustad** [comment]
SP based control appears to be working well now.

Defect file #4861 uses Coil:Cooling:DX:VariableSpeed with SetPoint control. This defect file is compared to a CoilsSystem version with identical results.

![4861_results_vscoil](https://cloud.githubusercontent.com/assets/5778156/9612348/2045be96-50b3-11e5-9050-d91f58b44ece.png)

Another file was created to use both a heating and cooling coil. This file controls to the SP as desired. This file uses Coil:*:WaterToAirHeatPump:VariableSpeedEquationFit coils.

![5067_testresults_coolheatvscoil](https://cloud.githubusercontent.com/assets/5778156/9612366/47686e10-50b3-11e5-9230-5b8b318d2303.png)

**Comment by rraustad** [comment]
Original figure above (5067-testFileZoneLoad_8-3 (Modified RunPeriod)) used load-based control. this figure shows that file when SP control used instead. Much better zone temperature control.

![5067_results_vscoil_spcontrol](https://cloud.githubusercontent.com/assets/5778156/9612876/08b6dc80-50b6-11e5-973a-44600372791b.png)

**Comment by rraustad** [comment]
Complete. See https://github.com/NREL/EnergyPlus/pull/5147

**Comment by mjwitte** [comment]
Closed via #5147
