### ISSUE TITLE
Remove CalcSoilSurfTemp from EP-Launch

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5069]
Since CalcSoilSurfTemp is not going to be part of future versions of the EnergyPlus installer, it should be removed from being available on EP-Launch. 

See #5001

**Comment by Myoldmopar** [comment]
@jasonglazer, we're building it from source and packaging it that way.

**Comment by JasonGlazer** [comment]
@Myoldmopar Sorry, I thought that its functionality was being incorporated into EnergyPlus directly and that the stand-alone program called CalcSoildSurfTemp was being removed.

**Comment by Myoldmopar** [comment]
Although, @JasonGlazer, @mmatts may be able to mark this deprecated with his ground temp work, in which case, I'll now remember to remove from EP-Launch at that point.  So thanks for the reminder.
