### ISSUE TITLE
Remove Other Side Conditions Userland

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5075]
Keep the underlying structures, but take away the input side of it.  Directly reference things together instead.  See some conversation [here](https://github.com/NREL/EnergyPlus/issues/5073#issuecomment-127745368)

PS: @mjwitte @mmatts

**Comment by mitchute** [comment]
@Myoldmopar another one addressed with the GroundDomain stuff from way back? Closing, but feel free to reopen if needed.
