### ISSUE TITLE
Degree days for LEED Summary Report Sec 1.1A reversed bases

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5083]
The heating and cooling degree days reported in the LEED Summary Report Section 1.1A General Information are reversed.

ASHRAE main weather parameters for determining climate zone are HDD65F and CDD50F, which correspond roughly to HDD18C and CDD10C. What is being reported in the LEED Summary report under Sec1.1A-General Information are HDD10C and CDD18C. So they are reversed. This is a bug and should be fixed.

See help desk ticket 10669

**Comment by mjwitte** [comment]
@JasonGlazer In the LEED report, these should also be labeled to indicate the DD base, and the source (standard ASHRAE or based on weather file).  Reference #4820

**Comment by JasonGlazer** [comment]
The example file I ran, 5ZoneEndUses using USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw with the stat file present, already shows a label that "HDD and CDD data source" is "Weather File Stat" so the source of the degree days appears to be working.

**Comment by mjwitte** [comment]
To me, "Weather file stat" is not clear since the stat file contains both the ASHRAE standard ddays and the ddays calculated from the weather file.

**Comment by JasonGlazer** [comment]
Suggestion?

**Comment by mjwitte** [comment]
I would mimic what is in the Climatic Data Summary 

![8-7-2015 12-13-36 pm](https://cloud.githubusercontent.com/assets/4991075/9141391/e5accf90-3cfd-11e5-8ed6-8b719ff80c79.jpg)

**Comment by JasonGlazer** [comment]
Maybe it is just my background but "standard" there does not seem appropriate since they are actually from "Climate Design Data 2009 ASHRAE Handbook" and not Standard 169. 

How about "weather file" and "ASHRAE Handbook 2009"

**Comment by mjwitte** [comment]
Yes, that would be better for both reports.

**Comment by Myoldmopar** [comment]
Closed via #5572
