### ISSUE TITLE
Refrigeration:Condenser:WaterCooled does not register water flow size with plant

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5089]
from UH, and code inspection.  The input for Refrigeration:Condenser:WaterCooled is not registering the volume flow rate with a call to RegisterPlantCompDesignFlow.  This should be inserted around line 3354 in RefrigeratedCase.cc

workaround is to hard size plant loop and no rely on autosizing plant loop based on condenser water flow

**Comment by JasonGlazer** [comment]
The SuperMarket_DetailedWaterCondenser.idf file uses the Refrigeration:Condenser:WaterCooled object.

**Comment by mjwitte** [comment]
Closed via #5309
