### ISSUE TITLE
Window frame heat gain not calculated correctly

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#5095]
There are two issues with the way frame heat gain is calculated:
1. If the interior projection depth is zero, then the interior convection is set to zero. `HInConv` is set to zero [here](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6073) and it is only set to a non-zero value ([here](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6084)) if the [frame projection depth is not zero](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6082). Note, [dividers](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6142) seem to handle this correctly.
2. The calculated frame heat gain only represents the convection. See the calculation [here](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6100). My understanding is that the `FrameHeatGain` variable is only used for surface, window, and frame output reporting purposes. But the [documentation](http://bigladdersoftware.com/epx/docs/8-3/input-output-reference/group-thermal-zone-description-geometry.html#surface-window-heat-gain-energy-j) is pretty explicit about the variables including the conduction through the frame, and not just the convection. Once again, [dividers](https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6159) seem to handle this correctly.

The solution is pretty straight forward, in that we need to replicate the divider calculations in the frame section.

**Comment by nealkruis** [comment]
@mjwitte do you have time to talk through a resolution on this bug?

**Comment by EnergyArchmage** [comment]
It isn't clear if you are saying this is a reporting issue or a zone air heat balance issue. 

It is the inside face surface temperature that matters for sumhat and it has more terms. https://github.com/NREL/EnergyPlus/blob/9ce4be335f113561dd48f0ff2a781b32c88a4cdf/src/EnergyPlus/WindowManager.cc#L6092

**Comment by nealkruis** [comment]
@EnergyArchmage it is both. @mjwitte and I agreed that the convection being set for zero for the calculation of surface temperatures was a bug and should be fixed. The FrameHeatGain reflecting only the is solely a reporting issue.

FWIW, I probably should have continued the discussion on PR #5099 instead of here.
