### ISSUE TITLE
Incorrect location for RunReadVars

### ISSUE THREAD

**Issue by jamiebull1** [NREL/EnergyPlus#5108]
Running EnergyPlus from the command line interface with the `--runreadvars` flag set raises an error (on Windows 10 with EnergyPlus 8.3):

`ERROR: Could not find ReadVarsESO executable: C:\EnergyPlusV8-3-0\ReadVarsESO.exe.`

The program is looking for `ReadVarsESO.exe` in the wrong place (the `C:\EnergyPlusV8-3-0` rather than `C:\EnergyPlusV8-3-0\Postprocess`.

**Comment by MatthewSteen** [comment]
duplicate of #5058?

**Comment by jamiebull1** [comment]
Ah yes. Looks like it. So it will be fixed and I can workaround for now by copying `ReadVarsESO.exe` into the EnergyPlus root?

**Comment by MatthewSteen** [comment]
@jamiebull1 I would think so, although I haven't run EP yet using the CLI.

**Comment by jamiebull1** [comment]
@MatthewSteen Yes, that works fine.
