### ISSUE TITLE
Problems when Windows users install into c:\Program Files folder or similar

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5109]
Helpdesk tickets 10697, 10690, and others
@JasonGlazer @kbenne On Windows, if the installer instructions are ignored and EnergyPlus is installed into a "Program Files" folder (fairly common, because who ever reads those screens?) then EnergyPlus simulations will fail in one of two (or more?) ways.

If EP-Launch is set to "Create BatchFile to run EnergyPlus", then it fails with this error
![image](https://cloud.githubusercontent.com/assets/4991075/9307272/2f2f5b8e-44c3-11e5-9817-3a26ff080f7d.png)

When this option is off, a dos box opens and closes and then the standard crash dialog appears. This is from running an example file in the Program Files\EnergyPlus...\ExampleFiles folder
![image](https://cloud.githubusercontent.com/assets/4991075/9307407/0353c472-44c4-11e5-8cb7-a6fa1e4055e0.png)

If I use the version installed to run a file located elsewhere (with "create batch file ..." checked or unchecked), the simulation will run (as long as it doesn't use parameters).

Seems we should be able to either check the install folder permissions and force the user to choose a different install path, or at least trap this at run-time and put up a better error message.

I can reproduce this in my Win 8.1 on which my login has full admin rights.  The OS allows the installer to write here, but the default permissions for users and "ALL APPLICATION PACKAGES" are read and execute only (no write or modify).  I tried to manually changes those permissions and it runs with "Create batch file" checked, but not without it.

Not suggesting a major overhaul here, just a better catch of this condition.  At a minimum, the we could just change the wording of the EP-Launch crash dialog.

**Comment by mbadams5** [comment]
@mjwitte This seems related to both #5080 and #5082. Did you try this with 8.3 Release or current develop?

**Comment by JasonGlazer** [comment]
The long term solution is to migrate to a more windows friendly set up that puts working directories and the results of simulations into normal "my documents" directories. It would take some reworking of the installer and EP-Launch but it is probably the right thing to do.

Short term, we can certainly add some tests in EP-Launch if temporary files cannot be created put out more useful error messages.

**Comment by mjwitte** [comment]
8.3 release.

**Comment by mjwitte** [comment]
Will let you know in an hour or two if current develop is the same.  I don't expect any change.

**Comment by mjwitte** [comment]
@mbadams5 Confirmed, same behavior with current develop (as of a couple of hours ago anyway).

**Comment by mjwitte** [comment]
@kbenne EP-Launch will warn now if it is installed in a protected directory.  We can close this issue, or keep it open for future installer changes.

**Comment by mjwitte** [comment]
@kbenne From helpdesk ticket 10817 "Since I installed OpenStudio with the integrated EP and accepted all the defaults, EP is installed in the Program Files directory."  Is that really what OpenStudio installer will do?  That's not good.  @JasonGlazer

**Comment by kbenne** [comment]
yes the OpenStudio installer will put E+ down in C:\Program Files\OpenStudio...... this is not like a typical E+ install. It does not run the E+ installer or anything like that, it just copies the E+ install tree. It was not really intended to be something that people access outside of E+, although since we are not being selective about what parts of E+ get copied, it is all there and tempting to fire up EP Launch for example. 

I am not inclined to move the OS install of E+ outside of the OS install directory, but perhaps we should pair down the E+ things that OS installs to the minimum so that it does not give the appearance of a proper E+ install. OS team can certainly do this without action on the E+ team's part, but I think this is closely related to my thoughts about splitting E+ into an engine distribution and GUI centric end user package. This never really went anywhere but for reference I'm talking about [this](https://docs.google.com/document/d/14dz4rd6dv8yVEaHRCYfXls58FbsgpsUHPMuD31-FalA/edit#heading=h.y37kiv4wwens).

**Comment by mjwitte** [comment]
@kbenne Got it.  Much has changed since those discussions 18 months ago.

**Comment by JasonGlazer** [comment]
@kbenne How difficult would it be for the OpenStudio installer to not install EnergyPlus if it finds that version already installed on a users computer? And then for OpenStudio to use that already installed version? That would probably reduce confusion for users that have the same version of EnergyPlus installed in two places. And I agree that when the OpenStudio installer does put EnergyPlus on a computer it should be minimal and just the parts that OpenStudio needs.

**Comment by kbenne** [comment]
@JasonGlazer I'll bring it up with the OS team. Certainly doable, but at the cost of some non zero complexity. I think in the future OS would prefer to forgo the E+ system call altogether and instead call into the DLL.

**Comment by JasonGlazer** [comment]
@kbenne Using the EnergyPlus DLL sounds like a great solution for OpenStudio.

**Comment by Myoldmopar** [comment]
Nailed it @kbenne!

**Comment by JasonGlazer** [comment]
@kbenne I think I addressed the short term issues for this so I think the rest is in your court. I am moving the assignee to you. If you disagree, let me know.

**Comment by mjwitte** [comment]
@kbenne It appears that the EnergyPlus side of things have been addressed here. If you want to cross-reference any changes to the OpenStuiod installer here, please do so.  I'm closing this issue.
