### ISSUE TITLE
Rules8-2-0-to-8-3-0.xls transition errors for GroundHeatExchanger:Vertical

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#5113]
Referencing issue #4660 for more description.

**Comment by EnergyArchmage** [comment]
maybe coordinate or related to #5203

**Comment by mjwitte** [comment]
@mitchute Is this still an open issue or was it addressed?

**Comment by mitchute** [comment]
@mjwitte I think it may have been addressed. I will check on it and confirm.

**Comment by mitchute** [comment]
@mjwitte @Myoldmopar this issue has been corrected. See this [PR 27](https://github.com/NREL/EnergyPlusBuildSupport/pull/27) over on BuildSupport.

**Comment by mjwitte** [comment]
Closed via #5545
