### ISSUE TITLE
HRV/Economizer lockout

### ISSUE THREAD

**Issue by Alex-Blue** [NREL/EnergyPlus#5115]
It would be good to get clearer documentation on economizer lockouts and HRV controls, and what it means for the economizer to be "active."
- Controller:OutdoorAir has a control for Heat Recovery Bypass Control Type. The two options are BypassWhenWithinEconomizerLimits and BypassWhenOAFlowGreaterThanMinimum
- The HeatExchanger:AirToAir:SensibleAndLatent object also has an Economizer Lockout Yes/No control.
- The BypassWhenWithinEconomizerLimits turns heat recovery off nearly all the time, as the economizer is very often "active" though not obviously above the minimum flow.
- The BypassWhenOAFlowGreaterThanMinimum seems to save considerable heating energy, and reduces outdoor air flow to zones by ~10% over the No Economizer Lockout option
- The No Lockout option seems like it should give the same answer as BypassWhenOAFlowGreaterThanMinimum, but heating energy use is significantly higher; cooling energy also increases slightly.
1. It seems like the BypassWhenOAFlowGreaterThanMinimum is able to reduce the OA flow. Is this the case? What is the difference between this and the No Economizer OA flow? 
2. What does it mean for the economizer to be active? The economizer seems to frequently be "active" when outdoor air is at minimum.

**Comment by mjwitte** [comment]
@Alex-Blue The short answer is the economizer is active when it's within all of it's limits _and_ the economizer control type indicates the economizer is not off.  e.g. if it's DifferentialDryBulb then it is active when ODB<ReturnAirTemp and none of the other limits (if any) are exceeded.  Will clarify this in the docs under "Heat Recovery Bypass Control Type".

The other concerns are related to #4568 

Also, depending what version your are using, the behavior of the heat exchanger setpoint controls was improved for version 8.3.0, see #4833
