### ISSUE TITLE
Output:Table:Monthly "Invalid/Undefined" meter caused by similarly named custom meters

### ISSUE THREAD

**Issue by ejhw** [NREL/EnergyPlus#5121]
Some custom meters are not properly read by Output:Table:Monthly reports (they are labeled "Invalid/Undefined"). This is somehow dependent on the name of the custom meter and seems to happen with custom meters with similar names.

8.3 defect file illustrating issue: https://gist.github.com/ejhw/87a6a794b50ead78dcc3

cc @nmerket

**Comment by JasonGlazer** [comment]
@ejhw  I ran your example file in 8.3 and it reproduced the issue you described but when I transitioned it to 8.4 it no longer showed the two variables as Invalid/Undefined but with the units of [J] and values in the columns. I assume this is fixed and I am closing the issue.
