### ISSUE TITLE
ExternalInterface*Schedule input processing could fail if no other schedule objects in idf

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5126]
These [if blocks](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ScheduleManager.cc#L372-L395) in ScheduleManager::ProcessScheduleInput have pasteos.  Instead of checking if NumCptSchedules > 0, these should be testing the respective NumExternalInterface\* variables set in the line above the if.

Noticed while working on a different issue.  No defect test file yet.  An idf which has no other schedule:\* objects but has any of ExternalInterface:Schedule, ExternalInterface:FunctionalMockupUnitImport:To:Schedule, or ExternalInterface:FunctionalMockupUnitExport:To:Schedule should have array bounds errors, because MaxNums and MaxAlps will never be set above their intial values of 1 and 0.

**Comment by tsnouidui** [comment]
@mjwitte Thanks. I will take a look.

**Comment by Myoldmopar** [comment]
Closed via #5593
