### ISSUE TITLE
Suggest adding architecture option to CLI

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#5157]
OpenStudio had an issue where we were packaging a 64 bit build of EnergyPlus with the 32 bit OpenStudio package.  This wasn't EnergyPlus's fault at all.  However, there is no way to check the architecture of the EnergyPlus build using the CLI (or any other file) as far as I know.  Would be great if this information was in the CLI (either under --version or a new flag --arch)

**Comment by kbenne** [comment]
I agree this would be handy but it seems a little unusual. Are there other programs that respond to --arch or similar? I know this is probably not as convenient but unixes will respond to file

```
kbenne$ file /Applications/EnergyPlus-8-3-0/energyplus
/Applications/EnergyPlus-8-3-0/energyplus: Mach-O 64-bit executable x86_64
```

**Comment by macumber** [comment]
My preference would be to include this in the version command:

c:> ruby -v
ruby 2.0.0p594 (2014-10-27) [x64-mingw32]

**Comment by mitchute** [comment]
This was added in #8779. Closing.
