### ISSUE TITLE
Error when converting 2004 new building warehouse reference models (8.2 to 8.3) RefBldgWarehouseNew2004_v1.4_7.2_3B_USA_CA_LOS_ANGELES

### ISSUE THREAD

**Issue by jburek** [NREL/EnergyPlus#5158]
Program Version,Conversion 8.2 => 8.3
   *\* Severe  *\* Out of range value Numeric Field#2 (Maximum Hot Water or Steam Flow Rate), value=0.00000, range={>0}, in ZoneHVAC:UnitHeater=BulkStorage Unit Heater
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   1833   Sizing:System,
   ************\* Only last 10 lines before error line shown.....
   ************\*   1842     12.8000,                 !- Central Cooling Design Supply Air Temperature {C}
   ************\*   1843     40.0,                    !- Central Heating Design Supply Air Temperature {C}
   ************\*   1844     NonCoincident,           !- Sizing Option
   ************\*   1845     No,                      !- 100% Outdoor Air in Cooling
   ************\*   1846     No,                      !- 100% Outdoor Air in Heating
   ************\*   1847     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   1848     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   1849     DesignDay,               !- Cooling Design Air Flow Method
   ************\*   1850     0.0,                     !- Cooling Design Air Flow Rate {m3/s}
   ************\*   1851     DesignDay,               !- Heating Design Air Flow Method
   *\* Warning *\* Invalid Number in Numeric Field#12 (Supply Air Flow Rate Per Floor Area During Cooling Operation), value=DesignDay, in Sizing:System=FURNACE_PACU_CAV_1:1
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   1833   Sizing:System,
   ************\* Only last 10 lines before error line shown.....
   ************\*   1844     NonCoincident,           !- Sizing Option
   ************\*   1845     No,                      !- 100% Outdoor Air in Cooling
   ************\*   1846     No,                      !- 100% Outdoor Air in Heating
   ************\*   1847     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   1848     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   1849     DesignDay,               !- Cooling Design Air Flow Method
   ************\*   1850     0.0,                     !- Cooling Design Air Flow Rate {m3/s}
   ************\*   1851     DesignDay,               !- Heating Design Air Flow Method
   ************\*   1852     0.0,                     !- Heating Design Air Flow Rate {m3/s}
   ************\*   1853     ZoneSum;                 !- System Outdoor Air Method
   *\* Warning *\* Invalid Number in Numeric Field#14 (Design Supply Air Flow Rate Per Unit Cooling Capacity), value=ZoneSum, in Sizing:System=FURNACE_PACU_CAV_1:1
   *\* Warning *\* Object=Sizing:System, name=FURNACE_PACU_CAV_1:1, entered with less than minimum number of fields.
   *\*   ~~~   *\* Attempting fill to minimum.
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   1855   Sizing:System,
   ************\* Only last 10 lines before error line shown.....
   ************\*   1864     12.8000,                 !- Central Cooling Design Supply Air Temperature {C}
   ************\*   1865     40.0,                    !- Central Heating Design Supply Air Temperature {C}
   ************\*   1866     NonCoincident,           !- Sizing Option
   ************\*   1867     No,                      !- 100% Outdoor Air in Cooling
   ************\*   1868     No,                      !- 100% Outdoor Air in Heating
   ************\*   1869     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   1870     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   1871     DesignDay,               !- Cooling Design Air Flow Method
   ************\*   1872     0.0,                     !- Cooling Design Air Flow Rate {m3/s}
   ************\*   1873     DesignDay,               !- Heating Design Air Flow Method
   *\* Warning *\* Invalid Number in Numeric Field#12 (Supply Air Flow Rate Per Floor Area During Cooling Operation), value=DesignDay, in Sizing:System=FURNACE_PACU_CAV_2:2
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   1855   Sizing:System,
   ************\* Only last 10 lines before error line shown.....
   ************\*   1866     NonCoincident,           !- Sizing Option
   ************\*   1867     No,                      !- 100% Outdoor Air in Cooling
   ************\*   1868     No,                      !- 100% Outdoor Air in Heating
   ************\*   1869     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   1870     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   1871     DesignDay,               !- Cooling Design Air Flow Method
   ************\*   1872     0.0,                     !- Cooling Design Air Flow Rate {m3/s}
   ************\*   1873     DesignDay,               !- Heating Design Air Flow Method
   ************\*   1874     0.0,                     !- Heating Design Air Flow Rate {m3/s}
   ************\*   1875     ZoneSum;                 !- System Outdoor Air Method
   *\* Warning *\* Invalid Number in Numeric Field#14 (Design Supply Air Flow Rate Per Unit Cooling Capacity), value=ZoneSum, in Sizing:System=FURNACE_PACU_CAV_2:2
   *\* Warning *\* Object=Sizing:System, name=FURNACE_PACU_CAV_2:2, entered with less than minimum number of fields.
   *\*   ~~~   *\* Attempting fill to minimum.
   *\* Severe  *\* Out of "range" values found in input
   *\* Severe  *\* Out of "range" values and/or blank required fields found in input
   ************\* Conversion Completed Successfully-- 6 Warning; 3 Severe Errors

**Comment by mjwitte** [comment]
@jburek What is the version ID in the original idf file?  The file name implies it is a v7.2 file.  In that case, you'll need to download the additional transition programs found [here](http://energyplus.helpserve.com/Knowledgebase/List/Index/46/converting-older-version-files)to get from v7.2 to v8.3 using the IDFVersionUpdater.
