### ISSUE TITLE
Improve waste heat function handling for Coil:Cooling:DX:MultiSpeed and Coil:Heating:DX:MultiSpeed 

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#5162]
This issue is a continuous fix of #4536 (Coil:Cooling:DX:MultiSpeed requires Waste Heat Function of Temperature Curve Name when it should not). It suggested 3 steps to handle this issue. 
1 Match IO description: when fuel is electricity, no waste heat curve check is needed. This has been fix in #4536
2 Check parent input. If no heat recovery from the parent, no need to check waste heat curve
3 If the parent has heat recovery and no waste heat curve inputs, simply use a constant value at 1.
This issue handles two remaining steps.

**Comment by mjwitte** [comment]
@lgu1234 Coil:Cooling:WaterToAirHeatPump:VariableSpeedEquationFit and probably others also have waste heat fields that are required.  Seems they should all be optional.

**Comment by lgu1234** [comment]
@mjwitte I am going to take a look at waste heat fields and will take proper actions to make the field optional.

**Comment by mjwitte** [comment]
@lgu1234 Thanks.  I added some defect files for the heatpump:multispeed, but not for any others.  You'll need to remove some of the \required-field tags in the IDD.

**Comment by lgu1234** [comment]
@mjwitte The \required-field tags in the fields of Speed 1 Waste Heat Function of Temperature Curve Name and Speed 2 Waste Heat Function of Temperature Curve Name in the Coil:Heating:DX:MultiSpeed have been removed. Will commit it now.

**Comment by mjwitte** [comment]
Also the waste heat fraction fields should not be required.

**Comment by mjwitte** [comment]
Closed via #5176
