### ISSUE TITLE
Enabling watercooled or evaporatively cooled condenser type for VRF results in lower performing VRF system

### ISSUE THREAD

**Issue by lincolnharmer** [NREL/EnergyPlus#5163]
The simulation is occurring in Atlanta and I'm controlling the condenser loop to float between 40F and 90F using a cooling tower and boiler for the water cooled scenario. I've confirmed that the condenser loop is seeing the load from the heat recovery VRF system but the VRF system performance is worse compared to air cooled. similar results have been found with the evaporatively cooled scenario.

**Comment by mjwitte** [comment]
Helpdesk ticket 10758 and unmet hours [8900](https://unmethours.com/question/8900/modeling-evapcooled-vrf-with-evaporative-condenser-effectiveness/)

I compared the idf files and found that they are not quite identical other than condenser type. 

This schedule "Min Max Temp w Deadband Max Temp Sch" is 26.7 in the air cooled file and it's 21.1 in the evap cooled and water cooled files.

This is being used as the thermostat cooling setpoint in the Data Center Zone.

Changing that to 21.1 in the air cooled case gives exactly the same answer as the evap cooled. That doesn't seem right either. Need to run this again with hourly outdoor dry bulb reporting and heat pump condenser inlet temp reported in the air cooled file.

The water cooled case shows lower cooling electricity, and about the same heating electricity, plus some gas boiler use.
Defect files added.

**Comment by eringold** [comment]
@mjwitte, @rraustad 

It does not appear that setting an AirConditioner:VariableRefrigerantFlow system Condenser Type = WaterCooled will result in the performance curves being evaluated (per the documentation) at outdoor condenser entering water temperature. 

I've created custom curves based on manufacturer data as a function of indoor wetbulb and condenser entering water temp, but when I output the variables 'Performance Curve Input Variable 1/2 Value' I see Input 2 values tracking with OA temp (MAU OA node temp included for reference): 
![image](https://user-images.githubusercontent.com/10799524/53648266-b66e7380-3bfc-11e9-9e1d-e24956fc6f9e.png)

Furthermore, it seems that this section of code sets `CondInletTemp = OutdoorDrybulb` when `CondenserType == WaterCooled`:
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L615-L617

Unless I'm missing something, it appears that watercooled VRFs simply do not work as intended.

**Comment by rraustad** [comment]
I thought that was corrected long ago. In your figure perf curve var 2 is not OA temp so then is the plant using an OA reset scheme?
Look at line 589 and 590 and see that if water-cooled the condenser inlet node will be non-zero:
Could have used a different variable here but it does look like it's water temp.

    if (VRF(VRFCond).CondenserNodeNum != 0) {
        OutdoorDryBulb = Node(VRF(VRFCond).CondenserNodeNum).Temp;

**Comment by eringold** [comment]
@rraustad there is no OA reset scheme on the plant loop. Here's the chart with the water loop outlet node temp:
![image](https://user-images.githubusercontent.com/10799524/53651817-b07c9080-3c04-11e9-8a6d-61623c6d6369.png)

**Comment by rraustad** [comment]
Is that the "plant" water loop outlet node temp? This is the temp expected to enter the VRF condenser? Could you plot the VRF condenser water inlet node temperature?

**Comment by eringold** [comment]
![image](https://user-images.githubusercontent.com/10799524/53652862-1a963500-3c07-11e9-9bb3-91e3dbaad7bd.png)

@rraustad I'll email you the input file.

**Comment by rraustad** [comment]
The VRF condenser entering water temp looks like it matches the plant temp from the previous plot.

I do see an issue. Does this input file use outdoor WB temp as the heating performance outdoor temperature type?

                    auto const SELECT_CASE_var(VRF(VRFCond).HeatingPerformanceOATType);
                    if (SELECT_CASE_var == DryBulbIndicator) {
                        if (OutdoorDryBulb > HeatOABoundary) {
                            if (VRF(VRFCond).HeatEIRFTHi > 0)
                                TotHeatEIRTempModFac = CurveValue(VRF(VRFCond).HeatEIRFTHi, InletAirDryBulbC, CondInletTemp);
                        }
                    } else if (SELECT_CASE_var == WetBulbIndicator) {
                        if (OutdoorWetBulb > HeatOABoundary) {
                            if (VRF(VRFCond).HeatEIRFTHi > 0)
                                TotHeatEIRTempModFac = CurveValue(VRF(VRFCond).HeatEIRFTHi, InletAirDryBulbC, OutdoorWetBulb);
                        }

**Comment by eringold** [comment]
...yes it does. I figured that input would be meaningless for a watercooled condenser, but apparently not: https://bigladdersoftware.com/epx/docs/9-0/input-output-reference/group-variable-refrigerant-flow-equipment.html#field-heating-performance-curve-outdoor-temperature-type

Looks like if I change to DB it should work?

**Comment by rraustad** [comment]
Absolutely. Same for cooling.

**Comment by eringold** [comment]
There doesn't seem to be a corresponding input for cooling, but I think the cooling curves are working fine.

**Comment by rraustad** [comment]
OK, I didn't check cooling inputs before commenting. So using DB for water-cooled should be the work-around. Let me know if the energy numbers make more sense.

**Comment by eringold** [comment]
Yes the energy numbers and curve input/output values make more sense now. Thank you very much for finding that.

I think at least the I/O reference for 'Heating Performance Curve Outdoor Temperature Type' should indicate that DryBulb should be used for WaterCooled condensers. I'll make a note of that over in the Documentation issue.

**Comment by rraustad** [comment]
No, this is a bug and needs to be corrected. I can do it in 1 line of code.

**Comment by eringold** [comment]
Oh ok, I suppose that's preferable. I'll delete that comment.

**Comment by jmarrec** [comment]
@rraustad can you do that 1 line of code please?

**Comment by rraustad** [comment]
The dev support 5163 files are not transitioning properly.

**Comment by jmarrec** [comment]
I transitionned the water_cooled.idf one. But it won't run.

first some issues with the ScheduleTypeLimits, easy enough. 

Then a new Severe that turned fatal about WetBulbTemperature being used, though it did say that it would reset to DryBulbTemperature and simulation continues, but simulation halted. 

And it's refusing the curves that are out of bounds... change the `0.25,                    !- Minimum Heat Pump Part-Load Ratio` to `0.50,                    !- Minimum Heat Pump Part-Load Ratio` and it works.

**Comment by rraustad** [comment]
It looks like this has been fixed. I used HVACTemplate-5ZoneVRF as a test with variables added to verify.

![image](https://user-images.githubusercontent.com/5778156/179789035-9acd9edf-d018-40e6-9516-bd7a6afeeb29.png)

[5163-in.idf.txt](https://github.com/NREL/EnergyPlus/files/9142519/5163-in.idf.txt)

You can review, comment, close, etc. as needed.

**Comment by jmarrec** [comment]
Closing as it appears fixed
 We can reopen if someone identifies the same issue with 22.1.0.
Thanks @rraustad
