### ISSUE TITLE
Example file VariableRefrigerantFlow_FluidTCtrl_5Zone.idf errors

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5167]
Ran example file as-is and as an annual run, with Miami,FL wather.  The error output is enormous in both cases (36k lines and 856k lines).  There are two common types of errors:

```
   ** Warning ** Coil:Heating:DX:VariableRefrigerantFlow:FluidTemperatureControl "TU1 VRF DX HEATING COIL" - Air volume flow rate per watt of rated total heating capacity is out of range at 2.672E-005 m3/s/W.
   **   ~~~   **  During Warmup, Environment=Miami Intl Ap FL USA TMY3 WMO#=722020, at Simulation time=01/01 02:15 - 02:30
   **   ~~~   ** Expected range for VolumeFlowPerRatedTotalCapacity=[2.684E-005--8.056E-005]
   **   ~~~   ** Possible causes include inconsistent air flow rates in system components or
   **   ~~~   ** inconsistent supply air fan operation modes in coil and unitary system objects.

   ** Warning ** GetSupHeatEnthalpyRefrig: Refrigerant [R410A] is saturated at the given conditions, saturated enthalpy at given temperature returned. **
   **   ~~~   ** ...Called From:VRFCondenser
   **   ~~~   ** Refrigerant temperature = -12.13
   **   ~~~   ** Refrigerant pressure = 1261139
   **   ~~~   ** Returned Enthalpy value = 417250.501
   **   ~~~   **  Environment=Miami Intl Ap FL USA TMY3 WMO#=722020, at Simulation time=01/01 02:30 - 02:32
```

The flow per capacity warnings are set up as recurring warnings, but I would not expect to see these in an example file.  There is also a sizing warning about capacity vs flow.  if these units typically operate in a wider range of cfm/ton, then the limits should be changed for this coil type.  If not, then the inputs should be fixed.

The bigger problem is the GetSupHeatEnthalpyRefrig warnings.  These shouldn't be happening in the first place, but when they do, they should only report a few times and then accumulate as a recurring warning.

Also, example file annual run has over 2000 hours of cooling setpoint not met.

**Comment by Myoldmopar** [comment]
Closed with #5210
