### ISSUE TITLE
Follow-up check/issue from #5107

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5168]
That PR is being merged, but there was one very small issue to be checked on.  From @rraustad: 

> This can go in, but I still want to check to see why the supp heater didn't size the same as the cooling coil. It may be correct now, I just wanted to double-check. I can update this anytime using any other branch.

**Comment by rraustad** [comment]
Oh, now I remember, this isn't a heat pump. Yes there is a DX cooling coil, DX heating coil, and gas supplemental heater on the main branch, but this configuration is not a HP. If you put a gas heating coil on the main branch for HVACDXSystem, what would you expect the supp heating coil size to be? I'd expect it to be completely independent of the other coils.

So this explains why the supp coil is not the same size at the DX cooling coil.

```
Branch,
  Air Loop Main Branch,    !- Name

  AirLoopHVAC:OutdoorAirSystem,  !- Component 1 Object Type

  Fan:ConstantVolume,      !- Component 2 Object Type

  AirloopHVAC:UnitarySystem,  !- Component 3 Object Type
  DX Cooling Coil,         !- Component 3 Name

  AirloopHVAC:UnitarySystem,  !- Component 4 Object Type
  HeatPump DX Coil 1,      !- Component 4 Name

  Coil:Heating:Gas,        !- Component 5 Object Type
  Heat Pump DX Supp Heating Coil 1,  !- Component 5 Name
```

**Comment by rraustad** [comment]
The coils do size the same on the other file which I think is a mistake. If the 2 DX coils were in the same parent, then yes, same size. But CoilSystem can't contain 2 coils, so the code accepts 2 DX as a HP. I'm trying to relax the restrictions in UnitarySystem.

DXCoilSystemAuto results:

 Component Sizing Information, Coil:Cooling:DX:SingleSpeed, HEAT PUMP ACDXCOIL 1, Design Size Gross Rated Total Cooling Capacity [W], 24978.88526
 Component Sizing Information, Coil:Heating:DX:SingleSpeed, HEAT PUMP DX HEATING COIL 1, Design Size Gross Rated Heating Capacity [W], 24978.88526
 Component Sizing Information, Coil:Heating:DX:SingleSpeed, HEAT PUMP DX HEATING COIL 1, Design Size Gross Rated Heating Capacity [W], 24978.88526
 Component Sizing Information, Coil:Heating:Gas, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 18770.14176

The supp heating coil size is now the same size as DXCoilSystemAuto. And this "independent" system also sizes all coils independently (unlike coil system). That's exactly what I intended.

UnitarySystem_DXCoilSystemAuto:

 Component Sizing Information, Coil:Cooling:DX:SingleSpeed, HEAT PUMP ACDXCOIL 1, Design Size Gross Rated Total Cooling Capacity [W], 24978.88526
 Component Sizing Information, Coil:Heating:DX:SingleSpeed, HEAT PUMP DX HEATING COIL 1, Design Size Gross Rated Heating Capacity [W], 11698.91454
Component Sizing Information, Coil:Heating:Gas, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 18770.14176

Any changes here would be a separate issue.

**Comment by rraustad** [comment]
This is why I can't get any work done.

Why is the DX heating coil a different size than the gas supp heater?

UPDATE: the gas heater sizes the same as the DX heating coil on the OA unit autosizing changes branch.

Old value:
- Component Sizing Information, Coil:Heating:Gas, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 18770.14176

New Value:
- Component Sizing Information, Coil:Heating:Gas, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 11698.91454

There a lot happening now with multiple commits. Things should settle down before this is looked at.

**Comment by rraustad** [comment]
DX coils size the same and supplemental heating coil sizes independently. I don't see a problem here at this point.

```
Component Sizing Information, Coil:Cooling:DX:SingleSpeed, HEAT PUMP ACDXCOIL 1, Design Size Gross Rated Total Cooling Capacity [W], 24978.88526
Component Sizing Information, Coil:Heating:DX:SingleSpeed, HEAT PUMP DX HEATING COIL 1, Design Size Gross Rated Heating Capacity [W], 24978.88526
Component Sizing Information, Coil:Heating:DX:SingleSpeed, HEAT PUMP DX HEATING COIL 1, Design Size Resistive Defrost Heater Capacity [W], 24978.88526
Component Sizing Information, Coil:Heating:Gas, HEAT PUMP DX SUPP HEATING COIL 1, Design Size Nominal Capacity [W], 18770.14176
```

**Comment by mjwitte** [comment]
@rraustad OK to close this then?

**Comment by rraustad** [comment]
Yes, I would close.
