### ISSUE TITLE
ElectricEquipment:ITE:AirCooled has space between "ElectricEquipment" and ":ITE:AirCooled" in the IO Reference

### ISSUE THREAD

**Issue by chandangsharma** [NREL/EnergyPlus#5169]
Reporting a minor issue here. InputOutput reference's table of content has incorrect object name for ElectricEquipment:ITE:AirCooled. Both in the TOC and in associate object description, there is a space between "ElectricEquipment" and ":ITE:AirCooled".

**Comment by mjwitte** [comment]
@Chandangsharma Thanks.  Fixed.

**Comment by mjwitte** [comment]
Addressed via #5154
