### ISSUE TITLE
Follow-up check for Evap Cooler Sizing

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5170]
PR #4940 is being merged in order to move on with development, and it appears correct, but the sizing of the evap cooler parameters should be verified and exercised again before the release.

**Comment by Myoldmopar** [comment]
Additionally verify that the docs are updated with autosize notes.

**Comment by mjwitte** [comment]
@Myoldmopar (repeating this here).  Thanks @Nigusse .

This should not have changed. I looked the evap cooler sizing code and find out the secondary air flow rate sizing code has changed (may be inadvertently). The code on line 1036 shown below:
`IndirectVolFlowRateDes = FinalSysSizing( CurSysNum ).DesOutAirVolFlow;`
 should have been:
`IndirectVolFlowRateDes = max( FinalSysSizing( CurSysNum ).DesOutAirVolFlow, 0.5*FinalSysSizing( CurSysNum ).DesMainVolFlow );`

If this suggested code is modified, it reverts the secondary airflow for the first unit to 0.26972.

**Comment by Myoldmopar** [comment]
Closed via #5189
