### ISSUE TITLE
EMS Schedule actuator does not work with shading surface transmittance schedule

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5185]
Helpdesk ticket 10763
User file has EMS program to actuate the transmittance schedule for a shading surface.  Results show that base schedule is always used, not the EMS actuated value.  This occurs even when the ShadowCalculation is TimestepFrequency.  

Traced the problem in the code to the use of LookUpScheduleValue here in [SolarShading](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SolarShading.cc#L4334-L4345) instead of GetCurrentScheduleValue.  LookUpScheduleValue is used because shadowing calculations are often looking ahead and not using the current time, so it has an hour argument.

Possible fix is to use GetCurrentScheduleValue when TimestepFrequency is set.

No workaround is apparent.

Defect files in EnergyPlusDevSupport\DefectFiles\5000\5185

**Comment by EnergyArchmage** [comment]
might be related to #4944

**Comment by mjwitte** [comment]
While answering helpdesk ticket 12076, noticed that diffuse shading option "DetailedSkyDiffuseModeling" is not honored is the base schedule is constant.  Initial search of source code shows that if's with `DetailedSkyDiffuseAlgorithm` are always && `ShadingTransmittanceVaries`.  So, if none of the shading surface transmittance schedules vary, but EMS actuates them, `ShadingTransmittanceVaries` will be false and the simple sky diffuse algorithm will be used - which means that diffuse shading from the sky dome and horizon will not vary over time.  This should be fixed here as well.

Also, this line in [SolarShading::GetShadowingInput](https://github.com/NREL/EnergyPlus/blob/b3a925464be7ee3d3290ffaf3847822a3e4c3d84/src/EnergyPlus/SolarShading.cc#L678) should be (3), not (2).

**Comment by jcyuan2020** [comment]
In investigating a recent helpdesk ticket# 15669, same problems show up: 1. ems override on shading surface transmittance does not cause a variation on the receiving surface; 2. A warning message shows up showing that setting `DetailedSkyDiffuseModeling` is not actually activated: 
```
   ** Warning ** GetShadowingInput: DetailedSkyDiffuseModeling is chosen but not needed as either the shading transmittance for shading devices does not change throughout the year
   **   ~~~   **  or MinimalShadowing has been chosen.
   **   ~~~   ** Simulation should be set to use SimpleSkyDiffuseModeling, but is left at Detailed for simulation.
   **   ~~~   ** Choose SimpleSkyDiffuseModeling in the ShadowCalculation object to reduce computation time.
```

**Comment by mjwitte** [comment]
And now helpdesk ticket #16048 is stuck on this issue. This needs to get fixed.

**Comment by mjwitte** [comment]
Also, if the base transmittance schedule happens to be 1.0, then then `SurfaceTmp(SurfNum).IsTransparent = true` and the surface will be skipped. This needs to cross-check with EMS somehow.

**Comment by sortiz-hub** [comment]
Any updates on this? We're stuck on this issue and it would be great to get it fixed.

Thanks in advance!

**Comment by mjwitte** [comment]
@sortiz-hub Nothing yet. Hoping to address this for the upcoming v22.1 release.
