### ISSUE TITLE
EP Launch should scan entire file for VERSION object

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5193]
Currently EP-Launch only scans the first 500 lines for detecting the VERSION object so that it can inform the user if it is compatible with the version of the IDD. If it finds a VERSION object with the previous version, it gives the option to update the file to the latest version.

Change this to scan the entire file instead of just the first 500 lines.

**Comment by Myoldmopar** [comment]
Fixed via https://github.com/NREL/EnergyPlusBuildSupport/issues/26
