### ISSUE TITLE
SQLiteFixture.OutputProcessor_getCustomMeterInput unit test failing

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#5194]
It looks like `energyplus_tests` on `develop` is failing again. Probably due to some `clear_state` issues. 

```
[ RUN      ] SQLiteFixture.OutputProcessor_getCustomMeterInput
/Users/nmerket/energyplus/gitrepo/tst/EnergyPlus/unit/OutputProcessor.unit.cc:2564: Failure
Value of: NumEnergyMeters
  Actual: 14
Expected: 17
Segmentation fault: 11
```

**Comment by Myoldmopar** [comment]
Hmm, OK, it doesn't show up on CI, presumably because CI is running them separate.  Thanks for noticing this.  I'm building it locally also to verify the issue.
