### ISSUE TITLE
ZoneHVAC:LowTemperatureRadiant:* Design Capacity Method = FractionOfAutosizedCapacity works without zone sizing run

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#5201]
Follow up on issue #4889 (PR #5137).

Simulation runs when using capacity method "FractionOfAutosized*Capacity" when zone sizing is set to "No". This should produce an error saying "For autosizing of ZoneHVAC:LowTemperatureRadiant:VariableFlow <NAME>, a zone sizing run must be done."

Added defect file: RadLoTempHydrTermReheat-FractionOfAutosize-NoZoneSizing.idf
- Write code to catch this case.
- Make sure there aren't other objects with this capacity method where this is happening.

**Comment by Myoldmopar** [comment]
Closed via #5473
