### ISSUE TITLE
Memory allocation in FMU import libraries

### ISSUE THREAD

**Issue by tsnouidui** [NREL/EnergyPlus#5221]
Revise memory allocation in FMU import libraries.

**Comment by Myoldmopar** [comment]
@tsnouidui Did I also see the changes go in somewhere or not yet?

**Comment by tsnouidui** [comment]
@Myoldmopar  I created an equivalent branch locally which is not check in yet.

Thanks!

Thierry

**Comment by Myoldmopar** [comment]
Closed via #5290
