### ISSUE TITLE
Improve waste heat function handling of AirloopHVAC:UnitarySystem

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#5222]
#5162 improved waste heat function handling for parent object of AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed, and child objects of Coil:*:DX:Multispeed. Since the AirloopHVAC:UnitarySystem object is a parent object of Coil:*:DX:Multispeed, the waste heat function handling of AirloopHVAC:UnitarySystem needs to be addressed in order to be consistent with AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed.

**Comment by mjwitte** [comment]
Closed via #5471
