### ISSUE TITLE
Revise EP-Launch crash dialog

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5224]
The current EP-Launch crash dialog needs some revisions.
![image](https://cloud.githubusercontent.com/assets/4991075/10048726/ed18e006-61d9-11e5-86b4-3a2fef8ca2df.png)

It shouldn't lead with Please Report Crash.  I would delete that section entirely and replace it with something like this.  

**Check the EnergyPlus Installation**
Run an example file to determine if the problem is with this idf file or a more general problem with your EnergyPlus installation.  EnergyPlus works best when installed in a path with no spaces or special characters, and in a location that requires no special permission to write files.  

Also, the last section is not applicable since we don't have traceback now.  Perhaps it could be changed to.
**Check for System Messages**
You may activate 'Pause during Simulation' under the 'View' menu to see if any system messages give any useful information about the reason for the crash.

This is tagged for v8.4.0-bugfix

**Comment by JasonGlazer** [comment]
Fixed in:

https://github.com/NREL/EnergyPlusBuildSupport/pull/21

**Comment by Myoldmopar** [comment]
Addressed via NREL/EnergyPlusBuildSupport#21
