### ISSUE TITLE
Site:WaterMainsTemperature correlation incorrect for southern hemisphere

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#5225]
@nmerket, @ejhw 
The Site:WaterMainsTemperature can use the Christensen/Burch correlation for calculating daily water mains temperatures. Unfortunately, the correlation as originally described is only correct for northern hemispheres. For southern hemispheres, the equation needs to be changed from:
`Tmains = (Tout,avg + 6) + ratio * (ΔTout,maxdiff / 2) * SIN(0.986 * (day - 15 - lag) - 90)`
to
`Tmains = (Tout,avg + 6) + ratio * (ΔTout,maxdiff / 2) * SIN(0.986 * (day - 15 - lag) + sign * 90)`
where
`sign = -1 for latitude > 0,
sign = 1 for latitude < 0`

**Comment by shorowit** [comment]
@nmerket Any chance of getting this into the bugfix release?

**Comment by nmerket** [comment]
Oh this fell off my radar. Sure I think we can manage getting it in there.

**Comment by shorowit** [comment]
Tested this and it gives correct results now. Thanks.

**Comment by nmerket** [comment]
@Myoldmopar this is ready to go.
