### ISSUE TITLE
Table format isn't showing up

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5240]
@lefticus The tables in the docs don't have borders like they used to.  The html tables have this:

```
<table class="table table-striped">
```

and it used to work fine to create nice looking tables.  Now they aren't.  Not sure what the actual issue is, but it would be awesome to fix up before the 8.4.0 release if it's a pretty simple, < 1 hour fix.

**Comment by mjwitte** [comment]
@Myoldmopar Guessing this issue is moot now and can be closed?

**Comment by Myoldmopar** [comment]
Aye. Closing.
