### ISSUE TITLE
Documentation needed for Variable Refrigerant Control - Fluid Temperature Control objects and controls descriptions

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/EnergyPlus#5246]
Documentation Links for EnergyPlus 8.4.0 (using 64 bit Windows version installed from here:  https://github.com/NREL/EnergyPlus/releases/download/v8.4.0/EnergyPlus-8.4.0-832e4bb9cb-Windows-x86_64.exe on 10/4/2015) do not include any information on new feature #5026 (https://github.com/NREL/EnergyPlus/pull/5026) - New VRF Heat Pump Model: VariableRefrigerantFlow:FluidTemperatureControl.

While the E+v8.4.0 .idf editor tool does contain object explanations hinting to proper use, no additional information on these objects can be found in the input/output reference manual linked to the E+v8.4.0 release. In addition, detailed descriptions of the VariableRefrigerantFlow:FluidTemperatureControl algorithm implementation have not been included in the engineering reference documentation referenced by this release. 

Without proper object documentation, misapplication and/or improper specification of this new VRF system (multiple new objects) will likely occur, leading to additional confusion as to proper VRF system modeling techniques when using EnergyPlus.

**Comment by mjwitte** [comment]
@chrisbalbach The pdf files in the installer package are v8.4.0 and include documentation for this feature.  The online pdf files and html documentation have not caught up yet, they are still v8.3.0.

**Comment by Myoldmopar** [comment]
I'll get the online pdfs updated.  For html docs, I could update ours but I'm not really trying to advertise them outside of maybe for interim builds for us devs.  Big Ladder will likely be posting formal html versions of the docs now that the release is out the door.  @nealkruis?

**Comment by nealkruis** [comment]
@Myoldmopar we are discussing this now. It should be pretty straightforward for us. We should have new docs posted soon.

**Comment by Myoldmopar** [comment]
I think this is resolved with the new docs packaged with the release.
