### ISSUE TITLE
FluidCooler:SingleSpeed fatal error with Design Water Flow Rate=autocalculate 

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5269]
Getting

   *\* Severe  *\* FluidCooler:SingleSpeed = "FLUID COOLER", invalid data for "Design Water Flow Rate", entered value <= 0.0, but must be > 0 for Performance Input Method = "UFACTORTIMESAREAANDDESIGNWATERFLOWRATE".
   *\*  Fatal  *\* Errors found in getting fluid cooler input.

when field is shown as autosizable in IDD

See helpdesk ticket 10518

http://energyplus.helpserve.com/staff/Tickets/Ticket/View/10518/inbox/-1/-1/-1/0/-1

This is related to ticket #4694

**Comment by JasonGlazer** [comment]
Added file that shows the problem in 

https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5269

using GBR_London.Gatwick.037760_IWEC.epw

**Comment by Myoldmopar** [comment]
Fixed via #5305
