### ISSUE TITLE
Constructions and materials tables differ between EIO and SQL

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#5272]
I have not seen different values but there are different fields included in the Construction and Material summaries in the EIO and in the Constructions and Materials tables in the SQL output.  Also there is no WindowConstruction table in sql.

**Comment by JasonGlazer** [comment]
@macumber I am starting to review the differences

## Material Details

| Field | In both | In EIO only | In SQLite only |
| --- | --- | --- | --- |
| Material Name | x |  |  |
| ThermalResistance {m2-K/w} | x |  |  |
| Roughness | x |  |  |
| Thickness {m} | x |  |  |
| Conductivity {w/m-K} | x |  |  |
| Density {kg/m3} | x |  |  |
| Specific Heat {J/kg-K} | x |  |  |
| Absorptance:Thermal |  | x |  |
| Absorptance:Solar |  | x |  |
| Absorptance:Visible |  | x |  |
| Material Type |  |  | x |
| ThermGradCoef |  |  | x |
| VaporDiff |  |  | x |

**Comment by JasonGlazer** [comment]
## Construction CTF

| Field | In both | In EIO only | In SQL only |
| --- | --- | --- | --- |
| Construction Name | x |  |  |
| Index |  | x |  |
| Number Layers | x |  |  |
| Number CTFs |  | x |  |
| Time Step {hours} |  | x |  |
| ThermalConductance(UValue in SQL) {w/m2-K} | x |  |  |
| OuterThermalAbsorptance | x |  |  |
| InnerThermalAbsorptance | x |  |  |
| OuterSolarAbsorptance | x |  |  |
| InnerSolarAbsorptance | x |  |  |
| Roughness | x |  |  |
| InsideAbsorpVis |  |  | x |
| OutsideAbsorpVis |  |  | x |

## WindowConstruction

These appear in Construction Table in SQLite

| Field | In both | In EIO only | In SQL only |
| --- | --- | --- | --- |
| Construction Name | x |  |  |
| Index |  | x |  |
| Number Layers | x |  |  |
| Roughness | x |  |  |
| Conductance {W/m2-K} (Uvalue in SQL) | x |  |  |
| SHGC |  | x |  |
| Solar Transmittance at Normal Incidence |  | x |  |
| Visible Transmittance at Normal Incidence |  | x |  |

## WindowMaterial:Glazing

| Field | In both | In EIO only | In SQL only |
| --- | --- | --- | --- |
| Material Name |  | x |  |
| Optical Data Type |  | x |  |
| Spectral Data Set Name |  | x |  |
| Thickness {m} |  | x |  |
| Solar Transmittance |  | x |  |
| Front Solar Reflectance |  | x |  |
| Back Solar Reflectance |  | x |  |
| Visible Transmittance |  | x |  |
| Front Visible Reflectance |  | x |  |
| Back Visible Reflectance |  | x |  |
| Infrared Transmittance |  | x |  |
| Front Thermal Emissivity |  | x |  |
| Back Thermal Emissivity |  | x |  |
| Conductivity {W/m-K} |  | x |  |
| Dirt Factor |  | x |  |
| Solar Diffusing |  | x |  |

## WindowMaterial:Gas

| Field | In both | In EIO only | In SQL only |
| --- | --- | --- | --- |
| Material Name |  | x |  |
| GasType |  | x |  |
| Thickness {m} |  | x |  |

**Comment by JasonGlazer** [comment]
@macumber If we changed both the EIO and SQLite file so that all fields shown above appeared in both, would that resolve this issue? Did I miss anything?

**Comment by JasonGlazer** [comment]
@macumber @mjwitte @Myoldmopar @EnergyArchmage @rraustad @hongtz68 I am planning on making the SQLite and EIO file more consistent. 

Are there other **additional** pieces of the MaterialProperties structure:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DataHeatBalance.hh#L620

or the ConstructionData structure

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DataHeatBalance.hh#L979

that we want in both the EIO and SQLite output files?

**Comment by EnergyArchmage** [comment]
Hummm,  these are the old original SQLite data tables from what Greg did in the beginning right?  I always thought that whole group should be removed and replaced with predefined tabular reports that also show in SQLite.  There is no requirement that everything that appers in the EIO also appears in the SQLite.  

Check out this discussion. 
https://unmethours.com/question/15081/sql-file-why-are-some-parameters-not-present-in-componentsizes/

**Comment by macumber** [comment]
From our side, we don't parse the EIO so it is just important that everything in the EIO also be in SQL.  It doesn't matter to me if these are in special tables or the tabular reports.

**Comment by macumber** [comment]
What is WindowConstruction::index?

**Comment by mjwitte** [comment]
So, we just need a general way to echo everything that's going to eio to sql?

**Comment by macumber** [comment]
Adding an "EIO" table to SQL would meet the most basic needs but it would be pretty gross.  Then there would be three potential places for each piece of data (the custom tables, tabular reports, and EIO table).  I guess it makes most sense to me to add these as tabular reports.  Is there any reason to not just add all the EIO content to the tabular reports?

**Comment by mjwitte** [comment]
No, not really, except the inputs to generate table outputs are different from the ones that generate eio outputs, and some of the eio output is automatic, and some things, like sizing, already go to both eio and table (but only to table if the output is allsummary or asks for that table specifically, but you don't have to request it to show in the eio.)  So, just needs some thought.

**Comment by JasonGlazer** [comment]
Looking at the code, there are over 700 lines that are related to output using the OutputFileInits file number  which is the EIO file. Some of the lines put the "header" lines that describe the contents of each line, some output all the values for a particular type of line and some output just one value at a time. Many still reference old Fortran based "format" lines. One approach would be to replace all those lines with calls to routines that write that information to both the EIO file and the tabular output file. That would put everything from the EIO file in the tabular file as well as in the SQLite file.

**Comment by Myoldmopar** [comment]
Closed via #5928
