### ISSUE TITLE
Documentation for ComponentCost:LineItem with interior surfaces

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#5274]
There is documentation for ComponentCost:LineItem that says 

> If the model includes duplicate surfaces, as for interior partitions or floors, these will be detected and not double-counted.

This seems to be true, however the algorithm that is used to determine which cost is used (e.g. for a ceiling / floor pair which cost is used the cost of the ceiling construction or the floor construction) is not documented

**Comment by Myoldmopar** [comment]
Fixed via #7366
