### ISSUE TITLE
Add Output Variable for Node Fluid Specific Heat 

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5277]
System node data for the specific heat are not reported.  Similiar to density, it would be helpful to be able to report the specific heat of the fluid at each node.  This would generally be useful in off-line energy balance checks of energy balance using M_c_DeltaT type calculations across HVAC components.  

In EMS, there is not a good way to obtain the specific heat for use in various calculations.  The functions for CpCW and CpHW are constant and not really temperature dependent.  There is no way to get specific heat when plant loop is using glycol making it difficult to control ice storage plants with EMS.  

The implementation should go in CalcMoreNodeInfo and follow the pattern used for dewpoint and the like to only do the calculations if the output has been requested.

**Comment by MatthewSteen** [comment]
https://unmethours.com/question/11950/specific-heat-of-water-in-ems/

**Comment by Myoldmopar** [comment]
Closed via #5308
