### ISSUE TITLE
Warn when using FollowThermal to control generators but no values are entered for Rated Thermal to Electrical Power Ratio

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5299]
Helpdesk ticket 10906 and [Unmethours 12451](https://unmethours.com/question/12451/cogeneration-unit-not-turning-on-in-e/)

If ElectricLoadCenter:Distribution species FollowThermal or FollowThermalLimitElectrical, then check the values entered in the ElectricLoadCenter:Generators generator list for "Generator n Rated Thermal to Electrical Power Ratio".  If they are all zero (or blank which becomes zero) then throw a warning or even a fatal (given that the generators aren't going to operate at all).

Also, make this clear in the Input Output Reference where FollowThermal\* is explained.

**Comment by EnergyArchmage** [comment]
Closed via #5437

**Comment by xwanguk** [comment]
My case shows no output even if this "Generator n Rated Thermal to Electrical Power Ratio" does have a value input, say 0.5. Does anybody have an idea why it happened? I am using a Generator:InternalCombustionEngine object and FollowThermal operation scheme in ElectricLoadCenter definition.
