### ISSUE TITLE
Transition end-of-file crash for Shading:Zone:Detailed with blank Number of Vertices field

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5316]
Helpdesk ticket 10928
Attempt to transition user file from v8.1 to v8.4 failed.  Tracked it down to blank number of vertices fields in this file that was generated by the CA CBECC-Com interface.  These default to autocalculate so EnergyPlus runs it just fine, but transition (any version) fails with an end-of-file error while processing Shading:Zone:Detailed objects.  [Code for that appears](https://github.com/NREL/EnergyPlus/blob/b194030982ab30336c3d3bca759fe75a9a29218e/src/Transition/VCompareGlobalRoutines.f90#L838-L846) to be the same as other similar objects, so not sure why it processes the BuildingSurface:Detailed objects OK and then fails on the shading objects.  Reproduced the problem with a v8.3 5ZoneAirCooled example file with all Number of Vertices fields changed to blank.

```
 Enter input file name, with path
-->5ZoneAirCooled-v8.3-BlankNumberOfVertices.idf
 Processing IDF -- 5ZoneAirCooled-v8.3-BlankNumberOfVertices.idf
At line 845 of file C:\ci\builds\EP-v8.4.0-Win64-VS12\src\Transition\VCompareGlobalRoutines.f90
Fortran runtime error: End of file

C:\EnergyPlusV8-4-0\PreProcess\IDFVersionUpdater>
```

**Comment by Myoldmopar** [comment]
Ugh.

**Comment by mjwitte** [comment]
Oh - now I see it. In line 842 ELSEIF (OutArgs(3) == '') THEN 
should be (4).
