### ISSUE TITLE
Unassigned ZoneHVAC:TerminalUnit:VariableRefrigerantFlow will crash program

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#5317]
Models that contain a ZoneHVAC:TerminalUnit:VariableRefrigerantFlow that is not associated with a AirConditioner:VariableRefrigerantFlow through ZoneTerminalUnitList will crash E+. This is clearly a user input error, but the program should not crash and it would be helpful to have some information in the error file.

I will attach a defect file to demonstrate this.

**Comment by mjwitte** [comment]
With 8.4?  A similar issue has been fixed, but this could be different.
https://github.com/NREL/EnergyPlus/pull/5164
https://github.com/NREL/EnergyPlus/issues/4952

**Comment by kbenne** [comment]
hmmm. thats a good point. This is 8.3. I'll transition the file and see if it persists.

**Comment by kbenne** [comment]
Yes it is fixed in 8.4. Thanks! Closing. Have a nice day. :)
