### ISSUE TITLE
Near-zero source side effectiveness in water heater causing NANs which trigger a fatal error later in the thermostat

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5319]
Helpdesk ticket 10919
Fatal error due to NANs:
   *\* Severe  *\* DualSetPointWithDeadBand: Unanticipated combination of heating and cooling loads - report to EnergyPlus Development Team
   *\*   ~~~   *\* occurs in Zone=R%0RI:ELOUNGE Environment=PARIS, at Simulation time=07/12 06:30 - 06:35
   *\*   ~~~   *\* LoadToHeatingSetPoint=NAN, LoadToCoolingSetPoint=NAN
   *\*   ~~~   *\* Zone Heating Set-point=17.69
   *\*   ~~~   *\* Zone Cooling Set-point=179.69
   *\*   ~~~   *\* Zone TempDepZnLd=51572.82
   *\*   ~~~   *\* Zone TempIndZnLd=NAN
   *\*   ~~~   *\* Zone ThermostatSetPoint=18.05
   *\*  Fatal  *\* Program terminates due to above conditions.

User tracked the problem down to having a near-zero source side effectiveness in the water heater (v8.3.0) 
But @rraustad found in v8.4 debug version that the defect file fails in SolarShading::ClipPoly [here](https://github.com/NREL/EnergyPlus/blob/fc19ef3490c5908eb3ec9412ca2370f13c239a15/src/EnergyPlus/SolarShading.cc#L2792) with S=0.

Note that a similar but different problem with number of vertices was addressed in #5215 where the number of vertices was too large for the array. While clippoly should protect itself from bad arguments for number of vertices, the root problem may lie in the routine(s) that are calling clippoly.

**Comment by rraustad** [comment]
I am not working on this one, take a crack at it.

**Comment by JasonGlazer** [comment]
Thanks. The run time is crazy for this defect file. I started it over an hour ago and it is still warming up.

**Comment by mjwitte** [comment]
@rraustad @JasonGlazer #5654 addresses the problem with tank source side effectiveness.  Is there still an issue with SolarShading::Clippoly?

**Comment by JasonGlazer** [comment]
@mjwitte If I remember correctly, the NaN was just percolating through the code and showed up in Clippoly.

**Comment by mjwitte** [comment]
Addressed via #5654
