### ISSUE TITLE
Object Count Summary Surface By Class table output miscounting some objects

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5320]
Helpdesk ticket 10938

Shading:Fin\* and Shading:Overhang:\* are counted as "Shading" and the rows for "Fin" and "Overhang" are zero. Sample table output for example file 4ZoneWithShading_Simple2 (with table output added).  This file has the following shading objects:
![image](https://cloud.githubusercontent.com/assets/4991075/11198897/52ca0c70-8c8e-11e5-9a6b-870e0b405439.png)
And the surface by class report is:
![image](https://cloud.githubusercontent.com/assets/4991075/11198903/67079fae-8c8e-11e5-90a1-29cd5224bb93.png)

Also, Tubular Daylighting Device Diffuser is not being counted - this row is zero for DaylightingDeviceTubular.idf

**Comment by JasonGlazer** [comment]
@mjwitte and @Myoldmopar It seems like the SurfaceClass_Overhang and SurfaceClass_Fin never actually get assigned to any surface().class anywhere even though it is referenced in a bunch of if()'s. Do you know if they were removed for some reason in the past or where they never fully implemented?

**Comment by mjwitte** [comment]
Nothing that I recall.  You might check the archive to see if they were ever used.  Shading:Overhang and Shading:Fin were added in v3.1.0 (April 2009) but the integer parameters were added [here](https://github.com/NREL/EnergyPlusArchive/commit/24b4c54d85d079212a83025eb5881edf63f06e38) in 2006.

Looking at the source back in v3.1 and prior, it doesn't appear that SurfaceClass_Overhang was ever assigned to surfaces, it was only used as an argument to the Triangulate function in OutputReports.  My guess is that the other if statements that are using SurfaceClass_Overhang were added without realizing that these aren't really assigned.  

So, since Shading:Overhang and the like are being set to SurfaceClass_Shading, is every place that checks for SurfaceClass_Shading also checking for SurfaceClass_Overhang and SurfaceClass_Fin?

**Comment by JasonGlazer** [comment]
No, SurfaceClass_Overhang is only used a few times including once that SurfaceClass_Shading is not used in DXFEarClipping.cc(307)

**Comment by JasonGlazer** [comment]
@mjwitte For counting of overhangs I assume that we just want the count of Shading:Overhang and Shading:Overhang:Projection and for counting fins I assume that we just want to count Shading:Fin and Shading:Fin:Projection correct? I know that other shading surfaces can act as overhangs and fins such as Shading:Zone:Detailed, Shading:Building, and Shading:Building:Detailed  but unless I examine the vertices, I don't know how to classify them as fins or overhangs. Should I ignore those?

**Comment by mjwitte** [comment]
@JasonGlazer Given current inputs, the best you can do is count those specific Overhang and Fin objects and put all the rest of the general shading objects into Shading.  But the reality is that most interfaces probably don't generate the Overhang and Fin objects (I may be wrong) but rather use the more general shading surface types.

So, are these counts of overhangs and fins required for LEED?  Could we just drop those rows from the table?

**Comment by Myoldmopar** [comment]
Closed via #5517
