### ISSUE TITLE
Swimming pool flow rate units corrected but not changed in Energy+.idd

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#5325]
I reported a bug about flow rate input as m3/s in Swimming pool object while it was taken as kg/s. It seems that you closed that in https://github.com/NREL/EnergyPlus/issues/4805 but Energy+.idd still shows m3/s (and so does IDFEditor).

**Comment by mjwitte** [comment]
The input is correct as m3/s.  Please see additional discussion added to #5028
