### ISSUE TITLE
Add website to top of the repository 

### ISSUE THREAD

**Issue by anselmbradford** [NREL/EnergyPlus#5335]
![screen shot 2015-11-25 at 7 50 36 pm](https://cloud.githubusercontent.com/assets/704760/11412688/de6bc482-93ad-11e5-9316-82c45e976b6c.png)

^ Add a short description and link to energyplus.gov there.

**Comment by Myoldmopar** [comment]
How's [this](https://github.com/nrel/energyplus)?

![image](https://cloud.githubusercontent.com/assets/849824/12340757/18f9f530-bada-11e5-865d-508724f79eca.png)

**Comment by anselmbradford** [comment]
:+1:
