### ISSUE TITLE
Documentation error in ERef IdealLoads

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#5341]
In Engineering Reference https://github.com/NREL/EnergyPlus/blob/develop/doc/src/docs/EngineeringReference/13d-EncyclopaedicRefs.md#all-input-data-for-the-zonehvacidealloadsairsystem-is-stored-in-the-array-purchair-the-model-and-data-are-encapsulated-in-the-module-purchasedairmanagercalculation

This formula:
`$${T_s} = {T_{ma}} + {\dot Q_z}/({c_{p,air}}\cdot {\dot m_s})$$`
Should be:
`$${T_s} = {T_z} + {\dot Q_z}/({c_{p,air}}\cdot {\dot m_s})$$`

**Comment by Myoldmopar** [comment]
Closed via #5424
