### ISSUE TITLE
Wrap-up for Bug Fix Release

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5355]
### [Issues](https://github.com/nrel/EnergyPlus/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22EnergyPlus+8.4.0%2BBugFix%22+label%3APriority+label%3A%22S1+-+High%22) (8.4.0+BugFix + S1 + Priority)

| Issue | Pivotal | Assignee | Status | Pull Request |
| --- | --- | --- | --- | --- |
| #5314 | [#109727440](https://www.pivotaltracker.com/story/show/109727440) | @myoldmopar | CLOSED | - |
| #5276 | [#106228940](https://www.pivotaltracker.com/story/show/106228940) | @wfbuhl | Will fix | - |
| #5257 | [#109384508](https://www.pivotaltracker.com/story/show/109384508) | @myoldmopar | [COMPLETE](https://github.com/NREL/EnergyPlus/commit/9da112c653f018f8484435fada1ff1cf68aa6593) | #5348 |
| #5252 | [#105155432](https://www.pivotaltracker.com/story/show/105155432) | @rongpengzhang | COMPLETE | #5367 |
| #5119 | [#109729064](https://www.pivotaltracker.com/story/show/109729064) | @mjwitte | Preliminary investigation | - |
| #4994 | [#109051292](https://www.pivotaltracker.com/story/show/109051292) | @mjwitte | COMPLETE | #5336 |
| #4944 | [#105671820](https://www.pivotaltracker.com/story/show/105671820) | @JasonGlazer | Fix in progress | - |
| #4931 | [#105671858](https://www.pivotaltracker.com/story/show/105671858) | @myoldmopar | In Discussion | - |
| #4853 | [#109729564](https://www.pivotaltracker.com/story/show/109729564) | @rraustad | COMPLETE | #5358 |
| #4633 | [#105671910](https://www.pivotaltracker.com/story/show/105671910) | @mjwitte | In Discussion | - |
| #3522 | [#103416576](https://www.pivotaltracker.com/story/show/103416576) | @myoldmopar | - | - |
| #4407 | [#101163166](https://www.pivotaltracker.com/story/show/101163166) | @myoldmopar | Fixed, waiting review | #5338 |
| #4399 | [#103711916](https://www.pivotaltracker.com/story/show/103711916) | @mjwitte | Fixed, waiting review | #5216 |
### Other tasks
- [x] Build documentation and post to BuildSupport
- [ ] Check if some 8.5 related items (transition, rules, etc.) snuck in, and if the cmake is pointing to the right branch on BuildSupport.
- [ ] Test installers on platforms
- [ ] Update website
- [ ] Update [epupdate.htm](http://energyplus.net/epupdate.htm) trigger
### Notes

FYI: @rraustad @mjwitte @lgentile

**Comment by rongpengzhang** [comment]
Hi Edwin,

#5252 <https://github.com/NREL/EnergyPlus/issues/5252>#105155432
<https://www.pivotaltracker.com/story/show/105155432>is almost there. I
have found a solution to fix the issue and the implementation is almost
done. I need 1-2 days to clean it up and update the unit test.


I think you can change its status to "Will fix".

Thanks,
Rongpeng



On Tue, Dec 8, 2015 at 9:32 AM, Edwin Lee <notifications@github.com> wrote:

> To-Do list for 8.4.0+BugFix release: Issues (8.4.0+BugFix + S1 + Priority)
> Issue Pivotal Assignee Status Pull Request #5314
> <https://github.com/NREL/EnergyPlus/issues/5314> #109727440
> <https://www.pivotaltracker.com/story/show/109727440> @myoldmopar
> <https://github.com/myoldmopar> Will fix - #5276
> <https://github.com/NREL/EnergyPlus/issues/5276> #106228940
> <https://www.pivotaltracker.com/story/show/106228940> @wfbuhl
> <https://github.com/wfbuhl> Might not fix - #5257
> <https://github.com/NREL/EnergyPlus/issues/5257> #109384508
> <https://www.pivotaltracker.com/story/show/109384508> @myoldmopar
> <https://github.com/myoldmopar> Fixed, in review #5348
> <https://github.com/NREL/EnergyPlus/pull/5348> #5252
> <https://github.com/NREL/EnergyPlus/issues/5252> #105155432
> <https://www.pivotaltracker.com/story/show/105155432> @rongpengzhang
> <https://github.com/rongpengzhang> Unknown - #5119
> <https://github.com/NREL/EnergyPlus/issues/5119> #109729064
> <https://www.pivotaltracker.com/story/show/109729064> @mjwitte
> <https://github.com/mjwitte> Preliminary investigation - #4994
> <https://github.com/NREL/EnergyPlus/issues/4994> #109051292
> <https://www.pivotaltracker.com/story/show/109051292> @mjwitte
> <https://github.com/mjwitte> Fixed, in review #5336
> <https://github.com/NREL/EnergyPlus/pull/5336> #4944
> <https://github.com/NREL/EnergyPlus/issues/4944> #105671820
> <https://www.pivotaltracker.com/story/show/105671820> - - - #4931
> <https://github.com/NREL/EnergyPlus/issues/4931> #105671858
> <https://www.pivotaltracker.com/story/show/105671858> - - - #4853
> <https://github.com/NREL/EnergyPlus/issues/4853> #109729564
> <https://www.pivotaltracker.com/story/show/109729564> @rraustad
> <https://github.com/rraustad> Preliminary investigation - #4633
> <https://github.com/NREL/EnergyPlus/issues/4633> #105671910
> <https://www.pivotaltracker.com/story/show/105671910> - - - #3522
> <https://github.com/NREL/EnergyPlus/issues/3522> #103416576
> <https://www.pivotaltracker.com/story/show/103416576> @myoldmopar
> <https://github.com/myoldmopar> - - Other tasks
>
>    - Build documentation and post to BuildSupport
>    - Test installers on platforms
>
> Notes
>
> FYI: @rraustad <https://github.com/rraustad> @mjwitte
> <https://github.com/mjwitte> @lgentile <https://github.com/lgentile>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NREL/EnergyPlus/issues/5355>.
>



-- 
Rongpeng Zhang, Ph.D.
Building Technology and Urban Systems Division
Lawrence Berkeley National Laboratory, Berkeley, CA 94720
