### ISSUE TITLE
HeatPump:WaterToWater:ParameterEstimation:Cooling/Heating requires R22 objects in idf - clarify docs and error message

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5363]
Helpdesk Ticket 10981
Hidden in an introductory paragraph for the HeatPump:WaterToWater:ParameterEstimation:\* objects (v8.4 Input Output Reference, p. 548) is this statement "Note that this model is currently “hardwired” to fluid property R22."  

It also should say "FluidProperties:\* objects for R-22 must be included in the idf file. These may be copied from DataSets\FluidPropertiesRefData.idf"

When this equipment is used without the R-22 objects, this is the error message:

`**  Fatal  ** Refrigerant for HeatPump:WaterToWater Heating not found, should have been=R22`

That needs to be expanded to say that FluidProperties objects for R-22 need to be added to the idf file.

**Comment by Myoldmopar** [comment]
Closed via #5424
