### ISSUE TITLE
Should show progress in output window even when using TimestepFrequency 

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5365]
When ShadowCalculation field Calculation Method is set to TimestepFrequency the output window does not show progress of the simulation. It shows when the simulation begins but no other dates. When this is set to AverageOverDaysInFrequency the shadowing calculations are updated regularly which shows the user the progress. It is good to show progression of time of the simulation to the user. Suggest that monthly indicators are shown on the output window when TimestepFrequency is specified.

**Comment by JasonGlazer** [comment]
EMSThermochromicWindow.idf when made an annual simulation demonstrates this issue. The output window shows no progress.

**Comment by Myoldmopar** [comment]
Closed via #5553
