### ISSUE TITLE
Reunify EnergyPlus Static Libraries

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5368]
Because of some issues during LTO/PGO investigation, we ended up pulling the E+ source into two separate static libraries, [`energypluslib`](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CMakeLists.txt#L571) and [`energypluslib2`](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CMakeLists.txt#L580), which are based on two separate chunks of source, [`SRC`](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CMakeLists.txt#L12) and [`SRC_2`](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CMakeLists.txt#L311).  For editing source in a non-IDE environment, it's no problem, because the source is still in a single folder.  However, it is awkward when opening the project in Visual Studio or XCode, because the code is then split into the two separate projects.  

I think we should move it back to a single static library project and remove this awkwardness.  Do you have any problem with this @kbenne or @lefticus or @mbadams5?

**Comment by lefticus** [comment]
My only comment is that I recall that the split lib compiled / linked
faster. But who knows if that's so true, or by how much.

**Comment by amirroth** [comment]
It wouldn't compile faster. I can't see anything fundamental about the
linking process that would make it link faster, but maybe.

**Comment by lefticus** [comment]
IIRC, splitting it up allowed for more parallelization during the build process, not that individual files were compiled faster.

I think it was the MSVC linker specifically that got bogged down with linking that many .o files at once

**Comment by kbenne** [comment]
:+1:

**Comment by Myoldmopar** [comment]
@kbenne Could you provide a link to what you are plus one ing?

Like: [:+1:](https://github.com/NREL/EnergyPlus/issues/5368#issue-121736667) or [:+1:](https://github.com/NREL/EnergyPlus/issues/5368#issuecomment-164255244)

**Comment by kbenne** [comment]
hehe. I liked that there was a little ambiguity, but I figured you might ask. I'm voting for the title of the issue. reunification.

**Comment by mjwitte** [comment]
Closed via #5396
