### ISSUE TITLE
Zone Thermal Comfort ASHRAE 55 Adaptive Model Running Average Outdoor Air Temperature Error at beginning of year

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5381]
Helpdesk ticket 10614
From user (have not verified, user files in dev support defect files folder):
The People objects provide for the calculation of the ASHRAE 55 Adaptive comfort temp for use in output, and which can also be used as a window control option if using AFN. The Standard provides for calculation of a prevailing mean outdoor air temp, called by E+ the "Zone Thermal Comfort ASHRAE 55 Adaptive Model Running Average Outdoor Air Temperature" (which I'll call Tpma following the standard). This is then used to calculate the center of the comfort band, called by E+ "Zone Thermal Comfort ASHRAE 55 Adaptive Model Temperature."

The issue is that the Tpma calculated by E+ seems to have some error in the beginning of the year. I would imagine this is some type of a startup issue. It's pretty severe the first month, and takes about 3 months to be fully forgotten by the moving average. In the attached, I just ran the idf for two run periods, and you'll see the calculated Tpma is different for the two years. Since it's just based on outdoor air temp, it should be the same. In this case, the Tpma error not only changes the indoor comfort temp but actually leads to it giving an error the first year (since Tpma with the error appeared to be out of the bounds allowed by the Standard), but not the second year.

I ran this with the San Fran weather file for demo. (Tpme in the file name because of the Portuguese translation -- same thing as Tpma).

**Comment by lgu1234** [comment]
I test file. "Zone Thermal Comfort ASHRAE 55 Adaptive Model Running Average Outdoor Air Temperature" is not calculated correctly. Here is my observation. 

There are several bugs in initialization in the CalcThermalComfortAdaptiveASH55 function of the ThermalComfort module.
1. Skip 9 lines when reading a weather file
Each epw file has 8 lines of headers. The code reads 9 lines. This needs to be corrected.
2. Use a wrong starting day
The Tpme is supposed to be an average value in the previous 30 days. When Jan. 1 is used in the first day for simulation, the starting day for average is Dec. 2. The code uses Dec. 1.
3. Wrong calculation of Tpma 
Here is a line of calculation:
	runningAverageASH = ( 29.0 * runningAverageASH + avgDryBulbASH ) / 30.0;
When the initial value of runningAverageASH is zero, the above calculation will give wrong output. The correct calculation is  
	runningAverageASH = runningAverageASH + avgDryBulbASH  / 30.0;

I will fix bugs in initialization, then take care of the rest. Other code also has problems.

**Comment by mjwitte** [comment]
Closed via #6474
