### ISSUE TITLE
Update "Check File Version" message when finding newer version

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5383]
When a newer file (say 8.4.0) is run in an old version of EP-Launch (say 8.3.0) the same error message comes up that says "Check File Version" saying that it is an "old" version even though it is actually a newer version. Either update the wording of the message or make the algorithm more sensitive to if the version is newer or older than the current version. 

See help desk 11006. It can be reproduced by running an EP-Launch in an older EnergyPlus directory while selecting a newer IDF file.

**Comment by Myoldmopar** [comment]
Fixed via https://github.com/NREL/EnergyPlusBuildSupport/issues/26
