### ISSUE TITLE
Provide a better warning message for a triangular window in the AirflowNetwork model

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#5384]
When a triangular window is used in the AirflowNetwork model, a warning message is not clear enough:

*\* ~~~ *\* The opening is a Triangular subsurface. A rectangular subsurface should be used

Ticket 10863 provides such suggestions:

How does EnergyPlus treat such openings? Does it ignore them in the AFN? Or does it make some assumptions about opening areas etc? It would be nice if the message said a word or two on this.

**Comment by mjwitte** [comment]
Closed via #5462
