### ISSUE TITLE
Include VRF Heat Pump modeling capabilities with AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl object

### ISSUE THREAD

**Issue by chrisbalbach** [NREL/EnergyPlus#5387]
After reading the engineering reference documentation for this object, it is my understanding that the AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl object can only be used to model VRF systems operating in Heat Pump models and cannot be configured to model VRF systems capable of operating in a heat recovery mode.

If it is possible to extend the AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl object to correctly represent heat recovery operations it would be a more useful (less limited) model.

**Comment by rongpengzhang** [comment]
@chrisbalbach  A new physics based VRF-HR model is a new feature we have been working on. Hopefully it will be ready for the next EPlus release.

**Comment by mjwitte** [comment]
@chrisbalbach This had been added for the v8.6.0 release in September.  See #5633.
