### ISSUE TITLE
Invalid Number in Numeric Field

### ISSUE THREAD

**Issue by jburek** [NREL/EnergyPlus#5390]
I'm using Reference Supermarket model: RefBldgSuperMarketPost1980_v1.4_7.2_5A_USA_IL_CHICAGO-OHARE.idf

During simulation I get these errors - most point to Invalid Number in Numeric Field (I copied all below). I would appreciate your help in fixing those issues. Thank you. 
Jasmina

Program Version,EnergyPlus, Version 8.4.0-832e4bb9cb, YMD=2015.12.25 14:25,IDD_Version 8.4.0
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   2610   Sizing:System,
   ************\* indicated Name=PSZ-AC:1
   ************\* Only last 10 lines before error line shown.....
   ************\*   2619     12.8000,                 !- Central Cooling Design Supply Air Temperature {C}
   ************\*   2620     40.0,                    !- Central Heating Design Supply Air Temperature {C}
   ************\*   2621     NonCoincident,           !- Type of Zone Sum to Use
   ************\*   2622     No,                      !- 100% Outdoor Air in Cooling
   ************\*   2623     No,                      !- 100% Outdoor Air in Heating
   ************\*   2624     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2625     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2626     DesignDay,               !- Cooling Supply Air Flow Rate Method
   ************\*   2627     ,                        !- Cooling Supply Air Flow Rate {m3/s}
   ************\*   2628     DesignDay,               !- Cooling Supply Air Flow Rate Per Floor Area {m3/s-m2}
   *\* Severe  *\* IP: IDF line~2628 Invalid Number in Numeric Field#12 (Cooling Supply Air Flow Rate Per Floor Area), value=DESIGNDAY, in SIZING:SYSTEM=PSZ-AC:1
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   2649   Sizing:System,
   ************\* indicated Name=PSZ-AC:2
   ************\* Only last 10 lines before error line shown.....
   ************\*   2658     12.8000,                 !- Central Cooling Design Supply Air Temperature {C}
   ************\*   2659     40.0,                    !- Central Heating Design Supply Air Temperature {C}
   ************\*   2660     NonCoincident,           !- Type of Zone Sum to Use
   ************\*   2661     No,                      !- 100% Outdoor Air in Cooling
   ************\*   2662     No,                      !- 100% Outdoor Air in Heating
   ************\*   2663     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2664     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2665     DesignDay,               !- Cooling Supply Air Flow Rate Method
   ************\*   2666     ,                        !- Cooling Supply Air Flow Rate {m3/s}
   ************\*   2667     DesignDay,               !- Cooling Supply Air Flow Rate Per Floor Area {m3/s-m2}
   *\* Severe  *\* IP: IDF line~2667 Invalid Number in Numeric Field#12 (Cooling Supply Air Flow Rate Per Floor Area), value=DESIGNDAY, in SIZING:SYSTEM=PSZ-AC:2
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   2688   Sizing:System,
   ************\* indicated Name=PSZ-AC:3
   ************\* Only last 10 lines before error line shown.....
   ************\*   2697     12.8000,                 !- Central Cooling Design Supply Air Temperature {C}
   ************\*   2698     40.0,                    !- Central Heating Design Supply Air Temperature {C}
   ************\*   2699     NonCoincident,           !- Type of Zone Sum to Use
   ************\*   2700     YES,                     !- 100% Outdoor Air in Cooling
   ************\*   2701     YES,                     !- 100% Outdoor Air in Heating
   ************\*   2702     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2703     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2704     DesignDay,               !- Cooling Supply Air Flow Rate Method
   ************\*   2705     ,                        !- Cooling Supply Air Flow Rate {m3/s}
   ************\*   2706     DesignDay,               !- Cooling Supply Air Flow Rate Per Floor Area {m3/s-m2}
   *\* Severe  *\* IP: IDF line~2706 Invalid Number in Numeric Field#12 (Cooling Supply Air Flow Rate Per Floor Area), value=DESIGNDAY, in SIZING:SYSTEM=PSZ-AC:3
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   2727   Sizing:System,
   ************\* indicated Name=PSZ-AC:4
   ************\* Only last 10 lines before error line shown.....
   ************\*   2736     12.8000,                 !- Central Cooling Design Supply Air Temperature {C}
   ************\*   2737     40.0,                    !- Central Heating Design Supply Air Temperature {C}
   ************\*   2738     NonCoincident,           !- Type of Zone Sum to Use
   ************\*   2739     No,                      !- 100% Outdoor Air in Cooling
   ************\*   2740     No,                      !- 100% Outdoor Air in Heating
   ************\*   2741     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2742     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2743     DesignDay,               !- Cooling Supply Air Flow Rate Method
   ************\*   2744     ,                        !- Cooling Supply Air Flow Rate {m3/s}
   ************\*   2745     DesignDay,               !- Cooling Supply Air Flow Rate Per Floor Area {m3/s-m2}
   *\* Severe  *\* IP: IDF line~2745 Invalid Number in Numeric Field#12 (Cooling Supply Air Flow Rate Per Floor Area), value=DESIGNDAY, in SIZING:SYSTEM=PSZ-AC:4
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   2766   Sizing:System,
   ************\* indicated Name=PSZ-AC:5
   ************\* Only last 10 lines before error line shown.....
   ************\*   2775     12.8000,                 !- Central Cooling Design Supply Air Temperature {C}
   ************\*   2776     40.0,                    !- Central Heating Design Supply Air Temperature {C}
   ************\*   2777     NonCoincident,           !- Type of Zone Sum to Use
   ************\*   2778     No,                      !- 100% Outdoor Air in Cooling
   ************\*   2779     No,                      !- 100% Outdoor Air in Heating
   ************\*   2780     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2781     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2782     DesignDay,               !- Cooling Supply Air Flow Rate Method
   ************\*   2783     ,                        !- Cooling Supply Air Flow Rate {m3/s}
   ************\*   2784     DesignDay,               !- Cooling Supply Air Flow Rate Per Floor Area {m3/s-m2}
   *\* Severe  *\* IP: IDF line~2784 Invalid Number in Numeric Field#12 (Cooling Supply Air Flow Rate Per Floor Area), value=DESIGNDAY, in SIZING:SYSTEM=PSZ-AC:5
   ************\* IDF Context for following error/warning message:
   ************\* Note -- lines truncated at 300 characters, if necessary...
   ************\*   2805   Sizing:System,
   ************\* indicated Name=PSZ-AC:6
   ************\* Only last 10 lines before error line shown.....
   ************\*   2814     12.8000,                 !- Central Cooling Design Supply Air Temperature {C}
   ************\*   2815     40.0,                    !- Central Heating Design Supply Air Temperature {C}
   ************\*   2816     NonCoincident,           !- Type of Zone Sum to Use
   ************\*   2817     No,                      !- 100% Outdoor Air in Cooling
   ************\*   2818     No,                      !- 100% Outdoor Air in Heating
   ************\*   2819     0.0085,                  !- Central Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2820     0.0080,                  !- Central Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
   ************\*   2821     DesignDay,               !- Cooling Supply Air Flow Rate Method
   ************\*   2822     ,                        !- Cooling Supply Air Flow Rate {m3/s}
   ************\*   2823     DesignDay,               !- Cooling Supply Air Flow Rate Per Floor Area {m3/s-m2}
   *\* Severe  *\* IP: IDF line~2823 Invalid Number in Numeric Field#12 (Cooling Supply Air Flow Rate Per Floor Area), value=DESIGNDAY, in SIZING:SYSTEM=PSZ-AC:6
   *\* Severe  *\* IP: Possible incorrect IDD File
   *\*   ~~~   *\* IDD Version:"IDD_Version 8.4.0"
   *\*   ~~~   *\* Version in IDF="8.4" not the same as expected="8.4"
   *\*   ~~~   *\* Possible Invalid Numerics or other problems
   *\*  Fatal  *\* IP: Errors occurred on processing IDF file. Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=7
   ..... Last severe error=IP: Possible incorrect IDD File
   ************\* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************\* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************\* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************\* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************\* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 7 Severe Errors; Elapsed Time=00hr 00min  0.41sec

**Comment by mjwitte** [comment]
Did you use the IDFVersionUpdater to transition the file up to v8.4.0?

**Comment by jburek** [comment]
Yes I did. I went back to check again and I get a message the file does not need to be updated. 
![image](https://cloud.githubusercontent.com/assets/8441346/12105817/1d47af2e-b31e-11e5-8312-f81bf9eb505f.png)

THen I run transition and I get info that no translation will be performed.
![image](https://cloud.githubusercontent.com/assets/8441346/12105849/57058b8c-b31e-11e5-8c85-1e6788397c45.png)

And a run simulation and shows the previous error. I'm not sure if my steps are correct, but what I noticed the file still remains with 8.3 in the title RefBldgSuperMarketPost1980_v1.4_7.2_5A_USA_IL_CHICAGO-OHARE_V830.idf (below I saved the idf file to txt, because I couldn't share here the original file. 
[RefBldgSuperMarketPost1980_v1.4_7.2_5A_USA_IL_CHICAGO-OHARE_V830.txt](https://github.com/NREL/EnergyPlus/files/77925/RefBldgSuperMarketPost1980_v1.4_7.2_5A_USA_IL_CHICAGO-OHARE_V830.txt)

**Comment by jburek** [comment]
Also I was able to run the original model in version 8.2 of Energy plus

**Comment by mjwitte** [comment]
Looking at the sizing:system objects, it appears that the transition from 8.2 to 8.3 was never done completely (possibly used an iteration release, or ?).  You'll need to go back to the v8.2 file an transition up to v8.4.

**Comment by jburek** [comment]
That solved the problem. Thank you.
