### ISSUE TITLE
Remove deprecated input fields from four Air Terminal Single Duct Objects

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#5404]
Refer to bug issue:
https://github.com/NREL/EnergyPlus/issues/4902

And while you're at it (either in this issue or a separate one), we should remove similar deprecated fields from:
AirTerminal:SingleDuct:ConstantVolume:FourPipeInduction
AirTerminal:SingleDuct:ConstantVolume:Reheat
AirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan
AirTerminal:SingleDuct:VAV:HeatAndCool:Reheat

**Comment by mjwitte** [comment]
Closed via #5414
