### ISSUE TITLE
Aircooled ChillerHeater:Absorption:DirectFired and ChillerHeater:Absorption:DoubleEffect should use curve coef for second parameter for outdoor air temp

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5405]
Upon code inspection noticed that the ChillerHeater:Absorption:DirectFired (function ChillerGasAbsorption) and ChillerHeater:Absorption:DoubleEffect (function ChillerExhaustAbsorption) chillers use the same calculation for aircooled and watercooled cases even though the aircooled should only be using single variable curves which the watercooled uses double variable curves. This affects the capacity calculation. Should check if same issue exists for energy consumption calculation.

See discussion for #5380

**Comment by JasonGlazer** [comment]
@Myoldmopar Feel free to add comments.

**Comment by JasonGlazer** [comment]
When changing either ChillerHeater:Absorption:DoubleEffect or ChillerHeater:Absorption:DirectFired to use AirCooled condenser type, EnergyPlus crashes. Posted new defect files in:

https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5405

**Comment by JasonGlazer** [comment]
Overall the second parameter should be getting used (although the title of this issue says it should not) for sensitivity to the air temperature that the air cooled condenser is facing.

**Comment by mjwitte** [comment]
Closed via #5609
