### ISSUE TITLE
El Capitan (Mac OSX) breaks EnergyPlus

### ISSUE THREAD

**Issue by mbadams5** [NREL/EnergyPlus#5410]
Due to new System Integrity Protection, various locations are no longer user writable, even as root. This breaks the runenergyplus script and potentially the installation script since it installs symlinks to `/usr/bin`.

See [UnmetHours post regarding this](https://unmethours.com/question/13844/el-capitan-breaking-energyplus/).

**Comment by kbenne** [comment]
Boot the runenergyplus script in favor CLI? Trying to write outside of user home seems like a bad idea from the get go.

One wrinkle is that I think the runenergyplus script is a dependency of EP-Launch Lite.

**Comment by mbadams5** [comment]
I am curious what happens during install. I haven't tried since I installed El Capitan. I don't think the installer can create the symlinks in `/usr/bin`.

**Comment by kbenne** [comment]
Along those lines... What happens when you do an upgrade where there are already links in place?

**Comment by mjwitte** [comment]
@mbadams5 @kbenne Any progress on this?

**Comment by mjwitte** [comment]
From @tsnouidui with some additional info.
Apple has enabled a new default security oriented featured called System Integrity Protection, often called rootless, in OS X 10.11 onwards.

The consequence is that some files and directories such as /usr/bin are now write-protected even for the root user.
Consequently, programs such as EnergyPlus won't longer be able to create symbolic link to /usr/bin/etc as done in the past. This will cause runenergyplus and energyplus to not work anymore.

Furthermore, this addition also prevents any shell script or non-protected softwares to set (touch) LD_LIBRARY_PATH or DYLD_LIBRARY_PATH. This is breaking a number of softwares including some of ours. 

some related threads
https://forums.developer.apple.com/thread/13161
https://github.com/oracle/node-oracledb/issues/231

**Comment by tsnouidui** [comment]
One solution could be to install symlinks to `/usr/local/bin`. Apple seems to want users to write to this location rather than `/usr/bin`.

**Comment by mbadams5** [comment]
@tsnouidui `/usr/local/bin

**Comment by mbadams5** [comment]
@tsnouidui `/usr/local/bin` is not always user writeable either (at least in my experience with Homebrew), however, you can `sudo chown` the folder IF you already have a `/usr/local/` folder. I am unsure if a fresh install has the `/usr/local/` folder already and if not you may need to temporarily disable SIP (involved process) to create the folder and then turn SIP back on.

**Comment by Myoldmopar** [comment]
So how are applications like CMake handling this situation.  Previously you would tell CMake to install symlinks over in wherever so they are available from command line.  Do you know if they (as one possible example) have a solution we can learn from?

**Comment by tsnouidui** [comment]
Sounds like we need to install Mac OS X 10.11 on a fresh mac and see whether `/usr/local/` exists and whether it can be used for Energyplus. My understanding is that Apple wants users to use this folder instead of `/usr/...`. I haven't tested it with Homebrew though.

**Comment by mbadams5** [comment]
@Myoldmopar [CMake appears to use `/usr/local/bin` in 3.3.0+](https://cmake.org/Bug/view.php?id=15627). As long as `/usr/local/bin` is root writeable, it should be fine to put it there. The downside is that `/usr/local/bin` is not part of the default PATH. At least I don't think so, it has been so long since i've had the default PATH.

**Comment by tsnouidui** [comment]
By the way, Yosemite doesn't seem to have `/usr/local` by default. We might have to conditionally add the link depending on the existence of the folder...

**Comment by cdcorbin** [comment]
Any update on this? I just switched to El Capitan, not realizing that EP and El Capitan don't play together. Maybe a patch?

**Comment by jmarrec** [comment]
@mbadams5 This feels pretty outdated (current is macOS High Sierra, and now there's definitely an E+ CLI), I think you should close.

**Comment by mbadams5** [comment]
@jmarrec The current is really Mojave. Anyways, I just checked and this is still valid if running `runenergyplus`. That said, it does say:

```
***** NOTE: This script is marked as deprecated as of August 2015.
*****       The functionality of this script is now in the command line interface.
*****       For information on the command line interface:
*****        - See the documentation (https://energyplus.net/documentation)
*****        - Call the application for usage: EnergyPlus --help
*****        - Refer to the man page: man EnergyPlus
*****       In a future version of EnergyPlus, this script will no longer be packaged.
```

I think with the new EPLaunch/Workflows and the CLI as well as sufficient time, I think we should not package this script with the next release. Thoughts? @Myoldmopar @mjwitte

**Comment by mjwitte** [comment]
@Myoldmopar Two more complaints about ep-launch lite (EnergyPlus v9.1.0) not working on Mac. Error is "the app cannot be opened" (or similar)
Helpdesk ticket 15136, macOS version is 10.14.4.
Ticket 15162, mocOS Sierra

We should stop packaging ep-launch lite.

**Comment by mbadams5** [comment]
@mjwitte I just tested on 10.14.4 and 9.1.0 ep-launch lite gives me the same error. However, when I tried the 9.0.1 ep-launch lite, it launches just fine (and appears to be using 9.1.0 engine).

![Screen Shot 2019-05-08 at 12 52 58 PM](https://user-images.githubusercontent.com/2001544/57393026-3af6e880-7190-11e9-87e6-d0ff20532633.png)

**Comment by mjwitte** [comment]
Interesting. So, did we change something in the 9.1.0 installer and/or 9.1.0 ep-launch lite?

**Comment by jmarrec** [comment]
@mjwitte Yes, there was some change to the installer (cf #7148), and the install directory structure changed by removing a top level. Perhaps that's why?

**Comment by mbadams5** [comment]
Related issue, #7298

**Comment by jmarrec** [comment]
There are two issues in one here, the symlinks / SIP which is the original.

The EP-Launch-Lite and IDFVersionUpdater should be tracked in #7298 and are due to the switch to QtIFW
