### ISSUE TITLE
Mixed air setpoint <0 causes 100% OA operation

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5412]
Helpdesk ticket 11038
User file with very low mixed air setpoint for economizer control, results in 100% OA, even when the outdoor air temperature is below the setpoint.
The problem is [here](https://github.com/NREL/EnergyPlus/blob/f3d31288af93cfb2dce7ca7a0aa46e6295eef0c5/src/EnergyPlus/MixedAir.cc#L3270-L3278), where the controller assumes any setpoint <= 0 is ignored.  Should be able to change this to test if > SensedNodeFlagValue, but need to check other possible uses of the setpoint to be sure.

**Comment by rraustad** [comment]
Changed to test if > SensedNodeFlagValue yet OA still at max? even when OAT < SPT towards end of this run period.

![5412](https://cloud.githubusercontent.com/assets/5778156/15732262/bf62035e-2849-11e6-9671-e2d0714c6f61.png)

**Comment by rraustad** [comment]
Wait,that's not OA, it's mixed air flow rate. Here's OA flow rate where OA < max when OAT < mixed air SP

![5412_oa](https://cloud.githubusercontent.com/assets/5778156/15732360/7f722458-284a-11e6-965c-66de8552e1fa.png)

**Comment by mjwitte** [comment]
Closed via #5703
