### ISSUE TITLE
v8.4 Documentation Missing "GroundCoupledSurface" option for Other Side Conditions Model

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#5420]
The [Ground Domain Slab](http://bigladdersoftware.com/epx/docs/8-4/input-output-reference/group-location-climate-weather-file-access.html#sitegrounddomainslab) and [Ground Domain Basement](http://bigladdersoftware.com/epx/docs/8-4/input-output-reference/group-location-climate-weather-file-access.html#sitegrounddomainbasement) are new capabilities of v8.4. Both of these objects reference a [Surface Property - Other Side Conditions Model](http://bigladdersoftware.com/epx/docs/8-4/input-output-reference/group-advanced-surface-concepts.html#surfacepropertyothersideconditionsmodel) (OSCM) object for setting temperatures of surfaces touching soil. However, the In/Out Reference documentation for this OSCM object states: The only available choices are ”GapConvectionRadiation” or “UndergroundPipingSystemSurface.” Checking the IDD file shows that there is a new third option called "GroundCoupledSurface", and comments state: "GroundCoupledSurface provides boundary conditions for surfaces in contact with GroundDomain objects". Documentation for the OSCM object should be updated to be consistent with the recently added Ground Domain objects and change to IDD file.

**Comment by Myoldmopar** [comment]
Closed via #5424
