### ISSUE TITLE
EP-Launch Lite for E+ V8.4.0 not showing proper E+ version

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#5427]
When opening EP-Launch Lite for the Mac after installing EnergyPlus Version 8.4.0, the main window that allows you to select an input file, choose a weather file, and click on simulate still says that it is running EnergyPlus Version 8.3.0.  The computer this was noted on is a MacBook Pro (Retina, Mid 2012) running OS X 10.11.2 (El Capitan).

**Comment by RKStrand** [comment]
Also discovered a couple of related issues making it seem as if EP-Launch Lite for the Mac was not updated at all for Version 8.4.  In addition to the problem initially noted above, it was also noticed that when clicking on the Input File button, that it goes to the EnergyPlus-8-3-0 folder.  A similar thing happens when trying to select the weather file.  The drop down list is based on the Weather Data folder in in EnergyPlus-8-3-0 folder.  It would be great to fix these for the current version or at a minimum make sure they are updated for the next version properly.

**Comment by Myoldmopar** [comment]
Closed via #5867
