### ISSUE TITLE
Order of input fields for Table:MultiVariableLookup in I/O doc doesn't match IDD and example files

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#5428]
Order of input fields in [I/O Reference for v8.4](http://bigladdersoftware.com/epx/docs/8-4/input-output-reference/group-performance-tables.html#tablemultivariablelookup):
Name
Curve Type
Interpolation Method
Table Data Format
Number of Interpolation Points
...

Order of input fields in v8.4 IDD and LookupTables.idf example file:
Name
Interpolation Method
Number of Interpolation Points
Curve Type
Table Data Format
...

**Comment by aaron-boranian** [comment]
Also, I/O Ref says that [options for independent variable sort order](http://bigladdersoftware.com/epx/docs/8-4/input-output-reference/group-performance-tables.html#field-x1-sort-order) are "Increasing" or "Decreasing", while IDD and LookupTables.idf example file show "Ascending" or "Descending".

**Comment by Myoldmopar** [comment]
Closed via #5574
