### ISSUE TITLE
Surface height out of range warning lacks sufficient information to correct problem.

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#5434]
User file shows a surface at 42,000 m, yet the offending surface does not have a Z vertex at this height. HelpDesk ticket 11080.

*\* Severe *\* SetOutBulbTempAt: Surface Outdoor Temperatures < -100 C
*\* ~~~ *\* ...check Surface Heights - Maximum Surface Height=[42729].
*\* ~~~ *\* ...according to your maximum Z height, your building is somewhere in the Stratosphere.

Warning message is not descriptive enough to find the offending surface. Suggest adding:
*\* ~~~ *\* ...look at Surface [2222] = Name="T3-RF1 - FLOOR:N"

Offending surface was:
    BuildingSurface:Detailed,
    T3-RF1 - Floor:n, !- Name
    Floor, !- Surface Type
    ExtSlabCarpet 4in ClimateZone 1-8, !- Construction Name
    T3-RF1, !- Zone Name
    Ground, !- Outside Boundary Condition
    , !- Outside Boundary Condition Object
    NoSun, !- Sun Exposure
    NoWind, !- Wind Exposure
    , !- View Factor to Ground
    , !- Number of Vertices
    -73.4395447868102, !- Vertex 1 X-coordinate {m}
    115.81641271866, !- Vertex 1 Y-coordinate {m}
    -4.90860981523342e-014, !- Vertex 1 Z-coordinate {m}
    -58.0249751030646, !- Vertex 2 X-coordinate {m}
    93.1706338416311, !- Vertex 2 Y-coordinate {m}
    -6.93120848813091e-014, !- Vertex 2 Z-coordinate {m}
    -68.9295447868101, !- Vertex 3 X-coordinate {m}
    74.3054685889134, !- Vertex 3 Y-coordinate {m}
    -6.06384403665968e-014, !- Vertex 3 Z-coordinate {m}
    -58.0345461881513, !- Vertex 4 X-coordinate {m}
    93.1761597101821, !- Vertex 4 Y-coordinate {m}
    -6.9300904918858e-014; !- Vertex 4 Z-coordinate {m}

**Comment by Myoldmopar** [comment]
Closed via #5438
