### ISSUE TITLE
Hailey Weather File Blank

### ISSUE THREAD

**Issue by DamonWoods** [NREL/EnergyPlus#5436]
The ddy for the Hailey-Sun Valley AP 725785 is blank. It downloads only as 1 kB and includes the longitude and lattitude but does not include any other weather information so I cannot use it to properly size the equipment for the design project in that location.

**Comment by mjwitte** [comment]
This (typically) means that location is not included in the ASHRAE handbook design data.  You either need to select a nearby location for design data or generate your own.  Stats based on the TMY3 data will not be equivalent to ASHRAE design data.
