### ISSUE TITLE
Inconsistent reference hot water temperature are used to calculate density in water flow autosize

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#5442]
While working adding unit test for #4980 , I came across a difference in water reference temperature used to calculated hot water density. In the Unit Heater parent object, the design hot water vol flow rate is calculated at 60.0C, just like the hot water Cp, but ReportSizingOutput uses, 5.05 C as the reference water temperature. And this difference in temperature leads to slight change of water mass flow rate and design coil capacity. This introduced about 1.7% difference between the Design Coil Load and the Design Coil Capacity. Shouldn't we use consistent reference temperature for sizing calculation? I went ahead checked FanCoil and Unit Ventilator objects and found out the same issue.

I am assuming that 5.05C is the reference temperature for water volume flow rate calculation. Shall I change reference water temperature used to calculated water density from 60.0C to 5.05C in the UnitHeater parent object design hot water vol flow rate calculation? @mjwitte @rraustad @Myoldmopar

@rraustad Response:
When the RequestSizing function was created, the component sizing methods were moved to a central function. At that time, the HW coil was sizing using InitConvTemp and I couldn't change it then since it would have caused diff's (I do recall seeing this). Also, we used to call CPCW and CPHW, where Cp was passed back as 4180 regardless of temperature. Now we use GetDensityGlycol (I don't recall when this was changed) and temperature does matter. So yes this should be corrected using a separate issue.

@mjwitte Response:
The change from CPCW/CPHW to GetDensityGlycol should be revisited. If a variable temp is being used, seems it should be tied to the Sizing:Plant design supply temp or the coil object Rated Inlet Water Temperature for coils that have that input, or the average of the design input/output water temps?

**Comment by Nigusse** [comment]
@mjwitte @rraustad @Myoldmopar There are three issues that I see here before I proceed forward:
- Correct the inconsistent use of 60.0C and 5.05C for hot water density calculation in autosizing hot water Volume Flow Rate.  What value should be used? should we take the value from the Sizing:Plant object or Coil:Heating:Water objects? Keep in mind that the values in these two objects can be different, which value should the precedence, the plant or the coil object? For density calculation I suggest to use an inlet condition, not an average.
-   I see consistent (in selected objects I visited) use of 60.0C for hot water the specific heat calculation for hot water coils capacity sizing even when the density is calculated at 5.05C.  Evaluation of specific heat at average of inlet and outlet temperatures is relatively correct.  Should we change the 60.0C to average of design hot water loop water temperatures, example  [= (Tin - DeltaT/2) ] for specific heat or an average of inlet and outlet as Mike suggest above?
- I suggest to limit the scope to hot water coils sizing related calculations only. Also includes hot water flow sizing in several Zone HVAC objects.

**Comment by EnergyArchmage** [comment]
I agree that we need a clear policy as to what temperature to use during sizing and initial setup.  I thought that was InitConvTemp, but it probably isn't used everywhere it should be.  I think it should be kept simple and not change with input and types of loops.

**Comment by rraustad** [comment]
InitConvTemp scares me a little for 2 reasons. One is that there should have been 2, CWInitConvTemp and HWInitConvTemp. And the other is that the use of a constant like this may get us into trouble when the simulation deviates from those temperatures. If autosized there are inputs for CW and HW temps, if not only a few objects have a temp input. Does that put us back to a global HW and CW initialization? Maybe for now only a search and replace all of InitConvTemp to CWInitConvTemp and then add HWInitConvTemp and correct where needed?

**Comment by Nigusse** [comment]
This issue was brought by observation that Hot Water Volume Flow Rate calculated at 60.0C in the parent objects is multiplied by Water Density at 5.05C (InitConvTemp) to get the Hto Water Mass Flow Rate in another place.  This in effect slightly changes the Coil Capacity used for UA-Sizing.  The simplest change than can be made is to make them consistent.

We use a standard dry air density to change user specified design volume flow rates to Dry Air Mass Flow Rate, and for this we use a constant reference 20.0C even though air density is more sensititive to temperature than water density is.  My question to you all is why not we have a fixed reference temperature for hot and chilled water that can be used just like StdRhoAir for air. Keep in mind when we allow users to specify Design Water Volume Flow Rate in [m3/s] for various objects there is an inherent assumption that the flow rate is defined at some reference temperature and pressure. Just as a thought!

**Comment by EnergyArchmage** [comment]
I also prefer a single constant reference.  I would be all in favor of changing the value of InitConvTemp from 5.05 to 20.0C, or some other number if there is a good argument.    If memory serves it matches the old 4180 specific heat. 

Remember this temperature sensitivity is a side effect of getting glycols to work everywhere, it isn't always water.

**Comment by Nigusse** [comment]
I was not aware that this temperature selection considered the side effect of getting glycols to work everywhere. May be more discussion is warranted before we make any changes.

**Comment by Myoldmopar** [comment]
Closed via #5774
