### ISSUE TITLE
IDF Editor add support for new units conversions

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5443]
Two new units conversions were added as part of the pump sizing changes in #5281 

```
!      W/(m3/s)               =>   W/(gal/min)         0.0000630902
!      W/((m3/s)-Pa)          =>   W/((gal/min)-ftH20) 0.188554
```

**Comment by mjwitte** [comment]
More new units will come in with #5468

**Comment by JasonGlazer** [comment]
@mjwitte and @Myoldmopar Are we expecting any more new features for 8.5.0 that are likely to have new unit conversions at this point?

**Comment by Myoldmopar** [comment]
I am not aware of any additional items.  Given that the IDD is essentially frozen, I think you are clear to move forward without any more coming.

**Comment by mjwitte** [comment]
Closed via https://github.com/NREL/EnergyPlusBuildSupport/pull/25
