### ISSUE TITLE
Wrong IP units for controllerWaterCoil min/max flow and other water flow rate fields

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#5452]
`Controller:WaterCoil` takes a Minimum Actuated Flow and a Maximum Actuated Flow. As seen in the [docs](http://bigladdersoftware.com/epx/docs/8-4/input-output-reference/group-controllers.html#field-maximum-actuated-flow), 

> **Field: Maximum Actuated Flow**
> This is the maximum water flow (m3/sec) through the coil. Set to the maximum design water flow for the coil.

But the IDF editor will show ft^3/min.

originally posted here before I knew it was an E+ rather an OS issue.
https://github.com/NREL/OpenStudio/issues/2057#issuecomment-178608001

**Comment by mjwitte** [comment]
The default ip units for m3/sec is ft3/min  Will add  \ip-units gal/min for these fields.  Searching the IDD for "water flow rate" reveals many other fields that should also be  \ip-units gal/min

**Comment by MatthewSteen** [comment]
@mjwitte didn't see your comment. Will finish this up.

**Comment by mjwitte** [comment]
Closed via #5468
