### ISSUE TITLE
Allow opening IDF files with unix line endings in IDFEditor on Windows

### ISSUE THREAD

**Issue by jamiebull1** [NREL/EnergyPlus#5453]
This has come about as an issue raised for Eppy which I think makes more sense to be dealt with in the IDFEditor code. The issue is that when an IDF is created in Eppy or in a text editor on Mac or Linux, then by default the IDF is created with that system's line endings. If we then try to open the file in IDFEditor on Windows it fails with an error message to convert the line endings to CR LF. Most text editors and even command line tools on Windows will handle unix line endings nowadays, either silently or by prompting the user to change the endings, so it seems to me that IDFEditor could/should do so too.

**Comment by mjwitte** [comment]
Closed via https://github.com/NREL/EnergyPlusBuildSupport/pull/25
