### ISSUE TITLE
Add auto-sizing capability for Nominal Air Flow Rate and Nominal Air Face Velocity in Desiccant BalancedFlow Performance DataType1 object

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#5465]
#4904

Nigusse:
While working on Idd update, I see two input fields "Nominal Air Flow Rate" and "Nominal Air Face Velocity" in the "HeatExchanger:Desiccant:BalancedFlow:PerformanceDataType1" object as autosizable. But the code does not support and it fatal out. So I am removing them.

MJW:
@Nigusse Our goal is for everything to be autosizable, so please post a new issue for the broken autosizable fields, or expand the scope of this issue.

**Comment by rraustad** [comment]
Closed via #5743.
