### ISSUE TITLE
User file with zone and system ERV crashes

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5476]
Helpdesk ticket 11114
I had this issue running Open Studio: when adding a ERV HX at system level, I didn't delete the ERV at the zone level, and that running failed, with the energyplus.err file doesn't even show error message. So I check the IDF and see the energyplus crashed, with screenshot and IDF attached.

**Comment by AryaInTheAir** [comment]
Thanks for posting it!

**Comment by Myoldmopar** [comment]
Closed via #5554
