### ISSUE TITLE
Provide addition explanation to input contaminant generation rate in IO Ref

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#5480]
Helpdesk ticket 11110: Zone contaminant generation rate
One of our users is asking about how to enter contaminant flow rate into a zone. The data is ZoneContaminantSourceAndSink:Generic:Constant > Design Generation Rate {m3/s}. He isn't clear how to convert from µg/s to m3/s.

 In his words:

 "The contaminant is tetrachlorethylene coming from the soil (a contaminant used in the drycleaning industry). I have a contaminant rate in µg/s from air tests that are been done before. I can recalculate that to a rate in m³/s, using the density of the substance, but this gives me a very low value. I also got an answer from the E+ forum and someone told me I should fill in the _equivalent air_ rate (in m³/s), using the density of air, which gives me a more "correct" value, but i don't get the logic about this."

Mike suggested to add additional explanation how to input the generation rate correctly.

**Comment by mjwitte** [comment]
Closed via #5492
