### ISSUE TITLE
Coil:Cooling:DX:MultiSpeed reporting incorrect fuel type inside AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed

### ISSUE THREAD

**Issue by asparke2** [NREL/EnergyPlus#5481]
@khaddad from Natural Resources Canada reported this:

When there is a `Coil:Cooling:DX:MultiSpeed` inside of an`AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed`, the cooling fuel consumption is being reported as NaturalGas rather than Electricity.

![coolingfuel](https://cloud.githubusercontent.com/assets/2009290/12991620/27ee825a-d0cd-11e5-8726-e2e998914486.PNG)

The example IDF is attached below.

[natural_gas_dx_hp.idf.txt](https://github.com/NREL/EnergyPlus/files/127139/natural_gas_dx_hp.idf.txt)

**Comment by mjwitte** [comment]
The coil has an input for fuel type, which defaults to NaturalGas (long story, but this was originally developed to model gas engine-driven heat pumps).  The field says NaturalGas in the attached idf.

```
Coil:Cooling:DX:MultiSpeed,
  Coil Cooling DX Multi Speed 2 46kBtu/hr 10EER, !- Name
  ,                                       !- Availability Schedule Name
  Node 36,                                !- Air Inlet Node Name
  Thermal Zone 1 ASHP Cool Coil Outlet,   !- Air Outlet Node Name
  ,                                       !- Condenser Air Inlet Node Name
  AirCooled,                              !- Condenser Type
  ,                                       !- Supply Water Storage Tank Name
  ,                                       !- Condensate Collection Water Storage Tank Name
  No,                                     !- Apply Part Load Fraction to Speeds Greater than 1
  No,                                     !- Apply Latent Degradation to Speeds Greater than 1
  0,                                      !- Crankcase Heater Capacity {W}
  10,                                     !- Maximum Outdoor Dry-Bulb Temperature for Crankcase Heater Operation {C}
  0,                                      !- Basin Heater Capacity {W/K}
  2,                                      !- Basin Heater Setpoint Temperature {C}
  ,                                       !- Basin Heater Operating Schedule Name
  NaturalGas,                             !- Fuel Type
```

**Comment by asparke2** [comment]
@mjwitte sorry to waste your time, I should have noticed that.  Good to know about the natural gas heat pumps though!  I was trying to model those recently.

**Comment by mjwitte** [comment]
@asparke2 No problem.  There's actually an open issue #4851 related to this, because the NaturalGas default is especially confusing is the field is left blank.
