### ISSUE TITLE
Expand Venting Availability to cover venting controls of ASHRAE55Adaptive and CEN15251Adaptive

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#5490]
Ticket 11125
User: I realized that, if in AirflowNetwork:MultiZone:Zone object the Ventilation Control Mode is set to CEN15251Adaptive, the Venting Availability Schedule has no impact on window openings, as opposed to I/O reference explanation.

Action:
The Venting Availability Schedule only works with 3 choices of Ventilation Control Mode: Temperature, Enthalpy, and Constant. The other two choices, ASHRAE55Adaptive and CEN15251Adaptive, are bypassed. The Venting Availability Schedule should cover all 5 choices.

**Comment by mjwitte** [comment]
Closed via #5658
