### ISSUE TITLE
DOAS inputs not autosizable

### ISSUE THREAD

**Issue by wfbuhl** [NREL/EnergyPlus#5491]
The Sizing:Zone DOAS inputs "Dedicated Outdoor Air Low Setpoint Temperature for Design" and "Dedicated Outdoor Air High Setpoint Temperature for Design" are denoted \autosizable in the IDD but are not autosized in the code. The intent was to auto-default them according to the DOAS strategy. Also the example inputs 5ZoneFanCoilDOASCool and 5ZoneFanCoilDOASCool_ERVOnAirLoopMainBranch have incorrect field names for these inputs: Outside instead of Outdoor.

**Comment by mjwitte** [comment]
@wfbuhl Are you able to address this for v8.5.0?

**Comment by wfbuhl** [comment]
No problem

**Comment by wfbuhl** [comment]
This is addressed in branch issue5491. The Sizing:Zone DOAS inputs are now autosized, and the inputs are echoed on the eio file.

But then there is the issue - what about SQL and tabular reports. The thing is, Sizing:Zone inputs are not reported on eio, SQL, or tabular. So this DOAS echo is new thing (occurring only when "account for DOAS" is yes.) I am not competent to add this to SQL. If it is to be added, we should really report out the Sizing:Zone and Sizing:Systems inputs. This would be more than a bug fix.

So ... this issue is dealt with. Will ignoring SQL etc. mess up other folks? Does it break our philosophy?

**Comment by Myoldmopar** [comment]
Closed via #5557
