### ISSUE TITLE
Image problem in IORef

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5494]
Trying to build the latest docs from develop today and it issued an error that it couldn't find `image7466.png`.  Not sure what happened along the way.

**Comment by Myoldmopar** [comment]
Welp, I saw [this](https://github.com/NREL/EnergyPlus/commit/93ec19777214586fb519d27d89ab231d0e72a683#diff-1d2e3d718cfd7cf9635d3d02efce004eR8391) back in the PR, but assumed it was intentional.  I'm guessing it wasn't..... @rglazer2 ?

Looks like it just needs to be put back to `image282.png`.

**Comment by rglazer2** [comment]
@Myoldmopar Yes, I believe that was a mistake. Sorry about that.
