### ISSUE TITLE
User file not calculating zone volumes correctly

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5501]
Helpdesk ticket 11140
User expected similar loads from four similar zones, but they varied signficantly.  The four zones have similar floor area and the same ceiling height but greatly different zone volumes:

![image](https://cloud.githubusercontent.com/assets/4991075/13236166/5aa0737a-d988-11e5-8d5e-975485bdd074.png)

The difference in volumes cause the infiltration and ventilation flows to be different, because both were specified in ACH.

Workaround is to put hard values for Volume in the Zone objects.

**Comment by mitchute** [comment]
@Myoldmopar I had a minute to look at this.

The volume is being calculated incorrectly by [CalcPolyhedronVolume](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SurfaceGeometry.cc#L8110). 

The building from the user's file is shown here.
![capture](https://cloud.githubusercontent.com/assets/2985979/13475340/df1fec06-e087-11e5-8490-ea984c3b50cb.PNG)

I'm not seeing anything that is immediately apparent that is wrong. Are there some assumptions, like the zone be convex, for `CalcPolyhedronVolume` to give accurate results? Either way, at the very least, I don't see how the the minimum volume limit is being enforced. It looks to me like `CalcVolume` always comes out of `CalcPolyhedronVolume` with a non-zero value. Cleaning up [this if statement](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SurfaceGeometry.cc#L8124) could at least clear up that problem. As far as `CalcPolyhedronVolume` over predicting volumes, I am going to need to dig in and understand the background on when the method `CalcPolyhedronVolume` uses is valid.

**Comment by JasonGlazer** [comment]
Updated defect file to EnergyPlus 8.6 in DevSupport repo, defect still present.

**Comment by Myoldmopar** [comment]
Closed via #6056
