### ISSUE TITLE
E+ does not comply with Ashrae App G G.3.1.14: Shading by adjacent structures without self-shading is not possible

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#5514]
## Issue overview

As E+ being one of the main simulation programs for LEED, it is an issue that it does not comply with Ashrae 90.1-2010 App G G.3.1.14. That provision states that proposed and baseline building have to include shading by adjacent structures. However, baseline also requires that self-shading or attached shading must be removed.

There should be a shadowing mode that allows detached shading without self-shading to meet Ashae requirements.
Just an option to remove self-shading will suffice (the user can remove shading surfaces manually for baseline building).

**Comment by MatthewSteen** [comment]
I don't personally see this as an issue. Automating the PRM for LEED or other programs is not a focus of EP, which currently only does baseline orientations. Instead this task should be left to the software that uses EP. 

For example, this can be done easily in OpenStudio. Attached shading is translated to `Shading:Zone:Detailed` objects and detached shading is translated to `Shading:Building:Detailed` objects, which can be removed before or after translation with either an OpenStudio measure or EnergyPlus measure.

**Comment by ecoeficiente** [comment]
Matthew, I'm afraid it is not a matter of automating, it is a matter of imposibility.

For the baseline building, LEED requires that the building does not shade itself but it has to be shaded by adjacent structures. **You cannot achieve that by any GUI or Openstudio measure**.

It is in the core of EnergyPlus code. If you want to remove self-shading (only possible with Solar Distribution: MinimalShadowing) you cannot have any external shading.

**Comment by amirroth** [comment]
I agree with @ecoeficiente. This has come up before and the determination then was that this had to be done by shutting off certain parts of the calculations from within. There were not available resources to do this, and the stance I adopted was that there are other things that LEED could implicitly incentivize that would be more impactful and easier to model. I maintain that stance, although the resource situation is somewhat better now and I could put aside my personal convictions.

**Comment by mattdoiron** [comment]
I've wondered about this situation as well and the best approximation that I have used for a reference building is to delete shading objects and set "Solar Distribution" to "MinimalShadowing" in the "Building" object. Then in the proposed building there are shading objects while the "SolarDistribution" is set to something more detailed like "FullInteriorAndExterior". Overall, I feel that this issue should not cause large differences in the modelling results, but it depends on how complicated the geometry is and also how strict the authority having jurisdiction is on the rules.

**Comment by ecoeficiente** [comment]
The safest bet is to remove adjacent external shading from both Proposed and Baseline.
@amirroth, as an energy modeller I try to follow LEED requirements as close as I can to avoid problems, even though I totally agree with your view about LEED priorities.

I hope you can get the resources to solve this in a near future.

**Comment by JasonGlazer** [comment]
In my opinion the intention of not allowing self-shading of the building surfaces in Table G3.1 part 5 under "a. orientation" is to incentivize building shapes that provide some self shading. This can be a significant incentive for some buildings that have L or U floorplates but will have no affect on many more commonly rectangular shaped buildings. It would be good if EnergyPlus could accomplish this and at the same time be able to shade from adjacent structures and topology which is included in the baseline and proposed to be fair to buildings in densely urban environment or in mountainous regions. Maybe this should be added as a [uservoice ](https://energyplus.uservoice.com/forums/258860-energyplus) suggestion. 

I should add that while I am the chair of 90.1 ECB subcommittee this should not be considered an official interpretation but rather just a personal opinion.

**Comment by mjwitte** [comment]
This will be available as a new feature in v8.9.0 See #6390

**Comment by aaron-boranian** [comment]
**Add option to disable self-shading**

LEED grants credit for self-shading, but to obtain this credit you need to model a baseline building that is shaded by adjacent structures, but not by itself (if I interpret correctly)! It doesn’t seem possible to back out this data point using multiple runs, rather direct switch inside EnergyPlus is needed. Here is a relevant unmethours discussion. 

https://unmethours.com/question/3871/shading-by-adjacent-structures-not-possible-in-leed-baseline-and-e/

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/14467461) feedback from @amirroth
