### ISSUE TITLE
Incorrectly Documented VRF "Minimum/Maximum OAT in Heating/Cooling Mode"

### ISSUE THREAD

**Issue by mattdoiron** [NREL/EnergyPlus#5515]
## Issue overview

The AirConditioner:VariableRefrigerantFlow object has a set of fields called “Minimum/Maximum Outdoor Temperature in Heating/Cooling Mode” which act as expected when the “Condenser Type” is set to AirCooled. However, from our testing, when the “Condenser Type” is WaterCooled, these fields appear to actually reference the water loop temperatures, not outdoor air temperatures. This makes sense, but is not documented. I would suggest that the “outdoor temperature” term be replaced with “source temperature” and the documentation be updated to make clear the difference in behaviour between air- and water-cooled modes.
### Details
- Documentation update for object: AirConditioner:VariableRefrigerantFlow
- Windows 7, EnergyPlus v8.4 Update 1

**Comment by mjwitte** [comment]
@rraustad Perhaps you can add this doc fix to #5537

**Comment by rraustad** [comment]
Will do.

**Comment by rraustad** [comment]
Sitting on my local #5536 branch. 4 places similar to:

#### Field: Minimum Outdoor Temperature in Cooling Mode

This numeric field defines the minimum source temperature allowed for cooling operation. For air-cooled equipment outdoor dry-bulb temperature is used. For water-cooled equipment inlet water temperature is used. Below this temperature, cooling is disabled. If this field is left blank, the default value is -6ºC.

**Comment by rraustad** [comment]
Closed via #5536 by incorporating this fix within #5537. See commit [here](https://github.com/NREL/EnergyPlus/commit/1131b7830b60ed1b8bac5ff3b966d7411bea4086)
