### ISSUE TITLE
Heat recovery from multi-speed dx coil does not appear to balance with water heater source energy

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5516]
## Issue overview

Noticed while reviewing #5471 that DXAC HEAT PUMP 1:Unitary System Heat Recovery Rate [W] is significantly higher than BIG WATER HEATER:Water Heater Source Side Heat Transfer Rate [W].  Expected these to be the same (plus pump heat) since these are the only two components on the heat recovery loop in this test file.
### Checklist
- [x] [Defect file](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5516) added
- [x] Ticket added to Pivotal for defect (development team task)
- [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
See PR https://github.com/NREL/EnergyPlus/pull/5724

**Comment by mjwitte** [comment]
@rraustad As we discussed on the call, perhaps this is impacted by #4188?

**Comment by Myoldmopar** [comment]
Closed via #5724
