### ISSUE TITLE
ZoneHVAC:OutdoorAirUnit reported fan power and energy includes only one fan

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5524]
The ZoneHVAC:OutdoorAirUnit has its own reports for fan power and energy.  From code inspection (while working on new fan model) it was noticed that the fan power is not correct when there is both a supply and an exhaust fan.  The problem is the global DataHVACGlobals::FanElecPower is only going to hold the power for the last fan simulated.  But if there are two fans the this line cannot be correct.  

`OutAirUnit( OAUnitNum ).ElecFanRate = FanElecPower`

When there is one fan, the unit's fan power/energy will be for the supply fan, but if there is also an exhaust fan the unit's fan power/energy will be for the exhuast fan.  It would seem that the unit should report the total fan power/energy for both fans. 

The existing test suite file OutdoorAirUnit.idf shows the problem, so no additional defect file. 

Compare  output variable "Fan Electric Power" for the fans Zone5OAUFan1 and Zone5OAUExhaustFan1 to the output variable Zone Outdoor Air Unit Fan Electric Power for OA unit called Zone5DXOutAir.

**Comment by rraustad** [comment]
All zone OA units now show agreement with specific fan power reports. Here's one example that's not a constant (e.g., Zone 5 shows 63 W + 63 W all day long).

![outdoorairunit](https://cloud.githubusercontent.com/assets/5778156/15834172/1b17c682-2bf8-11e6-9910-5d0a1d6d5d9e.png)

**Comment by rraustad** [comment]
PR #5715

**Comment by rraustad** [comment]
Defect file 5524-OutdoorAirUnit added to DevSupport.

**Comment by mjwitte** [comment]
Closed via #5715
