### ISSUE TITLE
EnergyPlus taking too long to compile in release mode

### ISSUE THREAD

**Issue by RehanKhalid** [NREL/EnergyPlus#5530]
Hi,
I am using Visual Studio 2015 to make changes to EP source code. Basically I want to add two actuators  to modify the behavior of the object ITEquipment:AirCooled. 
However, after adding the code, EP is not compiling in release mode. It does not produce any errors or warnings but takes forever to compile. It compiles in 25 minutes in debug mode but I ran it for more than 2 hours in release mode and it just won't finish compiling. It gets through all the library files but then gets stuck.

Please can anyone help me resolve these issues:
a) Help me to get it to compile in the least possible time.
b) explain what to do after it compiles. The exe file (energyplus.exe) created after the run in debug mode does not work.

I don't know how to proceed from here. Can someone please help ! I would really appreciate it.
### Details

OS: Windows 10; 
Visual Studio Express 2015
EnergyPlus repository downloaded from github.com/nrel/energyplus
EnergyPlus v8.4 currently installed.

**Comment by mjwitte** [comment]
I will answer briefly here - but help questions like this belong in unmethours.com or energyplus.helpserve.com VS2015 is very slow for release builds, takes about 2.5 hrs on my machine, with the vast majority of the time spent in linking so it looks like nothing is happening, but it will eventually complete.  The exe requires energyplusapi.dll and energyplusapi.lib.
