### ISSUE TITLE
Latex is a security risk

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#5541]
## Issue overview

The introduction of https://github.com/NREL/EnergyPlus/tree/LaTeXDummy poses a grave security threat to our faithful CI Robots. Marvin in particular is concerned. You see Latex is a programming language and therefore susceptible to code injections that may execute arbitrary files.

Recommend going back to the Microsoft Word safe zone before it's too late.
### Details

https://0day.work/hacking-with-latex/

**Comment by Myoldmopar** [comment]
Word safe zone...lol!  

So what would you suggest?  Disabling outside pull requests for now?  

Personally, I wish this issue would have come from Marvin himself...

**Comment by kbenne** [comment]
Marvin is busy dodging bullets and fending off evil doers. He'll chime in as time allows.
