### ISSUE TITLE
Fully autosized version of 5ZoneWLHPPlantLoopTower hangs

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5544]
## Issue overview

Followup from #5159 5ZoneWLHPPlantLoopTower and 5ZoneWaterLoopHeatPump were exhibiting max iteration problems due to a mix of inconsistent hard sizes and autosizing.  Initial attempt to fix this was to fully autosize the simulation, but it hangs during the first warmup day of the primary simulation.
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- pre-8.5.0 ffaabe11cd
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (DefectFiles\5544)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
InitialQLoad is jumping from 25262 to 25474 and never converges. Why is the initial load changing in an iteration loop?

![wlhpiterationloop](https://cloud.githubusercontent.com/assets/5778156/14047783/4731c44a-f280-11e5-969b-dd1742102a91.png)

**Comment by rraustad** [comment]
I see now, this did the trick. Needs to be done in 2 places I see so far. Runs much faster than usual now.

![wlhpiterationloop2](https://cloud.githubusercontent.com/assets/5778156/14048221/400ed2e0-f283-11e5-892a-964d6eb8c8a6.png)

**Comment by rraustad** [comment]
@EnergyArchmage this loop was bouncing back and forth and never converging. This fix corrected the problem but I am wondering if there is a better numerical method.

**Comment by EnergyArchmage** [comment]
I don't have any better idea than this changing of the relaxation.  This routine is challenging.  

It might be good to add report variables for the different iteration loops to start to get a feel for how many iterations are usual.  Those stops at 100,000 are scary and why this model goes into almost-infinite loop.

**Comment by rraustad** [comment]
Reminder for changes.
1) add iteration reporting to see what this model typically needs
2) inside loop should remain as Relax=0.5 since QLoadTotal doesn't change there. This makes this a half-step loop. I wish I could change this to RegulaFalsi but can't think of how.
3) outside loop should use decrementing relaxation factor in increasing iterations. Try to get as low as possible >2 (i.e., half-step will get fairly close in 3 iterations),4,6,8,10 (instead of 20,30,40,50,60)? Need something more relaxed than that?

**Comment by lgu1234** [comment]
@EnergyArchmage I think RelaxParam may be an output of a linear curve object with NumIteration3 as an independent variable, so that a user may have a chance to make any changes from inputs.

**Comment by rraustad** [comment]
branch 5544 started to address this issue

**Comment by rraustad** [comment]
see PR #5590

**Comment by Myoldmopar** [comment]
Fixed via #5590
