### ISSUE TITLE
Change in "Date/Time Of Peak" column in Zone Sensible Cooling and Heating Tables

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/EnergyPlus#5551]
## Issue overview

Previously the column header was "Date/Time Of Peak".
Now it is "Date/Time Of Peak {TIMESTAMP}"
### Details

This affects the query for tabular data for that column. If it were done as a unit [TIMESAMP] other columns then it wouldn't impact the query. But as it is, the query fails to find any results.

@Myoldmopar here is an example query that now fails to return anything.
SELECT Value FROM tabulardatawithstrings WHERE ReportName='HVACSizingSummary' and TableName='Zone Sensible Cooling' and RowName= 'THERMAL ZONE 1' and ColumnName= 'Date/Time Of Peak'
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by DavidGoldwasser** [comment]
@evanweaver and @macumber, it looks like this was by design in this pull request
https://github.com/NREL/EnergyPlus/pull/5295

@asparke2 and @rHorsey this link shows affected tables
https://github.com/NREL/EnergyPlus/blob/develop/src/Transition/OutputRulesFiles/OutputChanges8-4-0-to-8-5-0.md#timestamp-tag-added-to-tabular-headers

Since this includes Energy Meter Tables, wasn't sure if it would impact calibration or other reports.

It does sound like this should be closed here, and issues opened in OpenStudio to update affected sql queries. Sound good @macumber and @Myoldmopar

**Comment by Myoldmopar** [comment]
Yeah.

**Comment by macumber** [comment]
In that case, can we modify the measure so it will work?

**Comment by DavidGoldwasser** [comment]
@macumber I confirmed that just adding the tag the query works, so I'll fix that in OS tomorrow.

**Comment by brianlball** [comment]
does this effect the Calibration report?
