### ISSUE TITLE
Add LEED reporting of peak end use and EFLH

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5559]
Add to the LEED report, the peak demand for each end use. It already reports it at the building peak but not individual peak. Also add the equivalent full load hours (EFLH) for each end use and the total peak by dividing the energy consumption by the individual peak. 

See helpdesk #9676

**Comment by MatthewSteen** [comment]
#4588

**Comment by mjwitte** [comment]
Closed via #5672
