### ISSUE TITLE
Add specific option for showing Tariff reports

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5562]
Add a specific option to show or hide the Tariff reports. Currently The Economics Results Summary Report and the Tariff report appear if one or more UtilityCost:Tariff objects are in the file. Add specific control to show the Tariff report or not. See

https://unmethours.com/question/15790/tariff-report-in-e/

**Comment by JasonGlazer** [comment]
@mjwitte I am planning on adding three new options to display the Output:Table:SummaryReports for the Tariff Report, Economics Results Summary Report, and Life-Cycle Cost Report. I believe those are currently the only three reports that just appear without being specifically requested. They currently appear when tariff or lifecycle cost objects appear. I am making the change requested by a user to have them appear only when specifically requested. Of course they will also appear when AllSummary\* options are used which is what almost everyone uses anyway. This make sense now that costs appear in the LEED Report so people who just want the LEED report won't see all the tariff related reports. It is slight expansion of the scope of this bug but it makes sense to do them all together.

**Comment by mjwitte** [comment]
Closed via #5598
