### ISSUE TITLE
RunMultiDir.bat still refers to version 7-1-0

### ISSUE THREAD

**Issue by JanRaets** [NREL/EnergyPlus#5589]
## Issue overview

The RunMultiDir.bat file has it's maindir location hardcoded to:
: maindir - change if you did not install in default folder (to be safe, use quotes)
SET maindir="C:\EnergyPlusV7-1-0\"

Which should be updated to the appropriate version number for the release (in case of 8.5):
: maindir - change if you did not install in default folder (to be safe, use quotes)
SET maindir="C:\EnergyPlusV8-5-0\"
### Details

Windows 64-bit (WIndows 10)
EnergyPlus 8.2+

**Comment by mjwitte** [comment]
Rather than change this for each release, perhaps it should be blank and a check added to throw an error stating it needs to be set, and then quit.  Unless @Myoldmopar has a better suggestion.

**Comment by JasonGlazer** [comment]
Another option is to have the installer set an environmental variable that pointed to the install directory. That would solve the issue especially because the installer could do that automatically. What do you think @kbenne

**Comment by Myoldmopar** [comment]
@JasonGlazer it could be done by the installer, but I'd have to look up how the installer does configuration; I'm not sure if our installer actually does it now or not.  It would be simpler to add a configure step during compile time and point to the default install for the current version.  Not as fancy as the install configure step, but would probably cover 99% of users.

**Comment by JasonGlazer** [comment]
I ended up just putting a clear warning when running the batch file and removing any specific version number.

**Comment by JasonGlazer** [comment]
See:
https://github.com/NREL/EnergyPlusBuildSupport/pull/28/files

**Comment by Myoldmopar** [comment]
OK, that's a fine solution, and the changes to the script and the documentation look good.  I will merge if nothing remains to be done here.

**Comment by JasonGlazer** [comment]
I think we are done.

**Comment by Myoldmopar** [comment]
Closed via #5645
