### ISSUE TITLE
Remove deprecated Branch Maximum Flow Rate field

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5600]
## Issue overview

This is a follow-up to #5582 which deprecated the Branch object Maximum Flow Rate field.  The field is still in the IDD, so _when the time is right_, this issue will 
- [ ] Remove the field from the IDD
- [ ] Add the transition rule.
- [ ] Remove the field as needed in expandobjects
- [ ] Update (nearly all) the test files
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (list location of defect file here) - N/A
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #5575
