### ISSUE TITLE
Inconsistent cooling coil 'heat exchanger configuration' default between documentation and idd

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#5601]
## Issue overview

For Coil:Cooling:Water, Engineering reference [states](http://bigladdersoftware.com/epx/docs/8-4/input-output-reference/group-heating-and-cooling-coils.html#field-heat-exchanger-configuration): "Air-conditioning systems generally use cross flow heat exchangers, hence the default is set to cross flow." However, the idd has:

  A8 , \field Heat Exchanger Configuration
       \type choice
       \key CrossFlow
       \key CounterFlow
       \default CounterFlow

Note: changed this in OpenStudio with blessing from @kbenne https://github.com/NREL/OpenStudio/pull/2189.
### Details

Some additional details for this issue (if relevant):
- Platform (all)
- Version of EnergyPlus (if using an intermediate build, include SHA)
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@eringold @kbenne I've been told that CounterFlow is the more common configuration. So, it seems the default is good, but the docs should change.  This [reference](http://www.capitalcoil.com/coilsandcounter-flow5-common-questions-that-people-have-about-coils/) was cited.

Pasting here for perpetuity . . . 
HomeCapital Coil & Air: Knowledge LibraryCoils and Counter-flow: 5 Common Questions
COILS AND COUNTER-FLOW: 5 COMMON QUESTIONS
by Dan Jacobs, July 10, 2017

1)  COILS AND COUNTER-FLOW?
The first thing to remember about coils and counter-flow is that chilled water coils are always built to be piped in counter-flow. This means that the air flows in the opposite direction as the water. For example, with counter-flow, the air flows through rows 1-8, while the water runs through rows 8-1. Water always travels through the coil in the opposite direction of the air; hence the term “counter-flow.”  Direct Expansion Coils (Evaporator Coils) are also piped in the same manner.

**Comment by eringold** [comment]
Thanks @mjwitte, I wasn't aware of that.

Up to you whether to revert that PR, @kbenne.

**Comment by Myoldmopar** [comment]
Closed via #6951
