### ISSUE TITLE
LEED EAp2-4/5 Table in JtoKWH not converted properly

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5602]
The LEED EAp2-4/5 Table when using OutputControl:Table:Style set to JtoKWH, Electric Energy Use column as well as other columns are shown in GJ instead of kWH. Using EnergyPlus 8.5.0
- [x] Defect file added ([5602](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5602))
- [x] Ticket added to Pivotal for defect (development team task)
- [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

Originally reported for EnergyPlus 8.5.0 helpdesk ticket 11270

**Comment by Myoldmopar** [comment]
Closed via #5616
