### ISSUE TITLE
LaTeX documentation page numbers for objects in TOC do not correspond with document.

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#5608]
This is happening in the I/O ref and Eng. ref. I have not checked other docs.

**Comment by Myoldmopar** [comment]
Do the links go to the right spot?

**Comment by mitchute** [comment]
Yes, the links are good. The page numbers are not correct, though.

**Comment by Myoldmopar** [comment]
Weird.  OK.  And this is in the release versions of 8.5.0? 

@nealkruis @michael-okeefe @matthew-larson any thoughts?  I hadn't noticed this.

**Comment by mitchute** [comment]
Yes. 8.5.0. I just re-installed it again, just to make sure.

**Comment by michael-okeefe** [comment]
@Myoldmopar No, We hadn't noticed this either. @mitchute , Good catch.

We have a simpler build system that we're using in-house (Rake vs CMake). We had been building with 2 repetitions and I didn't see the issue in Engineering Reference but did see it in IO Ref. I just rebuilt with the number of repetitions set to 3 -- that fixes the issue across the board.

Can you set the number of build repetitions (i.e., the number of times xelatex is run over the source) to 3 in CMake? That should fix the issue. It looks like you need to add another repetition under the following line:

https://github.com/NREL/EnergyPlus/blob/develop/cmake/BuildDocumentation.cmake#L11

We should also be sure to check that the execute_process command from CMake is not cleaning out the *.aux, *.log, *.toc, etc. files generated by xelatex between runs. If it is, then we aren't making progress with each extra run.

Feel free to follow up directly via phone or email if you need anything else.

Cheers.

**Comment by michael-okeefe** [comment]
Note: it looks like from the CMake documentation that we can add more than one command within a single execute_process call:

https://cmake.org/cmake/help/v3.0/command/execute_process.html

Maybe we should change the BuildDocumentation.cmake to be:

execute_process(
  COMMAND ${XELATEX} -interaction=nonstopmode ${INNAME}.tex 
  COMMAND ${XELATEX} -interaction=nonstopmode ${INNAME}.tex 
  COMMAND ${XELATEX} -interaction=nonstopmode ${INNAME}.tex 
)

Not sure if it makes a difference vs three separate calls to execute_process...

**Comment by Myoldmopar** [comment]
I can add a third run there.

**Comment by Myoldmopar** [comment]
And don't worry, the execute process command is only doing exactly what we tell it to do, which is to run xelatex in that folder...nothing else.
