### ISSUE TITLE
Typo in No Mass Material name

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#5619]
In the ASHRAE_2005_HOF_Materials.idf data set, there is a Material:NoMass object named 
"Cement Pla**C**ter: Sand aggregate - 20mm", which should be fixed to be 
"Cement Pla**S**ter: Sand aggregate - 20mm".

**Comment by jmarrec** [comment]
Already fixed, see https://github.com/NREL/EnergyPlus/blob/develop/datasets/ASHRAE_2005_HOF_Materials.idf#L1922
