### ISSUE TITLE
ConvertESOMTR invalid dictionary line/infinite loop

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5623]
The defect file when run in EnergyPlus 8.3 with the Convert ESO/MTR to IP Units option checked in EP-Launch stops execution with "invalid dictionary line" message and may be going into an infinite loop with an ESO file that is 400MB with one line being repeated over and over:

2395,9,Carbon Equivalent:Facility [lb] !Monthly [Value,Min,Day,Hour,Minute,Max,Day,Hour,Minute]
- [x] Defect file [added ](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5623)
- [x] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@JasonGlazer Another user ran into this same issue, so I've upped the priority.  The defect file fails in EnergyPlus with a fatal error which then leads ConvertESOMTR to go into an infinite loop with the same message as indicated above.  This defect file has been added to the 5623 folder.

**Comment by mjwitte** [comment]
Closed via #5902
