### ISSUE TITLE
Equation number references missing in engineering documentation

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#5625]
## Issue overview

When I build the engineering documentation from the latex sources the equation numbers are missing. [Looking at the source](https://github.com/NREL/EnergyPlus/blob/6b851a070e0bff24c2f1e7c2d261365c13d3101f/doc/engineering-reference/src/integrated-solution-manager/basis-for-the-zone-and-air-system-integration.tex#L62), the references do not exist to the equations. Looking back to the [markdown docs](https://github.com/NREL/EnergyPlus/blob/79b6d8e7119012f2396bbcdc9c5f801d290d6e8c/doc/src/docs/EngineeringReference/02-IntegratedSolution.md), it looks like the equation number references never made it over from the original word docs. At this point, it's probably going to have to be a pretty manual process to update all those since the information was lost.
### Details

Some additional details for this issue (if relevant):
- Platform: all
- Version of EnergyPlus: f13eaeaef69a3812a37f4281cb282b2b665fe217
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Add equation references to engineering docs
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by EnergyArchmage** [comment]
Might be something about your system, I get all kinds of equation numbers when I build the engineering reference.

**Comment by eringold** [comment]
+1 
![doc](https://cloud.githubusercontent.com/assets/10799524/14749048/75df7aa2-087a-11e6-8382-b56512d87359.png)

**Comment by nmerket** [comment]
The title of the issue wasn't entirely clear. I changed it. The problem I'm having is that the _references_ to the equations in the text have all disappeared since the migration from Word. For example:

> This manipulation resulted in Equation , the formula for updating the zone mean air temperature:

The numbers on the equations themselves are there when the latex is rendered as a PDF, but the references to them were lost. They were also missing from the Markdown docs.

**Comment by EnergyArchmage** [comment]
Oh right, sorry.  Alternatively, the task here is to rewrite these old sections so that they no longer try to make such direct references to equations.  Maintaining those is big effort and I think it might have been intentionally abandoned.

**Comment by nmerket** [comment]
I went back and dug up the old word documents from the Build Support repo because I found that I needed the equation references to understand what was going on. We should keep them. Latex is certainly capable of doing that. It's just going to be tedious finding them all.

**Comment by Myoldmopar** [comment]
Closed via #7337
