### ISSUE TITLE
Heat Pump Water Heater DX coil model does not reliably find the evaporator fan

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5630]
## Issue overview

When the Coil:WaterHeating:AirToWaterHeatPump:Pumped object sets the Evaporator Fan Power Included in Rated COP to yes, the fan heat should add to the rated capacity.  Noticed that the method for finding the fan for HPWH DX heating coil does not work for heat pump water heaters.  The fan search method in DXCoil.cc is looking on air handler branches and doesn't find the fan dangling off the evaporator of a HPWH..  Need to have the parent water heater (WaterHeater:HeatPump:PumpedCondenser) call SetDXCoolingCoilData to inform the DX coil model what fan is involved.  As things stand now the Evaporator Fan Power Included in Rated COP to yes does not work correctly in the HeatPumpWaterHeaterStratified.idf for the HPWH called ScheduledHeatPumpWaterHeater.

This was found while working to add new fan and remove FanElecPower global. Fixed in System-Fan-Model branch
### Details

Some additional details for this issue (if relevant):
- Platform (win)
- Version of EnergyPlus (if using an intermediate build, include SHA)
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (example file HeatPumpWaterHeaterStratified.idf)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
@EnergyArchmage your assigned, will you be correcting this issue?

**Comment by EnergyArchmage** [comment]
I did correct it in https://github.com/NREL/EnergyPlus/pull/5653.   Could maybe port that change over as a separate batch of changes for this issue.

**Comment by mjwitte** [comment]
Closed via #6014
