### ISSUE TITLE
WaterHeater:Stratified with HorizontalCylinder tank shape uses incorrect height to check if heaters are inside the tank

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5635]
## Issue overview

User file with this tank input

```
WaterHeater:Stratified,
    Storage Tank,            !- Name
    Water Heater,            !- End-Use Subcategory
    0.360,                       !- Tank Volume {m3}
    0.4,                !- Tank Height {m}
    HorizontalCylinder,      !- Tank Shape
    ,                        !- Tank Perimeter {m}
    100,                     !- Maximum Temperature Limit {C}
    MasterSlave,             !- Heater Priority Control
    Standard Tariff,      !- Heater 1 Setpoint Temperature Schedule Name
    8,                       !- Heater 1 Deadband Temperature Difference {deltaC}
    3000,                       !- Heater 1 Capacity {W}
    0.535,                       !- Heater 1 Height {m}
```

throws this fatal error:

```
   ** Severe  ** WaterHeater:Stratified = STORAGE TANK: Heater 1 is located higher than overall tank height.
   **   ~~~   ** Tank Height = 0.4000
   **   ~~~   ** Heater 1 Height = 0.5350
   **  Fatal  ** Errors found in getting WaterHeater:Stratified input. Preceding condition causes termination.
```

This check needs to use the true tank height (diameter) which is 2*SQRT((0.36/0.4)/Pi)=1.07m not the input value of 0.4 which is the horizontal "height".  Quick look at the code finds two places where the true height is calculated from the input height and neither place saves this into the data structure so the variable names gets confusing WaterThermalTank.Height (input value) and TankHeight (local height dependent upon shape input).  Seems this calculation could be done once and stored in a new structure variable like ActualHeight  and WaterThermalTank.Height should be renamed to something like WaterThermalTank.InputHeightOrLength.  Then this error check could simply be changed to use .ActualHeight instead of .Height.

And perhaps change the field name to "Tank Height or Length"?
### Details

Some additional details for this issue (if relevant):
- Platform Win64
- Version of EnergyPlus 8.5.0
- Helpdesk ticket 11313
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (reproduced with an example file, attached here)
  [WaterHeaterStandAlone-Horizontal.idf.txt](https://github.com/NREL/EnergyPlus/files/242889/WaterHeaterStandAlone-Horizontal.idf.txt)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
@mjwitte So do you know if the rest of the calculations are performed appropriately?  If it's just the height out-of-range checks that are failing, I'll simply create a small temporary variable to hold this radial height.  

If you know for sure that the other calculations are using the wrong height then I'd rather spend a little extra time to:
- Change the field name to `Axial Height`, which jives with the description in the IO ref
- Keep two separate structure variables, `axialHeight` and `diameter` and verify they are used appropriately throughout the code
  In which case it probably won't be happening today...

**Comment by mjwitte** [comment]
@Myoldmopar I don't know for sure.  I didn't look any further than the offending error message and the usage of actual height.
