### ISSUE TITLE
Add "QuickBuild" Option for Docs to CMake

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#5640]
Is there any interest in a QuickBuild option for the documentation? XELATEX needs to be run 3-times _initially_ to resolve the references to figures, equations, etc., and I don't think there is any way around that. However, I think it would be nice to be able to build the docs to verify correct formatting/syntax/etc without the extra build time, especially if we are not adding references. Depending on how much material you add, the page numbers may not line up with the TOC, but the rest of it should be relatively close to complete.

The docs build sequentially, so that adds time, but IMO the bigger issue is that once XELATEX has been run a few times and no new reference are added, the .aux files are not going to change. At that point running it three times is not doing anything that just running it one time would resolve.

A few build times for reference below. First-fresh build; second-tiny change to EngRef and IORef runing XELATEX three times; third-same mod to EngRef and IORef but only running XELATEX once. I suppose I could just modify the CMake file, but a :ballot_box_with_check: in CMake is nice too!
#### Initial Build

```
 - 00h 03m 22s 284ms    -- zPDF_EngineeringReference --
 - 00h 04m 44s 860ms    -- zPDF_InputOutputReference --
```
#### Mod - 3X XELATEX - Normal

```
 - 00h 03m 01s 040ms    -- zPDF_EngineeringReference --
 - 00h 04m 28s 134ms    -- zPDF_InputOutputReference --
```
#### Mod - 1X XELATEX - Quick Build

```
 - 00h 01m 00s 787ms    -- zPDF_EngineeringReference --
 - 00h 01m 30s 097ms    -- zPDF_InputOutputReference --
```

**Comment by Myoldmopar** [comment]
@mitchute with the reworked doc build process, the docs are actually built in the source tree, so you can just edit/build the docs from the source tree directly using the tool and workflow of your choice.  You just need to run CMake configure to update the title page and such as you see fit.  I'm closing this one now.
