### ISSUE TITLE
EnergyPlus v8.5 idf version updater does not work

### ISSUE THREAD

**Issue by FaranQ** [NREL/EnergyPlus#5648]
## Issue overview

The idf file version updater in version 8.5 is not working (on MAC OSX10.11.4). I'm trying to update the reference building database idf files (http://energy.gov/eere/buildings/commercial-reference-buildings) to the current version (8.5), but it gives errors and just does not convert the files.

The error message displayed is: Error starting transiotion-Vx-x-x Program: 2

Anyone having similar problem, or knows how to solve it ?

**Comment by ecoeficiente** [comment]
I've had the same problem in Windows version.

**Comment by JasonGlazer** [comment]
@FaranQ and @ecoeficiente could you please send me the files that cause this problem to me? My email is jglazer at gard dot com.

**Comment by mjwitte** [comment]
Just for reference, I successfully transitioned RefBldgLargeOfficeNew2004_v1.4_7.2_1A_USA_FL_MIAMI from v7.2 to v8.5 with the v8.5 IDFVersionUpdater on Windows.

**Comment by asparke2** [comment]
I just hit this same issue, Windows 7, E+ 8.5.0.  I ran the IDF Version Updater on all of the Prototype and Reference IDFs (available on [this Github Repo](https://github.com/NREL/OpenStudio-Prototype-Buildings/tree/master/regression%20test/legacy%20prototype%20idf%20files).  Here is a list of all the files that failed conversion:

[failed_conversion_summary.txt](https://github.com/NREL/EnergyPlus/files/273214/failed_conversion_summary.txt)

**Comment by asparke2** [comment]
As a workaround I first ran the E+ 8.4.0 updater on all of the files that failed using 8.5.0.  Then, once the conversion up to 8.4.0 was done, I ran the 8.5.0 updater.  This workflow succeeded for all but 7 of the 1859 models.

**Comment by asparke2** [comment]
I think there is a difference between running via the .lst file and running individually.  I was able to re-run some of the individual idf files and they worked on their own.

**Comment by JasonGlazer** [comment]
@FaranQ and @ecoeficiente, were you using IDF Version Updater with a single file or with a LST file?

**Comment by FaranQ** [comment]
@JasonGlazer  I was using it on a single file.

**Comment by JasonGlazer** [comment]
@FaranQ any chance of you sending me (jglazer at gard dot com) the particular file?

**Comment by FaranQ** [comment]
@JasonGlazer: it's the small office model on this page (http://energy.gov/eere/buildings/new-construction-commercial-reference-buildings) - version 1.4_7.2

**Comment by JasonGlazer** [comment]
I was able to reproduce the problem and it seems like it is the transition from 8.1.0 to 8.2.0 that is causing a problem. I did find a workaround, just download the ZIP file for doing even older conversions at:

http://energyplus.helpserve.com/Knowledgebase/List/Index/46/converting-older-version-files

Unzip the file in the IDFVersionUpdater directory and it should work, it did for me at least. Let me know if this does not resolve any issues that you are having.

**Comment by JasonGlazer** [comment]
To reproduce this issue, use a brand new 8.5.0 installed directory and run the IDFVersionUpdater on ASHRAE90.1_HotelSmall_STD2004_Albuquerque.idf from [here](https://github.com/NREL/OpenStudio-Prototype-Buildings/tree/master/regression%20test/legacy%20prototype%20idf%20files). And run with Create Intermediate Version Files checked. The V820 file will not show that it was transitioned and will remain at Version 8.1 plus IDFVersionUpdater will show the "Error Starting Transition-Vx-x-x Program:2" message. If Transition is run at the command line the message will be:

```
At line 367 of file I:\epRepo\EnergyPlus\src\Transition\CreateNewIDFUsingRulesV8_2_0.f90
Fortran runtime error: Array bound mismatch for dimension 1 of array 'outargs' (25529/25530)
```

**Comment by ecoeficiente** [comment]
Sorry Jason, I missed your request. I've just sent you my file, which is a  v8.3. idf file.

**Comment by mjwitte** [comment]
Closed via #5678

**Comment by nxtruong** [comment]
I was hit with the same error (Error starting Transition-Vx-x-x Program: 2), on Mac with EnergyPlus v8.5.0, while converting an IDF file in v8.4 to v8.5. I followed the fix by @JasonGlazer (comment on May 23rd) but the error persisted.

The IDF file is from an example included in BCVTB (attached).
[SmOffPSZ.idf.zip](https://github.com/NREL/EnergyPlus/files/371821/SmOffPSZ.idf.zip)

**Comment by JasonGlazer** [comment]
@nxtruong I hope the fix that will be included in 8.6 resolves the issue you found. See [5678](https://github.com/NREL/EnergyPlus/pull/5678)

**Comment by nxtruong** [comment]
@JasonGlazer It seems the fix you mentioned is for a problem transitioning from v8.1 to v8.2. But my IDF file is currently in v8.4, so my transition is from 8.4 to 8.5, not involving the step from 8.1 to 8.2.

**Comment by JasonGlazer** [comment]
@nxtruong Thanks, I will take a look at it and if it is a new bug, I will open a new issue.

**Comment by JasonGlazer** [comment]
@nxtruong when I tried transitioning your file on Windows using IDFVersionUpdater, it worked without a problem. Although the only thing changed was the version line.

**Comment by ClaireGyn** [comment]
Do you know how to update 8.5 to 8.6?

**Comment by JasonGlazer** [comment]
Use IDFVersionUpdater. It is located in the PreProcess\IDFVersionUpdater directory where ever you installed EnergyPlus. I would recommend that you use the latest version of this from EnergyPlus 8.9.0 and when running the updater on your 8.5 file, click "Create Intermediate Version Files" and that should create the 8.6 file that you want.
