### ISSUE TITLE
Add an input for the design water delatT for coil sizing

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5655]
## Issue overview

Coil water side dT is taken from the plant loop Sizing:Plant object. In reality, the plant loop dictates the design of the chiller dT.  It would be nice to have the plant loop dT be the default at the coil, but allow an override.  There are cases where you select some coils with a different design dT, and this should work as long as all the water mixes back on the return side.  It would be nice to specify the water dT at the coil if it is different.
### Details

Some additional details for this issue (if relevant):
- ref PNNL e-mail on May 12, 2016
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [x] Ticket added to Pivotal for defect (development team task)
- [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by EnergyArchmage** [comment]
Yes, a coil-level input might be useful; the plant design dT is somewhat overused. 

As far as the chiller's dT (from actual operation of a mixed set of coils), this can already be addressed automatically using the coincident plant sizing method.  Similiarly, the measured dTs are planned to be part of future improvements to do coil (re)sizing using HVAC Sizing Simulation.

**Comment by Nigusse** [comment]
Any one working on this issue?

**Comment by mjwitte** [comment]
I'm not.

**Comment by Nigusse** [comment]
@mjwitte There are design water inlet and water outlet temperatures (Coil:Heating:Water and Coil:Cooling:Water) objects. We are not going to use those values to get deltaT, instead we add a input field for deltaT user input, right?

**Comment by mjwitte** [comment]
Possibly, but I don't think that they currently get used for the water side sizing (if I remember correctly), so the sizing function may need some changes to use those temperatures.  Feel free to query the user to see if that would meet their requirements.  And also check the detailed chilled water coil inputs.

**Comment by mjwitte** [comment]
I meant to say "Possibly, the existing input could be enough, . . . "

**Comment by Nigusse** [comment]
I see the "Coil:Cooling:Water:DetailedGeometry" does not have those inputs. You may be right, those input fields are not used. I will check that and contact the user as well. Thanks.

**Comment by Nigusse** [comment]
Coil:Heating:Water and Coil:Cooling:Water objects require those design water and air temperatures for sizing calculation in several places. For Coil:Cooling:Water [here](https://github.com/NREL/EnergyPlus/blob/137612401_Issue5655/src/EnergyPlus/WaterCoils.cc#L1148-L1158). For  Coil:Heating:Water [here](https://github.com/NREL/EnergyPlus/blob/137612401_Issue5655/src/EnergyPlus/WaterCoils.cc#L1030).
The heating water coil used deltaT from design inlet and outlet water temperatures.

The only concern I have is that if users specify values different from the rated condition, then would it be a problem for reporting UA values determined at a condition different from the rated one? But certainly we need a new input field for detailed water cooling coil model.

**Comment by Nigusse** [comment]
Sorry Coil:Cooling:Water object has design inlet water temperature but not the outlet water temperature. So, the option is to add new input field for deltaT for both cooling water coils.

**Comment by EnergyArchmage** [comment]
I prefer a separate delta-T-for-sizing input, in all three water coils.  The catalog coil conditions for coil performance might not match a particular plant application.  

I see a bit of confusion here between autosizing versus the one time inits.  For example hot water coil is really sized [here](https://github.com/NREL/EnergyPlus/blob/137612401_Issue5655/src/EnergyPlus/ReportSizingManager.cc#L732) and it uses the plant sizing delta T, not those coil performance inputs.

**Comment by EnergyArchmage** [comment]
I prefer a separate delta-T-for-sizing input.  The catalog coil conditions for coil performance might not match a particular plant application.  

I see a bit of confusion here over sizing versus UA calcs when hardsized.  For example hot water coil is sized here and it used the plant sizing delta T, not the coil performance inputs

**Comment by Myoldmopar** [comment]
Closed via #5983
