### ISSUE TITLE
FuelEquipment

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#5656]
## Issue overview

EnergyPlus currently has `ElectricEquipment` and `GasEquipment` objects that use electricity or natural gas and contribute to internal gains. There is also a `OtherEquipment` which uses no fuel and contributes to internal gains. Additionally, there is a `Exterior:FuelEquipment` that uses a fuel specified in a field (Electricity, NaturalGas, PropaneGas, FuelOil, etc) but does not contribute to internal gains. 

For residential use there exists equipment that uses fuels other than electricity or natural gas and contributes to internal gains (i.e. a propane oven/range or a propane clothes dryer). Therefore there is a need for a generic `FuelEquipment` object that allows the user to specify a fuel and contributes to internal gains.

This could be implemented in a couple of ways:
1. Create a `FuelEquipment` to replace (or deprecate) `GasEquipment` and `ElectricEquipment`.
2. Create a `FuelEquipment` that has all of the fuel types except electricity or natural gas.
3. Create separate `PropaneEquipment`, `FuelOilEquipment`, etc objects.
4. Equipment that replaces all interior/exterior, gas/electric/other. From [below](https://github.com/NREL/EnergyPlus/issues/5656#issuecomment-220482638)
5. Create a `FuelEquipment` to replace `GasEquipment`. From [below](https://github.com/NREL/EnergyPlus/issues/5656#issuecomment-219066932)
6. Add "Fuel Type" field to `OtherEquipment`. From [below](https://github.com/NREL/EnergyPlus/issues/5656#issuecomment-221892458)

My preference is 1. Before I go make an NFP, are there any thoughts on how this should be done?

@Myoldmopar @shorowit

Table previously in @nealkruis [post](https://github.com/NREL/EnergyPlus/issues/5656#issuecomment-221677604):

| Object | Generates Heat in Zone | Exterior (no zone heat gain) | Generates CO2 | Consumes Electricity | Consumes Natural Gas | Uses District Heat | Consumes any Fuel Type | Consumes no Energy Resource | Net Number of Objects |
| --- | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: | :-: |
| ElectricEquipment | x |  |  | x |  |  |  |  | NA |
| GasEquipment | x |  | x |  | x |  |  |  | NA |
| HotWaterEquipment | x |  |  |  |  | x |  |  | NA |
| SteamEquipment | x |  |  |  |  | x |  |  | NA |
| OtherEquipment | x |  |  |  |  |  |  | x | NA |
| Exterior:FuelEquipment |  | x |  | x | x | x | x |  | NA |
| Option 1 | x |  | x | x | x | x | x |  | -1 |
| Option 2 | x |  | x |  |  | x | x |  | +1 |
| Option 3 | x |  | x |  |  |  |  |  | +11 |
| Option 4 | x | x | x | x | x | x | x | x | -5 |
| Option 5 | x |  | x |  | x | x | x |  | 0 |
| Option 6 | x |  |  | x | x | x | x | x | 0 |

**Comment by mjwitte** [comment]
@nmerket I would be reluctant to get rid of the current ElectricEquipment and GasEquipment because they are nice and clear and heavily used, so I would prefer option 2. But you could let FuelEquipment fuel types include naturalgas and electricity, so you could use it for everything if you want.

**Comment by Nigusse** [comment]
@nmerket I prefer option 2.  I second Mike's idea, make it generic such that it includes electric and natural gas well.

**Comment by nmerket** [comment]
I am fine with adding a `FuelEquipment` object that allows all the fuel types while keeping `ElectricEquipment` and `GasEquipment`. I just know that there has been an overall effort to reduce redundant objects in EnergyPlus and this would add a redundant object.

**Comment by mjwitte** [comment]
One modeler's redundancy is another modeler's flexibility.  If the overlap really bothers people, then I could be persuaded to another option where `FuelEquipment` replaces `GasEquipment` with a fuel type field that defaults to NaturalGas (and, yes, it could exclude electricity).  I've always found `Exterior:FuelEquipment` with Electricity to be a bit odd anyway - most people don't think of electricity associated with the word fuel.  But I've haven't heard users clamoring for `Exterior:ElectricEquipment`.

**Comment by nmerket** [comment]
I'm not sure the overlap does bother anybody. It doesn't bother me. I just want to verify and document that before pressing forward.

**Comment by nealkruis** [comment]
Overlap bothers me! I vote for option 4: `Equipment` that replaces all interior/exterior, gas/electric/other. 

Maybe `Load` or `Gain` would be a better generic catch-all name, so as to not confuse with HVAC Equipment.

The more options users have to choose from, the more opportunity there is for confusion. Proliferation of objects is a major source of frustration for many people we've talked to for the usability study.

We should link to this conversation on [UserVoice](https://energyplus.uservoice.com/forums/258860-energyplus) and have users weigh in as well.

**Comment by shorowit** [comment]
I agree with @nealkruis in principle on both accounts (Equipment is a confusing name; overlap is not desired). That said, we have near-term needs for this capability and we don't want to take on a significant refactoring of existing objects, migration, etc., at this time. Maybe for FY17?

I'm fine with the current winning proposal. 

That said, I'd personally choose to replace GasEquipment (likely used MUCH less than ElectricEquipment) with FuelEquipment. Then, at least, there isn't an appearance of overlap simply based on object names, as you would have ElectricEquipment and FuelEquipment.

**Comment by mjwitte** [comment]
@nealkruis I've never heard complaints about these particular objects, so it seems there are better places to address concerns about overlap.  I think Load or Gain is too generic - because it doesn't say "I'm consuming energy" the way that Electric, Gas, or Fuel does.  
@shorowit I've added options 4 and 5 at the [top](https://github.com/NREL/EnergyPlus/issues/5656#issue-154586167).

**Comment by nealkruis** [comment]
@mjwitte Nothing says "I'm not consuming energy" like "Other". : )

**Comment by nmerket** [comment]
I'm so glad I haven't wasted time on an NFP for this yet. Carry on.

**Comment by shorowit** [comment]
Yes, OtherEquipment is a truly strange choice for a name. When I first saw GasEquipment, ElectricEquipment, and OtherEquipment, I thought E+ might already be able to handle other fuel types. Turns out that OtherEquipment is really not equipment at all. (Or, at least, I struggle to understand the scenario where you'd want to model a piece of equipment's internal gains but not have its energy use metered.)

**Comment by nealkruis** [comment]
@shorowit BEopt uses OtherEquipment all over the place to approximate duct losses in one of the most masterful EnergyPlus hacks of all time! (credit: J. Winkler et al.)

**Comment by EnergyArchmage** [comment]
OtherEquipment is very important, and very difficult to name.  Load with no energy consumption is very different from the others and cannot be lumped in with other objects to address some vague notion of overlap.

**Comment by nealkruis** [comment]
@EnergyArchmage I'm not necessarily suggesting that @nmerket does a deep refactoring of all the equipment objects into a single source. The source code for OtherEquipment can probably stay the way it is and key off of IDF input fields to determine how to map to the existing structures in the source code. 

For example:

```
SourceOrSink,                       !- Working Object Type Name (Thoughts? Maybe just 'Source'?)
  Name,
  Zone or Zone List,                !- If left blank assumed to be exterior equipment
  Fuel Type,                        !- If left blank assumed to be "Other Equipment". Fuel choices = normal Fuel Type list + District Heating/Cooling
  Schedule Name,
  Design Level Calculation Method,  !- (a bit of a tangent) This field could probably be dropped in favor of summing all three
  Design Level,
  Power per Zone Floor Area,
  Power per Person,
  Fraction Latent,
  Fraction Radiant,
  Fraction Lost,
  Carbon Dioxide Generation Rate,
  End-Use Subcategory;
```

This one object could replace 6 others:
- `ElectricEquipment`
- `GasEquipment`
- `HotWaterEquipment`
- `SteamEquipment`
- `OtherEquipment`
- `Exterior:FuelEquipment`

**Comment by mcneillj** [comment]
I agree with @nealkruis about using OtherEquipment.  It has most of the features necessary for applying loads to zones.  Commonly used fuel types that I see in labs and healthcare are: chilled water, hot water, steam, electricity, and natural gas.

Having multiple redundant models is confusing from a user perspective.  The other thing I have noticed is that over time changes occur that make these supposed redundant components operate differently.  In the design field we refer to all of this equipment as a _Process Load_.

One suggestion that is useful from a practitioner point of view is that we may want to apply process loads to zones, hydronic loops, or meters.  Currently it seems OtherEquipment would apply only to zones.

**Comment by JVDirkes2** [comment]
Simplicity is good. 
If #4 means a single object which can be defined as any of several typical fuels, contributing heat indoors or out, and the reporting keeps track of the fuel used... then that sounds "simple" from my user perspective. One object for all energy uses indoors or out.
If that becomes the new normal, then the other objects should be deprecated (for greater simplicity :)
p.s., I don't think "fuel" is confusing, nor is "equipment" for the various uses to which they're put in E+. A revamp of the "OtherEquipment" object to include "fuel" type and location would work well.

**Comment by JasonGlazer** [comment]
To me, the first rule of user experience/user interface design is "do no harm". It seems like this proposal is going to confuse thousands of existing users because a small group of us do not find it aesthetically pleasing. I think we can all acknowledge that if we were designing this today we would do it differently but we are not. EnergyPlus has thousands of users that use these objects regularly and as @mjwitte said in his earlier comment "I've never heard complaints about these particular objects, so it seems there are better places to address concerns about overlap." He would know since his is the front line for user support. I vote for leaving it alone.

**Comment by JVDirkes2** [comment]
Careful....
I understand what you are saying, but maintaining the status quo can become "stagnation", which can be viewed as "harm" when compared to growth and improvement. The thousands of current E+ users are, it seems, clearly aimed toward continuous improvement and the many new users have no bias. This would be quite a small change, regardless.
My opinion: Although complaints do often indicate the egregious problems, lack of complaints can also mean only that it's not a big enough problem to mention in the face of a full slate of other concerns. On the one hand, it's good to focus on the most pressing concerns, but on the other hand, it's also good to anticipate and make changes pro-actively.

**Comment by Myoldmopar** [comment]
This conversation is so beautiful it almost brings a tear to my eye.  Developers and Users working closely debating the path forward for changes to EnergyPlus.  Awesome.  (FYI @amirroth)

Now, I see two requirements popping up from this conversation:
1. @shorowit needs a fix to this in the near term, presumably for the Fall release
2. The overall structure needs a longer look, with more of this conversation resulting in a new methodology.

I think we should try to agree on something minimal, non-invasive for the current timeframe.  Something that does the job, but we spend as little time as possible on it, and doesn't block future (better) improvements in FY17.  Then for FY17, we plan to include a task item work on this with a bigger view.  Sound good?

**Comment by macumber** [comment]
On the OpenStudio side I don't have a strong preference either way.  OpenStudio tends to resist changes in the API so we would probably wrap the new objects and deprecate the old objects but keep them in the API for some time.  @kbenne might have additional thoughts

One additional note is that I have the dream of one day supporting electric lighting simulations in OpenStudio.  This is why OpenStudio has Luminaire objects with position, orientation, and IES file references.  These can be translated to Radiance to perform electric lighting calculations.  We still translate to a simple load in E+.  Would we ever want to do detailed modeling of any of the other load types?  Like special modeling of kitchen equipment or something?

**Comment by JVDirkes2** [comment]
Someone probably has a vision for the development of E+ and can comment on the desirability of adding more guts to the kitchen objects (or others). At the moment, the "...Equipment" objects are working for me. I split kitchen equipment which is underneath an exhaust hood roughly 90/10 into interior and exterior loads; refining these objects to allow the interior / exterior split in a single object strikes me as "it would be nice".
On the bigger picture, I wonder if non-energy aspects of an E+ simulation are distracting regarding the fundamental purpose of the software? Lighting and comfort are important, but can probably be handled better by other software to avoid the impression that E+ is intended for detailed analysis of those. ... or maybe that"s the "+" part of E+?
If you (Dan) are suggesting those capabilities for OpenStudio, that makes good sense to me. DesignBuilder is developing in that direction by providing handoffs to Radiance and CFD, for example - taking advantage of the info that's already present for the energy analysis.

**Comment by nealkruis** [comment]
We should rein in the scope of this discussion. I agree with @Myoldmopar about tabling this discussion and allowing @nmerket and @shorowit decide what is reasonable for them to handle to meet their short term need. To put some of the discussion points in context, here are all of the options compared with the current objects:

(table moved to [issue description](https://github.com/NREL/EnergyPlus/issues/5656#issue-154586167))

P.S. I think we can rule Option 3 out

**Comment by macumber** [comment]
Nice table Neal.  I only mentioned the additional modeling because I want to avoid merging all these model objects only to separate them out again later when we want to model more detailed features.

**Comment by shorowit** [comment]
We have an additional option suggested by a user who wishes to remain anonymous. Add a fuel type field to the OtherEquipment object; if the field is left blank (or set as "None"?), then the object behaves like it always did. Otherwise the fuel use is metered.

Personally, this is my new favorite option since it addresses my previous concern: "When I first saw GasEquipment, ElectricEquipment, and OtherEquipment, I thought E+ might already be able to handle other fuel types." Maybe @nealkruis can add it to his table?

**Comment by nealkruis** [comment]
@shorowit I added option 6. Shouldn't it also add the "Carbon Dioxide Generation Rate" field?

**Comment by mjwitte** [comment]
And an End-Use Subcategory.

**Comment by EnergyArchmage** [comment]
This is probably out of scope and for the future, but this could also allow for user-definable fuel types using the models in Generator:FuelSupply.  Then there would be a way to run hydrogen, biogas, etc.  -- virtually anything if given the molar concentrations.

**Comment by nmerket** [comment]
Option 6 it is!

**Comment by nmerket** [comment]
I added the NFP [here](https://github.com/NREL/EnergyPlus/blob/other_equipment/design/FY2016/OtherEquipment.md).
