### ISSUE TITLE
Crankcase heater for Coil:Cooling:DX:MultiSpeed

### ISSUE THREAD

**Issue by jonwinkler** [NREL/EnergyPlus#5659]
## Issue overview

I'm trying to simulate a crankcase heater in a Coil:Cooling:DX:MultiSpeed object when using the AirLoopHVAC:UnitarySystem. In this case, I'm using a gas furnace so there aren't crankcase heater inputs associated with a corresponding DX heating coil.
## Details

IDF, schedule, and sleeted output files are attached. 1.idf uses a single stage coil and the crankcase heater is handled appropriately; evident by the cooling electricity meter and crankcase energy hourly energy of 360,000 J during heating hours (corresponding to a 100W crankcase heater). 

2.idf is the same building with a MS coil but crankcase heater energy is not showing up in the cooling electricity meter. Additionally, crankcase heater output variables do not show up in the RDD file.
[_files.zip](https://github.com/NREL/EnergyPlus/files/266908/_files.zip)

[pivotal story](https://www.pivotaltracker.com/story/show/119835823)

**Comment by jonwinkler** [comment]
@nmerket

**Comment by nmerket** [comment]
@rraustad @lgu1234 @Myoldmopar Any takers?

**Comment by rraustad** [comment]
If in UnitarySystem, then it'd be me.

**Comment by rraustad** [comment]
Or, since this is a MS DX coil issue, if Gu wants it he could fix.

**Comment by lgu1234** [comment]
I take it.

**Comment by rraustad** [comment]
Closed via https://github.com/NREL/EnergyPlus/pull/5677
