### ISSUE TITLE
File links for weather files not downloading files

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5662]
When trying to download weather data from the energyplus.net web site, when clicking on the links instead of files downloading the files are being rendered as if they are HTML. 

https://energyplus.net/weather-location/north_and_central_america_wmo_region_4/USA/MA/USA_MA_Boston-Logan.725090_TMY2

The problem appears to be intermittent. Sometimes the link will work the first time and when canceled and tried again it will not work the second time.

Using Firefox 46.0.1 but the problem was originally report using IE.

**Comment by jmarrec** [comment]
I cannot reproduce the problem, so I suggest closing this one @JasonGlazer unless you can.

**Comment by JasonGlazer** [comment]
Looks like it is working.
