### ISSUE TITLE
Replace a field name of "Controlled Zone Name" in two objects

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#5664]
## Issue overview

A  field name of "Controlled Zone Name" is used in two objects: ZoneControl:ContaminantController and AvailabilityManager:HybridVentilation. In order to be consistent with other objects, the field name will be replaced by "Zone Name" in ZoneControl:ContaminantController to match pattern of thermostat and "Control Zone Name" in AvailabilityManager:HybridVentilation to match other objects.
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- Version of EnergyPlus (if using an intermediate build, include SHA)
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #5732
