### ISSUE TITLE
Logic problem in coincident plant sizing

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5665]
Plant coincident sizing doesn't alwasy work correctly when demand triggers to set a new size but the max flow timestamp is not valid.  The routine ResolveDesignFlowRate should work if there is only a demand-based timestamp but the way it is coded it needs to also have a max flow timestamp.

The || here should be an &&. 
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SizingAnalysisObjects.cc#L542

And several places need to check one or the other timestamp is null. 
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- Version of EnergyPlus (if using an intermediate build, include SHA)
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@EnergyArchmage Is there a defect file for this?

**Comment by EnergyArchmage** [comment]
No, sorry there isn't a defect file, just a unit test.  The large set of fixes that went in with https://github.com/NREL/EnergyPlus/pull/5751 corrected the problem that was generating null timestamps in the first place, now that they are gone this logic problem is hard to reproduce in a running file.  I considered rolling this small change into that PR but there was already a separate issue.

**Comment by mjwitte** [comment]
Got it

**Comment by mjwitte** [comment]
Closed via #5829
