### ISSUE TITLE
Dual duct outdoor air system economizer

### ISSUE THREAD

**Issue by Alex-Blue** [NREL/EnergyPlus#5667]
The dual duct outdoor air system currently does not allow economizer function; is there any way to add this in? We have a project that is considering a dual duct system with one duct supplying ventilation air and the other supplying heating/cooling. In the design, the central system will have the capability to bring in extra OA through the system to supply free cooling. Any chance of adding this feature request to a future release?

**Comment by mjwitte** [comment]
@Alex-Blue Economizer should work with dual-duct systems.  If you have a test file that demonstrates the problem, please attach to this issue (rename to xys.idf.txt to attach in github).
