### ISSUE TITLE
LrgOff_GridStorageEMSSmoothing.idf has no EMS program

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#5673]
## Issue overview

The example file called `LrgOff_GridStorageEMSSmoothing.idf` has no EMS program defined in it... Seems like it's missing or the file is really badly named.
### Details

Some additional details for this issue (if relevant):
- EnergyPlus V8.5.0
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file: https://github.com/NREL/EnergyPlus/blob/develop/testfiles/LrgOff_GridStorageEMSSmoothing.idf
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by EnergyArchmage** [comment]
Ack, somehow the EMS got mistakenly cut out during this commit to change reporting frequency.  https://github.com/NREL/EnergyPlus/commit/882e9e0cc9f66abb5b99f630f1fda3e185ac5fbc#diff-8eccea65797d64604c965dcd5fdb93c9

sorry, about that,
