### ISSUE TITLE
Error in interpolation of wind direction data points from weather files

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5682]
## Issue overview

From user:
There is an error in the method used to interpolate wind speeds between two data points within a weather file. TMY weather files typically have 1 hour data intervals, so EnergyPlus calculation timesteps have to interpolate the weather data between these large intervals. However, it was found that depending on values of two consecutive wind directions, the interpolation is performed incorrectly. This is best explained through an example:
If a weather file contains two consecutive wind direction entries of 1° and 3° spaced one hour apart, and as a simplification assuming that the EnergyPlus calculation timesteps are 10 minutes apart, the interpolation will calculate the wind speeds as 1, 1.33, 1.66, 2, 2.33, 2.66, 3 degrees. However, if the consecutive wind direction entries are 1° and 359°, the interpolation will calculate the wind speeds as 1, 60.66, 120.33, 180, 239.66, 299.33, 359. This is not the way that it should be calculated. The correct interpolation in this case should be 1, 0.66, 0.33, 360, 359.66, 359.33, 359.
Hopefully it is apparent through the example that in the current method, although both wind directions are almost directly north, interpolating between them causes the direction to traverse the entire compass.
In order to correct this problem, the code should identify the shortest path between the two consecutive points and choose that direction for interpolation. For example, if going from 20° to 300°, the interpolation should occur through the 0/360 crossover (through north) rather than avoiding it (through south). If the consecutive directions are exactly 180 degrees apart, then either route is equally valid. 

We found the issue when using the New York JFK Airport weather file (attached). We were simulating on 1/29 from 12 am to 6am. See the attached figure. In the figure, the red points are weather file values for wind direction, and the blue line is interpolated data from EnergyPlus. If the interpolation was done correctly, the blue line would follow the same path as the green dotted line.

![simulationwinddirectioninterpolationerror](https://cloud.githubusercontent.com/assets/4991075/15518440/7c913ff0-21c2-11e6-8ad8-a748a6dadc34.png)
### Details

Some additional details for this issue (if relevant):
- Platform Win64
- Version of EnergyPlus v8.5
- Helpdesk ticket 11359
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles\5682) run with USA_NY_New.York-J.F.Kennedy.Intl.AP.744860_TMY3.epw
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Defect files added, including spreadsheet to plot timestep output vs original data.  This plot is adjusted so both values are between -180 to +180.  Orange dots are the hourly weather data.
![image](https://cloud.githubusercontent.com/assets/4991075/15518549/0ccfb2d6-21c3-11e6-988a-078ad9551970.png)

**Comment by Myoldmopar** [comment]
Closed via #5701
