### ISSUE TITLE
Hot water preheat coil not running but electric preheat works as expected

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5695]
## Issue overview

From user:
I have constructed two VAV air systems. The difference between the two systems is the preheat coil in the outdoor air system, one is a hot water preheat coil, the other is a electric resistance heating coil. After the heating coil I have a setpoint manager with a constant temperature setpoint of 11.67 C. When I look at the heating design day simulation results, I see the following:
1. Both have economizer turned on.
2. For the case with hot water preheat coil, the preheat coil seems to be locked out by the economizer - it's not operating.
3. For the case with electric resistance preheat coil, the preheat coil is operating heating air to its setpoint of 11.67 C
### Details

Some additional details for this issue (if relevant):
- Platform (Win64)
- Version of EnergyPlus v8.5.0
- Helpdesk ticket 11367
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (DefectFiles\5695)
- [x] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by EnergyArchmage** [comment]
closed via PR #5973
