### ISSUE TITLE
Economizer with preheat is bringing in excess outdoor air on the winter design day

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5697]
## Issue overview

On the winter design day, the OA temperature is -17.3C, the mixed air setpoint is 17.4C, and the return air temp is 20.5C.  Why is the economizer opening beyond minimum causing a mixed air temp of 12.5C?
### Details

Some additional details for this issue (if relevant):
- Platform (Win64)
- Version of EnergyPlus (v8.5.0)
- Helpdesk ticket 11367
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [X] Defect file added (DefectFiles\5697)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
This code increases OA fraction a little:

line 4104 of MixedAir.cc on first non-warmup day iteration using Chicago weather.

	if ( std::abs( this->RetTemp - this->InletTemp ) > SmallTempDiff ) {
		OutAirSignal = ( this->RetTemp - this->MixSetTemp ) / ( this->RetTemp - this->InletTemp );

RetTemp = 20.51
InletTemp = -6.77 (heating coil is obviously on since OA = -17C) 
MixSetTemp = 17.42
IF test is true so OutAirSignal = 0.113 while MinOAFrac = 0.041

Then goes to RegulaFalsi where 0.113 is also chosen since it gives a mixed air T of 17.42.

Need to see what the heating coil is doing here. If it's on during these calcs and then is determined to be off, that would make sense if there were not another iteration. Still looking.

**Comment by rraustad** [comment]
In this file there is a heating coil sitting at the inlet to the OA mixer.

    AirLoopHVAC:OutdoorAirSystem:EquipmentList,
      AirLoopHVACOutdoorAirSystem_{00100} Equipment List,  !- Name
      Coil:Heating:Electric,   !- Component 2 Object Type
      ALT6 - Floor 1_ElecCoil_Preheat_{00119},  !- Component 2 Name
      OutdoorAir:Mixer,        !- Component 1 Object Type
      AirLoopHVACOutdoorAirSystem_{00100} Outdoor Air Mixer;  !- Component 1 Name

When the OA controller iterates the heating coil does not get called (nor any other OA equipment if it existed) in the MixedAirControlTempResidual RegulaFalsi function. Not sure of all the interactions here but simply avail scheduling off the OA heating coil give the expected results.

![5697_nopreheat](https://cloud.githubusercontent.com/assets/5778156/20862417/cc7e4be6-b977-11e6-88d4-27e9ddb3557b.png)

**Comment by rraustad** [comment]
Revising the iteration method to simulate the OA components corrects the problem. Here are the results of the defect file including the OA heating coil upstream of the OA mixer. I've got to clean this up before uploading the revised code.

![5697-fixed](https://cloud.githubusercontent.com/assets/5778156/20911286/fa8159ca-bb34-11e6-8e2b-0738b7a0ccd0.png)

**Comment by Myoldmopar** [comment]
Closed via #5955
