### ISSUE TITLE
MaterialProperty:VariableThermalConductivity and MaterialProperty:PhaseChange should be extensible

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5699]
## Issue overview

MaterialProperty:PhaseChange allows up to 16 temperature-enthalpy pairs, and MaterialProperty:VariableThermalConductivity allows up to 10 temperature-conductivity pairs.  These should both be extensible.
### Details

Some additional details for this issue (if relevant):
- Version of EnergyPlus v8.5.0
- Helpdesk ticket 11390
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
This _should_ be a fairly simple change - edit the IDD to mark the extensible fields, and change this declaration in HeatBalanceFiniteDiffManager::GetCondFDInput
        Array1D< Real64 > MaterialProps( 40 ); // Temporary array to transfer material properties

This should declared after checking the max numer of numerics for these two object types, then is can be right-sized.  The rest of the input processing already appears to be set up for any length object.

**Comment by RKStrand** [comment]
@mjwitte This is still active (as in it still hasn't been fixed and no one closed it).  Do you think this is still worth handling?  If so, I might take this on as a low complexity defect even though it is marked as "new feature request".  Thoughts?

**Comment by mjwitte** [comment]
Yes, it would be good to take care of. Remember that new extensible groups need an entry in 
https://github.com/NREL/EnergyPlus/blob/64093e60302b66f7213d400781d607310e0dd981/idd/schema/modify_schema.py#L74

**Comment by RKStrand** [comment]
Sounds good and thanks for the reminder on the need to add an entry in modify_schema.py because I am certain that I would have forgotten that.  Thanks!
