### ISSUE TITLE
Table:OneIndependentVariable documentation doesn't agree with behavior

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#5704]
## Issue overview

The documentation for Table:OneIndependentVariable has this for the minimum value independent variable field:

> Field: Minimum Value of X
> 
> The minimum allowable value of X. Values of X less than the minimum will be replaced by the
> minimum. This field can only limit extrapolation when the Interpolation Method is selected as
> EvaluateCurveToLimits or LagrangeInterpolationLinearExtrapolation. This filed can be used to
> limit interpolation using any Interpolation Method. If this field is left blank, the data set determines
> the limit.

There documentation for the maximum value is similar. If the documentation is correct, then neither value should be required. But that doesn't seem to be the case. Here's a unit test that fails (as long as I cut-and-pasted correctly):

```
TEST_F(EnergyPlusFixture, Tables_OneIndependentVariable_MinMaxFailure) {
    std::string const idf_objects = delimited_string({
        "Version,8.5;",
        "Table:OneIndependentVariable,",
        "TestTableMinMax,         !- Name",
        "Linear,                  !- Curve Type",
        "LinearInterpolationOfTable,  !- Interpolation Method",
        ",                        !- Minimum Value of X",
        ",                        !- Maximum Value of X",
        ",                        !- Minimum Table Output",
        ",                        !- Maximum Table Output",
        "Dimensionless,           !- Input Unit Type for X",
        "Dimensionless,           !- Output Unit Type",
        ",                        !- Normalization Reference",
        "0,                       !- X Value #1",
        "0,                       !- Output Value #1",
        "1,                       !- X Value #2",
        "1;                       !- Output Value #2" });
    ASSERT_FALSE(process_idf(idf_objects));
    EXPECT_EQ(0, CurveManager::NumCurves);
    CurveManager::GetCurveInput();
    CurveManager::GetCurvesInputFlag = false;
    ASSERT_EQ(1, CurveManager::NumCurves);
    EXPECT_EQ("LINEAR", CurveManager::GetCurveType(1));
    EXPECT_EQ("TESTTABLEMINMAX", CurveManager::GetCurveName(1));
    EXPECT_EQ(1, CurveManager::GetCurveIndex("TESTTABLEMINMAX"));
    bool error = false;
    int index = CurveManager::GetCurveCheck("TESTTABLEMINMAX", error, "TEST");
    EXPECT_FALSE(error);
    EXPECT_EQ(1, index);
    EXPECT_EQ(CurveManager::CurveType_TableOneIV, CurveManager::GetCurveObjectTypeNum(1));
    EXPECT_DOUBLE_EQ(0.0, CurveManager::CurveValue(1, 0)); // In-range value
    EXPECT_DOUBLE_EQ(0.75, CurveManager::CurveValue(1, 0.75)); // In-range value
    EXPECT_DOUBLE_EQ(0.0, CurveManager::CurveValue(1, -10.0)); // Minimum x
    EXPECT_DOUBLE_EQ(2.0, CurveManager::CurveValue(1, 5000)); // Maximum x
    EXPECT_FALSE(has_err_output());
}
```

All of the value checks fail, it always returns 1. Here is my defect file:
[AirflowNetwork_Simple_House_Linear_NoMinMax.idf.txt](https://github.com/NREL/EnergyPlus/files/296514/AirflowNetwork_Simple_House_Linear_NoMinMax.idf.txt)
### Details

Some additional details for this issue (if relevant):
- Platform: Windows 7, 64 bit
- Version of EnergyPlus: 8.5
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added
- [x] Ticket added to Pivotal for defect (development team task)
- [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@jasondegraw Interesting - the (confusing) docs above and the idd notes say the max/min x limits don't even apply for interpolation method LinearInterpolationOfTable.

**Comment by jasondegraw** [comment]
@mjwitte I think there's some logic in the value calculation that goes bonkers without the min/max values there. All of the "examples" I was able to find have both min and max given, and it seems like the easy fix would be to do as the docs say and set the min/max from the data. But I wasn't too sure of the original intent.

**Comment by mjwitte** [comment]
@jasondegraw The docs seem to imply that the default limits should be based on the input data.  Looking at the test snippet, seems like the last line should expect 1, not 2?

**Comment by jasondegraw** [comment]
@mjwitte Yes, that should be a 1 and not a 2. The logic happens around [line 3818 in PerformanceTableObject](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CurveManager.cc#L3818), and probably the block of code that sets Var1Min and Var1Max, currently [on line 1888 in GetCurveInputData](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CurveManager.cc#L1888), needs to get moved to after the data is read in.

**Comment by jasondegraw** [comment]
The documentation of minimum output value is this:

> Field: Minimum Table Output
> 
> The minimum allowable value of the table output. Values less than the minimum will be replaced
> by the minimum. This field can only limit extrapolation when the Interpolation Method is selected
> as EvaluateCurveToLimits or LagrangeInterpolationLinearExtrapolation. This filed can be used to
> limit interpolation using any Interpolation Method. If this field is left blank, the data set determines
> the limit.

The maximum output documentation is similar. What actually happens with EvaluateCurveToLimits is that both all of the limits (independent variable and output) are potentially overwritten by the regression solver routine. Here's a unit test that demonstrates the issue:

```
TEST_F(EnergyPlusFixture, Tables_OneIndependentVariable_EvaluateToLimits_OverwriteLimits) {

  std::string const idf_objects = delimited_string({
      "Version,8.5;",
      "Table:OneIndependentVariable,",
      "TestTableOverwrite,      !- Name",
      "Linear,                  !- Curve Type",
      "EvaluateCurveToLimits,   !- Interpolation Method",
      "0.1,                     !- Minimum Value of X",
      "4.9,                     !- Maximum Value of X",
      "1.2,                     !- Minimum Table Output",
      "2.5,                     !- Maximum Table Output",
      "Dimensionless,           !- Input Unit Type for X",
      "Dimensionless,           !- Output Unit Type",
      ",                        !- Normalization Reference",
      "0,                       !- X Value #1",
      "0,                       !- Output Value #1",
      "1,                       !- X Value #2",
      "2,                       !- Output Value #2",
      "2,                       !- X Value #3",
      "2,                       !- Output Value #3",
      "3,                       !- X Value #4",
      "3,                       !- Output Value #4",
      "4,                       !- X Value #5",
      "4,                       !- Output Value #5",
      "5,                       !- X Value #6",
      "2;                       !- Output Value #6" });

 ASSERT_FALSE(process_idf(idf_objects));

 EXPECT_EQ(0, CurveManager::NumCurves);
 CurveManager::GetCurveInput();
 CurveManager::GetCurvesInputFlag = false;
 ASSERT_EQ(1, CurveManager::NumCurves);

 // Linear curve type, specified min/max
 EXPECT_EQ("LINEAR", CurveManager::GetCurveType(1));
 EXPECT_EQ("TESTTABLEOVERWRITE", CurveManager::GetCurveName(1));
 EXPECT_EQ(1, CurveManager::GetCurveIndex("TESTTABLEOVERWRITE"));
 bool error = false;
 int index = CurveManager::GetCurveCheck("TESTTABLEOVERWRITE", error, "TEST");
 EXPECT_FALSE(error);
 EXPECT_EQ(1, index);
 Real64 min, max;
 CurveManager::GetCurveMinMaxValues(1, min, max);
 EXPECT_EQ(0.1, min); // Fails
 EXPECT_EQ(4.9, max);  // Fails
 EXPECT_EQ(CurveManager::CurveType_TableOneIV, CurveManager::GetCurveObjectTypeNum(1));

 EXPECT_DOUBLE_EQ(1.2, CurveManager::CurveValue(1, 0.5)); // Value should be too small, fails
 EXPECT_DOUBLE_EQ(2.5, CurveManager::CurveValue(1, 4)); // Value should be too large, fails
 EXPECT_DOUBLE_EQ(1.438095238095238, CurveManager::CurveValue(1, 1.0)); // In-range value

 CurveManager::SetCurveOutputMinMaxValues(1, error, 1.2, 2.5);
 EXPECT_FALSE(error);
 EXPECT_DOUBLE_EQ(1.2, CurveManager::CurveValue(1, 0.5)); // Value too small
 EXPECT_DOUBLE_EQ(2.5, CurveManager::CurveValue(1, 4)); // Value too large
 EXPECT_FALSE(has_err_output()); 
}
```

So for this case the data set determines the limits for EvaluateCurveToLimits, but it is overriding inputs.

**Comment by rraustad** [comment]
Well, maybe this was never tested with a blank input field?

```
if ( lNumericFieldBlanks( 1 ) ) {
    PerfCurve( CurveNum ).Var1Min = 99999999999.0;
} else {
    PerfCurve( CurveNum ).Var1Min = Numbers( 1 );
}
if ( lNumericFieldBlanks( 2 ) ) {
    PerfCurve( CurveNum ).Var1Max = -99999999999.0;
} else {
    PerfCurve( CurveNum ).Var1Max = Numbers( 2 );
}
```

Since these inputs are blank, the Var1Min and Var1Max values are 9999999 and -9999999, respectively. This yields 9999999 for V1 at line 3818 and always returns the top end of the table.

```
V1 = max( min( Var1, PerfCurve( CurveIndex ).Var1Max ), PerfCurve( CurveIndex ).Var1Min );
```

If the sign of the default inputs when blank are reversed, the first unit test above passes. I just can't recall why I chose those values. I think it has something to do with reordering inputs but can't seem to find that now (i.e., if max val > -99999 then do something).

**Comment by rraustad** [comment]
Also pointing out that GetInput doesn't do the 9999999/-99999999 initialization for the TwoIndependentVariable table (which means they may wind up as 0).

```
        PerfCurve( CurveNum ).Var1Min = Numbers( 1 );
        PerfCurve( CurveNum ).Var1Max = Numbers( 2 );
        PerfCurve( CurveNum ).Var2Min = Numbers( 3 );
        PerfCurve( CurveNum ).Var2Max = Numbers( 4 );
```

**Comment by jasondegraw** [comment]
@rraustad That does appear to be the case. I was going to make a separate issue for the two independent variable table, but I can add info here if that is preferred.

Also, using EvaluateCurveToLimits with the Exponent curve type doesn't produce a curve fit, it just falls through and all the coefficients are zero.

**Comment by rraustad** [comment]
Group everything here so all this gets fixed in the same issue. I'll see if I can create coefficients for the odd ball exponent curve type. I think I'll push up a fix tonight to see if any example files choke so I know if changing these defaults affects something else, which would then need to be fixed because these defaults need to be changed.

**Comment by rraustad** [comment]
@mjwitte @jasondegraw I can make EvaluateCurveToLimits use the user inputs for Minimum Value of X, Maximum Value of X, Minimum Table Output and Maximum Table Output, just not sure if I should. I guess if the user were allowed to enter the limits it would save time in data entry (if they knew what they were doing). On the other hand, it could result in some wacky results due to extrapolation (if they didn't know what they were doing). Right now is uses the limits of the data set, which is safe. Thoughts?

**Comment by mjwitte** [comment]
@rraustad Rather than have these limits behave differently for different types of curve/interpolation, why not have the Min/Max X/Y default to the range of the data set, and accept any user inputs for these limits (even if they extrapolate).  We don't protect users from wacky extrapolation with the regular curve objects.

**Comment by rraustad** [comment]
I'll give it a go.

**Comment by jasondegraw** [comment]
@rraustad I agree 100% with @mjwitte

**Comment by jasondegraw** [comment]
Here's what I've got for Table:TwoIndependentVariable so far:
- For at least LinearInterpolationOfTable, there is a similar min/max issue. See failing unit test below.
- The documentation and the IDD list two acceptable curve types (BiQuadratic and QuadraticLinear) but the code accepts two more (BiCubic and TriQuadratic [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/CurveManager.cc#L2039)) in GetCurveInputData. I haven't checked the other two interpolation types (Lagrange and EvalToLimits) where this actually matters yet.

Here's the unit test:

```
TEST_F(EnergyPlusFixture, Tables_TwoIndependentVariable_Linear_MinMaxFailure) {

    std::string const idf_objects = delimited_string({
        "Version,8.5;",
        "Table:TwoIndependentVariables,",
        "TestTableMinMax,         !- Name",
        "QuadraticLinear,         !- Curve Type",
        "LinearInterpolationOfTable, !- Interpolation Method",
        ",                        !- Minimum Value of X",
        ",                        !- Maximum Value of X",
        ",                        !- Minimum Value of Y",
        ",                        !- Maximum Value of Y",
        ",                        !- Minimum Table Output",
        ",                        !- Maximum Table Output",
        "Dimensionless,           !- Input Unit Type for X",
        "Dimensionless,           !- Input Unit Type for Y",
        "Dimensionless,           !- Output Unit Type",
        ",                        !- Normalization Reference",
        "0,                       !- X Value #1",
        "1,                       !- Y Value #1",
        "0,                       !- Output Value #1",
        "1,                       !- X Value #2",
        "1,                       !- Y Value #2",
        "2,                       !- Output Value #2",
        "2,                       !- X Value #3",
        "1,                       !- Y Value #3",
        "2,                       !- Output Value #3",
        "3,                       !- X Value #4",
        "1,                       !- Y Value #4",
        "3,                       !- Output Value #4",
        "4,                       !- X Value #5",
        "1,                       !- Y Value #5",
        "4,                       !- Output Value #5",
        "5,                       !- X Value #6",
        "1,                       !- Y Value #6",
        "2,                       !- Output Value #6",
        "0,                       !- X Value #7",
        "2,                       !- Y Value #7",
        "0,                       !- Output Value #7",
        "1,                       !- X Value #8",
        "2,                       !- Y Value #8",
        "2,                       !- Output Value #8",
        "2,                       !- X Value #9",
        "2,                       !- Y Value #9",
        "2,                       !- Output Value #9",
        "3,                       !- X Value #10",
        "2,                       !- Y Value #10",
        "3,                       !- Output Value #10",
        "4,                       !- X Value #11",
        "2,                       !- Y Value #11",
        "4,                       !- Output Value #11",
        "5,                       !- X Value #12",
        "2,                       !- Y Value #12",
        "2;                       !- Output Value #12" });

    ASSERT_FALSE(process_idf(idf_objects));

    EXPECT_EQ(0, CurveManager::NumCurves);
    CurveManager::GetCurveInput();
    CurveManager::GetCurvesInputFlag = false;
    ASSERT_EQ(1, CurveManager::NumCurves);

    // QuadraticLinear curve type, no min/max for IVs
    EXPECT_EQ("QUADRATICLINEAR", CurveManager::GetCurveType(1));
    EXPECT_EQ("TESTTABLEMINMAX", CurveManager::GetCurveName(1));
    EXPECT_EQ(1, CurveManager::GetCurveIndex("TESTTABLEMINMAX"));
    bool error = false;
    int index = CurveManager::GetCurveCheck("TESTTABLEMINMAX", error, "TEST");
    EXPECT_FALSE(error);
    EXPECT_EQ(1, index);
    Real64 min1, max1, min2, max2;
    CurveManager::GetCurveMinMaxValues(1, min1, max1, min2, max2);
    EXPECT_EQ(0, min1); 
    EXPECT_EQ(5, max1);  // Fails
    EXPECT_EQ(1, min2);  // Fails
    EXPECT_EQ(2, max2);  // Fails
    EXPECT_EQ(CurveManager::CurveType_TableTwoIV, CurveManager::GetCurveObjectTypeNum(1));

    EXPECT_DOUBLE_EQ(0.0, CurveManager::CurveValue(1, 0, 1.5)); // In-range value
    EXPECT_DOUBLE_EQ(1.0, CurveManager::CurveValue(1, 0.5, 1.5)); // In-range value, fails
    EXPECT_DOUBLE_EQ(0.0, CurveManager::CurveValue(1, -10.0)); // Minimum x
    EXPECT_DOUBLE_EQ(2.0, CurveManager::CurveValue(1, 5000)); // Maximum x, fails

    CurveManager::SetCurveOutputMinMaxValues(1, error, 0.5, 1.0);
    EXPECT_FALSE(error);
    EXPECT_DOUBLE_EQ(0.5, CurveManager::CurveValue(1, 0, 1.5)); // Value too small
    EXPECT_DOUBLE_EQ(1.0, CurveManager::CurveValue(1, 5, 1.5)); // Value too large, fails

    EXPECT_FALSE(has_err_output());
}
```

This unit test is not that great.

**Comment by rraustad** [comment]
PR https://github.com/NREL/EnergyPlus/pull/5719
