### ISSUE TITLE
HVAC Sizing Simulation crash with bad subscript

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5711]
## Issue overview

User file crashes [here](https://github.com/NREL/EnergyPlus/blob/d5db2e7f81c9d462bc85583ed347623e3384bcdf/src/EnergyPlus/SizingAnalysisObjects.cc#L254) in SizingAnalysisObjects.cc SizingLog::FillSysStep with a bad subscript.  `tmpSysStepStamp.stStepsIntoZoneStep = -1`.

Workaround is to turn off Do HVAC Sizing Simulation.
### Details

Some additional details for this issue (if relevant):
- Platform (Win64)
- Version of EnergyPlus (current develop 3b72813e45)
- helpdesk ticket number 11403
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (DefectFiles\5711)
- [x] Ticket added to Pivotal for defect (development team task)
- [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by EnergyArchmage** [comment]
Okay, I see it now, the defect file has also turned on report during warmup and the value for DataGlobals::DayOfSim is not as expected during warmup days.

**Comment by mjwitte** [comment]
Closed via #5751
