### ISSUE TITLE
Errors for Movable Insulation Found in ComputeIntThermalAbsorpFactors

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#5720]
In the current version of EnergyPlus (V8.5) while fixing a bug in another related to movable insulation, some bugs were found in the subroutine ComputeIntThermalAbsorpFactors.  This subroutine calculates interior side thermal absorption factors.  However, in looking through the code, it checks for EXTERIOR movable insulation rather than INTERIOR.  The call and all of the variables referring to exterior movable insulation need to be fixed so that this is correctly referring to interior movable insulation.  This should then be tested either with an existing file in the test suite that has movable insulation or a new file.

**Comment by Myoldmopar** [comment]
Closed via #5760
