### ISSUE TITLE
EIO and Bill of Materials

### ISSUE THREAD

**Issue by jburek** [NREL/EnergyPlus#5722]
## Issue overview

I'm having difficulties with the EIO file about material and construction. Do you perhaps know if it's compatible with any of the CAD programs? Or if there is a way to get Bill of Materials. If not I would recommend to add function that would show  Bill of Materials that is often used in CAD programs. I was able to get my building into a CAD program, but it doesn't translate all information about the materials. 

Thank you for your help. 

Jasmina

**Comment by mjwitte** [comment]
@jburek The CAD import _should_ be getting the information directly from the idf file if I'm following this correctly.   There  is no current report for a bill of materials.  The closest current output would be from  ComponentCost:LineItem which can be defined for each construction type and then would report the total area for each, but no materials detail.
