### ISSUE TITLE
Untranslated LaTex equations in Component Sizing section of Engineering Reference

### ISSUE THREAD

**Issue by wfbuhl** [NREL/EnergyPlus#5726]
Generally, the Component Sizing section of of EnergyPlus 8.5.0 as published in PDF looks like crap. Plus, we've got untranslated LaTex equations on pages 505, 523, 544, and 548. These should definitely get fixed.

**Comment by nealkruis** [comment]
@michael-okeefe can you look into this?

**Comment by michael-okeefe** [comment]
Sure, looking into it now. I can do a quick pass through. It's going to require manual correction of the LaTeX source at this point.

**Comment by Myoldmopar** [comment]
Closed via #5736
