### ISSUE TITLE
Order of setpoint managers can cause fatal missing setpoint error for Controller:WaterCoil controlling for HumidityRatio

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5729]
## Issue overview

User file failed after the SetpointManager:Scheduled objects were re-arranged.  The Controller:WaterCoil objects have Control Variable = `HumidityRatio`.  There are SetpointManager:Scheduled objects with Control Variable = MaximumHumidityRatio.  Normally this is OK, because the controller checks the all of the setpoint managers to find out if the node has either a MaximumHumidityRatio setpoint or a HumidityRatio setpoint.  But the function which checks this [SetpointManager::GetHumidityRatioVariableType](https://github.com/NREL/EnergyPlus/blob/09819874170d77a0257048ab77f435d89bcbc38e/src/EnergyPlus/SetPointManager.cc#L8236-L8248) loops over the SetpointManager:Scheduled objects and returns a value for the first setpoint manager that touches the controller sensor node.  These same nodes also have a SetpointManager:Scheduled to set a Temperature setpoint.  So, GetHumidityRatioVariableType is finding the temperature setpoint manager and returning the wrong humidity control type.

_Workaround:_ Move the humidity setpoint managers to be before the temperature setpoint managers, or change the setpoint manager control variable to `HumidityRatio` instead of `MaximumHumidityRatio`, or change the controller control variable to `TemperatureAndHumidity`.
### Details

Some additional details for this issue (if relevant):
- Platform (Win64)
- Version of EnergyPlus (v8.5.0)
- Helpdesk ticket number 11423
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (DefectFiles\5729)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #5978
