### ISSUE TITLE
Multistage heating coil doesn't honor flow ratios specific in UnitarySystemPerformance:Multispeed object and reports warning "Speed 1 Supply Air Flow Ratio During Heating Operation will be set = 1.0".

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#5737]
## Issue overview

Please change this line to a description of the defect, with useful supporting information including how the issue was found, conditions that trigger this defect, workarounds for users of the current version, and a clear description of how to validate that a fix is complete for this defect.
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- Version of EnergyPlus (if using an intermediate build, include SHA)
- Unmethours link or helpdesk ticket number
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
The heating coil is overshooting the cooling set point. 

![5737-v85](https://cloud.githubusercontent.com/assets/5778156/16196651/c4ab031a-36cc-11e6-995a-96e528cd93a6.png)

System outlet temperature is sporatic.

![5737-outlettemp](https://cloud.githubusercontent.com/assets/5778156/16196786/6e53221c-36cd-11e6-89b1-3370ccf7c008.png)

**Comment by rraustad** [comment]
See https://github.com/NREL/EnergyPlus/pull/5738

**Comment by lgu1234** [comment]
Closed.
