### ISSUE TITLE
Exponent interpolation for Table:OneIndependentVariable isn't computed

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#5739]
## Issue overview

Selecting Exponent interpolation for Table:OneIndependentVariable with the EvaluateCurveToLimits curve type results in a curve with all zero coefficients. It looks like selecting that option causes a fall-through and no fit is computed. I suggest removing this curve as an option.
### Details

Some additional details for this issue (if relevant):
- Version of EnergyPlus: 8.5
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
A mathematician shows the method used for solving the exponent case.

[LMRegressionAlgorithm.pdf](https://github.com/NREL/EnergyPlus/files/374620/LMRegressionAlgorithm.pdf)

**Comment by jmarrec** [comment]
object no longer exists. Table:IndependentVariable only now offers Linear and Cubic interpolation.
