### ISSUE TITLE
Some sizing info messages cause mixed line endings in the err output

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5745]
## Issue overview

@Myoldmopar While testing #5694 , noticed that the text editor was prompting to convert mixed line endings to DOS when opening the err output file.  Several of the error messages in this object have a newline embedded in the middle of the string, like [here](https://github.com/NREL/EnergyPlus/blob/b0dfcd9d271c8b2c1b60f8e7ca7ae973e74031e4/src/EnergyPlus/LowTempRadiantSystem.cc#L2550)

```
ShowMessage( "SizeLowTempRadiantSystem: Potential issue with equipment sizing for \nZoneHVAC:LowTemperatureRadiant:ConstantFlow = \" " +
CFloRadSys( RadSysNum ).Name + "\"." );
```

Should that work OK?  Seems this should be broken into two calls.

```
ShowMessage( "SizeLowTempRadiantSystem: Potential issue with equipment sizing for" );
ShowContinueError("ZoneHVAC:LowTemperatureRadiant:ConstantFlow = \" " + CFloRadSys( RadSysNum ).Name + "\"." );
```

And why is this ShowMessage instead of ShowWarningError? @rraustad Are these sizing messages intentionally not warnings?

These types of messages occur in other components as well.
### Details

Some additional details for this issue (if relevant):
- Platform (Win64)
- Version of EnergyPlus 8.5.0
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Yes, those should be separate calls.  We shouldn't have new lines in the error messages.  I can scan the code and find all instances of `\n` and filter it down to the instances within error messages if you'd like me to take this one.

**Comment by Myoldmopar** [comment]
https://github.com/NREL/EnergyPlus/commit/beef9b78022e348240c6572065c5b34bbb2912b8#diff-dd82b723e516edcdf293286ac3a49185R2407

**Comment by mjwitte** [comment]
@Myoldmopar OK for you to take this one.  When you search you'll find some other uses, like this in OutputProcessor::ProduceRDDMDD:

`rdd_stream << "Program Version," << VerString << ',' << IDDVerString << '\n';`
`rdd_stream << "Var Type (reported time step),Var Report Type,Variable Name [Units]" << '\n';`

These seem to work fine as-is.  And then there's also a platform-specific newline character string defined in DataStringGlobals which gets used in some places.

```
#ifdef _WIN32
    std::string const NL( "\r\n" ); // Platform newline
#else
    std::string const NL( "\n" ); // Platform newline
#endif
```

**Comment by Myoldmopar** [comment]
With some fanciful grepping, I count 8 valid hits:
- [ ] https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeCoolers.cc#L1275
- [ ] https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeCoolers.cc#L1310
- [ ] https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeCoolers.cc#L1393
- [ ] https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeCoolers.cc#L1426
- [ ] https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/LowTempRadiantSystem.cc#L2499
- [ ] https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/LowTempRadiantSystem.cc#L2523
- [ ] https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/LowTempRadiantSystem.cc#L2550
- [ ] https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/LowTempRadiantSystem.cc#L2590
