### ISSUE TITLE
WindowMaterial:Blind:EquivalentLayer Slat Angle Control not working and slat angle output always zero

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5750]
## Issue overview

WindowMaterial:Blind:EquivalentLayer slat angle control appears to always be Fixed.  Also, output for Surface Window Blind Slat Angle is always zero.

Should also check the MaximizeSolar option to see if it's working.
### Details

Some additional details for this issue (if relevant):
- Platform (Win64)
- Version of EnergyPlus (v8.5.0)
- Helpdesk ticket 11449
- Run with Chicago weather
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6191
