### ISSUE TITLE
Additional fuel type options for furnace heating coils

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5752]
## Issue overview

Similar to #5746 , furnaces currently only support gas or electric heating coils.  Propane and fuel oil are commonly used fuel types, especially for residential models.  This is similar to #5656 / #5746  which added a fuel type field to OtherEquipment.  In this case, I would suggest adding a fuel type field to Coil:Heating:Gas, and possibly change it's name to Coil:Heating:FuelFired, but maybe not at this point.
### Details

Some additional details for this issue (if relevant):
- Platform (all)
- Version of EnergyPlus (v8.5.0)
- Helpdesk ticket number 11461.
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@nmerket FYI, this request comes from PNNL for the residential prototype models.  I assume this is useful for your work as well.

**Comment by nmerket** [comment]
Thanks for alerting me to this. I think this will be useful. I think a lot of the same arguments could be made here about how and where to add the different fuel types. 

@shorowit @jonwinkler

**Comment by shorowit** [comment]
This is next on our list to tackle. See https://github.com/NREL/OpenStudio-Beopt/issues/64 for reference as well.

I think we will also want to make enhancements to the EnergyPlus output to more easily get oil, propane, etc. fuel consumption. For example, the end use table in the EnergyPlus html output only has electricity, natural gas, and "additional fuel".

**Comment by nmerket** [comment]
Right now I'm looking at the `Coil:Heating:Gas` and `Coil:Heating:Electric` objects. I'm thinking the best option would be to add a `Coil:Heating:OtherFuel` with appropriate fuel types. Any objections?

**Comment by shorowit** [comment]
Works for me. This is pretty consistent with `ElectricEquipment`, `GasEquipment`, and `OtherEquipment`.

**Comment by nmerket** [comment]
Here is the [New Feature Proposal](https://github.com/NREL/EnergyPlus/blob/coil_heating_otherfuel/design/FY2016/CoilHeatingOtherFuel.md)
