### ISSUE TITLE
Meter:Custom with Zone Packaged Terminal Air Conditioner Electric Energy causes a fatal error

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5753]
## Issue overview

Using "Zone Packaged Terminal Air Conditioner Electric Energy" in a Meter:Custom object results in some ambiguous warnings and then ultimately a fatal error:

```
   ** Warning ** Referenced variable or meter used in the wrong context "OFFICE_101_PTAC" of type "ZONEHVAC:PACKAGEDTERMINALAIRCONDITIONER"
   ** Warning ** Referenced variable or meter used in the wrong context "OFFICE_1103_PTAC" of type "ZONEHVAC:PACKAGEDTERMINALAIRCONDITIONER"

. . .

   **  Fatal  ** GetInternalVariableValue: passed index beyond range of array.
```

The warnings come from `OutputProcessor::GetMeteredVariables` which is called from the infamous `SystemReports::CreateEnergyReportStructure`.  This leaves zeroes in the system reports data structure which then trip the fatal error later.  One solution here may be to discern between custom meters and standard meters in `SystemReports::CreateEnergyReportStructure`.
### Details

Some additional details for this issue (if relevant):
- Platform (all)
- Version of EnergyPlus (v8.5.0)
- Helpdesk ticket number 11457
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #5869
