### ISSUE TITLE
Outside Movable Insulation Does Not Differentiate Between Solar and Thermal Absorptivity

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#5757]
## Issue overview

While working on a bug in the inside movable insulation, it was noticed that the inside movable insulation always grabs the solar absorptivity internally in the subroutine that evaluates inside movable insulation.  That actually is ok because code in the one place where thermal absorptivity is needed does not use the solar absorptivity returned by the subroutine call but actually grabs the correct data.  Unfortunately, in the calls for the OUTSIDE movable insulation, the call that needs the thermal absorptivity does not make this correction in the code surrounding the subroutine call.  This needs to be fixed.
### Details

Some additional details for this issue (if relevant):
- Platform: all platforms
- Version of EnergyPlus: problem was noted in Version 8.5 and has probably been there a while.
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ x ] No defect file but a new test suite file will likely be added as part of this modification
- [ x ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #5762
