### ISSUE TITLE
Chiller:CombustionTurbine autosizing not working

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5759]
## Issue overview

While working on adding autosizing heat recovery flow rate to Chiller:CombustionTurbine model, noticed that the other autosizing is broken for capacity and evaporator and condenser flow rates.  There is missing logic in the get input routine to set the *WasAutoSized boolean flags.  This was a mistake during rewrite for plant coincident sizing.  There is no integration testfile with autosizing of this model. 

Plan is to add this correction, and a new testfile that is autosizing, as part of project to fill gaps in plant equipment sizing. see https://github.com/NREL/EnergyPlus/tree/plant-autosizing-gaps
### Details

Some additional details for this issue (if relevant):
- Version of EnergyPlus 8.5
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/5000s/5759/5759-GasTurbChillerHeatRecoveryAuto.idf)  this is derived from GasTurbChiller.idf
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@EnergyArchmage Was this addressed by #5740? If so, can this be closed?

**Comment by Nigusse** [comment]
@mjwitte I have addressed autosizing problems of Engine Driven and Gas Turbine chillers along  with constant COP chiller in issues #6010 and #4991. Defect files for Gas Turbine and Engine Driven Chillers were added to issue #4991 defect folder.

**Comment by EnergyArchmage** [comment]
I lost track of what all got fixed when.  (BTW I think these changes got lost a few years ago as by a merge mistake between my last project at NREL and PNNLs sizing message stuff...)

But yes, this particular issue was fixed by #5740 and the code is here
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PlantChillers.cc#L1497
