### ISSUE TITLE
Fix for ZoneHVAC:WaterToAirHeatPump flow rates vs coil flow rates slowed HospitalLowEnergy

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5765]
## Issue overview

@rraustad PR #5632 (fix for #5430) has caused the HospitalLowEnergy test file to run very slowly.  v8.5.0 runs in 1:34 vs current develop (release build) in 32:35.

Noticed this because recent branches are showing a failure for HospitalLowEnergy in the integration coverage tests, and I'm guessing that the failure is a timeout. This was there in #5632 but I missed it.  So now it's failing in develop.  Develop also shows a performance hit which I apparently missed.
### Details

Some additional details for this issue (if relevant):
- Platform (Win64)
- Version of EnergyPlus (8.5.0-https://github.com/NREL/EnergyPlus/commit/d60482c9f60f218c0a2f4786be22f5e1dcc2cd32)
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (HospitalLowEnergy test file, should also check others with ZoneHVAC;WaterToAirHeatPump)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Yes, I didn't notice that earlier. I fixed that in PR #5754 on [this](https://github.com/NREL/EnergyPlus/pull/5754/commits/3440fb9db92513be89502f53a698cfd1a5475183) commit.

**Comment by mjwitte** [comment]
@rraustad Thanks, will review #5754 next and get it in to clean that up.

**Comment by mjwitte** [comment]
Closed via #5754
