### ISSUE TITLE
User file generating many fancoil max iteration warnings

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5770]
## Issue overview

Three files with increasing levels of electric equipment in the data hall zones.  The -P33 file has no fancoil iteration errors, -P66 has a few, and -P100 has a bunch more.  Runtime tripled between -P33 and -P100.  These files may have other issues, but there should be some way for the fancoil to come to a solution quickly even if it can't meet the load or is thrashing around to nail a tiny load.  
### Details

Some additional details for this issue (if relevant):
- Platform (Win64)
- Version of EnergyPlus (v8.5.0-https://github.com/NREL/EnergyPlus/commit/39aabddf19b23bc045868ab6effb8431c57510b8)
- helpdesk ticket number 11373
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added to EnergyPlusDevSupport\DefectFiles, run with Singapore weather
- [x] Ticket added to Pivotal for defect (development team task)
- [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Moved to RegulaFalsi and warnings are now gone in P66 version after I moved water coil sensor node to coil outlet node. Testing original P66 and P100 versions now.

**Comment by rraustad** [comment]
Original P66 runs with no fan coil or SimHVAC warnings. P100 runs with no fan coil warnings yet does have SimHVAC max iteration warnings. I wonder if the P100 SimHVAC warnings are due to air loop operation and not fan coil operation? There are so many HVAC systems in these files it's hard to tell what's causing the SimHVAC warnings.

**Comment by rraustad** [comment]
See PR #5800

**Comment by mjwitte** [comment]
Closed via #5800.
