### ISSUE TITLE
Warmup Convergence Issue in File with Only 3 Surfaces

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#5772]
## Issue overview

During the review of a fix for GitHub Issue #5261, it was discovered that there was a warmup convergence issue with a file that was testing a new error message.  It seems that there was problems converging during the warmup phase.  This needs to be further investigated to determine the cause of the convergence issue.
### Details

Some additional details for this issue (if relevant):
- Version of EnergyPlus: current version, V8.5
- Unmethours link or helpdesk ticket number
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles)
- [x] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mjwitte @Myoldmopar 

Investigation of problem:
1. As this was noted in a file with three surfaces that previously was not causing a problem in its six surface variety, the investigation started with looking at the radiation balance and the calculation of various information related to interior radiant exchange.  It was thought that perhaps there was a problem with the calculation of radiation exchange for three surfaces or less zone cases.  While not the cause of this particular problem, a defect was noted in the calculations for the view factors for two or three surface zones.  For all radiant exchange, both reciprocity and completeness are the goal.  Reciprocity is essentially that radiation is equal and opposite between two surfaces.  If the radiant exchange between two surfaces equals x, then it is a heat addition at one surface of x and a heat loss at the other surface of x.  It must be the same at both surfaces for energy.  Completeness is that all of the view factors between a particular surface and all of its surrounding surfaces is unity.  While completeness is important, it is not as critical as reciprocity.  Lacking reciprocity means an imbalance of radiation in the zone and potentially inaccuracies in the simulation or even instabilities.  Completeness is not crucial in a zone with few (three or less) surfaces since the enclosure is not really complete.  So, in calculating view factors for a zone with three or fewer surfaces, reciprocity is important.  The problem is that when the approximate view factors are “fixed” to enforce reciprocity with the current code the view factors are not checked and some surfaces do not reach completeness and others go beyond completeness meaning that the view factors add up to greater than unity.  Having view factors add up to greater than unity is physically impossible and thus should not happen in EnergyPlus.  This was verified by looking at various situations with both two and three surfaces in a zone.  When all surfaces in the zone are roughly equal in area, the completeness concern is fairly minor.  However, as the areas of the surfaces differ, view factors for the larger surfaces increase significantly past unity.  The problem gets progressively worse as the ratio of areas get larger.  For example, in the three surface zone example file added recently, the area ratios of the surfaces are approximately 1:7:7 and the fixed view factors for the larger surfaces end up adding up to 1.7.  This should not happen as completeness says they should add up to unity.  This was fixed by adding code to the FixViewFactors subroutine in HeatBalanceIntRadExchange.  The code only makes changes to zones with three or fewer surfaces.  Once the view factors have been “fixed” for reciprocity, the code now looks at the sum of view factors for each surface as well as the sum of all view factors.  If the sum of all view factors is greater than the number of surfaces (an indication that “over completeness” exists), the code uses the largest view factor summation for any surface as a scaling factor.  This scaling factor is defined as the inverse of this largest view factor summation and the fixed view factors are ALL multiplied by this factor.  By doing this, reciprocity is maintained without any further calculations.  In addition, the largest view factor sum (which corresponds to the largest surface in the space) will become unity preserving completeness for one surface in the zone.  Other surfaces will not satisfy completeness but at least they will not be “over complete” and their view factors will add up to less than one.  However, given that a three surface or less zone is not a complete enclosure, this is a problem since it simply will lead to less radiation exchange but still will maintain reciprocity.  While it is valid and useful to correct this problem, it did not resolve the warmup convergence that led to the defect.  I am attaching an Excel spreadsheet that shows the problem and also demonstrates the fix for both two and three surface zones.
   [20160803ThreeSurfaceWork.xlsx](https://github.com/NREL/EnergyPlus/files/401701/20160803ThreeSurfaceWork.xlsx)
2. Next, testing was done to attempt to determine what the problem is that is causing the warmup problem.  Looking at results stepping through the debugger, it did not appear that there was any specific issue causing a problem.  The case is very basic: a three surface zone with no internal gains.  The three surfaces are one exterior wall made of a no mass R-13 layer, one roof made of a no mass R-31 layer, and an adiabatic floor made of 4” of concrete.  The temperature progression through the warmup period is straightforward if slow.  The design day is roughly -15C during winter design day and what ends up happening is an exponential decay of temperatures in the three surfaces in an expected pattern.  There is no deviation from the pattern that I saw—no bouncing around or strange iterations.  Just an orderly decay to the solution point.  The problem is that it is simply slow in getting there.  Several things were tried: adding more exterior surfaces back in until the warmup completed before the limit.  Once a third exterior wall was added, convergence was again reached.  So, even with four surfaces in the space, convergence was not reached thus eliminating the three surface zone as a potential source of the problem.  Changing which three surfaces could cause a problem also was instructive as it showed that if the floor was eliminated or replaced with another surface (exterior wall for example) the warmup period converged.  The floor is the only surface in the file with any mass.  Changing the floor to a 2” layer of concrete instead of four reached convergence faster and the warmup period ended prior to the limit.  The problem also went away when two other things were changed.  First, when the area of the exterior wall was increased to three times its value, then the warmup period ended successfully.  Second, when the exterior wall area was left alone and the roof R-value was changed to R-13 like the exterior wall, the warmup period also ended successfully.  So, it seems that there simply isn’t enough heat transfer happening in the original input file (1ZoneUncontrolled3SurfaceZone.idf) to get the thermal mass floor to move to steady periodic in the time required.  When heat transfer to the exterior is increased by increasing wall area or decreasing the resistance of the roof provided more heat transfer to get the thermal mass floor to steady periodic during the warmup period limit.

Defect Resolution:
1. Implement view factor fix for three surface or less zones as outlined above.
2. Modify the 1ZoneUncontrolled3SurfaceZone.idf input file to increase the area of the exterior wall to four times that of the current exterior wall.  This would bring it in line with the base 1ZoneUncontrolled.idf file but as a three surface variation.
3. Enhance the documentation of the inside-heat-balance.tex file to provide more detail to the three surface or less cases.  Right now, there is one sentence to describe this.  This is not much and needs to be enhanced, particularly given this new fix.
4. Addition of a new unit test or expansion of the existing test to show that the changes made are working properly.

If you have any thoughts, questions, or reservations, please let me know.  Thanks!

**Comment by mjwitte** [comment]
@RKStrand I think I follow all of this, and the solution sounds reasonable.

**Comment by RKStrand** [comment]
@mjwitte Great--thanks, Mike!  I'll proceed on that basis and hope to have this wrapped up relatively soon.  I'll let you and Edwin know when it is ready for review.

**Comment by mjwitte** [comment]
Closed via #5804
