### ISSUE TITLE
AvailabilityManager:OptimumStart not working as expected - appears to be crosstalk between systems

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5783]
## Issue overview

_From user:_
I'm using AvailabilityManager:OptimumStart to start VAV system 'AHU.SP' up to 1 hour early in the attached IDF. The results show the AHU starting at the earliest possible time (5 AM) on all operating days of the year in 'OptStart.idf', regardless of zone temperature conditions. The normal start time is 6 AM which can be seen working normally in 'NoOptStart.idf'

I tried to limit the applicability by setting the applicability schedule in this object to zero when average temperature of connected zones is between 18 to 24 (OptStart_AppSched_18-24.idf). The applicability schedule seems to have no effect either. In another attempt, I set the applicability schedule to always zero. My expectation was that Optimum Start would not be triggered and the AHU would start as per it's fan schedule (6AM), but it still started at the earliest allowable optimum start time (5AM).

_Reply to user:_
It appears something is broken.  I added some more reporting and then decided just to see what would happen if I changed the Maximum Value for Optimum Start Time from 1 to 5 just for system SP.  This resulted _all_ of the systems starting 5 hrs early for two days and then _none_ of the systems started early after that.
### Details

Some additional details for this issue (if relevant):
- Platform (Win64)
- Version of EnergyPlus (v8.5.0)
- helpdesk ticket 11489
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Only works with single air loop, and even then there are deficiencies.

**Comment by rraustad** [comment]
See PR https://github.com/NREL/EnergyPlus/pull/5787

**Comment by Myoldmopar** [comment]
Closed via #5787
