### ISSUE TITLE
"integration.5ZoneElectricBaseboard"  test fails when swap "SizingPeriod:DesignDay" objects' positions in 5ZoneElectricBaseboard.idf

### ISSUE THREAD

**Issue by kburova** [NREL/EnergyPlus#5806]
## Issue overview

If I swap positions of two _SizingPeriod:DesignDay_ objects in [5ZoneElectricBaseboard.idf ](https://github.com/NREL/EnergyPlus/blob/fef0a0afbedd89d4d1ae22ea6d8262d9082108a2/testfiles/5ZoneElectricBaseboard.idf#L163) file it causes EnergyPlus simulation to fail. 
At some point of simulation, [at the line of code](https://github.com/NREL/EnergyPlus/blob/fef0a0afbedd89d4d1ae22ea6d8262d9082108a2/src/EnergyPlus/ElectricBaseboardRadiator.cc#L845), an _if_ statement evaluates to _true_ which would not happen if objects were in a opposite order.
Later on, inside of that _if_ statement, [DistributeBBElecRadGains()](https://github.com/NREL/EnergyPlus/blob/fef0a0afbedd89d4d1ae22ea6d8262d9082108a2/src/EnergyPlus/ElectricBaseboardRadiator.cc#L858) function gets called what brings us to [this line of code](https://github.com/NREL/EnergyPlus/blob/fef0a0afbedd89d4d1ae22ea6d8262d9082108a2/src/EnergyPlus/ElectricBaseboardRadiator.cc#L1094) eventually, and on a second iteration of that _for_ loop _ZoneNum_ gets assigned a value of _0_ and so next value assignment to _QElecBaseboardToPerson( ZoneNum )_ causes an insertion failure because arrays start with index 1.

Going back to that [_if_ statement](https://github.com/NREL/EnergyPlus/blob/fef0a0afbedd89d4d1ae22ea6d8262d9082108a2/src/EnergyPlus/ElectricBaseboardRadiator.cc#L845), when objects are in their original order, _(QZnReq > SmallLoad)_ part of _if_ statement evaluates to false, but when we swap objects in .idf file, this part of _if_ statement evaluates to true because of _QZnReq_ value change.
_QZnReq_ gets a value from _ZoneSysEnergyDemand( ZoneNum ).RemainingOutputReqToHeatSP_ [here](https://github.com/NREL/EnergyPlus/blob/fef0a0afbedd89d4d1ae22ea6d8262d9082108a2/src/EnergyPlus/ElectricBaseboardRadiator.cc#L834) and it depends on which environment (Object's name in this case) was processed last. If it's **CHICAGO_IL_USA ANNUAL COOLING 1% DESIGN CONDITIONS DB/MCWB** the value is -5034.271, if it's **CHICAGO_IL_USA ANNUAL HEATING 99% DESIGN CONDITIONS DB** the value is 1215.804. 
### Details
- Platform (Mac OSX, 10.11.5)

**Comment by mbadams5** [comment]
Do either of you two (@Myoldmopar or @EnergyArchmage) have any idea on this? This fails with an assertion error in debug build. Defect file uploaded to DevSupport. We are hitting this on the InputProcessor refactor.

**Comment by EnergyArchmage** [comment]
Bummer, these can be difficult find.  We used to run "reverse DD" tests fairly often to catch this sort of thing (and I shudder thinking about all the time spent tracking such things down).  

Running both IDFs in the debugger, I see what is going wrong.  When the system first runs on a cooling day, the heating calculation routine doesn't execute the first time the baseboard gets called.  But when the system first runs on a heating day, the calc routine does have a heating load and tries to distribute the radiant gains.  But the second radiator has not yet been called and it's zone index is not yet set.  It is a  flaw in the intialization here, should set all the zone indexes before the calc routine gets called, like during get input. 

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ElectricBaseboardRadiator.cc#L600

**Comment by EnergyArchmage** [comment]
okay, quick fix in pr #5811  that you can incorporate to get past this for your integration testing.  It still needs a unit test.

**Comment by EnergyArchmage** [comment]
looks like ZoneHVAC:Baseboard:RadiantConvective:Water, ZoneHVAC:Baseboard:RadiantConvective:Steam,  will have the same problem because they have the same code pattern.  

Adding a better fix for all three radiant baseboards to the pull request
