### ISSUE TITLE
Remove multithreading option from EP-Launch

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#5816]
EP-Launch has an option for "Disable Multi-Threading" and some related lines in [Epl-run.bat](https://github.com/NREL/EnergyPlus/blob/79c5313d90a1d2e256d21793c9be7f33bf3b59b7/scripts/Epl-run.bat#L324-L328) that need to be cleaned up following the removal of the OpenMP code remnants that were removed in PR #5812 
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #5840
