### ISSUE TITLE
Bug fix for variable speed heat pump water heater coil, COP calculation

### ISSUE THREAD

**Issue by shenb** [NREL/EnergyPlus#5819]
## Issue overview

when developing a new module, we found a bug in VariableSpeedCoils.cc. CalcVarSpeedHPWH(), the HPWH coil COP was calculated in a reversed way, and thus, leading to wrong power calculations. All versions before 8.5 had wrong power calculations related to variable-speed heat pump water heater module. 

for a single line for codes: 
previous error: 
        COP = 1.0/VarSpeedCoil( DXCoilNum ).MSRatedCOP( SpeedCal ) \* COPTempModFac \* COPAirFFModFac \* COPWaterFFModFac;

correction: 
        COP = VarSpeedCoil( DXCoilNum ).MSRatedCOP( SpeedCal ) \* COPTempModFac \* COPAirFFModFac \* COPWaterFFModFac;
### Details

Some additional details for this issue (if relevant):
- Platform --- ( all Operating systems, version 8.4 and before)
- Version of EnergyPlus --- (version 8.4 and before)
- Unmethours link or helpdesk ticket number --- no ticket number related. It was identified when developing a new function based on it. 
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here) --VariableSpeedCoils.cc
- [ ] Ticket added to Pivotal for defect (development team task) -- no ticket related, it was corrected when developing another feature. 
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)  --- [NREL/EnergyPlus] Add Air Source Integrated Heat Pump (#5584)

**Comment by mjwitte** [comment]
Closed via #5584.
