### ISSUE TITLE
IOReference Errors for HeatExchanger:AirToAir:SensibleAndLatent

### ISSUE THREAD

**Issue by dstuder** [NREL/EnergyPlus#5820]
There are several errors in the documentation for object 1.51.2 HeatExchanger:AirToAir:SensibleAndLatent:
1. Figure 1.164 has no caption. However, it appears that a legacy caption is misplaced lower on the page: "Figure 150. Schematic of the Sensible and Latent Air-to-Air Heat Exchanger"
2. Two headers are included for Table 1.48. The first one (at the bottom of page 2086) is correct, although the Heating/Cooling column labels are misaligned. The second (at the top of page 2087) is missing the Heating/Cooling column headers altogether.
3. The second instance of "Entering supply air temperature" in Table 1.48 (page 2087) should read "Entering **exhaust** air temperature".

**Comment by Myoldmopar** [comment]
Closed via #5875
