### ISSUE TITLE
Heating water coil sizing mixing up hot and cold initialization temps

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5821]
from code inspection, specific heat is calculated using DataGlobals::HWInitConvTemp but density is calculated using DataGlobals::CWInitConvTemp, here:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ReportSizingManager.cc#L1421
## Issue overview

Please change this line to a description of the defect, with useful supporting information including how the issue was found, conditions that trigger this defect, workarounds for users of the current version, and a clear description of how to validate that a fix is complete for this defect.
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- Version of EnergyPlus (if using an intermediate build, include SHA)
- Unmethours link or helpdesk ticket number
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
I have seen such use in more than one place. See some of the discussion in bug issue #5442 and PR #5774 are relevant for this bug issue.

**Comment by Myoldmopar** [comment]
Closed via #6813
