### ISSUE TITLE
Followup for new cooling panel ZoneHVAC:CoolingPanel:RadiantConvective:Water

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5823]
## Issue overview

ZoneHVAC:CoolingPanel:RadiantConvective:Water was added in #5027.  Some outstanding issues remain:
- [x] Fix sizing - scalable sizing input fields were added to IDD and input processing in https://github.com/NREL/EnergyPlus/pull/5027/commits/7eb88d9c799aa3c640f81b1d006e781bf62e92ab but it doesn't appear that they are implemented in the sizing function for this component.  *The sizing function was added later in Sep 2016 with https://github.com/NREL/EnergyPlus/commit/3944eb16f10b7aa98ea06e52c6be3ae9eceeac11 @RKStrand tested the various options in Nov 2017 and this is working.*
- [x] Some minor OO restructuring - move functions specific to this object to be member functions of the CoolingPanelSimple struct
- [x] Review new doc sections one more time - some of the engineering ref equations need some fixing (sub/superscripting out of place), add the actual object name at the beginning of the engineering reference section so it can be found
- [x] Change the SizeCoolingPanelUA so rather than returning the error status via the reference it returns true on success and false on failure? It's a more "C++" way of doing this.
- ~Annual simulations of the new tests files have many "ControlCompOutput: Maximum iterations exceeded"errors~ (will be addressed in #5884)
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- Version of EnergyPlus (if using an intermediate build, include SHA)
- Unmethours link or helpdesk ticket number
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mjwitte Could you elaborate on the "fix sizing" and "minor OO restructuring" comments above?  Maybe this was already discussed and I just need to refresh my memory?

**Comment by RKStrand** [comment]
@mjwitte Handling baseboard issues under GitHub Issue #5884 as this really has nothing to do with the new cooling panel model.  It affects all input files with baseboards.  Other test suite input files show the same behavior when an annual run is launched.

**Comment by mjwitte** [comment]
@RKStrand Expanded descriptions at the top of this issue.  Will forward prior e-mail thread regarding OO changes and will cc @Myoldmopar

**Comment by RKStrand** [comment]
@jasondegraw @mjwitte Adding another OO type task requested by Jason during the review of another defect to this defect:

change the SizeCoolingPanelUA so rather than returning the error status via the reference it returns true on success and false on failure? It's a more "C++" way of doing this. (See above issue overview where this has been added.) (Ended up doing this as part of Issue #6098, Pull Request 6181)

**Comment by RKStrand** [comment]
@Myoldmopar @mjwitte Creating a pull request for this shortly.  Please check and see if all of your concerns were addressed.  Thanks!

**Comment by Myoldmopar** [comment]
Closed via #6395
