### ISSUE TITLE
Daylighting followup

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5825]
## Issue overview

Followups from DElight integration #5725 
- [x] Restore delight stream and unit test or remove commented code in simulationmanager.
- [x] Question about eio diffs - DElight reporting is now for two zones instead of one.  Is this correct?
- [x] Complete or remove TEST_F(EnergyPlusFixture, DElightManagerF_InputGenerator_Test)
- [x] Add transition of daylighting reference point output:variable key names
- [x] Make Glare Calculation Azimuth Angle of View Direction Clockwise from Zone y-Axis not required
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- Version of EnergyPlus (if using an intermediate build, include SHA)
- Unmethours link or helpdesk ticket number
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
The EIO changes were incorrect, added code to detect condition.

**Comment by Myoldmopar** [comment]
Closed via #5826
