### ISSUE TITLE
Coil:Heating:Gas transition is missing from develop

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5833]
## Issue overview

Somehow the transition for Coil:Heating:Gas got lost from the transition source during the flurry of merges.  Need to double check rules file and transition source for anything else that may have been stomped on.
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- Version of EnergyPlus (if using an intermediate build, include SHA)
- Unmethours link or helpdesk ticket number
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
@mjwitte I can roll this into my work over on #5805, so I'll handle this unless you say otherwise.

**Comment by mjwitte** [comment]
Closed via #5836
