### ISSUE TITLE
IDF Editor update for new units conversions 

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5842]
Many unit conversion errors are showing in the IDF Editor for the new IDD changes
![capture](https://cloud.githubusercontent.com/assets/2582150/18051287/1eb280ae-6db9-11e6-9c7f-491e3f5db530.PNG)

**Comment by JasonGlazer** [comment]
@mjwitte and @Myoldmopar we should take care of this before building the final installer

**Comment by mjwitte** [comment]
@JasonGlazer I do not see any errors with the v8.5 IDF Editor and current develop IDD.  I think those were addressed [here](https://github.com/NREL/EnergyPlusBuildSupport/pull/25) and in #5509.

**Comment by JasonGlazer** [comment]
That's weird, I have a repo that I do install builds on and that is what was happening when I testing for #5105.

**Comment by JasonGlazer** [comment]
Sorry, not so weird #5841 hasn't been merged yet.
