### ISSUE TITLE
Transition for VAV terminal damper heating action

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5847]
## Issue overview
#5646 added a new choice for VAV terminal "Damper Heating Action" and changes the default.  Transition rules and code need to be added.
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- Version of EnergyPlus (if using an intermediate build, include SHA)
- Unmethours link or helpdesk ticket number
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Fixed via #5864
