### ISSUE TITLE
EnergyPlusFixture.PlantHXModulatedDualDefectFileLo unit test fails because of the order of "PlantLoop" objects

### ISSUE THREAD

**Issue by kburova** [NREL/EnergyPlus#5848]
## Issue overview

[Unit test](https://github.com/NREL/EnergyPlus/blob/input_processor_refactor/tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc#L1162) fails in [this build](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-1b73d8d6c909e7f69071c85a0d03f0e9988748ed-x86_64-MacOS-10.9-clang.html). It says:

Note: Google Test filter = EnergyPlusFixture.PlantHXModulatedDualDeadDefectFileLo
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from EnergyPlusFixture
[ RUN ] EnergyPlusFixture.PlantHXModulatedDualDeadDefectFileLo
/Users/kbenne/ci_runs/EnergyPlus-1b73d8d6c9-x86_64-clang/tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc:2235: Failure
The difference between DataLoopNode::Node(3).Temp and 20.0 is 0.59196613080090188, which exceeds 0.01, where
DataLoopNode::Node(3).Temp evaluates to 19.408033869199098,
20.0 evaluates to 20, and
0.01 evaluates to 0.01.
[ FAILED ] EnergyPlusFixture.PlantHXModulatedDualDeadDefectFileLo (249 ms)
[----------] 1 test from EnergyPlusFixture (249 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (578 ms total)
[ PASSED ] 0 tests.
[ FAILED ] 1 test, listed below:
[ FAILED ] EnergyPlusFixture.PlantHXModulatedDualDeadDefectFileLo

First , I checked that Node(3) and in fact it should check Node(4).
Different indexing is caused by storing input objects in json format (they get sorted in lexicographical order).
Fixing indexing made test pass individually but it still fails when all test are run. 

I decided to change [idf input](https://github.com/NREL/EnergyPlus/blob/input_processor_refactor/tst/EnergyPlus/unit/PlantHeatExchangerFluidToFluid.unit.cc#L1167) in unit test and placed "PlantLoop" objects in a same order they would appear in json. I ran released version of EnergyPlus and it failed. So this means that an outcome of the EnergyPlus code depends on order of objects in idf file.

For reference, index 3 in released version of Energy+ and index 4 in json_input version of Energy+ for Node() array corresponds to : 
 NodeNumOut of "TRANSFER SUPPLY OUTLET PIPE", which is a component of
 "TRANSFER SUPPLY OUTLET BRANCH" in "TRANSFER SUPPLY BRANCHES" OF "TRANSFER LOOP (part of PlantLoop data)

**Comment by kburova** [comment]
@mbadams5 take a look at this please

**Comment by EnergyArchmage** [comment]
Is "lexicographical order" going to be predictable on all platforms?  If not it seems that all unit tests that use IDF input would need to be rewritten to detect indexes rather than hard code them.

**Comment by mbadams5** [comment]
@EnergyArchmage Yes it should be consistent. It is how `std::map` sorts keys so it can have log(n) find operations.

Yes the unit tests should be written without hard code indexes but we have already changed many of these and they all pass now. This is more of a case where EnergyPlus depends on the order of input objects. Similar to the other defect you fixed a little bit ago.

I can create a defect idf file if that helps (anyone) to address this issue.

**Comment by jmarrec** [comment]
Is this issue still a thing or it's way outdated? @mbadams5 ?

**Comment by mbadams5** [comment]
It is outdated. We subsequently switched to using IDF-order when reading an IDF and these kinds of problems went away.
