### ISSUE TITLE
Can't build EnergyPlus on Centos 6.6

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#5854]
@Myoldmopar @lefticus 

I've tried building EnergyPlus 8.6 on Centos 6.6.  The default compiler is gcc 4.4 which doesn't seem to support c++11.  I get compiler crashes using gcc 4.7 and 4.8.  When I tried to install clang 3.4 I get GLIBCXX_3.4.15, GLIBC_2.15 and GLIBC_2.14 not found.  What compiler should I use?

**Comment by Myoldmopar** [comment]
Energyplus won't build after 1145pm local time.

**Comment by macumber** [comment]
Resets at midnight?  Can I feed it after midnight?

**Comment by mbadams5** [comment]
@macumber which point release of GCC 4.8 was it? You need to use 4.8.2+. You should download and use [DevTool set 2.1 or greater](https://linux.web.cern.ch/linux/devtoolset/) Or you can use the newer [Software Collections](https://linux.web.cern.ch/linux/scientific6/docs/softwarecollections.shtml) to get even newer versions of GCC. You can also download clang from [EPEL packages](https://fedoraproject.org/wiki/EPEL)

**Comment by macumber** [comment]
I am on CentOS 6.6, I tried installing devtoolset 2.1 with [these](http://linuxtoolkit.blogspot.com/2014/11/install-gcc-481-and-other-scientitic.html) instructions:

```
# cd /etc/yum.repos.d/ 
# wget -O /etc/yum.repos.d/slc6-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo
# yum install devtoolset-2 --nogpgcheck
# scl enable devtoolset-2 bash
```

gcc -v gives `gcc version 4.8.2 20140120 (Red Hat 4.8.2-15) (GCC)` (which seems right for devtoolset 2.1)

When I compile E+ I get:

```
[ 28%] Building CXX object src/EnergyPlus/CMakeFiles/energypluslib.dir/AirflowNetworkBalanceManager.cc.o
In file included from /home/dmacumbe/EnergyPlus/src/EnergyPlus/DataHeatBalance.hh:75:0,
             from /home/dmacumbe/EnergyPlus/src/EnergyPlus/AirflowNetworkBalanceManager.cc:83:
/home/dmacumbe/EnergyPlus/src/EnergyPlus/DataSurfaces.hh: In function ‘bool EnergyPlus::DataSurfaces::operator==(const EnergyPlus::DataSurfaces::Surface2D&, const EnergyPlus::DataSurfaces::Surface2D&)’:
/home/dmacumbe/EnergyPlus/src/EnergyPlus/DataSurfaces.hh:556:38: internal compiler error: Segmentation fault
return eq( a.vertices, b.vertices );
```

**Comment by macumber** [comment]
I'm also starting to feel weird after working on E+ after midnight last night...

![gremlins-2-wallpaper_53441_7176](https://cloud.githubusercontent.com/assets/1327850/18413059/1feb01ca-775b-11e6-9ec5-56600364a837.jpg)

**Comment by mbadams5** [comment]
@macumber It may require 4.8.4+ then, I can't remember exactly. If so then you'll need devtoolset 3.0+

**Comment by macumber** [comment]
Thanks @mbadams5 that worked for me!  I was not able to install devtoolset 3 on CentOS 6.6, so getting this to work with 2.1 was great.  Watch out for any signs of gremlinification!

**Comment by macumber** [comment]
@mbadams5 I spoke too soon, when I tried to make a package with the fortran components I am getting this error.  Do you see this as well?

```
Run CPack packaging tool...
CPack: Create package using TBZ2
CPack: Install projects
CPack: - Run preinstall target for: EnergyPlus
CPack: - Install project: EnergyPlus
 +++ AutoDocs: Completed processing output variable audit: processed 3795 calls
 +++ AutoDocs: Completed processing example file summary: processed 565 example files
 +++ AutoDocs: Completed processing example file links summary: processed 565 example files
CMake Error at /usr/share/cmake-3.6/Modules/GetPrerequisites.cmake:824 (message):
  /usr/bin/ldd failed: 1

Call Stack (most recent call first):
  /home/dmacumbe/EnergyPlus/cmake/ProjectMacros.cmake:196 (get_prerequisites)
  /home/dmacumbe/EnergyPlus/build/src/ExpandObjects/cmake_install.cmake:48 (fixup_executable)
  /home/dmacumbe/EnergyPlus/build/cmake_install.cmake:444 (include)


CPack Error: Error when generating package: EnergyPlus
make: *** [package] Error 1
```

**Comment by mbadams5** [comment]
@macumber I didn't try to package, but just from looking you may not be using the correct ldd.

**Comment by macumber** [comment]
Thanks Mark, I am just using the ldd that comes with CentOS 6.6, which ldd should I be using?  devtoolset does not seem to come with ldd

```
[dmacumbe@localhost build]$ which gcc
/opt/rh/devtoolset-2/root/usr/bin/gcc
[dmacumbe@localhost build]$ which ldd
/usr/bin/ldd
[dmacumbe@localhost build]$ ls /opt/rh/devtoolset-2/root/usr/bin/ld*
ld       ld.bfd   ld.gold  
```

**Comment by jasondegraw** [comment]
Reopening because the second issue that @macumber had is still a thing on Linux, at least on Ubuntu 16.04. CMake is running ldd on a static executable and then bombing out. This may be a CMake version issue, I am not certain.

**Comment by jasondegraw** [comment]
I believe it is a CMake issue. The 14.04 version of CMake is 2.8.12, and that implementation of get_prerequisites doesn't check the ldd return value. Later versions (not sure when the change happened) do check the return value:

https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/GetPrerequisites.cmake#L856

So looks like we shouldn't call get_prerequisites on static executables.

**Comment by mbadams5** [comment]
@jasondegraw You are correct. I have a working solution for 16.04 and I assume this will (properly) fix the issue Dan was having on CentOS with CMake 3.6.

**Comment by jasondegraw** [comment]
@mbadams5 I believe he was using very recent CMake, so I think so. I fixed it by reworking the Fortran CMakeLists.txt files to only call get_prerequisites if the build was not static. We should coordinate.
