### ISSUE TITLE
RunPeriodControl:DaylightSavingTime not respected with UseWeatherFile in Day of Week for Start Day

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5862]
When UseWeatherFile is set for the Day of Week for Start Day in RunPeriod, the daylight savings time start and end date do not seem to correspond to the RunPeriodControl:DaylightSavingTime specifications.

Reported on helpdesk ticket #11549

Defect files in 5862 folder.
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jasondegraw** [comment]
@JasonGlazer @Myoldmopar Setting aside for the moment that we do DST at midnight (🤦‍♂️ x approximately a billion), I haven't been able to verify that this is an issue any longer. The story is about the same as #5818. The defect file updated to 9.0 behaves as expected, so barring additional info and/or objections, we should close this issue.

**Comment by JasonGlazer** [comment]
If it is no longer an issue, close the issue.

**Comment by jasondegraw** [comment]
Closing, reopen if the problem reappears.
