### ISSUE TITLE
Processing of non-rectangular window surfaces

### ISSUE THREAD

**Issue by rongpengzhang** [NREL/EnergyPlus#5878]
## Issue overview

Current EnergyPlus prohibits building models with 4-sided but non-rectangular window or glassdoor surfaces. Such surfaces lead to severe errors in the surface pre-processing and the termination of the simulation.

```
   ** Severe  ** ProcessSurfaceVertices: Suspected 4-sided but non-rectangular Window, Door or GlassDoor:
   **   ~~~   ** Surface=WF-1
   **  Fatal  ** Errors found in Building Input, Program Stopped
```

This strict restriction is related with the calculation of Nusselt number  at window air gaps. We find that this restriction can be released by transforming the surface into an equivalent rectangular surface with the same area and aspect ratio. This approach is similar to the approach implemented in the current EnergyPlus to handle triangular windows. The current severe error caused by the detection of non-rectangular window will be replaced by a warning message before the shape transformation.
### Details

Some additional details for this issue (if relevant):
- Platform Win64
- Version of EnergyPlus 8.5.0
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (list location of defect file here)
- [x] Ticket added to Pivotal for defect (development team task)
- [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

[Uploading 5ZoneAirCooled_with non-rectangular window.zip…]()

**Comment by mjwitte** [comment]
Closed via #5920
