### ISSUE TITLE
Issues found during 8.6.0 Installer Testing

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5883]
A place to keep a checklist of things to do before callling 8.6.0 done
- [x] Update README
- [ ] Update EP-Launch trigger file
- [ ] Update energyplus.net
- [x] 1ZoneDataCenterCRAC_wPumpedDXCoolingCoil in San Fran results in a severe on fresh Win 8.1 VM
- [x] Documentation still says 8.5 and March 31, 2016

**Comment by Myoldmopar** [comment]
## Mac

# Installation
- Typical 'have to right click to open' approach
- Otherwise successful

# First tests - command line
- Verify version:

```
$ EnergyPlus --version
EnergyPlus, Version 8.6.0-fc5b8c5c90
```
- Run a simulation with HVACTemplate:

```
$ EnergyPlus -x -r -d /tmp/myoutput -w /Applications/EnergyPlus-8-6-0/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw /Applications/EnergyPlus-8-6-0/ExampleFiles/HVACTemplate-5ZoneBaseboardHeat.idf
ExpandObjects Started.
 Begin reading Energy+.idd file.
 Done reading Energy+.idd file.
ExpandObjects Finished. Time:     0.037
EnergyPlus Starting
EnergyPlus, Version 8.6.0-fc5b8c5c90, YMD=2016.09.25 07:05
Processing Data Dictionary
****SNIP****
Starting Simulation at 07/07 for Chicago Ohare Intl Ap IL USA TMY3 WMO#=725300
Writing tabular output file results using HTML format.
Writing final SQL reports
 ReadVarsESO program starting.
 Requested ESO file=eplusout.eso
 does not exist.  ReadVarsESO program terminated.
 ReadVarsESO program terminated.
 ReadVarsESO program starting.
 Requested ESO file=eplusout.mtr
 does not exist.  ReadVarsESO program terminated.
 ReadVarsESO program terminated.
EnergyPlus Run Time=00hr 00min  0.79sec
```

# Other Tests
- Open EP-Launch-Lite
  - Shows version 0.0.0 in Spotlight -- may be a cache issue on my local machine
  - Changed to Spanish, ran different HVACTemplate file, success
- Documentation installed and looks good.

I think that's about all I will do on Mac.  I'll test Linux later.

**Comment by Myoldmopar** [comment]
## Linux

EnergyPlus itself worked well.  I tried to run IDFVersionUpdater, but ran into issues.  Went back to Mac install and had trouble there as well.  I may try to fix the issues, but then again, I may just spend another 2 or 3 days making my own IDFVersionUpdater tool like with EP-Launch-Lite, and release it separately after the release.  That's my current plan.  So this won't hold up the release.  @mjwitte as you have time, could you put it through the rigors on Windows?  Thanks!

**Comment by JasonGlazer** [comment]
Can you post an issue related to IDFVersionUpdater?

**Comment by EnergyArchmage** [comment]
I have been checking out the windows x64 version, on a polluted Win10 OS.  IDFVersionUpdater worked. 
- [ ] minor, but is it too late to add an update of LCCusePriceEscalationDataSet2016.idf?   if this issue https://github.com/NREL/EnergyPlus/issues/5873 was ready.

**Comment by JasonGlazer** [comment]
@EnergyArchmage #5873 is not ready but could be if it is important for this release

**Comment by mjwitte** [comment]
Tested on Win10 with lots of other EnergyPlus version installed. Ran various example files (including params, HVACTemplate, basement, delight, ep-macro), ran transition, opened outputs, opened IDF Editor, IDF Version Updater (transitioned v8.2 5ZoneAirCooled to v8.6) - no problems found.
- [ ] One minor detail (which has been happening since v8.3) Under ExampleFiles, there is an empty "performance" folder.

**Comment by JasonGlazer** [comment]
I just ran IDFVersionUpdater on a Mac OS X Yosemite (10.10.5) and it transitioned files from 8.3, 8.4 and 8.5 just fine. @Myoldmopar could you describe what was failing?

Also EP-Launch-Lite does not seem to be launching. Could it be the PreProcess directory?

**Comment by Myoldmopar** [comment]
OK, I anticipate pushing the button today, hopefully this morning.  
- @JasonGlazer do you want to push forward with the LCC 2016 data?  
- @mjwitte I'll remove the performance folder
- @JasonGlazer  IDFVersionUpdater: It couldn't launch the app for some reason; I presume my machine configuration
- @JasonGlazer Does it show anything when your EP-Launch-Lite won't launch?  Launching **so** lite-ly you don't even notice?? 😉 

Seems like we need to fill this in with one more person to determine if it is just a fluke or something else:

| Application | Works for @myoldmopar | Works on @jasonglazer | Works for third party |
| --- | --- | --- | --- |
| IDFVersionUpdater | NO | YES | ? |
| EP-Launch-Lite | YES | NO | ? |

**Comment by mjwitte** [comment]
@RKStrand Has a Mac, yes?

**Comment by JasonGlazer** [comment]
@Myoldmopar what is weird about EP-Launch-Lite is that the version I tested just the other day is working fine. But when I try the version with the installer, it shows up for a moment in the dock and then disappears. No window opens or anything. Did you change anything when you integrated it with EnergyPlus 8.6.0 installer?

**Comment by Myoldmopar** [comment]
I don't believe so, @JasonGlazer.  And directly launching the one from my 8.6 installer works fine.  Gremlins...

**Comment by Myoldmopar** [comment]
OK, I was able to reproduce the EP-Launch-Lite problem on a coworker machine.  I think I know the problem.  I'm updating that now.  I also have the performance folder removed, and the README updated.  Do you plan on doing the LCC 2016 change @JasonGlazer?  I hope to wrap this up before lunch.

**Comment by JasonGlazer** [comment]
I think I will wait until the next release on the LCC update.

**Comment by Myoldmopar** [comment]
Dumb.  OK, I found the EP-Launch-Lite problem.  The py2app application bundles up some blobs deep inside the .app/ folder, and some of those were being ignored by our .gitignore file, and so they weren't getting committed to the repo, and thus the program wouldn't run.  I was able to reproduce it locally, fixed it and it runs now.  I think we are done.  I am tagging develop right now as v8.6.0.

**Comment by Myoldmopar** [comment]
Hmm, just noticed the comments above about DataCenter failing and the documentation version numbers.  OK, almost there...

**Comment by Myoldmopar** [comment]
As for the data center file, it runs in Denver, and fails elsewhere due to the coil design conditions.  Error file is clear about this.  It won't hold the release.  File a ticket if necessary.

As for the documentation, I updated the date and version number and merged it in.  **NOW** I'm tagging develop as v8.6.0
