### ISSUE TITLE
Trigger CI to build more package types

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5887]
It would be awesome if CI could go ahead and post the following package types:
- Windows 32-bit zip
- Windows 64-bit zip
- Darwin 64-bit bz2
- Linux 64-bit bz2

I think it's just a matter of CMake flags, need to test and see.

**Comment by jmarrec** [comment]
@Myoldmopar Given the list of packages (and under the assumption that a tar.gz on a *Nix system is as fine as a .bz2).

I think the only one potentially missing would be the `EnergyPlus-9.0.1-bb7ca4f0da-Windows-i386.zip`.

Is this 32-bit zip needed? Otherwise, this could be closed.

**Comment by Myoldmopar** [comment]
We don't need a 32-bit Windows, good catch.  I'll close this.
