### ISSUE TITLE
IDFVersionUpdater issues

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5889]
IDFVersionUpdater has intermittent problems, and is written in a language that is difficult to maintain/improve for the broad team.  It should probably be rewritten in something else.

**Comment by JasonGlazer** [comment]
@Myoldmopar could you describe the problem more specifically? In the past, most of the issues have actually been from the various Transition programs being called.

**Comment by Myoldmopar** [comment]
It won't launch on my machine.

**Comment by JasonGlazer** [comment]
What OS?

**Comment by Myoldmopar** [comment]
Mac

**Comment by JasonGlazer** [comment]
What version? Is this the case with the 8.6.0 install?

**Comment by Myoldmopar** [comment]
I didn't test with the very final install candidate, but yeah during the initial testing of 8.6 I couldn't open it.  And since I don't have a RealBasic compiler, I wasn't going to spend my time investigating any fixes to that codebase.
