### ISSUE TITLE
ZoneHVAC:Baseboard:RadiantConvective:Electric user-specified and design sizes are reporting the same value

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5890]
## Issue overview

Sizing logic is broken in ZoneHVAC:Baseboard:RadiantConvective:Electric.  For sizing method = HeatingDesignCapacity (have not checked other methods), the reported values for Design Size and User-Specified capacity are the same.  In this test file, one baseboard is hard-sized at 1000W and the other is autosized.  Quick inspection of ElectricBaseboardRadiator::SizeElectricBaseboard shows that it's setting ZoneEqSizing( CurZoneEqNum ).DesHeatingLoad and TempSize (which gets passed in to RequestSizing) to each other.  Looks wrong.

```
 Component Sizing Information, ZoneHVAC:Baseboard:RadiantConvective:Electric, BLOCK1:ZONE1 ELECTRIC RADIATOR, Design Size Heating Design Capacity [W], 1000.00000
 Component Sizing Information, ZoneHVAC:Baseboard:RadiantConvective:Electric, BLOCK1:ZONE1 ELECTRIC RADIATOR, User-Specified Heating Design Capacity [W], 1000.00000
 Component Sizing Information, ZoneHVAC:Baseboard:RadiantConvective:Electric, BLOCK1:ZONE2 ELECTRIC RADIATOR, Design Size Heating Design Capacity [W], 1876.88037
 Component Sizing Information, ZoneHVAC:Baseboard:RadiantConvective:Electric, BLOCK1:ZONE2 ELECTRIC RADIATOR, User-Specified Heating Design Capacity [W], 1876.88037
```
### Details

Some additional details for this issue (if relevant):
- Win64
- Version of EnergyPlus 8.6.0
- helpdesk ticket 11523
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6123
