### ISSUE TITLE
OA system controller list apparently requires the OA controller to come first followed by water coil controllers

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5891]
## Issue overview

This input

```
AirLoopHVAC:ControllerList,
    Central_AHU OA System Controllers,  !- Name
    Controller:WaterCoil,    !- Controller 1 Object Type
    Central_AHU Dehum Coil Controller,  !- Controller 1 Name
    Controller:OutdoorAir,   !- Controller 2 Object Type
    Central_AHU OA Controller;  !- Controller 2 Name
```

results in this error

```
   **  Fatal  ** SimOAController: Outside Air Controller not found=CENTRAL_AHU DEHUM COIL CONTROLLER
```

Reversing the order of the controller list eliminates the error.  This needs to be trapped with a better error message during input processing for AirLoopHVAC:ControllerList, or automatically fix the order.
### Details

Some additional details for this issue (if relevant):
- Version of EnergyPlus 8.6.0
- helpdesk ticket 11515
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles, reproduced with modified 5ZoneAirCooled)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6518
