### ISSUE TITLE
Lights object references discontinued Daylighting:DElight:Controls object in v8.6 IDD

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#5894]
## Issue overview

In the IDD file for v8.6, the **Fraction Replaceable** input field of the **Lights** object has a note that references the **Daylighting:DElight:Controls** object, which is no longer available. Since this error is in a note, it's only a documentation error and doesn't affect usability.

**Comment by JasonGlazer** [comment]
@aaron-boranian good catch!

**Comment by mjwitte** [comment]
Closed via #5945
