### ISSUE TITLE
LEED Summary EAp2-4/5 Report Problems

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5895]
The tabular report table LEED Summary EAp2-4/5 has a number of issues that need to be resolved based on the test file:
- When both a normal Lights object and a ElectricEquipment with End-Use Subcategory set to Interior Lighting - process are in the same file, the calculation of the interior lighting is computed as the difference but this results in an incorrect negative value.
- When Industrial process is used as the End-Use Subcategory in ElectricEquipment, the Receptacle Equipment and the Industrial Process rows show the same value.
- The total of the rows does not add up to the total shown for electricity.

Here is the LEED Summary EAp2-4/5 table:

![capture1](https://cloud.githubusercontent.com/assets/2582150/19077884/d118347a-8a13-11e6-8cf3-1d288796bc27.PNG)

Here is the ABUPS End Uses By Subcategory table:

![capture2](https://cloud.githubusercontent.com/assets/2582150/19077915/ee8db584-8a13-11e6-942e-b3ce0c2404a8.PNG)

These problems are exhibited in the EnergyPlus 8.6.0 defect file associated with this issue. First reported in comment to #5580 

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ ] Defect file added (list location of defect file here)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by xwanguk** [comment]
I just found that using Lights object instead of ElectricEquipment object for "Interior Lighting - process" the interior lighting offset problem will not exist. This has been tested and confirmed by using both E+ 8.5.0 and 8.6.0.

**Comment by xwanguk** [comment]
One more point added: version 8.6.0 fixed most of "Receptacle" double counted issue leaving only one category that from LEED still double counted - "Fans - parking garage". Glad to say, regarding LEED EAp2-4/5 table outputs, v8.6.0 behaves much better than v8.5.

**Comment by JasonGlazer** [comment]
As part of the #6150 we have removed the special meaning that some end-use subcategory labels carried that would cause certain rows of the EAp2-4/5 table to be calculated in a special way. Instead, the EAp2-4/5 table now includes all subcategories which allow users to add things up however they wish.
