### ISSUE TITLE
Command line interface does not update RunPeriods between runs.

### ISSUE THREAD

**Issue by tsnouidui** [NREL/EnergyPlus#5897]
@Myoldmopar @nealkruis 

I found the following issue (?) when trying to use the command line interface of E+. 
I am using EnergyPlus version 8.5 on Windows 10 64 bit.

I have an  IDF named `SmOffPSZ.idf` which I ran using the command line below:

`energyplus -w C:/EnergyPlusV8-5-0/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw -p SmOffPSZ -s C -x -m -r SmOffPSZ.idf`

The run was successful.

I changed the `RunPeriod` in the IDF and try to re-run it using the same command.
Surprisingly, I noticed that the IDF was run using the previous `RunPeriod`.

I had to manually delete the files generated from previous run for the CLI to use the correct `RunPeriod`.
Is this the expected behavior?

Thanks!

Please rename the file from jpg to IDF to reproduce.

![smoffpsz](https://cloud.githubusercontent.com/assets/3789840/19084270/bb942792-8a1a-11e6-9a6b-1eb91642072f.jpg)

**Comment by nealkruis** [comment]
@tsnouidui are you sure you're editing the correct file? both ExpandObjects (`-x`) and EPMacro (`-m`) will create temporary IDFs that will be overwritten on subsequent runs.

**Comment by tsnouidui** [comment]
@nealkruis Did you try on Windows 10 to see if you can reproduce?

**Comment by nealkruis** [comment]
The [rename function](https://github.com/NREL/EnergyPlus/blob/198c6a3cffe4df717545e75a97f01510aa6a1875/src/EnergyPlus/FileSystem.cc#L273) on Windows does not allow files to be overwritten like it does for other operating systems. There is a bit on how to better handle this [here](http://stackoverflow.com/questions/11021639/overwriting-files-in-windows-by-renaming-randomly-fails).

We should also do a better job of trapping these kind of failures. Currently, they are pretty quiet.

**Comment by JasonGlazer** [comment]
I stumbled across another instance of this problem related to using the -x expandobjects option. Ran a file (LBuilding-G090.idf) on Windows within Visual Studio using command line options. 

--output-prefix LBuilding-G090 --readvars -D -x --idd Energy+.idd --weather USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw LBuilding-G090.idf

The file contained HVACTemplates so the expidf file was created. Edited the file to add "Output:Diagnostics, DisplayExtraWarnings;" and reran the file. The err file showed no additional messages. When I checked in debugger, it did not even find an OutputDiagnostics object. Deleted the expidf file and reran the file and the extra warning messages were there. It behaved like the expidf file was not being overwritten. 

I confirmed that when using the command line with HVACTemplates, changes made to the IDF file after the first time EnergyPlus runs ExpandObjects are not read by EnergyPlus. The expidf file needs to be deleted prior to ExpandObjects running.

**Comment by tsnouidui** [comment]
This affects all BCVTB users and should ideally be part of the next release.

**Comment by Myoldmopar** [comment]
Tempted to close this....

In other words, I'll mark this for the next release, and then in approximately 6 months when I am scanning the final list for 9.4 I'll see this note and probably just say the same thing.

**Comment by nealkruis** [comment]
@Myoldmopar I'll take this on for the next release.
