### ISSUE TITLE
EP-Launch Lite not running ReadVarsESO for standard .ESO file

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#5898]
## Issue overview

@nealkruis Edwin asked me to "ping" you on this, so that is why I am listing you here.  Is this a bug or a problem with my machine or something else?

In the V8.6 release for the Mac, I tried to run a simple input file from the test suite (1ZoneUncontrolled.idf) just to test out the new EP-Launch Lite app for the Mac.  E+ runs and produces a lot of output files include two .csv files for metered data and table data, but it does not appear to produce a CSV file for the standard eplusout.eso file.
### Details

Some additional details for this issue (if relevant):
- Platform: Mac
- Version of EnergyPlus: V8.6.0
- Unmethours link or helpdesk ticket number: none
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [ no ] Defect file added (problem was noted by running test suite file 1ZoneUncontrolled.idf)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by nealkruis** [comment]
@RKStrand Is this related to the command line interface? Otherwise I have very little knowledge of EP-Launch Lite. @Myoldmopar?

**Comment by Myoldmopar** [comment]
EP Launch Lite is just calling EnergyPlus with `-r` and [other arguments](https://github.com/NREL/EnergyPlus/blob/198c6a3cffe4df717545e75a97f01510aa6a1875/third_party/EP-Launch-Lite/EPLaunchLite/EnergyPlusThread.py#L31-L40), so this felt isolated from anything EP-Launch-Lite related.

**Comment by RKStrand** [comment]
I wish I knew more about the command line, EP Launch Lite, and Mac app development in general but I basically ran the input file using the EP Launch Lite app and didn't get the standard output as a csv file.  I did get other csv files (meter and table).

**Comment by nealkruis** [comment]
ReadVars is running, it's just not finding the ESO file defined by the RVI file. The RVI files included in the example files directory are not compatible with the command line arguments used by EP Launch Lite. EnergyPlus sees the "1ZoneUncontrolled.rvi" file and so it doesn't attempt to create an RVI file automatically. The RVI file tells ReadVars to look for a file called "eplusout.eso", but EnergyPlus is told to name the output files differently.

There are a couple of solutions here:
1. Remove the RVI files from the example files directory.
2. Change the way EP Launch calls EnergyPlus to output files in the "Legacy" file naming convention.

**Comment by mjwitte** [comment]
@nealkruis Referencing discussion from October:

> There are a couple of solutions here:
Remove the RVI files from the example files directory.
Change the way EP Launch calls EnergyPlus to output files in the "Legacy" file naming convention.

The RVI files are there to maintain column order, so I would be reluctant to remove them.  Perhaps there's a third alternative where we can make ReadVars a little smarter in this case to find the eso?  Perhaps it could accept a command line argument for the eso path and then ignore the eploust.eso in the rvi?
@RKStrand @Myoldmopar

**Comment by Myoldmopar** [comment]
@mjwitte I'm inclined to close this as won't-fix.  We aren't doing anything with EPLaunchLite anymore and it looks like this already spawned a separate defect that was addressed.

**Comment by mjwitte** [comment]
@Myoldmopar Plus new EP-Launch will replace this.
