### ISSUE TITLE
EMS Actuator for Window Shading Control can cause crash if status set to "blind on" but there are no blinds

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5903]
## Issue overview

User file crashes becaseu EMS actuator for Window Shading Control is setting the control status to 6 "Interior blind on" but there are no blinds in the file.  The crash occurs [here](https://github.com/NREL/EnergyPlus/blob/198c6a3cffe4df717545e75a97f01510aa6a1875/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L3198), because it's trying to pass Blind(0).IRBackTrans.  Need some protection here, and possibly a few lines above for shade materials.  Or, add some checks where the actuator is read?  Not sure if this should warn (recurring warning), fatal, or just silently ignore invalid status.
### Details

Some additional details for this issue (if relevant):
- Win64
- Version of EnergyPlus 8.6.0
- helpdesk ticket 11599
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (EnergyPlusDevSupport\DefectFiles, run with any weather)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
And it can also cause NAN errors if the shading control is set up as exterior blind and the actuator tries to deploy an interior blind.  Seems like the shading control needs to validate any EMS signals to be sure they are compatible with the specified shading material/type/construction.

New defect file added from helpdesk ticket 11605.

**Comment by Myoldmopar** [comment]
Closed via #6466
