### ISSUE TITLE
ZoneHVAC:IdeaLoadsAirSystem zone load outputs not consistent with more general system outputs

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5908]
## Issue overview

These outputs should always be the same, but they are not:
Ideal Loads Zone Sensible Cooling Rate
Zone Air Heat Balance System Air Transfer Rate 
Zone Air System Sensible Cooling Rate

Example results from the defect file.
![image](https://cloud.githubusercontent.com/assets/4991075/19445499/2073031a-945a-11e6-95c9-b86f2692f768.png)
### Details

Some additional details for this issue (if relevant):
- Platform Win64
- Version of EnergyPlus 8.6.0
- helpdesk ticket number 11494
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added EnergyPlusDevSupport\DefectFiles
- [x] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
Investigated the defect by creating different test cases:
(1) created two test files (1 zone and 3 zone test cases)
(2) code review shows that the three variables expected use a slightly different forms of equation that can cause a small difference in the values. I think a small diffs of less than 1.0W should be tolerable for now. So I focused on the large differences ( up to 5000.0 W)
(3) investigated the random large difference. The random large differences were observed when the the system time step is shortened. Shortening of the system time step occurs when the thermostat temperature set point has a step changes. Changing the step change thermostat to a fixed thermostat temperature set point, washed out the large difference observed. After changing to a fixed set point, the
larger differences reduced to the order of 1.0E-6.  Of the three report variables impacted by the thermostat set point change is "Zone Ideal Loads Supply Air Sensible Cooling Rate". 

It appears that the large difference is caused by impact of step change in thermostat set point and system step down shifting.  May be the "Zone Ideal Loads Supply Air Sensible Cooling Rate" variable update equation is not accounting for the effects of shortening system time step on the load?

**Comment by Nigusse** [comment]
I did further investigation. Below is the summary:
(1) if the is no thermostat setpoint setback or setup (i.e., fixed temperature), then the difference between the three variables is negligible.
(2) if there is thermostat setpoint setback or setup, then there will be a significant difference at or around the time of setpoint temperature change, between "ZONE1AIR:Zone Ideal Loads Supply Air Sensible Cooling Rate [W](Each Call)" and the other two variables.
(3) the reason for the large difference is that the report variable "ZONE1AIR:Zone Ideal Loads Supply Air Sensible Cooling Rate [W](Each Call)" is calculated [here](https://github.com/NREL/EnergyPlus/blob/137048597_HWCoilOnAOSys/src/EnergyPlus/PurchasedAirManager.cc#L2148) using a lagged room air temperature, while the other two variables are calculated using corrected zone air temperature ( ZT() and MAT() ), for example look [here](https://github.com/NREL/EnergyPlus/blob/137048597_HWCoilOnAOSys/src/EnergyPlus/ZoneTempPredictorCorrector.cc#L5192) and [here](https://github.com/NREL/EnergyPlus/blob/137048597_HWCoilOnAOSys/src/EnergyPlus/ZoneTempPredictorCorrector.cc#L3949). This has been confirmed by stepping through the code and post processing the report variables of supply mass flow rates, zone air temperatures and supply air temperatures at detailed reporting frequency. 
(4) I think, this is not a defect, rather it is a limitation of the use of lagged zone condition to calculate the delivered load for the Ideal Zone equipment. 

@mjwitte Please comment if you do not agree with my assessment.

**Comment by mjwitte** [comment]
@Nigusse Good explanation.  Other zone equipment likely has similar differences.  Ran a test with UnitHeaterAuto.idf with detailed output, and it shows similar patterns for Zone Unit Heater Heating Rate vs Zone Air System Sensible Heating Rate.

It does raise the question, however of whether using ZT or MAT is valid for the zone component outputs.  I see a couple of places in [CalcZoneComponentLoadSums](https://github.com/NREL/EnergyPlus/blob/3b7a828663cfcffdd4db62f7ad55e1328cddea0d/src/EnergyPlus/ZoneTempPredictorCorrector.cc#L5143-L5147) that have comments suggesting ZTAV should be used instead of MAT.  Oh, but ZTAV is "Zone Air Temperature Averaged over the Zone Time step" so that would not be appropriate.

Perhaps the "fix" here is to add a sentence or so to the descriptions of Zone Air Heat Balance System Air Transfer Rate and 
Zone Air System Sensible Cooling/Heating Rate explaining that these may not agree exactly with equipment-level values when the zone temperature is changing significantly over a timestep, but the energy will balance out over time?  

@EnergyArchmage any insight to offer here?

**Comment by Nigusse** [comment]
@mjwitte I agree, the logic will have similar effect to other zone equipment as well. 

Let us see a particular time step case:
The "ZONE1AIR:Zone Ideal Loads Supply Air Sensible Cooling Rate [W](Each Call)" was 21078.9 W, and the "Zone Predicted Sensible Load to Cooling Setpoint Heat Transfer Rate [W](Each Call)" was -21078.9 W. So the zone equipment is delivering exactly what is required. For the same time step the other two variables delivered:
Zone Air Heat Balance System Air Transfer Rate [W](Each Call) = -15806.07 W
Zone Air System Sensible Cooling Rate [W](Each Call) = 15807.8 W

The formulation of the equation used to calculate these variables are expected to show difference when there is a change in a zone thermostat set point values. The question here is what is the correct explanation for this difference?  Is there any assumption in the predictor that explains this difference? Adding Gu in the discussion @lgu1234

**Comment by EnergyArchmage** [comment]
I always thought the explanation was using a different definition for what conditions to use when evaluating cp -- the inlet, the zone, or an average of inlet and zone.  E+ equipment models don't really know the zone temp yet and so use the inlet conditions.  Nowadays I think cp for an average is the most accurate (that is drybulb and hum ratio are from an average of the inlet node and the zone node).

**Comment by Nigusse** [comment]
The difference between these variables is expected per the design, hence only explanation was added to the following three output variables description:
-Zone Air Heat Balance System Air Transfer Rate
-Zone Air System Sensible Cooling Rate
-Zone Air System Sensible Heating Rate

**Comment by mjwitte** [comment]
Closed via #5979
