### ISSUE TITLE
Add an Air-To-Water Heat Pump

### ISSUE THREAD

**Issue by vsotofrances** [NREL/EnergyPlus#5915]
## Issue overview

In Spain a common facility is made up of: fan-coils (two-pipes) connected to an AirToWater heat pump (AWHP).
In the templates there are chillers and boilers but there are no AWHP and it would be very interesting to have this type plant available.
### Answer
- Is it possible to develop such template with the existing atomic elements of EnergyPlus?
- Or, is it already available? (and we have missed something)
- In negative case,... is it planned its development?

Regards,
Victor

**Comment by mjwitte** [comment]
@vsotofrances There is no model (yet) in EnergyPlus for an air-to-water central heat pump.  There is a [new feature request](https://energyplus.uservoice.com/forums/258860-energyplus/suggestions/13658316-air-source-central-plant-electric-or-gas-engine-dr) for this type of equipment.

**Comment by aaron-boranian** [comment]
**Air Source Central Plant Electric or Gas Engine-Driven Heat Pump**

Problem: EnergyPlus cannot model a heat pump in the central plant supplying (alternatively) cooling to a chilled water loop or heating to a hot water loop. This is an air to water heat pump.

Rationale: Though not as common in the US, in other parts of the world air to water heat pumps for heating are used and EnergyPlus should be able to model them..

Solution: Add a new component model to EnergyPlus plant for such equipment.

Context: Current work around is to use a heat pump water heater, which is really inteded for domestic hot water, along with an air-cooled chiller. This is an air-source central heat pump and differs from the existing CentralHeatPumpSystem in that it is water-source

Pros and Cons of Solution:
+ long-standing request from users in Europe and Asia
+ fill gap in plant equipment models
- adds yet-another input object that is similiar to an existing one — alternatively could make air source an option in a revamped CentralHeatPumpSystem.

Suggestion from legacy enhancement list (HVAC_2007_40)

Migrated from [UserVoice](https://energyplus.uservoice.com/forums/258860/suggestions/13658316) feedback from @EnergyArchmage

**Comment by mitchute** [comment]
This was addressed in #7489. Closing.
