### ISSUE TITLE
Coil:Heating:WaterToAirHeatPump:EquationFit shows very low/high outlet temperature

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#5919]
## Issue overview

User file shows very low and high outlet water temperature for WAHP.
Help desk ticket 1633. 
### Details

Some additional details for this issue (if relevant):
- Platform (Operating system, version)
- Version of EnergyPlus (if using an intermediate build, include SHA)
- Unmethours link or helpdesk ticket number
### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
- [x] Defect file added (Weather: USA_ID_Boise.Air.Terminal.726810, attached to HD ticket)
- [ ] Ticket added to Pivotal for defect (development team task)
- [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Things look to be calculated correctly inside the cooling and heating functions. The water temperature and enthalpy difference are used to calculate the outlet conditions. In this case, the water temp is calculated correctly yet the enthalpy is negative. Interestingly, the inlet water temperature is 25C and enthalpy is 19,700 J/kg. At 25C, the water enthalpy should be 104,860 J/kg.

Here Qsource_fullload = 33797, SourceSideMassFlowRate = 1.29, and CpWater = 3983. This gives a water temp of 18.4C, all fine and good.
For the enthalpy calc, QSource_fullload / SourceSideMassFlowRate = 26,199 so 19,700 - 26,199 = -6486. Had the correct inlet enthalpy been used, the outlet enthalpy would have been 78,660 which is about right for 18.4C. I found the water enthalpy values [here](http://www.thermexcel.com/english/tables/eau_atm.htm).

![wahp_wateroutletconditions2](https://cloud.githubusercontent.com/assets/5778156/19781190/3532329a-9c56-11e6-8d42-169309d8d9b6.png)

Similar calculations are used for cycling water flow control and constant flow control so changing water flow control mode may not help.

Finally, the outlet water temp shown here as 18.4 is not what is reported in the output file. Very large negative numbers for this coil.

**Comment by rraustad** [comment]
Here's where the 19700 water node enthalpy came from in Init. Not sure if this is some form of ReverseDD thing or what:

	// Do the Begin Environment initializations
	if ( BeginEnvrnFlag && MyEnvrnFlag( HPNum ) && ! MyPlantScanFlag( HPNum ) ) {
		// SNIP //
                Node( WaterInletNode ).Temp = 5.0;
		Node( WaterInletNode ).Enthalpy = Cp * Node( WaterInletNode ).Temp;
		Node( WaterInletNode ).Quality = 0.0;
		Node( WaterInletNode ).Press = 0.0;
		Node( WaterInletNode ).HumRat = 0.0;

		Node( SimpleWatertoAirHP( HPNum ).WaterOutletNodeNum ).Temp = 5.0;
		Node( SimpleWatertoAirHP( HPNum ).WaterOutletNodeNum ).Enthalpy = Cp * Node( WaterInletNode ).Temp;
		Node( SimpleWatertoAirHP( HPNum ).WaterOutletNodeNum ).Quality = 0.0;
		Node( SimpleWatertoAirHP( HPNum ).WaterOutletNodeNum ).Press = 0.0;
		Node( SimpleWatertoAirHP( HPNum ).WaterOutletNodeNum ).HumRat = 0.0;

**Comment by rraustad** [comment]
Well this is interesting. I don't recall seeing this on any other equipment type. For example, what if there are 2 chillers in series, does the pump get oversized since water flows through each in series? In this case, what if these 2 coils (cooling and heating) are on different plant loops? If all coils operate, won't the pump starve flow since it's sized to 1/2 the flow request?
At end of function SizeHVACWaterToAir.

    // Save component design water volumetric flow rate.
    // Use 1/2 flow since both cooling and heating coil will save flow yet only 1 will operate at a time
    if ( SimpleWatertoAirHP( HPNum ).RatedWaterVolFlowRate > 0.0 ) {
      RegisterPlantCompDesignFlow( SimpleWatertoAirHP( HPNum ).WaterInletNodeNum, 0.5 * SimpleWatertoAirHP( HPNum ).RatedWaterVolFlowRate );
    }

**Comment by mjwitte** [comment]
It's kind of kludgy but it's ok here for the heat pump.  As for 2 chillers in series, I'm not sure.

**Comment by mjwitte** [comment]
Just to expand on this for the heat pump, the two coils represent the same physical coil, just different operating modes, so they can't (shouldn't) be on different loops.

**Comment by rraustad** [comment]
See PR #6035.

**Comment by Myoldmopar** [comment]
Closed via #6035
