### ISSUE TITLE
Output:Variable,*,Facility Total HVAC Electric Demand Power does not show in the rdd

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#5922]
Issue overview
--------------
User file does not provide a report variable for HVAC electric demand even though an Output:Meter,Electricity:Facility exists in the input file. Adding ElectricLoadCenter:Distribution and associated objects allows the report variable to show in the rdd.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (V8.5 and V8.6)
 - helpdesk ticket number 11652

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Thread from help desk:

This file does run in V8.6. Still no output report for "Facility Total HVAC Electric Demand Power".

 The code gets here:

 int anyElectricityPresent = GetMeterIndex( "ELECTRICITY:FACILITY" );
 if ( anyElectricityPresent > 0 ) {
 elecLoadCenterObjs.emplace_back( new ElectPowerLoadCenter ( 0 ) );
 numLoadCenters_ = 1;
 }

 and returns 0 for anyElectricyPresent, so no report variables.

 Then the code gets here eventually...

 cCurrentModuleObject = "Output:Meter";
 NumReqMeters = GetNumObjectsFound( cCurrentModuleObject );

 for ( Loop = 1; Loop <= NumReqMeters; ++Loop ) {

 So your doing nothing wrong and I can't think of a workaround other than adding a "ElectricLoadCenter:Distribution" object to see if you can get it to run. I added these objects to your input file and the output report your looking for showed up.

 ElectricLoadCenter:Distribution,
 Electric Load Center, !- Name
 Backup Generators, !- Generator List Name
 DemandLimit, !- Generator Operation Scheme Type
 0.0, !- Generator Demand Limit Scheme Purchased Electric Demand Limit {W}
 , !- Generator Track Schedule Name Scheme Schedule Name
 , !- Generator Track Meter Scheme Meter Name
 AlternatingCurrent; !- Electrical Buss Type

 ElectricLoadCenter:Generators,
 Backup Generators, !- Name
 Cat Diesel, !- Generator 1 Name
 Generator:InternalCombustionEngine, !- Generator 1 Object Type
 0.0, !- Generator 1 Rated Electric Power Output {W}
 ON PEAK GENERATOR SCHEDULE, !- Generator 1 Availability Schedule Name
 ; !- Generator 1 Rated Thermal to Electrical Power Ratio

 Schedule:Compact,
 ON PEAK GENERATOR SCHEDULE, !- Name
 FRACTION, !- Schedule Type Limits Name
 Through: 12/31, !- Field 1
 For: AllDays, !- Field 2
 Until: 24:00,0.00; !- Field 7

 Generator:InternalCombustionEngine,
 Cat Diesel, !- Name
 1.0, !- Rated Power Output {W}
 Generator Diesel Electric Node, !- Electric Circuit Node Name
 0.15, !- Minimum Part Load Ratio
 1.0, !- Maximum Part Load Ratio
 0.65, !- Optimum Part Load Ratio
 BG Shaft Power Curve, !- Shaft Power Curve Name
 BG Recovery Jacket Heat Curve, !- Jacket Heat Recovery Curve Name
 BG Recovery Lube Heat Curve, !- Lube Heat Recovery Curve Name
 BG Total Exhaust Energy Curve, !- Total Exhaust Energy Curve Name
 BG Exhaust Temperature Curve, !- Exhaust Temperature Curve Name
 0.00952329, !- Coefficient 1 of U-Factor Times Area Curve
 0.9, !- Coefficient 2 of U-Factor Times Area Curve
 0.00000063, !- Maximum Exhaust Flow per Unit of Power Output {(kg/s)/W}
 150, !- Design Minimum Exhaust Temperature {C}
 45500, !- Fuel Higher Heating Value {kJ/kg}
 0.0, !- Design Heat Recovery Water Flow Rate {m3/s}
 , !- Heat Recovery Inlet Node Name
 , !- Heat Recovery Outlet Node Name
 Diesel; !- Fuel Type

 Curve:Quadratic,
 BG Shaft Power Curve, !- Name
 0.09755, !- Coefficient1 Constant
 0.6318, !- Coefficient2 x
 -0.4165, !- Coefficient3 x**2
 0, !- Minimum Value of x
 1; !- Maximum Value of x

 Curve:Quadratic,
 BG Recovery Jacket Heat Curve, !- Name
 0.25, !- Coefficient1 Constant
 0, !- Coefficient2 x
 0, !- Coefficient3 x**2
 0, !- Minimum Value of x
 1; !- Maximum Value of x

 Curve:Quadratic,
 BG Recovery Lube Heat Curve, !- Name
 0.15, !- Coefficient1 Constant
 0, !- Coefficient2 x
 0, !- Coefficient3 x**2
 0, !- Minimum Value of x
 1; !- Maximum Value of x

 Curve:Quadratic,
 BG Total Exhaust Energy Curve, !- Name
 0.1, !- Coefficient1 Constant
 0, !- Coefficient2 x
 0, !- Coefficient3 x**2
 0, !- Minimum Value of x
 1; !- Maximum Value of x

 Curve:Quadratic,
 BG Exhaust Temperature Curve, !- Name
 425, !- Coefficient1 Constant
 0, !- Coefficient2 x
 0, !- Coefficient3 x**2
 0, !- Minimum Value of x
 1; !- Maximum Value of x

**Comment by eringold** [comment]
Thanks @rraustad! 

I'll add that the confusion stemmed from the [Whole Facility Electric Service](http://bigladdersoftware.com/epx/docs/8-5/engineering-reference/whole-facility-electric-service.html) documentation page which states 

> Whenever an EnergyPlus model includes **anything that consumes electricity** the program will do some basic modeling of what can be thought of as the main panel where utility grid connects to the building and HVAC loads.

 The model in question represents a central utility plant with chillers, pumps and cooling towers and LoadProfile:Plant objects, but no zones or other electric load equipment. I would think either changing the documentation language to be more precise, or refining [this](https://github.com/NREL/EnergyPlus/blob/13627153888d3ac71645178a674491bc8151b8b6/src/EnergyPlus/ElectricPowerServiceManager.cc#L249) check to capture plant HVAC equipment would resolve the issue.

**Comment by EnergyArchmage** [comment]
I suspect it is a calling order problem, not all the equipment that might use electricity has been setup yet.  The electric load center gets called before plant.

**Comment by lklawrie** [comment]
Did you get my message that this variable shows up in the .rdd until 
V8.1 with the given idf?

Linda

**Comment by rraustad** [comment]
@EnergyArchmage I am considering passing up this first call to manageElectricPowerService on the first pass only. Is there any reason why this shouldn't be done. For example, in the call to ManagePlantLoops the power services need to be known, etc.

    facilityElectricServiceObj->manageElectricPowerService( FirstHVACIteration, SimElecCircuitsFlag, false );
    ManagePlantLoops( FirstHVACIteration, SimAirLoops, SimZoneEquipment, SimNonZoneEquipment, SimPlantLoops, SimElecCircuits );
    AskForPlantCheckOnAbort = true; // need to make a first pass through plant calcs before this check make sense
    facilityElectricServiceObj->manageElectricPowerService( FirstHVACIteration, SimElecCircuitsFlag, false );

Trying to find the least intrusive way to do this I thought of this:

    if ( getInputFlag_ ) {
        if ( !DataErrorTracking::AskForPlantCheckOnAbort ) return;
        getPowerManagerInput();
        getInputFlag_ = false;
    }

**Comment by rraustad** [comment]
I should have mentioned that the defect file only has a plant using LoadProfile:Plant with no building, zone or air loop equipment, etc. so no electricity meters are read in until the plant is called.

**Comment by rraustad** [comment]
With the suggested change above, these report variables no show in the rdd. 

    Output:Variable,*,Facility Total Purchased Electric Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total Purchased Electric Energy,hourly; !- HVAC Sum [J]
    Output:Variable,*,Facility Total Surplus Electric Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total Surplus Electric Energy,hourly; !- HVAC Sum [J]
    Output:Variable,*,Facility Net Purchased Electric Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Net Purchased Electric Energy,hourly; !- HVAC Sum [J]
    Output:Variable,*,Facility Total Building Electric Demand Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total HVAC Electric Demand Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total Electric Demand Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total Produced Electric Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total Produced Electric Energy,hourly; !- HVAC Sum [J]

Any reason to not include some of these if no load centers are included in the input? I'm thinking these should be suppressed if no load centers:

    Output:Variable,*,Facility Total Surplus Electric Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total Surplus Electric Energy,hourly; !- HVAC Sum [J]
    Output:Variable,*,Facility Net Purchased Electric Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Net Purchased Electric Energy,hourly; !- HVAC Sum [J]
    Output:Variable,*,Facility Total Produced Electric Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total Produced Electric Energy,hourly; !- HVAC Sum [J]

leaving just these for a typical simulation:

    Output:Variable,*,Facility Total Purchased Electric Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total Purchased Electric Energy,hourly; !- HVAC Sum [J]
    Output:Variable,*,Facility Total Building Electric Demand Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total HVAC Electric Demand Power,hourly; !- HVAC Average [W]
    Output:Variable,*,Facility Total Electric Demand Power,hourly; !- HVAC Average [W]

**Comment by rraustad** [comment]
Sizing call determined that all report variables should show up in rdd so users can see that load center specific variables are 0. See #6038.

**Comment by mjwitte** [comment]
Closed via #6038
