### ISSUE TITLE
VRF terminal unit shows max iterations exceeded when no cooling/heating flow rate = 0 and constant fan mode is used

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#5925]
Issue overview
--------------
User file shows PLR calculation fails with bad PLR limits. This is a result of using 0 for the no cooling/heating supply air flow rate when using constant fan operating mode. When the model calculates the coil off capacity it was using 0 as the supply air flow rate when in fact, a non-zero value should have been used.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - helpdesk ticket number 11660

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #5946
