### ISSUE TITLE
Transition problem with AirTerminal:SingleDuct:ParallelPIU:Reheat, 8.4 to 8.5

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5926]
Issue overview
--------------
Transitioning defect file from 8.3 to 8.6 fails.  The AirTerminal:SingleDuct:ParallelPIU:Reheat objects get stripped out.  May only affect electric reheat coils, there are only HW coils in test suite. 

The field called Reheat Coil Name in gets quietly lost from 8.4 to 8.5.

then from 8.5 to 8.6 transition flags missing require field and removes the objects with messages.  

Object has no min_fields. 8.4 to 8.5 is stripping a \required-field.

Manually fix broken transition by copying over AirTerminal:SingleDuct:ParallelPIU:Reheat objects from 8.3 file as is.  The IDD has not changed. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5926)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Probably doesn't have anything to do with min-fields or required-fields.  Many of these terminal units had a transition rule for 8.4 to 8.5 to remove excess node name fields.  [Transition rule](https://github.com/NREL/EnergyPlus/blob/198c6a3cffe4df717545e75a97f01510aa6a1875/src/Transition/CreateNewIDFUsingRulesV8_5_0.f90#L820-L825) looks OK, odd.

**Comment by EnergyArchmage** [comment]
This object, with electric reheat coil, starts out with only 14 arguments in 8.4, nothing changes.  So why decrement CurArgs, here
https://github.com/NREL/EnergyPlus/blob/198c6a3cffe4df717545e75a97f01510aa6a1875/src/Transition/CreateNewIDFUsingRulesV8_5_0.f90#L825

**Comment by Myoldmopar** [comment]
Yeah, I think that decrement assumes that the object is fully filled out.  We just need to make sure it only decrements down to the minimum number of fields.

**Comment by Myoldmopar** [comment]
And I assume the series PIU needs the same thing...
