### ISSUE TITLE
Ecoroof Material:RoofVegetation fails with NANs if the input value for initial moisture is greater than max moisture

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5932]
Issue overview
--------------
User file fails with this error.
```
   ** Severe  ** DualSetPointWithDeadBand: Unanticipated combination of heating and cooling loads - report to EnergyPlus Development Team
   **   ~~~   ** occurs in Zone=BLOCK1:ZONE1 During Warmup & Sizing, Environment=SUMMER DESIGN DAY IN UNTITLED (01-01:31-12) JUL, at Simulation time=07/15 00:00 - 00:01
   **   ~~~   ** LoadToHeatingSetPoint=NAN, LoadToCoolingSetPoint=NAN
   **   ~~~   ** Zone Heating Set-point=12.00
   **   ~~~   ** Zone Cooling Set-point=100.00
   **   ~~~   ** Zone TempDepZnLd=9888.77
   **   ~~~   ** Zone TempIndZnLd=NAN
   **   ~~~   ** Zone ThermostatSetPoint=0.00
   **  Fatal  ** Program terminates due to above conditions.
```

This was one of a series of parametric runs looking at varying inputs for `Material:RoofVegetation`.  Comparing other cases that ran successfully revealed that the problem case had these inputs:
```
   0.4,                                  !- Max volumetric moisture content of the soil layer (saturation)
   0.06,                               !- Min (residual) volumetric moisture content of the soil layer
   0.45,                                  !- Initial volumetric moisture content of the soil layer
```

Notice how the initial moisture content has been set greater than the max moisure content.  The init routine should catch this and reset initial = max with a warning.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.6.0
 - Helpdesk ticket number 11678

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #5981
