### ISSUE TITLE
Adaptive comfort model fatal for irrelevant blank fields

### ISSUE THREAD

**Issue by FarhangTahmasebi** [NREL/EnergyPlus#5948]
Adaptive comfort models in the People class do not use mean radiant temperature, work efficiency, clothing, and air velocity as input. Therefore, if a modeler wants to only use this type of comfort models (ASHRAE55, CEN15251), there is no need in principle to fill the aforementioned fields. But EnergyPlus crashes because of these blank fields. In my view, checking the blank fields in the People object should be sensitive to the selected comfort models.

**Comment by mjwitte** [comment]
Closed via #5990
