### ISSUE TITLE
Not possible to get incident solar radiation on shading:building surface

### ISSUE THREAD

**Issue by FarhangTahmasebi** [NREL/EnergyPlus#5949]
In EnergyPlus 8.6.0 the output:variable 'Surface Outside Face Incident Solar Radiation Rate per Area' does not work for building shading surfaces (while it was working for example in EP 8.1.0).

It is quite important to obtain this output because it is common to use shading surfaces to model PV panels and solar collectors, and one needs to evaluate the potential in terms of incident solar radiation before getting into detailed modeling.

An EnergyPlus model with this issue is attached as TXT file.
[m06_errorReport.txt](https://github.com/NREL/EnergyPlus/files/615969/m06_errorReport.txt)

**Comment by FarhangTahmasebi** [comment]
It seemed to me this is a small bug that can be solved easily. I hope it won't be postponed from one version to another. Getting incident solar radiation on a (shading) surface is a very basic query that the users expect from a reliable simulation tool like EnergyPlus.

**Comment by FarhangTahmasebi** [comment]
Is this bug solved in 8.9.0?

**Comment by mjwitte** [comment]
No. When it is resolved there will be a comment with a link to a pull request and the issue will be closed.
