### ISSUE TITLE
Update energyplus.net/downloads to reference Windows 10

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#5950]
Update the web page to reference Windows 10 as well as Windows 7 and 8:

https://energyplus.net/downloads

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
This has been done.

![image](https://user-images.githubusercontent.com/5479063/100427675-15437400-3093-11eb-9581-a58af722be18.png)

**Comment by jmarrec** [comment]
And now I realize the Linux at least needs to be updated. I opened https://github.com/NREL/EnergyPlus/issues/8395
