### ISSUE TITLE
Crash when ZoneHVAC:LowTemperatureRadiant:Electric and ZoneHVAC:LowTemperatureRadiant:SurfaceGroup are not listed 1-N in input file

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#5958]
Issue overview
--------------
User file crashes with zone surface not corresponding to electric radiant system when surface group objects do not correspond to the radiant system object in the same order.
Workaround: list electric radiant system 1-N in input file and also list corresponding SurfaceGroup objects also 1 - N.

Issue #4303 discusses documentation issues with electric rad heater.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) - Windows 8
 - Version of EnergyPlus (if using an intermediate build, include SHA) Version 8.6.0-26de487aef
 - Helpdesk ticket number 11759

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Incorrect indexing of elec rad heater and surface group list.

should be: for ( SurfNum = 1; SurfNum <= SurfList( SurfListNum ).NumOfSurfaces; ++SurfNum ) {

![ticket11795](https://cloud.githubusercontent.com/assets/5778156/20992552/bfdd87ce-bcb2-11e6-8602-89740c9ac78d.jpg)

**Comment by Myoldmopar** [comment]
Closed via #5960
