### ISSUE TITLE
Issue with veiwing dxf file using EPDrawGUI

### ISSUE THREAD

**Issue by abdelaha** [NREL/EnergyPlus#5959]
Issue overview
--------------
I just installed EnergyPlus V8-6-0 on windows 7 64x. I started to follow the simple example (Example 1A) in gettingstarting PDF (Tutorial Example for running EnergyPlus). The simulation run successfully with no warning, errors, or fatal errors; However, I get an Error when I try to open the drawing DXF file. This error is ("File not found Example1A.dxf). 
The simulation does generate the file successfully, but it disappears when I press the drawing file button in EP-Launch then I get the error. Therefore, I tried to open using EPDrawGUI.exe program an infrequently I get another errors which are: 
Object type not recognized: PROGRAM VERSION
It appears on line: Program Version, EnergyPlus, Version 8.6.0-198c6a3cff, YMD=2016.12.07 18:57
line number: 8

Object type not recognized: POLYGON ACTION 
It appears on line: Polygon Action, ThickPolyline
line number: 10

Object type not recognized: COLOR SCHEME
It appears on line: Color Scheme, Default
line number: 12

The first 15 line of EXAMPLE1A.dxf file is:
  0
SECTION
  2
ENTITIES
999
DXF created from EnergyPlus
999
Program Version,EnergyPlus, Version 8.6.0-198c6a3cff, YMD=2016.12.07 18:57
999
Polygon Action,ThickPolyline
999
Color Scheme,Default
999
Text - True North
  0

Is there incompatibility issue with EnergyPlusV8-6 and EPDrawGUI? How can solve this issue? 

Best,
Hamzah

**Comment by mjwitte** [comment]
EPDrawGUI opens idf files and generates a dxf.  You need to install software which can open dxf files.  There are several free dxf viewers available, just search for them.  Once installed, you will need to tell EP-Launch what program to use to open dxf files.  In EP-Launch go to View --> Options --> Drawing Viewer and press the "autofind" button.
