### ISSUE TITLE
AirTerminal: SingleDuct:VAV:Reheat air flow varying during heating operation

### ISSUE THREAD

**Issue by borismbravo** [NREL/EnergyPlus#5961]
Issue overview

[LargeOffice.txt](https://github.com/NREL/EnergyPlus/files/645031/LargeOffice.txt)

--------------
The AirTerminal: SingleDuct:VAV:Reheat (normal control)  air flow is varying during heating operation. 
Upon eplus documentation: "For the case of AirTerminal:SingleDuct:VAV:NoReheat and AirTerminal:
SingleDuct:VAV:Reheat, **air flow only varies during cooling operation and the air flow
rate is set at the minimum value (minimum air flow fraction) when zone heating is required."** This is the expected behavior of single max VAV boxes. While the simulation mimics this most of the time, it doesn't do it at the beginning of a heating cycle when the thermostat set-point swings from unoccupied to occupied values. This happens even when even when there is cooling at the air handler unit therefore overestimating reheat.

Thanks,
Boris

**Comment by EnergyArchmage** [comment]
The problem in the code is here
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SingleDuct.cc#L3127

Normal damper action is supposed to run at the minimum stop.  There needs to be an else if for Normal mode with code like this:

      MaxDeviceAirMassFlowReheat = Sys( SysNum ).AirMassFlowRateMax * Sys( SysNum ).ZoneMinAirFrac ;

**Comment by rraustad** [comment]
There are only 3 choices for control so it appears the else needs to be revised as suggested.

    A10, \field Damper Heating Action
       \type choice
       \key Normal
       \key Reverse
       \key ReverseWithLimits

    // fill dual-max reheat flow limit, if any
    if (Sys(SysNum).DamperHeatingAction == ReverseAction) {
        MaxDeviceAirMassFlowReheat = Sys(SysNum).AirMassFlowRateMax;
    } else if (Sys(SysNum).DamperHeatingAction == ReverseActionWithLimits) {
        MaxDeviceAirMassFlowReheat = Sys(SysNum).AirMassFlowDuringReheatMax;
    } else {
        MaxDeviceAirMassFlowReheat = Sys(SysNum).AirMassFlowRateMax * Sys( SysNum ).ZoneMinAirFrac;
    }

**Comment by rraustad** [comment]
Closed via #6890.
