### ISSUE TITLE
Transition v8.5 to v8.6 (and maybe others) chokes on autosize instead of autocalculate in Tower:TwoSpeed

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#5975]
Issue overview
--------------
Transition of user file from v8.5 to v8.6 threw this error:

```
Program Version,Conversion 8.5 => 8.6
   ** Severe  ** Out of range value Numeric Field#7 (Low Fan Speed Fan Power), value=0.00000, range={>0.0}, in CoolingTower:TwoSpeed=CndW Loop Tower1
   ** Severe  ** Out of "range" values found in input
   ** Severe  ** Out of "range" values and/or blank required fields found in input
   ************* Conversion Completed Successfully-- 0 Warning; 3 Severe Errors
```
The incoming tower object is:

```
CoolingTower:TwoSpeed,
    CndW Loop Tower1,        !- Name
    CndW Loop Tower1 CndW Inlet,  !- Water Inlet Node Name
    CndW Loop Tower1 CndW Outlet,  !- Water Outlet Node Name
    autosize,                !- Design Water Flow Rate {m3/s}
    autosize,                !- High Fan Speed Air Flow Rate {m3/s}
    autosize,                !- High Fan Speed Fan Power {W}
    autosize,                !- High Fan Speed U-Factor Times Area Value {W/K}
    autocalculate,           !- Low Fan Speed Air Flow Rate {m3/s}
    ,                        !- Low Fan Speed Air Flow Rate Sizing Factor
    autosize,                !- Low Fan Speed Fan Power {W}
```
Changing the Low Fan Speed Power from autosize to autocalculate gets rid of the error.  Even with the error, the object transitioned OK (untouched) but the error shouldn't be there.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (EnergyPlusDevSupport\DefectFiles)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
I don't understand.  I mean, maybe E+ has been lenient on the intermix of autosize and autocalculate being allowed, but this seems like a philosophical issue.  The IDD calls that field `\autocalculatable` so users or GUIs should be putting `autocalculate` there.  I assume this happens in all autocalculatable fields, not just towers, and probably every version of transition.  But then again, it's very early Sunday morning, so feel free to correct me!

**Comment by EnergyArchmage** [comment]
The error message itself seems strange, reporting value = 0.0.  The value of autocalculate should be the same as autosize at -99999.0.

**Comment by Myoldmopar** [comment]
I'm guessing it's from [this line](https://github.com/NREL/EnergyPlus/blob/PrepFor87/src/Transition/InputProcessor.f90#L80) in the transition input processor.  The transition input processor really shouldn't have a concept of numeric representations for autosize and autocalculate, as, imo, those numeric values are subject to change within the guts of E+ without having to consult outside entities.

All that said, the error message does direct the user to the bad line, and if they compare the value of that line (autosize) to the allowed value (numeric or autocalculate), I think it should be OK.  I'm most likely not going to rework the guts of the transition input processor/range checker at this point in the release.  I'll keep looking a bit, but I'm just saying it's not likely.

**Comment by mjwitte** [comment]
Closing this, not worth fixing at this point.
