### ISSUE TITLE
Potential IDD/IDF Issues

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#5977]
- [x] Several instances of `\Maximum`  (capital M)
- [x] `\memo` in Field A4 on `SurfaceProperty:SolarIncidentInside`
- [x] `\memo` on several fields in `ComplexFenestrationProperty:SolarAbsorbedLayers`
- [x] `\memo` on several fields in `DemandManager:Ventilation`
- [x] `SizingPeriod:DesignDay` field N7 has a stray `!` comment
- [x] The IDF issues [below](https://github.com/NREL/EnergyPlus/issues/5977#issuecomment-274996653) and [below](https://github.com/NREL/EnergyPlus/issues/5977#issuecomment-275004211)

**Comment by Myoldmopar** [comment]
And IDF Issues...

These files are all 8.4 in the repo as I see it:
 - 5ZoneFanCoilDOAS_HumidifierOnOASystem
 - CoolingCoilFreezingPrevention
 - DOAToWaterToAirHPInlet
 - DOAToWaterToAirHPSupply
 - ZoneCoupledGroundHTBasement
 - ZoneCoupledGroundHTSlabInGrade
 - ZoneCoupledGroundHTSlabOnGrade

**Comment by Myoldmopar** [comment]
Multiple files (CustomSolar...idf included) have AutoSize as the plant/condenser volume when it should be autocalculate.  I think this may be acceptable to the E+ IP, but should still be fixed.

**Comment by Myoldmopar** [comment]
Several files appearing 8.4.0...

**Comment by Myoldmopar** [comment]
These failed my custom transition from 85-86 so investigate why:

- IceStorage-Parallel.idf
- OutdoorAirUnitwithAirloopHVAC.idf
- PlantLoadProfile_updated.idf

**Comment by Myoldmopar** [comment]
Non-ascii characters in IDD:
- [x] AirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan air inlet and outlet node names have goofy apostrophes

**Comment by mjwitte** [comment]
@Myoldmopar Does this have to wait until after release?

**Comment by Myoldmopar** [comment]
Unnnnnnhhhhhh yeah, we probably shouldn't do this right now in order to stay official.

**Comment by mitchute** [comment]
@Myoldmopar can you elaborate on the idf issues referenced above?

**Comment by Myoldmopar** [comment]
Hmm.  Well, in [this comment](https://github.com/NREL/EnergyPlus/issues/5977#issuecomment-274996653), there were several files that were version 8.4 in the repo.  

Then as I commented [here](https://github.com/NREL/EnergyPlus/issues/5977#issuecomment-275014060) there were some files that failed to transition properly in my custom little tool, so just verify they run/transition properly.

Do you want some more details on any of those or was there another comment I'm missing?

**Comment by mitchute** [comment]
I'm not seeing any out-of-date versions, so I'm guessing that was resolved elsewhere. Regarding the transition issues, do we need to need to verify the transition 87-88 works, or somehow go back and figure out what might be any 85-86 transition issues?

**Comment by Myoldmopar** [comment]
I think verifying those files can be transitioned all the way from 8.5 up to now would be sufficient for putting that issue to bed.

**Comment by mitchute** [comment]
@Myoldmopar ```IceStorage_Parellel``` and ```OutdoorAirUnitwithAirloopHVAC``` transition from 85 to 88 just fine. ```PlantLoadProfile_Updated``` doesn't exist in the 85 source.

**Comment by Myoldmopar** [comment]
Closed via #6238
