### ISSUE TITLE
Performance decrease from 8.5 to 8.6 

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5984]
Issue overview
--------------
User reports that execution time increased by factor of 9 between version 8.5 and version 8.6.  Preliminary testing confirmed performance decrease.  From monitoring stdout, appears to be in zone heat balance model because slow execution happens during zone sizing calculations as well as full HVAC simulation. 

One thing to investigate is  use ofDetailedSkyDiffuseModeling algorithm in ShadowCalculation, file has overlapping shading surfaces and maybe varying transmittance of shading surfaces.

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (Windows release 8.5 and release 8.6, 64 bit and 32 bit)
 - Unmethours link https://unmethours.com/question/22066/energyplus-86-taking-9-times-longer-than-energyplus-85/

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/5000s/5984)

defect files include both the original user files and a second pair that are fixed up.  user had made small EMS changes between and apparently was using a modified IDD that changed a minimum.  defect files that start out with 5984* are the fixed ones

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mbadams5** [comment]
@EnergyArchmage I profiled the code and this is the call stack down the functions that are causing the performance regression.

```
Weight	Self Weight		Symbol Name
1.02 min  100.0%	0 s	 	energyplus-8.6.0 (28518)
1.02 min  100.0%	0 s	 	 Main Thread  0x77b6f
1.02 min   99.9%	0 s	 	  start
1.02 min   99.9%	0 s	 	   main
1.02 min   99.9%	0 s	 	    EnergyPlusPgm(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
1.01 min   99.4%	0 s	 	     EnergyPlus::SimulationManager::ManageSimulation()
1.01 min   99.3%	0 s	 	      EnergyPlus::SizingManager::ManageSizing()
59.23 s    97.0%	0 s	 	       EnergyPlus::HeatBalanceManager::ManageHeatBalance()
57.16 s    93.6%	0 s	 	        EnergyPlus::HeatBalanceManager::InitHeatBalance()
57.16 s    93.6%	0 s	 	         EnergyPlus::SolarShading::PerformSolarCalculations()
57.16 s    93.6%	0 s	 	          EnergyPlus::SolarShading::CalcPerSolarBeam(double, double, double)
57.15 s    93.6%	238.00 ms	 	   EnergyPlus::SolarShading::FigureSolarBeamAtTimestep(int, int)
56.91 s    93.2%	373.00 ms	 	    EnergyPlus::SolarShading::SHADOW(int, int)
```

Now, what I haven't figured out yet is why the shadow calculations are running many more iterations in 8.6 vs 8.5. I tried to look back through old PRs for 8.6 but nothing jumped out at me.

**Comment by EnergyArchmage** [comment]
Thanks https://github.com/mbadams5 ! I think it likely to be this one https://github.com/NREL/EnergyPlus/pull/5741

**Comment by mbadams5** [comment]
Considering the call stack and glancing at the code, I agree.

**Comment by EnergyArchmage** [comment]
Note that user had ShadowCalculation's Calculation Method key set to AverageOverDaysInFrequency , but it may need key TimestepFrequency instead, when used with DetailedSkyDiffuseModeling.

**Comment by JasonGlazer** [comment]
There is no doubt that fixing #5741 has some performance impacts on specific files.

**Comment by mitchute** [comment]
Closing in lieu of the ongoing 10X work. We should open a new issue if there's a specific issue to address.
