### ISSUE TITLE
IDD for Boiler:Steam lists incorrect units for Maximum Operating Pressure

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#5985]
Issue overview
--------------
IDD description of the input field called Maximum Operating Pressure in Boiler:Steam lists units as kPa, however units should be Pa.  It also appears this should be a required-field.  

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Too bad we missed this one before IDD freeze.

**Comment by Myoldmopar** [comment]
Closed via #6236
