### ISSUE TITLE
Advanced Single-Sided Natural Ventilation Docs Missing

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#6004]
Issue overview
--------------
The documentation of the advanced single-sided natural ventilation feature is missing from the Engineering Reference and the I/O Reference. Looks like it has gotten lost somehow, as there is documentation in Word document form.

### Details
Some additional details for this issue:
 - All Platforms
 - Version 8.6

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6071
