### ISSUE TITLE
Report incorrect output of AFN Surface Venting Window or Door Opening Modulation Multiplier

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6005]
Issue overview
--------------
When hybrid ventilation request no natural ventilation, the AFN model set OpenFactor =0. However, the output variable of AFN Surface Venting Window or Door Opening Modulation Multiplier is not set correctly.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6008
