### ISSUE TITLE
Constant COP chiller sizing is broken and leads to zero chiller energy consumption

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6010]
Issue overview
--------------
Constant COP chiller reports zero chiller energy consumption. Testing the defect file in develop shows that the chiller capacity sizing is broken. User also report the defect in EnergyPlus versions 8.3 and 8.5. 

Details:
 - Platform Win64
 - Version of EnergyPlus 8.6
 - Helpdesk ticket 11873

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Also see #4991

**Comment by mjwitte** [comment]
Closed via #6012
