### ISSUE TITLE
Zone warmup load convergence check errors for small loads

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6013]
Issue overview
--------------
The calculations used to check for zone warmup load convergence, for both heating and cooling, have a flaw when loads are less than MinLoad.

For heating there is:

MaxHeatLoadZone( ZoneNum ) = std::abs( max( MaxHeatLoadZone( ZoneNum ), MinLoad ) );
WarmupConvergenceValues( ZoneNum ).TestMaxHeatLoadValue = std::abs( ( MaxHeatLoadZone( ZoneNum ) - MaxHeatLoadPrevDay( ZoneNum ) ) / MaxHeatLoadZone( ZoneNum ) );

But the test value calculation is using a MaxHeatLoadPrevDay that has not gotten the same treatment. need to add in 
MaxHeatLoadPrevDay( ZoneNum ) = std::abs( max( MaxHeatLoadPrevDay( ZoneNum ), MinLoad ) );

for example cooling test load should be like this.
					
MaxCoolLoadZone( ZoneNum ) = std::abs( max( MaxCoolLoadZone( ZoneNum ), MinLoad ) ); 
MaxCoolLoadPrevDay( ZoneNum ) = std::abs( max( MaxCoolLoadPrevDay( ZoneNum ), MinLoad ) ); 
WarmupConvergenceValues( ZoneNum ).TestMaxCoolLoadValue = std::abs( ( MaxCoolLoadZone( ZoneNum ) - MaxCoolLoadPrevDay( ZoneNum ) ) / MaxCoolLoadZone( ZoneNum ) );

Contribution from TRANE. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mjwitte I have assigned this to myself andwill take a look at this one as this is something I have worked on in the past and should be able to figure out what @EnergyArchmage is saying in the overview.

**Comment by RKStrand** [comment]
@EnergyArchmage @Myoldmopar @mjwitte Fixed as per Brent's suggestion and added unit tests.  Pull request coming to your inbox soon...

**Comment by rraustad** [comment]
Closed via #6262.
