### ISSUE TITLE
Incorrect distribution of DOA to primary air inlet nodes of terminal air mixers 

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6020]
Issue overview

DOA primary air from terminal air mixer is evenly distributed among all the zones, regardless of the amount of design outdoor air specified for each zone. This was reported for FanCoil unit example file DOAToFanCoilInlet.idf.

### Details
Some additional details for this issue (if relevant):
- Platform Win64
- Version of EnergyPlus 8.6, 8.5

Further testing showed the same issue in PTAC, PTHP, WSHP, VRF, and UnitarySystem connected to DOA example files.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by EnergyArchmage** [comment]
Currently the whole-air-system OA flow rate comes from the sum of the OA design rates for each of the zones attached.  Then that whole-air-system flow is evenly divided between the zones attached, which will nearly always be incorrect. 

I suggest that the best solution to this issue is to add a new input field for the name of a DesignSpecification:OutdoorAir to the AirTerminal:SingleDuct:Mixer object.  This allows for DCV as well as correctly distributing OA flow among the different zones.

**Comment by Nigusse** [comment]
The AirTerminal:SingleDuct:Mixer object implementation use all the calculations in each zoneHVAc equipment.  We can use the OA amount from ZoneHVAC equipment determined from DesignSpecification:OutdoorAir object.

**Comment by mjwitte** [comment]
Also check CO2 concentration at mixer outlet (and other contaminants and OA mass flow).  Ref:  Helpdesk ticket 12014.

**Comment by EnergyArchmage** [comment]
But the ZoneHVAC equipment do not all have a reference to a DesignSpecification:OutdoorAir object, so how can it be used.  Are you proposing to take it from the zone sizing object?  

The I/O reference specifically says to set the outdoor air flow rates to zero in the ZoneHVAC when using the mixer.

**Comment by mjwitte** [comment]
I think the ZoneHVAC equipment should have a non-zero OA flow rate (set either directly or autosized) and that should be the flow request on the mixer terminal unit.  That should flow upstream to the DOAS just like it would from any other standard terminal unit.

**Comment by Nigusse** [comment]
@EnergyArchmage Those statements were added to reflect the original implementation assumption, which was incorrect. The I/O reference will be corrected as part of this fix.

**Comment by Nigusse** [comment]
Added update equations for CO2 and general contaminant propagation at the air terminal mixer.

**Comment by rraustad** [comment]
closed via #6223

**Comment by aaron-boranian** [comment]
**Allow User to Set Primary Airflow Rate Through AirTerminal:SingleDuct:Mixer Object**

The AirTerminal:SingleDuct:Mixer object functions well with respect to its goal to enable the connection of central air systems to the inlet side of Zone:HVAC equipment. One feature that would be helpful, however, would be the ability to set the primary air flow rate through the terminal. Currently, E+ just sets this value equal to the central air flow rate / # branches, which makes it impossible to apportion OA appropriately between non-identical zones. Based on examination of eio files, I do not believe that E+ even attempts to size the terminal unit, so it is also not currently possible to use EMS to override the flow rates during sizing. Having the ability to set, or modify via EMS, the primary airflow through the terminal unit would greatly expand the utility of the AirTerminal:SingleDuct:Mixer object.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/20301160)
