### ISSUE TITLE
PTAC heating coil undersized for ventilation load when zone design heating load is zero

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6028]
Issue overview
--------------
User file has PTACs with hot water heating coils.  PTACs provide ventilation air.  For zones with a zero design zone heating load, the PTAC heating coil is undersized and cannot temper the ventilation load.  Adding a small negative other equipment load to those zones in order to force a non-zero design heating load fixes the coil sizing.  Unit 116 and Unit 206 show the problem.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 8.6.0
 - Helpdesk ticket 11551

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Same as #6006 ?? At least similar.

**Comment by mjwitte** [comment]
True, probably the same issue with `CalcFinalZoneSizing( CurZoneEqNum ).ZoneTempAtHeatPeak`

**Comment by rraustad** [comment]
This is the reason for low heating coil capacity. Results are in paren for Unit 116. The air flow rate used to size the coil is the DesHeatMassFlow while the PTAC is sized to the greater of cooling and heating volume or 0.251 m3/s. So the question is, should the coil be sized at the higher air flow rate? BTW, ZoneEqSizing(84).AirVolFlow = 0.251 (set in the PTAC) and is not used in sizing the water coil capacity. The coil would have been 7 times larger had the higher air flow rate been used. My question is if the DesHeatCoilInTemp includes the ventilation, then why does a 366W design load not meet the load at the higher air flow rate (i.e., you should get more than 366W out of a water coil)?

    } else if ( SizingType == WaterHeatingCapacitySizing ) {
        if ( TermUnitSingDuct || TermUnitPIU || TermUnitIU ) {
        } else if ( ZoneEqFanCoil || ZoneEqUnitHeater ) {
        } else {
            CoilInTemp (22.22C) = FinalZoneSizing( CurZoneEqNum ).DesHeatCoilInTemp;
            CoilOutTemp (32.22C) = FinalZoneSizing( CurZoneEqNum ).HeatDesTemp;
            CoilOutHumRat (0.008) = FinalZoneSizing( CurZoneEqNum ).HeatDesHumRat;
            DesMassFlow (0.0359kg/s) = FinalZoneSizing( CurZoneEqNum ).DesHeatMassFlow;
            NominalCapacityDes (366W) = PsyCpAirFnWTdb( CoilOutHumRat, 0.5 * ( CoilInTemp + CoilOutTemp ) ) * DesMassFlow * ( CoilOutTemp - CoilInTemp );

    Sizing:Zone,
     Unit 116,                !- Zone or ZoneList Name
     SupplyAirTemperature,    !- Zone Cooling Design Supply Air Temperature Input Method
     12.78,                   !- Zone Cooling Design Supply Air Temperature {C}
     11.11,                   !- Zone Cooling Design Supply Air Temperature Difference {deltaC}
     SupplyAirTemperature,    !- Zone Heating Design Supply Air Temperature Input Method
     32.22,                   !- Zone Heating Design Supply Air Temperature {C}
     11.11,                   !- Zone Heating Design Supply Air Temperature Difference {deltaC}
     0.0085,                  !- Zone Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
     0.008,                   !- Zone Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
     90.1-2010 - FrasierMeadows - Apartment - LivingUnit Ventilation - Unit 116 FC,  !- Design Specification Outdoor Air Object Name
     ,                        !- Zone Heating Sizing Factor
     ,                        !- Zone Cooling Sizing Factor
     DesignDay,               !- Cooling Design Air Flow Method
     0,                       !- Cooling Design Air Flow Rate {m3/s}
     0.000762,                !- Cooling Minimum Air Flow per Zone Floor Area {m3/s-m2}
     0,                       !- Cooling Minimum Air Flow {m3/s}
     0,                       !- Cooling Minimum Air Flow Fraction
     DesignDay,               !- Heating Design Air Flow Method
     0,                       !- Heating Design Air Flow Rate {m3/s}
     0.002032,                !- Heating Maximum Air Flow per Zone Floor Area {m3/s-m2}
     0.1415762,               !- Heating Maximum Air Flow {m3/s}
     0.3,                     !- Heating Maximum Air Flow Fraction
     Unit 116 Design Spec Zone Air Dist,  !- Design Specification Zone Air Distribution Object Name
     No;                      !- Account for Dedicated Outdoor Air System

    DesignSpecification:ZoneAirDistribution,
     Unit 116 Design Spec Zone Air Dist,  !- Name
     1,                       !- Zone Air Distribution Effectiveness in Cooling Mode {dimensionless}
     1;                       !- Zone Air Distribution Effectiveness in Heating Mode {dimensionless}

    DesignSpecification:OutdoorAir,
     90.1-2010 - FrasierMeadows - Apartment - LivingUnit Ventilation - Unit 116 FC,  !- Name
     Sum,                     !- Outdoor Air Method
     0.00239524392778712,     !- Outdoor Air Flow per Person {m3/s-person}
     0.000309386292778422,    !- Outdoor Air Flow per Zone Floor Area {m3/s-m2}
     0,                       !- Outdoor Air Flow per Zone {m3/s}
     0;                       !- Outdoor Air Flow Air Changes per Hour {1/hr}

**Comment by rraustad** [comment]
Zone Unit 116 = 106.49 m2 with about 1.8 people so total OA = 0.0373 m3/s which is about equivalent to the zone design heating mass flow rate. So it was 22.2C outside during the peak heating load? All sizing knows is a zone load and a heating SAT to calculate mass flow rate. The heating coil SAT at the higher flow rate and 22.2C inlet would be much lower than 32.2C and might even be lower than the zone temp so this heating coil could not meet much of a load much less the ventilation load.

    Zone Information, UNIT 116,0.0,-27.71,-24.21,3.14,-24.14,-21.16,4.71,1,1,1,-29.14,-17.05,-30.00,-12.47,3.14,6.28,3.14,334.39,TARP,DOE-2,106.49,70.54,70.54,0.00,13,0,0,Yes

  People,
    90.1-2010 - Residential - LivingUnit People 17,  !- Name
    90.1-2010 - FrasierMeadows - Apartment - LivingUnit - Unit 116 FC,  !- Zone or ZoneList Name
    FrasierMeadows Apartment LivingUnit Occupancy Schedule,  !- Number of People Schedule Name
    People/Area,             !- Number of People Calculation Method
    ,                        !- Number of People
    0.0170069784584014,      !- People per Zone Floor Area {person/m2}

**Comment by mjwitte** [comment]
Sizing may need to get smarter about ventilation loads.  In discussions about the reheat coil fix, I recall that we tossed around the possibility of tracking ventilation loads during sizing.  If I'm following your analysis correctly, the zone peak heating load has no relation to when the coil with outdoor air will see it's peak load.

**Comment by rraustad** [comment]
Peak zone heating load vs peak coil load. The coil should size to the greater of these. Not sure what to do here?

So at line 750 of ZoneEquipmentManager we set the load equal to the zone load without concern for ventilation if any. And then we calculate the zone heating/cooling mass flow rate. Yep, not enough info to size the coil. That's why there's backflips in the sizing routines to include OA in the calculation. Got it.

     750  SysOutputProvided = ZoneSysEnergyDemand( ActualZoneNum ).RemainingOutputRequired;
     754  MassFlowRate = max( SysOutputProvided / ( CpAir * DeltaTemp ), 0.0 );

For each timestep there is a zone load and a ventilation load. These are additive. 

I think we could easily add in the ventilation load at line 750 and be done with it. It's the calculation I did above for OA flow and we know the OAT at each time step and SAT so OALoad = OAFlow * StdRho * (SAT - OAT); Seems like a few lines of code right in this area to get the proper load. However, it wouldn't be zone mass flow rate anymore, in the context of what we report now. I think you have to add that in here since we are calculating zone air flow rate before anything else. Adjusting the coil inlet temp in the sizing routines to account for OA miss the impact on supply air mass flow rate.

Then it would be tedious to back out all of the adjustments in component sizing. As long as the coil could hit SAT, it should be able to meet all load conditions.

We've got to ask first what we want as the output regarding reported zone mass flow rate and what that means. We report zone loads and mass flow rates in zsz. We'd have to add ventilation loads there as well. 

I assume if the defect file OA flow rates are zero'd it would work just fine.

**Comment by rraustad** [comment]
After some thought, the method used now is sound. The zone load is met by the calculation of zone mass flow rate at ( SAT - Tzone ). This is the same as the coil load with no OA ( Tzone = Tmix ). With OA, the coil load is zone mass flow rate * ( SAT - Tmix ). The coil must meet the SAT requirement at the ultimate coil flow rate so changing the sizing routine to use the correct flow rate is the most likely solution. The coil can be oversized using this method, but that is unavoidable given a choice between the flow rate calculated for heating loads and that calculated for cooling loads. I remember what a mech eng told me about the coil needing to be able to meet a minimum SAT requirement to avoid call backs. This means I'm back to the original suggestion for a fix, correct the flow rate used for the water coil capacity calculation. Easy fix.

**Comment by mjwitte** [comment]
This should have been closed a while ago, addressed via #6079
