### ISSUE TITLE
Example file 1ZoneDataCenterCRAC_wPumpedDXCoolingCoil fails to size coil bypass factor in varous climates

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6033]
Issue overview
--------------
Example file fails to find CBF in cities other than those similar to Denver since DX coil is hard sized and other weather conditions can cause coil outlet condition to be past the psyc saturation curve and yield RH>100%. The result is a fatal error requiring the user to adjust the DX coil capacity, SHR and/or air flow rate. Nothing stops the user from entering data to yield CBF = 0.0+ (i.e., outlet conditions winds up very near the saturation curve) so why should suspect data input cause a simulation failure. Using Chicago weather yields:

    ** Severe  ** For object = Coil:Cooling:DX:SingleSpeed, name = "MAIN COOLING COIL 1"
    **   ~~~   ** Calculated outlet air relative humidity greater than 1. The combination of
    **   ~~~   ** rated air volume flow rate, total cooling capacity and sensible heat ratio yields coil exiting
    **   ~~~   ** air conditions above the saturation curve. Possible fixes are to reduce the rated total cooling
    **   ~~~   ** capacity, increase the rated air volume flow rate, or reduce the rated sensible heat ratio for this coil.
    **   ~~~   ** If autosizing, it is recommended that all three of these values be autosized.
    **   ~~~   ** ...Inputs used for calculating cooling coil bypass factor.
    **   ~~~   ** ...Inlet Air Temperature     = 26.67 C
    **   ~~~   ** ...Outlet Air Temperature    = 13.84 C
    **   ~~~   ** ...Inlet Air Humidity Ratio  = 1.125000E-002 kgWater/kgDryAir
    **   ~~~   ** ...Outlet Air Humidity Ratio = 1.034142E-002 kgWater/kgDryAir
    **   ~~~   ** ...Total Cooling Capacity used in calculation = 148300.00 W
    **   ~~~   ** ...Air Mass Flow Rate used in calculation     = 9.599302 kg/s
    **   ~~~   ** ...Air Volume Flow Rate used in calculation   = 8.500000 m3/s
    **   ~~~   **  During Warmup, Environment=DENVER CENTENNIAL ANN HTG 99.6% CONDNS DB, at Simulation time=12/21 00:00 - 00:10
    **  Fatal  ** Check and revise the input data for this coil before rerunning the simulation.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
See #6034

**Comment by rraustad** [comment]
The underlying issue here is that a valid coil with standard ratings should run cleanly in any climate. What I find is that the rated CBF is calculated wrt the operating mass flow rate (barometric pressure adjusted) instead of the mass flow rate at standard conditions. From AHRI/ANSI 210-240 2008:

    3.13 Standard Air. Air weighing 0.075 lb/ft3 [1.2 kg/m3] which approximates dry air at 70°F [21°C] and at a barometric pressure of 29.92 in Hg [101.3 kPa].

I think a better method to calculate rated CBF is to use standard conditions where volume is passed to the function and converted to standard mass for the CBF calculation. I discussed this with Hugh Henderson who has worked with modeling DX coils for some time and he agreed. The RATED capacity, air flow volume, and SHR define the coil. The model variable, CBF, is adjusted based on rated CBF, HX theory and actual operating conditions here:

    //    Adjust coil bypass factor for actual air flow rate. Use relation CBF = exp(-NTU) where
    //    NTU = A0/(m*cp). Relationship models the cooling coil as a heat exchanger with Cmin/Cmax = 0.
    
    RatedCBF = DXCoil( DXCoilNum ).RatedCBF( Mode );
    if ( RatedCBF > 0.0 ) {
        A0 = -std::log( RatedCBF ) * DXCoil( DXCoilNum ).RatedAirMassFlowRate( Mode );
    } else {
        A0 = 0.0;
    }
    ADiff = -A0 / AirMassFlow;
    if ( ADiff >= EXP_LowerLimit ) {
        CBF = std::exp( ADiff );
    } else {
        CBF = 0.0;
    }

This should mean that RatedAirMassFlowRate is at standard conditions and AirMassFlow is at operating conditions (altitude). Note use of StdPressureSeaLevel and StdBaroPress (altitude adjusted) below.

However, in E+ the RatedAirMassFlowRate is at altitude so fixing this would be a fundamental change.

For DX coils:

    Real64 const RatedInletAirTemp( 26.6667 ); // 26.6667C or 80F
    Real64 const RatedInletWetBulbTemp( 19.44 ); // 19.44 or 67F
    Real64 const RatedInletAirHumRat( 0.01125 ); // Humidity ratio corresponding to 80F dry bulb/67F wet bulb

    DXCoil( DXCoilNum ).RatedAirMassFlowRate( Mode ) = DXCoil( DXCoilNum ).RatedAirVolFlowRate( Mode ) * PsyRhoAirFnPbTdbW( StdBaroPress, RatedInletAirTemp, RatedInletAirHumRat, RoutineName );
    DXCoil( DXCoilNum ).RatedCBF( Mode ) = CalcCBF( DXCoil( DXCoilNum ).DXCoilType, DXCoil( DXCoilNum ).Name, RatedInletAirTemp, RatedInletAirHumRat, DXCoil( DXCoilNum ).RatedTotCap( Mode ), DXCoil( DXCoilNum ).RatedAirMassFlowRate( Mode ), DXCoil( DXCoilNum ).RatedSHR( Mode ) );

Same for HPWH:

    HPInletAirHumRat = PsyWFnTdbTwbPb( DXCoil( DXCoilNum ).RatedInletDBTemp, DXCoil( DXCoilNum ).RatedInletWBTemp, StdPressureSeaLevel, RoutineName );
    HPWHInletDBTemp = DXCoil( DXCoilNum ).RatedInletDBTemp;
    HPWHInletWBTemp = DXCoil( DXCoilNum ).RatedInletWBTemp;
    DXCoil( DXCoilNum ).RatedAirMassFlowRate( 1 ) = DXCoil( DXCoilNum ).RatedAirVolFlowRate( 1 ) * PsyRhoAirFnPbTdbW( StdBaroPress, DXCoil( DXCoilNum ).RatedInletDBTemp, HPInletAirHumRat, RoutineName );

This would imply 1) large changes to results, and 2) that volume should be passed to CalcCBF and converted to standard mass flow rate for the RatedCBF calculation.

**Comment by rraustad** [comment]
The BaroPressure used in the common sizing routines would also need changing in 2 places.

    } else if ( SizingType == CoolingSHRSizing ) {
        DesMassFlow = DataFlowUsedForSizing * PsyRhoAirFnPbTdbW( StdBaroPress, RatedInletAirTemp, RatedInletAirHumRat, CallingRoutine );

**Comment by Myoldmopar** [comment]
Closed via #6034
