### ISSUE TITLE
Correct surface convection calculation with AirRef = ZoneSupplyAirTemp and zero supply air flow in Window modules

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6037]
Issue overview
--------------
#5906 fixed surface convection calculation with AirRef = ZoneSupplyAirTemp and zero supply air flow in ZoneTempPredictorCorrector by replacing inlet node temperature by zone air temperature to avoid extreme low zone air temperature. The same calculation procedure also occurs in WindowComplexManager, WindowEquivalentLayer, and WindowManager, and needs to be fixed.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #6116
