### ISSUE TITLE
DX coil system and unitary system with 100% OA coil mode and variable speed DX coils throws severe errors

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6040]
Issue overview
--------------
Parent objects for DX cooling coils, CoilSystem and Unitary System throw severe errors when used with both VS coils and 100% OA mode.  Calls to SetDXCoilTypeData are made to set the value of DXCoil( ).ISHundredPercentDOASDXCoil, however this only applies to coil models in DXCoils.cc.  Both of these parent objects allow for variable speed coil models but the coil models in VariableSpeedCoils.cc do not have a special 100% OA mode and the coil parent objects need to deal with this.  Current behavior produces a severe error when it cannot find the coil in DXCoil, but it should not be looking there.

problem occurs in the following places:
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACDXSystem.cc#L614
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACDXSystem.cc#L2886
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACUnitarySystem.cc#L4796
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACUnitarySystem.cc#L13531

Need to add logic to only call SetDXCoilTypeData  for the coil types that in DXCoils.cc

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6145
