### ISSUE TITLE
Components should all use the final zone sizing array

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6043]
Issue overview
--------------
Searching the code for CalcFinalZoneSizing shows multiple occurrences in equipment model sizing routines. This is an intermediate array which is copied to FinalZoneSizing at the end of the sizing calcs. Further updates to this array occurs after these arrays are set equal. So any component model using CalcFinalZoneSizing is not using the most updated data.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
The question here is which sizing array to use for equipment models.

The eio reports the design load and user specified loads:

    ! <Zone Sizing Information>, Zone Name, Load Type, Calc Des Load {W}, User Des Load {W}, Calc Des Air Flow Rate {m3/s}, User Des Air Flow Rate {m3/s}, Design Day Name, Date/Time of Peak, Temperature at Peak {C}, Humidity Ratio at Peak {kgWater/kgDryAir}, Floor Area {m2}, # Occupants, Calc Outdoor Air Flow Rate {m3/s}, Calc DOAS Heat Addition Rate {W}
    Zone Sizing Information, SPACE1-1, Cooling, 2462.87170, 3201.73321, 0.20717, 0.26932, CHICAGO ANN CLG 1% CONDNS DB=>MWB, 7/21 16:00:00, 30.85800, 1.45947E-002, 99.16000, 11.00000, 0.10384, 0.00000
    Zone Sizing Information, SPACE1-1, Heating, 2637.54214, 3428.80478, 7.66703E-002, 0.10384, CHICAGO ANN HTG 99% CONDNS DB, 1/21 24:00:00, -17.30000, 8.38927E-004, 99.16000, 11.00000, 0.10384, 0.00000

It's easy to see where these data come from here:

    ReportZoneSizing( FinalZoneSizing( CtrlZoneNum ).ZoneName, "Cooling", CalcFinalZoneSizing( CtrlZoneNum ).DesCoolLoad,
        FinalZoneSizing( CtrlZoneNum ).DesCoolLoad, CalcFinalZoneSizing( CtrlZoneNum ).DesCoolVolFlow,
        FinalZoneSizing( CtrlZoneNum ).DesCoolVolFlow, FinalZoneSizing( CtrlZoneNum ).CoolDesDay, CoolPeakDateHrMin( CtrlZoneNum ),
        TempAtPeak, HumRatAtPeak, Zone( ZoneNum ).FloorArea, Zone( ZoneNum ).TotOccupants,
        FinalZoneSizing( CtrlZoneNum ).MinOA, DOASHeatGainRateAtClPk );

and how these are calculated:

    FinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow = CalcFinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow * TotHeatSizMult;
    FinalZoneSizing( CtrlZoneNum ).DesHeatMassFlow = CalcFinalZoneSizing( CtrlZoneNum ).DesHeatMassFlow * TotHeatSizMult;
    FinalZoneSizing( CtrlZoneNum ).DesHeatLoad = CalcFinalZoneSizing( CtrlZoneNum ).DesHeatLoad * TotHeatSizMult;

I am under the impression now that equipment models should be using the user adjusted criteria to size the equipment (FinalZoneSizing) not the unadjusted zone loads and air flow rates (CalcFinalZoneSizing).

The models do account for the user sizing factor but it is confusing to others which is used when.

All occurrences of CalcFinalZoneSizing in SingleDuct.cc:

    TermUnitSizing( CurZoneEqNum ).AirVolFlow = max( UserInputMaxHeatAirVolFlowRate, CalcFinalZoneSizing( CurZoneEqNum ).DesHeatVolFlow * CalcFinalZoneSizing( CurZoneEqNum ).HeatSizingFactor, Sys( SysNum ).MaxAirVolFlowRate * Sys( SysNum ).ZoneMinAirFrac );
    TermUnitSizing( CurZoneEqNum ).AirVolFlow = max( CalcFinalZoneSizing( CurZoneEqNum ).DesHeatVolFlow * CalcFinalZoneSizing( CurZoneEqNum ).HeatSizingFactor, Sys( SysNum ).MaxAirVolFlowRate * Sys( SysNum ).ZoneMinAirFrac );
    DesZoneHeatLoad = CalcFinalZoneSizing( CurZoneEqNum ).DesHeatLoad * CalcFinalZoneSizing( CurZoneEqNum ).HeatSizingFactor;
    ZoneDesTemp = CalcFinalZoneSizing( CurZoneEqNum ).ZoneTempAtHeatPeak;
    ZoneDesHumRat = CalcFinalZoneSizing( CurZoneEqNum ).ZoneHumRatAtHeatPeak;
    DesZoneHeatLoad = CalcFinalZoneSizing( CurZoneEqNum ).DesHeatLoad * CalcFinalZoneSizing( CurZoneEqNum ).HeatSizingFactor;
    ZoneDesTemp = CalcFinalZoneSizing( CurZoneEqNum ).ZoneTempAtHeatPeak;
    ZoneDesHumRat = CalcFinalZoneSizing( CurZoneEqNum ).ZoneHumRatAtHeatPeak;

This does look correct, however, there are actions performed on FinalZoneSizing that are not performed on CalcFinalZoneSizing. 

For example here (these lines are different now in #6041):

    // initialize sizing conditions if they have not been set (i.e., no corresponding load) to zone condition
    if ( FinalZoneSizing( CtrlZoneNum ).ZoneTempAtHeatPeak == 0.0 ) {
        FinalZoneSizing( CtrlZoneNum ).ZoneTempAtHeatPeak = ZoneSizing( DDNumF, CtrlZoneNum ).DesHeatSetPtSeq( TimeStepAtPeakF );

Also in #6041 I had to add new code here to please the equipment models:

        CalcFinalZoneSizing( CtrlZoneNum ).ZoneTempAtCoolPeak = FinalZoneSizing( CtrlZoneNum ).ZoneTempAtCoolPeak;  

How can future developers keep all this straight?
Wouldn't it be more maintenance friendly if all models used only the FinalZoneSizing array?

2 occurences in ElectricBaseboardRadiator:

    ZoneEqSizing( CurZoneEqNum ).DesHeatingLoad = CalcFinalZoneSizing( CurZoneEqNum ).DesHeatLoad * CalcFinalZoneSizing( CurZoneEqNum ).HeatSizingFactor;

2 in HIghTempRadiantSystem

    ZoneEqSizing( CurZoneEqNum ).DesHeatingLoad = CalcFinalZoneSizing( CurZoneEqNum ).DesHeatLoad * CalcFinalZoneSizing( CurZoneEqNum ).HeatSizingFactor / (HighTempRadSys( RadSysNum ).FracRadiant + HighTempRadSys( RadSysNum ).FracConvect );

2 in HVACSingleDuct

    DesCoilLoad = CalcFinalZoneSizing( CurZoneEqNum ).DesHeatLoad * CalcFinalZoneSizing( CurZoneEqNum ).HeatSizingFactor - CpAir * RhoAir * DesPriVolFlow * ( TermUnitFinalZoneSizing( CurZoneEqNum ).DesHeatCoilInTempTU - TermUnitFinalZoneSizing( CurZoneEqNum ).ZoneTempAtHeatPeak );

2 in HWBaseboardRadiator

    ZoneEqSizing( CurZoneEqNum ).DesHeatingLoad = CalcFinalZoneSizing( CurZoneEqNum ).DesHeatLoad * CalcFinalZoneSizing( CurZoneEqNum ).HeatSizingFactor;

Similar code in LowTempRadiantSystem and SteamBaseboardRadiator. 

It's interesting that most of these have to do with the design loads. And it also looks like using Calc* multiplied by the sizing factor would be the same as using a user adjusted FinalZoneSizing array data (if the final data correctly accounted for the sizing factor).

Also, if the user specified a sizing factor, that factor would apply to both the air flow rate and zone loads so equipment models should be sizing using the user adjusted air flow rate and user adjusted zone load (which appears to be what we do now).

@EnergyArchmage @mjwitte any comments before proceeding?

**Comment by rraustad** [comment]
Also, there is no use of CalcFinalZoneSizing in SimAirServingZones or ReportSizingManager (only FinalZoneSizing) which also supports using the FinalZoneSizing array for zone equipment model sizing.

**Comment by mjwitte** [comment]
@rraustad Given that the uses of CalcFinalZoneSizing appear to all be related to zone heating devices, I'd say there's something more subtle going on here.  There is the question of what happens to these arrays when, say, a system is given a hard flow rate, or it is sized to ventilation requirements, and some adjustments are made back to the zone sizing calcs to align the terminal units.  Some (all?) of these adjustments happen in TermUnitSizing and TermUnitFinalZoneSizing, but maybe not?  I've been wading in that code recently in order to implement the new terminal unit sizing factors, but I hadn't caught on to the CalcFinalZoneSizing issue.

**Comment by EnergyArchmage** [comment]
I don't have much to add but I agree that moving to all FinalZoneSizing seems to make sense.

**Comment by rraustad** [comment]
This part of the code overwrites FinalZoneSizing.DesHeatLoad when a user specifies Flow/Zone or DesignDayWithLimit as the air flow input method. Note the example above for SingleDuct does not use this updated value so not being consistent bit us on this one. So all other heating types are radiant systems, which probably should not use the Flow/Zone input criteria? Unless of course the documentation is clear on what happens to all zone equipment when this input is used.

    Sizing:Zone,
      Flow/Zone,               !- Heating Design Air Flow Method
      0,                       !- Heating Design Air Flow Rate {m3/s}
      0.1,                        !- Heating Maximum Air Flow per Zone Floor Area {m3/s-m2}

    // Now take into account the user specified sizing factor or user specified heating design air flow
    // rate (which overrides the sizing factor)
    TotHeatSizMult = 0.0;
    // Calculate a sizing factor from the user specified heating design air flow rate
    if ( FinalZoneSizing( CtrlZoneNum ).InpDesHeatAirFlow > 0.0 && FinalZoneSizing( CtrlZoneNum ).HeatAirDesMethod == InpDesAirFlow && FinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow > 0.0 ) {
        TotHeatSizMult = ( FinalZoneSizing( CtrlZoneNum ).InpDesHeatAirFlow / FinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow ) * FinalZoneSizing( CtrlZoneNum ).HeatSizingFactor;
        // Calculate a sizing factor from the user specified max heating design air flow rates
    } else if ( FinalZoneSizing( CtrlZoneNum ).HeatAirDesMethod == DesAirFlowWithLim && FinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow > 0.0 ) {
        MaxHeatVolFlow = max( FinalZoneSizing( CtrlZoneNum ).DesHeatMaxAirFlow, FinalZoneSizing( CtrlZoneNum ).DesHeatMaxAirFlow2, FinalZoneSizing( CtrlZoneNum ).DesCoolVolFlow * FinalZoneSizing( CtrlZoneNum ).DesHeatMaxAirFlowFrac );
        if ( MaxHeatVolFlow < FinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow ) {
            TotHeatSizMult = ( MaxHeatVolFlow / FinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow ) * FinalZoneSizing( CtrlZoneNum ).HeatSizingFactor;
        } else {
            TotHeatSizMult = FinalZoneSizing( CtrlZoneNum ).HeatSizingFactor;
        }
        // If no user specified heating design air flow rate input, use the user specified sizing factor
    } else {
        TotHeatSizMult = FinalZoneSizing( CtrlZoneNum ).HeatSizingFactor;
    }

    if ( std::abs( TotHeatSizMult - 1.0 ) > 0.00001 ) {
        if ( FinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow > 0.0 ) {
            TimeStepAtPeak = FinalZoneSizing( CtrlZoneNum ).TimeStepNumAtHeatMax;
            DDNum = FinalZoneSizing( CtrlZoneNum ).HeatDDNum;
            FinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow = CalcFinalZoneSizing( CtrlZoneNum ).DesHeatVolFlow * TotHeatSizMult;
            FinalZoneSizing( CtrlZoneNum ).DesHeatMassFlow = CalcFinalZoneSizing( CtrlZoneNum ).DesHeatMassFlow * TotHeatSizMult;
            FinalZoneSizing( CtrlZoneNum ).DesHeatLoad = CalcFinalZoneSizing( CtrlZoneNum ).DesHeatLoad * TotHeatSizMult;

**Comment by mjwitte** [comment]
If I'm following this correctly, that's why the non-forced-air heating systems are working off of CalcFinalZoneSizing so they get the "pure" design heating load.  In some ways it's wrong to be changing DesHeatLoad by TotHeatSizMult when airflow adjustments are part of it.  One fix it to carry two separate values along - one for forced air "desheatload" and one for non-forced air.

**Comment by rraustad** [comment]
Great minds!

    Real64 DesHeatLoad; // zone design heating load [W]
    Real64 NonAirSysDesHeatLoad; // same as zone design heating load without special multipliers from Sizing:Zone object [W]

    z.DesHeatLoad = c.DesHeatLoad;
    z.NonAirsysDesHeatLoad = c.DesHeatLoad;

Baseboards:

    ZoneEqSizing( CurZoneEqNum ).DesHeatingLoad = FinalZoneSizing( CurZoneEqNum ).NonAirSysDesHeatLoad;

**Comment by mjwitte** [comment]
But it should still get the HeatingSizingFactor, no?

**Comment by rraustad** [comment]
It's already in there. I've checked, but I'll check again.

**Comment by rraustad** [comment]
OK, it needed to be accounted for.

**Comment by mjwitte** [comment]
But not in the baseboard, it should be put in FinalZoneSizing.NonAirSysDesHeatLoad, like it is already being added to FinalZoneSizing.DesHeatLoad.

**Comment by rraustad** [comment]
Correct. It's  done in ZoneEquipmentManager like everything else. I'm going to do this step wise so I know which change causes diff's.

**Comment by mjwitte** [comment]
Closed via #6052
