### ISSUE TITLE
Reheat coils using main air loop air flow rate to size coil UA

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6044]
Issue overview
--------------
Ran into this with #6006 where reheat coils are sizing heating coil water flow rate using TermUnitSizing( CurZoneEqNum ).AirVolFlow and then using the main air loop air flow rate to calculate UA. This leads to a higher UA value than it should.

Use example file ElectricEIRChillerHeatRecoveryAuto. See PR #6041 for discussion.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Using the example file ElectricEIRChillerHeatRecoveryAuto, the resulting differences in reheat coil sizing is (only diffs in eio other than warmup convergence):

develop:

    Component Sizing Information, Coil:Heating:Water, REHEAT COIL ZONE 1, Design Size U-Factor Times Area Value [W/K], 1770.49067
    Water Heating Coil Capacity Information,Coil:Heating:Water,REHEAT COIL ZONE 1,16970.61
    Component Sizing Information, Coil:Heating:Water, REHEAT COIL ZONE 2, Design Size U-Factor Times Area Value [W/K], 1573.25876
    Water Heating Coil Capacity Information,Coil:Heating:Water,REHEAT COIL ZONE 2,17228.76
    Component Sizing Information, Coil:Heating:Water, REHEAT COIL ZONE 3, Design Size U-Factor Times Area Value [W/K], 1999.58422
    Water Heating Coil Capacity Information,Coil:Heating:Water,REHEAT COIL ZONE 3,24271.45

this branch:

    Component Sizing Information, Coil:Heating:Water, REHEAT COIL ZONE 1, Design Size U-Factor Times Area Value [W/K], 733.48318
    Water Heating Coil Capacity Information,Coil:Heating:Water,REHEAT COIL ZONE 1,15365.68
    Component Sizing Information, Coil:Heating:Water, REHEAT COIL ZONE 2, Design Size U-Factor Times Area Value [W/K], 748.76887
    Water Heating Coil Capacity Information,Coil:Heating:Water,REHEAT COIL ZONE 2,15693.77
    Component Sizing Information, Coil:Heating:Water, REHEAT COIL ZONE 3, Design Size U-Factor Times Area Value [W/K], 1063.69382
    Water Heating Coil Capacity Information,Coil:Heating:Water,REHEAT COIL ZONE 3,22264.85

**Comment by rraustad** [comment]
I spoke with Kannan Rengarajan at Cape Design Engineering. I asked about reheat coil sizing with respect to a simulation and actual installation where air flow rate through that coil could be higher than that needed for reheat purposes. He said he uses the simulation results to spec the coil. Then to avoid call-backs, they upsize the coil 25% and make sure the leaving air temperature can achieve at least 85F (95F for heating coils). He also said a 3.5kW electric reheat coil typically only gives 3.2kW so they upsize those as well.
So, the bottom line is that the simulated reheat coil load and air flow rate during reheat is used to spec the coil. They also assume a 0.1 to 0.2 pressure drop through the coil at higher air flow rates and don't do anything special when expecting this coil to sit in a terminal unit that has increased air flow during cooling or heating mode.

**Comment by Myoldmopar** [comment]
Closed via #6049
