### ISSUE TITLE
DX Coil rating for bypass factor should use volume converted to standard mass

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6046]
Issue overview
--------------
Rated performance of HVAC coils should not change with geography. Performance of these coils will change with changes in altitude/pressure, but the rated performance of a coil should be standardized so that a specific coil can be autosized regardless of the location.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6048
