### ISSUE TITLE
Return Fan:VariableVolume Fan Power Minimum Flow Fraction imposes air loop flow

### ISSUE THREAD

**Issue by ecoeficiente** [NREL/EnergyPlus#6050]
Issue overview
--------------
Return Fan:VariableVolume imposes air loop flow to _Fan Power Minimum Flow Fraction_ despite E+I/O states the opposite:

> This field does not enforce the system air flow rate during simulation

### Details
It seems to happen with return fan but not with supply fan.

**Comment by Nigusse** [comment]
Looking at the source code confirms that the input field _Fan Power Minimum Flow Fraction_ value is used for fan power calculation only. @ecoeficiente Do you have idf file that shows the defect?

**Comment by Nigusse** [comment]
@mjwitte There is no defect file to confirm the defect and looking at the source code the value of _Fan Power Minimum Flow Fraction_ is used for fan power calculation only. I labeled the issue to unconfirmed defect.

**Comment by ecoeficiente** [comment]
So sorry I did not notice your request for example files. I attatched 2 idf files, everything identical but Fan Power Minimum Flow Fraction in AHU return fan.
You will see that the one with 0.3 fraction imposes the flow (the one with 0 fraction gets no flow).

[FlowFractionBug.zip](https://github.com/NREL/EnergyPlus/files/1763238/FlowFractionBug.zip)

**Comment by jmarrec** [comment]
I took the files from @ecoeficiente , updated them to E+ 9.4 and I can reproduce the issue : Here I am plotting the `('CIRCUITO DE AIRE SUPPLY SIDE OUTLET 1', 'System Node Mass Flow Rate', 'kg/s')` variable

![image](https://user-images.githubusercontent.com/5479063/100435516-51c89d00-309e-11eb-8961-bface2163c69.png)


Interestingly I created a MCVE test case using OpenStudio with a simple AirLoopHVAC that has two Fan:VariableVolume, and changing the Min Flow Fraction on the return fan from 0 to 0.3 has no effect there...

![image](https://user-images.githubusercontent.com/5479063/100435961-fcd95680-309e-11eb-991e-491f9c761438.png)

**Comment by jmarrec** [comment]
Ok, I found it, it's becasue my VAV:NoReheat terminal had a Constant Minimum Air Flow Fraction = 0.3... Switching it to 0 like in the defect files exhibits the defect.

![image](https://user-images.githubusercontent.com/5479063/100438518-89d1df00-30a2-11eb-94ab-1e579fc39504.png)
