### ISSUE TITLE
FuelCell Plant connection in ElectricPowerServiceManager

### ISSUE THREAD

**Issue by brianlball** [NREL/EnergyPlus#6051]
Issue overview
--------------
Fuel Cell plant connection in ElectricPowerServiceManager may not be correct.  Fuel Cell has 2 possible plant connections. StackCooler is included but is an optional connection.  ExhaustGasHeatExchanger is NOT an optional component but is not included.

### Details
Should this line also handle the ExhaustGasHeatExchanger:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ElectricPowerServiceManager.cc#L1943

**Comment by mjwitte** [comment]
@EnergyArchmage Is this issue still relevant?

**Comment by Myoldmopar** [comment]
Closed via #6821
