### ISSUE TITLE
Autosized Nominal capacity and design water flow rate values are set to hard sized values for Hot Water Boilers

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6053]
Issue overview
--------------

In Boiler:HotWater the "Nominal Capacity" and "Design Water Flow Rate" are hard sized and "Do Plant Sizing Calculation" is set to yes, then the autosized design values are set to the corresponding hard sized values.  The correct autosized values are reported if the input fields are auto-sized. 

Defect file results:
 Component Sizing Information, Boiler:HotWater, CENTRAL BOILER, Design Size Nominal Capacity [W], 20000.00000
 Component Sizing Information, Boiler:HotWater, CENTRAL BOILER, User-Specified Nominal Capacity [W], 20000.00000
 Component Sizing Information, Boiler:HotWater, CENTRAL BOILER, Design Size Design Water Flow Rate [m3/s], 6.00000E-004
 Component Sizing Information, Boiler:HotWater, CENTRAL BOILER, User-Specified Design Water Flow Rate [m3/s], 6.00000E-004

### Details
Some additional details for this issue (if relevant):
-[ ] Platform Win64
-[ ] Version of EnergyPlus 8.6
-[ ] Found when looking at Helpdesk ticket 11913

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
Added more defect files. The same problem was observed in Boiler:Steam, Chiller:Electric:ReformulatedEIR, and Chiller:Electric:EIR. The fix will address the same problem in all the four objects.

**Comment by Myoldmopar** [comment]
Closed via #6057
