### ISSUE TITLE
Crash in UnitarySystem when heating only DX multispeed coil is used

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6059]
Issue overview
--------------
Please change this line to a description of the defect, with useful supporting information including how the issue was found, conditions that trigger this defect, workarounds for users of the current version, and a clear description of how to validate that a fix is complete for this defect.

Wrokaround: Include Coil:Cooling:DX:Multispeed and schedule this coil off.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
User file crases when DX coil model tries to access DXCoil(DXCoil(DXCoilNum).CompanionUpstreamDXCoil).NumOfSpeeds since this model expects both cooling and heating coils. Safeguards added to DXCoils.cc and minor edits to HVACUnitarySystem.cc.

See PR #6060.

**Comment by Myoldmopar** [comment]
Closes via #6060
