### ISSUE TITLE
File ran in E+ 8.6, 8.7 pre-release, but not 8.7 rc

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#6084]
Issue overview
--------------
This file ran in previous versions of E+ but not in current RC.  Just want to make sure this is a known regression.  Error is:

   ** Severe  ** The Output:Table:Monthly report named="OCCUPANT COMFORT DATA SUMMARY" has a --DuringHoursShown aggregation type for a column without a previous field that uses one of the Hour-- aggregation types. The report will not be generated.

**Comment by macumber** [comment]
Defect file [in.idf](https://github.com/NREL/EnergyPlus/files/883421/in.idf.txt)

**Comment by macumber** [comment]
Problem object:

  Output:Table:Monthly,
    Occupant Comfort Data Summary,  !- Name
    3,                       !- Digits After Decimal
    Zone People Number of Occupants,  !- Variable or Meter 1 Name
    HoursNonZero,            !- Aggregation Type for Variable or Meter 1
    Zone/Sys Air Temperature,!- Variable or Meter 2 Name
    SumOrAverageDuringHoursShown,  !- Aggregation Type for Variable or Meter 2
    Zone Air Relative Humidity,  !- Variable or Meter 3 Name
    SumOrAverageDuringHoursShown,  !- Aggregation Type for Variable or Meter 3
    ThermalComfortMRT,       !- Variable or Meter 4 Name
    SumOrAverageDuringHoursShown,  !- Aggregation Type for Variable or Meter 4
    Time Not Comfortable Summer Or Winter Clothes,  !- Variable or Meter 5 Name
    SumOrAverageDuringHoursShown,  !- Aggregation Type for Variable or Meter 5
    FANGERPMV,               !- Variable or Meter 6 Name
    SumOrAverageDuringHoursShown;  !- Aggregation Type for Variable or Meter 6

**Comment by macumber** [comment]
@Myoldmopar @mjwitte any thoughts?

**Comment by macumber** [comment]
@JasonGlazer looks like this came in on https://github.com/NREL/EnergyPlus/pull/6039

**Comment by Myoldmopar** [comment]
Yeah, that was a bug fix, but as I understand it, it should've passed because the aggregation for variable 1 is not one of the "advanced" aggregation types...  @mjwitte @JasonGlazer did #6039 have a leak in it?  Or am I missing something?

**Comment by JasonGlazer** [comment]
That error message should not be getting generated. Looks like something is broken with the new error message. I will take a look.

**Comment by JasonGlazer** [comment]
@macumber Edwin just pulled this bug fix out of the 8.7 code for the release. https://github.com/NREL/EnergyPlus/pull/6085
