### ISSUE TITLE
Add Hybrid Unitary Air Conditioner model

### ISSUE THREAD

**Issue by spencerdutton** [NREL/EnergyPlus#6091]
Issue overview
--------------
Working with Jonathan Wooley, and to a limited extent NREL I aim to add a new model. Im creating an issue so I can give my branch an identifier.

**Comment by Myoldmopar** [comment]
The 6 independent variable addition to the lookup table is ready for testing: #6093

**Comment by Myoldmopar** [comment]
This is done.
