### ISSUE TITLE
Same idf file can produce different result - related to Fan:SystemModel

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6092]
Issue overview
--------------
User complained that two identical files were producing a different sizing result.  At first, could not reproduce this, but after repeated attempts, saw two different results show up for the same idf file.  Diffing the err file shows one additional error:
```
   ** Warning ** SizeUnitarySystem: Potential issue with equipment sizing for AirLoopHVAC:UnitarySystem CORE_RETAIL ASHP UNITARY
   **   ~~~   ** ...Rated Total Cooling Capacity = 0.00 [W]
   **   ~~~   ** ...Air flow rate used for sizing = 5.95662 [m3/s]
   **   ~~~   ** ...Outdoor air fraction used for sizing = 0.40
   **   ~~~   ** ...Coil inlet air temperature used for sizing = 29.11 [C]
   **   ~~~   ** ...Coil outlet air temperature used for sizing = 12.77 [C]
```
Diffing the eio files, show differences in component sizing for 
```
Coil:Cooling:DX:MultiSpeed, CORE_RETAIL ASHP COOLING COIL (cooling capacities and SHRs, no diffs in airflow rates)
AirLoopHVAC:UnitarySystem, CORE_RETAIL ASHP UNITARY (design size cooling and heating capacities, no diffs in airflow rates)
Coil:Heating:DX:MultiSpeed, CORE_RETAIL ASHP HEATING COIL (heating capacities, no diffs in airflow rates)
Coil:Heating:Electric, CORE_RETAIL ASHP SUPP HEATING COIL (heating capacity)
```

There are also diffs in the DX Heating Coil Standard Rating Information for the CORE_RETAIL coils which is to be expected.  But there is also a diff in the DX ratings for one of the other coils even though none of it's component sizing results are different:
```
! <DX Cooling Coil Standard Rating Information>, Component Type, Component Name, Standard Rating (Net) Cooling Capacity {W}, Standard Rated Net COP {W/W}, EER {Btu/W-h}, SEER {Btu/W-h}, IEER {Btu/W-h}
 DX Cooling Coil Standard Rating Information, Coil:Cooling:DX:MultiSpeed, BACK_SPACE ASHP COOLING COIL, 35028.7,  ,  , 59.67,  
vs.
 DX Cooling Coil Standard Rating Information, Coil:Cooling:DX:MultiSpeed, BACK_SPACE ASHP COOLING COIL, 35028.7,  ,  , 70.71,  
```
When I noticed that the same file gave different results, I ran it repeatedly to see if there was a pattern.  There doesn't seem to be.  Result A 3 times, then result B 10 times, then 3A, 1B, 3A.

### Details
Some additional details for this issue (if relevant):
 - Platform Win10 Home, 64-bit, Version 1607, OA Build 14393.953
 - Version of EnergyPlus Version 8.7.0-78a111df4a
 - Helpdesk ticket number 11961

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles requires groundtemp.csv schedule file (in the zips).  Also added a version of the idf that uses the parametric preprocessor to launch 10 runs of the idf (on windows anyway with ep-launch).  Running this with unfixed code will show in the run summary that some instances have a different number of warnings than others.
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6126
