### ISSUE TITLE
HW supplemental heating coil in AirloopHVAC UnitarySystem not controlling to set point

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6105]
Issue overview
--------------
User file uses HW supplemental heating coil in AirloopHVAC:UnitarySystem with Setpoint control. HW coil outlet temperature overshoots set point at times and undershoots other times. The Coil:Heating:WaterToAirHeatPump:VariableSpeedEquationFit also appears to have control issues.

Found that CW and HW coils also exhibit poor set point based control. Added new defect file 6105-HVACTemplate-5ZoneUnitarySystem_expidf.idf

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (V8.7)
 - Unmethours link or helpdesk ticket number - HelpDesk  ticket 11986

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (GitHub - EnergyPlusDevSupport\DefectFiles) - Burlington VT weather
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Results show poor control of HW supplemental coil.

Supp coil inlet air node = Unitary HC Air Outlet
Supp coil outlet air node = Unitary Air Outlet Node

See x-axis 400 - 600. HW coil inlet node air temp (dark blue dash line) is at the SP (grey line) yet coil is fully on providing a high outlet temperature (orange). Also appears that HW supp coil water outlet node mass flow rate (yellow) does not represent coil heating rate (light blue) (i.e., why 0 at 500-550 when heating coil heating rate is non-zero)?

![6105-hwsuppcontrol](https://cloud.githubusercontent.com/assets/5778156/25183948/f9de786a-24e6-11e7-9fc3-3b48718a54af.png)

**Comment by rraustad** [comment]
A few changes and this looks much better but the water side flow rate still does not match the heating coil heating rate. Still looking and suspect that the SetComponentFlowRate is not called when needed.

![6105-hwsuppcontrol_nearlyfixed](https://cloud.githubusercontent.com/assets/5778156/25188505/49971eea-24f4-11e7-936e-30df28f878cb.png)

**Comment by rraustad** [comment]
So changing thinking in that I wanted to see if the UnitarySystem was doing what I see in code (i.e., I can't find any reason why the water flow rate is non-zero when heating coil heating rate = 0). This is what I get now that I think I've fixed the problem. With a snapshot showing that the HW coil water flow rate is not 0 at times when it should be.

![6105_results1](https://cloud.githubusercontent.com/assets/5778156/25289471/c1f02c52-2697-11e7-9302-b22e2029980e.png)

So I added debug output at the end of the call to UnitarySystem. Low and behold, the output looks as expected. Is it possible that something in the plant loop is setting these flow rates? At the splitter, mixer, etc.

The 1st figure below is same subset from the above figure from the day of 4/6 on the x-axis. The 2nd figure is the debug output for the same time period. I conclude that it is not the UnitarySystem that is setting these water-side flow rates. It must be happening after the call to the UnitarySystem and before the end of the iteration. @EnergyArchmage @mjwitte I hope you have some advice on this as I am stumped. There is also about 400 max iteration warnings that may very well be tied to this problem?

![6105_results2](https://cloud.githubusercontent.com/assets/5778156/25289696/bfdbd5be-2698-11e7-9ffa-7dfbfccea85e.png)

Oh, and there is this error:

    ** Severe  ** Plant flows do not resolve -- splitter inlet flow does not match branch outlet flows
    **   ~~~   **  Environment=YEAR, at Simulation time=04/04 18:38 - 18:45
    **   ~~~   ** PlantLoop name= HW LOOP
    **   ~~~   ** Plant Connector:Mixer name= HW LOOP DEMAND MIXER
    **   ~~~   ** Sum of Branch outlet mass flow rates= 1.449342 {kg/s}
    **   ~~~   ** Plant Connector:Splitter name= HW LOOP DEMAND SPLITTER
    **   ~~~   ** Splitter inlet mass flow rate= 1.261542 {kg/s}
    **   ~~~   ** Difference in two mass flow rates= 0.187800 {kg/s}

    *************  ** Severe  ** Plant Flows (Loop=HW LOOP) splitter inlet flow does not match branch outlet flows
    *************  **   ~~~   **   This error occurred 35 total times;
    *************  **   ~~~   **   during Warmup 0 times;
    *************  **   ~~~   **   during Sizing 0 times.
    *************  **   ~~~   **   Max=14.305445 kg/s  Min=0.144756 kg/s

**Comment by rraustad** [comment]
Also, this HW coil is included on a loop with these components which I'm sure are well behaved.

    Connector:Mixer,
     HW Loop Demand Mixer,    !- Name
     HW Loop Demand Outlet Branch,  !- Outlet Branch Name
     HW Loop Backup Heat HX Branch,  !- Inlet Branch 1 Name
     Water Heater Branch,     !- Inlet Branch 2 Name
     Unitary Supp Heat Branch;!- Inlet Branch 3 Name

    Branch,
     HW Loop Backup Heat HX Branch,  !- Name
     ,                        !- Pressure Drop Curve Name
     HeatExchanger:FluidToFluid,  !- Component 1 Object Type
     Backup Heat HX,          !- Component 1 Name
     Backup Heat HX Loop Demand Side Inlet Node Name,  !- Component 1 Inlet Node Name
     Backup Heat HX Loop Demand Side Outlet Node Name;  !- Component 1 Outlet Node Name

    Branch,
     Water Heater Branch,     !- Name
     ,                        !- Pressure Drop Curve Name
     WaterHeater:Mixed,       !- Component 1 Object Type
     Water Heater,            !- Component 1 Name
     Water Heater Source Inlet,  !- Component 1 Inlet Node Name
     Water Heater Source Outlet;  !- Component 1 Outlet Node Name

**Comment by rraustad** [comment]
Might as well include the water side temps so we can see the HW coil is actually off and acting as a pass through pipe.

![6105_results3](https://cloud.githubusercontent.com/assets/5778156/25291016/586b4c38-269e-11e7-857d-b1b06aa131c2.png)

**Comment by rraustad** [comment]
Saving my debug code in case I need it again.

    static Real64 CurrentEndTime( 0.0 ); // end time of time step for current simulation time step
    bool FileExist( false ); // initialize to false, then override to true if present
    int write_stat;
    static int MyUnitNum( 0 );
    static int SaveMonth;
    static int SaveDay;
    static Real64 SaveTime;
    static Real64 SaveTimeStepSys;
    static Real64 SaveSysTimeElapsed;
    static Real64 SaveWaterHeatingRate;
    static Real64 SaveSuppHeatPLR;
    static Real64 SaveWaterCoilInletMass;
    static Real64 SaveWaterCoilOutletMass;
    static gio::Fmt Format_160( "(1X,I2,1X,I2,1X,F6.3,1X,F6.4,1X,F6.5,1X,F10.3,1X,3(F6.4,2X))" );

    CurrentEndTime = CurrentTime + SysTimeElapsed;

    std::string readMyPath = "eplusout.xyz";
    { IOFlags flags; gio::inquire( readMyPath, flags ); FileExist = flags.exists(); }
    if( FileExist ) {
        if( !DataGlobals::WarmupFlag && CurrentEndTime > SaveTime && TimeStepSys >= SaveTimeStepSys ) {
            gio::write( MyUnitNum, Format_160 ) << SaveMonth << SaveDay << SaveTime << SaveTimeStepSys << SaveSysTimeElapsed << SaveWaterHeatingRate << SaveSuppHeatPLR << SaveWaterCoilInletMass << SaveWaterCoilOutletMass;
        }
    } else {
        MyUnitNum = GetNewUnitNumber();
        { IOFlags flags; flags.ACTION( "write" ); flags.STATUS( "UNKNOWN" ); gio::open( MyUnitNum, "eplusout.xyz", flags ); write_stat = flags.ios(); }
    }

    // save last system time step and last end time of current time step (used to determine if warning is valid)
    SaveMonth = DataEnvironment::Month;
    SaveDay = DataEnvironment::DayOfMonth;
    SaveTime = DataGlobals::CurrentTime;
    SaveTimeStepSys = DataHVACGlobals::TimeStepSys;
    SaveSysTimeElapsed = DataHVACGlobals::SysTimeElapsed;
    SaveWaterHeatingRate = WaterCoil( 1 ).TotWaterHeatingCoilRate;
    SaveSuppHeatPLR = UnitarySystem( UnitarySysNum ).SuppHeatPartLoadFrac;
    SaveWaterCoilInletMass = Node( UnitarySystem( UnitarySysNum ).SuppCoilFluidInletNode ).MassFlowRate;
    SaveWaterCoilOutletMass = Node( UnitarySystem( UnitarySysNum ).SuppCoilFluidOutletNodeNum ).MassFlowRate;

**Comment by rraustad** [comment]
See PR #6107.

**Comment by rraustad** [comment]
The reason for the water-side discrepancy in the defect file was due to the user setting plant minimum flow rate = max without using a bypass branch on the chilled water plant demand side. The HW loop does have a bypass branch so was not affected. Plantloop min was set to 0 and a bypass branch added to the CW loop.

    PlantLoop,
     HW Loop,                 !- Name
     0.020000,                !- Maximum Loop Flow Rate {m3/s}
     0.020000,                !- Minimum Loop Flow Rate {m3/s}

    PlantLoop,
     CHW Loop,                !- Name
     0.062112,                !- Maximum Loop Flow Rate {m3/s}
     0.062112,                !- Minimum Loop Flow Rate {m3/s}

**Comment by mjwitte** [comment]
Closed via #6107
