### ISSUE TITLE
Missing output row in SQL database

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#6112]
E+ 8.7 on Windows

The E+ html file includes 21 rows in the Component Sizing Information table, where row 20 is:
`20 	Boiler:HotWater 	RESIDENTIAL BOILER ELECTRIC 	User-Specified Nominal Capacity [W] 	26352.97405`
whereas the SQL file only has 20 rows and is missing this output.

IDF file attached.

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/970829/in.idf.txt)

**Comment by mjwitte** [comment]
@shorowit @macumber Actually, there are lots of missing entries in the sql component sizing table.  This particular file only has one missing value, but most files that have user-specified sizes will have dual reporting for nearly every autosized value (design size and user-specified).  For example, 5ZoneAutoDXVAV, the first part of the component sizing table looks like this:
![image](https://user-images.githubusercontent.com/4991075/26946677-baa941e8-4c55-11e7-98ac-c1ff211c34d4.png)

Currently, only the 5 "Design Size" columns of this table are being written to sql.  With the fix, all of the Design Size and User-Specified values will be written to sql.  Is this going to cause problems in reading this table?

**Comment by macumber** [comment]
@DavidGoldwasser @asparke2

**Comment by shorowit** [comment]
I can't speak for others but it won't be a problem for me.

**Comment by DavidGoldwasser** [comment]
Shouldn't cause an issue for me unless the names of existing columns change, if that happens and I know it, I can update the reporting measure if needed.

**Comment by mjwitte** [comment]
@DavidGoldwasser OK, will merge this then.  Just to be clear, all existing rows in this table will still be there, but the additional user-defined values that will now appear in the table are the ones to grab if you're trying to report the sizing that was actually used in the simulation.  I will add an explanation of this to the output changes doc.

**Comment by asparke2** [comment]
As long as the existing column headings in the sql file don't change I won't have any issue.  If they do change, it would be nice to have it documented so I can preemptively correct any code that uses those names.

**Comment by mjwitte** [comment]
@asparke2 This table is organized differently in the sql file than it appears in the table file.  The sql file has a separate record for every value in the table, so the generic sql column headings won't change, but there will be additional records that were previously omitted.
![image](https://user-images.githubusercontent.com/4991075/26983820-b10182a6-4d02-11e7-9b60-812c4e91d090.png)
![image](https://user-images.githubusercontent.com/4991075/26983833-ba4d8224-4d02-11e7-951c-2a9583dc3afd.png)

**Comment by mjwitte** [comment]
Closed via #6147
