### ISSUE TITLE
FourPipeBeamLargeOffice crashes when system sizing is turned off

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#6136]
I found this while working on #5120. 

Four pipe beam relies on system sizing being run before it is initialized. Error messages need to be added so it fails gracefully.

### Checklist
 - [x] Defect file added (FourPipeBeamLargeOffice.idf)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6137
