### ISSUE TITLE
Fix package builds on Linux

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#6141]
It was a known issue that later versions of CMake had trouble with packages.  The problem appears to be that we are calling `GetPrerequisites` on the static Fortran binaries, which calls `ldd`, which fails.  I guess we need to add an option to our `fixup_executable` command to allow it to skip trying to find dependencies.

@kbenne What do you think about this approach?

**Comment by jasondegraw** [comment]
@Myoldmopar You sure we need another issue for this?

**Comment by Myoldmopar** [comment]
I'm not. But it's early on Saturday so I didn't peruse the other issues. :). If I made a dup feel free to close this or I'll do it later.

**Comment by jasondegraw** [comment]
Closing as a duplicate of #5854 with PR #6042
