### ISSUE TITLE
LifeCycleCost:UsePriceEscalation should impact the Total Cost column of the Present Value by Year table

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#6144]
The LifeCycleCost:UsePriceEscalation should impact the Total Cost column of the Present Value by Year table. The LifeCycleCost:UsePriceEscalation does seem to impacting numbers but its impact is not directly shown in any of the existing tables. 

 - Version of EnergyPlus 8.6.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (in DevSupport repo)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Might as well tackle this as well: https://unmethours.com/question/25171/life-cycle-costs-escalation-for-electricity/

I noticed that the LifeCycleCost:UsePriceEscalation isn't taken into account for my electricity usage in the table "Present Value for Recurring, Nonrecurring and Energy Costs (Before Tax)", while it is correctly taken into account for gas.

**Comment by JasonGlazer** [comment]
To address @jmarrec concern, add a warning message when the resource referenced in LifeCycleCost:UsePriceEscalation does not match any of the resources that have non-zero costs. Also consider changing LCCusePriceEscalationDataSet2016.idf files to use the resource ElectricityPurchased instead of Electricity.

**Comment by Myoldmopar** [comment]
This is only partially addressed via the merge of #6311 right?

**Comment by JasonGlazer** [comment]
Correct. The rest will be addressed after the 8.8 release. Please don't close this issue.

**Comment by luisclv** [comment]
Just a friendly note that once that PR #7459 is closed, the part of this issue about meters `Electricity` and `ElectricityPurchased` is still open. Ran into the issue today so I am glad someone else noticed. Thank you for the hard work!

**Comment by JasonGlazer** [comment]
@luisclv I think the meter issue was resolved in #6311 which adds a warning and was included in an earlier release of EnergyPlus. What else is still an issue? It might be worth describing in a new issue.
