### ISSUE TITLE
  ElectricEquipment:ITE:AirCooled not showing in Component Loads table

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6146]
Issue overview
--------------
IT equipment does not appear in the component loads summary table report.  Existing testfile 2ZoneDataCenterHVAC_wEconomizer.idf shows the problem when ZoneComponentLoadSummary is requested.  It seems that IT equipment should appear as load in the equipment row but it is empty.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6286
