### ISSUE TITLE
Add low temperature shut off to air-cooled DX cooling coils

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6149]
Issue overview
--------------
DX heating coils (Coil:Heating:DX:SingleSpeed, Coil:Heating:DX:MultiSpeed, Coil:Heating:DX:VariableSpeed) have a field for Minimum Outdoor Dry-Bulb Temperature for Compressor Operation.

Request that a similar field be added to Coil:Cooling:DX:*.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.7.0
 - helpdesk ticket 12022

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
TBD:

- [x] All DX cooling coils will have new field for low temp cutout
- [x] IDD change for new field with default of -25C ??
- [x] Update EPFilter for HVACTemplate objects
- [x] GetInput and code change similar to that used for DX heating coil
- [x] documentation updates
- [x] unit test
- [x] example file mods (blank field)
- [x] transition rules
- see PR #6158

**Comment by rraustad** [comment]
@Myoldmopar @EnergyArchmage @mjwitte Any comments on placement of this new field are welcome. Inserted at the end of the min field limit so it's available before other more innocuous input fields. Easier to move now before moving on to other coil types. Wrestling with default of -25C or just set to -999C if blank.

Coil:Cooling:DX:SingleSpeed,
  \min-fields 14
  A1 , \field Name
  A2 , \field Availability Schedule Name
  N1 , \field Gross Rated Total Cooling Capacity
  N2 , \field Gross Rated Sensible Heat Ratio
  N3 , \field Gross Rated Cooling COP
  N4 , \field Rated Air Flow Rate
  N5 , \field Rated Evaporator Fan Power Per Volume Flow Rate
  A3 , \field Air Inlet Node Name
  A4 , \field Air Outlet Node Name
  A5 , \field Total Cooling Capacity Function of Temperature Curve Name
  A6 , \field Total Cooling Capacity Function of Flow Fraction Curve Name
  A7 , \field Energy Input Ratio Function of Temperature Curve Name
  A8 , \field Energy Input Ratio Function of Flow Fraction Curve Name
  A9 , \field Part Load Fraction Correlation Curve Name

      N6 , \field Minimum Outdoor Dry-Bulb Temperature for Compressor Operation

  N7 , \field Nominal Time for Condensate Removal to Begin

**Comment by rraustad** [comment]
I think I like the default method since users or GUIs can change the IDD as needed.

     N6 , \field Minimum Outdoor Dry-Bulb Temperature for Compressor Operation
       \type real
       \default -25.0
       \units C

**Comment by mjwitte** [comment]
@rraustad Field placement and default work for me.

**Comment by Myoldmopar** [comment]
Closed via #6158
