### ISSUE TITLE
Add option to AvailabilityManager:NightCycle to run just until the zone temperature recovers

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6151]
Issue overview
--------------
Currently, AvailabilityManager:NightCycle activates an airloop or zone equipment for a fixed amount of time when the zone temperature is one half the Thermostat Tolerance above the thermostat setpoint for cooling (or below for heating).  It would be useful to have an option for the system to run just until the zone temperature recovers to the thermostat setpoint.

Possible approaches for this:
A.  Use Cycling Run Time = 0 to indicate shut off by thermostat rather than a fixed time. No new fields.

B.  New field "Cycling Run Time Control Type" with choices of
  - FixedRunTime: Run for the time specified in Cycling Run Time (current method)
  - Thermostat: Cycle off when the zone reaches the thermostat setpoint (Cycling Run Time is ignored)
  - ThermostatWithMinimumRunTime:  Run for the time specified in Cycling Run Time and then continue running until the zone reaches the thermostat setpoint.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.7.0
 - Helpdesk ticket number 12018

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
One vote at this point for Option B.

**Comment by Nigusse** [comment]
I am thinking to implement option B and add the new input field _"Cycling Run Time Control Type"_ right after input field "A4" as shown below. @mjwitte @Myoldmopar Please let me know what your thoughts are?

AvailabilityManager:NightCycle,
       \min-fields 6
  A1 , \field Name
  A2 , \field Applicability Schedule Name
  A3 , \field Fan Schedule Name
  A4 , \field Control Type

 new input filed: A4 , \field Cycling Run Time Control Type

  N1 , \field Thermostat Tolerance
  N2 , \field Cycling Run Time
  A5 , \field Control Zone or Zone List Name
  A6 , \field Cooling Control Zone or Zone List Name
  A7 , \field Heating Control Zone or Zone List Name
  A8 ; \field Heating Zone Fans Only Zone or Zone List Name

**Comment by mjwitte** [comment]
Yes on Option B.  I would put the new field right before the existing Cycling Run Time field.

**Comment by Nigusse** [comment]
@mjwitte for the ThermostatWithMinimumRunTime cycling run time control option the thermostat tolerance for during the minimum Run Time Period will be user specified value in input field Thermostat Tolerance, right?

**Comment by mjwitte** [comment]
Thermostat Tolerance will determine when it should come on.  But it should run until the thermostat setpoint is met.  I didn't think about a tolerance for that - but we probably need another input.  Depending on the system type, it may not hit the setpoint exactly, but should be very close.  Or we could just say it will shut off when it's within 10% (or ??%) of the tolerance.

**Comment by Nigusse** [comment]
Now with two new input fields added below is what I am proposing for the idd change. The "Thermostat Tolerance Fraction" new input field will be placed next to "Thermostat Tolerance" input field. @mjwitte what do you think?

AvailabilityManager:NightCycle,
\min-fields 6
A1 , \field Name
A2 , \field Applicability Schedule Name
A3 , \field Fan Schedule Name
A4 , \field Control Type

N1 , \field Thermostat Tolerance
new input filed: N2 , \field Thermostat Tolerance Fraction
new input filed: A5 , \field Cycling Run Time Control Type

N3 , \field Cycling Run Time
A6 , \field Control Zone or Zone List Name
A7 , \field Cooling Control Zone or Zone List Name
A8 , \field Heating Control Zone or Zone List Name
A9 ; \field Heating Zone Fans Only Zone or Zone List Name

**Comment by mjwitte** [comment]
@Nigusse As I look at this now, "Thermostat Tolerance Fraction" seems more complicated than it needs to be.  How about this:
new field name N1, \field Cycle On Thermostat Tolerance (or System On . . . or ???)
new input filed: N2 , \field Cycle Off Thermostat Tolerance
And the new field should have a minimum of at least 0.01 deltaC, maybe 0.1.  
And the get input should probably warn and reset if the cycle off tolerance is >= (the cycle on tolerance)/2?
Hmmm, never did understand why the existing Thermostat Tolerance is divided by 2 when it is applied.  Do we need to do the same with the new field?    I don't suppose we can change the way the current tolerance is used without really confusing everyone.  @Myoldmopar ?

**Comment by Nigusse** [comment]
For me the concept of Cycle On and Cycle Off are also confusing? Why do we introduce the Off cycle concept? The tolerance simply provides the cut point for turning the equipment On or Off?  In both cases the " Thermostat Tolerance" input field is used in a similar way. We can allow/advise user to specify a different range of values for "Thermostat Tolerance" input field depending on the Cycling Run Time Control Type. I suggest to use the existing "Thermostat Tolerance" input field only.

**Comment by mjwitte** [comment]
The dual tolerances prevent short-cycling but in an automated way to avoid choosing a minimum run-time.  If we had perfect control, we could skip the second tolerance and just shut off when the setpoint is reached.  But some systems don't peg the setpoint so it may never shut off.  I'm ok with not adding a new tolerance field and use a hard-wired off tolerance of, say 0.05C.

**Comment by Myoldmopar** [comment]
Closed via #6179
