### ISSUE TITLE
Fix example file geometry issues uncovered while fixing zone volume calculations

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#6161]
While fixing zone volume calculations as part of the issue:

https://github.com/NREL/EnergyPlus/issues/5501

A number of files tested by the CI showed differences, see pull request:

https://github.com/NREL/EnergyPlus/pull/6056

But many of these differences in files were due to geometry descriptions that were incorrect for the building surfaces. Of the 60 files, 6 have been examined so far and three of those have geometry issues:

•    1ZoneUncontrolled_DD2009 – the floor is located at the ceiling height – fixed file
•    AirflowNetwork_Multizone_HorizontalOpening – surface attached to wrong zone
•    HP_wICSSolarCollector – wall attached to wrong zone, missing another wall, roof coordinates wrong

Based on this the rest of the files need to be reviewed and fixed if necessary.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6056
