### ISSUE TITLE
Swimming pool init only calls ScanPlantLoopsForObject for the first pool resulting in errors

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6170]
Issue overview
--------------
User file with two swimming pools generates this error:
```
   ** Severe  ** SetComponentFlowRate: trapped plant loop index = 0, check component with inlet node named=POOL WATER INLET NODE2
```
The call to ScanPlantLoopsForObject in [SwimmingPool::InitSwimmingPool](https://github.com/NREL/EnergyPlus/blob/fa73d590331fc1852c4c9ad1b9502035dbff99a5/src/EnergyPlus/SwimmingPool.cc#L646-L657) is misplaced.  It should be after the MyOneTimeFlag block.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.7.0
 - Helpdesk ticket number 12009

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6217
