### ISSUE TITLE
There is no advanced single-sided natural ventilation example file

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#6180]
Issue overview
--------------
The advanced single-sided natural ventilation feature was added in 8.1 or 8.2, but the original example file was not added to the set of example files used for CI testing. The original file needs to be updated to current example file standards, or perhaps a new example file needs to be created.

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #6818
