### ISSUE TITLE
Earth Tube One Per Zone Limit Check has Errors

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#6182]
Issue overview
--------------
There is a limit of only one earth tube per zone in EnergyPlus.  (While this could be changed to allow multiple earth tubes per zone, that is not the subject of this issue and should be considered as a future minor enhancement.)  The code to check that there is only one earth tube per zone has several errors in it:

Code:
		// Check to make sure there is only on ventilation statement per zone
		for ( Loop = 1; Loop <= TotEarthTube; ++Loop ) {
			for ( Loop1 = Loop + 1; Loop1 <= TotEarthTube - 1; ++Loop1 ) {
				if ( EarthTubeSys( Loop ).ZonePtr == EarthTubeSys( Loop1 ).ZonePtr ) {
					ShowSevereError( cAlphaArgs( 1 ) + " is assigned to more than one " + cCurrentModuleObject );
					ShowContinueError( "Only one such assignment is allowed." );
					ErrorsFound = true;
				}
			}
		}

Errors:
- The outer loop should be to TotEarthTube -1 and the inner loop to TotEarthTube (the code as it currently stands could actually allow two earth tubes in a single zone but the second would overwrite the results of the first.)
- The comment at the beginning of the code snippet needs to be edited.
- The error message is very unclear and needs to be modified.

The condition that could trigger this problem is having the last earth tube be assigned to a zone that already has another earth tube.

The workaround for the user is to simply not have more than one earth tube per zone.

Validation should be straightforward--the code should not allow the last earth tube to be in a zone that has another earth tube already.

### Details
Some additional details for this issue (if relevant):
 - Platform (any)
 - Version of EnergyPlus (Version 8.7)
 - Unmethours link or helpdesk ticket number (none)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
I have checked defect file added above, but in reality there is not a need for a separate defect file.  You can show that this is a problem by taking the EarthTubeSimpleTest.idf file in the test suite and doing two separate tests.  In the first test, copy the first earth tube for zone 1 and paste it AFTER the earth tube for zone 3.  This makes this fourth earth tube the LAST one in the file.  This file should crash and in V8.7 it does NOT.  This is the problem because it allows a second earth tube because of the bad logic in the code.  What happens in this situation is that the last earth tube will overwrite the previous earth tube for that zone.  However, if you switch the order of the earth tube from zone 3 and the duplicate for zone 1, this will produce the error message.  Again, this was verified in V8.7.  The code fix will not allow this to take place and also cleans up the error message to make the problem more understandable.

**Comment by Myoldmopar** [comment]
Closed via #6185
