### ISSUE TITLE
Antivirus hits

### ISSUE THREAD

**Issue by fourdayforecast** [NREL/EnergyPlus#6183]
Issue overview
--------------
Looks like 8.7 is detected by some antivirus, similar to [issue 4871](https://github.com/NREL/EnergyPlus/issues/4871). 

### Details
EnergyPlus-8.7.0-78a111df4a-Windows-x86_64.exe had a detection in Virustotal by Rising as Malware.Heuristic!ET#88% (cloud:I4mEy9r8dpV)

File Hashes:
MD5 3fcbfb566738c0c25ab6f6f5c3b44843
SHA1 1e5d9ba065b34c1dd43243929fa88fb78854533c
SHA256 7c02e85decf2589cc55282cf747080315760d9ead7a3c322ef3b9e2403ef1a88

See also: 
https://virustotal.com/en/file/7c02e85decf2589cc55282cf747080315760d9ead7a3c322ef3b9e2403ef1a88/analysis/1498152635/

It was also previously detected by Trend by that seems to be resolved now.

**Comment by jmarrec** [comment]
If you keep experiencing this with newer installed (9.2.0 or forthcoming 9.3.0) please let us know so we can reopen this issue (or open a brand new one). Thanks!
