### ISSUE TITLE
EP-Launch-Lite Closing Issue

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#6186]
Issue overview
--------------
On the Mac, the EP-Launch-Lite tool is very useful and some of the issues from the past have been fixed (THANK YOU!!!).  In the version that came with Version 8.7, a minor problem was noted.  When closing the program, quitting from the EP-Launch-Lite menu (or pressing command Q) does not do anything.  The workaround is to click on the red close dot in the upper left corner of the window.  This does close the program.  So, not a big deal and probably easy to fix, but it was something that I noticed.

### Details
Some additional details for this issue (if relevant):
 - Platform: Mac OS 10.12.5 (Sierra) on a mid-2012 MacBookPro
 - Version of EnergyPlus: Release version of V8.7
 - Unmethours link or helpdesk ticket number: none

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Thanks @RKStrand, glad to know it's being used and tested!  This should be an easy fix.

**Comment by RKStrand** [comment]
@Myoldmopar No problem--EP-Launch-Lite keeps getting better and that is good news for Mac users.  I really like the button that takes me directly to the results folder for a run.  And it seems to be pretty good now about running input files anywhere.

**Comment by jmarrec** [comment]
Could a mac user check if this issue is still happening with 9.4.0 please?

**Comment by jmarrec** [comment]
EP-launch will end up being replaced by EP-Launch3, and this has not been reported since 2017, closing. We can reopen if someone runs into it.
