### ISSUE TITLE
Unit heater operation suspect in combination with VAV reheat system in the same zone

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6189]
Issue overview
--------------
 Central AHU only has a chilled water coil and a VFD fan. Each zone has a VAV reheat terminal and a unit heater, both with electric resistance heater. The VAV terminal serves as the first stage heating. I re-ran the simulation and the problem still exists. 

See these two plots of North space for designday 2/21.
![image](https://user-images.githubusercontent.com/4991075/27712949-eda1c616-5cee-11e7-9de0-52a6eaed4356.png)

From the plots looks like the zone unit heater runs for some hours during the day, which it should not be, since the VAV terminal reheat coil has enough capacity to keep the zone temperature at or above the heating setpoint. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus v8.7
 - Helpdesk ticket number 11369

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Comparison of defect file results with original (above) after correction in #6203

![6189](https://user-images.githubusercontent.com/5778156/29236663-adde9450-7edb-11e7-80ba-2c0e19778adb.png)

**Comment by rraustad** [comment]
closed via #6203
