### ISSUE TITLE
Remove limits for "Minimum Outdoor Drybulb Temperature for Compressor Operation" field in DX Heating Coil objects

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6190]
Issue overview
--------------
All DX heating coil objects (space heating and water-heating) have an input field for "Minimum Outdoor Drybulb Temperature for Compressor Operation".  Most of them have a minimum specified in the IDD, while some do not.  Specifically, the limit was removed for multi-speed heat pumps in #4383.  

The minimum limit should be removed from the other DX heating coils, space heating coils for sure, and also water heating coils?

At a "minimum" :-) this requires IDD changes, but there may also be checks in the code that need to be removed.  And maybe some doc changes as well.

```
ZoneHVAC:PackagedTerminalHeatPump,
   N8 , \field Minimum Outdoor Dry-Bulb Temperature for Compressor Operation
        \type real
        \minimum -20.0

Coil:Heating:DX:SingleSpeed,
  N5 , \field Minimum Outdoor Dry-Bulb Temperature for Compressor Operation
       \type real
       \minimum -20.0

Coil:Heating:DX:VariableSpeed,
   N5,  \field Minimum Outdoor Dry-Bulb Temperature for Compressor Operation
        \type real
        \minimum -50.0

WaterHeater:HeatPump:PumpedCondenser,
  N4 , \field Minimum Inlet Air Temperature for Compressor Operation
       \type real
       \units C
       \minimum -5

WaterHeater:HeatPump:WrappedCondenser,
  N5 , \field Minimum Inlet Air Temperature for Compressor Operation
       \type real
       \units C
       \minimum -5
```
### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus v8.7
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] No defect files - should modify pertinent example files and test with a low limit.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6213
