### ISSUE TITLE
IDF Editor cleanup for v8.8 release

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6199]
Issue overview
--------------
- [x] Changes in #6114 result in a new input unit type 
![image](https://user-images.githubusercontent.com/4991075/27887165-d57dc99e-61a4-11e7-95c2-e17c39bb5218.png)

### Details
Some additional details for this issue (if relevant):
 - Platform Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
![image](https://user-images.githubusercontent.com/4991075/29461454-5f9804a0-83f1-11e7-9828-3bdf34b12dd0.png)

More units conflicts.  
@Myoldmopar The W/mK in the phase change PR should be W/m-K - need to fix the IDD for that.

**Comment by Myoldmopar** [comment]
Easy enough, I'll push that fix shortly.

**Comment by Myoldmopar** [comment]
Alright I pushed up my fix, as well as the start of a script that would do this validation for us in CI.  I guess it doesn't catch the "Unit Type for ... " types of fields, but it would be straightforward to add that in.

**Comment by Myoldmopar** [comment]
Feel free to address the other unit issues on that same branch if you like.

**Comment by mjwitte** [comment]
Nice

**Comment by JasonGlazer** [comment]
@Myoldmopar what branch?

**Comment by Myoldmopar** [comment]
It's already in develop, at `scripts/dev/validate_idd_units.py`

**Comment by JasonGlazer** [comment]
Ok, thanks

**Comment by mjwitte** [comment]
Closed via #6291
