### ISSUE TITLE
UnitarySystem unexpected fan operation

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#6200]
[E+ 8.7 in.idf](https://github.com/NREL/EnergyPlus/files/1129202/in.idf.txt)

The `UnitarySystem`'s fan is operating at full speed whenever there is a cooling load despite the fact that there is no cooling coil specified. I'd expect there to be zero fan energy when there is a cooling load.

![image](https://user-images.githubusercontent.com/5861765/27931308-01278d84-6257-11e7-9318-2a12087e3b78.png)

We've also tried setting the `Cooling Supply Air Flow Rate {m3/s}` field for the `UnitarySystem` to an extremely small number, hoping this would reduce the fan power to zero, but it did not.

According to the documentation: 

> Field: Supply Air Fan Operating Mode Schedule Name
> 
> This alpha field specifies the name of the supply air fan operating mode schedule. The supply air fan operating mode may vary during the simulation based on time-of-day or with a change of season. **Schedule values of 0 denote that the unitary system supply air fan and the heating or cooling coil cycle on and off together to meet the heating or cooling load (a.k.a. AUTO fan)**. Schedule values other than 0 denote that the supply fan runs continuously while the heating or cooling coil cycles to meet the load. The SingleZoneVAV control type is only active when the supply air fan runs continuously (i.e., during cycling fan operation the Control Type = Load model is used).
> 

This suggests that the fan should only operate when the heating/cooling coils are operating.

[Pivotal Story](https://www.pivotaltracker.com/story/show/148488195)

**Comment by rraustad** [comment]
This is an interesting dilemma. The UnitarySystem might not have a cooling or heating coil. And if that is the case then what is the design air flow rate for the mode where the coil does not exist? There is also nothing stopping a user from putting 2 UnitarySystems on the same branch. So if a downstream system needs a specific flow rate, how does the upstream system know what to do? If I assume only one UnitarySystem it's an easy fix. If I allow more than 1, then things get much harder.

The defect file has a single UntarySystem with a heating coil on the main branch. If a user also had a UnitarySystem with a cooling coil on that same branch, what air flow rate would the UnitarySystem with the heating coil operate at when cooling was required?

To keep the flexibility that UnitarySystem is supposed to have, then 2 things need to happen. One is that the UnitarySystem needs to broadcast that it needs air flow, and the second is that the UnitarySystem needs to act on that broadcast signal and pass through some air flow rate when needed.

**Comment by rraustad** [comment]
Step 1: stop setting an arbitrary air flow rate for the mode where a coil does not exist.

		// not sure what to do if UnitarySystem has only 1 coil type and flow needs to occur when present coil is off
		// how does constant fan operating mode pertain here?
    //		if ( UnitarySystem( UnitarySysNum ).HeatCoilExists && ! UnitarySystem( UnitarySysNum ).CoolCoilExists ) {
    //			UnitarySystem( UnitarySysNum ).MaxCoolAirVolFlow = EqSizing.HeatingAirVolFlow;
    //		} else if ( UnitarySystem( UnitarySysNum ).CoolCoilExists && ! UnitarySystem( UnitarySysNum ).HeatCoilExists ) {
    //			UnitarySystem( UnitarySysNum ).MaxHeatAirVolFlow = EqSizing.CoolingAirVolFlow;
    //		}

![image](https://user-images.githubusercontent.com/5778156/29245996-0ff5ed36-7fb9-11e7-9f3d-a6fca17968bd.png)

Step 2: figure out how to allow an air flow rate set by equipment external to the UnitarySystem.

**Comment by rraustad** [comment]
https://github.com/NREL/EnergyPlus/pull/6240

**Comment by mjwitte** [comment]
@rraustad We may need to rethink the flexibility here.  Somebody has to be king in setting the airflow on the branch, and that would be the supply fan.  Presumably only one unitary system should have a fan in it, or the fan is loose on the branch.  So, in my simple view, any unitary system object that doesn't have a fan should take whatever flow rate is present at it's inlet node and not mess with it.

**Comment by rraustad** [comment]
My first thought is that any UnitarySystem with a fan will set the air flow rate according to the air flow logic of cycling vs constant fan systems. Then any UnitarySystem without a fan will simply use the inlet air flow rate.

My second thought is that this won't work with existing control logic for cycling fan systems that iterates on a range of air flow rates to find the operating PLR.

My third thought is to revert the previous change and add a check for AutoSize in the code where air flow rate is set. That way the user could enter 0 for the air flow rate where a coil isn't used (i.e., cooling air flow = 0 if no cooling coil is present).

this is a revised version of the above commented code:

    // not sure what to do if UnitarySystem has only 1 coil type and flow needs to occur when present coil is off
    // how does constant fan operating mode pertain here?
    if ( UnitarySystem( UnitarySysNum ).HeatCoilExists && ! UnitarySystem( UnitarySysNum ).CoolCoilExists ) {
        if ( UnitarySystem( UnitarySysNum ).MaxCoolAirVolFlow == AutoSize ) UnitarySystem( UnitarySysNum ).MaxCoolAirVolFlow = EqSizing.HeatingAirVolFlow;
    } else if ( UnitarySystem( UnitarySysNum ).CoolCoilExists && ! UnitarySystem( UnitarySysNum ).HeatCoilExists ) {
        if ( UnitarySystem( UnitarySysNum ).MaxHeatAirVolFlow == AutoSize ) UnitarySystem( UnitarySysNum ).MaxHeatAirVolFlow = EqSizing.CoolingAirVolFlow;
    }

This should give the user what they wanted with this defect file and we can figure out what to do with other configurations later. 

I do like the suggestion to use if ( ! FanExists ) then use inlet air flow rate. Using this logic, the old HVACDXSystem with 2 systems on the branch and a dangling fan may still work.

**Comment by rraustad** [comment]
Easing into this without a major change, the revised code above gives the same result.

![image](https://user-images.githubusercontent.com/5778156/29298321-e746ee94-8134-11e7-975e-5226ff8412e0.png)

**Comment by nmerket** [comment]
@shorowit this was fixed in #6240 and has been merged.
