### ISSUE TITLE
Low Temperature Radiant Systems Autosize Tube Length Using Fixed Parameter

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#6202]
Issue overview
--------------
When a user asks EnergyPlus to autosize the tube length for either the hydronic (variable flow) or constant flow low temperature radiant systems, the program is currently using a default tube spacing of 0.15m (6 inches) rather than what the user has entered for tube spacing in the construction information.  This should be fixed to use what the user has entered for tube spacing.

### Details
Some additional details for this issue (if relevant):
 - Platform: all
 - Version of EnergyPlus: V8.7 (current)
 - Unmethours link or helpdesk ticket number: none

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
This was closed via #6239
