### ISSUE TITLE
Coil:Cooling:DX:VariableSpeed air-to-air coil autosizes cooling capacity using CapFT curve results based on RatedInletWaterTemp = 84.2

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6204]
Issue overview
--------------
line 3357 of VariableSpeedCoil:
TotCapTempModFac = CurveValue( VarSpeedCoil( DXCoilNum ).MSCCapFTemp( VarSpeedCoil( DXCoilNum ).NormSpedLevel ), MixWetBulb, RatedInletWaterTemp );

Found during development of unit test = UnitarySystem_MultispeedPerformance

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Adding a permalink for future reference. Notice the comment:

https://github.com/NREL/EnergyPlus/blob/9ce5c3eda4dd9333e1dfa7ffa3690274e022584c/src/EnergyPlus/VariableSpeedCoils.cc#L4082-L4084
