### ISSUE TITLE
Add DesignSpecification:OutdoorAir field and control to AirTerminal:SingleDuct:Uncontrolled and AirTerminal:SingleDuct:Mixer

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6205]
Issue overview
--------------
In order to make terminal units to determine the AirLoop flow rate as DOAS system, DesignSpecification:OutdoorAir field and control to AirTerminal:SingleDuct:Uncontrolled and AirTerminal:SingleDuct:Mixer is needed.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lgu1234** [comment]
In order to make terminal units to determine the AirLoop flow rate as DOAS system,  DesignSpecification:OutdoorAir field and control to AirTerminal:SingleDuct:Uncontrolled and AirTerminal:SingleDuct:Mixer is needed. Trane developed the code. This new feature will integrate the code in EnergyPlus.

**Comment by rraustad** [comment]
closed via #6223
