### ISSUE TITLE
Error -1073741819

### ISSUE THREAD

**Issue by eugeniorodrigues** [NREL/EnergyPlus#6207]
Issue overview
--------------
When running an house with plant loops with solar collectors, water use equipment and water heater mixed, sometimes EnergyPlus 8.7.0 for Windows 10 crashes with the output Error -1073741819. This can happen at any moment of the simulation. The output file err is empty.

### Details
Some additional details for this issue (if relevant):
 - MS Windows 10 (64 bits)
 - EnergyPlus 8.7.0

**Comment by jmarrec** [comment]
This issue is stale (sorry about that) and is lacking files to reproduce the defect. If by (a lot of) chance you happen to still have these files handy, please share them and I will reopen.
