### ISSUE TITLE
FanCoil Capacity Control Issues

### ISSUE THREAD

**Issue by zara1363** [NREL/EnergyPlus#6208]
EnergyPlus is run for small office in Houston Climate zone. HVAC system used is Fancoil unit coupled with DOAS.  Two Types of DOAS is tested: 1- DOAS with Chilled and Hot water for cooling and heating, 2- DOAS with DX cooling coil and Electric Heating.  When Testing different capacity control of fancoil units following errors will occurs many times. 
1- Full load outlet air dry-bulb temperature < 2C. This indicates the possibility of coil frost/freeze. This error for all types of fancoil control
2-  Part-load ratio cooling control failed in fan coil unit, When capacity control is Variable fan-Variable Flow
3- Exceeded max iterations while adjusting cycling fan sensible runtime to meet the zone load within the cooling convergence tolerance, When control capacity is variable Fan- Constant Flow
4-  Cold and Hot Water control failed in fan coil unit, When Control Capacity is ASHRAE 90, Variable Fan
However, The first error is detected when DOAS is equipped with DX cooling coil and Electric heating. 

What is the possible problem?

**Comment by jmarrec** [comment]
This type of question is best suited to unmethours.com, as it is likely this results from a user error in the IDF file. (sorry for the delay in treating your issue though)
