### ISSUE TITLE
EvaporativeCooler:Indirect:ResearchSpecial does not always set the secondary air outlet node conditions

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6211]
Issue overview
--------------
EvaporativeCooler:Indirect:ResearchSpecial only sets the secondary air outlet node conditions when these four fields have inputs:

```
EvaporativeCooler:Indirect:ResearchSpecial,

    0.75,                    !- Cooler Drybulb Design Effectiveness

    -99,                     !- Evaporative Operation Minimum Limit Secondary Air Drybulb Temperature
    99,                      !- Evaporative Operation Maximum Limit Outdoor Wetbulb Temperature
    99;                      !- Dry Operation Maximum Limit Outdoor Drybulb Temperature

```
If any one of these fields is blank, then `EvapCoolerOperationControlFlag` is set to false [here](https://github.com/NREL/EnergyPlus/blob/9a786ca0a17b0eb97c4641f31663b44367a3d54f/src/EnergyPlus/EvaporativeCoolers.cc#L645-L652)

And if `EvapCoolerOperationControlFlag` is false, then the secondary outlet node conditions are skipped [here](https://github.com/NREL/EnergyPlus/blob/9a786ca0a17b0eb97c4641f31663b44367a3d54f/src/EnergyPlus/EvaporativeCoolers.cc#L3212-L3217).  Not sure why this should be skipped here.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.7
 - Helpdesk ticket number 12149

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
@mjwitte Before the evaporator cooler operation control (advanced control features) was added, the outlet conditions of the secondary air stream were not calculated (and not reported). Evap cooler operation control needs all the three variables specified by the user.  The advanced evaporator cooler operation control feature was intended for Data Center HVAC application.

**Comment by mjwitte** [comment]
@Nigusse Do we have an example file that shows it working?  I tried adding the above fields to the DirectIndirectEvapCoolers example file and then that cooler never came on.
[DirectIndirectEvapCoolers-ActivateOperatingMode.idf.txt](https://github.com/NREL/EnergyPlus/files/1160065/DirectIndirectEvapCoolers-ActivateOperatingMode.idf.txt)

**Comment by Nigusse** [comment]
@mjwitte When that feature was added it worked and I expect it to work now. Let me check if I have those example files and I will also test the attached idf.

**Comment by Nigusse** [comment]
@mjwitte If the secondary air node is specified and EvapCooler type is "iEvapCoolerInDirectRDDSpecial", then the secondary air node properties should be available for reporting whether there is secondary air flow or not.  I am investigating this issue.

However, some Evap Cooler inlet conditions and user specified operating temperature limits combination (such as in the attached idf) may cause the Evapcooler to be turned off, .i.e, "*.EvapCoolerRDDOperatingMode = None", then the Evap cooler does not do any cooling and secondary air outlet condition are set to inlet condition. And the secondary air outlet condition were not reported because of the previous condition.

**Comment by Nigusse** [comment]
@mjwitte No secondary air outlet condition are calculated and reported unless the "*.EvapCoolerOperationControlFlag" is TRUE. This flag is turned on only when the operating range temperature limits fields (the last three input fields ) are not blank. It was made so, to allow the previous research special Evap Cooler model to run without this requirement and the previous model doesn't do any secondary air outlet condition calculation and reporting. For this reason the the secondary outlet node conditions reporting are skipped.

**Comment by mjwitte** [comment]
Well, that's fine as long as it's documented in the I/O Ref.  But I added these inputs to the example file (which is now the defect file) and my inputs caused the evap cooler to shut off.  Why?  I thought I was giving it unlimited room to operate with -99/+99.  Without the extra inputs (the base example file) the evap cooler runs.

**Comment by Nigusse** [comment]
The example file you provided was turned off for two reasons. First a logic needs to be fixed [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeCoolers.cc#L2335). The "TEDB <= InletDryBulbTempSec" should have been "TEDB < InletDryBulbTempSec" per the design document. Second, the advanced Evap cooler control feature works based on secondary air flow modulation and that requires wet and dry effectiveness modifier curves. Without the effectiveness modifier curves the secondary air flow modulation causes maximum iteration error. So the effectiveness modifier curves must be required fields when the "*.EvapCoolerOperationControlFlag" is TRUE.
