### ISSUE TITLE
@CpCW and @CpHW Erl functions both result in same value

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6214]
Issue overview
--------------
There are two built-in psychrometric Erl functions named @CpCW and @CpHW. These both accept water temperature as an argument, but both functions always return 4180 J/kg-K regardless of temperature value input. It is confusing and misleading to have two functions that both return the same result.

As a solution, I would suggest removing these two Erl functions and replacing them with a built-in Erl variable for specific heat of water similar to the built-in Erl variable PI for the mathematical constant 3.14159265358979.

**Comment by jmarrec** [comment]
I cannot find any trace of the lower case `cpcw` function nowadays (circa 9.4.0)
