### ISSUE TITLE
Failing EnergyPlus unit test on develop

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6215]
We’ve been seeing some issues with the AirTerminalSingleDuctMixer_SimPTAC_HeatingCoilTest unit test that is [here](https://github.com/NREL/EnergyPlus/blob/develop/tst/EnergyPlus/unit/PackagedTerminalHeatPump.unit.cc#L530):

It fails in some cases, passes in others:
1) The test passes when built in Debug mode
2) The test passes when built in Release mode and run by itself
3) The test fails when built in Release mode and run with other unit tests

### Details
The CI machine builds in Release mode and runs the unit tests individually, so that is why it isn’t appearing as a failure in the online dashboard. Building in 32 bit may result in further permutations, I haven’t tried that. What I have tried is building in Release mode on different Windows machines and one Linux VM, and this unit test fails on all of them.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6216
