### ISSUE TITLE
VRF:FluidTemperatureControl crashes with Fan:SystemModel

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6218]
Issue overview
--------------
User file crashes with VariableRefrigerantFlow:FluidTemperatureControl and Fan:SystemModel.  

Crash occurs [here](https://github.com/NREL/EnergyPlus/blob/9ff1a0bf8d1c66ced5d5aa23aaed80891e6b8d96/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L3323) trying to access fan data without checking fan type.  There are some other similar places that need fixing as well - search on FanIndex.

Also, some documentation issues:

1) I/O Ref 1.30.15 vrf terminal - Fan type description does not reflect new fan type or fan type requirements of new VRF type.  This is clear in the idd file.

2) Getting weird errors.  New model requires the terminal to reference new coil models but error message is not at all clear and manual makes not mention of this for VRF unit or terminal.  In the coil documention it mentions applicability which led me in the right direction but it could be worded better.  Suggestion: Clean up error messages, and move Energy+.idd discussion of  vrf terminal coil fields into the manual for the terminal object.

### Workaround
Use Fan:VariableVolume instead.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus - tested with current version on branch for #6079, 864269532b
 - Direct e-mail, July 21, MK

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Issue with GetInput. Correction is fairly straight-forward.

![image](https://user-images.githubusercontent.com/5778156/29052266-e5ca6b50-7bb6-11e7-9943-5c1b36959b02.png)

**Comment by rraustad** [comment]
See PR #6232

**Comment by mjwitte** [comment]
Closed via #6232
