### ISSUE TITLE
Zone air flow mass balance is broken

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6219]
Issue overview
--------------
Zone air flow mass balance is broken. Testing 5ZoneAirCooled_ZoneAirMassFlowBalance.idf example file in develop and in EnergyPlus version 8.7 shows that zone air flow mass conservation is broken. 

### Details
Some additional details for this issue (if relevant):
 -Version of EnergyPlus v8.7
 - defect was notices while fixing #6119 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Close via #6272
