### ISSUE TITLE
System output provided and single duct zone HVAC equipment load calculation use different cp air values

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6220]
Issue overview
--------------
System output provided variable "SysOutputProvided" calculated [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SingleDuct.cc#L2902-L2907) and
the load passed to reheat heating coil calculated [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneAirLoopEquipmentManager.cc#L769-L772) use different cp value of supply air that results in remaining output required variable to have residual value updated [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneEquipmentManager.cc#L3687-L3689) and passed to the next priority zone HVAC equipment.  

The cp value of air based on the supply air condition entering the air terminal reheat coil and cp value of air determined using zone air condition can result in load difference of up to 15 Watts (based on defect file tested). This load difference cased by cp value calculation reference is significant enough to trigger the second priority zone HVAC equipment connected to a zone.

Suggestion: change the reheat coil load calculation for example [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SingleDuct.cc#L2902-L2907) to this form:
QZnReq = QZoneMax2 - MassFlow *  ( CpAirSys * SysInlet( SysNum ).AirTemp - CpAirZn * ZoneTemp );
CpAirSys = PsyCpAirFnWTdb( SysInlet( SysNum ).AirHumRat, SysInlet( SysNum ).AirTemp); 

Similar change may be required for gas reheat coils [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SingleDuct.cc#L2895-L2900) and steam heating coils [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SingleDuct.cc#L2909-L2914).

### Details
Some additional details for this issue (if relevant):
 - Win64
 - EnergyPlus Version 8.7
 - observed during investigation of issue #6189

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Closed via #6226.
