### ISSUE TITLE
ChillerHeaterPerformance:Electric:EIR doesn't check the curve types

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#6224]
Issue overview
--------------
There is no check done to verify the type of curve assigned to a `ChillerHeaterPerformance:Electric:EIR`.

Here's where it's retrieved: https://github.com/NREL/EnergyPlus/blob/a5b04d73ecfef706cda7d0543ccad31e7c27087a/src/EnergyPlus/PlantCentralGSHP.cc#L988

Specifically, the E+ example itself (sic!) `CentralChillerHeaterSystem_Cooling_Heating.idf`  does use Cubic curve for the cooling eirFPLR, but if you look at the E+ idd for 8.7 at least, it expects a Bicubic or a Quadratic

**CentralChillerHeaterSystem_Cooling_Heating.idf**

```
  ChillerHeaterPerformance:Electric:EIR,
    ChillerHeaterModule 1,   !- Name
    [...]
    ChillerHeaterClgEIRFPLR, !- Cooling Mode Electric Input to Cooling Output Ratio Function of Part Load Ratio Curve Name
    [...]

  Curve:Cubic,
    ChillerHeaterClgEIRFPLR, !- Name
    0.0,                     !- Coefficient1 Constant
    1.22895,                 !- Coefficient2 x
    -0.751383,               !- Coefficient3 x**2
    0.517396,                !- Coefficient4 x**3
    0.2,                     !- Minimum Value of x
    1;                       !- Maximum Value of x

```

**Energy+.idd.in**

```
ChillerHeaterPerformance:Electric:EIR,
   [...]
  A7 , \field Cooling Mode Electric Input to Cooling Output Ratio Function of Part Load Ratio Curve Name
       \note Electric Input Ratio (EIR) as a function of Part Load Ratio (PLR)
       \note EIR = 1/COP
       \required-field
       \type object-list
       \object-list BicubicCurves
       \object-list QuadraticCurves
       \object-list UniVariateTables
       \object-list BiVariateTables
```

There are cases in the code where such a check is done, eg: https://github.com/NREL/EnergyPlus/blob/a5b04d73ecfef706cda7d0543ccad31e7c27087a/src/EnergyPlus/MicroturbineElectricGenerator.cc#L741

### Details
Some additional details for this issue (if relevant):
 - Platform: All
 - Version of EnergyPlus: 8.7.0 (but checked again current develop as of 2017-07-27)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
In this case, the IDD and the documentation are inconsistent with the model.  The I/O ref and list of curve types say that a bi-variate curve can be used to make EIRfPLRT.  But a quick inspection of the code shows that this curve is always evaluated with a single independent variable of PLR.  So, either the code needs to be changed to support the bi-cubic (or really any bi-variate form) or mention of this should be deleted from the docs and IDD.

Ultimately, the number of independent variables is the only thing that should matter.  The calling component model doesn't care (or need to know) if the curve is linear, quadratic, cubic, etc. It simply passes PLR as the first independent variable and the curve manager evaluates the curve.  If we don't change the code to add support for the bi-cubic curve, then it doesn't really need to check the curve type, and the IDD should be
       \object-list UniVariateCurves
       \object-list UniVariateTables

In general, we don't want the component models to care about the form of the curve or table, just the number of variables.  I suppose the curve manager could be modified to throw a warning if a curve with x independent variables is evaluated with <>x variables passed to it.

**Comment by jmarrec** [comment]
I'm pretty sure the intended behavior originally was to have support for BiVariateCurves. I shouldn't have truncated the extract from the IDD file, but here it is in full with the notes:

```
A7 , \field Cooling Mode Electric Input to Cooling Output Ratio Function of Part Load Ratio Curve Name
       \note Electric Input Ratio (EIR) as a function of Part Load Ratio (PLR)
       \note EIR = 1/COP
       \required-field
       \type object-list
       \object-list BicubicCurves
       \object-list QuadraticCurves
       \object-list UniVariateTables
       \object-list BiVariateTables
       \note  Bicubic = a + b*TCond + c*TCond**2 + d*PLR + e*PLR**2 + f*TCond*PLR +g*0 + h*PLR**3+i*0+j*0
       \note    If ClgModeCondWaterCurveInputVariable = EnteringCondenser, TCond = ECT
       \note    If ClgModeCondWaterCurveInputVariable = LeavingCondenser, TCond = LCT
       \note    Normally, a bicubic curve here should be in terms of LCT rather than ECT
       \note    Also, a bicubic curve is more applicable for variable-speed compressor motor drives
       \note or
       \note  Quadratic = a + b*PLR + c*PLR**2
       \note PLR = part load ratio (cooling load/steady-state capacity)
       \note LCT = leaving condenser fluid temperature(C)
       \note ECT = entering condenser fluid temperature(C)
```
