### ISSUE TITLE
Add more choices of Outdoor Air Method in DesignSpecification:OutdoorAir

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6225]
Issue overview
--------------
OA methods specified in the Controller:MechanicalVentilation can not be applied to terminal units directly. This can be achieved by using DesignSpecification:OutdoorAir object. However, the OA methods are limited in DesignSpecification:OutdoorAir. Several choices will be added.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Closed via #6223
