### ISSUE TITLE
Followup to #6158

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#6228]
- unify use of CondenserInletAirTemp between parent and child (both use same information)
- change function call to use int's
- revise input field name? to Minimum Condenser Inlet Air Temperature for Compressor Operation
- VS DX coil example files all use a unity performance curve for Total Cooling Capacity Function of Air Flow Fraction Curve Name. This can lead to RH > 100% issues. A valid curve needs to be developed from manufacturers data (does this even exist) or other source.
- remove minimum outdoor temp for compressor operation field from WSHP and mine information from child object

**Comment by rraustad** [comment]
Not sure I trust these but some Capacity as a Function of Air Flow curves found here:
http://simulationresearch.lbl.gov/modelica/releases/latest/help/Buildings_Fluid_HeatExchangers_DXCoils_AirCooled_Data_SingleSpeed.html#Buildings.Fluid.HeatExchangers.DXCoils.AirCooled.Data.SingleSpeed.Generic

![capfairflow](https://user-images.githubusercontent.com/5778156/28755530-29063314-752b-11e7-8ac9-2bbfde2c6eb7.png)

**Comment by rraustad** [comment]
@mjwitte  do you feel strongly about changing the input field name for Minimum Outdoor Temperature for Compressor Operation to Minimum Inlet Air Temperature for Compressor Operation? If so, I'd like to get this in before release.

**Comment by mjwitte** [comment]
No.

-------- Original message --------

**Comment by rraustad** [comment]
Working on resolving differences in MinOAT. For multispeed HP I see that the parent and both MS coils have an input for Min OAT for compressor op. If there is a discrepancy, who wins? I'm leaning towards the parent, but the input in the parent object is not even needed, just use the inputs in the coil objects.

```
   ** Warning ** AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed:DXAC HEAT PUMP 1
   **   ~~~   ** Minimum Outdoor Dry-Bulb Temperature for Compressor Operation = -8.000
   **   ~~~   ** Coil:Cooling:DX:MultiSpeed:HEAT PUMP ACDXCOIL 1 Minimum Outdoor Dry-Bulb Temperature for Compressor Operation = -25.000
```

MultispeedHeatPump example file:
```
  AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed,
    -8.0,                    !- Minimum Outdoor Dry-Bulb Temperature for Compressor Operation {C}

  Coil:Heating:DX:MultiSpeed,
    -8.0,                    !- Minimum Outdoor Dry-Bulb Temperature for Compressor Operation {C}

  Coil:Cooling:DX:MultiSpeed,
    ,                        !- Minimum Outdoor Dry-Bulb Temperature for Compressor Operation {C}
```

**Comment by rraustad** [comment]
I guess the best way forward is to use the coil object inputs, so there are 2 inputs for cooling and heating, and deprecate the input in the AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed object. This is the same way UnitarySystem does it, using a MinOATCompressorCooling and MinOATCompressorHeating to control operation and each of these are mined from the coil objects.
