### ISSUE TITLE
Documentation Margins

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#6229]
It's 2017.  And almost no one is printing the docs.  Could we consider shrinking the page margins down to fit more content per page and longer equations, etc.?

**Comment by mjwitte** [comment]
Printed or not, the left/right/bottom margins do seem a bit wide.  Could probably cut them in half and still maintain the aesthetics of the page.

**Comment by Myoldmopar** [comment]
I was able to get the bottom and sides down to 0.5" and it looked good.  The top didn't benefit from the margin change because the header got smushed up against the page border.  This still made a nice change.  PR opened and sent to @michael-okeefe for a quick review, but if you happen to build docs with this change and they look good to you, feel free to merge the PR.
