### ISSUE TITLE
Remove a section with ZoneMassFlowRate <= 0.0 in moisture balance equation

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6233]
Issue overview
--------------
#6119 corrected items related to exhaust mass flow rate with ZoneMassFlowRate > 0.0 in moisture balance equation. The section with ZoneMassFlowRate <= 0.0 is not needed and should be removed in order to be consistent with energy balance equation.
 
### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #6415
