### ISSUE TITLE
HVACSystemRootFindingAlgorithm not writing correctly to eio output

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6267]
Issue overview
--------------
The eio output for `HVACSystemRootFindingAlgorithm` comes out like this:
```
! <Zone Air Solution Algorithm>, Value {ThirdOrderBackwardDifference | AnalyticalSolution | EulerMethod}
 Zone Air Solution Algorithm, NO
```
It's written from [here](https://github.com/NREL/EnergyPlus/blob/fabf0a4f65edf6e4605030f83e77746f3bcca8a3/src/EnergyPlus/HeatBalanceManager.cc#L1265-L1267).  Two problems:
1.  If the object isn't present, Alphanames( 1 ) is not set to the default string, so it still holds whatever the prior value was.
2.  It's using the formats for `<Zone Air Solution Algorithm>`.  This needs new formats of its own.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus Version 8.7.0-153e6294a3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file  - any example file will show the problem.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Close via #6279.
