### ISSUE TITLE
Fix Severe Errors and Warnings in Test Suite IDF Files

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#6271]
I ran the test suite files to get an idea how many severe errors or warnings are occurring currently in the test suite. The results can be found here: https://gist.github.com/mitchute/c4b16cc0807f8c291dddd09e7378181c

Summary:
40 Severe Errors
1487 Warnings

Disclaimer: I didn't run expand objects or any of the other preprocessors, so those files are likely not included in this list, although we may find that some go away once that is resolved. I also only passed the Chicago weather file, so there are also some spurious weather file warnings.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6316
