### ISSUE TITLE
Electric Baseboard Providing Negative Heating

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#6276]
A problem was noted with electric radiant/convective baseboard units where there were strange occasional occurrences of negative heating rates being provided by the baseboard unit.  This should never happen.  While simply zeroing out negative loads would be one short-term solution, it is possible that the calculation of ZeroSourceSumHAT is not being updated properly.  If this is the source of the problem, then it could be an issue for other radiant/convective units that also use this variable.  So, this needs to be investigated for this model and then potentially looked at for other models as well.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus (if using an intermediate build, include SHA): V8.8
 - Rich Raustad identified the negative load issue
[BaseboardsOperatingWithNegativeLoadMet.idf.txt](https://github.com/NREL/EnergyPlus/files/1253787/BaseboardsOperatingWithNegativeLoadMet.idf.txt)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ x ] Defect file added (attached to this issue)
 - [ x ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
This is ID#150572819 in PivotalTracker

**Comment by RKStrand** [comment]
@rraustad @Myoldmopar @mjwitte This is now fixed and a pull request will be created shortly.  The defect file attached above does not report any negative baseboard heating after the fix.  While in the code, I also cleaned up the variable assignments for when the device is on and off (new routines) and eliminated extra comment lines there were basically blank holdovers from F90 days.

**Comment by rraustad** [comment]
Closed via #6277.
