### ISSUE TITLE
SimHVAC max iteration warnings caused by Coil:Heating:Gas:MultiStage

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6282]
Issue overview
--------------
User file has a simple system with unitarysystem, fan:systemodel, single speed DX, and multistage gas heat, all set to 1 speed.   It runs fine most of the time, but it's throwing seemingly random max iteration warnings.  First one happens at 01/06 02:15.  There's a small heating load, but for some reason, the system is showing that it's running at full flow.  The max iteration data says some part of the system wants to be at zero.

Preliminary diagnosis:

The first thing I noticed was the NoLoadCapacity was non-zero and that air flow at PLR=0 was also non-zero. For cycling fan cases these should be 0 (i.e., 0 flow = 0 capacity). I followed code into SetOnOffMassFlowRate and see that the multi-stage heating coil sets the idle speed flow rate (which I think is only used for DX equipment) at speed 0 which makes no sense since that model doesn't have an idle speed air flow rate input or any air flow rate inputs for that matter. I also saw the fix for 5518 just below (https://github.com/NREL/EnergyPlus/pull/5519). I copied that code up to where HeatSpeedNum < 1 and now there are no warnings.

Another thought is that the idle speed air flow rate for multi-stage coils could be set to 0.

I also think the else is wrong for HeatSpeedNum== 1. The CompOffMassFlow should be idle speed air flow rate?

    if ( HeatSpeedNum < 1 ) {
        if ( UnitarySystem( UnitarySysNum ).MultiSpeedHeatingCoil ) {
            CompOffMassFlow = 0.0; // #5518
            CompOffFlowRatio = 0.0;
        } else {
            CompOffMassFlow = UnitarySystem( UnitarySysNum ).IdleMassFlowRate;
            CompOffFlowRatio = UnitarySystem( UnitarySysNum ).IdleSpeedRatio;
        }
    } else if ( HeatSpeedNum == 1 ) {
        if ( UnitarySystem( UnitarySysNum ).MultiSpeedHeatingCoil ) {
            CompOffMassFlow = 0.0; // #5518
            CompOffFlowRatio = 0.0;
        } else {
            CompOffMassFlow = UnitarySystem( UnitarySysNum ).HeatMassFlowRate( HeatSpeedNum );
            CompOffFlowRatio = UnitarySystem( UnitarySysNum ).HeatMassFlowRate( HeatSpeedNum );
        }
    } else {

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6284
