### ISSUE TITLE
Transition fails on very long Schedule:Compact object with 26000+ fields

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6287]
Issue overview
--------------
Transition from v8.7 to v8.8 crashes with an array bounds error on this file.
```
At line 3112 of file C:\ci\EnergyPlus-V8.8.0IDDF-Win64-VS14\src\Transition\InputProcessor.f90
Fortran runtime error: Array bound mismatch for dimension 1 of array 'tempcharacter' (4500/4520)
```
That section of the code looks like this (lines 3109:3112)
```
    if (ObjectDef(ObjectNum)%NumAlpha+NumNewAlphas > MaxAlphaArgsFound) then
      ! must redimension LineItem args
      ALLOCATE(TempCharacter(ObjectDef(ObjectNum)%NumAlpha+NumNewAlphas))
      TempCharacter(1:ObjectDef(ObjectNum)%NumAlpha)=LineItem%Alphas
```
After some trial and error and searching the code, found these line at 411:414
```
     IF (.not. ALLOCATED(LineItem%Numbers)) ALLOCATE (LineItem%Numbers(MaxNumericArgsFound+20))
     IF (.not. ALLOCATED(LineItem%NumBlank)) ALLOCATE (LineItem%NumBlank(MaxNumericArgsFound+20))
     IF (.not. ALLOCATED(LineItem%Alphas)) ALLOCATE (LineItem%Alphas(MaxAlphaArgsFound+20))
     IF (.not. ALLOCATED(LineItem%AlphBlank)) ALLOCATE (LineItem%AlphBlank(MaxAlphaArgsFound+20))
```
Removing the "+20" from these lines fixes the problem for this file.  Question is whether that's a general solution.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of Transition-V8-7-0-to-V8-8-0.exe, develop as of https://github.com/NREL/EnergyPlus/commit/001b3a8b6586a169ecaaab5666a8d77d53d15a18
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file is the one attached to #6200 
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6288
