### ISSUE TITLE
Add documentation for calling EnergyPlus as a library to the Interface Developers Guide (or where appropriate)

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6292]
Issue overview
--------------
per @Myoldmopar 
I don't think there's any proper documentation for calling it as a library, but it's really rather easy:

  *   Compile against the EnergyPlusPgm.hh file at src/EnergyPlus/public/EnergyPlusPgm.hh
  *   Dynamic link with the EnergyPlusAPI.dll library
  *   Have your C++ (or whatever) set up a run directory with in.idf, in.epw, etc.
  *   Optionally have your C++ (or whatever) code call into the Callback functions so that your C++ code can get progress and status updates during the simulation
  *   Finally, have your C++ (or whatever) code call into the EnergyPlusPgm() function with a file path (I thought this was a run directory, but maybe not) as the only argument

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
[This file](https://github.com/NREL/EnergyPlus/blob/3ef1eaf299a4db7fb70d10ade1c7b993d5c694ff/src/EnergyPlus/test_ep_as_library.cc) demonstrates the above code steps. And [these CMake lines](https://github.com/NREL/EnergyPlus/blob/dc34fec00d3e11fd9a49f3a5e1f65cd17bd2fdef/src/EnergyPlus/CMakeLists.txt#L630-L631) show how to compile it into a useful program.  

Yeah, interface developers guide should be good.

**Comment by jmarrec** [comment]
Should we close this issue?

**Comment by Myoldmopar** [comment]
Yeah, given the new API land, I think we should close this.
