### ISSUE TITLE
VRF Terminal unit flow balance problems

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6301]
Issue overview
--------------
1. Found this while investigating error diffs from #6272 VariableRefrigerantFlow_FluidTCtrl_HR_5Zone because it tripped new zone unbalanced flow warnings. Reporting the node flow rates shows that TUn Outlet Node flow is always significantly less than TUn Inlet Node flow.  Also made a version of VariableRefrigerantFlow_5Zone with cycling fan and the inlet outlet node flow rates are all over the place (sometimes more, sometimes less).

For both the VRF:HR and VRF without HR, using VariableTemp control results in flow imablances.  Use ConstantTemp control is ok (this is with cycling fan).  So, it may be only certain combinations of cycling fan and VRF AC control type that are broken.  Ultimately will need to test all combinations.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus Version 8.8.0-ddaa5689de
 - Helpdesk ticket 12306
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Apparent adjustment to outlet air flow after inlet node air flow is set.

![vrf_fluidtctrl_flowimbalance](https://user-images.githubusercontent.com/5778156/30701173-9c6499d0-9eb7-11e7-9b4c-cdd625a0945f.png)

**Comment by rraustad** [comment]
It looks like it happens here where the next Te/Tc is calculated for the next time step. This routine sets
the air flow rate again for some reason. I don't know enough about the model to make an educated guess. @rongpengzhang can you take a look at this?

![vrf_fluidtctrl_flowimbalancecode](https://user-images.githubusercontent.com/5778156/30709038-db70e022-9ece-11e7-86f1-084ed7853e56.png)

**Comment by rraustad** [comment]
@rongpengzhang do you only need to calculate Te/Tc on the first pass through for each time step? Would calling CalcVRFIUTeTc_FluidTCtrl only when FirstHVACIteration = true be OK? The next time through the TUs would respond differently and cause Te/Tc to change again, but I see nothing in code that forces model iterations until Te/Tc converges? So I don't know what to do here.

**Comment by rraustad** [comment]
It would be nice if I knew what this model was supposed to do. I made some changes and get this:

![image](https://user-images.githubusercontent.com/5778156/57478065-035b6f80-7268-11e9-8462-8ccc4964faed.png)
