### ISSUE TITLE
Airloop with zero design heating load crashes in AirLoopComponentLoadSummary

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6307]
Issue overview
--------------
Stumbled onto this while testing defect files for #6173.  Both VAV airloops in this file have zero design heating load, and they crash [here](https://github.com/NREL/EnergyPlus/blob/91933e29e35a5e085d8e9ddfe8a7d9ba21939623/src/EnergyPlus/OutputReportTabular.cc#L11812) because `heatDesSelected` is zero.  Looks like the same problem would occur a few lines above if a loop had no design cooling load.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.8.0 ddaa5689de

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@JasonGlazer Would you be able to look at this in the next day or so?

**Comment by JasonGlazer** [comment]
Sure

**Comment by Myoldmopar** [comment]
Closed via #6334
