### ISSUE TITLE
Fault model coil fouling for hot water heating coil does not appear to be working

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6313]
Issue overview
--------------
User file has a FaultModel:Fouling:Coil attached to a Coil:Heating:Water.  The coil output, water flow and all other results are identical with and without the fault model.  User reports that it also has no impact on cooling coils.

Another ticket complains about the cooling coil, with test file.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.8.0 f4f8b9e466
 - Helpdesk ticket 12279 abd 12144

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I see a difference in patterns being used and wouldn't mind guidance.

**Should the Fault object reference the object it's fouling, or the other way around?**

It seems that Boilers, Chillers, etc are the ones including an Index to the Fault object: eg ElectricEIRChillerSpecs' FaultyChillerFoulingIndex https://github.com/NREL/EnergyPlus/blob/588fe91ef15aedef7c68a25117c1e27ec8293a43/src/EnergyPlus/ChillerElectricEIR.hh#L170

Yet FaultModel:Fouling:Coil has an index FouledCoilID (and WaterCoil doesn't include a placeholder for a FaultyIndex): https://github.com/NREL/EnergyPlus/blob/588fe91ef15aedef7c68a25117c1e27ec8293a43/src/EnergyPlus/FaultsManager.hh#L232

**Comment by jmarrec** [comment]
I don't think it's needing both directions, and I'd say that having the object reference its fault model is better because it avoids having to loop on all fault objects everytime, but that means modifying `WaterCoils::WaterCoilEquipConditions` to add an int that isn't going to be used that often.

**Comment by rraustad** [comment]
The UnitarySystem uses a call to the fault manager instead of a call from fault manager to UnitarySystem. I had the same epiphany as you when connecting this to UnitarySystem. The only issue is if name/type in the fault manager does not match a valid UnitarySystem object (e.g., misspelling) and how to warn the user. I don't recall if I addressed that or not.

FaultsManager.cc line 1035

    } else if (UtilityRoutines::SameString(SELECT_CASE_VAR, "AirLoopHVAC:UnitarySystem")) {
        // UnitarySystem model connects to FaultManager via function call to FaultsManager::SetFaultyCoilSATSensor
