### ISSUE TITLE
RoomAirModelManager::CheckEquipName function possible issues

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6321]
Issue overview
--------------
For #6272, need to eliminate use of ZoneEquipConfig.ReturnAirNode and search through all possible return nodes.  Posting this issue now, but I will be working in this code, so any changes here should wait at least until #6272 is complete and merged.

Looking at [this function](https://github.com/NREL/EnergyPlus/blob/404d30d66fdb6101627578132a274c648a2ffeee/src/EnergyPlus/RoomAirModelManager.cc#L2822-L2849), it is getting various zone equipment objects and assigning node names based on Alpha( n ).  This is fragile if the alphas move there won't be any way to know this is broken (test file only uses PTACs). This should either use mining functions to get node numbers from the equipment, or after the JSON input processor drops in, this could grab node names using field names directly.

Also, [this code](https://github.com/NREL/EnergyPlus/blob/404d30d66fdb6101627578132a274c648a2ffeee/src/EnergyPlus/RoomAirModelManager.cc#L2983-L2985) for AirLoopHVACReturnAir does not look correct.  Since there is no such object type, the alphas will be empty.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@lgu1234 Hmm, all the supply nodes for air terminals use Alphas( 1 ) which looks incorrect.

**Comment by lgu1234** [comment]
@mjwitte You are right. Most supply node names of air terminal objects are Alphas( 3 ). Some use 4, 5 and 9. I will wait until #6272 is merged.

**Comment by mjwitte** [comment]
@lgu1234 For the zone equipment, I noticed that there are already a set of functions to get the various nodes, e.g. `FanCoilUnits::GetFanCoilZoneInletAirNode`.  They're used by SystemReports::ReportMaxVentilationLoad, so there's a full list of them [here](https://github.com/NREL/EnergyPlus/blob/8dc1d02c8854097f8fe255435560a98d76365b2d/src/EnergyPlus/SystemReports.cc#L3941-L3971).  Of course, this will force those to do a full getinput instead of the side path used here, so that may or may not be a good thing.  Probably want to try one first before changing them all.
