### ISSUE TITLE
Autosized Coil in OutdoorAirUnit.idf Fails to Converge on UA

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#6324]
From issue #6316 

This file has two Coil:Cooling:Water objects; one fully autosized, the other with user defined numerical inputs. The autosized coil fails to converge on a UA value. I copied the numerical inputs over to the autosized coil and the severe error went away. This looks like there may need to be some investigation into what could be going wrong with autosizing.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 7 SP2
 - Version of EnergyPlus: Pre 8.8. 0c736af1ca11d92f9d639de67236f3c6051eecfb

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Cannot reproduce in EnergyPlus 9.0.1, there isn't any Severe error anymore.
