### ISSUE TITLE
VAV design minimum cooling air flow fraction > 1.0 when system adjusts zone flows

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6327]
Issue overview
--------------
- [x] Defect file for #6218 shows new warnings.  Not sure if this is the result of #6248 or #6140 .  Should this warning even be happening.  And if so, do fractions >1.0 make any sense?  And in any case, the units are wrong.
```
   ************* SizeHVACSingleDuct: Potential issue with equipment sizing for AirTerminal:SingleDuct:VAV:NoReheat = "CORE_BOTTOM ATU".
   **   ~~~   ** User-Specified Minimum Cooling Air Flow Fraction of 1.00000 [m3/s]
   **   ~~~   ** differs from Design Size Minimum Cooling Air Flow Fraction of 1.47043 [m3/s]
   **   ~~~   ** This may, or may not, indicate mismatched component sizes.
```
Pretty sure this came is as a result of #6140.

Preliminary look at this says it's because system sizing is using ventilation requirement  so the original cooling vol flow rate has been reduced. But then why is the DesCoolVolFlowMin > the OA requirement which should result in a 1.0 min frac.
One solution is in SingleDuct::SizeSys around line 2116, `MinAirFlowFracDes` should be limited to no more that 1.0.
That's probably useful, but either DesCoolVolFlowMin or Sys.MaxAirVolFlowRate is wrong at this point.

- [x] Also, noticed there are twice as many TermUnitSizing objects as zones when debugging. 
*That's correct.  There is one TermUnitsizing object for each zone inlet node, so if there is zone equipment there will be extra instances of TermUnitSizing.*

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 8.8.0 9bd43c6688
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added use the defect file for #6218
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6338
