### ISSUE TITLE
AirTerminal:SingleDuct:Mixer leaving air conditions invalid when zone equip flow < primary flow for InletSide

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6332]
Issue overview
--------------
DOAToWaterToAirHPInlet test file fails in branch #6272 with a negative density during warmup because the Space2-1 mixer outlet node temperature is -279C.  This is happening because the primary air mass flow rate is greater than the mixed air mass flow rate (entering the heat pump), so the mixed outlet enthalpy and humidity calculations are bogus here (more mass flow in the divisor than in the dividend (they should be equal).  

The same thing is happening in develop, just not to the same degree.  Why?  Because in develop, the return node max avail flow rate is set to the zone node max avail which is small because the heat pump is cycling.  In #6272 the return max avail is paired with the primarly inlet node max avail.

Looking at develop, with the defect test file that reports during warmup, you can see here that the space2-1 heat pump inlet node temp is 1207C
![image](https://user-images.githubusercontent.com/4991075/30656507-fae77a18-9df9-11e7-98b1-4815c6a8166e.png)

The proposed fix is to limit primary air flow to be <= the mixed air mass flow (which is set by the zone equipment).  

Will put this up shortly and see what happens to all of the DOATo* files.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus  8.8.0 914052f563

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6333
