### ISSUE TITLE
VRF with Fan:systemModel Runs When Fan:OnOff Wouldn't have run

### ISSUE THREAD

**Issue by energysims** [NREL/EnergyPlus#6336]
I have a ZoneHVAC:TerminalUnit:VariableRefrigerantFlow object with 24/7 availability and fan mode specified as 0 so the fan should cycle on as need and otherwise be on.  The terminal fans behave the same with Fan:systemmodel and Fan:onoff except during hours where there is no load in which case Fan:onoff turns off and fan:systemmodel turns full on and runs that way until there is an hour with load.  

### Details
Some additional details for this issue (if relevant):
 - Windows 7
 - :EnergyPlus, Version 8.7.0-78a111df4a, 

[fanOperationTest.zip](https://github.com/NREL/EnergyPlus/files/1319611/fanOperationTest.zip)

**Comment by rraustad** [comment]
@EnergyArchmage this user file highlights a problem with the system fan. When the VRF model determines that the system is off, and sets inlet air mass flow rate = 0 and PLR = 0, when the system fan is called it doesn't result in 0 power.

Basically one of these returns where PLR = 0 and VRF TU inlet mass flow = 0.

Function ControlVRF at line 6063:

    // do nothing else if TU is scheduled off
    //!!LKL Discrepancy < 0
    if ( GetCurrentScheduleValue( VRFTU( VRFTUNum ).SchedPtr ) == 0.0 ) return;
    // do nothing if TU has no load (TU will be modeled using PLR=0)
    if ( QZnReq == 0.0 ) return;

On the return from ControlVRF, the code will then call CalcVRF and model the fan. The fan does not respond to PLR = 0.

    if ( VRF( VRFTU( VRFTUNum ).VRFSysNum ).VRFAlgorithmTypeNum == AlgorithmTypeFluidTCtrl ) {
    // Algorithm Type: VRF model based on physics, appliable for Fluid Temperature Control
        VRFTU( VRFTUNum ).ControlVRF_FluidTCtrl( VRFTUNum, QZnReq, FirstHVACIteration, PartLoadRatio, OnOffAirFlowRatio );
        VRFTU( VRFTUNum ).CalcVRF_FluidTCtrl( VRFTUNum, FirstHVACIteration, PartLoadRatio, SysOutputProvided, OnOffAirFlowRatio, LatOutputProvided );
        //CalcVRF( VRFTUNum, FirstHVACIteration, PartLoadRatio, SysOutputProvided, OnOffAirFlowRatio, LatOutputProvided );
    } else {
        // Algorithm Type: VRF model based on system curve
        ControlVRF( VRFTUNum, QZnReq, FirstHVACIteration, PartLoadRatio, OnOffAirFlowRatio );
        CalcVRF( VRFTUNum, FirstHVACIteration, PartLoadRatio, SysOutputProvided, OnOffAirFlowRatio, LatOutputProvided );
    }

Can you advise how to correct this? Within the VRF code, or in the FanSystemModel code?

**Comment by rraustad** [comment]
I changed this line in CalcVRF and the results look good. It's just that I'm not sure if this is the correct fix or not.

From this:

    HVACFan::fanObjs[ VRFTU( VRFTUNum ).FanIndex ]->simulate( 1.0, ZoneCompTurnFansOn, ZoneCompTurnFansOff,_ );

to this:

    HVACFan::fanObjs[ VRFTU( VRFTUNum ).FanIndex ]->simulate( PartLoadRatio, ZoneCompTurnFansOn, ZoneCompTurnFansOff,_ );

Before and after results look identical. The question is if PLR is the correct argument or if OnOffFanPartLoadFraction should be used instead.

![6336beforeandafter](https://user-images.githubusercontent.com/5778156/30767200-cd18a4d8-9fc8-11e7-924e-0775d4f32e2b.png)

**Comment by Myoldmopar** [comment]
Closed via #6342
