### ISSUE TITLE
AirflowNetwork model error while Wind Pressure Coefficient Type is set to "SurfaceAverageCalculation"

### ISSUE THREAD

**Issue by sriraj-gokarakonda** [NREL/EnergyPlus#6344]
I am encountering the following warning message while modelling AirflowNetwork in EnergyPlus:

** Warning ** GetAirflowNetworkInput: SurfaceAverageCalculation is entered for field = Wind Pressure Coefficient Type, but no roof surface is defined using an AirflowNetwork:MultiZone:Surface object.
** ~~~ ** Reconsider if this is your modeling intent. Simulation continues. 
** Warning ** GetAirflowNetworkInput: SurfaceAverageCalculation is entered for field = Wind Pressure Coefficient Type.
** ~~~ ** The AirflowNetwork model provides wind pressure coefficients for 4 vertical exterior orientations and 1 horizontal roof.
** ~~~ ** There are only 0 exterior surface orientations defined in this input file using AirflowNetwork:MultiZone:Surface objects. 
** ~~~ ** Reconsider if this is your modeling intent. Simulation continues.
--------------
This error appears in spite of clearly defining all the exterior surfaces (Walls and Roof). 

I have checked the EnergyPlus AirflowNetwork example files for reference., All of them have WPC set to "Input" and even when I changed it to "SurfaceAverageCalculation", I see no such warning message in those example files. However, this error appears when I generate my own geometry files, even in a simple single zone which I have attached herewith for reference. 

### Details
Some additional details for this issue (if relevant):
 - Windows 10 (Operating system, version)
 - Version of EnergyPlus:8.7 
 - https://unmethours.com/question/26667/airflownetwork-model-error-in-energyplus/
- Ticket ID: 12305

[oneZoneCheck-idf.txt](https://github.com/NREL/EnergyPlus/files/1327185/oneZoneCheck-idf.txt)
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lgu1234** [comment]
@sriraj-gokarakonda I tested your input file using Ver. 8.8. The warning message shows the correct number of exterior surfaces shown below:

Program Version,EnergyPlus, Version 8.8.0-9148e5cf10, YMD=2017.09.26 10:27,IDD_Version 8.8.0
   ** Warning ** Version: in IDF="8.7" not the same as expected="8.8"
   ** Warning ** GetAirflowNetworkInput: SurfaceAverageCalculation is entered for field = Wind Pressure Coefficient Type, but no roof surface is defined using an AirflowNetwork:MultiZone:Surface object.
   **   ~~~   ** Reconsider if this is your modeling intent. Simulation continues.
   ** Warning ** GetAirflowNetworkInput: SurfaceAverageCalculation is entered for field = Wind Pressure Coefficient Type.
   **   ~~~   ** The AirflowNetwork model provides wind pressure coefficients for 4 vertical exterior orientations and 1 horizontal roof.
   **   ~~~   **  There are only 2 exterior surface orientations defined in this input file using AirflowNetwork:MultiZone:Surface objects.
   **   ~~~   ** Reconsider if this is your modeling intent. Simulation continues.

**Comment by sriraj-gokarakonda** [comment]
Thank you very much for your reply Dr. Gu. I tried to read the subroutine code, but I could not decipher the process.
There were only two surfaces in the idf file attached under AirflowNetwork:MultiZone:Surface and so the error message shows 2 exterior surface orientations. This leaves me with few more questions:
1. Since AirflowNetwork:MultiZone:Surface required at least 2 surfaces to model air flow, is it not enough to define just two surfaces of a zone?
2. Should all the exterior surfaces (or at least one on each orientation) including roof should be defined under AirflowNetwork:MultiZone:Surface?
3. Even though this error message appears, the .eio file gives different CP values when the inputs in the AFN control: Azimuth angle, ratio of the building are changed. In addition, the external node (auto generated) pressures and other related zone output parameters (temperature etc.) changes when those two inputs are changed. So does this mean the simulation runs correctly in spite of this error message? 
4. Are there changes related to this aspect in 8.8?

Thank you very much for the clarification.

**Comment by jasondegraw** [comment]
The answers to your questions are: maybe, probably, no, and no.

Two surfaces is "enough" in the sense that your model has more than the minimum number of connections to be a network, but whether it is sufficient is an entirely different matter. If only two surfaces are subject to wind pressure etc. then it might be enough, but as the message says this is a question of modeling intent. Generated external nodes will only be attached to surfaces that have a corresponding AirflowNetwork:MultiZone:Surface, so if you want the surface to participate, it needs the multizone surface object. The CP tables are generated as a function of the control inputs and the number of surfaces is not taken into account, so as long as you're using SurfaceAverageCalculation you'll see tables in the EIO whether other things are correct or not. Seeing those in the output only means that input handling happened correctly.

It looks to me like things are functioning properly.

**Comment by sriraj-gokarakonda** [comment]
Thank you very much for further clarifications Jason. Now that the calculation protocol is clear to me, I can verify the model validity and results accordingly.

**Comment by jasondegraw** [comment]
Looks like this can be closed.
