### ISSUE TITLE
Generator:FuelCell:ExhaustGasToWaterHeatExchanger on plant equipment list without load center inputs will crash without error

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6347]
Issue overview
--------------
User file has Generator:FuelCell:ExhaustGasToWaterHeatExchanger in a plant equipment list, but does not have any objects for ElectricLoadCenter:Generators or ElectricLoadCenter:Distribution.  Without these, the generator hasn't been initialized when `SimFuelCellPlantHeatRecovery` is called and CWLoopNum is still zero, because InitFuelCellGenerators didn't execute.

### Workaround
Add appropriate ElectricLoadCenter:Generators or ElectricLoadCenter:Distribution objects.  These are necessary anyway if the HX is going to have any heat to offer.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.8.0
 - Helpdesk ticket number 12264 and 12693

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
OK, so what should the fix be here?  I wonder if a simple call to Init will work.  I'd have to dig in to evaluate whether there were any side effects from the initialization, so this will have to be a 'try to do it soon' sort of thing.

**Comment by EnergyArchmage** [comment]
I think the solution will probably be to call createFacilityElectricPowerServiceObject();
around here, unless the top level power service object is already created. 
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/FuelCellElectricGenerator.cc#L3973

probably manageElectricPowerService() will be need to get triggered.

**Comment by mjwitte** [comment]
Ultimately the simulation should error out, because the HX won't do anything if there is no generator to drive it.

**Comment by EnergyArchmage** [comment]
Current code does already does detect this situation and the error file has this warning. 
  ** Warning ** Electric generator input objects require and ElectricLoadCenter:Distribution input object.

I will elevate them to severe and then fatal out to avoid the hard crash

**Comment by Myoldmopar** [comment]
Closed via #6821
