### ISSUE TITLE
Furnaces and unitary equipment may not find correct sequenced load when another airloop also serves the control zone

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6348]
Issue overview
--------------
Furnaces and unitary equipment are controlled using the sequenced zone loads assigned to the furnace terminal unit in the control zone.  If there is another airloop terminal unit also serving the control zone (v8.8.0 or later) then the furnace will be controlled based on the first air terminal in the zone equipment list.  This could be the wrong one and will cause the furnace to meet the wrong load.

### Workaround
Put the furnace terminal unit first in the zone equipment list. The sequence number does not have to be one; the terminal just needs to be the first item in the zone equipment list. If there are two furnaces using the same zone as the control zone, there is no workaround.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.8.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@rraustad @EnergyArchmage This is why the test file I mentioned yesterday with two furnaces serving a single zone appeared to be sharing the load.  @shorowit  FYI.

**Comment by Myoldmopar** [comment]
Closed via #5952
