### ISSUE TITLE
DesignSpecification:AirTerminalSizing not found with AirTerminal:SingleDuct:Uncontrolled

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6349]
Issue overview
--------------
AirTerminal:SingleDuct:Uncontrolled does not find Design Specification Air Terminal Sizing Object Name.

###Workaround
Use a different air terminal type, such as AirTerminal:SingleDuct:VAV:NoReheat with a constant minimum fraction of 1.0.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #5952
