### ISSUE TITLE
IDFVersionUpdater app is missing in 8.8.0 on macOS

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#6352]
Issue overview
--------------
On macOS, in the 8.8.0 installed (dmg) there is no `IDFVersionUpdater.app`.

In 8.7.0, I have `/Applications/EnergyPlus-8-7-0/PreProcess/IDFVersionUpdater/IDFVersionUpdater.app`

In 8.8.0, I **don't** have `/Applications/EnergyPlus-8-8-0/PreProcess/IDFVersionUpdater/IDFVersionUpdater.app`

I know how to run it by command line, so not a massive problem for me, but it's probably confusing for others.

### Details
Some additional details for this issue (if relevant):
 - Platform: macOS Sierra 10.12
 - Version of EnergyPlus: 8.8.0 (7c3bbe4) [here](https://github.com/NREL/EnergyPlus/releases/tag/v8.8.0)

Content of folder `/Applications/EnergyPlus-8-8-0/PreProcess/IDFVersionUpdater`:

```
Report Variables 7-2-0-006 to 8-0-0.csv Transition-V8-6-0-to-V8-7-0
Report Variables 8-0-0-007 to 8-1-0.csv Transition-V8-7-0-to-V8-8-0
Report Variables 8-1-0-009 to 8-2-0.csv V7-2-0-Energy+.idd
Report Variables 8-2-0 to 8-3-0.csv     V8-0-0-Energy+.idd
Report Variables 8-3-0 to 8-4-0.csv     V8-1-0-Energy+.idd
Report Variables 8-4-0 to 8-5-0.csv     V8-2-0-Energy+.idd
Report Variables 8-5-0 to 8-6-0.csv     V8-3-0-Energy+.idd
Report Variables 8-6-0 to 8-7-0.csv     V8-4-0-Energy+.idd
Report Variables 8-7-0 to 8-8-0.csv     V8-5-0-Energy+.idd
Transition-V7-2-0-to-V8-0-0             V8-6-0-Energy+.idd
Transition-V8-0-0-to-V8-1-0             V8-7-0-Energy+.idd
Transition-V8-1-0-to-V8-2-0             V8-8-0-Energy+.idd
Transition-V8-2-0-to-V8-3-0             libgcc_s.1.dylib
Transition-V8-3-0-to-V8-4-0             libgfortran.3.dylib
Transition-V8-4-0-to-V8-5-0             libquadmath.0.dylib
Transition-V8-5-0-to-V8-6-0             

```

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Typo in your description: In **8.8.0** I **don't** have ...

Anyway, I can't figure out why this wouldn't have been included.  We haven't changed the [line of code](https://github.com/NREL/EnergyPlus/blame/7c3bbe48305fc421887df2fd5fb75cfb72e4075b/cmake/Install.cmake#L238) that installs that package in over a year.  I'll have to investigate.  In the meantime, a (slightly annoying) workaround could be to either distribute the app separate and have the user drop it in that folder, or get it from a previous installation.  

Wait.  I vaguely remember we had a problem similar to this a long time ago.  The pre-built .app packages that we bundle in our installation sometimes get confused and get dropped into an older installation folder if they exist.  I have EnergyPlus 8.1 to 8.8 installed on my Mac.  I just checked, and the IDFVersionUpdater.app package is found in the 8.1 to 8.5 installation folders, and they all have the same timestamp - May 16, 2017.  There is something funny about the installation of .app packages contained within .app packages themselves.

I am working on a small side project to make a cross platform, Python-based idf version updater, which would be easier to package up and include.  Hopefully avoiding these problems.  This issue will help make that little project a higher priority.  I will also try to investigate the .app package problem itself.

**Comment by jmarrec** [comment]
This works fine now, cf #7323
