### ISSUE TITLE
Equation typo in documentation for "Chilled-Water-Based Air Cooling Coil"

### ISSUE THREAD

**Issue by jfirrantello** [NREL/EnergyPlus#6357]
Issue overview
--------------
The equation is _16.2.4_ in _Engineering Reference_ v8.8.0, under _16.2.1.4 Design Block Calculations_. The denominator in log mean enthalpy difference appears to be incorrect. It is listed as:

log((hair,in − hw,sat,out) - (hair,out − hw,sat,in))

where I believe it is supposed to be:

log((hair,in − hw,sat,out) / (hair,out − hw,sat,in))

### Details
 - EnergyPlus v8.8 documentation

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
You're right, thanks for the report @jfirrantello 

In 9.0: 

15.2.1.4 Design Block Calculations, equation 15.29

![image](https://user-images.githubusercontent.com/5479063/47096838-5ae4b000-d230-11e8-8ead-64c23ecfc719.png)

https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/WaterCoils.cc#L1513

**Comment by jmarrec** [comment]
After fix in #7015:

![image](https://user-images.githubusercontent.com/5479063/47100461-cc742c80-d237-11e8-8768-914aba56f60b.png)
