### ISSUE TITLE
Zone multiplier doesn't impact Output:Variable value for lights and equipment

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6361]
Issue overview
--------------
In a test, I modified the *5ZoneAirCooled.idf* example file to apply a multiplier of 5 to the **SPACE1-1** `Zone` object, then renamed the model to *5ZoneAirCooled-test.idf*. After running a simulation and comparing results across the generated ESOs for both IDFs, **InteriorLights:Electricity** and **InteriorEquipment:Electricity** output meters change as expected but **Zone Lights Electric Energy** and **ZoneElectric Equipment Electric Energy** output variables remain the same. Refer to table below for annual results for **SPACE1-1**.

| IDF                 | Interior Lights Meter [MBtu] | Interior Equipment Meter [MBtu] | Lights Variable [MBtu] | Equipment Variable [MBtu] |
|---------------------|------------------------------|---------------------------------|------------------------|---------------------------|
| 5ZoneAirCooled      | 16.262                       | 95.479                          | 16.262                 | 95.479                    |
| 5ZoneAirCooled-test | 81.311                       | 477.398                          | **16.262**                 | **95.479**                    |
|                     |                              |                                 |                        |                           |

I tested individual **Lights Electric Energy** output variables as well and got the same results as the cumulative **Zone Lights Electric Energy** output variables.

There are similar closed issues on Github from previous CRs: [#745](https://github.com/NREL/EnergyPlus/issues/745) for zone multiplier for lights and equipment and [#1137](https://github.com/NREL/EnergyPlus/issues/1137) and zonelist multipliers for lights and equipment. These may have addressed applying multipliers to meters and report variables, but not output variables viewed in ESO and CSV files. 

If people want to recreate the test, I have attached the two input files (change the extension from .txt to .idf)
[5ZoneAirCooled-test.txt](https://github.com/NREL/EnergyPlus/files/1380952/5ZoneAirCooled-test.txt)
[5ZoneAirCooled.txt](https://github.com/NREL/EnergyPlus/files/1380953/5ZoneAirCooled.txt)

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus - 8.8

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added 
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@aaron-boranian This is the way it's designed to be.  Zone-level outputs should be unmultiplied - they are per instance of the zone.
