### ISSUE TITLE
Environment variable FullAnnualRun should ignore extra RunPeriod objects

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6366]
Issue overview
--------------
When environment variable FullAnnualRun = yes, the first RunPeriod object is forced to be a full year from Jan 1 to Dec 31, or if there is no RunPeriod object, one is created.  

But if the incoming file has more than one RunPeriod object, the additional run periods are simulated.  These should be ignored so that FullAnnualRun always produces a single year simulation.

This environment variable is described in the Module Developer Guide.  The current description just says this will flip the SimulationControl  "Do Weather File Simulation" to yes.  It should also talk about how it changes the RunPeriod:* objects.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 8.8.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file  - testfile 5ZoneWarmest illustrates the problem when run using the TestSuites scripts with force annual simulations.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@YanfeiNREL The code was addressed in https://github.com/NREL/EnergyPlus/commit/4e96134d9498cbe7c2d3555e3dbaa3c88d368d38 as part of #5893.

Just to clarify, command line argument "-a" sets `DataGlobals::AnnualSimulation` [here](https://github.com/NREL/EnergyPlus/blob/3e91d130a5724d86a9172f4156001e69b10127ad/src/EnergyPlus/CommandLineInterface.cc#L198).

Environment variable "FullAnnualRun" is processed [here](https://github.com/NREL/EnergyPlus/blob/3e91d130a5724d86a9172f4156001e69b10127ad/src/EnergyPlus/EnergyPlusPgm.cc#L329-L331) and sets `DataSystemVariables::FullAnnualRun` true. 

And in the same place if `DataGlobals::AnnualSimulation` is true, then `DataSystemVariables::FullAnnualRun` is set true.
So, both the environment variable and -a do the same thing.  We could still add some detail to the docs, but I don't think anyone would care.

Closing this.

**Comment by YanfeiNREL** [comment]
It was fixed within #5893, with commit id: 4e96134d9498cbe7c2d3555e3dbaa3c88d368d38.

**Comment by YanfeiNREL** [comment]
Thanks @mjwitte . I think it is better to add a line of description to the docs. Then the user would know how to force the idf run whole year simulation.
