### ISSUE TITLE
Annual Cost table from the Economics Results Summary Report does not report the total utility cost

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#6368]
Issue overview
--------------
The Annual Cost table from the Economics Results Summary Report does not report the total utility cost if the model contains more than one UtilityCost:Tariff for a single meter. 

![image](https://user-images.githubusercontent.com/8397034/31870666-6262ff6a-b76c-11e7-9314-279ef335204c.png)

---

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 7)
 - Version of EnergyPlus (8.8.0)
 - Unmethours link or helpdesk ticket number (NA)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by MatthewSteen** [comment]
I assume this is a result of the `Selected` column set to No (I'm not sure how to set this to Yes). 

Also affects the `LEED Summary > EAp2-3. Energy Type Summary` table, which will show the incorrect (lower) Virtual Rate. FYI @JasonGlazer.

**Comment by JasonGlazer** [comment]
@MatthewSteen what you may see as a bug was intended to be a feature. The lowest cost tariff for a particular meter is the one that is automatically "selected" if it qualifies. Thus if you have modeled all the tariffs for a utility, one is selected for you automatically. 

So what is the use case where you want multiple tariffs added up? If it is just dergulated, I assumed that a block would be for the distribution company and another block would be for transmission and another for generation.

**Comment by MatthewSteen** [comment]
I've typically used one for energy and one for demand (along with one for gas), which adds some transparency, but perhaps that's not the best way to do it.

**Comment by JasonGlazer** [comment]
It is probably best to include all the components of a tariff such as energy and demand charges, within a single tariff object, That way if you want to add tax or surcharges, they get applied to the total just like you would expect.
