### ISSUE TITLE
Crash in AvailabilityManager:NightCycle when used with zone equipment and there is no primary air system

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6370]
Issue overview
--------------
This change has a problem when there is no primary air system and only ZoneHVAC equipment with night cycle manager. Need to add " && allocated( DataAirLoop::PriAirSysAvailMgr ) to the logic here to avoid hard crash (or some other test).

Also, this should probably be expanded to reset the ZoneComp....Start/Stop times as well during warmup.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.8.0
 - Comment [here](https://github.com/NREL/EnergyPlus/commit/2a6f67174c4f9e6c7f3789c4c7b56513f2b223e3#commitcomment-25137486)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6410
