### ISSUE TITLE
Invalid error messages with EMS @CurveValue when used with Table:TwoIndependentVariables

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6373]
Issue overview
--------------
User file has EMS program using the `@CurveValue` function with a Table:TwoIndependentVariables object.  
```
    SET rCAP=@CurveValue  HeatingRCAP  AirInTemp WaterOutTemp,  !- A4
    SET rCOP=@CurveValue  HeatingRCOP  AirInTemp WaterOutTemp;  !- A5
```
This results in error messages.
```
   ** Severe  ** TableLookupObject: Table:TwoIndependentVariables"RCAP_ALFEAE8"
   **   ~~~   ** ...Excess number of independent variables (3) passed to subroutine when 2 or less are required.
   ** Severe  ** TableLookupObject: Table:TwoIndependentVariables"RCOP_ALFEAE8"
   **   ~~~   ** ...Excess number of independent variables (3) passed to subroutine when 2 or less are required.

   *************  ** Warning ** Table:TwoIndependentVariables "RCAP_ALFEAE8": Excess number of independent variables warning continues...
   *************  **   ~~~   **   This error occurred 110043 total times;
   *************  **   ~~~   **   during Warmup 4923 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=5.  Min=3.
   *************
   *************  ** Warning ** Table:TwoIndependentVariables "RCOP_ALFEAE8": Excess number of independent variables warning continues...
   *************  **   ~~~   **   This error occurred 110043 total times;
   *************  **   ~~~   **   during Warmup 4923 times;
   *************  **   ~~~   **   during Sizing 0 times.
   *************  **   ~~~   **   Max=5.  Min=3.
```

The EMS Application Guide says that `@CurveValue` should always be called with six arguments, using a dummy variable for the excess arguments.  Doing this resulted in the same error messages.

Example file EMSUserDefinedWindACAuto uses curve function with a Curve:Biquadratic object without similar errors.

1.  This needs to be fixed for EMS.
2.  In general, I don't think the recurring warning for this is necessary.  Just change the severe error to a warning that writes once, and say that it will not be reported again.  And the warning can say that the excess arguments will be ignored.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.8.0
 - Helpdesk ticket number 12166

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6429
