### ISSUE TITLE
Bad initial tank temperature in WaterHeater:Mixed

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6381]
Issue overview
--------------
User file is using a WaterHeater:Mixed as a chilled water storage tank and the initial file fails with a psychrometric error:
```
   ** Severe  ** PsyRhoAirFnPbTdbW: RhoAir (Density of Air) is calculated <= 0 [-0.16864].
   **   ~~~   ** pb =[99041.67], tdb=[-2312.17], w=[2.2414659E-003].
   **   ~~~   **  Routine=CorrectZoneHumRat, During Warmup, Environment=RUN PERIOD 1, at Simulation time=01/01 00:03 - 00:04
   **  Fatal  ** Program terminates due to preceding condition.
```
With some extra output, the source of the problem is the WaterHeater:Mixed, ChilledWaterTank object which reports initial values for Water Heater Tank Temperature of 308570C.  Disconnecting the tank from the basement zone (for heat loss) gets past the fatal psych error and the tank temperature is reasonable by 01/01 06:00.

### Details
Some additional details for this issue (if relevant):
 - Win64
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 -elpdesk ticket number 11402.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6781
