### ISSUE TITLE
VAV airflow problems with Ideal Loads Zone Equipment

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6382]
Issue overview
--------------
#6173 provided warnings when exhaust air fields are not set up correctly for ZoneHVAC:OutdoorAirUnit objects. It does not address exhaust air flow rate of ZoneAirExhaust node for ZoneHVAC:IdealLoadsAirSystem objects. 
 
5952  ### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #6386
