### ISSUE TITLE
SVG text locations wrong in Chrome and Safari

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#6384]
The SVG file that is created by HVAC-Diagram includes spaces between the double quote and the coordinate. These do not seem to be parsed correctly with the Chrome browser or the Safari browser and the text ends up in the upper left corner instead of within the boxes. 

`
  <text x="   802" y="   313">HEATING SUPPLY SIDE BYPASS</text>
`
When the extra spaces are removed this is fixed.

`  
  <text x="802" y="313">HEATING SUPPLY SIDE BYPASS</text>
`

This does not impact how it rendered using Inkscape.

Fix this by removing spaces in x and y coordinates for text to be rendered.

This is based on help desk ticket 12377

See dev support repo for 6384 for example files.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Internet Explorer and Edge both do a good job of rendering the svg diagrams.

**Comment by JasonGlazer** [comment]
@jasondegraw if fixing this would help in the short term, it looks like it would not take much effort. Let me know.

**Comment by JasonGlazer** [comment]
This was previously fixed in #8952 by @jmarrec.
