### ISSUE TITLE
Adaptive convection with lights and baseboard heat or high-temp radiant will crash in v8.8

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6391]
Issue overview
--------------
User file which ran fine in v8.7 now crashes in v8.8 due to accessing an unallocated array [here in DynamicIntConvSurfaceClassification](https://github.com/NREL/EnergyPlus/blob/1f84213a71d31a2094a639730a04cec4f1eae841/src/EnergyPlus/ConvectionCoefficients.cc#L6520-L6521). `DynamicIntConvSurfaceClassification` gets called when there's a surface using AdaptiveConvectionAlgorithm for inside convection, but that's only part of the problem.

So, why did it get to this line too soon in v8.8 but not in v8.7? Because `EquipOnCount` is > 0.  Why is it >0 now and it wasn't before?  Because `Zone( ZoneNum ).IsControlled` is true sooner that it used to be.

So, why is that?  Because `DataZoneEquipment::GetReturnNumForZone` (new function in v8.8) calls `GetZoneEquipmentData1` to make sure that the zone equipment configuration has been gotten so that the zone return nodes are known.

So, where did `GetReturnNumForZone` come from? It was added as part of #6272 to support multiple airloops.  It gets called by lights with return air heat gain (and a few other places). 

So, this file is failing because it has Lights with return air heat gain + adaptive convection.  

But it's a bit more complicated than that, because test file ConvectionAdaptiveSmallOffice has lights plus adaptive convection and it does not fail.

So, why is that?  I think it's because ConvectionAdaptiveSmallOffice only has forced air systems, and the user file which is failing here also has baseboard heat which gets handled differently [here](https://github.com/NREL/EnergyPlus/blob/1f84213a71d31a2094a639730a04cec4f1eae841/src/EnergyPlus/ConvectionCoefficients.cc#L6442-L6449).

*More Diagnosis*
When this fails in v8.8,, it's during SetupZoneSizing.  No zone equipment should be running yet at this point, because the thermostats haven't been set up yet (which is why SNLoadPredictedRate isn't allocated yet).  In [DynamicIntConvSurfaceClassification](https://github.com/NREL/EnergyPlus/blob/1f84213a71d31a2094a639730a04cec4f1eae841/src/EnergyPlus/ConvectionCoefficients.cc#L6442-L6449) EquipCount is being incremented based on this test for baseboard heat and hi-temp radiant:
```
if ( ZoneEquipList( ZoneEquipConfig( ZoneNum ).EquipListIndex ).EquipData( EquipNum ).ON )
```
Problem is, this is initialized to true and I can't find any code that changes it - ever.  So, as it stands, it seems that two fixes are needed.
1.  Protect against unallocated SNLoadPredicted (and maybe more that are used in `DynamicIntConvSurfaceClassification`.
2.  *New issue #6402  posted for this part - Fix the use of `ZoneEquipList( ZoneEquipConfig( ZoneNum ).EquipListIndex ).EquipData( EquipNum ).ON` for adaptive convection.*

### Details
Some additional details for this issue (if relevant):
 - Win64
 - Version of EnergyPlus v8.8.0
 - Direct e-mail from user on Nov 10, 2017

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6401
