### ISSUE TITLE
Unitary system as both zone equipment and airloop equipment in the same file fails in v8.8

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6405]
Issue overview
--------------
Multiple airloop changes in #6248 required some rearranging of HVACUnitarySystem::GetUnitarySystemInputData to separate the input processing for unitary system as zone equipment and air loop equipment.  This solved some issues with internal test files, but some files fail.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 8.9.0 d8a479ad5f
 - e-mail on 2017-11-28 from @rraustad 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Closed via #6406.
