### ISSUE TITLE
Economizer faults do not work because fault objects are processed too late - other fault types may have a similar issue

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6422]
Issue overview
--------------
User complained that FaultModel:TemperatureSensorOffset:OutdoorAir has no impact on results.  As explained below, economizer faults stopped working in v8.7.

Tracing this in the debugger reveals that `NumFaultyEconomizer` is zero [here](https://github.com/NREL/EnergyPlus/blob/017868e84f0eb0de7711a942c72aebc273bafcc8/src/EnergyPlus/MixedAir.cc#L1442-L1449) in `MixedAir::GetOAControllerInputs` because `CheckAndReadFaults` is called too late [here](https://github.com/NREL/EnergyPlus/blob/017868e84f0eb0de7711a942c72aebc273bafcc8/src/EnergyPlus/SimulationManager.cc#L386) in `SimulationManager::ManageSimulation`.

Not sure why, but `CheckAndReadFaults` was moved to be after `SetupSimulation` as part of [this commit](https://github.com/NREL/EnergyPlus/commit/a9ceacfac709cc668d380727577c15d32de11138#diff-5b4ea1e38e96bd2ee33e0d0cf51d12b0L384).

As part of this fix, it seems that it would be more efficient to add the fault model index(es) to the OA controller data structure rather than the current method of adding the controller ID to the faults data structure (which is currently broken) and then searching through all of the economizer faults every time step for every OA controller [here](https://github.com/NREL/EnergyPlus/blob/017868e84f0eb0de7711a942c72aebc273bafcc8/src/EnergyPlus/MixedAir.cc#L3182-L3183) in `MixedAir::InitOAController`.

Just to confirm, ran example file AirEconomizerFaults_RefBldgLargeOfficeNew2004_Chicago.idf with v8.6, v8.7, and v8.8.  Cooling Electricity changed from 1486 GJ in v8.6 to 1696 GJ in v8.7 and v8.8.  (Interesting that the fault saves energy, but that's a secondary concern.)   Just to confirm, made a copy of this with faults deleted.  v8.6 results with faults are different from no faults.  v8.7 and v8.8 are identical with or without the faults.

### Workaround
There is no workaround other than going back to v8.6.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.8.0 (the problem was introduced in v8.7.0), and current develop v8.9 017868e84f
 - Helpdesk ticket 12395

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6778
