### ISSUE TITLE
ZoneHVAC:Baseboard:Convective:Water UA sizing fails if Plant water temp is too low

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6438]
Issue overview
--------------
ZoneHVAC:Baseboard:Convective:Water fails to size UA if plant water temps are set too low. Using 5ZoneCooledBeam example file with Sizing:Plant temp set to 40C.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
See PR #6440.

**Comment by Myoldmopar** [comment]
Closed via #6440
