### ISSUE TITLE
Equipment Summary has incorrect conversions from SI to IP

### ISSUE THREAD

**Issue by pflaumingo** [NREL/EnergyPlus#6442]
Issue overview
--------------

On the Equipment Summary report, when the standard HTML output report is reported in IP units the values on DX Cooling Coils and VAV DX Cooling Standard Rating Details are incorrect. The header suggests tons, but the magnitude is too large for it to be tons - the Cooling Coils section reports as btuh so I'm guessing it should be that.

I'm guessing the DX Cooling Coils and VAV DX Cooling Standard Rating Details are reporting as W because the difference between them and Cooling Coils is just over 3.412 (W to btuh conversion). Being a little over makes sense as DX Cooling Coils and VAV DX Cooling Standard Rating Details I believe include fan heat.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): Energyplus 9.0.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added : `testfiles/1ZoneDataCenterCRAC_wApproachTemp.idf`
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I took the liberty of updating the issue to include the issue checklist, and indicating I can reproduce it with 1ZoneDataCenterCRAC_wApproachTemp.idf.

## SI-units:

![image](https://user-images.githubusercontent.com/5479063/47494234-79aafe00-d851-11e8-8f33-927a11e6ef4a.png)


## IP-units

![image](https://user-images.githubusercontent.com/5479063/47494261-83346600-d851-11e8-957e-c4c23125dfee.png)

**Comment by jmarrec** [comment]
## After fix in #7033, in IP Units:

![image](https://user-images.githubusercontent.com/5479063/47509041-880b1100-d875-11e8-861e-062637c2d8bd.png)

**Comment by mjwitte** [comment]
The Equipment Summary, Central Plant subtable has columns for "IPLV in SI Units [Btuh/Btuh]" and "IPLV in IP Units [Btuh/Btuh]". This probably was written before table units conversions became an option?

Using test file ElectricEIRChiller.idf, here are the SI and IP versions of this table:


  | Type | Nominal Capacity [W] | Nominal Efficiency [W/W] | IPLV in SI Units [W/W] | IPLV in IP Units [Btu/W-h]
-- | -- | -- | -- | -- | --
LITTLE CHILLER | Chiller:ConstantCOP | 25000.00 | 2.50 |   |  
BIG CHILLER | Chiller:Electric:EIR | 25000.00 | 2.75 | 3.05 | 10.42
BIG TOWER | CoolingTower:SingleSpeed | 49380.64 |   |   |  


  | Type | Nominal Capacity [Btu/h] | Nominal Efficiency [Btuh/Btuh] | IPLV in SI Units [Btuh/Btuh] | IPLV in IP Units [Btu/W-h]
-- | -- | -- | -- | -- | --
LITTLE CHILLER | Chiller:ConstantCOP | 85300.00 | 2.50 |   |  
BIG CHILLER | Chiller:Electric:EIR | 85300.00 | 2.75 | 3.05 | 10.42
BIG TOWER | CoolingTower:SingleSpeed | 168486.74 |   |   |  

The values are fine here, but the heading of "IPLV in SI Units [Btuh/Btuh]" makes no sense. Is there a way to force the column heading units to *not* convert? Or for this table, should we drop a column and let the overall conversion take over, assuming there is one? @JasonGlazer @rraustad

**Comment by JasonGlazer** [comment]
I seem to remember that the unit strings needed to be in brackets to be recognized so to avoid converting them just don't use brackets.

**Comment by jmarrec** [comment]
Removing brackets will avoid the conversion, but then again the heater will not be formatted with brackets around the unit and it does look weird/inconsistent.

I added a new unitConv that goes W/W to W/W, with a hint of "SI", so that it doesn't convert really but does format like the rest. 
It you would rather only keep only column that would display SI or IP as appropriate, I can also do that.

I also looked for other places where Roundsdigit its used in combination with PreDefTableEntry as @mjwitte told me in https://github.com/NREL/EnergyPlus/pull/7033#discussion_r239944744, and it looks like all of them are for DX coils, and looking at the comments and the name of the parameters, I'm not sure whether it was really meant to be converted, but in some cases the headings are already being converted while the units aren't (take for eg `pdchVAVDXCoolCoilNetCapSI` or `pdchVAVDXCoolCoilMdotA`)

**Comment by rraustad** [comment]
Seems like we only need one column for IPLV.

**Comment by mjwitte** [comment]
@rraustad Yeah, SI and IP vesrions of IPLV do seem unnecessary, but that's been stable so let's keep that as-is.

Similar conversion errors were present in the "VAV DX Cooling Standard Rating Details" subtable for capacity and airflow (headings were changing to IP, but the values did not). This subtable only gets produced for air-cooled Coil:Cooling:DX:TwoSpeed.
