### ISSUE TITLE
UnitarySystem with Coil:Cooling:DX:VariableSpeed does not cycle the fan with compressor when cycling fan mode is used

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6448]
Issue overview
--------------
Test of the VS DX cooling coil shows the fan operating at max speed when the coil is cycling and fan operating mode is cycling fan. Comparison of Fan Runtime Fraction and Unitary System Part Load Ratio shows the issue. A plot of the Unitary System Part Load Ratio and Cooling Coil Part Load Ratio shows that the coil and unitary system have the same part load ratio.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (DevSupport 6448 w/ Chicago weather)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
The defect file shows the issue where the fan is operating at max speed instead of cycling with the coil/compressor. File set up shown as:

    Schedule:Constant,
      SYS0SZUHC-1FanOpSchedule_0,             !- Name
      AnyValue,                               !- Schedule Type Limits Name
      0.0000;                                 !- Hourly Value

    AirLoopHVAC:UnitarySystem,
      SYS0SZUHC-1FanOpSchedule_0,             !- Supply Air Fan Operating Mode Schedule Name


![6448-fanplrequals1withcyclingfan](https://user-images.githubusercontent.com/5778156/35514183-460ccfa6-04fd-11e8-8227-0cfe0db1024a.jpg)

**Comment by rraustad** [comment]
See PR #6449.

**Comment by Myoldmopar** [comment]
Fixed via #6449
