### ISSUE TITLE
Comparison of single speed DX coil with variable speed DX coil shows differences in performance

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6459]
Issue overview
--------------
Using the same input file with only difference being the coil types (DX:SingleSpeed vs DX:VariableSpeed) the results are markedly different.

Weather file: USA_IA_Des.Moines.Intl.AP.725460_TMY3

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (DevSupport\6459)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
If only there was some intensive coding session on the horizon that could potentially eliminate this type of discrepancy :rofl: :rofl:

**Comment by rraustad** [comment]
Comparison of differences found when comparing SS vs VS DX coils.

![6459-ssvsvscompare-before](https://user-images.githubusercontent.com/5778156/35743287-117c20e4-0835-11e8-9f9b-43f8b7384ba2.jpg)

**Comment by rraustad** [comment]
Testing with changes described in PR #6449 account for some of these differences.

**Comment by rraustad** [comment]
Adding in 6449 corrects most of the differences except for the difference in electric power:

![6459-ssvsvscompare-before_w6449](https://user-images.githubusercontent.com/5778156/35743333-3966044e-0835-11e8-8bf9-3ba20fc8e095.jpg)


With the change made to use adjusted inlet air WB temp in the EIR calculation, plus the changes in #6449, the results now match.

![6459-fixed](https://user-images.githubusercontent.com/5778156/35743347-427970d4-0835-11e8-9c3f-e2c35c8d1771.jpg)

**Comment by rraustad** [comment]
See PR #6460.

**Comment by Myoldmopar** [comment]
Closed via #6460
