### ISSUE TITLE
Fuel Cell solver minimum product gas temperature is too high

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6464]
Issue overview
--------------

User file has set the fuel and air inlet temperatures to use an outdoor air inlet node.  This results in very low inlet enthalpy values during winter design days.  The FC model solves for exit product gas temperatures that provide an energy balance.  With the low inlet enthalpy, the product gas temperatures are also fairly cool.  However the solver minimum temperature bound was originally set at 100C and this is too warm for the solver to bound the root leading to the error message: "CalcFuelCellGeneratorModel: Root Solver problem, flag = -2, check signs, all positive"

Experimenting with lower values of MinProductGasTemp shows that the solver error condition can be removed and that the solver finds a product gas temperature of 19.2C for example.  Clearly the arbitrary, hard-coded, minimum value of 100C for fuel cell power module exhaust was chosen too high for a fuel cell located outdoors.  ( Initial development likely considered the fuel cell device would located indoors rather than outdoors and so would have much higher inlet fuel and air enthalpy. )

Initial testing shows a MinProductGasTemp value of -100 allows the solver to run for the defect file

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Defect file added (https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/6000s/6464)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6542
