### ISSUE TITLE
ThermalStorage:ChilledWater:Stratified is reporting the same value for Source Side Inlet and Outlet Temperatures

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6470]
Issue overview
--------------
User noted that ThermalStorage:ChilledWater:Stratified always reports the same value for both the Source Side Inlet Temperature and the Source Side Outlet Temperature. Comparing against the System Node Temperature outputs, it appears that the Souce Side Inlet Temperature output is incorrect.

### Workaround
Use the System Node Temperature for the corresponding node.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.8 and  v8.9.0-8346d7a61c (Feb 12)
 - Helpdesk ticket number 12507

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6782
