### ISSUE TITLE
Heating Coil energy transfer report variables use different names and should be unified 

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6471]
Issue overview
--------------
Setting up reporting is difficult for heating coils since the heating coils currently use different naming conventions. Previous work to unify report variable names missed the heating coils.

Water heating coils:
Heating Coil Heating Rate
Heating Coil Heating Energy

DX heating coils (includes VRF):
Heating Coil Total Heating Rate
Heating Coil Total Heating Energy

non-DX/water heating coils (i.e., elect, multistage, other fuel, gas, desuperheater):
Heating Coil Air Heating Rate
Heating Coil Air Heating Energy

Not only does this make it difficult for users to remember which report variable to use it also adds complexity when different coil types are used in the same simulation.

In addition, setting up a monthly report table for heating and/or cooling coils would require the user to include all report variable names to make this table generic across different models.

    Output:Table:Monthly,
      Unitary Coil Report Variable Test,    !- Name
      ,                                     !- Digits After Decimal
      Heating Coil Heating Energy,          !- Variable or Meter Name 1
      SumOrAverage,                         !- Aggregation Type for Variable or Meter 1
      Heating Coil Heating Rate,            !- Variable or Meter Name 2
      Maximum,                              !- Aggregation Type for Variable or Meter 2
      Heating Coil Total Heating Energy,    !- Variable or Meter Name 3
      SumOrAverage,                         !- Aggregation Type for Variable or Meter 3
      Heating Coil Total Heating Rate,      !- Variable or Meter Name 4
      Maximum,                              !- Aggregation Type for Variable or Meter 4
      Heating Coil Air Heating Energy,      !- Variable or Meter Name 5
      SumOrAverage,                         !- Aggregation Type for Variable or Meter 5
      Heating Coil Air Heating Rate,        !- Variable or Meter Name 6
      Maximum,                              !- Aggregation Type for Variable or Meter 6
      Cooling Coil Total Cooling Energy,    !- Variable or Meter Name 4
      SumOrAverage,                         !- Aggregation Type for Variable or Meter 4
      Cooling Coil Sensible Cooling Energy, !- Variable or Meter Name 5
      SumOrAverage,                         !- Aggregation Type for Variable or Meter 5
      Cooling Coil Sensible Cooling Rate,   !- Variable or Meter Name 5
      Maximum,                              !- Aggregation Type for Variable or Meter 5
      Cooling Coil Latent Cooling Energy,   !- Variable or Meter Name 6
      SumOrAverage;                         !- Aggregation Type for Variable or Meter 6

To make matters worse, if this data were to be post-processed using scripting, the data for a specific heating coil type would be in different places and the time stamp for a max/min report would float in the table depending on the heating coil type.

For example:

The supplemental water coil used in PTHP 5 shows up in columns 1 and 2 with a time stamp for the peak heating rate in column 3 while the next coil, a single speed DX heating coil used in PTHP 1, shows this data in columns 3 and 4 with the time stamp in column 5. This type of floating table data makes it hard for generic post processing.

![heatingcoilreporting1](https://user-images.githubusercontent.com/5778156/36166005-33f9adf0-10e9-11e8-90d6-d56148bc3ca4.jpg)

![heatingcoilreporting2](https://user-images.githubusercontent.com/5778156/36166017-39b57102-10e9-11e8-9a38-18066332e55f.jpg)

Suggestion is to consolidate all heating coil energy transfer variables to be:
Heating Coil Heating Rate
Heating Coil Heating Energy

Also change documentation and report variable transition rules.

Weather file: any (Chicago used for tables above)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([defect file](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/6000s/6471))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
See PR #6473.

**Comment by mjwitte** [comment]
Closed via #6473
