### ISSUE TITLE
AirTerminal:singleDuct:ConstantVolume:FourPipeBeam not responding correctly to minimum ventilation limit when autosize design primary airflow

### ISSUE THREAD

**Issue by dconantgilles** [NREL/EnergyPlus#6479]
Issue overview
--------------
AirTerminal:singleDuct:ConstantVolume:FourPipeBeam not responding correctly to minimum ventilation limit when user selects autosize design primary airflow and autosize chilled water flow, hot water flow, and total beam length. 

When attempting to demonstrate lack of effectiveness of fourpipe beams in a ventilation driven lab, it was discovered that the primary airflow for the fourpipebeam does not correctly account for minimum ventilation if ventilation is larger than airflow required for heating/cooling the space. 
Examining the example fourpipebeam file, the condition can be replicated, whereas a DesignSpecification:OutdoorAir for zone 'Perimeter_mid_ZN_1 4pipe Beam' is changed to AirChangesperHour and set to be a large value > cooling or heating airflow. The primary airflow remains unchanged whether 10 ACH, 100 ACH, 1000 ACH, etc. is input as a ventilation requirement (hourly peak at 14640 cfm). The  supply airflow rate reported in ComponentSizing report remains unchanged at 6.91 m3/s, while the air flow rate adjustment increases corresponding to required ventilation input. 
![image](https://user-images.githubusercontent.com/36515893/36284029-e303b3da-126b-11e8-986c-f667e49380ea.png)
![image](https://user-images.githubusercontent.com/36515893/36284056-f2159b86-126b-11e8-88e6-c2482a106eb1.png)
![image](https://user-images.githubusercontent.com/36515893/36284072-08dc9856-126c-11e8-9a69-1632af3612a7.png)
![image](https://user-images.githubusercontent.com/36515893/36284092-178a5460-126c-11e8-9f08-dfc364427958.png)

Currently working around the issue by calculating the primary airflow required for ventilation, setting the design primary airflow for the beam accordingly. This requires an iterative process when a mix of ventilation driven and load driven spaces are examined with fourpipebeams in a model. Autosizing primary airflow is not working. A working autosizing condition will hold minimum of ventilation flow requested in the zone. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system: WINDOWS 10 Enterprise)
 - Version of EnergyPlus (v8.8)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by matthew-larson** [comment]
Looks to still be an issue, I can take this on unless anyone objects.
