### ISSUE TITLE
Followup issues for Enhancements to Data Center Model

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6480]
Issue overview
--------------
Followup items from #6154.

- [x] I/O Ref needs a definition for the new output variable "Zone ITE Adjusted Return Air Temperature".
- [x] While in the I/O Ref, it would be nice to break up the description of Air Flow Calculation Method into separate paragraphs for the two methods with the choices in bold.
- [ ] Need to finalize transition rules and add transition code.
- [x] ThermalComfort.cc line 2290 has a stray tab at the end.
- [x] Move check for terminal unit type from [here](https://github.com/NREL/EnergyPlus/blob/c0223f6ed62d7242a3a84cd568a402706033ba6a/src/EnergyPlus/ZoneAirLoopEquipmentManager.cc#L227-L235) to `InitZoneAirLoopEquipment`.
- [x] Maybe more comments on the method - out of time to review further.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by xuanluo113** [comment]
#6514

**Comment by Myoldmopar** [comment]
Closed via #6514
