### ISSUE TITLE
VRF power in heat recovery using ThermostatOffsetPriority is 0 when coils are active

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6485]
Issue overview
--------------
Testing of the VariableRefrigerantFlow_5Zone example file and changing the master thermostat priority control type to ThermostatOffsetPriority shows that power sometimes goes to 0 when the coils are actively cooling or heating. The figure below exemplifies the problem.

    AirConditioner:VariableRefrigerantFlow,
      ThermostatOffsetPriority,            !- Master Thermostat Priority Control Type

![vrfpower0usingtstatoffsetpriority](https://user-images.githubusercontent.com/5778156/36482234-831ac38e-170a-11e8-9aca-bb57bdd0a95d.jpg)
 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6498
