### ISSUE TITLE
IdealLoadsAirSystem halves the outdoor air

### ISSUE THREAD

**Issue by vsotofrances** [NREL/EnergyPlus#6488]
Issue overview
--------------
Ideal Loads Air System when specifying the outdoor air as ach/hour and fixed gives a value that is half of the minimum outdoor air requiered. That is visualized in xESOVIEW ( in design loads and annual simulation) .

HOWEVER in the HTML output in HVAC Sizing Summary the values are RIGHT.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 8.8.0

[UnifamiliarClase_PROF_EPLUS_2_VLC.zip](https://github.com/NREL/EnergyPlus/files/1745258/UnifamiliarClase_PROF_EPLUS_2_VLC.zip)
Look at zones COMUN_1_ and COMUN_2_ in the enclosed file

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ X] Defect file added (list location of defect file here)

**Comment by vsotofrances** [comment]
I almost answer myself.

I have found that the occupancy for the design day is always 0.5 in my file.

I guess therefore that it is applying 0.5 of the minimum ventilation given as ach/hour.

Overall I think it is Confusing:
* in HTML the ventilation is the Volume*ach/hour (declared in DesignSpecification:OutdoorAir)
* in xESOVIEW the design days use the schedule of occupancy in DesignSpecification:OutdoorAir
 in concrete the designdays of the schedule.

 (when it is supposed that is sizing the system and the help says that the schedule is not applied)

**Comment by mjwitte** [comment]
A couple of points to clarify.
In DesignSpecification:OutdoorAir - the "Outdoor Air Schedule" is multiplied  times the total OA from all components (per person, per area, per zone, and ACH).  The eso time series output on a design day is a full simulation of the system on the design day.

Sizing calculations are done separately first. So, the minimum outdoor air is sized to the full amount (without applying the schedule), but then when the design days are simulated, all schedules are active.

**Comment by vsotofrances** [comment]
Thanks a lot for your response.!In the sizing calculation when the output goes to the HTML,...in the table appears with which design day (if there are several for winter or summer), the peak load was obtained.But the OA that appears, as you say, is without applying the schedule.That confused me. (I expected that the sizing in the HTML was using the design days calculation).Final doubts:Therefore the sizing loads in the HTML ,..were they come from?....Is it a radiant time series calculation or something like that?,..not a "full" simulation?.SincerelyVictorEl 22 feb. 2018 12:23 a. m., "Michael J. Witte" <notifications@github.com> escribió:A couple of points to clarify.
In DesignSpecification:OutdoorAir - the "Outdoor Air Schedule" is multiplied  times the total OA from all components (per person, per area, per zone, and ACH).  The eso time series output on a design day is a full simulation of the system on the design day.
Sizing calculations are done separately first. So, the minimum outdoor air is sized to the full amount (without applying the schedule), but then when the design days are simulated, all schedules are active.

**Comment by mjwitte** [comment]
Sizing calculations use the full heat balance to simulate the envelope and other gains (people, lights, infiltration, equipment, etc.) to calculate the zone sensible loads for each sizing period (design day or sizing period from weather file). There is no HVAC simulation during the zone sizing pass, just a calculation of the load required to meet the thermostat setpoint. The zone sizing loads are used to calculate air flow rates and size the system based on the inputs in the Sizing:* objects.

**Comment by vsotofrances** [comment]
Thanks a lot. If i understand correctly...thenI would suggest to remove from the:Report:HVAC sizing summaryThe last two columns, since for the sizing E+ is not using the outdoor air assigned to any HVAC system...or .. output there the value if the ventilation is assigned directly into the zone.(In which case I understand is being used for the sizing).SincerelyVEl 22 feb. 2018 2:53 p. m., "Michael J. Witte" <notifications@github.com> escribió:Sizing calculations use the full heat balance to simulate the envelope and other gains (people, lights, infiltration, equipment, etc.) to calculate the zone sensible loads for each sizing period (design day or sizing period from weather file). There is no HVAC simulation during the zone sizing pass, just a calculation of the load required to meet the thermostat setpoint. The zone sizing loads are used to calculate air flow rates and size the system based on the inputs in the Sizing:* objects.

**Comment by mjwitte** [comment]
There is a footnote at the bottom of the Zone Sensible Heating/Cooling Load subtables:
*The Design Load is the zone sensible load only. It does not include any system effects or ventilation loads.*

While the Minimum Outdoor Air Flow Rate is not part of the zone design load, it *is* used as a minimum for the Calculated Design Air Flow and it is passed on the system sizing calculations to set the system outdoor air flow rate.

**Comment by vsotofrances** [comment]
Thank you very much for your response. Very kind.


"Michael J. Witte" <notifications@github.com> escribió:

> There is a footnote at the bottom of the Zone Sensible  
> Heating/Cooling Load subtables:
> *The Design Load is the zone sensible load only. It does not include  
> any system effects or ventilation loads.*
>

In my opinion, the footnote is not clear enough ( at least as a user  
like me :-) ).

* The Design Load is the zone sensible load only*
(OK...I understand.... only sensible loads are computed, not latent)

* It does not include any system effects or ventilation loads*.
It does not include any system effects...
(system 'effects' starts to be a confusing term , because is too  
general or vague )
..or ventilation loads.
( ... however, if the ventilation was assigned directly into the zone,  
it is taken into account in the sizing - at least its sensible part- ,  
is it correct?.
Here the footnote idea is: ventilation assigned to or provided by the  
system, am I wrong?)

> While the Minimum Outdoor Air Flow Rate is not part of the zone  
> design load, it *is* used as a minimum for the Calculated Design Air  
> Flow and it is passed on the system sizing calculations to set the  
> system outdoor air flow rate.

If the Minimum Outdoor Air Flow Rate "is not part of the zone design  
load" but it is a constraint for the Design Air Flow then the footnote  
should indicate so.
Otherwise (from my point of view) just looking at the table at  
'report: HVAC Sizing Summary', one may think that at the Date/Time of  
peak{TIMESPAN} the minimum outdoor air flow rate was that appearing in  
the table, or at least creates in the user a confusion - or lost  
sensation-  when reading the footnote.

Sincerely
V
