### ISSUE TITLE
Unexpected interaction between Fan:ZoneExhaust and Controller:OutdoorAir

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#6492]
Found in v8.8 (made with OpenStudio v2.4.0)

I'm not entirely certain this is a bug, if not it's just really unexpected and confusing behavior.

I have a VAV with Reheat air loop serving multiple zones, where one zone also has a Fan:ZoneExhaust which is Decoupled from the System Availability Manager. I’ve set the Air Loop to follow an operation schedule, but cycle on at night to meet any heating/cooling loads. Everything is autosized, and the terminals set to control for outside air. I also want to shut down outside air at night, so I’ve set a schedule (same as the loop operation schedule) to the Controller:Outdoor Air ‘Maximum Fraction of Outside Air Schedule Name’.

Here’s the problem: If the Fan:ZoneExhaust attached to one of the zones does NOT have a ‘Flow Fraction Schedule Name’ schedule set, the entire air system will shut off during the outdoor air shutoff hours, even if the attached systems are showing a heating load:

![image](https://user-images.githubusercontent.com/10799524/36514612-7cc6912a-1732-11e8-8e9d-df32f1bf64f5.png)

If I DO set the exhaust fan ‘‘Flow Fraction Schedule Name’ to a schedule, which matches the system operation schedule, I get the correct air system operation: outdoor air off at night, but system cycles to meet heating loads:

![image](https://user-images.githubusercontent.com/10799524/36514628-904a0e7a-1732-11e8-8360-18ef172e9359.png)

Extra: if the exhaust fan operation schedule is different from the system operation/outdoor air schedule, say turns on at 4AM instead of 8, I get an air system which shuts down from 4AM to 8AM (the exhaust fan ON before system ON hours), then works normally the rest of the day:

![image](https://user-images.githubusercontent.com/10799524/36514673-c49c744c-1732-11e8-9aa7-51607688a7da.png)

@mjwitte I think this might have to do with the changes in https://github.com/NREL/EnergyPlus/pull/5794 (since the interaction seems to disappear when I don't define a schedule in Maximum Fraction of Outdoor Air Schedule of the Controller:OutdoorAir), but that's just a guess.

I can provide an example file if necessary.

**Comment by mjwitte** [comment]
@eringold Please upload example(s) here or e-mail me.

**Comment by eringold** [comment]
@mjwitte 
idf with no exhaust fan schedule:
[Issue6492_noschedule.txt](https://github.com/NREL/EnergyPlus/files/1748333/Issue6492_noschedule.txt)

idf with exhaust fan schedule same as loop operation (the alternate exhaust fan schedule described above is also in the file, named 'Fan Sch'):
[Issue6492_schedule.txt](https://github.com/NREL/EnergyPlus/files/1748334/Issue6492_schedule.txt)

Tested with the Denver Intl AP TMY3 file.

**Comment by eringold** [comment]
PS I just edited the description of the third case results above. The air system is OFF for the hours the exhaust fan is scheduled to ON **before** the system/OA schedule is ON.
