### ISSUE TITLE
Annual Reporting Followup

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#6495]
Issue overview
--------------
Something is up with the annual reporting, probably an issue with ReadVars processing the eso header.  This output variable column appears in every output csv file I have run since the annual reporting went in:

![image](https://user-images.githubusercontent.com/849824/36547802-4dfdf766-17b4-11e8-9490-922ea62b48c3.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
OK, scratch that.  I had a "ReadVarsESO" on my path and it didn't understand the new output.  A fresh ReadVarsESO binary runs fine.  I don't *think* this will trip up any users.  Closing.

**Comment by mjwitte** [comment]
Users - probably not. Developers who keep multiple copies of readvars laying around - probably so.
