### ISSUE TITLE
Outdoor air node wet-bulb EMS override only work with with OutdoorAir:Node not OutdoorAir:NodeList and other problems

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6506]
Issue overview
--------------
1. In `OutAirNodeManager::GetOutAirNodeInputs` the [input processing](https://github.com/NREL/EnergyPlus/blob/f84f30a62482f0b7881f33516b972faf077c3cfe/src/EnergyPlus/OutAirNodeManager.cc#L329-L332) for `OutdoorAir:Node` sets `AnyLocalEnvironmentsInModel = true` if there is more than one alpha field.  This is wrong - it will cause a performance hit elsewhere in the code if local environments are not really being used. This should test if `AnyLocalEnvironmentsInModel == true` in deciding whether to set the `IsLocalNode` flag.

2. In `OutAirNodeManager::InitOutDoorAirNodes` the [logic for setting humrat](https://github.com/NREL/EnergyPlus/blob/f84f30a62482f0b7881f33516b972faf077c3cfe/src/EnergyPlus/OutAirNodeManager.cc#L461-L467) needs to be much more general. 
    a. It should not rely on `IsLocalNode` because EMS or schedules could be used to override OA node data even without using the local environments model.
    b. It needs a flag that gets set if any of the overrides for EMS dry bulb, EMS wet bulb, drybulb schedule, or wet bulb schedule are active and then recalculate humrat.
    c. But what if only dry bulb is overridden - then humrat should use the OA condition and wetbulb should be recalculated?
    d. And shouldn't the OA condition be height-based if applicable?
    e. Other cases I haven't thought of here?

3. There is a similar block of code in [CheckAndAddAirNodeNumber](https://github.com/NREL/EnergyPlus/blob/f84f30a62482f0b7881f33516b972faf077c3cfe/src/EnergyPlus/OutAirNodeManager.cc#L603-L626). These should be consolidated into a single function that sets a single node.

### Workaround
Use `OutdoorAir:Node` with the last field non-blank for any OA node that will have an EMS override for wetbulb temperature.
```
OutdoorAir:Node,
    Node 12,                 !- Name
    ,                        !- Height Above Ground {m}
    ,                        !- Drybulb Temperature Schedule Name
    ,                        !- Wetbulb Schedule Name
    ,                        !- Wind Speed Schedule Name
    ,                        !- Wind Direction Schedule Name
    ,                        !- Wind Pressure Coefficient Curve Name
    ,                        !- Symmetric Wind Pressure Coefficient Curve
    Absolute;                !- Wind Angle Type
```

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.9.0-IDDFreeze 1c5ba897d1
 - Direct e-mail from PI on 2081-02-28.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added in EnergyPlusDevSupport\DefectFiles
Look at the outputs for outdoor wet bulb, outdoor humrat, and the node wetbulb and humrat. Starting about 05/03 you can see that the node wet-bulb has been changed by EMS to be different from the outdoor wet bulb, but the node humidity ratio is still equal to outdoor. There are two files, one with OutdoorAir:Node and one withh OutdoorAir:NodeList.

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6841
