### ISSUE TITLE
Coil:Cooling:DX:TwoSpeed  does not process input for Minimum Outdoor Dry-Bulb Temperature for Compressor Operation

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6507]
Issue overview
--------------
User points out that Coil:Cooling:DX:TwoSpeed can not be made to run when outdoor air is less than 0 C.  From code inspection find that the input field Minimum Outdoor Dry-Bulb Temperature for Compressor Operation (N10) is never processed during get input.  Need add code to read input for Numbers(10) around here:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DXCoils.cc#L2542

The documentation and IDD claim a default of -25C but that is not the case because the IDD default never makes it into data structure because of missing code in get input.  So the initialized value of 0 is what the model uses. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #6768.
