### ISSUE TITLE
Yearly output bugs

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#6512]
Issue overview
--------------
There are some potential bugs in the yearly output.
 - Annual variables aren't properly represented in the SQLite ReportDataDictionary. Verified, the ReportingFrequency field is not correct.
 - Year values are wrong on the last day of the year. Not yet verified.

### Details
 - Platform: All
 - Version of EnergyPlus: 8.9

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jasondegraw** [comment]
@macumber I've verified and fixed one of the issues you commented on in #6456, but I'm not able to verify the second one:

>Also the time table goes from year 0 (whole year up to 12/30), to year 1 (lasts one day 12/31), to year 2 (1/1-12/31).

Could you send me the input files (idf, epw) that produced that?

**Comment by jasondegraw** [comment]
So it turns out that the second one is related to repeat run periods, and this will only work properly with `RunPeriod:CustomRange`.

**Comment by Myoldmopar** [comment]
@jasondegraw is this still an issue or can it be closed?

**Comment by jasondegraw** [comment]
We should leave it open for a bit until I'm certain it's addressed.

**Comment by jasondegraw** [comment]
@Myoldmopar I've run my tests and am not finding any issues, so I'll close this for now.
