### ISSUE TITLE
Underflow in CalcFluidHeatExchanger

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6516]
Issue overview
--------------
While debugging other issues with 5ZoneCoolBeam stumbled into floating point underflow [here in CalcFluidHeatExchanger](https://github.com/NREL/EnergyPlus/blob/537dda002df3d9f23cbbf6e34fc90359dcb925c3/src/EnergyPlus/PlantHeatExchangerFluidToFluid.cc#L1498). `NTU` = 7594 which makes `-NTU < EXP_LowerLimit` which is -20. Need more logic here to test if `ExpCheckValue2` is safe before evaluating this if statement.

Need to compile with fp/strict and special line uncommented in main.cc - see [debugging tips](https://github.com/NREL/EnergyPlus/wiki/Debugging-Tips).

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus 8.9.0 0660657580
 - Found while working on #6338.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
@lgu1234 should this issue be closed due to the work completed in #6779?

**Comment by mjwitte** [comment]
Confirmed this issue can be closed (cannot reproduce with v9.4.0 I/O Freeze 908c5cedf5.
