### ISSUE TITLE
Equation numbers missing in Section 3.5.5.4.1 of v8.8.0 Engineering Reference 

### ISSUE THREAD

**Issue by ronnenlevinson** [NREL/EnergyPlus#6517]
Issue overview
--------------
Equation numbers are missing in the following line within Section 3.5.5.4.1 of v8.8.0 Engineering Reference:

h_n is calculated using Equation or Equation .  

![image](https://user-images.githubusercontent.com/14968812/37248355-2ac1db54-2485-11e8-80aa-f0e64032334b.png)

**Comment by RKStrand** [comment]
There may be more of these.  I started doing a search on "as shown in equation" and found some other ones.  Will try to get all of these as part of this work.

**Comment by RKStrand** [comment]
Whoa--much bigger problem than I thought.  Something needs to be done here.

**Comment by mjwitte** [comment]
Closed via #6845
