### ISSUE TITLE
8.9 Release Items

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6521]
Issue overview
--------------
Checklist of things to finish before 8.9 release.

- [x] V8-9-0-Energy+.idd is not included in the IDFVersionUpdater folder in the release package.
- [x] Untransitioned v8.8 file can cause crash with empty error file (at lest when run in debug version). e.g. Files attached to #6508.
- [x] Also make sure package includes Rules8-7-0-to-8-8-0.md and OutputChanges8-7-0-to-8-8-0.md (IDD freeze package had old ones)
- [x] Add input value to select error messages
- [x] character encoding on windows in climatic data summary table output - garbage and causes missing rows
- [x] In the readme under Platforms "Windows 7, 8 & 8"
- [x] In the readme under Platforms, should we delete "(32-bit and RHEL-compatible versions may be available via Helpdesk)"?
- [x] In the readme under Known Problems, the link to issues is getting modified to include the install path (similar to the way the change log linke is correctly modified):
`file:///C:/EnergyPlusV8-9-0-RC0/github.com/NREL/EnergyPlus/issues`
- [x] Turn back on the duplicate item error and fix unit tests that failed.
- [x] the link in readme to "this EnergyPlus website for third party interfaces" which points to https://energyplus.net/interfaces is shown as access denied
- [x] the link in readme to "this EnergyPlus website for third party IDF creation tools." which points to https://energyplus.net/input-files is shown as access denied
- [x] LBuildingAppGRotPar on Win10 . . .
![image](https://user-images.githubusercontent.com/4991075/37773002-66ef5f6a-2daa-11e8-8dda-3e728f0c7389.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
@mjwitte I didn't know about the untransitioned file error.  Do you know whether this is JSON related or something I can fix?  @mbadams5 is still polishing up a branch with the json follow-up changes.

**Comment by mjwitte** [comment]
@Myoldmopar Fairly sure it's JSON. See also #6486

**Comment by Myoldmopar** [comment]
I did confirm that it hard crashes on develop but fails more gracefully with @mbadams5 JSON followup branch.

**Comment by mjwitte** [comment]
@Myoldmopar Added some readme issues at the top of this issue.

**Comment by Myoldmopar** [comment]
Thanks @mjwitte I plan to create a release candidate once the JSON PR merges (very soon), and then I'll collect anything else found during testing into this issue, and put it all in one PR before doing final release of 8.9.0.

**Comment by jasondegraw** [comment]
@mjwitte @Myoldmopar It looks like there is a problem in how CalcSoilSurfTemp and ParametricPreprocessor are being packaged on all platforms. Examining the contents of the installers (7-zip ftw) for the current release candidate and running the x86_64 installer, I'm seeing both of these executables in the PreProcess subdirectory instead of in PreProcess/CalcSoilSurfTemp etc.

On Windows, there is a subdirectory in PreProcess for both, they're just not where they're supposed to be. On Mac and Linux, I don't see the subdirectories. Presumably that's because there's a .BAT for each of these in the Windows installation.

**Comment by jasondegraw** [comment]
@mjwitte @Myoldmopar OK, found the problem. I was *totally* going call "not it" on this one, but unfortunately for me it is *totally* my fault. Unless there are any objections, I'll put the fix over in #6564.

**Comment by mjwitte** [comment]
@jasondegraw Cool - thanks. Yes in #6564

**Comment by mjwitte** [comment]
@Myoldmopar Built a win64 package locally and everything listed above is fixed except the character encoding problem. Does that happen on other platforms or just windows?

**Comment by mbadams5** [comment]
@mjwitte Is the epJSON schema put in the installed package? Also, the encoding problem does/did happen on my Mac as well.

**Comment by mjwitte** [comment]
@mbadams5 No epjSON schema yet. Added to the checklist at the top.

**Comment by mbadams5** [comment]
@Myoldmopar @mjwitte I updated the encoding for the OutputReportTabular.cc and when I run it locally I see all rows and characters properly in the HTML file. Also, I added the epJSON schema to the package scripts, but if you could double check it @Myoldmopar that would be great.

@mjwitte Can you test that the encoding problem on windows is fixed?

**Comment by Myoldmopar** [comment]
closed via #6564
