### ISSUE TITLE
Reuse shading calculations between runs / implement external shading calculations

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6528]
Shading calculations are processing intensive and can take a long time for large models with a lot of shading surfaces.

Once all design decisions for the geometry and envelope properties of a building are made, the effect of shading on the building should be identical between simulations (valid assumption?).

If EnergyPlus could reuse these calculations between runs, a lot of processing time could be saved. Of course, EnergyPlus would have to detect that geometry and envelope have changed to force a recalculation.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/14170068)

**NOTE**: This seems to be related to PR #6388 and issue #6482. Would @Myoldmopar, @hongtz68, or @mjwitte like to chime in?

**Comment by tkdogan** [comment]
We can't wait to see this implemented. I think the implementation could be quite simple. Just write out the shaded fractions to a separate file (and allow that to be overwritten by another shading tool). In the IDF you indicate whether shading calc should be performed or whether it can be loaded from the file. That way the user decides and you don't have to implement the "geometry has changed" check.

**Comment by Myoldmopar** [comment]
https://github.com/NREL/EnergyPlus/pull/6388

**Comment by aaron-boranian** [comment]
As stated in the feedback post “Reuse shading calculations between runs”, shading calculations are time consuming for large models with a lot of shading surfaces. In addition, the polygon clipping based algorithms that are used to determine shaded fractions also tends to be unreliable for complex geometry and results in several severe warnings. This limits applicability in shading device design and urban applications or require somewhat awkward workarounds with shading surfaces and transparency schedules such as suggested in this helpserve post (http://energyplus.helpserve.com/Tickets/Ticket/View/9310).

In computer graphics there are OpenGL based methods (such as: http://www.ibpsa.us/simbuild2012/Papers/SB12_TS09b_3_Jones.pdf) that could drastically speed up shading simulations and make them more robust for complex geometry. Similarly, users might wish to use ray-tracing based methods to include inter-reflections in the diffuse contribution.

Hence, I would like to suggest to implement an option to override the existing shading calculation methods in EnergyPlus where users could provide externally computed shaded fraction data for each model surface. Ideally, users would switch from the exsisting “FullExterior” or “FullExteriorAndInterior” modes to something like a “ExteriorManualInput” and would provide a path to a CSV file or an EnergyPlus schedule name where shaded fractions and diffuse contribution coefficients for each model surface (window and opaque) are given. Similarly, one would want to override the interior radiation distribution. Surprisingly, there seem to be “SurfaceProperty” implementations for this in EnergyPlus currently.

An example may be TRNSYS, where the shading calculation and thermal simulation are two separate steps that communicate via a text file. This allows a manual overwrite of the shading calculation.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/14680032)

**Comment by tkdogan** [comment]
I tested this in the release version 8.9. It looks like the CSV Export just creates an empty file with column headers. I used EPlaunch with one of the example files.

**Comment by mjwitte** [comment]
@tkdogan Looks like we forgot to modify the run scripts to save the shading file alongside the other output, but it sounds like you found eplusshading.csv in the EPTEMP-0000000n folder. I tested this with the 5ZoneAirCooled example and got some data. And apparently, it only writes shading data (sunlit fractions, actually) for weather file RunPeriods. For design days, it writes only headers. I have added some [additional comments](https://github.com/NREL/EnergyPlus/issues/6482#issuecomment-382378155) to issue #6482.

Finally, I am going to close this issue, because the feature is essentially complete.

**Comment by mjwitte** [comment]
Completed. New features have been added to ShadowCalculation to export (v8.8 #6227 ) and import (v8.9 #6388 ) shading fractions.

**Comment by tkdogan** [comment]
Hi Michael - thanks for your elaboration here and on [UnmetHours](https://unmethours.com/question/35984/ep901-crashes-when-external-shading-is-imported-from-file/?answer=36055#post-id-36055). 

I am adding a reply to this thread to put in a requests to improve the implementation of this feature:

(1) Currently the ShadowCalculation override only considers direct sunlight. It would be great if in the same way the diffuse portion (skypatch - surface view-factors) could be overridden. We would like to use this feature to exclude complex shading context geometry from the IDF file.

(2) The shaded-fraction output file should match the input format. Currently a comment line is added to it that the input parser does not understand. Further, shadow calculation frequency and time-step influence the output changing the number of rows that are reported. This seems to be inconsistent with the way the input needs to be provided (8769 hourly values).

**Comment by mjwitte** [comment]
Above comment copied to [6482](https://github.com/NREL/EnergyPlus/issues/6482#issuecomment-449391682).

**Comment by tkdogan** [comment]
hi @aaron-boranian is there a way to override the diffuse contribution similar to the CSV file for the direct solar exposure of surfaces?
