### ISSUE TITLE
Modeling one DOAS to serve multiple AHUs

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6529]
This feature develops the modeling and simulation approach for a dedicated outdoor air system (DOAS) connected to multiple air handling units (AHUs). Many buildings have a separate DOAS system that feeds outdoor air directly to individual AHUs on each building floor. Currently EnergyPlus can only model a DOAS delivering outdoor air directly to zones or to the inlet or outlet of some zone equipment acting as terminal units. This feature will allow a single DOAS to supply air to the outdoor air inlet of multiple air systems.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/9674514)

**NOTE**:  This could be related to PR #6248 and #5921 that allow multiple air systems to serve one zone.

**Comment by FredWorter** [comment]
While this may be "related to" those other modifications, it is really about allowing DOAS AHUs to provide preconditioned air to OA node of multiple large AHUs, which themselves serve multiple zones. At times, said DOAS may also provide air directly to some zones.

**Comment by eringold** [comment]
More related to PR https://github.com/NREL/EnergyPlus/pull/6025.

Really curious why that seems to have died...

**Comment by MatthewSteen** [comment]
@eringold I recall hearing that the people working on it changed jobs/retired.

**Comment by jasondegraw** [comment]
Being worked on in #7230

**Comment by shorowit** [comment]
Completed in https://github.com/NREL/EnergyPlus/pull/7230.
