### ISSUE TITLE
Report Whole Window U-factor, SHGC, and VT

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6530]
Problem: EnergyPlus only reports U-factor, SHGC, and VT for center-of-glass. It does not report those values for the whole window.

Rationale: It is very important for modelers to confirm that the window systems (glass layers, gas layers, frames, dividers, shades, etc.) have been input correctly and reporting standard rating values from EnergyPlus’s models is very helpful to close the loop.

Solution: Add content to the fenestration summary report for whole window U/SHGC/VT. Calculate the whole-window metrics using procedures defined by NFRC and consistent with LBNL Window program. Correct any problems with how frame and edge-of-glass regions are input and modeled to make EnergyPlus’s whole-window representation consistent with NFRC and LBNL Window program.

Context: Frame and edge-of-glass effects can be significant making whole-window performance values very different from center-of-glass values. NFRC uses whole-window U/SHGC/VT for performance ratings. EnergyPlus echoes out center-of-glass U/SHGC/VT but that information is not complete when modeling frames, dividers, etc.

Suggestion from legacy enhancement list (Windows_2009_06).

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/13660317)

**NOTE**: This is currently in progress under a [working branch](https://github.com/NREL/EnergyPlus/tree/%232520943-WindowsCalc-Engine_Integration).
*MJW 2019-07-25- It appears that this is not in progress.*

**Comment by jeannieboef** [comment]
Since the LBNL WINDOW calculation engine is being intergrated, will it then solve this feature?

**Comment by mjwitte** [comment]
The WINDOW engine may be able to calculate this, but at this point, EnergyPlus has not been modified to access the calculation and report the values. Is that correct @vidanovic ?

**Comment by vidanovic** [comment]
@mjwitte that is correct. As part of EnergyPlus, WINDOW engine have "no interest" in calculating U-value nor SHGC since that is not used as part of heat transfer and solar radiation distribution calculations. U-value and SHGC are standardized values at certain boundary conditions that are almost never exactly met when using weather file(s). However, when applying certain boundary conditions, WINDOW and EnergyPlus should give identical results.

**Comment by jeannieboef** [comment]
EnergyPlus used to report other ratings such as SEER for dx-units, etc. Should the same not be doable for windows? It makes reporting the input verification far easier and clearer, especially for less experienced users who have no experience creating glazing systems with WINDOW.
