### ISSUE TITLE
Standardize simulation outputs in XML or JSON format

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6531]
EnergyPlus simulation results are currently stored in several different files with various formats. Putting the simulation results, including the summary reports, into a standardized data format such as XML or JSON can highly benefit the interoperability of EnergyPlus.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/9674592)

**Comment by jasondegraw** [comment]
In progress, see #6192

**Comment by shorowit** [comment]
#6192 has been merged and is part of E+ v9.1.
