### ISSUE TITLE
Improved Error Message Handling and Documentation

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6535]
Error messages (warning, severe, and fatal) are a source of confusion for many users as well as creating problems for interface developers. To improve the error messages, several improvements can be made:

- An error number could be shown with each unique error message.

- A new section in the documentation could show the next steps to take to resolve each type of error message. It would be arranged by error number.

- The format of the error messages could be made more uniform.

- The text of some error messages could be improved to be clearer

- Error messages that must be resolved will be shown more prominently compared to those that are acceptable.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/14799240)

Link to [design document](https://docs.google.com/document/d/1D8nBHzGnoIfJK5OGBl2AUhf4NtopOI8euvPIS8SwLaU/edit) (out of date)

**NOTE**: This is in progress under the branch [error-enhancement-prep](https://github.com/NREL/EnergyPlus/tree/error-enhancement-prep) (out of date)

**Comment by TobiasMaile** [comment]
We as a GUI developer, we have a strong interest in this feature. With a unique identifier for each error message, our code related to error processing would dramatically simplify and become much more reliable between versions. 

We briefly looked at the code in the branch and discovered some hard-coded constants that contain the error strings. This is not really useful. The mapping between unique error message and message string should be stored in a separate file (XML, JSON, ...) that can be parsed by EnergyPlus and by third-party developers. 

I am happy to discuss this in more detail.

**Comment by jasondegraw** [comment]
The current NFP is located [here](https://github.com/NREL/EnergyPlus/blob/05ad5acfe660081a61127af58762300be89671c3/design/FY2018/NFP-error-enhancement.md).

I'll edit the top level comment to indicate those links are out of date.

**Comment by shorowit** [comment]
There is an NFP for this but no further progress as far as I can tell. Removing the InProgress label.
