### ISSUE TITLE
Address limitations and overshooting problem

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6546]
Issue overview
--------------
This is an issue to address limitations and overshooting problem for OnOffThermostat. Here are detailed limitations based on Mike's comments:

- [ ] I've tested SingleFamilyHouse_TwoSpeed_CutoutTemperatureI with this branch and current develop. The temperature pattern with this branch is much better. The system see that this control strategy does not work well for a heat pump, because the supplemental heat is coming on (even in April) to push the zone to the higher heating setpoint. For this to work correctly with a heat pump, the heat pump will need to know more information so that the supp heat does not kick in for this. Also, there are quite a few times where the zone air temperature overshoots the upper heating setpoint one timestep after the heating shuts off - doesn't seem possible. For example
image

- [x] I also tested with a modified version of HVACTemplate-5ZoneFurnace with fan operating mode set to cycling fan. The daytime heating setpoint is 23C and the cooling setpoint is 24C.
 For some reason, with this system type the cooling setpoint is tracking the heating setpoint which is causing problems (requesting cooling on the winter day, and it fails with a fatal thermostat error). I don't see the same setpoint behavior in SingleFamilyHouse_TwoSpeed_CutoutTemperature.
Then I changed the cooling setpoint to 27C and the setpoints were indepednent. So, apparently if the cooling and heating setpoint are too close to each other they stomp on each other?
 If it's possiible to detect and protect against it or throw a meaningful error message, that would be good here. New input files attached.
*This was addressed prior to v8.9.0 release.  Probably in #6541.*

- [x] User correct zone temperature variable to limit overshoot problems.
*Addressed in #6754*

- [ ] Also, excess hours of thermostat setpoint not met are being counted with this method. That's another item that will need improvement.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lgu1234** [comment]
@mjwitte 
Overshooting issue:

When ThirdOrderBackwardDifference is used as a choice of ZoneAirHeatBalanceAlgorithm, ZTM1 is used to represent the zone temperature at previous time step. The variable is used in zone energy balance equation to predict system load and solve zone temperature at the current time step. Unfortunately, ZTM1 does not represent the value in the OnOff thermostat. The correct value should be used as zone temperature at the previous time step in OnOff thermostat. I am going to fix this issue first to avoid overshooting.

**Comment by mjwitte** [comment]
Of the three issues noted at the top, the middle one appears to have been addressed prior to the v8.9 release.
#6754 only addresses overshoot.
The other two are not addressed by #6754, so this stays open.

**Comment by Myoldmopar** [comment]
Closed via #6900
