### ISSUE TITLE
Generate CSV hourly output directly from EnergyPlus (deprecate ReadVarsESO)

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6552]
Problem: Post processing hourly output with ReadVars is an additional step and generates duplicate data.

Solution: Allow EnergyPlus to create CSV files directly instead of converting the ESO file through ReadVars.

This would deprecate the need for ReadVars altogether and create one fewer auxiliary program to package and install.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/9117616) feedback from @nealkruis

**Comment by xixihaha1995** [comment]
@mjwitte I want to change the following **monthly** output to **hourly** output:
What's the correct direction should I look into? Thank you.
```
  Output:Table:Monthly,
    NameHolderMonthlySummary ClimateZone 0B,  !- Name
    3,                       !- Digits After Decimal
    Site Outdoor Air Drybulb,!- Variable or Meter 1 Name
    SumOrAverage,            !- Aggregation Type for Variable or Meter 1
    Heating:Gas,             !- Variable or Meter 2 Name
    SumOrAverage;            !- Aggregation Type for Variable or Meter 2
```
![image](https://user-images.githubusercontent.com/43649779/138616175-6b9c8e6a-67f1-48bc-9b43-21d004929547.png)

**Comment by mjwitte** [comment]
@xixihaha1995 Please open a [helpdesk](https://energyplushelp.freshdesk.com/) ticket or an [unmethours](unmethours.com) queston.
