### ISSUE TITLE
Multiple CO2 controllers are not set correctly

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6565]
Issue overview
--------------
A user have found that regardless of defining 7 controllers in the 7 zones, the model is only considering the first controller and using it for all the other zones in the model.

[EnergyPlus !12562]: Assigned Ticket Activity - Multiple Contaminant Controllers

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6745
