### ISSUE TITLE
Create scripting language bindings

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6568]
Problem: Writing and compiling C++ is daunting and prevents many users from contributing to the source code.

Solution: Create scripting language bindings (e.g., Python or Ruby), that allow users to prototype new features that simulate at runtime.

Dependency: Expanded API (http://energyplus.uservoice.com/forums/258860-energyplus/suggestions/9676680-expand-the-energyplus-api-library-to-expose-intern)

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/9676944) feedback from @nealkruis

**Comment by blockspacer** [comment]
It may be good idea to use cling to solve that issue
see https://github.com/godotengine/godot/issues/31630

**Comment by mitchute** [comment]
The issue is addressed by #7776.
