### ISSUE TITLE
Parametric Preprocessor leaves funny file and err file repeats last error message

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#6573]
Running the parametric preprocessor on Linux in an empty folder without giving any arguments leaves a bad error filename: 
`C:\Documents and Settings\Jason\My Documents\projects\EnergyPlusDev\ParametricInputs\dev 2009-08a\Debug\Cond-1-Parametric-LogicTestingIF.err`

**Comment by JasonGlazer** [comment]
@Myoldmopar looks like some old debugging code that should not be active.

**Comment by JasonGlazer** [comment]
This line:

https://github.com/NREL/EnergyPlus/blob/40101eaafd1525ee63406264ae9535f25acf4805/src/ParametricPreprocessor/ParametricPreprocessor.f90#L354

is definitely just some old debugging code.

**Comment by mjwitte** [comment]
Also, the context string was not initialized, so the console output dumped a bunch of garbage when run from a command window if there was an error.
And the index for writing the err file was incorrect, so the last error message was repeated in the err output. See attached:
[ParametricPreProcessor.zip](https://github.com/NREL/EnergyPlus/files/5269034/ParametricPreProcessor.zip)
