### ISSUE TITLE
Problems with Airloop operation with Zone Exhaust Fan and Cooled Beam

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6574]
Issue overview
--------------
The AirloopHVAC will not operate when a ZoneHVAC:ExhaustFan is added.  There seems to be serious problems with zone return air node flow calculations when a zone exhaust fan is added to a zone served by AirTerminal:SingleDuct:ConstantVolume:CooledBeam.  The central fan does not operate and the air system provides no ventilation air to any of zones.  

Defect file adds one zone exhaust fan to example file 5ZoneCooledBeam.idf.  Problem is that after adding the zone exhaust the airloop central fan does not operate. 

After much debugging, the problem appears to be with MassFlowRateZSup term here https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneEquipmentManager.cc#L4487

Unclear why zero return air flow is propagating past the OA system and shutting down the air handler.   

### Workaround ###
Make the zone exhaust fan "balanced".

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (\EnergyPlusDevSupport\DefectFiles\6000s\6574\6574_5ZoneCoolBeam.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@lgu1234 There is an initial fix in #6575 but I haven't gone back to confirm and add a unit test. Are you planning to complete this?

**Comment by eringold** [comment]
This might be related to https://github.com/NREL/EnergyPlus/issues/6492

Assuming "ZoneHVAC:ExhaustFan" is Fan:ZoneExhaust.

**Comment by lgu1234** [comment]
@mjwitte I took a look at #6574 and have not started it formally. Since you have an initial fix, it is better for you to complete it. Thanks.
