### ISSUE TITLE
Flexible Control Sequence for zone with multiple Window Shading Devices

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6582]
Problem: Zones often have more than one window. Currently EnergyPlus applies window shades in the order of their appearance in the input file. The first shade is applied, and if it does not meet the shading control requirement the second shade is applied, and so on. Users do not have a way to specify how multiple shades can be applied in a certain order or in certain sets.

Rationale: Window shading control is important for daylighting controls and visual comfort and impacts solar gains. Flexible shading controls are required to model how shading devices are typically actuated in real buildings.

Solution: Modify window shading control input and routines so that multiple shades/blinds can be applied in a certain order.
Context: This may be doable with EMS but native feature for this would be helpful. Users may not be aware of current behavior.

Context: This may be doable with EMS but a native feature for this would be helpful. Users may not be aware of current behavior.

Suggestion from legacy enhancement list (Windows_2009_01)

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/13658856) feedback from @EnergyArchmage

**Comment by mjwitte** [comment]
Completed for v9.0 via #6421
