### ISSUE TITLE
Fan:SystemModel crashes using Continuous speed control method.

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6598]
Issue overview
--------------
A result of HelpDesk ticket 12594. Changed Fan:SystemModel speed control to Continuous just to test if constant fan operating mode would work correctly for UnitarySystem. Crash where m_flowFractionAtSpeed is not yet allocated.

        if (m_numSpeeds > 1) { // set up values at speeds
            m_massFlowAtSpeed.resize(m_numSpeeds, 0.0);
            m_totEfficAtSpeed.resize(m_numSpeeds, 0.0);
            for (auto loop = 0; loop < m_numSpeeds; ++loop) {
                m_massFlowAtSpeed[loop] = m_maxAirMassFlowRate * m_flowFractionAtSpeed[loop];

Chicago weather but shouldn't matter.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (EnergyPlusDevSupport defect files folder)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
Any one working on this bug issue?

**Comment by rraustad** [comment]
I already have a fix for this one.

**Comment by rraustad** [comment]
See PR #6805.

**Comment by Myoldmopar** [comment]
Closed via #6805
