### ISSUE TITLE
HVACAirloop:UnitarySystem does not honor continuous fan mode using multispeed heating coil

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6599]
Issue overview
--------------
HelpDesk ticket 12594 shows incorrect fan air flow using constant fan operating mode. Fan should operate continuously at low speed during no load condition. Constant fan mode is scheduled between 6 AM and 10 PM, otherwise cycling fan.

![12594_multispeedheatcoilcontfan](https://user-images.githubusercontent.com/5778156/38001195-83e497b8-31f9-11e8-9ef7-9edf9362b7d3.jpg)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Preliminary changes show what appears to be correct fan operation. Full flow when load exists, 25% of flow when no load exists.

![12594_multispeedheatcoilcontfan_fixed](https://user-images.githubusercontent.com/5778156/38003404-674823fc-3205-11e8-8956-d508521e5f6a.jpg)

**Comment by rraustad** [comment]
See PR #6600.

**Comment by mjwitte** [comment]
Closed via #6600
