### ISSUE TITLE
Add Supplemental Heating Coil option to VRF Terminal Unit

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6605]
Problem: There is currently no way to include a supplemental heater in VRF zone terminal units.

Rationale: VRF systems may not have sufficient heating power during extremely cold conditions and require backup electric resistance heaters in the terminal units. Heat pump systems may experience simultaneous heating and cooling loads and when in cooling mode the zones that lost the vote for heating could still heat with supplementary heat. Other air system heat pump equipment in EnergyPlus have supplemental heaters.

Solution: Include supplemental heating coil option in ZoneHVAC:TerminalUnit:VariableRefrigerantFlow object

Suggestion from legacy enhancement list (HVAC_Zone_2014_01)

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/13660020) feedback from @EnergyArchmage

**Comment by jasondegraw** [comment]
Resolved by #7252
