### ISSUE TITLE
Add Interzone Air Wall object

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6621]
Two separate thermal zones often have no actual wall separating them, for example open plan offices, or zones open to atria. It is not clear how to best, or if it is possible to, represent these so-called air walls in EnergyPlus. There is a need for a robust and straightforward way to model air walls without messy workarounds. Current workarounds all have different problems that are difficult for users to understand and adjust for. A new air wall feature that passes solar, daylight, interzone air, and connects interior thermal radiation would be a useful addition.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/20303137) feedback from @EnergyArchmage 

**NOTE**: This seems to be related to issue #3446. Would @mjwitte like to chime in?

**Comment by shorowit** [comment]
Addressed by https://github.com/NREL/EnergyPlus/pull/7455 and included as of EnergyPlus 9.2.
