### ISSUE TITLE
Update EP-Launch and make it cross-platform

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6632]
EP-Launch Lite that is distributed on non-Windows installs of EnergyPlus is not functionally equivalent to EP-Launch on Windows. It does not support all the same utilities or options. EP-Launch has not had a significant GUI update in many years. EP-Launch would be rewritten to have a more modern GUI while supporting all the same utilities and options and would be made to be cross platform compatible.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/20246977) feedback from @JasonGlazer 

**NOTE**: This is related to issue #6551 and issue #6566.

**Comment by JasonGlazer** [comment]
See: https://github.com/NREL/EP-Launch
