### ISSUE TITLE
Moisture sorption curve slope equation is incorrrect

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6634]
Issue overview
--------------
Please change this line to a description of the defect, with useful supporting information including how the issue was found, conditions that trigger this defect, workarounds for users of the current version, and a clear description of how to validate that a fix is complete for this defect.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus V8.8 

While working on another project I came across the following issues in the EMPD model:
- [du_dRH](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/MoistureBalanceEMPDManager.cc#L560-L561) calculation equation has duplicate "material.MoistCCoeff" term.
- Suspicious how the vapor density at the surface and deep layers are calculated during init [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/MoistureBalanceEMPDManager.cc#L394-L396). shouldn't we use surface temperature instead zone air temperature?  

Documentation issues:
- Equations 3.50 and 3.51 in engineering reference (V8.8) should have temperature (T) in the denominator
- Equation 3.48 the moisture penetration depth should have subscript 1
- In Engineering Reference section 3.4.3 Nomenclature universal gas constant for water is defined as 452.61, instead of 461.52. Correctly defined earlier section.

**Comment by shorowit** [comment]
FYI @jdwoods21 @nmerket

**Comment by Myoldmopar** [comment]
Closed via #6759
