### ISSUE TITLE
Central Air Humidity Control Based on Return Air

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6637]
Problem: Humidity controls for central air systems are cumbersome and don’t always reflect actual system configurations.
Rationale: Multizone air handlers might locate a single humidistat in the return air duct rather than separate humidistats in every individual zone. EnergyPlus could implement similar controls and avoid a lot of separate zone humidistat input and the need to calculate predicted-moisture-load-to-setpoints in the zone balance and save computation.
Solution: Create some kind of setpoint manager (or maybe a controller) that senses return air moist air conditions and adjusts supply air dewpoint temperature to meet high and low targets.

Context: The concept is similar to SetpointManager:ReturnTemperature:ChilledWater but instead of controlling return water temperature, control return air humidity ratio. 
Pros and Cons of Solution:
+ Simplifies input for central air humidity control by avoiding the need for humidistats in every zone.
+ mimics configurations found in real buildings. 
- May duplicate capabilities that are essentially already available with SetpointManager:MultiZone:Humidity:Minimum and SetpointManager:MultiZone:Humidity:Maximum
Suggestion from legacy enhancement list (Control_2009_01 )

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/13658613) feedback from @EnergyArchmage

**Comment by mjwitte** [comment]
@EnergyArchmage I believe this is addressed with #9261 If not, please reopen this issue and explain what's missing.
