### ISSUE TITLE
Add "lean" installer package option

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6641]
Problem: There are an overwhelming number of accessory files, tools, and GUIs that come with the current EnergyPlus installer.

Solution: It would be cleaner to package the command line engine separately for a lighter installation for those who just want access to the engine.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/9117883) feedback from @nealkruis

**Comment by jmarrec** [comment]
This is fixed now since the QtIFW installers allow you to deselect optional components like weather files, datasets, etc
