### ISSUE TITLE
Better documentation for Counter flow vs. Parallel flow coil parameter

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6650]
For the clarification on counter flow vs. parallel flow coil parameter, it is not clear what’s the difference between the two settings.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/14843391)

**Comment by dareumnam** [comment]
I'll be taking a look at fixing this defect, could you please provide any more information about this issue?

**Comment by aaron-boranian** [comment]
@dareumnam sorry, but the original poster of the suggestion on UserVoice didn't leave any further comments. My best guess is that they are referring to the [Heat Exchanger Configuration](https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-heating-and-cooling-coils.html#field-heat-exchanger-configuration-000) input field of the Coil:Cooling:Water object. The I-O ref section for this input field states:

 > The coil is operable in two configurations: CounterFlow or CrossFlow. Chilled water coils are generally built as counter-flow. The default is CounterFlow.

This doesn't really expand on what impact these flow settings have on the model. However, the impact is explained in the [Effectiveness Equations](https://bigladdersoftware.com/epx/docs/9-1/engineering-reference/coils.html#effectiveness-equations) section of the Engineering Ref section showing NTU-Effectiveness relationships for each flow setting.

**Comment by Myoldmopar** [comment]
@dareumnam At a minimum then, we'd need to point the user from the IO ref section at that field to the engineering reference section.  Not an actual inter-document link, but just a note telling them either a little more information about the field, or telling them to see the "XYZ" section in the engineering reference.

**Comment by dareumnam** [comment]
I also found that the I-O ref has the same description for the "CounterFlow" and "ParallelFlow" in HeatExchanger:FluidToFluid Section. (Field: Heat Exchange Model Type)

"CounterFlow: Specifies a counter-flow shell and tube heat exchanger. The effectiveness will be calculated using a counter-flow shell and tube heat exchanger correlation."
"ParallelFlow:  Specifies a  parallel-flow shell and tube heat exchanger. The effectiveness will be calculated using a parallel-flow shell and tube heat exchanger correlation."

Including all the comments above, I will be taking a look and will clarify the difference between the two settings.

**Comment by Myoldmopar** [comment]
Fixed via #7349
