### ISSUE TITLE
Allow "Type of Load to Size On" setting at the Terminal Unit

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6661]
Currently in EnergyPlus you set the type of load to size on at the system itself rather than the terminal units, which adds rigidity to the sizing runs. Systems nowadays often utilize hybrid solutions where the air system is sized for ventilation at some zones and full load at other zones. My suggestion would be to set the sizing requirement at the terminal unit rather than the air system for greater flexibility. This would allow for sizing calculations of such hybrid systems to be performed without the need of post processing, which can be lengthy for large projects.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/11101635)

**Comment by mjwitte** [comment]
This was added in v8.8, see `DesignSpecification:AirTerminal:Sizing`.
