### ISSUE TITLE
Spend several development cycles squashing long-standing bugs and paying off any technical debt

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6670]
Lots of great new features and capabilities have been made available with E+ over the years, but there are still many lingering bugs that seem to pop up unexpectedly. When these bugs pop up, there is a detrimental effect on project timelines and our ability to rely on E+ to do the heavy engineering lifting.

A good example is plant pumping systems; seems like the same types of issues are being reported by a number of users over the last year.
https://github.com/NREL/EnergyPlus/issues/5892

Also there appear to be some issues with sizing that get reported a lot; HW coils sizing to zero in the entire building, etc.

I trust that the developers know where the big bugs and deficiencies are and am suggesting that the amount of time needed to pay off tech debt be allocated in development timelines.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/19400185)

**Comment by mitchute** [comment]
Good sentiment, but yeah... I think everyone is doing their best to triage the most important issues. #5892 is still a valid issue, so unless there are other *specific* issues that are not already noted in the issues list, I'm going to close this.
