### ISSUE TITLE
EnergyPlus for Dummies

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6672]
Update the GettingStarted documentation to help new EnergyPlus users really understand what EnergyPlus is all about and how to start becoming productive energy modelers using EnergyPlus. Assume that the readers of the GettingStarted documentation do not know anything about modeling. It would assume nothing about the user and walk them through the process introducing a bunch of different concepts at simple level. It would build off the approach used in GettingStarted but would be enhanced with addressing the many issues that we know that new users have when starting with EnergyPlus. It would also include a links on how to get help and common interfaces as well as description of common workflows for new users.

It would also be good to have some part of the GettingStarted guide that is written specifically on how to transition users from eQUEST and TRACE describing concepts that are different and even having some mapping of input screens in those programs to the appropriate objects in EnergyPlus.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/14800185) feedback from @JasonGlazer 

**NOTE**: Would @jasondegraw like to chime in about the work he is currently doing for this?

**Comment by JasonGlazer** [comment]
I think most of this was addressed in EnergyPlus Essentials
