### ISSUE TITLE
Integrate Window Calculation Engine

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6673]
EnergyPlus currently has three different calculation modules for the detailed calculation of thermal, solar and daylighting properties for fenestration systems:
1. Original window module implementation (referred as “Winkelmann” here)
2. Tarcog/BSDF
3. ASHWAT/EquivalentLayer

Calculation modules a) Winkelmann and b) Tarcog/BSDF use the same calculation standard (ISO 15099) and for specular systems, they produce very similar results (for surface temperatures and heat flows). The Winkelmann calculation modules include optical calculations for both specular and lambertian, grey body diffuse reflectance of venetian blind slats and woven shade threads. The Tarcog/BSDF calculation module, on the other hand, lacks optical calculations in EnergyPlus and relies on calculations in the WINDOW program and export of BSDF results to EnergyPlus for those calculations. The calculation of lambertian, grey body diffuse venetian blind slats and woven shades produce somewhat different results in WINDOW, which is due to the more accurate implementation of the diffuse model. The use of seemingly identical, but actually different calculation engines in EnergyPlus for the purpose of achieving the same results is confusing and does not provide for a sustainable long-term solution. While the WINDOW optical engines are constantly enhanced and debugged, the Winkelmann calculation module in EnergyPlus has remained in the code without any maintenance for years now.

Window calculation engine (WCE), a shared library with the WINDOW program, will consolidate all three models into one and this will be done through different stages. This will allow a single well-maintained code base to be used by both EnergyPlus and WINDOW.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/14491113) feedback from @mjwitte 

**NOTE**: Work for this is underway on PR #6388 and issue #6247. Would @vidanovic like to chime in?

**Comment by vidanovic** [comment]
This is still in branch and it should be merged in after 8.9 gets released (since there are some minor IDD changes).

**Comment by mjwitte** [comment]
Completed for v9.0 via #6247
