### ISSUE TITLE
Mexico should be in North America category on weather download website

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6681]
Good evening,

In the weather data Region 4, you have Mexico in Central America which is incorrect because is part of North America. I just wanted to point this mistake.

Best regards.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/31964197) 

**NOTE**: Would @Myoldmopar or @mjwitte like to chime in if there is a different repo group that this kind of issue should be posted to? I didn't find any "weather" repos under NREL.

**Comment by jasondegraw** [comment]
@aaron-boranian Since this is mainly about the website, we'll label it as such and keep it here.

**Comment by jmarrec** [comment]
This is fixed now that website uses master.geojson

https://energyplus.net/weather-region/north_and_central_america_wmo_region_4
