### ISSUE TITLE
Central Plant Water to Water Heatpump with EIR Formulation

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6682]
The existing models for central plant water to water heatpump, HeatPump:WaterToWater:* are not formulated to be able to use the types of performance curves that are typically used in the industry. It is not possible to properly represent equipment performance characteristics with the current equation fit models and the parameter estimation model is not robust enough in practice.

Suggest to add new models for water-to-water heatpump that are formulated using an EIR-type approach for unloading curves such as are used elsewhere in the chiller and chiller-heater models. The existing two models might be deprecated.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/20303266) feedback from @EnergyArchmage

**Comment by mjwitte** [comment]
HeatPump:PlantLoop:EIR:Cooling and Heating were added in v9.3.0.
