### ISSUE TITLE
Wrong weather station data

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6686]
WMO id used for Simcoe, ON in Canada i.e. 715270 is actually for Dryden, ON and both locations are about 1814 km away from each other.

Just an idea, but it would be nice to work on a conversion tool that allows users to convert .csv or .xls weather data (hourly, daily or monthly) into energy plus weather data to enable users utilize custom data that isn't supported by the program and improve the accuracy of their energy model simulations.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/32982781) 

**NOTE**: Would @Myoldmopar or @mjwitte like to chime in if there is a different repo group that this kind of issue should be posted to? I didn't find any "weather" repos under NREL.

**Comment by aaron-boranian** [comment]
**Weather File Information Update for Hong Kong**

I am checking at the weather file for Hong Kong and there may be some misleading information in the weather file and the WMO is mixed up. 
It seems that the weather file available from Energy Plus webpage “Hong Kong SAR 450070 (CityUHK)” with a latitude of 114° 10′ (114.167) is actually from weather station WMO 450050 (with a latitude of 114.167). It seems confusing to mark another weather station (WMO 450070 with latitude of 113.915) in the weather file data.

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/33521698)

**Comment by jasondegraw** [comment]
@aaron-boranian Since these two items are with data that we don't maintain, we'll note them and forward the issues to the correct party. The conversion tool request was addressed on UserVoice, so closing this issue.
