### ISSUE TITLE
Development of External Interface: BCVTB interaction with exterior surface solar gain actuator

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6690]
Dear all,

I am currently developing a co-simulation tool using EnergyPlus through BCVTB. Versions after versions of EnergyPlus I observe that the development of the external interface with the Ptolemy server is not a major concern since the version 8.0. In order to improve the interoperability of EnergyPlus with other simulation software, I think it would be great to increase the number of actuators available through the external interface. For instance, I would be keen to be capable of defining the total solar gain on any exterior surface (cf. Eq. 5.55 Engineering Reference) on my own. Do you think it would be possible to ask your development team to include this functionality in the new version of EnergyPlus?

Best regards,

Miguel Martin

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/19841920)

**Comment by Myoldmopar** [comment]
With the advent of the data exchange API, and the ≈π number of years since last activity, I think this can be closed.
