### ISSUE TITLE
Allow evaporative coolers to cycle

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#6707]
Problem: Many residential evaporative cooling technologies (e.g., swamp coolers) are controlled to cycle on and off to meet the load. As stated in the I/O reference, these units cannot cycle, meaning that their pumps run continuously even when the required airflow rate is close to zero.

Solution: Give zone evaporative coolers the capability to cycle like unitary equipment.

Context: See the second paragraph [here](http://bigladdersoftware.com/epx/docs/8-3/input-output-reference/group-zone-forced-air-units.html#zonehvacevaporativecoolerunit)

Migrated from [UserVoice](http://energyplus.uservoice.com/forums/258860/suggestions/9118099) feedback from @nealkruis

**Comment by mjwitte** [comment]
I see this as more of a defect. Other systems such as unit heater were upgraded a while back to do a proper cycling fan (operating just long enough to meet the load in a given timestep).
Also, when operating with variable flow fan, the pump power stays at full power. Seems it should vary or have an option to vary.
See [unmethours 33251](https://unmethours.com/question/33251/why-my-zone-have-heating-load-in-summer)

**Comment by nmerket** [comment]
@mjwitte This looks like it might be important to us in the near term. Is this something on your (or someone's) list to get to soon?

**Comment by mjwitte** [comment]
@nmerket Not that I'm aware of.

**Comment by mjwitte** [comment]
Closed via #7319.
