### ISSUE TITLE
Remove unnecessary warnings in an example file

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6710]
Issue overview
--------------
[EnergyPlus !12603]: Question about warnings in 8.7 example file.

A user found warnings from an example file of AirflowNetwork_Simple_SmallOffice.idf using Output:Diagnostics, DisplayExtraWarnings.

 ** Warning ** GetAirflowNetworkInput: SurfaceAverageCalculation is entered
 for field = Wind Pressure Coefficient Type, but no roof surface is defined
 using an AirflowNetwork:MultiZone:Surface object.
 ** ~~~ ** Reconsider if this is your modeling intent. Simulation continues.
 ** Warning ** GetAirflowNetworkInput: SurfaceAverageCalculation is entered
 for field = Wind Pressure Coefficient Type.
 ** ~~~ ** The AirflowNetwork model provides wind pressure coefficients for
 4 vertical exterior orientations and 1 horizontal roof.
 ** ~~~ ** There are only 2 exterior surface orientations defined in this
 input file using AirflowNetwork:MultiZone:Surface objects.
 ** ~~~ ** Reconsider if this is your modeling intent. Simulation continues.

The example file should be enhanced to remove unnecessary warnings by adding more surface object.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Helpdesk ticket number 12603 and 12623

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6760
