### ISSUE TITLE
Zone Coil Autosizing does not include impact of AirTerminal:SingleDuct:Mixer

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6712]
Issue overview
--------------
From code inspection and studying coil sizing summary table output it was found that the coil inlet conditions are the zone return air conditions and not the mixed air from AirTerminal:SingleDuct:Mixer and the zone return air.  When a DOAS unit is connected to ZoneHVAC equipment there will often be a benefit that can reduce zone coil size.  For example if the DOAS is handling latent load and providing low wet bulb primary air, the actual mixed air condition will have a lower wet bulb than the zone return air leading to a smaller cooling coil size result.  Current code does not take this account. 

Suggest that the ZoneEqSizingData structure be expanded to include terms for air terminal mixer volume flow and primary air drybulb and humidity ratio for cooling and heating.  These values can be obtained from the central values in Sizing:System.  The coil parent objects are modified to fill in the sizing information needed in a way analogous to how OAVolFlow is used to account for direct outdoor air. Then all the coil sizing routines would be changed to use the new air terminal mixer information passed via ZoneEqSizing whenever the coil has an AirTerminal:SingleDuct:Mixer attached to the parent. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
See PR #6788.

**Comment by mjwitte** [comment]
Closed via #6788
