### ISSUE TITLE
Multiple transition idf version updater does not work

### ISSUE THREAD

**Issue by sharon1234567** [NREL/EnergyPlus#6719]
Issue overview
--------------
the multiple transition idf version updater does not work. Error message prompts when extracting the RAR (I have tried to extract it to \PreProcess\IDFVersionUpdater folder, but still don't work). 

![image](https://user-images.githubusercontent.com/38464172/38870626-f968094c-4280-11e8-86e0-bf1c9dad7b32.png)

If you have fixed this problem, would you please do me a favor to send me an email (shj198983@126.com)? Thank you very much .

**Comment by jmarrec** [comment]
Works fine on my machine: http://energyplus.helpserve.com/Knowledgebase/Article/View/86
