### ISSUE TITLE
HVACTemplate:Zone:IdealLoadsAirSystem expansion missing DSOA

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/EnergyPlus#6724]
`Design Specification Outdoor Air Object Name` fields defined in `HVACTemplate:Zone:IdealLoadsAirSystem` objects aren't being included in the `ZoneHVAC:IdealLoadsAirSystem` object at expansion.  Other fields translate fine.

Related to [this Unmet Hours thread](https://unmethours.com/question/30924/outside-air-ideal-loads/) and [this issue](https://github.com/NREL/OpenStudio/issues/3100) and [this issue](https://github.com/NREL/OpenStudio/issues/3101).

Example:
Run the measure tests for [this OpenStudio measure](https://github.com/UnmetHours/openstudio-measures/tree/master/ideal_loads_options) and then expand the `test_good_inputs.idf` with EnergyPlus.  The `test_good_inputs.expidf` file is missing the DSOA object defined in the HVACTemplate for that zone.

Using Windows10, EnergyPlus v8.9.0.

**Comment by mjwitte** [comment]
The Design Specification Outdoor Air Object Name is only written to the expidf file if the `HVACTemplate:Zone:IdealLoadsAirSystem` Outdoor Air Method = `DetailedSpecification`.
