### ISSUE TITLE
Return flow basis nodes calculation is broken

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6725]
Issue overview
--------------
User file illustrates that the return node flow rate when using the Zone Return Air Node 1 Flow Rate Basis Node or NodeList Name option is incorrect. In this file, it's 2x what it should be, but what's really happening is the flow is being set to the default flow (system inlet node associated with that return times the airloop return fraction) *plus* the sum of the basis node flows (multiplied by the Zone Return Air Node 1 Flow Rate Fraction Schedule).

### Workaround
If possible, instead of using Zone Return Air Node 1 Flow Rate Basis Node or NodeList Name to control the flow at return node 1, use the AirLoopHVAC "Design Return Air Flow Fraction of Supply Air Flow" field for the corresponding air loop.

### Details
Some additional details for this issue (if relevant):
 - Platform Win10
 - Version of EnergyPlus v8.9.0
 - Helpdesk ticket number 12636

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
I already have a fix for this, so don't spend time debugging this.

**Comment by mjwitte** [comment]
Specifically, look at the flow rates for node "SPACE2-1 DOAS Return Node" (csv column BW). They should match the flow for "SPACE2-1 Zone Equip Inlet" (csv column KC).

**Comment by rraustad** [comment]
Closed via #6726.
