### ISSUE TITLE
Schedule:Year error in 8.9

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#6729]
The `Schedule:Year` object is supposed to accept 53 weeks, but errors out after week 26. As far as I can tell, it appears that the epJSON schema does not reflect weeks 27-53 (which are written in shorthand in the IDD).

Here's an example file:
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/1947117/in.idf.txt)

Here is the error:
```
   ** Severe  ** Line: 47903 Index: 0 - Error parsing "Schedule:Year". Error in following line.
   ** Severe  ** ~~~ 
   ** Severe  ** Line: 47903 Index: 60 - "Schedule:Week:Daily {dca2e87a-322e-4e55-ae72-7b00ea884bf1}" is not a valid Object Type.
```
The Schedule:Week:Daily above is week 27.

**Comment by mjwitte** [comment]
Yep, the JSON schema stops at week 26. Probably because this was not tagged as extensible (which it is not since anything more than 53 wouldn't make sense, or maybe it would for multi-year simulations in the future with other code changes). Anyway, I think changing the IDD to act as if it's extensible and then rebuild the schema may fix the problem. It would make a cleaner schema anyway.

**Comment by RKStrand** [comment]
@mjwitte I might consider taking this on.  I took a look at this and interestingly enough after week 26 the IDD switches to a condensed notation.  There is actually room for 53 weeks in the existing IDD but for some reason it doesn't seem to figure out the weeks greater than 26.  Could the condensed IDD notation be a problem?  If so, one solution might be to simply make the IDD use the regular, one line per parameter.  Any idea what testing has been done on the "condensed" notation in the IDD?

**Comment by mjwitte** [comment]
We need guidance from @mbadams5 on this one.  It's an issue with the JSON scheme translation vs the incoming IDD definition.

**Comment by RKStrand** [comment]
@mjwitte Oh, well then perhaps it would better reside with @mbadams5 as I have no experience with JSON.

**Comment by mbadams5** [comment]
I fixed this one instance, but it is a little odd that the idd parser for conversion to epJSON schema didn't pick up the extra condensed fields. I will have to look into that later, but this specific issue should be addressed now.

**Comment by Myoldmopar** [comment]
@mbadams5 do you want to make another issue for the extra condensed fields?  Did you already?
