### ISSUE TITLE
Build Bots Comparing "PR vs PR" Rather than "PR vs Develop" Leading to Many Diffs

### ISSUE THREAD

**Issue by drewyh** [NREL/EnergyPlus#6730]
Issue overview
--------------
The build bots seem to be comparing with v8.8 results, meaning there are a lot of diffs showing up. This seemed to working correctly as of two days ago as there were no version number diffs showing up that I could see.

See here pull request here: #6728
See EIO diff here: http://energyplus.s3-website-us-east-1.amazonaws.com/regressions/2018-04/d57990544ea3c4228552f4698cb75e1202f0d7f3-24dd596bf55affa539b6bbfeb10ebf9a8746d51d/1ZoneDataCenterCRAC_wPumpedDXCoolingCoil/x86_64-MacOS-10.9-clang/eplusout.eio.diff.html

Thanks,
Andrew

**Comment by Myoldmopar** [comment]
This isn't possible.  The build bots build against the current develop branch.  Every time a new CI build is started, the develop branch is pulled, built, and run, to generate a baseline set of results.  Then the current commit is pulled, built, and run to generate the results for the current run.  The results are compared and posted to the web.  We don't do any caching or pull baseline results from anywhere.

**Comment by drewyh** [comment]
Odd. The EIO diff linked above shows the 8.8->8.9 diff, and the only commit since the last round of builds (which show no 8.8->8.9 diffs) was 24dd596bf55affa539b6bbfeb10ebf9a8746d51d which didn't change anything that should affect it. I can't force a rebuild as I get a 404 error from the "Delete results and force rebuild." button, but maybe this is worth a go?

**Comment by drewyh** [comment]
Investigating further, the failures are occurring because the results are being comparing between two pull requests (see below) rather than between this PR and develop. The comparison is being done between #6298 and #6728 (this PR) as shown below.
```
Device id: x86_64-MacOS-10.9-clang
Comparing `/Users/kbenne/ci_runs/EnergyPlus-d57990544e-PR6298-x86_64-clang/build/testfiles/1ZoneDataCenterCRAC_wPumpedDXCoolingCoil` with `/Users/kbenne/ci_runs/EnergyPlus-24dd596bf5-PR6728-x86_64-clang/build/testfiles/1ZoneDataCenterCRAC_wPumpedDXCoolingCoil`
Processing (Diffs) : 1ZoneDataCenterCRAC_wPumpedDXCoolingCoil
[decent_ci:test_result:message] AUD diffs.
[decent_ci:test_result:message] BND diffs.
[decent_ci:test_result:message] EIO diffs.
[decent_ci:test_result:message] MTD diffs.
[decent_ci:test_result:message] RDD diffs.
[decent_ci:test_result:message] Table big diffs.
[decent_ci:test_result:warn]
Regression Results
```
Will push another commit to force rebuild and see if that works.

**Comment by drewyh** [comment]
Forcing the rebuild fixed the build for i386-Windows-7-VisualStudio-14, however others are still checking results against #6298 rather than develop and hence result in many diffs.

@Myoldmopar I'm not sure why the build bots would be checking against another PR (see above) rather than develop, so I'll hold off any further troubleshooting for the moment.

**Comment by mjwitte** [comment]
@drewyh I see the same thing happening in @lgu1234 's recent commit in #6450 Very strange. @kbenne @jasondegraw  Any thoughts? Look at the paths [here](https://nrel.github.io/EnergyPlusBuildResults/EnergyPlus-338fbc9517576d288f5954a2c1039736b42177f4-x86_64-MacOS-10.9-clang.html):


Comparing `/Users/kbenne/ci_runs/EnergyPlus-d57990544e-PR6298-x86_64-clang/build/testfiles/1ZoneDataCenterCRAC_wPumpedDXCoolingCoil` with `/Users/kbenne/ci_runs/EnergyPlus-338fbc9517-x86_64-clang/build/testfiles/1ZoneDataCenterCRAC_wPumpedDXCoolingCoil`

**Comment by jasondegraw** [comment]
@mjwitte Unfortunately, the Windows CI box is stillrunning from when @Myoldmopar was last out here, so I can't really get much visibility into what is happening since it's running under his login. It certainly looks like  the wrong comparison is happening.

**Comment by MatthewSteen** [comment]
@jasondegraw @Myoldmopar any updates on a fix?

**Comment by Myoldmopar** [comment]
I'm working on this, please hold...

**Comment by Myoldmopar** [comment]
This was resolved.  It was a combination of our develop branch being way out of date, and an external pull request who made their changes on the develop branch in their fork.  Unlikely to have that combination again soon.  I also opened a ticket on decent_ci to try to fix the problem over there.
