### ISSUE TITLE
In files with two short RunPeriods only the second RunPeriod is executing  

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6736]
Issue overview
--------------
Running regression tests comparing code based off version 8.9 to 8.8 revealed that for many regression tests, the time series data are misaligned.  Found that in 8.9, not all the environments are being simulated. 

Example file 5ZoneAutoDXVAV.idf shows the problem. It has two short RunPeriods, one for February 2- 5 and the second for June 1 -5.  In Version 8.8, both run periods execute when Run Simulation for Weather File Run Periods is set to yes.  But in Version 8.9 only the second RunPeriod for June 1 - 5 gets executed.  

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (Release 8.9.0 compared to Release 8.8.0)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@EnergyArchmage @mbadams5 This was known but supposedly fixed before release. It's an input processing problem due to multiple RunPeriod objects with blank names.

**Workaround:** Add names to the RunPeriod objects, or for regression suites, force design days or annuals.
