### ISSUE TITLE
Extra fields in Construction:ComplexFenestrationState causes crash

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#6744]
Issue overview
--------------
EnergyPlus crashes with extra blank fields at the end of an Construction:ComplexFenestrationState object. When those fields are removed the file does not crash.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 8.900
 - Helpdesk ticket number: 12670

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (see devSupport repo)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lgu1234** [comment]
@JasonGlazer Are you handling this issue? If not, I will take it.

**Comment by JasonGlazer** [comment]
@lgu1234 I am not currently working on this issue. Good luck!

**Comment by JasonGlazer** [comment]
@lgu1234 should this issue be closed?

**Comment by lgu1234** [comment]
@JasonGlazer Yes.
