### ISSUE TITLE
Installation packaging failing on SetupOutputVariables.csv with new style formatting

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6746]
Issue overview
--------------
The latest clang auto formatting spreads arguments out to multiple lines for calls to SetupOutputVariable().  The script called parse_output_variables.py, that is used to scrape the code to generate the csv summary list, assumes the calls are all on one line.  The script needs to be revised to concatenate all the separate lines up to the semicolon.  

Verify by apply latest style to AirflowNetworkBalanceManager.cc and successfully build package.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
I already have PR (#6608) (opened on March 28) which should fix this.  I need to do final testing on it before I make any claims about it being ready.

**Comment by Myoldmopar** [comment]
Merged #6608; this is done.
