### ISSUE TITLE
Multiple GenericContam controllers are not set correctly

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6747]
Issue overview
--------------
Issue #6565 fixed a bug to set multiple CO2 controllers correctly. The same issue occurs to handle multiple generic contam controllers.
 
### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Fixed via #6751
