### ISSUE TITLE
Issue a fatal error with two or more fans in an AirLoop using AirflowNetwork model

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#6748]
Issue overview
--------------
The input file has two fans in an AirLoop. The AirflowNetwork model assumes a single fan in each AirLoop. A fatal error should be issued to stop simulation and give a user clear instruction how to fix input errors.

[EnergyPlus !12675]: L U factorisation Error in AIrflow network distribution

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6758
