### ISSUE TITLE
Confusing errors when no control zone name is specified for Load control in AirloopHVAC:UnitarySystem

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6750]
Issue overview
--------------
Initial checks for system connections fail when Load control is specified and no Control Zone Name is entered. Review of code also indicates that the AirTerminal:SingleDuct:Mixer will not work correctly when used with AirloopHVAC:UnitarySystem if Setpoint control is specified.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
See PR #6757.

**Comment by mjwitte** [comment]
Closed via #6757
