### ISSUE TITLE
Crash in 8.9 during Initialization Summary tabular report

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#6756]
A crash occurs when generating the Initialization Summary tabular report. When tabular reports are eliminated the simulation completes successfully.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (8.9.0)
 - helpdesk ticket number #12687

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (devsupport)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
@mjwitte I confirmed that this is the same issue as #6860

**Comment by mjwitte** [comment]
Closed via #6942
