### ISSUE TITLE
Coil Sizing Summary shows incorrect VAV box coil inlet air conditions

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6761]
Issue overview
--------------
The new coil sizing summary does not pick up the entering coil conditions for non-water coils. The Powered Induction Units also report the inlet conditions incorrectly.

 - [ ] VAV coil entering air conditions incorrect for non-water coils.
 - [ ] PIU calculates entering air temperature differently than used for coil capacity sizing
 - [x] Inch Pound conversion converts -999 and -99999 to large negative numbers which can be confusing to users
 - [x] Add zone name to Coil Sizing Details table (Yahoo groups user was complaining about not knowing which zone was associated with zone coils)

Yahoo email:
"I have model with VAV Reheat air loops. Each zone has a reheat coil and some have baseboard convectors. I have not been able to find a report that tells me which reheat coil serves which zone and which baseboard convector serves which zone."

Defect file is modification of 5ZoneAutoDXVAV.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) - all
 - Version of EnergyPlus (if using an intermediate build, include SHA) - V8.9
 - Unmethours link or helpdesk ticket number - none

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Coil sizing summary does not pick up coil inlet conditions for non-water coils. Coil entering air temps should be 18 C (64.4 F) in table below.

  Sizing:System,
    VAV Sys 1,               !- AirLoop Name
    18.,                     !- Central Heating Design Supply Air Temperature {C}

![wrongvavcoilinlettemps](https://user-images.githubusercontent.com/5778156/40677485-ccf4718e-634b-11e8-8aea-cbab8b3b9b94.jpg)

**Comment by rraustad** [comment]
See PR #6762

**Comment by rraustad** [comment]
Coil Sizing Details also leaves out zone name where users cannot match up zone coil with zone (unless coil name includes zone name).

![6761_step2_showzonenameincoilsizingdetailstable](https://user-images.githubusercontent.com/5778156/40683979-14dcc93a-635e-11e8-9156-f510b7031b7d.jpg)

**Comment by Myoldmopar** [comment]
Closed via #6762
