### ISSUE TITLE
Swimming pool flow not added to plant loop sizing

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6763]
Issue overview
--------------
User file with an autosized plant loop serving only a swimming pool (no other coils) results in zero maximum loop volume flow rate. The flow rate specified in the SwimmingPool:Indoor apparently is not getting registered in the plant loop sizing data.  This happens even if there are other coil on the plant loop - the swimming pool flow rate is not added to the total flow.

### Workaround
Hard-size the plant loop and pump flow rates.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus 8.9.0
 - Helpdesk ticket number 12403

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Can it be this easy?

Simply added RegisterPlantCompDesignFlow where the nodes are initialized.

    if (Pool(PoolNum).WaterInletNode > 0) {
        InitComponentNodes(0.0, Pool(PoolNum).WaterMassFlowRateMax, Pool(PoolNum).WaterInletNode,
          Pool(PoolNum).WaterOutletNode, Pool(PoolNum).HWLoopNum, Pool(PoolNum).HWLoopSide,
          Pool(PoolNum).HWBranchNum, Pool(PoolNum).HWCompNum);
        PlantUtilities::RegisterPlantCompDesignFlow(Pool(PoolNum).WaterInletNode, 
          Pool(PoolNum).WaterVolFlowMax);
    }

![6763-poolflowratefixed](https://user-images.githubusercontent.com/5778156/40691957-f0c98a82-637c-11e8-9f62-efbaa0cb3ab7.jpg)

**Comment by rraustad** [comment]
See PR #6765.

**Comment by rraustad** [comment]
@RKStrand do you need defects to work on? I can review if you want this one.

**Comment by RKStrand** [comment]
@rraustad Yes, I need defects to work on and will put this on my list. I will tag you as the reviewer when it’s done. Hopefully I will work on this soon. Thanks for sending this my way!

**Comment by rraustad** [comment]
@RKStrand the branch is already created with name #6763-Swimming-pool-flow-not-added-to-plant-loop-sizing

**Comment by rraustad** [comment]
Closed via #6765.
