### ISSUE TITLE
Life cycle analysis crashes if 100 years is selected.

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6784]
Issue overview
--------------
The problem shows up in the debugger when 100 years is used as the life cycle cost period. This does not cause a crash in the release version.

When the LifeCycleCost:UsePriceEscalation is read in, the maximum numbers is allocated to 100 and when the start year numeric is included, the number of numbers = 101.

    Array1D<Real64> NumArray(100);   // numeric data

    for (iInObj = 1; iInObj <= numUsePriceEscalation; ++iInObj) {
        inputProcessor->getObjectItem(CurrentModuleObject, iInObj, AlphaArray, NumAlphas, NumArray, NumNums, IOStat, lNumericFieldBlanks,
                             lAlphaFieldBlanks, cAlphaFieldNames, cNumericFieldNames);

When getObjectItem is called, the Numbers array is allocated to 100 while numeric_index = 101. What happens in the release version is unknown.

    Numbers(numeric_index) = field_value.get<double>();

Additionally, this object is not really extensible since the limit is 100 years. Suggest just adding the number of years directly in the IDD and eliminate the extensible attribute. This method also allows the IDFEditor to open files that have greater than 30 years of input data.

Used the example file 5ZoneEconomicsTariffAndLifeCycleCosts.idf and extended the number of years to 100.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
See PR #6785.

**Comment by mjwitte** [comment]
Closed via #6785
