### ISSUE TITLE
Revise error trap in PsyWFnTdpPb when the saturation pressure comes back greater than barometric pressure

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6787]
Issue overview
--------------
Prompted by a user questioning a negative humidity ratio warning, like this:
```
   ** Warning ** Calculated Humidity Ratio invalid (PsyWFnTdpPb)
   **   ~~~   **  Routine=UpdateZoneSizing, During Sizing, Environment=SACRAMENTO METROPOLITAN AP ANN CLG 2% CONDNS ENTH=>MDB, at Simulation time=07/21 24:00 - 24:10
   **   ~~~   **  Dew-Point= 100.00 Pressure= 101264.94
   **   ~~~   ** Calculated Humidity Ratio= -410.2300 ... Humidity Ratio set to .00001
```
In this case, UpdateZoneSizing is trying to calulate the humidity ratio at a dew-point of 100C (because the zone has no cooling so the tstat cooling setpoint is 100C) which, in this case, results in a saturation pressure that is greater than the barometric pressure. The resulting humidity ratio should be the maximum possible at the barometric pressure (or something like that), not 0.00001. And it possibly shouldn't even result in an error, it should just proceed with the maximum possible value? Needs more thought than this, but the current behavior is confusing and misleading.

For this particular test file, using a cooling setpoint of 99C instead of 100C would have avoided the psychrometric error.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.9.0
 - Unmethours [32111](https://unmethours.com/question/32111/negative-humidity-in-doe-reference-model/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file 
[in-100.idf.txt](https://github.com/NREL/EnergyPlus/files/2116733/in-100.idf.txt)
[in-99.idf.txt](https://github.com/NREL/EnergyPlus/files/2116737/in-99.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lgu1234** [comment]
Closed via #7438
