### ISSUE TITLE
Ventilation Rate Procedure Standard 62.1 problem with system population diversity 

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6790]
Issue overview
--------------
Interface developer reported issues in Ventilation Rate Procedure Standard 62.1 calculations.  There is a mistake in how System Population diversity term, D, is applied.  
The D term should only be multiplied by the sum of zone per-person OA requirements. However the last revision of the code did not get this corrected.  

In addition the intermediate value for Vou should have had the D term included in it, per Standard.  This makes the currently reported values for Vou, Xs, Ev, and Vot appear to be inconsistent and is confusing to users.

Code changes are needed to correct how D is applied and Vou is reported. This will tend to increase minimum OA at the system level in files with D < 1.0.  

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
@nagappanchidambaram @larryscheier what other pressing E+ engine issues should be corrected before next week?

**Comment by larryscheier** [comment]
@nagappanchidambaram  would be the one to identify pressing remaining issues for this service pack but he may be on vacation?

**Comment by mjwitte** [comment]
Closed via #6791
