### ISSUE TITLE
Throw error for excess Controller:WaterCoil objects

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6792]
Issue overview
--------------
User file has (many) AirloopHVAC:UnitarySystem with water coils. Plus there is a Controller:WaterCoil for every coil, which shouldn't be used when the water coil is inside another system. This file results in many  FindRootSimpleController errors.

In order to make a simpler test file, tried to start with example file UnitarySystem_WaterCoils_wMultiSpeedFan which has one AirLoopHVAC:UnitarySystem with lwater coils, but discovered that this has a Controller:WaterCoil present for the CW coil - which it should not.  Made a version of this with the water coil deleted and the results change.

1. Need to fix UnitarySystem_WaterCoils_wMultiSpeedFan and remove the excess controller object (and controller list, and excess setpoint managers)
2. Need to throw a fatal error when a Controller:WaterCoil object is present for a water coil that is not directly on a branch or outdoor air system, or ??? This may be difficult to determine. Maybe the water coil init can figure this out.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.9.0
 - Private e-mail 2018-06-20

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6804
