### ISSUE TITLE
Use of Schedule:File suppresses progress messages to the console window

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6793]
Issue overview
--------------
Any idf that uses Schedule:File runs almost silently with no progress messages to the console window. Happened to notice this with the defect file for #6792 but didn't understand why. until sharing the file with @Myoldmopar but forgot to send the schedule csv file.

Example file 5ZoneTDV shows the problem.  Here's a screen shot on Win64 using v8.9.0.

![image](https://user-images.githubusercontent.com/4991075/41674376-6cad5994-7485-11e8-8919-a61e4188c22d.png)

And here's a slightly different result using HybridZoneModel:

![image](https://user-images.githubusercontent.com/4991075/41674560-03069798-7486-11e8-894c-26a4f3cf02f8.png)

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.9.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file - use 5ZoneTDV and HybridZoneModel example files.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
And it did work OK for me on Linux (I see the normal standard output.)

I wonder if some IO setting is being set when the program attempts to read the csv file on Windows and it muffles all standard output from that point on.

**Comment by Myoldmopar** [comment]
Closed via #6975
