### ISSUE TITLE
VRF Cooling Capacity function of Temperature Boundary Curve doesn't include Temperature as a valid type

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6797]
Issue overview
--------------
I am modeling a VRF system and find the Cooling Capacity Function of Temperature Boundary Curve (some others more) should have output in "Temperature", but idd for Output Unit Type only allows Dimensionless, Capacity and Power options. Should E+ add Temperature as an option as well.

 Checking EnergyPlus VRF example file reveals Temperature is input for Output Unit Type of curve objects.

Helpdesk Ticket 12864.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Presently, EnergyPlus only validates the curve object unit types and then does nothing else with them. IDF Editor uses them, and possibly other input tools, so this is a useful change. Further use of units in curves and tables is suggested in #7075.
