### ISSUE TITLE
BCVTB Issue on Linux

### ISSUE THREAD

**Issue by nowox** [NREL/EnergyPlus#6800]
Issue overview
--------------
I am trying to use BCVTB to iterate through the simulation. I have written a Python script that open a TCP socket and communicate with EnergyPlus 8.8.  I experience an error on pure Linux operating systems: 

* Windows 10 [OK]
* Windows Subsystem for Linux [OK]
* Ubuntu 1604 [Error, received: `\x882 -1`]
* Docker Debian [Error, received: `\x882 -1`]

When it works, energyplus I can read this on my script: 

```
Warming up {1}
Instantiating Building Controls Virtual Test Bed
ExternalInterface initializes.
2018-06-27 14:44:44,032 DEBUG - Connected with 127.0.0.1:52480
2018-06-27 14:44:44,032 INFO - Waiting for simulation start states
Number of outputs in ExternalInterface = 5
Number of inputs  in ExternalInterface = 2
Warming up {2}
Warming up {3}
Warming up {4}
Warming up {5}
Warming up {6}
Warming up {7}
Warming up {8}
Warming up {9}
Warming up {10}
Warming up {11}
Warming up {12}
Starting Simulation at 05/15 for BARCELONA-AP - ESP IWEC2 WMO#=081810
ExternalInterface starts first data exchange.
2018-06-27 14:45:00,140 INFO - Received message from EnergyPlus: b'2 0 5 0 0 0.000000000000000e+00 1.600000000000000e+01 0.000000000000000e+00 0.000000000000000e+00 1.000000000000000e+00 0.000000000000000e+00
```

When it doesn't work, I get this: 

```
Warming up {1}
Instantiating Building Controls Virtual Test Bed
ExternalInterface initializes.
2018-06-27 14:49:52,332 DEBUG - Connected with 127.0.0.1:56354
2018-06-27 14:49:52,332 INFO - Waiting for simulation start states
EnergyPlus Run Time=00hr 00min  1.37sec
2018-06-27 14:49:52,953 INFO - Received message from EnergyPlus: b'\x882 -1'
2018-06-27 14:49:52,954 ERROR - Simulation stopped with error code -1'
```

### Details

 - WSL, Windows 10, Ubuntu, Debian on Docker
 - EnergyPlus, Version 8.8.0-7c3bbe4830, YMD=2018.06.27 14:44
 - Anaconda 3
 - Python Script that I am using: https://gist.github.com/nowox/7ce93ec0ef68d9a9e7e3b948e68d271c 

### Analysis

It seems EnergyPlus never get to the Warming up phase: 

```
Number of outputs in ExternalInterface = 5
Number of inputs  in ExternalInterface = 2
Warming up {2}
Warming up {3}
Warming up {4}
...
```

Unfortunately I don't have any output log and I don't know where it is blocked. Any clues?

**Comment by nowox** [comment]
Up ?

**Comment by mjwitte** [comment]
@nowox Does EnergyPlus generate any output files?  Any error messages in eplusout.err?

**Comment by nowox** [comment]
Unfortunately no other errors than provided. The weird output is this `x882 -1` where `x882` does not look like a version number, but `-1` is indeed an error code.

**Comment by mjwitte** [comment]
@mwetter Any suggestions?

**Comment by mwetter** [comment]
I don't see in the BCVTB code that writes `Received message from`. This message may be from the Python script from @nowox that points to a local link 
https://gist.github.csem.local/ycr/efacec8094b27e1ad4fb17881796b85a and hence I don't see what is going on.
As I wrote to @nowox  by email on Nov. 1, I recommend to export EnergyPlus as an FMU and use for example PyFMI. This way allows using a tested API rather than developing your own interface.

**Comment by nowox** [comment]
Sorry about this, I misplaced my gist. It is now available [here]( https://gist.github.com/nowox/7ce93ec0ef68d9a9e7e3b948e68d271c). 

I am not against using PyFMI, but the documentation is very sparse and it is meant to be used with JModelica. My goal far less ambitious, I only would like to: send a new setpoint to EnergyPlus, and get the intermediate states. I have tried to use PyFMI, but there are a lot of hidden code. You need to compile a FMU file which is OS specific. By digging down how PyFMI or Ptolemy communicate with EnergyPlus I discovered that things are way simpler. You don't need a mass of code, just a TCP socket, that's it and I would be really happy with that. 

As you can see on my Gist, the simulation file is only 250 lines of Python with no dependencies to specific products such as JModelica. I am perfectly aware that this code is preliminary, not well tested, but the only few things it does are: 

- Generate a socket file needed by EnergyPlus (PyFMI does the same)
- Run EnergyPlus with the path of my model and weather file
- Listen to the TCP socket

The problem is that before I send any data through the socket, EnergyPlus has already crashed on Linux with this weird error message. This proves that my code should not be responsible for what happens. 

If you have a simpler solution that works on both Windows and Linux with proper documentation I would be more than happy.

**Comment by YanfeiNREL** [comment]
@nowox Did you have any luck in solving this issue?  using the FMU/PyFMI approach?  Or figured out your own way by using bare Socket programming?  Please let me know so i can help you for the next step if necessary.

**Comment by YanfeiNREL** [comment]
it appears the user figured out this issue. i am closing it.
