### ISSUE TITLE
Inconsistent convection coefficients

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#6806]
Issue overview
--------------
Doing a search through the code I came across an inconsistency.  I was searching for the float literal '9.482', and came up with four hits in the convection algorithms, and one in the fluid properties.  The convection was my interest.  The four all look to be based on the same Walton expression, but there is one inconsistent.  All hits are in ConvectionCoefficients.cc at eb68ccb2bf.

- [Line 985](https://github.com/NREL/EnergyPlus/blob/eb68ccb2bfb3d01807412e33399299da8cdb4b11/src/EnergyPlus/ConvectionCoefficients.cc#L985)
  - Hn = 9.482 * (std::pow(std::abs(TOutSurf - TAir), OneThird)) / (7.238 - std::abs(CosTilt));
- [Line 4266](https://github.com/NREL/EnergyPlus/blob/eb68ccb2bfb3d01807412e33399299da8cdb4b11/src/EnergyPlus/ConvectionCoefficients.cc#L4266)
  - HcIn(SurfNum) = 9.482 * std::pow(std::abs(DeltaTemp), OneThird) / (7.283 - std::abs(Surface(SurfNum).CosTilt));
- [Line 4293](https://github.com/NREL/EnergyPlus/blob/eb68ccb2bfb3d01807412e33399299da8cdb4b11/src/EnergyPlus/ConvectionCoefficients.cc#L4293)
  - HcIn(SurfNum) = 9.482 * std::pow(std::abs(DeltaTemp), 1.0 / 3.0) / (7.283 - std::abs(Surface(SurfNum).CosTilt));
- [Line 8063](https://github.com/NREL/EnergyPlus/blob/eb68ccb2bfb3d01807412e33399299da8cdb4b11/src/EnergyPlus/ConvectionCoefficients.cc#L8063)
  - Hn = 9.482 * std::pow(std::abs(DeltaTemp), OneThird) / (7.283 - std::abs(CosineTilt));

Note how the first one uses a 7.238 multiplier while the others use 7.283.  I am inclined to say the 283 is correct since it was used more times, but that could've easily been mistakenly used once and then the others based on that.  So the fix needs to include a check back at the handbook to find the right value.  And the fix also needs to include putting this and other convection coefficients into a single function/class to eliminate this insanity of repeated repeated repeated repeated expressions.

### Details
Some additional details for this issue (if relevant):
 - Platform: agnostic
 - Version of EnergyPlus: eb68ccb2bf

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@Myoldmopar Well, that was an interesting trip down memory lane.  I traced this back to old IBLAST code which is borrowed from BLAST and the subroutine written by George Walton (completely with GOTOs everywhere--love it!).  I searched for both 7.238 and 7.283 and only found 7.238.  So, given that this is George's work, I'm actually inclined to believe that 7.238 is correct and not 7.283.  And the most likely source of the error is...me.  The oldest subroutines where the 7.283 show up have my name on it.  The other occurrence was probably based on my mistake.  Good catch on your part though.  I will fix it based on this and do the unit test.  I will also correct the documentation.

**Comment by Myoldmopar** [comment]
Solid detective work.  I can see the problem in Blast in the 34th column of this line:
![image](https://user-images.githubusercontent.com/849824/42710470-c7461252-86a9-11e8-983c-63790f8858ac.png)

**Comment by RKStrand** [comment]
@Myoldmopar Hahaha!  Hilarious!! 😂😂😂

**Comment by Myoldmopar** [comment]
Closed via #6839
