### ISSUE TITLE
Transformer Rated Capacity of 0 hard crashes

### ISSUE THREAD

**Issue by brianlball** [NREL/EnergyPlus#6814]
Issue overview
--------------
If a value of 0 is used for the 'Rated Capacity {VA}' field in the Transformer, E+ will hard crash and will be difficult for user to debug.

### Details
To reproduce, change line 2546 from 15000 to 0 in the Generators_Transformer.idf test file or see attached zip.
[Generators_Transformer_0.zip](https://github.com/NREL/EnergyPlus/files/2177960/Generators_Transformer_0.zip)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #6877
