### ISSUE TITLE
Three small inconsistencies in IDD

### ISSUE THREAD

**Issue by alex-tan** [NREL/EnergyPlus#6815]
Issue overview
--------------

1. AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR

has two attributes with the index N43:

`\field Heat Recovery Heating Capacity Time Constant`
`\field Initial Heat Recovery Heating Energy Fraction`

This seems to be the only duplicate attribute index in the IDD, which I assume is unintentional.

2. `\ group Hybrid Model`

There's a space between `\` and `group` unlike all the other group declarations.

3. 4 Objects use different capitalization for \type 

These 4 objects are annotated as `\type Alpha` instead of `\type alpha` which is how all other objects are.

RoomAir:Node:AirflowNetwork
RoomAir:Node:AirflowNetwork:AdjacentSurfaceList
RoomAir:Node:AirflowNetwork:InternalGains
RoomAir:Node:AirflowNetwork:HVACEquipment

### Details
Some additional details for this issue (if relevant):

Found in versions 8.7 and 8.8

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Item 1 is still present, N42 was skipped.  Item 2 was addressed prior to v8.9.0 release.

**Comment by mjwitte** [comment]
@Myoldmopar And another one that I suppose has to wait until after release.

**Comment by alex-tan** [comment]
Note: just added a third small issue I found regarding `\type` capitalization in the issue text.

**Comment by mjwitte** [comment]
@alex-tan Added to #6951

**Comment by Myoldmopar** [comment]
Closed via #6951
