### ISSUE TITLE
unintended ZoneHVAC:FourPipeFanCoil fan sizing interaction with ZoneHVAC:EquipmentList

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/EnergyPlus#6820]
Issue exists in EnergyPlus 8.9.0

I'm adding a **ZoneHVAC:EnergyRecoveryVentilator** and a **ZoneHVAC:FourPipeFanCoil** to a zone.
This process is going in the default hvac systems module in the openstudio-standards gem, so hard-sizing isn't an option.

In the original process, the fan coil units were being added first, but this created some heating unmet hours in a core zone. It was related to the order of operations of HVAC equipment in **ZoneHVAC:EquipmentList**.  The fan coil was acting first, and not taking into account the introduced ventilation load from the ERV during cold outdoor air conditions.

The **ZoneHVAC:EquipmentList** object in the EnergyPlus I/O reference mentions this:
_"For situations where one or more equipment types has limited capacity or limited control capability, order the sequence so that the most controllable piece of equipment runs last. For example, with a dedicated outdoor air system (DOAS), the air terminal for the DOAS should be assigned Heating Sequence = 1 and Cooling Sequence = 1. Any other equipment should be assigned sequence 2 or higher so that it will see the net load after the DOAS air is added to the zone."_

I changed the equipment ordering to put ERVs first.  When I do this the fans in the **ZoneHVAC:FourPipeFanCoil** objects are now being sized to the ventilation air flow rate, rather than the heating or cooling design air flow rate as they should be.  The coil sizes are the same in both cases and reference the higher air flow rate, so it's just the fans that didn't get sized correctly when the **ZoneHVAC:FourPipeFanCoil** objects are called second in **ZoneHVAC:EquipmentList**.
***
Component Sizing when Fan Coils are called first in **ZoneHVAC:EquipmentList**:
![fan_coils_first](https://user-images.githubusercontent.com/2249271/42539558-a9165baa-8458-11e8-8520-727faf48c2b6.PNG)
![fan_coils_first2](https://user-images.githubusercontent.com/2249271/42539563-abc6bf16-8458-11e8-9b42-5ccba93ba4d2.PNG)
***
Component Sizing when Fan Coils are called second in **ZoneHVAC:EquipmentList**:
![ervs_first](https://user-images.githubusercontent.com/2249271/42539835-87107d14-8459-11e8-8497-d214c7805c54.PNG)
![ervs_first2](https://user-images.githubusercontent.com/2249271/42539841-88721640-8459-11e8-86c1-9dd5b99989a2.PNG)
***
This issue isn't happening with a similar **ZoneHVAC:WaterToAirHeatPump** object - here the fans there are getting sized to the heating and cooling airflow with ERVs listed first in **ZoneHVAC:EquipmentList** and identical **Sizing:Zone** object inputs.

Changing the **Sizing:Zone** objects to no longer account for a "DOAS system" (Neutral Supply Air) doesn't change the fan sizing.

Including a **DesignSpecification:ZoneHVAC:Sizing** object doesn't change the fan sizing either.

My guess is this has something to do with the order of operations in the [Fan Coil sizing routine in EnergyPlus](https://github.com/NREL/EnergyPlus/blob/7caa7447ba09ea0b7926718477b0a8719c4aafd2/src/EnergyPlus/FanCoilUnits.cc#L1315)

**Comment by Myoldmopar** [comment]
@rraustad would you be able to take a look at this as you start working on your next bug fixes?

**Comment by mdahlhausen** [comment]
Here is an example file with the issue:
[fan_coil_fan_sizing_issue.zip](https://github.com/NREL/EnergyPlus/files/2211335/fan_coil_fan_sizing_issue.zip)
I think what's happening is the fan coil fan is defaulting to the zone ventilation size, when it should size to the maximum of the coil design air flow rates, and ignore the zone ventilation size if the fan coil doesn't provide outdoor air.  If the fan coil does provide outdoor air, then it should take the maximum of zone ventilation and the coil design air flow rates.

**Comment by rraustad** [comment]
Yes I can. I think I already know that when there are 2 systems in the same zone and one uses outdoor air and the other does not, then FinalZoneSizing doesn't know which OA data goes where since there is only 1 FinalZoneSizing per zone. The work around is to hard size but the first sentence in the description says that is not an option.

**Comment by mjwitte** [comment]
@rraustad Just a guess but it's possible that the ERV is not clearing all of the sizing data flags after it finishes sizing.

**Comment by mjwitte** [comment]
A single FinalZoneSizing should be fine, the equipment needs to decide what data to grab from it.

**Comment by rraustad** [comment]
@mjwitte is correct. ERV doesn't reset the sizing flags and fan coil calls the fan (during sizing) before setting them (at the end of sizing). So lingering sizing flags is a no-no. I have corrected that in #6753, at least partially, with new function resetHVACSizingGlobals (it's not applied to ERV). Simple fix just reset the flags in ERV. No workaround I can think of.

**Comment by rraustad** [comment]
Sizing after fix of restting data at very end of ERV sizing.

    // Reset zone equipment sizing data
    ZoneEqSizing(CurZoneEqNum).AirVolFlow = 0.0;
    ZoneEqSizing(CurZoneEqNum).OAVolFlow = 0.0;
    ZoneEqSizing(CurZoneEqNum).SystemAirFlow = false;
    ZoneEqSizing(CurZoneEqNum).DesignSizeFromParent = false;


    Component Sizing Information, Fan:OnOff, THERMAL ZONE: STORY 1 CORE SPACE ERV SUPPLY FAN, Design Size Maximum Flow Rate [m3/s], 0.19154
    Component Sizing Information, Fan:OnOff, THERMAL ZONE: STORY 1 CORE SPACE ERV EXHAUST FAN, Design Size Maximum Flow Rate [m3/s], 0.19154
    Component Sizing Information, ZoneHVAC:FourPipeFanCoil, THERMAL ZONE: STORY 1 CORE SPACE FCU, Design Size Maximum Supply Air Flow Rate [m3/s], 0.77515
    Component Sizing Information, Fan:OnOff, THERMAL ZONE: STORY 1 CORE SPACE FAN COIL FAN, Design Size Maximum Flow Rate [m3/s], 0.77515

**Comment by mdahlhausen** [comment]
@rraustad will this fix be in the EnergyPlus 8.10 release?  Should this issue be closed?

**Comment by Myoldmopar** [comment]
@mdahlhausen Pull request #6753 was indeed merged into the main branch, and will be released with version **9.0**.  I believe that did address this issue but I'll let @mjwitte or @rraustad confirm by closing this issue or commenting that something is still not quite done.

**Comment by rraustad** [comment]
I'll have to check. There were code changes that reset sizing data after each zone equipment is sized. These changes may fix this problem but I'd rather check first before closing this.

**Comment by rraustad** [comment]
@mdahlhausen if I test this tomorrow do you agree that the results above as I show in my comment for Jul 19 are correct?

    Component Sizing Information, Fan:OnOff, THERMAL ZONE: STORY 1 CORE SPACE ERV SUPPLY FAN, Design Size Maximum Flow Rate [m3/s], 0.19154
    Component Sizing Information, Fan:OnOff, THERMAL ZONE: STORY 1 CORE SPACE ERV EXHAUST FAN, Design Size Maximum Flow Rate [m3/s], 0.19154
    Component Sizing Information, ZoneHVAC:FourPipeFanCoil, THERMAL ZONE: STORY 1 CORE SPACE FCU, Design Size Maximum Supply Air Flow Rate [m3/s], 0.77515
    Component Sizing Information, Fan:OnOff, THERMAL ZONE: STORY 1 CORE SPACE FAN COIL FAN, Design Size Maximum Flow Rate [m3/s], 0.77515

**Comment by rraustad** [comment]
In the latest develop is the same results (almost) as shown previously,  0.19 for for the ERV and 0.77 for the fan coil. Any comments?

    Component Sizing Information, Fan:OnOff, THERMAL ZONE: STORY 1 CORE SPACE ERV SUPPLY FAN, Design Size Maximum Flow Rate [m3/s], 0.19154
    Component Sizing Information, Fan:OnOff, THERMAL ZONE: STORY 1 CORE SPACE ERV EXHAUST FAN, Design Size Maximum Flow Rate [m3/s], 0.19154
    Component Sizing Information, ZoneHVAC:FourPipeFanCoil, THERMAL ZONE: STORY 1 CORE SPACE FCU, Design Size Maximum Supply Air Flow Rate [m3/s], 0.77566
    Component Sizing Information, Fan:OnOff, THERMAL ZONE: STORY 1 CORE SPACE FAN COIL FAN, Design Size Maximum Flow Rate [m3/s], 0.77566

**Comment by mdahlhausen** [comment]
@rraustad Yep that's correct.  Thanks for fixing!  I'm glad it got in this next release.  I think the issue can be closed.
