### ISSUE TITLE
Dry Climate Water Cooling Coil Sizing Calculations Not Consistent for Leaving Humidity Ratio

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#6829]
Issue overview
--------------
Studying results in the new coil report table shows some inconsistent things with leaving humidity ratio where different parts of the cooling coil sizing in WaterCoils.cc use different leaving humidity ratios..  Usually the leaving humidity ratio is taken from the input in Sizing:System but that can be modified in dry climates, such as Denver.  There are two methods. First, if the mixed air humidity ratio is already lower than the target supply air humidity ratio the target is halved. Second, based on the entering chilled water temperature, there is a lower limit of humidity ratio that is possible and if entering or leaving humidity ratio is too low then the coil is running dry and the leaving humidity ratio adjusted upward to match the entering humidity ratio. These dry coil checks need to be implemented earlier in the cooling coil sizing routines and used consistently when calculating coil capacity and water flows.  

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #7196
