### ISSUE TITLE
EMS program object no longer allows a blank line (field)

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6831]
Issue overview
--------------
Prior to v8.9, a blank line (blank field) was allowed in the middle of an EnergyManagementSystem:Program object. Now, all fields in this object are required, so a blank fails.  

Either need to change the IDD so that only the first program line is required (move begin-extensible to the second program line) or change v8.8-v8.9 transition to find a remove any blank fields.  I'd prefer just changing the IDD.

@mbadams5 Perhaps you can address this in one of your current JSON PRs.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.9.0
 - Found while running defect file for #6347 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles\6000s\6347\Hospital Fuel Cell 2-v8.8.idf
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mbadams5** [comment]
I have addressed this here #6832. Although I need to think about if I want to keep it my way or move begin-extensible to the second program line like you suggested.

**Comment by mjwitte** [comment]
Duplicate of #6601 [this comment](https://github.com/NREL/EnergyPlus/issues/6601#issuecomment-377024207). Closed via #6832.
