### ISSUE TITLE
Bug in surface dot/cross product calculation

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#6834]
Issue overview
--------------
Surfaces maybe have multiple co-linear points generated by intersection with other surrounding surfaces.  EnergyPlus's dot/cross product routines appear to only consider the first couple of points when computing the dot/cross product.  This can cause failures if the points considered all happen to be co-linear, even if the surface is not.  For example:

    BuildingSurface:Detailed,
      Face 47,                                !- Name
      Floor,                                  !- Surface Type
      ExtSlabCarpet 4in ClimateZone 1-8,      !- Construction Name
      Corridor 04,                            !- Zone Name
      Ground,                                 !- Outside Boundary Condition
      ,                                       !- Outside Boundary Condition Object
      NoSun,                                  !- Sun Exposure
      NoWind,                                 !- Wind Exposure
      ,                                       !- View Factor to Ground
      ,                                       !- Number of Vertices
      64.008, 8.8392, 0,                      !- X,Y,Z Vertex 1 {m}
      64.008, 11.8872, 0,                     !- X,Y,Z Vertex 2 {m}
      64.008, 20.7264, 0,                     !- X,Y,Z Vertex 3 {m}
      64.008, 30.48, 0,                       !- X,Y,Z Vertex 4 {m}
      64.008, 39.3192, 0,                     !- X,Y,Z Vertex 5 {m}
      64.008, 42.3672, 0,                     !- X,Y,Z Vertex 6 {m}
      64.008, 51.2064, 0,                     !- X,Y,Z Vertex 7 {m}
      76.8096, 51.2064, 0,                    !- X,Y,Z Vertex 8 {m}
      76.8096, 8.8392, 0;                     !- X,Y,Z Vertex 9 {m}

Generates the error:

    ** Warning ** GetSurfaceData: There are 40 coincident/collinear vertices; These have been deleted unless the deletion would bring the number of surface sides < 3.
       **   ~~~   ** For explicit details on each problem surface, use Output:Diagnostics,DisplayExtraWarnings;
       ** Severe  ** CalcCoordinateTransformation: Invalid dot product, surface="FACE 47":
       **   ~~~   **  (  64.008,   8.839,   0.000)
       **   ~~~   **  (  64.008,  42.367,   0.000)
       **   ~~~   **  (  64.008,  42.367,   0.000)
       **   ~~~   **  (  64.008,  51.206,   0.000)
       **  Fatal  ** CalcCoordinateTransformation: Program terminates due to preceding condition.

Interestingly enough, the warning says that co-linear points are deleted but they have not been.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus - 8.9

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by macumber** [comment]
Defect file below:
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/2189192/in.idf.txt)

**Comment by mjwitte** [comment]
@lgu1234 It appears this was addressed by #6853, correct?

**Comment by lgu1234** [comment]
@mjwitte Yes. You may close it.

**Comment by mjwitte** [comment]
Closed via #6853
