### ISSUE TITLE
No way to just convert IDF to JSON without running simulation

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#6835]
Issue overview
--------------
I would like to use `energyplus -c my.idf` to convert an IDF to JSON.  However, when I do this, EnergyPlus also attempts to run a simulation.  This takes additional time and generates many unwanted files.  Can we add a way to only do the conversion and then exit?

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus - 8.9

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@macumber Did you try setting everything in SimulationControl to "No"?

**Comment by macumber** [comment]
That is a possibility, would still be preferable to not have to change the IDF though.  A command line switch would be my preference.
