### ISSUE TITLE
Incorrect temperature is used in CalcRadSysHXEffectTerm function

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6842]
Issue overview
--------------
CalcRadSysHXEffectTerm() function in LowTempRadiantSystem.cc uses fixed sizing temperature when it should be using actual water temperature value, which is already available in the function, when calculating Cp of water [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/LowTempRadiantSystem.cc#L5574-L5600). The DataGlobals::HWInitConvTemp and DataGlobals::CWInitConvTemp are used for sizing or may be initialization only.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@Nigusse That appears to be a strange bug, but a bug nonetheless.  I'm not sure how that happened, but I will definitely fix this.  I've assigned it to myself now, and I'll keep you posted as to when it is ready for review.  Thanks!

**Comment by Nigusse** [comment]
closed via PR #6847
