### ISSUE TITLE
OutdoorAirUnit crashes when used with steam heating coil

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6843]
Found two issues when using ZoneHVAC:OutdoorAirUnit with steam heating coil: 

- [ ] Parent object steam flow rate autosizing problem. Steam flow rate  Steam mass flow rate  is calculated using liquid water density in the OutdoorAirUnit parent. Steam heating coils object volume flow rates are sized using saturated vapor. Conversion of vapor volume flow rate to mass flow rate should use vapor density instead of liquid density.  InitOutdoorAirUnit is using incorrect density [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/OutdoorAirUnit.cc#L1281-L1288).  
- [ ] ZoneHVAC:OutdoorAirUnit crashes when used with steam heating coil due to missing coil outlet node 
initialization.
- [ ] Also found coil cooling water flow rate sizing issue due to uninitialized variable CoilDesWaterDeltaT when the water cooling coil is part of ZoneHVAC equipment (e.g. ZoneHVAC:OutdoorAirUnit)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
When auto-sizing water cooling coil flow rate and the coil is part of ZoneHVAC:* equipment such as ZoneHVAC:OutdoorAirUnit, the variable CoilDesWaterDeltaT is undefined. As the results the water coil flow rate cannot be autosized.

**Comment by Nigusse** [comment]
Further testing showed that ZoneHVAC:OutdoorAirUnit crashes when steam heating coil is used instead of hot water heating coil due to missing to init steam coil outlet node.

**Comment by Myoldmopar** [comment]
No defect file?

**Comment by Myoldmopar** [comment]
Closed via #6848
