### ISSUE TITLE
Unit test failure in ReportSizingManager

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6849]
Issue overview
--------------
EnergyPlusFixture.HeatRecoveryHXOnMainBranch_SimHeatRecoveryTest fails in Windows debug run. `CoilDesWaterDeltaT` used without being initialized [here in ReportSizingManager](https://github.com/NREL/EnergyPlus/blob/2d029a9105e631b293db1cc4d3b6c052b5769b82/src/EnergyPlus/ReportSizingManager.cc#L3362).

Don't know if other unit tests will trip on this as well.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus https://github.com/NREL/EnergyPlus/commit/fb7543800d9a4f53560fdb3c9e4d9209c4fe1a1f

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
@mjwitte I have addressed this problem in issue #6843.

**Comment by mjwitte** [comment]
Closed via #6850.
