### ISSUE TITLE
Multispeed gas heating coil crashes in UpdateDataandReport when speeds are > 1

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6851]
Issue overview
--------------
Defect file 6599 was tested for 2 speed heating operation and caused a crash in UpdateDataandReport.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (DevSupport [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/6000s/6851))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
@mbadams5 I saw your name where this file crashed. Feel free to reassign. I don't know at this point if it's the defect file or code.

**Comment by jmarrec** [comment]
I upgraded the defect file to v9.4, and it now runs succesfully.
