### ISSUE TITLE
Connecting DIVA and EnergyPlus (Help wanted)

### ISSUE THREAD

**Issue by MMeshkinkiya** [NREL/EnergyPlus#6856]
Dear EnergyPlus developers team, 

I am working on solar irradiation availability on building facades inside urban canyons. I already performed a couple of analysis with DIVA and at this stage need to insert the obtained solar radiation from diva into building heat balance calculations within EnergyPlus.

My main issue is that I am not familiar with FORTRAN coding language since I mainly work with MATLAB. 

I would like to know if there are any previous experiences similar on this issue.
Ps: I am familiar with compiling EnergyPlus from the source code with minor modifications and running customized simulations.
 
I wonder if a look up table of solar radiant on each facade (or orientation) can help, assuming that we can replace it in the heat balance module prior to the CTF calculations. 
 
Many thanks in advance
Maryam

**Comment by mjwitte** [comment]
If you can get shading fractions from DIVA, or calculate them based on the incident solar, then you can use `SurfaceProperty:LocalEnvironment` " External Shading Fraction Schedule Name" to override the internal shading calculations. Or if you want to import shading fractions for the entire building, you can use `ShadowCalculation` "External Shading Calculation Method".

If you still want to modify EnergyPlus, it is in C++, see [Building EnergyPlus](https://github.com/NREL/EnergyPlus/wiki/BuildingEnergyPlus)**
