### ISSUE TITLE
AFN wind angles in the EIO are incorrect for advanced single-sided natural ventilation

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#6857]
Issue overview
--------------
The wind angles that are being output for advanced single-sided natural ventilation are the default angles (in increments of 30 degrees) rather than the higher-frequency angles for the feature (in increments of 10 degrees).

### Details
Some additional details for this issue (if relevant):
 - Version 8.9

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #6858
