### ISSUE TITLE
Crash if an interzone surface has one construction as conduction finite difference and the other not

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6859]
Issue overview
--------------
User file had an interzone ceiling where one construction was set to be ConductionFiniteDifference but the reverse construction was not.  This needs to be trapped and throw an error message.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v8.9.0 and v9.0 73281ffba3
 - Helpdesk ticket number 12889

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@lgu1234 Are you still planning on working on this?  If not, I can take it over as I am looking for things to work on.

**Comment by lgu1234** [comment]
@RKStrand No. Please take it over.

**Comment by RKStrand** [comment]
@lgu1234 Thanks, Gu.  I have change the assignee to me and will start working on it right away.

**Comment by RKStrand** [comment]
@mjwitte Is this still an issue?  I run the defect idf using the current develop and it runs to completion.  No crash and it seems that there is an error message that is being generated.  Or am I missing something?

**Comment by mjwitte** [comment]
@RKStrand If you can't reproduce it, then close it. If you want to figure out when it was fixed, check the blame on the error message? Hopefully the error message is relevant to this mismatch?

**Comment by RKStrand** [comment]
@mjwitte Here is what is produces:

   ** Warning ** An interior surface is defined as two surfaces with reverse constructions. The HeatTransferAlgorithm in both constructions should be same.
   **   ~~~   ** The HeatTransferAlgorithm of Surface: BLOCK1:DATATELCOM_CEILING_1_0_0, is CondFD - ConductionFiniteDifference
   **   ~~~   ** The HeatTransferAlgorithm of Surface: ROOF1:ZONE1_FLOOR_4_0_10000, is CTF - ConductionTransferFunction
   **   ~~~   ** The HeatTransferAlgorithm of Surface: ROOF1:ZONE1_FLOOR_4_0_10000, is assigned to CondFD - ConductionFiniteDifference. Simulation continues.
 
If you are okay with that, I'll close it.

**Comment by mjwitte** [comment]
@RKStrand Looks like this was addressed in #6867 but never cross-referenced here. Closing.
