### ISSUE TITLE
Redundant lines of code in Heating Water flow Sizing

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6866]
When mixed use of DataGlobals::HWInitConvTemp and DataGlobals::CWInitConvTemp in sizing calculation was corrected some codes in RequestSizing became redundant like [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ReportSizingManager.cc#L1306-L1328) and can be consolidated. There could also be similar redundancy in other places. This is just code cleanup.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
This is oudated, the file doesn't exist anymore
