### ISSUE TITLE
CoolingTower:VariableSpeed:Merkel calls recurring warnings incorrectly resulting in array bounds error

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6874]
Issue overview
--------------
User file crashes in debug build [here](https://github.com/NREL/EnergyPlus/blob/fee1ef0cf3e5a62b4436e44cbfbbed181dbc5282/src/EnergyPlus/UtilityRoutines.cc#L1854) because the `MsgIndex` argument in the call from [`CalcMerkelVariableSpeedTower`](https://github.com/NREL/EnergyPlus/blob/fee1ef0cf3e5a62b4436e44cbfbbed181dbc5282/src/EnergyPlus/CondenserLoopTowers.cc#L5763-L5766) is incorrect. The first time a recurring warning is called, the index should be zero, but the variable passed as the index has been incremeted in the block above. Same thing is happening in the next error block.  Didn't look elsewhere in the tower models for similar issues.

Wondering if `StoreRecurringErrorMessage` needs to protect itself and check if the index is greater than the size of `RecurringErrors` then throw an developer error and just skip the warning and continue so users can get results.

### Workaround
Use a different type of cooling tower.

### Details
Some additional details for this issue (if relevant):
 - Win64
 - Version of EnergyPlus 9.0.0-fee1ef0cf3
 - Helpdesk ticket 12923

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles, run with USA_KS_Olathe-Johnson.County.Executive.AP.724468_TMY3 weather
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
This one is set up correctly and has a variable for count and a variable for index. The developer just chose to print out the standard warnings only if count < 1. So anywhere the index is incremented, delete that line of code.

    if (SimpleTower(TowerNum).CoolingTowerAFRRFailedCount < 1) {
        ++SimpleTower(TowerNum).CoolingTowerAFRRFailedCount;
        ShowWarningError("CoolingTower:VariableSpeed \"" + SimpleTower(TowerNum).Name +
                                                 "\" - Cooling tower air flow rate ratio calculation failed ");
        ShowContinueError("...with conditions as Twb = " + OutputChar + ", Trange = " + OutputChar2 +
                                                  ", Tapproach = " + OutputChar3 + ", and water flow rate ratio = " + OutputChar4);
        ShowContinueError("...a solution could not be found within the valid range of air flow rate ratios");
        ShowContinueErrorTimeStamp(" ...Valid air flow rate ratio range = " + OutputChar5 + " to 1.0.");
        ShowContinueError("...Consider modifying the design approach or design range temperature for this tower.");
    } else {
        ShowRecurringWarningErrorAtEnd("CoolingTower:VariableSpeed \"" + SimpleTower(TowerNum).Name +
        "\" - Cooling tower air flow rate ratio calculation failed error continues.", SimpleTower(TowerNum).CoolingTowerAFRRFailedIndex);
    }

**Comment by rraustad** [comment]
Can't think of a way to protect ShowRecurringWarningErrorAtEnd since that function doesn't know if the developer inadvertently incremented the index and now that index is pointing to a different warning but IS within the range of RecurringErrors.size(). You could protect against passed index > RecurringErrors.size() and show a developer warning but you won't be able to protect against the incremented index where index <= RecurringErrors.size(). Maybe @jasondegraw has a thought on this with the new warnings. So for now it's just fixing the Merkel tower warnings.

**Comment by rraustad** [comment]
It's just those 2 places.

**Comment by rraustad** [comment]
Think I have a way to protect this.

    *************  ** Warning ** CoolingTower:VariableSpeed:Merkel "CNDW_LOOP COOLINGTOWER1" - Iteration limit exceeded calculating air flow ratio error continues. air flow ratio statistics follow.
    *************  **   ~~~   **   This error occurred 195 total times;
    *************  **   ~~~   **   during Warmup 0 times;
    *************  **   ~~~   **   during Sizing 0 times.
    *************  **   ~~~   **   Max=0.941704  Min=0.221405

**Comment by rraustad** [comment]
If you don't think your getting your message across, put a little redundancy in the message...

    ** Warning ** Processing Monthly Tabular Reports: EnergyConsumptionElectricityNaturalGasMonthly
    **   ~~~   ** ..Variable name=GAS:FACILITY not valid for this simulation.
    **   ~~~   ** ..Variables not valid for this simulation will have "[Invalid/Undefined]" in the Units Column of the Table Report.
    ** Warning ** Processing Monthly Tabular Reports: EnergyConsumptionElectricityNaturalGasMonthly
    **   ~~~   ** ..Variable name=GAS:FACILITY not valid for this simulation.
    ** Warning ** Processing Monthly Tabular Reports: EnergyConsumptionElectricityNaturalGasMonthly
    **   ~~~   ** ..Variable name=GAS:FACILITY not valid for this simulation.
    **   ~~~   ** ..i.e., Variable name=Meter:GAS:FACILITY not valid for this simulation.
    ** Warning ** Processing Monthly Tabular Reports: EnergyConsumptionElectricityNaturalGasMonthly
    **   ~~~   ** ..Variable name=GAS:FACILITY not valid for this simulation.
    **   ~~~   ** ..i.e., Variable name=Meter:GAS:FACILITY not valid for this simulation.

**Comment by rraustad** [comment]
Getting closer:

    ** Warning ** Developer error in ShowRecurringWarningAtEnd index. Please notify EnergyPlus support team. Message passed =  ** Warning ** CoolingTower:VariableSpeed:Merkel "CNDW_LOOP COOLINGTOWER1" - Iteration limit exceeded calculating air flow ratio error continues. air flow ratio statistics follow.

**Comment by rraustad** [comment]
See PR #6901.

**Comment by Myoldmopar** [comment]
Closed via #6901
