### ISSUE TITLE
Schedule:File accepts "Space" but not "Fixed" as a column separator

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#6880]
Issue overview
--------------
The IDD says that Schedule:File accepts "Fixed" as a column separator, but that isn't the case. It accepts Comma, Tab, Space, and Semicolon:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ScheduleManager.cc#L1692

### Details
Some additional details for this issue:
 - Version 8.9

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #7369
