### ISSUE TITLE
Incorrect minimum OA amount when the Minimum Limit Type is FixedMinimum 

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6881]
Issue overview
--------------
Incorrect minimum OA mass flow rate calculation when the OA controller Minimum Limit Type is  FixedMinimum. It uses the calculation method applicable for ProportionalMinimum. This was found while working on another bug issue #6796. 

### Details
 - V8.9 (or even older versions)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #6886
