### ISSUE TITLE
Stray test strings showing in EquipmentSummary Fans table for fan sizing peak day and time

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6899]
Issue overview
--------------
Noticed strange design day and time showing in EquipmentSummary report, Fans subtable:

![image](https://user-images.githubusercontent.com/4991075/43852375-ac989aac-9b02-11e8-8970-36f3989b07ac.png)

[This code](https://github.com/NREL/EnergyPlus/blob/388f60e37b098ffeb933af1a4f2ae94fb448697f/src/EnergyPlus/ReportSizingManager.cc#L423-L425) slipped in here in https://github.com/NREL/EnergyPlus/commit/f6453b19814547242c727bf037dd808f573f4159 and wasn't noticed while completing #6454.

It think it's showing up for non-autosized fans.  e.g. Fan:OnOff (use test file FurnaceWithDXSystem.idf) and Fan:ConstantVolume (1ZoneEvapCooler.idf). Fix could be as simple as deleting the offending lines and leaving the report cell blank.

No, there's more to it than that, see 5ZoneAirCooledConvCoef.idf. The PIU fans are autosized. They are displaying a valid design day name, but not a valid peak time.

![image](https://user-images.githubusercontent.com/4991075/43852919-2dcaaba0-9b04-11e8-829a-e6a4d961581d.png)

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v8.9.0 up through v9.0 https://github.com/NREL/EnergyPlus/commit/388f60e37b098ffeb933af1a4f2ae94fb448697f

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file noted above
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@Myoldmopar It would be good to clean this up before freeze.

**Comment by Myoldmopar** [comment]
I am doubtful to get anything done on here beyond maybe leaving it blank.  @mjwitte choosing the least bad option, would you rather have a blank cell, leave it with the test string, or put some other string in it.  I'll leave this open for proper fix up for the next release.

**Comment by mjwitte** [comment]
I think blank is the best fallback, but we probably want an open issue to see if  we can fill it with useful info.

**Comment by Myoldmopar** [comment]
During the release of E+ 9.0, this wasn't able to be addressed properly.  The "test" string was removed and the cell is now blank.  This isn't great, but it was better than nothing being done at all.

Before #6983:
![image](https://user-images.githubusercontent.com/849824/45979106-a500ba00-c013-11e8-9a0b-d3a61b82303a.png)

After #6983:
![image](https://user-images.githubusercontent.com/849824/45979118-af22b880-c013-11e8-8e08-86299c5154fb.png)

Proper fix:
**Actual design day name**

**Comment by jmarrec** [comment]
Fixed in #7034

**Comment by Myoldmopar** [comment]
Closed via #7034
