### ISSUE TITLE
Invalid key is set as default for Season input field in UtilityCost:Charge:Block object 

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#6904]
Issue overview
--------------
The season input field in UtilityCost:Charge:Block object does not have "Season" as one of its key choices but the default value is set to "Season".  Probably default should have been "Annual", instead. This is IDD defect.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@JasonGlazer Is the suggested change correct? @Myoldmopar I suppose this has to wait until after release now.

**Comment by JasonGlazer** [comment]
The default should be Annual.

**Comment by Myoldmopar** [comment]
Yeah, we should wait until after release unless something else pops up where a change is warranted, then this could sneak in along with it.

**Comment by Myoldmopar** [comment]
Closed via #6951
