### ISSUE TITLE
Incorrect severe error message in CondenserLoopTowers.cc

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#6910]
Issue overview
--------------
The following error message is incorrect/confusing to users. 

https://github.com/NREL/EnergyPlus/blob/7caa7447ba09ea0b7926718477b0a8719c4aafd2/src/EnergyPlus/CondenserLoopTowers.cc#L3245-L3252

The last line should be changed to match the check in the first line.

`TrimSigDigits(SimpleTowerInlet(TowerNum).DesInletAirWBTemp, 2) + " C.");`

### Details
Some additional details for this issue (if relevant):
 - Platform `Windows 10`
 - Version of EnergyPlus `8.9`
 - Unmethours link or helpdesk ticket number `NA`

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
It's even worse if you look at the untruncated error message, the following lines (last 2) make no sense:

```
   ** Severe  ** Error when autosizing the UA value for cooling tower = CT SINGLE SPEED. Design Loop Exit Temperature must be greater than 25.60 C when autosizing the tower UA.
   **   ~~~   ** The Design Loop Exit Temperature specified in Sizing:Plant object = CNDW LOOP
   **   ~~~   ** is less than or equal to the design inlet air wet-bulb temperature of 21.27 C.
   **   ~~~   ** It is recommended that the Design Loop Exit Temperature = 25.60 C plus the cooling tower design approach temperature = 3.90C.
   **   ~~~   ** If using HVACTemplate:Plant:ChilledWaterLoop, then check that input field Condenser Water Design Setpoint must be > 25.60 C if autosizing the cooling tower.
```
