### ISSUE TITLE
CoilSystem:Cooling:DX model with variable speed cooling coil shows poor RH control

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6920]
Issue overview
--------------
Defect file shows poor RH control with VS cooling coil. Used DXCoilSystemAuto example file and changed coil type to Coil:Cooling:DX:VariableSpeed. Humidistat is set at 50%.

![image](https://user-images.githubusercontent.com/5778156/44425782-dab90b80-a55a-11e8-8eb9-69a1fe930829.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (EnergyPlusDevSupport\DefectFiles\6000s\6920)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Modified code looks much better now...

![image](https://user-images.githubusercontent.com/5778156/44426515-d55cc080-a55c-11e8-946d-7b6a6d3bd6b1.png)

**Comment by Myoldmopar** [comment]
Closed via #6922
