### ISSUE TITLE
Using measured solar irradiation in EnergyPlus

### ISSUE THREAD

**Issue by MMeshkinkiya** [NREL/EnergyPlus#6921]
Dear EnergyPlus developer team,

I am wondering if anyone has any experience of using measured solar irradiation on vertical surfaces instead of default EnergyPlus calculations. 
I have a data set of measured solar irradiation on 90 degree tilts and would like to know whether it is possible to replace this data in EnergyPlus calculations.

Thank you in advance,
Maryam.

**Comment by Myoldmopar** [comment]
Hi @MMeshkinkiya.  The issues pages here on the Github repo are really more suited for when someone finds a defect or requests a new feature in EnergyPlus.  I would suggest closing this and instead asking the question over on the unmethours.com forum, where you will get not just developer responses, but user-to-user help as well.
