### ISSUE TITLE
WindowShadingControl Followup

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6923]
Issue overview
--------------
Followup items from #6421. See [comment here](https://github.com/NREL/EnergyPlus/pull/6421#issuecomment-415511303).

- [x] 1. Update new example file PurchAirWithDaylightingAndShadeControl.idf
- [x] 2. Investigate and correct glare control shade sequencing.
- [x] 3. DaylightingManager now needs clear_state to clear vectors created in CreateShadeDeploymentOrder. Unit test MapShadeDeploymentOrderToLoopNumber_Test runs fine by itself but crashes when all unit tests are ran together. *Addressed by https://github.com/NREL/EnergyPlus/commit/b60e442e74023642d56657167e74f3e51258b994*

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
@mjwitte thanks for getting this started

**Comment by JasonGlazer** [comment]
@mjwitte I'm not getting the clear_state() issue when I try to run the unit tests. Any suggestions?

**Comment by mjwitte** [comment]
@Myoldmopar Fixed it yesterday. https://github.com/NREL/EnergyPlus/commit/b60e442e74023642d56657167e74f3e51258b994

**Comment by Myoldmopar** [comment]
Closed via #6940
