### ISSUE TITLE
RunPeriod names in error messages

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#6937]
Issue overview
--------------
Many of the error messages for RunPeriod identify the object as `RunPeriod object #1` instead of using the RunPeriod name:
```
   ** Warning ** RunPeriod: object #1, start weekday (THURSDAY) does not match the start year (2019), corrected to TUESDAY.
```
Requiring that the RunPeriods have names would remove the need for filling in a name and would make it easier to identify the object that has the issue.

### Details
Some additional details for this issue (if relevant):
 - Platform: All
 - Version of EnergyPlus: 8.9+

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created: #7068

**Comment by Myoldmopar** [comment]
#7068 fixed some aspects of this by properly reporting a name for the run period.  This isn't closed yet though, as @jasondegraw really wants the name itself to be required.  This will require transition rules, so will be addressed separately from #7068.
