### ISSUE TITLE
Fans table End Use header incorrect

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#6949]
Issue overview
--------------
The `Equipment Summary` > `Fans` table `End Use` header is incorrect, it should be `End Use Subcategory` [here](https://github.com/NREL/EnergyPlus/blob/75a40dfc84745b3be24f5f782ed0a0b0eb126d5f/src/EnergyPlus/OutputReportPredefined.cc#L1877).

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (8.9)
 - Unmethours link or helpdesk ticket number (NA)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I see the table and column you mention:

![image](https://user-images.githubusercontent.com/5479063/48788996-4773ab80-ecec-11e8-88a0-6eb33de1b405.png)

And I agree that the general pattern would be "End Use Subcategory" (eg: https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/OutputReportPredefined.cc#L1747)
