### ISSUE TITLE
VRF Temperature Control outputs don't add up

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#6950]
Issue overview
--------------
Defect file has AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl:HR with several terminal units with no outdoor air.
Cooling Coil Total Cooling Rate *should* equal Zone VRF Air Terminal Total Cooling + Fan Electric Power but it does not.

For AirConditioner:VariableRefrigerantFlow, these do add up.  Have not tested AirConditioner:VariableRefrigerantFlow:FluidTemperatureControl.

Also, the I/O Ref description for VRF Heat Pump Total Cooling Rate is incorrect.
"This value should match the sum of the individual zone terminal unit output variables for ~Zone VRF Air Terminal Total Cooling Rate.~"
should be
""This value should match the sum of the individual zone terminal unit *cooling coil* output variables for *Cooling Coil Total Cooling Rate.*"

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v9.0.0-111432f7f1
 - Helpdesk ticket number 12357

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Closed via #7449.
