### ISSUE TITLE
Using EMS with Construction:ComplexFenestrationState doesn't yield reliable results

### ISSUE THREAD

**Issue by tobiasskov** [NREL/EnergyPlus#6954]
Issue overview
--------------
Setting up an EMS that switches between two Construction:ComplexFenestrationState, in order to model dynamic solar shading (drawing inspiration from the example file ThermochromicWindow.idf). 

To test this approach an EMS that switches between two identical con...:CFS are compared to a model that a assigns one con...:CFS directly to the fenestration surface. These two idfs do not yield the same results as they should: 
[CFS1.zip](https://github.com/NREL/EnergyPlus/files/2374424/CFS1.zip)

[CFS2.zip](https://github.com/NREL/EnergyPlus/files/2374425/CFS2.zip)

(Running the test twice, with two different kinds of con...:CFS)

When running the test with the Simple window construction the two idfs do in fact yield the same result as they should.

[Simple.zip](https://github.com/NREL/EnergyPlus/files/2374434/Simple.zip)

### Details
Some additional details for this issue (if relevant):
 - Win64
 - Version of EnergyPlus - 8.9.0
 - Unmethours [33169](https://unmethours.com/question/33169/discrepancies-when-using-ems-to-assign-constructioncomplexfenestrationstate-compared-to-assigning-by-construction-name/)
 - Helpdesk ticket 15357

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added 
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #7981
