### ISSUE TITLE
ZoneHVAC:EquipmentList UniformLoad issues with ZoneHVAC equipment

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#6977]
When using `UniformLoad` as the `ZoneHVAC:EquipmentList`'s Load Distribution Scheme, we get unexpected results with `ZoneHVAC:Baseboard:Convective:Electric` objects whereas `AirLoopHVAC:UnitarySystem` objects yield expected results.

Scenarios run with 1 or 3 systems, each with `UniformLoad` and `SequentialLoad`. Table below shows annual heating results for electric baseboard and electric furnace runs.

Scenario | Elec Baseboard Heating Energy [GJ] | Elec Furnace Heating+Fan Energy [GJ]
-- | -- | --
x1-SequentialLoad | 41 | 41
x1-UniformLoad | 41 | 41
x3-SequentialLoad | 41 | 41
x3-UniformLoad | **44** | 41

Note the outlier above. Furthermore, the 3 baseboard objects yeild different heating energy uses:

Object Name | Variable | Value
-- | -- | --
RES BB LIVING CONVECTIVE ELECTRIC | Baseboard Total Heating Energy | 26447250081.07
RES BB LIVING CONVECTIVE ELECTRIC 1 | Baseboard Total Heating Energy | 8815740061.34
RES BB LIVING CONVECTIVE ELECTRIC 2 | Baseboard Total Heating Energy | 8815740061.34

Tested with E+ 8.9 and 9.0. Will upload two IDFs shortly for reproducing.

**Comment by shorowit** [comment]
Electric baseboard IDFs attached:
[x3-SequentialLoad.idf.txt](https://github.com/NREL/EnergyPlus/files/2402874/x3-SequentialLoad.idf.txt)
[x3-UniformLoad.idf.txt](https://github.com/NREL/EnergyPlus/files/2402873/x3-UniformLoad.idf.txt)

**Comment by shorowit** [comment]
If it's not already obvious, it appears that the first piece of ZoneHVAC equipment consumes 3x times the energy as the 2nd/3rd equipment. In other words, it sees 100% of the load instead of 33% of the load, while the 2nd and 3rd equipment see 33% of the load -- thus resulting in over-conditioning the zone.

**Comment by mjwitte** [comment]
@shorowit Have you tested any other types of ZoneHVAC equipment to see if UniformLoad works correctly?

**Comment by shorowit** [comment]
Here is my full set of test results:
- ZoneHVAC:Baseboard:Convective:Water: BAD
- ZoneHVAC:Baseboard:Convective:Electric: BAD
- ZoneHVAC:PackagedTerminalAirConditioner: BAD
- AirLoopHVAC:UnitarySystem (zone equip; no airloop): GOOD
- ZoneHVAC:AirDistributionUnit (airloop): GOOD

**Comment by shorowit** [comment]
And I can upload files for any of the above if you want them, Just let me know.

**Comment by Myoldmopar** [comment]
Closed via #7025
