### ISSUE TITLE
ZoneHVAC:EnergyRecoveryVentilator sizing issue when using Fan:SystemModel

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#6987]
Issue overview
--------------
The energy recovery ventilator sizes the fan to be able to meet excess air flow by calling the fan model during sizing. The existing code does not call a fan with index = 0 which can happen with the Fan:SystemModel. Odd sizing results were noticed previously and are likely due to unnecessary (fans are required) protection of the fan index.

        if (StandAloneERV(StandAloneERVNum).SupplyAirFanIndex > 0) {
            if (!(StandAloneERV(StandAloneERVNum).SupplyAirFanType_Num == DataHVACGlobals::FanType_SystemModelObject)) {
                SimulateFanComponents(StandAloneERV(StandAloneERVNum).SupplyAirFanName, true, StandAloneERV(StandAloneERVNum).SupplyAirFanIndex);
            } else {
                HVACFan::fanObjs[StandAloneERV(StandAloneERVNum).SupplyAirFanIndex]->simulate(_, ZoneCompTurnFansOn, ZoneCompTurnFansOff, _);
            }
        }
        if (StandAloneERV(StandAloneERVNum).ExhaustAirFanIndex > 0) {
            if (!(StandAloneERV(StandAloneERVNum).ExhaustAirFanType_Num == DataHVACGlobals::FanType_SystemModelObject)) {
                SimulateFanComponents(StandAloneERV(StandAloneERVNum).ExhaustAirFanName, true, StandAloneERV(StandAloneERVNum).ExhaustAirFanIndex);
            } else {
                HVACFan::fanObjs[StandAloneERV(StandAloneERVNum).ExhaustAirFanIndex]->simulate(_, ZoneCompTurnFansOn, ZoneCompTurnFansOff, _);
            }
        }

Recent differences in fan sizing for the ERV model:

![standaloneervsizing](https://user-images.githubusercontent.com/5778156/46032045-97f1d280-c0c8-11e8-9f8d-9a10fa416c7b.jpg)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (example file: HVACStandAloneERV_Economizer.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
PR #6989 also cleans up other HVACUnitarySystem related items not noticed during the scramble to get out the release.

**Comment by Myoldmopar** [comment]
Closed via #6989
