### ISSUE TITLE
Add an entry to IDD,but **is not a valid Object Type.

### ISSUE THREAD

**Issue by lxk1993** [NREL/EnergyPlus#6999]
Issue overview
--------------
Add an entry to IDD,but **is not a valid Object Type.

### Details
![1](https://user-images.githubusercontent.com/42338103/46590013-8a821280-cae2-11e8-8fa7-0efc91e21a08.jpg)
![2](https://user-images.githubusercontent.com/42338103/46590014-9077f380-cae2-11e8-8236-ace52b3b2a96.jpg)

**Comment by mbadams5** [comment]
@lxk1993 Are you adding a new object to the EnergyPlus source code? If so, you need to add your new IDD object to the [Energy+.idd.in file](https://github.com/NREL/EnergyPlus/blob/develop/idd/Energy+.idd.in). Then when you compile EnergyPlus, it will translate the new object into the epJSON Schema and compile it into the final executable. If you have done all this and you are getting the error referenced above then this is a bug and I'd like to know more information.

If you are adding this object to the IDD file distributed with the release version of EnergyPlus then you will absolutely get the above error message. The epJSON Schema is compiled into the executable and neither the IDD nor epJSON Schema distributed with the release version of EnergyPlus are read by EnergyPlus during simulation (they are for informational purposes only).

**Comment by jmarrec** [comment]
@lxk1993 Can we close this then?
