### ISSUE TITLE
Feature request: get CI bot to compute and output a md5sums.txt

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7000]
Issue overview
--------------

Currently, each time we update the OpenStudio CMakeLists.txt to a new E+ version, we have to download at least 3 large compressed files (one for windows, mac, and linux, and possibly one for windows i386 if the .zip version comes back) just to compute md5sum. Plus, unless you're smart about it, next time you actually build OpenStudio, it'll also redownload that version...

It'd be great if the CI bot could compute them to put them in a md5sums.txt on the release itself, so we don't have to do this. I'll avoid transferring 300 MB of unnecessary files, and won't skew the download counts too much.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
This is now happening, but I'm having trouble tracking down which PR added this feature. Closing this, but the interested code detective can feel free to tag the PR here for reference.

**Comment by Myoldmopar** [comment]
CI actually isn't building it, @jmarrec simply builds it and posts it.  To set this up, I think we need to get all the Github Action packaging workflows into one yaml file so that you can define a post-run job when they are all completed that will grab all the finished package files, download them, md5 them, and then create a hash file and post it to the release.  

Honestly it's probably sufficient to just create a file in `scripts/dev` that will do that whole process and create the file (maybe even post it?) given the Git tag name as an argument.

**Comment by mitchute** [comment]
Ah, thanks for pointing that out. I'll reopen the issue.

**Comment by jmarrec** [comment]
I'm fine if people want to call me "CI bot" and just close this issue.

I don't think computing md5sum is warranting complicated changes to the workflows: we've been over this: putting everything into the same yaml is a bad idea (I know: I tried and changed my mind).

I would however consider adding to each workflow yaml a step that computes and output its (to the GHA console, slack notification to a channel, or even the release notes directly). That way that I wouldn't have to download a couple of GB of data just to compute it (it seems like a solid waste of energy to me...) and post it on the release page. Thoughts?

**Comment by Myoldmopar** [comment]
This is done now though, right?

**Comment by jmarrec** [comment]
Yeah I added compute_checksums workflow, which is a manual dispatch one but serves the purpose
