### ISSUE TITLE
IDF updater 8.9->9.0 fails to convert a working 8.9 IDF

### ISSUE THREAD

**Issue by smnrd** [NREL/EnergyPlus#7004]
Issue overview
--------------
IDF updater 8.9->9.0 hangs indefinitely with [this IDF file](https://github.com/NREL/EnergyPlus/files/2465874/N4.idf.txt). The  [VCpErr file](https://github.com/NREL/EnergyPlus/files/2466011/N4.VCpErr.txt) only shows obsolete object warnings for AirTerminal:SingleDuct:Uncontrolled, but no error.
I tried running the Transition executable from CLI too, same result.

### Details
Some additional details for this issue (if relevant):
 - Platform : Windows 10
 - Version of EnergyPlus : 9.0.1-bb7ca4f0da

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@smnrichard It isn't hanging, but it's taking a very long time to find the zone numbers for all of the fenestration surfaces which have window shading controls assigned in order to accomplish the transition for WindowShadingControl.
@Myoldmopar I will work on improving this. This file is taking hours to complete transition.

**Comment by Myoldmopar** [comment]
In the meantime is it possible to extract out the relevant portions of the IDF and transition separately, or break it into individual parts?

Also, @smnrichard if this is a "one-off" issue where your specific IDF file happens to be very intensive and you won't be having to do this often, I'd be happy to let this run on my machine and send you back the one-time updated file.

Thanks @mjwitte for working on it, and thanks @smnrichard for notifying us!

**Comment by smnrd** [comment]
Thanks for the quick reply.
I let it run about an hour, since transition for previous versions took about 10min to complete, I figured it might have fallen into an infinite loop.
@Myoldmopar , this IDF is not particularly complex with our use of Energy+ ("as built" whole building simulation with design builder), but waiting longer for the transition to complete on my machine is not an issue, thanks for offering to help.
