### ISSUE TITLE
Pump:VariableSpeed I/O document mistakes?

### ISSUE THREAD

**Issue by xwanguk** [NREL/EnergyPlus#7006]
Issue overview
--------------
For the fields after the VFD Control Type, two RPM schedules (Minimum and Maximum) should be applicable to VFD Control Type = ManualControl, not the other way round (I/O document shows both of them are still applicable to VFD Control Type = PressureSetPointControl).

Engineering Reference document indirectly proves this.

### Details

The correct texts should be:

1.39.1.1.22 Field: Minimum RPM Schedule
For VFD Control Type = ManualControl, this field defines the minimum allowable RPM, or
the lower bound of pump speed to use when determining the required pump speed. For VFD Control Type = PressureSetPointControl, this field is not interpreted. The value of the schedule is RPM.

1.39.1.1.23 Field: Maximum RPM Schedule
For VFD Control Type = ManualControl, this field defines the maximum allowable RPM, or
the lower bound of pump speed to use when determining the required pump speed. For VFD Control Type = PressureSetPointControl, this field is not interpreted. The value of the schedule is RPM.

**Comment by mjwitte** [comment]
Actually, the I/O Ref is correct as-is. Minimum RPM Schedule and Maximum RPM Schedule are used with PressureSetpointControl to specify limits on the automatic control.
See [code here](https://github.com/NREL/EnergyPlus/blob/5358d3eb87d1376b3484e1a38ade8274b01f0027/src/EnergyPlus/Pumps.cc#L458-L467).
