### ISSUE TITLE
Transition IDF Version Updater Bug in v9.0

### ISSUE THREAD

**Issue by ff-kschlansker** [NREL/EnergyPlus#7010]
There appears to be an issue introduced between 8.9.0 and 9.0.1 having to do with updating IDFs to newer versions.  With 8.9.0 I had no problem updating IDF files.  With 9.0.1 I get the following error on every IDF I attempt to update:

```
At line 787 of file /Users/kbenne/ci_runs/EnergyPlus-v9.0.1-x86_64-clang/src/Transition/VCompareGlobalRoutines.f90
Fortran runtime error: Bad integer for item 1 in list input
```

The full output from the Transition program is as follows:
```
 Transition Starting
 Conversion 7.2 => 8.0
 Processing Old IDD -- V7-2-0-Energy+.idd
 Processing New IDD -- V8-0-0-Energy+.idd
 Will create new full IDFs
 Will create new IDF lines with units where applicable
 Will create new IDF lines leaving blank incoming fields as blank (no default fill)
 F
 Processing IDF -- /Users/kschlansker/work/ff/stack-validation/idf-conversion/test.ep90/idfs/RefBldgOutPatientPre1980_v1.4_7.2_1A_USA_FL_MIAMI.idf
At line 787 of file /Users/kbenne/ci_runs/EnergyPlus-v9.0.1-x86_64-clang/src/Transition/VCompareGlobalRoutines.f90
Fortran runtime error: Bad integer for item 1 in list input
```

**Comment by mjwitte** [comment]
@ff-kschlansker I see the problem. There is a shared function that is used across all transition versions which was updated for v9.0 without recognizing that it will break earlier transition versions. 

### Workaround
Copy all of the older transition exe's from the v8.9.0 install into the v9.0.1 IDFVersionUpdater folder.

**Comment by ff-kschlansker** [comment]
Thank you @mjwitte - using the the EP 9.0 binaries for only V8-9-0 ==> V9-0-0, and EP 8.0 binaries for everything <V9-0-0 appears to work.

**Comment by Myoldmopar** [comment]
Closed via #7007

**Comment by jasminaburek** [comment]
I got IDF updater working without errors but the EnergyPlus run shows severe error
Program Version,EnergyPlus, Version 9.0.1-bb7ca4f0da, YMD=2019.03.06 09:54,
   ** Severe  ** <root>[WaterHeater:Mixed][SWH Laundry][off_cycle_parasitic_fuel_type] - "Natural Gas" - Failed to match against any enum values.
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=<root>[WaterHeater:Mixed][SWH Laundry][off_cycle_parasitic_fuel_type] - "Natural Gas" - Failed to match against any enum values.
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.35sec

**Comment by mjwitte** [comment]
Prior to v8.9, EnergyPlus was rather forgiving, allowing various synonyms that are not in the official key choice list in the idd. As of v8.9 and later, the input processor requires that key choice fields match one of the choices listed in the IDD. On the do-list is updating the transition tool to fix all of these (see #6601). In this case, change "Natural Gas" to "NaturalGas" and it should run.

**Comment by jasminaburek** [comment]
> Prior to v8.9, EnergyPlus was rather forgiving, allowing various synonyms that are not in the official key choice list in the idd. As of v8.9 and later, the input processor requires that key choice fields match one of the choices listed in the IDD. On the do-list is updating the transition tool to fix all of these (see #6601). In this case, change "Natural Gas" to "NaturalGas" and it should run.

I am looking under #6601 and can't find the fix for the next error "Object required to validate 'required' properties"

Program Version,EnergyPlus, Version 9.0.1-bb7ca4f0da, YMD=2019.03.06 10:34,
   ** Severe  ** <root> - Object required to validate 'required' properties.
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=1
   ..... Last severe error=<root> - Object required to validate 'required' properties.
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 1 Severe Errors; Elapsed Time=00hr 00min  0.17sec

**Comment by mbadams5** [comment]
@jasminaburek Do you have the IDF file which generated that error message? If you can share it, can you add it here or send it to the EnergyPlus Helpdesk?

**Comment by jasminaburek** [comment]
> @jasminaburek Do you have the IDF file which generated that error message? If you can share it, can you add it here or send it to the EnergyPlus Helpdesk?
Yes. I have attached the 2 files I tested. Thank you for
your help.
Jasmina
[EnergyPlus files.zip](https://github.com/NREL/EnergyPlus/files/2941654/EnergyPlus.files.zip)

**Comment by mbadams5** [comment]
@jasminaburek I found the issue for the "Object required to validate 'required' properties." error. The IDF file is encoded as UTF-8 with BOM, which is [Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark). If you convert it to just normal UTF-8 then it processes as expected. I am opening a new pull request to add BOM support.

**Comment by jasminaburek** [comment]
Yes. That fixed some of the errors. But there are some other errors. Should I ignore these?
More importantly, I am not able to import the IDF file into OpenStudio. I receive this error. I attached my files again.

[ASHRAE90.1_Hospital_STD2016_SanDiego.zip](https://github.com/NREL/EnergyPlus/files/2942996/ASHRAE90.1_Hospital_STD2016_SanDiego.zip)
[ASHRAE90.1_Hospital_STD2010_Atlanta.zip](https://github.com/NREL/EnergyPlus/files/2942997/ASHRAE90.1_Hospital_STD2010_Atlanta.zip)
Error in OpenStudio:
The collection is INVALID at strictness level 'Draft', because of the errors:
Field      level data error of type DataType          .
Error is in an object of type 'GlobalGeometryRules', named '', in field 0.
Additional information about the error type: field-level data is of an incorrect type.

**Comment by lingqi-su** [comment]
> Yes. That fixed some of the errors. But there are some other errors. Should I ignore these?
> More importantly, I am not able to import the IDF file into OpenStudio. I receive this error. I attached my files again.
> 
> [ASHRAE90.1_Hospital_STD2016_SanDiego.zip](https://github.com/NREL/EnergyPlus/files/2942996/ASHRAE90.1_Hospital_STD2016_SanDiego.zip)
> [ASHRAE90.1_Hospital_STD2010_Atlanta.zip](https://github.com/NREL/EnergyPlus/files/2942997/ASHRAE90.1_Hospital_STD2010_Atlanta.zip)
> Error in OpenStudio:
> The collection is INVALID at strictness level 'Draft', because of the errors:
> Field level data error of type DataType .
> Error is in an object of type 'GlobalGeometryRules', named '', in field 0.
> Additional information about the error type: field-level data is of an incorrect type.

Have you found the solution for this error? I would like to import the ASHRAE prototype large office building model into openstudio. After updating the idf files, I got the same error as yours.

```
The collection is INVALID at strictness level 'Draft', because of the errors:
Field      level data error of type DataType          .
Error is in an object of type 'GlobalGeometryRules', named '', in field 0.
Additional information about the error type: field-level data is of an incorrect type.
```

Here is the updated file.

[ASHRAE90.1_OfficeLarge_STD2016_NewYork.idf.zip](https://github.com/NREL/EnergyPlus/files/3621210/ASHRAE90.1_OfficeLarge_STD2016_NewYork.idf.zip)

**Comment by jasminaburek** [comment]
I have not found the solution yet.

**Comment by mjwitte** [comment]
The problem with the `GlobalGeometryRules` object is that the prototype files use old synonyms which EnergyPlus accepts but OpenStudio does not allow. These *should* be cleaned up by transition, but are not currently (along with other synonyms, see #6601 ). Here's the object in these files:
```
  GlobalGeometryRules,
    ULC,                     !- Starting Vertex Position
    CCW,                     !- Vertex Entry Direction
    Relative;                !- Coordinate System
```
Here is the IDD definition for the first two fields:
```
GlobalGeometryRules,
      \memo Specifies the geometric rules used to describe the input of surface vertices and
      \memo daylighting reference points.
      \required-object
      \unique-object
  A1, \field Starting Vertex Position
      \required-field
      \note Specified as entry for a 4 sided surface/rectangle
      \note Surfaces are specified as viewed from outside the surface
      \note Shading surfaces as viewed from behind.  (towards what they are shading)
      \type choice
      \key UpperLeftCorner
      \key LowerLeftCorner
      \key UpperRightCorner
      \key LowerRightCorner
  A2, \field Vertex Entry Direction
      \required-field
      \type choice
      \key Counterclockwise
      \key Clockwise
```
So, replace the geometry object with this, and the OpenStudio import error regarding `GlobalGeometryRules` should be fixed:
```
  GlobalGeometryRules,
    UpperLeftCorner,                     !- Starting Vertex Position
    Counterclockwise,                     !- Vertex Entry Direction
    Relative;                !- Coordinate System
```
