### ISSUE TITLE
Fan:SystemModel is highlighted as not allowed on branch when using IDF Editor

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7013]
Issue overview
--------------
The IDF Editor shows that the Fan:SystemModel is not allowed on a branch although the simulation completes without error. See UnmetHours [ticket](https://unmethours.com/question/34887/how-to-change-idd-file-to-allow-fansystemmodel-on-branch/?comment=34919#post-id-34919)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
It was also missing some other applicable reference tags. Fixed in #6951

**Comment by Myoldmopar** [comment]
Closed via #6951

**Comment by mldichter** [comment]
Do you know if this will also fix this error in the next version of openstudio?

https://unmethours.com/question/34887/how-to-change-idd-file-to-allow-fansystemmodel-on-branch/

There is a problem with measures assigning a string to an idf object's field if openstudio considers the string invalid for that field. For instance, an openstudio measure won't allow a reference to an object by name if that object does not currently exist in the idf file. See the link below for an example.

https://unmethours.com/question/32993/force-measure-to-assign-string-to-field-whether-or-not-the-string-is-valid-or-invalid/

**Comment by mjwitte** [comment]
EnergyPlus IDD changes do not normally propogate into OpenStudio until after the next official EnergyPlus release, which would be v9.1 planned for March 2019.

**Comment by Lefort-Antoine** [comment]
I detect a similar error.
reference "FansCVandVAV" is missing in idd (9.0.1) for object Fan:SystemModel.
