### ISSUE TITLE
Degree sign not showing in doc PDF, standardize around siunitx

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7018]
Issue overview
--------------

Package `siunitx` is already included, but `\textdegree` is used through the documentation, while `textcomp the package package that provides this `\textdegree` command` isn't actually used, so you end up with missing degree signs in the PDF.

Eg:
![image](https://user-images.githubusercontent.com/5479063/47162207-d2c7de80-d2f3-11e8-8327-f242436ddd14.png)

```
\paragraph{Field: Full Load Temperature Rise}\label{field-full-load-temperature-rise}

This numeric field defines the temperature rise of the windings above the ambient temperature, when the transformer is loaded at its nameplate rating. For liquid-immersed distribution transformers, the full load temperature rise usually takes the value of 65 \textdegreeC. For dry-type transformers, the temperature rise usually takes three optional values: 80, 115 and 150 \textdegreeC. This field accepts any value between the minimum (50 \textdegreeC) and the maximum (180 \textdegreeC). The default is 150 \textdegreeC.
```

We should standardize around the `siunitx` package, and I'll also implement a `\farenheit` unit.

**Edit:** In fact, to encourage/ensure usage of `siunitx`, I think we should upgrade the entire documentation to use `siunitx` rather than rely on a mixture of things (eg: "5C, 5 C, 5 °C (not sure the ° will render properly), `5$^\circ$`, etc)). This could be automated to some extent with a scripting language and regexes.

In the process, we'll define the appropriate units we need, including IP units.

### Details
Some additional details for this issue (if relevant):
 - Platform: Any
 - Version of EnergyPlus: 9.0.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
Should be spelled "fahrenheit" :-)

**Comment by jmarrec** [comment]
oopsy, thanks for the catch... +1:
