### ISSUE TITLE
SetpointsNotMetWithTemperaturesMonthly table report all zeros unless the corresponding output:variable objects are added to the idf

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7019]
Issue overview
--------------
User noted that output for the SetpointsNotMetWithTemperaturesMonthly and ComfortReportSimple55Monthly were all zero, but the summary at the end of ABUPS was not.

### Workaround
Add the corresponding output:variable objects (any reporting frequency will work).
```
Output:Variable,*,Zone Thermal Comfort ASHRAE 55 Simple Model Summer Clothes Not Comfortable Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Thermal Comfort ASHRAE 55 Simple Model Winter Clothes Not Comfortable Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Thermal Comfort ASHRAE 55 Simple Model Summer or Winter Clothes Not Comfortable Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Heating Setpoint Not Met Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Heating Setpoint Not Met While Occupied Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Cooling Setpoint Not Met Time,annual; !- Zone Sum [hr]
Output:Variable,*,Zone Cooling Setpoint Not Met While Occupied Time,annual; !- Zone Sum [hr]
```

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus 9.0.1
 - Helpdesk ticket number 13082.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Seems like adding these variables was planned for already: https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/InputProcessing/InputProcessor.cc#L1585:L1597

Except none of these ever get actually requested, so KeyCount [here](https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/OutputReportTabular.cc#L1135) ends up being zero and the num of tables isn't initialized (and therefore in WriteMonthlyTables [here](https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/OutputReportTabular.cc#L6709), `MonthlyInput(1).numTables` is zero)

**Comment by mjwitte** [comment]
It used to work just fine, not sure when it stopped working.

**Comment by mjwitte** [comment]
So, can you track down why `GetVariableKeyCountandType` is not finding these? Are they present in the master variable list at that point? These output variables are set up in `ThermalComfort::InitThermalComfort` - is that executing before `InitializeTabularMonthly`?

**Comment by jmarrec** [comment]
`ThermalComfort::InitThermalComfort` does execute before `InitializeTabularMonthly`

In `GetVariableKeyCountandType` is does find the variable type https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/OutputProcessor.cc#L8085

But when it reaches `// Search real Variables Next`, there are only 9 Real Variables defined:

```
   8146	    } else if (varType == VarType_Real) {
   8147	        // Search real Variables Next
-> 8148	        for (Loop = 1; Loop <= NumOfRVariable; ++Loop) {
   8149	            if (RVariableTypes(Loop).VarNameOnlyUC == varNameUpper) {
   8150	                Found = true;
   8151	                varType = VarType_Real;
(lldb) p NumOfRVariable
(int) $8 = 9
(lldb) p RVariableTypes(1).VarNameOnlyUC
(std::__cxx11::string) $9 = "EXTERIOR LIGHTS ELECTRIC ENERGY"
(lldb) p RVariableTypes(2).VarNameOnlyUC
(std::__cxx11::string) $10 = "ZONE AIR SYSTEM SENSIBLE HEATING ENERGY"
(lldb) p RVariableTypes(3).VarNameOnlyUC
(std::__cxx11::string) $11 = "ZONE AIR SYSTEM SENSIBLE COOLING ENERGY"
(lldb) p RVariableTypes(4).VarNameOnlyUC
(std::__cxx11::string) $12 = "FACILITY TOTAL PURCHASED ELECTRIC ENERGY"
(lldb) p RVariableTypes(5).VarNameOnlyUC
(std::__cxx11::string) $13 = "FACILITY TOTAL SURPLUS ELECTRIC ENERGY"
(lldb) p RVariableTypes(6).VarNameOnlyUC
(std::__cxx11::string) $14 = "FACILITY NET PURCHASED ELECTRIC ENERGY"
(lldb) p RVariableTypes(7).VarNameOnlyUC
(std::__cxx11::string) $15 = "ENVIRONMENTAL IMPACT TOTAL N2O EMISSIONS CARBON EQUIVALENT MASS"
(lldb) p RVariableTypes(8).VarNameOnlyUC
(std::__cxx11::string) $16 = "ENVIRONMENTAL IMPACT TOTAL CH4 EMISSIONS CARBON EQUIVALENT MASS"
(lldb) p RVariableTypes(9).VarNameOnlyUC
(std::__cxx11::string) $17 = "ENVIRONMENTAL IMPACT TOTAL CO2 EMISSIONS CARBON EQUIVALENT MASS"

```

**Comment by mjwitte** [comment]
More information, starting with 5ZoneAirCooled with no output:variable or output:meter objects, and requesting "AllMonthly" reports.
1. This reporting was working properly in v8.8.
2. In v8.9 and v9.0, requesting "AllMonthly" produces some of the monthly reports, but not SetpointsNotMetWithTemperaturesMonthly
3. Add SetpointsNotMetWithTemperaturesMonthly in v8.9 and v9.0 and still no report - lots of warnings like this:
```
   ** Warning ** Processing Monthly Tabular Reports: SetpointsNotMetWithTemperaturesMonthly
   **   ~~~   ** ..Variable name=ZONE HEATING SETPOINT NOT MET WHILE OCCUPIED TIME not valid for this simulation.
```
So, why does the original defect file produce this report (albeit with zeros) and 5ZoneAirCooled does not?
[5ZoneAirCooled-WithMonthlyReports-v9.0-AddSetpointsNotMetWithTemperaturesMonthly.idf.txt](https://github.com/NREL/EnergyPlus/files/2511071/5ZoneAirCooled-WithMonthlyReports-v9.0-AddSetpointsNotMetWithTemperaturesMonthly.idf.txt)

**Comment by jmarrec** [comment]
I found the problem with the help of @mbadams5, it's a problem of DataOutputs::FindItemInVariableList that fails with different casing. I'm trying to write a proper unit test now.

**Comment by JasonGlazer** [comment]
@jmarrec I think this is exactly the same issue as #6863 so let me know when you get it fixed and I will test if it fixes that issue also.

**Comment by jmarrec** [comment]
@jasonglazer see PR #7031 referenced above
