### ISSUE TITLE
ZoneInfiltration Airflow Stats Nominal section displaying wrong units

### ISSUE THREAD

**Issue by luisclv** [NREL/EnergyPlus#7029]
Issue overview
--------------

After changing the OutputControl:Table:Style object Unit Conversion to _InchPound_, the _ZoneInfiltration Airflow Stats Nominal_ included in the _AllSummary_ report displays some columns in SI units. The values displayed in the columns are the correct entered values in SI units. The fix will be complete when this report does the conversion for this columns.

![image](https://user-images.githubusercontent.com/26468227/47382556-307b7280-d6c8-11e8-9113-c057c3b97427.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of EnergyPlus (if using an intermediate build, include SHA): Energyplus 8.9.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added : `testfiles/5ZoneAutoDXVAV.idf`
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
If you take `5ZoneAutoDXVAV.idf` which has already AllSumary and InchPound reporting, you'll find a few more missing conversions, such as  Zone Internal Gains Nominal and  People Internal Gains Nominal still show `person/m2` (while `ft2/person` works fine)

![image](https://user-images.githubusercontent.com/5479063/47492956-75311600-d84e-11e8-8b77-5ca92c81cd8f.png)

**Comment by Myoldmopar** [comment]
Closed via #7032
