### ISSUE TITLE
Heat exchanger effectiveness applied twice to stratified tanks

### ISSUE THREAD

**Issue by nmerket** [NREL/EnergyPlus#7035]
Issue overview
--------------
For both the source and use side, the heat exchanger effectiveness is [applied to the flow rates](https://github.com/NREL/EnergyPlus/blob/c1a8cbbf47edf480e3c9e680a32d310591a11b3c/src/EnergyPlus/WaterThermalTanks.cc#L8464-L8465) in `CalcNodeMassFlows` and then [saved onto the tank node for the inlets](https://github.com/NREL/EnergyPlus/blob/c1a8cbbf47edf480e3c9e680a32d310591a11b3c/src/EnergyPlus/WaterThermalTanks.cc#L8519-L8520). Back in `CalcWaterThermalTankStratified` they are [applied again](https://github.com/NREL/EnergyPlus/blob/c1a8cbbf47edf480e3c9e680a32d310591a11b3c/src/EnergyPlus/WaterThermalTanks.cc#L8197-L8198) which shouldn't be done.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: `develop` branch, sha `c1a8cbbf47edf480e3c9e680a32d310591a11b3c`

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

@jmaguire1

**Comment by nmerket** [comment]
Also, the on- and off- cycle parasitic fraction to tank is being applied twice.

- Off cycle fraction [here](https://github.com/NREL/EnergyPlus/blob/48cebab627f272efb7d370b4e8ab747858b5b503/src/EnergyPlus/WaterThermalTanks.cc#L6032) and [here](https://github.com/NREL/EnergyPlus/blob/48cebab627f272efb7d370b4e8ab747858b5b503/src/EnergyPlus/WaterThermalTanks.cc#L8259)
- On cycle fraction [here](https://github.com/NREL/EnergyPlus/blob/48cebab627f272efb7d370b4e8ab747858b5b503/src/EnergyPlus/WaterThermalTanks.cc#L6036) and [here](https://github.com/NREL/EnergyPlus/blob/48cebab627f272efb7d370b4e8ab747858b5b503/src/EnergyPlus/WaterThermalTanks.cc#L8246)

**Comment by Myoldmopar** [comment]
Closed via #7146
