### ISSUE TITLE
Suspect calculations in ElectricEquipment:ITE:AirCooled when Air Flow Calculation Method = FlowFromSystem

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7041]
Issue overview
--------------
Working in branch ZoneAirFlow6574 in case this has already been corrected in develop.

Test file shows a break in the debugger for uninitialized variable in the CalcZoneITEq routine where TSupply is uninitialized.

    if (abs(TAirOut - TSupply) < SmallTempDiff) {
        TAirOut = TSupply;
    }

In GetInput this input sets FlowControlWithApproachTemps = false (which is redundant based on class constructor)

                // IT equipment design level calculation method.
                if (lAlphaFieldBlanks(3)) {
                    ZoneITEq(Loop).FlowControlWithApproachTemps = false;
                } else {
                    if (UtilityRoutines::SameString(AlphaName(3), "FlowFromSystem")) {
                        ZoneITEq(Loop).FlowControlWithApproachTemps = false;
                    } else if (UtilityRoutines::SameString(AlphaName(3), "FlowControlWithApproachTemperatures")) {
                        ZoneITEq(Loop).FlowControlWithApproachTemps = true;
                        Zone(ZoneITEq(Loop).ZonePtr).HasAdjustedReturnTempByITE = true;
                        Zone(ZoneITEq(Loop).ZonePtr).NoHeatToReturnAir = false;
                    } else {
                        ShowSevereError(RoutineName + CurrentModuleObject + "=\"" + AlphaName(1) + "\": invalid calculation method: " + AlphaName(3));
                        ErrorsFound = true;
                    }
                }

and later in GetInput checks are made for Supply Air Node Name (alpha 14) to ensure it is available when needed.

                if (lAlphaFieldBlanks(14)) {
                    if (ZoneITEq(Loop).AirConnectionType == ITEInletAdjustedSupply) {
                        ShowSevereError(RoutineName + CurrentModuleObject + ": " + AlphaName(1));
                        ShowContinueError("For " + cAlphaFieldNames(11) + "= AdjustedSupply, " + cAlphaFieldNames(14) +
                                          " is required, but this field is blank.");
                        ErrorsFound = true;
                    } else if (ZoneITEq(Loop).FlowControlWithApproachTemps) {
                        ShowSevereError(RoutineName + CurrentModuleObject + ": " + AlphaName(1));
                        ShowContinueError("For " + cAlphaFieldNames(3) + "= FlowControlWithApproachTemperatures, " + cAlphaFieldNames(14) +
                                          " is required, but this field is blank.");
                        ErrorsFound = true;
                    } else {
                        ZoneITEq(Loop).SupplyAirNodeNum = 0;
                    }

Then in the CalcZoneITEq routine checks are made for the specific configuration to set up local variables. Also, checks are made here in the Calc routine for SupplyNodeNum > 0 which should be done in GetInput or a one time Init to save execution time, these checks should be moved. Note here that for FlowControlWithApproachTemps = false and AirConnection == ITEInletZoneAirNode that TSupply is not initialized (last ELSE).

            if (ZoneITEq(Loop).FlowControlWithApproachTemps) {
                if (SupplyNodeNum != 0) {
                    TSupply = Node(SupplyNodeNum).Temp;
                    WSupply = Node(SupplyNodeNum).HumRat;
                } else {
                    ShowSevereError(RoutineName + ": ElectricEquipment:ITE:AirCooled " + ZoneITEq(Loop).Name);
                    ShowContinueError("Air Inlet Connection Type = AdjustedSupply but no Supply Air Node is specified.");
                    ShowFatalError("Program terminates due to above conditions.");
                }
                if (ZoneITEq(Loop).SupplyApproachTempSch != 0) {
                    TAirIn = TSupply + GetCurrentScheduleValue(ZoneITEq(Loop).SupplyApproachTempSch);
                } else {
                    TAirIn = TSupply + ZoneITEq(Loop).SupplyApproachTemp;
                }
                WAirIn = Node(SupplyNodeNum).HumRat;
            } else {
                if (AirConnection == ITEInletAdjustedSupply) {
                    if (SupplyNodeNum != 0) {
                        TSupply = Node(SupplyNodeNum).Temp;
                        WSupply = Node(SupplyNodeNum).HumRat;
                    } else {
                        ShowSevereError(RoutineName + ": ElectricEquipment:ITE:AirCooled " + ZoneITEq(Loop).Name);
                        ShowContinueError("Air Inlet Connection Type = AdjustedSupply but no Supply Air Node is specified.");
                        ShowFatalError("Program terminates due to above conditions.");
                    }
                    if (ZoneITEq(Loop).RecircFLTCurve != 0) {
                        RecircFrac = ZoneITEq(Loop).DesignRecircFrac * CurveValue(ZoneITEq(Loop).RecircFLTCurve, CPULoadSchedFrac, TSupply);
                    } else {
                        RecircFrac = ZoneITEq(Loop).DesignRecircFrac;
                    }
                    TRecirc = MAT(NZ);
                    WRecirc = ZoneAirHumRat(NZ);
                    TAirIn = TRecirc * RecircFrac + TSupply * (1.0 - RecircFrac);
                    WAirIn = WRecirc * RecircFrac + WSupply * (1.0 - RecircFrac);
                } else if (AirConnection == ITEInletRoomAirModel) {
                    // Room air model option not implemented yet
                    TAirIn = MAT(NZ);
                    WAirIn = ZoneAirHumRat(NZ);
                } else { // Default to ITEInletZoneAirNode
                    TAirIn = MAT(NZ);
                    WAirIn = ZoneAirHumRat(NZ);
                }

then comes the debugger issue for uninitialized variable

    if (abs(TAirOut - TSupply) < SmallTempDiff) {
        TAirOut = TSupply;
    }

this was corrected with a simple test and initialization at top of routine

        Real64 TSupply(0.0);                              // Supply air temperature [C]

            if ((SupplyNodeNum != 0) && abs(TAirOut - TSupply) < SmallTempDiff) {
                TAirOut = TSupply;
            }

however, later in Calc are these types of calculations which will be reported.

            ZoneSumTinMinusTSup(NZ) += (TAirIn - TSupply) * AirVolFlowRate;
            ZoneSumToutMinusTSup(NZ) += (TAirOut - TSupply) * AirVolFlowRate;

and later the report variables

        // Zone-level sensible heat index
        for (Loop = 1; Loop <= NumOfZones; ++Loop) {
            if (ZoneSumToutMinusTSup(Loop) != 0.0) {
                ZnRpt(Loop).ITEqSHI = ZoneSumTinMinusTSup(Loop) / ZoneSumToutMinusTSup(Loop);
            }
        }

So something needs to be done here to 1) protect against the unitialized variable, 2) move tests for SupplyNodeNum == 0 to GetInput, and 3) resolve the reporting when Air Flow Calculation Method = FlowFromSystem.

No defect file here, ITE object is:

ElectricEquipment:ITE:AirCooled,
  ATM 104_Misc. Equipment,           !- Name
  Server_Room,                !- Zone Name
  FlowFromSystem,                         !- Air Flow Calculation Method
  Watts/Unit,                             !- Design Power Input Calculation Method
  3000,                                   !- Watts per Unit {W}
  1,                                      !- Number of Units
  ,                                       !- Watts per Zone Floor Area {W/m2}
  ,                                       !- Design Power Input Schedule Name
  ,                                       !- CPU Loading  Schedule Name
  Schedule1,   !- CPU Power Input Function of Loading and Air Temperature Curve Name
  0,                                      !- Design Fan Power Input Fraction
  0.001,                                  !- Design Fan Air Flow Rate per Power Input {m3/s-W}
  Schedule2,   !- Air Flow Function of Loading and Air Temperature Curve Name
  Schedule3, !- Fan Power Input Function of Flow Curve Name
  15,                                     !- Design Entering Air Temperature {C}
  None,                                   !- Environmental Class
  ZoneAirNode,                            !- Air Inlet Connection Type
  ,                                       !- Air Inlet Room Air Model Node Name
  ,                                       !- Air Outlet Room Air Model Node Name
  ,                                       !- Supply Air Node Name
  ,                                       !- Design Recirculation Fraction
  Schedule4,   !- Recirculation Function of Loading and Supply Temperature Curve Name
  1,                                      !- Design Electric Power Supply Efficiency
  Schedule5, !- Electric Power Supply Efficiency Function of Part Load Ratio Curve Name
  1,                                      !- Fraction of Electric Power Supply Losses to Zone
  ITE-CPU,                                !- CPU End-Use Subcategory
  ITE-Fans,                               !- Fan End-Use Subcategory
  ITE-UPS;                                !- Electric Power Supply End-Use Subcategory

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by YanfeiNREL** [comment]
@rraustad Hey, is this issue still open? It looks like #6575 fixed it? I am a little bit of confused.

**Comment by YanfeiNREL** [comment]
Here is the issue i recreated:
![Error_Recreate](https://user-images.githubusercontent.com/43475933/65167216-5c4dc800-d9ff-11e9-8c59-a84471b5b680.PNG)
