### ISSUE TITLE
EnergyPlus Not Supporting UTF-8

### ISSUE THREAD

**Issue by pflaumingo** [NREL/EnergyPlus#7043]
Issue overview
--------------
EnergyPlus no longer seems to support UTF-8 encoding as it did before breaking it's use for a lot of international applications. I tested using various UTF-8 characters, such as 模型, and found that from EnergyPlus 8.9 onwards the files don't run. EnergyPlus 8.8 worked, but 8.9 and 9.0.1 did not work.

Some additional details for this issue (if relevant):
 - Windows 10 + Mac OS Sierra
 - 8.9 and 9.0.1

**Comment by pflaumingo** [comment]
@Myoldmopar and @macumber I've attached a zip file with some passing and failing cases to test against. Unicode doesn't seem to cause issues in the paths or weather file, but does in the IDF and epJSON.

- [x] Unicode characters in weather file runs and reports appropriately in the HTML and SQL file
- [x] Unicode characters in the file path doesn't cause issues
- [ ] Unicode characters in the IDF causes a failure during parsing
- [ ] Unicode characters in the epJSON file causes errors related to node connections

[samples.zip](https://github.com/NREL/EnergyPlus/files/2553939/samples.zip)

**Comment by Myoldmopar** [comment]
I wonder if there's a little difference on Linux because when I created a directory named 模型, and tried to run EnergyPlus on a file in there, I get 

    ERROR: Could not find input data file: ..../add_utf8_模型/1ZoneEvapCoolerWithUTF8Char.idf.

Also, when I put that character inside an IDF and try to run it, I get the parser error.

**Comment by Myoldmopar** [comment]
And I checked out that one section of international characters inside E+ source.  It seems they were really just added to allow for some international characters to be made "upper case" because the input processor liked to upper case things for internal storage.  I don't think it was a declaration of allowing a certain set of input characters.  This adds to the case that E+ never actually officially supported UTF-8, but that it may have simply allowed them in with the existing input processor.  The new input processor is more strictly parsing the file, causing it to fail.  I think what we need to do is change this issue to a new feature request that can become an enhancement to E+ officially supporting UTF-8 in input file contents, file paths, etc., on all platforms.

**Comment by mjwitte** [comment]
@Myoldmopar Yeah, but . . . EnergyPlus de-facto supported extended characters for a long time, so this is a step backwards.

**Comment by Myoldmopar** [comment]
Agreed @mjwitte it's technically a step backward; the step forward will be to formalize what we support and do it right in every text-processing part of E+.

**Comment by jasondegraw** [comment]
@Myoldmopar Not to kick over any rocks here and I'll probably be banished for suggesting it, but I wonder if we should consider just dropping case insensitivity?

**Comment by pflaumingo** [comment]
Yeh, I should note that I tested on a Macbook Pro 2017 running Sierra 10.12.6. I tried on a Windows 10 via parallels, but I'm having issues with non-ascii characters in the path as well.

**Comment by macumber** [comment]
Upcase/down casing of UTF-8 strings is not a trivial thing.  It's also possible that E+ supported an extended code page with some international characters but was still limited to 1 byte characters so never really supported unicode.

**Comment by Myoldmopar** [comment]
A couple additional comments that were discussed during a call and I just don't want to lose them:
- Need to consider our output file encoding, what is it now?  What should it be?
- Are there any limitations with the SQLite library in terms of UTF-8 support?

**Comment by Myoldmopar** [comment]
@pflaumingo,

@mbadams5 took time to quickly fix up unicode support.  Essentially his changes get EnergyPlus back to where we were before 8.9.0.  I'm going to review his changes and try to get that in quickly, and I believe this issue will then be wrapped up.  Please take a look over there and confirm that those results are satisfactory to close this issue.

**Comment by pflaumingo** [comment]
@Myoldmopar if all those screenshots reflect the output and tests are passing then I believe those results are satisfactory.
