### ISSUE TITLE
Thermal chimney impact on zone infiltration is not clear, also could use an EMS actuator.

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7044]
Issue overview
--------------
1. `ZoneThermalChimney` calculates a total flow for the chimney and then distributes this flow to the zone(s) as infiltration. This is added to any base infiltration that is calculated by `ZoneInfiltration:*` objects. The total infiltration (including the induced infiltration from the chimney) is reported in the "Zone Infiltration *" output variables. This connection to the zone infiltration is not mentioned in the `ZoneThermalChimney` description in the Input Output Reference or the Engineering Reference.

2. 'ZoneThermalChimney' does not have an EMS actuator to control the total chimney flow and/or the zone-by-zone induced infiltration rates.

3. If there is a `ZoneThermalChimney` object(s), but no `ZoneInfiltration:*` objects, the "Zone Infiltration *" output variables are not set up. Since these are zone level variables (not tied to the name of the `ZoneInfiltration:*` objects) then it seems the infiltration output variables should be set up if there's a `ZoneThermalChimney` object connected to the zone.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.0.1
 - Unmethours [35341](https://unmethours.com/question/35341/reset-the-infiltration-by-ems/?comment=35459#post-id-35459)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lgu1234** [comment]
Closed at #8004
