### ISSUE TITLE
Change in results for 2ZoneDataCenterHVAC_wEconomizer from V8.9 to V9.0

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7049]
Issue overview
--------------
Work on an issue where coil inlet air temps used for sizing are incorrect when sizing OA fraction differs from simulation OA fraction (e.g., VRP adjusts design spec OA fraction) led to the finding that this example file result has changed significantly. Comparing the results in the release versions shows these results. It appears that the water coil model has somehow changed. This is a complex example file where the East zone uses a water coil in the air loop while West zone uses a CoilSystem:Cooling:DX object with single speed DX. Also troubling is that the TSTAT cooling SP is 23C while neither of these zones can attain that temperature. Review of the eio results show no significant differences in component sizing.

First row shows zone temps between V8.9 and 9.0 for entire simulation.
Next rows show zoomed in results as shown for csv rows 500-600.

![2zonedatacenterhvac_weconomizer_1](https://user-images.githubusercontent.com/5778156/48138499-70b72500-e272-11e8-83fc-cec541462659.jpg)
![2zonedatacenterhvac_weconomizer_2](https://user-images.githubusercontent.com/5778156/48138506-73b21580-e272-11e8-953b-2a6dc4646327.jpg)

I did have to add a few output variables to get water coil water-side data here. I don't think it's the plant that has changed so initially focus on the water coil model with the existing example file.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Closing as stale and very unlikely to be picked up now.
