### ISSUE TITLE
How to add phase change function to the HAMT module

### ISSUE THREAD

**Issue by lxk1993** [NREL/EnergyPlus#7063]
I have joined the following five equations.
![1](https://user-images.githubusercontent.com/42338103/48593725-00eb1d80-e989-11e8-81d6-cc9867e29386.jpg)
![4](https://user-images.githubusercontent.com/42338103/48594065-4bb96500-e98a-11e8-9c85-d26c9224e3e0.jpg)
![5](https://user-images.githubusercontent.com/42338103/48594072-52e07300-e98a-11e8-9ddc-487f99ed4426.jpg)
![6](https://user-images.githubusercontent.com/42338103/48594078-57a52700-e98a-11e8-8fe0-cf651f73ff6a.jpg)
![2](https://user-images.githubusercontent.com/42338103/48593737-08aac200-e989-11e8-82b3-1c7b987ecc8a.jpg)
Modified the source code of HAMT.
![3](https://user-images.githubusercontent.com/42338103/48593800-3f80d800-e989-11e8-8b83-f3658d01dee9.jpg)
But it can only simulate the process of warming up, and the process of cooling does not have the effect of phase change.
How should I modify？

**Comment by jmarrec** [comment]
This is an interesting question, but one better suited for unmethours.com. Thank you.
