### ISSUE TITLE
Object with too many fields not trapped correctly

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7076]
Issue overview
--------------
If an object has too many fields, the next field after what should be end-of-object is processed as if it's the start of a new object.

Defect file 1ZoneUncontrolled-TooManyFields.idf
```
  SurfaceConvectionAlgorithm:Inside,TARP,Yes;

   ** Severe  ** Line: 107 Index: 40 - Error parsing "SurfaceConvectionAlgorithm:Inside". Error in following line.
   ** Severe  ** ~~~   SurfaceConvectionAlgorithm:Inside,TARP,
   ** Severe  ** Line: 107 Index: 43 - "Yes" is not a valid Object Type.
```

Defect file 1ZoneUncontrolled-TooManyFieldsB.idf
```
  SurfaceConvectionAlgorithm:Inside,TARP,Chiller:Electric:EIR;

   ** Severe  ** Line: 107 Index: 40 - Error parsing "SurfaceConvectionAlgorithm:Inside". Error in following line.
   ** Severe  ** ~~~   SurfaceConvectionAlgorithm:Inside,TARP,
   ** Severe  ** <root>[Chiller:Electric:EIR][SurfaceConvectionAlgorithm:Outside][reference_capacity] - Value type not permitted by 'type' constraint.
   ** Severe  ** <root>[Chiller:Electric:EIR][SurfaceConvectionAlgorithm:Outside][reference_capacity] - Failed to validate against child schema #0.
   ** Severe  ** <root>[Chiller:Electric:EIR][SurfaceConvectionAlgorithm:Outside][reference_capacity] - "DOE-2" - Failed to match against any enum values.
   ** Severe  ** <root>[Chiller:Electric:EIR][SurfaceConvectionAlgorithm:Outside][reference_capacity] - Failed to validate against child schema #1.
   ** Severe  ** <root>[Chiller:Electric:EIR][SurfaceConvectionAlgorithm:Outside][reference_capacity] - Failed to validate against any child schemas allowed by anyOf constraint.
```
Notice this while testing #7069 where the "before" case had an PlantEquipmentList with extra fields, and it generated errors like case B above.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.0.1-a7c9cc14ce

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files
[1ZoneUncontrolled-TooManyFields.idf.txt](https://github.com/NREL/EnergyPlus/files/2611387/1ZoneUncontrolled-TooManyFields.idf.txt)
[1ZoneUncontrolled-TooManyFieldsB.idf.txt](https://github.com/NREL/EnergyPlus/files/2611400/1ZoneUncontrolled-TooManyFieldsB.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I'm not sure if the error message was truncated too much, or if 9.0.1 didn't have the first warning which is more explicit about what's going on. **Edit**: Actually, a git blame shows that @mbadams5 in https://github.com/NREL/EnergyPlus/pull/7807 added this line (see specifically https://github.com/NREL/EnergyPlus/commit/dbe1883b71a88e8026adfa2cfc248c8d46214be9)

```
   ** Severe  ** Line: 108 Index: 40 - Object contains more field values than maximum number of IDD fields and is not extensible.
```

 Here's with current develop 36db22b9af45b33371b30b85de916659c091c7c8

```
Program Version,EnergyPlus, Version 9.4.0-36db22b9af, YMD=2020.05.26 13:48,
   ** Severe  ** Line: 108 Index: 40 - Object contains more field values than maximum number of IDD fields and is not extensible.
   ** Severe  ** Line: 108 Index: 40 - Error parsing "SurfaceConvectionAlgorithm:Inside". Error in following line.
   ** Severe  ** ~~~   SurfaceConvectionAlgorithm:Inside,TARP,Yes;
   ** Severe  ** Line: 108 Index: 43 - "Yes" is not a valid Object Type.
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.
```

**Comment by jmarrec** [comment]
@mjwitte given the new severe which gives you a very hard clue about what the problem is, is this worth addressing or can we close?

**Comment by mjwitte** [comment]
Yes, that's better.
