### ISSUE TITLE
Add additional option for shading control for WindowProperty:ShadingControl object

### ISSUE THREAD

**Issue by supriyagoel** [NREL/EnergyPlus#7081]
Issue overview
--------------
We need an option in the 'Shading Control' dropdown of 'WindowProperty:ShadingControl' object which can control the shades based on transmitted direct solar energy. At present, all available options are for incident direct + diffuse  solar radiation.

This feature is required to model an ASHRAE 90.1 Appendix C requirement (Section C3.5.5.1) which requires manually operated shades to be modeled for all vertical fenestration. These shades are required to be modeled to be lowered based on either a transmitted luminance threshold or a transmitted direct solar radiation threshold. Both of these thresholds are not supported by E+ currently.

**Comment by mjwitte** [comment]
Also, 90.1 requires that once the shade are lowered that they remain in place until the end of the day. An option for that, and an option to set a minimum time between changes in shade status would also be useful.
