### ISSUE TITLE
EvapCooler crash with autosized field and no design days

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7083]
Issue overview
--------------
EnergyPlus 9.0.1 crashes when there is a `EvaporativeCooler:Direct:ResearchSpecial` object that is autosized but there are no design days. Example file: [in.idf.txt](https://github.com/NREL/EnergyPlus/files/2633284/in.idf.txt)

(Context: we were hardsizing the evap cooler object in OpenStudio, but a [bug in OpenStudio](https://github.com/NREL/OpenStudio/issues/3363) caused the airflow rate not to be written to the IDF, triggering this crash.)

cc @jmarrec @mpathak24

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I'm thinking it might actually be also the fact that since openstudio didn't find any design day, it didn't force the SimulationControl to do system sizing.

```
SimulationControl,
  No,                                     !- Do Zone Sizing Calculation
  No,                                     !- Do System Sizing Calculation
  No,                                     !- Do Plant Sizing Calculation
  No,                                     !- Run Simulation for Sizing Periods
  Yes;                                    !- Run Simulation for Weather File Run Periods
```

But anyways, that shouldn't crash either with a segfault.
