### ISSUE TITLE
Kiva foundation setup divide-by-zero with North Axis=45.0 for this file

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7088]
Issue overview
--------------
We have two IDFs whose only difference is the Building's North Axis. One of them runs in E+ 9.0.1, the other one freezes at "Initializing Simulation".

[good.idf.txt](https://github.com/NREL/EnergyPlus/files/2650937/good.idf.txt)
[bad.idf.txt](https://github.com/NREL/EnergyPlus/files/2650938/bad.idf.txt)

We tracked down the issue to being introduced between the [IDD Freeze of Version 9.0.0 release](https://github.com/NREL/EnergyPlus/releases/tag/v9.0.0-IOFreeze) and the [EnergyPlus 9.0, Release Candidate 2 release](https://github.com/NREL/EnergyPlus/releases/tag/v9.0.0-RC2). Both files run in the former release, but one of them fails in the latter.

cc @joseph-robertson

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
When run in a debug build, northaxis=45.0 hits a divide by zero [here in SurfaceData::get_average_height](https://github.com/NREL/EnergyPlus/blob/ae4c2ce0d208dff6982b852c40fccb78aa78c552/src/EnergyPlus/DataSurfaces.cc#L1040) which is called during Kiva foundation setup. North axis of 44.9 or 45.1 get by ok.

**Comment by mjwitte** [comment]
`get_average_height` was added as part of https://github.com/NREL/EnergyPlus/pull/6852 "Allow any wall shape for Kiva Foundations"

**Comment by mjwitte** [comment]
@nealkruis
