### ISSUE TITLE
Incorrect Fan RTF depending on HVAC equipment order

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7093]
Issue overview
--------------
I am seeing incorrect fan runtime fractions depending on the order of my HVAC equipment in the ZoneHVAC:EquipmentList object.

Attached are two IDF files with the only change being the order of the heating and cooling systems in the ZoneHVAC:EquipmentList. The building has a single conditioned zone served by two unitary systems. One unitary system has _only_ a heating coil and the other unitary system has _only_ a cooling coil.

We're trying to use the fan RTFs to drive an EMS program, hence why it's important. The expectation is that, for any given timestep, only one of the fan RTFs should be greater than zero (i.e., only the heating system or cooling system should be running).

If the heating system is before the cooling system, we get good results where only one fan RTF is greater than zero. But if the cooling system is before the heating system, we got many timesteps where the heating fan RTF is greater than zero and the cooling fan RTF is 1 (whereas it should be 0).

[in-good.idf.txt](https://github.com/NREL/EnergyPlus/files/2659013/in-good.idf.txt)
[in_bad.idf.txt](https://github.com/NREL/EnergyPlus/files/2659016/in_bad.idf.txt)

Good result (cooling fan RTF = 0 whenever heating fan RTF > 0):
![image](https://user-images.githubusercontent.com/5861765/49677185-99ca0180-fa3a-11e8-9dd5-553b2698082d.png)

Bad result (cooling fan RTF = 1 whenever heating fan RTF > 0)
![image](https://user-images.githubusercontent.com/5861765/49677047-e19c5900-fa39-11e8-9b90-4734d0607a65.png)

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10
 - Version of EnergyPlus: 9.0.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Just off the top of my head, the unitary system with Control Type=Load tries  to meet both cooling and heating loads, regardless of what coil types are present. So, whenever there is any remaining load (heating or cooling), the equipment will run.  So, in the bad case, the cooling system is trying to meet the heating load, it can't, so the second system sees a remaining load and meets it.  My guess is that the "good" case is bad when the zone requires cooling.

Options to fix this:
1. Set the Heating Supply Air Flow Rate=0.0 for the cooling-only unit and set the Cooling Flow Rate=0.0 for the heating-only unit.
2. Or combine them into a single unitary system - not following why you want these to be two systems anyway.

**Comment by rraustad** [comment]
If these unitary systems are in series then how can one fan have RTF=0? That would choke the flow through the other system. EMS should use the PLR of the coil.

**Comment by mjwitte** [comment]
They are both zone equipment, in parallel.

**Comment by shorowit** [comment]
>     1. Set the Heating Supply Air Flow Rate=0.0 for the cooling-only unit and set the Cooling Flow Rate=0.0 for the heating-only unit.

@mjwitte Thanks for the suggestion. We had set the "unused" airflow rates to a small number but not zero (I think because OpenStudio did not allow us to set zero). I entered zero manually and it gave the results we're looking for! That's good enough for us, I'll close this issue.

>     2. Or combine them into a single unitary system - not following why you want these to be two systems anyway.

For what it's worth, we decided to split up our heating/cooling systems into separate unitary systems so that we could disaggregate the supply fan energy use into heating fan energy vs cooling fan energy. We had initially looked into modifying EnergyPlus itself to accommodate the disaggregation, but after discussing with you and @rraustad many months ago, learned all the ways this could be complicated/nuanced. So using two unitary systems seemed like an easy workaround to avoid it.

**Comment by mjwitte** [comment]
@rraustad I was wrong - this model has two complete airloops serving the one zone.

@shorowit An alternate approach to collecting heating/cooling fan energy is to use `Output:Table:Monthly`.
```
  Output:Table:Monthly,
    Fan Report,              !- Name
    ,                        !- Digits After Decimal
    Air System Total Heating Energy,     !- Variable or Meter 1 Name
    HoursPositive,            !- Aggregation Type for Variable or Meter 1
    Air System Fan Electric Energy,  !- Variable or Meter 2 Name
    SumOrAverageDuringHoursShown,            !- Aggregation Type for Variable or Meter 2
    Air System Total Cooling Energy,      !- Variable or Meter 3 Name
    HoursPositive,                 !- Aggregation Type for Variable or Meter 3
    Air System Fan Electric Energy,  !- Variable or Meter 4 Name
    SumOrAverageDuringHoursShown,  !- Aggregation Type for Variable or Meter 4
    Air System Fan Electric Energy,  !- Variable or Meter 4 Name
    SumOrAverage;  !- Aggregation Type for Variable or Meter 4
```
Here's an example file with this added. Variable 4 is there as a check for the total, 'cause there might be hours when neither coil is operating if there's continuous fan operation or free cooling. 

I don't recall the prior discussion on this, but it seems we could come up with some additional output variables in the Air System group that can report fan energy either based on coil operation or net heating/cooling added to the supply air (including impact of OA), or whatever definition you want.

**Comment by mjwitte** [comment]
Forgot to attach the file.  [FurnaceWithDXSystem-FanReport.idf.txt](https://github.com/NREL/EnergyPlus/files/2664469/FurnaceWithDXSystem-FanReport.idf.txt) The report looks like this.
![fan report](https://user-images.githubusercontent.com/4991075/49754090-d7b56880-fc7a-11e8-9240-281ea329b2b8.png)

**Comment by shorowit** [comment]
Cool! I was not aware that Output:Table:Monthly has such capability. Now I have to decide which approach to go with, there are pros/cons to both.

**Comment by mjwitte** [comment]
Yep, neither one is perfect. One limitation of Output:Table:Monthly is that all variables must share the same keyname. Output:Table:Annual with its "Filter" field, offers a way to combine variables with different key names (i.e. a coil output and a fan output) if they share a common string in their names (at least I think that's how it works).
