### ISSUE TITLE
What is the equivalent of RunEPlus.bat in macOS and Linux?

### ISSUE THREAD

**Issue by nheeren** [NREL/EnergyPlus#7097]
I am trying to run an .idf file from [here](https://www.energycodes.gov/development/residential/iecc_models) that requires the basement preprocessor. In the Windows version of e+ this works fine, because `RunEPlus.bat` performs all the necessary steps and copies the results into in.expidf. However, I could not find an equivalent script in the macOS version. Am I overlooking something?

If this does not exist, could you please consider adding one? Is there some documentation on what RunEPlus.bat exactly does? It would be great if you could enhance this article a bit: https://github.com/NREL/EnergyPlus/blob/develop/doc/running-energyplus-from-command-line.md

EDIT: It seems like `runenergyplus` used to be that file but it now stops with a deprecation message saying that `EnergyPlus` would substitute it. However, that one does not seem to care about preprocessors...

> ***** NOTE: This script is marked as deprecated as of August 2015.
*****       The functionality of this script is now in the command line interface.
*****       For information on the command line interface:
*****        - See the documentation (https://energyplus.net/documentation)
*****        - Call the application for usage: EnergyPlus --help
*****        - Refer to the man page: man EnergyPlus
*****       In a future version of EnergyPlus, this script will no longer be packaged.

After more trial & error the necessary steps seem to be as follows: 

1. Run `./ExpandObjects`
2. *Optional*: Run necessary preprocessors
    - `./Basement` if `BasementGHTIn.idf` is present
    - `./Slab` if ??? is present
3. *If preprocessors were run:* Append `expanded.idf` with `EPObjects.txt`
4. Run `./energyplus -r expanded.idf`

**Comment by jmarrec** [comment]
runenergyplus is just a shell script, which you can see the source here: https://github.com/NREL/EnergyPlus/blob/develop/scripts/runenergyplus.in

You'll see on line 518 that it runs slab if 'GHTIn.idf' is in the folder.

**Comment by jmarrec** [comment]
I'm closing this one as I don't see any proper action item.
