### ISSUE TITLE
Typo in IDF Editor description of Fan:ZoneExhaust field Balanced Exhaust Fraction Schedule Name

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7101]
Issue overview
--------------
In the IDF editor, the field description for Fan:ZoneExhaust field Balanced Exhaust Fraction Schedule Name has redundant text.

![fan exhaust field description typo](https://user-images.githubusercontent.com/39242689/49889198-bcbb3380-fdf5-11e8-8d21-f1ee104db461.PNG)

**Comment by mjwitte** [comment]
Interesting, this is caused by a stray emtpy `\note` following the real note in the idd:
```
  A9 ; \field Balanced Exhaust Fraction Schedule Name
       \note Used to control fan's impact on flow at the return air node. Enter the portion of the exhaust that is balanced by simple airflows.
       \note
       \type object-list
       \object-list ScheduleNames
```
The same problem is present in `Coil:Cooling:DX:SingleSpeed:ThermalStorage` "Storage Capacity Sizing Factor".
