### ISSUE TITLE
Change climatic data summary string searches to avoid potential encoding differences

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7102]
Issue overview
--------------
As noted [here in #6192](https://github.com/NREL/EnergyPlus/pull/6192#issuecomment-439079747) the string searches for some of the Climatic Data Summary fields have embedded special characters which fail to match if the weather stat file does not have the same encoding as EnergyPlus (which is now UTF-8). Note the bad encoding of the degree symbol for latitude and longitude. Also all the lines related to Köppen classification and ASHRAE Handbook CDD/HDD are missing with the Western (Windows 1252) encoded stats file.

It can't find the Köppen classification because it is searching the Western (Windows 1252) line using an UTF-8 encoded string. We'd need to either re-write the specific parts to be encoding agnostic, read the file stats file as UTF-8, or convert the encoding of that specific input string to UTF-8.

Possible approach (MJW):Would it work to search just parts of the string, leaving out the offending characters, and then output the full utf-8 string, not what's in the stat file? In fact, I'd prefer to see the line show up in the table with a blank value even if the data isn't found in the stat file.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Ref #6192 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lklawrie** [comment]
I will be glad to try to help with this issue -- of course, the files on
energyplus.net seem to be more static than the ones on either
climate.onebuilding or joe huang's site (temporarity forgotten but I
recently found out that he doesn't know what the stat files are for).

Anything we can do to  further the issue going forward?

Linda

**Comment by EnergyArchmage** [comment]
I ran into this issue, which causes 7 fields to be missing in the Weather Statistics File summary table output. 

As discussed during a subgroup call on 7/31/2019, I experimented with truncating the search strings to avoid the special characters and it worked well.  The changes have been published in 

https://github.com/NREL/EnergyPlus/tree/7102-weather-stat-file-search-strings

**Comment by mjwitte** [comment]
Nice that it works.
