### ISSUE TITLE
Zone over-conditioned when using UniformLoad (AirLoopHVAC + IdealLoadsAirSystem)

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7110]
Issue overview
--------------
I'm doing testing on a simple residential building (one conditioned thermal zone) served by either zonal or airloop HVAC equipment. My tests involve adding a ZoneHVAC:IdealLoadsAirSystem to the model with the expectation that the energy use of the original HVAC system is cut in half (because there are now two HVAC systems w/ UniformLoad scheme).

All simulations were run using a build created from [the UniformLoad bugfix PR](https://github.com/NREL/EnergyPlus/pull/7025). Here are my findings:

  | Zonal or AirLoop | HVAC Energy w/o IdealLoads | HVAC Energy w/ IdealLoads | Calculated Fraction | Result
-- | -- | -- | -- | -- | --
ZoneHVAC:Baseboard:Convective:Water | Zonal | 40.32 | 20.16 | 0.50 | Good
ZoneHVAC:PackagedTerminalAirConditioner | Zonal | 41.60 | 21.13 | 0.51 | Good
AirLoopHVAC:UnitarySystem (heating coil only) | Zonal | 46.35 | 23.17 | 0.50 | Good
AirLoopHVAC:UnitarySystem (cooling coil only) | AirLoop | 18.57 | 12.59 | 0.68 | **Bad**
AirLoopHVAC:UnitarySystem (heating coil only) | AirLoop | 35.91 | 25.24 | 0.70 | **Bad**

I get near perfect results for zonal equipment (including UnitarySystems used as zonal equipment). But the AirLoopHVAC test results are way off -- the calculated fractions are around 0.7 instead of 0.5. When I look at the model with the IdealLoads system, it appears to be over-conditioning the zone.

![image](https://user-images.githubusercontent.com/5861765/50309774-52416d80-045d-11e9-89e4-dda50b7a49f2.png)

The two IDFs corresponding to the last row of the table are attached:
[AirLoopHVAC_withIdealLoads.idf.txt](https://github.com/NREL/EnergyPlus/files/2700404/AirLoopHVAC_withIdealLoads.idf.txt)
[AirLoopHVAC_withoutIdealLoads.idf.txt](https://github.com/NREL/EnergyPlus/files/2700408/AirLoopHVAC_withoutIdealLoads.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Likely related to #7106

**Comment by shorowit** [comment]
Ah yes, it very well could be. I hope so!
