### ISSUE TITLE
Compiler Warnings with GCC 8.2.0

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#7115]
Issue overview
--------------
Upgraded my system and now I get some compiler warnings like:
```
/eplus/repos/1eplus/third_party/ObjexxFCL/src/ObjexxFCL/ubyte.hh: In member function ‘ObjexxFCL::ubyte ObjexxFCL::ubyte::operator-() const’:
/eplus/repos/1eplus/third_party/ObjexxFCL/src/ObjexxFCL/ubyte.hh:199:89: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
   return ubyte( static_cast< unsigned char const >( -static_cast< short int const >( b_ ) ) );
                                                                                         ^
/eplus/repos/1eplus/third_party/ObjexxFCL/src/ObjexxFCL/ubyte.hh:199:91: warning: type qualifiers ignored on cast result type [-Wignored-qualifiers]
   return ubyte( static_cast< unsigned char const >( -static_cast< short int const >( b_ ) ) );
                                                                                           ^
```

I'm likely to just mute this warning since it is only occurring inside this third_party code, but I wanted to at least bring it up so @DeadParrot could evaluate whether it needs to be more properly addressed or not.  **Actually**, it looks like the fix is in fact already implemented in #6902, but that PR is on hold due to some surprising performance results.  @DeadParrot could you confirm whether I can just remove the type qualifiers on that line without any issues?  Since the compiler is ignoring them, I assume I can...

I am also getting an issue with the recently added no-vexing-parse ignorance, so that should be cleaned up too.
`cc1plus: warning: unrecognized command line option ‘-Wno-vexing-parse’`

**Comment by DeadParrot** [comment]
@Myoldmopar I don't see any problem cherry picking updates from #6902. The qualifiers were just for intent clarity.
