### ISSUE TITLE
Cannot Produce I/O doc statement on EvaporativeCooler:Direct:ResearchSpecial Water Pump Modifier Curve 

### ISSUE THREAD

**Issue by xwanguk** [NREL/EnergyPlus#7118]
Issue overview
--------------
I/O documentation section 1.50.2.1.8 Field: Water Pump Power Modifier Curve Name states that:

This alpha input field is the name of a dimensionless normalized pump power modifying curve. This curve modifies the pump electric power in the previous field by multiplying the design power by the result of this curve. The normalized curve is a function of the primary air flow fraction as independent variable. The curve shall yield a value of 1.0 at a flow fraction of 1.0. The flow fraction is the ratio of the primary air during current operation divided by primary air Design Air Flow Rate. If this input field is left blank, the pump power is assumed to linearly vary with the load. Any curve or table with one independent variable can be used: Curve:Linear, Curve:Quadratic, Curve:Cubic, Curve:Quartic, Curve:Exponent, Curve:ExponentialSkewNormal, Curve:Sigmoid, Curve:RectuangularHyperbola1, Curve:RectangularHyperbola2, Curve:ExponentialDecay, Curve:DoubleExponentialDecay, and Table:OneIndependentVariable.

Within above lines, I can see "If this input field is left blank, the pump power is assumed to linearly vary with the load."

I've tested a simple curve that has a linear change of Y against X with X ranges [0, 1], but eso files show different results especially from "Evaporative Cooler Electric Power" variable.

Changing the curve to a constant one (always 1) does not solve the problem (this test was based on the suspect that there might be a typo/mistake in the documentation).

So now I have a concern that the source codes don't treat this curve object well. As a contrast, the Indirect ResearchSpecial operative cooler has been tested well between using and not using curves generated by the guidance defined in the I/O documentation, where for Water Pump Power Modifier Curve Name field it says "If this input field is left blank, the pump power is assumed to be constant."

### Details
Some additional details:
 - Tested on Windows 7 64-bit computer.
 - Using EnergyPlus V8.9

**Comment by Nigusse** [comment]
This is a defect in evaporative cooler research special water pump modifier curve use implementation. The documentation is correct. The water pump power is correctly calculated only if "Effectiveness Flow Ratio Modifier Curve Name" input field is not blank. This fix modified the logic such that pump power calculation uses the correct flow ratio regardless of the Effectiveness modifier curve presence. Addressed in pull request #7305.

**Comment by xwanguk** [comment]
I have checked the same models in E+ V9.2, it seems the reported problem is still there.
