### ISSUE TITLE
2 Typos In IO Reference 9.0 page 1012

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7122]
![1012 typos](https://user-images.githubusercontent.com/39242689/50914713-06467080-13ec-11e9-8c47-2a2bb29f9f24.PNG)

**Comment by mjwitte** [comment]
Thanks, if you find any more, please just keep adding to this one as an additional comment.

**Comment by mjwitte** [comment]
Moved to https://github.com/NREL/EnergyPlus/issues/7160#issuecomment-461191828
