### ISSUE TITLE
Plant SetComponentFlowRate not properly scanning components in series active branches

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#7125]
Issue overview
--------------
While debugging a separate issue with a chiller plant with parallel branch pumps and chillers, noticed in the debugger that there is a small coding mistake in two places in SetComponentFlowRate where the routine is not properly sweeping component inlet nodes down a series branch.  The for loops should be using this_comp instead of comp here:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PlantUtilities.cc#L364
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PlantUtilities.cc#L393

current code does not really update node numbers as the for loops execute. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #7126
