### ISSUE TITLE
Building from source only

### ISSUE THREAD

**Issue by jluttine** [NREL/EnergyPlus#7131]
This is a question, not a bug report. I didn't figure out where I should ask, so I decided to ask here. Sorry for the noise on your issue tracker..

I noticed that there are some binaries in the repo as explained here: https://github.com/NREL/EnergyPlus/blob/develop/bin/README.md

Is it possible to either
- build and use EnergyPlus without these binary files
- build these binaries from source myself (where are the sources?)

I was also a bit confused as some binaries were only for Windows (.exe) so are those binaries not relevant for Linux users (like me) for some reason?

**Comment by jluttine** [comment]
Also, there seems to be `Products/libsqlite.a` and other `Products/*.a` files. I suppose these are binary files needed when compiling on Linux. Are there still some other binaries in the repo that are used and is there a way to not use them?

**Comment by jasondegraw** [comment]
@jluttine Yes, it is possible to build and use EnergyPlus without those binary files. There are a couple that will make certain things easier, and there are descriptions of the programs in the Auxiliary Programs document (see https://energyplus.net/documentation). But fundamentally these are separate programs from the engine.

For further assistance, UnmetHours (https://unmethours.com) or the helpdesk (http://energyplus.helpserve.com) is probably a better avenue than here.
