### ISSUE TITLE
Feature Request: Generate Warning when a WaterUse:Equipment object has a target temperature is below water temperature

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7133]
Issue overview
--------------
In the FullServiceRestaurant model created by the Create DOE Prototype Building BCL measure, one of the WaterUse:Equipment objects has a target temperature of 15.5F = -9.1C, a.k.a. ice. 

In this case, there isn't a problem with having not frozen water coming out of a faucet. However, in other instances it would be good to have a warning generated if the faucet temperature is above the target temperature of the WaterUse:Equiptment object. At the very least, this would be good to catch human input error.

### Details
Some additional details for this issue (if relevant):
 - Wnidows 10
 - EnergyPlus 9.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added https://drive.google.com/file/d/1rPdD9HkG_tevBclcMMXTfDTbMoWVYWXq/view?usp=sharing
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
See also #4954 which is very similar (closing that one, but worth referencing for additional discussion).
Related to #6435 - WaterUse:Storage Design Inflow Rate not respected.
