### ISSUE TITLE
Error transitioning Shading:Building:Detailed objects from 8.9.0 to 9.0.1 

### ISSUE THREAD

**Issue by liq2519** [NREL/EnergyPlus#7135]
Issue overview
--------------
The below error message appears when updating a working v8.9.0 IDF to v9.0.1 using IDFVersionUpdater. This appears to be caused by three Shading:Building:Detailed objects, after removing which the error disappears.

![2019-01-23](https://user-images.githubusercontent.com/11031984/51705326-f4b2ba80-1fe0-11e9-9576-538ca44bb718.png)

A simple IDF that can replicate the issue is attached: [updater_error_example.zip](https://github.com/NREL/EnergyPlus/files/2793408/updater_error_example.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10 Enterprise Version 10.0.16299 Build 16299
 - Version of EnergyPlus: v9.0.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [DefectFiles/7000s/7135](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/7000s/7135)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I can reproduce this on Ubuntu with current develop (5ddf585d0378775ebe219927560b332b6ed68d82).

```
At line 875 of file /home/julien/Software/Others/EnergyPlus/src/Transition/VCompareGlobalRoutines.f90
Fortran runtime error: Bad integer for item 1 in list input
```


Problem is here in [VCompareGlobalRoutines.f90#L875](https://github.com/jmarrec/EnergyPlus/blob/5ddf585d0378775ebe219927560b332b6ed68d82/src/Transition/VCompareGlobalRoutines.f90#L875)

**Comment by jmarrec** [comment]
@liq2519 

Problem is that you have a float for Number of Vertices when it must be an integer

**For Number of Vertices, either set it to Autocalculate (or empty, which amounts to the same), or change it to be an Integer rather than a floating point number**:

eg:

```
Shading:Building:Detailed,
    Shading Surface 3,       !- Name
    ,                        !- Transmittance Schedule Name
    4.0,                     !- Number of Vertices

```

Change it to be:

```
Shading:Building:Detailed,
    Shading Surface 3,       !- Name
    ,                        !- Transmittance Schedule Name
    4,                     !- Number of Vertices
```

**Comment by jmarrec** [comment]
Added a fix for this one in 43efd7e out of curiosity. But the same would be generally required everywhere we try to read a certain number format and fail to do so...

**Comment by liq2519** [comment]
@jmarrec Thank you very much. I was able to convert successfully after using integers. The float 4.0 is shown as 4 in V8.9 IDFEditor so I didn't find it at first.

**Comment by mjwitte** [comment]
Using `READ` in transition is always dangerous for numeric fields. `ProcessNumber` should be used instead. [Here is an example.](https://github.com/NREL/EnergyPlus/blob/5ddf585d0378775ebe219927560b332b6ed68d82/src/Transition/CreateNewIDFUsingRulesV9_0_0.f90#L697-L700)
