### ISSUE TITLE
Unclear which peak the outputs of the coil sizing details are referring to

### ISSUE THREAD

**Issue by pflaumingo** [NREL/EnergyPlus#7136]
Issue overview
--------------

### Details
Checked using EnergyPlus 9.0.1. The coil sizing details outputs contain a coil sensible, total and airflow ideal loads peak all of which may or may not occur at the same time. Aside from the timestamps, all the other outputs state some output at "Ideal Loads Peak", but it isn't clear which peak that is associated with (Sensible, Total or Airflow). I think it'd be helpful to report out which peak the outputs are referring to. The documentation for these outputs can be found here below, but also don't quite clarify the peak at which the output is reporting.

https://bigladdersoftware.com/epx/docs/9-0/output-details-and-examples/eplustbl-lt-ext-gt.html

**Comment by jmarrec** [comment]
IIUC, this only applies to central cooling coils. The Sizing:System "Type of Load to Size On" field is used to determine what the supply air flow rate used is, where `Total` means the airflow and system air conditions is at the system cooling total peak, and all other choices mean "Sensible". 

> https://bigladdersoftware.com/epx/docs/9-1/engineering-reference/component-sizing.html#coilcoolingwater
> By choosing Type of Load to Size On = Sensible or Total in Sizing:System the user indicates to the program to save the cooling coil air flow rate and system air conditions (mixed, return, outside) at the time of either the system cooling sensible or total load peak. Note that the choice VentilationRequirement uses the time of the sensible peak.

The "Air Flow Ideal Loads Peak" design day name and timestamp are given for reference only (they apply to fan sizing).

@rraustad's I could use your expertise here please, as I'm not sure I'm correct...

If the above is correct, then we could add a column in `Report: Coil Sizing Details` that would indicate whether "Total" or "Sensible" was used (cf "Peak Load Type to Size On")

![image](https://user-images.githubusercontent.com/5479063/61218047-64dd0600-a711-11e9-8972-a73c83fb5884.png)

**Comment by rraustad** [comment]
I agree that the sizing tables should include the sizing method. When latent coil sizing is added there would then be 4 choices and users can change the sizing method per system. Documentation could include a description of sizing details for each choice. Should the Design Day Name (and Date/Time) be reported for the Sensible, 2nd row, when sizing method = Total? Is that helpful without the associated peak coil size magnitudes? If ventilation sizing method is chosen is the Sensible and Total time at Sensible/Total Ideal Loads Peak known (i.e., should they be reported, probably not)? For Air Flow Ideal Loads Peak, the time at max air flow is reported. For constant volume systems this is likely the first occurrence.
