### ISSUE TITLE
Generator Availability Schedule

### ISSUE THREAD

**Issue by taherahel** [NREL/EnergyPlus#7151]
Issue overview
--------------
`ElectricLoadCenter:Generators: Generator Availability Schedule Name`
The schedule that I input didn't work and my PVs works all the day

here is my code:

```
!- =========== ALL OBJECTS IN CLASS: SCHEDULE:COMPACT ===========

Schedule:Compact,

PV_ON,                   !- Name
Any,                     !- Schedule Type Limits Name
Through: 12/31,          !- Field 1
For: AllDays,            !- Field 2
Until: 11:00,            !- Field 3
0.0,                     !- Field 4
Until: 15:00,            !- Field 5
1.0,                     !- Field 6
Until: 24:00,            !- Field 7
0.0;                     !- Field 8
!- =========== ALL OBJECTS IN CLASS: GENERATOR:PVWATTS ===========

Generator:PVWatts,
PV-AA,                   !- Name
5,                       !- PVWatts Version
4160,                    !- DC System Capacity {W}
Standard,                !- Module Type
FixedOpenRack,           !- Array Type
0.14,                    !- System Losses
TiltAzimuth,             !- Array Geometry Type
25,                      !- Tilt Angle {deg}
204;                     !- Azimuth Angle {deg}
!- =========== ALL OBJECTS IN CLASS: ELECTRICLOADCENTER:INVERTER:PVWATTS ===========

ElectricLoadCenter:Inverter:PVWatts,
Inverter1,               !- Name
1.022,                   !- DC to AC Size Ratio
0.981;                   !- Inverter Efficiency
!- =========== ALL OBJECTS IN CLASS: ELECTRICLOADCENTER:GENERATORS ===========

ElectricLoadCenter:Generators,
PVList1,                 !- Name
PV-AA,                   !- Generator 1 Name
Generator:PVWatts,       !- Generator 1 Object Type
4160,                    !- Generator 1 Rated Electric Power Output {W}
PV_ON,                   !- Generator 1 Availability Schedule Name
;                        !- Generator 1 Rated Thermal toElectrical Power Ratio
!- =========== ALL OBJECTS IN CLASS: ELECTRICLOADCENTER:DISTRIBUTION ===========

ElectricLoadCenter:Distribution,
ELC1,                    !- Name
PVList1,                 !- Generator List Name
Baseload,                !- Generator Operation Scheme Type
0,                       !- Generator Demand Limit Scheme Purchased Electric Demand Limit {W}
,                        !- Generator Track Schedule Name Scheme Schedule Name
,                        !- Generator Track Meter Scheme Meter Name
DirectCurrentWithInverter,  !- Electrical Buss Type
Inverter1;               !- Inverter Name
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 9.0.1
 - Helpdesk ticket number 13171

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
This is definetely true, the availability schedule defined in `ElectricLoadCenter:Generators` is ignored for `Generator:PVWatts` (doesn't take any runFlag) and `Generator:Photovoltaics` if `Photovoltaic Performance Object Type = PhotovoltaicPerformance:Simple` (runFlag unused):  https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Photovoltaics.cc#L800:L802

(Note that with Generator:Photovoltaics SimplePV you can place an availability schedule on the ELCD's inverter and that'll work though.)

I can see how that would be surprising for a user.

I'm not sure what is the correct course of action here to close this issue:
* Should the availability schedule actually be enforced (risk of having large diffs in regression tests)?
* Should we keep ignoring the schedule but issue an informative warning for the user?

Thoughts @Myoldmopar @EnergyArchmage please?

**Comment by EnergyArchmage** [comment]
I think it was intentional, PV panels don't really have an off mode.  Could be changed to use the schedule if folks want it.

**Comment by jmarrec** [comment]
I understand the rationale yes. Would you recommend just sending a warning to the user?

**Comment by EnergyArchmage** [comment]
sure, a low-severity warning makes sense.
