### ISSUE TITLE
Change debug configuration to catch NaNs by default on Windows

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7152]
Issue overview
--------------
There are special instructions to catch NaNs on Windows [here](https://github.com/NREL/EnergyPlus/wiki/Debugging-Tips).
It would be nice to add this to the debug cmake configuration so that:
1. EnergyPlus gets set for /fp:strict
2. except sqlite needs /fp:precise
3. main.cc needs to be configurable or add a compiler flag to include the `unsigned int fp_control_state` line

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #7198
