### ISSUE TITLE
AirFlowNetwork output variables for Infiltration and Mixing Latent Gain/Loss are missing heat of vaporization

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7162]
Issue overview
--------------
As noted by @XuanLuoLBL in https://github.com/NREL/EnergyPlus/pull/7040#discussion_r254387314 the heat of vaporization term appears to be missing from the calculations for output variables:
AFN Zone Infiltration Latent Heat Gain Rate and similar (Gain Energy, Loss Rate, and Loss Energy) and AFN Zone Mixing Latent Heat Gain Rate and similar.

These are calculated [here and following](https://github.com/NREL/EnergyPlus/blob/a2bd500d83ad361e2860eba8a03d4d1beae2b0d1/src/EnergyPlus/AirflowNetworkBalanceManager.cc#L8179-L8186).

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.0.1-a2bd500d83ad361e2860eba8a03d4d1beae2b0d1 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@lgu1234 Also, these variables in `AirflowNetworkBalanceManager::AirflowNetworkReportVars` (`AirflowNetworkZnRpt`) are computed, but never used anywhere. Can these be deleted?
```
        Real64 MeanAirTemp;        // Mean Air Temperature {C}
        Real64 OperativeTemp;      // Average of Mean Air Temperature {C} and Mean Radiant Temperature {C}
        Real64 InfilHeatGain;      // Heat Gain {W} due to infiltration
        Real64 InfilHeatLoss;      // Heat Loss {W} due to infiltration
```

**Comment by lgu1234** [comment]
@mjwitte Yes. These report variables are computed and never reported. Here is my thought.

Remove first two variables, because we can get them from somewhere.
        Real64 MeanAirTemp;        // Mean Air Temperature {C}
        Real64 OperativeTemp;      // Average of Mean Air Temperature {C} and Mean Radiant Temperature {C}

Report the last two variables to provide more output information for users.

        Real64 InfilHeatGain;      // Heat Gain {W} due to infiltration
        Real64 InfilHeatLoss;      // Heat Loss {W} due to infiltration

**Comment by mjwitte** [comment]
@lgu1234 I think `InfilHeatGain` and `InfilHeatLoss` are being reported using [different variables](https://github.com/NREL/EnergyPlus/blob/e10cc09529476181172b86b238f1c822baaef1a8/src/EnergyPlus/AirflowNetworkBalanceManager.cc#L5165-L5236) so these can also be removed here.

**Comment by lgu1234** [comment]
@mjwitte I agree. Thanks for finding out. These 4 variables can be removed.
