### ISSUE TITLE
Unexpected HVAC energy w/ AirLoopHVAC attached to multiple zones

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7165]
Issue overview
--------------
I have performed a number of tests using the [Fix Zone Equipment Load Distribution PR](https://github.com/NREL/EnergyPlus/pull/7025). It fixes all of my tests except for one. 

[1.idf.txt](https://github.com/NREL/EnergyPlus/files/2842107/1.idf.txt)   [2.idf.txt](https://github.com/NREL/EnergyPlus/files/2842108/2.idf.txt)

The files are:
- 1.idf with 2 conditioned thermal zones, electric furnace AirLoopHVAC (hard-sized at 100% capacity/airflow
  - Zone 1: Furnace air terminal (SequentialLoad)
  - Zone 2: Furnace air terminal (SequentialLoad)
- 2.idf with 2 conditioned thermal zones, electric furnace AirLoopHVAC (hard-sized at 50% capacity/airflow)
  - Zone 1: Furnace air terminal + Ideal Loads Air System in each conditioned zone (UniformLoad)
  - Zone 2: Furnace air terminal + Ideal Loads Air System in each conditioned zone (UniformLoad)

I’m expecting 2.idf to use 50% of the heating/cooling energy compared to 1.idf, but the attached test files result in 55%. The results are perfect if it was a ZoneHVAC system instead or if I had a single conditioned thermal zone instead.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
@shorowit I am transitioning these files up to V9.6, doing them both at the same time, I get 1.idf to run. Then I run 2.idf and I see this. 

    ** Severe  ** <root>[ZoneHVAC:EquipmentList][finished basement Equipment List][equipment][1][zone_equipment_object_type] - "2" - Failed to match against any enum values.

1.idf

    ZoneHVAC:EquipmentList,
      finished basement Equipment List,  !- Name
      SequentialLoad,          !- Load Distribution Scheme
      ZoneHVAC:AirDistributionUnit,  !- Zone Equipment 1 Object Type
      ADU res fur electric finished basement direct air,  !- Zone Equipment 1 Name
      1,                       !- Zone Equipment 1 Cooling Sequence
      1;                       !- Zone Equipment 1 Heating or No-Load Sequence

2.idf

    ZoneHVAC:EquipmentList,
      living Equipment List,   !- Name
      UniformLoad,             !- Load Distribution Scheme
      ZoneHVAC:AirDistributionUnit,  !- Zone Equipment 1 Object Type
      ADU res fur electric living direct air,  !- Zone Equipment 1 Name
      1,                       !- Zone Equipment 1 Cooling Sequence
      1,                       !- Zone Equipment 1 Heating or No-Load Sequence
      ZoneHVAC:IdealLoadsAirSystem,  !- Zone Equipment 2 Object Type
      ideal heating system,    !- Zone Equipment 2 Name
      2,                       !- Zone Equipment 2 Cooling Sequence
      2;                       !- Zone Equipment 2 Heating or No-Load Sequence

So there is a UnitarySystem using load control with the control zone set as living zone. The UnitarySystem in 2.idf is exactly 1/2 of the heating capacity and air flow as specified for 1.idf. OK I would agree the 2.idf should use 1/2 of the energy of 1.idf, that is if the operating conditions are the same. The zone temperature in the living zone is nearly identical. However, the zone temperature in the basement is not the same which leads to a change in heat transfer of the living zone floor.

The basement is colder in 2.idf which would mean the living space load is slightly larger. Would this explain the difference you see here? Or would you like me to continue investigating?

![image](https://user-images.githubusercontent.com/5778156/130855816-c8f86c7d-7b4c-4f8b-b0cf-bda17b7a2e88.png)

Updated defect files:

[7165-2.idf.txt](https://github.com/NREL/EnergyPlus/files/7049555/7165-2.idf.txt)
[7165-1.idf.txt](https://github.com/NREL/EnergyPlus/files/7049556/7165-1.idf.txt)

**Comment by rraustad** [comment]
Well, I don't see a big difference in load. Maybe if you add IdealLoads to 1.idf and make sure that the zone conditions are the same it would be 50%? I wonder if zone humidity ratio has something to do with this.

![image](https://user-images.githubusercontent.com/5778156/130982738-9acf3cad-e092-48dc-961d-5eb690a6ff8c.png)

**Comment by rraustad** [comment]
Since the heater outlet temp is based on CpAir(win) then if these systems are not operating at the same conditions I would expect there to be differences in the results. Can I say that these differences should equate to 5%, not at this time.

HeatingCoils.cc

    void CalcElectricHeatingCoil()

        CapacitanceAir = PsyCpAirFnW(Win) * AirMassFlow;
        TempAirOut = TempAirIn + QCoilCap / CapacitanceAir;

This figure shows roughly the same inlet temperature but if I plot inlet temp only when the heater is on (otherwise T=0) I see that 2.idf heater is on while 1.idf heater is off. So a difference in operation. Same for humidity ratio except that the inlet w is more different.

![image](https://user-images.githubusercontent.com/5778156/130994110-90a448fb-68ff-46a3-ba31-6baea9478640.png)

I'll leave this here and let @shorowit decide whether to close or if further investigation is needed.

**Comment by shorowit** [comment]
I have to admit that this issue is no longer a priority given how we use EnergyPlus. (We used to model a conditioned basement as a separate thermal zone from the above-grade conditioned space, but now we model all conditioned space as one thermal zone.) So I am okay with closing this issue. It can always be reopened if someone else observes a similar issue.
