### ISSUE TITLE
AirloopHVAC:UnitarySystem should warn if all flow rates are zero and the unit has a fan in it

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7166]
Issue overview
--------------
User file had blanks for all of the `AirloopHVAC:UnitarySystem` cooling/heating/noload air flow rate fields. This resulted in no system operation, zero HVAC energy consumption, and no warnings in the error file. Seems if a unitary system has fan in it and all of the airflow rates are zero, this should prompt a warning. Likewise, if there's a cooling coil, should the cooling airflow rate be > 0? And for heating? Other combinations that can reliably throw a warning?

### Details
Some additional details for this issue (if relevant):

 - Version of EnergyPlus 9.0.1
 - Unmethours [37081](https://unmethours.com/question/37081/model-using-zero-heating-and-cooling/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached here
[scenario_1.idf.txt](https://github.com/NREL/EnergyPlus/files/2843094/scenario_1.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
I recall an issue where the field names where unknown when switching to JSON read of inputs. It may be that some of the previous warnings were not translated when this module was upgraded to OO.
