### ISSUE TITLE
Update Research Papers and Articles Page

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#7168]
The page:

https://energyplus.net/references

Weirdly covers papers related to EnergyPlus from 2009 to 2011 (probably the last time it was updated). 

Add newer and older references including foundational papers related to the development of EnergyPlus.

**Comment by mitchute** [comment]
This was updated about a year ago by @kflemin. Closing, but feel free to open again in another 10 years 😄
