### ISSUE TITLE
Fix Engineering Reference equation for undisturbed Kusuda Anchenbach model

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#7170]
Issue overview
--------------
The cosine term of the [current equation](https://github.com/NREL/EnergyPlus/blob/208212976a28f796b2181f8bef621f050518f96d/doc/engineering-reference/src/surface-heat-balance-manager-processes/undisturbed-ground-temperature-model-kusuda.tex#L8) describing the [Kusuda Anchenbach model](https://bigladdersoftware.com/epx/docs/8-4/engineering-reference/undisturbed-ground-temperature-model-kusuda.html) for undisturbed soil temperatures has a fraction with a "t" term in the numerator and "alpha * t" in the denominator, which is incorrect. It should have a "t" in the numerator, but just "tau" in the denominator based on the [original Kusuda research paper](https://apps.dtic.mil/dtic/tr/fulltext/u2/472916.pdf). The new fraction in the cosine term should be:

\frac{2\pi t}{\tau}

Or, the equation shown in the Engineering Reference should match the equation used in the [source code](https://github.com/NREL/EnergyPlus/blob/208212976a28f796b2181f8bef621f050518f96d/src/EnergyPlus/GroundTemperatureModeling/KusudaAchenbachGroundTemperatureModel.cc#L200) (but that has more terms to define / explain).

Tagging @mitchute since they worked on this part source code last.

**Comment by jmarrec** [comment]
Not sure it warrants its own issue and should probably be added to #7160 instead

**Comment by mitchute** [comment]
@jmarrec Do you want to add this to #7666, or should I create a separate PR for this?

**Comment by jmarrec** [comment]
@mitchute I started addressing it, only to realize that it's been fixed by @RKStrand already in https://github.com/NREL/EnergyPlus/commit/c3840d1583a2880f5bf631e8315de7098a99b427#diff-bd925b30348217846c62bf3e16382616
