### ISSUE TITLE
IDF editor does not highlight invalid fields in ConnectorList object

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7172]
Issue overview
--------------
Fields are not highlighted in the ConnectorList object in the IDF editor when the referenced objects do not exist. The following image has a ConnectorList object referencing Connector:Splitter and Connector:Mixer objects, but there are zero of those objects in the IDF file. (highlighting added by user)

![failed to highlight](https://user-images.githubusercontent.com/39242689/52746313-14148600-2f96-11e9-9511-fe393931b59c.PNG)

### Details
Some additional details for this issue (if relevant):
 - Platform Windows 10
 - Version of EnergyPlus 9.0

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@mldichter The IDF Editor validity checks are all driven by codes in the idd file. If you find any more, please add to this issue.

**Comment by mldichter** [comment]
@mjwitte Please merge with the below issue as well then. Sorry for the bother.

https://github.com/NREL/EnergyPlus/issues/7161

**Comment by mjwitte** [comment]
Not a bother, but I will note that the IDD is not complete for these types of cross-references, so there are likely other cases which may or may not be easily addressed.
