### ISSUE TITLE
Incorrect handling of weather file leap year flag in some situations

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#7173]
Issue overview
--------------
In some situations, setting the leap year flag in the weather file will cause a leap year to appear for non-leap years. Testing with 5ZoneAirCooled.idf and an EPW file with the leap year flag set to 'Yes' ended up adding an incorrect leap day for a variety of different situations, but not for simulations beyond a year in length. So something untoward is going on with handling the flag out of the EPW.

### Details
Some additional details for this issue (if relevant):
 - Version 9.0.1
 - Helpdesk ticket ID 13165

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Fixed via #7199
