### ISSUE TITLE
EMS actuator response delay with ElectricEquipment, OtherEquipment

### ISSUE THREAD

**Issue by ghost** [NREL/EnergyPlus#7179]
Issue overview
--------------
Our project team attempted to use an EMS program to change the electric input power to an equipment object. Initially we tried the OtherEquipment object, then the ElectricEquipment object. In both cases, the EMS actuator response is one timestep (e.g., 1 min) later than it should be, regardless of the calling point used. This problem occurs whether we use a power actuator or a schedule actuator. In contrast, HVAC equipment actuators respond in the correct timestep, so we don't know why the non-HVAC equipment objects' actuators are delayed.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 7 (also on Mac)
 - Version of EnergyPlus: 9.0.1
 - Unmethours link or helpdesk ticket number: n/a

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (see link below)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

[in_test.zip](https://github.com/NREL/EnergyPlus/files/2881265/in_test.zip)

**Comment by mjwitte** [comment]
*(Lots of detail here just to document this for future reference.)*

Internal gains are evaluated in `ManageInternalHeatGains` which is called by `InitSurfaceHeatBalance` which is called by `ManageSurfaceHeatBalance` which is called by `ManageHeatBalance` which is called by `ManagerSimulation` for every zone timestep.

Calling point `BeginTimestepBeforePredictor` is called from `ManageHVAC` which is called by `CalcHeatBalanceAir` which is called by `ManagerAirHeatBalance` which is called by `ManageSurfaceHeatBalance` *after* `InitSurfaceHeatBalance`. So none of the old calling points happen early enough to affect internal gains in the same timestep. This is also true for other things like daylighting and solar gains.

In [v9.1.0](https://github.com/NREL/EnergyPlus/releases/tag/v9.1.0), two new EMS calling points were added in #7177 which shows as a defect fix in the v9.1.0 changelog (should have also been tagged as a new feature). The two new calling points are `BeginZoneTimestepBeforeInitHeatBalance` and `BeginZoneTimestepAfterInitHeatBalance`. Both of these happen before `ManageSurfaceHeatBalance` so either one will work for this application.

Also note that `Minute` is not always an exact integer (you can see this in the verbose edd output), so this is only activating the equipment at 00:02, not 01:02 or any other hour of the day. So, if you plan to use the minute of the hour as a trigger, you'll need to allow some tolerance (1.9 < Minute < 2.1) or something like that.
