### ISSUE TITLE
IDD Ouput:Variable field Variable Name miss retaincase

### ISSUE THREAD

**Issue by Lefort-Antoine** [NREL/EnergyPlus#7181]
Issue overview
--------------
The IDD says that the "Variable Name" field of the Output:Variable object it not "retaincase" 
It's seems to be an error. No eso output file is generate if variable name are change to lower case.

### Details
Some additional details for this issue:
 - Version of EnergyPlus 9.0.1

**Comment by mjwitte** [comment]
This has been addressed for v9.1 in https://github.com/NREL/EnergyPlus/pull/7031. Just to be clear, the IDD is correct, output variable names are not case-sensitive.
