### ISSUE TITLE
Energy Meters report is screwy when simulating with leap days

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7182]
Issue overview
--------------
Run the attached IDF file using the attached EPW that includes a leap day. The Energy Meters report in the html file will look like this:

![image](https://user-images.githubusercontent.com/5861765/53122105-03728b80-3513-11e9-823e-72f7445e739c.png)

If you modify the EPW to turn off the leap day (e.g., change "HOLIDAYS/DAYLIGHT SAVINGS,Yes,0,0,0" to "HOLIDAYS/DAYLIGHT SAVINGS,No,0,0,0" in the EPW header), the results are fine:

![image](https://user-images.githubusercontent.com/5861765/53122325-8f84b300-3513-11e9-934e-e209477bcf2c.png)

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/2886375/in.idf.txt)
[in.epw.txt](https://github.com/NREL/EnergyPlus/files/2886376/in.epw.txt)

cc @joseph-robertson @jasondegraw 

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10
 - Version of EnergyPlus: 9.0.1

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by dareumnam** [comment]
I am taking a look at fixing this defect and I think I need to do a regression test after fixing the code. Could I use the epw file you uploaded for my regression test?

**Comment by shorowit** [comment]
@dareumnam Yes, that's fine.
