### ISSUE TITLE
Array bounds error in SizePIU

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7183]
Issue overview
--------------
User reported several types of unexplained error from the same file - different results on consecutive runs. Running with v9.1 debug build reveals an array bounds error [here](https://github.com/NREL/EnergyPlus/blob/f88eb67c7fc1539d9827bbde166762af34c833ee/src/EnergyPlus/PoweredInductionUnits.cc#L1464) in SizePIU. This line should be 
```
TermUnitSizing(CurTermUnitSizingNum).DesHeatingLoad = DesCoilLoad;
```

Note that this file fails on an assert in [DataSurfaces](https://github.com/NREL/EnergyPlus/blob/f88eb67c7fc1539d9827bbde166762af34c833ee/src/EnergyPlus/DataSurfaces.cc#L606), so need to comment that out to test this in debug build. Not sure what the issue is with that.

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v9.1.0-f88eb67c7f
 - Helpdesk ticket 13180

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added in EnergyPlusDevSupport\DefectFiles, use San Antonio TX TMY3 (but any weather would trigger the issue).
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by MatthewSteen** [comment]
Thanks @mjwitte.

**Comment by Myoldmopar** [comment]
The two oldest ones and the newest one mentioned there appear to have been addressed.  #539 looks to just have a workaround, possibly not fixed.

**Comment by mjwitte** [comment]
Doh! Red means *closed*. Never mind any of those. Darn related issue prompting . . .

**Comment by jmarrec** [comment]
Are you handling this one @mjwitte? Obviously the fix itself seems straightforward, but it's going to need a unit test.

**Comment by mjwitte** [comment]
I haven't yet. It would be great to get this into v9.1. Thanks.

**Comment by jmarrec** [comment]
@mjwitte could you upload the file prior to your transition of it to 9.1? 

All the `ZoneHVAC:EquipmentLists` have missing fields (the Zone Equipment Sequential Cooling/Heating Fractions). I'd rather not fix that manually if I can avoid it. thanks!

**Comment by mjwitte** [comment]
@jmarrec v9.0 file is there now.

**Comment by jmarrec** [comment]
When User files crashes:

```
PIUNum = 110, named=O.L09-10.W.OFFICE CORE.TZ - SPIU, CurZoneEqNum=206, CurTermUnitSizingNum=144
```

`TermUnitSizing` has a capacity of 205, so logically when you try to get `TermUnitSizing(206)` you get an out of bound error.
