### ISSUE TITLE
Feature Request: Modify InternalMass object to reference Zonelist objects

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7184]
Allow the InternalMass object to take a ZoneList object name or Zone object name in the "Zone Name" field. 

InternalMass,
    ,                !- Name
    ,                !- Construction Name
    ,                !- Zone Name
    ;                !- Surface Area {m2}

**Comment by mldichter** [comment]
Additionally, this object would be nice to accept a Zonelist object too.

ZoneVentilation:WindandStackOpenArea

![zonelist wanted](https://user-images.githubusercontent.com/39242689/53275844-8598b680-36b1-11e9-916a-5f5475ad3153.PNG)

**Comment by Myoldmopar** [comment]
Closed via #7312
