### ISSUE TITLE
PsyTwbFnTdbWPb: humidity ratio calculation does not include case for TWetBulb < 0

### ISSUE THREAD

**Issue by dmey** [NREL/EnergyPlus#7187]
This may not be an issue per se but I just wanted to report it given that I have noticed differences between the results of wet-bulb temperature from dry-bulb temperature, humidity ratio, and pressure calculated by EnergyPlus and [PsychroLib](https://github.com/psychrometrics/psychrolib#readme) when running tests for a separate model I am working with. The following snippet:

https://github.com/NREL/EnergyPlus/blob/d830726d9ea59782c5f19a6ceab71219106e7713/src/EnergyPlus/Psychrometrics.cc#L661-L663

shows that the humidity ratio is calculated for cases where the temperature is below and above zero in the same way. The ASHRAE Handbook however also gives a formulae with different constants for cases where the wet-bulb temperature is below zero as also done in PsychroLib -- see [this](https://github.com/psychrometrics/psychrolib/blob/517686dc7f5c6caef5a79c653dfb2ed563dec7bf/src/fortran/psychrolib.f90#L573-L578). This difference seem to amount to a max wet-bulb temperature difference of approximately 0.7 degree C close to zero, exponentially decreasing to approximately 0.1 at about -30 degree C dry bulb temperature. If you think that this may be worth addressing, I am happy to send you a PR for the additional case when the temperature is below zero.

**Comment by rraustad** [comment]
This does seem problematic especially for heat pumps operating in heating mode where the outdoor wet-bulb temperature is used to evaluate performance curves. Low temperature heat pumps can operate well below 0C (dry-bulb) where wet-bulb temperature would be negative.

From the NOAA handbook ftp://ftp.ncdc.noaa.gov/pub/data/EngineeringWeatherData_CDROM/engwx/handbook.pdf

![image](https://user-images.githubusercontent.com/5778156/54449051-9920c580-4723-11e9-9606-7c62751cd6e2.png)
