### ISSUE TITLE
HotFixes needed after IOFreeze

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7191]
Issue overview
--------------

I'm in the process of updating OpenStudio to use E+ 9.1.0 based off of release [v9.1.0-IOFreeze](https://github.com/NREL/EnergyPlus/tree/v9.1.0-IOFreeze) and hitting various problems that are E+ related during testing (C++ unit tests and OpenStudio-resources regression tests).

This issue aims to provide a place to centralize this, and have the possibility to upload supporting Defect files.

**List:**

* `ZoneHVACEquipmentList` transition rules aren't working after new IDD extensible groups added in #7171 *(Fixed in #7189)*
* `GatherHeatEmissionReport` fails when you have refrigeration objects after #7040, see Defect file `EnergyPlusDevSupport/DefectFiles/7000s/7191/GatherHeatEmissionReport_Failure.idf` *(Fixed in #7192)*

### Details
Some additional details for this issue (if relevant):

 - Version of EnergyPlus: [v9.1.0-IOFreeze](https://github.com/NREL/EnergyPlus/tree/v9.1.0-IOFreeze)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Addressed in #7189 and #7192.
