### ISSUE TITLE
Table output file incorrectly reports capacity of water-to-water heat pumps

### ISSUE THREAD

**Issue by mhinds2** [NREL/EnergyPlus#7195]
Table output file incorrectly reports capacity of water-to-water heat pumps
--------------
In the Table output file, it appears that the capacity of water-to-water heat pumps is incorrectly reported.

In the Central Plant section of the Table output file, there is a column with heading "Nominal Capacity". 
 When central plant objects of the class HeatPump:WaterToWater:EquationFit:Cooling are present, it appears that the values appearing in this column do not properly reflect the IDF field "Reference Cooling Capacity" in that object class, but rather the IDF field "Reference Cooling Power Consumption".

Therefore, in the case of water-to-water heat pumps, the value appearing in the "Nominal Capacity" column in the Table output file is not actually the Nominal Capacity, but rather the Nominal Capacity divided by the COP.

We also observed all of the above with HeatPump:WaterToWater:EquationFit:Heating.  Please correct me if I am wrong?  Otherwise please confirm our observations of this error?

Thanks in advance, Matt

### Details
 - Windows 10
 - EnergyPlus v. 8.7.0

----

**Edit Julien M:**

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: `testfiles/WWHPSimpleAuto.idf` exhibits this behavior
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
@mhinds2 I can confirm what you're seeing, thanks for reporting it.

I'll fix it shortly.
