### ISSUE TITLE
kiva autocalculated deep ground depth is negative

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7200]
Issue overview
--------------
I took the example files for the kiva objects, ZoneCoupledKivaSlab.idf and ZoneCoupledKivaBasement.idf, and changed the Site:Location, SizingPeriod:DesignDay objects, and weather file for each of the CA climate zones. There are some strange errors for the "autocalculated deep ground depth" in some of the simulations. Obviously, something is wrong. Here is a [google drive link](https://drive.google.com/file/d/1Nm2_AsXd1qZGBtVL6xUwWin_4F2naVD7/view?usp=sharing) to the files.

ZoneCoupledKivaSlab.idf

    Foundation:Kiva="SLAB FOUNDATION", the autocalculated deep ground depth (1.328 m) is shallower than foundation construction elements (1.500 m)
    
    Foundation:Kiva="SLAB FOUNDATION", the autocalculated deep ground depth (-0.919 m) is shallower than foundation construction elements (1.500 m)

ZoneCoupledKivaBasement.idf

    Foundation:Kiva="BASEMENT FOUNDATION", the autocalculated deep ground depth (1.328 m) is shallower than foundation construction elements (3.425 m)
    
    Foundation:Kiva="BASEMENT FOUNDATION", the autocalculated deep ground depth (3.883 m) is shallower than foundation construction elements (3.425 m)
    
    Foundation:Kiva="BASEMENT FOUNDATION", the autocalculated deep ground depth (-0.919 m) is shallower than foundation construction elements (3.425 m)

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - energyplus 9.0
 - [Unmethours link](https://unmethours.com/question/37606/kiva-autocalculated-deep-ground-depth-0919-m/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by nealkruis** [comment]
This is intended behavior. See my response on [Unmet Hours](https://unmethours.com/question/37606/kiva-autocalculated-deep-ground-depth-0919-m/?answer=37608#post-id-37608).

The warning message should be changed, and we should add a warning if both autocalculate and a deep ground temperature are selected (see comments in Unmet Hours).
