### ISSUE TITLE
IDF Updater from 8.4 to 9.1 to OpenStudio

### ISSUE THREAD

**Issue by jasminaburek** [NREL/EnergyPlus#7201]
I was able to successfully update the orginal idf file (https://www.energycodes.gov/development/commercial/prototype_models)  from 8.0 to 8.4 using the old IDF updater. I have the latest version of IDF Updater and EnergyPlus and the IDF Updater shows a lot of errors during the update. I try to run the model in EnergyPlus but it shows errors as well. I ultimately want to be able to open the .idf file in OpenStudio. Thank you
[EnergyPlus.zip](https://github.com/NREL/EnergyPlus/files/2932418/EnergyPlus.zip)
 for your help. I have included files in zip.

**Comment by mjwitte** [comment]
There is a known problem with the v9.0.1 transition programs. See https://github.com/NREL/EnergyPlus/issues/7010 for a workaround.
