### ISSUE TITLE
CeilingDiffuser convection algorithm does not revert to natural convection algorithm when the system is off

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#7208]
Issue overview
--------------
The [documentation](https://bigladdersoftware.com/epx/docs/9-0/input-output-reference/group-simulation-parameters.html#field-algorithm-000) states:

> To avoid discontinuities in surface heat transfer rate calculations, all of correlations have been extrapolated beyond the lower limit of the data set (3 ACH) to a natural convection limit that is applied during the hours when the system is off.

However, in the source code, this only appears in [CalcCeilingDiffuserInletCorr](https://github.com/NREL/EnergyPlus/blob/a310a424e4ea98bb8183137f0fd5f1012a6bd918/src/EnergyPlus/ConvectionCoefficients.cc#L4430), a function that is never called ([though it looks like it was intended for use if it could be accommodated](https://github.com/NREL/EnergyPlus/blob/a310a424e4ea98bb8183137f0fd5f1012a6bd918/src/EnergyPlus/ConvectionCoefficients.cc#L4358)).

Instead, EnergyPlus uses [CalcCeilingDiffuserIntConvCoeff](https://github.com/NREL/EnergyPlus/blob/a310a424e4ea98bb8183137f0fd5f1012a6bd918/src/EnergyPlus/ConvectionCoefficients.cc#L4267), which never calls a natural convection algorithm.

### Checklist
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Note that` CalcCeilingDiffuserIntConvCoeff` is used only if the full zone uses ceiling diffuser. See #6539. And also, ` CalcCeilingDiffuserIntConvCoeff` was reformulated to use leaving temp (zone air temp, instead of the supply air inlet temp), so this function seems rather intentional as-is. @RKStrand ?

**Comment by nealkruis** [comment]
@mjwitte you're suggesting that each of the surface specific functions (e.g., `CalcFisherPedersenCeilDiffuserFloor`) should separately implement the natural convection fallback so that it works outside of the full-zone context? I like that approach.

**Comment by mjwitte** [comment]
Not necessarily, just making sure you're aware that the other functions get used when convection is selected by the adaptive master or has been specified using `SurfaceProperty:ConvectionCoefficients` or `SurfaceProperty:ConvectionCoefficients:MultipleSurface`.

**Comment by RKStrand** [comment]
@nealkruis @mjwitte I'd need to take a closer look at this at some point and get back to you both as it has been a little while since I worked on this last.  I'll get back to you both when I've had a chance to analyze this with my full attention (unless @nealkruis has already fixed it in the meantime).

**Comment by nealkruis** [comment]
@RKStrand I haven't made any fixes yet, but it would be great to get this fixed for this release. I feel like I have enough understanding to at least propose a fix. Then maybe you can help review it?

**Comment by RKStrand** [comment]
@nealkruis I'm a bit out of the loop at the moment, but I would be happy to take a look at whatever you end up doing for a fix.

**Comment by nealkruis** [comment]
@RKStrand Another related issue is how the ACH is calculated. At the zone level, `CalcCeilingDiffuserIntConvCoeff` applies a MinFlow that is not applied in `EvaluateIntHcModels`. I made a change to use the same ACH calculation for both, but it broke a unit test. My suggestion is to change the expected result of the unit test to apply the MinFlow. I didn't see any other diffs related to this change.

@EnergyArchmage FYI.
