### ISSUE TITLE
Update LCC to use 2019 NIST supplement

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#7218]
The 2019 EIA energy price projections `encost19.txt` file will be available to make the `LCCusePriceEscalationDataSet2019.idf` at...

* https://www.energy.gov/eere/femp/building-life-cycle-cost-programs

**Comment by MatthewSteen** [comment]
The current [LCCusePriceEscalationDataSet2018.idf](https://github.com/NREL/EnergyPlus/blob/develop/datasets/LCCusePriceEscalationDataSet2018.idf) uses `PropaneGas` for the resource field, which should be changed to `Propane`.

**Comment by MatthewSteen** [comment]
@dareumnam looks like the data is available. 

* https://www.energy.gov/sites/prod/files/2019/05/f62/encost19.txt

I also added a Python script to do it in #6374 (see below) if that's useful and the eppy dependency has been approved by the team (@Myoldmopar).

* https://github.com/NREL/EnergyPlus/blob/aa2389f1ae948f8c1d556ddf67cab797a6ac6365/scripts/dev/update_nist_escalation.py

**Comment by dareumnam** [comment]
@MatthewSteen Thanks for the links, Matt. I will take a look and fix this issue.

**Comment by mjwitte** [comment]
Closed via #7404
