### ISSUE TITLE
Incorrect Pump in Energyplus Example File

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7220]
Issue overview
--------------
In the IceStorage-Parallel.idf enegyplus example file, there is a warning of the wrong pump object being used.

```
   ** Warning ** SetupCommonPipes: detected variable speed pump on supply inlet of TwoWayCommonPipe plant loop
   **   ~~~   ** Occurs on plant loop name = CHILLED WATER LOOP
   **   ~~~   ** The common pipe model does not support varying the flow rate on the primary/supply side
   **   ~~~   ** The primary/supply side will operate as if constant speed, and the simulation continues
```

### Details
 - EnergyPlus 9.0

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Fixed via #7362
