### ISSUE TITLE
Clarification needed for where a CoilSystem:Cooling:DX:HeatExchangerAssisted can be placed

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7222]
Issue overview
--------------

From the I/O reference [CoilSystem:Cooling:DX:HeatExchangerAssisted](https://bigladdersoftware.com/epx/docs/9-0/input-output-reference/group-heating-and-cooling-coils.html#coilsystemcoolingdxheatexchangerassisted), I seem to understand that this object doesn't necesarilly have to be wrapped inside a `AirLoopHVAC:Unitary(:XXX)` object:

> This compound object is used in place of where a DX cooling coil object would normally be used by itself.

Nevertheless, unlike the similar `CoilSystem:Cooling:Water:HeatExchangerAssisted`, it **does not** have the `\reference` fields indicating it can be placed on a branches etc:

```
CoilSystem:Cooling:Water:HeatExchangerAssisted,
       A1 , \field Name
       \required-field
       \reference CoolingCoilsWater 
       \reference-class-name validBranchEquipmentTypes
       \reference validBranchEquipmentNames
       \reference-class-name validOASysEquipmentTypes
       \reference validOASysEquipmentNames
  A2 , \field Heat Exchanger Object Type
```

```
CoilSystem:Cooling:DX:HeatExchangerAssisted,
  A1 , \field Name
       \required-field
       \reference CoolingCoilsDX
       \reference CoolingCoilsDXSingleSpeed
       \reference CoolingCoilsDXMultiModeOrSingleSpeed
  A2 , \field Heat Exchanger Object Type
```

I also couldn't find any example files where the `CoilSystem:Cooling:DX:HeatExchangerAssisted` is placed outside of a `AirLoopHVAC:UnitaryXXX`, but that doesn't mean it shouldn't.

Is this an IDD omission or should the I/O ref be clarified?

Ref: https://github.com/NREL/OpenStudio/pull/3449

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I dug into the source code and found this in SimAirServing Zones

https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/SimAirServingZones.cc#L1267:L1270

> HX Assisted coils are not allowed on a branch at this time

I'm not sure if the course of action (and the renaming of this issue) from there is to:
* Documentation update: Update the I/O
* Enhancement Request/Bug Fix: allow this object on a branch

**Comment by rraustad** [comment]
It's allowed on the main branch inside of the CoilSystem:Cooling:DX parent.

    CoilSystem:Cooling:DX,
    A6,  \field Cooling Coil Object Type
        \type choice
        \required-field
        \key Coil:Cooling:DX:SingleSpeed
        \key CoilSystem:Cooling:DX:HeatExchangerAssisted
        \key Coil:Cooling:DX:TwoSpeed
        \key Coil:Cooling:DX:TwoStageWithHumidityControlMode
        \key Coil:Cooling:DX:VariableSpeed
        \key Coil:Cooling:DX:SingleSpeed:ThermalStorage

**Comment by mjwitte** [comment]
@jmarrec Where specific coil types can be used has changed over time. The IDD \key choices for object type are accurate. The IDD \reference and \object-list tags *should* be consistent with that. `CoilSystem:Cooling:DX:HeatExchangerAssisted` must always be inside a parent object, never directly on a branch  or OA equipment list, because it has no controls. `CoilSystem:Cooling:Water:HeatExchangerAssisted` also has not controls, but it can be controlled (not well) by a `Controller:WaterCoil` so that's why it's acceptable directly on a branch or OA equipment list, but in that case the HX will always be active (not controllable, I'm 99% certain on that).

**Comment by mjwitte** [comment]
@jmarrec So my point was to say it's very likely that docs for the parent objects are up-to-date with all of the coil types they support, but the docs for the various coils may not be up-to-date for the coils or compound coils like this.

**Comment by jmarrec** [comment]
Added to https://github.com/NREL/EnergyPlus/issues/7160

Thanks for feedback @rraustad  and @mjwitte

**Comment by mjwitte** [comment]
@jmarrec I think you meant DX, not Water [here](https://github.com/NREL/EnergyPlus/issues/7160#issuecomment-472466602)?

**Comment by jmarrec** [comment]
I do, thanks for the catch. I've been typing both a LOT for the past day and a half...

**Comment by RKStrand** [comment]
@jmarrec @mjwitte @rraustad So, what would you all suggest as an appropriate clarification in the documentation?  I'm not sure what text would clarify this limitation.  Here is a possible suggestion:

This compound object is used in place of where a DX cooling coil object would normally be used by itself.  However, unlike other similar objects like CoilSystem:Cooling:Water:HeatExchangerAssisted, it cannot be used directly on branches.

I'm not sure that this really clarifies the situation or simply makes it more muddled.  Thoughts?

**Comment by mjwitte** [comment]
@RKStrand How about this: 

This compound object is used in the same way as a DX cooling coil object. It cannot be used directly on a branch. It must be contained within a parent object such as  CoilSystem:Cooling:DX or AirloopHVAC:UnitarySystem and others which list CoilSystem:Cooling:DX:HeatExchangerAssisted as a valid cooling coil option.

**Comment by RKStrand** [comment]
@mjwitte Sounds good to me.  I have put your suggested text in exactly as shown above.  Thanks!  Want to review #7160 ? :)
