### ISSUE TITLE
Different number of daylighting reference points in zone can cause crash in DaylightingManager

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7223]
Issue overview
--------------
User file has multiple daylighting objects with different number of reference points. Simulation crashed in debug when a zone with more than 1 reference point was encountered.
This part of the code does not account for different number of reference points (NREFPT) when allocating the tmp* arrays. The allocation uses the first zones number of daylighting reference points to allocate these arrays. I added the +1 to get around the crash while debugging a file.

    void  DayltgInteriorIllum(int &ZoneNum) // Zone number

        NREFPT = ZoneDaylight(ZoneNum).TotalDaylRefPoints;

        // Three arrays to save original clear and dark (fully switched) states'
        //  zone/window daylighting properties.
        if (DayltgInteriorIllum_firstTime) {
            int const d1(max(maxval(Zone, &ZoneData::NumSubSurfaces), maxval(ZoneDaylight, &ZoneDaylightCalc::NumOfDayltgExtWins)));
            tmpIllumFromWinAtRefPt.allocate(d1, 2, NREFPT + 1);
            tmpBackLumFromWinAtRefPt.allocate(d1, 2, NREFPT + 1);
            tmpSourceLumFromWinAtRefPt.allocate(d1, 2, NREFPT + 1);
            DayltgInteriorIllum_firstTime = false;
        }

Assert failure occurred here:

        // Added TH 1/21/2010 - save the original clear and dark (fully switched) states'
        //  zone daylighting values, needed for switachable glazings
       tmpIllumFromWinAtRefPt(loop, IS, IL) = ZoneDaylight(ZoneNum).IllumFromWinAtRefPt(loop, IS, IL);
       tmpBackLumFromWinAtRefPt(loop, IS, IL) = ZoneDaylight(ZoneNum).BackLumFromWinAtRefPt(loop, IS, IL);
       tmpSourceLumFromWinAtRefPt(loop, IS, IL) = ZoneDaylight(ZoneNum).SourceLumFromWinAtRefPt(loop, IS, IL);

Here's a snippet of 2 daylighting objects:

### Zone with 1 ref point:

    Daylighting:Controls,
    Thermal Zone: 000_SEG DaylightingControls, !- Name
    Thermal Zone: 000_SEG,                  !- Zone Name
    ,                                       !- Daylighting Method
    ,                                       !- Availability Schedule Name
    Continuous,                             !- Lighting Control Type
    0.3,                                    !- Minimum Input Power Fraction for Continuous or ContinuousOff Dimming Control
    0.2,                                    !- Minimum Light Output Fraction for Continuous or ContinuousOff Dimming Control
    ,                                       !- Number of Stepped Control Steps
    ,                                       !- Probability Lighting will be Reset When Needed in Manual Stepped Control
    000_SEG daylighting control,            !- Glare Calculation Daylighting Reference Point Name
    0,                                      !- Glare Calculation Azimuth Angle of View Direction Clockwise from Zone y-Axis {deg}
    ,                                       !- Maximum Allowable Discomfort Glare Index
    ,                                       !- DElight Gridding Resolution {m2}
    000_SEG daylighting control,            !- Daylighting Reference Point Name 1
    1,                                      !- Fraction of Zone Controlled by Reference Point 1
    500;                                    !- Illuminance Setpoint at Reference Point 1 {lux}

    Daylighting:ReferencePoint,
    000_SEG daylighting control,            !- Name
    Thermal Zone: 000_SEG,                  !- Zone Name
    -3.65386581735227,                      !- X-Coordinate of Reference Point {m}
    -0.24523522484613,                      !- Y-Coordinate of Reference Point {m}
    0.7874;                                 !- Z-Coordinate of Reference Point {m}

### Zone with 2 ref points:

    Daylighting:Controls,
    Thermal Zone: 000_RESTAURANTE DaylightingControls, !- Name
    Thermal Zone: 000_RESTAURANTE,          !- Zone Name
    ,                                       !- Daylighting Method
    ,                                       !- Availability Schedule Name
    ContinuousOff,                          !- Lighting Control Type
    0.3,                                    !- Minimum Input Power Fraction for Continuous or ContinuousOff Dimming Control
    0.2,                                    !- Minimum Light Output Fraction for Continuous or ContinuousOff Dimming Control
    ,                                       !- Number of Stepped Control Steps
    1,                                      !- Probability Lighting will be Reset When Needed in Manual Stepped Control
    000_RESTAURANTE daylighting control,    !- Glare Calculation Daylighting Reference Point Name
    0,                                      !- Glare Calculation Azimuth Angle of View Direction Clockwise from Zone y-Axis {deg}
    ,                                       !- Maximum Allowable Discomfort Glare Index
    ,                                       !- DElight Gridding Resolution {m2}
    000_RESTAURANTE daylighting control,    !- Daylighting Reference Point Name 1
    1,                                      !- Fraction of Zone Controlled by Reference Point 1
    500,                                    !- Illuminance Setpoint at Reference Point 1 {lux}
    Daylighting Control 1,                  !- Daylighting Reference Point Name 2
    0,                                      !- Fraction of Zone Controlled by Reference Point 2
    500;                                    !- Illuminance Setpoint at Reference Point 2 {lux}

    Daylighting:ReferencePoint,
    000_RESTAURANTE daylighting control,    !- Name
    Thermal Zone: 000_RESTAURANTE,          !- Zone Name
    -6.56237537382633,                      !- X-Coordinate of Reference Point {m}
    -0.306084574094293,                     !- Y-Coordinate of Reference Point {m}
    0.7874;                                 !- Z-Coordinate of Reference Point {m}

    Daylighting:ReferencePoint,
    Daylighting Control 1,                  !- Name
    Thermal Zone: 000_RESTAURANTE,          !- Zone Name
    -6.51704177922846,                      !- X-Coordinate of Reference Point {m}
    -1.06464183917781,                      !- Y-Coordinate of Reference Point {m}
    0.762;                                  !- Z-Coordinate of Reference Point {m}

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (EnergyPlusDevSupport\DefectFiles\7223\)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
@jasondegraw this seems like a very simple fix. Are you available?

**Comment by mjwitte** [comment]
@rraustad Yep, those static arrays need to be allocated to `maxNumRefPtInAnyZone` instead of `NREFPT` if I'm following this correctly.

**Comment by mjwitte** [comment]
Hmm, and it seems like `DaylIllum` should only be allocated once, and why not make all of these variables static or module-level and allocate them only once? Oh my, there's all sorts of allocates in this function.

**Comment by rraustad** [comment]
@jmarrec what time is it over there? This look interesting?

**Comment by rraustad** [comment]
Trying a simple fix in PR #7227.

**Comment by jmarrec** [comment]
@rraustad It was 2:26 AM when you asked what time it was (I'm in the Paris timezone, UTC+1 and soon +2 on 3/31) :)
I'm sorry I haven't gotten back to you today until right now, been swamped. I see you've done the work already, but please don't hesitate to tag me again on stuff like this in the future!

**Comment by rraustad** [comment]
That sounds about right for the time, we are UTC-5 and it was around 8 or 9 PM here. I was just looking for someone who knew this stuff better than I did. Glad to hear your another resource. It's 9:43 PM here so you won't see this until tomorrow.
