### ISSUE TITLE
IDF editor displays strange characters

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7241]
Issue overview
--------------
See red circled text in the following image.

![strange chars](https://user-images.githubusercontent.com/39242689/54766413-76296200-4bb8-11e9-876e-57627d743300.PNG)

### Details
 - Windows 10
 - EnergyPlus 9.0

### Checklist
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by dareumnam** [comment]
@mldichter I guess these strange characters are not matters of EnergyPlus, but these come from the IDF file you used for this defect. If you open that IDF file with a text editor, you can see those comments (starting with !) from the IDF. If you confirm this, we can close this issue.

**Comment by mldichter** [comment]
You're right. It's an apostrophe that is causing the problem. The IDF is from here
https://www.energycodes.gov/development/commercial/prototype_models
which is a bunch of Commercial Prototype Building Models made by the DOE.

Please close the issue.

![Capture](https://user-images.githubusercontent.com/39242689/65898502-8a6bca00-e366-11e9-80dd-b272b9cdd008.PNG)
