### ISSUE TITLE
Linux sh installer is broken in 9.1.0

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7256]
Issue overview
--------------

The linux .sh install script isn't behaving correctly due to the lack of the extra level (https://github.com/NREL/EnergyPlus/pull/7148), it's installing everything at `/usr/local/` instead of `/usr/local/EnergyPlus-9-1-0` like it would have before.

With the official 9.1.0 install script `EnergyPlus-9.1.0-08d2e308bb-Linux-x86_64.sh`, even if you specify `/usr/local/EnergyPlus-9-1-0` (after `mkdir` it), it's going to mess up a few things during the install, and all the symlinks in `/usr/local/bin` are broken:

```
Extracting, please wait...
Unpacking to directory /usr/local/EnergyPlus-9-1-0 was successful.
chmod: cannot access '/usr/local/EnergyPlus-9-1-0/EnergyPlus-9-1-0/PreProcess/IDFVersionUpdater/': No such file or directory
mv: cannot stat '/usr/local/EnergyPlus-9-1-0/EnergyPlus-9-1-0/energyplus.1': No such file or directory
./EnergyPlus-9.1.0-08d2e308bb-Linux-x86_64.sh: 102: ./EnergyPlus-9.1.0-08d2e308bb-Linux-x86_64.sh: cannot create /usr/local/EnergyPlus-9-1-0/EnergyPlus-9-1-0/uninstall.sh: Directory nonexistent
./EnergyPlus-9.1.0-08d2e308bb-Linux-x86_64.sh: 127: ./EnergyPlus-9.1.0-08d2e308bb-Linux-x86_64.sh: cannot create /usr/local/EnergyPlus-9-1-0/EnergyPlus-9-1-0/uninstall.sh: Directory nonexistent
chmod: cannot access '/usr/local/EnergyPlus-9-1-0/EnergyPlus-9-1-0/uninstall.sh': No such file or directory
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Ubuntu
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.1.0 official, current develop too
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: N/A
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by samuelduchesne** [comment]
I concur...

**Comment by cgoodman11** [comment]
Does this issue apply to EnergyPlus 9.2.0 for Linux? I am having issues installing EnergyPlus on my Linux virtual machine for use with Volttron. When I run the downloaded executable, when it ends, it says there was an error opening the file due to invalid characters.

**Comment by gopal86** [comment]
Hi, I am facing the same issue after installing [EnergyPlus 9.1.0](https://github.com/NREL/EnergyPlus/releases/tag/v9.1.0) from the sh file . Can someone help me with it?

**Comment by jmarrec** [comment]
Just use E+ 9.2 if you can.

For 9.1, Just use the tar.gz file and place it in `/usr/local/EnergyPlus-9-1-0` then recreate the symlinks by hand...
