### ISSUE TITLE
Typo in I/O reference? 

### ISSUE THREAD

**Issue by DavidHollman** [NREL/EnergyPlus#7257]
In section 1.1.3 of the EnergyPlus Input/Output Reference, version 9.1, it says:

> Note that the terms “**output variable**” and “**output variable**” (accessed by the
> Output:Variable and/or Output:Meter objects) are used interchangeably in this document.

I have bolded the duplicated term “output variable” which seems to be repeated redundantly. Is the second one meant to say something else?

**Comment by rraustad** [comment]
Searching for " variable" in the IO Ref shows that "output variable" is typically used. I do see places where "variable" refers to Output:Variable.  I didn't search through the whole document. So I would think this should be "output variable" or "variable"... But this really isn't needed so that whole sentence could be removed. I'd rather see output variable be used consistently throughout but it's not a big deal.

For example here:

    1.9.2.15 Zone Air System Sensible Heating Energy [J]

    Zone Air System Sensible Heating (and Cooling) Energy (and Rate) all report the heating or cooling
    delivered by the HVAC system to a zone. These values are calculated by multiplying the supply air
    mass flow rate by the difference between the supply air temperature and the zone air temperature.
    This does not always indicate the operation of heating or cooling coils. For example, cooling will be
    reported if the supply air is cooled due to the introduction of outside air, even if all coils are off.
    Note that these variables are calculated at the system timestep. When reported at the “detailed” reporting
    frequency, these variable will never show heating and cooling both in the same system timestep.
    If reported at a frequency less than “Detailed” (for example, Hourly) values may appear in both the
    heating and cooling variable for the same hour if the system cooled the zone for part of the reporting
    period and heated the zone for another part of the reporting period.


Looking in the IDD at the Output:Meter memo also shows a typo, "A list of" is repeated.

    Output:Meter,
       \memo Each Output:Meter command picks meters to be put onto the standard output file (.eso) and
       \memo meter file (.mtr). Not all meters are reported in every simulation. A list of
       \memo a list of meters that can be reported are available after a run on
       \memo the meter dictionary file (.mdd) if the Output:VariableDictionary has been requested.

**Comment by RKStrand** [comment]
@rraustad Are you planning on taking on this issue or is it open for others to pick up?

**Comment by rraustad** [comment]
I was not, just talked through description here for future reference. I think this is the type of thing that would typically be combined with other document updates.

**Comment by RKStrand** [comment]
@rraustad Yes, it could be combined with #7160 and whoever does that one can pick this up too.  I'll put a link to this over in #7160 so that it doesn't get lost.

**Comment by RKStrand** [comment]
Correcting the originally noted text to "variable" and "output variable".  Will also correct a typo that @rraustad noted in the IDD and also a typo in the I/O Ref section that he noted above.  Handling this separately from #7160 and lumping it together with other doc mods I have been working on.
