### ISSUE TITLE
LifeCycleCost:RecurringCost isn't applied to correct year

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#7272]
Issue overview
--------------
The following LCC objects produce a cost 25 years from the Base Date (2019, 2044) rather than the Service Date (2020, 2045) when the `Start of Costs` field is set to `ServicePeriod`.

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/3087097/in.idf.txt)

    LifeCycleCost:Parameters,
      Life Cycle Cost Parameters,  !- Name
      EndOfYear,               !- Discounting Convention
      ConstantDollar,          !- Inflation Approach
      0.03,                    !- Real Discount Rate
      ,                        !- Nominal Discount Rate
      ,                        !- Inflation
      April,                   !- Base Date Month
      2019,                    !- Base Date Year
      March,                   !- Service Date Month
      2020,                    !- Service Date Year
      50,                      !- Length of Study Period in Years
      0,                       !- Tax rate
      None;                    !- Depreciation Method

    LifeCycleCost:RecurringCosts,
      25-year Fabric Building cost,  !- Name
      Replacement,             !- Category
      27591000.0,              !- Cost
      ServicePeriod,           !- Start of Costs
      25,                      !- Years from Start
      ,                        !- Months from Start
      25,                      !- Repeat Period Years
      0;                       !- Repeat Period Months

![image](https://user-images.githubusercontent.com/8397034/61242652-8800b900-a703-11e9-93b6-ed37c26aef82.png)

---

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (9.1.0)
 - Unmethours link or helpdesk ticket number (NA)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by YanfeiNREL** [comment]
@MatthewSteen Hey, i tried to recreate this issue, and what i got for the "Present Value By Year" table are from  2019 until 2068, which is 50 years span. Would you please give more details for this issue?

**Comment by MatthewSteen** [comment]
@yanfeinrel the issue isn't the length of study period (table was truncated) it's when the recurring cost occurs, which is in year 2044 instead of 2045 (25 years from the *base date year* of 2019 instead of 25 years from the *service* date year of 2020). It looks to me like EnergyPlus is using the base date year instead of the service date year.

**Comment by YanfeiNREL** [comment]
![PresentValue](https://user-images.githubusercontent.com/43475933/61324056-be573a80-a7ce-11e9-90ee-8803f60344dc.png)
Here is what i got for PResent-Value

**Comment by YanfeiNREL** [comment]
@MatthewSteen Thanks for the clarification. Here is what i got after fixing the bug.
However, I have some uncertainty before closing this: does the "Present-Value" start from base date or service date? Right now it starts from service date. 
 
![Capture](https://user-images.githubusercontent.com/43475933/61324526-e2ffe200-a7cf-11e9-886c-f0ec4dd22ef3.PNG)

**Comment by MatthewSteen** [comment]
It looks like you changed the IDF because the table goes from March 2020 to 2069 instead of April 2019 to 2068 like mine.

**Comment by YanfeiNREL** [comment]
@MatthewSteen  I didn't make changes to the IDF. I just changed the line of code where this Present-Value table is being produced. (starting from service date year).

**Comment by MatthewSteen** [comment]
Ok, then to answer your question above, no I don't think the PV should start from the service date. 

* https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/lifecyclecost-parameters.html#field-base-date-month

**Comment by YanfeiNREL** [comment]
Thanks for the detailed information, which were very helpful to fix this defect. @MatthewSteen 
I made improvements and the results are good now. Please see the output file for details. I used your input IDF file. I made a few other service-dates and they are all good.

[eplustbl.zip](https://github.com/NREL/EnergyPlus/files/3408364/eplustbl.zip)

**Comment by Myoldmopar** [comment]
@YanfeiNREL the issue will remain open until the pull request is reviewed and merged.  Thanks for offering the fix, we'll get it reviewed soon.

**Comment by YanfeiNREL** [comment]
okay. Thanks.

**Comment by JasonGlazer** [comment]
@MatthewSteen after reviewing the issue you reported and @YanfeiNREL fix, I believe that there is no bug at all. Let me explain and see if you concur. The base date that you are using is April 2019 and the Service Date is March 2020. The months are very important. The Present Value by Year table that shows the total present value starting that month and year for that month and the following 11 months. As you can see from the top of the table, April 2019 is the first year and represents all the costs from April 2019 to March 2020.  So, 25 years after March 2020 is March 2045 but that is counted in the year starting April 2044 and going for the next 11 months. 

To double-check this, if you make the service date start on April 2020, you will see that cost ends up in the year starting April 2045.

I hope you are following my logic here. Please let me know if you agree. 

BTW, your file took so long to run that I copied all your LCC objects into the 5ZoneEconomicsTariffAndLifeCycleCosts.idf for testing see here:
[5ZoneEconomicsTariffAndLifeCycleCosts-7272-7401.idf.txt](https://github.com/NREL/EnergyPlus/files/3486915/5ZoneEconomicsTariffAndLifeCycleCosts-7272-7401.idf.txt)

**Comment by MatthewSteen** [comment]
@JasonGlazer thanks for the clarification, that makes sense. I'll close and trust that the code aligns with NIST's methodology. Perhaps some additional detail or an example in the I/O documentation would be helpful for other users. Regarding run time, the model is small and only took 3.5 min on my machine.
