### ISSUE TITLE
Error when running PlantApplicationGuide_Example2

### ISSUE THREAD

**Issue by Fan-Feng** [NREL/EnergyPlus#7277]
Issue overview
--------------
I encountered an error when I ran the "PlantApplicantGuide_example2". MY E+ version is 9.0. The error shown is as follow. 
************************************************
** Severe  ** FindRootSimpleController: Controller error for controller = "VAV WITH REHEAT_COOLC_CONTROLLER"
   **   ~~~   **  Environment=CHICAGO ANN CLG .4% CONDNS DB=>MWB, at Simulation time=07/21 00:00 - 00:10
   **   ~~~   **   Controller function is inconsistent with user specified controller action = Reverse action
   **   ~~~   **   Actuator will be set to maximum action
   **   ~~~   ** Controller control type=Temperature
   **   ~~~   ** Controller temperature setpoint = 13.80 [C]
   **   ~~~   ** Controller sensed temperature = 34.74 [C]
   **   ~~~   ** Controller actuator mass flow rate set to 2.89 [kg/s]
   **   ~~~   ** Controller actuator temperature = 34.92 [C]
   **   ~~~   **   Note: Chilled water coils should be reverse action and the entering chilled
   **   ~~~   **         water temperature (controller actuator temperature) should be below the setpoint temperature
   **   ~~~   **   Note: Hot water coils should be normal action and the entering hot
   **   ~~~   **         water temperature (controller actuator temperature) should be above the setpoint temperature
*************************************************

But after I check this E+ idf file, I found the control action for this Cooling Coil is correct.  The tricky part is that when I ran the same model using E+ 8.5, I didn't get this error. So I'd like to know if there is some bug with E+9.0.

**Comment by jmarrec** [comment]
@faithefeng I can't reproduce this with Energyplus 9.0.1 (nor with current develop). Are you sure you ran the file `ExampleFiles/PlantApplicationsGuide_Example2.idf` from the **same version** as the energyplus executable you used? Did you modify it in any way?

**Comment by jmarrec** [comment]
This is getting stale, and without further input from @faithefeng I cannot reproduce. So I'm going to close this issue, which we can reopen if we get more information to reproduce the bug.
