### ISSUE TITLE
AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass copressor shuts off causing unmet cooling hours

### ISSUE THREAD

**Issue by chandangsharma** [NREL/EnergyPlus#7283]
Issue overview
--------------
AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass compressor turns off when there is still cooling demand. Schedule, Minimum Outlet Air Temperature During Cooling Operation are checked to not cause compress shutdown. There are no EMS in the model. EnergyPlus V8.5 and 9.1 are used to run the model. Attached file illustrates the defect.

Problem seems to be in `GetZoneLoads` in `HVACUnitaryBypassVAV.cc`. `CurDeadBandOrSetback` is checked for `ZoneNum` as opposed to `CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum)`. After making the following changes, the issue is resolved.

```
            if (!CurDeadBandOrSetback(ZoneNum)) {
                if (ZoneLoad > 0.0 && std::abs(ZoneLoad) > SmallLoad) {

```
changed to 
```
            if (!CurDeadBandOrSetback(CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum))) {
                if (ZoneLoad > 0.0 && std::abs(ZoneLoad) > SmallLoad) {

```
Workaround: If there is only 1 AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass object in the input, reorganize the Zone objects in the input file (idf) so that all controlled zones come before any uncontrolled zones. There is no workaround if there are more than 1 AirLoopHVAC:UnitaryHeatCool:VAVChangeoverBypass in the input file.

[Office_Proposed.zip](https://github.com/NREL/EnergyPlus/files/3134119/Office_Proposed.zip)

**Comment by chandangsharma** [comment]
@Myoldmopar Hello Edwin, is this all the information needed from my end? Thanks.

**Comment by rraustad** [comment]
Chandan, I just looked. You are correct, and any use of the loop counter ZoneNum should always be CBVAV(CBVAVNum).ControlledZoneNum(ZoneNum). I see a few places just above your change that also need the same change. The workaround is to order the zones in the same order as the control zones (e.g., put a plenum or any uncontrolled zones last as ordered in the idf).

**Comment by rraustad** [comment]
Well, not always. These CBVAV(CBVAVNum).ZoneSequenceCoolingNum(ZoneNum) needs to use the loop counter.

**Comment by rraustad** [comment]
Select plots in the defect file show the system is now working correctly.

![image](https://user-images.githubusercontent.com/5778156/57094079-97b05a00-6cdd-11e9-804f-b83f5a2f3c76.png)

**Comment by rraustad** [comment]
See #7288.
