### ISSUE TITLE
HVACTemplate:Zone:BaseboardHeat Rated Average Water Temperature needs better value

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7297]
Issue overview
--------------
HVACTemplate:Zone:BaseboardHeat writes a hard-wired default value of 87.78C for Rated Average Water Temperature in the ZoneHVAC:Baseboard:RadiantConvective:Water object. This value impacts the sizing of the baseboard UA and it should be consistent with the hot water loop design temperature. In this case, the HVACTemplate default hot water supply temp is 82C, so the baseboard will never see an average water temp of 87.78.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.1.0
 - Helpdesk ticket number 15167

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by matthew-larson** [comment]
Looks like that hasn't been fixed in the latest develop, I can take care of this one.
