### ISSUE TITLE
EMS Application Guide CurrentEnvironment variable documentation

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/EnergyPlus#7303]
The EMS Application Guide documentation includes this description for the CurrentEnvironment EMS variable:

Variable Name | Value
--- | ---
CurrentEnvironment | Integer index for the current environment period (sizing periods and run periods accumulate throughout the run)

Please include which integers correspond to the sizing periods and run periods in the documentation. 1 = Design Day, 2 =~ Design Run Period, 3 = Weather Run Period, from the eplusout-sql reference.

**Comment by mjwitte** [comment]
@mdahlhausen I am not sure there is a direct correspondence to environment type. My understanding of the current doc is that the first environment that is simulated (no matter what the type) will be CurrentEnvironment=1, the next will be 2, etc. Watch the value of this with different combinations of Run Simulation for Sizing Periods and Run Simulation for Weather File Run Periods to confirm.

**Comment by mdahlhausen** [comment]
@mjwitte you're correct.  Just checked and the CurrentEnvironment variable is matched to the EnvironmentPeriodIndex, not the EnvironmentType in the EnvironmentPeriods table of the eplusout.sql.

It'd be nice to have some direction in the EMS Application Guide directing a user to that table so they can find the correct integer to use for the CurrentEnvironment variable in their application.
