### ISSUE TITLE
IDFVersionUpdater Breaks Fenestration Objects Between v8.8 and v8.9

### ISSUE THREAD

**Issue by mattdoiron** [NREL/EnergyPlus#7306]
Issue overview
--------------
IDFVersionUpdater breaks `FenestrationSurface:Detailed` objects when updating from v8.8 to v8.9. The last one or more vertices are discarded. When the subsequent IDFVersionUpdater is run to get to v9.0 or v9.1, the missing vertices are sometimes interpreted as an invalid object and the `FenestrationSurface:Detailed` are deleted completely. Other times, if three vertices remain, triangular windows will result and the file will run normally without any issues (but with incorrect results). This silent failure variation has come back to bite us on several occasions.

### Details
Occurs when seemingly any file is updated from v8.8 to v8.9. The issues happens if the v8.9 updater is used or if the v9.0 or v9.1 updaters are used.

Defect files are attached and include the pre- and pos-updated example file that comes with EnergyPlus v8.8: [5ZoneWarmestVFD.zip](https://github.com/NREL/EnergyPlus/files/3209343/5ZoneWarmestVFD.zip)

**Comment by mjwitte** [comment]
This is a known issue (#7010) with the transition programs in the v9.0 (and v9.0.1) install packages. Start over using the transitions in v9.1.

**Comment by mjwitte** [comment]
Here's the v8.9 file transitioned from v8.8 using the v9.1 IDFVersionUpdater. 

[5ZoneWarmestVFD_V890_MJW.idf.txt](https://github.com/NREL/EnergyPlus/files/3213820/5ZoneWarmestVFD_V890_MJW.idf.txt)

**Comment by mattdoiron** [comment]
Thanks! We've tried this with v9.1 and it appears to work. We'll use this version whenever we want to update.
