### ISSUE TITLE
Outdoor air node conditions are not used correctly for zone local environment and for airflow network

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7308]
Issue overview
--------------
User file attempts to adjust infiltration heat gain by using EMS to change the temperature of an `OutdoorAir:Node` which is used as the external node on an `AirflowNetwork:MultiZone:Surface`. The node temperature changes as expected, but there is little or no impact on the infilration heat gain/loss. Investigation into this revealed several issues:

1. Calculation of [AFN Zone Infiltration Sensible Heat Gain/Loss](https://github.com/NREL/EnergyPlus/blob/7a7082a357ad875ac3f0d9dd66564a85cae454d2/src/EnergyPlus/AirflowNetworkBalanceManager.cc#L8252-L8272) uses `Zone(ZN1).OutDryBulbTemp` instead of the external node temp. This appears to be just a reporting issue - these values aren't used in the heat balance.

2. The [AFN heat balance calculation](https://github.com/NREL/EnergyPlus/blob/7a7082a357ad875ac3f0d9dd66564a85cae454d2/src/EnergyPlus/AirflowNetworkBalanceManager.cc#L6835-L6838) uses `Node.OutAirDryBulb`. Why? Why not `Node.Temp`? Don't understand why `Node.OutAirDryBulb` is even a variable - there's no output:variable associated with it. `SetOANodeValues` sets `Node(NodeNum).Temp = Node(NodeNum).OutAirDryBulb` so it's probably ok, but why confuse things by having two dry bulb temp variables on the same node structure?

3. So, tried to use `ZoneProperty:LocalEnvironment` to associated the same `OutdoorAir:Node` with the zone in question (R01). There was some impact on infiltration heat gain/loss, but the reported values for R01:Zone Outdoor Air Drybulb Temperature are all zero. This is partly due to [this code for local environment](https://github.com/NREL/EnergyPlus/blob/7a7082a357ad875ac3f0d9dd66564a85cae454d2/src/EnergyPlus/HeatBalanceManager.cc#L5335-L5346) which is grabbing from the outdoor air node schedules rather than taking the OA node conditions directly.  This block should look like the [equivalent one for surfaces](https://github.com/NREL/EnergyPlus/blob/7a7082a357ad875ac3f0d9dd66564a85cae454d2/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L448-L454).

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Helpdesk ticket number 15158.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added in EnergyPlusDevSupport\DefectFiles
...SmartWindow-TVent1VeryCold-ZoneOANode.csv - Col A shows "R01:Zone Outdoor Air Drybulb Temperature [C](Hourly)" always zero.
...SmartWindow and ..._SmartWindow-TVent1VeryCold - Col F "R01:Zone Air Heat Balance Outdoor Air Transfer Rate" is similar in both, but there should be much more heat loss in "VeryCold" file.  These both actuate the outdoor air node only.
...SmartWindow-TVent1VeryCold-ZoneOANode-ActuateBoth - Col F shows much more heat loss.

After this is fixed, I would expect these three files to have the same results:
..SmartWindow-TVent1VeryCold
...SmartWindow-TVent1VeryCold-ZoneOANode.csv 
...SmartWindow-TVent1VeryCold-ZoneOANode-ActuateBoth (this one shouldn't change with this fix, 90% certain of this?)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Closed via #7447.
