### ISSUE TITLE
FluidCooler:SingleSpeed cannot autosize

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7318]
Issue overview
--------------
1. User file with autosized FluidCooler:SingleSpeed fails to reject any heat. Stepped through `SizeFluidCooler` and found that `SimpleFluidCooler(FluidCoolerNum).HighSpeedFluidCoolerUAWasAutoSized` is false [here](https://github.com/NREL/EnergyPlus/blob/e5e9977e455951877332892a2062c093dfee08d6/src/EnergyPlus/FluidCoolers.cc#L1228-L1229) which causes the fluid cooler capacity to be zero.

`GetFluidCoolerInput` needs [this code](https://github.com/NREL/EnergyPlus/blob/e5e9977e455951877332892a2062c093dfee08d6/src/EnergyPlus/FluidCoolers.cc#L453-L455) added above in the singlespeed input processing.

2. Also, setting the capacity method to NominalCapacity causes a fatal error if the UA value is not blank - that should be a warning or simply silently ignored.
```
   ** Severe  ** FluidCooler:SingleSpeed= "FLUIDCOOLER_SINGLESPEED 1". Nominal fluid cooler capacity has been specified and design fluid cooler UA is being autosized.
   **   ~~~   ** Design fluid cooler UA field must be left blank when nominal fluid cooler capacity performance input method is used.
   **  Fatal  ** Errors found in getting fluid cooler input.
```
3. This file fails in debug with a floating point underflow [here](https://github.com/NREL/EnergyPlus/blob/e5e9977e455951877332892a2062c093dfee08d6/src/EnergyPlus/HVACInterfaceManager.cc#L695). Yet another `exp(<largenegativenumber>)` issue? Could we trap just overflows and allow underflows to go through - would they be zero?

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.2.0-e5e9977e45
 - Helpdesk ticket number 15178.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles - 
190517_FluidCooler_Original-MJW - see col CJ FLUIDCOOLER_SINGLESPEED 1:Cooling Tower Heat Transfer Rate [W](Each Call) - always zero. After fix, there should be non-zero values, similar to 190517_Original-MJW which uses a cooling tower.
190517_FluidCooler_Original-MJW-HardSizeNomCapacity-Fatal - this shows the overly strict input error.

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #7354
