### ISSUE TITLE
EP-Compare is outdated for modern macs

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7324]
Issue overview
--------------

The EP-Compare is a outdated to run on modern mac. Fixing the permissions doesn't help really.

```
chmod +x /Applications/EnergyPlus-9-1-0/PostProcess/EP-Compare/EP-Compare.app/Contents/MacOS/EP-Compare
```

If I chmod +x I still can't launch it by clicking on the App (which shows a O/ sign).: "You can't open the application "EP-Compare" because it may be damaged or incomplete"

If I launch it from the terminal, it complains but eventually launches anyway. I did briefly also get a messagebox saying the app needed an update from the developpers.

```
./EP-Compare
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/Exceptions.plist'
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Common/ChunkCompression.cpp:49: Error: unsupported compressor 8
/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleFSCompression/AppleFSCompression-96.60.1/Libraries/CompressData/CompressData.c:353: Error: Unknown compression scheme encountered for file '/System/Library/CoreServices/CoreTypes.bundle/Contents/Library/AppExceptions.bundle/Exceptions.plist'
```

I see only binary files, not development files in https://github.com/NREL/EnergyPlus/tree/develop/bin/EP-Compare/Run-Mac/EP-Compare.app/Contents. **No clue where the source is.**

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
@JasonGlazer Do you have the source somewhere to check if simply recompiling would suffice please?

**Comment by JasonGlazer** [comment]
@jmarrec I do have the source code but I don't have an updated license on the compiler. Do you want access to the code?
