### ISSUE TITLE
Positively pressurized ventilation system

### ISSUE THREAD

**Issue by AbdellaAlzade** [NREL/EnergyPlus#7335]
Issue overview
--------------
I am facing an issue that I hope that you have an answer for, would be really appreciated if you were able to help me with it.
I am aiming to design a ventilation system for building in E+ with a positive pressure (The supply air should be more than the exhaust), as in surgeries and operations rooms. I tried everything so far, modelling the pressure controller, zone exhaust fan etc. But the E+ kept compensating and balancing the pressure difference in every trial.
Is it possible to model it by the EnergySystemManager class?

May you have any tips to create such a model or know whether it is even possible or not in E+.

Thanks in adavance.

**Comment by mjwitte** [comment]
Support questions belong on unmethours.com or energyplus.helpserve.com or energyplus-support@gard.com
