### ISSUE TITLE
sqlite TimestepType is backwards

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7342]
Issue overview
--------------
Noticed in various sqlite tables that `TimestepType` is backwards. Zone timestep variables are tagged as "HVAC System" and HVAC variables are tagged as "Zone".
![image](https://user-images.githubusercontent.com/4991075/59634086-91eac880-9113-11e9-8394-f034de1f98ec.png)

[SQLite::timestepTypeName](https://github.com/NREL/EnergyPlus/blob/f43e577cc4735e48577bdca46a73cfd09404f746/src/EnergyPlus/SQLiteProcedures.cc#L1274-L1287) is where the error is.

[OutputProcessor::ValidateIndexType](https://github.com/NREL/EnergyPlus/blob/f43e577cc4735e48577bdca46a73cfd09404f746/src/EnergyPlus/OutputProcessor.cc#L1145-L1151) shows the correct mapping. 1=Zone, 2=HVAC.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.1-https://github.com/NREL/EnergyPlus/commit/f43e577cc4735e48577bdca46a73cfd09404f746
 - Noticed this while looking at sql tables in Excel using method given in this [bldg-sim post](http://lists.onebuilding.org/pipermail/bldg-sim-onebuilding.org/2019-June/000785.html)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added - any example file with sql output, e.g. RefBldgLargeOfficeNew2004_Chicago
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Instead of just fixing the method, I propose to use a single enum throughout energyplus to avoid this kind of mistake down the line and make it clearer as to what's happening.

This is going to involve a lot of file changes, but I'm willing to give it a shot.

**Comment by mjwitte** [comment]
Yes, that would be good to do at some point. But given where we are in the release cycle, it seems best to just fix this and plan for an enum pass through the code shortly after the next release when we have fewer open PRs.

**Comment by jmarrec** [comment]
@mjwitte I did see your comment, but when I was already about 70% in adding the enum... Tests results in #7415 seem pretty clean though, so hopefully this won't be too much of a hassle reviewing.
Just fixing this the "easy" way would also pose the same problems of having to modify the existing unit tests etc.

**Comment by mjwitte** [comment]
Well, we'll have to see how it looks. @Myoldmopar will make the call whether this can go forward now or wait until after release.
