### ISSUE TITLE
ASHWAT_Thermal not converging causes simultaneous heating and cooling load error

### ISSUE THREAD

**Issue by aaron-boranian** [NREL/EnergyPlus#7345]
Issue overview
--------------
The EquivalentLayerWindow.idf example file showcases how to use various `WindowMaterial:###:EquivalentLayer` objects combined into assemblies with the `Construction:WindowEquivalentLayer` object. The `WindowMaterial:Gap:EquivalentLayer` objects are all set to "Sealed" for the **Gap Vent Type** input field. The example file is set up for only simulating design days, but also running the annual run period yields no warnings or errors. Changing the innermost gap equivalent layers to use the "VentedIndoor" option instead of "Sealed" also runs without warnings or errors. However, when the "VentedOutdoor" option is applied to the outermost gap equivalent layers, the annual simulation fails (no warnings or errors over the design days). 

The first severe error is related to [ASHWAT_Thermal radiation analysis not converging](https://github.com/NREL/EnergyPlus/blob/f43e577cc4735e48577bdca46a73cfd09404f746/src/EnergyPlus/WindowEquivalentLayer.cc#L5469), but that message doesn't stop the simulation. The final severe error is related to an [unanticipated combination of heating and cooling loads](https://github.com/NREL/EnergyPlus/blob/f43e577cc4735e48577bdca46a73cfd09404f746/src/EnergyPlus/ZoneTempPredictorCorrector.cc#L4298), which is the message that does stop the simulation. However, various components of the message are set to "NAN" and don't give much help to the user. This seems like a bug - perhaps divide by zero somewhere results in NAN and triggers this message?

Defect IDF and resulting ERR file after running a simulation with Atlanta EPW are attached. There is also an [Unmet Hours post](https://unmethours.com/question/38902/naturally-vented-double-skin-glazing-model/) with the same series of severe errors using the equivalent layer objects.

On this topic, it would be helpful if the time stamp of when the ASHWAT_Thermal error occurs was included in the error file.

### Details
Some additional details for this issue (if relevant):
 - Version 9.1.0 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

[EquivalentLayerWindow-outdoor-vented-err.txt](https://github.com/NREL/EnergyPlus/files/3303128/EquivalentLayerWindow-outdoor-vented-err.txt)
[EquivalentLayerWindow-outdoor-vented-idf.txt](https://github.com/NREL/EnergyPlus/files/3303129/EquivalentLayerWindow-outdoor-vented-idf.txt)

**Comment by Myoldmopar** [comment]
Fixed with #7363
