### ISSUE TITLE
epJSON schema object EnergyManagementSystem:Program change to allow blank lines, breaks from idd/epJSON compatibility convention

### ISSUE THREAD

**Issue by SchildCode** [NREL/EnergyPlus#7347]
Issue overview
--------------
As a result of pull request #6832 (merged with #6601) small changes were made to the **EnergyManagementSystem:Program** object in the schema in July 2018, between E+ version v.8.9.0 and v.9.0.0. Changes included the IDD schema (_idd/Energy+.idd.in_) and the epJSON schema script (_scripts/dev/generate_epJSON_schema/modify_schema.py_). As a result of this change, the new epJSON schema now requires *"lines"* which is the name of the extended group; see code below. This requirement is not properly mirrored in the the _legacy_idd_ part of the epJSON schema, and breaks the established practice that only names of field listed in *legacy_idd:{fields:[]}* or *legacy_idd:{extensibles[]}* are required, not names of extended groups. Take for example, object *"Wall:Detailed"*, for which the epJSON schema explicitly requires all 3 extensible fields (*vertex_x_coordinate, vertex_y_coordinate and vertex_z_coordinate*), not the extension group name (*vertices*). Over 50 objects in the schema follow this same convention. I bring up this issue because it has consequences for future coding of E+ user interfaces that can read both legacy .idf and new epJSON input files. Do we not want a consistent schema, and to maintain backwards-compatibility between the legacy IDD and epJSON, at least until support for IDD is dropped in version v.10.0.0? I suggest a re-evaluation of the code changes that were done July 2018 (#6832) in line with this goal. 

### **Original epJSON object schema in v.8.9.0:**
        "EnergyManagementSystem:Program": {
            "patternProperties": {
                ".*": {
                    "type": "object", 
                    "properties": {
                        "lines": {
                            "items": {
                                "required": [
                                    "program_line"
                                ], 
                                "type": "object", 
                                "properties": {
                                    "program_line": {
                                        "type": "string"
                                    }
                                }
                            }, 
                            "type": "array"
                        }
                    }
                }
            }, 
        }, 

### **Corrupt object schema in v.9.1.0:**
        "EnergyManagementSystem:Program": {
            "patternProperties": {
                ".*": {
                    "required": [     |
                        "lines"       | <= This requirement breaks with established practice in the schema. Remove it.
                    ],                |
                    "type": "object", 
                    "properties": {
                        "lines": {
                            "minItems": 1, 
                            "items": {
                                "type": "object", 
                                "properties": {
                                    "program_line": {
                                        "type": "string"
                                    }
                                }
                            }, 
                            "type": "array"
                        }
                    }
                }
            }, 
        }, 

## Checklist
 - [x] See pull request #6832
 - [x] The change to _scripts/dev/generate_epJSON_schema/modify_schema.py_ has been commented
 - [ ] Ticket added to Pivotal for defect (development team task)

**Comment by Myoldmopar** [comment]
@mbadams5 would you take a look at this issue and determine if it is something worth pursuing?  Otherwise it will be closed.  Thanks!
