### ISSUE TITLE
Vented Cavity

### ISSUE THREAD

**Issue by gracesuri** [NREL/EnergyPlus#7348]
Attempting to model an exterior vented cavity. 

Unable to use the vented cavity since I have both exterior and interior insulation. Assembly is:
-SBS Bitumen 
-DensDeck
-Polyiso (Rigid Insulation)
-Plywood
-2" Vented cavity
-Roof Insulation
-Gypsum

If I model the vented cavity as an airgap, I am unable to see the effects of air movement, If I model as an exterior vented cavity, I am unable to model the polyiso. I attempted to model it as a small 2" zone, and used AFN to model airflow through the walls, however because the zone is so small, it leads to a malformed zone error. 

I have tried changing the zone size, but its still an issue. I have modeled it as 10" in height, and that works. Results wont be as accurate because my cavity is 2" not 10".

Please advise.

**Comment by mjwitte** [comment]
@gracesuri Please post this question at unmethours.com or the EnergyPlus helpdesk at energyplus.helpserve.com . Issues are for reporting defects or requesting new features.
