### ISSUE TITLE
SurfaceControl:MovableInsulation doesn't catch wrong Material types

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7355]
Issue overview
--------------

The I/O ref specifies that the `SurfaceControl:MovableInsulation` `Material Name accepts (see https://github.com/jmarrec/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-advanced-surface-concepts.tex#L230:L232)

> This field refers to a material layer (e.g., Material, Material:NoMass, or WindowMaterial:Glazing; transparent layers are only valid for outside movable insulation) via its user assigned name

If you set it to a `WindowMaterial:SimpleGlazingSystem` E+ doesn't catch that, and you'll end up with a floating point exception in [InitIntSolarDistribution#L3552](https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L3552) because `HeatBalanceMovableInsulation::EvalOutsideMovableInsulation`  will set AbsExt to zero [here](https://github.com/jmarrec/EnergyPlus/blob/develop/src/EnergyPlus/HeatBalanceMovableInsulation.cc#L135).

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #7387
