### ISSUE TITLE
Fan models need to protect against negative fan power due to bad EMS override values

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7365]
Issue overview
--------------
User file failed with a fatal psychrometric error due to very cold temperatures in the HVAC system. The problem comes from negative values set by EMS for fan pressure , which caused negative values for fan power and fan heat gain, leading to very cold node temperatures, which then cascaded until the psych error tripped.

All of the fan models need a trap for this. I'd be find with simply putting a max(power,0.0) around the first power values calculated in each fan model - just clip it silently without warning.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.1.0-08d2e308bb
 - Helpdesk ticket number 15206

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added in EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
@mjwitte Confirmed the defect. Modified the code for simple fan per your suggestion, now the defect file runs to completion.  Is it helpful to add a minimum limit of zero for Pressure Rise input field in the fan objects? Currently it does not have any limit.

**Comment by mjwitte** [comment]
@Nigusse The idd has limits of 0 for the Pressure Rise in the simple fans, so that's ok. Fan:SystemModel has a limit of >0.0 - that will be a problem when we transition away the old fans. 

@EnergyArchmage is there a reason for >0.0 for fan Pressure Rise in Fan:SystemModel?

**Comment by Nigusse** [comment]
@mjwitte I just looked at "Pressure Rise" of five fan objects (Fan:ConstantVolume, Fan:VariableVolume, Fan:OnOff, Fan:ZoneExhaust and FanPerformance:NightVentilation) of the IDD in current develop, all five of them do not have limits.

**Comment by mjwitte** [comment]
Oh - you're right - I was searching too quickly. And none of them check that on input?

**Comment by EnergyArchmage** [comment]
There is this check in code, so having the IDD limit probably helps avoid hitting it.  

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACFan.cc#L464

**Comment by Nigusse** [comment]
@EnergyArchmage Shouldn't we give users the option to set the fan pressure rise to 0? For instance, what if the user want the fan power to be zero when the fan effect is included in the HVAC unit efficiency although it is not a common practice.
