### ISSUE TITLE
Very low surface temperatures for WindowEquivalentLayer with interior blind

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7367]
Issue overview
--------------
Comparisons between Winkelmann and the WindowEquivalentLayer (ASHWAT) methods for a window with interior blinds show large differences. From the user's post:

> Transmitted solar radiation is consistent for both models but the equivalent layer approach gives extremely low indoor surface temperatures (lower than indoor and outdoor temp), no radiative exchange and very high convective exchange.

See [here for plots](https://unmethours.com/question/38948/inconsistency-in-results-from-winkelman-and-equivalent-layer-blinds-models/).

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.1
 - Unmethours [38948](https://unmethours.com/question/38948/inconsistency-in-results-from-winkelman-and-equivalent-layer-blinds-models/)
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files added - v9.1 files for horizontal 2cm blinds and v8.8 files for wide vertical blinds are in EnergyPlusDevSupport\DefectFiles. 
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
@mjwitte do we have defect file for this issue?

**Comment by mjwitte** [comment]
Defect files are in EnergyPlusDevSupport\DefectFiles
