### ISSUE TITLE
AirFlowNetwork control

### ISSUE THREAD

**Issue by silviabi19** [NREL/EnergyPlus#7374]
Issue overview
--------------
Hello everybody, 
I'm new here and in the use of EnergyPlus! I have already looked for an answer in existing issues but I couldn't find it. I hope my question is not useless. 

I'm implementing the ASHRAE Small Office in EnergyPlus v8.0 adding an AirFlowNetwork for an accurate opening of the windows. 
I see that in AirFlowNetwork:SimulationControl is possible to select different AirFlowNetwork Controls (MultiZoneWithDistribution, MultiZoneWithoutDistribution, MultiZoneWithDistributionOnlyDuringFanOperation or NoMultiZoneOrDistribution) that allow the calculation of the air exchanges between zones. 

The problem is that I would like to implement a new model of window opening leaving the previous setting for infiltration (in the base model the infiltrations are modeled with ZoneInfiltration:DesignFlowRate) in order to evaluate the only window opening influence. I see that MultiZoneWithDistributionOnlyDuringFanOperation is the only control that allows the ZoneInfiltration to run but it performs the MultiZone calculation only during HVAC fan operation.

Does this mean that it considers the influence of window opening only during HVAC fan operation? I would like to consider it during every timestep. Is there another a way?

Thank you everybody!

**Comment by jasondegraw** [comment]
This is a question more for UnmetHours than for here, and I've answered it there:

https://unmethours.com/question/39416/airflownetwork-control/
