### ISSUE TITLE
Potential Freezing Water in Water Storage Tanks

### ISSUE THREAD

**Issue by jmaguire1** [NREL/EnergyPlus#7378]
Issue overview
--------------
For water heaters (both WaterHeater:Mixed and WaterHeater:Stratified), there's an upper limit on tank temperature to account for the temperature and pressure relief valve (which will trip before boiling occurs). However, there's no lower limit on temperature, which means the water temperature can get below 0 C. 

### Details
In a real tank, freezing would likely cause catastrophic damage to the equipment. At a minimum, this should trigger some sort of warning/error. This situation could happen with water heaters installed outside in cold locations of if the tank is being used for chilled water and the controls aren't working correctly. @nmerket @shorowit and I have encountered this situation as being possible for a heat pump water heater installed outside if it's too cold outside, which is consistent with how some other tools would model a HPWH in unconditioned space.

### Checklist
 - [ ] Add a warning/error if the water tank temperature drops below 0 C, indicating a freeze.
 - [ ] Pull request created

**Comment by jmarrec** [comment]
@jmaguire1 Could you please send me a file that exhibits this behavior? I want to check that repeated warnings will be handled gracefully in particular.

**Comment by jmaguire1** [comment]
@jmarrec Sure, I've attached a run where the water heater is located outside in a cold US climate (northern Minnesota) with a very small burner size, you should see the tank temp drop below 0 within the first few days

[WH_freezing.zip](https://github.com/NREL/EnergyPlus/files/3402393/WH_freezing.zip)

**Comment by jmarrec** [comment]
Added user defect file after cleaning invalid stuff and transition to 9.2.0 at https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/7000s/7378
