### ISSUE TITLE
Coil:Heating:DX:MultiSpeed & Coil:Heating:WaterToAirHeatPump:EquationFit values missing from ComponentSizes when hard-sized

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7381]
Issue overview
--------------
I ran EnergyPlus 9.1 simulations with single-speed and multi-speed DX coils. When I look in the ComponentSizes table in eplusout.sql, I don't see capacity/airflow values for the `Coil:Heating:DX:MultiSpeed` object. The `Coil:Cooling:DX:MultiSpeed`, `Coil:Heating:DX:SingleSpeed`, and `Coil:Cooling:DX:SingleSpeed` objects appear correct.

### Coil:Heating:DX:SingleSpeed ComponentSizes

CompType | CompName | Description
-- | -- | --
Coil:Heating:DX:SingleSpeed | ASHP HTG COIL | User-Specified Rated Air Flow Rate
Coil:Heating:DX:SingleSpeed | ASHP HTG COIL | User-Specified Gross Rated Heating Capacity
Coil:Cooling:DX:SingleSpeed | ASHP CLG COIL | User-Specified Rated Air Flow Rate
Coil:Cooling:DX:SingleSpeed | ASHP CLG COIL | User-Specified Gross Rated Total Cooling Capacity
Coil:Cooling:DX:SingleSpeed | ASHP CLG COIL | User-Specified Gross Rated Sensible Heat Ratio

### Coil:Heating:DX:MultiSpeed ComponentSizes

CompType | CompName | Description
-- | -- | -- 
Coil:Heating:DX:MultiSpeed | ASHP HTG COIL | Design Size Resistive Defrost Heater Capacity
Coil:Cooling:DX:MultiSpeed | ASHP CLG COIL | User-Specified Speed 2 Rated Air Flow Rate
Coil:Cooling:DX:MultiSpeed | ASHP CLG COIL | Design Size Speed 1 Rated Air Flow Rate
Coil:Cooling:DX:MultiSpeed | ASHP CLG COIL | User-Specified Speed 1 Rated Air Flow Rate
Coil:Cooling:DX:MultiSpeed | ASHP CLG COIL | Speed 2 User-Specified Total Cooling Capacity
Coil:Cooling:DX:MultiSpeed | ASHP CLG COIL | Speed 2 User-Specified Rated Sensible Heat Ratio
Coil:Cooling:DX:MultiSpeed | ASHP CLG COIL | Speed 1 Design Size Evaporative Condenser Air Flow Rate
Coil:Cooling:DX:MultiSpeed | ASHP CLG COIL | Speed 2 Design Size Evaporative Condenser Air Flow Rate
Coil:Cooling:DX:MultiSpeed | ASHP CLG COIL | Speed 1 Design Size Rated Evaporative Condenser Pump Power Consumption
Coil:Cooling:DX:MultiSpeed | ASHP CLG COIL | Speed 2 Design Size Rated Evaporative Condenser Pump Power Consumption

IDFs:
[single-speed.idf.txt](https://github.com/NREL/EnergyPlus/files/3379155/single-speed.idf.txt)
[multispeed.idf.txt](https://github.com/NREL/EnergyPlus/files/3379157/multispeed.idf.txt)

Perhaps related to https://github.com/NREL/EnergyPlus/issues/6061?

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
The capacity for the `Coil:Heating:WaterToAirHeatPump:EquationFit` object is also missing, though the airflow value is there. The `Coil:Cooling:WaterToAirHeatPump:EquationFit` object correctly has both capacities and airflow.

[gshp.idf.txt](https://github.com/NREL/EnergyPlus/files/3379568/gshp.idf.txt)

**Comment by mjwitte** [comment]
Are the items that are missing from the sql output present in the eio?

**Comment by shorowit** [comment]
@mjwitte No, I don't see them in the eio either.

**Comment by mjwitte** [comment]
So - next question - are the missing fields actually "autosize"d?

**Comment by shorowit** [comment]
No, they are hardsized and I want to read the "User-Specified" capacities. (This is the same situation as the other coils that work correctly.)

**Comment by mjwitte** [comment]
OK - so that likely means that these coils are not using the latest method for reporting sizes.  I'll change the issue title accordingly. @rraustad @Nigusse

**Comment by rraustad** [comment]
Coil:Cooling:DX:MultiSpeed uses RequestSizing for air flow only and the old method for other inputs. Coil:Heating:DX:MultiSpeed uses the old method for sizing all inputs.

**Comment by Nigusse** [comment]
I just saw that for multispeed DX cooling/heating coils in "Coil Sizing Details" HTML tabular report shows the low speed capacity instead of the high speed for Coil Final Gross Total Capacity [W]. This needs to be corrected. @shorowit Did you see this issue as well.

**Comment by shorowit** [comment]
@Nigusse Thanks for working on this! 

I haven't looked at the Coil Sizing Details report much, but just took a quick look and agree with you that the "Coil Final Gross Total Capacity [W]" in this report is nowhere close to matching the "Speed X User-Specified Total Cooling Capacity [W]" in the Component Sizing Summary report.

**Comment by shorowit** [comment]
Is https://github.com/NREL/EnergyPlus/pull/7435 related to the coil sizing issue? Or just a coincidence?

**Comment by Myoldmopar** [comment]
Closed with #7436
