### ISSUE TITLE
SurfaceControl:MovableInsulation does not support equivalent layer window glazing but we have unit test for it

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#7385]
Issue overview
--------------
Noticed that the unit tests added for SurfaceControl:MovableInsulation in issue #5757 [HERE](https://github.com/NREL/EnergyPlus/blame/develop/tst/EnergyPlus/unit/HeatBalanceMovableInsulation.unit.cc#L97-L99) and [HERE](https://github.com/NREL/EnergyPlus/blame/develop/tst/EnergyPlus/unit/HeatBalanceMovableInsulation.unit.cc#L132-L134) and the pull request #5762 shows that Equivalent Layer Window glazing can be used as material layer. But testing shows that SurfaceControl:MovableInsulation does not support any of the equivalent layer window materials.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.2.0
 - see the code [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SurfaceGeometry.cc#L9713-L9773). The code requires that the material must have either thermal resistance or thermal conductivity and thickness to be valid in this object.

 Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
added defect files

**Comment by RKStrand** [comment]
@Nigusse This must have been an oversight.  The GetMovableInsulationData does not allow GlassEquivalentLayer.  However, the code in HeatBalanceMovableInsulation.cc clearly allows this type of material as does the code in the unit test as you noted.  I will fix this so that the Get routine does not disallow this type of material.  Good catch!
