### ISSUE TITLE
Plant Flow Resolver not correctly handling parallel branch pumps

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#7400]
Issue overview
--------------
This issue could be a repeat of #3522 where parallel branches that do not need to run are getting flow. 

Interface developer (TRANE) provided a defect file that has a chiller plant configuration with two chillers in parallel, variable speed branch pumps dedicated to each chiller, chiller flow mode "NotModulated" and operation scheme of sequential loading.  Loading does not appear to be sequential as second chiller comes on before first chiller is fully loaded.  Plant supply side outlet temperature is not meeting setpoint even though there is plenty of capacity.  

here is a plot of chiller part load ratio
![Case1_Chiller_PLRs](https://user-images.githubusercontent.com/8754769/61488923-4586e880-a95e-11e9-8987-4e5c0c94867e.png)

here is a plot of chiller leaving temperatures

![Case1_SupplyOutletTemp](https://user-images.githubusercontent.com/8754769/61488983-6d764c00-a95e-11e9-96fe-3e61331067d8.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA) 9.1, old behavior
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (EnergyPlusDevSupport\DefectFiles\7000s\7400\7400.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by EnergyArchmage** [comment]
With changes in PR #7402 the plots for defect file look like this now

Chiller Part load ratios
![Case1_Chiller_PLRs_withSolverFix](https://user-images.githubusercontent.com/8754769/61490598-343fdb00-a962-11e9-8792-5587fc9a0470.png)

And comparison of supply side outlet temperatures, before and after 
![Case1_SupplyOutletTemp_WithSolverFix](https://user-images.githubusercontent.com/8754769/61490625-4588e780-a962-11e9-8424-17b856e0c2c4.png)

**Comment by Myoldmopar** [comment]
Closed with #7402
