### ISSUE TITLE
Change EP-Launch update checking to use GitHub releases page for EnergyPlus

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#7406]
Issue overview
--------------
The current approach for EP-Launch to notify users of updates is to check the page:

http://nrel.github.io/EnergyPlus/epupdate.htm

but the approach requires a specially formatted page and it prone to be forgotten about during the process of releasing a new version of EnergyPlus. Instead change EP-Launch to check the normal GitHub releases page that is used by EnergyPlus:

https://github.com/NREL/EnergyPlus/releases

This could be done by either using the GitHub API or page scraping.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
This should probably be moved over to the new EPLaunch repo.

**Comment by JasonGlazer** [comment]
I just added https://github.com/NREL/EP-Launch/issues/122

**Comment by Myoldmopar** [comment]
Thanks, I'll close this on here then.

**Comment by JasonGlazer** [comment]
I'm not sure this should be closed yet. We still are distributing EP-Launch 2 with EnergyPlus so maybe it should be fixed also.

**Comment by Myoldmopar** [comment]
If we do any updating of the old EP-Launch, I'd think we would just be pointing them to EP-Launch-3 at this point.  I don't think we should update the old EP-Launch to give users more incentive to keep using it, when we've spent a bunch of effort on the new one.  I'm not strongly against fixing this particular thing, but I just don't want to make a habit of adding features to both tools.

**Comment by JasonGlazer** [comment]
Ok. I get that. I will go through the other EP-Launch issues.
