### ISSUE TITLE
(Desuperheater heating energy) / (cooling coil cooling energy + cooling coil electric energy) never hit Heat Reclaim Recovery Efficiency

### ISSUE THREAD

**Issue by yzhou601** [NREL/EnergyPlus#7407]
Issue overview
--------------
In running a model with an desuperheater object, whenever ``WATER HEATER:Water Heater Heating Energy [J](Hourly)`` is not 0, I would expect:

 ``DESUPERHEATER:Water Heater Heating Energy [J]`` / (``ASHP CLG COIL:Cooling Coil Electric Energy [J]`` + ``ASHP CLG COIL:Cooling Coil Total Cooling Energy [J]``) = 0.25,

which is the Rated Heat Reclaim Recovery Efficiency defined in idf.
IDF desuperheater snippet:

    Coil:WaterHeating:Desuperheater,
    desuperheater,            !- Name
      ,                                 !- Availability Schedule Name
    Desuperheater Setpoint Temp,  !- Setpoint Temperature Schedule Name
    5,                       !- Dead Band Temperature Difference {deltaC}
    0.25,                    !- Rated Heat Reclaim Recovery Efficiency
    50,                      !- Rated Inlet Water Temperature {C}
    35,                      !- Rated Outdoor Air Temperature {C}
    60,                      !- Maximum Inlet Water Temperature for Heat Reclaim {C}
    ,                          !- Heat Reclaim Efficiency Function of Temperature Curve Name
    DesuperheaterIn,         !- Water Inlet Node Name
    DesuperheaterOut,        !- Water Outlet Node Name
    WaterHeater:Mixed,       !- Tank Object Type
    water heater,                  !- Tank Name
    Coil:Cooling:DX:SingleSpeed,  !- Heating Source Object Type
    ashp clg coil,         !- Heating Source Name
    0.001,                   !- Water Flow Rate {m3/s}
    ,                        !- Water Pump Power {W}
    0.2;                     !- Fraction of Pump Heat to Water

Results:

 DESUPERHEATER:Water Heater Heating Energy [J] / (ASHP CLG COIL:Cooling Coil Electric Energy [J] + ASHP CLG COIL:Cooling Coil Total Cooling Energy [J]) :

![image](https://user-images.githubusercontent.com/32500275/61648411-9eab9080-ac6c-11e9-9adb-dedb1aa2093e.png)

Water heating energy:

![image](https://user-images.githubusercontent.com/32500275/61648685-242f4080-ac6d-11e9-8242-b8d0ab216fa3.png)

The highest reclaimed ratio is just about 0.1+. Why couldn't we reclaim more to save water heating energy?

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus (E+ 9.1.0)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by yzhou601** [comment]
@rraustad Do you want to talk about this issue to see if there's any remaining work related to this? Otherwise we can close it.

**Comment by rraustad** [comment]
I think we need to identify where the 0.25 is being lost, or missed, or something. Yes, the desuperheater coil can recovery energy proportional to PLR, but still I would think the desuperheater to coil energy ratio should be 0.25. I'm not sure where the 0.1 is coming from in your figure. I first thought it was coil PLR, but the coil reports for energy should already include PLR.

**Comment by yzhou601** [comment]
> I think we need to identify where the 0.25 is being lost, or missed, or something. Yes, the desuperheater coil can recovery energy proportional to PLR, but still I would think the desuperheater to coil energy ratio should be 0.25. I'm not sure where the 0.1 is coming from in your figure. I first thought it was coil PLR, but the coil reports for energy should already include PLR.

@rraustad I agreed. Sorry for the confusion caused by the figure and the following table [here](https://github.com/NREL/EnergyPlus/pull/7251#issuecomment-513366445). The table is not something from report, but my assumption. My hypothesis is that the 0.25 is applied more than once in water heater iterations (coil available reclaimed heat is not recalculated in DXcoils.cc), so 0.1+ is actually AvailableRelaimedHeat * (1-0.25)^(n) * 0.25, where n supposed to be 0 when 25% is reclaimed. If n = 3, the 0.1+ number in my figure came to its place.

**Comment by yzhou601** [comment]
@rraustad sorry I initially thought you're talking about the comment in that PR.

**Comment by yzhou601** [comment]
![image](https://user-images.githubusercontent.com/32500275/69187102-27c9bb80-0ad7-11ea-84b1-32e2c76e0765.png)
I recorded a few values with a debugging build as shown above. The breakpoints are this equation in [WaterThermalTanks.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WaterThermalTanks.cc#L9223) and here in [WaterToAirHeatPumpSimple.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WaterToAirHeatPumpSimple.cc#L2398), the values of updating Qsource are not included, but the bold numbers are `HeatReclaim.WaterHeatingDesuperheaterReclaimedHeatTotal` that was subtracted from Qsource (for the test file with only one desuperheater reclaiming heat).  It looked like the multiple times calling CalcDesuperheaterWaterHeater caused AvailCapacity shrinking, finally resulting reclaimed heat to only ~10% of origianl AvailCapacity. This is the callstack of CalcDesuperheaterWaterHeater function:
![image](https://user-images.githubusercontent.com/32500275/69188374-a9224d80-0ad9-11ea-991d-5aed5f9c6660.png)
I felt like this issue is very similar as the previous situation we faced of passing data through functions with "-="s. Inspired by what we solved for gshp source heat subtraction, a potential solution to this issue could be changing HeatRelaim-ish data structures to record every user of reclaimed heat, summed them up and subtracted locally and dynamically, then kept AvailCapacity untouched.

**Comment by rraustad** [comment]
I agree that it is difficult to maintain a single bucket of energy for multiple components when those components are modeled in specific order with respect to the time that energy is consumed. Some can be modeled before and some after the consumer uses the energy. I believe this is what we saw in the previous situation. For this reason, I agree that the same method should be used here.

From the values you recorded above I cannot tell if the bucket is being adjusted multiple times or if the later iterations are operating at different PLRs.

**Comment by yzhou601** [comment]
> I agree that it is difficult to maintain a single bucket of energy for multiple components when those components are modeled in specific order with respect to the time that energy is consumed. Some can be modeled before and some after the consumer uses the energy. I believe this is what we saw in the previous situation. For this reason, I agree that the same method should be used here.
> 
> From the values you recorded above I cannot tell if the bucket is being adjusted multiple times or if the later iterations are operating at different PLRs.

I instrumented breakpoints at both functions: Desuperheater and Heat Pump Coil calculation. I recorded whenever it called coil functions as `WaterToAirHeatPumpSimple:CalculateHPCoolingSimple()`, so those numbers neighbored with each other means there's no coil side update. Another fact is that the previous AFTER number is taken as next BEFORE number, which seems to be a clue of multiple adjustments.
