### ISSUE TITLE
Unit ventilator with cycling fan results in simultaneous heating-cooling and negative cooling coil loads

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7420]
Issue overview
--------------
This was noticed while testing #7386. A test file with variable percent outdoor air and cycling fan operation has 1000s of warnings like this:
```
   ** Warning ** GetSpecificHeatGlycol: Temperature is out of range (too low) for fluid [WATER] specific heat supplied values **
   **   ~~~   ** ..Called From:UpdatePlantLoopInterface,Temperature=[-0.67], supplied data range=[0.00,125.00]
   **   ~~~   **  Environment=RUN PERIOD 1, at Simulation time=01/01 00:00 - 00:15
```

Looking at the output reveals times when the heating and cooling coils are both operating and times when the cooling coil output is negative. For example, look at the variables output, columns BJ and BM on 01/01.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.2.0-7a21f42855
 - Ref #7386 
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached:
[UnitVent5ZoneAuto-CycFan2-Variable-MinOAOn-Annual-SelectMonths-Detailed.idf.txt](https://github.com/NREL/EnergyPlus/files/3443963/UnitVent5ZoneAuto-CycFan2-Variable-MinOAOn-Annual-SelectMonths-Detailed.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mjwitte Hmmm...negative cooling coil rates but also cooling coil loads when there is clearly a heating load.  Would you agree that both of those are a problem?  Should there ever be a cooling coil load in a unit ventilator if it is in heating mode and the heating coil is on?  Or am I forgetting something here?

**Comment by mjwitte** [comment]
Actually, to be sure of what's going on, you should re-run the defect file with "detailed" output instead of hourly. But my guess is that the control logic is calling the cooling coil when it shouldn't be.

**Comment by RKStrand** [comment]
@mjwitte That would be my guess too.  One additional data point that I just discovered.  Zone1UnitVent is the only one that did not have a Supply Air Fan Operating Mode Schedule Name.  When I added one similar to the other unit ventilators, the problem went away...interesting... Actually, just checked...the output is already detailed on the variables that we are interested in here.

**Comment by mjwitte** [comment]
Without the schedule name it's always in cycling mode. If you added a schedule that's always 1 then it's in continuous fan mode. The problem appears to be related only to cycling fan operation - perhaps a mis-step in adjusting for the cycling output vs continuous output?
