### ISSUE TITLE
Condenser hot gas reheat model for DX Cooling Coil System

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#7421]
Issue overview
--------------
Many equipment manufacturers offer dehumidification reheat using condenser hot gas in rooftop, split DX AHU, and DX DOAS products.  In applications where active humidity control is used to control either discharge air or space air relative humidity, dehumidification reheat is required to prevent sensible overcooling.  Dehumidification by conventional means such as electric resistance or fossil fuel combustion heaters is costly and energy-inefficient.  To confront this challenge manufacturers have developed schemes to take heat from the DX refrigeration system condenser and use it to provide what is "free" reheat.   These schemes are typically referred to as "hot gas reheat".  Beyond simply using hot gas for reheat, some manufacturers have devised controls to allow dehumidification and hot gas reheat at times of high sensible load, low sensible load, or no sensible load.  
    Currently EnergyPlus does not provide modeling capabilities for hot gas reheat.    Addition of this feature to EnergyPlus would allow engineers to evaluate the energy-efficient humidity control options.  An EnergyPlus model for this feature would need to model not just the use of hot gas for free reheat, but also controls for these three dehumidification modes.  Sample  data for Carrier, Trane, Daikin, and Aaon products are listed here:

[Daikin-1](https://www.daikinapplied.com/o365/api/graphapi/GetDocument/Doc100/ASP31-292_ModHotGasReheat_Brochure_2PG.pdf/)
[Daikin-2:  see pg 14-15 in this document](https://www.daikinapplied.com/o365/GetDocument/Doc100/Daikin_CAT_256-13_LR_Rebel_Comm_Pkg_Rooftop_Catalog.pdf)

[Trane-1](https://www.trane.com/content/dam/Trane/Commercial/global/products-systems/equipment/unitary/rooftop-systems/precedent-3-to-10-tons/RT-SLB006-EN_11232009.pdf)
[Trane-2: DOAS with HGRH: See pages 17-23](https://www.trane.com/content/dam/Trane/Commercial/global/products-systems/equipment/unitary/dedicated-air-solutions/OAU-PRC001J-EN_12012018.pdf)

[Carrier-1](https://www.utcccs-cdn.com/hvac/docs/1001/Public/01/04-581048-01.pdf)
[Carrier-2](https://www.utcccs-cdn.com/hvac/docs/1001/Public/02/04-811-70007.pdf)

[Aaon-1](https://www.aaon.com/Documents/Technical/AAON_HumidityControlSolution_170921.pdf)
[Aaon-2](https://www.aaon.com/Documents/Technical/ModReheat_Unitary_071012.pdf)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by luisclv** [comment]
This already exists, it is the [Coil:Heating:Desuperheater](https://bigladdersoftware.com/epx/docs/9-1/input-output-reference/group-heating-and-cooling-coils.html#coilheatingdesuperheater). Please correct me if I am wrong.

**Comment by TiejunWu** [comment]
@luisclv Thanks for pointing this out. In additional to just use the condenser heat for reheat purpose, the proposal also looks at the different controls related to operating modes the heat is used. We will take a look at this object and evaluate how much it covers the controls features.

**Comment by TiejunWu** [comment]
I read some of the EnergyPlus documents and looked into the EnergyPlus example 5Zone_Unitary_VSDesuperheater.idf. Looks like this component is a simple model that calculates the regfrigerant-to-air heat recovery, and it does not consider the effect on the refrigerant cycle efficiency. When there is hot gas reheat, depending on the system configuration and the reheat heat transfer rate, some or all of the refrigerant is going to be exchanging heat with the lower temperature dehumidified air instead of the hot outdoor air. This would to some degree reduce the compressor lift compared to the no hot gas reheat case and improve the refrigerant loop efficiency. This detail is important for representing the full energy efficiency story of using hot gas reheat instead of conventional means like electric or hot water reheat. 

Across the HVAC industry, manufacturers configure HGRH differently in their products, and each equipment configuration has a different effect on refrigeration system efficiency, as well as on how hot gas reheats the air stream. Reflecting some of these details in the model can help in comparing the energy benefits of different configurations.

a.     Some manufacturers place the HGRH coil in parallel with the condenser, with refrigerant streams mixing downstream of the condenser and upstream of the TXV.
![Picture1](https://user-images.githubusercontent.com/7797674/63470110-bdeb3880-c439-11e9-8020-f5b085fab99d.png)

b.	Some manufacturers place the HGRH coil in series and upstream of the condenser.  Refrigerant streams mix before entering the condenser.
![Picture2](https://user-images.githubusercontent.com/7797674/63470121-c5aadd00-c439-11e9-8a32-8b8627252db6.png)

c.	Some manufacturers place the HGRH coil in series but downstream of the condenser.  Refrigerant streams mix before entering the TXV.
![Picture3](https://user-images.githubusercontent.com/7797674/63470130-c8a5cd80-c439-11e9-8382-440e0131c2be.png)

**Comment by lgu1234** [comment]
Closed via #7707
