### ISSUE TITLE
Connecting Air Loop DX coils to VRF refrigerant loops

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#7422]
Issue overview
--------------
One of the recent developments in the VRF field is the ability to connect terminal devices other than indoor split fan coils to a VRF refrigerant loop.  These new terminal devices include Dedicated Outdoor Air System (DOAS) AHUs and roof top mounted split DX AHUs for space conditioning and ventilation.  
    Nearly all VRF applications need ventilation.  Previously ventilation had to be provided by separate packaged rooftop type DOAS equipment since VRF indoor units cannot handle raw outdoor air directly and VRF condensing units could not serve DOAS equipment.  In addition, one of the energy efficiency limitations of VRF systems is the lack of an outdoor air economizer cycle.  Both challenges have now been solved.  Multiple manufacturers such as Daikin, Mitsubishi, LG, and Toshiba-Carrier offer the ability to connect split DX DOAS AHUs to VRF condensing units.  In addition, Toshiba-Carrier condensing units can be connected to multiple rooftop-mounted split DX AHUs that provide space conditioning and ventilation, and can offer outdoor air economizer cycles.  These developments extend the application of VRF systems and the energy efficiency of these systems.
  Currently VRF systems in EnergyPlus only allow indoor DX fan coil terminals to be connected to a VRF refrigerant loop.  This request proposal would allow terminal devices such as split DX DOAS AHUs and split DX AHUs for space conditioning and ventilation to be connected to VRF refrigerant loops.
    
A sampling of product references are provided below:

[Daikin](https://www.daikinac.com/content/commercial/ventillation-units/dvs-dedicated-outside-air-system)

[Mitsubishi-Electric-1](https://www.mitsubishipro.com/products/city-multi-vrf/ventilation/premisys-dedicated-outdoor-air-systems)

[Mitsubishi-Electric-2](http://meus1.mylinkdrive.com/item/PremiSys.html)

[LG Systems](https://lghvac.com/commercial/product-type/?productTypeId=a2x44000003XR0s&iscommercial=true) 

[Toshiba-Carrier-1](https://www.carrier.com/commercial/en/us/products/variable-refrigerant-flow/toshiba-carrier-vrf-products/toshiba-carrier-indoor-units/40qq/)

[Toshiba-Carrier-2](https://dms.hvacpartners.com/docs/1001/Public/0C/01-VRF-016-01.pdf)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
See PR #7605.

**Comment by rraustad** [comment]
Addressed by #7605. Closing this issue.
