### ISSUE TITLE
Forced to natural convection transition for "Ceiling Diffuser" convection model

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#7423]
Issue overview
--------------
EnergyPlus v9.1 fixed a defect in the "Ceiling Diffuse" convection model (https://github.com/NREL/EnergyPlus/issues/7208).  The intended operation of this model was to use forced convection coefficients for air circulation rates of more than 3 ACH, and to use natural convection coefficients for air circulation rates less than 3 ACH.  Previously the model was using forced convection coefficients for all air circulation levels, but apparently this was not intended.
    There are two issues with this return to "intended" operation of the model.  First the 3 ACH threshold needs to be validated.  Second, the change from forced to natural convection is currently a step change rather than a smooth transition.  Its unclear whether this represents actual building physics.  
   Validation: The basis for the 3 ACH threshold is not clear.  Talking with EnergyPlus developers, a source for the 3 ACH threshold could not be cited.  A large fraction of VAV air systems have VAV box minimum flow rates less than 3 ACH so heating season and heating design operation is affected by the 3 ACH threshold.  Heating loads and therefore heating energy consumption is significantly lower when assuming natural convection rather than forced convection in these zones.  Having a strong, documented basis for the 3 ACH threshold is therefore very important for the accuracy of EnergyPlus and the credibility of the engine as EnergyPlus gains wider use among engineers doing "production" work - that is creating equipment specifications for commercial projects and doing energy modeling to optimize system designs.
    Transition:  The second aspect of this is whether the change from forced to natural convection is actually a step change that occurs a particular ACH threshold, or is a smooth transition that occurs across an interval between two ACH levels.  Having a strong, documented basis for the transition modeling is also important for accuracy and credibility of EnergyPlus results.
    It is possible initial FlexLAB test results can help with validation of the model.  However, talking with the researchers, it appears much more test work is needed to fully validate the threshold and to understand how transition between convection modes occurs.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@TiejunWu Just out of curiosity, which developers did you talk to regarding the 3 ACH threshold?  I'm trying to avoid asking team members the same question twice and see if there is someone else who might have some insight into this.

As for a transition, I definitely agree with you on that issue.  A step change is never a good idea and there are other things in EnergyPlus that have transitions to avoid such a thing happening.  I'll fix this as part of the solution.

**Comment by RKStrand** [comment]
@TiejunWu I have an update based on an email conversation with the model author.  The 3 ACH threshold was based on the data under which the correlation was developed.  However, he felt that the results of the model would extrapolate down to 1 ACH fairly well.  I have implemented a fix based on a new threshold of 1 ACH and included a note regarding this in the Engineering Reference documentation.  Hope this helps!

**Comment by TiejunWu** [comment]
@RKStrand Thank you very much for the fix. Last year it was Neal that found the the problem. Glad you have fixed it. Would this be included as part of version 9.2?

**Comment by RKStrand** [comment]
@TiejunWu I've made the fix and am waiting on someone to review it before it gets into the official code.  So, it seems very likely that this will make the Fall 2019 (V9.2) release.
