### ISSUE TITLE
Wrong PLR in chiller IPLV calculation

### ISSUE THREAD

**Issue by lymereJ** [NREL/EnergyPlus#7425]
Issue overview
--------------
The wrong Part Load Ratio (PLR) is used in chiller IPLV calculation.

### Details
In the current implementation of the chiller IPLV calculation it is assumed that the chiller PLR is equal to the different loading percentage prescribed by AHRI 550-590 (% of full load capacity). The PLR at each different loading should be recalculated as the PLR is function of the operating capacity, not the full load capacity.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Pull request created

**Comment by Myoldmopar** [comment]
Closed via #7426
