### ISSUE TITLE
Debug file gets deleted when it is not empty

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7433]
Issue overview
--------------
Tried to dump out user view factor objects using "Output:Surfaces:List, ViewFactorInfo, idf;" but eplusout.dbg disappeared at the end of the simulation.

In the debugger, I could see that the content was being written to `OutputFileDebug` in `InitInteriorRadExchange` but at the end of the simulation in `UtilityRoutines::CloseMiscOpenFiles`, this [check on the debug file position](https://github.com/NREL/EnergyPlus/blob/4f4f5d8ca1d7a7fd5722de8e43c4fba7e99a17e6/src/EnergyPlus/UtilityRoutines.cc#L677-L695) comes back with "ASIS" so it closes and deletes the debug output file.

Not sure if this happens with any sort of debug output request or just with the view factors.

### Details
Some additional details for this issue (if relevant):
 - Platform Windows 10 - this could be a platform-specific problem?
 - Version of EnergyPlus 9.2.0-7a21f42855

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached:
[5ZoneAirCooled-OutputViewFactors.idf.txt](https://github.com/NREL/EnergyPlus/files/3448066/5ZoneAirCooled-OutputViewFactors.idf.txt)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Tested on Ubuntu with current develop, eplusout.dbg is available. I think it was fixed by the IO refactor. New routine is here:

https://github.com/NREL/EnergyPlus/blob/3d2145e57854707476a667f73c514417625964aa/src/EnergyPlus/UtilityRoutines.cc#L696-L703

@mjwitte I'll close this one. If you can reproduce on windows with current develop, we can always reopen.

**Comment by mjwitte** [comment]
@jmarrec Tested with develop on Windows, Version 9.4.0-fa9c482c78 and confirmed the debug file remains. Fixed.

**Comment by jmarrec** [comment]
@mjwitte thanks for taking the time to confirm!
