### ISSUE TITLE
Remove minimum limits for Heat Pump Heating Minimum Outdoor Dry-Bulb Temperature or equivalent

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7437]
Issue overview
--------------
Minimum limits were removed a while back from native idf objects for Minimum Outdoor Drybulb Temperature for Compressor Operation (or similar) fields (e.g. #6190). But there are still limits in the IDD for several HVACTemplate objects. This should be simply and IDD change.
```
 N19, \field Heat Pump Heating Minimum Outdoor Dry-Bulb Temperature
      \type real
      \minimum -20.0
      \default -8.0
      \units C
```
This field is found in HVACTemplate:Zone:PTHP, HVACTemplate:System:UnitaryHeatPump:AirToAir, and HVACTemplate:System:UnitarySystem.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.1.0
 - Helpdesk ticket number 15238

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Update: Apparently the code has hard limits for Coil:Heating:DX:SingleSpeed and for VRF. Need to search all DX heatng coils and HVAC system which support heat pumps to see if there are any other limits lurking in the code.

**Comment by rraustad** [comment]
Used when input field is not present:

static Real64 const minOATCompDXCooling = -25.0;      // min OAT for compressor operation for DX cooling coils

Update: min-fields = 21 for Coil:Heating:DX:SingleSpeed so this variable should never get used.

**Comment by mjwitte** [comment]
Update from the user:

I just used e+ v8.9 and checked that the dx heating coil does in fact stay on below -20 DegC. I used -25 DegC for the test. I think I tested this before with OpenStudio and whenever I set the temperature in OS below -20 it sets back to -20 in the idf file. So the limitation is in OS and not e+. I just checked this again with OS 2.6. I might be different in 2.8.

Note that the ‘OpenStudio’ limitation, on the outdoor temp for compressor operation, is only with object ‘Coil:Heating:DX:SingleSpeed’. The other coils ‘Coil:Heating:DX:VariableSpeed’ and ‘AirConditioner:VariableRefrigerantFlow’ can be used with minimum outdoor temp < -20 DegC using ‘OpenStudio’.
@jmarrec is this an OpenStudio issue?

**Comment by jmarrec** [comment]
It's probably not an "issue" per se.

Typically OS idd will match E+ and sometimes we make some fields required and when they have no default in the IDD (because input is or isn't required based on a choice field usually, but sometimes there should be one instead of harcoding in the code), we usually search through the cpp code to see if there's an harcoded default and use that.

Sometimes os IDD will also fall out of sync with recent changes in e+

I think that's likely the case here and OS will need a small adjustement, I'll check monday when back at a computer.
