### ISSUE TITLE
Heating Coil Calculation uses Cooling-Coil properties

### ISSUE THREAD

**Issue by YanfeiNREL** [NREL/EnergyPlus#7440]
Issue overview
--------------
The heating coil calculation uses the cooling coil properties in SetupOutputVariable() of the file DXCoils.cc, between the line of 5521-5602. This impacts the Coil:WaterHeating:AirToWaterHeatPump:Pumped, and Coil:WaterHeating:AirToWaterHeatPump:Wrapped.
 
Mainly, the heating coil has no latent/sensible energy, no latent/sensible energy rate. However the source code reference the cooling coil latent/sensible energy and energy rate for the heating coil.

### Details
'''

    else if (Coil.DXCoilType_Num == CoilDX_HeatPumpWaterHeaterPumped || Coil.DXCoilType_Num == CoilDX_HeatPumpWaterHeaterWrapped) {
                // Setup Report Variables for Cooling Equipment
                // CurrentModuleObject='Coil:WaterHeating:AirToWaterHeatPump:Pumped'
                // or 'Coil:WaterHeating:AirToWaterHeatPump:Wrapped'
                SetupOutputVariable(
                    "Cooling Coil Total Cooling Rate", OutputProcessor::Unit::W, Coil.TotalCoolingEnergyRate, "System", "Average", Coil.Name);

                if (Coil.IsDXCoilInZone) {
                    SetupOutputVariable("Cooling Coil Total Cooling Energy",
                                        OutputProcessor::Unit::J,
                                        Coil.TotalCoolingEnergy,
                                        "System",
                                        "Sum",
                                        Coil.Name,
                                        _,
                                        "ENERGYTRANSFER",
                                        "COOLINGCOILS",
                                        _,
                                        "System");
                } else {
                    SetupOutputVariable(
                        "Cooling Coil Total Cooling Energy", OutputProcessor::Unit::J, Coil.TotalCoolingEnergy, "System", "Sum", Coil.Name);
                }

                SetupOutputVariable(
                    "Cooling Coil Sensible Cooling Rate", OutputProcessor::Unit::W, Coil.SensCoolingEnergyRate, "System", "Average", Coil.Name);
                SetupOutputVariable(
                    "Cooling Coil Sensible Cooling Energy", OutputProcessor::Unit::J, Coil.SensCoolingEnergy, "System", "Sum", Coil.Name);
                SetupOutputVariable(
                    "Cooling Coil Latent Cooling Rate", OutputProcessor::Unit::W, Coil.LatCoolingEnergyRate, "System", "Average", Coil.Name);
                SetupOutputVariable(
                    "Cooling Coil Latent Cooling Energy", OutputProcessor::Unit::J, Coil.LatCoolingEnergy, "System", "Sum", Coil.Name);
                SetupOutputVariable(
                    "Cooling Coil Runtime Fraction", OutputProcessor::Unit::None, Coil.CoolingCoilRuntimeFraction, "System", "Average", Coil.Name);

                if (Coil.ReportCoolingCoilCrankcasePower) {
                    SetupOutputVariable("Cooling Coil Crankcase Heater Electric Power",
                                        OutputProcessor::Unit::W,
                                        Coil.CrankcaseHeaterPower,
                                        "System",
                                        "Average",
                                        Coil.Name);
                    SetupOutputVariable("Cooling Coil Crankcase Heater Electric Energy",
                                        OutputProcessor::Unit::J,
                                        Coil.CrankcaseHeaterConsumption,
                                        "System",
                                        "Sum",
                                        Coil.Name,
                                        _,
                                        "Electric",
                                        "DHW",
                                        _,
                                        "Plant");
                }

                // new report variables for a HP water heater DX coil
                SetupOutputVariable(
                    "Cooling Coil Total Water Heating Rate", OutputProcessor::Unit::W, Coil.TotalHeatingEnergyRate, "System", "Average", Coil.Name);
                SetupOutputVariable("Cooling Coil Total Water Heating Energy",
                                    OutputProcessor::Unit::J,
                                    Coil.TotalHeatingEnergy,
                                    "System",
                                    "Sum",
                                    Coil.Name); //, &
                //                           ResourceTypeKey='ENERGYTRANSFER',EndUseKey='HEATING',GroupKey='Plant')
                SetupOutputVariable("Cooling Coil Water Heating Electric Power",
                                    OutputProcessor::Unit::W,
                                    Coil.ElecWaterHeatingPower,
                                    "System",
                                    "Average",
                                    Coil.Name);
                SetupOutputVariable("Cooling Coil Water Heating Electric Energy",
                                    OutputProcessor::Unit::J,
                                    Coil.ElecWaterHeatingConsumption,
                                    "System",
                                    "Sum",
                                    Coil.Name,
                                    _,
                                    "Electric",
                                    "DHW",
                                    _,
                                    "Plant");
            }
'''
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ x ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@YanfeiNREL I think this is OK, because Coil:WaterHeating:AirToWaterHeatPump* is a cooling coil from the perspective of the zone. It draws heat from the zone and heats the water in the water heater.

**Comment by rraustad** [comment]
I agree, the Cooling Coil report variables refer to the cooling coil on the heat pump. The condenser coil is in the water tank. This issue can be closed once @YanfeiNREL agrees.

**Comment by rraustad** [comment]
@YanfeiNREL, I am closing this issue. You may reopen it if we have missed something with your description.
