### ISSUE TITLE
CoolingTower:VariableSpeed control problems

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7464]
Issue overview
--------------
User file with CoolingTower:VariableSpeed not delivering setpoint even though the load on the tower is well below capacity. The tower fan is running at full flow, but the outlet temp is well above setpoint. Not sure if it's a design input issue or a control problem in the tower algorithm. Problems shows up on 08/12 and other days.

The tower is also putting out lots of warnings, most of which say they are expected or may not affect performance. So, why issue the warnings then?
```
   ** Warning ** CoolingTower:VariableSpeed "COOLING TOWER VARIABLE SPEED 1" - Water flow rate ratio is outside model boundaries at 0.14.
   **   ~~~   **  ...Valid range = 0.75 to 1.25. Occurrence info = RUN PERIOD 1, 08/01 00:00 - 00:10
   **   ~~~   **  ...Water flow rate ratio passed to the model = 0.75000
   **   ~~~   **  ...Water flow rate ratios outside model boundaries may not adversely affect tower performance.
   ** Warning ** CoolingTower:VariableSpeed "COOLING TOWER VARIABLE SPEED 1" - Inlet air wet-bulb temperature is outside model boundaries at 26.76.
   **   ~~~   **  ...Valid range = -1.00 to 26.67. Occurrence info = RUN PERIOD 1, 08/01 14:00 - 14:10
   **   ~~~   **  ...Inlet air wet-bulb temperature passed to the model = 26.666700
   **   ~~~   **  ...Wet-bulb temperatures outside model boundaries may not adversely affect tower performance.
   ** Warning ** CoolingTower:VariableSpeed "COOLING TOWER VARIABLE SPEED 1" - Cooling tower air flow rate ratio calculation failed 
   **   ~~~   ** ...with conditions as Twb = 26.67, Trange =  6.47, Tapproach =  2.54, and water flow rate ratio =  0.75
   **   ~~~   ** ...a solution could not be found within the valid range of air flow rate ratios
   **   ~~~   **  ...Valid air flow rate ratio range =  0.20 to 1.0.
   ** Warning ** CoolingTower:VariableSpeed "COOLING TOWER VARIABLE SPEED 1" - Tower range temperature is outside model boundaries at 12.50.
   **   ~~~   **  ...Valid range = 1.11 to 11.11. Occurrence info = RUN PERIOD 1, 08/12 03:40 - 03:50
   **   ~~~   **  ...Tower range temperature passed to the model = 12.49717
   **   ~~~   **  ...Range temperatures outside model boundaries may not adversely affect tower performance.
   **   ~~~   **  ...This is not an unexpected occurrence when simulating actual conditions.
   ** Warning ** CoolingTower:VariableSpeed "COOLING TOWER VARIABLE SPEED 1" - Tower approach temperature is outside model boundaries at 11.12.
   **   ~~~   **  ...Valid range = 1.11 to 11.11. Occurrence info = RUN PERIOD 1, 08/12 03:40 - 03:50
   **   ~~~   **  ...Tower approach temperature passed to the model = 11.11685
   **   ~~~   **  ...Approach temperatures outside model boundaries may not adversely affect tower performance.
   **   ~~~   **  ...This is not an unexpected occurrence when simulating actual conditions.
```

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.2.0-6150bb56e0
 - Unmethours [39364](https://unmethours.com/question/39364/cooling-tower-out-of-model-boundaries-e)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached, using USA_TX_Austin-Mueller.Muni.AP.722540_TMY3 weather
[in-moreoutput-2xTower.idf.txt](https://github.com/NREL/EnergyPlus/files/3521721/in-moreoutput-2xTower.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lymereJ** [comment]
I ran into the same exact issue with the following file in 23.2: [defect_file.zip](https://github.com/NREL/EnergyPlus/files/12743908/defect_file.zip). One thing that makes this issue hard to identify by just looking at the simulation output is that there's no warning that's issued when the tower does not do anything to control the outlet water temperature (but run at an airflow fraction of 1!).
