### ISSUE TITLE
MultiSpeed DX Cooling Coil sizing variable names and capacity reporting issues 

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#7477]
## Issue overview
--------------
Multispeed DX cooling coil has the following reporting inconsistencies:

- Coil:Cooling:DX:MultiSpeed lists, e.g., "Speed 2 User-Specified ... Capacity" while  Coil:Heating:DX:MultiSpeed lists, e.g., "User-Specified Speed 2 ... Capacity".
- Coil:Cooling:DX:MultiSpeed lists the capacity at only max speed (e.g., 4) while Coil:Heating:DX:MultiSpeed lists the capacity at all speeds (e.g., 1, 2, 3, and 4).
- Coil:Cooling:DX:MultiSpeed only lists the total cooling capacity while Coil:Cooling:WaterToAirHeatPump:EquationFit lists both sensible and total cooling capacities.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 -  @shorowit commented in pull request https://github.com/NREL/EnergyPlus/pull/7436#issuecomment-525591009

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@Nigusse @shorowit Where can I find a defect test file for this?

**Comment by shorowit** [comment]
@mjwitte It's in https://github.com/NREL/EnergyPlus/issues/7381 -- multispeed.idf.txt

**Comment by Nigusse** [comment]
Yes, it is the same defect file. I do not think I have changed it. Any way here is the idf used to generate the sql outputs shown in the pull request #7495.

[Issue7381_MultiSpeed.idf.txt](https://github.com/NREL/EnergyPlus/files/3719293/Issue7381_MultiSpeed.idf.txt)
