### ISSUE TITLE
Question regarding Engineering Reference Section 7.8

### ISSUE THREAD

**Issue by NicolaiMortensenMS** [NREL/EnergyPlus#7478]
Issue overview
--------------
I'm interested in using the EnergyPlus Engineering Reference Section 7.8 (Window Heat Balance Calculation) in order to calculate surface temperatures of glazings. I intend to perform this calculation in MATLAB.

The documentation in section 7.8 is based on a double-glazing, and details a system of 4 linear equations to solve in order to calculate the four surface temperatures (7.433, 7.434, 7.435 and 7.436 respectively).

I'm interested in reducing/expanding these equations to perform the same calculation for single- and triple-layer glazings. I've attempted to do so, and would very much appreciate help from anyone who might be able to validate my work.

I apologize if this question is not in line with typical issue practices, but would very thankful for any help that might be provided.

Kind regards,

Nicolai Mortensen

**Comment by jmarrec** [comment]
This type of question is best suited for unmethours.com, where you will draw a larger base that can help you with this. (And sorry about the fact that your question above has been unanswered in more than a year).
