### ISSUE TITLE
Error in IDD for ZoneHVAC:Baseboard:RadiantConvective:Electric

### ISSUE THREAD

**Issue by Lefort-Antoine** [NREL/EnergyPlus#7490]
The IDD has this:
```
ZoneHVAC:Baseboard:RadiantConvective:Electric,
       \min-fields 8
       \extensible:2 - repeat last two fields, remembering to remove ; from "inner" fields.
       \memo The number of surfaces can be expanded beyond 100, if necessary, by adding more
       \memo groups to the end of the list
  A1 , \field Name
       \required-field
       \reference ZoneEquipmentNames
```
should be:
```
ZoneHVAC:Baseboard:RadiantConvective:Electric,
       \min-fields 8
       \extensible:2 - repeat last two fields, remembering to remove ; from "inner" fields.
       \memo The number of surfaces can be expanded beyond 100, if necessary, by adding more
       \memo groups to the end of the list
  A1 , \field Name
       \required-field
       \reference-class-name validBranchEquipmentTypes
       \reference validBranchEquipmentNames
       \reference ZoneEquipmentNames
```

**Comment by RKStrand** [comment]
@Lefort-Antoine Is this really an error?  In the baseboard models that connect to a water loop, referencing a baseboard on a branch seems to make sense.  For an electric baseboard, it does not fit on a plant loop.  So, I'm not sure that this is actually an error?

**Comment by Lefort-Antoine** [comment]
Yes. You are right. I'm sorry I didn't keep the trace of the work. You can close or delete the issue for when I retrieve it.

**Comment by RKStrand** [comment]
@Lefort-Antoine I'm going to go ahead and close this issue as I think that the IDD is actually correct in this case.

**Comment by mjwitte** [comment]
@RKStrand See similar one #7537.

**Comment by RKStrand** [comment]
@mjwitte Yes, I believe #7537 is an issue that needs to be address.  I have gone ahead and assigned that one to myself and will work on it, hopefully sometime in the near future.  Thanks for the heads up!

On Oct 24, 2019, at 3:59 PM, Michael J. Witte <notifications@github.com<mailto:notifications@github.com>> wrote:


@RKStrand<https://github.com/RKStrand> See similar one #7537<https://github.com/NREL/EnergyPlus/issues/7537>.
