### ISSUE TITLE
USA_MI_Rhinelander-Oneida.County.AP.727415_TMY3 incorrectly named

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7500]
As far as I can tell, the EPW file posted on the [EnergyPlus website](https://energyplus.net/weather-location/north_and_central_america_wmo_region_4/USA/MI/USA_MI_Rhinelander-Oneida.County.AP.727415_TMY3) is incorrectly named with MI.

Note that:
- The header line in the EPW says WI
- The [TMY3 site](https://rredc.nrel.gov/solar/old_data/nsrdb/1991-2005/tmy3/by_state_and_city.html#W) lists it as WI
- The [OpenStudio BCL](https://bcl.nrel.gov/node/75610) lists it as WI
- [Google maps](https://www.google.com/maps/place/Rhinelander,+WI+54501/@45.6356057,-89.4709064,13z/data=!3m1!4b1!4m5!3m4!1s0x4d55aae7221bc6df:0x260e3396b6815e8f!8m2!3d45.6366228!4d-89.4120753) shows it entirely inside of WI

**Comment by shorowit** [comment]
I quickly checked all the TMY3 EPW files and this was the only file incorrect relative to the TMY3 website.

**Comment by mitchute** [comment]
I have a branch locally that addresses this. I will push it up once I get write access to the repo.

**Comment by mitchute** [comment]
There's a PR open over on the other private repo that addresses this. @Myoldmopar @nllong can either of you review that when you get a chance?

**Comment by bonnema** [comment]
> There's a PR open over on the other private repo that addresses this. @Myoldmopar @nllong can either of you review that when you get a chance?

let me know if I can help

**Comment by nllong** [comment]
I just reviewed and merged. I think @kflemin (which isn't part of this repo) needs to deploy the updated weather. Unless we always pull from github...

**Comment by mitchute** [comment]
Thanks, @nllong. We can hold this open for now and check back later for that final update. This and https://github.com/NREL/EnergyPlus/issues/8920 should be able to close after that.

**Comment by shorowit** [comment]
I'm seeing the EPW correctly renamed and showing up now under WI instead of MI. Unfortunately if I [search for "rhinelander"](https://energyplus.net/weather-search/rhinelander), it still returns the old MI URL.

**Comment by kflemin** [comment]
@shorowit search is fixed on this component...

**Comment by shorowit** [comment]
Verified. Looks good to me now, thanks @kflemin!
