### ISSUE TITLE
No data in Output:Table:Annual when using Maximum/MinimumDuringHoursShown

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7502]
Issue overview
--------------
The `Output:Table:Annual` object is returning no data when using MaximumDuringHoursShown or MinimumDuringHoursShown.

I used the following object in my IDF:
```
Output:Table:Annual,
  Peak Electricity Annual Report,
  ,
  ,
  Heating:EnergyTransfer:Zone:LIVING,
  HoursPositive,
  ,
  Electricity:Facility,
  MaximumDuringHoursShown,
  ;
```

There are hours from which the maximum value should be pulled, but the report shows no data:

![image](https://user-images.githubusercontent.com/5861765/64907502-8a09d880-d6b0-11e9-8be0-e67cf1c171f9.png)

Interestingly, if I use the `Output:Table:Monthly` object instead it works properly and gives good results.

Test file:
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/3612656/in.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - EnergyPlus 9.1.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@JasonGlazer

**Comment by JasonGlazer** [comment]
Updated test file:
[7502-in_v920.idf.txt](https://github.com/NREL/EnergyPlus/files/3789593/7502-in_v920.idf.txt)
