### ISSUE TITLE
Prep for 9.2.0 Release

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#7515]
Issue overview
--------------
A catch-all for tasks to accomplish for the 9.2.0 release.  Add to this list as needed:
- [x] Tag RC1
- [x] Check on Windows 8.1 Installer issues
- [x] Review any other last minute pull requests
- [x] Update README
- [x] Test on all platforms
- [x] Tag RC2
- [ ] Final Testing
- [ ] Tag v9.2.0

**Comment by mjwitte** [comment]
Cleaning up old RC installs by running the maintenance tool and just realized that it's deleting all EP-Launch settings from the registry. Ugh.

**Comment by mjwitte** [comment]
And that generates an error during uninstall of the next folder, because the keys are gone.

**Comment by Myoldmopar** [comment]
Thanks @mjwitte, @jmarrec any thoughts about this issue?

**Comment by mjwitte** [comment]
This is the error message that comes up on the second consecutive uninstall:
![image](https://user-images.githubusercontent.com/4991075/65703774-eecb1880-e04a-11e9-8470-a0dd56a7833a.png)
This key deletion is what I hope we can prevent.

**Comment by jmarrec** [comment]
Hum, I thought I cornered that case here https://github.com/NREL/EnergyPlus/blob/087671f57a95f899e49500f158090cba8606e1e3/cmake/qtifw/install_registerfiletype.qs#L33:L36

Are you sure you're not uninstalling some older test installers? Can someone try to install both rc2 and rc3 for eg?
Worst case we can just not delete them...

**Comment by jmarrec** [comment]
This block of code is actually there just to clean up some previous things done by the NSIS installers and should eventually be removed. Registering filetypes wouldn't work on a machine that had installed a previous E+ version

**Comment by mjwitte** [comment]
Earlier today it's certainly possible some of the folders were from older installers. I'm fairly certain I repeated the test with today's installer, but I will redo that to be sure.

**Comment by mjwitte** [comment]
@jmarrec Finally retested this (computer decided to have issues . . . ). Using the 9.2-RC3 installer: installed to folder A, installed again to folder B. Opened EP-Launch and changed some settings. Uninstalled folder B. Opened EP-Launch, settings are back to defaults.

**Comment by mjwitte** [comment]
@jmarrec Just to be clear, I expected the settings in the registry to remain intact for use by other copies of ep-launch; same as what the old installer did.

**Comment by jmarrec** [comment]
@mjwitte Ok there's the section that does that:

https://github.com/NREL/EnergyPlus/blob/e5409c525216085346653a731cbc74eb1ebb46d6/cmake/qtifw/install_operations.qs#L62:L64

I'll remove that then.
