### ISSUE TITLE
Fluid Cooler Crash

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#7533]
Issue overview
--------------
A user file is crashing in the fluid cooler sizing code because the plant sizing index is zero.  The fluid cooler is not autosized at all, and the file shouldn't need a sizing:plant object.  Adding a dummy sizing:plant object for that loop allows the file to avoid a hard crash (encounters a fatal error which is a different problem...for now).

Should probably address #5353 while at it. (Which is a follow on from a similar bug fix #5305).

Once fixed, the code should properly handle a fluid cooler file without sizing objects in the file.  As a second verification, you could hardsize a fluid cooler example file and remove the plant sizing objects and see if it does the same thing.

### Details
Some additional details for this issue (if relevant):
 - Platform: Original user is Windows, I believe, but I reproduced the issue on Linux
 - Version of EnergyPlus: file is 9.1, but I transitioned it to 9.2 and it had the same behavior

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added: [FluidCoolerCrash_9.1.idf.txt](https://github.com/NREL/EnergyPlus/files/3672493/FluidCoolerCrash_9.1.idf.txt)
 - [ ] Ticket added to Pivotal for defect: #168846714

**Comment by dareumnam** [comment]
[FluidCoolerCrash_9.2.idf.txt](https://github.com/NREL/EnergyPlus/files/3768431/FluidCoolerCrash_9.2.idf.txt)
