### ISSUE TITLE
Some key choices for No Load Supply Air Flow Rate Method field in AirLoopHVAC:UnitarySystem are broken

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#7547]
Of the six choice keys in No Load Supply Air Flow Rate Method field only SupplyAirFlowRate and FlowPerFloorArea work correctly. The other four methods either fatal out or return zero flow rate.

Defects file tested using EnergyPlus V9.10 shows:
(1) If FractionOfAutosizedCoolingValue is selected this field is sized to 0.0 and simulation continuous 
(2) FractionOfAutosizedHeatingValue, FlowPerCoolingCapacity and FlowPerHeatingCapacity fatal out.

  A22, \field No Load Supply Air Flow Rate Method
       \type choice
       \key None
       \key SupplyAirFlowRate
       \key FlowPerFloorArea
       \key FractionOfAutosizedCoolingValue
       \key FractionOfAutosizedHeatingValue
       \key FlowPerCoolingCapacity
       \key FlowPerHeatingCapacity

Defect files tested using develop version shows:
(1) If FractionOfAutosizedCoolingValue is selected, E+ fatal out with the following error
Note that the error message is incorrect, it refers to wrong field for problem description. see below:

   ** Severe  ** AirLoopHVAC:UnitarySystem = THERMAL ZONE ONE SZ-VAV SYSTEM
   **   ~~~   ** Input for No Load Supply Air Flow Rate Method = FractionOfAutosizedCoolingValue.
   **   ~~~   ** Blank field not allowed for No Load Supply Air Flow Rate Per Unit of Capacity During Cooling Operation
   **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs

(2) If FractionOfAutosizedHeatingValue is selected, E+ fatal out with the following error
Note that the error message is incorrect, it refers to wrong field for problem description. see below:
   ** Severe  ** AirLoopHVAC:UnitarySystem = THERMAL ZONE ONE SZ-VAV SYSTEM
   **   ~~~   ** Input for No Load Supply Air Flow Rate Method = FractionOfAutosizedHeatingValue.
   **   ~~~   ** Blank field not allowed for No Load Supply Air Flow Rate Per Unit of Capacity During Heating Operation
   **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs
 

(3) If FlowPerCoolingCapacity is selected, E+ runs but No Load Supply Air Flow Rate is sized to 0.0. See below:
 Component Sizing Information, AirLoopHVAC:UnitarySystem, THERMAL ZONE ONE SZ-VAV SYSTEM, Design Size Supply Air Flow Rate [m3/s], 0.54651
 Component Sizing Information, AirLoopHVAC:UnitarySystem, THERMAL ZONE ONE SZ-VAV SYSTEM, Design Size Heating Supply Air Flow Rate [m3/s], 0.54651
 Component Sizing Information, AirLoopHVAC:UnitarySystem, THERMAL ZONE ONE SZ-VAV SYSTEM, Design Size Cooling Supply Air Flow Rate [m3/s], 0.54651
 Component Sizing Information, AirLoopHVAC:UnitarySystem, THERMAL ZONE ONE SZ-VAV SYSTEM, Design Size No Load Supply Air Flow Rate [m3/s], 0.00000

(4) If FlowPerHeatingCapacity is selected, E+ fatal out with the following error.
Note that the error message says black field but it is not. see error message eblow:
   ** Severe  ** AirLoopHVAC:UnitarySystem = THERMAL ZONE ONE SZ-VAV SYSTEM
   **   ~~~   ** Input for No Load Supply Air Flow Rate Method = FlowPerHeatingCapacity.
   **   ~~~   ** Blank field not allowed for No Load Supply Air Flow Rate Per Unit of Capacity During Heating Operation
   **  Fatal  ** getUnitarySystemInputData: previous errors cause termination. Check inputs

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (V9.1 and current develop)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
uploaded defect files.

**Comment by mjwitte** [comment]
@Nigusse @rraustad Ran into this with another user's file. Looks like there are several fields in [UnitarySystem::getUnitarySystemInputData](https://github.com/NREL/EnergyPlus/blob/a39c7dc5238bfa4812562d1ff610bdcf8220fa7b/src/EnergyPlus/UnitarySystem.cc#L2784-L2792) that have incorrect field names in the `fields.find` function, e.g.:
```
                if (fields.find("no_load_fraction_of_autosized_cooling_supply_air_flow") != fields.end()) { // not required field
                    loc_m_NoCoolHeatSAFMethod_FracOfAutosizedCoolingSAFlow = fields.at("no_load_fraction_of_autosized_cooling_supply_air_flow");

  N13, \field No Load Fraction of Autosized Cooling Supply Air Flow Rate

```
`_rate` is missing from the end of the field name, so it fails the if !=fields.end() and the user input for that field is ignored as if the field was blank.

@Myoldmopar @mbadams5 This is a weak link that requires unit testing every field input to make sure it finds the correct value which is probably a good idea anyway. However, would it be possible to add some verification in fields.find that throws an error if the requested field name doesn't exist in the schema?
