### ISSUE TITLE
Segmentation Fault when AirLoopHVAC doesn't have a single component in the main branch

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7552]
Issue overview
--------------

I was doing a dummy test for OpenStudio, I just created an AirLoopHVAC (empty), and assigned an AVM NigthCycle, then launched the simulation, expecting it to crash, but not to segfault.

Crash with file happens here: https://github.com/NREL/EnergyPlus/blob/a39c7dc5238bfa4812562d1ff610bdcf8220fa7b/src/EnergyPlus/BranchInputManager.cc#L3044

InletNode is 0.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: develop, 9.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/7000s/7552/7552_crash.idf
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@jmarrec I downloaded 7552_crash.idf and ran it using the current develop code.  It crashed with a fatal error.  Here are the warning messages that I got:

   ** Severe  ** GetAirPathData: AirLoopHVAC="AIR LOOP HVAC 1", branch in error.
   **   ~~~   ** Probable missing or misspelled node referenced in the branch(es):
   **   ~~~   ** Possible Error in Branch Object="AIR LOOP HVAC 1 MAIN BRANCH".
   **   ~~~   ** ...looking to match to Node="NODE 2".
   ** Severe  ** GetAirPathData: AirLoopHVAC="AIR LOOP HVAC 1", connection to zone.
   **   ~~~   ** No Connection found for Return Air from Zone
   **   ~~~   ** Expected node name ="NODE 1".
   ** Warning ** GetAirPathData: AirLoopHVAC="AIR LOOP HVAC 1" has no Controllers.
   ** Severe  ** GetAirPathData: AirLoopHVAC = "AIR LOOP HVAC 1".
   **   ~~~   ** ..Invalid Air Loop Component Type = "".
   **   ~~~   ** ..Air Loop Component Name = "".
   **   ~~~   ** ..reference Branch = "AIR LOOP HVAC 1 MAIN BRANCH".
This seems like a different response than what you got which is strange.  In fact, I put a breakpoint at the line of code that you noted and it never got to that point.  Could you double check that the version of the input file that you uploaded is the same one that caused the segfault that you saw and that it is still existing in EnergyPlus?
Either way, the error messages seem to be a bit vague.  It could easily say something to the effect that a branch has no components on it.  I don't think that is or should be allowed.

**Comment by jmarrec** [comment]
@RKStrand I am really unsure what happened there, sorry about this.

I tried to reproduce the initial crash with OpenStudio (on another machine) but couldn't. I'll try to check on the initial machine to see if I can reproduce and will reopen if I can. I don't have this machine handy at the moment, so it might be a few days before I can try.
