### ISSUE TITLE
"Normalization Reference" transition error in "Table:MultiVariableLookup" from 9.1 to 9.2

### ISSUE THREAD

**Issue by hongyuanjia** [NREL/EnergyPlus#7560]
Issue overview
--------------
### Details
 - Platform (Operating system, version): Windows, OS X and Linux
 - Version of EnergyPlus: v9.2
 - Unmethours link or helpdesk ticket number: N/A

### Checklist
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/7000s/7560
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

I am trying to add transition support from v9.1 to v9.2 to my [R package](https://github.com/hongyuanjia/eplusr/pull/138). When looking at the source file `CreateNewIDFUsingRulesV9_2_0.f90`, the `InArgs(13)` on line 775 seems to be wrong. That line should reference to field `Normalization Reference` in class `Table:MultiVariableLookup` in v9.1, which is field 9 instead of 13 (field 13 is `Maximum Value of X2`). Line 780 seems to be correct.

https://github.com/NREL/EnergyPlus/blob/0e6e9c08a048eb9bb04387a61384bd842816c52f/src/Transition/CreateNewIDFUsingRulesV9_2_0.f90#L775-L781

Please correct if I am wrong. Hope this helps.

**Comment by jmarrec** [comment]
Thanks for the catch @hongyuanjia ! Indeed, you are right.

This is probably a copy paste error from the Table:TwoIndependentVariable rule that's a few lines above.

**Comment by hongyuanjia** [comment]
@jmarrec Glad to help!
