### ISSUE TITLE
Insufficient sizing due to large supply approach temperatures in ITE electric equipment

### ISSUE THREAD

**Issue by xuanluo113** [NREL/EnergyPlus#7561]
Issue overview
--------------
When using FlowControlWithApproachTemperatures in`ElectricEquipment:ITE:AirCooled` objects, we found the systems can be undersized due to large supply approach temperatures that the user defines. In the ITE object, the CPU load and IT fan power under design conditions were applied during sizing. However, both the CPU load and the IT fan power could vary considerably with the IT inlet temperature, determined by user input performance curves. For example, when the actual IT inlet temperature rises 10C, the IT fan power can go up as high as 50%. This would cause insufficient sizing capacity of the coil and chiller, and further none converging issue in the zone heat balance calculation. Hard sizing the chiller with higher capacity makes the simulation ran through. 

To solve the issue, we propose to take this variation into consideration during sizing. We propose add the following logic to the sizing calculation of the ITE object: 
(1) calculate the IT inlet T based on design supply air T and the supply approach T
(2) calculate the IT fan flow and power under this IT inlet T using the two curves in the ITE object
(3) compare this IT fan power with design value, if larger, use this new value instead.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by xuanluo113** [comment]
@mjwitte We've been working on this but met some issues that we spent a lot of time but don't know exactly how to fix. I was wondering if you have time you can review and provide some suggestions to save us. Thanks! Summarized below.

According to what we proposed in this issue, we implemented the logic at PR #7582. This logic overwrites the Convective Internal Heat Gain from the ITE object, and then affects the sizing of the HVAC objects, including the Chiller. However, with these changes the sizing is still not sufficient.
 
For example, in the attached IDF, the design inlet temperature is 22.5C, and the calculated design ITE power (considered as heat gain in sizing) is 3.47117e+06 W, and the *autosized chiller sizing* is 4.34941e+06 W (with a sizing factor of 1.2).

After overwriting the *maximum ITE inlet temperature* to 37 C (max supply temp 27C + approach temp 10C), the calculated design ITE power is 3.91094e+06, which is almost the total `InternalHeatGain `of the zone, which is 3.91586e+06, and the  *autosized chiller sizing* is enlarged to 4.69126e+06 W.
 
We thought this chiller sizing would be sufficient with *1.2X sizing factor*, and the supply temperature should never reach 27C (the max value system allows), but during run time it still does. As the results printed in the attached spreadsheet, on Day 3 we set the Datacenter Equipment schedule fraction to 1, as on Day 4 the temperature started to run out of bound. As soon as ITE supply temperature is over 27C, the ITE run time heat gain run out of bounds of the design value, and then causes an iterative effect on insufficient sizing and the program fails.
 
We were trying to identify why the chiller sizing is still not sufficient. *(1) Changing the sizing factor from 1.2 to 1.3; (2)Hard sizing the Chiller by a small amount (~6%), or (3)hard-coding the ITE design power by the same amount* would fix the issue. Couldn’t think of a good explanation and was hoping to get some advice on where to look at.

<img width="720" alt="Screen Shot 2019-11-11 at 3 48 20 PM" src="https://user-images.githubusercontent.com/23508095/68694070-4e16b680-052d-11ea-9134-8d64b6fbc4bf.png">

[ITE bug.xlsx](https://github.com/NREL/EnergyPlus/files/3837370/ITE.bug.xlsx)

[ite-1zone.idf.txt](https://github.com/NREL/EnergyPlus/files/3837374/ite-1zone.idf.txt)

**Comment by mjwitte** [comment]
@XuanLuoLBL I've puzzled over this, adding many new outputs, trying to shut off various things (EMS, humidifier, etc.) and I do not have an answer. This particular test file uses the CommonPipe option in the chilled water loop. I would try removing that (and the secondary chilled water pump) to see if that alters the result. 

When run for design days, this doesn't even make it past the first warmup day. I can't help thinking that there's still a fundamental imbalance in all of the `HasAdjustedReturnTempByITE` adjustments in ZoneTempPredictorCorrector and elsewhere. For example, it doesn't seem right that the zone return node temperature remains fixed across each zone time step.

So, to get around that I tried changing the timestep to 60. The zone overheats even more quickly fails at 01:32 on the first warmup day compared to 02:19 with TS=6. Both are dismal, but this implies there's some kind of imbalanced feedback loop in the ITE load adjustments. Here are the test files: 
[7561-ITE chiller sizing.zip](https://github.com/NREL/EnergyPlus/files/3843803/7561-ITE.chiller.sizing.zip)

**Comment by xuanluo113** [comment]
@mjwitte Mike, we troubleshoot this issue again and found out the problem was with `Coil:Cooling:Water`. In the idf, we had a hard sized `Design Outlet Air Temperature` to be always the same with T_air_inlet, which causes the chiller sizing to be insufficient. Changing it to 'Autosize' fixed it, with the current solution. Thanks so much for your help.

About the zone return node, since the 99% of total zone heat gain is from the ITE object, and it does not have many variations throughout the year, the zone return node temperature is pretty much constant as well.

I'd clean up the branch and hope you could help with the review.

**Comment by mjwitte** [comment]
Closed via #7582
