### ISSUE TITLE
Imperial conversion of coil leaving air humidity ratio in Coil Sizing Summary shows temperature 

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7565]
Issue overview
--------------
Test of example file 5ZoneWaterCooled_HighRHControl shows incorrect conversion of humidity ratio in Coil Sizing Summary and Coil Sizing Details report in column "Coil Leaving Air Humidity Ratio at Ideal Loads Peak [F]".

Only change to example file is:

  OutputControl:Table:Style,
    HTML,                    !- Column Separator
    InchPound;

![image](https://user-images.githubusercontent.com/5778156/67014560-04b88000-f0c3-11e9-80f5-c3a7986342e1.png)

The Component Sizing Summary report for Coil:Cooling:Water is also missing units for humidity ratio.

![image](https://user-images.githubusercontent.com/5778156/67015716-f4090980-f0c4-11e9-97db-a41cf07c466b.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (use example file 5ZoneWaterCooled_HighRHControl or any water coil file)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
It's a typo in the SI unit one actually, `Coil Leaving Air Humidity Ratio at Ideal Loads Peak [C]`. I will fix this one and another one I found and will look for more incoherence in the file.
For the missing one, WaterCoils.cc has the units commented out, and it's been this way for at least 6 years. I'll put the units back, I see no reason not to.

While on the subject, it seems two units are used for Humidity Ratio: `[kgWater/kgAir]` and `[KGWATER/KGDRYAIR]`. Would it make sense to use this opportunity to standardize around a single one? `[kgWater/kgAir]` perhaps? @rraustad @mjwitte thoughts?

**Comment by mjwitte** [comment]
@jmarrec I thought we cleaned up all the kgAir years ago. It should be `[kgWater/kgDryAir]` to avoid any ambiguity. Searching the I/O Ref, I found a few instances of "kgAir" remaining. These could be cleaned up as well - I check the rdd for one of them and the rdd is kgDryAir.

**Comment by jmarrec** [comment]
There are a couple:

```
OutputReportPredefined.cc:1920:        pdchZnClPkIndHum = newPreDefColumn(pdstZoneClSize, "Indoor Humidity Ratio at Peak Load [kgWater/kgAir]");
OutputReportPredefined.cc:1922:        pdchZnClPkOAHum = newPreDefColumn(pdstZoneClSize, "Outdoor Humidity Ratio at Peak Load [kgWater/kgAir]");
OutputReportPredefined.cc:1938:        pdchZnHtPkIndHum = newPreDefColumn(pdstZoneHtSize, "Indoor Humidity Ratio at Peak Load [kgWater/kgAir]");
OutputReportPredefined.cc:1940:        pdchZnHtPkOAHum = newPreDefColumn(pdstZoneHtSize, "Outdoor Humidity Ratio at Peak Load [kgWater/kgAir]");
OutputReportTabular.cc:14099:                    rowHead(4) = "Outside Humidity Ratio at Peak [kgWater/kgAir]";
OutputReportTabular.cc:14102:                    rowHead(7) = "Zone Humidity Ratio at Peak [kgWater/kgAir]";
OutputReportTabular.cc:15954:        UnitConv(33).siName = "KGWATER/KGAIR";
```

I'll standardize around `[kgWater/kgDryAir]` (case sensitive) then.
