### ISSUE TITLE
Wrong unit in the calculation of ITE Air Inlet Relative Humidity

### ISSUE THREAD

**Issue by xuanluo113** [NREL/EnergyPlus#7581]
Issue overview
--------------
The declared unit of the reportable variable `ITE Air Inlet Relative Humidity` is percentage.

`Output:Variable,*,ITE Air Inlet Relative Humidity,hourly; !- Zone Average [%]`

In the current implementation, it is calculated as decimal [0, 1]. Need a quick fix to be multiplied by 100%.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
This also impacts these related output variables which check ranges declared as [%].
```
Output:Variable,*,ITE Air Inlet Relative Humidity Above Operating Range Time,hourly; !- Zone Sum [hr]
Output:Variable,*,ITE Air Inlet Relative Humidity Below Operating Range Time,hourly; !- Zone Sum [hr]
Output:Variable,*,ITE Air Inlet Relative Humidity Difference Above Operating Range,hourly; !- Zone Average [%]
Output:Variable,*,ITE Air Inlet Relative Humidity Difference Below Operating Range,hourly; !- Zone Average [%]
```
