### ISSUE TITLE
Restore silent install option

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7589]
Issue overview
--------------
From one corporate and one university admins:
Is there a silent command line install available for the EnergyPlus-9.2.0-921312fa1d-Windows-x86_64.exe installer? For previous versions we were able to deploy silently via SCCM using /S /D=C:\EnergyPlusV9-2-0 but this latest installer does not appear to have the option available.

We've historically distributed this software with SCCM, using the '/S' switch to install it silently. It appears that this no longer works with 9.2.0. Is there a different switch we can use?

From @jmarrec regarding the new installer software:
you can create stuff that allows silent install on QtIFW, but it requires writing a javascript file (that mimics going to next page etc).

### Details
Some additional details for this issue (if relevant):
 - Platform Windows
 - Version of EnergyPlus v9.2.0
 - Helpdesk ticket number 15290 and 15298

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by gtaylor-feduni** [comment]
I am also attempting to deploy EnergyPlus with SCCM in a University setting and having similar issues to @mjwitte. I did locate some information about scripting QtIFW installs but this wasn't sufficient to successfully create a silent install script for EnergyPlus.

A sample silent install script and documentation of the new QtIFW installer would be greatly appreciated.

**Comment by jmarrec** [comment]
@gtaylor-feduni I'm writing an install script, which I am fine testing in regular `cmd.exe` on Windows, but I don't have any knowledge of SCCM so I'd ideally need someone who could try it out for me (a nice side effect would be that perhaps you could start rolling out your deployment in the next couple of days if it works fine).

Could you please reach out to me at julien at effibem dot com if you are willing to test it? It shouldn't take much of your time. Thanks!

**Comment by gtaylor-feduni** [comment]
@jmarrec I would be happy to help with testing your install script. SCCM is a software management suite created by Microsoft to manage large numbers of Windows PCs. SCCM is used for Software Updates, Operating System Deployment and Application deployment.

SCCM runs application deployments in the SYSTEM context on each device. You can replicate this using Sysinternals PSEXEC to create a command prompt in the system context and run your script from there. To start a command prompt in the system context use the following command:

psexec -s -i cmd.exe

Running an application in the SYSTEM context is similar to running an application as administrator but with some important differences. The TEMP/TMP folder for the SYSTEM account is C:\WINDOWS\TEMP while the User Profile is located in C:\Windows\System32\config\systemprofile. The SYSTEM user profile folder does not contain the folders normally found in a user profile such as Documents, Desktop and Pictures. Shortcuts added to the Start Menu located in the SYSTEM user profile do not show up when logged in as a normal user. Start Menu shortcuts should be created in the ALLUSERSPROFILE (C:\ProgramData).

PsExec v2.2:
https://docs.microsoft.com/en-us/sysinternals/downloads/psexec

How to: become the LOCAL SYSTEM account with PsExec:
https://specopssoft.com/blog/how-to-become-the-local-system-account-with-psexec/

**Comment by gtaylor-feduni** [comment]
The script provided by @jmarrec worked perfectly. I ran the script with the following command line:

EnergyPlus-9.2.0-<id>-Windows-x86_64.exe --script install_script.qs AllUsers=true

This installed EnergyPlus in "C:\EnergyPlus-9-2-0" and created start menu shortcuts in the all users profile and an entry in Add/Remove programs under HKLM. 

I was also able to successfully uninstall EnergyPlus with the following command line:

maintenancetool.exe --script install_script.qs AllUsers=true

Thanks again @jmarrec for creating the install_script.qs and working through the issue so quickly.

**Comment by jmarrec** [comment]
@gtaylor-feduni FYI I was going to try to install the `install_scripts.qs` as `uninstall_script.qs` to put it next to the maintenancetool.exe in the user's installation folder.
And I know how to do that without any problem.
But we're trying to keep multiple build systems (like DEB on Unix) and installing some files only for QtIFW and not other cpack generator has proven _very_ difficult, so I gave up on it (not worth the effort).

**Comment by ghost** [comment]
Just want to  throw in my two cents also say that I was able to use the same strings in SCCM. 

Install is in a .bat file creates that directory on the root and copies over the .qs file and has this line: %curpath%\EnergyPlus-9.2.0-64.exe --script install_script.qs AllUsers=true 
(where %curpath% is the current path for SCCM)

Uninstall string is: "C:\EnergyPlusV9-2-0\maintenancetool.exe" --script install_script.qs AllUsers=true
