### ISSUE TITLE
EIR WWHP Electric Input to Output Ratio Modifier Function of Part Load Ratio Curve Name is ignored

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7590]
Issue overview
--------------
For both HeatPump:WaterToWater:EIR:Heating (and Cooling)  the"Electric Input to Output Ratio Modifier Function of Part Load Ratio Curve Name" is ignored. The "Electric Input to Output Ratio Modifier Function of Temperature Curve Name" get used for both the EIR fT and EIRfPLR curves.

The offending pasteo in the code is [here](https://github.com/NREL/EnergyPlus/blob/0e6e9c08a048eb9bb04387a61384bd842816c52f/src/EnergyPlus/WaterToWaterHeatPumpEIR.cc#L1016-L1028).

And @mitchute the offending code is still [here](https://github.com/NREL/EnergyPlus/pull/7489/files#diff-d5cec73fe6ecb0d05b1d13a456017641R1065) in #7489 

### Workaround
With this bug, the power consumption is being computes as 
(loadSideHeatTransfer  / referenceCOP) * EIRfT(loadSideOutletTemp, sourceSideInletTemp) * **EIRfT**(partLoadRatio). 

I suppose if one were to make a table object with appropriate output values for inputs in the range of 0 to 1, this might work, as long as the temperature variables are never expected to operate near freezing.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.2.0 (and 9.1)
 - Unmethours [40787](https://unmethours.com/question/40787/heatpumpwatertowatereir-models-curves-report-wrong-values/)or helpdesk ticket number 15300

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
Addressed by #7714. Closing.
