### ISSUE TITLE
AHU fault

### ISSUE THREAD

**Issue by nbt2019** [NREL/EnergyPlus#7594]
Issue overview
--------------
Hi, I want to apply fault to the AHU of a building. The faults that I want are about terminal unit reheat valve, supply air temperature, valve position, supply fan VFD speedterminal unit damper position, etc. could you please help me , because I couldn't find a way to apply fault to these components. 

### Details
Some additional details for this issue (if relevant): - windows 10
 - Version of EnergyPlus 8.9.0

**Comment by jmarrec** [comment]
@nbt2019 Check out the existing FaultModel:* objects in the I/O reference guide.
If you do not find a specific faultmodel for a feature you want to test, you can look into EnergyManagementSystem objects to try to implement it yourself.

If you need more help after doing your research, then narrow down your problem and post a question on https://unmethours.com. I suggest making a single question for a specific fault you want to model to maximize chances of getting help. If you're question is too broad (like it is now), then it's unlikely going to receive much attention.

I'm closing this as it's not an issue per se.
