### ISSUE TITLE
Unsuccessful simulation using PerformancePrecisionTradeoffs

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#7601]
Issue overview
--------------
When I add `PerformancePrecisionTradeoffs, Yes;` to my IDF, the simulation just stops after "Initializing Simulation" and the err file is empty. If I change the object to `PerformancePrecisionTradeoffs, No;`, it runs successfully.

File to reproduce:
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/3811168/in.idf.txt)

@XuanLuoLBL 

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - EnergyPlus 9.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
My expectation was that the direct coil solution would be used for PLR calculation for all supported coils in the model (`AirLoopHVAC:UnitarySystem` with `Coil:Heating:Fuel` and `Coil:Cooling:DX:SingleSpeed` in the attached file) and not used for all unsupported coils/systems (perhaps `ZoneHVAC:IdealLoadsAirSystem` in the attached file?).

I can't tell if our file is supposed to run but there's a bug, or supposed to throw an error message.

**Comment by yzhou601** [comment]
With the same object turned on for another model with `Coil:Cooling:DX:SingleSpeed` and `Coil:Heating:DX:SingleSpeed`, I can run 1 successfully over 5 simulation trials (without changing anything in the model or weather file). [Defect file](https://drive.google.com/file/d/16ffa0KWQuk3lyPr3dmr5xwaaQyR6oyJC/view?usp=sharing)

**Comment by xuanluo113** [comment]
@lgu1234 Lixing, it seems it's not anything related to the object input. Do you mind checking the coil implementation? Thanks

**Comment by lgu1234** [comment]
@XuanLuoLBL I will take a look next week.

**Comment by shorowit** [comment]
https://github.com/NREL/EnergyPlus/pull/7636

**Comment by Myoldmopar** [comment]
Closed via #7636
