### ISSUE TITLE
HVACSystemRootFindingAlgorithm input option for Bisection algorithm not working. 

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#7604]
Issue overview
--------------
Discovered during testing different algorithms with a user file.

Small capitalization typo doesn't allow bisection input to work:
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HeatBalanceManager.cc#L1365

lowercase "i" should be uppercase "I"

The following error should not occur when entering Bisection into HVACSystemRootFindingAlgorithm object.
```
   ** Warning ** HVACSystemRootFindingAlgorithm: Invalid input of Algorithm. The default choice is assigned = BISECTION
   **   ~~~   ** Valid choices are: RegulaFalsi, Bisection, BisectionThenRegulaFalsi, RegulaFalsiThenBisection, or Alternation.
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #7641
