### ISSUE TITLE
EnergyPlus doesn't output: ZoneThermalComfortFangerModelPPD (v9.1, v9.2)

### ISSUE THREAD

**Issue by YanfeiNREL** [NREL/EnergyPlus#7610]
Issue overview
--------------
The energyplus v9.1 and v9.2 both does not output "Zone Thermal Comfort Fanger Model PPD" for specified zones, in the generated output.csv file.
I requested Fanger model for People module, and specified the AirVelocity Schedules, Clothing Insulation Schedules, Working Efficiency Schedules. 
I tried other thermal comfort models, like: Pierce, KSU. They are the same issue.
### Details
Some additional details for this issue (if relevant):
 - Platform (Windows, and Linux)
 - Version of EnergyPlus ( v9.1 and v9.2)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
The idf files are given in the attachment for both version 9.1 and 9.2. 

[idf_files.zip](https://github.com/NREL/EnergyPlus/files/3828098/idf_files.zip)

**Comment by Nigusse** [comment]
@YanfeiNREL The "Zone Thermal Comfort Fanger Model PPD" report variable is generated by people object not by the zone object. Use people object name, instead of zone object name.

Output:Variable,SPACE1-1 People 1, Zone Thermal Comfort Fanger Model PPD,Hourly;
Output:Variable,SPACE1-1 People 1, People Occupant Count,Hourly;

**Comment by YanfeiNREL** [comment]
Thanks for your help. It worked based on your suggestion. I suggest we add this note to the InputOutputRef document. 
I have another issue: i made a people object for a zonelist, and when i tried to output the zone PPD, i got no output variables relate with PPD.

[in002.zip](https://github.com/NREL/EnergyPlus/files/3880996/in002.zip)

**Comment by mjwitte** [comment]
With ZoneList, the output variable key names are a combination of zone name plus people object name. Ask for the variable with * and you'll see the outputs and how the names are built.
Output:Variable, *, Zone Thermal Comfort . . .

**Comment by YanfeiNREL** [comment]
Thanks. solved!
