### ISSUE TITLE
PlantLoop:HeatPump:EIR:Cooling/Heating electric energy is not on any meter

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7611]
Issue overview
--------------
User requested that the electric energy for HeatPump:WaterToWater:EIR:Heating and Cooling be metered on separate end uses, Cooling:Electricity and Heating:Electricity. This would follow the patter of the other water-to-water heat pumps.

However, checking the mtd output and the [current source code](https://github.com/NREL/EnergyPlus/blob/0e6e9c08a048eb9bb04387a61384bd842816c52f/src/EnergyPlus/WaterToWaterHeatPumpEIR.cc#L344-L346) shows that the electric energy use is not any *any* meter at all.

@mitchute 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus v9.2.0
 - Helpdesk ticket number 15317.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file: use example file WaterToWaterHeatPump_EIR
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by nealkruis** [comment]
@mjwitte @mitchute Is it okay if I have someone at Big Ladder take a crack at resolving this one?

**Comment by mjwitte** [comment]
@nealkruis Since this code is changing in #7489 it's probably best dealt with there.

**Comment by mitchute** [comment]
@nealkruis Unless I hear otherwise, I'm gonna take this one.
