### ISSUE TITLE
EnergyPlus as cmake sub project

### ISSUE THREAD

**Issue by kbenne** [NREL/EnergyPlus#7613]
Issue overview
--------------
EnergyPlus does not lend itself to be used as a cmake sub project, meaning if you try to add_subdirectory(EnergyPlus) from a parent cmake project it will typically fail. This is because the variable CMAKE_SOURCE_DIR is often used, where a better choice would be PROJECT_SOURCE_DIR. The former will resolve to the top level source directory, whereas the latter will always resolve to the root of the EnergyPlus project source directory. 

Reference
--------------
https://stackoverflow.com/questions/32028667/are-cmake-source-dir-and-project-source-dir-the-same-in-cmake

I will propose a PR to address this issue.

**Comment by jmarrec** [comment]
Fixed via https://github.com/NREL/EnergyPlus/pull/7616
