### ISSUE TITLE
Inconsistent field name in Curve:DoubleExponentialDecay

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7617]
Issue overview
--------------

This is a (very) minor issue about an inconsistent naming of field in a curve:

```
Curve:DoubleExponentialDecay,
       \memo Double exponential decay curve with one independent variable.
       \memo Input consists of the curve name, the five coefficients, and the maximum and minimum
       \memo valid independent variable values. Optional inputs for the curve minimum and
       \memo maximum may be used to limit the output of the performance curve.
       \memo curve = C1+C2*exp(C3*x)+C4*exp(C5*x)
  A1 , \field Name
       \required-field
       \type alpha
       \reference UnivariateFunctions
  N1 , \field Coefficient1 C1
       \required-field
       \type real
  N2 , \field Coefficient2 C2
       \required-field
       \type real
  N3 , \field Coefficient3 C3
       \required-field
       \type real
  N4 , \field Coefficient3 C4
       \required-field
       \type real
  N5 , \field Coefficient3 C5
       \required-field
       \type real
```

I would expect

```
  N4 , \field Coefficient4 C4
  N5 , \field Coefficient5 C5
```

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus (if using an intermediate build, include SHA): current develop. 9.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@jmarrec Since this is a fairly minor issue, I suggest that this be lumped together with #7760

**Comment by jmarrec** [comment]
@RKStrand The I/O ref is actually just fine (cf [here](https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-performance-curves.html#field-coefficient4-c4-2)), so if you don't mind I'll lump this one into something else where I do IDD changes instead.

**Comment by RKStrand** [comment]
@jmarrec Sounds good to me--thanks!
