### ISSUE TITLE
Curve:ExponentialSkewNormal documentation isn't in line with actual equation

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7618]
Issue overview
--------------

https://bigladdersoftware.com/epx/docs/9-2/input-output-reference/group-performance-curves.html#curveexponentialskewnormal

![image](https://user-images.githubusercontent.com/5479063/68877485-73125180-0706-11ea-813c-af0f868e1065.png)

https://github.com/NREL/EnergyPlus/blob/b4404bb76c8f9d0a63f952ff3f6efc0341f671d6/src/EnergyPlus/CurveManager.cc#L2457-L2465

At least z1 is wrong in the doc.

* Source code: `z1 = (x - c1) / c2`
* Doc: `z1 = (x * c1) / c2`

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
It looks to me that the source code is OK, just the docs need updating. See the following from plotting the ```FanEff120CPLANormal``` curve from the ```StripMallZoneEvapCooler.idf``` file.

![image](https://user-images.githubusercontent.com/2985979/73627106-5573ca80-4619-11ea-9a58-a52cf1c40127.png)


Is this right? I'm not finding any references regarding how the curve should be formed.

**Comment by jmarrec** [comment]
Addressed in #7666 as well, cf screenshot https://github.com/NREL/EnergyPlus/pull/7666#issuecomment-581361460
