### ISSUE TITLE
Standardize Output Variable and Meter Fuel Types

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7622]
**This is part 4 of 4: Part 1 = #7532, Part 2 = #7523 , and Part 3 is #7621.**

Issue overview
--------------
This is the final piece of standardizing fuel type on both input and output. Issues #5941 and #7621 dealt with the input side, with the goal of no diffs. This issue takes the plunge and modifies output variable names and meter names to the final standard list:

**Input choice, Meter Resource and Output Variable, Table Headings** (*updated 03 Aug 2020 MJW*)
Electricity, Electricity, Electricity
NaturalGas, NaturalGas, Natural Gas
Propane, Propane, Propane
Diesel, Diesel, Diesel
Gasoline, Gasoline, Gasoline
FuelOilNo1, FuelOilNo1, Fuel Oil No 1
FuelOilNo2, FuelOilNo2, Fuel Oil No 2
Coal, Coal, Coal
OtherFuel1, OtherFuel1, Other Fuel 1
OtherFuel2, OtherFuel2, Other Fuel 2
Water, Water, Water

Note that Meter Resource = Input Choice when this is all done. That may allow some simplification in how the objects use fuel types.

This will impact:

1. Meter resource types for Gas will become NaturalGas.

2. Output variable names will change for Electricity, NaturalGas, FuelOilNo1, FuelOilNo2, OtherFuel1, and OtherFuel2 ( more less?). This will required potentially many lines in the transition Report Variables 9-2-0 to 9-3-0.csv - script this? Or see modify transition to replace on substrings - maybe that's better.

3. Electricity output variables are currently different from other fuels. "Electric Power" and "Electric Energy" vs others that are "Gas Rate" and "Gas Energy". So, if we go with always matching the long version of the input fuel type, then these would become "Electricity Rate" and "Electricity Energy" - a little less natural, but makes things consistent across all fuel types. ~Yes? No? Some other approach?~ *updated 03 Aug 2020 MJW - Yes, change to Electricity Rate and Electricity Energy.*

4. For the most part table output column headings are using the desired strings, but some column headings may be affected and some table row headings may change.

5. There will be diffs everywhere:  mtd, eso, mtr, table - even though it's more work, it may be best to stage this in 2 parts: change the meters first (there should be no eso diffs) then change the output variables (there should be no mtr diffs). Or make a special version of mathdiff that can map old to new variable names?

6. More???

### Details
Some additional details for this issue (if relevant):
 - Followup to #7621 (final part of #5941)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by dareumnam** [comment]
I am wondering if someone already started working on this issue. If not, I would like to take a look at this.

**Comment by mjwitte** [comment]
@dareumnam I have not done anything on this yet. It should wait until #7621 is complete. And, because this will cause significant output changes, it must wait until after v9.3 release.

**Comment by dareumnam** [comment]
@mjwitte Thank you for letting me know. Then I'll wait until after v9.3 release & #7621 is done.

**Comment by jasondegraw** [comment]
A couple of related terminology resources are:

  * Building Energy Data Exchange Specification, [bedes.lbl.gov](https://bedes.lbl.gov)
  * BuildingSynch, [buildingsync.net](https://buildingsync.net) and [github.com/BuildingSync/schema](https://github.com/BuildingSync/schema)

There's some overlap and circular references, but between the two a lot of terminology is covered.

Here's a list of resource types:
https://bedes.lbl.gov/bedes-online/input-resource-type

**Comment by mjwitte** [comment]
@shorowit In [this comment](https://github.com/NREL/EnergyPlus/pull/8134#issuecomment-656907855) you said:

>  I am more annoyed by the inconsistencies between fuel names for input objects and fuel names for output objects (see FuelOil issue here, NaturalGas vs Gas, Electricity vs Electric, Rate vs Power).

Please elaborate. It's relevant here and to #8134.

**Comment by shorowit** [comment]
It looks like this ticket already covers my concerns -- primarily that some input/output fuel names are different, and secondarily that Electricity specifically uses a different term (Power) compared to all other fuels (Rate).

That said, am I seeing that the proposal here is to change output variable names to include spaces (e.g., "Natural Gas" instead of "NaturalGas") but meters and inputs would not have spaces? I would strongly prefer the _exact_ same fuel names used across all inputs/outputs. (I'd probably just stick with PascalCase myself to minimize changes for developers.)

**Comment by mjwitte** [comment]
@shorowit For output variable names, I think I agree that we should use the input string, e.g. "Boiler NaturalGas Energy". 

What's your preference on table output headers? Spaces or not? The table outputs currently use spaced names everywhere (or nearly so?). Here's a current ABPUS report:
![image](https://user-images.githubusercontent.com/4991075/88306482-67811c80-ccd0-11ea-88b8-2dfa5d613ba6.png)

Whatever we do will be highly disruptive, because "Gas" and "Electric" are used all over the place, and they'll change to "NaturalGas" (output variables and meter names will change) and "Electricity" (output variables only, meters are already Electricity).

**Comment by shorowit** [comment]
I would prefer no spaces there either to make it easier to query outputs from, e.g., the SQL output.

**Comment by mjwitte** [comment]
I'll put this out on Slack to see if we have any consensus. 
(Just thinking out loud here, if we do change table headers, that should be a separate PR so we can manage evaluating diffs. )

**Comment by dareumnam** [comment]
@mjwitte Thank you for the update. I just return to work from my leave. I'll try to wrap this up asap.
