### ISSUE TITLE
App signing of programs for converting older pre-v7.2.0 IDF files to current versions

### ISSUE THREAD

**Issue by samuelduchesne** [NREL/EnergyPlus#7631]
Issue overview
--------------
With MacOs Catalina's new mandatory app signing/notarization ([Gatekeeper](https://developer.apple.com/developer-id/)), the [Programs for converting older pre-v7.2.0 IDF files to current (or intermediate) versions](http://energyplus.helpserve.com/Knowledgebase/Article/View/98) cannot be opened because they are not signed (see image below). 

<img width="532" alt="Screen Shot 2019-11-21 at 12 15 33 PM" src="https://user-images.githubusercontent.com/22966009/69360526-bc0f5c00-0c58-11ea-8b20-a8d80737ec14.png">

### Details
 - Platform (MacOs Catalina 10.15.1 (19B88))
 - Version of EnergyPlus (all versions)

**Comment by samuelduchesne** [comment]
In the meantime, the transition programs can be removed from the quarantine (similarly to [this](https://github.com/tuxu/ipynb-quicklook/issues/6#issuecomment-562185140)).

The idea is to remove the transition programs from the quarantine. This can be done in one go with `xattr -d com.apple.quarantine [files ...]`. A quick way is to drag and drop the transition programs (unix executables) after the command in the Terminal:

```
xattr -d com.apple.quarantine [drag and drop the list of Transition files here V1-0-0-to-V7-1-0]
```

**Comment by mitchute** [comment]
I'm pretty sure this isn't going to get fixed. You've provided a good workaround for anyone that may encounter this issue in the future. Closing.
