### ISSUE TITLE
Remove a wrong error message using PerformancePrecisionTradeoffs

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#7640]
Issue overview
--------------
@shorowit found a wrong error message when the PerformancePrecisionTradeoffs object is used:

   ** Warning ** The following lines are "Unused Objects".  These objects are in the input
   **   ~~~   **  file but are never obtained by the simulation and therefore are NOT used.
   **   ~~~   **  Only the first unused named object of an object class is shown.  Use Output:Diagnostics,DisplayAllWarnings; to see all.
   **   ~~~   **  See InputOutputReference document for more details.
   ************* Object=PerformancePrecisionTradeoffs=PerformancePrecisionTradeoffs 1

The message should be removed.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@lgu1234 Are you planning on fixing this or is this open for anyone to pick up?

**Comment by lgu1234** [comment]
@RKStrand Yes. I am almost done, except for a unit test. Thanks.

**Comment by RKStrand** [comment]
@lgu1234 Awesome--thanks!

**Comment by lgu1234** [comment]
Closed via #7724
