### ISSUE TITLE
PerformancePrecisionTradeoffs should produce eio output to indicate which options are active

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7646]
Issue overview
--------------
PerformancePrecisionTradeoffs options should be echoed to the eio output, similar to other global options such as ShadowCalculation and HeatBalanceAlgorithm.

PerformancePrecisionTradeoffs should probably also throw one warning if any non-default options are selected.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
Related to: https://github.com/energy-plus/EnergyPlus/blob/PerfOverrideAndReporting/design/FY2020/NFP-PerformanceOverRidesAndReporting.md

**Comment by JasonGlazer** [comment]
@lgu1234 have you started working on this?

**Comment by lgu1234** [comment]
@JasonGlazer I am going to work on it.
