### ISSUE TITLE
unable to log in energyplus public website

### ISSUE THREAD

**Issue by hopezh** [NREL/EnergyPlus#7676]
Issue overview
--------------
I was **unable to log in EnergyPlus public website** after I created a new user account.

It still didn't work even after I "**requested a new password**". 

It always remind me that "Sorry, unrecognized username or password".

May I ask if anyone has experienced similar issue before, and if yes, how to solve it?

**Comment by Myoldmopar** [comment]
I'm sorry this has happened, I will see what I can find out.

**Comment by Myoldmopar** [comment]
@hopezh we have someone working on it.  If this issue gets addressed, please close it, otherwise if you don't have it resolved soon please comment on here so we can continue to work on it.

**Comment by hopezh** [comment]
Noted with thanks, @Myoldmopar
