### ISSUE TITLE
Electric Chiller Forgets to Update Sometimes

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#7680]
Issue overview
--------------
Possible related or duplicates:
 - #7134 
 - #6404

While refactoring the electric chiller for PlantComponent in #7637, a bunch of time was ~~spent~~ wasted debugging stray diffs in CompSetPtControl.idf.  As it turns out, even in develop that chiller model is misbehaving.  Primarily due to forgetting to update a number of what used to be module-level shared variables.  Overall, now that the chiller is refactored and cleaned up, someone needs to take a full pass to clean up all return paths to ensure variables are initialized/cleared wherever needed.  This will indeed cause diffs, so this needs to be done in a dedicated branch, not in conjunction with larger work.

This can be seen by just looking at the CompSetPtControl.idf outputs, especially how the condenser flow and delta T do not agree for some timesteps.

(FYI @mjwitte @mitchute)

**Comment by rraustad** [comment]
I'm not positive on this but I think when Chiller:Electric:EIR was developed it was a mimic of Chiller:Electric. So this same symptom should be looked for in EIR chiller example files.

**Comment by mitchute** [comment]
@myoldmopar I'm leaving one module-level variable on the reformulated EIR chiller refactor to be addressed here. See #7683. This looks to be related.
