### ISSUE TITLE
VRF does not show rated COP when using unity performance curves

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7682]
Issue overview
--------------
User questions COP results when performance curves are changed to equal 1. See UnMetHours post https://unmethours.com/question/42281/vrf-with-constant-curves-has-cop-10/?answer=42284#post-id-42284

Results show varying COP while it seems COP should be constant with these inputs.

And with unity part load fraction correlation curves the PLR and RTF should be equal. Maybe the issue with PLR != RTF is the min PLR input. Below min PLR there is a cycling ratio that is used to calculate RTF and above min PLR the VRF system runs the entire time step where PLR = 1 and RTF should also = 1. Something looks strange with PLR and RTF.

![VRF_COP](https://user-images.githubusercontent.com/5778156/72471805-58fdf980-37b1-11ea-905a-19e607d89168.JPG)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added [here](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/7000s/7682/DOAToVRF_ConstantCurves.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Updating performance curves as specified in the UH post shows a constant COP. Still looking to see if there are any other changes required. Defect file also updated.

![VRFCOP_New2](https://user-images.githubusercontent.com/5778156/72843358-5cd5c400-3c68-11ea-98fb-768b61cae685.JPG)

**Comment by KWSL** [comment]
I just discovered this as well.  Thought I was taking crazy pills when I saw that the COP's were dropping at low PLR.  I'm attaching a modified example file that sets all curves for the AirConditioner:VariableRefrigerantFlow equal to 1.  What I discovered is that the COP calculated by the program equals the rated COP * PLR, so at low PLR's, the COP is very low.  (see columns EC & ED in the attached excel file).

A temporary work-around is to set the minimum PLR equal to 1.0 so the PLR calculation doesn't effect the results...

[DOASDXCOIL_wADPBFMethod_ConstCurves.zip](https://github.com/NREL/EnergyPlus/files/4094636/DOASDXCOIL_wADPBFMethod_ConstCurves.zip)

**Comment by KWSL** [comment]
the defect file link isn't working for me

**Comment by KWSL** [comment]
Looks like the following needs to be changed in "HVACVariableRefrigerantFlow.cc":

Line 1153:
`VRF(VRFCond).ElecCoolingPower =
                (VRF(VRFCond).RatedCoolingPower * TotCoolCapTempModFac) * TotCoolEIRTempModFac * EIRFPLRModFac * HREIRAdjustment * VRFRTF*CoolingPLR;`

& Line 1171:

`            VRF(VRFCond).ElecHeatingPower = (VRF(VRFCond).RatedHeatingPower * TotHeatCapTempModFac) * TotHeatEIRTempModFac * EIRFPLRModFac *
                                            HREIRAdjustment * VRFRTF * InputPowerMultiplier*HeatingPLR;`

**Comment by rraustad** [comment]
@kwsl see my discussion and results in the UH post.

**Comment by KWSL** [comment]
@rraustad - so is it an issue with the curves or an issue with the source code?  The Engineering Reference documentation has the EIRPLR equation as (16.489):

EIRFPLR = a + b (PLR)+ c (PLR)^2 + d (PLR)^3

& the curves in the example file also result in very low COPs at low PLRs

**Comment by rraustad** [comment]
If setting the curves to 1 (those that are appropriate) give the rated COP then I have to think that the model is working as expected. If you plot the EIRfPLR curve then you should see a near 45 degree line, which is how the power would change as PLR changes. So as of yet I haven't seen anything that makes me think the VRF model is broken. When using the provided EnergyPlus curves, and setting the weather outdoor T and Twb to rated cooling/heating conditions, then is the COP reasonable (I didn't try this)?

**Comment by rraustad** [comment]
I still have to check the report variables used for capacity and power to see if those match with the reported COP.

**Comment by KWSL** [comment]
@rraustad - in the example file "DOASDXCOIL_wADPBFMethod.idf" the PLR curves do change somewhat linearly with PLR (@ PLR = 0.5, EIRPLR = 0.59).  However, the minimum PLR input for this curve is 0.5, and the minimum part-load ratio in the AirConditioner:VariableRefrigerantFlow is 0.25, so when the VRF unit is operating at a PLR below 0.5, there is no energy reduction below that point.

**Comment by rraustad** [comment]
I would agree that seems wrong and would cause low COP at low PLRs.

**Comment by KWSL** [comment]
seems like how the PLR would be integrated into the model was not well thought-out & not documented particularly well.

**Comment by rraustad** [comment]
I'm still trying to see if any model calculations looks suspect.

**Comment by KWSL** [comment]
yep, this makes sense - min PLR in the unit needs to match min PLR in the curve & then I think things are right, my corrections are not.  I misunderstood the EIRPLR curve

**Comment by rraustad** [comment]
I agree that those 2 inputs should match, or at least min PLR input in the EIRfPLR curve should be <= min PLR in the VRF object.

**Comment by KWSL** [comment]
It would be useful to throw an error if that's not the case.  Or remove the minimum PLR field from the AirConditioner:VariableRefrigerantFlow object & just use the curve minimum.

**Comment by rraustad** [comment]
I agree with the error idea, it would help users get correct answers. I ran one of the VRF example files and compared the reported COP with hand calculated values (reported cooling and heating capacity / cooling and heating power from 2nd figure). They match and also appear reasonable. VRF condenser PLR and RTF are included.

![image](https://user-images.githubusercontent.com/5778156/72916580-497e3380-3d10-11ea-99d2-efeb8759fabd.png)

**Comment by rraustad** [comment]
Wait, look at time 890 on the graph above, the yellow dotted and green solid lines do not match.

**Comment by KWSL** [comment]
in that file, there is no minimum curve output for the EIRPLR curves & the minimum value of X is 0.  Can you plot the PLR and run-time fractions on the graph as well?  & how are you doing the hand calculations for the COP?

Do you know the source data for this VRV?  the VRV can go down to 0.25 PLR, did the source data go that low?

**Comment by rraustad** [comment]
Updated figure above. VRF data was from Mitsubishi manufacturers data and created as described in [this report](http://publications.energyresearch.ucf.edu/wp-content/uploads/2018/06/FSEC-CR-1910-12.pdf).

! Variable Refrigerant Flow (VRF) Heat Pump
! Mitsubishi PURY-P108TGMU
! Nominal Cooling Capacity = 31.7 kW
! Nominal Cooling Power Input = 9.63 (Cooling COP = 3.2917)
! Nominal Heating Capacity = 35.2 kW
! Nominal Power Input = 9.92 kW (Heating COP = 3.5484)
! Note: Capacity performance curves are normalized to capacity at 16C indoor wet-bulb temperature
!       For this reason, the similation will report that capacity as a function of temperature curves are not 1 at the rating point

**Comment by rraustad** [comment]
I added a warning for the min value of x issue in the DOASDXCOIL_wADPBFMethod.idf example file.

    ** Warning ** GetVRFInput: AirConditioner:VariableRefrigerantFlow="VRF HEAT PUMP", invalid
    **   ~~~   ** ...Cooling Energy Input Ratio Modifier Function of Low Part-Load Ratio Curve Name = COOLINGEIRLOWPLR has out of range value.
    **   ~~~   ** ...Curve minimum value of X = 0.500 must be <= Minimum Heat Pump Part-Load Ratio = 0.250.
    ** Warning ** GetVRFInput: AirConditioner:VariableRefrigerantFlow="VRF HEAT PUMP", invalid
    **   ~~~   ** ...Heating Energy Input Ratio Modifier Function of Low Part-Load Ratio Curve Name = HEATINGEIRLOWPLR has out of range value.
    **   ~~~   ** ...Curve minimum value of X = 0.500 must be <= Minimum Heat Pump Part-Load Ratio = 0.250.
    **  Fatal  ** GetVRFInput: Errors found in getting AirConditioner:VariableRefrigerantFlow system input. Preceding condition(s) causes termination.

**Comment by rraustad** [comment]
Defrost Electric Power was the reason for the difference at x = 890 in the plot above. When that is included in the hand calculation the values match.

![image](https://user-images.githubusercontent.com/5778156/72923440-12fae580-3d1d-11ea-851b-da8f8b6bfecf.png)

**Comment by KWSL** [comment]
great!  That's super helpful.  Documentation for the min PLR field could be updated too.

So many curves for these it's tough to keep them all straight.  Is it possible to also create an output variable for the combination ratio?

**Comment by KWSL** [comment]
@rraustad - I found another issue that should require an error - with a water-source VRV, if the if the "Heating Performance Curve Outdoor Temperature Type" is Wetbulb, then the wetbulb calculation is used inlet temperature calculations.  Somehow ,the actual source water temperature is reported.

Seems like if the two "else if" statements on lines 577 and 571 were switched, the issue would go away.

**Comment by KWSL** [comment]
> Defrost Electric Power was the reason for the difference at x = 890 in the plot above. When that is included in the hand calculation the values match.
> 
> ![image](https://user-images.githubusercontent.com/5778156/72923440-12fae580-3d1d-11ea-851b-da8f8b6bfecf.png)

perfect it makes sense now & is coming together.

**Comment by rraustad** [comment]
I thought we had a check in there for not allowing WetBulbTemperature indicating type for water-cooled. Either way this also needs fixing.

**Comment by KWSL** [comment]
Thanks!!
