### ISSUE TITLE
Condenser plant load dispatch not working for two-speed evaporative fluid cooler tower

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#7688]
Issue overview
--------------
From user file and code inspection, the two speed evap fluid cooling tower model is not reporting back its max and optimum capacity for use in condenser load dispatch calculations.  

The problems are here
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeFluidCoolers.cc#L982
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeFluidCoolers.cc#L983

the code should be the same as for single speed fluid cooler, e.g.
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EvaporativeFluidCoolers.cc#L974

If getDesignCapacities returns zero for MaxLoad and OptLoad the load based operation schemes will not work

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@EnergyArchmage I've taken a look at this in the code and I think I understand what is needed here.  However, I don't want to fix something that someone else is already working to correct.  Are you working on this (now or in the future) or is anyone else that you know of working/planning to work on this?

**Comment by EnergyArchmage** [comment]
Hi @RKStrand, I am not working on it and don't know of anyone else.  I figured my changes would conflict with plant refactor.  It is a simple fix.

**Comment by RKStrand** [comment]
Thanks, @EnergyArchmage, I will go ahead and assign it to myself and take care of it.
