### ISSUE TITLE
Construction:AirBoundary solar not working correctly for all cases

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7725]
Issue overview
--------------
 - [x] Construction:AirBoundary "Solar and Daylighting Method" = GroupedZones works as expected with Solar Distribution = Full Exterior, but not with FullInteriorAndExterior. User comments:

> Using either FullExterior or InteriorAndExterior, the sum of Surface Inside Face Solar Radiation Heat Gain Rate plus Surface Window Shortwave from Zone Back Out Window Heat Transfer Rate is nearly equal to Zone Windows Total Transmitted Solar Radiation Rate. For both solar distribution methods, the former is always ~1-2% smaller than the later. Why?
> Using FullExterior all floors in a solar enclosure receive Surface Inside Face Beam Solar Radiation Heat Gain Rate, and no other surfaces receive beam solar. Surface Inside Face Solar Radiation Heat Gain Rate per Area is equal for all floor surfaces, confirming that beam solar is distributed equally across all floor surfaces.
Using InteriorAndExterior Surface Inside Face Beam Solar Radiation Heat Gain Rate reports reasonable values for appropriate surfaces in exterior zones, but no surfaces in the interior zones receive beam solar.

 - [x] Construction:AirBoundary "Solar and Daylighting Method" = InteriorWindow does not work. It was disabled for the 9.2 release.

*3. With plain old interior windows, there are significant non-zero values of Surface Inside Face Solar Radiation Heat Gain Energy at night when they should all be zero. (This is not related to the airwall work, see #7865.)*

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 9.2.0
 - Unmethours [41171](https://unmethours.com/question/41171/constructionairboundary-solar-enclosures-for-grouped-zones-solar-distribution/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached here:

[7725-AirWall-BeamSolar.zip](https://github.com/NREL/EnergyPlus/files/4357865/7725-AirWall-BeamSolar.zip) - this shows the beam solar working in the interior zones with FullExteriorAndInterior:

  7725-FullExt-5ZoneAirCooled_AirBoundaries_Daylighting - beam solar only on the floor surfaces (see column HI F5-1:Surface Inside Face Beam Solar Radiation Heat Gain Rate [W](Hourly))

  7725-FullIntExt-5ZoneAirCooled_AirBoundaries_Daylighting - beam solar showing in the interior zones (see columns GY, HD, and HI for example)
  7725-FullIntExt-5ZoneAirCooled_CombineZones_Daylighting - this is the same file with the zones actually merged (no air boundaries) - and, after the fix, wait for it . . . .
  All of the Surface Inside Face Solar Radiation Heat Gain Energy and Surface Inside Face Beam Solar Radiation Heat Gain Rate variables are the *same* as the file above using air boundaries!

[7725-AirBoundaryInteriorWindow.zip](https://github.com/NREL/EnergyPlus/files/4357891/7725-AirBoundaryInteriorWindow.zip)

5ZoneAirCooled_AirBoundaries_Daylighting-IntWindow
5ZoneAirCooled_Daylighting-ActualIntWindow - uses actual walls with interior windows instead of air boundary InteriorWindow
After fix:
  SPACE5-1 DAYLIGHTING CONTROL:Daylighting Reference Point 1 Illuminance - values are similar between the two files. They are not identical, because the properties of the implied window from the InteriorWindow option are perfectly transmitting, which can't be reproduced with an explicit window.
  F5-1:Surface Inside Face Solar Radiation Heat Gain Energy is similar in both files when the sun is shining. The file with the actual interior window shows values at night (issue #7865 which isn't fixed yet).
  
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mjwitte Reading through this defect, it looks like item 3 in the description is something different.  Has this been broken out into a separate defect yet?  Also, what is being requested for item 2 above--correction of documentation or reimplementation of what was disabled?

**Comment by mjwitte** [comment]
@RKStrand Items 1 and 2 are my work to finish up from the original development. Item 3 I noticed while trying to fix item 2. So, I just noted it here, and haven't circled back to test some other files and post a new defect.

**Comment by RKStrand** [comment]
@mjwitte No problem.  If you don't want to work on the new defect that contains item 3, let me know when you establish that new defect and I could potentially work on it.  If you would rather work on that yourself, don't bother telling me and I'll assume that you took care of it.  Thanks!
