### ISSUE TITLE
Refactor VRF static timing variables

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7729]
Issue overview
--------------
The VRF models have several troublesome static local variables in `InitVRF`,  `CalcVRFCondenser` and `CalcVRFCondenser_FluidTCtrl` which can cause problems with serial unit tests.  Seems they should either be part of the component structs or should be module level variables. Also, at first glance, if there's more than one VRF condenser these variables will be wrong, because `CurrentEndTimeLast` will get updated for the first component and then it will be wrong for the next component? Also, some of these variables are beings stored in ...HRTimer and ...HRTime.

Suggest refactoring the VRF models to use a different approach to track timing for control decisions that does not rely on local statics.

### Details
Some additional details for this issue (if relevant):
 - This came to light due to a serial unit test failure introduce in #7723 which was fixed with a kludge in #7726.
 - Version of EnergyPlus 9.3.0'ish

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
CurrentEndTime and CurrentEndTimeLast are only used to determine the progression of time and when down-shifting of the HVAC time step occurs. These variables are the same for all VRF systems (i.e., this time step has a time and last time step has a time). Yes these should probably be moved to the module level for unit testing. And if there is a better way to track time then that is preferred. Regarding the location of CurrentEndTime and CurrentEndTimeLast in the CalcVRFCondenser function, these variables should be moved up and down, respectively, outside the IF block where currently set. Also, TimeStepSysLast is not used in this function.

i.e, outside (above and below) this IF block

    if (!DoingSizing && !WarmupFlag) {
        // lots of code //
        // calculate end time of current time step to determine if max capacity reset is required
        CurrentEndTime = double((DayOfSim - 1) * 24) + CurrentTime - TimeStepZone + DataHVACGlobals::SysTimeElapsed;
        // more code //
        TimeStepSysLast = DataHVACGlobals::TimeStepSys; <- not used in this function
        CurrentEndTimeLast = CurrentEndTime;
        // more code //
    }
