### ISSUE TITLE
Water to Water Heat Pump output variable name conflict

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7733]
Issue overview
--------------
In v9.2, all of the HeatPump:WaterToWater:* objects had output variables which began with "Water to Water Heat Pump . . . ".

In #7489, HeatPump:WaterToWater:EIR:Cooling became HeatPump:PlantLoop:EIR:Cooling and was extended to include an air-source option, so it's output variables were all changed to "~Water to Water~ Heat Pump . . . ". The transition Report Variables 9-2-0 to 9-3-0.csv implements this change.

But HeatPump:WaterToWater:ParameterEstimation:* and HeatPump:WaterToWater:EquationFit:* still use the old output variable names, but transition doesn't know the difference so it will change the names and break idf files which have these heat pumps in them. 

The simplest solution is probably to update the names for HeatPump:WaterToWater:ParameterEstimation:* and HeatPump:WaterToWater:EquationFit:* to drop "Water to Water . . .".

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus 9.3.0 (after merge of #7730).

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added the v9.2 PlateHeatExchanger.idf example file can be used as a test file.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
> "... HeatPump:WaterToWater:ParameterEstimation:* and HeatPump:WaterToWater:EquationFit:* still use the old output variable names..."

Of course they do... I'll submit another PR to fix this up.

**Comment by mitchute** [comment]
Closed by #7734
