### ISSUE TITLE
Parametric Spreadsheet References Present in Docs but not in Repo or Install

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#7739]
Issue #7026 notes several ParametricSpreadsheet references in the docs, however, these spreadsheets are not present in the repo, which means that they also don't get shipped in the installer. We need to decide whether to find (and update) and include the spreadsheets or delete the documentation and associated references.

See also #5423

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
closed by #7026
