### ISSUE TITLE
Output:Diagnostics should be \unique-object and \extensible

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#7742]
Issue overview
--------------

https://github.com/NREL/EnergyPlus/blob/ce80ec5008dab9fe404249011757b97e115f7733/idd/Energy+.idd.in#L107565-L107594

Proposed IDD, similar to Output:Table:SummaryReports

```
Output:Diagnostics,
    \extensible:1
    \memo Special keys to produce certain warning messages or effect certain simulation characteristics.
    \unique-object
  A1 ; \field Key 1
       \begin-extensible
       \type choice
       \key DisplayAllWarnings
       \key DisplayExtraWarnings
       \key DisplayUnusedSchedules
       \key DisplayUnusedObjects
       \key DisplayAdvancedReportVariables
       \key DisplayZoneAirHeatBalanceOffBalance
       \key DoNotMirrorDetachedShading
       \key DoNotMirrorAttachedShading
       \key DisplayWeatherMissingDataWarnings
       \key ReportDuringWarmup
       \key ReportDetailedWarmupConvergence
       \key ReportDuringHVACSizingSimulation
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
How about extensible, but not \unique-object ?

**Comment by jmarrec** [comment]
My opinion is that if we make a change, might as well go ahead and make it `\unique-object` like `Output:JSON`, `Output:SQLite`, `Output:Table:SummaryReports`, etc.

**Comment by mjwitte** [comment]
Whichever. Change to \unique-object will require a transition rule. (either way, it's too late for v9.3 now).
