### ISSUE TITLE
ZoneHVAC:HybridUnitaryHVAC is not metering its water use

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#7754]
Issue overview
--------------
ZoneHVAC:HybridUnitaryHVAC is not metering its water use.  The output variable for the water consumption is [here](https://github.com/NREL/EnergyPlus/blob/b1c11ff5a75e8e34a6e667b25b8d350f4f1cddae/src/EnergyPlus/HybridUnitaryAirConditioners.cc#L1043).  The water consumption is an important aspect of this system.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
See related issue #7520

**Comment by matthew-larson** [comment]
Closed via #7827.
