### ISSUE TITLE
EnergyPlus not catching improper AirFlowNetwork Linkages, Duplicate Ducts, Duplicate Nodes, Etc

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7756]
Issue overview
--------------
In the AirflowNetwork_Attic_Duct.idf example file, the AirFlowNetwork is very poorly formed. Some of the flaws are detailed in the UnmetHours post, such as Duct objects used more than once. The IDF simulates flawlessly, which it should definitely not.

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus 9.2
 - https://unmethours.com/question/42733/example-airflownetwork-drawing-for-idf/

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] C:\EnergyPlusV9-2-0\ExampleFiles\AirflowNetwork_Attic_Duct.idf
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jasondegraw** [comment]
@mldichter As I pointed out on UnmetHours, there are some forms of reuse that are OK. Reuse of ducts should be OK as long as it makes modeling sense. Other potential problems, like node duplication, are potentially more of an issue and should get fixed. With those two things in mind, could you list out the things you're seeing? If you'd prefer an offline conversation, we can probably arrange that as well if it would help.

**Comment by mldichter** [comment]
@jasondegraw Could you update the documentation instead of an offline conversation? I pointed out a discrepancy in #7451 between the IO Ref and the IDD file, but the documentation could use a once over. For instance, your comment in the UnmetHours post,

> The duplication of nodes isn't great, but that doesn't mean the network isn't legit. Basically if the solver works, the network is legit (it won't work otherwise). In this case it may actually even match the modeling intent (yes, perhaps by accident). Most of the AFN "airflow element" objects (like ducts, cracks, etc.) are reusable, so reuse is acceptable.

It's not in the IO Ref as far as I can tell. I assumed that nodes and ducts had to be unique, but I have no intuition for how to correctly use duplicate nodes for desired simulation behavior.

**Comment by jasondegraw** [comment]
@mldichter Please don't take quotes like that out of context. It's muddling things together when what we need here is a concrete information for an assignee to work from. #7451 already has someone assigned and is being worked on. I'm sure he'll address your items when he can, so I'd call that "in progress". I don't necessarily agree that the documentation is lacking on this, but feel free to add that over there.

As I've indicated, the duplication of nodes is not ideal. I personally can't think of an application for doing it, but that alone doesn't mean that the network is poorly formed. It just makes it more complicated than necessary. I think that it should be fixed, but as of right now if someone is assigned to this issue it is not clear what your request is. I can edit the issue to help, but I'd prefer not to do that.

**Comment by mldichter** [comment]
@jasondegraw I agree the duplication of nodes is not ideal, but that's not my greatest concern. Let's say that a non EnergyPlus developer is trying to understand what the AFN in the AirflowNetwork_Attic_Duct.idf example is modeling, More specifically, trying to understand the physical significance of multiple AFN nodes referring to the same AirLoop node.

What document and page number should the non EnergyPlus developer read? I don't think that documentation exists.

**Comment by jasondegraw** [comment]
@mldichter At this point, I think the best thing to do is to close this issue. I'll open a separate issue on the node duplication issue. Please submit documentation items to the current pre-existing issues or as a new feature request for additional documentation.

**Comment by mldichter** [comment]
@jasondegraw You've essentially brushed this problem under the rug. The issue you opened, #7762, implies the example files are working but might be more complicated than necessary. It doesn't address lack of documentation, and your statement of zero errors implies a correct simulation when multiple AFN nodes reference the same AirLoop node is not sound.

I'll be going through the IO Ref to find inconsistencies with the IDD and pointing out any lack of explanation to understand the example files.

**Comment by mjwitte** [comment]
@mldichter EnergyPlus is open source. Feel free to contribute documentation changes. The EnergyPlus contribution policy may be found [here](https://energyplus.net/contributing).

**Comment by mldichter** [comment]
@mjwitte Some of the documentation I can update, It's a bunch of LaTeX, so not too bad. However, there's a few things missing in the documentation of the AirflowNetwork objects that just doesn't exist. In this thread for instance, What is the physical significance of multiple AFN nodes referring to the same AirLoop node? I have no idea, but it must represent physical connection of ducts since the AFN runs and gives reasonable results. Other than digging into the EnergyPlus code, how can I answer that question? And if no one knows, that perfectly fine. I know EnergyPlus is a very large and complicated piece of software. I'd just like to know if I'm not asking the right person, or not asking the right question, or if I really do need to start digging into the code.

**Comment by mjwitte** [comment]
Contribute what you can.
