### ISSUE TITLE
Evaluate Yahoo! Users Group on Website

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#7759]
From the Yahoo! users group website:

> Attention: Starting December 14, 2019 Yahoo Groups will no longer host user created content on its sites. New content can no longer be uploaded after October 28, 2019. Sending/Receiving email functionality is not going away, you can continue to communicate via any email client with your group members.

Evaluate usage and remove from the website as needed.

**Comment by shorowit** [comment]
Yahoo Groups officially shut down on December 15.
