### ISSUE TITLE
Documentation Issues - 2020a

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#7760]
Issue overview
--------------
A collection of small documentation issues. See checkboxed comments below.

**Comment by mitchute** [comment]
Moved from #7026 

- [ ] The organization of groups in the IOref does not always match the arrangement in the IDD! - *Probably won't fix, ever. MJW*
- [ ] The IDD group Natural Ventilation and Duct Leakage is shown in the IOref as AirflowNetwork - *Will do the opposite at some point, rename the IDD group. MJW*
- [x] The IDD has Water Heaters and Thermal Storage group that includes thermal storage objects but they are described in the IOref under Plant Equipment
- [x] The IDD has Zone HVAC Air Loop Terminal Units group but in the IOref it is called Air Distribution Equipment
- [x] The IDD has one group called Humdifiers and Dehumidifiers but the IOref has two separate groups called Humidifiers and another called Desiccant Dehumidifiers

**Comment by jasondegraw** [comment]
- [x] @mitchute I'd personally prefer that the IDD group "Natural Ventilation and Duct Leakage" be changed to "AirflowNetwork" rather than the other way around. Also, are IDD groups going to be around in the epJSON future?

2021.06.09 (RKS) This seems to be taken care of already.

**Comment by mitchute** [comment]
- [x] Minor typo [here](https://github.com/NREL/EnergyPlus/blob/ca68d4566b28f69da0aa1ee90933d034a8e0fe0d/doc/engineering-reference/src/climate-sky-and-solar-shading-calculations/climate-calculations.tex#L47).

![Screen Shot 2020-03-02 at 11 22 41 AM](https://user-images.githubusercontent.com/2985979/75705217-2e400580-5c78-11ea-8225-a02b89e144ca.png)

```Wh/m2``` should be ```W/m2```.

**Comment by mitchute** [comment]
- [x] I/O Ref. in ```CentralHeatPumpSystem```. Field: Control Method should be taken out of the ```\paragraph{}``` See source [here](https://github.com/NREL/EnergyPlus/blob/415a34b98116cbefa62e3c88a93c2a3c12c59515/doc/input-output-reference/src/overview/group-plant-equipment.tex#L5637).

![Screen Shot 2020-03-03 at 3 58 07 PM](https://user-images.githubusercontent.com/2985979/75827891-d4b70400-5d67-11ea-9379-6dafe9435798.png)

**Comment by mitchute** [comment]
- [x] minor typo in units. [See here](https://github.com/NREL/EnergyPlus/blob/3eccb7f17bf19358ba2603d424beb877e25e5a4f/doc/input-output-reference/src/overview/group-electric-load-center-generator.tex#L4373)

<img width="497" alt="Screen Shot 2020-03-05 at 9 21 55 AM" src="https://user-images.githubusercontent.com/2985979/76002010-3475f200-5ec3-11ea-894f-35fe3fbb9577.png">

**Comment by mldichter** [comment]
- [x] The documentation for the Coil:Cooling:WaterToAirHeatPump:EquationFit in the 9.2 IO Ref is lacking for the performance coefficient fields. Looks like the Engineering Reference has an explanation of the Total Cooling Capacity Coefficients and Sensible Cooling Capacity Coefficients, but not the Cooling Power Consumption Coefficients.

![Capture](https://user-images.githubusercontent.com/39242689/76444946-e9a42080-6381-11ea-89d3-e35de22a7c0c.PNG)

The documentation for the Coil:Heating:WaterToAirHeatPump:EquationFit is similarly lacking in the IO Ref, but the Engineering reference discusses neither the Heating Capacity Coefficients nor Heating Power Consumption Coefficients.

I'm pretty sure these objects are from this thesis paper at [this link](https://hvac.okstate.edu/sites/default/files/pubs/theses/MS/27-Tang_Thesis_05.pdf) around page 49. Can anyone confirm?

EDIT:
I think I found the description of the curves in this file, which can be used for updating the IO Ref.
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WaterToAirHeatPumpSimple.cc

```
Real64 const Tref(283.15); // Reference Temperature for performance curves,10C [K]
CelsiustoKelvin = 273.15

ratioTDB = ((LoadSideInletDBTemp + CelsiustoKelvin) / Tref);
ratioTWB = ((LoadSideInletWBTemp + CelsiustoKelvin) / Tref);
ratioTS = ((SourceSideInletTemp + CelsiustoKelvin) / Tref);
ratioVL = (LoadSideMassFlowRate /(AirVolFlowRateRated * PsyRhoAirFnPbTdbW(StdBaroPress, LoadSideInletDBTemp, LoadSideInletHumRat, RoutineName)));
ratioVS = (SourceSideMassFlowRate) / (SimpleWatertoAirHP(HPNum).DesignWaterMassFlowRate);

Coil:Cooling:WaterToAirHeatPump:EquationFit
TotalCapCoeff1 + (ratioTWB * TotalCapCoeff2) + (ratioTS * TotalCapCoeff3) + (ratioVL * TotalCapCoeff4) + (ratioVS * TotalCapCoeff5)
SensCapCoeff1 + (ratioTDB * SensCapCoeff2) + (ratioTWB * SensCapCoeff3) + (ratioTS * SensCapCoeff4) + (ratioVL * SensCapCoeff5) + (ratioVS * SensCapCoeff6)
CoolPowerCoeff1 + (ratioTWB * CoolPowerCoeff2) + (ratioTS * CoolPowerCoeff3) + (ratioVL * CoolPowerCoeff4) + (ratioVS * CoolPowerCoeff5)

Coil:Heating:WaterToAirHeatPump:EquationFit
HeatCapCoeff1 + (ratioTDB * HeatCapCoeff2) + (ratioTS * HeatCapCoeff3) + (ratioVL * HeatCapCoeff4) + (ratioVS * HeatCapCoeff5)
HeatPowerCoeff1 + (ratioTDB * HeatPowerCoeff2) + (ratioTS * HeatPowerCoeff3) + (ratioVL * HeatPowerCoeff4) + (ratioVS * HeatPowerCoeff5)
```

**Comment by jmythms** [comment]
> * [x]  The documentation for the Coil:Cooling:WaterToAirHeatPump:EquationFit in the 9.2 IO Ref is lacking for the performance coefficient fields. Looks like the Engineering Reference has an explanation of the Total Cooling Capacity Coefficients and Sensible Cooling Capacity Coefficients, but not the Cooling Power Consumption Coefficients.
> 
> ![Capture](https://user-images.githubusercontent.com/39242689/76444946-e9a42080-6381-11ea-89d3-e35de22a7c0c.PNG)
> 
> The documentation for the Coil:Heating:WaterToAirHeatPump:EquationFit is similarly lacking in the IO Ref, but the Engineering reference discusses neither the Heating Capacity Coefficients nor Heating Power Consumption Coefficients.
> 
> I'm pretty sure these objects are from this thesis paper at [this link](https://hvac.okstate.edu/sites/default/files/pubs/theses/MS/27-Tang_Thesis_05.pdf) around page 49. Can anyone confirm?
> 
> EDIT:
> I think I found the description of the curves in this file, which can be used for updating the IO Ref.
> https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/WaterToAirHeatPumpSimple.cc
> 
> ```
> Real64 const Tref(283.15); // Reference Temperature for performance curves,10C [K]
> CelsiustoKelvin = 273.15
> 
> ratioTDB = ((LoadSideInletDBTemp + CelsiustoKelvin) / Tref);
> ratioTWB = ((LoadSideInletWBTemp + CelsiustoKelvin) / Tref);
> ratioTS = ((SourceSideInletTemp + CelsiustoKelvin) / Tref);
> ratioVL = (LoadSideMassFlowRate /(AirVolFlowRateRated * PsyRhoAirFnPbTdbW(StdBaroPress, LoadSideInletDBTemp, LoadSideInletHumRat, RoutineName)));
> ratioVS = (SourceSideMassFlowRate) / (SimpleWatertoAirHP(HPNum).DesignWaterMassFlowRate);
> 
> Coil:Cooling:WaterToAirHeatPump:EquationFit
> TotalCapCoeff1 + (ratioTWB * TotalCapCoeff2) + (ratioTS * TotalCapCoeff3) + (ratioVL * TotalCapCoeff4) + (ratioVS * TotalCapCoeff5)
> SensCapCoeff1 + (ratioTDB * SensCapCoeff2) + (ratioTWB * SensCapCoeff3) + (ratioTS * SensCapCoeff4) + (ratioVL * SensCapCoeff5) + (ratioVS * SensCapCoeff6)
> CoolPowerCoeff1 + (ratioTWB * CoolPowerCoeff2) + (ratioTS * CoolPowerCoeff3) + (ratioVL * CoolPowerCoeff4) + (ratioVS * CoolPowerCoeff5)
> 
> Coil:Heating:WaterToAirHeatPump:EquationFit
> HeatCapCoeff1 + (ratioTDB * HeatCapCoeff2) + (ratioTS * HeatCapCoeff3) + (ratioVL * HeatCapCoeff4) + (ratioVS * HeatCapCoeff5)
> HeatPowerCoeff1 + (ratioTDB * HeatPowerCoeff2) + (ratioTS * HeatPowerCoeff3) + (ratioVL * HeatPowerCoeff4) + (ratioVS * HeatPowerCoeff5)
> ```

It's not very obvious, but the water-to-air heat pump cooling and heating coil equations and coefficients are explained in the engineering reference [here](https://bigladdersoftware.com/epx/docs/9-3/engineering-reference/air-system-compound-component-groups.html#single-speed-equation-fit-model). Updating the IO Reference with these references. Thanks @mjwitte
