### ISSUE TITLE
Node duplication in some of the AirflowNetwork example files

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#7762]
Issue overview
--------------
Some of the the AirflowNetwork example files have duplicate nodes: multiple AFN nodes are pointing toward the same feature/component. See, for example, AirflowNetwork_Attic_Duct.idf, where MainInletNode and FanInletNode both reference Air Loop Inlet Node. The example files still run successfully, but the networks are possibly more complex than necessary. One possible solution is to upgrade the auditing script to warn about this, but it would also work to just check all of the files to make sure that the networks represent what is intended.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (example file AirflowNetwork_Attic_Duct.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mldichter** [comment]
I discovered the difficult AirflowNetwork layout to interpret in the AirflowNetwork_Attic_Duct.idf example file which is discussed in this UnmetHours post.
https://unmethours.com/question/42733/example-airflownetwork-drawing-for-idf/

```
AirflowNetwork:Distribution:Node,
    MainInletNode,           !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    1;                       !- Node Height {m}

AirflowNetwork:Distribution:Node,
    FanInletNode,            !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    1;                       !- Node Height {m}

AirflowNetwork:Distribution:Linkage,
    SystemInletLink,         !- Name
    MainInletNode,           !- Node 1 Name
    FanInletNode,            !- Node 2 Name
    MainReturn,              !- Component Name
    Occupied Thermal Zone;   !- Thermal Zone Name
```

**Comment by mldichter** [comment]
AirflowNetwork_MultiZone_House_OvercoolDehumid.idf
"Air Loop Inlet Node" referenced twice and used on the same linkage.

```
AirflowNetwork:Distribution:Node,
    MainInletNode,           !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Node,
    CoolingInletNode,        !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Linkage,
    SystemInletLink,         !- Name
    MainInletNode,           !- Node 1 Name
    CoolingInletNode,        !- Node 2 Name
    MainReturn,              !- Component Name
    GARAGE ZONE;             !- Thermal Zone Name
```

**Comment by mldichter** [comment]
AirflowNetwork_MultiZone_House_FanModel.idf
AirflowNetwork_MultiZone_House.idf
AirflowNetwork_Simple_House.idf
AirflowNetwork_MultiZone_LocalNode.idf
AirflowNetwork_MultiZone_House_TwoSpeed.idf
"Air Loop Inlet Node" referenced twice and used on the same linkage.

```
AirflowNetwork:Distribution:Node,
    MainInletNode,           !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Node,
    FanInletNode,            !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Linkage,
    SystemInletLink,         !- Name
    MainInletNode,           !- Node 1 Name
    FanInletNode,            !- Node 2 Name
    MainReturn,              !- Component Name
    GARAGE ZONE;             !- Thermal Zone Name
```

**Comment by mldichter** [comment]
AirflowNetwork_MultiZone_House.idf
"Air Loop Inlet Node" referenced twice and used on the same linkage.

```
AirflowNetwork:Distribution:Node,
    MainInletNode,           !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Node,
    FanInletNode,            !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Linkage,
    SystemInletLink,         !- Name
    MainInletNode,           !- Node 1 Name
    FanInletNode,            !- Node 2 Name
    MainReturn,              !- Component Name
    GARAGE ZONE;             !- Thermal Zone Name
```

**Comment by mldichter** [comment]
AirflowNetwork_Simple_House.idf
"Air Loop Inlet Node" referenced twice and used on the same linkage.

```
AirflowNetwork:Distribution:Node,
    MainInletNode,           !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Node,
    FanInletNode,            !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Linkage,
    SystemInletLink,         !- Name
    MainInletNode,           !- Node 1 Name
    FanInletNode,            !- Node 2 Name
    MainReturn,              !- Component Name
    GARAGE ZONE;             !- Thermal Zone Name
```

**Comment by mldichter** [comment]
AirflowNetwork_MultiZone_LocalNode.idf
"Air Loop Inlet Node" referenced twice and used on the same linkage.

```
AirflowNetwork:Distribution:Node,
    MainInletNode,           !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Node,
    FanInletNode,            !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

AirflowNetwork:Distribution:Linkage,
    SystemInletLink,         !- Name
    MainInletNode,           !- Node 1 Name
    FanInletNode,            !- Node 2 Name
    MainReturn,              !- Component Name
    GARAGE ZONE;             !- Thermal Zone Name
```

**Comment by mldichter** [comment]
I went through all the energyplus example files with AirflowNetwork:Distribution:Node objects,

AirflowNetwork_Attic_Duct.idf
AirflowNetwork_MultiAirLoops.idf
AirflowNetwork_MultiZone_House.idf
AirflowNetwork_MultiZone_House_FanModel.idf
AirflowNetwork_MultiZone_House_OvercoolDehumid.idf
AirflowNetwork_MultiZone_House_TwoSpeed.idf
AirflowNetwork_MultiZone_LocalNode.idf
AirflowNetwork_MultiZone_SmallOffice.idf
AirflowNetwork_MultiZone_SmallOffice_CoilHXAssistedDX.idf
AirflowNetwork_MultiZone_SmallOffice_GenericContam.idf
AirflowNetwork_MultiZone_SmallOffice_HeatRecoveryHXSL.idf
AirflowNetwork_MultiZone_SmallOffice_VAV.idf
AirflowNetwork_PressureControl.idf
AirflowNetwork_Simple_House.idf
AirflowNetwork_Simple_SmallOffice.idf
EMSAirflowNetworkOpeningControlByHumidity.idf
HybridVentilationControl.idf

and the files in the previous comments had two AFN nodes referencing the same AirLoop node.

**Comment by lgu1234** [comment]
@mldichter @jasondegraw I changed an object from

AirflowNetwork:Distribution:Node,
    MainInletNode,           !- Name
    Air Loop Inlet Node,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

To:

AirflowNetwork:Distribution:Node,
    MainInletNode,           !- Name
    ,     !- Component Name or Node Name
    Other,                   !- Component Object Type or Node Type
    3.0;                     !- Node Height {m}

by removing duplicated "Air Loop Inlet Node" in the following 7 example files:

AirflowNetwork_Attic_Duct.idf
AirflowNetwork_MultiZone_House.idf
AirflowNetwork_MultiZone_House_FanModel.idf
AirflowNetwork_MultiZone_House_OvercoolDehumid.idf
AirflowNetwork_MultiZone_House_TwoSpeed.idf
AirflowNetwork_MultiZone_LocalNode.idf
AirflowNetwork_Simple_House.idf

No differences of simulation results were found. Here is my suggestion to fix this issue.

1. Set blank for the Component Name or Node Name field for MainInletNode node.
2. Revised the code to check the inputs of the Component Name or Node Name field to avoid duplication.

Please let me know what you think.

**Comment by jasondegraw** [comment]
@lgu1234 That's sort of what I had expected. The information that the pressure network is passing back to the rest of the code isn't really changing the computations that EnergyPlus does. Your plan sounds good to me.
