### ISSUE TITLE
No Initialization Summary in Tabular file

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#7790]
Issue overview
--------------
The current develop creates an EIO file when using HeatPumpProportionalControl_DCV.idf (or several other files with tabular reports that I tried) but the Initialization Summary content does not be generated. The link the table of contents is created as well as the header for the report but it has not tables. The Initialization Summary depends on reading the EIO file. 

This may be related to #7746.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
@lefticus could you take a look?

**Comment by lefticus** [comment]
@JasonGlazer It's probably related to some change I made, but can you give me a specific example of what is missing?

Which specific file is missing data?
What does this data look like?

**Comment by JasonGlazer** [comment]
Run HeatPumpProportionalControl_DCV.idf , open the HTML file, look for the Initialization Summary. For me, no table show up for that report.

**Comment by JasonGlazer** [comment]
![image](https://user-images.githubusercontent.com/2582150/74780998-4ec69380-5266-11ea-86ad-c32de63ec046.png)

**Comment by JasonGlazer** [comment]
It should look like:

![image](https://user-images.githubusercontent.com/2582150/74781057-6bfb6200-5266-11ea-9cf5-56d2cc5633ab.png)

and it goes on and on covering everything in the EIO file.

**Comment by lefticus** [comment]
OK, I'll look into it.

**Comment by lefticus** [comment]
It might be tomorrow afternoon before I get this figured out, but have confirmed that it was that last large change from me that broke things. d822fa7d7

**Comment by JasonGlazer** [comment]
I would guess the file isn't written by the time it is needed by the tabular reports or maybe it just isn't closed, something like that.

**Comment by JasonGlazer** [comment]
WriteEioTables() actually reads the EIO file to produce the tables in the initialization summary.
