### ISSUE TITLE
OPENGL_REQUIRED changes target folders in Visual Studio solution explorer

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7802]
Issue overview
--------------
On the `transition_ems_func` branch with latest develop merged in, I configured without OpenGL and the fortran projects (ExpandObjects_build, and Transition_build) are present in the solution.

Check OPENGL_REQUIRED (BUILD_FORTRAN is still checked), reconfigure, and those project are now missing from the solution.

![image](https://user-images.githubusercontent.com/4991075/75076927-f8a45b00-54c6-11ea-8e3e-2a732ad6319a.png)  ![image](https://user-images.githubusercontent.com/4991075/75076950-02c65980-54c7-11ea-88db-eb75b6933685.png)

### Details
Some additional details for this issue (if relevant):
 - Win10, VS2019 
 - Version of EnergyPlus 9.3.0-a99bd2c44e

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
And if it matters, also checked are build docs, testing, and package.

**Comment by nealkruis** [comment]
@mjwitte Looking into this today.

**Comment by ajscimone** [comment]
@mjwitte Hi Mike. I currently don't see a branch named `transition_ems_func` on the NREL Github repo. Have you pushed this branch?

**Comment by mjwitte** [comment]
@ajscimone That's been merged into develop. You should see this same problem with develop now.

**Comment by ajscimone** [comment]
@mjwitte Ah, now I understand. Got it, thank you for clarifying.

**Comment by nealkruis** [comment]
We are going to use CMAKE to explicitly define target organization in the solution explorer view.

**Comment by nealkruis** [comment]
@mjwitte I took a stab at an explicit target organization for VS solution explorer. This is all done through settings in CMake. I can move stuff around if needed. The general idea is to leave the EnergyPlus executable target at the top level and organize all the other targets into other folders.

I tried to think of all the possible targets, but there may be a few that I missed that appear with special CMake settings.

What do you think?

![Screen Shot 2020-06-01 at 12 58 54 PM](https://user-images.githubusercontent.com/1964570/83443932-d005f880-a407-11ea-9ab7-cb80df96b488.png)

**Comment by Myoldmopar** [comment]
:+1: :+1: :+1: :+1: 

And I don't even use VS.

The only thing I'd suggest is putting the energyplusapi at the top level as well, since it isn't just an internal thing.  But it doesn't affect me so others can decide whether that would be valid.

**Comment by nealkruis** [comment]
It also removes the "CTestDashboardTargets" ("Continuous", "Experimental", "Nightly", "NightlyMemoryCheck"). I don't think anyone is using those.

@Myoldmopar I can move energyplusapi back up. My only hesitancy is that outside of holding a majority of the source files for EnergyPlus, it isn't used much in the context of the development environment (e.g., debugging--since that is done through the executable target). I don't really feel strong about this, though.

It would be good to hear from others to see if they use the Solution Explorer in other ways that would be disrupted by this change.

**Comment by Myoldmopar** [comment]
@nealkruis I think energyplusapi should only contain the files needed for building out the DLL.  The energypluslib target is the one that contains the bulk of the source files, and I don't think there's any need to include that at the top level.  As we progress further down the API path, it may be more common to interact with that target.

Are you putting these changes purely in the VS side of things?  Or will this show up in Makefile based builds.  If it will affect Makefile based builds then I'll get more opinionated :laughing:.

**Comment by nealkruis** [comment]
> I think energyplusapi should only contain the files needed for building out the DLL. The energypluslib target is the one that contains the bulk of the source files, and I don't think there's any need to include that at the top level.

True.

As far as I can tell this only impacts the folder structure in VS, though maybe other IDEs use it as well? Here's the [CMake documentation](https://cmake.org/cmake/help/latest/prop_tgt/FOLDER.html#prop_tgt:FOLDER).

**Comment by jasondegraw** [comment]
90% of my interactions via the solution explorer are with the energypluslib target, so I'd vote for that one to be at the top level.

**Comment by nealkruis** [comment]
Here's an updated proposal (all collapsed):

![Screen Shot 2020-06-01 at 2 42 35 PM](https://user-images.githubusercontent.com/1964570/83452604-401b7b00-a416-11ea-86d5-b00c6e25a35f.png)

**Comment by Myoldmopar** [comment]
Looks fantastic to me!
