### ISSUE TITLE
Error with PCM hysteresis model

### ISSUE THREAD

**Issue by Fan-Feng** [NREL/EnergyPlus#7831]
Issue overview
--------------
I am using the PhaseChangeHysteresis model, while there are some problems with my result. 
I am running the example file--**1ZoneUncontrolledWithHysteresisPCM.idf.** , where the PCM is supposed to melt from 22C to 24C and to freeze from 21C to 19C.
My outputs are shown below. It could be observed that this PCM starts to melt when Node temperature goes from 18 to 19C. However, it is supposed to start melting when node temperature hits 22C. I

I am not sure if there is something wrong with EnergyPlus, or I did not use it correctly.

![image](https://user-images.githubusercontent.com/12513752/75751910-3c7c3900-5ced-11ea-9d49-f422f76b04e8.png)

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - 9.2.0

**Comment by Fan-Feng** [comment]
I found this error is ascribed to the input for object--MaterialProperties: PhaseChangeHysteresis in that Example file--*1ZoneUncontrolledWithHysteresisPCM.idf*. The following picture is the DEMO picture in EngineeringReference. Clearly, the melting temperature and freezing temperature in the first figure are 23C and 20C, respectively. However, this example takes the melting temperature as the freezing temperature as shown below, and vice versa. 
![image](https://user-images.githubusercontent.com/12513752/75752958-59b20700-5cef-11ea-96ca-c10749419602.png)
![image](https://user-images.githubusercontent.com/12513752/75753130-af86af00-5cef-11ea-83a9-eee14c41b568.png)

If my understanding is not correct, please leave a comment below. Thank you.

**Comment by jmarrec** [comment]
With 22.1.0:

```
  MaterialProperty:PhaseChangeHysteresis,
    C5 - 4 IN HW CONCRETE,   !- Name
    10000,                   !- Latent Heat during the Entire Phase Change Process {J/kg}
    1.5,                     !- Liquid State Thermal Conductivity {W/m-K}
    2200,                    !- Liquid State Density {kg/m3}
    2000,                    !- Liquid State Specific Heat {J/kg-K}
    1,                       !- High Temperature Difference of Melting Curve {deltaC}
    23,                      !- Peak Melting Temperature {C}
    1,                       !- Low Temperature Difference of Melting Curve {deltaC}
    1.8,                     !- Solid State Thermal Conductivity {W/m-K}
    2300,                    !- Solid State Density {kg/m3}
    2000,                    !- Solid State Specific Heat {J/kg-K}
    1,                       !- High Temperature Difference of Freezing Curve {deltaC}
    20,                      !- Peak Freezing Temperature {C}
    1;                       !- Low Temperature Difference of Freezing Curve {deltaC}
```

The peak freezing temperature (20°C) is below the peak melting temperatue (23°C), which makes sense.
