### ISSUE TITLE
Modify idle air flow rate for variable/multi speed coils

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7862]
Issue overview
--------------
In AirloopHVAC:UnitarySystem the idle air flow rate for variable-speed and multi-speed coils is currently autosized to the max air flow rate. The idle air flow rate represents the fan flow when the coil is off and should be changed to be less than or equal to the minimum speed air flow rate. The original implementation was for Furnaces.  See discussion in #7783.

Furnaces:

    if (Furnace(FurnaceNum).NumOfSpeedHeating > 0) {
        Furnace(FurnaceNum).IdleMassFlowRate = min(Furnace(FurnaceNum).HeatMassFlowRate(1), Furnace(FurnaceNum).CoolMassFlowRate(1));
        Furnace(FurnaceNum).IdleSpeedRatio = min(Furnace(FurnaceNum).MSHeatingSpeedRatio(1), Furnace(FurnaceNum).MSCoolingSpeedRatio(1));
        Furnace(FurnaceNum).IdleVolumeAirRate = min(Furnace(FurnaceNum).HeatVolumeFlowRate(1), Furnace(FurnaceNum).CoolVolumeFlowRate(1));
    } else {
        Furnace(FurnaceNum).IdleMassFlowRate = Furnace(FurnaceNum).CoolMassFlowRate(1);
        Furnace(FurnaceNum).IdleSpeedRatio = Furnace(FurnaceNum).MSCoolingSpeedRatio(1);
        Furnace(FurnaceNum).IdleVolumeAirRate = Furnace(FurnaceNum).CoolVolumeFlowRate(1);
    }

UnitarySystems:

    if (MSHPIndex > 0) {
        this->m_IdleVolumeAirRate = this->m_MaxCoolAirVolFlow * designSpecMSHP[MSHPIndex].noLoadAirFlowRateRatio;
    } else if (this->m_CoolVolumeFlowRate.size() == 0) {
        this->m_IdleVolumeAirRate = this->m_MaxNoCoolHeatAirVolFlow;
    }
### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added [UnitarySystem_TwoStageDXWithHumidityControl.idf](https://github.com/NREL/EnergyPlus/blob/develop/testfiles/UnitarySystem_TwoStageDXWithHumidityControl.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
Added four defect files.
