### ISSUE TITLE
Continued API/Plugin Issues

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#7877]
Issue overview
--------------
The API/Plugin work will be released with 9.3.  As such, I expect to see issues trickling in as users kick the tires on it.  I already have a starter list of tasks that persisted through the 9.3 release (from [here](https://github.com/NREL/EnergyPlus/issues/7803)) that I will start with on this issue.  More can be added in this issue so they aren't spread out everywhere.

 - [ ] getMeterValue is returning the instantaneous value of a meter, not the cumulative.  Alter this.
 - [ ] Add example build folder for C/Python APIs, with CMakeLists for C, and pointing Python to an E+ install for Python.
 - [ ] Integrate API docs into build process, or at least streamline it
 - [ ] Finish converting EMS examples to PythonPlugin, and clean up any warnings in all of them
 - [ ] Eliminate GetPrerequisites build warning on Mac
 - [ ] TestMathAndKill idf files DO fail, but not for the right reason -- they need fixing up
 - [ ] Add a proper test of resetActuator in a test file/script
 - [ ] Add tests that provide handles out of range and check the flag or expect an exception depending on run type.
 - [ ] Resolve declspec vs throw warning

The base CI 32-bit Windows builds will not be linked with Python for now.  These builds are used so rarely, I don't envision this being a problem.  Maybe sometime we can just stop building them...but that's for another day.  In the crazy case that someone wants a 32-bit Windows build linked with Python, I can probably figure out how to get a one-off, but no guarantee.  With that in mind, though:
 - [ ] Verify that the build fails gracefully if the wrong bitness is encountered.
 - [ ] Should the UserDefined IDD objects be modified to allow Plugins?  I can't remember.

**Comment by bonnema** [comment]
@Myoldmopar to run E+ 9.3 from the command line on Windows, you now need to have the python37.dll and the python_standard_lib directory in the same directory as your in.idf and in.epw (and the IDD, energyplus.exe, and energyplusapi.dll; but that was the same as before). I',m not totally sure if the IDD is required anymore, but I do it out of habit.

However, it'd be nice to see for the next release the python stuff be like expand objects - if there are no python IDD objects, the DLL and library directory are not needed.

**Comment by Myoldmopar** [comment]
@bonnema thanks.  Are you copying around the energyplus.exe file everytime you run an IDF?  If so, I wouldn't.  Just copy the IDF to a folder and then run the exe from where it was:

```
mkdir /tmp/test
cd /tmp/test
cp /eplus/install/ExampleFiles/1ZoneUncontrolled.idf .
/eplus/install/energyplus -w /eplus/install/WeatherData/ChicagoBlah.epw ./1ZoneUncontrolled.idf
```

I know that's Linux but still, you shouldn't need to copy anything around, just use the command line args and it should be fine.

**Comment by bonnema** [comment]
@Myoldmopar sweet! That is much better. Thank you - I think my initial comment is not applicable anymore...

**Comment by Myoldmopar** [comment]
Great!  Glad to hear it!

**Comment by bonnema** [comment]
```
C:\Users\ebonnema\Documents\Projects\...>dir
 Volume in drive C is Local
 Volume Serial Number is ...

 Directory of C:\Users\ebonnema\Documents\Projects\...

03/30/2020  08:59 AM    <DIR>          .
03/30/2020  08:59 AM    <DIR>          ..
12/17/2019  02:45 PM         1,614,875 in.epw
03/30/2020  08:44 AM            68,135 in.idf
02/09/2017  01:53 PM               109 rw.rb
               3 File(s)      1,683,119 bytes
               2 Dir(s)  545,300,406,272 bytes free

C:\Users\ebonnema\Documents\Projects\...>C:\EnergyPlusV9-3-0\energyplus.exe -w in.epw in.idf
EnergyPlus Starting
EnergyPlus, Version 9.3.0-baff08990c, YMD=2020.03.30 09:00
Adjusting Air System Sizing
Adjusting Standard 62.1 Ventilation Sizing
Initializing Simulation
Reporting Surfaces
Beginning Primary Simulation
Initializing New Environment Parameters
Warming up {1}
Updating Beam-to-Diffuse Exterior Solar Reflection Factors
Updating Beam-to-Beam Exterior Solar Reflection Factors
Warming up {2}
Warming up {3}
Warming up {4}
Warming up {5}
Warming up {6}
Warming up {7}
Warming up {8}
Warming up {9}
Warming up {10}
Warming up {11}
Warming up {12}
Starting Simulation at 07/13/2015 for LAGUARDIA TMY3
Writing tabular output file results using HTML format.
Writing final SQL reports
EnergyPlus Run Time=00hr 03min 45.89sec
EnergyPlus Completed Successfully.

C:\Users\ebonnema\Documents\Projects\...>

**Comment by bonnema** [comment]
@Myoldmopar must be a feature I missed - I don't think you were able to do that in the past. Now I won't have a bunch of exes all over my computer...

**Comment by bonnema** [comment]
This does not seem to work on Mac.

**Comment by Myoldmopar** [comment]
What doesn't?  I'm aware of some issues: https://github.com/NREL/EnergyPlus/issues/7888

**Comment by bonnema** [comment]
running with command line arguments

**Comment by bonnema** [comment]
Never mind

**Comment by Myoldmopar** [comment]
OK whew :+1:

**Comment by mitchute** [comment]
It looks like this isn't relevant anymore due to #8235, #8181, #8173, #8139, #8105, #8093, #8086, #7927, #7836, #7835, AND #7776. Whew!

Feel free to reopen or start a new issue if needed.

**Comment by Myoldmopar** [comment]
OMG.  Thanks for itemizing those @mitchute !

**Comment by mitchute** [comment]
There were more 😆

**Comment by wta12** [comment]
@Myoldmopar @mitchute : Would like to follow up with _**getMeterValue** is returning the instantaneous value of a meter, not the cumulative._ - Has it been corrected ? with 9.5 EMS code it's still an issue so I doubt if Python EMS works with cumulative meter reading.

**Comment by bonnema** [comment]
I would think you would want the method to return the instantaneous value. You could accumulate in your code (Python or ERL).

**Comment by wta12** [comment]
Yeah, ERL or Python accumulate code will work. If that limit is pending forever, it's better to add notes to documentation or add warnings/error output while the output:meter and output:meter:cumulative are both available in mdd list

**Comment by bonnema** [comment]
I think using meters in EMS can lead to unexpected behavior. I think the preferred practice is to stick with output variables.

**Comment by wta12** [comment]
It works on my particular case and I have not seen any problem so far - Output:Meter without accumulate is exactly Output:Variable analogue and called by EMS Sensor. Btw, just want to follow up development progress not EMS practice since I found adequate work around. Thanks

**Comment by bonnema** [comment]
Sure, just mentioning it. See https://github.com/NREL/EnergyPlus/issues/8915 or https://github.com/NREL/EnergyPlus/issues/7563 for an example.
