### ISSUE TITLE
Python File in EnergyPlus src Directory

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#7892]
Issue overview
--------------
There's a Python file mixed in with the EnergyPlus source, potentially a mistaken commit:

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Untitled.ipynb

If it is intentional, then it should probably be elsewhere.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Easy to swipe right by that intermingled with the [other files](https://github.com/NREL/EnergyPlus/pull/7415/files#diff-8028699caaeafe405dfa4951dee41245) in a moderate sized PR.  Good find.
