### ISSUE TITLE
HeatExchanger:AirToAir:SensibleAndLatent negative effectiveness and sizing

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7901]
Issue overview
--------------
1. HeatExchanger:AirToAir:SensibleAndLatent is allowing a negative latent effectiveness to produce very cold (<-100C) outlet node temperatures. At a minimum, effectiveness should be clipped at zero, and maybe with a one-time warning that there's a problem.

2. HeatExchanger:AirToAir:SensibleAndLatent "Nominal Supply Air Flow Rate" (for "Air-to-Air HX 15") is autosizing to 0.48682 while the max OA flow rate is autosizing to 4.88937 m3/s which contributes to the problem. Seems the HX flow should match the max OA flow rate?
*Correction: The system is a makeup air system (DOAS) and the Sizing:System Type of Load to Size On=Sensible. It should be VentilationRequirement. Then everything would be sizing to the minOA flow as it should be.*

Background
-------------
User file is failing with
```
   ** Severe  ** PsyRhoAirFnPbTdbW: RhoAir (Density of Air) is calculated <= 0 [-7.76103].
   **   ~~~   ** pb =[98390.00], tdb=[-317.32], w=[1.0000000E-005].
   **   ~~~   **  Routine=Unknown, Environment=RUN PERIOD 1, at Simulation time=08/04 07:20 - 07:25
   **  Fatal  ** Program terminates due to preceding condition.
```

Trapping this in the debugger revealed the failure occurs in `CalcMoreNodeInfo` for `Node(670)` which is "Node 393, !- Exhaust Air Outlet Node Name" in HeatExchanger:AirToAir:SensibleAndLatent "Air-to-Air HX 15'.

Trapping for negative outlet temp in `MixedAir::CalcAirToAirGenericHeatExch` revealed that  the latent effectiveness is -22 (yes, negative) which results in a wildly negative exhaust air leaving enthalpy.

This is partly driven by the actual flow rate being 10x the nominal flow rate for the heat exchanger. For some reason, the HX flow rate is autosizing to 0.48682 while the max OA flow rate is autosizing to 4.88937 m3/s. 

Looking at the HX cooling effectiveness inputs explains why the latent effectiveness is going negative:

0.76, !- Sensible Effectiveness at 100% Cooling Air Flow {dimensionless}
0, !- Latent Effectiveness at 100% Cooling Air Flow {dimensionless}
0.76, !- Sensible Effectiveness at 75% Cooling Air Flow {dimensionless}
0.73, !- Latent Effectiveness at 75% Cooling Air Flow {dimensionless}

The last field should be zero (like all of the other HXs in this idf).

### Details
Some additional details for this issue (if relevant):
 - Platform Win64
 - Version of EnergyPlus v9.3.0
 - Helpdesk ticket number 15440

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added EnergyPlusDevSupport\DefectFiles, run with Toronto weather.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
added defect file
