### ISSUE TITLE
Error: Heater Control Type for WaterHeater:Stratified must be CYCLE?

### ISSUE THREAD

**Issue by bbrannon4** [NREL/EnergyPlus#7902]
Issue overview
--------------
I've got this error:

   ** Severe  ** WaterHeater:HeatPump:WrappedCondenser = PLANTHEATPUMPWATERHEATER:
   **   ~~~   ** Heater Control Type for WaterHeater:Stratified = WATER HEATER TANK must be CYCLE.

on a fairly simple model, where I have I think completely copied the heat pump water heater components from the WaterHeaterHeatPumpWrappedCondensor example file (which has both a wrapped condenser heater and a stratified water heater tank, just like my model). This is why this error is confusing me, because it says the tank must have a cycle control, but that is only available in a WaterHeater:Mixed, not a WaterHeater:Stratefied - and somehow this combination is working fine int he example file. I wasn't able to find anything explaining the requirement in the documentation, so I'm at a bit of a loss. Any idea what might trigger this requirement in the heat pump settings or somewhere else? 

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - version 9.1 (used in current version of CBECC-Com - haven't tested in newer E+ versions)
 - https://unmethours.com/question/43617/error-heater-control-type-for-waterheaterstratified-must-be-cycle/

[HotSml-03-ECM207_idf.txt](https://github.com/NREL/EnergyPlus/files/4429346/HotSml-03-ECM207_idf.txt)

### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/7000s/7902/HotSml-03-ECM207.idf
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
File provided was at version 9.0. Added that to DevSupport, transitioned to 9.3.0, removed a ScheduleFile. File will fatal out for another reason (wrong branchlist objects), but it still does exhibit the severe mentioned above.

```
   ** Severe  ** WaterHeater:HeatPump:WrappedCondenser = PLANTHEATPUMPWATERHEATER:
   **   ~~~   ** Heater Control Type for WaterHeater:Stratified = WATER HEATER TANK must be CYCLE.
```
