### ISSUE TITLE
Utilities Tab is Blank after EnergyPlus 9.3 Installation

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7910]
Issue overview
--------------
The Utilities Tab is blank in EP-Launch after installing EnergyPlus 9.3.
![Capture](https://user-images.githubusercontent.com/39242689/78716127-42a89b00-78d3-11ea-9b1c-ce43ba7004b0.PNG)

### Details
Some additional details for this issue (if relevant):
 - Windows 10, Windows Server 2016
 - Version of EnergyPlus 9.3
 - https://unmethours.com/question/43648/utilities-tab-in-e93-launcher/

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
@mldichter could you please see if the new EP-Launch.exe fixes the issue you saw.

https://github.com/NREL/EnergyPlus/tree/7910-FixUtilityTabOnEPlaunch/bin/EP-Launch

**Comment by mldichter** [comment]
@JasonGlazer I'm having some trouble with permissions on windows 10. I was able to force the file to download, but windows won't let me copy the file into the EnergyPlusV9-3-0 directory and windows won't let me run the file saying,

![Capture](https://user-images.githubusercontent.com/39242689/79489984-fba45f00-7fd0-11ea-801d-1772bb9c7570.PNG)

You could try the other people from the unmet hours post.

**Comment by JasonGlazer** [comment]
@mldichter looks like some kind of permission issue.

@aaron-boranian Could you try this and see if the utility tab shows?

**Comment by JasonGlazer** [comment]
@mjwitte had luck by using the ep-launch.exe after pulled that branch on his local EnergyPlus repo. Not sure why the link I provided above would not work but clearly that messed up.
