### ISSUE TITLE
EP-Launch being marked as Trojan by Windows Defender

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7911]
Issue overview
--------------
After installing EnergyPlus 9.3, the EP-Launch application was deleted by Windows Defender during the next scan for viruses.
    Threat quarantined
    Threat detected: Trojan:Win32/Woreflint.A!cl
    Alert level: Severe
    Category: Trojan
    Details: This program is dangerous and executes commands from an attacker.
    Affected items: file: C:\EnergyPlusV9-3-0\EP-Launch.exe

Reinstallation does not resolve the issue. I was able to stop EP-Launch from being removed by adding C:\EnergyPlusV9-3-0 as an Exclusion in the "Virus & threat protection" settings in Windows.

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - Version of EnergyPlus 9.3

### Checklist
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
I just submitted it to Microsoft [here](https://www.microsoft.com/en-us/wdsi/submission/a817783e-ce48-4fe5-af89-e7cec21a49a6)

**Comment by JasonGlazer** [comment]
Here are the results from Microsoft. It looks like this will not occur in the future. Assuming that the Windows Defender database is updated 

![image](https://user-images.githubusercontent.com/2582150/78800524-295e2800-7981-11ea-87fb-2acb190f95af.png)
