### ISSUE TITLE
Surface Convection Algorithm AdaptiveModelSelections is not truncatable.

### ISSUE THREAD

**Issue by ajscimone** [NREL/EnergyPlus#7917]
Issue overview
--------------
The SurfaceConvectionAlgorithm:(Inside/Outside):AdaptiveModelSelections algorithm selection cannot be truncated even though all the inputs have a default defined in the idd. The expected behavior here would be that the user can input:
"    SurfaceConvectionAlgorithm:Inside:AdaptiveModelSelections,
    Default Algorithm;       !- Name"
into their idf and expect to get all default algorithm selections. However, a ',' must be input for each field for this object in order to get default values.

### Details
 - Platform: All
 - Version of EnergyPlus: 9.3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
I'm fairly certain that `\min-fields` in the IDD should fix that. 91 for Inside, 13 for Outside.

**Comment by ajscimone** [comment]
@mjwitte Would this actually allow for the fields to be truncated? I am under the impression that putting `\min-fields` would require the user to have a line for each field. It is relatively easy to have EnergyPlus default each field even if its not input if that's the case.

**Comment by mjwitte** [comment]
No. \min-fields serves two functions - the input processor fills the defaults for all fields up to that point (there was some question in my mind if that's still the case after the epJSON input processor change, but apparently it's still necessary to force defaults to be filled). Also, IDF Editor (and other tools?) uses min-field when writing the idf, it will write at least that many fields no matter what.
