### ISSUE TITLE
Eng Ref documenation issue for ground heat transfer using C and F Factor methods

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#7926]
Issue overview
--------------
 - Equation 3.197 [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-c.tex#L73) for fictitious thermal resistance has incorrect sign. The double negative sign appears in equations 3.198 and 3.99 [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-c.tex#L97) and [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-c.tex#L113) as well. 

 - Underground wall effective heat transfer coefficient including the "floor construction" should have been "wall construction" [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-c.tex#L126), This is most likely copied from section above but not edited.
 
## Details
Some additional details for this issue (if relevant):
 - All Platforms
 - Version of EnergyPlus V9.3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmythms** [comment]
> ## Issue overview
> * Equation 3.197 [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-c.tex#L73) for fictitious thermal resistance has incorrect sign. The double negative sign appears in equations 3.198 and 3.99 [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-c.tex#L97) and [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-c.tex#L113) as well.
> * Underground wall effective heat transfer coefficient including the "floor construction" should have been "wall construction" [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/engineering-reference/src/surface-heat-balance-manager-processes/ground-heat-transfer-calculations-using-c.tex#L126), This is most likely copied from section above but not edited.
> 
> ## Details
> Some additional details for this issue (if relevant):
> 
> * All Platforms
> * Version of EnergyPlus V9.3
> 
> ### Checklist
> Add to this list or remove from it as applicable. This is a simple templated set of guidelines.
> 
> * [ ]  Defect file added (list location of defect file here)
> * [ ]  Ticket added to Pivotal for defect (development team task)
> * [ ]  Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

I will attempt to correct the issue. Thanks.
