### ISSUE TITLE
User input meter type FUELOIL#1 instead of FUELOILNO1 

### ISSUE THREAD

**Issue by xuanluo113** [NREL/EnergyPlus#7930]
Issue overview
--------------
In `Meter:Custom` object, the available choices of fuel oil are `FUELOIL#1` and `FUELOIL#2`. These types have already been renamed to `FUELOILNO1` and `FUELOILNO2` in EnergyPlus 9.3. However, declaring `FUELOILNO1` and `FUELOILNO2` in this object causes fatal error.

Referring [this line](https://github.com/NREL/EnergyPlus/blob/185e20e71c38982ae12f355ab950587cc20caa7f/src/EnergyPlus/OutputProcessor.cc#L1947).

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Only the component fuel type inputs were changed for v9.3. All outputs, including meter names remained unchanged. See #7622 and #7621. Hopefully the output side will be done for v9.4.

**Comment by xuanluo113** [comment]
@mjwitte Thanks for the clarification. I'll close this then.

**Comment by mjwitte** [comment]
@xuanluo113 Turns out this really was a valid issue. It was reported again in #8132 and will be addressed in #8134. Sorry for the confusion.
