### ISSUE TITLE
energyplus command line removing first two characters of idf filename

### ISSUE THREAD

**Issue by dshen109** [NREL/EnergyPlus#7937]
Issue overview
--------------
EnergyPlus 9.2 was working fine on my computer, then over the weekend after I autoremoved some packages in Linux while installing some other unrelated software, the first two characters of every `idf` file I pass in as a command gets removed:

```
dshen@bleh:~/Documents $ energyplus test.idf
ERROR: Could not find input data file: /home/dshen/Documents/st.idf.
Type 'energyplus --help' for usage.
```
(this does not work, even when the file `test.idf` exists in the directory)

Uninstalling EnergyPlus and updating to 9.3 did not fix the issue.

### Details
Some additional details for this issue (if relevant):
 - Ubuntu 18.04
 - 9.2.0 and 9.3.0
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Do you know which packages got autoremoved?  That is a very strange problem!  I would try to run EnergyPlus in different ways to help isolate the problem, as at this point, it's unclear whether the autoremoved packages interfered with EnergyPlus itself, or the shell that is parsing the arguments to pass into EnergyPlus.
 - Rename the input file to in.idf, and just run EnergyPlus without any arguments -- in.idf is the default file name, so if it finds it there then that at least narrows it down to the argument as the problem.
 - Call to run EnergyPlus without a shell.  This can be done in Python with subprocess, just make a small script like:
```
import subprocess
subprocess.check_call(['/path/to/energyplus', '/path/to/test.idf'], shell=False, cwd='/your/working/dir')
```

You can play around with arguments there and see if running it by default works (in.idf), or if it works with your test file name.  

I'd mess around with a few things like that and report back so we can try to help figure it out.

**Comment by rraustad** [comment]
You might also try copying test.idf to st.idf and then run your original script and see if it does run st.idf.

**Comment by jmarrec** [comment]
Are other commands affected? eg `cat test.idf` ?

Can you try with `energyplus -- test.idf` to see if that solves it?

**Comment by jmarrec** [comment]
Also, please check what readline libraries you have. Can you paste the output of this please?

```shell
lsb_release -a
uname -a
sudo apt list --installed | /bin/grep readline
```

eg on mine:

```shell
$ lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

$ uname -a
Linux julien-XPS-15-9570 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

$ sudo apt list --installed | grep readline
libreadline-dev/bionic,now 7.0-3 amd64 [installed]
libreadline7/bionic,now 7.0-3 amd64 [installed]
readline-common/bionic,bionic,now 7.0-3 all [installed]
```

**Comment by dshen109** [comment]
Other commands such as `cat` were not affected. The problem has somehow resolved itself, though. 

For the record, commands such as `energyplus ./test.idf` did work.

```
 $ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

$ uname -a
Linux rigel-97 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ sudo apt list --installed | /bin/grep readline

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libreadline-dev/bionic,now 7.0-3 amd64 [installed,automatic]
libreadline6/now 6.3-8ubuntu2 amd64 [installed,local]
libreadline7/bionic,now 7.0-3 amd64 [installed,automatic]
readline-common/bionic,bionic,now 7.0-3 all [installed]

```

**Comment by jmarrec** [comment]
closing as this seemed unrelated to E+ specifically and is resolved on user machine too.
