### ISSUE TITLE
Provide some example files in epJSON format

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#7943]
As examples of the new file format, please include some files in epJSON format in the Examples directory.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
There is one, RefBldgMediumOfficeNew2004_Chicago_epJSON.epJSON

**Comment by JasonGlazer** [comment]
RefBldgMediumOfficeNew2004_Chicago_epJSON.epJSON is already distributed
