### ISSUE TITLE
Documentation Issues - 2020b

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7949]
Issue overview
--------------
A collection of small documentation issues. See checkboxed comments below.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
- [x] In the Auxiliary Programs Document, searching for "Sky Cover" (p. numbers for v9.3.0 docs):
p. 26, in the table opaque sky cover should be "y" for Used by EnergyPlus, with a footnote "Opaque sky cover is used when horizontal infrared radiation intensity from sky is missing or when specified by user input."
p. 27, in the table opaque sky cover should be "Y" for Used by EnergyPlus, referring to the same footnote
p. 30, in the table, in row for Opaque Sky Cover Value,there's a formatting problem causing words to overlap (I'm guessing this isn't really a table in the LaTeX source, so the whole table should be reformatted?)

Also in the same tables Albedo is used by the PVWatts model, but not elsewhere.

**Comment by JasonGlazer** [comment]
- [x] In all fields were air flows are entered such as Outdoor Air Flow per Person in DesignSpecification:OutdoorAir, include that the air flow is standard density.

**Comment by mjwitte** [comment]
- [ ] Several new output variables were added  in [#6087](https://github.com/NREL/EnergyPlus/pull/6087/files?file-filters%5B%5D=.cc&file-filters%5B%5D=.hh&file-filters%5B%5D=.idf&file-filters%5B%5D=.png&file-filters%5B%5D=.txt#diff-5c8ae68e0c1957e13e46b597f3cfd5ffR917-R919) related to `MaterialProperty:PhaseChangeHysteresis`, but these is no documentation for them in the Input Output Reference:
```
Output:Variable,*,CondFD Phase Change State 1,hourly; !- Zone Average []
Output:Variable,*,CondFD Phase Change Previous State 1,hourly; !- Zone Average []
Output:Variable,*,CondFD Phase Change Node Temperature 1,hourly; !- Zone Average [C]
```
@Myoldmopar

**Comment by mldichter** [comment]
- [x] Having the ZoneAirMassFlowConservation object referenced as a solution to unbalanced air flows in the IO Ref text for the Fan:ZoneExhaust object would be immensely helpful to users. (I wish I had known about this years ago!) Trying to balance exhaust fan airflow with outdoor air system flow and infiltration, ventilation, or zone mixing schedules is tedious and seems to have trouble on the timestep when the equipment turns on or off no mater what, especially if there is any airflow from zone mixing like in a restaurant. This object takes almost all those burdens off the user. https://unmethours.com/question/8746/questions-about-zone-mixing-and-other-airflow-objects/

**Comment by shorowit** [comment]
- [x] The `GroundHeatExchanger:Vertical:Properties` object is missing a description for the "Borehole Diameter" field in the I/O Reference.

**Comment by jmarrec** [comment]
* [x] I/O ref for "Schedule Output" mentions a specific report [here](https://bigladdersoftware.com/epx/docs/9-3/input-output-reference/group-schedules.html#outputs-031), but E+ throws with `Output:Reports is a not a valid object type`


![image](https://user-images.githubusercontent.com/5479063/85731071-7c32ba80-b6fa-11ea-9171-2a88f3f91adf.png)

https://github.com/NREL/EnergyPlus/blob/243d26133276886d7c7e4929b2788e3cd143eba7/doc/input-output-reference/src/overview/group-schedules.tex#L545-L556

**Comment by jmarrec** [comment]
* [x] I/O ref for SwimmingPool:Indoor has wrong output variables, at least these two:

HVAC, Average, Indoor Pool Heating Rate [W]
HVAC, Sum, Indoor Pool Heating Energy [J]

Instead should be https://github.com/NREL/EnergyPlus/blob/6c588048d43afb2dacf480174013e050ae104d1a/src/EnergyPlus/SwimmingPool.cc#L661-L662

**Comment by mldichter** [comment]
* [x] Duplicate paragraph IO Ref 9.3
![Capture](https://user-images.githubusercontent.com/39242689/87586327-3b90e600-c695-11ea-9f1f-c7943bad4f15.PNG)

**Comment by mjwitte** [comment]
- [x] EMS actuators `BeginZoneTimestepBeforeInitHeatBalance` and `BeginZoneTimestepAfterInitHeatBalance` were added in #7177 

They are documented in the EMS Application Guide text, but they were never added to the calling point figures. That would be useful.

Also, in the text description for BeginZoneTimestepBeforeInitHeatBalance it would be good to add: "This calling point would be an appropriate place to modify weather data values." (or something like that.
Ref. Helpdesk ticket 15517

**Comment by jcyuan2020** [comment]
- [x] The equations are incorrect for the RectangularHyperbola1 (Sec 1.58.17, Page 2368, InputOutputReference.pdf, Version 9.3.0) and RectangularHyperbola2 (Sec 1.58.18, Page 2370) curves. There are redundant mistyped minus signs in these two equations.  

![image](https://user-images.githubusercontent.com/64040111/89664505-e1063680-d89c-11ea-822c-6e486069c361.png)
![image](https://user-images.githubusercontent.com/64040111/89664558-f2e7d980-d89c-11ea-80b1-8e5ba65f10b0.png)

Ref. Helpdesk ticket 15536

**Comment by jcyuan2020** [comment]
- [x] Weather related outputs section has wrong headings in the InputOutputReference.pdf. Section 1.7.29.2 (Named `Outputs` should never belong to Section 1.7.29 (which is about `Site:SpectrumData`). Rather, it should be bumped at least one level up, as the new Section 1.7.30. In Version 9.3.0, it is on Page 122. This problem also caused the headings for the subsequent section headings in the next few pages to be messed up.  The subsequent headings in Page 122--129, till the end of Section 1.7, will all be affected. 

![image](https://user-images.githubusercontent.com/64040111/89751283-0b224900-da95-11ea-808c-e2f19c726997.png)

**Comment by jcyuan2020** [comment]
- [x] Still, for the above mentioned affected section headings in Page 122-129 (Version 9.3.0, InputOutputReference.pdf) about weather outputs, it seems that the structure need to be adjusted. It seems that the current Sec 1.7.29.2 should be bumped up one level as new Sec 1.7.30; the current Sec 1.7.29.3 should become new Sec 1.7.30.1; and a few pages down in Page 128, the current Sec 1.7.30 should be downgrade one level as the new Sec 1.7.30.2 (as one of the parallel subsubsections). 
Some text changes may also be needed. For example, an additional sentence or two can be added to explain the two places where the outputs occur, as were mentioned in the current content of Sec 1.7.29.2 (new Sec 1.7.30). The current Sec 1.7.29.2 heading title can also be changed to something a little bit more specific—e.g. `General Environment Outputs`. 

![image](https://user-images.githubusercontent.com/64040111/89752357-a9b0a900-da99-11ea-95cd-fbf18965add2.png)
![image](https://user-images.githubusercontent.com/64040111/89752419-e9779080-da99-11ea-8b15-7f101cf5632a.png)

**Comment by mjwitte** [comment]
@jcyuan2020 Referring back to the v8.2 I/O Reference the two "Outputs" headings above are missing words, and they belong at the same level as Site:SpectrumData.
![image](https://user-images.githubusercontent.com/4991075/89786856-367f5500-dae2-11ea-85c7-d2d6c6100a5d.png)

**Comment by jcyuan2020** [comment]
@mjwitte Thank you! This issue about weather/climate output headings has been corrected as part of the revisions in PR #8143.

**Comment by jcyuan2020** [comment]
- [x] Page 45 of Engineering Document (V9.3.0):  the coefficient `1.0^6` should be `10^6` in Equation (2.65). 

![image](https://user-images.githubusercontent.com/64040111/89911485-1a99b300-dbb7-11ea-83b3-e5c7660a243d.png)

**Comment by jmythms** [comment]
> * [x]  In the Auxiliary Programs Document, searching for "Sky Cover" (p. numbers for v9.3.0 docs):
>   p. 26, in the table opaque sky cover should be "y" for Used by EnergyPlus, with a footnote "Opaque sky cover is used when horizontal infrared radiation intensity from sky is missing or when specified by user input."
>   p. 27, in the table opaque sky cover should be "Y" for Used by EnergyPlus, referring to the same footnote
>   p. 30, in the table, in row for Opaque Sky Cover Value,there's a formatting problem causing words to overlap (I'm guessing this isn't really a table in the LaTeX source, so the whole table should be reformatted?)
> 
> Also in the same tables Albedo is used by the PVWatts model, but not elsewhere.

I was correcting this issue and noticed some inconsistent capitalization. Does the capitalization of "y" and "n" mean anything specific in the last column of this table? Else, I can correct it to look the same way.

**Comment by mitchute** [comment]
> Does the capitalization of "y" and "n" mean anything specific in the last column of this table? Else, I can correct it to look the same way.

Feel free to correct them to be all upper case.

**Comment by jmythms** [comment]
> Output:Variable,*,CondFD Phase Change State 1,hourly; !- Zone Average []



> * [ ]  Several new output variables were added  in [#6087](https://github.com/NREL/EnergyPlus/pull/6087/files?file-filters%5B%5D=.cc&file-filters%5B%5D=.hh&file-filters%5B%5D=.idf&file-filters%5B%5D=.png&file-filters%5B%5D=.txt#diff-5c8ae68e0c1957e13e46b597f3cfd5ffR917-R919) related to `MaterialProperty:PhaseChangeHysteresis`, but these is no documentation for them in the Input Output Reference:
> 
> ```
> Output:Variable,*,CondFD Phase Change State 1,hourly; !- Zone Average []
> Output:Variable,*,CondFD Phase Change Previous State 1,hourly; !- Zone Average []
> Output:Variable,*,CondFD Phase Change Node Temperature 1,hourly; !- Zone Average [C]
> ```
> 
> @Myoldmopar

These outputs seem to be on a layer by layer basis as seen [here](https://github.com/NREL/EnergyPlus/blob/7badc378a280879046ae72d47b0b12e90e5ea128/src/EnergyPlus/HeatBalFiniteDiffManager.cc#L951-L994). Should the variable names be changed to add "layer" or similar help clarify this point? @mjwitte @Myoldmopar  Do you have any other suggestions on this suggested change?
