### ISSUE TITLE
AirTerminal:SingleDuct:ConstantVolume:NoReheat Zone Air Terminal Outdoor Air Volume Flow Rate always zero

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#7950]
Issue overview
--------------
The AirTerminal:SingleDuct:ConstantVolume:NoReheat object, which explicitly has no outputs in the IO Reference, is being associated with the Zone Air Terminal Outdoor Air Volume Flow Rate output variable having value zero during the simulation. The error can be reproduced in an IDF with an AirTerminal:SingleDuct:ConstantVolume:NoReheat object and the following object.

```
Output:Variable,
    *,                       !- Key Value
    Zone Air Terminal Outdoor Air Volume Flow Rate,  !- Variable Name
    Hourly;                  !- Reporting Frequency
```

I wasted a bit of time trying to figure out why my outdoor air flow was zero in my airloop using the Zone Air Terminal Outdoor Air Volume Flow Rate output variable. Worth fixing so no one else has to debug the same problem.

### Details
 - EnergyPlus 9.3

### Checklist
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@mldichter Actually, it's the reverse. This output variable *should* work for any type of terminal unit. This one isn't setting the value, so that needs to be fixed. (I've edited the issue name.)

Developer note: need to check all terminal unit types and perhaps centralize setting this variable. And check the documentation for this an other related output variables - if they are documentated at the AirDistributionUnit, then the terminal units should probably have a note pointing there.

**Comment by mldichter** [comment]
@mjwitte The IO Ref needs to be changed as well for at least two object then.

1.30.1 AirTerminal:SingleDuct:ConstantVolume:Reheat
> 1.30.1.2 Outputs
> There are no outputs for the constant volume reheat air terminal.

1.30.2 AirTerminal:SingleDuct:ConstantVolume:NoReheat
> 1.30.2.2 Outputs
> There are no outputs for the constant volume NoReheat air terminal.

**Comment by Nigusse** [comment]
Reviewed develop code and I see the report variable *Zone Air Terminal Outdoor Air Volume Flow Rate* is available (set-up) only for the following four air terminal units:
 - AirTerminal:DualDuct:VAV
 - AirTerminal:SingleDuct:VAV:Reheat
 - AirTerminal:SingleDuct:VAV:NoReheat
 - AirTerminal:SingleDuct:ConstantVolume:NoReheat

While the dual duct air terminal unit type AirTerminal:DualDuct:VAV:OutdoorAir has a report variable *Zone Air Terminal Outdoor Air Fraction*, instead.

The code shows the *ZoneHVAC:AirDistributionUnit* has no flow related output variables setup even though the I/O Ref documentation claims so.

**Comment by Nigusse** [comment]
Posted new issue for DualDuct VAV air terminal report variable issue #7974. Testing example files with the following *eight* single duct air terminal types revealed that all of them do not have the report variable *Zone Air Terminal Outdoor Air Volume Flow Rate* set-up.  

```cpp
	AirTerminal:SingleDuct:SeriesPIU:Reheat
	AirTerminal:SingleDuct:ParallelPIU:Reheat
        AirTerminal:SingleDuct:ConstantVolume:FourPipeInduction
	AirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan
	AirTerminal:SingleDuct:VAV:HeatAndCool:Reheat
	AirTerminal:SingleDuct:VAV:HeatAndCool:NoReheat
	AirTerminal:SingleDuct:ConstantVolume:CooledBeam
        AirTerminal:SingleDuct:ConstantVolume:FourPipeBeam
```
@mjwitte Do we need to add the same report variable for all these eight singe duct air terminal types? If that is the case I may need to post new issue separately.

**Comment by mjwitte** [comment]
I would like to see consistency across all terminal units, as appropriate. Clearly all terminal units can deliver some fraction of out door air, so, yes. But this should happen in a common place (or at most one place for single duct and one for dual duct). Instead of adding multiple `SetUpOutputVariable` statements in the various terminal type loops, it seems you could add a single loop over all the single-duct `SysNum` (`NumSDAirTerminal`) at the end of `SingleDuct::GetSysInput` that sets up Zone Air Terminal Outdoor Air Volume Flow Rate for everyone.

**Comment by Nigusse** [comment]
OK. @mjwitte Thanks. I will consolidate the calc function in single place and common member function, also set-up the report variable for all single air terminal units in one place as suggested.

**Comment by Nigusse** [comment]
@mjwitte Three of the eight single duct air terminals are contained in SingleDuct.cc module but the other five single duct air terminals contained in four different modules:

   ```cpp
   AirTerminal:SingleDuct:VAV:Reheat:VariableSpeedFan, in SingleDuct.cc
   AirTerminal:SingleDuct:VAV:HeatAndCool:Reheat, in SingleDuct.cc
   AirTerminal:SingleDuct:VAV:HeatAndCool:NoReheat, in SingleDuct.cc

   AirTerminal:SingleDuct:SeriesPIU:Reheat, in PoweredInductionUnits.cc
   AirTerminal:SingleDuct:ParallelPIU:Reheat, in PoweredInductionUnits.cc

   AirTerminal:SingleDuct:ConstantVolume:FourPipeInduction, in HVACSingleDuctInduc.cc
   AirTerminal:SingleDuct:ConstantVolume:CooledBeam, in HVACCooledBeam.cc
   AirTerminal:SingleDuct:ConstantVolume:FourPipeBeam, in HVACFourPipeBeam.cc
```

So, the fix is done in five different places/modules by adding a member function to each module.
