### ISSUE TITLE
Error in water consumption calculation in evaporatively cooled Chiller:Electric:EIR

### ISSUE THREAD

**Issue by jawysocki** [NREL/EnergyPlus#7951]
Issue overview
--------------
Model of evaporatively cooled Chiller:Electric:EIR incorrectly uses air density to calculate volumetric water consumption rate, which results in 1000-fold errors in calculated chiller water use (line 2189):

```cpp
((this->CondOutletHumRat - DataLoopNode::Node(this->CondInletNodeNum).HumRat) * this->CondMassFlowRate) / RhoAir;
```
Water density should rather be used instead.

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - EnergyPlus 8.9

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
Confirmed the defect in develop [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ChillerElectricEIR.cc#L2188-L2189).
