### ISSUE TITLE
Removed IgnoreInteriorWindowTransmission tag in Output:Diagnostics

### ISSUE THREAD

**Issue by xuanluo113** [NREL/EnergyPlus#7960]
Issue overview
--------------
Seems the `IgnoreInteriorWindowTransmission` tag no longer exists in the object `Output:Diagnostics`, but the logic of checking this condition still remains in the [code](https://github.com/NREL/EnergyPlus/blob/274e7df1216d33e62ac53c4e2d75e20600bb83fb/src/EnergyPlus/SimulationManager.cc#L1079
).

Wonder if this logic is meant to be removed as well.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
There are several other choices in [GetProjectData](https://github.com/NREL/EnergyPlus/blob/274e7df1216d33e62ac53c4e2d75e20600bb83fb/src/EnergyPlus/SimulationManager.cc#L1055-L1100) which are not listed as \keys in the IDD, e.g. IgnoreSolarRadiation, IgnoreBeamRadiation, etc. Some of these are accessible as environment variables in [DataSystemVariables::processEnviornmentVariables](https://github.com/NREL/EnergyPlus/blob/274e7df1216d33e62ac53c4e2d75e20600bb83fb/src/EnergyPlus/DataSystemVariables.cc#L422). I see the ignore solar variables there, but I don't see `IgnoreInteriorWindowTransmission`. Most of these are undocumented, so I don't know if anyone but some of the original authors ever use them.

**Comment by xuanluo113** [comment]
@mjwitte Thanks, Mike. Now I got confused about when `DataSystemVariables::processEnviornmentVariables` is required. It seems to me that by calling [get_environment_variable](https://github.com/NREL/EnergyPlus/blob/274e7df1216d33e62ac53c4e2d75e20600bb83fb/src/EnergyPlus/DataSystemVariables.cc#L426) and `env_var_on`, it's only trying to get the env list by calling [std::getenv](https://github.com/NREL/EnergyPlus/blob/274e7df1216d33e62ac53c4e2d75e20600bb83fb/third_party/ObjexxFCL/src/ObjexxFCL/environment.cc#L60).

I don't know when and how often EnergyPlus would read from a system ENV variable.


------------

Okay, I found the documentation that they are reserved for **module developers**. Nevermind.

**Comment by xuanluo113** [comment]
Under `Output:Diagnostics` It looks to me:
1. `IgnoreInteriorWindowTransmission` is somewhat useful, but can go under `PerformanceAccuracyTradeoff`.
2. Maybe `DoNotMirrorDetachedShading` and `DoNotMirrorAttachedShading` should go under `ShadowCalculation` or simulation control instead of `Output:Diagnostics`? They are not reporting flags.
3. Checking of `IgnoreSolarRadiation`, `IgnoreBeamRadiation` `IgnoreDiffuseRadiation`, and `DeveloperFlag` are not necessary here as they are removed from the IDD.  
4. `TimingFlag`, `CreateMinimalSurfaceVariables` and `CreateNormalSurfaceVariables` are not used anymore in the code. Maybe they could be removed from the input check as well as the system variable list.

@mjwitte Could you please help check these assumptions? Thanks very much.
