### ISSUE TITLE
OCX file not registered errors - again

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#7973]
Issue overview
--------------
Several users have recently run into missing ocx or dll errors again (like we did back in v8.3, ref #5105). The files are there in the operating system, but are either not registered or broken somehow.

If I'm following this portion of the current [installer scripts](https://github.com/NREL/EnergyPlus/blob/develop/cmake/qtifw/install_win_copydll.qs), it appears that the ocx and dll files are not registered by the installer if they are already present in the operating system folder.

I don't think it would hurt anything to have the installer register all of these even if they aren't copied fresh by the installer.

Workaround
------------------------
Confirm that the "missing" file is present in c:\windows\syswow64
Then open a command window (run as administrator) and type `regsvr32 c:\windows\syswow64\<missing-file-name.extension>`
For example `regsvr32 c:\windows\syswow64\MSCOMCTL.ocx`

### Details
Some additional details for this issue (if relevant):
 - Platform Win10
 - Version of EnergyPlus 9.3.0
 - Helpdesk tickets 15468, 154563, 15467

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@jmarrec Any concerns with always registering all of the ocx/dlls in the windows install?

**Comment by jmarrec** [comment]
@mjwitte just need to make sure we catch any exit codes different than 0 that indicate the thing is already registered
