### ISSUE TITLE
Separate Infiltration from Natural Ventilation for AirflowNetwork

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#7977]
Issue overview
--------------
Currently AirflowNetwork does not seem to distinguish between infiltration (through cracks) and ventilation (through openings), it's all tracked as infiltration. They should be separated so that the natural ventilation component is clearly identified. 

The fix should include new output variables and also updating the enhanced outdoor air tabular reports.

Found this while working on #7629. An enhancement to 9.3.0

**Comment by lgu1234** [comment]
@JasonGlazer I am going to take this issue. The AFN model provides output variables as AFN Zone Infiltration *. Are you OK with the new output variables as AFN Zone Ventilation * applied to opening components?

**Comment by JasonGlazer** [comment]
Sounds good to me. I have not used AFN so I may not have captured the nuances in the Issue Overview but in general when people are modeling infiltration effects (I guess I would say usually unplanned outdoor air) versus natural ventilation effects (planned for outdoor air) it would be good to organize it that way. I'm not sure that openings are always used for natural ventilation or not or cracks are always used for infiltration or not, that was a supposition.

**Comment by JasonGlazer** [comment]
And thanks for jumping on this so fast!

**Comment by Myoldmopar** [comment]
Closed via #8018
