### ISSUE TITLE
SwimmingPool:Indoor crashes with incorrect surface name

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7986]
Issue overview
--------------
HelpDesk ticket 15470. User file crashes with no evidence in error file.

Line 301 of SwimmingPool.cc

    Pool(Item).ZonePtr = DataSurfaces::Surface(Pool(Item).SurfacePtr).Zone;

crashes with no indication of problem. This line of code should be moved up into the else above.

As a test this line was changed to:

    if (Pool(Item).SurfacePtr > 0) Pool(Item).ZonePtr = DataSurfaces::Surface(Pool(Item).SurfacePtr).Zone;

and then shows:

    ** Severe  ** GetSwimmingPool: Invalid Surface Name = ZN001:FLR001
    **   ~~~   ** Occurs in SwimmingPool:Indoor = INDOORPOOL1
    **  Fatal  ** GetSwimmingPool: Errors found in swimming pool input. Preceding conditions cause termination.
 
### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added [EnergyPlusDevSupport/DefectFiles/7000s/7986](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/7000s/7986)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@rraustad Thanks, Rich.  I will put that at the top of my bug fixing list.

**Comment by RKStrand** [comment]
@rraustad Yup, definitely this is an error in the logic since it should not crash.  I will fix that.  There is also an error in the user input file which can be fixed by referencing the correct pool floor surface (Pool01 Surface 0 or Pool02 Surface 0 or Pool03 Surface 0).  So, what you saw in your modified version as far as error messages is "correct" as far as what EnergyPlus should have done with this situation.
