### ISSUE TITLE
Natural gas meter reporting as Other in Energy Cost Summary tariff report

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#7999]
Issue overview
--------------
User was confused with reporting tariffs for natural gas equipment.

![image](https://user-images.githubusercontent.com/5778156/82258677-41ce4480-9928-11ea-91d2-a0d24b923ac2.png)

The use of custom meters confused the tariff cost model.

    Meter:Custom,
      Building Natural Gas,                   !- Name
      NaturalGas,                             !- Fuel Type
      ,                                       !- Key Name 1
      Gas:Facility;                           !- Output Variable or Meter Name 1

    UtilityCost:Tariff,
      Sample with All Utilities_NGas,         !- Name
      Building Natural Gas,                   !- Output Meter Name
      Therm,                                  !- Conversion Factor Choice

If the user had used Gas:Facility as the Output Meter Name the tariff object cost result would show up in the Natural Gas row in the Energy Cost Summary. But since they used the name of a custom meter the cost information shows up in the Other category.

The code that selects where this information is reported is in EconomicTariff.cc.

The first IF here looks at tariff(iTariff).kindElectricMtr >= kindMeterElecSimple, or any type of electricity meter.

The next else if looks only at the Gas:Facility meter which is why this custom meter was reported to the Other category.

The suggestion here is to change the first else if to look at all natural gas meters [e.g., else if (tariff(iTariff).kindGasMtr == kindMeterGas)].

Also, this first variable is not used in this function. And depending on how this is implemented, the second may also not be needed. 

    elecFacilMeter = GetMeterIndex("ELECTRICITY:FACILITY");
    gasFacilMeter = GetMeterIndex("GAS:FACILITY");
    distCoolFacilMeter = GetMeterIndex("DISTRICTCOOLING:FACILITY");
    distHeatFacilMeter = GetMeterIndex("DISTRICTHEATING:FACILITY");

    if (tariff(iTariff).kindElectricMtr >= kindMeterElecSimple) {
        if (tariff(iTariff).totalAnnualEnergy > elecTotalEne) elecTotalEne = tariff(iTariff).totalAnnualEnergy;
        elecTotalCost += tariff(iTariff).totalAnnualCost;
        elecTariffNames += ' ' + tariff(iTariff).tariffName;
        elecUnits = tariff(iTariff).convChoice;
    } else if (tariff(iTariff).reportMeterIndx == gasFacilMeter) {
        if (tariff(iTariff).totalAnnualEnergy > gasTotalEne) gasTotalEne = tariff(iTariff).totalAnnualEnergy;
        gasTotalCost += tariff(iTariff).totalAnnualCost;
        gasTariffNames += ' ' + tariff(iTariff).tariffName;
        gasUnits = tariff(iTariff).convChoice;
        gasDemWindowUnits = tariff(iTariff).demandWindow;
    } else if (tariff(iTariff).reportMeterIndx == distCoolFacilMeter) {
        if (tariff(iTariff).totalAnnualEnergy > distCoolTotalEne) distCoolTotalEne = tariff(iTariff).totalAnnualEnergy;
        distCoolTotalCost += tariff(iTariff).totalAnnualCost;
        distCoolTariffNames += ' ' + tariff(iTariff).tariffName;
        distCoolUnits = tariff(iTariff).convChoice;
        distCoolDemWindowUnits = tariff(iTariff).demandWindow;
    } else if (tariff(iTariff).reportMeterIndx == distHeatFacilMeter) {
        if (tariff(iTariff).totalAnnualEnergy > distHeatTotalEne) distHeatTotalEne = tariff(iTariff).totalAnnualEnergy;
        distHeatTotalCost += tariff(iTariff).totalAnnualCost;
        distHeatTariffNames += ' ' + tariff(iTariff).tariffName;
        distHeatUnits = tariff(iTariff).convChoice;
        distHeatDemWindowUnits = tariff(iTariff).demandWindow;
    } else {
        if (tariff(iTariff).totalAnnualEnergy > otherTotalEne) otherTotalEne = tariff(iTariff).totalAnnualEnergy;
        otherTotalCost += tariff(iTariff).totalAnnualCost;
        othrTariffNames += ' ' + tariff(iTariff).tariffName;
        othrUnits = tariff(iTariff).convChoice;
        othrDemWindowUnits = tariff(iTariff).demandWindow;
    }

To create a defect file, use a tariff example file and add a Meter:Custom natural gas object as shown here and point to it in the tariff object.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
Thanks @rraustad.

**Comment by rraustad** [comment]
@JasonGlazer did you get a notification when I assigned you yesterday?

**Comment by rraustad** [comment]
OK, I guess you did.

**Comment by rraustad** [comment]
The other thing that is bothering me while looking at this. If I create multiple tariff objects for multiple electric meters, and some of those electric meters are included in others on this report, will that cause double counting of energy/cost? I didn't see anything in this function to avoid that but there may be other checks elsewhere that check for duplication?

**Comment by JasonGlazer** [comment]
It has been a while since I looked at the logic but I remember that a lot of it had to do with working with good default assumptions.

**Comment by EnergyArchmage** [comment]
There are two places to make the code change to use tariff(iTariff).kindGasMtr >= kindMeterGas

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EconomicTariff.cc#L4099

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/EconomicTariff.cc#L4298
