### ISSUE TITLE
Simple Glazing system produces negative absorptance at some angles of incidence

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#8000]
Issue overview
--------------
Discovered when running ASHRAE 140 Section 7 tests for both layer-by-layer and simple glazing methods. The simple glazing method under-underestimates the heating benefit of moving to an efficient double-pane lowE window from a single pane window.

This plot shows the hourly solar absorptance for the layer-by-layer "Detailed" model and the "Simple" model.
![Screen Shot 2020-05-18 at 3 31 10 PM](https://user-images.githubusercontent.com/1964570/82261699-c3b87080-991c-11ea-9af5-767f1b7d0216.png)

The formulation of the reflectance curves for the simple glazing method are independent of the transmittance curves and, as a result, the combined transmittance + reflectance can be greater than 1.0 (making absorptance less than zero). The solution will reformulate the reflectance curve data into the same formulation that is used for the [coated glass angular properties](https://bigladdersoftware.com/epx/docs/9-3/engineering-reference/window-calculation-module.html#angular-properties-for-coated-glass). This can be done algebraically using the original reflectance coefficients for curves A-J. I will also add a final energy balance check to enforce a lower limit on absorptance.

This will also require documentation changes/fixes.

Defect file: [L130AC.idf](https://github.com/NREL/EnergyPlus/files/4668616/L130AC.txt)

**Comment by EnergyArchmage** [comment]
can you post a defect idf that shows the negative absorptance.
