### ISSUE TITLE
Envelope Summary report should include additional Interior sections

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#8007]
Issue overview
--------------
The Envelope Summary output report currently includes the following sections:
- Opaque Exterior
- Exterior Fenestration
- Interior Fenestration
- Exterior Door

In residential buildings, it's common to have interior opaque surfaces (e.g., attic floors, basement ceilings, walls between conditioned space and garage) through which the heat transfer is just as important as exterior opaque surfaces. It is currently not possible to view properties for these surfaces in the output.

To address this, I suggest adding two additional sections:
- Opaque Interior
- Interior Door

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
@mjwitte @Myoldmopar Any objection to us making these changes? Seems like a small enough change that a NFP is not required?

**Comment by Myoldmopar** [comment]
I don't have any problem with you doing it, and I guess it's small enough to skip a major NFP process, but I would still open a discussion on Slack at least so that you can get feedback and identify any gotchas that could bite you while doing it.

**Comment by mjwitte** [comment]
I don't see any problem with this. @JasonGlazer

**Comment by Nigusse** [comment]
While reviewing the changes for this new feature (#8152) I saw the output summary tables headings for exterior and interior Fenestration are different. But the headings for opaque surfaces and doors interior and exterior headings are identical. See the sample fenestration summary table headings for exterior and interior. The red color highlighted headings in the exterior fenestration don't exist in the interior fenestration summary table, and one of the headings highlighted with green color that exists in both tables is named differently although it represents the same information.  If there is good reason in keeping them different, then it is fine but wanted to bring my observation to your attention. @Myoldmopar @mjwitte @shorowit @yzhou601 

![Fenestration_tableHeadingDifference](https://user-images.githubusercontent.com/5805126/90276311-b3d3fe00-de31-11ea-972b-1319d5ac9ca5.png)

**Comment by JasonGlazer** [comment]
@Nigusse I think the two tables could be made the same. For "area of multiplied openings" vs "area of openings", I kind of like "area of openings" better. It might make sense to add "multiplier" as another column either way.
