### ISSUE TITLE
Windows CI Warnings/Messages

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#8012]
I recently made a modification to CI's parser of msvc messages, and a chunk of new messages started appearing.  I thought about going back in and revising the parser to eliminate these but I think they may be valid.  It is possible that some of these are being parsed incorrectly, but I'll just lay them out as CI is reporting them.  The messages include:

A few C4267 warnings, that appear to be isolated to ConvertInputFormat and Penumbra, but really it's the code they are importing, not the program themselves.

```
warning | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\numeric(24,1):0:0 | C4267 with [C:\ci\runs\clone_branch\build\src\ConvertInputFormat\ConvertInputFormat.vcxproj]
warning | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\numeric(24,1):0:0 | C4267 _Ty=unsigned long [C:\ci\runs\clone_branch\build\src\ConvertInputFormat\ConvertInputFormat.vcxproj]
warning | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\numeric(24,1):0:0 | C4267 [ [C:\ci\runs\clone_branch\build\src\ConvertInputFormat\ConvertInputFormat.vcxproj]
warning | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\numeric(24,1):0:0 | C4267 ] [C:\ci\runs\clone_branch\build\src\ConvertInputFormat\ConvertInputFormat.vcxproj]
warning | C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.21.27702\include\numeric(24,1):0:0 | C4267 '=': conversion from 'size_t' to '_Ty', possible loss of data [C:\ci\runs\clone_branch\build\src\ConvertInputFormat\ConvertInputFormat.vcxproj]
warning | C:\ci\runs\clone_branch\third_party\penumbra\vendor\libtess2\Source\bucketalloc.c(66,67):0:0 | C4267 'function': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\ci\runs\clone_branch\build\third_party\penumbra\vendor\tess2.vcxproj]
```

These should be addressed, or explained away and muted.  @mbadams5 @nealkruis 

Then there are a few messages that are categorized as CMake Messages:

```
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\ConvertESOMTR_build.vcxproj]
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\CalcSoilSurfTemp_build.vcxproj]
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\Basement_build.vcxproj]
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\Transition_build.vcxproj]
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\ExpandObjects_build.vcxproj]
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\HVAC-Diagram_build.vcxproj]
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\ParametricPreprocessor_build.vcxproj]
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\ReadVars_build.vcxproj]
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\Slab_build.vcxproj]
CMake | CUSTOMBUILD:0:0 | warning [C:\ci\runs\clone_branch\build\AppGPostProcess_build.vcxproj]
```

The CI parser isn't able to parse any more detailed information about these, but I noticed that they are all Fortran builds.  And almost all our Fortran CMakeLists are identical in nature.  Running one locally reveals some warnings:

```
CMake Warning (dev) at CMakeLists.txt:38 (if):
  if given arguments:

    "NOT" "TRUE"

  An argument named "TRUE" appears in a conditional statement.  Policy
  CMP0012 is not set: if() recognizes numbers and boolean constants.  Run
  "cmake --help-policy CMP0012" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.13)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.
```

The first message there is because we have lines like: `set(STATIC_EXE TRUE)`, then later we have `if(NOT ${STATIC_EXE})`, and CMake is warning that this could be confusing behavior.  The second is simple - we don't have a minimum CMake version specified.  Both of these can be addressed easily: @Myoldmopar 

Then finally we have what looks like just two "Command Messages":

```
Command | cl:0:0 | line overriding '/W1' with '/w'
Command | cl:0:0 | line overriding '/W3' with '/w'
```

These messages are actually popping up a bunch of times, and they are related to the builds of some of our third party tools, namely:

- delight
- fmi
- bcvtb
- expat
- miniziplib

In the CMake files for each of these, there is a block with: `IF( MSVC )  ADD_DEFINITIONS( "/w" )`.  This overrides what was already specified for the warning level, and so MSVC complains.  In theory, this is easy enough to get rid of, just disable the warning override.  But I'm guessing that will start throwing a ton of warning messages for these tools, since they were probably silenced to hush them up.  These come out in the build output as: `cl : Command line warning D9025: overriding '/W3' with '/w'`, and I may end up just silencing messages if they specifically include "D9025" and "/w".  I'll investigate that and see what we can do.  It's funny how the effort to silence warnings also throws a warning.

**Comment by nealkruis** [comment]
@Myoldmopar do you want me to tackle all of these in the same PR? or did you want to take a crack at the CMake and compiler flag warnings?

**Comment by nealkruis** [comment]
Relevant discussion related to D9025 for future versions of CMake: https://gitlab.kitware.com/cmake/cmake/-/issues/19084

In the end, I decided just to remove the override and resolve the previously silenced warnings.
