### ISSUE TITLE
Addition of Surface Temperature Controls for Variable Flow Low Temperature Radiant Systems

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#8020]
Requests from the OpenStudio team and researchers at the Center for the Built Environment (CBE) at the University of California Berkeley have included several enhancement to the low temperature radiant system models.  This is the first of a series of issues that address some of those concerns.

The work here includes adding two types of surface control to variable flow low temperature radiant systems: surface temperature control and interior slab temperature control.  For surface temperature control, the radiant system would be controlled to achieve a particular temperature at the surface of the system that faces the rest of the zone.  For interior slab temperature control, the radiant system would be controlled to achieve a particular temperature at an interior point within the slab.

In addition, the existing code for low temperature radiant systems is in need of some refactoring to improve its level of OO and make additional work in this area more efficient.  So, as the work is done on the new controls, work should also be done laying the groundwork for upcoming enhancements by refactoring to some extent.

### Details
Some additional details for this issue (if relevant):
 - Platform: all
 - Version of EnergyPlus: current
 - Unmethours link or helpdesk ticket number: there's probably something there but the communications I've had with the CBE are probably better references.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Defect file added: not a defect--new IDF will be added
 - [X] Ticket added to Pivotal for defect (development team task)
 - [X] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
This was addressed by #8016
