### ISSUE TITLE
Simple Glazing system produces fatal error when using maximum U-factor for CZ1 in 90.1-2004

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#8034]
Issue overview
--------------
ASHRAE 90.1-2004 defines a maximum U-factor of 1.22 U-IP. This is a physically impossible U-factor given the limiting case of air-film resistances (~1.03 U-IP) but, regardless, it is the stated basis for the Appendix G baseline.

The proposed fix would remove the maximum value from the IDD and instead throw a (loud?) warning that the U-factor will be automatically reduced to the maximum physically possible value. This way, users attempting to model the 90.1-2004 baseline in CZ1 won't have to work around the problematic value defined in that standard.

**Comment by mjwitte** [comment]
There's an existing issue somewhere related to this. https://github.com/NREL/EnergyPlus/issues/4643 was closed in a cleanup pass and marked as `WontFix`.

**Comment by JasonGlazer** [comment]
The highest is 1.22 according to the standard. Are you using the air-film resistances from NFRC?

**Comment by nealkruis** [comment]
Thanks, @JasonGlazer. I updated the description to match. I also added the maximum U-IP value in the algorithm.

The air-film resistances for the simple glazing model are defined [here](https://bigladdersoftware.com/epx/docs/9-3/engineering-reference/window-calculation-module.html#step-1.-determine-glass-to-glass-resistance.) and are based on an approximated fit to NFRC calculations.

Here's the original fit:

![Screen Shot 2020-06-03 at 11 06 19 AM](https://user-images.githubusercontent.com/1964570/83666513-4894c280-a58a-11ea-8fc4-73711b0aa2b3.png)

**Comment by nealkruis** [comment]
Adding @EnergyArchmage, too, in case he has input on this.

I will point out that higher U-factors are technically possible, but would effectively require fin-like structures on the frame to enhance the conductance of the frame beyond an infinitely thin sheet of aluminum (probably not a case we need to accommodate).
