### ISSUE TITLE
Implementation of On-Off Control for Variable Flow and Electric Radiant Systems

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#8044]
Issue overview
--------------
In the variable flow and electric low temperature radiant systems, the throttling range that impacts when the systems turn on and at what fraction they run is not allowed to be less than 0.5C.  However, some systems in practice actually operate in an on-off manner with no throttling range.  If the system is required for heating in the electric system or heating or cooling in the variable flow system, there are applications that simply turn on at full power or flow and then turn off when the setpoint temperature is met.  The implementation of this requires the relaxing of the requirement for a 0.5C minimum flow rate so that a 0.0C throttling range is allowed and the changing of algorithm logic to avoid divide by zero errors when the user does select a 0.0C throttling range.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): current
 - Unmethours link or helpdesk ticket number: none but documented request from the Center for the Built Environment (CBE) at the University of California Berkeley

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Defect file added (list location of defect file here): none needed as this is not a defect
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #8113
