### ISSUE TITLE
Windows CI issues size_t to unsigned int conversion warning in libtess2

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#8053]
Issue overview
--------------
Windows CI gives this warning:

`C4267 'function': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\ci\runs\clone_branch\build\third_party\penumbra\vendor\tess2.vcxproj]`

**Comment by Myoldmopar** [comment]
It's also listed in here: https://github.com/NREL/EnergyPlus/issues/8012, but pulling this into a standalone issue makes sense.
