### ISSUE TITLE
Coil:Cooling:DX:CurveFit:OperatingMode: Nominal Evaporative Condenser Pump Power is marked autosizabled, but not autosized

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#8066]
Issue overview
--------------

Implementing this object in OpenStudio, I was checking the SQL file to find the entry for `Nominal Evaporative Condenser Pump Power` but couldn't find it.

From the IDD:

```
Coil:Cooling:DX:CurveFit:OperatingMode,
  [...]
   N8, \field Nominal Evaporative Condenser Pump Power
       \note Rated power consumed by the evaporative condenser's water pump
       \type real
       \units W
       \minimum 0.0
       \default 0.0
       \autosizable
```

Yet, `CoilCoolingDXCurveFitOperatingMode::size` does not autosize this one, but correctly autosizes the other 3 autosizable fields this object has:

https://github.com/NREL/EnergyPlus/blob/431d52730f3c519476342ed7f5c9f9c7c35818d5/src/EnergyPlus/Coils/CoilCoolingDXCurveFitOperatingMode.cc#L152-L192

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): E+ 9.4 in progress, at 431d52730f3c519476342ed7f5c9f9c7c35818d5
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Additionally, the other three don't have any units in the SQL output.

![image](https://user-images.githubusercontent.com/5479063/91417876-b54def00-e851-11ea-85a9-e628a0a23062.png)

That's an easy fix.

**Comment by mjwitte** [comment]
@jmarrec There are some pending changes to Coil:Cooling:DX in #8204 but I don't see the evap condenser pump power sizing there.
