### ISSUE TITLE
Report correct total heat gain or loss to ensure energy conservation for Zone Infiltration objects

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#8068]
Issue overview
--------------
The total heat gain or loss reported from Zone Infiltration objects is a sum of sensible and latent heat gain or loss. The sensible heat is calculated using CpAir, and the latent heat is calculated using hg. Due to incorrect argument to calculate CpAir or hg, the total heat is not equal to the enthalpy difference between indoor and outdoor conditions.

"Use correct argument to calculate hg in AirflowNetwork" (https://github.com/NREL/EnergyPlus/pull/7916) uses correct argument to calculate hg to ensure energy conservation to make reported sum of sensible and latent load equal to the enthalpy difference between 2 points. The same approach should be used to report sensible, latent, and total for Zone Infiltration objects.
   
### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Closed via #8075
