### ISSUE TITLE
compiling energyplus with c++14

### ISSUE THREAD

**Issue by xcosmos6** [NREL/EnergyPlus#8103]
Issue overview
--------------
I am trying to add HELICS as an external interface into energyplus.

### Details
I added helics header files in the externalinterface.cc file and tried to build energyplus with HELICS. The helics header file would reference some third party library where single quotes are used as number separators thus require c++14 to compile. However, when I use c++14, there would be error in energyplus so the build process stops. I am wondering if there's a way to build energyplus with c++14.

I also opened an issue here [issue#1440](https://github.com/GMLC-TDC/HELICS/issues/1440#issue-644197682)

Thank you very much!

**Comment by jmarrec** [comment]
Closed by #8355 which enables C++17
