### ISSUE TITLE
Coal fuel type not available in Coil:Heating:Fuel

### ISSUE THREAD

**Issue by yzhou601** [NREL/EnergyPlus#8110]
Issue overview
--------------
E+’s `Coil:Heating:Fuel` object doesn’t support `Coal` fuel type for some reason. But some other objects with fuel type options do. From the Energy+.idd:

OtherEquipment | Coil:Heating:Fuel | Boiler:HotWater | WaterHeater:Tank
-- | -- | -- | --
\key NaturalGas | \key NaturalGas | \key NaturalGas | \key NaturalGas
\key Propane | \key Propane | \key Propane | \key Propane
\key FuelOilNo1 | \key FuelOilNo1 | \key FuelOilNo1 | \key FuelOilNo1
\key FuelOilNo2 | \key FuelOilNo2 | \key FuelOilNo2 | \key FuelOilNo2
\key Diesel | \key Diesel | \key Diesel | \key Diesel
\key Gasoline | \key Gasoline | \key Gasoline | \key Gasoline
\key Coal |   | \key Coal | \key Coal
\key OtherFuel1 | \key OtherFuel1 | \key OtherFuel1 | \key OtherFuel1
\key OtherFuel2 | \key OtherFuel2 | \key OtherFuel2 | \key OtherFuel2

Is there any specific reason that coal is excluded in `Coil:Heating:Fuel` object? [source code](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HeatingCoils.cc#L670-L677) and idd is limiting its use, while the [docs](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex#L1244), is inconsistently specifying coal as a valid option. 
Can we add `Coal` as a valid option?

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows, 10)
 - Version of EnergyPlus (9.3.0)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
At the time this was converted from Coil:Heating:Gas to Coil:Heating:Fuel, coal was probably excluded, because it's hard to envision an actual piece of equipment like this. But I don't see a problem allowing it here, even though it may never be used that way.
