### ISSUE TITLE
 **ModuleNotFoundError: No module named 'pyenergyplus'**

### ISSUE THREAD

**Issue by nvskumar-m** [NREL/EnergyPlus#8125]
Issue overview
--------------
I have seen the EnergyPlus API and tried to use it. But on run, the runtime API is requesting for "**pyenergyplus**" library that is not available with pip or conda.

### Details
I have installed EnergyPlus v9.3 after reading the documentation about the EnergyPlus Python API from https://nrel.github.io/EnergyPlus/api/python/api.html

I tried to run a sample IDF file from python using API libraries provided in "C:\EnergyPlusV9-3-0\pyenergyplus" folder.

However, the python started to warn with following error
 **ModuleNotFoundError: No module named 'pyenergyplus'**

 I couldnt find the module online and installed **energyplus** module from "**https://pypi.org/project/energyplus/**"

There was no use and still the issue of  **ModuleNotFoundError: No module named 'pyenergyplus'** exists

**Comment by bonnema** [comment]
@nvskumar-m, can you try the following?

1. Copy PythonPluginUserDefined5ZoneAirCooled.idf and PythonPluginUserDefined5ZoneAirCooled.py from the EnergyPlus example files to a temporary directory
2. Execute the following (adapt for your operating system):

`C:\Users\ebonnema\tmp>C:\EnergyPlusV9-3-0\energyplus.exe -w C:\EnergyPlusV9-3-0\WeatherData\USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw PythonPluginUserDefined5ZoneAirCooled.idf`

I was able to run this successfully. Note: `C:\Users\ebonnema\tmp>C:\EnergyPlusV9-3-0\energyplus.exe --version` returns `EnergyPlus, Version 9.3.0-baff08990c`

**Comment by Myoldmopar** [comment]
@nvskumar-m it sounds like you just need to put the E+ install directory on your PATH.  In your Python script just:

```
import sys
sys.path.insert(0, '/path/to/eplus/install')
```

Then when you run the script it will be able to find `pyenergyplus` inside that directory that was just added to PATH.  I guess theoretically you could also just add the E+ install to your system PATH but that seems excessive.

**Comment by nvskumar-m** [comment]
> @nvskumar-m, can you try the following?
> 
> 1. Copy PythonPluginUserDefined5ZoneAirCooled.idf and PythonPluginUserDefined5ZoneAirCooled.py from the EnergyPlus example files to a temporary directory
> 2. Execute the following (adapt for your operating system):
> 
> `C:\Users\ebonnema\tmp>C:\EnergyPlusV9-3-0\energyplus.exe -w C:\EnergyPlusV9-3-0\WeatherData\USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw PythonPluginUserDefined5ZoneAirCooled.idf`
> 
> I was able to run this successfully. Note: `C:\Users\ebonnema\tmp>C:\EnergyPlusV9-3-0\energyplus.exe --version` returns `EnergyPlus, Version 9.3.0-baff08990c`

Still error occurs
![image](https://user-images.githubusercontent.com/54622340/86260805-6716c980-bbdb-11ea-802b-66cb0c531f77.png)

**Comment by Myoldmopar** [comment]
There are two ways to utilize Python with EnergyPlus:
- Running an EnergyPlus input file (IDF) and declaring a Python Plugin instance in that IDF, which will pair it with an existing Python Plugin class file (Normal mode)
- Calling EnergyPlus from an external python script (Library mode)

The PythonPlugin*.py files that exist in the EnergyPlus ExampleFiles directory are not to be run standalone.  Those are plugin classes that are called by EnergyPlus at runtime when they are declared in the IDF.  The workflow is to run EnergyPlus.exe on the PythonPlugin IDF file of your choice.  If you look inside that file you will see a `PythonPlugin:Instance` declared which tells EnergyPlus to go out and import the matching Python plugin file.  

If you want to call the API in library mode, you just create a simple python script and run Python on it, making sure to tell Python where to find the `pyenergyplus` package.  This package is **not** distributed on PyPi or any other means.  It is included with the EnergyPlus installation.  Just try:

```
import sys
sys.path.insert(0, '/path/to/eplus/install')
from pyenergyplus import api
```

If that alone works, then it means your standalone Python script can access EnergyPlus and you can start having fun with the API.

**Comment by nvskumar-m** [comment]
> ```
> import sys
> sys.path.insert(0, '/path/to/eplus/install')
> ```

Thanks @Myoldmopar, there has been no error raised when  **sys.path.insert(0, '/path/to/eplus/install')** has been scripted in code.

**Comment by Myoldmopar** [comment]
1. Do you understand that I don't actually mean use the path `'/path/to/eplus/install'`?  That's just a placeholder for wherever you installed EnergyPlus.
2. That code alone won't do anything, you need to exercise it by then trying to find the `pyenergyplus` package: `from pyenergyplus import api`

**Comment by nvskumar-m** [comment]
> 1. Do you understand that I don't actually mean use the path `'/path/to/eplus/install'`?  That's just a placeholder for wherever you installed EnergyPlus.
> 2. That code alone won't do anything, you need to exercise it by then trying to find the `pyenergyplus` package: `from pyenergyplus import api`

1. Ya I replaced the string **/path/to/eplus/install** with the EnergyPlus installation folder **'C:\EnergyPlusV9-3-0'**
2. When you have suggested the solution, I understood that pyenergyplus is the directory but not the library

**Comment by Myoldmopar** [comment]
OK, good.  Yes, `pyenergyplus` is both a directory in the E+ install, but also includes a `__init__.py` file, making it also a Python package, or library.  As long as your Python interpreter can find it then it should be able to import it.  Can you confirm that the `from pyenergyplus import api` works once you add the install directory to the `sys.path`?

**Comment by nvskumar-m** [comment]
> OK, good. Yes, `pyenergyplus` is both a directory in the E+ install, but also includes a `__init__.py` file, making it also a Python package, or library. As long as your Python interpreter can find it then it should be able to import it. Can you confirm that the `from pyenergyplus import api` works once you add the install directory to the `sys.path`?

Following is the result on loading pyenergyplus api
**runfile('C:/Users/naga/Desktop/CESS/_testing_PythonPlugin/sourceCode/EPpythonPlugIn/01__runV1.py', wdir='C:/Users/naga/Desktop/CESS/_testing_PythonPlugin/sourceCode/EPpythonPlugIn')
Reloaded modules: pyenergyplus, pyenergyplus.api, pyenergyplus.func, pyenergyplus.common, pyenergyplus.datatransfer, pyenergyplus.runtime**

yes, added path to environment variables directly
![image](https://user-images.githubusercontent.com/54622340/86263957-8152a680-bbdf-11ea-976f-3282fedf0f75.png)

**Comment by Myoldmopar** [comment]
OK, let's back up again.  Your directory structure implies you are trying to test the PythonPlugin system out.  In that case you shouldn't be executing a Python file, you should be executing EnergyPlus and letting it do all the hard work for you.

Running as python plugin:
- Create an IDF file with building information and a PythonPlugin:Instance IDF object
- Create a paired Python plugin class that interacts with EnergyPlus at runtime.  This Python script has a line at the top that says `from pyenergyplus.plugin import EnergyPlusPlugin`, and you don't have to worry about paths at all.
- Run energyplus.exe on that IDF file, and let EnergyPlus go out and do all the Python stuff and call your script as needed during the run

This is the more likely path to take for people who are transitioning from a normal EnergyPlus workflow.

Running as library:
- Create a standalone Python script that starts with inserting the E+ install root into the `sys.path`, and then `from pyenergyplus import api`, then uses the EnergyPlus API to do fun stuff
- Run Python.exe on that Python script and it will do the magic

This is a more exotic path to take for people who want to take more control of a running simulation.

You need to decide/clarify which way you want to go before continuing.

Also, that environment variable is not correct.  You don't need an environment variable *named* pyenergyplus.  You should be appending it to the PATH, and It should be just `C:\EnergyPlusV9-3-0`.  But you don't need to do that anyway, as long as you insert it into sys.path inside your Python script.

**Comment by nvskumar-m** [comment]
> OK, let's back up again. Your directory structure implies you are trying to test the PythonPlugin system out. In that case you shouldn't be executing a Python file, you should be executing EnergyPlus and letting it do all the hard work for you.
> 
> Running as python plugin:
> 
> * Create an IDF file with building information and a PythonPlugin:Instance IDF object
> * Create a paired Python plugin class that interacts with EnergyPlus at runtime.  This Python script has a line at the top that says `from pyenergyplus.plugin import EnergyPlusPlugin`, and you don't have to worry about paths at all.
> * Run energyplus.exe on that IDF file, and let EnergyPlus go out and do all the Python stuff and call your script as needed during the run
> 
> This is the more likely path to take for people who are transitioning from a normal EnergyPlus workflow.
> 
> Running as library:
> 
> * Create a standalone Python script that starts with inserting the E+ install root into the `sys.path`, and then `from pyenergyplus import api`, then uses the EnergyPlus API to do fun stuff
> * Run Python.exe on that Python script and it will do the magic
> 
> This is a more exotic path to take for people who want to take more control of a running simulation.
> 
> You need to decide/clarify which way you want to go before continuing.
> 
> Also, that environment variable is not correct. You don't need an environment variable _named_ pyenergyplus. You should be appending it to the PATH, and It should be just `C:\EnergyPlusV9-3-0`. But you don't need to do that anyway, as long as you insert it into sys.path inside your Python script.

Thank you soo much @Myoldmopar. 
Although its a bit tricky to me at this stage, I will learn by resolving the errors I commit at each step of self-learning and help from you and others in this community. 
I have learned EMS of EP through examples stated in application guide. It would be great to have such knowledge product even for Python Plugin.

**Comment by Myoldmopar** [comment]
You are welcome @nvskumar-m, this is a brand new feature of EnergyPlus, and there could be corner cases to resolve, but I am hopeful you will be good to go.  If you have learned EMS then I think you are better suited for the Python Plugin method of running, where everything still centers around the EnergyPlus.exe and the IDF file, and then the Python plugin is simply a python file that tags along for the ride :+1:

**Comment by nvskumar-m** [comment]
@Myoldmopar Thank you for motivational words. Last week I understood how to develop Python functions for IDF from example files provided. 

This week I want to script and test on a sample five-zone model. 

But the road block I am facing is to get actuator control type details for component types of EnergyPlus. On web search, I found the details are listed in EDD file similar to RDD file for variables.

I searched a lot in EnergyPlus folder as well as in web to get the file for reference. 

Can you pls provide me a way forward to avail the EDD file or any other reference to get the list of actuators along with control type details specified for each component?

**Comment by bonnema** [comment]
@nvskumar-m, Section 2.6 in https://energyplus.net/sites/all/modules/custom/nrel_custom/pdfs/pdfs_v9.3.0/OutputDetailsAndExamples.pdf is a good reference. The general mapping would be:

EDD:
`EnergyManagementSystem:Actuator Available, Actuated Component Unique Name,Actuated Component Type,Actuated Component Control Type,[units]`

_Traditional EMS:_
`EnergyManagementSystem:Actuator,`
`Name,`
`Actuated Component Unique Name,`
`Actuated Component Type,`
`Actuated Component Control Type;`

_Python EMS:_
`self.data['name'] = self.api.exchange.get_actuator_handle("Actuated Component Type", "Actuated Component Control Type", "Actuated Component Unique Name")`
`self.api.exchange.set_actuator_value(self.data['name'], value)`

An example (from EMSCustomSchedule.idf and PythonPluginCustomSchedule.idf/.py in the E+ example files) is:

_EDD:_
`EnergyManagementSystem:Actuator Available, HTGSETP_SCH,Schedule:Constant,Schedule Value,[ ]`

_Traditional EMS:_
`EnergyManagementSystem:Actuator,`
`myHTGSETP_SCH,`
`HTGSETP_SCH,`
`Schedule:Constant,`
`Schedule Value;`

_Python EMS:_
`self.data['actuator_heating'] = self.api.exchange.get_actuator_handle("Schedule:Constant", "Schedule Value", "HTGSETP_SCH")`
`self.api.exchange.set_actuator_value(self.data['actuator_heating'], value)`

**Comment by nvskumar-m** [comment]
> @nvskumar-m, Section 2.6 in https://energyplus.net/sites/all/modules/custom/nrel_custom/pdfs/pdfs_v9.3.0/OutputDetailsAndExamples.pdf is a good reference. The general mapping would be:
> 
> EDD:
> `EnergyManagementSystem:Actuator Available, Actuated Component Unique Name,Actuated Component Type,Actuated Component Control Type,[units]`
> 
> _Traditional EMS:_
> `EnergyManagementSystem:Actuator,`
> `Name,`
> `Actuated Component Unique Name,`
> `Actuated Component Type,`
> `Actuated Component Control Type;`
> 
> _Python EMS:_
> `self.data['name'] = self.api.exchange.get_actuator_handle("Actuated Component Type", "Actuated Component Control Type", "Actuated Component Unique Name")`
> `self.api.exchange.set_actuator_value(self.data['name'], value)`
> 
> An example (from EMSCustomSchedule.idf and PythonPluginCustomSchedule.idf/.py in the E+ example files) is:
> 
> _EDD:_
> `EnergyManagementSystem:Actuator Available, HTGSETP_SCH,Schedule:Constant,Schedule Value,[ ]`
> 
> _Traditional EMS:_
> `EnergyManagementSystem:Actuator,`
> `myHTGSETP_SCH,`
> `HTGSETP_SCH,`
> `Schedule:Constant,`
> `Schedule Value;`
> 
> _Python EMS:_
> `self.data['actuator_heating'] = self.api.exchange.get_actuator_handle("Schedule:Constant", "Schedule Value", "HTGSETP_SCH")`
> `self.api.exchange.set_actuator_value(self.data['actuator_heating'], value)`

@bonnema Thank you, You made my life easy by providing me the method to extract EDD file.
Now I will be able to create custom EP Python Plugin.

Once again, Thank you soo much :)

**Comment by nvskumar-m** [comment]
@Myoldmopar @bonnema 
I have scripted custom Python Module. At first although it denied the file existence even when it is placed in the same folder of idf, the python file could be recognised after declaring the search path. 

However, severe error erupted denying the class name provided in idf for the module created. At first I though its my coding issue. But when I checked with example file 'PythonPluginWindowShadeControl', the same error popped up. 
![image](https://user-images.githubusercontent.com/54622340/86781345-62d72a00-c07b-11ea-88e7-52ca3a4a34e0.png)

**Comment by Myoldmopar** [comment]
As for finding the python file, you can control where the IDF is found by either declaring a custom search path, or by switching on and off the other settings in the PythonPlugin:SearchPaths object, including whether the engine should search in the current working directory, or the directory of the IDF.

Can you clarify how you are running EnergyPlus?  Some engines may move files around when setting up a run and so run folders may be getting mixed up.

**Comment by nvskumar-m** [comment]
> As for finding the python file, you can control where the IDF is found by either declaring a custom search path, or by switching on and off the other settings in the PythonPlugin:SearchPaths object, including whether the engine should search in the current working directory, or the directory of the IDF.
> 
> Can you clarify how you are running EnergyPlus? Some engines may move files around when setting up a run and so run folders may be getting mixed up.

@Myoldmopar  I am running simulation using EP Launch.

**Comment by Myoldmopar** [comment]
Can you try running it from the command line?  The very easiest way would be to copy the IDF and Python file right in the same folder as the EnergyPlus.exe file.  The PythonPlugin:SearchPaths object should not be needed for this quick test so you could delete the object from this copied IDF.  Then just open a command prompt and `cd` into that directory, then run `energyplus.exe yourIDFName.idf`.  I would try this by copying the window shade control IDF and Python file since we know that file and plugin do work.

**Comment by nvskumar-m** [comment]
The example file worked by my file got error in EnergyPlus.exe comprising folder

![image](https://user-images.githubusercontent.com/54622340/86788046-5ce54700-c083-11ea-940a-264755b0ab9a.png)

**Comment by bonnema** [comment]
@nvskumar-m what does the error file (eplusout.err) say?

**Comment by nvskumar-m** [comment]
No it is some internal issue. The Python plugin was taken

![image](https://user-images.githubusercontent.com/54622340/86788417-c5342880-c083-11ea-941c-c1686005103d.png)

**Comment by Myoldmopar** [comment]
Oh, you have HVACTemplate objects in your IDF.  So to run it manually, you'd need to run ExpandObjects first, then run EnergyPlus on the resulting expanded.idf file.  It never got to the PythonPlugin processing part.

**Comment by jmarrec** [comment]
`energyplus.exe -x PythonPluginWindowShadeControl.idf` should run the ExpandObjects for you.

```
(py38)julien@8084 (master *+%=)$ energyplus --help
EnergyPlus, Version 9.3.0-baff08990c
PythonLinkage: Linked to Python Version: "3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]"
Usage: energyplus [options] [input-file]
Options:
  -a, --annual                 Force annual simulation
  -c, --convert                Output IDF->epJSON or epJSON->IDF, dependent on
                               input file type
  -D, --design-day             Force design-day-only simulation
  -d, --output-directory ARG   Output directory path (default: current
                               directory)
  -h, --help                   Display help information
  -i, --idd ARG                Input data dictionary path (default: Energy+.idd
                               in executable directory)
  -m, --epmacro                Run EPMacro prior to simulation
  -p, --output-prefix ARG      Prefix for output file names (default: eplus)
  -r, --readvars               Run ReadVarsESO after simulation
  -s, --output-suffix ARG      Suffix style for output file names (default: L)
                                  L: Legacy (e.g., eplustbl.csv)
                                  C: Capital (e.g., eplusTable.csv)
                                  D: Dash (e.g., eplus-table.csv)
  -v, --version                Display version information
  -w, --weather ARG            Weather file path (default: in.epw in current
                               directory)
  -x, --expandobjects          Run ExpandObjects prior to simulation
--convert-only                 Only convert IDF->epJSON or epJSON->IDF,
                               dependent on input file type. No simulation
Example: energyplus -w weather.epw -r input.idf
```

**Comment by nvskumar-m** [comment]
> Oh, you have HVACTemplate objects in your IDF. So to run it manually, you'd need to run ExpandObjects first, then run EnergyPlus on the resulting expanded.idf file. It never got to the PythonPlugin processing part.

Even the example file has also not ran outside C:\EnergyPlusV9-3-0 folder.
For my file I understood the expanded IDF objects issue and @Julien Marrec thank you for the tip. Im trying to re-execute now

**Comment by nvskumar-m** [comment]
> Oh, you have HVACTemplate objects in your IDF. So to run it manually, you'd need to run ExpandObjects first, then run EnergyPlus on the resulting expanded.idf file. It never got to the PythonPlugin processing part.

@Myoldmopar even my file ran when i placed in C:\EnergyPlusV9-3-0 folder and after adding -x in the cmd line. 

It throwed error related to weather file which I have not provided in cmd line
![image](https://user-images.githubusercontent.com/54622340/86790547-2fe66380-c086-11ea-87c7-571591250313.png)

![image](https://user-images.githubusercontent.com/54622340/86790594-3b398f00-c086-11ea-8a04-89f458f44770.png)

**Comment by jmarrec** [comment]
provide the weather file... I suggest you read the command line help by typing `energyplus --help` (or read my message above).


`energyplus.exe -x -w /path/to/weatherfile.epw PythonPluginWindowShadeControl.idf`

**Comment by nvskumar-m** [comment]
> provide the weather file... I suggest you read the command line help by typing `energyplus --help` (or read my message above).
> 
> `energyplus.exe -x -w /path/to/weatherfile.epw PythonPluginWindowShadeControl.idf`

yes, it worked. I ran my file in C:\EnergyPlusV9-3-0 by using cmd  "energyplus.exe -w SRINAGAR_2014.epw -x testCase1_V930_EMS.idf"

![image](https://user-images.githubusercontent.com/54622340/86791692-6cff2580-c087-11ea-803f-9b3260e585f6.png)

**Comment by nvskumar-m** [comment]
@Myoldmopar We got the solution. To run the Python Plugin outside the source folder **C:\EnergyPlusV9-3-0**, we need to add **C:\EnergyPlusV9-3-0** in the PythonPlugin:SearchPaths like I tested below and ran successfully
![image](https://user-images.githubusercontent.com/54622340/86792685-586f5d00-c088-11ea-8c40-a1c8c5d10874.png)

**Comment by Myoldmopar** [comment]
Did you end up copying any of your Python files into the `C:\EnergyPlusV9-3-0` folder?  If so then it could be working just _by chance_.  That root folder should **always** be added to the search path automatically.  I'm going to leave this issue open for now and please keep up posted if you run into any further issues.

**Comment by nvskumar-m** [comment]
@Myoldmopar, I have searched my  **C:\EnergyPlusV9-3-0** directory for custom python plugin files remained which might be helping IDF run outside the EP source directory. But they aren't any. 

One more thing that I could observe is that after I adding  **C:\EnergyPlusV9-3-0** directory in IDF PythonPlugin:SearchPaths, the need for command line **sys.path.insert(0, '/path/to/eplus/install')** disappeared. The python plugin file is able to locate the **pyenergyplus** directory automatically.

Yesterday, I validated the results of IDF integrated with Python file and they are inline with actual results 
![image](https://user-images.githubusercontent.com/54622340/86881636-623aa400-c10c-11ea-828c-cc32a148cade.png)

Thank you soo much all for helping me to learn this new feature.

**Comment by Myoldmopar** [comment]
That is really great to hear it is all working!

The `sys.path.insert` stuff was really only needed back when I thought you were running this as a library.  Once you were running it as a plugin, it was not necessary.  However, I'm still not sure why you needed to add the install directory to the search path.  It's a minor workaround, of course, but that is already added to the python search path when EnergyPlus starts up.

In any case, have fun with this new feature!

**Comment by Myoldmopar** [comment]
And if you feel like everything is satisfied, you are welcome to close this issue.
