### ISSUE TITLE
Transition truncating long field values

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#8131]
When transitioning a test file that had long field values, the text was truncated.

Using IDFVersionUpdater.

This occurred with EnergyManagementSystem:Program field lines which when using long variable names in the EMS program, is not too surprising that they were longer than transition was built for.

### Details
Some additional details for this issue (if relevant):
 - Win10
 - 9.3.0 bug fix

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (devsupport)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Hmm, are they being truncated in EnergyPlus as well?

**Comment by JasonGlazer** [comment]
I don't see any warning messages about that.
