### ISSUE TITLE
Mismatch between fuel type enumeration in the code and idd for fuel type "FuelOilNo*"

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#8132]
Issue overview
--------------
There is mismatch between fuel type enumeration in the code and idd for fuel type  *FuelOilNo1* and *FuelOilNo2* that lead to fatal out. In the idd fuel type key words are defined as *FuelOilNo1* and *FuelOilNo2* where as the code expects "FUELOIL#1" and "FUELOIL#2" [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DataGlobalConstants.cc#L126-L130) and [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/OutputProcessor.cc#L1924-L1928).  I run into this problem when I tried to transition V8.6 idf to the latest. Then I created a defect file and it fatal out when using use FuelOilNo1 or FuelOilNo2 in Meter:Custom object. See error sample below:

```
   ** Severe  ** GetStandardMeterResourceType: Illegal OutResourceType (for Meters) Entered=FUELOILNO2
   **   ~~~   ** ..on Meter:Custom="ENERGYHEATING:FUELOIL_NO1".
   **  Fatal  ** UpdateMeterReporting: Previous Meter Specification errors cause program termination.

```

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus V9.3 and Develop

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
That's all been fixed (well, should be) if you use the transitions that are packaged with v9.3.0. The original old transitions missed this.

**Comment by mjwitte** [comment]
@Nigusse Please confirm here if it works is you use IDFVersionUpdater in v9.3.0 to manage the full transition from 8.6 to 9.3.

**Comment by Nigusse** [comment]
@mjwitte I just created defect file using latest example file from develop and I see the same problem.

**Comment by Nigusse** [comment]
@mjwitte It is not a direct transition problem. The problem I am having is that if I use FuelOilNo1 or FuelOilNo2 as required by the idd the defect file fatal out because the code (as I see it in the code [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DataGlobalConstants.cc#L126-L130)) anticipates *FuelOil#1* or *FuelOil#2*. I do not see any problem with other fuel types.

**Comment by mjwitte** [comment]
What object and field are we talking about?

**Comment by mjwitte** [comment]
Oh, right, meters still expect the old names. If the IDD keys were changed, that's wrong it's too early for that.

**Comment by mjwitte** [comment]
Never mind, looks like I broke that in #7523. Rats! The inputs and idd keys *should* all use the new names. It's time to bite the bullet and move all of the meters and output variables to use the "new" fuel type names. https://github.com/NREL/EnergyPlus/issues/7622

**Comment by Nigusse** [comment]
@mjwitte Sorry I was away from my desk. You have already figured it out. But here is the offending object:


```
  Meter:Custom,
    EnergyHeating:FuelOil_NO1,  !- Name
    !NATURALGAS,             !- Fuel Type
    !OTHERFUEL1,              !- Fuel Type
    !FUELOILNO1,              !- Fuel Type
    FUELOILNO2,               !- Fuel Type
    ,                                   !- Key Name 1
    EnergyUse Reporting_1;   !- Output Variable or Meter Name 1
```

**Comment by MatthewSteen** [comment]
This affects OpenStudio users for EDA utility incentive programs. FYI @asparke2 PAT fails with the `XcelEDATariffSelectionAndModelSetup` measure in v3.0.0+. Workaround is to comment out all LCC code in the measure. Related to...
- https://github.com/NREL/OpenStudio-measures/issues/252
- https://github.com/NREL/OpenStudio-measures/issues/315

![image](https://user-images.githubusercontent.com/8397034/87068193-721cbb80-c1d2-11ea-9b1b-8c944fec1e3c.png)

**Comment by Nigusse** [comment]
@MatthewSteen This issue has been addressed at PR #8134. If you have EnergyPlus defect file please drop it here and I will use to test the fix.

**Comment by MatthewSteen** [comment]
@Nigusse here you go...

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/4899286/in.idf.txt)

**Comment by mjwitte** [comment]
@MatthewSteen I'm reviewing #8134 and used the file attached [above](https://github.com/NREL/EnergyPlus/issues/8132#issuecomment-656329175). That file is using old inputs. If all of the FuelOil#1/2 in the idf are replaced with FuelOilNo1/2 it runs fine with v9.3.0. So, for this case, the problem appears to be with the measures, not with EnergyPlus.

**Comment by mjwitte** [comment]
@MatthewSteen Never mind that last comment, it's half right. 
1. The LifeCycleCost resource type *should* be FuelOilNo1/2 now in v9.3 and will stay that way for v9.4.
2. But the meter names in the Output:Table:Monthly object should still be FuelOil#1/2 in v9.3. Those will be FuelOilNo1/2 in v9.4.  
3. But I also noticed some other meter names in the Output:Table:Monthly object that are not correct (unrelated to this issue). e.g.:
```
Interior Lighting:* --> InteriorLights:*
Exterior Lighting:* --> ExteriorLights:*
Interior Equipment:* --> InteriorEquipment:*
Exterior Equipment:* --> ExteriorEquipment:*
Heat Rejection:* --> HeatRejection:*
Heat Recovery:* --> HeatRecovery:*
Water Systems:* --> WaterSystems:*
```
These end uses are correct in the defect file for the common fuel types like Electricity and Gas, but they are wrong for other fuel types like Propane and Fuel OIl). So whatever part of OpenStudio is writing the Output:Table:Monthly objects by fuel type should get fixed. Maybe at the same time that the other meter names change when #7622 is finished (hopefully for v9.4).
