### ISSUE TITLE
Sizing information not appearing in the EquipmentSummary table

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/EnergyPlus#8146]
Issue overview
--------------
In E+9.3 during a sizing run simulation, sizing fields for some objects are left blank in the EquipmentSummary section.  Attached is an example .idf in E+9.2 and E+9.3 with the html output tables for both. The main issue I'm facing is that with E+9.3 and OpenStudio 3.0, the OS API rated flow rate method for the pumps and rated capacity method for the chiller do no work after the sizing run.  These are necessary for openstudio-standards to determine equipment efficiencies.
[E9_2_vs_E9_3.zip](https://github.com/NREL/EnergyPlus/files/4903978/E9_2_vs_E9_3.zip)

Some previous question on a possibly related issue at #8124 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mdahlhausen** [comment]
@lgu1234 and @mjwitte new issue created for specifically the EquipmentSummary table

As part of the testing, it would be great if someone could test this with the OpenStudio API to confirm that the rated flow rate and rated capacity methods return values after a sizing run.

**Comment by mjwitte** [comment]
@lgu1234 Note that the E9_2.idf file above when transitioned to v9.3 *does* populate the EquipmentSummary report. But the E9_3.idf above does not.
[E9_2to9_3.idf.txt](https://github.com/NREL/EnergyPlus/files/4905116/E9_2to9_3.idf.txt)

**Comment by lgu1234** [comment]
@mjwitte Thanks for letting me know.

**Comment by lgu1234** [comment]
@mdahlhausen @mjwitte I found the problem. Here is the input of SimlationControl object in E9_3.idf:

SimulationControl,
  Yes,                                    !- Do Zone Sizing Calculation
  Yes,                                    !- Do System Sizing Calculation
  Yes,                                    !- Do Plant Sizing Calculation
  Yes,                                    !- Run Simulation for Sizing Periods
  No,                                     !- Run Simulation for Weather File Run Periods
  Yes;                                    !- Do HVAC Sizing Simulation for Sizing Periods

Here is the input of SimlationControl object in E9_2toE9_3.idf:

  SimulationControl,
    Yes,                     !- Do Zone Sizing Calculation
    Yes,                     !- Do System Sizing Calculation
    Yes,                     !- Do Plant Sizing Calculation
    Yes,                     !- Run Simulation for Sizing Periods
    No;                      !- Run Simulation for Weather File Run Periods

The default choice of Do HVAC Sizing Simulation for Sizing Periods is No. Based on the code, when Do HVAC Sizing Simulation for Sizing Periods is set to Yes, the final results of plant sizing will not reported in html.

After I set to No for Do HVAC Sizing Simulation for Sizing Periods, the final sizing results are reported as expected. Here is a screen shot:

![Capture](https://user-images.githubusercontent.com/5970656/87430374-23e13100-c5b3-11ea-907d-78831c368aca.PNG)

I am going to add a warning to show user "Final plant sizing values are not reported in the table outputs."

**Comment by mdahlhausen** [comment]
@lgu1234 thank you for clarifying the issue.  I think the issue I encountered may have resulted from a change in OpenStudio, not EnergyPlus.

**Comment by lgu1234** [comment]
@mdahlhausen This issue may be done from your side. We still think to make a report even though Do HVAC Sizing Simulation is true. I reopen it for further discussion.

**Comment by EnergyArchmage** [comment]
The HVAC sizing simulation failed for some reason.  This table is empty as well.  


  | Previous Design Volume Flow Rate [m3/s] | Algorithm Volume Flow Rate [m3/s] | Coincident Design Volume Flow Rate [m3/s] | Coincident Size Adjusted | Peak Sizing Period Name | Peak Day into Period {TIMESTAMP}[day] | Peak Hour Of Day {TIMESTAMP}[hr] | Peak Step Start Minute {TIMESTAMP}[min]
-- | -- | -- | -- | -- | -- | -- | -- | --
None |   |   |   |   |   |   |   |  

Normally when the HVAC sizing simulation finishes those values are filled with final results as expected.   I have not tested with the input missing for Maximum Number of HVAC Sizing Simulation Passes, but I suspect that with the field is missing the default of 1 pass is not being handled properly.  

The plant loop sizing is also nonCoincident which does not make sense for sizing plant loop with HVAC sizing simulation.

**Comment by mdahlhausen** [comment]
@EnergyArchmage and @lgu1234 I just confirmed that the issue is the field `Maximum Number of HVAC Sizing Simulation Passes` is not being defaulted in EnergyPlus.  When I include this field in the .idf set to the default of 1, the sizing values show up in the table.  When the field is excluded (the object is closed at the `Do HVAC Sizing Simulation for Sizing Periods`), the sizing values are missing.

**Comment by lgu1234** [comment]
@mdahlhausen Thanks for letting us know. @mjwitte provided a good solution yesterday to make "      \min-fields 7", so that the default value as 1 of Maximum Number of HVAC Sizing Simulation Passes is automatically assigned. You don't need to do anything at your side. I am going to commit the change tomorrow.

**Comment by EnergyArchmage** [comment]
I'm not sure you want to extend min fields to include the HVAC sizing sim fields. They aren't used often.

**Comment by lgu1234** [comment]
@EnergyArchmage If min field is not extended to 7, The default value will not be assigned to the HVAC sizing sim field, so that some reporting values will be missed.
