### ISSUE TITLE
autocalculate fails in the View Factor to Ground field of the FenestrationSurface:Detailed with lightshelf

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#8154]
Issue overview
--------------
Specifying autocalculate in the View Factor to Ground field of the FenestrationSurface:Detailed objects fails with an outdoor lightshelf. This behavior can be reproduced in the DaylightingDeviceShelf.idf example file by simply changing object
```
FenestrationSurface:Detailed,
    Daylit Upper Window,     !- Name
    WINDOW,                  !- Surface Type
    Standard Window,         !- Construction Name
    Daylit South Wall,       !- Building Surface Name
    ,                        !- Outside Boundary Condition Object
    0.211,           !- View Factor to Ground
```
to
```
FenestrationSurface:Detailed,
    Daylit Upper Window,     !- Name
    WINDOW,                  !- Surface Type
    Standard Window,         !- Construction Name
    Daylit South Wall,       !- Building Surface Name
    ,                        !- Outside Boundary Condition Object
    autocalculate,           !- View Factor to Ground
```
Which produces this error.
```
   ** Warning ** DaylightingDevice:Shelf = SHELF:  Window view factors to sky [0.50],
   **   ~~~   ** ground [0.50], and outside shelf [0.29] add up to > 1.0.
```
This looks like an easy fix since the outside shelf view factor is calculated and can be subtracted from the ground view factor.

### Details
 - Version of EnergyPlus 9.3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mldichter** [comment]
There is an old issue about unenclosed zone warning from the inside shelf as well. #7080

**Comment by RKStrand** [comment]
@mldichter Will look at #7080 separately as they have different causes, but thanks for linking it here.  I hope to work on that as soon as I wrap this one up.

**Comment by RKStrand** [comment]
@mldichter Will look at #7080 separately as they have different causes, but thanks for linking it here.  I hope to work on that as soon as I wrap this one up.
