### ISSUE TITLE
Enhanced Python API get_variable_value Error Handling

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#8155]
Issue overview
--------------
If the method ```get_variable_value``` somehow gets passed a ```None``` value, the resulting error message is as follows:

```
   ** Severe  ** Call to on_end_of_zone_timestep_before_zone_reporting() on PythonPluginCustomOutputVariable.AverageZoneTemps failed!
   **   ~~~   ** Python error description follows: 
   **   ~~~   ** "argument 1: <class 'TypeError'>: wrong type"
   **  Fatal  ** Program terminates after call to on_end_of_zone_timestep_before_zone_reporting() on PythonPluginCustomOutputVariable.AverageZoneTemps failed!
```

This is a bit too cryptic. Maybe we could enhance the error message on this and similar methods?

To replicate, take any of the PythonPlugin example files and make sure ```None``` is passed to ```get_variable_value```.

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac OS X 10.14.6)
 - Version of EnergyPlus (9.4 8876db28a5f5e80e8844c65271789fbe86ff802b)
 - Unmethours link or helpdesk ticket number - None
 
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I'd be happy to take this one on. But I'm allowed to work on Defects, not NewFeature. So which one is it? :)
