### ISSUE TITLE
SingleDuctAirTerminal Heat/Cool Rate/Energy variables are no longer used

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#8161]
Issue overview
--------------
[`struct SingleDuctAirTerminal`](https://github.com/NREL/EnergyPlus/blob/8876db28a5f5e80e8844c65271789fbe86ff802b/src/EnergyPlus/SingleDuct.hh#L226-L229) has four variables that are never really used for anything: `HeatRate, CoolRate, HeatEnergy, and CoolEnergy`.

[`SingleDuctAirTerminal::SimConstVolNoReheat`](https://github.com/NREL/EnergyPlus/blob/8876db28a5f5e80e8844c65271789fbe86ff802b/src/EnergyPlus/SingleDuct.cc#L4756-L4794) does some calculations for these, but it's not used anywhere else. This function can be reduced to essentially just [lines 4778-4784](https://github.com/NREL/EnergyPlus/blob/8876db28a5f5e80e8844c65271789fbe86ff802b/src/EnergyPlus/SingleDuct.cc#L4778-L4784) and the last line calling ` this->UpdateSys();`

And there's a few lines in `SingleDuct::InitSys` that set these to zero that can be deleted.

This should give a small speed improvement and zero diffs.

It may seem like this check will be lost if it's deleted:
```
if (GetCurrentScheduleValue(this->SchedPtr) > 0.0 && MassFlow > SmallMassFlow)
```
but that's already checked in [`SingleDuctAirTerminal::InitSys`](https://github.com/NREL/EnergyPlus/blob/8876db28a5f5e80e8844c65271789fbe86ff802b/src/EnergyPlus/SingleDuct.cc#L2308-L2341).

More background. These variables became obsolete when the duplicate output variables were removed from `SingleDuct::GetSysInput` as part of #7448.
```
            SetupOutputVariable(
                "Zone Air Terminal Sensible Heating Energy", OutputProcessor::Unit::J, Sys(SysNum).HeatEnergy, "System", "Sum", Sys(SysNum).SysName);
            SetupOutputVariable(
                "Zone Air Terminal Sensible Cooling Energy", OutputProcessor::Unit::J, Sys(SysNum).CoolEnergy, "System", "Sum", Sys(SysNum).SysName);
            SetupOutputVariable(
                "Zone Air Terminal Sensible Heating Rate", OutputProcessor::Unit::W, Sys(SysNum).HeatRate, "System", "Average", Sys(SysNum).SysName);
            SetupOutputVariable(
                "Zone Air Terminal Sensible Cooling Rate", OutputProcessor::Unit::W, Sys(SysNum).CoolRate, "System", "Average", Sys(SysNum).SysName);
```

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus v9.4.0-https://github.com/NREL/EnergyPlus/commit/8876db28a5f5e80e8844c65271789fbe86ff802b

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@Nigusse Let's make a simple PR for this one - should be no diffs - and it will simplify #7861 slightly.

**Comment by Nigusse** [comment]
@mjwitte do you want me to create this simple PR or you have already done this? 

If I understand correctly your plan is to merge this simple PR to develop and then pull develop into #7861?

**Comment by mjwitte** [comment]
@Nigusse Please proceed with this. Let's get this in first. I'll have some more comments on #7861 as well.
