### ISSUE TITLE
Unable to avoid WaterHeater:Stratified warning

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#8163]
Issue overview
--------------
The WaterHeater:Stratified object gives the following warning whenever you have less than 12 nodes but have fields for all 12 loss coefficients:
```
** Warning ** WaterHeater:Stratified = WATER HEATER TANK:  More Additional Loss Coefficients were entered than the number of nodes; extra coefficients will not be used
```

The problem is that if you have a stratified tank with < 12 nodes and want to access the fields that occur after the loss coefficient fields, it is impossible to avoid the warnings. Perhaps the warning made sense back when the coefficient fields were the last fields in the object, but now there are additional fields at the end.

Here is an example IDF where the object has 6 nodes, but in order to specify the "Source Side Flow Control Mode" at the end, all 12 coefficient fields must be included:

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/4941856/in.idf.txt)

Possible solutions:
- Excluding empty coefficient fields, as shown in the attached IDF, from the warning check
- Reorder the object fields so that the coefficient fields are at the end; then the fields can be excluded in the IDF
- Remove the warning altogether

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here): https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/8000s/8163/in.idf
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I'm in favor of "Reorder the object fields so that the coefficient fields are at the end; then the fields can be excluded in the IDF". Then these could become actual \extensible fields with a \max-fields later down the road.

**Comment by jmarrec** [comment]
Well, looking at your example file, I suppose the quick fix is to just check for non-blank values after the number of nodes to compare with the number of nodes specified.

I don't know what others think. I'm ok with the quick fix, but I'm also willing to make an IDDChange with a fortran translation.

----

example:

```
WaterHeater:Stratified,
  water heater tank,                      !- Name
  Domestic Hot Water,                     !- End-Use Subcategory
  0.272549648445829,                      !- Tank Volume {m3}
  1.5975,                                 !- Tank Height {m}
  VerticalCylinder,                       !- Tank Shape
  ,                                       !- Tank Perimeter {m}
  90,                                     !- Maximum Temperature Limit {C}
  MasterSlave,                            !- Heater Priority Control
  water heater TopElementSetpoint,        !- Heater 1 Setpoint Temperature Schedule Name
  18.5,                                   !- Heater 1 Deadband Temperature Difference {deltaC}
  4500,                                   !- Heater 1 Capacity {W}
  1.1315625,                              !- Heater 1 Height {m}
  water heater BottomElementSetpoint,     !- Heater 2 Setpoint Temperature Schedule Name
  3.89,                                   !- Heater 2 Deadband Temperature Difference {deltaC}
  4500,                                   !- Heater 2 Capacity {W}
  0.3328125,                              !- Heater 2 Height {m}
  electricity,                            !- Heater Fuel Type
  1,                                      !- Heater Thermal Efficiency
  3,                                      !- Off Cycle Parasitic Fuel Consumption Rate {W}
  electricity,                            !- Off Cycle Parasitic Fuel Type
  0,                                      !- Off Cycle Parasitic Heat Fraction to Tank
  0,                                      !- Off Cycle Parasitic Height {m}
  3,                                      !- On Cycle Parasitic Fuel Consumption Rate {W}
  electricity,                            !- On Cycle Parasitic Fuel Type
  0,                                      !- On Cycle Parasitic Heat Fraction to Tank
  0,                                      !- On Cycle Parasitic Height {m}
  Schedule,                               !- Ambient Temperature Indicator
  water heater Tamb act,                  !- Ambient Temperature Schedule Name
  ,                                       !- Ambient Temperature Zone Name
  ,                                       !- Ambient Temperature Outdoor Air Node Name
  0.924989966690986,                      !- Uniform Skin Loss Coefficient per Unit Area to Ambient Temperature {W/m2-K}
  1,                                      !- Skin Loss Fraction to Zone
  0,                                      !- Off Cycle Flue Loss Coefficient to Ambient Temperature {W/K}
  1,                                      !- Off Cycle Flue Loss Fraction to Zone
  ,                                       !- Peak Use Flow Rate {m3/s}
  ,                                       !- Use Flow Rate Fraction Schedule Name
  ,                                       !- Cold Water Supply Temperature Schedule Name
  Node 21,                                !- Use Side Inlet Node Name
  Node 22,                                !- Use Side Outlet Node Name
  1,                                      !- Use Side Effectiveness
  0,                                      !- Use Side Inlet Height {m}
  Autocalculate,                          !- Use Side Outlet Height {m}
  ,                                       !- Source Side Inlet Node Name
  ,                                       !- Source Side Outlet Node Name
  1,                                      !- Source Side Effectiveness
  0,                                      !- Source Side Inlet Height {m}
  0,                                      !- Source Side Outlet Height {m}
  Fixed,                                  !- Inlet Mode
  0.00453493591424009,                    !- Use Side Design Flow Rate {m3/s}
  0,                                      !- Source Side Design Flow Rate {m3/s}
  1.5,                                    !- Indirect Water Heating Recovery Time {hr}
  6,                                      !- Number of Nodes
  0,                                      !- Additional Destratification Conductivity {W/m-K}
  0,                                      !- Node 1 Additional Loss Coefficient {W/K}
  0,                                      !- Node 2 Additional Loss Coefficient {W/K}
  0,                                      !- Node 3 Additional Loss Coefficient {W/K}
  0,                                      !- Node 4 Additional Loss Coefficient {W/K}
  0,                                      !- Node 5 Additional Loss Coefficient {W/K}
  0,                                      !- Node 6 Additional Loss Coefficient {W/K}
  ,                                       !- Node 7 Additional Loss Coefficient {W/K}
  ,                                       !- Node 8 Additional Loss Coefficient {W/K}
  ,                                       !- Node 9 Additional Loss Coefficient {W/K}
  ,                                       !- Node 10 Additional Loss Coefficient {W/K}
  ,                                       !- Node 11 Additional Loss Coefficient {W/K}
  ,                                       !- Node 12 Additional Loss Coefficient {W/K}
  IndirectHeatPrimarySetpoint;            !- Source Side Flow Control Mode
```

**Comment by shorowit** [comment]
I don't have a strong opinion, but I tend to feel that reordering the elements is the cleanest solution even though it's a breaking change. Skipping non-blank fields feels nuanced since, in the above IDF snippet, a blank field could also be used for nodes 1-6 in order to use the default value.

**Comment by jmarrec** [comment]
I propose to skip blank fields After NumNodes only to determine the actual number of nodes. I'll open a PR with unit tests and that'll clear out doubt.

I ask other devs on slack about which way to go (quick fix or reordering) and the advice I got what to go for the quick fix here (bearing epJSON in mind)

**Comment by shorowit** [comment]
Okay, that's fine. I don't object. 😉

**Comment by shorowit** [comment]
Any chance you can also update the OS forward translator for this logic? The FT writes a 0 for all nodes regardless of how many nodes were specified for the tank and thus would still produce a false alarm warning.

**Comment by jmarrec** [comment]
MJWitte made the same comment about the IDF editor filling these with 0. I'll address the zero case here in E+

**Comment by shorowit** [comment]
@jmarrec I'm still getting this warning using an IDF produced by OpenStudio-3.1.0-alpha+a754624776-Windows.exe. As far as I can tell, the IDF looks to be correctly written so I'm not sure why E+ is giving a warning.

[in.idf.txt](https://github.com/NREL/EnergyPlus/files/5272883/in.idf.txt)

**Comment by jmarrec** [comment]
@shorowit HEAD commit of PR #8172 https://github.com/NREL/EnergyPlus/pull/8172/commits/41869bc7a5df4bb251fa66f04d8a2f28c6dba7e9 is only in v9.4.0-RC1 not in v9.4.0-IOFreeze which is what your OS installer is using. I confirmed that the warning isn't issued with current E+ develop.

![image](https://user-images.githubusercontent.com/5479063/94117547-a0627c80-fe4c-11ea-9c6d-76044cc66ac4.png)

**Comment by shorowit** [comment]
Oops! Sorry about that. Thanks @jmarrec.
