### ISSUE TITLE
Allow weather actuators to work with EMS

### ISSUE THREAD

**Issue by AndyTindale** [NREL/EnergyPlus#8184]
Issue overview
--------------
In E+ v9.3 and earlier the weather data actuators such as "Direct Solar" do not work for EMS as there is no appropriate calling point available.

AT: I’ve tried replacing BeginTimestepBeforePredictor with BeginZoneTimestepBeforeInitHeatBalance in the program calling manager, but the results are still the same. Very high spikes of direct normal solar are reported with corresponding high gains through East windows.

MW: *** Hmmm, looking more closely at the code, these two callingn points occur after ManageWeather which is where the weather actuators fire. The only calling point I see before ManageWeather is BeginNewEnvironment which is too early (and it's before the day/hour/timestep loops).
I'm not sure how these weather actuators were intended to work. Oh, here's a clue from the description in the EMS application guide "These provide the ability to alter weather data and were originally requested for use with ExternalInterface for using measured data." Sure enough, there's a call to ExternalInterfaceExchangeVariables just before ManageWeather. So, as it stands now. you can't do this with EMS, only ExternalInterface.
I could add a new EMS calling point easy enough for v9.4. BeginTimeStepBeforeManageWeather. If that would help, please post a new issues asking for this.

### Details
Heldesk ticket: [EnergyPlus #15517]: How to modify weather data using EMS

### Checklist
The attached zip file includes an idf and epw file for testing. The epw file includes some very high direct normal values which we are trying to filter out. 

After the fix I would hope that the reported incident solar on the 1m2 window **Block1:Zone1_Wall_2_0_0_0_0_0_Win** will be no higher than 1000W. Without the fix the solar goes over 4,500W. 

Also the reported site **Direct Solar** values should be no higher than 900 W/m2 (if EMS is allowed to change the Environment reported values)

- [x] *Here's a revised defect file that uses the new calling point and new functions and one with no EMS to show that the values noted above are too high without the EMS correction.* 
[8184-WeatherActuator.zip](https://github.com/NREL/EnergyPlus/files/5092575/8184-WeatherActuator.zip)

**Comment by mjwitte** [comment]
@AndyTindale Looking more carefully at the EMS snippet (from the helpdesk ticket), I'm not sure a new calling point will be adequate:
```
EnergyManagementSystem:Sensor,
Direct_Solar_Check,
Environment,
Site Direct Solar Radiation Rate per Area;

EnergyManagementSystem:Actuator,
Direct_Solar_Set,
Environment,
Weather Data,
Direct Solar;

EnergyManagementSystem:Program,
CorrectDSOutliers,
IF (Direct_Solar_Check > 900),
SET Direct_Solar_Set = 900,
ELSE,
SET Direct_Solar_Set = NULL,
ENDIF;
```
As it is currently programmed, the weather actuators need to be set before entering `SetCurrentWeather`, so the current value for `Direct_Solar_Check` will be from the prior timestep if a new calling point is placed before `ManageWeather`. I'll have to re-think this.

**Comment by AndyTindale** [comment]
Mike,


  *   As it is currently programmed, the weather actuators need to be set before entering SetCurrentWeather, so the current value for Direct_Solar_Check will be from the prior timestep if a new calling point is placed before ManageWeather.


We are not constrained in any way with the code structure. Can you suggest an alternative way to program this in EMS that could work?

Andy

**Comment by AndyTindale** [comment]
[8184.zip](https://github.com/NREL/EnergyPlus/files/5040663/8184.zip)
Test zip file attached

**Comment by mjwitte** [comment]
@AndyTindale My current thought is to add some new EMS functions that can query the internal arrays that hold 24 hrs of weather data for Today and Tomorrow. These are the base values from the epw (or design day creation) that are used in `SetCurrentWeather` to set the values for a given timestep. This would provide access to the original solar values in your case. It would also provide a look into the future which may or may not be the best approach. That would be in addition to the new calling point.

**Comment by AndyTindale** [comment]
@mjwitte Your suggested approach sounds really powerful especially if the base values could also be accessible from the Python scripts as well as EMS
