### ISSUE TITLE
ERL trace assertion error

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#8186]
Issue overview
--------------
An assertion error is shown when running debug:

Assertion failed: outputFile.os, file
C:\repos\EnergyPlus01\src\EnergyPlus\IOFiles.hh, line 360

with the defect file.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ( EnergyPlusDevSupport\DefectFiles\8000s\8186\orig_back_930-fix.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lefticus** [comment]
Fixed in #8187
