### ISSUE TITLE
Allow Zone HVAC Terminal Units to draw return air from  return air plenum or an air branch off the return air duct

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#8190]
Issue overview
--------------
Currently EnergyPlus only allows a zone HVAC terminal unit to draw recriculation air from the zone air node - i.e. air at zone conditions. See the following diagrams for reference:
![Ducted Return - Current State](https://user-images.githubusercontent.com/7797674/89577555-da28e680-d7fe-11ea-8615-b0bf4f06bd05.jpg)
![Plenum Return - Current State](https://user-images.githubusercontent.com/7797674/89577569-e0b75e00-d7fe-11ea-8b6e-b668df403f3b.jpg)

Many applications of ceiling-mounted zone HVAC terminal units (VRF, hydronic fan coil, WSHP) actually draw air from the ceiling space or from a return air duct.  In those applications the air entering the zone HVAC terminal mixing box is at a condition thermally different from the zone air node.  In the case of drawing air from a return air plenum, air is at the mixed plenum temperature, having incorporated heat gains or losses occurring in the plenum.  In the case of drawing air from a return duct, the air temperature may have been altered by lighting fixture heat gain in the case of returns originating at vented lighting fixtures.  The altered condition of recirculating air affects the loads on cooling or heating coils in the zone HVAC terminal.   It allows more accurate modeling of equipment loads and energy use.

This feature request is based on study of commercial building HVAC design drawings in which ceiling mounted HVAC terminals simply have an inlet port that draws air from the ceiling space rather than a duct running from the return grille to the zone HVAC unit mixing box.  The distance between return grille and inlet port is sometimes quite large, meaning that return air from the space has sufficient time to mix with air in the plenum to absorb heat gains or losses. The following two diagrams shows the proposed alternative option:
![Ducted Return - Proposed Alternative Option](https://user-images.githubusercontent.com/7797674/89577603-ef9e1080-d7fe-11ea-9c16-9189f7c7c5c8.jpg)
![Plenum Return - Proposed Alternative Option](https://user-images.githubusercontent.com/7797674/89577609-f2990100-d7fe-11ea-9fdc-e74a263b3a99.jpg)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
This was implemented in #8719, closing.
