### ISSUE TITLE
Warning "Windows has protected your PC

### ISSUE THREAD

**Issue by DavidHollman** [NREL/EnergyPlus#8197]
When I ran the 9.3 installer on Windows 10, it gave me a malware warning. This is the full 9.3 installer (not the later bug fix installer) which I downloaded from here.

![image](https://user-images.githubusercontent.com/18285074/90020932-8d219600-dc7e-11ea-955f-ff0d20040465.png)

Possibly related - later on once actual installation has started, a yellow UAC prompt comes up with the wording "unknown publisher". This probably is because the installer is not code signed.

**Comment by Myoldmopar** [comment]
Thanks for posting this, we don't need two issues open so I am closing this one.  #8198 will stay open.

**Comment by DavidHollman** [comment]
@Myoldmopar  sorry about that, I have no idea how it posted twice! Thanks for cleaning it up.

**Comment by Myoldmopar** [comment]
No problem at all.
