### ISSUE TITLE
Minor cosmetic issues in 9.3 installer screens

### ISSUE THREAD

**Issue by DavidHollman** [NREL/EnergyPlus#8199]
I thought I should mention these minor issues.

I'm on Windows 10 and running at 125% text scaling.

The title bar is blank. Also, the black-on-blue text is hard to read:
![image](https://user-images.githubusercontent.com/18285074/90020988-a296c000-dc7e-11ea-9874-38e20ffa416f.png)

The blue color of the EnergyPlus logo is also hard to make out.

The text at the right looks like it might be cut off. This is more obvious after the first screen as the graphics do seem to move it over:

![image](https://user-images.githubusercontent.com/18285074/90021123-d1ad3180-dc7e-11ea-9f19-1b4d19a315b3.png)

Here's what it looks like when another window has focus. The text is readable but the logo still doesn't seem right:

![image](https://user-images.githubusercontent.com/18285074/90021013-ad515500-dc7e-11ea-9d00-653b463684d8.png)

Thanks

**Comment by jmarrec** [comment]
Thanks for the feedback!

Tweaking the UI is inherently tedious and long as you need to do changes, build the entire installer, then manually try to install it to see if it's better. Also customizing the QtIFW UI is a massive pain. Setting up the E+ logo and stuff took me a while already when we moved from NSIS to QtIFW (NSIS didn't have any fancy features), but the clear benefit was that we could have components (you can deselect stuff you don't want to install) which wasn't a thing with NSIS.

My two cents is I'd rather we spend 8 or more hours fixing issues and doing enhancements to the actual code than trying to tweak the installer's **UI** so I'd classify it as a very low priority for now.

**Comment by DavidHollman** [comment]
@jmarrec personally, I'm sure your prioritization is correct :)  Especially because it didn't look like anything important was not visible.

Maybe if over time you accumulate a series of minor installer issues someday it will be worth trying to hammer them all out at once, that's probably what I would do.

**Comment by jmarrec** [comment]
Yeah I was definitely planning on trying to lump it in another installer work, next time we have to do iterative testing on it. It's good to have this issue to serve as a reference for improvements

**Comment by jmarrec** [comment]
V22-1-0-IOFreeze installer:

![image](https://user-images.githubusercontent.com/5479063/155681460-29c38052-2f78-41b1-9746-81e828b9542f.png)


The title bar **is** "EnergyPlus is a whole building energy simulation program". 

https://github.com/NREL/EnergyPlus/blob/4fa778ec59f792656c87f75512e4ed21920f2859/cmake/Install.cmake#L121

https://cmake.org/cmake/help/latest/cpack_gen/ifw.html#variable:CPACK_IFW_PACKAGE_TITLE

There is no blue, regardless of whether the window has focus or not.

As far as the logo's clearness, I'm not about to start redrawing it as an SVG, and it looks ok enough.

I consider this addressed then.
