### ISSUE TITLE
NaN value for new window surface temperature due to overflow in AirflowNetworkBalanceManager

### ISSUE THREAD

**Issue by ajscimone** [NREL/EnergyPlus#8200]
Issue overview
--------------
The attached EnergyPlus idf file results in a series of EnergyPlus error outputs indicating NaN values occuring during new window surface temperature calculations. The observed output observed is as follows:
`  ** Warning ** Saturation Temperature not converged after 51 iterations (PsyTsatFnPb)
  **  ~~~  ** Routine=Unknown, Environment=RUNPERIOD 1, at Simulation time=03/13 17:20 - 17:30
  **  ~~~  ** Input Pressure= NAN
  **  ~~~  ** Resultant Temperature= NAN
  ** Severe ** Convergence error in SolveForWindowTemperatures for window NORTH WALL WINDOW 1
  **  ~~~  ** Environment=RUNPERIOD 1, at Simulation time=03/13 17:30 - 17:40
  **  ~~~  ** Glazing face index = 1 ; new temperature =NANC ; previous temperature = 17.3239C
  **  ~~~  ** Glazing face index = 2 ; new temperature =NANC ; previous temperature = 17.5398C
  ** Fatal ** Program halted because of convergence error in SolveForWindowTemperatures for window NORTH WALL WINDOW 1`

This error is likely due to a divide by zero error causing a cascade of NaN values. 

### Details
Some additional details for this issue (if relevant):
 - Platform: All
 - Version of EnergyPlus: 9.3
[failing.txt](https://github.com/NREL/EnergyPlus/files/5064369/failing.txt)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
@ajscimone or @nealkruis can you make a Pivotal ticket out of this so that we can get it discussed on the iteration call and assigned to someone...looks like an important fix.

**Comment by ajscimone** [comment]
@Myoldmopar Created a Pivotal just now (#174305347). I have started getting a fix and unit testing together.
