### ISSUE TITLE
Bypass interior solar distribution calculation at night

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#8201]
Issue overview
--------------
LBL identified 20 hotspots for speed improvement. InitIntSolarDistribution is one of hotspots. The interior solar distribution calculation is performed every time step. The present check-in bypasses the calculation at night, because no solar is available at night.

This issue is a task for 10x project to speed up calculation.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Addressed by #8182
