### ISSUE TITLE
Packages Need OS Version Number

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#8224]
We are going to be producing packages for Mac OSX 13.Something and 15 this release.  CI will be producing both of them.  We need to give them unique names so that CI doesn't fail to upload a duplicate name and also so that users will know which one to download.  The package built on 13 will likely work on 15, but not the other way around.  And we don't have an option to downgrade the CI machine running 15 down to 13, so here we are.

Right now this could just be for Mac, but I suspect Ubuntu is coming down the line with 20.04 LTS.  I don't see needing multiple Windows versions anytime soon.  So we can leave Windows as just Windows.  I don't have a strong opinion on naming convention as long as it conveys the intent.  Maybe as simple as:

| Original FileName                           | New FileName                                      |
|---------------------------------------------|---------------------------------------------------|
| EnergyPlus-9.4.0-62b9de59ab-Darwin-x86_64.* | EnergyPlus-9.4.0-62b9de59ab-Darwin-OSX13-x86_64.* |
|                                             | EnergyPlus-9.4.0-62b9de59ab-Darwin-OSX15-x86_64.* |
| EnergyPlus-9.4.0-62b9de59ab-Linux-x86_64.*  | EnergyPlus-9.4.0-62b9de59ab-Linux-U1804-x86_64.*  |
|                                             | EnergyPlus-9.4.0-62b9de59ab-Linux-U2004-x86_64.*  |

I'm totally open to suggestion, but would like input soon as I want to get this fully stabilized to make sure CI and my installer sanity tests get a chance to work on it.

@jmarrec if you or anyone else has interest in this, you are welcome to take this, otherwise I'll do it.

**Comment by jmarrec** [comment]
@Myoldmopar I'll happily take this one on, thanks for the suggestion. I'll try to get a PR going early next week
