### ISSUE TITLE
Transition needed for some objects following the fuel type standardization

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#8232]
Issue overview
--------------

I've just updated a bunch of IDF files we have on the OpenStudio repo. Seems like the Output:Variable fuel name conversion (Following #8134) works fine thanks to the CSV Report Variables. But some stuff isn't correctly handled by VT, such as `UtilityCost:Tariff`'s "Output Meter Name" field.

I found it by first running the TransitionV9-3-0-to-V-9-4-0 on all files. Then I also did a python script to do a search on replace based each line of the `Report Variables 9-3-0 to 9-4-0.csv`, and I found more diffs:

```diff
  UtilityCost:Tariff,
    IN_EIAMonthlyRateGas,    !- Name
-    Gas:Facility,            !- Output Meter Name
+    NaturalGas:Facility,            !- Output Meter Name
    MCF,                     !- Conversion Factor Choice
    ,                        !- Energy Conversion Factor
    ,                        !- Demand Conversion Factor
```

```diff
  UtilityCost:Tariff,
    Generic Fuel Oil 1,      !- Name
-    FuelOil#1:Facility,      !- Output Meter Name
+    FuelOilNo1:Facility,      !- Output Meter Name
    ,                        !- Conversion Factor Choice
    ,                        !- Energy Conversion Factor
    ,                        !- Demand Conversion Factor
```

```diff
-  Output:Meter,Water Heater:WaterSystems:Gas,HOURLY;
+  Output:Meter,Water Heater:WaterSystems:NaturalGas,HOURLY;
```

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.4.0-IOFreeze

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Additionally, PythonPlugin:OutputVariable, still lists FuelOil#1 in the IDD

```
PythonPlugin:OutputVariable,
       \memo This object sets up an EnergyPlus output variable from a Python Plugin variable
       \min-fields 4
   A1, \field Name
       \required-field
       \type alpha
   A2, \field Python Plugin Variable Name
       \required-field
       \type alpha
       \note Must be listed in the PythonPlugin:Variables object
   A3, \field Type of Data in Variable
       \required-field
       \type choice
       \key Averaged
       \key Summed
       \key Metered
       \note If Metered is selected, the variable is automatically set to a "Summed" type, and the
       \note Resource Type, Group Type, and End-Use Subcategory fields on this object are required
   A4, \field Update Frequency
       \required-field
       \type choice
       \key ZoneTimestep
       \key SystemTimestep
   A5, \field Units
       \note optional but will result in dimensionless units for blank
       \note EnergyPlus units are standard SI units
       \type alpha
   A6, \field Resource Type
       \note This field is optional for regular output variables with "Type of Data in Variable" set to
       \note either Averaged or Summed.  For Metered variables, this field is required.
       \note Choose the type of fuel, water, electricity, pollution or heat rate that should be metered.
       \type choice
       \key Electricity
       \key NaturalGas
       \key Gasoline
       \key Diesel
       \key Coal
       \key FuelOil#1
       \key FuelOil#2
```

**Comment by mjwitte** [comment]
`UtilityCost:Tariff` meter name should get converted [here](https://github.com/NREL/EnergyPlus/blob/908c5cedf506343fd08ab3ff5cb7974707d70f68/src/Transition/CreateNewIDFUsingRulesV9_4_0.f90#L992-L994) Likely problem is that the object type needs to be upper case there.

**Comment by mjwitte** [comment]
@dareumnam Would you be able to add these fixes to #8240 ?

**Comment by dareumnam** [comment]
@mjwitte I got it. I'll update current PR.

**Comment by dareumnam** [comment]
@mjwitte Should the IDD change of FuelOil# be done separately? (since I/O freeze for this release was already done)

**Comment by mjwitte** [comment]
The IDD is clearly in error as noted above, so I think it needs to go in. But @Myoldmopar may want it done as a separate PR to give it more visibility?

**Comment by dareumnam** [comment]
@mjwitte I checked with Edwin that this needs to go in. I'll add this fix.
