### ISSUE TITLE
Surface Heat Flux Accumulating Imbalance with HeatBalanceAlgorithm = ConductionFiniteDifference

### ISSUE THREAD

**Issue by mldichter** [NREL/EnergyPlus#8234]
Issue overview
--------------
An IDF with HeatBalanceAlgorithm = ConductionFiniteDifference has an imbalance in heat flux going into and out of the wall that accumulates over time.

![sum flux with bug](https://user-images.githubusercontent.com/39242689/91224219-a0991c00-e6d6-11ea-8318-587ec83698ee.PNG)

This does not occur when HeatBalanceAlgorithm = ConductionTransferFunction, which is the default in the IDFEditor.

![sum flux without bug](https://user-images.githubusercontent.com/39242689/91224285-bad2fa00-e6d6-11ea-928a-621e1192feb2.PNG)

### Details
 - EnergyPlus 9.3
 - https://unmethours.com/question/45700/heat-fluxes-through-wall-not-matching-leading-to-cumulative-heat-gain-over-annual-simulation/?answer=46889#post-id-46889

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added https://drive.google.com/file/d/1nN2JEly9i0tFSrdz0zwoPm8n5A2-6SM4/view?usp=sharing
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
Note to self or whoever fixes this...the unmethours post might actually contain two separate issues.  The original one posted here about two years ago and a potentially new one that was posted within the last week or so.  The new one might relate to the fact that the surfaces that show an issue (even using CTFs) uses "Zone" as the other side.  In these situations, E+ creates the appropriate surface.  Maybe there is a problem there (not sure, just speculation at this point).  If that is the case, that is a separate issue that will be logged separately once that is determined.

**Comment by RKStrand** [comment]
Second issue is clearly a different problem that does not relate to the finite difference solution and has been logged as a separate issue (#10089).  The problem discussed above in this issue has been verified to still be a problem.

**Comment by RKStrand** [comment]
Problem has been isolated.  The surface flux was not being calculated properly on the outside when rain was present.  That is now fixed.  With the fix for the CondFD solution, here is an updated heat flux sum graph for a five year period:

<img width="644" alt="image" src="https://github.com/NREL/EnergyPlus/assets/5804989/05ccd873-82bb-4865-ac54-182fd2b24a8d">
