### ISSUE TITLE
Linux version IDFVersionUpdater converting problems

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8245]
Issue overview
--------------
The Linux version IDFVersionUpdater was reported to have problems issue with when up-converting from V7.2 to V8.0. The parameters in the object  ``Sizing:Zone`` were reported to be in wrong orders, so that the ``DesignDay`` took the place of the value of ``Cooling Minimum Air Flow Fraction``, where ``Heating Design Air Flow Method`` had been expected in stead. Some other parameters were also shown to be in incorrect places after the conversion. 
The Windows updater tool is not affected. 

### Details
Some additional details for this issue (if relevant):
 - Linux system only
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Ref helpdesk ticket #15544

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I took the defect file, upgraded it incrementally up to 9.4. I See no problem whatsoever with the Sizing:Zone object. The upgraded files as on `EnergyPlusDevSupport`.

Here it is at 9.4:

```
  Sizing:Zone,
    Atrium,                  !- Zone or ZoneList Name
    SupplyAirTemperature,    !- Zone Cooling Design Supply Air Temperature Input Method
    13.,                     !- Zone Cooling Design Supply Air Temperature {C}
    ,                        !- Zone Cooling Design Supply Air Temperature Difference {deltaC}
    SupplyAirTemperature,    !- Zone Heating Design Supply Air Temperature Input Method
    50.,                     !- Zone Heating Design Supply Air Temperature {C}
    ,                        !- Zone Heating Design Supply Air Temperature Difference {deltaC}
    0.010,                   !- Zone Cooling Design Supply Air Humidity Ratio {kgWater/kgDryAir}
    0.009,                   !- Zone Heating Design Supply Air Humidity Ratio {kgWater/kgDryAir}
    SZ DSOA Atrium,          !- Design Specification Outdoor Air Object Name
    ,                        !- Zone Heating Sizing Factor
    ,                        !- Zone Cooling Sizing Factor
    DesignDay,               !- Cooling Design Air Flow Method
    ,                        !- Cooling Design Air Flow Rate {m3/s}
    ,                        !- Cooling Minimum Air Flow per Zone Floor Area {m3/s-m2}
    ,                        !- Cooling Minimum Air Flow {m3/s}
    ,                        !- Cooling Minimum Air Flow Fraction
    DesignDay,               !- Heating Design Air Flow Method
    ,                        !- Heating Design Air Flow Rate {m3/s}
    ,                        !- Heating Maximum Air Flow per Zone Floor Area {m3/s-m2}
    ,                        !- Heating Maximum Air Flow {m3/s}
    ,                        !- Heating Maximum Air Flow Fraction
    ,                        !- Design Specification Zone Air Distribution Object Name
    No,                      !- Account for Dedicated Outdoor Air System
    NeutralSupplyAir,        !- Dedicated Outdoor Air System Control Strategy
    autosize,                !- Dedicated Outdoor Air Low Setpoint Temperature for Design {C}
    autosize;                !- Dedicated Outdoor Air High Setpoint Temperature for Design {C}
```
