### ISSUE TITLE
module 'numpy' has no attribute 'ndarray'

### ISSUE THREAD

**Issue by nvskumar-m** [NREL/EnergyPlus#8256]
Issue overview
--------------
I have created EP Python Plugin which uses third party libraries like numpy for computation. On testing, I understood that EP python requires library folders added to the current working directory or Python standard library directory located in C:\EnergyPlusV9-3-0. 

I have added all the python libraries specified in the error. But after installing numpy, EP is asking for pandas library although I didn't used it in EP plugin script. After adding pandas library directory, the EP shows error [module 'numpy' has no attribute 'ndarray']. I checked changing the versions of pandas library. For version less than 1.0.1 of pandas, the EP shows warning [module 'numpy' has no attribute '__version__']. Is there a simple way to add libraries to EnergyPlus python through pip? 
![image](https://user-images.githubusercontent.com/54622340/92312822-3e97bb00-efe2-11ea-8e51-36ad22379970.png)

**Comment by Myoldmopar** [comment]
> Is there a simple way to add libraries to EnergyPlus python through pip?

Not exactly, but we are working on it.  The plugin system has had some important improvements that will be released with 9.4 in a few weeks, and we look forward to formalizing the way third-party libraries are added to the packaged up Python library for the next version after that.

There is a bit of a hacky workaround, which has been proven by other users, but let's just call it unofficial guidance for now :smile:  You can install the exact same version of Python that EnergyPlus is linked to (find this with `./energyplus --help`).  In that separate version of Python, you can pip install whatever dependencies you want.  Then when you specify extra Python folders in your IDF, you can point to that separate Python's library folder, and it will find those things you pip installed.

**Comment by nvskumar-m** [comment]
Thank you for reply @Myoldmopar.
After the post, I tried an approach that involves invoking the virtual environment from __init__.py in **venv** directory.
firstly I created a **ENV_DIR** directory and later used the python.exe from **script** subfolder .
But the installed libraries are in **Lib** folder of **venv** directory and are being required to be pasted in **python_standard_lib** directory for use. 
Additionally, the simulation time got increased because of using third party libraries in EnergyPlus Python.

**Comment by Myoldmopar** [comment]
@nvskumar-m I don't think you want to be moving files around.  I would suggest some trying to point EnergyPlus to the venv's library directory.  In the Python search paths object, just list "path\to\my\venv\Lib", or whatever path has the `numpy` folder in it.  Again, you'll want it to be the same version of Python as packaged up with EnergyPlus.

> Additionally, the simulation time got increased because of using third party libraries in EnergyPlus Python.

Umm, yes.  It will certainly be slower than running optimized C++ code native to EnergyPlus, but we have run a litany of tests and found it to be similar in speed, and sometimes fast than, the Erl built-in EMS language.

**Comment by nvskumar-m** [comment]
> @nvskumar-m I don't think you want to be moving files around. I would suggest some trying to point EnergyPlus to the venv's library directory. In the Python search paths object, just list "path\to\my\venv\Lib", or whatever path has the `numpy` folder in it. Again, you'll want it to be the same version of Python as packaged up with EnergyPlus.

Thank you @Myoldmopar. I think path should be provided even in EnergyPlus IDF other than in system Python Library Search Path. This is because earlier I tried adding "path\to\my\venv\Lib" in Python Library Search Path but it didn't worked. However, I will try once again and let you know. Regarding EP version, while trying the Python virtual environment I downgraded my Python version from 3.8 to 3.7

> Umm, yes. It will certainly be slower than running optimized C++ code native to EnergyPlus, but we have run a litany of tests and found it to be similar in speed, and sometimes fast than, the Erl built-in EMS language.

I am using a library which is scripted in python and uses other python libraries like pandas and numpy in its source code. Probably, that may be reason for why the timeframe for simulation has increased in my test run case.

**Comment by bonnema** [comment]
@nvskumar-m @Myoldmopar: just FYI, I've used the following in my `PythonPlugin:SearchPaths` objects for various operating systems:
- Debian GNU/Linux: `/usr/local/lib/python3.7/dist-packages`
- MacOS: `/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages`
- Windows 10: `%USERPROFILE%\AppData\Local\Programs\Python\Python37\Lib\site-packages`

These all used python downloaded from https://www.python.org/downloads/.
