### ISSUE TITLE
Tips and Tricks Document Air Wall section is outdated - should refer to Construction:AirBoundary

### ISSUE THREAD

**Issue by saeranv** [NREL/EnergyPlus#8259]
Issue overview
--------------
This issue stems from my difficulties attempting to model interzone airflow through Air walls with the AirflowNetwork (AFN), originally detailed in this unmethours post[1]. In his response to my post @jasondegraw suggested that the lack of support for SimpleOpening objects in Air walls could be considered a bug, given the purpose of the Air wall to model interzone heat exchange, and the role of vertical openings to model interzone airflow. For example, the EnergyPlus _'Tips and Tricks'_ section on '_Air wall, Open air connection_'[2] suggests using a large vertical opening between zones with the AFN. in order to realistically capture both the volume and two-way flow of air between two zones open to each other. 

However, my colleague @chriswmackey has found that this is not possible since the AirflowNetwork:MultiZone:Component:SimpleOpening object cannot be used with with the BuildingSurface object. It can only be inserted in a FenestrationSurface object. We would like to use the Air wall, rather then a FenestrationSurface, since the former models radiant exchange between zones, and the latter doesn't.

Is our reasoning correct that this is a bug, and can it be looked into? Thank you.

### Details
1. https://unmethours.com/question/47107/best-way-to-model-interzone-airflow-through-air-walls-with-afn/
2. https://bigladdersoftware.com/epx/docs/8-5/tips-and-tricks-using-energyplus/air-wall-open-air-connection-between-zones.html

**Comment by mjwitte** [comment]
@saeranv The referenced tips and tricks section was written before `Construction:AirBoundary` was added. It needs a major rewrite - noted.

Regarding AFN with `Construction:AirBoundary` see #8254.

**Comment by saeranv** [comment]
Thanks for the response @mjwitte, I can see that you've made a lot of progress towards fixing this in the other git issue with Chris. I'll follow up there if I have any further questions.
