### ISSUE TITLE
Output file eplusout.bnd is not being created in the specified output directory

### ISSUE THREAD

**Issue by DavidHollman** [NREL/EnergyPlus#8260]
Instead, the `bnd` file is being created in the location that `energyplus.exe` is in.

In my case energyplus.exe is run from under the Program Files directory; as a result it is (rightly) not allowed to write to disk in that location. But this causes an error in my application.

We are using the `-d` option and can see that all the other output files are using it, such as `eplusout.mtr`, `eplusout.eso`, etc. `bnd` appears to be the only exception up to the point in time it is written. (After that point, the process terminates due to the write-prohibition noted above, so I don't know if other files might also be written to the wrong location also.)

This did not appear to happen in earlier versions, which is why this seems to be a bug. The error occurs for both 32bit and 64 bit. With the original 9.3.0 release there was no such a problem.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10
 - Version of EnergyPlus: 9.3 "bugfix release", specifically I installed EnergyPlus-9.3.0-64d91887f6-Windows-i386.exe
 - Unmethours link or helpdesk ticket number

**Comment by DaveInCaz** [comment]
In addition to reporting the issue, I also need to find at least a workaround. In my case `energyplus.exe` is run from under the `Program Files` directory; as a result it is (rightly) not allowed to write to disk in that location. But this causes an error in my application.

**Comment by mitchute** [comment]
This may be corrected by #8250. @jmarrec any thoughts?

**Comment by DavidHollman** [comment]
In addition to reporting the issue, I also need to find at least a workaround while using 9.3, if anyone has a suggestion.

For my purposes, it would be fine if I can entirely suppress creation of this file.

**Comment by DavidHollman** [comment]
Small update - testing EnergyPlus running in a different (writable) location, the bnd file is then created OK, and also I see no other errant output files in that location. So this does seem isolated to that one file.

**Comment by mitchute** [comment]
Local testing shows that this has been corrected.

```
$ ./energyplus -d /Users/mmitchel/Projects/EnergyPlus/bugs/8260/ -D ../../testfiles/1ZoneUncontrolled.idf
...
EnergyPlus Completed Successfully.
$ ls /Users/mmitchel/Projects/EnergyPlus/bugs/8260/
.rw-r--r-- 1.7k mmitchel 30 Sep 10:33 eplusout.audit
.rw-r--r-- 6.3k mmitchel 30 Sep 10:33 eplusout.bnd
.rw-r--r-- 5.4k mmitchel 30 Sep 10:33 eplusout.dxf
.rw-r--r--  14k mmitchel 30 Sep 10:33 eplusout.eio
.rw-r--r--   97 mmitchel 30 Sep 10:33 eplusout.end
.rw-r--r--  883 mmitchel 30 Sep 10:33 eplusout.err
.rw-r--r--  15k mmitchel 30 Sep 10:33 eplusout.eso
.rw-r--r-- 3.5k mmitchel 30 Sep 10:33 eplusout.mdd
.rw-r--r-- 6.9k mmitchel 30 Sep 10:33 eplusout.mtd
.rw-r--r-- 4.3k mmitchel 30 Sep 10:33 eplusout.mtr
.rw-r--r--  26k mmitchel 30 Sep 10:33 eplusout.rdd
.rw-r--r-- 1.5k mmitchel 30 Sep 10:33 eplusout.shd
.rw-r--r--  59k mmitchel 30 Sep 10:33 eplustbl.csv
.rw-r--r-- 252k mmitchel 30 Sep 10:33 eplustbl.htm
.rw-r--r--  59k mmitchel 30 Sep 10:33 eplustbl.tab
.rw-r--r-- 117k mmitchel 30 Sep 10:33 eplustbl.txt
.rw-r--r-- 171k mmitchel 30 Sep 10:33 eplustbl.xml
```

I'll close this, but feel free to reopen if you still have troubles.

**Comment by DavidHollman** [comment]
@mitchute  thanks for the update. Do you know what release this will go into?

**Comment by mitchute** [comment]
v9.4 was released yesterday: https://github.com/NREL/EnergyPlus/releases/tag/v9.4.0

It should work there.
