### ISSUE TITLE
Near zero single speed cooling coil electric power for unitary system with cycling supply fan

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#8285]
Issue overview
--------------
I have a model that has a Unitary System set up as a DOAS with gas heating, DX cooling, and cycling fan operation. The cycling fan operation is set by the Supply Air Fan Operating Mode Schedule Name input field of the unitary system object with the schedule set to always zero. 

![image](https://user-images.githubusercontent.com/17144687/93522092-3860e300-f8ee-11ea-9d06-707ea3a6ac63.png)
![image](https://user-images.githubusercontent.com/17144687/93522174-50d0fd80-f8ee-11ea-806a-a4616c736538.png)

According to IO Ref for this input field:
Supply Air Fan Operating Mode Schedule Name - This alpha field specifies the name of the supply air fan operating mode schedule. The supply air fan operating mode may vary during the simulation based on time-of-day or with a change of season. Schedule values of 0 denote that the unitary system supply air fan and the heating or cooling coil cycle on and off together to meet the heating or cooling load (a.k.a. AUTO fan). Schedule values other than 0 denote that the supply fan runs continuously while the heating or cooling coil cycles to meet the load. The SingleZoneVAV control type is only active when the supply air fan runs continuously (i.e., during cycling fan operation the Control Type = Load model is used).

Simulating just a heating and cooling design day, the DOAS Unitary system works correctly on both days. However, in the cooling design day the Cooling Coil Electricity Rate is near zero. See table below.

![image](https://user-images.githubusercontent.com/17144687/93520387-cedfd500-f8eb-11ea-80cf-28ab56461e05.png)

If the fan operation schedule changes to always 1, indicating a constant flow supply fan per IO Ref, then the Cooling Coil Electricity Rate is much more realistic.

[CyclingFan_SetpointControl.zip](https://github.com/NREL/EnergyPlus/files/5453260/CyclingFan_SetpointControl.zip)

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@matthew-larson @rraustad I'm confused. How does setpoint control with cycling fan decide how long to run the fan? It seems this combination should not be valid.

**Comment by rraustad** [comment]
I agree, set point control only works with constant fan mode.

                thisSys.m_FanOpModeSchedPtr = ScheduleManager::GetScheduleIndex(loc_supFanOpMode);
                if (loc_supFanOpMode != "" && thisSys.m_FanOpModeSchedPtr == 0) {
                    ShowSevereError(cCurrentModuleObject + " = " + thisObjectName);
                    ShowContinueError("Illegal Fan Operating Mode Schedule Name = " + loc_supFanOpMode);
                    // ShowContinueError("Illegal " + cAlphaFields(iFanSchedAlphaNum) + " = " + Alphas(iFanSchedAlphaNum));
                    errorsFound = true;
                } else if (loc_supFanOpMode == "") {
                    if (thisSys.m_ControlType == ControlType::Setpoint) {
                        // Fan operating mode must be constant fan so that the coil outlet temp is proportional to PLR
                        // Cycling fan always outputs the full load outlet air temp so should not be used with set point based control
                        thisSys.m_FanOpMode = DataHVACGlobals::ContFanCycCoil;
                    } else {

**Comment by matthew-larson** [comment]
@mjwitte @rraustad You guys are correct, what I just realized is that with the Setpoint Control Type and the Supply Air Fan Operating Mode Schedule being set to 0, there are no severe errors or warnings in the output file along with the 0 electric power.  The above error only gets triggered if it can't find the schedule name in the file.  So maybe the issue isn't the 0 electric power but the lack of warning or error.  I will post a defect file and error file in here shortly to demonstrate this.

**Comment by matthew-larson** [comment]
Below is a zip file with the IDF which has the DOAS Unitary AirLoopHVAC with the Setpoint Control Type and Supply Air Fan Operating Mode Schedule being set to 0 as shown in the description screenshots.  Also included is the corresponding error file showing no warnings or errors and weather file.
[CyclingFan_SetpointControl.zip](https://github.com/NREL/EnergyPlus/files/5453252/CyclingFan_SetpointControl.zip)

**Comment by matthew-larson** [comment]
I think the error should be caught here but `thisSys.m_FanOpMode` has not been set over the default of 0, so the error isn't caught.
 
```
                } else if (loc_supFanOpMode != "" && thisSys.m_FanOpMode > 0 && thisSys.m_ControlType == ControlType::Setpoint) {
                    if (!ScheduleManager::CheckScheduleValueMinMax(thisSys.m_FanOpModeSchedPtr, ">", 0.0, "<=", 1.0)) {
                        ShowSevereError(cCurrentModuleObject + " = " + thisObjectName);
                        ShowContinueError("For " + loc_fanType + " = " + loc_m_FanName);
                        ShowContinueError("Fan operating mode must be continuous (fan operating mode schedule values > 0).");
                        ShowContinueError("Error found in Supply Air Fan Operating Mode Schedule Name " + loc_supFanOpMode);
                        ShowContinueError("...schedule values must be (>0., <=1.)");
                        errorsFound = true;
                    }
                }
```

**Comment by mjwitte** [comment]
Seems like `&& thisSys.m_FanOpMode > 0` should not be part of this `if` statement.

**Comment by matthew-larson** [comment]
I'll go ahead and update this pull request to revert my previous changes and implement this new fix/unit test so it can be reviewed.  Thanks @mjwitte

**Comment by rraustad** [comment]
It should be `&& thisSys.m_FanOpModeSchedPtr > 0`

**Comment by rraustad** [comment]
I'm not looking at the code right now but you'll have to think about what the first part of the IF represents, the `loc_supFanOpMode != ""` part.

**Comment by rraustad** [comment]
I see, `loc_supFanOpMode` is the schedule name. I think you could remove that first part and just rely on `m_FanOpModeSchedPtr > 0` .
