### ISSUE TITLE
Zero heating rate in DOAS Unitary System with Temperature Setpoint Node Name

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#8299]
Issue overview
--------------
I have a model that has a Unitary System set up as a DOAS with fuel heating, DX cooling, and cycling fan operation. The fuel heating coil has it's setpoint node name specified as the heating coil's outlet node (see below).

       Coil:Heating:Fuel,
         DOAS Unitary Heating Coil, !- Name
         ...
         DOAS Unitary Heating Coil Outlet Node, !- Air Outlet Node Name
         DOAS Unitary Heating Coil Outlet Node; !- Temperature Setpoint Node Name

According to IO Ref for this input field:
Temperature Setpoint Node Name - If the coil is used in the air loop simulation and is temperature controlled using a Set Point Manager, then the node that is the control node needs to be specified here. If the coil is used in an air terminal unit, the coil is load controlled and a control node set point is not required.

The DOAS unitary system is setpoint controlled, and the fuel heating coils' outlet node is part of a node list used by the mixed air setpoint manager of the DOAS unitary system, so I would assume that the highlighted IO Ref sentence above applies. However, in simulating just a heating and cooling design day, the DOAS Unitary system's fuel heating coil doesn't turn on. See plot from Results Viewer below.
![image](https://user-images.githubusercontent.com/17144687/94054207-967f4180-fd98-11ea-84f2-1bd21a861083.png)

If the fuel heating coil's Temperature Setpoint Node Name input field is instead left blank, then the fuel heating coil works as intended. See plot from Results Viewer below.
![image](https://user-images.githubusercontent.com/17144687/94054244-a6972100-fd98-11ea-815f-7c2e20d2fc11.png)

This bug case is contained in the attached "setpoint-node-specified.idf". The IDF uses Chicago weather.

[setpoint-node-specified.idf.txt](https://github.com/NREL/EnergyPlus/files/5483499/setpoint-node-specified.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.3

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@matthew-larson That IO Ref should read more like this:
Temperature Setpoint Node Name - If the coil is used in the air loop simulation *directly on a branch* and is temperature controlled using a Set Point Manager, then the node that is the control node needs to be specified here. If the coil is used in an air terminal unit *or other parent object (ZoneHVAC:* or AirloopHVAC:*)*, the coil is controlled by the parent object and a control node set point is not required.

So, when the coil is used in a Unitary System, it shouldn't need a setpoint node name. It would be nice if we could either warn or ignore it when the setpoint node name is entered where it's not needed.

**Comment by rraustad** [comment]
I'll add that the UntarySystem can be specified as Load, SetPoint or SZVAV controlled, and in the case of SetPoint control, control nodes are required.

    A2,  \field Control Type
       \type choice
       \key Load
       \key SetPoint
       \key SingleZoneVAV
       \default Load
       \note Load control requires a Controlling Zone name.
       \note SetPoint control requires set points at coil outlet node.
       \note SingleZoneVAV also requires a Controlling Zone name and allows
       \note load control at low speed fan until the load exceeds capacity
       \note or outlet air temperature limits. The fan speed is then increased.

**Comment by mjwitte** [comment]
@rraustad A setpoint is required at the coil outlet node node, yes, But what about the Coil:Heating:Fuel field for "Temperature Setpoint Node Name"? I think that needs to be blank for this use case.

**Comment by rraustad** [comment]
Good point, I think your correct but would have to test to be sure.

**Comment by rraustad** [comment]
I think I'd end that description above as:

... the coil is controlled by the parent object and the temperature set point node name is not required.

It may be possible for the UnitarySystem to zero out the heating coil's temperature control node for this use case.

**Comment by matthew-larson** [comment]
Thanks for the feedback.  I agree that the IO Ref needs to be modified to make it more clear when this node should be specified.  What also concerned me was even though you do get the following warning if the node is not required, it doesn't state the magnitude of the error that it could result in zero heating energy.  I was going to see if there is a bug that is zeroing out the heating energy in this case but not mess with the below warning as it still applies.

```
   ** Warning ** Coil:Heating:Fuel "DOAS UNITARY HEATING COIL"
   **   ~~~   **  The Temperature Setpoint Node Name input is not required for this heating coil because
   **   ~~~   **  this heating coil is controlled based on the load calculated by the thermostat.
   **   ~~~   ** ... this heating coil is not controlled by using a temperature setpoint manager.
   **   ~~~   ** ... if a temperature setpoint is placed at the outlet node of this heating coil, that temperature setpoint will not be used.
   **   ~~~   ** ... leaving the input field "Temperature Setpoint Node Name" blank will eliminate this warning.
```

**Comment by mjwitte** [comment]
@matthew-larson I can't find the defect file.

**Comment by matthew-larson** [comment]
@mjwitte Oops, I just added the defect file to the Description.
