### ISSUE TITLE
Inlet and Outlet Node idf errors with AirLoopHVAC:UnitarySystem objects cause are not caught, resulting in faulty data members.

### ISSUE THREAD

**Issue by ajscimone** [NREL/EnergyPlus#8305]
Issue overview
--------------
When using an *AirLoopHVAC:UnitarySystem*, the error detection for inlet and outlet nodes do not seem to catch mismatched nodes, and instead result in the following error far downstream in the simulation:  

`** Severe  ** Duplicate internal variable was sent to SetupEMSInternalVariable.`

For example, in the attached idf, there is a typo in one of the *NodeList* items here:

    NodeList,
        Bath_ZN_1_FLR_1 Exhaust Nodes,  !- Name
        Bath_ZN_1_FLR_1 ZN-PTAC Inlet Node;  !- Node 1 Name

idf: [in.idf.txt](https://github.com/NREL/EnergyPlus/files/6145467/in.idf.txt)

The problem with this object is the *Node 1* name is misspelled. Instead of printing out that the there is some mismatch in the inlet and exhaust nodes, we instead see these other strange errors much further downstream in the simulation.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.3
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Hmmm, I don't see how the EMS variable error could be related. Does this file run without that error if you correct the node name?

**Comment by mjwitte** [comment]
Noting here that the AirloopHVAC:UnitarySystem is used a zone equipment in this file.

**Comment by ajscimone** [comment]
No, I don't think this is related to the EMS variable error. I think this is some sort of parsing failure for Unitary System. Yes, the file will run correctly if you correct the name of the node. However, Unitary System is supposed to check its input and exhaust nodes and make sure they are hooked up correctly. This is somehow taking a decision path in that code that is not hitting the throw error, and instead moving on with the simulation with faulty objects.
