### ISSUE TITLE
Incorrect interpolations for weather data outputs at the first few sub-hour time step stamps

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8313]
Issue overview
--------------
In calculating the sub-hour time step values for the weather data, for the few time stamps prior to Hour 1, the code uses the values spot for Hour 1 and Hour 24 in the weather file for interpolation. Therefore, for the sub-hour time step interpretation, the few first hour values are actually interpolated using the first hour weather data and the 24th hour weather data (about one day later). There are many valid situations that the spot values at Hour 1 and Hour 1 to interpolate (therefore the sub-hour time steps should expect the same values as the spot value at Hour 1). 

This issue is currently for every single simulation case with sub-hour weather data output. It will impact nearly all the output weather variables. On the other hand, it only occurs for the first entry of the simulation time range (i.e. the starting hour of a simulation environment). To the user, this bug makes the first the first few interpolated weather output data hard to understand in the cvs output file if when they do not agree with the spot values exactly at Hour 1. 

The code should be fixed using the first hour data itself to do the interpretation. After the fix, the sub-hour time step outputs should have the same values as the exact Hour 1 weather data values. 

### Details
Some additional details for this issue (if relevant):
 - Platform (All Operating systems, all versions)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
I'm not convinced this is an error. I'll have to look at the source code (and history) more closely. My memory (from many years ago) is that we want to use the hour 24 data, because the first day is repeated for warmup, so this gives the same pattern for hour 1 for warmup days 1 and 2 and so on.

**Comment by EnergyArchmage** [comment]
Perhaps this could be resolved by adding a new user input to control desired behavior.  A modeler doing a simulation of more than one year could very well want the interpolation changed to what is suggested here.  While usual EnergyPlus practice of repeating first day as warm up would be better off with current practice I believe.  Adding an input switch could allow both options. 

I forget if the weather files are artificially smoothed across the Dec-Jan month change as they are for the other months.

**Comment by mjwitte** [comment]
@jcyuan2020 I agree with @EnergyArchmage that the best solution is to add an option. This method has been in place for a long time (since 2012). Looking at the blame history in the archive it was set to hour 1 when the comment was added and then shortly after changed to grab hour 24. Given we don't know the history now, adding an option to use hour 1 should satisfy users who care about this. I haven't though about where that option should go in the idd, but please propose something in https://github.com/NREL/EnergyPlus/pull/8314.
