### ISSUE TITLE
Bug in TDD related calculations in CalcInteriorSolarDistribution

### ISSUE THREAD

**Issue by xuanluo113** [NREL/EnergyPlus#8356]
Issue overview
--------------
Three potential bugs in TDD related calculations in `CalcInteriorSolarDistribution`.

1. The reporting at the end of the function starts a new surface loop, but the CosInc [here](https://github.com/NREL/EnergyPlus/blob/f37f9762f1d98546443addfdbd0afd539b5ac8b9/src/EnergyPlus/SolarShading.cc#L8195) is not re-calculated. The value, CosInc(Surfnum), used here is always the last calculated value for the last surface in the previous loop.

2. There are multiple special calculations (that are supposed to happen) for TDD Diffusers in the calculation loop ([branch 1](https://github.com/NREL/EnergyPlus/blob/f37f9762f1d98546443addfdbd0afd539b5ac8b9/src/EnergyPlus/SolarShading.cc#L6387), [branch 2](https://github.com/NREL/EnergyPlus/blob/f37f9762f1d98546443addfdbd0afd539b5ac8b9/src/EnergyPlus/SolarShading.cc#L6815), [branch 3](https://github.com/NREL/EnergyPlus/blob/f37f9762f1d98546443addfdbd0afd539b5ac8b9/src/EnergyPlus/SolarShading.cc#L7015), [branch 4](https://github.com/NREL/EnergyPlus/blob/f37f9762f1d98546443addfdbd0afd539b5ac8b9/src/EnergyPlus/SolarShading.cc#L7046)), but Diffusers are not `ExtSolar` surface, and they get bypassed after this [line](https://github.com/NREL/EnergyPlus/blob/f37f9762f1d98546443addfdbd0afd539b5ac8b9/src/EnergyPlus/SolarShading.cc#L6334).

3. The branch [here](https://github.com/NREL/EnergyPlus/blob/f37f9762f1d98546443addfdbd0afd539b5ac8b9/src/EnergyPlus/SolarShading.cc#L6822) for TDD dome can never be reached as it's under an `else if` condition of `SurfWinWindowModelType(SurfNum) != WindowBSDFModel && SurfWinWindowModelType(SurfNum) != WindowEQLModel`, which also applies to TDD Domes.

**Defect file**: testfiles/DaylightingDeviceTubular.idf

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@xuanluo113 All true.
1. This has been broken since these calculations were first added in 2003.
2. This has been broken since 2010. Would it work to set `ExtSolar = true` for TDD_Diffuser? But that could have unwanted side effects. It can't be set on input, because that would be an error (Sunlit = Yes on an interior surface), but maybe it could be set internally.
3. This has been broken since 2012. TDD_Diffuser and TDD_Dome need to be first.

**Comment by xuanluo113** [comment]
@mjwitte Thanks.

2. `ExtSolar` is fixed by adding an `&&` clause, the previous check of `if (((Surface(SurfNum).ExtBoundCond != ExternalEnvironment) && (Surface(SurfNum).ExtBoundCond != OtherSideCondModeledExt)) &&
                    SurfWinOriginalClass(SurfNum) != SurfaceClass_TDD_Diffuser)` is deleted since duplicated.

3. The branch is reordered. Regular windows and EQL windows are merged as they seem to have identical calculations.

Tested with `DaylightingDevicesTubular.idf` and `DaylightingDeviceShelf.idf` to make sure the branches get visited. Diffs are expected. (Although not seen for `DaylightingDeviceShelf.idf` in CI)

2 and 3 are temporary fixes. The TDD branches could be sorted out of the loop later.
