### ISSUE TITLE
Suggest a few tweaks on Github Actions

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#8357]
Now that we are using Github Actions, there are many possibilities.  There are also already a few things I'd like to fix up.

- [x] Need to tweak the add-path stuff to properly set the path to the miktex and qtifw binaries
- [x] Something still goes wrong sometimes while trying to install miktex.  It's nothing we are doing, just a communication error.  I think we may need to investigate an alternative miktex install approach.
- [x] We should try to collapse the two Windows builds into a matrix, maybe even moving all the package builds to a matrix if it is reasonable.
- Maybe other things, but that alone would help.

@jmarrec care to take a crack at some of this?

**Comment by jmarrec** [comment]
Seems like it's always a specific mirror repo `mirror.koddos.net` that's unreliable. I'm going to pin the repo we use, that should avoid this kind of problems. There's a problem with the chocolatey miktex recipe, I fixed it in https://github.com/teknowledgist/Chocolatey-packages/pull/40 but that doesn't update the released recipe though...
