### ISSUE TITLE
9.4 Transition Issue

### ISSUE THREAD

**Issue by bonnema** [NREL/EnergyPlus#8362]
Issue overview
--------------
_Output Variable or Meter Name_ field in `Meter:CustomDecrement` object is not properly transitioned and causes a fatal error if it requires the new **Electric Energy** -> **Electricity Energy** change.

### 9.3 Object
```
Meter:CustomDecrement,
 Electricity,                            !- Resource Type
 InteriorEquipment:Electricity,          !- Source Meter Name
 Core_bottom_Elevators_Equip,            !- Key Name 1
 Electric Equipment Electric Energy;     !- Output Variable or Meter Name 1
```
### What 9.4 Object _SHOULD_ Look Like
```
Meter:CustomDecrement,
 Electricity,                            !- Resource Type
 InteriorEquipment:Electricity,          !- Source Meter Name
 Core_bottom_Elevators_Equip,            !- Key Name 1
 Electric Equipment Electricity Energy;  !- Output Variable or Meter Name 1
```

**Comment by mjwitte** [comment]
@bonnema Electric *Energy* should transition to Electricity *Energy*, not rate.

**Comment by bonnema** [comment]
> @bonnema Electric _Energy_ should transition to Electricity _Energy_, not rate.
Correct. Sorry. I'll edit the issue to reflect this.

**Comment by mjwitte** [comment]
That said, we fixed some things at the last minute. Are you using the final release version of transition? (Not the IDD Freeze version.)

**Comment by bonnema** [comment]
I am using the release (https://github.com/NREL/EnergyPlus/releases/download/v9.4.0/EnergyPlus-9.4.0-998c4b761e-Windows-x86_64.exe). FWIW, I rarely use a non-release transition because I am too lazy to build it unless I have to :grinning:. Here is the error post-transition and prior to my manual fix.
```
Program Version,EnergyPlus, Version 9.4.0-998c4b761e, YMD=2020.10.30 13:47,
(...)
   ** Warning ** Meter:CustomDecrement="WIRED_INT_EQUIP", invalid Output Variable or Meter Name="ELECTRIC EQUIPMENT ELECTRIC ENERGY".
   **   ~~~   ** ...will not be shown with the Meter results.
   ** Warning ** Meter:CustomDecrement="WIRED_INT_EQUIP", no items assigned 
   **   ~~~   ** ...will not be shown with the Meter results
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ************* All Return Air Paths passed integrity testing
   ************* No node connection errors were found.
   ************* Beginning Simulation
   **  Fatal  ** Non-electricity meter used for TRANSFORMER 1
```
This can be replicated using the DOE Prototype Medium Office (https://www.energycodes.gov/development/commercial/prototype_models)

**Comment by mitchute** [comment]
Merry (early) Christmas, @mjwitte. This issue is the gift that keeps on giving.

**Comment by bonnema** [comment]
> Merry (early) Christmas, @mjwitte. This issue is the gift that keeps on giving.

😆 If it makes you feel any better I think this is a fringe case that slipped though the cracks...

**Comment by mjwitte** [comment]
Bah humbug! @mitchute

**Comment by mjwitte** [comment]
@dareumnam The code changes look ok, but I would feel better about this if the test file actually ran without errors in 9.3, failed with release 9.4 transition, and run without errors in 9.4 with this transition.

**Comment by dareumnam** [comment]
@mjwitte I got it. I'll test using the DOE Prototype Medium Office idf file mentioned above.

**Comment by mjwitte** [comment]
The file you were using is fine, it just needs some tweaks to use valid meter names and to avoid duplicate object names (in the demand manager objects if I remember correctly).

**Comment by dareumnam** [comment]
@mjwitte I modified the file to use valid meter names and to avoid duplicate object names so that it runs without errors on 9.3 release. I confirmed that the test file ran without errors in 9.3, failed with release 9.4 transition (the exact same error message that Eric mentioned above, like below), and ran without errors in 9.4 with #8366 transition. Please take a look and let me know what you think.
[Modified_9_3_ASHRAE901_OfficeMedium_STD2019_Denver.idf.txt](https://github.com/NREL/EnergyPlus/files/5597950/Modified_9_3_ASHRAE901_OfficeMedium_STD2019_Denver.idf.txt)
[Modified_9_4_ASHRAE901_OfficeMedium_STD2019_Denver.idf.txt](https://github.com/NREL/EnergyPlus/files/5597951/Modified_9_4_ASHRAE901_OfficeMedium_STD2019_Denver.idf.txt)
[Modified_8366_ASHRAE901_OfficeMedium_STD2019_Denver.idf.txt](https://github.com/NREL/EnergyPlus/files/5597953/Modified_8366_ASHRAE901_OfficeMedium_STD2019_Denver.idf.txt)

```
Program Version,EnergyPlus, Version 9.4.0-998c4b761e, YMD=2020.11.25 09:07,
(...)
   ** Warning ** Meter:CustomDecrement="WIRED_INT_EQUIP", invalid Output Variable or Meter Name="ELECTRIC EQUIPMENT ELECTRIC ENERGY".
   **   ~~~   ** ...will not be shown with the Meter results.
   ** Warning ** Meter:CustomDecrement="WIRED_INT_EQUIP", no items assigned 
   **   ~~~   ** ...will not be shown with the Meter results
   ************* Testing Individual Branch Integrity
   ************* All Branches passed integrity testing
   ************* Testing Individual Supply Air Path Integrity
   ************* All Supply Air Paths passed integrity testing
   ************* Testing Individual Return Air Path Integrity
   ************* All Return Air Paths passed integrity testing
   ************* No node connection errors were found.
   ************* Beginning Simulation
   **  Fatal  ** Non-electricity meter used for TRANSFORMER 1
```

**Comment by mjwitte** [comment]
@dareumnam Excellent - thanks!
