### ISSUE TITLE
on_begin_timestep_before_predictor() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by nvskumar-m** [NREL/EnergyPlus#8363]
Issue overview
--------------
Hi @Myoldmopar 

AN EP PythonPlugin script that worked in EP version9.3 version is throwing error "on_begin_timestep_before_predictor() takes 1 positional argument but 2 were given" in EP version 9.4.

### Details
As you can see in the image attached here, only "self" has been declared.
![Screenshot 2020-11-01 195637](https://user-images.githubusercontent.com/54622340/97805542-cd405580-1c7c-11eb-8d53-f08ac38e1876.jpg)

Please let me know if I missed something.

Thank you

**Comment by Myoldmopar** [comment]
There are some breaking API changes that are listed in the README, release notes, and documentation for 9.4.0.  The API function callbacks now need to accept a `state` argument which then needs to be passed into any other function calls made to the API.  For this plugin, just add `state` as a second argument to this overridden function, and then if you make any calls to get sensor data, read API data, write actuator data, you'll need to pass state in as the first argument.  API changes like this are going to be very rare, but this was an important change to make early in this development.
