### ISSUE TITLE
Incorrect transition of RoomAir:Node:AirflowNetwork:HVACEquipment from v9.2 to v9.3

### ISSUE THREAD

**Issue by hongyuanjia** [NREL/EnergyPlus#8372]
In EnergyPlus v9.3, class `AirTerminal:SingleDuct:Uncontrolled` has been converted to new class `AirTerminal:SingleDuct:ConstantVolume:NoReheat`. Looking through the corresponding transition code, I found that class `RoomAir:Node:AirflowNetwork:HVACEquipment` may not be treated correctly:

https://github.com/NREL/EnergyPlus/blob/74959091b81f488c791470fd5773fd24745aa2b4/src/Transition/CreateNewIDFUsingRulesV9_3_0.f90#L685-L702

The code above basically tries to append the original `AirTerminal:SingleDuct:Uncontrolled` node with suffix ` ATInlet` starting from 2nd field. However, according to IDD v9.2, the 2nd field is a choice field which can be `AirTerminal:SingleDuct:Uncontrolled`, and there is no way that any fields can be a node. The code above will do nothing if an `AirTerminal:SingleDuct:Uncontrolled` is referenced in Field 2 and Field 3.

```
#   1: Name
#   2: ZoneHVAC or Air Terminal Equipment Object Type 1
#   3: ZoneHVAC or Air Terminal Equipment Object Name 1
#   4: Fraction of Output or Supply Air from HVAC Equipment 1
#   5: Fraction of Input or Return Air to HVAC Equipment 1
#    ......
```

The proper way to transition this class is to follow the same logic as in the `ZoneHVAC:EquipmentList`:

https://github.com/NREL/EnergyPlus/blob/74959091b81f488c791470fd5773fd24745aa2b4/src/Transition/CreateNewIDFUsingRulesV9_3_0.f90#L473-L489

Hope above helps.

### Details

Some additional details for this issue (if relevant):
 - Version of EnergyPlus 9.2.0 to **9.3.0**

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file: https://github.com/NREL/EnergyPlusDevSupport/blob/ec4052601eebe20b3f9bf1bb59bd85866a9f5d53/DefectFiles/8000s/8372/RoomAirflowNetwork_mod.idf
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@hongyuanjia If you have a file with this combination of objects that can be used for testing, that would be appreciated.

**Comment by jmarrec** [comment]
@hongyuanjia Do you have a file please.?

**Comment by hongyuanjia** [comment]
@jmarrec, I modified the example file RoomAirflowNetwork.idf to include the case I mentioned.

[RoomAirflowNetwork.idf.txt](https://github.com/NREL/EnergyPlus/files/5647241/RoomAirflowNetwork.idf.txt)

**Comment by jmarrec** [comment]
@hongyuanjia Thank you!

I added the details and checklist from the issue template to your original post.
