### ISSUE TITLE
Building Material Properties for HAMT calculations

### ISSUE THREAD

**Issue by nvskumar-m** [NREL/EnergyPlus#8373]
Issue overview
--------------
I have been searching for hygrothermal properties of building materials for Heat and Moisture Transfer calculations in EnergyPlus. Although I found few sources, the properties detailed are not similar to the inputs requested by EP MaterialProperty:HeatAndMoistureTransfer objects. Can someone suggest the appropriate sources for data?

**Comment by jmarrec** [comment]
This type of question is more suited to be asked on https://unmethours.com where you will find help and support from the community, thank you!
