### ISSUE TITLE
EnergyPlus with option --expandobjects set fails when working directory is not on the same device as the output directory (on Linux)

### ISSUE THREAD

**Issue by MaximilianAzendorf** [NREL/EnergyPlus#8376]
Issue overview
--------------
ExpandObjects writes two files named expanded.idf and expandedidf.err into the working directory and then moves them (via rename() unix syscall) into the output directory. This does not work if the working directory is not on the same device as the output directory (e.g. a working directory in /tmp while the output directory is under an externally mounted /home).

### Details
Some additional details for this issue (if relevant):
 - Platform: Arch Linux x64 (linux 5.9.4)
 - Version of EnergyPlus: 9.4.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
@MaximilianAzendorf Thanks for the issue report.

This the Fortran `OPEN` command that is indeed used to create the file.

https://github.com/NREL/EnergyPlus/blob/4e2af181c66c3a55748df2f7167ae5aae41a7e15/src/ExpandObjects/epfilter.f90#L1935-L1962

The CLI will then move it via `moveFile`: https://github.com/NREL/EnergyPlus/blob/734af19f9a7fc87715a5078c529a4083d2dff7ce/src/EnergyPlus/CommandLineInterface.cc#L560-L588

`moveFile` does indeed use a `rename` syscall on Unix: https://github.com/NREL/EnergyPlus/blob/734af19f9a7fc87715a5078c529a4083d2dff7ce/src/EnergyPlus/FileSystem.cc#L258-L266
