### ISSUE TITLE
Add CI tests to ensure each CPP macro condition works

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#8377]
Issue overview
--------------
It might be good to add some CI tests to compile with other than the default set of switches for the CPP macros to ensure that code change continue to work. I recently tried compiling with EP_cache_PsyTsatFnPb not defined and EnergyPlus does not compile. This may also exist for other of the CPP macros.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
@Myoldmopar and @mitchute should this issue still be open? I thought that the alternate build configurations handled this.

**Comment by mitchute** [comment]
I think we can close it. https://github.com/NREL/EnergyPlus/pull/8521 is one example of how this has been addressed, but there are others.
