### ISSUE TITLE
Update energyplus.net/downloads to reference correct supported platforms

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#8395]
Issue overview
--------------

Linux at least is outdated. Found while closing https://github.com/NREL/EnergyPlus/issues/5950

![image](https://user-images.githubusercontent.com/5479063/100427769-3dcb6e00-3093-11eb-808b-cb083dabf595.png)

**Comment by mitchute** [comment]
Current status

![Screen Shot 2021-06-01 at 11 13 19 AM](https://user-images.githubusercontent.com/2985979/120364351-60e90b80-c2ca-11eb-812c-3d765b749ece.png)

Do we need to do more here? Any point in noting that Mac OS 11 is also supported?

@Myoldmopar @jmarrec

**Comment by bonnema** [comment]
Related to #8763 also.

**Comment by mitchute** [comment]
I ran a basic test using 9.5 on my OS 11.4 Mac with an Intel chip and it worked just fine. I'm closing this for now since we don't have any way to "officially" support anything above 10.15. The current release page looks great.
