### ISSUE TITLE
building project "energyplusapi.vcxproj" -- FAILED

### ISSUE THREAD

**Issue by sekaina** [NREL/EnergyPlus#8418]
I'm trying to build EnergyPlus in visual studio. I've followed all the steps in Wiki but building project "energyplusapi.vcxproj" -- FAILED and I get this error :

> MSB3073	The command "setlocal
> "C:\Program Files (x86)\CMake\bin\cmake.exe" -DREPO_ROOT=C:/Users/elkhatts/Downloads/EnergyPlus-develop -DEXECUTABLE_PATH=C:/Users/elkhatts/Downloads/EnergyPlus-develop/build/Products/Release/energyplusapi.dll -DCMAKE_VERSION_MAJOR="9" -DCMAKE_VERSION_MINOR="4" -DCMAKE_VERSION_PATCH="0" -DCMAKE_VERSION_BUILD="Unknown" -DPYTHON_API_VERSION_MAJOR="0" -DPYTHON_API_VERSION_MINOR="2" -P C:/Users/elkhatts/Downloads/EnergyPlus-develop/cmake/PythonSetupAPIinBuild.cmake
> if %errorlevel% neq 0 goto :cmEnd
> :cmEnd
> endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
> :cmErrorLevel
> exit /b %1
> :cmDone
> if %errorlevel% neq 0 goto :VCEnd
> setlocal
> "C:\Program Files (x86)\CMake\bin\cmake.exe" "-DRESOLVED_PYTHON_LIB=C:/Program Files (x86)/Microsoft Visual Studio/Shared/Python37_64/libs/python37.lib" -DEXECUTABLE_PATH=C:/Users/elkhatts/Downloads/EnergyPlus-develop/build/Products/Release/energyplusapi.dll -P C:/Users/elkhatts/Downloads/EnergyPlus-develop/cmake/PythonGetLibAndLinkUp.cmake
> if %errorlevel% neq 0 goto :cmEnd
> :cmEnd
> endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
> :cmErrorLevel
> exit /b %1
> :cmDone
> if %errorlevel% neq 0 goto :VCEnd
> setlocal
> C:\Users\elkhatts\AppData\Local\Programs\Python\Python38-32\python.exe C:/Users/elkhatts/Downloads/EnergyPlus-develop/cmake/PythonCopyStandardLib.py C:/Users/elkhatts/Downloads/EnergyPlus-develop/build/Products/Release/energyplusapi.dll python_standard_lib
> if %errorlevel% neq 0 goto :cmEnd
> :cmEnd
> endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
> :cmErrorLevel
> exit /b %1
> :cmDone
> if %errorlevel% neq 0 goto :VCEnd
> :VCEnd" exited with code 3.
> 
I'm beginner that's why I don't know how to deal with this issue. 
Can anyone help me ?
Thank you !

**Comment by jmarrec** [comment]
@sekaina In your Cmake configuration, is `LINK_WITH_PYTHON=OFF`? There was a recent problem on develop, where building with `LINK_WITH_PYTHON=OFF` wasn't working, perhaps that's it.

Note: https://unmethours.com/question/49595/building-project-energyplusapivcxproj-failed/

**Comment by sekaina** [comment]
Thank you for your help ! That's exactly what I've missed.

**Comment by jmarrec** [comment]
@sekaina you're welcome. And you didn't "miss" anything, it should have worked with link with python set to off.

Could you tell me which commit you are building please? I think that @mitchute should have fixed that problem in https://github.com/NREL/EnergyPlus/pull/8378

**Comment by sekaina** [comment]
I'm not sure I understood your question correctly (I'm new to programming and github). I intend to make modifications in the source code of energyplus so that it can take into account fractions in window shading control (instead of shades being either fully open or fully closed). So, first I build the original code to make sure that all is well and then I will see how to make modifications. Do you know if anyone has already made such modifications?
Thank you so much

**Comment by jmarrec** [comment]
My question is which commit did you check out. I aim to check whether #8378 was already pulled inside develop or not, since it should have fixed the issue you encountered. At the root of the energyplus repo, can you type this?

```
cd /path/to/EnergyPlus
git rev-parse HEAD

de5717264117424151ea2838f8d1c323365d99cc
```

If you are using a git GUI client (Github for Desktop, Sourcetree, Gitkraken) you can also find the same information easily.

**Comment by sekaina** [comment]
Sorry but I didn't download it as a repository ( I've downloaded the code in ZIP format). Is there another way to check which commit ?

**Comment by jmarrec** [comment]
Where did you get the zip, and did you acquire the code more than 12 days ago?

**Comment by sekaina** [comment]
I've got the code from github (branch develop) more than a month ago

**Comment by jmarrec** [comment]
ok thank you, that explains why you hit the issue that has been fixed since then. (I would recommend you use git to clone the repo and start off the latest code)

**Comment by sekaina** [comment]
Ok thank you very much !
