### ISSUE TITLE
Error Message when an Outdoor Air Reset Manager second reset rule Schedule returns a value other than 1 or 2

### ISSUE THREAD

**Issue by jeannieboef** [NREL/EnergyPlus#8424]
Issue overview
--------------
Please have the program issue a Fatal with message when the Outdoor Air Reset Manager second reset rule Schedule returns a value other than 1 or 2. Only the values 1 or 2 are allowed.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - EnergyPlus 8.9
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.

**Comment by RKStrand** [comment]
This is still an issue in 22.1.  Basically, the docs say it must be 1 or 2.  In practice, in the code, if it isn't 2, then it is assumed to be 1.  While not a huge problem, the code should match the docs and there should be some checks within the code to avoid unintended consequences.
