### ISSUE TITLE
FileSystem unit test fails spuriously

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#8430]
Happens just every once in a while.

https://github.com/NREL/EnergyPlus/pull/8427#commitcomment-45234748

![image](https://user-images.githubusercontent.com/849824/102622438-a0e67880-4106-11eb-9614-f2c6bf1998df.png)

It's not reproducible, and our maintenance of file system operations could be eliminated by moving to the standard C++ file system library.

**Comment by jmarrec** [comment]
Fixed via #8480
