### ISSUE TITLE
epJSON input file generated by converting an IDF triggers fatal simulation errors

### ISSUE THREAD

**Issue by lymereJ** [NREL/EnergyPlus#8441]
Issue overview
--------------
Running simulations for input files in the epJSON format that have been generated by converting IDF files can lead to fatal errors. The reason appears to be that fields that have a default value in EnergyPlus, and that are not explicitly specified in the IDF file used as the basis for the conversion to the epJSON format, are not present in the converted epJSON file.

For example, in the attached IDF file the `Central Cooling Capacity Control Method` and `Heating Design Capacity Method` fields in the `Sizing:System` objects aren't specified. The converted epJSON file does not include these fields, and as a result it triggers a fatal simulation error. If one specifies the default value for these fields in the epJSON file (`"central_cooling_capacity_control_method": "OnOff"` and `"heating_design_capacity_method": "None"`), the simulation runs successfully.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10.
 - Version of EnergyPlus:  9.4

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [defect_files.zip](https://github.com/NREL/EnergyPlus/files/5752674/defect_files.zip)

**Comment by mjwitte** [comment]
Fixed in #8661.
