### ISSUE TITLE
License checking does not check Python code

### ISSUE THREAD

**Issue by jasondegraw** [NREL/EnergyPlus#8446]
Issue overview
--------------
The current license checking script does not check Python code (nothing outside of C/C++ is checked). As more Python is added, we should fix that. Some of the scripts live in the source tree now, so those will get found. What other locations should we add to the search? The entire scripts directory? Is there anything that should be skipped? 

### Details
This is a dev/repo issue. 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
In the cmake root directory there are a couple Python worker scripts.  They are just used in the build process and not anything we distribute.  Is that something we also want to license?  I only ask because if so, should we also add the license checking to all the CMake rules?

**Comment by jasondegraw** [comment]
@Myoldmopar I don't think I've ever seen build files with copyright info in them, which probably doesn't mean all that much as it wouldn't have been why I was looking at the file. I guess I'd say "no" for CMake rules but "yes" for Python, but that's really only a personal preference. Probably needs to be an NREL call.

Most of the `scripts` directory makes sense, I guess `workflows` as well, let me know about the build files. I've already got a version that checks the Python working, extending it to do the build files will be bit more of a challenge but it should be doable.

**Comment by Myoldmopar** [comment]
Concur, no for CMake rules and macros, but yes for Python.
