### ISSUE TITLE
Air-Source Heat Pumps (reqested since 2019) is:NewFeatureRequest

### ISSUE THREAD

**Issue by jeannieboef** [NREL/EnergyPlus#8449]
Issue overview
--------------
So the Fluid Cooler can only cool. Amazing. I assumed it was a heat exchanger that could do both. I was wrong. The  ground source heat exchanger is really the only realistic option for a reversible heat pump? That’s pretty disappointing considering that air to water heat pumps for heating are by far the most popular method of building compliance to the energy code in Germany. The reversible cooling effect is just nice to have.

If I walk around the block, every new home post 2016 has this tech. The only exceptions are solar thermal for room heating or ground source heat…and these too are far less prevalent.

I just checked the feature request pdfs and since 2019 Air-Source Heat Pumps have been on the list. There is a note on the 2021 list “(1) Recent component model additions should handle this, and if not, a workaround should be possible”

Please provide for a working system. I need to tell clients that we can't simulate this and it's a little weird. What workaround is the standard for an air source heat pump for hotwater heating applications?

Best regards,

Jean

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Have you tried the `HeatPump:PlantLoop:EIR:Heating (and Cooling)`?  They provide air source water [heating](https://github.com/NREL/EnergyPlus/blob/637ea911c08986d9ffe0df06e7140b819888ed02/testfiles/PlantLoopHeatPump_EIR_AirSource.idf#L261-L276) and [cooling](https://github.com/NREL/EnergyPlus/blob/637ea911c08986d9ffe0df06e7140b819888ed02/testfiles/PlantLoopHeatPump_EIR_AirSource.idf#L420-L435).

**Comment by jeannieboef** [comment]
No I have not. Thanks.
