### ISSUE TITLE
UtilityCost:Variable type list error and mismatch

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8455]
Issue overview
--------------
UtilityCost:Variable have listed type "Power" (among "Energy", "Power", "Dimensionless", and "Currency") in the Energy+.idd file; however, in the source code it accepts "Demand" rather than "Power". The I/O references list the option as "Demand" (among "Energy", "Demand", "Currency", and "Dimensionless"). 

This mismatch will cause a JSON schema rejection when inputting "Demand" to this field in an .idf file; and a rejection by the input processing code sections when inputting "Power". In neither way would the program run properly. Severe errors will be reported. 

This should be easy to fix by either changing the "Power" option in the .idd feeder file to "Demand", or by changing the code from "Demand" to "Power"--in the latter option a fix can still be made with some more code/doc changes. 

For the users, a temporary workaround would be manually changing the key "Power" under UtilityCostVariable->A3 to "Demand" in the Energy+.idd file. An additional step is needed to: find the "Power" in the enum list of under "UtilityCost:Variable" the Energy+.schema.epJSON and change it to "Demand" as well. In v9.4, this section is originally like this: 
```
                        "variable_type": {
                            "type": "string",
                            "enum": [
                                "",
                                "Currency",
                                "Dimensionless",
                                "Energy",
                                "Power"
                            ],
                            "default": "Dimensionless"
```
Then then change the "Power" there (on Line 191611 in v9.4) to "Demand". 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) All
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.2-9.4
 - Helpdesk ticket number 15607

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Neither the idd nor the schema file are read at runtime.  The schema is embedded into the EnergyPlus binary so a user cannot modify either idd or schema and expect any effect.

But in any case, the fix over in #8456 looks like a suitable fix for the next release.
