### ISSUE TITLE
Build error due to duplicate symbols in BCVTB utilXml

### ISSUE THREAD

**Issue by JoelStienlet** [NREL/EnergyPlus#8459]
Hello all,

I've tried to compile EnergyPlus on fedora 33, gcc version: 10.2.1 20201125, and got a linking error at the very end of the process: the linker found some duplicate symbols.
After investigation, I found that these symbols come from global variables declared in utilXml.h. This header file is then included in multiple .c files. Even if the variable is not used in the .c, the compiler still defines the symbol in the corresponding .o elf file.
That obviously lead to multiple definitions of the same symbols, hence the linking errors.
How to correct this problem IMO:
move the "local global variables" out of utilXml.h, and put them all in utilXml.c.
(Buff, expStk, att, outputVarsName, ......)
After this change, everything linked fine on my system. I haven't run any simulation yet to check that it all works as expected though.

**Comment by jmarrec** [comment]
@JoelStienlet did you open a PR with your changes? I missed this issue but bumped into the problem myself after trying to build with gcc 10 (which unlike gcc < 10 defaults to `-fno-common`), so I proposed a fix in #8522

**Comment by JoelStienlet** [comment]
Hello @jmarrec , no I didn't open a PR. Thank you for the fix!
