### ISSUE TITLE
Solar Collector efficiency

### ISSUE THREAD

**Issue by DavideLiviero** [NREL/EnergyPlus#8465]
Issue overview
--------------
Using EnergyPlus 8.4 and Design Builder v4.7 I continuously received warnings about the temperature of the fluid in the solar circuit being too high (more details [here).](https://unmethours.com/question/50598/solar-collector-temperature-out-of-range/)

Workaround
-------------
Change the efficiency equation coefficients in order to have a lower efficiency and a lower temperature within the solar circuit.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10
 - Version of EnergyPlus: EnergyPlus 8.4
 - Unmethours link: https://unmethours.com/question/50598/solar-collector-temperature-out-of-range/

**Comment by jmarrec** [comment]
@DavideLiviero You mention a "problem with the efficiency equation". it would be helpful to show us what you think is wrong so we're not running around guessing please. A side by side diff of the original equation and the corrected one, with context to back up why your version is correct would go a long way towards fixing any potential bug in a timely fashion. Thanks!

**Comment by jmarrec** [comment]
I'm closing. happy to reopen if we get enough information to address it though.
