### ISSUE TITLE
problem when add FaultModel:Fouling:EvaporativeCooler

### ISSUE THREAD

**Issue by zbb2022hust** [NREL/EnergyPlus#8467]
Issue overview
--------------
I'm adding fault model, the foul in Evaporative Cooler. But when I selected the chiller, the severe reminded me that the Evaporative Cooler Object Name of this chiller can not be found. I checked the InputOutputreference but can't find detailed description of this fault. I wonder know whether the wetted coil evaporative cooler is.

### Details

error:

```
   ** Severe  ** FaultModel:Fouling:EvaporativeCooler = "1A" invalid Evaporative Cooler Object Name = "WATERCOOLED ROTARY SCREW CHILLER 600-9999TONS 0.6KW/TON" not found.
   ** Severe  ** FaultModel:Fouling:EvaporativeCooler = "1B" invalid Evaporative Cooler Object Name = "WATERCOOLED ROTARY SCREW CHILLER 600-9999TONS 0.6KW/TON 1" not found.
   ** Severe  ** FaultModel:Fouling:EvaporativeCooler = "1C" invalid Evaporative Cooler Object Name = "WATERCOOLED ROTARY SCREW CHILLER 600-9999TONS 0.6KW/TON 2" not found.
   **  Fatal  ** CheckAndReadFaults: Errors found in getting FaultModel input data. Preceding condition(s) cause termination.
```

![Snipaste_2021-01-14_22-04-41](https://user-images.githubusercontent.com/61374634/104600664-406e3b00-56b4-11eb-89dd-eca36895dd1f.jpg)

**Comment by zbb2022hust** [comment]
![Snipaste_2021-01-14_22-04-41](https://user-images.githubusercontent.com/61374634/104600862-83c8a980-56b4-11eb-981a-d7718d6c652e.jpg)

**Comment by jmarrec** [comment]
@zjx2020 please provide your input file.
