### ISSUE TITLE
Missing Step in Conduction Transfer Function Calculation

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#8472]
Issue overview
--------------
During a review of the EnergyPlus code that uses the state space method to calculate the conduction transfer functions, a user noticed that one of the steps did not match the relevant procedure as outlined in the doctoral dissertation of John Seem upon which the procedure is based.  In Seem's dissertation, on page 128, there is a four step procedure for calculating the exponential matrix.  In Step 4, the term "L" is calculated based not on the original value of the A(delta) matrix but rather the modified version of the A(delta) matrix after it has been divided by 2^k.  In the EnergyPlus code, L is based on the on the original value of the A(delta) matrix.  This is incorrect according to Seem's dissertation and should be fixed.

The user has suggested added another section of code at line 1202 of Construction.cc (click here to get there: https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Construction.cc#L1202 ) that repeats the code in lines 1166-1179 which calculates AMatRowNormMax.  It may be possible (though this should be checked as part of the fix) to simply adjust AMatRowNormMax by the same factor as was used to update AMat1 with a single assignment statement.  Thorough testing of this will be needed to make sure that nothing strange happens, even though it does appear that the code is wrong.  It is not anticipated that this fix will have large impacts on the results and some preliminary testing by @mitchute backs that up.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus (if using an intermediate build, include SHA): V9.4 and all previous versions

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [none needed] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@mitchute @Myoldmopar I have implemented a potential fix to this issue and am starting to look at the results.  Given that this is a change to the CTF calculations, it is not all that surprising that there are a lot of diffs.  What I can say so far, based on the limited results that I have looked at, is that in general most differences are pretty small.  I have seen one case so far in what I have looked at where there is a seemingly large difference in a variable (happens once in the two design days).  I think it is probably because something went into setback and that sometimes trips things to operate differently because one case is just barely on one side of the setpoint and the other case is just on the other side.  So, I don't feel like the results are super surprising.

However, at this point, I am wondering if making this change is the "best" approach.  I agree with the user who found this error--the code does NOT line up with the algorithm laid out in Seem's dissertation.  So, there is definitely a disconnect.  What specifically is the disconnect?  As part of Seem's dissertation, he suggests an algorithm for calculating the exponential of a matrix in the state space formulation for calculation CTFs.  The algorithm involves calculating successive terms to add to an overall sum.  These successive terms get smaller and smaller so at some point they should be cut off.  That cutoff (the number of terms to calculate or L in Seem's dissertation) is defined by a particular equation which is taken from a publication written in the 1970s.  While I am not familiar with that article am have no reason to doubt that its suggestion was solid, I do wonder if that approach is still valid given what computers are able to accomplish in 2021 vs. 1970.  If memory serves me correct, there is another place in the CTF calculation where we based a decision on whether to continue adding more terms on something related to the number of terms available in a given level of precision variable.  In that approach, the addition of more terms was cut-off if the newest term to add to the sum was such that the new term divided by the sum was less than the precision of the variable type.  My concern is that implementing a fix that follows Seem's dissertation may unnecessarily lead to the early truncation of a calculation which would be inaccurate.  So, I guess in a nutshell what I am asking is: should we base the EnergyPlus code on a limit defined in the 1970s or one that is based on the realities of modern computer capabilities?  Maybe that's a loaded question since it kind of reveals my bias.  Or in other words, should this fix be to make the code agree with Seem's dissertation or to implement what might make more sense from a programming standpoint or just leave this alone and implement some comments in the code and some additional documentation language?

I realize that while I might understand all that I may not have made this understandable to everyone else.  In any case, I am interested in hearing what you think about this before I actually proceed with a fix.  Thanks!

**Comment by mjwitte** [comment]
@RKStrand suggested "...  or just leave this alone and implement some comments in the code and some additional documentation language?"
That would seem reasonable to me. Perhaps that is exactly why it was programmed as it is rather than truncating by the referenced method.

**Comment by RKStrand** [comment]
@mitchute @Myoldmopar I should have explained that the current code, due to an error, does actually include MORE terms than the algorithm that Seem's references from the 1970s.  To change the code to agree with Seem's dissertation, we would very likely be using FEWER terms than are currently used in EnergyPlus.  So, leaving the EnergyPlus code the way it is could be viewed as being more accurate because it uses more terms than suggested by the 1970s article.  Fixing it to agree with the 1970s article would potentially speed E+ up very slightly in the CTF calculation but might not give results that are as accurate.  So, again, I think it makes sense at this point to ask what we should do rather than should we simply implement Seem's suggestion.

**Comment by RKStrand** [comment]
@mjwitte My guess is that it was actually an oversight (mistake), rather than intentional.  But it's one of those few times where a mistake was actually preferable to what was supposed to be done.

**Comment by mitchute** [comment]
It seems reasonable to me that if this potential fix simply reduces the number of terms, which then in turn negatively affects the accuracy, then we can just proceed with a documentation-only fix. But if there's currently a problem with the method (which also negatively affects accuracy) that this would correct, then we should fix it.

**Comment by RKStrand** [comment]
There is currently no problems with the current method.  Accuracy is fine as far as I know and we've been using this equation since the beginning of EnergyPlus.  Reducing the number of terms could potentially make things less accurate.  We could increase the number of terms, but I do not have any reason to believe that this would make EnergyPlus more accurate.  I think what we would see is maybe a slight increase in computational time with a change in results (think in terms of 10-5).  Also, based on the code, there is already a check to avoid underflow problems when adding terms to the exponential matrix that are incredibly small.

In summary, changing the code to match Seem's dissertation would potentially reduce accuracy very slightly.  After 20 years of successful implementation of what is currently there and no known issues, there is no compelling reason to implement something new that might not have any benefit and potentially very slightly increase simulation time.  So, my plan is to implement a documentation-only fix that includes some additional comments in the code and add some new text to the Engineering Reference to briefly discuss the solution procedure outlined by Seem and how EnergyPlus differs from that.  That should address the concern identified by the user and also better document this for the future.

**Comment by RKStrand** [comment]
@mitchute @mjwitte Ok, I've implemented the changes requested as per the comments above, merged in develop, and committed it all.  Should be ready for further inspection whenever you are able to get to it.  Thanks!
