### ISSUE TITLE
EMS actuator for View Factor to Ground

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#8476]
Issue overview
--------------
The [Engineering documentation for the Shading Module states](https://bigladdersoftware.com/epx/docs/9-4/engineering-reference/shading-module.html#solar-gains-000), "Shading of ground diffuse solar radiation is not calculated by the program. It is up to the user to estimate the effect of this shading and modify the input value of Fsg accordingly."

As noted [here](https://github.com/NREL/EnergyPlus/issues/4278), this value is entered as the Surface/Subsurface View Factor to Ground. However, this is a constant value and cannot vary throughout the year. There can be situations where one would like to vary this value.

We propose to create an EMS actuator that allows the value to be dynamically calculated.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
@bpark1327 is working on this.

**Comment by mjwitte** [comment]
@shorowit Actually, when the Solar Distribution option include "WithReflections", the ground diffuse does include shading effects. See I/O Reference. This is still a useful actuator for other reasons, but I had forgotten about WithReflections. The engineering reference might need an update to note that.

**Comment by shorowit** [comment]
Good point, @mjwitte.
