### ISSUE TITLE
 [pyenergyplus] system exit called when energyplus can't run

### ISSUE THREAD

**Issue by antoine-galataud** [NREL/EnergyPlus#8483]
Issue overview
--------------

When invalid arguments prevent EnergyPlus binary from running, system exit (1) is called and api caller program is interrupted.

Example:

```python
from pyenergyplus.api import EnergyPlusAPI

if __name__ == "__main__":
    api = EnergyPlusAPI()
    exit_code = api.runtime.run_energyplus(api.state_manager.new_state(), "wrong")
    print("exit:", exit_code)
```

Output is:

```
ERROR: Multiple input files specified:
  Input file #1: w
  Input file #2: r
  Input file #3: o
  Input file #4: n
  Input file #5: g
Type 'energyplus --help' for usage.
```

then script exists with code 1. Last print statement isn't executed.

In library mode, the caller program should be responsible for calling system exit.

### Details
 - Platform: Ubuntu 20.04 LTS
 - Version of EnergyPlus: v9.4.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I find this really annoying too. It kills my jupyter notebook whenever it doesn't work, which defeats the purpose of using a notebook.
