### ISSUE TITLE
IDFVersionUpdater for Mac needs to be updated

### ISSUE THREAD

**Issue by fishbaugher** [NREL/EnergyPlus#8485]
<img width="426" alt="Screen Shot 2021-01-26 at 2 20 46 PM" src="https://user-images.githubusercontent.com/479175/105913556-e0479500-5fe1-11eb-8d22-3653712560c0.png">

<img width="271" alt="Screen Shot 2021-01-26 at 2 21 04 PM" src="https://user-images.githubusercontent.com/479175/105913566-e3428580-5fe1-11eb-98ef-9f6b6eaf4fc3.png">

```
markfishbaugher@Thing-1 IDFVersionUpdater $ energyplus --version
EnergyPlus, Version 9.4.0-998c4b761e
```

**Comment by jmarrec** [comment]
Perhaps time to replace with an alternative, like https://github.com/Myoldmopar/IDFVersionUpdater2

This shares the same root cause as https://github.com/NREL/EnergyPlus/issues/7324
