### ISSUE TITLE
Airflow network doesn't allow zonal ERVs and HPWHs connections

### ISSUE THREAD

**Issue by lymereJ** [NREL/EnergyPlus#8503]
Issue overview
--------------
When modeling an airflow network (AFN), it is currently not possible to connect a zonal ERV (`ZoneHVAC:EnergyRecoveryVentilator`) and/or an HPWH. All HVAC related nodes have to be included in an AFN, however, nodes of these objects cannot be associated to an AFN as they are not part of an air loop.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.4

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
See #8698 and #8699.
