### ISSUE TITLE
Fanger thermal comfort calculation misaligned with zone air (and other) temperature values

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8516]
Issue overview
--------------
In calculating the Fanger thermal comfort values, such as PMV and PPD in a simulation run, the calculated PMV values look like if it is one time-step behind the corresponding temperature values (such as zone air temperature or zone radiant temperature). This is especially the case when the air temperature in a zone abruptly changes (e.g. when the thermostat setpoint changes). 

![image](https://user-images.githubusercontent.com/64040111/110336789-d48cbc80-7fea-11eb-8e81-ccf332b9682e.png)

 
The cause of the problem is that the calculation module uses as a saved zone air temperature value for the previous time step, which causes the calculated PMV lagging behind. The calculated PMV value is thus off from what is “supposed” to be, depending on how quickly the zone air temperature changes. 

There is limited impact to the average users who do not need precise real-time thermal comfort information. Currently no workaround is available. The bug is expected to be fixed in future releases. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) All
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.4, probably all
 - Helpdesk ticket number 15616

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by sortiz-hub** [comment]
Do you think this issue will be included in E+ 9.5.0 release?

Thanks!

**Comment by jcyuan2020** [comment]
> 
> 
> Do you think this issue will be included in E+ 9.5.0 release?
> 
> Thanks!

Yes, the fix is in the plan to be included for the v9.5 release.
