### ISSUE TITLE
Some IDF object names can break the HTML output file

### ISSUE THREAD

**Issue by santoshphilip** [NREL/EnergyPlus#8542]
**Problem**

- The EnergyPlus objects can have legal names in the following format `Special glass <thickness is 3mm>`
-  Energyplus itself has no problems with such names
- This name turns up in the HTML output file.
    - In the HTML file the part name`<thickness is 3mm>` looks like an HTML tag.
    - The browser tries to make sense of it and fix it so that something can be displayed
    - This results in a mangled name in the HTML file as viewed in the browser

**Solution**

- Before the name goes into the HTML file, it has to be modified in the following manner
    - `Special glass <thickness is 3mm>` should become `Special glass &lt;thickness is 3mm&gt;`
    - `&lt;` becomes `<` in the browser and `&gt;` becomes `>` in the browser

### Details

Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - EnergyPlus version: current develop, circa v9.4.0-IOFreeze, ea7967b30df81996e58ea9ca0bd4c950d074e88b

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect): https://github.com/NREL/EnergyPlus/pull/8544

**Comment by jmarrec** [comment]
Thanks for the report @santoshphilip. I added the checklist to your original post.

**Comment by JasonGlazer** [comment]
The fix should also be included for the XML output file (OutputControl:Table:Style, XML) which I don't think is commonly used but would face the same issue with confused tags.

**Comment by jmarrec** [comment]
@JasonGlazer XML is fine already: https://github.com/NREL/EnergyPlus/blob/ea7967b30df81996e58ea9ca0bd4c950d074e88b/src/EnergyPlus/OutputReportTabular.cc#L14276

**Comment by JasonGlazer** [comment]
Good. To bad the author of ConvertToEscaped() didn't think of applying it to the HTML file :-)

**Comment by jmarrec** [comment]
I'm guessing it was you, but it's been there as far as this repo's git history can go (7+ years), so who knows when it was really added and what HTML looked like then :)
