### ISSUE TITLE
Remove unused Var6 in curve function

### ISSUE THREAD

**Issue by yzhou601** [NREL/EnergyPlus#8547]
Issue overview
--------------
Var6 is never used in any current type of curve. Remove it from functions can improve runtime performance. See [conversations in PR#8464](https://github.com/NREL/EnergyPlus/pull/8464#issuecomment-781529713) for more details.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
@yzhou601 was this fixed by #8464 or is there still work to be done on this?

**Comment by yzhou601** [comment]
> @yzhou601 was this fixed by #8464 or is there still work to be done on this?

@mitchute Yes, it is not resolved by #8464 because the issue is not caused by the change proposed there. This issue is opened for https://github.com/NREL/EnergyPlus/pull/8464#issuecomment-781417709. An unused var warning is thrown by function `PerformanceCurveObject` for `Optional<Real64 const> Var6`. Edwin temporarily marked it as `maybe_unused ` to get rid of the warning. He suggested taking a bit extra time to investigate whether Var6 is used anywhere, if not we can remove it in case of performance penalty.

**Comment by mitchute** [comment]
Thanks for noting that @yzhou601. Are you planning on addressing this or is it available to others?

**Comment by yzhou601** [comment]
> Thanks for noting that @yzhou601. Are you planning on addressing this or is it available to others?

It's available to others.
