### ISSUE TITLE
Floating point divide by zero exception in calcSZVAVModel with UnitarySys

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#8566]
Issue overview
--------------

Floating point divide by zero exception in calcSZVAVModel with UnitarySys. This happens (obviously) in the worst possible test on the OpenStudio-resources: the autosizing test. The goal of this test is to add **ALL HVAC objects that might be autosized** to test the autosize / getAutosizeValue methods. This test is now failing with v9.5.0-IOFreeze

```
* thread #1, name = 'energyplus', stop reason = signal SIGFPE: floating point divide by zero
    frame #0: 0x00007ffff1d8ee1d libenergyplusapi.so.9.5.0`EnergyPlus::SZVAVModel::calcSZVAVModel(state=0x00007fffffffb890, SZVAVModel=0x00005555590637c8, SysIndex=0x00005555590637d0, FirstHVACIteration=0x00007fffffff8a68, CoolingLoad=0x00005555561714c5, HeatingLoad=0x00005555561714c4, ZoneLoad=0x00007fffffff8a58, OnOffAirFlowRatio=0x00007fffffff9be8, HXUnitOn=0x00007fffffff9bb4, AirLoopNum=0x00007fffffff8a6c, PartLoadRatio=0x00007fffffff8ac8, CompressorONFlag=0x00007fffffff8a88) at SZVAVModel.cc:1197:47
   1194	            // Step 2: Load is greater then allowed in region 1, determine boundary load for region 3
   1195	            // only difference in this calculation is using maxAirMassFlow instead of minAirMassFlow, just use the ratio to adjust previous
   1196	            // calculation
-> 1197	            boundaryLoadMet *= maxAirMassFlow / minAirMassFlow;
   1198	
   1199	            if ((CoolingLoad && boundaryLoadMet < ZoneLoad) || (HeatingLoad && boundaryLoadMet > ZoneLoad)) { // in Region 2 of figure
   1200	
```

```
(lldb) p thisSys.Name
(std::string) $7 = "AIR LOOP HVAC UNITARY SYSTEM 2"
```

minAirMassFlow is zero from here: https://github.com/NREL/EnergyPlus/blob/e003a916370b9bc68fa60e39e504bd8b2ae52ca9/src/EnergyPlus/SZVAVModel.cc#L988

You need fixes in https://github.com/NREL/EnergyPlus/pull/8565 in order to make this file run.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.5.0-IOFreeze

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/commit/0222b4740a764a62b879695e9ec6e1663337e8ac
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
No load air volume flow rate never got set when the no load air flow rate method is blank or none.

**Comment by jmarrec** [comment]
@rraustad I explicitly set all three flow rate methods to "SupplyAirFlowRate" and the file doesn't crash anymore, thanks.
