### ISSUE TITLE
IORef Table of Contents Missing on Windows Packages

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#8568]
Issue overview
--------------
- [x] Rules9-4-0-to-9-5-0.md is missing from the install package. Should be in the \PreProcess\IDFVersionUpdater folder.
- [ ] The I/O Ref table of contents is missing on windows. *Building locally on Windows, the TOC is present with develop at https://github.com/NREL/EnergyPlus/commit/ad0249bc3ec63e73513039d0ac0e18e22d31649d (26 Feb 2021). The TOC is also present when I build locally using the 9.5.0-IOFreeze tag. So, is this something about the build process for packages? Or some other issue on windows CI?*
- [ ] 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
It builds fine locally, and other CI platforms produce a full IO ref.  Not sure yet, but I realize this is urgent.  I'm pinning this issue.

**Comment by Myoldmopar** [comment]
Also, after 9.5 is released, I'll post a copy of the IO ref to the release page assets, and make sure that the documentation on energyplus.net has a proper IO ref.

**Comment by mjwitte** [comment]
From @EnergyArchmage:

. . . this error message

`32>[LATEXERROR::doc\input-output-reference\src\overview\idd-conventions.tex:None::TeX capacity exceeded, sorry [main memory size=3000000].<argument> ...shipout:D \box_use:N \l_shipout_box]`

eventually led me to this https://github.com/NREL/EnergyPlus/issues/8721

**Comment by EnergyArchmage** [comment]
Actually my comment is not helpful. That pattern is everywhere. I am still stuck with IO ref problems, with docs based on 9.4.

**Comment by mjwitte** [comment]
Hmm, but maybe the memory error is still a useful clue. I seem to recall some instructions on how to increate the LaTeX memory limits?

**Comment by mitchute** [comment]
I just built the I/O Ref on my Windows VM from b2b28f60b756e9706312c25438883442396a7334. The TOC *is* present.

**Comment by EnergyArchmage** [comment]
Is the doc full length?

**Comment by mitchute** [comment]
It appears to be. 2805 pages that go through the end of Appendix A.

**Comment by jmarrec** [comment]
Is someone actively working on this one or should I?

**Comment by mitchute** [comment]
I am not. I wasn't able to duplicate it, though.

**Comment by jmarrec** [comment]
I think the primary issue is with github actions rather than locally. I do not want to dismiss @EnergyArchmage 's apparent problem, but it might be a fringe configuration issue on his machine. Hopefully investigation will fix both.

**Comment by EnergyArchmage** [comment]
I wonder if it is related to newer version of MiKTeX behaving differently that what is specified in E+ docs.  That old version is not really available anymore and when setting up a new machine I used a newer MiKTex.  But I only have problems with I/O ref.  

I also wonder about the huge numbers of warnings coming out of Latex, it doesn't feel like a finished effort.

**Comment by jmarrec** [comment]
I've been hacking at this for the past day or so, and I think I've identified the problem:

* It works with MikTex 2.9
* It does not work with MikTex 4.1+
* It is due to the main memory size exceeded
* I will fix it in our cmake, but you can change your global settings already

in a cmd.exe
```
# User one, at %Appdata%\MiKTeX\miktex\config\xelatex.in
initexmf --edit-config-file=xelatex 
# System one, at C:\ProgramData\MiKTeX\miktex\config\xelatex.in (run in elevated CMD.Exe)
initexmf --admin --edit-config-file=xelatex 
```

The file open, add this to it, then save

```
extra_mem_top = 2000000
extra_mem_bot = 4000000
```

--- 

I think the default values are from C:\Program Files\MiKTeX\miktex\config\texmfapp.ini . I was trying to gauge whether 2.9 (for eg) had different defaults than 4.1 which might explain why it worked on 2.9 but not 4.1, but I wiped my 2.9 installation...

**Comment by EnergyArchmage** [comment]
Thanks @jmarrec !  I edited my texmfapp.ini and it worked!
