### ISSUE TITLE
Airflow curve input defect in AirloopHVAC:UnitarySystem when MS DX Heating coils operate at Speed = 1

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#8580]
Issue overview
--------------
PR #8501 fixed the issue #8335 to pass correct mass flow rate to calculate flow fraction for DX cooling coil performance curves at Speed = 1. However, the same problem occurs for a MS DX heating coil at speed=1, when a UnitarySystem is used as a parent. The input values vary with node mass flow rate as show below.
![Pinture3](https://user-images.githubusercontent.com/5970656/109869610-1ad2cc00-7c37-11eb-9053-b030d3591364.png)
It is expected to get a constant input value. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #8592.
