### ISSUE TITLE
Make ComfortViewFactorAngles extensible - error extending number of surfaces

### ISSUE THREAD

**Issue by rafael-a** [NREL/EnergyPlus#8589]
Issue overview
--------------
ComfortViewFactorAngles are used to compute Thermal comfort runs accounting for the specific location of the calculation point in space. Currently, up to 20 surfaces can be specified with a correpsonding view angle which are considered in the Radiant Temperature Calculation.

I have tried to extend the number of surfaces accounted in the calculation, but E+ fails to recognise any additional one than those specified originally. See [this ](https://unmethours.com/question/52501/error-extending-number-of-surfaces-in-comfortviewfactorangles/) for more details.

Thanks,
Rafael

**Comment by mjwitte** [comment]
True, that object is not marked "extensible" in the IDD, and the input processing function `GetAngleFactorList` specifies a hard limit of 20 surfaces. This could be changed (but it's too late for v9.5 due to the required IDD change).

**Comment by rafael-a** [comment]
that's ok, it can wait for following updates. Thank you.
I managed to amend the IDD myself and have the idf editor recognise the extra fields, but the simulation still limits them.

**Comment by mjwitte** [comment]
Correct, you need to build your own version of EnergyPlus and modify both the idd and remove the hard limit in `GetAngleFactorList` to make this work. Build instructions are [here](https://github.com/NREL/EnergyPlus/wiki/BuildingEnergyPlus).

**Comment by rafael-a** [comment]
Building my own Energyplus seems a bit beyond my capabilities for now. But that's fine, I'll amend my model for this one.
