### ISSUE TITLE
EMS Actuator no change in mass flow rate.

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [NREL/EnergyPlus#8593]
Hi,

I'm trying to control both the setpoint temperature and the mass flow rate of a 5 zone HVAC system. You find the IDF here https://drive.google.com/file/d/1hjnxdoUBych6X7eQp_3Pkk6Z7VWxAoIs/view?usp=sharing or here [IDF.zip](https://github.com/NREL/EnergyPlus/files/6103497/IDF.zip)

.

I can change and the supply setpoint temperature and the overall supply mass flow rate, but I cannot change the individual zone mass flow rate.

```
     EnergyManagementSystem:Actuator,
        mdot_fan,                !- Name
        SUPPLY FAN 1,            !- Actuated Component Unique Name
        Fan,                     !- Actuated Component Type
        Fan Air mass Flow Rate;  !- Actuated Component Control Type
    
    EnergyManagementSystem:Actuator,
        T_in_air,                !- Name
        VAV SYS 1 OUTLET NODE,   !- Actuated Component Unique Name
        System Node Setpoint,    !- Actuated Component Type
        Temperature Setpoint;    !- Actuated Component Control Type
    
    EnergyManagementSystem:Actuator,
        mdot_air,                !- Name
        MIXED AIR NODE 1,        !- Actuated Component Unique Name
        System Node Setpoint,    !- Actuated Component Type
        Mass Flow Rate Setpoint; !- Actuated Component Control Type
    
    EnergyManagementSystem:Actuator,
        mdot_1,                  !- Name
        SPACE1-1 ZONE COIL AIR IN NODE,  !- Actuated Component Unique Name
        System Node Setpoint,    !- Actuated Component Type
        Mass Flow Rate Setpoint; !- Actuated Component Control Type
    
    EnergyManagementSystem:Actuator,
        mdot_2,                  !- Name
        SPACE2-1 ZONE COIL AIR IN NODE,  !- Actuated Component Unique Name
        System Node Setpoint,    !- Actuated Component Type
        Mass Flow Rate Setpoint; !- Actuated Component Control Type
    
    EnergyManagementSystem:Actuator,
        mdot_3,                  !- Name
        SPACE3-1 ZONE COIL AIR IN NODE,  !- Actuated Component Unique Name
        System Node Setpoint,    !- Actuated Component Type
        Mass Flow Rate Setpoint; !- Actuated Component Control Type
    
    EnergyManagementSystem:Actuator,
        mdot_4,                  !- Name
        SPACE4-1 ZONE COIL AIR IN NODE,  !- Actuated Component Unique Name
        System Node Setpoint,    !- Actuated Component Type
        Mass Flow Rate Setpoint; !- Actuated Component Control Type
    
    EnergyManagementSystem:Actuator,
        mdot_5,                  !- Name
        SPACE5-1 ZONE COIL AIR IN NODE,  !- Actuated Component Unique Name
        System Node Setpoint,    !- Actuated Component Type
        Mass Flow Rate Setpoint; !- Actuated Component Control Type
    
    EnergyManagementSystem:Program,
        setActions,              !- Name
        SET T_in_air = 20,       !- Program Line 1
        SET mdot_fan= mdot_1 + mdot_2 + mdot_3 + mdot_4 + mdot_5;  !- Program Line 2
    
    
    EnergyManagementSystem:Program,
        setmdot,                 !- Name
        SET mdot_1 = 0.25,       !- Program Line 1
        SET mdot_2 = 0.25,       !- Program Line 2
        SET mdot_3 = 0.25,       !- A4
        SET mdot_4 = 0.25,       !- A5
        SET mdot_5 = 0.25;       !- A6
    
    EnergyManagementSystem:ProgramCallingManager,
        mdot,                    !- Name
        InsideHVACSystemIterationLoop,  !- EnergyPlus Model Calling Point
        setmdot;                 !- Program Name 1
    
    EnergyManagementSystem:ProgramCallingManager,
        act,                     !- Name
        InsideHVACSystemIterationLoop,  !- EnergyPlus Model Calling Point
        setActions;              !- Program Name 1
```

Looking at the EDD file I see that for each zone I can use those actuators but none of them makes the change in the zone mass flow rate.
```

    SPACE1-1 IN NODE
    SPACE1-1 NODE
    SPACE1-1 OUT NODE
    SPACE1-1 ATU IN NODE
```

How can I solve this issue?
`    SPACE1-1 ZONE COIL AIR IN NODE`

--------------
Please change this line to a description of the defect, with useful supporting information including how the issue was found, conditions that trigger this defect, workarounds for users of the current version, and a clear description of how to validate that a fix is complete for this defect.

### Details
Some additional details for this issue (if relevant):
 - Platform Windows
 - Version of EnergyPlus 9.0
 - Unmethours link or helpdesk ticket number https://unmethours.com/question/52708/ems-actuator-no-change-in-mass-flow-rate/

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (https://drive.google.com/file/d/1hjnxdoUBych6X7eQp_3Pkk6Z7VWxAoIs/view?usp=sharing) 
[IDF.zip](https://github.com/NREL/EnergyPlus/files/6103500/IDF.zip)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
* In general, node mass flow rate setpoints have no effect.
* The only air terminal type that can be controlled by EMS is AirTerminal:SingleDuct:ConstantVolume:NoReheat.
* VAV SYS 1 OUTLET NODE:System Node Mass Flow Rate [kg/s](TimeStep) matches what the fan mass flow rate actuator is setting
* The unmet hours link above does not exist.
* Please test with the latest version of EnergyPlus before posting a new issue.

**Comment by LorenzoBottaccioli** [comment]
@mjwitte the unmethours link is now active it was waiting for the moderator approval. Is there any other way rather than EMS actuator for controlling the mass flow rate for every single zone?

**Comment by 1273247644** [comment]
I encountered the same problem, tried using the Python API to modify the mass flow rate at the CAV terminal in real-time, but failed. Did you eventually succeed in using the EMS actuator for control? If so, could you share your solution and experience? This would be very helpful for me in solving similar issues.
