### ISSUE TITLE
Hybrid Unitary HVAC equipment cannot be found

### ISSUE THREAD

**Issue by LipingWang** [NREL/EnergyPlus#8614]
Issue overview
--------------
The name for the object ZoneHVAC: HybridUnitaryHVAC can only be correctly recognized if it is written in capital letter from users' inputs. If small letters are part of the name for HybridUnitaryHVAC , the simulation will run into the fatal error as follows. "SimZoneHybridUnitaryAirConditioners: Zone evaporative cooler unit not found."

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.5  
 - helpdesk ticket number #15653

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
So, regardless of the case issue, the error message here is a copy/paste error and should say "ZoneHVAC: HybridUnitaryHVAC" not found.

I think I've found the reason why this is happening. In `InputProcessor::getObjectItem` all [object *names* are made uppercase](https://github.com/NREL/EnergyPlus/blob/83402156ae773d8b87568ffac3f867fe68b1910b/src/EnergyPlus/InputProcessing/InputProcessor.cc#L812-L818), but not other alpha fields.

[`GetInputZoneHybridUnitaryAirConditioners`](https://github.com/NREL/EnergyPlus/blob/83402156ae773d8b87568ffac3f867fe68b1910b/src/EnergyPlus/HybridUnitaryAirConditioners.cc#L461) uses `getObjectItem` so it's name should be uppercase. 

@LipingWang When this throws the errror, where is the call to HybridUnitaryAC coming from?
