### ISSUE TITLE
Water-cooled VRF heating mode operation

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#8687]
Issue overview
--------------
UnmetHours post should be looked into.
https://unmethours.com/question/53520/water-cooled-vrfboiler-do-not-handle-heating-load/

I figured out the cause by comparing my model and HVACTemplate-5ZoneVRF.idf in ExampleFiles.

The cause was Maximum Outdoor Temperature in Heating Mode in HVACTemplate:System:VRF. The default value is 16ºC. However, if a value that is less than 26.5ºC is input, the WaterCooled VRF doesn't heat zones even when the actual outdoor temperature is much lower than the input value. This might be a bug.

This does not occur when AirCooled is selected as Condenser Type of VRF. The value is set to 30ºC in HVACTemplate-5ZoneVRF.idf (below image), and it runs fine. My model used default 16ºC. When I changed it to 26.5ºC or higher, my model started to heat zones in winter. Conversely, when I changed the value to less than 26.5ºC in HVACTemplate-5ZoneVRF.idf, the model stopped heating.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Turns out this is working correctly. The user was confused with an input that refers to outdoor air temperature when the system is water-cooled. I am waiting on feedback from user, or others, before closing this issue.

Answer: I think the confusion might be that when the system is water-cooled, those inputs apply to the plant water temperature. Maybe the report name should be changed to Min/Max Condenser Inlet Temperature ...

    -20, !- Minimum Outdoor Temperature in Heating Mode {C}
    16, !- Maximum Outdoor Temperature in Heating Mode {C}

This is the warning I get when I run the example file using 16C Max temp in heating mode. Any suggestions for changes?

** Warning ** AirConditioner:VariableRefrigerantFlow "VRF SYS 1 WATER SOURCE VRF HEAT PUMP".
**   ~~~   ** ...InitVRF: VRF Heat Pump Min/Max Operating Temperature in Heating Mode Limits have been exceeded and VRF system is disabled.
**   ~~~   ** ... Outdoor Unit Inlet Water Temperature  = 25.0
**   ~~~   ** ... Heating Minimum Outdoor Unit Inlet Temperature = -19.99
**   ~~~   ** ... Heating Maximum Outdoor Unit Inlet Temperature = 16.0

**Comment by eringold** [comment]
@rraustad could the issue be related to this: https://github.com/NREL/EnergyPlus/issues/5163#issuecomment-468734865?

**Comment by rraustad** [comment]
I think the issue with dry-bulb vs wet-bulb for water-cooled systems was corrected over a year ago. I am just wondering if there is something else that could be done to avoid confusion in the future. It's hard for a user to figure out why the system isn't running if they don't know where to look. I assume this user didn't notice the warning in the error file so this issue may be a moot point. Changing the field name may help (i.e., condenser inlet temperature vs outdoor temperature) but is there something else? I can't think of anything.

**Comment by eringold** [comment]
Oh I see - looks like that was fixed here https://github.com/NREL/EnergyPlus/commit/732cc6dbac61b254d1b57a8d3c542653bb48977d

I agree 'condenser inlet temperature' would help avoid confusion over 'outdoor temperature' for water-cooled condensers.
