### ISSUE TITLE
HVAC Sizing Summary Thermostat Setpoint Temperature at Peak Load outputs 0C when no peak load

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#8688]
Issue overview
--------------
The HVAC Sizing Summary Zone Sensible Heating Report shows a value of 32F, or 0C, for the Thermostat Setpoint Temperature at Peak Load column when there is no peak heating load in the zone.  Option to either set this to the normal thermostat temperature during the first (or other) timestep, or have this field blank since there is no actual value since there is no peak.

![image](https://user-images.githubusercontent.com/17144687/113222666-b8c0b300-9244-11eb-8534-3eafc9e54e14.png)

[in.zip](https://github.com/NREL/EnergyPlus/files/6407939/in.zip)

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v8.5

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
There is a place in sizing where data is set if there is no heating load. I'll see if I can find that.

**Comment by rraustad** [comment]
Line 2615 of ZoneEquipmentManager in the EndZoneSizingCalc section.

    // initialize sizing conditions if they have not been set (i.e., no corresponding load) to zone condition
    if (state.dataSize->FinalZoneSizing(CtrlZoneNum).ZoneTempAtCoolPeak == 0.0) {
        // issue 6006, heating coils sizing to 0 when no heating load in zone
        if (state.dataSize->ZoneSizing(DDNumF, CtrlZoneNum).DesCoolSetPtSeq.empty()) {

and line 2813

    // initialize sizing conditions if they have not been set (i.e., no corresponding load) to zone condition
    if (state.dataSize->FinalZoneSizing(CtrlZoneNum).ZoneTempAtHeatPeak == 0.0) {
        // issue 6006, heating coils sizing to 0 when no heating load in zone
        if (state.dataSize->ZoneSizing(DDNumF, CtrlZoneNum).DesHeatSetPtSeq.empty()) {

**Comment by matthew-larson** [comment]
Thanks @rraustad, I didn't catch those sections.  I started looking at [Line 681](https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/SizingManager.cc#L681) of SizingManager.cc

```
            if (state.dataSize->FinalZoneSizing(CtrlZoneNum).DesHeatVolFlow > 0.0) {
                TimeStepAtPeak = state.dataSize->FinalZoneSizing(CtrlZoneNum).TimeStepNumAtHeatMax;
                DDNum = state.dataSize->FinalZoneSizing(CtrlZoneNum).HeatDDNum;
                if (DDNum > 0 && TimeStepAtPeak > 0) {
                    TempAtPeak = state.dataSize->DesDayWeath(DDNum).Temp(TimeStepAtPeak);
                    HumRatAtPeak = state.dataSize->DesDayWeath(DDNum).HumRat(TimeStepAtPeak);
                    DOASHeatGainRateAtHtPk = state.dataSize->CalcZoneSizing(DDNum, CtrlZoneNum).DOASHeatAddSeq(TimeStepAtPeak);
                    TStatSetPtAtPk = state.dataSize->ZoneSizing(DDNum, CtrlZoneNum).HeatTstatTempSeq(TimeStepAtPeak);
                } else {
                    TempAtPeak = 0.0;
                    HumRatAtPeak = 0.0;
                    DOASHeatGainRateAtHtPk = 0.0;
                    TStatSetPtAtPk = 0.0;
                }
```

When there is no heating peak load but still an OA requirement, `FinalZoneSizing(CtrlZoneNum).DesHeatVolFlow` is greater than 0 and `TimeStepAtPeak` ends up equalling 1, which results in `TStatSetPtAtPk` equalling 0, which is passed through to the report later in the function.  This results from `CalcZoneSizing(state.dataSize->CurOverallSimDay, ControlledZoneNum).HeatTstatTemp` never being set in [Line 657](https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/ZoneEquipmentManager.cc#L657) of ZoneEquipmentManager.cc since `CalcZoneSizing(state.dataSize->CurOverallSimDay, ControlledZoneNum).HeatLoad` is never > 0.

```
        if (state.dataSize->CalcZoneSizing(state.dataSize->CurOverallSimDay, ControlledZoneNum).HeatLoad > 0.0) {
            state.dataSize->CalcZoneSizing(state.dataSize->CurOverallSimDay, ControlledZoneNum).HeatZoneRetTemp = RetTemp;
            if (state.dataHeatBalFanSys->TempZoneThermostatSetPoint(ActualZoneNum) > 0.0) {
                state.dataSize->CalcZoneSizing(state.dataSize->CurOverallSimDay, ControlledZoneNum).HeatTstatTemp =
                    state.dataHeatBalFanSys->TempZoneThermostatSetPoint(ActualZoneNum);
            } else {
                state.dataSize->CalcZoneSizing(state.dataSize->CurOverallSimDay, ControlledZoneNum).HeatTstatTemp =
                    state.dataHeatBalFanSys->ZoneThermostatSetPointLo(ActualZoneNum);
            }
        } else {
            state.dataSize->CalcZoneSizing(state.dataSize->CurOverallSimDay, ControlledZoneNum).CoolZoneRetTemp = RetTemp;
            if (state.dataHeatBalFanSys->TempZoneThermostatSetPoint(ActualZoneNum) > 0.0) {
                state.dataSize->CalcZoneSizing(state.dataSize->CurOverallSimDay, ControlledZoneNum).CoolTstatTemp =
                    state.dataHeatBalFanSys->TempZoneThermostatSetPoint(ActualZoneNum);
            } else {
                state.dataSize->CalcZoneSizing(state.dataSize->CurOverallSimDay, ControlledZoneNum).CoolTstatTemp =
                    state.dataHeatBalFanSys->ZoneThermostatSetPointHi(ActualZoneNum);
            }
        }
```

I need to investigate the sections you sent but wanted to see if this sparks any new thoughts or if the EndZoneSizingCalc section is still the place i should focus on for the fix.  I do know that 'CalcFinalZoneSizing(CtrlZoneNum).ZoneTempAtHeatPeak' in SizingManager.cc ends up equalling 70F in my test model but need to verify `FinalZoneSizing(CtrlZoneNum).ZoneTempAtHeatPeak`.  Thanks again!

**Comment by rraustad** [comment]
If FinalZoneSizing(CtrlZoneNum).DesHeatVolFlow > 0, then I would think there would be a zone heating load. I would try to figure out why TStatSetPtAtPk = 0 at this point. A timestep of 1 for winter operation is normal because the design day outdoor temp is usually constant as are internal loads and the heating load doesn't change throughout the day. Still, the Tstat temp should have been known for that time step. This may be a corner case that wasn't caught with the fix at lines 2615 and 2813. Put a breakpoint in of function SizeZoneEquipment (line 405) and step through at the first time step (or break somewhere when heating flow rate  > 0) to investigate why the Tstat temp is 0 when there is a zone heating flow rate > 0.
