### ISSUE TITLE
Template District Systems - Feature Proposal

### ISSUE THREAD

**Issue by bbrannon4** [NREL/EnergyPlus#8694]
Problem: District systems are very popular, and are becoming more and more common to take advantage of shared storage, generation, and various decarbonization strategies.  Many of this analysis takes place at early project stages and so makes use of template HVAC systems in E+, however non currently have the capability to add these in.

Rationale: Expanded early stage modeling capability, especially regarding decarbonization strategy

Solution: Add district heating and cooling capability to as many template systems as possible, particularly the common ones including: System:VAV, System:PackagedVAV (probably heating only), System:ConstantVolume, System:DedicatedOutdoorAir

Context: District systems, which are already present in E+ in the detailed HVAC modeling objects, allow only chilled water or heating hot water to be measured, but have no efficiency applied to them.  This is very common in campuses such a universities,a and more and more in large tech companies and other similar groups of buildings.  Often only these flow rates are needed for analysis, or potentially to have multiple buildings water loads combined together and then simulated in a central plant.

Pros and Cons of Solution:
+ Easier early stage modeling of campus/district buildings
+ Easier modeling of buildings that may want to post process plant loads
- More work for development team that may take away from other tasks

**Comment by mjwitte** [comment]
District hot water and chilled water are currently available in the HVACTemplate objects (but somewhat hidden). HVACTemplate:Plant:Boiler has an option for Boiler Type = DistrictHotWater. And HVACTemplate:Plant:Chiller has an option for DistrictChilledWater. 

If I'm missing the point of this, please re-open with more details.

**Comment by bbrannon4** [comment]
Thanks, you're right.  I thought I checked there but completely missed it.
