### ISSUE TITLE
VRF TU on AirLoopHVAC supply branch will force loop off if terminal OA mixer not set and OA inputs not autosized

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#8718]
Issue overview
--------------
@rraustad I'm not sure this is intended or just a misinterpretation of the input requirement. 

A ZoneHVAC:TerminalUnitVariableRefrigerantFlow on the supply branch of an AirLoopHVAC will force the loop off if the terminal unit OA mixer is left blank **and** the terminal unit 'Cooling/Heating/No Load Outdoor Air Flow Rate' inputs are not 'autosized'. 

The documentation for VRF Terminal Unit Field: Outdoor Air Mixer Object Type states:
"If this field is left blank, an outdoor air mixer is not simulated. If the VRF terminal unit is used as air loop equipment and this terminal unit’s outdoor air flow rates are autosized then the autosized flow rates will be set to 0 when an outdoor air system is used in the air loop"

From this, I expected that not specifying an OutdoorAir:Mixer at the terminal unit will cause any input in the 'outdoor air flow rate' inputs to be ignored, since "an outdoor air mixer is not simulated". Instead, if those inputs are, say, hard-sized to 0, the air loop operation will be overridden and (in the example files below) the air loop will never turn on:

![image](https://user-images.githubusercontent.com/10799524/114912611-70c19480-9ddd-11eb-8395-ce980a2c6b56.png)

[VariableRefrigerantFlow_5Zone_wAirloop.zip](https://github.com/NREL/EnergyPlus/files/6320039/VariableRefrigerantFlow_5Zone_wAirloop.zip)

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - 9.5

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
@eringold I can't recall if I tested without the OA Mixer but I should still have the test file I used during development. So if OA Mixer is blank and inputs are 0 the air loop is off. And if OA Mixer is not blank and inputs are autosized the air loop turns on. Is that correct?

**Comment by eringold** [comment]
That's correct. I attached a working file "VariableRefrigerantFlow_5Zone_wAirLoop_working.idf" and one in which the air loop remains off for the full run period "VariableRefrigerantFlow_5Zone_wAirLoop_termzeroOA.idf". The only difference between the two files is highlighted in the image above. 

Additionally, if the terminal unit does specifies an OutdoorAir:Mixer, then the outdoor air inputs are ignored, even if hard-sized to zero (i.e., the system will run).

To be clear, my expectation here was that if a terminal unit is on an air loop with an AirLoopHVAC:OutdoorAirSystem, then either all the TU's outdoor air-related inputs are ignored, or that they need to specifically set to zero and/or omitted from the TU input.

**Comment by rraustad** [comment]
These are the reduced TU inputs for the problem TU in question. Note the name of the inlet node is Airloop Mixed Air Outlet, which in the NodeID array is 22. 

    ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
        TU5inAirloop,            !- Zone Terminal Unit Name
        Airloop Mixed Air Outlet,!- Terminal Unit Air Inlet Node Name
        0,                       !- Cooling Outdoor Air Flow Rate {m3/s}
        0,                       !- Heating Outdoor Air Flow Rate {m3/s}
        0,                       !- No Load Outdoor Air Flow Rate {m3/s}
        ,                        !- Outside Air Mixer Object Type
        ,                        !- Outside Air Mixer Object Name

Now in this figure you can see (barely given the new state structure) that VRFTUNum = 4 and that this is the correct TU (i.e., VRFTU(4).Name = TU5InAirloop).  In the watch window you can see that OAMixerUsed = false. And that the TU inlet node = 22. So why if OAMixerUsed = false are we at line 7234 if the conditional at line 7233 resolves to false ??????? This probably has something to do with the issue at hand. But I am not sure if this is a 0-based indexing issue, or something else. I'm still trying to figure out why the OAMixer is getting called for this TU. I may need a little help with figuring this one out. Any help with a diagnosis of this specific quirk would be appreciated.

![image](https://user-images.githubusercontent.com/5778156/114955308-6f6a8900-9e2a-11eb-9edf-e8351073717e.png)

**Comment by rraustad** [comment]
Can someone help me figure out why this state variable resolves to true when it seems to be false? VRFTUNum == 4 here so I think I am looking at the correct data. OAMixerUsed is false and testBool = true. WTS ! (what the state). HVACVariableRegrigerantFlow.cc

![image](https://user-images.githubusercontent.com/5778156/114957096-4a781500-9e2e-11eb-91a2-b2f79e067643.png)

**Comment by mitchute** [comment]
Obviously, "have you tried turning it off and on again???"

This is weird, at least based on the screenshot you posted.

**Comment by rraustad** [comment]
Interesting. I jumped into the OA mixer here and see that this is the OA mixer for TU3 (TU5 OA mixer name = "", i.e., VRFTU(4).OAMixerName = ""). I just rebooted this PC so someone should be able to replicate this. Is E+ running multi-threaded now? i.e., are the state vars in sync?

![image](https://user-images.githubusercontent.com/5778156/114959372-ed329280-9e32-11eb-968d-fd7df9fd7883.png)

**Comment by rraustad** [comment]
When state gets passed into a function as a reference, can this functions state var change as the function executes? Yes, or no?

    void InitVRF(EnergyPlusData &state, int const VRFTUNum, int const ZoneNum, bool const FirstHVACIteration, Real64 &OnOffAirFlowRatio, Real64 &QZnReq)

**Comment by mitchute** [comment]
(not sure if this is the right terminology) the address of ```state``` itself should not change, as far as I know. You could check the state address from when the names are set and at the point when they are coming up blank. I'd expect that to be the same at both places.

Which file are you working with?

**Comment by rraustad** [comment]
VariableRefrigerantFlow_5Zone_wAirloop_termzeroOA. The one without "working" in the file name.

**Comment by rraustad** [comment]
The correct TU index is 5, not 4. Inspecting the state tree is a little more difficult now. The good news is that these data are not changing when simulating each TU.

![image](https://user-images.githubusercontent.com/5778156/115039427-7337f300-9e9e-11eb-960e-824da5b59d11.png)

**Comment by mitchute** [comment]
OK, I debugged into VRF at line 7234 (https://github.com/NREL/EnergyPlus/blob/4a4bce01363987d2dada71706a7357e3440f1c8c/src/EnergyPlus/HVACVariableRefrigerantFlow.cc#L7234) and it all looks like it's behaving well. I'm not seeing it drop into that block of code when it shouldn't.

I'm also not seeing VRFTUNum == 5. I added a print statement to the IF block beginning on 7234 and only got TUNum 1-4 and OAMixerUsed is always true.

**Comment by eringold** [comment]
...so do I win some kind of prize for stumping the developers?

Seriously though, I'm just starting to learn to use the debugger and this conversation has been really informative so far. Hope to be able to report more detailed issues (and maybe contribute solutions) in the future. Thanks!

**Comment by rraustad** [comment]
@eringold when you removed the VRF TU OA Mixer you also needed to change the name of the cooling coil inlet node.

    ZoneHVAC:TerminalUnit:VariableRefrigerantFlow,
      TU5inAirloop,            !- Zone Terminal Unit Name
      Airloop Mixed Air Outlet,!- Terminal Unit Air Inlet Node Name
      Airloop Fan Outlet Node, !- Terminal Unit Air Outlet Node Name

    Coil:Cooling:DX:VariableRefrigerantFlow,
      TU5 VRF DX Cooling Coil, !- Name
      TU5 VRF DX CCoil Inlet Node,  !- Coil Air Inlet Node
      TU5 VRF DX CCoil Outlet Node;  !- Coil Air Outlet Node

When there is no VRF TU OA Mixer, the cooling coil inlet node name needs to match the VRF TU inlet node name when draw through fan is used.

    Coil:Cooling:DX:VariableRefrigerantFlow,
      TU5 VRF DX Cooling Coil, !- Name
      Airloop Mixed Air Outlet,  !- Coil Air Inlet Node   <<<<<<<<<<<<<
      TU5 VRF DX CCoil Outlet Node;  !- Coil Air Outlet Node

![image](https://user-images.githubusercontent.com/5778156/115053674-62db4480-9ead-11eb-845c-109384a94f0d.png)

**Comment by rraustad** [comment]
The result above nearly matches the working defect file. I would have expected them to match.

![image](https://user-images.githubusercontent.com/5778156/115054655-7a66fd00-9eae-11eb-9f1b-58142275e405.png)

**Comment by eringold** [comment]
well... 🤦

**Comment by mjwitte** [comment]
So, this didn't generate any kind of node connection warning?

**Comment by eringold** [comment]
@mjwitte it did:
```
   ** Warning ** Node Connection Error for object OUTDOORAIR:MIXER, name=TU5 OA MIXER
   **   ~~~   **   Air Nodes not on any Branch or Parent Object
   **   ~~~   **   Inlet Node : OUTSIDE AIR INLET NODE 5
   **   ~~~   **   Outlet Node: TU5 VRF DX CCOIL INLET NODE
   ************* There was 1 node connection error noted.
```
...double 🤦

**Comment by rraustad** [comment]
I did see that warning. That is because you did not delete the VRF TU OA Mixer object.

    OutdoorAir:Mixer,
      TU5 OA Mixer,            !- Name
      TU5 VRF DX CCoil Inlet Node,  !- Mixed Air Node Name
      Outside Air Inlet Node 5,!- Outdoor Air Stream Node Name
      Relief Air Outlet Node 5,!- Relief Air Stream Node Name
      Airloop Mixed Air Outlet;!- Return Air Stream Node Name

When I delete this unused object I don't see any warnings related to node connections. I am looking now to see how node connections are tested in the VRF model.

**Comment by rraustad** [comment]
Geez, there is no node connection testing in the VRF model. I'll have to add that, however, there are a lot of things to account for. OA Mixer present or not, cooling coil present or not, AT Mixer present or not, etc. I have added this specific warning. There is a lot more to do.

    ** Severe  ** ZoneHVAC:TerminalUnit:VariableRefrigerantFlow "TU5INAIRLOOP"
    **   ~~~   ** ... For draw thru fan when no OA mixer is specified the terminal unit inlet node name must match the cooling coil inlet node name.
    **   ~~~   ** ... The terminal unit inlet node name = AIRLOOP MIXED AIR OUTLET.
    **   ~~~   ** ... The cooling coil inlet node name = TU5 VRF DX CCOIL INLET NODE.
    **  Fatal  ** GetVRFInput: Errors found in getting AirConditioner:VariableRefrigerantFlow system input. Preceding condition(s) causes termination.

**Comment by rraustad** [comment]
Well, there are node connection tests. I missed this because node connection checks were moved to Init since the VRF TU can now be used as zone and air loop equipment. This check is obviously missing.

**Comment by rraustad** [comment]
The problem is here for draw thru fan. There was a check for node connections when an OA mixer was not used. However, additional logic was added that is not correct. The node connections are only tested when the VRF TU is connected to a zone. The VRF TU in question is connected to the air loop. I am trying to unwind this logic.

        } else if (state.dataHVACVarRefFlow->VRFTU(VRFTUNum).isInZone &&
                   state.dataHVACVarRefFlow->VRFTU(VRFTUNum).FanPlace == DataHVACGlobals::DrawThru) {
            if (state.dataHVACVarRefFlow->VRFTU(VRFTUNum).CoolingCoilPresent) {
                if (!state.dataHVACVarRefFlow->VRFTU(VRFTUNum).OAMixerUsed) {
                    if (state.dataHVACVarRefFlow->VRFTU(VRFTUNum).VRFTUInletNodeNum != CCoilInletNodeNum) {
