### ISSUE TITLE
v9.4 download link reported missing

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8720]
Issue overview
--------------
The official v9.4 version download link was reported missing on the page https://energyplus.net/downloads. 

The user realized that he can download from the direct link at: https://github.com/NREL/EnergyPlus/releases/tag/v9.4.0; but would like to have the link listed on the energyplus.net webpage (probably in the "Recent Releases" section). 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.4
 - Helpdesk ticket number: 15690

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
This was addressed by @kflemin
