### ISSUE TITLE
Duplicate \begin{lstlisting} in idd-conventions.tex

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#8721]
Issue overview
--------------

Problems building I/O Ref appear to be related to duplicate name --  "1stlisting" is used twice, with second instance here:

https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/idd-conventions.tex#L221

Change to unique name at first appeared to show better results building pdf on windows, but that pattern is everywhere.  

When I do a full clean solution, I get a short pdf with the TOC.  If I build again without doing a clean, I get the full length PDF but no TOC.  

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Here's my tab group for debugging this:

![image](https://user-images.githubusercontent.com/849824/116701069-1b64b600-a98d-11eb-8bf1-784f72327f0a.png)

I'll get it.

**Comment by jmarrec** [comment]
I just hit it on a clean build of develop on Windows 10.

```
54>[LATEXERROR::doc\input-output-reference\src\overview\idd-conventions.tex:None::TeX capacity exceeded, sorry [main memory size=3000000].<argument> ...shipout:D \box_use:N \l_shipout_box]
```

**Comment by mitchute** [comment]
I don't think having multiple ```lstlisting``` instances in the same file should cause problems. That should just be one of the ways we are able to add non-formatted text to the docs, like code or IDD/IDF snippets.

https://en.wikibooks.org/wiki/LaTeX/Source_Code_Listings

There *may* still be I/O Ref TOC issues on Windows (#8568), but I'd be surprised if it's related to this. I think I'll go ahead and close this for now, but feel free to reopen if we need to keep discussing.
