### ISSUE TITLE
Sizing:System Heating Design Capacity Method FractionOfAutosizedHeatingCapacity not working

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#8730]
Issue overview
--------------
When using FractionOfAutoSizedCooling or HeatingCapacity, the cooling coil size changes in the table report but the heating coil size does not.

![image](https://user-images.githubusercontent.com/5778156/116252505-a18abd80-a73d-11eb-81ea-a88c180ad6bd.png)

The eio file shows the cooling coil size increased. The heating coil size also increased but the U-value decreased. It is suspected that the sizing for HW coil UA does not include the fraction of heating capacity factor.

![image](https://user-images.githubusercontent.com/5778156/116253150-38577a00-a73e-11eb-8a71-9e44f52b1c8c.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added ([5ZoneAirCooledHWCoilSizing.txt](https://github.com/NREL/EnergyPlus/files/6385036/5ZoneAirCooledHWCoilSizing.txt))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Suggested change.

![image](https://user-images.githubusercontent.com/5778156/116254605-7b661d00-a73f-11eb-863b-3684f7df1c90.png)

![image](https://user-images.githubusercontent.com/5778156/116254913-bff1b880-a73f-11eb-804a-e0974c3f042e.png)

**Comment by matthew-larson** [comment]
@rraustad I'm happy to jump on this unless you or someone else were planning on taking care of it.

**Comment by rraustad** [comment]
Go right ahead. These changes corrected this issue in a 3rd party version of E+.
