### ISSUE TITLE
Issues autosizing flow and controlling temp leaving a HeatExchanger:AirToAir:SensibleAndLatent on AirLoopHVAC:DedicatedOutdoorAirSystem

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#8732]
Issue overview
--------------
I have identified two potential issues trying to model a HeatExchanger:AirToAir:SensibleAndLatent located on an AirLoopHVAC:DedicatedOutdoorAirSystem. 

1. Nominal Supply Air Flow Rate set to 'autosize' will produce warnings that `Heat Exchanger Air Volume Flow Ratio = INF`
2. Supply Air Outlet Temperature Control does not seem to work.

Attached is example file 'SmallOffice_CentralDOAS_HX' that modifies the existing 'SmallOffice_CentralDOAS' example file with a HX as the first component on the AirLoopHVAC:OutdoorAirSystem:EquipmentList. I also moved the supply fan to the end of the list (I received a warning about the fan only allowed as the first or last equipment). Nodes have been re-assigned accordingly. The modified example runs and produces output that verifies heat is recovered at the HX. 

1. Keeping the HX input 'Nominal Supply Air Flow Rate' as 'autosize' will yield the following warnings:
```
   ** Warning ** HeatExchanger:AirToAir:SensibleAndLatent ="DOAS HEAT RECOVERY" sensible effectiveness is less than zero. Check the following inputs.
   **   ~~~   ** ...Sensible Effectiveness at 100% Heating Air Flow = 0.70
   **   ~~~   ** ...Sensible Effectiveness at 75% Heating Air Flow = 0.75
   **   ~~~   ** ...Sensible effectiveness reset to zero and the simulation continues.
   **   ~~~   ** ...Heat Exchanger Air Volume Flow Ratio = INF
   ** Warning ** HeatExchanger:AirToAir:SensibleAndLatent ="DOAS HEAT RECOVERY" latent effectiveness is less than zero. Check the following inputs.
   **   ~~~   ** ...Latent Effectiveness at 100% Heating Air Flow = 0.65
   **   ~~~   ** ...Latent Effectiveness at 75% Heating Air Flow = 0.70
   **   ~~~   ** ...Latent effectiveness reset to zero and the simulation continues.
   **   ~~~   ** ...Heat Exchanger Air Volume Flow Ratio = INF
   ** Warning ** HeatExchanger:AirToAir:SensibleAndLatent "DOAS HEAT RECOVERY"
   **   ~~~   ** Average air volume flow rate is <50% or >130% of the nominal HX supply air volume flow rate.
```

2. Setting the HX input 'Supply Air Outlet Temperature Control' to 'Yes' will cause the following severe error: 
```
   ** Severe  ** Missing temperature setpoint for HeatExchanger:AirToAir:SensibleAndLatent "DOAS HEAT RECOVERY" :
   **   ~~~   **   use a Setpoint Manager to establish a setpoint at the supply air outlet node of the Heat Exchanger.
   **  Fatal  **  Previous condition causes program termination.
```
Note that this file has a SetpointManager:OutdoorAirReset object assigned to the HX Supply Air Outlet Node. I have also experienced this error with other setpointmanager types (scheduled, mixedair). 

[SmallOffice_CentralDOAS_HX.idf.txt](https://github.com/NREL/EnergyPlus/files/6387740/SmallOffice_CentralDOAS_HX.idf.txt)
[USA_IL_Chicago-Midway.AP.725340_TMY3.epw.txt](https://github.com/NREL/EnergyPlus/files/6387747/USA_IL_Chicago-Midway.AP.725340_TMY3.epw.txt)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) : Windows 10
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.5
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
I verified that this appears to be a problem in V9.5.  However, in current develop, the error messages noted above do not show up in the .err file.  It seems like there has been some work in this area of the code and it seems likely that this is no longer an issue.  As a result, I am closing this issue for now.
