### ISSUE TITLE
ObjexxFCL copy & paste bug in function not used in E+

### ISSUE THREAD

**Issue by DeadParrot** [NREL/EnergyPlus#8733]
Although maxloc functions are not currently used in E+ this copy & paste bug I just discovered should be fixed for protection against future use.

In this maxloc line the `max()` should be `lowest()`

https://github.com/NREL/EnergyPlus/blob/f9d82c18b7b828893f611b5b4d0f7ec624afedd0/third_party/ObjexxFCL/src/ObjexxFCL/Array.functions.hh#L3759

**Comment by mitchute** [comment]
@DeadParrot it looks like this has already been pared away on the [```remove_unused_objexx branch```](https://github.com/NREL/EnergyPlus/blob/0f166f60923c6900073741adf8d104642df6e2aa/third_party/ObjexxFCL/src/ObjexxFCL/Array.functions.hh). I'll tag this issue on that PR once it gets opened.

**Comment by DeadParrot** [comment]
Right, I saw that branch, but I don't know how long it will be until that gets merged and for historic tracking it is probably wise to make this fix in develop.
