### ISSUE TITLE
err and audit outputs are empty with PixelCounting on Windows

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#8788]
Issue overview
--------------
SolarShadingTestGPU (or any file with PixelCounting) completes successfully, but the err and audit output files are empty, only on Windows. 

### Details
Some additional details for this issue (if relevant):
 - Platform Windows 10 ( (tested on 3 different machines, 2 AMD and 1 Intel)
 - Linux and Mac are fine.
 - And v9.4.0 on windows is fine.
 - EnergyPlus 9.5.0 release, and develop at 9.6.0-0adfd25d1c are not fine (on Windows)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Here's where it crashes when run in the debugger.
![image](https://user-images.githubusercontent.com/4991075/119739420-d3c83180-be47-11eb-8a47-7b4d3580e575.png)

**Comment by michaldengusiak** [comment]
I have the same issue our IDF crushes on e+ when PixelCounting,
I tested also on e+ 9.6 and there is the same problem. I run on 3 examples

![image](https://user-images.githubusercontent.com/26113670/140888393-8e27eaf6-0408-4f3b-83dd-74ac7dede583.png)

here are sample files: 
[sample.zip](https://github.com/NREL/EnergyPlus/files/7503115/sample.zip)

**Comment by mjwitte** [comment]
This was addressed by #9257 (duplicate issue).
