### ISSUE TITLE
Spaces in Python path removed

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#8797]
Issue overview
--------------
A user on Unmet Hours reported the following issue:

> I had the same issue in EP9.5. I had .py in the same folder as IDF file, but it could not find it using the default "Add Current Working Directory to Search Path" set to yes.
> 
> I think I found the cause of the issue. EnergyPlus removes the space from the "search paths" as a result he can't find the py module.
> 
> The original folder directory was "C:\Users\BT\Desktop\EnergyPlus95pythonexamples\test run"
> 
> The line from the .err file
> 
> *** Successfully added path "C:\\Users\\BT\\Desktop\\EnergyPlus95pythonexamples\\testrun" to the sys.path in Python

Apologies if this has already been reported/addressed, I couldn't find anything in a quick search.

### Details
Some additional details for this issue (if relevant):
 - Windows
 - EnergyPlus 9.5
 - https://unmethours.com/question/50207/python-plugin-for-energyplus-issues/?answer=55171#post-id-55171

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
I haven't confirmed the defect on Windows, but I was able to get it running fine on Linux using a path with spaces.

I took a PythonPlugin based IDF and Python pair, put the IDF in one folder, then the Python script in a folder with spaces.  In the IDF it has:

```
PythonPlugin:SearchPaths,DummyName,Yes,Yes,/tmp/dir_name with spaces;
```

The file runs fine and has this in the error file:

```
Program Version,EnergyPlus, Version 9.6.0-45aed47ae1, YMD=2021.06.02 10:25,
   ************* Successfully added path "/tmp/dir_name with spaces" to the sys.path in Python
   ************* PythonPlugin: Class AverageZoneTemps imported from: /tmp/dir_name with spaces/PythonPluginCustomOutputVariable.py
```

We are definitely not trying to remove or alter the path prior to asking Python to import the library for us.  There must be something to do with the backslashes on Windows.  I'll try to confirm.

**Comment by mjwitte** [comment]
Windows may need the path to be enclosed in quotes if is has spaces or other special characters that it thinks are delimiters.

**Comment by shorowit** [comment]
Looks like there is no bug here after all. The user updated their response:

> Search Paths do work. I must have made a mistake. *** Successfully added path "C:\Users\BT\Desktop\EnergyPlus95pythonexamples\test run" to the sys.path in Python
