### ISSUE TITLE
Surface Outside Face Outdoor Air Wind Direction equals to Site Wind Direction

### ISSUE THREAD

**Issue by eugeniorodrigues** [NREL/EnergyPlus#8804]
Issue overview
--------------
When asked to output the 'Surface Outside Face Outdoor Air Wind Direction', the output values are equal to the output 'Site Wind Direction'. The same happens for 'Surface Outside Face Outdoor Air Wind Speed' ('Site Wind Speed'). Both happen for all surfaces. Shouldn't the outputs be relative to each individual surface? Thanks.

### Details
 - macOS Big Sur 11.4
 - EnergyPlus 9.5.0

### Checklist
 - [x] [IDF File with the Example of Outputs](https://www.dropbox.com/s/tctib0dtoqw5yfi/Test.idf?dl=0)
 - [x] [Weather File ](https://www.dropbox.com/s/m8berzgwwznhtyp/weather.epw?dl=0)

**Comment by mjwitte** [comment]
No. 'Surface Outside Face Outdoor Air Wind Direction' (which apparently is not described in the Input Output Reference) is intended to report the actual wind direction at the surface which may be different from the site wind direction when using OutdoorAir:Node with SurfaceProperty:LocalEnvironment or ZoneProperty:LocalEnvironment. It can also be modified using EMS. Tagging this as a documentation issue to add a description for this output to the I/O Ref.

**Comment by shorowit** [comment]
This was addressed in https://github.com/NREL/EnergyPlus/pull/9057
