### ISSUE TITLE
No error/warning if DHW hot water temp is less than the cold water temp

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#8806]
Issue overview
--------------
If a user accidentally sets the hot water temperature to a value below the cold water temperature in the WaterUse:Equipment object, WaterUse:Connections object, or PlantLoop outlet temperature, there is no error or warning and if the Target Temperature is above the Hot Water Temperature, the Hot Water Mass Flow Rate will be set to it's peak flow rate.  This results in unnecessary high flow rates and no Cold Water Mass Flow Rate.  If the Target Temperature is below the Hot Water Temperature, you will end up with a negative Hot Water Mass Flow Rate.  This was mentioned in the code below:

```
        // Calculate hot and cold water mixing at the tap
        if (this->TotalMassFlowRate > 0.0) {
            // Calculate the flow rates needed to meet the target temperature
            if (this->HotTemp == this->ColdTemp) { // Avoid divide by zero
                // There is no hot water
                this->HotMassFlowRate = 0.0;

                // Need a special case for HotTemp < ColdTemp, due to bad user input  (but could happen in a plant loop accidentally)

            } else if (this->TargetTemp > this->HotTemp) {
                this->HotMassFlowRate = this->TotalMassFlowRate;

            } else {
                this->HotMassFlowRate = this->TotalMassFlowRate * (this->TargetTemp - this->ColdTemp) / (this->HotTemp - this->ColdTemp);
            }
```

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.5

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
See also #7133 and related issues mentioned there.

**Comment by mjwitte** [comment]
And somewhat related to this (if I remember correctly but I can't find an open issue) is that there is no warning or way to know if the water heater capacity is inadequate and the supply temperature is below the target, it just delivers cool water and moves on.

**Comment by matthew-larson** [comment]
I can create a pull request that addresses this and #7133 and also look into the inadequate water heater capacity.
