### ISSUE TITLE
Change ObjexxFLC "bit_" functions with C++ operators in psychrometric and fluid property caching

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#8815]
Issue overview
--------------
The caching code in psychrometrics and fluid properties uses ObjexxFLC functions:

- bit_transfer 
- bit_shift 
- bit_and
- bit_xor

which should be replaced with native ">>" and "&" and "|" and "^" operators to increase performance.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
@JasonGlazer I've got a branch locally that has started addressing this. I can take care of it unless you already have the work done.

**Comment by JasonGlazer** [comment]
@mitchute that is terrific. I started working on it in one place and was using reinterpret_cast but it seemed to be getting hung up on types which did not seem to make sense to me. I'm sure you understand this better than me.

**Comment by amirroth** [comment]
@mitchute can you get that merged? I would like to try something that builds on top of it. Thx.

**Comment by mitchute** [comment]
This was addressed by #8818
