### ISSUE TITLE
Move from UtilityRoutines::ProcessNumber to std::stod

### ISSUE THREAD

**Issue by mitchute** [NREL/EnergyPlus#8816]
Issue overview
--------------
- See https://github.com/NREL/EnergyPlus/pull/8810 for a discussion of the issue.
- Changing [this line](https://github.com/NREL/EnergyPlus/commit/e7a3474e19996a41a0d13bf3d9ab16dc03ddb076#diff-7cffab7456bea4477765aa6b0c514f970453ba01a4bff6c62180752f238700dbR565) from ```std::stod``` to ```UtilityRoutines::ProcessNumber``` resulted in the runtime for SolarShadingTest_ImportedShading.idf going from about 15 sec to 2:30-3:00 min.
- This was on Mac 10.15.7, but there also appears to be some performance regression on Linux, although it's less significant.

### Details
Some additional details for this issue (if relevant):
 - Platform (Mac, 10.15.7)
 - Version of EnergyPlus (e7a3474e19996a41a0d13bf3d9ab16dc03ddb076)

**Comment by Myoldmopar** [comment]
Closed via #8819 unless I'm mistaken.
