### ISSUE TITLE
Standard62.1Summary not be treated as valid report name in Output:Table:SummaryReports

### ISSUE THREAD

**Issue by swangdb** [NREL/EnergyPlus#8822]
Issue overview
--------------
Added the summary report key Standard62.1Summary into Output:Table:SummaryReports object and run the simulation for a model, EnergyPlus has reported a severe error:

   ** Severe  ** Output:Table:SummaryReports Field[6]="STANDARD62.1SUMMARY", invalid report name -- will not be reported.

The simulation still runs but there is not a Standard 62.1 Summary generated.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 7 Professional
 - Version of EnergyPlus: 9.4.0

**Comment by jmarrec** [comment]
@swangdb I cannot reproduce this issue either with 9.4.0 or current develop. Could you provide your IDF file please?

I took 5ZoneAirCooled.idf (from ExampleFiles) and modified the Output:Table:SummaryReports to be like below. I get zero warning in eplusout.err and the eplustbl.htm shows the Report correctly.

```
  Output:Table:SummaryReports,
    EnvelopeSummary,              !- Report 1 Name
    ShadingSummary,!- Report 2 Name
    LightingSummary,!- Report 3 Name
    OutdoorAirSummary,!- Report 4 Name
    ZoneComponentLoadSummary,!- Report 5 Name
    Standard62.1Summary;!- Report 6 Name
```

**Comment by swangdb** [comment]
@jmarrec Please see attached idf file in question.
[Standard621SummaryProblem.zip](https://github.com/NREL/EnergyPlus/files/6663536/Standard621SummaryProblem.zip)

**Comment by jmarrec** [comment]
@swangdb Thanks for the quick turn around. I can reproduce with 9.4.0. Will investigate and report back.

**Comment by jmarrec** [comment]
@swangdb So it turns out that you need to enable either "Zone Sizing" or "System Sizing" in `SimulationControl` for the report to be available. I added a new warning message in #8831,. This is your IDF

```diff
  SimulationControl,
-   No,                      !- Do Zone Sizing Calculation
-   No,                      !- Do System Sizing Calculation
    No,                      !- Do Plant Sizing Calculation
    No,                      !- Run Simulation for Sizing Periods
    Yes,                     !- Run Simulation for Weather File Run Periods
    ,                        !- Do HVAC Sizing Simulation for Sizing Periods
    ;                        !- Maximum Number of HVAC Sizing Simulation Passes
```

https://github.com/NREL/EnergyPlus/blob/e936516a4cbf93937c945019c80e048dcc77d6a9/src/EnergyPlus/OutputReportPredefined.cc#L935-L937

**Comment by jmarrec** [comment]
This is explained in the I/O reference guide, but it's very easy to miss it...

Quoting, emphasis (bold) is mine:

https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/output-table-summaryreports.html#standard-62.1-summary

> The Standard 62.1 Summary (key: Standard62.1Summary) produces a report that is consistent with many of the outputs needed when doing calculations consistent with ASHRAE Standard 62.1-2010. **The report is generated when sizing calculations are specified.**

**Comment by swangdb** [comment]
@jmarrec Thank you very much for the quick response to the issue, your solution works a treat! But I'm a bit confused why those two sizing calculations need to be enabled in order to see the Standard 62.1 Summary.
