### ISSUE TITLE
Limit of Zone Cooling Design Supply Air Temperature in Sizing:Zone object

### ISSUE THREAD

**Issue by swangdb** [NREL/EnergyPlus#8827]
Issue overview
--------------
It's nowhere that the Zone Cooling Design Supply Air Temperature input is given a range. But if this input is negative, say -20°C, the simulation returns an error message saying this input should not be negative.

    _Severe ** Sizing:Zone="OfficeZone", invalid data.
    ~~~ ** ... incorrect Zone Cooling Design Supply Air Temperature=[-20.00], value should not be negative.
    Fatal ** Sizing:Zone: Errors found in getting input. Program terminates._

Is it intended that the minimum input should be 0? If yes, please update the documentation (including IDD) to reflect this. Otherwise, maybe the input range needs to extend to take negative value.

### Some additional details for this issue:
 - Platform: Windows 7 Professional
 - Version of EnergyPlus: 9.4.0

**Comment by jmarrec** [comment]
https://github.com/NREL/EnergyPlus/blob/c18d89d4f13f376998ffefb6d13668be0a964229/src/EnergyPlus/SizingManager.cc#L2906-L2920

**Comment by RKStrand** [comment]
Has anyone looked to see if this is the only input field with this issue?  Are there more cases in the sizing routine that also need to be fixed (IDD and docs)?

**Comment by swangdb** [comment]
@jmarrec Thanks for listing the source code. Do you know if there is a reference used for this setting?

**Comment by jmarrec** [comment]
I'm curious to see what application do you have that uses below freezing air temperatures?

**Comment by mjwitte** [comment]
@RKStrand This error message was added when the two supply air temperature methods were added. There was [no error](https://github.com/NREL/EnergyPlusArchive/blame/4bd5fe3be40c56e6024b3aab0189f88d5f3cd7a1/SourceCode/SizingManager.f90#L1209-L1210) prior to that.
My suggestion would be to change this to a warning, worded more like "... is negative, verify the input."

**Comment by RKStrand** [comment]
Will follow suggestion of @mjwitte
This appears to be a problem for both the heating and cooling supply air temperatures so those will be fixed.  All other inputs in this section relate to things that really should not be negative (flow rates, humidity ratios, etc.) and will be left as is.
