### ISSUE TITLE
Timeout finish prematurely find OpenMP_C process in CMake when building E+ 9.5 from source for ARMv8 architecture using Docker

### ISSUE THREAD

**Issue by juancaoviedo** [NREL/EnergyPlus#8828]
Issue overview:
--------------
### Description of the error: 
".*timeout.*" finish prematurely find OpenMP_C process in CMakeLists.txt when building E+ 9.5 from source (cloning github repo) for ARMv8 architecture using docker. 
### Error message: 
CMake Error at CMakeLists.txt:277 (message): Generating epJSON Schema from IDD failed: Process terminated due to timeout 
### Expected behavior: 
Found OpenMP_C: -fopenmp (found version "4.5")
### Platform: 
Docker, base image arm64v8/python:3.8-slim-buster, Raspberry Pi 4 model B, Energy Plus: 9.5, ARMv8.

### Details:
Line 272 of CMakeLists:
execute_process(  COMMAND ${PYTHON_EXECUTABLE} 
   "${PROJECT_SOURCE_DIR}/scripts/dev/generate_epJSON_schema/generate_epJSON_schema.py" "${PROJECT_SOURCE_DIR}"  
   TIMEOUT 30  
   RESULT_VARIABLE generate_epJSON_schema_result)
if(${generate_epJSON_schema_result} MATCHES ".*timeout.*")  
message(FATAL_ERROR "Generating epJSON Schema from IDD failed: ${generate_epJSON_schema_result}")
endif() 

The process hit the timeout when building the docker container. If the cmake command is executed inside the container once is running the cmake process finish without problems. I attach the Docker instructions. The instructions that I run in the container once its running are exactly the same. Inside the container work properly, when building the container fails.  

### Instructions to compile and install EnergyPlus 9.5 over ARM architecture
RUN mkdir /EnergyPlusInstaller
RUN git clone https://github.com/NREL/EnergyPlus.git EnergyPlusInstaller
WORKDIR /EnergyPlusInstaller
RUN mkdir ./buildcmake
WORKDIR /EnergyPlusInstaller/buildcmake
RUN cmake /EnergyPlusInstaller
RUN make -j4 install

## Possible workaround: 
It seems possible to pass the --timeout flag for cmake tests but that option it is not available for CMakeLists*. So, maybe increasing the value of TIMEOUT will work? 

*https://stackoverflow.com/questions/45009595/how-to-overwrite-ctest-default-timeout-1500-in-cmakelists-txt

**Comment by jmarrec** [comment]
@juancaoviedo manually change the timeout for now on this line: https://github.com/NREL/EnergyPlus/blob/5358d3eb87d1376b3484e1a38ade8274b01f0027/CMakeLists.txt#L274

This is in seconds, so set it to whatever, say 600 (10 minutes) and try again.

in context: https://github.com/NREL/EnergyPlus/blob/5358d3eb87d1376b3484e1a38ade8274b01f0027/CMakeLists.txt#L272-L278

**Comment by jmarrec** [comment]
@juancaoviedo Add a new RUN command before building

```diff
RUN mkdir /EnergyPlusInstaller
RUN git clone https://github.com/NREL/EnergyPlus.git EnergyPlusInstaller
WORKDIR /EnergyPlusInstaller
+ RUN sed -i '250,290s/TIMEOUT 30/TIMEOUT 600/g' CMakeLists.txt
RUN mkdir ./buildcmake
WORKDIR /EnergyPlusInstaller/buildcmake
RUN cmake /EnergyPlusInstaller
RUN make -j4 install
```

Anyways, I'm going to close this one, the fact that your specific platform in a specific application times out shouldn't warrant changing the cmakelists.txt for everyone IMHO, especially when manually fixing it is easy.

**Comment by juancaoviedo** [comment]
Thank you very much @jmarrec, adding the new RUN command works perfectly!
