### ISSUE TITLE
"Could not find ReadVarsESO exectuable" does not seem to be reported to the Stderr

### ISSUE THREAD

**Issue by germolinal** [NREL/EnergyPlus#8843]
Hi, 

So, I was trying to call `EnergyPlus` from a Golang script and found an error, but there was no error message. Ultimately, the error was that `ReadVarsESO` could not be found. Is it possible that the `DisplayString` function reports to the `Stdout` instead of the `Stderr`? I tried to check that, but it seems to be a Fortran function... and I know nothing of that.

```c++
 if (!FileSystem::fileExists(readVarsPath)) {
            readVarsPath = (state.dataStrGlobals->exeDirectoryPath / "PostProcess" / "ReadVarsESO").replace_extension(FileSystem::exeExtension);
            if (!FileSystem::fileExists(readVarsPath)) {
                /* THIS BIT --> */DisplayString(state, "ERROR: Could not find ReadVarsESO executable: " + FileSystem::getAbsolutePath(readVarsPath).string() + ".");
                return static_cast<int>(ReturnCodes::Failure);
            }
        }
```
https://github.com/NREL/EnergyPlus/blob/b574f9764d4b63b4b79ca19045bbd515cc59a2ca/src/EnergyPlus/CommandLineInterface.cc#L872

**Comment by mitchute** [comment]
```DisplayString``` is here:

https://github.com/NREL/EnergyPlus/blob/1a131475d56bc6ff761569b794799287a3e0b581/src/EnergyPlus/DisplayRoutines.cc#L63-L103

And it is reporting to stdout, which I believe is appropriate in *this* instance. IDK, we sort of have a mixed bag of issues when it comes to our error reporting, and this is potentially opening a can of worms. Case in point, here: https://github.com/NREL/EnergyPlus/issues/4838#issuecomment-88569360

**Comment by germolinal** [comment]
I see. No problem, then... although, perhaps, printing it to both the STDERR and STDOUT would help some people?

I sorted this out anyway, so feel free to close the issue if you feel like it.
