### ISSUE TITLE
Dividing by tiny values causing water thermal tank model failure and yielding negative energy usage results

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8844]
Issue overview
--------------
It was reported in a case that EnergyPlus got negative water heating related energy usage for unknown reasons.  

The root cause is found to be in the water tank model, where a line of calculation code has a normal (double) float divided by a tiny double (float) which leads to a floating-point overflow:
https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/WaterThermalTanks.cc#L7240

And before that, the tiny value of `b` (and also `a`) was obtained at the following code lines: 
https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/WaterThermalTanks.cc#L7218-L7219

So in the reported case, the program actually continued running under this overflow condition and finished the simulation, but with obviously incorrect results.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v8.9-v9.6
 - Helpdesk ticket number: 15599

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@jcyuan2020 Is there an input file that demonstrates this problem?  Or a specific line in the code where you see this happen?

**Comment by jcyuan2020** [comment]
@RKStrand Yes, we have both. The defect idf file is to be uploaded to the developer repo soon. And the code line that gets the problem is here: 
https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/WaterThermalTanks.cc#L7240
And before that, the tiny value of `b` (and `a`) was obtained at the following code lines: 
https://github.com/NREL/EnergyPlus/blob/de239b2e5f504e381ef4f296893ef93ce5410215/src/EnergyPlus/WaterThermalTanks.cc#L7218-L7219

**Comment by RKStrand** [comment]
@jcyuan2020 I have fixed the issue here.  The users input file (which takes about 2 hours to run on my computer--wow!) now runs all the way through to completion.  PR should be showing up shortly.

**Comment by jcyuan2020** [comment]
That's fabulous! Thank you, @RKStrand !
