### ISSUE TITLE
Microsoft Edge or Google Chrome web browser having problems in fully displaying HVAC schematics SVG files

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8847]
Issue overview
--------------
It was observed that when trying to use Microsoft Edge open the SVG files generated by HVAC-Diagram, most (actually nearly all) texts would be missing. For example as shown in the following figure: 
![image](https://user-images.githubusercontent.com/64040111/123673032-9b7c9000-d805-11eb-91b5-a071576f38d7.png)

However, the display would be ok and the the texts would show up in correct places when using Mozilla Firefox or another free SVG handling tool named InkScape: 
![image](https://user-images.githubusercontent.com/64040111/123673247-df6f9500-d805-11eb-8dcb-e29c2826690f.png)

A user recently also reported similar issue claiming that the Microsoft Edge or Chrome would have problem; but the to-be-obsolete Internet Explore browser would display ok. It was also reported that the problem on Microsoft Edge or Chrome could be eliminated by editing the SVG as a text file and removed the extra spaces in front of the coordinates. So there is a snap shot of an original SVG generated by HVAC-Diagram program, which seemed to have sued fix-length text output format and will then have some spaces in most coordinate fields: 
![image](https://user-images.githubusercontent.com/64040111/123672869-72f49600-d805-11eb-99bf-f33c689f56d5.png)
(Microsoft Edge and Google Chrome would have problem to correctly display the texts; but Mozilla FireFox and InkScape do not have the problem).

The manually edited file does not change anything essential but removed the extra spaces in front of the coordinates strings: 
![image](https://user-images.githubusercontent.com/64040111/123673466-1d6cb900-d806-11eb-9e26-1fca044a7289.png)
(and All the programs, including Microsoft Edge and Google Chrome, would display correctly now).

So it could be a Edge or Chrome bug in handling the SVG file with spaces in front of the coordinate strings--actually these to browsers share the same rendering engine code base. But on the other hand, for EnergyPlus developers, some programming effort to eliminate the spaces before coordinate numbers when generating the SVG could also be a solution to this problem. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): Probably all
 - Helpdesk ticket number: 15727

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: added a test BND file and an analysis notebook at https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/8000s/8847
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Firefox is fine with the spacing, chrome indeed isn't. See this gist: https://gist.github.com/jmarrec/3645262ad8762187adbe99b94a63cf85?short_path=9ea508d#file-dummy-svg-L33-L35

```
  <!-- Here the space DOES matter -->
  <text x="  12" y="    23">x='&#160;&#160;12'</text>
  <text x="52" y="23">x='52'</text>
```

See its rendering: you mileage will vary depending on which browser you use.

![](https://gist.githubusercontent.com/jmarrec/3645262ad8762187adbe99b94a63cf85/raw/c0ca6d4975ffc05f0347c9922f78fb81d33a8e8b/dummy.svg)


What I see on Firefox:

![image](https://user-images.githubusercontent.com/5479063/127460431-8d756de4-e1be-40da-b5ec-fd16b4611263.png)


What I see On chrome:

![image](https://user-images.githubusercontent.com/5479063/127460378-920cdfe8-61d3-4647-b090-14af8c8ed273.png)
