### ISSUE TITLE
After running EnergyPlus from the C++ API, files are left open?

### ISSUE THREAD

**Issue by DavidHollman** [NREL/EnergyPlus#8853]
Issue overview
--------------
After running EnergyPlus using the C++ API I find that the process still has several open file handles. The files being:

```
eplusout.audit
eplusout.sql
eplusout.bnd
```

This is a problem because it prevents re-running the same simulation a second time without first terminating the entire application process. It also prevents any modification to these files (we add some indexes to the SQLite database for performance before reading its contents).

### Details
I'm calling it pretty simply, just by doing:

```
energyplus(argc, argv);
cClearAllStates();
```
(These functions are declared in [`EnergyPlus\api\runtime.h`](https://github.com/NREL/EnergyPlus/blob/v9.3.0-BugFix/src/EnergyPlus/api/runtime.h)).

After that I've verified using Process Explorer which files are open and that its my process which has them.

Is there something else that needs to be done after that call in order to force a "cleanup"? I've tried it with/without the call to `cClearAllStates()` but that didn't have any effect on these open files either way.

I'm using the 9.3-bugfix release on Windows 10. These functions are being called from a C++/CLI DLL (which is basically just C++ with extensions for .NET interoperability).

Thanks!

----

Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows 10
 - Version of EnergyPlus (if using an intermediate build, include SHA): **9.3-bugfix**

**Comment by Myoldmopar** [comment]
@DaveInCaz I'm glad you are trying out the API.  I would _highly_ recommend going to a more recent version of EnergyPlus.  After an initial 9.3 release, the global state of EnergyPlus was refactored and quite a bit of the API was broken in 9.4 to allow for a running instance of EnergyPlus to be passed around as a payload.  Then in 9.5 the global refactor was completed to the point where we are fully thread-safe.

We routinely test the code on our CI system with multiple runs serially in the same process and things are looking good nowadays, it's not a surprise that there are issues with that first release in 9.3.  At this point, it should work well with this:

```
#include <EnergyPlus/api/runtime.h>
#include <EnergyPlus/api/state.h>
#include <stdio.h>
#include <string.h>

void newEnvrnHandler(EnergyPlusState state) { printf("Starting a new environment\n"); }

int main(int argc, const char *argv[])
{
    // run once without any callbacks
    EnergyPlusState state = stateNew();
    energyplus(state, argc, argv);

    // reset and run again
    stateReset(state); // note previous callbacks are cleared here
    callbackAfterNewEnvironmentWarmupComplete(state, newEnvrnHandler);
    registerStdOutCallback(state, stdOutHandler);
    energyplus(state, argc, argv);

    // create a new state and run it with console output muted
    printf("Running EnergyPlus with Console Output Muted...\n");
    EnergyPlusState state2 = stateNew();
    setConsoleOutputState(state2, 0);
    energyplus(state2, argc, argv);
    printf("...and it is done.");
    return 0;
}
```

I trimmed the main test file down a bit but I think I still left enough for that to compile and run.  Try linking against 9.5 and let me know how that goes.  We won't be able to go back and make any changes to support 9.3.

**Comment by DavidHollman** [comment]
@Myoldmopar thanks for the info & the example. I was kind of afraid you'd say that about 9.3... there are a variety of reasons we're still using that version (and also a number of reasons to update, including this one now). TBD, for the moment, what approach we take...

**Comment by DavidHollman** [comment]
@Myoldmopar  I can confirm that with 9.5 the open file issue no longer occurs. Other than making updates needed for the revised API I ran it exactly the same way.
