### ISSUE TITLE
Is there a python api for CurveFitTool.xlsm

### ISSUE THREAD

**Issue by ninenerd** [NREL/EnergyPlus#8863]
Issue overview
--------------
Hi, I came across the CurveFitTool.xlsm on energy plus. I am looking to calculate the capacity curve equation based on temperature and flow. 

The spreadsheet uses ahu datasheet to make some initial tables and then some inputs. 

Is there a python implementation of this ?
Also it may be obvious for there is another file IceStorageCurveFitTool.xlsm, is that also used for HVAC or CurveFitTool.xlsm is enough ?

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) Windows 10
 - Version of EnergyPlus (if using an intermediate build, include SHA) 9.5

**Comment by ninenerd** [comment]
[](url![ep](https://user-images.githubusercontent.com/65250478/124244096-3514ac00-db3c-11eb-9686-6bf71adfbfb0.JPG)
There are two set of values, one for HPCoolingCAPFFF and other HPCoolingEIRFFF . 

How different are they ?
and which one should i use for capacity curve ?

**Comment by bonnema** [comment]
There is not Python code that ships with EnergyPlus that takes table data as input and generates a curve, if that's what you're asking.

There are examples of using curves in the Python plugin system. See C:\EnergyPlusV9-5-0\ExampleFiles\PythonPluginTestMathAndKill.py line 66.

The ice storage curve fit tool is for making curves for detailed ice storage models. The HVAC curve fit tool is best suited for making the DX coil curves from manufacturers data, as you point out. Start reading where it says: ["This model requires 5 curves..."](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-heating-and-cooling-coils.html#coilcoolingdxsinglespeed) for more information.

The curves that have CAP in the name are normalized capacity curves. There are two for most E+ DX models, one a function of outdoor dry bulb and entering wet bulb temperature and another a function of flow fraction. The curves that have EIR in the name are normalized energy input ratio curves. Typically the same two curve formulations as capacity. The documentation link above details this well.

If you have tabular data, you may consider just using that directly via a [performance table](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-performance-tables.html#group-performance-tables). No curve fitting required. Enter the data and EnergyPlus with do the interpolation for you.

**Comment by Myoldmopar** [comment]
@ninenerd for reference, we do actually have a plan to create a python-backed tool for helping generate inputs from manufacturer's data, hopefully not very far in the future.

**Comment by ninenerd** [comment]
@Myoldmopar @bonnema 

Thanks for the inputs. 

One more question, i was able to give input values using CurveFitTool.xlsm, as shown in 1st image here, 

![ep2](https://user-images.githubusercontent.com/65250478/124286317-71f89700-db6c-11eb-9109-1c25b26bd846.JPG)
![ep3](https://user-images.githubusercontent.com/65250478/124286374-7fae1c80-db6c-11eb-91a6-a1fa183f65ca.JPG)

If you the equation : 
Capacity as a Function of Flow Fraction: Cubic Curve
       EIR = a0 + a1*X + a2*X^2 + a3*x^3


What is the value of x, i understand the coeff that i got, but i inputted 3 values, what is x here and what it gives me if i put in equation ?

**Comment by bonnema** [comment]
For this curve, `x` is flow fraction, or the ratio of the actual air flow rate across the cooling coil to the rated air flow rate. In looking at your table data, the rated flow rate is 712 CFM. So the flow fraction for each of the performance data points is 800 / 712 = 1.124, 900 / 712 = 1.264, and so on. I would double-check your table data. It looks like the rated flow rate should be 900 CFM. Then the flow fraction would be 0.889, 1, 1.1, 1.222, 1.361.

**Comment by ninenerd** [comment]
Appreciate the quick response @bonnema . 

You are right the value 712 wrong, i manually put it. 

So if i understand right, 
1. **Rated Data** is what you get from manufacturer and that can be at any supply flow rate ? 
2. When i clicked the options to test, **performance data** was already there, is that what i need to change ?
3. So basically how i want to use this tool is that, given the supply air flow rate, fan speed, chiller water temp, cooling valve status, **i want to dynamically calculate the capacity of ahu at a given time**, so 2 tons,2.2 tons at different time (as capacity depends on various factors), _is that possible with the tool_ ?

**Comment by bonnema** [comment]
The tool only generates curves from tabular data (effectively a preprocessing step). The curves themselves could then be used in some fashion to dynamically calculate how capacity changes based on input conditions.

**Comment by ninenerd** [comment]
@bonnema After using the below equation, 

```
Capacity as a Function of Flow Fraction: Cubic Curve
EIR = a0 + a1X + a2X^2 + a3*x^3 
```

the value it returns what is its unit , lets say it returns 1. Based on below image i.e input, what does that mean and if i want to convert it to tons, is that possible ?
![ep5](https://user-images.githubusercontent.com/65250478/124421476-2833ca80-dd7f-11eb-9ffd-7b396d2080d1.JPG)

**Comment by bonnema** [comment]
The `CurveFitTool.xlsm` is an "auxiliary tool [that] generates HVAC performance curves in EnergyPlus curve object format." All it does is generate curves that can be directly inserted into an EnergyPlus input data file (IDF). I don't think it has other uses. Refer to the _INSTRUCTION_ tab in the file for more details.

In general, performance curves in E+ return fractional multipliers that determine how a units performance deviates from rated conditions. The curves almost always return 1 at rated conditions. For example, a unit may be rated for 4 tons, but when it is really hot outside the capacity as a function of temperature curve could return 0.92. That would mean that the actual capacity of the unit under those conditions would be 3.68 (4 x 0.92) tons. Please see [Chapter 21](https://energyplus.net/sites/all/modules/custom/nrel_custom/pdfs/pdfs_v9.5.0/EngineeringReference.pdf) for more information.

**Comment by jmarrec** [comment]
I don't think there is any actual action item from this issue, we should close it.
