### ISSUE TITLE
Facility Total Produced Electricity Rate (or Energy) of PVWatts generator showing excessively large numerical values

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8867]
Issue overview
--------------
It was reported in a case with PVWatts generator, the meter reporting values for the Facility Total Produced Electricity shows “infinity” values occasionally for some timesteps or hours, especially for the timesteps/hours near around daily generation peaks/highs. 

This is a sign that the program has floating point overflow issues when generating these meter outputs. A preliminary investigation shows that the related output variables Facility Total Produced Electricity Rate (or Energy) outputs are having issues with floating point overflow. 

In a common setup, the user may use some workaround might work by choosing some alternative output variables, e.g. electricity load center generated electricity, to estimate the corrupted Facility Total Values—try using good data as an efficiency or by some simple regression relationship

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows, probably All
 - Version of EnergyPlus (if using an intermediate build, include SHA): : 9.0 to 9.6 pre-release
 - Helpdesk ticket number: 15744

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/8000s/8867))
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@jcyuan2020 Is there an example file that demonstrates this problem?  The issue will be easier to address if there is an example file the shows this behavior.

**Comment by jcyuan2020** [comment]
@RKStrand Yes, we will get uploaded or send it to your email soon.

**Comment by RKStrand** [comment]
@jcyuan2020 I am looking at the file that you provided and have run it with the Sacramento 724835 (TMY2) weather file.  I am looking at hourly data for Whole Building:Facility Total Produced Electricity Rate [W](Hourly).  I get a maximum of roughly 109 kW.  The DC capacity set in the input is 132 kW.  Are you running a different weather file or am I not understanding what you are seeing?

**Comment by jcyuan2020** [comment]
@RKStrand I used the SACRAMENTO-EXECUTIVE_724830_CZ2010.epw weather file that the user sent in. 

Here is what it looks like in the CSV---I sorted the last column `Whole Building:Facility Total Produced Electricity Rate [W](Hourly)` from high to low values, and there are about 100 lines out of the 8760 hours total that shows these `e^308` values:
![image](https://user-images.githubusercontent.com/64040111/126012553-02779881-9255-4e24-8a0e-1bdf0bf118a0.png)

**Comment by RKStrand** [comment]
@jcyuan2020 Ok, I am seeing what you are seeing now.  Very strange but I am looking at it now.

**Comment by RKStrand** [comment]
The bug is in the ElectricLoadCenter:Storage:Simple which divides by the energetic efficiency for charging.  The user input file entered a value of zero so when it divided by this, it gets a NaN value.  When the zero value is altered, reasonable results are returned.  The problem is really that a zero value should not be allowed but the IDD does allow for it.  I will fix that for both the charging and discharging efficiencies.

**Comment by jcyuan2020** [comment]
I run a local CI on the few test files that showed the diffs in the web portal. The diffs were explained by the corrected efficiency (which occurs when plr is <=0 according to the code). The defect file finished running without problems.

**Comment by RKStrand** [comment]
Thanks, @jcyuan2020 and @mjwitte
