### ISSUE TITLE
ZoneHVAC:LowTemperatureRadiant:VariableFlow input processing problem for cooling only configuration

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#8885]
Issue overview
--------------

There is a code mistake here
https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/LowTempRadiantSystem.cc#L834

` lAlphaBlanks(6) || lAlphaBlanks(7)   `

should be 

` lAlphaBlanks(8) || lAlphaBlanks(9) `

This causes cooling-only radiant files throw severe error when they should not.  Code changed a lot from 9.4 to 9.5. It looks like a copy/paste error from the same check on heating nodes. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (CoolingOnlyRadSys8885.idf in EnergyPlusDevSupport)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
Added an input file that verifies the description above.  With develop, the severe error shows up.  With the corrections to the code, the error goes away as it should.
