### ISSUE TITLE
Contaminant Resilience Hourly Reporting Defect

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#8895]
Issue overview
--------------
@jcyuan2020 identified an issue with the reporting of contaminant level hours while reviewing #8870.  The discussion is here: https://github.com/NREL/EnergyPlus/pull/8870#pullrequestreview-708948591.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
This is **OccupantHours**. Not **Occupied Hours**.

https://github.com/NREL/EnergyPlus/blob/e0d2dea7123012ea6f5bdea4cb007f1f01d70993/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L5347-L5348
