### ISSUE TITLE
RDD file generated but having empty contents

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8896]
Issue overview
--------------
It was found that in a simulation the RDD file was created but no items were written in .RDD file, like this: one: 

![image](https://user-images.githubusercontent.com/64040111/126168956-f458712f-37e9-426a-bd77-69f2eda3e0cd.png)

The simulation was completed successfully and results were obtained without problems though. The RDD file was still empty after repeating the simulation runs more than once. 

As a result, when adding (and selecting) output variables using the IDFEditor program (after proper first simulation run), an empty drop-down list will be encountered. However, it is still possible to add output variables manually by editing the IDF file in text mode---the output variables would report correctly in the simulation results if inputted correctly this way.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.4, v9.5, and v9.6 pre-release
 - Related helpdesk ticket number: 15751

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Add `Output:VariableDictionary,regular;` and now it'll be filled... Tested with 22.1.0: as is rdd is empty. After adding the VariableDictionary object, RDD is full.
