### ISSUE TITLE
No energy use for ElectricEquipment object referencing Schedule:File

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#8909]
Issue overview
--------------
See attached E+ IDF where the "res hot water recirc pump" ElectricEquipment object ends up with zero energy use:

![image](https://user-images.githubusercontent.com/5861765/126550559-6fad338b-68ff-4f83-9441-857b65d2b34c.png)

Test files:
[files.zip](https://github.com/NREL/EnergyPlus/files/6858420/files.zip)

Interestingly, I took just the ElectricEquipment & Schedule:File objects from the above file and inserted them into an E+ example file and got correct (non-zero) results. So there is something more nuanced/complex going on in the original file that results in zero energy use. Maybe the use of custom meters? Or the fact that the same Schedule:File column is referenced by other objects (OtherEquipment and WaterUse:Equipment)?

### Details
Some additional details for this issue (if relevant):
 - Tested on Windows and Linux
 - EnergyPlus v9.5

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
@shorowit I took your testfiles.zip, extracted it. I edited the in.idf to point to `schedules.csv` instead of `C:/git/resstock/test/test_samples_osw/run0/generated_files/schedules.csv`. Ran with 9.5.0

![image](https://user-images.githubusercontent.com/5479063/127195690-a7bf8c3c-ea9b-4673-bdc6-033b1755fa24.png)

Am I misunderstanding something?

**Comment by jmarrec** [comment]
double checking the value. Note that in Python I select column 13 because it's 0-indexed, to get the "showers" column.

```python
In [1]: df_schedules = pd.read_csv('schedules.csv')
In [2]: df_schedules.iloc[:, 13].sum() * 1054.93773625732 * 3.6e-6
Out [2]: 0.6947999999999952
```


IDF extract

```diff
  Schedule:File,
+   showers,                 !- Name
    Fractional,              !- Schedule Type Limits Name
+   schedules.csv,  !- File Name
+   14,                      !- Column Number
    1,                       !- Rows to Skip at Top
    8760,                    !- Number of Hours of Data
    Comma,                   !- Column Separator
    No,                      !- Interpolate to Timestep
    60;                      !- Minutes per Item

  ElectricEquipment,
    res hot water recirc pump,  !- Name
    living zone,             !- Zone or ZoneList Name
+   showers,                 !- Schedule Name
    EquipmentLevel,          !- Design Level Calculation Method
+   1054.93773625732,        !- Design Level {W}
    ,                        !- Watts per Zone Floor Area {W/m2}
    ,                        !- Watts per Person {W/person}
    0,                       !- Fraction Latent
    0.5,                     !- Fraction Radiant
    0,                       !- Fraction Lost
    res hot water recirc pump;  !- End-Use Subcategory
```

**Comment by shorowit** [comment]
Ah, shoot, sorry for the waste of time here. It turns out that I was looking at the wrong csv file. 🤦‍♂️ Indeed EnergyPlus is working as expected.
