### ISSUE TITLE
Facility Electricity Output Variable not aligned with EMS Sensor

### ISSUE THREAD

**Issue by bonnema** [NREL/EnergyPlus#8915]
Issue overview
--------------
The value of the `Facility Total Purchased Electricity Energy` output variable does not always align with an EMS sensor using the same `Output:Variable`. To reproduce:

1. Start with `5ZoneAirCooled.idf` EnergyPlus example file (`C:\EnergyPlusV9-5-0\ExampleFiles\5ZoneAirCooled.idf`).
2. Comment out all existing `Output:Variable` objects (not necessary, but convenient).
3. Add the following objects:
```
EnergyManagementSystem:Sensor,
  Elec_Sen,                               !- Name
  Whole Building,                         !- Output:Variable or Output:Meter Index Key Name
  Facility Total Purchased Electricity Energy; !- Output:Variable or Output:Meter Name

EnergyManagementSystem:ProgramCallingManager,
  Test Prgm,                              !- Name
  EndOfZoneTimestepBeforeZoneReporting,   !- EnergyPlus Model Calling Point
  Test_Prgm;                              !- Program Name 1

EnergyManagementSystem:Program,
  Test_Prgm,                              !- Name
  SET elec = Elec_Sen;                    !- Program Line 1

EnergyManagementSystem:OutputVariable,
  EMS Electricity,                        !- Name
  elec,                                   !- EMS Variable Name
  Summed,                                 !- Type of Data in Variable
  ZoneTimestep,                           !- Update Frequency
  Test_Prgm,                              !- EMS Program or Subroutine Name
  J;                                      !- Units

Output:Variable,
  EMS,                                    !- Key Value
  EMS Electricity,                        !- Variable Name
  hourly;                                 !- Reporting Frequency

Output:Variable,
  Whole Building,                         !- Key Value
  Facility Total Purchased Electricity Energy, !- Variable Name
  hourly;                                 !- Reporting Frequency
```
4. Run the simulation.
5. The first few day of the CSV is below, and not as expected. Some hours the values align, others (7-10, 13, 19, 21) they do not.
```
Date/Time,EMS:EMS Electricity [J](Hourly),Whole Building:Facility Total Purchased Electricity Energy [J](Hourly) 
 01/01  01:00:00,3064358.8289917588,3064358.8289917588 
 01/01  02:00:00,3064390.9218475006,3064390.9218475006 
 01/01  03:00:00,3066203.950329956,3066203.950329956 
 01/01  04:00:00,3069278.532286522,3069278.532286522 
 01/01  05:00:00,3072233.098369529,3072233.098369529 
 01/01  06:00:00,3075909.389426966,3075909.389426966 
 01/01  07:00:00,1035814.3967818932,3553568.672329401 
 01/01  08:00:00,2207201.979812064,3536735.9014515739 
 01/01  09:00:00,23395692.022680686,33048981.380180088 
 01/01  10:00:00,27075943.743954965,43323864.45416245 
 01/01  11:00:00,44657588.74793638,44657588.74793638 
 01/01  12:00:00,43287894.39572204,43287894.39572204 
 01/01  13:00:00,24517316.706315724,39228248.13557948 
 01/01  14:00:00,41919680.998112518,41919680.998112518 
 01/01  15:00:00,42818326.054239738,42818326.054239738 
 01/01  16:00:00,41021691.25450396,41021691.25450396 
 01/01  17:00:00,37421503.93574435,37421503.93574435 
 01/01  18:00:00,37424383.50924227,37424383.50924227 
 01/01  19:00:00,17286031.97409433,23046817.456997839 
 01/01  20:00:00,12280910.768599162,12280910.768599162 
 01/01  21:00:00,2578955.075509513,7114358.82899176 
 01/01  22:00:00,3064358.8289917588,3064358.8289917588 
 01/01  23:00:00,3064358.8289917588,3064358.8289917588 
 01/01  24:00:00,3064358.8289917588,3064358.8289917588 
```
6. Tried different calling points with no better (and sometimes worse) results. Strange that some hours match exactly when others do not.

### Details
Some additional details for this issue (if relevant):
 - Windows 10 Enterprise, Version 20H2, OS build 19042.1110
 - EnergyPlus 9.5 Release (Version 9.5.0-de239b2e5f)
 - Similar (and possibly related to) https://github.com/NREL/EnergyPlus/issues/7563

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([IDF](https://github.com/NREL/EnergyPlus/files/6865494/in.idf.txt) and [EPW](https://github.com/NREL/EnergyPlus/files/6865495/in.epw.txt))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by EnergyArchmage** [comment]
I think the sensor is at HVAC System timestep, and the test program is at zone timestep.  So it samples the last system timestep.  The calling point needs to be within the system timestep.

**Comment by bonnema** [comment]
🥇 for @EnergyArchmage. Setting the calling point to `EndOfSystemTimestepBeforeHVACReporting` and the `EnergyManagementSystem:OutputVariable` update frequency to `SystemTimestep` fixed it.
```
Date/Time,EMS:EMS Electricity [J](Hourly),Whole Building:Facility Total Purchased Electricity Energy [J](Hourly) 
 01/01  01:00:00,3064358.8289917588,3064358.8289917588 
 01/01  02:00:00,3064390.9218475006,3064390.9218475006 
 01/01  03:00:00,3066203.950329956,3066203.950329956 
 01/01  04:00:00,3069278.532286522,3069278.532286522 
 01/01  05:00:00,3072233.098369529,3072233.098369529 
 01/01  06:00:00,3075909.389426966,3075909.389426966 
 01/01  07:00:00,3553568.672329401,3553568.672329401 
 01/01  08:00:00,3536735.9014515739,3536735.9014515739 
 01/01  09:00:00,33048981.380180088,33048981.380180088 
 01/01  10:00:00,43323864.45416245,43323864.45416245 
 01/01  11:00:00,44657588.74793638,44657588.74793638 
 01/01  12:00:00,43287894.39572204,43287894.39572204 
 01/01  13:00:00,39228248.13557948,39228248.13557948 
 01/01  14:00:00,41919680.998112518,41919680.998112518 
 01/01  15:00:00,42818326.054239738,42818326.054239738 
 01/01  16:00:00,41021691.25450396,41021691.25450396 
 01/01  17:00:00,37421503.93574435,37421503.93574435 
 01/01  18:00:00,37424383.50924227,37424383.50924227 
 01/01  19:00:00,23046817.456997839,23046817.456997839 
 01/01  20:00:00,12280910.768599162,12280910.768599162 
 01/01  21:00:00,7114358.82899176,7114358.82899176 
 01/01  22:00:00,3064358.8289917588,3064358.8289917588 
 01/01  23:00:00,3064358.8289917588,3064358.8289917588 
 01/01  24:00:00,3064358.8289917588,3064358.8289917588 
```
Interesting that `EndOfSystemTimestepAfterHVACReporting` gave inconsistencies, but different than before. 🤦‍♂️. Sorry everyone.

**Comment by bonnema** [comment]
What is a good way to update the docs to help with this? I chose `ZoneTimestep` for the update frequency because the [I/O ref](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-energy-management-system-ems.html#field-update-frequency) (to me) implies use zone timestep unless related to HVAC. Is it correct to use system timestep for all "whole building" meter-like output variables?

**Comment by mjwitte** [comment]
The update frequency for every output variable is listed in the RDD. (And for meters in the MDD, but meters are all zone, and appear to have their own issues.)

**Comment by bonnema** [comment]
I see. It's the comment in `Output:Variable,*,Facility Total Purchased Electricity Energy,hourly;` _**HVAC** Sum [J]_ from the RDD.

To confirm the issue with meters, I ran a test with the sensor changed to the `Electricity:Facility` meter. I could not get agreement between the EMS output variable and the `Output:Meter` the for either:
1. Calling point `EndOfZoneTimestepBeforeZoneReporting` and EMS output variable update frequency `ZoneTimestep`, or
2. Calling point `EndOfSystemTimestepBeforeHVACReporting` and EMS output variable update frequency `SystemTimestep`.

The `Output:Variable` and the `Output:Meter` do match in the ESO.

**Comment by EnergyArchmage** [comment]
Meters are HVAC system timestep.  the HVAC equipment uses energy and runs at the system timestep. I would not expect either of those 1. and 2. to work.

**Comment by bonnema** [comment]
> Meters are HVAC system timestep. the HVAC equipment uses energy and runs at the system timestep. I would not expect either of those 1. and 2. to work.

Sorry, `EndOfSystemTimestepAfterHVACReporting` doesn't work either.

**Comment by EnergyArchmage** [comment]
oh you switched from Output:Variable to Output:Meter.  yeah meters rarely work well in EMS.  best to find the Output:Variable with the same info as the meter.
