### ISSUE TITLE
One weather file location listed under a neighboring state

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8920]
Issue overview
--------------
A user reported that the weather file for Rhinelander-Oneida County AP 727415 (TMY3) is listed under the state of Michigan. However, this county/city is actually located in Wisconsin: 

![image](https://user-images.githubusercontent.com/64040111/127020167-0c218bdc-f01b-4fde-bd60-ad864fd77351.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Helpdesk ticket number: 15758

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mitchute** [comment]
See here: https://github.com/NREL/EnergyPlus/issues/7500
