### ISSUE TITLE
Multi-speed Fan for VRF Indoor Terminal Units

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#8934]
Issue overview
--------------
Many of the VRF indoor terminal unit come with multi-speed fan control to save fan energy and reduce noise. To simulate these VRF terminal units accurately, we propose to add supply air flow ratio input fields for multiple speed fan to the object ZoneHVAC:TerminalUnit:VariableRefrigerantFlow. In simulation calculation, for each time step, cycle the terminal fan between two speeds based on the capacity at each air flow ratio and the required load output.

Background information
-------------------------
Recently there has been rapid growth in application of Variable Refrigerant Flow (VRF) systems in the US.  There is already deep market adoption of VRF globally.  One of the key features for increasing energy efficiency of VRF systems is use of multi-speed fans in VRF indoor units.  Adding multi-speed fan modeling capabilities to EnergyPlus would allow engineers to demonstrate the energy performance benefits of this feature.  This feature would have application for many VRF manufacturer’s products and across many market verticals.

Reference Links
----------------
1.	https://www.daikinac.com/content/assets/DOC/Product%20Brochures/CT-VRV-Catalog-08-15.pdf  Daikin - on page 67, the FXEQ-PVJU series terminal units have a 5 speed fan.
2.	https://www.lg.com//global/business/download/airsolution/2020 MULTI V Catalogue_EU[20200713_184653935].pdf   LG indoor unit documentation on pages 55-80 shows 3-speed capabilities across multiple product lines.
3.	https://www.shareddocs.com/hvac/docs/1001/Public/0A/TCTC-E20-VRF007.pdf For Carrier VRF terminals, on page 2, the indoor unit has 3 speed fan control.
4.	https://www.shareddocs.com/hvac/docs/1001/Public/0B/A10-1604-3.pdf  Toshiba-Carrier MMDB service manual.  See pages 8 and 9 for relevant unit data.  See pages 17 and 18 for multi-speed fan “auto” control explanations

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
This was already achieved with PR #9746
