### ISSUE TITLE
Consolidate HVAC radiant surface variables

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#8938]
Issue overview
--------------
There are a lot of places in the code that manually aggregate the radiant components of HVAC equipment like this:

```
        state.dataHeatBalSurf->QdotRadHVACInRepPerArea(SurfNum) =
            state.dataHeatBalFanSys->QHTRadSysSurf(SurfNum) + state.dataHeatBalFanSys->QCoolingPanelSurf(SurfNum) +
            state.dataHeatBalFanSys->QHWBaseboardSurf(SurfNum) + state.dataHeatBalFanSys->QSteamBaseboardSurf(SurfNum) +
            state.dataHeatBalFanSys->QElecBaseboardSurf(SurfNum);
```

These individual variables are not needed and anytime a new equipment type is added this section has to be added to each aggregation.  These can be consolidated into a single report variable that is incremented for all relevant equipment types.  It was also found that `state.dataHeatBalFanSys->QCoolingPanelSurf(SurfNum)` was missing from a number of these instances.  There are similar aggregations performed for thermal comfort.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@matthew-larson Given my involvement in many of those models, I'm interested in your solution to this problem.  Also, just to clarify, you are talking about reports here right?  In other words, the CoolingPanelSurf being missing in some places is not affecting the heat balance but rather some reporting variables?  Thanks!

**Comment by nealkruis** [comment]
@RKStrand, I came across this while I was doing some work on caching surface calculations. We were going to reach out to you to get your input, but you beat us to it 😃 . We'd appreciate your feedback on this!

The CoolingPanelSurf missing was affecting heat balances, though it was correctly incorporated into the output variable reports. This approach also reduces the memory footprint of the program.
