### ISSUE TITLE
GSHP heating coil energy not consistent when running at non-rated air flow rate

### ISSUE THREAD

**Issue by yzhou601** [NREL/EnergyPlus#8955]
Issue overview
--------------
I am modeling a gshp system in EnergyPlus with `Coil:Heating:WaterToAirHeatPump:EquationFit` and `Coil:Cooling:WaterToAirHeatPump:EquationFit` coil objects along with an `AirLoopHVAC:UnitarySystem` parent object. It worked well when the actual airflow rate(specified at fan object, unitary system object, terminal object, and airloop object) is equal to coil rated airflow rate(specified at coil objects). But if the actual airflow rate is lower than coil rated airflow rate, energy report looked suspicious.

I looked at two timestep variable outputs: `Heating Coil Heating Energy` and `Air System Heating Coil Total Heating Energy`. Since the system only have two heating coils - GSHP equationfit coil and electric backup coil, the backup coil was not working in most hours and it was not providing so much heating compared to gshp coil, I would expect `Heating Coil Heating Energy` and `Air System Heating Coil Total Heating Energy` to report a similar heating energy for most of time. However, `Heating Coil Heating Energy` actually reports much MORE energy than `Air System Heating Coil Total Heating Energy` (and load variable Predicted Sensible Load to Setpoint Heat Transfer) almost every hour when it heats. I used a small actual airflow rate (0.1m3/s) compared to rated airflow rate(0.536m3/s) to maximize this impact:

![GSHPenergyreporting](https://user-images.githubusercontent.com/32500275/128792902-fdbe2460-4d6f-4412-9c28-eeadf1ed8093.png)

And it looks normal if running at rated air flow rates (actual = rated = 0.536 m3/s):

![GSHPenergyreporting-rated](https://user-images.githubusercontent.com/32500275/128792931-d647bef6-a6bc-4190-8ff3-21ee3f304b4d.png)

The same behavior happened in cooling coils too.

[idf files](https://drive.google.com/drive/folders/12rToUuk--UCUwVYcp21OzcsqYUxFJvfa?usp=sharing)

FYI, @shorowit 

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows, 10)
 - Version of EnergyPlus (E+ 9.5.0)
 - Unmethours link or helpdesk ticket number (https://unmethours.com/question/58255/gshp-heating-coil-energy-not-consistent-when-running-at-non-rated-air-flow-rate/?answer=58441#post-id-58441)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by yzhou601** [comment]
@mjwitte @rraustad @Myoldmopar Any idea on what happened here? I agree to @rraustad on [his comment](https://unmethours.com/question/58255/gshp-heating-coil-energy-not-consistent-when-running-at-non-rated-air-flow-rate/?answer=58441#post-id-58441) on UMHs that ` Heating Coil Heating Energy` may have an issue. I verified that `Heating Coil Part Load Ratio` also reported oddly with heating energy. Considering the `Air System Heating Coil Total Heating Energy` output still looks reasonable, it is likely to be a reporting issue of coil object-level variables from our initial observation.

In terms of priority, as we can see, the discrepancy can be very large with air flow rate being greatly off rated condition. So I think this issue is very important on user side especially if they're querying coil outputs for reporting. It cannot be better if this can be fixed in the 9.6 release. Is there still availability in E+ team to pick this one? Otherwise I can start investigating it but might need some help from someone who has more E+ HVAC knowledge.

**Comment by rraustad** [comment]
It might be as easy as seeing if the coil is operating at rated air flow or not, and if not then does the performance curve output reasonable results. I don't think the stock performance curve is sensitive to changes in air flow. @yzhou601 plotted the performance curve output and there is not much change for a factor of 4 reduction in air flow.
