### ISSUE TITLE
Prevent CI from running when not desired

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#8978]
Issue overview
--------------
From the discussion https://github.com/NREL/EnergyPlus/pull/8653

> The second reason is for CI. When we are doing hackathons, for example, we have a small group of people pushing rapidly to branches and sharing patches. If this was all pushed to the main E+ repo, it could very easily add hours and days of CI backlog just from that one group of developers, leaving the rest of the team without much CI support. Once we are ready for CI to run, we can open a pull request and everything is fine. Other projects sometimes start out on forks so that they can make commits freely without worrying about impacting our CI capacity for unimportant and frequent commits, which is appreciated.

It would be nice to have some way within the normal repo to push preliminary code and not cause CI to run. Sometimes we just want to share code with others and we know it would be a waste of time for the CI to run it. Would it be possible to modify the CI so that if it sees a file named something like "NO_CI.TXT" it prevents the CI from running?

**Comment by mitchute** [comment]
Good idea. What about a `[[no integration tests]]` comment in the git commit message instead of a separate file?

**Comment by JasonGlazer** [comment]
@mitchute excellent idea!

**Comment by mjwitte** [comment]
Not sure about that,  it would clutter up the commit history. How about a PR label instead?

**Comment by mitchute** [comment]
> it would clutter up the commit history

To play the devil's advocate, it's not like our commit history is really that pristine anyway. But I see your point. A PR label is fine by me, too.

Edit: we *can* edit the commit message after the fact, but I'm not sure we'd want to go down that road regularly
https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by shorowit** [comment]
I don't have a strong preference between using a PR label vs commit message, but note that many third-party CIs look in commit messages. For example, [CircleCI looks for `[ci skip]` or `[skip ci]` in the commit message](https://circleci.com/docs/2.0/skip-build/).

Edit: Another example from [Travis CI](https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build).

**Comment by EnergyArchmage** [comment]
I think this is an important issue.   Always running CI seems to reduce ability to scale.  Think of the optics of all that wasted electricity going into useless CI clock cycles for software aiming to reduce energy use.

**Comment by Myoldmopar** [comment]
If anyone is wondering, the Decent CI machines are powered by a solar array in Colorado.  I am fine with doing a commit message skip.  We currently use both Github Actions as well as Decent CI.  Github Actions uses the usual suspects for patterns to match to skip tests: `[skip ci]`, `[ci skip]`, `[no ci]`, `[skip actions]`, or `[actions skip]`.  We could utilize one of those for Decent, or Decent could have its own.  That way if we still wanted Github Actions to run but not Decent, we could do that.  And the dev could always put both.  `[skip decent]` anyone?  Or is it better to just lump them together in one pattern that we can't differentiate?

**Comment by JasonGlazer** [comment]
I think there are two different lengths of tests and perhaps we should differentiate them that way. Some are quick (usually less than a minute each such as checking labels and format) and some are slow (10 minutes to 30 minutes or more such as running all the unit tests, simulations, and compiling alternate configs). So how about: [skip ci_short] and [skip ci_long]

**Comment by Myoldmopar** [comment]
I like the idea of splitting it, but all the short ones are already on Github Actions and the long ones are on Decent CI.  I think we can keep the separation by the CI system and still achieve what you are hoping for.  And Github Action is already set up to be skipped with their own log message.  I could be swayed still, let me know if I am missing something.

**Comment by JasonGlazer** [comment]
That is fine. My thought was to break it by use rather than by software since that would allow using the software in the future in different ways such as future short tests in Decent CI and long tests in Github Actions or perhaps something else entirely for one of those two uses.

**Comment by mjwitte** [comment]
Not to make this more complicated, but I could see wanting just a quick check for diffs and unit test failures without everything else (like integration debug and coverage). Maybe a [ci mac-only] option? Not crucial, just a thought.

**Comment by Myoldmopar** [comment]
I appreciate the thought there, but I think that would indeed be a bit too complex for this.  Honestly, if you are wanting this level of detailed turning on and off the CI machines for a commit, just rename the `.decent` CI files at the root of the repo temporarily and push.  Then rename them back before merge.  Same for the Github Actions, just move the workflow files to the disabled workflows folder and move them back before merge.  What I'm looking for here is a way to tell our Decent CI system to skip this branch.

**Comment by JasonGlazer** [comment]
I never realized it was that simple. Maybe we just document this on the wiki page related to CI:

https://github.com/NREL/EnergyPlus/wiki/Continuous-Integration

**Comment by Myoldmopar** [comment]
OK, I'm merging in a fix to Decent CI that will let you use `[decent_ci_skip]` in the commit messages.  It will still run the commit if the branch is the `develop` branch however.  This could have ramifications if one ever sets a regression baseline to non-develop and that other branch's most recent commit has the skip comment.  That is a wild corner case though.  I'll be watching testing and watching CI to make sure it's working OK.  If something goes awry I'll revert and it'll settle back down.

**Comment by Myoldmopar** [comment]
(https://github.com/Myoldmopar/decent_ci/pull/47)

**Comment by Myoldmopar** [comment]
I'm going to mark this complete for now.  We can always tweak the behavior later.

**Comment by JasonGlazer** [comment]
@Myoldmopar thanks for implementing this so quickly. I think this is going to be a useful feature for developers and will reduce the burden on the CI. 

Where do you think it should be documented? 

Maybe we should talk about it on the next technicalities call.
