### ISSUE TITLE
PythonPlugin:SearchPaths Add Input File Directory to Search Path input not working with EP-Launch

### ISSUE THREAD

**Issue by matthew-larson** [NREL/EnergyPlus#8981]
Issue overview
--------------
When using the PythonPlugin:SearchPaths object and setting the field Add Input File Directory to Search Path to "Yes" and running the model through EP-Launch, it results in a fatal error that the module can't be found.  This appears to be due to the fact that EP-Launch makes a copy of the input file in a different directory, which doesn't get included in the search paths for the python module.

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.5

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by bonnema** [comment]
Does setting the [Add Current Working Directory to Search Path](https://bigladdersoftware.com/epx/docs/9-5/input-output-reference/group-python-plugins.html#field-add-current-working-directory-to-search-path) field to `Yes` have any impact?

**Comment by matthew-larson** [comment]
Having both of them set to "Yes" has the same effect.  I found the section in the source code where the python search paths are set and we are putting a fix in now that should resolve this issue.
