### ISSUE TITLE
Hard crash in ITE equipment for uncontrolled zone. 

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlus#8986]
Issue overview
--------------
User file had ITE equipment in a zone with no HVAC equipment, ie. not a controlled zone.  Got a hard crash in the following code block. 

Need a trap in case zoneEqIndex  returns 0 so it won't then crash in the next lines. 

```
                // check supply air node for matches with zone equipment supply air node
                int zoneEqIndex =
                    DataZoneEquipment::GetControlledZoneIndex(state, state.dataHeatBal->Zone(state.dataHeatBal->ZoneITEq(Loop).ZonePtr).Name);
                auto itStart = state.dataZoneEquip->ZoneEquipConfig(zoneEqIndex).InletNode.begin();
                auto itEnd = state.dataZoneEquip->ZoneEquipConfig(zoneEqIndex).InletNode.end();
```

When that gets trapped, it then crashes again here 

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/InternalHeatGains.cc#L6810

Of course the ITE closet with no cooling blows up eventually but it will terminate gracefully rather than hard crash. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@EnergyArchmage Was looking at this a little bit here to see if it's something I could work on.  My question for you is: if it's going to blow up anyway, should this just be trapped and EnergyPlus exit gracefully via Severe/Fatal errors?  There are probably ways around the index related crashes.  However, if this shouldn't be allowed, then the approach might be different perhaps.  Just curious (also if you are already or plan on working on this, let me know and I'll leave it all for you).

**Comment by EnergyArchmage** [comment]
I am not planning on doing more on this. You could have a low power closet with ventilation that should be able to run. It is a big ITE load in a an uncontrolled zone that will likely terminate

**Comment by RKStrand** [comment]
@EnergyArchmage The issue overview mentions a user file.  Any chance you could share that with me?  Thanks!

**Comment by RKStrand** [comment]
@EnergyArchmage I went ahead and created my own file using a modified version of 1ZoneUncontrolled.idf that has an ITE added to it.  It crashes in develop but I have fixed that and will create a pull request shortly.  I'm still waiting on results from CI but it seems pretty likely that it should come back clean.  I'll tag you as a potential reviewer but feel free to ignore that if you don't have time/funds to review this.  I'll also suggest the usual suspects as other potential reviewers.  Also, if you are able to post the user file and/or use it to test this fix, that would be great.  Thanks!

**Comment by EnergyArchmage** [comment]
Thanks @RKStrand , the file I had is huge 13megs and would have been a chore to clean up for DOE version.

**Comment by RKStrand** [comment]
@EnergyArchmage Totally get that.  I've been dealing with some pretty big user input files for some recent bugs.  They can be a total bear to work with because they are so big and complex.  Glad I went ahead and created a pretty simply file that demonstrated the problem.  It's up in EnergyPlusDevSupport now.
