### ISSUE TITLE
Airflow unit conversion recognition in IDD

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8989]
Issue overview
--------------
There seems to be a warning coming up whenever an idf file is opened using the EP-Launch IDFEditor. The message is like this:
![image](https://user-images.githubusercontent.com/64040111/130270014-e0c1dd7d-cd3a-4f8b-9d08-ca590448591c.png)

It traces back to the following lines in the IDD file (in object AirflowNetwork:MultiZone:SpecifiedFlowRate):
```
 A2 ; \field Air Flow Units
      \type choice
      \key kg/s
      \key m3/s
      \default kg/s
      \note Enter the units of the air flow value.
```

It does not seem to affect the simulation to run successfully; and this pops up only in recent develop commits. However, it shows up whenever opening an idf via IDFEditor even if there isn't any `AirflowNetwork:MultiZone:SpecifiedFlowRate` object in the input file. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows
 - Version of EnergyPlus (if using an intermediate build, include SHA): only in recent pre-release v9.6 (e.g. commit fb325cb83c)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
IO Freeze should be wrapped up soon, but this one really should be addressed ahead of it.  I do not understand why EPLaunch is complaining about this from a units perspective when this field is a type choice.

**Comment by jcyuan2020** [comment]
It is actually not related to EP-Lauch---even when starting the IDFEditor from the startup menu or direct double click the exe, the warning message would show up. The problem is in the IDFEditor when loading/reading the .idd file (maybe related to the the slash processing in the new keys?)

**Comment by Myoldmopar** [comment]
Yeah sorry, I said EP Launch in my comments, but meant IDF Editor.
