### ISSUE TITLE
AIRLOOPHVAC:OUTDOORAIRSYSTEM transitions for the 3-line cases

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#8995]
Issue overview
--------------
In earlier versions, the AIRLOOPHVAC:OUTDOORAIRSYSTEM can take a block of either 3-line or 4-line inputs. The new transition for v9.6 is now dropping the last line (`Availability Manager List Name`) to make it a 3-line object. This is working well for the 4-line case---the newly transition filed will be reduced to a 3-line object by dropping the redundant `Availability Manager List Name` line. 

However, earlier versions also allow a 3-line version of the AIRLOOPHVAC:OUTDOORAIRSYSTEM without a fourth line (so no `Availability Manager List Name` line)—for example, according to v9.5 IOReferece, this 3-line version is also a valid input. Now there is a conversion problem. If this type of 3-line version is converted up to v9.6 (pre-release), it will be reduced to a 2-line object, which will immediately cause an error when running the newly transitioned idf case (since the third line is essential and should not be dropped). 

The root cause  should be here
https://github.com/NREL/EnergyPlus/blob/163a5b006fe9c924428b0e43410b2afd5a166ee0/src/Transition/CreateNewIDFUsingRulesV9_6_0.f90#L400
where `CurArgs` should be reduced by 1 only for the 4-line version, but be kept the same for the 3-line version. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): pre-release v9.6 (e.g. 163a5b006f)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@Myoldmopar @mjwitte So, should the problematic line have been:

CurArgs = 3

Would that have correctly resolved this issue?  Can this still be fixed given we are past the IO Freeze?

**Comment by mjwitte** [comment]
I'm confused. There's no Schedule field in AirLoopHVAC:OutdoorAirSystem. From a v9.5 example file:
```
  AirLoopHVAC:OutdoorAirSystem,
    OA Sys 1,                !- Name
    OA Sys 1 Controllers,    !- Controller List Name
    OA Sys 1 Equipment,      !- Outdoor Air Equipment List Name
    VAV Sys 1 Avail List;    !- Availability Manager List Name
```
Do you have a 3-line version of this that actually runs without error in v9.5?

**Comment by jcyuan2020** [comment]
@mjwitte Sorry I mean the last line anyway---it should be the `Availability Manager List Name`.

**Comment by jcyuan2020** [comment]
@mjwitte Yes. I do have one idf that can get processed correctly in v9.5. Also, in the IORef (v9.5), it has the following description: 

![image](https://user-images.githubusercontent.com/64040111/130466657-0eb707d8-f18b-4602-8575-a7b0a5bf937c.png)

And IORef also gives an example object (3-line version):
![image](https://user-images.githubusercontent.com/64040111/130466861-0574f104-fc6d-4dcf-a715-77eab4cabeb8.png)

**Comment by mjwitte** [comment]
@jcyuan2020 Oh, I see. You're right. It does run fine in v9.5 without this field. So, yes, the transition code should be changed and probably have an if `CurArgs=4` so it does nothing it there's only 3 incoming fields. 
@RKStrand Yes, there's still time to fix this, today, with a new PR.

**Comment by RKStrand** [comment]
@mjwitte I'm on it.  So, to expedite this and make sure it gets in today, the preference on what the code should say is:

IF (CurArgs == 4) THEN
  CurArgs = 3
END IF

and this should replace the current:

CurArgs = CurArgs - 1

Correct?

**Comment by mjwitte** [comment]
The IF/ENDIF could wrap everything after the CASE statement.

**Comment by RKStrand** [comment]
@mjwitte Everything?  So:

              CASE('AIRLOOPHVAC:OUTDOORAIRSYSTEM')
                  IF (CurArgs == 4) THEN                 
                      CALL GetNewObjectDefInIDD(ObjectName,NwNumArgs,NwAorN,NwReqFld,NwObjMinFlds,NwFldNames,NwFldDefaults,NwFldUnits)
                 .    nodiff=.false.
                      OutArgs(1:3)=InArgs(1:3)
                      CurArgs = 3
                  END IF

Is that what it should look like/what you'd like to see?  Sorry if I'm being super specific.  I want to make sure this gets done today and it's easier to do back and forth before clogging up the CI.  Thanks!

**Comment by mjwitte** [comment]
@RKStrand I think that should work just fine. @jcyuan2020 Can test it (thanks) for both 3 and 4 line examples.

**Comment by jcyuan2020** [comment]
@RKStrand @mjwitte I did a test on on the new branch. But it has a new problem for the 3-line case now. A 3-line object gets converted to an empty 3-line object: 
```
  AirLoopHVAC:OutdoorAirSystem,
    ,                        !- Name
    ,                        !- Controller List Name
    ;                        !- Outdoor Air Equipment List Name
```

**Comment by mjwitte** [comment]
Hmm, oh well, I got too clever, sorry. @RKStrand Narrow the scope of the IF/THEN back to your original proposal.

**Comment by RKStrand** [comment]
@mjwitte @jcyuan2020 Ok, I've bounced it back to what I originally proposed and made another commit.  How are things looking with this variation?

I realize this is an unusual case--normally we aren't getting rid of input like this.  I hope to remember this if I have to do something like this again.

**Comment by jcyuan2020** [comment]
I tested both a 4-line case and a 3-line case, the new changes work perfectly in converting both cases 👍. @RKStrand  @mjwitte

**Comment by rraustad** [comment]
5ZoneAirCooled.idf

V9.5:

      AirLoopHVAC:OutdoorAirSystem,
        OA Sys 1,                !- Name
        OA Sys 1 Controllers,    !- Controller List Name
        OA Sys 1 Equipment;      !- Outdoor Air Equipment List Name
    !    VAV Sys 1 Avail List;    !- Availability Manager List Name

V9.6 transition:

      AirLoopHVAC:OutdoorAirSystem,
        OA Sys 1,                !- Name
        OA Sys 1 Controllers,    !- Controller List Name
        OA Sys 1 Equipment;      !- Outdoor Air Equipment List Name

    !    VAV Sys 1 Avail List;    !- Availability Manager List Name
