### ISSUE TITLE
energyplus weather website getting 404 if directly accessed

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9036]
Issue overview
--------------
A user reported that she encountered 404 warning when trying to access energyplus weather site. 

A quick investigation shows that the website: energyplus.net/weather cannot be directly accessed (neither https or http), a 404 error would just show up: 
![image](https://user-images.githubusercontent.com/64040111/131735772-9b8cf89a-783c-4858-a11b-9013fd4e3d85.png)

However, it is found that if you access energyplus.net first; and then click the "Weather" item on the top banner (the last item on the banner), then the energyplus.net/weather could be accessed without problems:
![image](https://user-images.githubusercontent.com/64040111/131736133-a02be52a-90ac-46da-a4b9-756371ff86d4.png)

Weather files could also be downloaded from there (after following the above workaround steps)--so this could be a temporary workaround. 

So it seems that the website is picky about where the click is originated and the issue may need some attention. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): energyplus.net/weather
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Helpdesk ticket number: 16011, 16012

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by kandersolar** [comment]
Howdy, [pvlib python](https://github.com/pvlib/pvlib-python) has a function to fetch data from urls under `energyplus.net/weather` and our automated test suite just started failing w/ this 404 issue.  I played around a bit with `referer` headers but I think that's barking up the wrong tree if the whole `energyplus.net` website is a single page application like I suspect it is (kind of out of my depth here).

Is it safe to assume that direct access to urls under `energyplus.net/weather` will work again at some point before too long, or should we pursue some other way of programmatically accessing those data files?  Thanks!

**Comment by mikofski** [comment]
they move from ghpages to aws s3, new links are here:
https://energyplus-weather.s3.amazonaws.com/europe_wmo_region_6/NLD/NLD_Amsterdam.062400_IWEC/NLD_Amsterdam.062400_IWEC.epw

**Comment by kflemin** [comment]
@jcyuan2020, we ported the site to a new platform today and are resolving some issues with the routing system. Should be addressed soon!

**Comment by jcyuan2020** [comment]
@kflemin  Thanks! I can see it is working again now.

**Comment by jcyuan2020** [comment]
@kflemin Sorry another user ticket came in about the download link on the map: 
"Hello, I am having a problem with the EnergyPlus weather file downloads. Whenever I go to https://energyplus.net/weather and select a weather station, instead of taking me directly to that weather station, the page redirects me to https://energyplus.net/ . Obviously this is not good, as it is preventing me from downloading any weather files I need. Your help is much appreciated. "

I tested it out and it seems that the map download does have the problem. Downloading via the region->country->state list chain are still working fine.

**Comment by kflemin** [comment]
@jcyuan2020, yes we are working on that...I will let you know when that is fixed! Browsing to the weather station or using the search bar should work now (just not the map).

**Comment by shorowit** [comment]
@kflemin Note that when you search for e.g. "Denver", the resulting hits just link back to energyplus.net rather than the actual weather files.

**Comment by kflemin** [comment]
thanks @shorowit. we are almost done with the changes and should have those deployed shortly.

**Comment by kflemin** [comment]
@shorowit, @jcyuan2020: search issues should all be resolved now!

**Comment by jcyuan2020** [comment]
Thanks @kflemin ! One minor issue I noticed is that when I left-click the links "Download All" (or "Download weather file" or the others such as "Download stat" etc) from the popped-out menu of a map pin, it will do nothing. However, doing a right-click and then select the "Save Link as" menu in the browser pop-up menu it will work and download file properly--for both Mozilla Firefox or Microsoft Edge. I wonder if this is intended to be? The "Go to folder" is working fine with a left-click.

**Comment by kflemin** [comment]
@jcyuan2020, I believe it should be fixed now!  thanks, @axelstudios !

**Comment by Myoldmopar** [comment]
Everything looks to be working perfect now, I'm going to close this.  @jcyuan2020 if you identify any remaining issues, feel free to reopen or open a new ticket.  Thanks all!
