### ISSUE TITLE
ABUPS 'Total Source Energy' does not include Electricity when FuelFactors are used

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#9042]
Issue overview
--------------
When Electricity FuelFactors are used in a model, the ABUPS table 'Site and Source Energy' will not include Electricity Source energy in the 'Total Source Energy' row.

To reproduce: 
Take an example file that has Electricity FuelFactors, e.g. 'AirEconomizerFaults_RefBldgLargeOfficeNew2004_Chicago.idf'. Simulate an annual run period. The Site and Source Energy table will only report Gas source energy in the 'Total Source Energy' row (Net Source Energy will be correct). 

![image](https://user-images.githubusercontent.com/10799524/131926709-21932968-ec1c-4a3b-8d92-dcc8962070db.png)

![image](https://user-images.githubusercontent.com/10799524/131926618-6df08007-0eab-4553-80c1-51fcef933ee9.png)

![image](https://user-images.githubusercontent.com/10799524/131926745-dfbfdcad-f7f2-49fb-a41a-68017b765d56.png)

5130.83 * 1.092 = 5602.87 

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: 9.5

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by eringold** [comment]
Maybe related to https://github.com/NREL/EnergyPlus/issues/7466

**Comment by eringold** [comment]
OK I _think_ this is happening because:

When FuelFactors are used, Total Source Energy is gathering from the first element of [`gatherTotalsSource`](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/OutputReportTabular.cc#L8118) array.

`gatherTotalsSource` array is populated from [`meterNumTotalsSource`](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/OutputReportTabular.cc#L3961).

which is assigned from a call to `GetMeterIndex` with [`ort->sourceTypeNames(iResource) + "Emissions:Source"`](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/OutputReportTabular.cc#L1809).

where `sourceTypeNames(1)` is ["Electricity"](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/OutputReportTabular.cc#L1738).

So it's looking for meter "ElectricityEmissions:Source".
But looking at the .mtd file of the defect run, it has "ElectricEmissions:Source":
![image](https://user-images.githubusercontent.com/10799524/132032989-e0eb08ef-2058-4fc3-b05d-9458584bea59.png)

I'm not sure where these meter names get setup. [Here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/PollutionModule.cc#L3016-L3244)? Should they all be 'ElectricityEmissions'?

**Comment by matthew-larson** [comment]
I can look at getting this one resolved, unless there are any other takers out there.
