### ISSUE TITLE
Report variable Environmental Impact OtherFuel1 CO2 Water Consumption Volume makes no sense

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#9069]
Issue overview
--------------
Recent review of emissions reports shows a strange inference to CO2 Water Consumption Volume. The V9.5 and V9.6 both show Environmental Impact OtherFuel1 Water Consumption Volume as the report name. Yet the latest code shows:

PollutionModule.cc 
    SetupOutputVariable(state, "Environmental Impact OtherFuel1 CO2 Water Consumption Volume"
    SetupOutputVariable(state, "Environmental Impact OtherFuel2 CO2 Water Consumption Volume"

![image](https://user-images.githubusercontent.com/5778156/133668926-738ac331-c2ff-4442-a0aa-e47db90b361a.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by matthew-larson** [comment]
@rraustad Looking to close out some easy issues, mind if I take this one?  I can do a pass-through of all the output variables as well.

**Comment by rraustad** [comment]
Go right ahead.
