### ISSUE TITLE
LaTeX Error 

### ISSUE THREAD

**Issue by Myoldmopar** [NREL/EnergyPlus#9092]
Issue overview
--------------
A LaTeX build error recently popped up:

```
[LATEXERROR::doc/input-output-reference/src/appendix-a-units-and-abbreviations/standard-energyplus-units.tex:None::LaTeX Error: \begin{itemize} on input line 182 ended by \end{document}.]
```

The line number is in relation to a root document, not the actual line number in the file listed there.  I tried a little poking around to find the dangling itemize but couldn't find it quickly.  It would probably be easiest to just bisect to find where it came in.

**Comment by mjwitte** [comment]
This has been addressed in #9132
