### ISSUE TITLE
Old Versions of Eplus; Access to?

### ISSUE THREAD

**Issue by oldusertoday** [NREL/EnergyPlus#9099]
Issue overview
--------------
Hi, 
I'm querying if there's anywhere on the web where I can access versions of Eplus which will work with 32-bit Windows Vista? A google search would suggest, no;

I previously worked in co-simulation, integrating Matlab , BCVTB and V5.0 Eplus and will be re-engaging with this setup, but on a 32-bit windows vista system (unfortunately, I will not be able to upgrade to Windows 10 or any other OS).

I was planning on just installing the earliest available version of Eplus, though when I attempt to run 32-bit Version 8.7 (earliest available to download) on the 32-bit Vista, I receive --and is covered in another issue thread, since closed-- "Component MSCOMTL.OCX or one of its dependencies not correctly registered: file is missing or invalid"

Any suggestions on how to proceed (or if you have access to an older version of Eplus) would be of help;

(the other attributes--BCVTB, Matlab and exchange over the sockets, for integration I have enough experience to be able to de-bug)

OlduserToday

**Comment by rraustad** [comment]
Have you tried regisgtering or installing that file?

https://answers.microsoft.com/en-us/windows/forum/all/component-mscomctlocx-or-one-of-its-dependencies/4ae4dfc4-4a67-4927-990e-489cdb070efb
