### ISSUE TITLE
Kiva problem when using clockwise geometry rule

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9103]
Issue overview
--------------
The “Clockwise” rule is a much less frequently used option to most users, although it is still allowed and used by some users for some specifical needs. It was recently identified from an input file supplied by a user that used “clockwise” geometry rule, that would cause some essential lines of code block to be skipped inadvertently (and apparently incorrectly skipped). This will further cause EnergyPlus to crash due to floating-point overflow errors. 

The code that is apparently wrong is the condition statement of `i <= 0` in the following line: 
https://github.com/NREL/EnergyPlus/blob/f420c06a69737dddcf4ba740ad855b45a03a8ef3/src/EnergyPlus/HeatBalanceKivaManager.cc#L733

The correct statement should be `i >=0`. A temporary fix is placed to fix the apparent code errors above. It is not clear if this would be a full fix to the issue yet.

It is expected that the specific problem should not occur if a default “CounterClockWise” geometry rule (and the correct geometry specification and also other “correct” inputs). So sticking to the default and more commonly used “CounterClockWise” should avoid the problem. 

The above line is the obvious one that needs to be fixed (actually tried to fix in PR #9104). However, it seems that change alone would not fully fix the problem--the defect file would not go through and still encounters problems in other part of the foundation calculations. There could be more deeper changes needed for the Kiva foundation part that would be needed to make the defect file finally work (@nealkruis). Another test was conducted by changing the geometry rule to CounterClockWise and reverting all the surface vertex input orders from the orignal defect file---that actually yield a case that could run through without any problems. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): at least from v9.4 to v9.6
 - Unmethours link or helpdesk ticket number 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9103/9103_Kiva_Clockwise.idf))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jcyuan2020** [comment]
@nealkruis The line mentioned in the top comment is the obvious one that needs to be fixed (actually tried to fix in PR #9104). However, it seems that change alone would not fully fix the problem--the defect file would still encounter problems in later part of the code which seems deeper in the foundation calculations. So there could be more deeper changes needed for the Kiva foundation part that would be needed to make the defect file finally work. 

Another test was conducted by changing the geometry rule to CounterClockWise and reverting all the surface vertex input orders from the original defect file---that actually yielded a case that could run through without any problems. See this file [here](https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9103/9103_Kiva_CounterClockWise_OK.idf). 

Please feel free to ditch the PR #9104 tentative changes and start a new fix on the issue as needed.

**Comment by nealkruis** [comment]
@jcyuan2020 it's up to you. We can have separate PRs or I can add this to a new one. I will assign this issue to me.

**Comment by jcyuan2020** [comment]
@nealkruis Thanks!

**Comment by nealkruis** [comment]
@Myoldmopar I haven't had a chance to review this. Is the defect file working now, or were there more changes that needed to be made?
