### ISSUE TITLE
Documentation 2021c

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#9111]
Issue overview
------

A place to collect requested documentation fixes. Add a new comment to the issue with new doc-change-only issues. Someone will eventually fix them all up at the same time once critical mass has been reached.

**Comment by jmarrec** [comment]
* [x] Space Name isn't documented in I/O ref for `BuildingSurface:Detailed`, `Floor:Detailed`, etc
     * https://github.com/NREL/EnergyPlus/blob/2ad67318cfe34c038d73081846e141c43440678b/doc/input-output-reference/src/overview/group-thermal-zone-description-geometry.tex#L2143-L2149 missing the 'Space Name' in between 'Zone Name' and 'Outside Boundary Condition'
    * [x] `Space or SpaceList Name` is not documented in `InternalMass` either
          * **Incidentally** since `Space or SpaceList Name` is not used if 'Zone or ZoneList' field is used, I find it weird that that this wouldn't be a single field like `Zone or ZoneList or Space or SpaceList Name` like it's done on many object**

* [ ] Be explicit about the need for Zone, Space, ZoneList, and SpaceList names to be unique among the four groups.

**Comment by shorowit** [comment]
- [x] Incorrect output variables for some Coil:WaterHeating objects; see https://github.com/NREL/EnergyPlus/issues/9124#issuecomment-940121827

**Comment by mitchute** [comment]
- [ ] DHW Documentation Issues. See #9143 and resolve any doc-change issues.

**Comment by mjwitte** [comment]
- [x] In the I/O Ref, for ZoneHVAC:EquipmentConnections, the overview and the field description for "Zone Return Air Node or NodeList Name" still say that Return Node is required. The idd does not tag this as required. I'm 99% certain it is no longer required. Should probably test this before changing the docs.

**Comment by shorowit** [comment]
- [x] "generatros" appears twice instead of "generators" in https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-electric-load-center-generator.html

**Comment by shorowit** [comment]
- [x] The [zone name](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-electric-load-center-generator.html#liion-zone-name) field for the Li-ion battery only describes how the zone is used with respect to heat gains. It should also include language stating that the zone temperature is used by the battery (or if no zone is provided, outside temperatures are used). See [the code](https://github.com/NREL/EnergyPlus/blob/f355562c8937495dc098b66c76914045b9056518/src/EnergyPlus/ElectricPowerServiceManager.cc#L4308-L4315).

**Comment by shorowit** [comment]
- [x] The `Output:JSON` object added in https://github.com/NREL/EnergyPlus/pull/6192 cannot be found anywhere in the I/O Ref or the OutputDetailsAndExamples documentation.

**Comment by michaldengusiak** [comment]
- [x] In the Engineering Reference, under Heat Gain From Lights, the units for Cp are incorrect., 

please refer to https://unmethours.com/question/65109/value-for-cp-specific-heat-of-air/

(J/kg should be J/kg−K) in the EnergyPlus documentation


- [x] In the Engineering Reference, for Fanger Comfort Model, abbrevation and order

https://bigladdersoftware.com/epx/docs/8-7/engineering-reference/occupant-thermal-comfort.html#fanger-comfort-model 

![image](https://user-images.githubusercontent.com/26113670/144300229-b46a5cde-bef7-435c-a904-ff6e89c69473.png)

- [x] abrevation and order
![image](https://user-images.githubusercontent.com/26113670/144302471-938d321a-d656-47f3-aabe-368b209907e6.png)

**Comment by JasonGlazer** [comment]
- [x] UtilityCost:Computation EXCEEDS has operands reversed according to this comment on [unmethours](https://unmethours.com/question/66028/utilitycostcomputation-does-not-work/). The IOref should say: "Returns the difference between the first and second variable if the second variable is greater than the first. If the first variable is greater or equal to the second variable returns a zero."

**Comment by eringold** [comment]
- [x] Multiple objects in Energy+.idd have the following \memo lines;
```
\memo a list of meters that can be reported are available after a run on
\memo the meter dictionary file (.mdd) if the Output:VariableDictionary has been requested.
```
Objects are:
```
DemandManagerAssignmentList,
ElectricLoadCenter:Transformer,
ElectricLoadCenter:Distribution,
Output:Meter:MeterFileOnly,
Output:Meter:Cumulative,
Output:Meter:Cumulative:MeterFileOnly,
```
Seems appropriate for Output:Meter types, but not DemandManager or ElectricLoadCenter.

**Comment by mjwitte** [comment]
> Seems appropriate for Output:Meter types, but not DemandManager or ElectricLoadCenter.

Those memos should be expanded to describe the object (that's what memos are for), but referencing the mdd is appropriate, because these objects have input fields which are meter names. Perhaps these line should be \notes at the first meter name field.

**Comment by lymereJ** [comment]
- [x] Small typo in the description of High/Low System Node Setpoint Temperature: "upper" is used to describe both outputs.

![image](https://user-images.githubusercontent.com/5149279/149986225-70fb1db0-11ce-48f2-bf8f-3e4710d1b087.png)

**Comment by jmarrec** [comment]
* [ ] `Coil:WaterHeating:AirToWaterHeatPump:VariableSpeed`: Output variables look weird as they mention "Cooling Coil" when really this is a heating one. The :Wrapped and :Pumped ones correctly mention "Heating Coil XXX". 
    * https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-heating-and-cooling-coils.html#vshpwhheating-outputs
    * https://github.com/NREL/EnergyPlus/blob/2f3618a629077d45308382a808b82c81e87a697b/doc/input-output-reference/src/overview/group-heating-and-cooling-coils.tex#L6613-L6668

**Comment by shorowit** [comment]
@jmarrec That is apparently intentional. Note where the documentation says: “This coil draws heating energy from air to the heater. Thus it is regarded as a cooling coil, as shown in the output variable names.”

**Comment by jmarrec** [comment]
@shorowit I understand the rationale, but the discrepancy with the Pumped and Wrapped coils bothers me.

**Comment by shorowit** [comment]
@jmarrec Ah! I just remembered that this has been brought up before and, actually, the Pumped and Wrapped coils are incorrectly documented. This issue is captured above in this issue [here](https://github.com/NREL/EnergyPlus/issues/9111#issuecomment-940122434) and you can see the discussion on it [here](https://github.com/NREL/EnergyPlus/issues/9124#issuecomment-940121827).

**Comment by eringold** [comment]
- [x] I/O ref for ElectricLoadCenter:Distribution lists old '... Electric Demand Power' outputs: 
https://github.com/NREL/EnergyPlus/blob/c17e07c8ba6f2c31403f2f7bf14ee2b51ebbada8/doc/input-output-reference/src/overview/group-electric-load-center-generator.tex#L432-L436
Which should be "...Electricity Demand Rate":
https://github.com/NREL/EnergyPlus/blob/2f8b2517baa1e6e553fe766f4587a0926b4f5032/src/Transition/SupportFiles/Report%20Variables%209-3-0%20to%209-4-0.csv#L171-L173

**Comment by RKStrand** [comment]
- [x] In the documentation for the recently split up input for variable and constant flow radiant systems (into design and system specific data), the "design data" has been added as a subsection under the sections for these objects.  However, there is no text that really describes the fact that the user will need both the design and system specific data and the design data is somewhat lost in that it is subsection "2" while subsection "1" is labeled "input".  This could be confusing and should be addressed.  In addition, in the constant flow section, the temperature control schedules mention a temperature control type "above", but that information was moved to the design data which actually comes after this.  So, this needs to be cleaned up and maybe a quick double check of similar issues in the other radiant system models need to be made while we are at it.  Example:

![image](https://user-images.githubusercontent.com/5804989/153477125-e0f93b05-1d03-4ecc-97d9-37a26bb113b8.png)
![image](https://user-images.githubusercontent.com/5804989/153477257-8ec8e747-aeab-4eb0-bdeb-dd2d08f09697.png)

**Comment by aaron-boranian** [comment]
- [ ] [Make-up Water Supply Schedule Name](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-internal-gains-people-lights-other.html#field-make-up-water-supply-schedule-name) input field of `SwimmingPool:Indoor` object claims that field can be left blank to use same calculations as site's water mains temperature, but leaving blank results in severe error that stops the simulation. The IDD also lists this input field as required, so "if blank" references  in bold below should be removed.

I/O Ref:

The scheduled named by this field establishes a cold water temperature [C] for the water that replaces the water which is lost from the pool due to evaporation. **If blank, water temperatures are calculated by the [Site:WaterMainsTemperature](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-location-climate-weather-file-access.html#sitewatermainstemperature) object.** This field **(even if blank)** overrides the Cold Water Supply Temperature Schedule in all of the listed [WaterUse:Equipment](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-water-systems.html#wateruseequipment) objects.

Also, is last sentence true (this field overrides cold water supply temperature for **ALL** water use equipments?

Severe Error:
   ** Severe  ** <root>[SwimmingPool:Indoor][Indoor Pool] - Missing required property 'make_up_water_supply_schedule_name'.
   **  Fatal  ** Errors occurred on processing input file. Preceding condition(s) cause termination.

**Comment by mjwitte** [comment]
> * [ ]  [Make-up Water Supply Schedule Name](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-internal-gains-people-lights-other.html#field-make-up-water-supply-schedule-name) input field of `SwimmingPool:Indoor` object claims that field can be left blank to use same calculations as site's water mains temperature, but leaving blank results in severe error that stops the simulation. The IDD also lists this input field as required, so "if blank" references  in bold below should be removed.
> 
> I/O Ref:
> 
> The scheduled named by this field establishes a cold water temperature [C] for the water that replaces the water which is lost from the pool due to evaporation. **If blank, water temperatures are calculated by the [Site:WaterMainsTemperature](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-location-climate-weather-file-access.html#sitewatermainstemperature) object.** This field **(even if blank)** overrides the Cold Water Supply Temperature Schedule in all of the listed [WaterUse:Equipment](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-water-systems.html#wateruseequipment) objects.
> 
> Also, is last sentence true (this field overrides cold water supply temperature for **ALL** water use equipments?

@aaron-boranian Probably not. Looks like this is a pasteo from another object. Code inspection or a quick test run should answer for sure.

> 
> Severe Error: ** Severe ** [SwimmingPool:Indoor][Indoor Pool] - Missing required property 'make_up_water_supply_schedule_name'. ** Fatal ** Errors occurred on processing input file. Preceding condition(s) cause termination.

Sounds like this is just an idd error, but you'll need to check the code and test with the required tag removed to see if it all works as exepected.

**Comment by jcyuan2020** [comment]
- [x] Incorrect equation for convective coefficient definition in Engineering Ref: 
![image](https://user-images.githubusercontent.com/64040111/160058775-931a5c8e-8a49-483e-bf46-ebf420f116b9.png)

**Comment by jcyuan2020** [comment]
- [x] The IDD entry does not agrees with this: 
![image](https://user-images.githubusercontent.com/64040111/160059121-e572720f-cb63-49b9-93bb-9e8bd73cb995.png)

**Comment by jcyuan2020** [comment]
- [x] The field name does not have "External" and also the choice name should be "Imported": 
![image](https://user-images.githubusercontent.com/64040111/160059402-c06282d3-88a9-4d1e-a404-86c2c7b60dce.png)

**Comment by jcyuan2020** [comment]
- [x] The separation line after the first row in the table is not needed: 
![image](https://user-images.githubusercontent.com/64040111/160059826-8b61ff07-5313-48f7-a558-0e15b54a45f1.png)

**Comment by jcyuan2020** [comment]
> * [x]  UtilityCost:Computation EXCEEDS has operands reversed according to this comment on [unmethours](https://unmethours.com/question/66028/utilitycostcomputation-does-not-work/). The IOref should say: "Returns the difference between the first and second variable if the second variable is greater than the first. If the first variable is greater or equal to the second variable returns a zero."

This change is now completed in the IORef. However, the "correct" definition actually seems to be very counter-intuitive.

**Comment by jcyuan2020** [comment]
> @jmarrec Ah! I just remembered that this has been brought up before and, actually, the Pumped and Wrapped coils are incorrectly documented. This issue is captured above in this issue [here](https://github.com/NREL/EnergyPlus/issues/9111#issuecomment-940122434) and you can see the discussion on it [here](https://github.com/NREL/EnergyPlus/issues/9124#issuecomment-940121827).

The output variables' naming for the pumped and wrapped Coil:WaterHeating:AirToWaterHeatPump are now changed according to the discussion.

**Comment by jcyuan2020** [comment]
> * [x]  In the documentation for the recently split up input for variable and constant flow radiant systems (into design and system specific data), the "design data" has been added as a subsection under the sections for these objects.  However, there is no text that really describes the fact that the user will need both the design and system specific data and the design data is somewhat lost in that it is subsection "2" while subsection "1" is labeled "input".  This could be confusing and should be addressed.  In addition, in the constant flow section, the temperature control schedules mention a temperature control type "above", but that information was moved to the design data which actually comes after this.  So, this needs to be cleaned up and maybe a quick double check of similar issues in the other radiant system models need to be made while we are at it.  Example:
> 
> 
> ![image](https://user-images.githubusercontent.com/5804989/153477125-e0f93b05-1d03-4ecc-97d9-37a26bb113b8.png) ![image](https://user-images.githubusercontent.com/5804989/153477257-8ec8e747-aeab-4eb0-bdeb-dd2d08f09697.png)

The following changes are applied now: 
1. The section headings for "ZoneHVAC:LowTemperatureRadiant:ConstantFlow:Design" and "ZoneHVAC:LowTemperatureRadiant:VariableFlow:Design" are now pumped one level up to be in the same level as the two parent objects. Each is placed right after the parent object. 
2. Added hyperref to the parent objects "Design Object" input field description to point to their own "xxx:Design" section. 
3. According to the IDD, it is not so clear if a "Design Object" is absolutely required, since this is not marked as a required field there. So probably will leave this to later determinations about if a design object should always be required. Currently using the added hyperref in item 2 to slightly emphasize the linkage. 
4. Addressed the pointing issue in the "temperature control type" descriptions in each of the objects. 
5. Some typo corrections across a few different sections.

**Comment by jcyuan2020** [comment]
> > * [ ]   [Make-up Water Supply Schedule Name](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-internal-gains-people-lights-other.html#field-make-up-water-supply-schedule-name) input field of `SwimmingPool:Indoor` object claims that field can be left blank to use same calculations as site's water mains temperature, but leaving blank results in severe error that stops the simulation. The IDD also lists this input field as required, so "if blank" references  in bold below should be removed.
> > 
> > I/O Ref:
> > The scheduled named by this field establishes a cold water temperature [C] for the water that replaces the water which is lost from the pool due to evaporation. **If blank, water temperatures are calculated by the [Site:WaterMainsTemperature](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-location-climate-weather-file-access.html#sitewatermainstemperature) object.** This field **(even if blank)** overrides the Cold Water Supply Temperature Schedule in all of the listed [WaterUse:Equipment](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-water-systems.html#wateruseequipment) objects.
> > Also, is last sentence true (this field overrides cold water supply temperature for **ALL** water use equipments?
> 
> @aaron-boranian Probably not. Looks like this is a pasteo from another object. Code inspection or a quick test run should answer for sure.
> 
> > Severe Error: ** Severe ** [SwimmingPool:Indoor][Indoor Pool] - Missing required property 'make_up_water_supply_schedule_name'. ** Fatal ** Errors occurred on processing input file. Preceding condition(s) cause termination.
> 
> Sounds like this is just an idd error, but you'll need to check the code and test with the required tag removed to see if it all works as exepected.

The original text seems to be an accurate description of what's happening in the two code blocks below): 1). if left blank->will override with environment water mains temperature; 2). if not left blank but not a schedule match->will have `ErrorsFound = true' which is equivalent to a fatal-out; 3). for all other scenarios, it will take the schedule value. So here left blank and code running ok (only occurs in 1) is equivalent to having the value is overridden by water main temperature anyway. 

Based on: 
```
        if ((state.dataSwimmingPools->Pool(Item).MakeupWaterSupplySchedPtr == 0) && (!lAlphaBlanks(4))) {
            ShowSevereError(state, cAlphaFields(4) + " not found: " + Alphas(4));
            ShowContinueError(state, "Occurs in " + CurrentModuleObject + " = " + Alphas(1));
            ErrorsFound = true;
        }
```

and 
```
    if (this->MakeupWaterSupplySchedPtr > 0) {
        this->CurMakeupWaterTemp = ScheduleManager::GetCurrentScheduleValue(state, this->MakeupWaterSupplySchedPtr);
    } else {
        // use water main temperaure if no schedule present in input
        this->CurMakeupWaterTemp = state.dataEnvrn->WaterMainsTemp;
    }
```

So looks like an idd change to allow blank input is what's needed here.

**Comment by jcyuan2020** [comment]
- [x] Duplicated or redundant `Zone Thermal Output` section: 
Section 1.10.5: 
![image](https://user-images.githubusercontent.com/64040111/161393916-83a503c3-0e14-40d9-ace7-f97cfe3926d4.png)


Section 1.10.67: 
![image](https://user-images.githubusercontent.com/64040111/161393873-53135b03-0bef-44dd-a19e-1992aeba64a3.png)

It looks the latter may be some kind of residual from previous versions?

**Comment by eringold** [comment]
- [x] 'Output Details and Examples', eplustbl.<ext> states that units for 'Coil Entering/Leaving Air Enthalpy at Ideal Loads Peak' in the 'Coil Summary Table' within the HVAC Summary Report is [J/(kg-C)]: https://github.com/NREL/EnergyPlus/blob/44de4f7d8067ad59f1bb2ed1a4c6e83740eb3c6b/doc/output-details-and-examples/src/output-files/eplustbl-lt-ext-gt.tex#L1374

However the actual table displays these units to be [J/(kg*K)]: 
![image](https://user-images.githubusercontent.com/10799524/161795624-9d5d29de-0ffb-4927-b702-76b21a06f79f.png)
And is located in the 'Coils' table of the Coil Sizing Report.

**Comment by RKStrand** [comment]
- [x] In the constant flow radiant system documentation in the IO Ref, the underlined terms should say "Zone Radiant HVAC" not "Constant Flow".

![image](https://user-images.githubusercontent.com/5804989/163431559-7509c5f7-7075-44c2-8e3c-d8776906e242.png)

The sections that provide detail on these output variables after this got it right.
