### ISSUE TITLE
Surfaces in EnergyPlus v9.6.0 InputOutputReference PDF document do not include the Space Name field

### ISSUE THREAD

**Issue by eugeniorodrigues** [NREL/EnergyPlus#9114]
Issue overview
--------------
In EnergyPlus v9.6.0 InputOutputReference pdf document, the descriptions of all surfaces (Floor, Ceiling, Wall, BuildingSurface, etc.) do not include the field for Space Name or SpaceList Name.

**Comment by shorowit** [comment]
This has been noted in https://github.com/NREL/EnergyPlus/issues/9111
