### ISSUE TITLE
File with spaces suddenly has zero outside air when DesignSpecification:OutdoorAir is per person

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#9135]
Issue overview
--------------

File with spaces suddenly has zero outside air when DesignSpecification:OutdoorAir is per person

OpenStudio-resources regression tests are exhibit 0 outside air when we use E+ Spaces and DesignSpecification:OutdoorAir:SpaceList.

I will supply one example test model with two versions:
* No Spaces
* With Spaces

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.6.0
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here): https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9135
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Among other things, this was completely broken if the spacelist only had one item.
