### ISSUE TITLE
Unclear if 'DHW' is valid EndUse key

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#9143]
"DHW" shows up in the documentation a couple places as a valid end-use type. E.g. in the I/O Ref Table 5.3: End Use Category Types for Output:Meter
![image](https://user-images.githubusercontent.com/10799524/137945886-0965ca6b-151a-481e-97dc-9f47b78c84d3.png)

and https://github.com/NREL/EnergyPlus/blob/2f8b2517baa1e6e553fe766f4587a0926b4f5032/doc/getting-started/src/energy-meters/standard-energy-meters.tex#L116

But there is no "DHW" in DataGlobalConstant::EndUse https://github.com/NREL/EnergyPlus/blob/cf82e98489dfb281ca206fe089549b209644a89a/src/EnergyPlus/DataGlobalConstants.hh#L62-L78

Despite this, a number of output variables are setting EndUseKey to 'DHW', e.g.: 
https://github.com/NREL/EnergyPlus/blob/badf2e3a783bd0608582a05e5314ff9b64fb2f85/src/EnergyPlus/WaterThermalTanks.cc#L5323-L5334

Should all 'DHW' energy be changed to 'WaterSystems' and removed from the documentation? 

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: 9.5
https://unmethours.slack.com/archives/C0AJFLV1Q/p1634315663003100

**Comment by mjwitte** [comment]
Closed via #10011
