### ISSUE TITLE
Update LCC to use 2020 and 2021 NIST supplement 

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#9153]
Issue overview
--------------
Add LCCusePriceEscalationDataSet20xx.idf for the 2020 and 2021 EIA energy price projections using data from:

https://www.energy.gov/eere/femp/building-life-cycle-cost-programs

Please note a script is available to do update this via #7218 created by @MatthewSteen

**Comment by jmarrec** [comment]
Duplicate of #9551
