### ISSUE TITLE
Set Sizing:Parameters - Timesteps in Averaging Window when using PerformancePrecisionTradeoffs override mode

### ISSUE THREAD

**Issue by xuanluo113** [NREL/EnergyPlus#9159]
Issue overview
--------------
When using the `PerformancePrecisionTradeoffs` object with Override Mode 01-07, the number of timesteps in an hour is set to 1 (as 1-hour time step). However, the `Timesteps in Averaging Window` field in `Sizing:Parameters` is not set to 1 correspondingly. 
The `Timesteps in Averaging Window` field sets the timesteps in the averaging window to calculate the final zone sizing load curve in the 24-hour period, and the default field is the number of timesteps for the 1-hour averaging window. However, when users provide input values to this field, it's set to the user input. With the Override Modes overriding the simulation timestep but not the timestep in the averaging window for sizing, the sizing curve will not be calculated as expected.

The figure plots the example heating load curve when using timestep = 6 and timestep = 1, using `RefBldgOutpatientNew2004_Chicago.idf` in the testfile folder.
![image](https://user-images.githubusercontent.com/23508095/139379748-63d2684d-7eb4-4a23-9989-5d6f20c338d3.png) The peak load has large differences.

The simple fix can be a hard reset of the `Timesteps in Averaging Window` when using the override mode for performance.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Fixed in #9180
