### ISSUE TITLE
9.6 introduced invalid weather line to EPW used for BESTEST runs.

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/EnergyPlus#9161]
Issue overview
--------------
The EPW used for BESTEST runs fails to load with EnergyPlus 9.6. Has energy plus gotten more strict and is an update just needed to this weather file, or should this weather file still load into EnergyPlus. It was not a problem in 9.5 or earlier.

> Program Version,EnergyPlus, Version 9.6.0-4b123cf80f, YMD=2021.10.29 10:55,
   ** Warning ** Site:GroundTemperature:BuildingSurface: Some values fall outside the range of 15-25C.
   **   ~~~   ** These values may be inappropriate.  Please consult the Input Output Reference for more details.
   ** Severe  ** Invalid Weather Line at date=1959/ 1/ 1 Hour#= 1 Min#=60
   **   ~~~   ** Full Data Line=1959,1,1,1,60,?0?0E7_0E0?0?9D0?9?9?9?9?0?0?0?0?0?0?9?9?9?9,0.0,-6.6,57,82780,0,0,253,0,0,0,999900,999900,999900,99990,203,2.8,7,3,24.1,77777,0,999999999,0,0.0000,0,88
   **   ~~~   ** Remainder of line=88
   **  Fatal  ** Error in Reading Weather Data

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

Mac, E+ 9.6 here is link to GitHub BESTEST issue
https://github.com/NREL/BESTEST-GSR/issues/8

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jcyuan2020** [comment]
Helpdesk Ticket 16053 reported a similar problem--the following error message is shown: 
```
 Invalid Weather Line at date=2002/ 1/ 1 Hour#= 1 Min#=60
```

**Comment by mjwitte** [comment]
@DavidGoldwasser Please attach an idf and epw that show the issue. The epws that are used on CI and distributed with EnergyPlus don't seem to have this problem.

**Comment by jcyuan2020** [comment]
@DavidGoldwasser Do you have a defect file for this problem? The user who posted helpdesk Ticket 16053 supplied a file but it comes with quite some other errors/issues that prevent this to be singled out.

**Comment by mjwitte** [comment]
@jcyuan2020 Here's the BESTEST epw for this issue.
[DRYCOLDTMY.zip](https://github.com/NREL/EnergyPlus/files/7770764/DRYCOLDTMY.zip)

**Comment by Myoldmopar** [comment]
I'm not sure what else this needs, I was able to confirm the fix.

`$ ./energyplus -w /eplus/epw/DRYCOLDTMY.epw ../../../testfiles/1ZoneUncontrolled.idf`

- Develop: `Program terminated: EnergyPlus Terminated--Error(s) Detected.`
- This Branch: `EnergyPlus Completed Successfully.`
