### ISSUE TITLE
Site:WaterMainsTemperature `CorrelationFromWeatherFile` uses bogus values

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#9190]
Issue overview
--------------
Based on an [unmet hours post](https://unmethours.com/question/64396/why-is-sitewatermainstemperature-correlation-from-weather-file-locked-on-one-temperature-for-all-times-and-locations/), I verified that using `CorrelationFromWeatherFile` as the calculation method in the `Site:WaterMainsTemperature` object gives bogus results. Every stranger, the results are completely different (but equally bogus) across two different versions of EnergyPlus.

Both simulations below used USA_CO_Denver.Intl.AP.725650_TMY3.epw as the weather file (w/ no stat file in the run directory).

### EnergyPlus v9.4

The temperature ends up as 3.33 deg-C for every hour of the year:

![image](https://user-images.githubusercontent.com/5861765/141807081-7976d31b-dbd9-4800-8157-cd11b281d5fa.png)

![image](https://user-images.githubusercontent.com/5861765/141808779-07262e82-0345-47a3-a4da-32cc313bd0d9.png)

[in94.idf.txt](https://github.com/NREL/EnergyPlus/files/7539639/in94.idf.txt)

### EnergyPlus v9.6

The temperature ends up as approximately 47000000 deg-C for every hour of the year.

![image](https://user-images.githubusercontent.com/5861765/141807637-f669467a-4e43-4e77-91ec-222ce8057f55.png)

![image](https://user-images.githubusercontent.com/5861765/141807884-eef49fe0-ce64-4015-8844-db3470abd7fd.png)

[in96.idf.txt](https://github.com/NREL/EnergyPlus/files/7539658/in96.idf.txt)

### Details
Some additional details for this issue (if relevant):
 - Ubuntu Linux
 - EnergyPlus v9.4.0 & v9.6.0
 - [Unmethours link](https://unmethours.com/question/64396/why-is-sitewatermainstemperature-correlation-from-weather-file-locked-on-one-temperature-for-all-times-and-locations/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here): https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9190/in96.idf
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by chriswmackey** [comment]
I have verified this same bug on my end and almost all of my simulations are failing because of unreasonably high water mains temperatures with the `CorrelationFromWeatherFile`.

I am just noting here that the suggested workaround is to use `Correlation` with either the real average outdoor temperature or a best guess (as explained in the unmethours post). I came very close to just forgoing the update to E+ 9.6 because of this and I would urge this fix to be prioritized for the next release.
