### ISSUE TITLE
Slab pre-processor not working on macOS

### ISSUE THREAD

**Issue by nheeren** [NREL/EnergyPlus#9197]
Issue overview
--------------
I am running energyplus on macOS 11.6.1 and usually this works fine. My typical workflow is that I copy the required binaries into a temporary folder along with a `in.idf` file. In the past I had issues when I forgot to copy one of the library files along, such as `libgcc_s.1.dylib`. Now, I wanted update from energyplus 9.2.0 to 9.6.0 and I am not able to resolve this issue. When I try to run the Slab pre-processor as a dry-run, even from within the installation path, I get this issue: 

```bash
$ /Applications/EnergyPlus-9-6-0/PreProcess/GrndTempCalc/Slab
dyld: Library not loaded: /usr/local/opt/gcc@9/lib/gcc/9/libgfortran.5.dylib
  Referenced from: /Applications/EnergyPlus-9-6-0/PreProcess/GrndTempCalc/Slab
  Reason: image not found
[1]    53934 abort      /Applications/EnergyPlus-9-6-0/PreProcess/GrndTempCalc/Slab
```

Naturally `libgfortran.5.dylib` is present in the same folder (which usually resolved similar issues in the past). The weird thing is that all other files, such as `/Applications/EnergyPlus-9-6-0/PreProcess/GrndTempCalc/Basement` or `/Applications/EnergyPlus-9-6-0/energyplus` run just fine.

Can anyone confirm that it is not just me? Are there workarounds for this specific issue?

### Details
Some additional details for this issue (if relevant):
 - macOS 11.6.1 
 - EnergyPlus 9.6.0 installed from `EnergyPlus-9.6.0-f420c06a69-Darwin-macOS10.15-x86_64.dmg`
 - GCC installed with homebrew in `/usr/local/Cellar/gcc/11.2.0_3`

**Comment by aaron-boranian** [comment]
Cross-posting where this issue was raised on [Unmet Hours](https://unmethours.com/question/65197/macos-slab-pre-processor-not-working/).

**Comment by mjwitte** [comment]
If the v9.2 Slab runs ok, a workaround might be to copy all of it's pieces into the v9.6 folder. Slab hasn't changed for years.

**Comment by nheeren** [comment]
> If the v9.2 Slab runs ok, a workaround might be to copy all of it's pieces into the v9.6 folder. Slab hasn't changed for years.

Thanks! Good to know. Then I may have to raise another issue, because my motivation to switch was actually an error message I received from Slab, as mentioned here https://github.com/nheeren/BuildME/issues/44: 
> Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

**Comment by mjwitte** [comment]
@nheeren That sounds familiar. See https://github.com/NREL/EnergyPlus/issues/8333.

**Comment by jmarrec** [comment]
Should be fixed by https://github.com/NREL/EnergyPlus/pull/9676, everything is statically linked into these fortran binaries now.
