### ISSUE TITLE
reset_state does not work

### ISSUE THREAD

**Issue by kamasyali** [NREL/EnergyPlus#9202]
Issue overview
--------------
I am using EnergyPlus Python API. When I try to reset the state using api.state_manager.reset_state(state), I receive OSError: exception: access violation reading 0x0000000000000010 error. 

### Details
Some additional details for this issue (if relevant):
Windows 10
EnergyPlus 9.6.0
Python 3.9.9 64-bit

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files added: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9202
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by bonnema** [comment]
@kamasyali, can you please provide a little more detail about what you're trying to accomplish? are you trying to reset an actuator?

**Comment by kamasyali** [comment]
As described [here](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/api-usage.html), I am trying to reset state of a simulation so that I can re-run another, in the same memory space.

**Comment by Myoldmopar** [comment]
For now, as a quick workaround, just create a new state instance rather than reusing the original state.  I'll try to take a look as to the problem.  Can you send your example file and weather file if relevant?

**Comment by kamasyali** [comment]
[example.zip](https://github.com/NREL/EnergyPlus/files/7652058/example.zip)
The problem occurs when I try to reset the state in Line 17.

**Comment by sortiz-hub** [comment]
Happy to see there is already a fix for the bug - currently stuck by it.
When do you think the fix will be included in E+?

Thanks!
