### ISSUE TITLE
EnergyPlus Crashes Without Error Log When Several Zones Are Connected by Construction:AirBoundary

### ISSUE THREAD

**Issue by chriswmackey** [NREL/EnergyPlus#9218]
Issue overview
--------------
I and several users of [Ladybug Tools](https://www.ladybug.tools/) have been making heavy use of the `Construction:AirBoundary` that was introduced to EnergyPlus a few versions ago, which has been a godsend and has allowed us to model many situations that we could not model previously. However, we have discovered that, in large models with big contiguous spaces connected by `Construction:AirBoundary`, EnergyPlus will crash during the "Initializing Simulation" phase. The .err file will be completely empty in this case and there's no record of what exactly when wrong. When the `Construction:AirBoundary` is replaced by just a normal opaque `Construction`, the simulation is successful.

### Details
We are using [the last official release of EnergyPlus 9.6](https://github.com/NREL/EnergyPlus/releases/tag/v9.6.0) and here you can find an IDF exported for EnergyPlus 9.6 that can recreate the crash:
https://drive.google.com/file/d/1NJWAkZzULieEp1RXAyY80dI3AflTX2xP/view?usp=sharing

I tried to create as minimal of a sample file as I could and I apologize that there are still 24 Zones and 216 Surfaces in the model. However, in our experience, we have only been able to recreate this error in cases when there are fairly large numbers of zones and `Construction:AirBoundary` surfaces in the model. To illustrate that the error is, in fact, the result of the `Construction:AirBoundary`, here is the exact same model using a normal opaque `Construction`, which can simulate successfully:
https://drive.google.com/file/d/1yNhpB_AhWyRE2i5KKjDEsM4D0FAwBpsK/view?usp=sharing

We have been able to reproduce the error on both Windows and Linux and across a wide range of system specifications. So this bug does not appear to be platform-specific.

In my opinion as an energy modeler, this type of use of `Construction:AirBoundary` is pretty excessive and I think most users of Ladybug Tools would find it acceptable if this excessive use of `Construction:AirBoundary` ultimately remains non-simulate-able. We can always join many of these Zones together into one and accept a higher degree of air mixing across the model. However, the fact that EnergyPlus crashes without any error log has been challenging for us since it forces us to question what exactly went wrong and whether the `Construction:AirBoundary` is, in fact to blame. So, at a minimum, we would really benefit from some error reporting that made it clear to us that the excessive use of `Construction:AirBoundary` is to blame.

### Checklist

 - [x] Defect file added (see above)
 - [ ] Ticket added to Pivotal for defect
 - [ ] Pull request created

**Comment by mjwitte** [comment]
@chriswmackey Can you tell what the intent of this file is after all of the airwalls are eliminated, how many enclosures should there be?

**Comment by chriswmackey** [comment]
Thanks for the response, @mjwitte . The file is a single continuous solar enclosure when all of the air walls are eliminated.  So all of the 24 Zones should be merged into one enclosure.

I realize it's an extreme case but, as I mentioned, I have only been able to find this bug in cases of large models and enclosures.

**Comment by mjwitte** [comment]
In theory this should work, so there may be something wrong with the enclosure merging logic.

**Comment by mjwitte** [comment]
@chriswmackey I've found the offending line of code and a couple of other potential problems related to spaces in the enclosure merging function. It appears that this issue was present in v9.5. Is it possible that you can generate a v9.5 idf from the same Ladybug model to confirm?

**Comment by chriswmackey** [comment]
Thanks, @mjwitte . Glad to hear it! What you describe fits my experience. I am confident that we encountered this issue in EnergyPlus 9.5 but we just weren't sure if it was actually an issue in EnergyPlus at the time or something that was wrong on our end.

Interestingly enough, I cannot recreate the crash using the exact same model in EnergyPlus 9.5. Here is the IDF file that you requested (the same as above but with E+ 9.5):
https://drive.google.com/file/d/1-QBGyD4ba5WTz9P4FhD32Z7IN1ZS55zG/view?usp=sharing

**HOWEVER**, if I add a few more Zones to this model, I am able to recreate the crash in 9.5. Here is a version of the file above with a few more Zones that crashes in EnergyPlus 9.5 in the same manner:
https://drive.google.com/file/d/1R-aqHW3yVr4X3icyaxcLAtEzEYG64siB/view?usp=sharing
The crashing model should still be a single solar enclosure. It just has 33 Zones instead of 24.
