### ISSUE TITLE
delete_state() causing crashes in Linux

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9222]
Issue overview
--------------
A recently reported issue is about reset_state() fail to run properly in v9.6 (#9202). Following the work-around suggestions in issue the discussion (https://github.com/NREL/EnergyPlus/issues/9202#issuecomment-985785648) and using the new_state() and delete_state() combination, a user recently reported that the delete_state() would cause crash in a Linux version/system. The problem did not show up in Windows systems. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Linux
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.6 only, EnergyPlus-9.6.0-f420c06a69-Linux-Ubuntu18.04-x86_64.sh
 - Related helpdesk tickets: 16098; 16069

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect files added (list location of defect files [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9222))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by zha** [comment]
Both delete or reset states would cause the crash for me. The workaround would not work for me as the memory would fill up really quickly without deleting the state.
