### ISSUE TITLE
Python Plugin DataExchange minutes rounding issue

### ISSUE THREAD

**Issue by apoerschke** [NREL/EnergyPlus#9225]
Issue overview
--------------
It appears that the conversion to integer minutes in the Python DataExchange class is broken, and not correctly rounding, but rather using float -> integer conversion.
I discovered this when developing a Python Plugin which logs data every minute to a separate log file. Some minutes were being duplicated, and some dropped.

Below is console output showing the problem. The timestamp shows (Year,Month,Day,Hour,Minute). Notice how minute 52 is duplicated and minute 54 is dropped. The floating point HRS correctly shows the 1 minute delta with each timestep. Minute is populated with a `api.exchange.minutes(state)` call and hours with a `api.exchange.current_time(state)` call.

```
Current Timestamp: (2020, 7, 14, 23, 52) HRS: 23.866666666666667
Current Timestamp: (2020, 7, 14, 23, 52) HRS: 23.883333333333333
Current Timestamp: (2020, 7, 14, 23, 53) HRS: 23.9
Current Timestamp: (2020, 7, 14, 23, 55) HRS: 23.916666666666668
Current Timestamp: (2020, 7, 14, 23, 56) HRS: 23.933333333333334
Current Timestamp: (2020, 7, 14, 23, 56) HRS: 23.95
Current Timestamp: (2020, 7, 14, 23, 57) HRS: 23.966666666666665
Current Timestamp: (2020, 7, 14, 23, 59) HRS: 23.983333333333334
Current Timestamp: (2020, 7, 14, 23, 60) HRS: 24.0
```

Converting floating point hours to minutes `0.883333333333333*60=52.99999999999998` which yields 52 when converted from float to int (should be mintue 53).

### Details
 -  Windows 10
 -  EnergyPlus 9.6

**Comment by bonnema** [comment]
Related to https://github.com/NREL/EnergyPlus/issues/9195?

**Comment by apoerschke** [comment]
> Related to #9195?


@bonnema Possibly related, but I suspect this is a simple rounding issue when the C++ code returns the integer minutes to the Python Plugin. I don't know if the same `minutes` variable exists within other aspects of E+, and if the rounding issue is present elsewhere.

It looks like the issue is line 756 of datatransfer.cc:
```
    Real64 fractionalHoursIntoTheDay = currentTimeVal - double(thisState->dataGlobal->HourOfDay - 1);
    Real64 fractionalMinutesIntoTheDay = fractionalHoursIntoTheDay * 60.0;
    return (int)(fractionalMinutesIntoTheDay);
```

**Comment by bonnema** [comment]
This is interesting. When you run the input files [here](https://github.com/NREL/EnergyPlus/files/7824382/in.zip), you get this [eplusout.csv](https://github.com/NREL/EnergyPlus/files/7824387/eplusout.csv), which (to me) shows no discernible pattern in the minute after the first hour.

**Comment by apoerschke** [comment]
Your example shows the same behavior I was seeing. Again, it appears to be an issue with how floating point minutes is converted to an integer.

**Comment by bonnema** [comment]
For sure. I was just adding a dead simple example file duplicating the issue. This definitely appears to be a problem.

**Comment by mitchute** [comment]
Thanks for the simple example files, @bonnema. We just need to wrap the calculation in [this line](https://github.com/NREL/EnergyPlus/blob/3d028d8976d1b7104662d53a55fb6d6c4ec9d6c4/src/EnergyPlus/api/datatransfer.cc#L745) with `std::round`. 

After that, the new [eplusout.csv](https://github.com/NREL/EnergyPlus/files/7864921/eplusout.csv) looks right. I'll push a fix shortly.
