### ISSUE TITLE
PythonPlugin:Variables multiple objects issue

### ISSUE THREAD

**Issue by nirajkunwar** [NREL/EnergyPlus#9227]
Issue overview
--------------
The EnergyPlus takes only one PythonPlugin:Variables object and gives error if there are more than one object. This means maximum of 10 variables can be defined (as shown in image attached) and used for getting output.
The EnergyPlus file with only one  PythonPlugin:Variables works completely fine.
[Eplus_error.zip](https://github.com/NREL/EnergyPlus/files/7822610/Eplus_error.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows)
 - Version of EnergyPlus (9.6)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 [ ] EnergyPlus error file added

**Comment by bonnema** [comment]
I think with newer versions (9.4+) >10 variables are allowed. I have this running in 9.5:
```
PythonPlugin:Variables,
  Python Variables,                       !- Name
  mt1_t_supp_f,                           !- Variable Name 1
  mt1_t_case_f,                           !- Variable Name 2
  mt1_t_prod_f,                           !- Variable Name 3
  mt1_cc_sen,                             !- Variable Name 4
  mt1_cc_lat,                             !- Variable Name 5
  mt2_t_supp_f,                           !- Variable Name 6
  mt2_t_case_f,                           !- Variable Name 7
  mt2_t_prod_f,                           !- Variable Name 8
  mt2_cc_sen,                             !- Variable Name 9
  lt1_t_supp_f,                           !- Variable Name 10
  lt1_t_case_f,                           !- Variable Name 11
  lt1_t_prod_f,                           !- Variable Name 12
  lt1_cc_sen,                             !- Variable Name 13
  lt2_t_supp_f,                           !- Variable Name 14
  lt2_t_case_f,                           !- Variable Name 15
  lt2_t_prod_f,                           !- Variable Name 16
  lt2_cc_sen;                             !- Variable Name 17
```

**Comment by mitchute** [comment]
Correct, only one object is allowed but it is extensible so just add all of your variables to that object.

@Myoldmopar Is there a reason to limit E+ to only have one instance of the `Variables` object? It looks like the code is already configured to handle it.

https://github.com/NREL/EnergyPlus/blob/6b569b81cfb978be795d3051f683ce7d3a799ca6/src/EnergyPlus/PluginManager.cc#L574-L591

The `Name` field isn't referenced anywhere as far as I can tell, so I think all we would have to do is remove the `\unique-object` from the IDD.

**Comment by bonnema** [comment]
\>1 object is interesting. It could allow the user to group them and ID by the name field that really isn't used. It could also be helpful for programmatic workflows (a new object can just be created instead of trying to append to an existing object).
