### ISSUE TITLE
`HAMT origins` in .eio file seem incorrect

### ISSUE THREAD

**Issue by germolinal** [NREL/EnergyPlus#9238]
I am using HAMT and the cells described in the EIO file span from 0.0 to the whole thickness of the construction
--------------

I am working with HAMT and I am trying to use the data in the EIO file. However, my construction is `0.1055m` thick, and the cell origins span from edge to edge, as you can see here:

```
HAMT cells, SOUTH,INTERNAL_IN,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20
HAMT origins,SOUTH,INTERNAL_IN, 0.0000000, 0.0003750, 0.0015000, 0.0026250, 0.0041012, 0.0083983, 0.0165719, 0.0278219, 0.0410471, 0.0549529, 0.0681781, 0.0794281, 0.0876017, 0.0918988, 0.0935968, 0.0957561, 0.0992500, 0.1027439, 0.1049032, 0.1055000
```

I thought the last value was just an added value to represent the end of the final cell, but the output CSV file reports from `SOUTH:HAMT Surface Relative Humidity Cell 0 [%](Hourly)` to `SOUTH:HAMT Surface Relative Humidity Cell 20 [%](Hourly)`, meaning that I was wrong.

So, my question is: is this a bug? am I misinterpreting the data in the EIO?

**Comment by mjwitte** [comment]
The Input Output Reference description gives a subtle clue:

> HAMT automatically assigns cells to construction objects so that there are more cells closer to boundaries between materials and also at the “surfaces” of the surface.

Looking in the source code, there is a virtual cell at the inside and outside face of the surface. Also, it appears that the "origins" listed in the eio ouput are the center of each cell, not an edge. So Cell 1 is the virtual cell at 0.0 and Cell N is the virtual cell at the inside face of the surface. Using the HAMT example file, the outputs for Cell 1 match the equivalent "HAMT Surface Outside Face" values, and Cell N matches the "HAMT Surface Inside Face" values. I cannot reproduce any outputs for Cell 0.

**Comment by germolinal** [comment]
I have been trying to reverse-engineer the positions of these cells. After a while, I think that:

* I am quite sure that the "origins" are actually the "center".
* The EIO includes data for both the Interior and Exterior virtual cells.

I have arrived to that second conclusion by calculating the positions and thicknesses of the cells. 

Let's take the following example code:

```python

# This is a subdivision of a construction with four layers:
# The first one has a thickness of 0.1m; the second one, 0.003m; third one, 0.09; fourth one, 0.0125 .

centers = [0.0000000, 0.0012236, 0.0059982, 0.0150799, 0.0275799, 0.0422746, 0.0577254, 0.0724201, 0.0849201, 0.0940018, 0.0987764, 0.1003750, 0.1015000, 0.1026250, 0.1041012, 0.1083983, 0.1165719, 0.1278219, 0.1410471, 0.1549529, 0.1681781, 0.1794281, 0.1876017, 0.1918988, 0.1935968, 0.1957561, 0.1992500, 0.2027439, 0.2049032, 0.2055000]

delta = [0.0] * len(centers )
for i in range(1,len(delta)):
    delta[i] = centers[i]-centers[i-1]

thickness = [0.0]*len(centers)
thickness[1] = delta[1] * 2
for i in range(1,len(thickness)):
    thickness[i] = 2.*delta[i] - thickness[i-1]

thickness[-1] = 0.0 # Correct final rounding error

# The resulting thickness vector has thickness 0 at the first and last elements. The rest are: the first 10 cells of this vector add 0.1m (1st layer); the following three add up to 0.003m (2nd layer); the following 10 add 0.09m (3rd layer); next 5 add up to 0.0125m (4th layer). 

```
# Rationale of this calculation:

Let's say that the `origin` is actually the `center` of each cell; then the `center` of the first cell is `0.0` and its full thickness is `thick_0 = from_eio[1] - from_eio[0]`. Then, the distance between `center_1` and `center_0` must be `from_eio[2] - from_eio[1] = thick_0/2. + thick_1/2.` Meaning that `thick[i] = 2*(from_eio[i+1] - from_eio[i+1]) - thick[i-1]`.

# Proposed changes

* Emphasise in the documentation that these are centres and that the data in the output includes the first and last "surface" or "virtual" cells...? 
* Change the keyword "origin" by "center" in the EIO file.
