### ISSUE TITLE
Leap day included w/ March when reporting frequency is monthly

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#9241]
Issue overview
--------------
See attached IDF and results. When the simulation uses a leap year and you request an `Output:Variable` with frequency of "monthly", the February results are still through 2/28 and the leap day ends up in the March results:

![image](https://user-images.githubusercontent.com/5861765/150006625-d6be079d-03ac-480c-b8b1-0e35f5922036.png)

I've confirmed that a leap day is being simulated by switching to a frequency of "hourly":

![image](https://user-images.githubusercontent.com/5861765/150006701-855bfa43-be71-4db2-882f-37f1d65e4aae.png)

Files to reproduce:
[test.zip](https://github.com/NREL/EnergyPlus/files/7891904/test.zip)

### Details
Some additional details for this issue (if relevant):
 - EnergyPlus v9.6

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
The 2nd figure above, on line 1417, shows Month = 2 and Day = 29. I would think this means data is grouped into Feb in monthly table reporting. So what indication is there that this data is included in Mar?

**Comment by rraustad** [comment]
Never mind, the first figure shows Feb has 28 days.

**Comment by JasonGlazer** [comment]
Updated the test file to 23.1 and was able to reproduce that the same issue is showing.
[in23-1-0.idf.txt](https://github.com/NREL/EnergyPlus/files/12421450/in23-1-0.idf.txt)

**Comment by JasonGlazer** [comment]
Looks like the problem is here: https://github.com/NREL/EnergyPlus/blob/a87b71bfab996f95ed51e662780a8389550c5ded/src/EnergyPlus/SQLiteProcedures.cc#L1618

**Comment by JasonGlazer** [comment]
@shorowit do you know if the accumulation of values was really broken on this or was just labeled incorrectly?

**Comment by shorowit** [comment]
@JasonGlazer I just ran a test simulation and the accumulation of values is wrong too -- Feb 29 is included in March. (Our software switched from reading SQLite to reading MsgPack, but I assume it's the same.)

**Comment by JasonGlazer** [comment]
Thanks @shorowit yes, I see this is a problem in two places. The accumulation of monthly results even when producing the ESO and CSV files is wrong too for February's with leap years. The CSV file below shows the second column which is the monthly total and it gets totaled at the end of Feb 28 instead of Feb 29:

![image](https://github.com/NREL/EnergyPlus/assets/2582150/5f1c9bf3-0150-4e7a-bf7d-670c37ccd6dd)
