### ISSUE TITLE
Kiva problem with clockwise geometry - part 2

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#9243]
Issue overview
--------------
#9104 fixed part of #9103, but there may be more to fix (from #9103):

> The above line is the obvious one that needs to be fixed (actually tried to fix in PR #9104). However, it seems that change alone would not fully fix the problem--the defect file would not go through and still encounters problems in other part of the foundation calculations. There could be more deeper changes needed for the Kiva foundation part that would be needed to make the defect file finally work (@nealkruis). Another test was conducted by changing the geometry rule to CounterClockWise and reverting all the surface vertex input orders from the orignal defect file---that actually yield a case that could run through without any problems.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added  - see #9103 
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@jcyuan2020 Did this originate from a helpdesk ticket?

**Comment by jcyuan2020** [comment]
@mjwitte No. It is from another source (Australia) and we have the defect files, which were already placed under the original issue post.
