### ISSUE TITLE
ZoneCoolTower:Shower, availability schedule does not default as stated in docs 

### ISSUE THREAD

**Issue by TfedUD** [NREL/EnergyPlus#9247]
Issue overview
--------------
It appears that leaving the availability schedge blank; does not default to always available as stated in documentation:
[Applicable EnergyPlus 9.6 I/O reference](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-airflow.html#:~:text=use%20this%20name.-,Field%3A%20Availability%20Schedule%20Name,the%20schedule%20has%20values%20of%201%20for%20all%20time%20periods.,-Field%3A%20Zone%20Name)

## Field: Availability Schedule Name
This field is the name of the schedule that denotes whether the cooltower can run during a given time period. A schedule value greater than 0 (usually 1 is used) indicates that the cooltower is available and can be on during the time period. A value less than or equal to 0 (usually 0 is used) denotes that the cooltower is not available and must be off for the time period. ***If this field is blank, the schedule has values of 1 for all time periods.***

--------------
Errors given are asking for an availability schedule, using E+ 9.6 via OS 3.3.0 and LadybugTools.

**Comment by mjwitte** [comment]
@TfedUD I'm unable to reproduce this. Please attach an idf. Thanks.

**Comment by TfedUD** [comment]
@mjwitte yeah.. its working fine for me now; just went back to the file to get an idf to upload: ran it; it works...
Soo definitely was PICNE
(Problem in chair not equipment)
appreciate your time!
