### ISSUE TITLE
Missing idd defaults for CoolingTower:*Speed

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/EnergyPlus#9262]
Issue overview
--------------
```
  A6 , \field Evaporation Loss Mode
       \type choice
       \key LossFactor
       \key SaturatedExit
```

```
  A7 , \field Blowdown Calculation Mode
       \type choice
       \key ConcentrationRatio
       \key ScheduledRate
```

Missing `\default SaturatedExit` and `\default ConcentrationRatio`, respectively, for:
* `CoolingTowerSingleSpeed`
* `CoolingTowerTwoSpeed`
* `CoolingTowerVariableSpeed`
* `CoolingTower:VariableSpeed:Merkel`

Also:
* `Performance Input Method` for `EvaporativeFluidCooler:SingleSpeed` (required-field)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
The I/O ref mentions the default, but it would be a lot clearer for users if it was in the IDD.

https://github.com/NREL/EnergyPlus/blob/923772d985c14e803c7ae0e5348a2d595fe5739d/doc/input-output-reference/src/overview/group-condenser-equipment.tex#L2208-L2210

> There are two options: LossFactor or SaturatedExit. The default is SaturatedExit.


The Actual default is done in the source code: https://github.com/NREL/EnergyPlus/blob/923772d985c14e803c7ae0e5348a2d595fe5739d/src/EnergyPlus/CondenserLoopTowers.cc#L420-L431
