### ISSUE TITLE
Message : EnergyPlus Completed Successfully.

### ISSUE THREAD

**Issue by xavfa** [NREL/EnergyPlus#9266]
Dear all,
During a simulation, EnergyPlus gives a lot on useful messages if one wants to follow closely the simulation.
But when launching a bunch of simulations for different purposes (urban scale, optimization or calibration, ...) or even using parallel computing, these are no longer useful (and pretty annoying).
I have manage to get rid of almost all of them using the following option in the check_call function : `check_call(cmd, stdout=open(os.devnull, "w"))`.  With _cmd_ being the command line with energyplus exectubale, the weatherfile, up to the .idf file.

The issue is that I still get the very last message : _EnergyPlus Completed Successfully_ for all launched simulation.

Is there a way to avoid having this message at the end of a simulation ?
How comes EnergyPlus knows were to print this message ? We are launching several prgm in check_call (so as external processes) up to the very final EnergyPlus run, but this last message is able to get back to the very first terminal !

I understand the request could sound weird but I am using other way around to check the simulation status.

Thanks in advance for some tips to resolve this (tiny) issue.

**Comment by mitchute** [comment]
That line is getting reported on the error stream, so you also need to send the error stream to dev/null (`stderr=open(os.devnull, "w")`). 

https://github.com/NREL/EnergyPlus/blob/fadc5973b85c70e8cc923efb69c144e808a26078/src/EnergyPlus/UtilityRoutines.cc#L913

🤷

**Comment by Myoldmopar** [comment]
Also if you want to call EnergyPlus via API, you can use the runtime API function: `set_console_output_status` to mute everything.

**Comment by xavfa** [comment]
Great, Many thanks to both of you !
