### ISSUE TITLE
PUBLIC linkage of energypluslib propagates lib dependency to all clients of energyplusapi

### ISSUE THREAD

**Issue by tanaya-mankad** [NREL/EnergyPlus#9287]
Issue overview
--------------
EnergyPlus (exe) links to both energypluslib (statically) and energyplusapi (dynamically) for duplicated and sometimes conflicting access to the same objects. (This occurs because the default linkage of energypluslib into energyplusapi is currently  PUBLIC.)

### Details
 - Discovered during defect resolution for Issue 9091; exists in branch develop (7627a7d1).
 - 
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
I wonder how this change will impact the unit test suite binary.  Just something to be aware of as this is addressed.  :+1:

**Comment by tanaya-mankad** [comment]
@Myoldmopar, it looks as though you added code to main() about a year ago, that was always intended to be removed: https://github.com/NREL/EnergyPlus/blob/5231fcf39b5e3cef09904fc8bbe8334b22290343/src/EnergyPlus/main.cc#L59.
Part of the solution to this issue will indeed remove it, if that's fine.

**Comment by Myoldmopar** [comment]
Yep, sounds great to me.
