### ISSUE TITLE
Code Error in DXCoils.cc

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#9301]
Issue overview
--------------

In the source code DXCoils.cc, in module named "CalcTwoSpeedDXCoilStandardRating", there is one line of code as follow (Line [15282](https://github.com/NREL/EnergyPlus/blob/747398a414f97f8867b8b79c8a567e4a028df695/src/EnergyPlus/DXCoils.cc#L15282))

```c++
TotCapFlowModFac = CurveValue(state, state.dataDXCoils->DXCoil(DXCoilNum).CCapFTemp2, AirMassFlowRatio);
```

Looks like this line of code is to calculate the Capacity Ratio as a function of Flow Fraction, but it's referencing the Capacity Ratio as Function of Temperature curve.  This caused an error "Target and Gridded Data do not have the same dimensions" when I was running a simulation using lookup tables for the cooling coil performance. I think it is because the CAPFT requires two independent variables, whereas in this function call only one independent variable is provided.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9301))
 - [x] Ticket added to Pivotal for defect (development team task)
 - [x] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
https://github.com/NREL/EnergyPlus/blob/747398a414f97f8867b8b79c8a567e4a028df695/src/EnergyPlus/DXCoils.cc#L15282

**Comment by jmarrec** [comment]
Probably supposed to be this:

```diff
-TotCapFlowModFac = CurveValue(state, state.dataDXCoils->DXCoil(DXCoilNum).CCapFTemp2, AirMassFlowRatio);
+TotCapFlowModFac = CurveValue(state, state.dataDXCoils->DXCoil(DXCoilNum).CCapFFlow(1), AirMassFlowRatio);
```

**Comment by rraustad** [comment]
That looks correct given that for the Coil:Cooling:DX:TwoSpeed model there is only 1 input for Total Cooling Capacity Function of Flow Fraction Curve Name.

**Comment by ykabusalah** [comment]
Could I have a shot at fixing this?
