### ISSUE TITLE
Zone entered Floor Area not used in calculations

### ISSUE THREAD

**Issue by eringold** [NREL/EnergyPlus#9302]
Issue overview
--------------
In v9.5, a 'Floor Area' entered in the Zone object is used to calculate zone internal loads entered as W/area. In v9.6, the load will be applied to the calculated floor area instead. 

### Details
In v9.5, this object: 
```
Zone,
  TZ_8_Elec/Data,                         !- Name
  90,                                     !- Direction of Relative North {deg}
  8.57041,                                !- X Origin {m}
  27.35629,                               !- Y Origin {m}
  0,                                      !- Z Origin {m}
  ,                                       !- Type
  1,                                      !- Multiplier
  ,                                       !- Ceiling Height {m}
  ,                                       !- Volume {m3}
  15.05029248,                            !- Floor Area {m2}
  ,                                       !- Zone Inside Convection Algorithm
  ,                                       !- Zone Outside Convection Algorithm
  Yes;                                    !- Part of Total Floor Area
```
with this load: 
```
ElectricEquipment,
  L1_BOH_ElectricData Electric Equipment, !- Name
  TZ_8_Elec/Data,                         !- Zone or ZoneList Name
  EQUIP SCH,                             !- Schedule Name
  Watts/Area,                             !- Design Level Calculation Method
  ,                                       !- Design Level {W}
  495.339011511356,                       !- Watts per Zone Floor Area {W/m2}
  ,                                       !- Watts per Person {W/person}
  0,                                      !- Fraction Latent
  0.1,                                    !- Fraction Radiant
  0,                                      !- Fraction Lost
  Electric/Data Electric Equipment;       !- End-Use Subcategory
```
Will use the entered zone area for calculating Plug and Process load and energy: 
![image](https://user-images.githubusercontent.com/10799524/156075908-19bfb43f-e000-4104-80e7-1ce741a476e0.png)
![image](https://user-images.githubusercontent.com/10799524/156076113-17605fc7-2953-49e7-8e14-05d592aea9b5.png)

Updating the same input file to 9.6.0, the Zone object and ElectricEquipment object remain the same, but now the load is multiplied by the calculated floor area (although Zone Summary table reports the entered area):

![image](https://user-images.githubusercontent.com/10799524/156076242-f098ad4a-0f10-4ba1-a33b-47dbbfc37034.png)
![image](https://user-images.githubusercontent.com/10799524/156076439-3059a262-b45b-4a2a-9ceb-05e21dfcd746.png)

Note: in both 9.5.0 and 9.6.0, DisplayExtraWarnings does note that the calculated floor area differs from entered, but "entered Floor Area will be used in calculations", which does not appear to be the case in 9.6.

@mjwitte probably related to Spaces? I can email input files directly. 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@eringold Probably is related to spaces, please send the files. Does this file have explicit Space object(s) in the idf for this zone? If so, it's likely the Space Floor Area is being used. Either way, the code needs to do some checking/warning if there are conflicting inputs for Space and Zone, and I don't think that's in there.

**Comment by eringold** [comment]
No spaces in these inputs, just the classic Zones. Files sent via email.

**Comment by mjwitte** [comment]
@eringold The v9.6 workaround for the zone floor area is to add Space objects for each Zone with the desired floor areas. e.g.:
```
Space,
    TZ_1_MainRetail,         !- Name
    TZ_1_MainRetail,         !- Zone Name
    282.05362944;            !- Floor Area {m2}
```
You can name the Spaces the same as the corresponding zones or not, works either way since these are all one-to-one. The areas in the Input Verification and Results Summary subtables for Zone Summary and Space Summary should match after the Space objects are added, and you should get the desired internal gain levels.

**Comment by eringold** [comment]
Thanks, good to know. I'm using OpenStudio with this model, which I don't think yet has the capability to set the floor area of a space (and have it translated to IDF correctly). 

Instead of trying to rock that boat, my workaround was just to adjust the load input to be based on the calculated area.

**Comment by shorowit** [comment]
> Thanks, good to know. I'm using OpenStudio with this model, which I don't think yet has the capability to set the floor area of a space (and have it translated to IDF correctly).

You actually can with OpenStudio 3.3.0. From its [release notes](https://github.com/NREL/OpenStudio/releases/tag/v3.3.0):

![image](https://user-images.githubusercontent.com/5861765/156623959-feb4d317-2eed-4a00-985a-f29d4f69e20e.png)

**Comment by eringold** [comment]
@shorowit right, but OS:Space doesn't have a Floor Area field?

**Comment by shorowit** [comment]
@eringold Hmm. Sorry, I'm probably just not following the issue close enough so maybe I'm not making sense. But note that OS:ThermalZone doesn't have a Floor Area field either, it's [calculated from the OS:Spaces](https://openstudio-sdk-documentation.s3.amazonaws.com/cpp/OpenStudio-3.3.0-doc/model/html/classopenstudio_1_1model_1_1_thermal_zone.html#a5dd366b6d8425e6115b884e1a093a50a). So you can either get individual Space floor areas in the IDF by using the experimental OS feature, or get their sum in the ThermalZone floor area.

**Comment by eringold** [comment]
OS:ThermalZone does have a Floor Area field (N4 in the OpenStudio.idd entry), there's just no setter for it specifically. I get around that with `zone.setString(5, area)`. 

OS:Space has no such field, so I couldnt set the value there, even if I did use the new FT option.

**Comment by shorowit** [comment]
Ah, got it. I understand now. I'm sure you already know this, but you could [request that OS enhancement](https://github.com/NREL/OpenStudio/issues). 😉
