### ISSUE TITLE
Duplicated "Detailed" timestep choice item in IDD file for Output:Meter

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9305]
Issue overview
--------------
There is a duplicated "Detailed" timestep choice item for Output:Meter field A2 "Reporting Frequency": 

```
Output:Meter,
       \memo Each Output:Meter command picks meters to be put onto the standard output file (.eso)
       \memo and meter file (.mtr). Not all meters are reported in every simulation. A list of meters
       \memo that can be reported are available after a run on the meter dictionary file (.mdd) if
       \memo the Output:VariableDictionary has been requested.
       \format singleLine
  A1 , \field Key Name
       \required-field
       \type external-list
       \external-list autoRDDmeter
       \note Form is EnergyUseType:..., e.g. Electricity:* for all Electricity meters
       \note or EndUse:..., e.g. GeneralLights:* for all General Lights
       \note Output:Meter puts results on both the eplusout.mtr and eplusout.eso files
  A2 ; \field Reporting Frequency
       \type choice
       \key Detailed
       \key Timestep
       \note Timestep refers to the zone Timestep/Number of Timesteps in hour value
       \note RunPeriod and Environment are the same
       \key Hourly
       \key Daily
       \key Detailed
       \key Monthly
       \key RunPeriod
       \key Environment
       \key Annual
       \default Hourly
```

As a result, in IDFEditor, two choice items of the same name will be shown under the droplist menu for the "Reporting Frequency" field of Output:Meter:
![image](https://user-images.githubusercontent.com/64040111/156213347-7b889b3d-5711-4772-b594-9a5267900db2.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.6
 - Notice while investigating helpdesk tickets 16136 & 16137

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Good catch, that is _quite_ silly.  It's obviously not causing (m)any issues, thankfully.
