### ISSUE TITLE
New compiler warnings on Ubuntu 21.10: unused variable

### ISSUE THREAD

**Issue by jmythms** [NREL/EnergyPlus#9326]
Issue overview
--------------

This unused variable warning started popping up after upgrading to Ubuntu 21.10, and GCC 11.2. 
Warning on [line 529 in FluidProperties.hh](https://github.com/NREL/EnergyPlus/blob/1ca392b3a183d24d4a2823e056dbb8b341b4087b/src/EnergyPlus/FluidProperties.hh#L529) (`std::uint64_t const T_tag(*reinterpret_cast<std::uint64_t const *>(&t) >> Grid_Shift);`) : 
`/EnergyPlus/src/EnergyPlus/FluidProperties.hh:529:35: warning: 't' is used uninitialized [-Wuninitialized]`. 

The compiler flags have to be set correctly to recreate the error, as seen [here](https://godbolt.org/z/EKrebd6T3). The warning goes away when the optimization flag is changed to -O1 or it is removed. 

Couldn't figure out how to fix it. Tagging @amirroth, @mbadams5, @lefticus for ideas. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) : Ubuntu 21.10
 - Version of EnergyPlus (if using an intermediate build, include SHA) :  Current Develop branch: 1ca392b3
 - Compiler: GCC 11.2
 - Compiler flags: -std=-std=c++20 -O3 -Wall -pedantic -Wconversion -Wno-strict-aliasing

**Comment by amirroth** [comment]
Well, `t` is initialized literally one line of code above that, so ... 🤷

**Comment by jmythms** [comment]
Yeah, I saw that, but I just wanted to make sure whether the warning was safe to ignore 👍🏽 Thank you

**Comment by mitchute** [comment]
> Well, `t` is initialized literally one line of code above that, so ... 🤷

It is Friday, and maybe I'm just having a :brain: moment... but what? How is `t` uninitialized?

**Comment by mitchute** [comment]
I see that I misread your statement. LIke I said, Friday... I'm going to bed now.

**Comment by jmarrec** [comment]
Here's a Compiler Explorer to show how it's possible to shush off the compiler warning: https://godbolt.org/z/q76hYYb1n

Bottom line:

```diff
-std::uint64_t const T_tag(*(reinterpret_cast<std::uint64_t const *>(&t)) >>  Grid_Shift);
+std::uint64_t const *temp = reinterpret_cast<std::uint64_t const *>(&t);
+std::uint64_t const T_tag = *temp >> Grid_Shift;
```

Otherwise pragma warning push, disable, pop...
