### ISSUE TITLE
IDFVersionUpdater copies installation folder files to the working directory

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9329]
Issue overview
--------------
For 22.1 IOFreeze version, when upgrading files, the ReportVariablesxxx.csv and Vxxx-Energy+.idd files (of related versions) got copied to the working folder, as shown in the following screenshot: 
![image](https://user-images.githubusercontent.com/64040111/158275215-0651bb52-c9fd-4afe-a836-65b53d22245c.png)

These files will be removed after the transition is done. 

This does not happen in updater for v9.6 or previous versions. So not sure if it is intended new behaviors in v22.1.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows (not tested on other platforms)
 - Version of EnergyPlus (if using an intermediate build, include SHA): v22.1 IOFreeze
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
@jcyuan2020 the IOFreeze version of the IDFVersionUpdater still had some problems. Would you mind retesting with the version associated with this #9306 ?  The files are at:

https://github.com/NREL/EnergyPlus/tree/fix_idfversionupdater_part2/bin/IDFVersionUpdater/Run-Win

BTW, a bunch of files should be copied during transition but then should be removed after that is complete.

**Comment by jcyuan2020** [comment]
@JasonGlazer Thanks! I tested binaries you provided and they are doing the same thing---copying a bunch of files (Report variables xxx.csv and related idds) and then removing them after. But according to your description above that seems to be the expected behavior for the 22.1 version (not in v9.6 and before). So may not be a problem.

**Comment by JasonGlazer** [comment]
That is the expected behavior so I'm closing this issue.
