### ISSUE TITLE
Window Assembly NFRC for report (Tarcog) related crash in v22.1 IOFreeze

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9330]
Issue overview
--------------
An idf case file will cause a simulation crash in v22.1 IOFreeze but not in v9.6 or earlier versions. The call is here inside GetWindowAssemblyNfrcForReport(): 
https://github.com/NREL/EnergyPlus/blob/1ca392b3a183d24d4a2823e056dbb8b341b4087b/src/EnergyPlus/WindowManagerExteriorThermal.cc#L305
And then traced down to: 
https://github.com/NREL/EnergyPlus/blob/1ca392b3a183d24d4a2823e056dbb8b341b4087b/src/EnergyPlus/WindowManagerExteriorThermal.cc#L478

And a few more steps further traced down to third_party/Windows-CalcEngine/src/Tarcog/src/Surface.cpp:
![image](https://user-images.githubusercontent.com/64040111/158391876-3f22f45d-e55d-4696-ab03-2c1ecbb1db7b.png)

### Details
Some additional details for this issue (if relevant):
 - Windows (other platforms not tested)
 - Version: v22.1 IOFreeze
 - Spotted while looking into Helpdesk ticket 16145

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9330))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by vidanovic** [comment]
@jcyuan2020 Do you have an IDF file that causes this crash?

**Comment by jcyuan2020** [comment]
@vidanovic They are at the defect file link: https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9330

**Comment by vidanovic** [comment]
@mjwitte @JasonGlazer One stupid question. Do we have a way to run all continuous integration test locally before committing anything to the GitHub? I remember some python script in the past that was doing that.

**Comment by mjwitte** [comment]
https://github.com/NREL/EnergyPlusRegressionTool

**Comment by vidanovic** [comment]
@mjwitte Perfect. Thanks!!!!
