### ISSUE TITLE
Add field to use cubic spline interpolation for PsyTsatFnPb to PerformancePrecisionTradeoffs

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#9333]
Issue overview
--------------
Currently Mode06 is the only way to trigger the use cubic spline interpolations in replacement of the psychrometric
function PsyTsatFnPb in PerformancePrecisionTradeoffs. All the other Modes in PerformancePrecisionTradeoffs also have a way to trigger that function independently. A new field should be added to PerformancePrecisionTradeoffs to do this.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
Same issue as https://github.com/NREL/EnergyPlus/issues/9107

**Comment by JasonGlazer** [comment]
Somehow I missed that the issue already existed. Closing this one.
