### ISSUE TITLE
DOAS system fan mass flow output does not match fan outlet system node mass flow rate output

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9339]
Issue overview
--------------
A user recently reported that in a Dedicated Outdoor Air system case, the fan mass flow rate report does not match the system node mass flow report for the fan outlet node: the fan outputs reported a positive mass flow rate and also positive fan power; but the fan's outlet system node reported zero flow rate. 

This can be demonstrated by the slightly revised from the SmallOffice_CentralDOAS.idf example (with only output variables modifications): 
![image](https://user-images.githubusercontent.com/64040111/159565298-d13b1aa0-6229-4f82-9859-e92207f672a6.png)
The fan output reports 0.3235 mass flow rate (it also reports a postive 235.81W fan energy); but the fan outlet system node reports 0 mass flow rate. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.4 to v22.1 iofreeze, or newer e.g. bfab14b526
 - Helpdesk ticket number: 16149

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file: see example file  SmallOffice_CentralDOAS.idf)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
This issues is addressed in PR #9408.
