### ISSUE TITLE
Update PVWatts Ground Coverage Ratio IDD max value

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#9348]
Issue overview
--------------
The IDD allows a maximum value of 1.0 for the `Generator:PVWatts` Ground Coverage Ratio input, but if you enter 1.0, you get errors like so:
```
Log Error: fail(gcr, max=0.99): 1 time -1
```
This suggests that the IDD should be changed to a max value of 0.99. (I haven't verified this.) It might be worth checking whether a minimum value of zero is allowed too.

Reported on [Unmet Hours](https://unmethours.com/question/71396/why-does-pvwatts-fail-in-openstudioapplication-121/).

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - EnergyPlus Version 9.5
 - [Unmethours link or helpdesk ticket number](https://unmethours.com/question/71396/why-does-pvwatts-fail-in-openstudioapplication-121/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by eringold** [comment]
Note that the PVWatts v5 [manual ](https://pvwatts.nrel.gov/downloads/pvwattsv5.pdf)indicates a GCR value of 1 is OK (or at least doesn't specify it's _not_): 

![image](https://user-images.githubusercontent.com/10799524/160446186-b53412f9-d691-4ad1-92e8-3493faac7d94.png)

**Comment by RKStrand** [comment]
It would be helpful to have an input file here.  I just ran this with the test suite file Generator_PVWatts.idf that I modified to try all the different system types with a GCR of 1 and everything ran.  The error message does not look like a typical E+ error message so I'm wondering where it is coming from.

**Comment by shorowit** [comment]
I just noticed that the Unmet Hours user was using E+ 9.5. I verified that I could reproduce the error by adding objects to one of the sample files:
[1ZoneUncontrolled_GCR1.idf.txt](https://github.com/NREL/EnergyPlus/files/9551939/1ZoneUncontrolled_GCR1.idf.txt)
I then changed the same sample file for E+ 22.1:
[1ZoneUncontrolled_GCR1.idf.txt](https://github.com/NREL/EnergyPlus/files/9551942/1ZoneUncontrolled_GCR1.idf.txt)
It ran successfully this time.

So it looks like the bug no longer exists in the latest version. My best guess is that it no longer occurs because of [this](https://github.com/NREL/EnergyPlus/pull/8960/files/d7fb6a5af0aefda07f84c50c6df0d58d1463b574#diff-5ab59b1dc98c9be9fe8d2675ca95c5cf19bab942065477b72887933f5fd62b39), which disabled some checks inside the pvwatts code.
