### ISSUE TITLE
Multi-stage electric backup coil modeling

### ISSUE THREAD

**Issue by yzhou601** [NREL/EnergyPlus#9357]
Issue overview
--------------
It is not uncommon that the multispeed heat pumps might come with a multi-stage back up coil. But there's no explicit capability in current E+ to allow modeling a multistage electric coil.  There're mainly two restrictions:
1. The `Coil:Heating:Electric:MultiStage` looks like a good fit to model a multi-stage electric coil, but it is not an option of [`Supplemental Heating Coil Object Type` for AirLoopHVAC:UnitarySystem parent object](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-unitary-equipment.html#field-supplemental-heating-coil-object-type). It is documented as "For the time being, this coil model can only be called by the parent object [AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed.](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-unitary-equipment.html#airloophvacunitaryheatpumpairtoairmultispeed)" There're a few objects that are only able to be called by specific parent objects, but considering AirLoopHVAC:UnitarySystem is supposed to serve as an universal object that covers most functionalities, should we consider allowing Coil:Heating:Electric:MultiStage to be with AirLoopHVAC:UnitarySystem as well?
2. And there's no explicit method to control the backup coil staging. To model realistic hvac cycling, the heat pump coil is operating with an [on-off thermostat](https://github.com/NREL/EnergyPlus/pull/6385), and in this context, the current modeling flexibility is not sufficient to implement the staging of backup coil. A stage actuator or a schedule input is needed to allow EMS program for specific backup coil staging. Similar to the purpose of https://github.com/NREL/EnergyPlus/pull/8865.  

This capability is important for our GEB hvac modeling and analysis, so we want to get some feedback from E+ dev team on this. Let me know if you have any thought. Thanks!

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
UnitarySystem should be able to model all coil types. IO Ref Figure 1-141, pg 1450 (GROUP – UNITARY EQUIPMENT) says this coil is included as a supplemental heater but the code says otherwise.

        if (UtilityRoutines::SameString(loc_suppHeatCoilType, "Coil:Heating:Water")) {
            this->m_SuppHeatCoilType_Num = DataHVACGlobals::Coil_HeatingWater;
        } else if (UtilityRoutines::SameString(loc_suppHeatCoilType, "Coil:Heating:Steam")) {
            this->m_SuppHeatCoilType_Num = DataHVACGlobals::Coil_HeatingSteam;
        } else if (UtilityRoutines::SameString(loc_suppHeatCoilType, "Coil:Heating:Fuel") ||
                   UtilityRoutines::SameString(loc_suppHeatCoilType, "Coil:Heating:Electric") ||
                   UtilityRoutines::SameString(loc_suppHeatCoilType, "Coil:Heating:DesuperHeater")) {
            this->m_SuppHeatCoilType_Num = HeatingCoils::GetHeatingCoilTypeNum(state, loc_suppHeatCoilType, loc_m_SuppHeatCoilName, errFlag);
        } else if (UtilityRoutines::SameString(loc_suppHeatCoilType, "Coil:UserDefined")) {
            this->m_SuppHeatCoilType_Num = DataHVACGlobals::Coil_UserDefined;
        }

Matrix doc for Figure 1-110, 1-120 and 1-141 https://github.com/NREL/EnergyPlusDevSupport/blob/master/DesignDocuments/Proposals/FillGaps_HVACComponents_ParentChildMatrix_ExistingCapabilities.docx
