### ISSUE TITLE
Add volume property to space object

### ISSUE THREAD

**Issue by macumber** [NREL/EnergyPlus#9362]
Issue overview
--------------
Since geometry in E+ is now assigned to a space object it would make sense to be able to assign volume to a space directly and not just to a thermal zone.  This would be useful in cases where a user knows detailed information about the air volume in each space (perhaps from a more detailed CAD model).

**Comment by evapace** [comment]
Hello, I am a senior Computer Science major at Vanderbilt University. For my Software Engineering final project we are being asked to assist a public Github repository in implementing some of their issues, and I would love to move forward with this pull request. I've been looking through the files locally, specifically in the InputProcessing folder, to see how I could approach adding this volume property. Any guidance as to where implementing volume may have dependencies in other files (i.e. output calculations) throughout would be much appreciated, please let me know how I can be most helpful. Thanks in advance.

**Comment by mjwitte** [comment]
This was addressed in #9564
