### ISSUE TITLE
Mean Radiant Temperature (MRT) calculations are zone-based (not enclosure-based)

### ISSUE THREAD

**Issue by nealkruis** [NREL/EnergyPlus#9377]
Issue overview
--------------
Several locations in the source code are still calculating mean radiant temperatures using the zone surface temperatures and not the enclosure surface temperatures. It appears to be done correctly for enclosures in the HBIRE routines.

- [Thermal Comfort](https://github.com/NREL/EnergyPlus/blob/4dfcba32e15375f1e1cf27b5d8b96b1c8845ed81/src/EnergyPlus/ThermalComfort.cc#L2088-L2098)
- [Zone Mean Radiant Temperature](https://github.com/NREL/EnergyPlus/blob/4dfcba32e15375f1e1cf27b5d8b96b1c8845ed81/src/EnergyPlus/HeatBalanceSurfaceManager.cc#L5328-L5340)

I'm not sure a zone mean radiant temperature means much outside of contexts where the zone and the enclosure are 1-to-1. For example, when these temperatures are used to control radiant systems, I would expect they should be controlled based on the mean radiant temperature of the enclosure containing the radiant surface. This enclosure could include surfaces from other zones connected via air walls, or exclude surfaces in the same zone if they are not part of the same space.

The [ComfortViewFactorAngles](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-internal-gains-people-lights-other.html#comfortviewfactorangles) and [AirflowNetwork:Distribution:DuctViewFactors](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-airflow-network.html#airflownetworkdistributionductviewfactor) objects should maybe be adapted to allow input for surfaces outside the zone, but within the same enclosure, too (similar to [ZoneProperty:UserViewFactors:BySurfaceName](https://bigladdersoftware.com/epx/docs/9-6/input-output-reference/group-advanced-surface-concepts.html#zonepropertyuserviewfactorsbysurfacename)).

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [x] Working v22.2 test files in EnergyPlusDevSupport
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@shorowit Do you have a test file to demonstrate the residential basement impact?

**Comment by shorowit** [comment]
@mjwitte I think this should do it. It's a residential home in Denver w/ two spaces, a conditioned basement space adjacent to a Kiva foundation and an above-grade living space, both in the same thermal zone. (It's generated from an HPXML file so there is not full 3D geometry, sorry.)
[in.idf.txt](https://github.com/NREL/EnergyPlus/files/9447532/in.idf.txt)

**Comment by shorowit** [comment]
And here's the same file but using CarrollMRT as the radiation heat transfer algorithm. (Not sure if that triggers any additional branches of code in E+?)
[in2.idf.txt](https://github.com/NREL/EnergyPlus/files/9447577/in2.idf.txt)
