### ISSUE TITLE
** Severe  ** stoi: no conversion in macOS Monterey

### ISSUE THREAD

**Issue by eugeniorodrigues** [NREL/EnergyPlus#9400]
Issue overview
-------------
When running EnergyPlus 22.1.0 in macOS Monterey (M1 Chip) the simulation completes but returns status 1. In the ERR file, the message "** Severe  ** stoi: no conversion" appears. When running in EnergyPlus 9.6.0, no error is returned.

When running the same IDF file in a Windows machine (EnergyPlus 22.1.0), no error is returned. 

The IDF and ERR files are attached to replicate the issue.

### Details
Some additional details for this issue (if relevant):
 - macOS Monterey, MacBook Pro (M1, 2020)
 - EnergyPlus 22.1.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [X] IDF file added
 - [X] ERR file added

[Issue_Example.zip](https://github.com/NREL/EnergyPlus/files/8566122/Issue_Example.zip)

**Comment by jmarrec** [comment]
@eugeniorodrigues Could you please supply your EPW and the .stat file if it's next to it? That's likely what's causing this issue.
Is this from https://climate.onebuilding.org/WMO_Region_6_Europe/PRT_Portugal/index.html?

I can reproduce it with  [PRT_LB_Lisboa.Portela.AP.085360_TMYx.zip](https://climate.onebuilding.org/WMO_Region_6_Europe/PRT_Portugal/LB_Lisboa/PRT_LB_Lisboa.Portela.AP.085360_TMYx.zip).

Anyways, this is the same issue as https://github.com/NREL/EnergyPlus/issues/9420. You can delete /rename the .stat file and it'll run. I'm closing in favor of #9420
