### ISSUE TITLE
Documentation issues in SurfaceProperty:SurroundingSurfaces and ZoneProperty:LocalEnvironment objects

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#9407]
Issue overview
--------------
-  (1) Incorrect Description of Ground Temperature Schedule Name field in SurfaceProperty:SurroundingSurfaces object [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-advanced-surface-concepts.tex#L2546). The text ~solar radiation calculation~ should be replaced with *long wave radiation exchange calculation*.

-  (2) Also a typo in Zone Name field description in ZoneProperty:LocalEnvironment object [here](https://github.com/NREL/EnergyPlus/blob/develop/doc/input-output-reference/src/overview/group-advanced-surface-concepts.tex#L2628). The text *name of a ~surface~ defined elsewhere* should be replaced with *name of a zone defined elsewhere*.

### Details
Some additional details for this issue (if relevant):
 - Platform (Any)
 - Version of EnergyPlus (Develop)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jcyuan2020** [comment]
These two were added to #9351 and now they are fixed now.
