### ISSUE TITLE
ConvertInputFormat incorrectly handles file name with period in name

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#9410]
Issue overview
--------------
On Windows when using ConvertInputFormat with a file that contains a period in the file name an error occurs with the output file name:

```
C:\EnergyPlusV22-1-0>ConvertInputFormat "MediumOffice-90.1-2013-ASHRAE 169-2013-5B-no_user_data-remove_transformer_Baseline.idf"
Input file converted to EPJSON successfully | 1/1 | MediumOffice-90.1-2013-ASHRAE 169-2013-5B-no_user_data-remove_transformer_Baseline.idf
```

Results in a file named:

```
MediumOffice-90.epJSON
```

When using a file with a path as an argument the same occurs.

It looks like a period is searched for from the beginning of the string rather than from the end of the string to identify the extension.

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - Version of EnergyPlus 22.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
The CLI with `energyplus --convert-only 1.ZoneUncontrolled.idf` is affected as well.
