### ISSUE TITLE
Initialization Summary does not appear in Output:JSON

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#9419]
Issue overview
--------------
When specifying that tabular output should be in the JSON format using the Output:JSON input object, the Initialization Summary  (which is the tabular report copy of the EIO report contents) does not appear in the JSON output file. it will appear in the HTML tabular output file but not the EIO file.

To reproduce add the following to 5ZoneAirCooled.idf

```
  Output:JSON,
    TimeSeriesAndTabular,    !- Option Type
    Yes,                     !- Output JSON
    No,                      !- Output CBOR
    No;                      !- Output MessagePack
```

Run simulation and open the JSON output file in text editor then search for "initial"  

Note that EP-Launch won't properly name the output JSON file and instead leaves it in the EPTEMP directory, see #9403

### Details
Some additional details for this issue (if relevant):
 - Windows 10
 - EnergyPlus 22.10, EnergyPlus 9.5.0, and probably other versions

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
It is possible other reports are also missing from the JSON output file such as the Annual Heat Emissions Summary. Like the Initialization Summary, the routine that populates the JSON 

state.dataResultsFramework->resultsFramework->TabularReportsCollection.addReportTable()

seems to be missing near the end of the routine. A good first step may be to check what other reports are missing from the JSON output file and make sure they all get added to the resultsFramework.

**Comment by jmarrec** [comment]
I ran a test with both Output:SQLite and Output:JSON enabled (with 1ZoneUncontrolled.idf). You can read the results here: https://github.com/NREL/EnergyPlusDevSupport/blob/a15a6157a31cc20e2cb4821cccfff965772526cf/DefectFiles/9000s/9419/9419_MissingJSONReports.ipynb

* Spacing in report Names is inconsistent:
    * In OutputSQL's TabularDataWithStrings, there is a single ReportName that has a space: `Initialization Summary` 
    * In Output:JSON there are a lot more:
      ```
      ['Annual Building Utility Performance Summary',
       'Demand End Use Components Summary',
       'Source Energy End Use Components Summary',
       'Surface Shadowing Summary',
       'Input Verification and Results Summary']
      ```

* When you remove spaces, you realize:
    * Reports that are in the SQL but not in JSON: `{'AnnualHeatEmissionsReport', 'InitializationSummary'}`
    * Reports that are in the JSON but not in SQL: `{'SurfaceShadowingSummary'}`

----

**Question:** Do we want to standardize ReportNames to not include spaces? That's an output change since it'll force a limited people to update their SQL queries or JSON queries. Thoughts please @Myoldmopar @JasonGlazer @mjwitte ?

**Comment by JasonGlazer** [comment]
@jmarrec I guess I would say that SQL and JSON should have ReportName with no spaces to just make it more standardized and consistent. That only impacts a single report for OutputSQL. I don't think a lot of people are using Output:JSON yet.
