### ISSUE TITLE
Parsing for precipitation values fails for some weather stat files

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#9420]
Issue overview
--------------
User file fails with this cryptic error:
```
   ************* Beginning Simulation
   ** Severe  ** invalid stoi argument
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
```

There are [two places where `std::stoi` is used](https://github.com/NREL/EnergyPlus/blob/463ec66491ea8a9764668e600abbc67761e45117/src/EnergyPlus/OutputReportTabular.cc#L5928-L5969) to parse lines from the weather stat file for reporting monthly total and max precipitation.

The line being parsed when it fails is this header under ` - Wind Frequency (m/s) by Direction {Interval 11.25 deg from displayed deg) [%]`:
` 	           	<=.5 	<=2  	<=4  	<=6  	<=8  	<=10 	<=12 	<=14 	<=16 	<=18 	>18  	Total	`

This is a newer block that does not exist in the stat files distributed with EnergyPlus.

The root of the problem is [here in `parseStatLine`](https://github.com/NREL/EnergyPlus/blob/463ec66491ea8a9764668e600abbc67761e45117/src/EnergyPlus/OutputReportTabular.cc#L5415-L5420) which assumes that any line containing "Max Hourly" will be for ` - Monthly Statistics for Liquid Precipitation [mm]`. The stat file for this defect has two lines with "Max Hourly" one for liquid precipitation and one for snow depth.

`parseStatLine` also assumes that there will be only 2 occurences of "Total" in the entire stat file, once for `Average Hourly Statistics for Total Sky Cover` and once for liquid precipitation. The stat file for this defect has 4 occurences of "Total".

1. `parseStatLine` needs to be more robust to ensure that values are being pulled from the correct block of statistics. The loop that calls `parseStatLine` needs to be modified to search for " - Monthly Statistics for Liquid Precipitation [mm]" first, then look for "Total" and "Max Hourly".
2. `std::stoi` is fragile and needs to be protected to produce a useful error message, or ignore exceptions and move on to the next statistic, or be replaced with a more robust function such as `UtilityRoutines::ProcessNumber`.

### Workaround
Rename the stat file so that EnergyPlus cannot find it. The simulation will complete, but the Weather Statistics File subtable of the Climatic Data Summary table output will be empty.

### Details
Some additional details for this issue (if relevant):
 - Platform Windows 10
 - Version of EnergyPlus v22.1
 - Private email and helpdesk ticket number nnnn

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached: [9420-weather error.zip](https://github.com/NREL/EnergyPlus/files/8664660/9420-weather.error.zip)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lklawrie** [comment]
Am glad to supply any files to help test this defect but cannot commit to changing some 20,000 files on climate.onebuilding.org at this time.

Linda

**Comment by jmarrec** [comment]
@lklawrie completely understandable :).

I'll fix it on this side. I would suggest making some unit tests on your side to ensure this doesn't creep up again if you make change to your code generation though (or run the ones I added in https://github.com/NREL/EnergyPlus/commit/243ba2ef9dc2219e194b5d9b7cad1f5a5d3ecec3 with some of your files or something)

**Comment by chriswmackey** [comment]
It took me a while to figure out why I wasn't getting any summary reports for my simulations with OneBuilding EPW files but this seems to be the reason. I appreciate the suggested workaround, @mjwitte , and I plan to make use of it until the next stable EnergyPlus release.
