### ISSUE TITLE
Building north axis affects the roof perimeter in the outside surface convection calculations

### ISSUE THREAD

**Issue by eugeniorodrigues** [NREL/EnergyPlus#9432]
Issue overview
--------------
When plotting the perimeter of a ROOF from the outside surface convection calculations (eio file <Surface Convection Parameters>, Outside Perimeter [m]) for all 360° of the building north axis, the perimeter value varies despite the building being the same. In the following figure, the floor and roof surface outside perimeters are plotted. The surfaces are equivalent, only varying the surface normal and the height at which these are placed.

![Screenshot 2022-05-16 at 10 42 30](https://user-images.githubusercontent.com/16454403/168567087-d087a69e-b34f-422d-a73e-c2f26c6d1677.png)

If we use another box-shaped variation of the building, we have a slightly different graph.

![Screenshot 2022-05-16 at 11 10 49](https://user-images.githubusercontent.com/16454403/168570728-61a63456-0ff6-424b-a63e-77d4406daa9e.png)

### Files
- IDF files and plot results
[I_shape_4_h3m_s0_9.zip](https://github.com/NREL/EnergyPlus/files/8699098/I_shape_4_h3m_s0_9.zip)
[I_shape_4_h3m_s0_4.zip](https://github.com/NREL/EnergyPlus/files/8699176/I_shape_4_h3m_s0_4.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): V22.1.0 (and develop at 240b4a238cf93d3094d96667f82d6728c7d1f299)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
@eugeniorodrigues Could you please let us know how you produced this graph? What output data / variable did you use, and what post processing did you do? (If I can avoid guessing that'd be a lot better for everyone!)

Thanks!

So you're running the same model 360 times varying the Building North Axis, then you go to the EIO file and you get this:

```
! <Surface Convection Parameters>, Surface Name, Outside Model Assignment, Outside Area [m2], Outside Perimeter [m], Outside Height [m], Inside Model Assignment, Inside Height [m], Inside Perimeter Envelope [m], Inside Hydraulic Diameter [m], Window Wall Ratio, Window Location, Near Radiant {Yes/No}, Has Active HVAC {Yes/No}
Surface Convection Parameters,SURFACE_0,0,273.86,202.19,8.00,0,3.00,79.03,52.16,0.00,0,No,No
Surface Convection Parameters,SURFACE_1,0,109.54,132.90,8.00,0,3.00,79.03,52.16,0.00,0,No,No
Surface Convection Parameters,SURFACE_2,0,273.86,202.19,8.00,0,3.00,79.03,52.16,0.00,0,No,No
Surface Convection Parameters,SURFACE_3,0,109.54,132.90,8.00,0,3.00,79.03,52.16,0.00,0,No,No
Surface Convection Parameters,SURFACE_4,0,3333.33,255.60,0.00,0,3.00,79.03,52.16,0.00,0,No,No
Surface Convection Parameters,SURFACE_5,0,3333.33,310.38,0.00,0,3.00,79.03,52.16,0.00,0,No,No
```

Then what? You plot get the results for "SURFACE_5" (which is the roof), here `310.38`, and put that into a table, then you plot a plot for each 360 values? Is that it?

If you have used a script to do that, please supply it as well so we don't have to reinvent the wheel trying to reproduce this.

**Comment by eugeniorodrigues** [comment]
@jmarrec Yes. The SURFACE_4 is the floor surface and SURFACE_5 is the roof. I have selected the outside perimeter values of both in each north axis variation run and saved it in a dataframe. Then I have plotted them. Do you need the python script?

**Comment by eugeniorodrigues** [comment]
@jmarrec Here goes the python script. If you need anything else, please tell. Thanks for the support.

[SurfaceConvection.zip](https://github.com/NREL/EnergyPlus/files/8701210/SurfaceConvection.zip)

**Comment by jmarrec** [comment]
This is the variable that's being reported:
https://github.com/NREL/EnergyPlus/blob/240b4a238cf93d3094d96667f82d6728c7d1f299/src/EnergyPlus/ConvectionCoefficients.cc#L4610

https://github.com/NREL/EnergyPlus/blob/240b4a238cf93d3094d96667f82d6728c7d1f299/src/EnergyPlus/DataSurfaces.hh#L1531

And it's set here: https://github.com/NREL/EnergyPlus/blob/240b4a238cf93d3094d96667f82d6728c7d1f299/src/EnergyPlus/ConvectionCoefficients.cc#L4537-L4580

**Comment by Myoldmopar** [comment]
Lots of messages showing up in the error files, so this is not yet ready to go.  I'll hold off from digging into the code for now.
