### ISSUE TITLE
Allow Space-level infiltration/ventilation

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#9448]
Issue overview
--------------
Now that EnergyPlus has the concept of Spaces, it'd be nice if it supported space-level infiltration/ventilation. This was requested [several times here](https://github.com/NREL/EnergyPlus/pull/8394) -- search for infiltration. OpenStudio supports space-level infiltration objects, but then has to go through hoops to combine them into a zone-level infiltration object for EnergyPlus.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jasondegraw** [comment]
How the infiltration objects (and other "ZoneSomethingSomething" objects) fit into the overall scheme of things is a part of the current discussions on the heat balance at the space level (#9394). However that all shakes out would probably close this issue with an implementation that does it, a plan for when it will get done, or WontFix. So do we really need a separate issue?

**Comment by shorowit** [comment]
If the space-level heat balance doesn't get implemented (WonfFix), I would still like to see EnergyPlus support space-level infiltration/ventilation objects. But yes, that PR might resolve this issue depending on where it ends up.

**Comment by nealkruis** [comment]
@shorowit I don't think that this aspect is in question for the PR (correct, @mjwitte?). We might want to change the name from "ZoneInfiltration" to "Infiltration", though.
