### ISSUE TITLE
AirLoop Component Load Summary not sizing for coincident

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#9451]
Issue overview
--------------
Here is a description from a user:

Cove Tool has a question about the component load summary reports.

Basically, the AirLoop Component Load Summary is showing the noncoincident peak (sum of zone peaks) rather than the coincident peak, regardless of the Concident/Nonconcident status in the Sizing:System object.

It is seemingly related to this issue: [https://github.com/NREL/EnergyPlus/issues/6337](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2FEnergyPlus%2Fissues%2F6337&data=05%7C01%7CEdwin.Lee%40nrel.gov%7C33f08c4b734242c778ca08da3927fd6a%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637885142236592703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=d7EJ%2FCeIWMagKmQ5Czovq1tZIrRoHmd%2FcKid%2B0dbJsI%3D&reserved=0)

Is there a way to see if the ‘else’ portion of this method ([https://github.com/NREL/EnergyPlus/blob/da69d5b3e21eeab7be9c29b19ec2a98e248abac5/src/EnergyPlus/OutputReportTabular.cc#L11846-L11870](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2FEnergyPlus%2Fblob%2Fda69d5b3e21eeab7be9c29b19ec2a98e248abac5%2Fsrc%2FEnergyPlus%2FOutputReportTabular.cc%23L11846-L11870&data=05%7C01%7CEdwin.Lee%40nrel.gov%7C33f08c4b734242c778ca08da3927fd6a%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637885142236592703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iXafc8BH%2ByADXqqzNx%2BKQbiDX70Z1tloW0tl%2BDz0soY%3D&reserved=0)) of the Air Loop Component Load is getting called?

Or is ‘iZone’ the correct argument here to get ‘coolDesSelected’ and ‘timeCoolMax’?
[https://github.com/NREL/EnergyPlus/blob/da69d5b3e21eeab7be9c29b19ec2a98e248abac5/src/EnergyPlus/OutputReportTabular.cc#L11851-L11852](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FNREL%2FEnergyPlus%2Fblob%2Fda69d5b3e21eeab7be9c29b19ec2a98e248abac5%2Fsrc%2FEnergyPlus%2FOutputReportTabular.cc%23L11851-L11852&data=05%7C01%7CEdwin.Lee%40nrel.gov%7C33f08c4b734242c778ca08da3927fd6a%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637885142236592703%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=12%2BiVu26La6aYMCcWC%2BZubSyER3E7hPX4VUTe%2BAuzEo%3D&reserved=0) 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by JasonGlazer** [comment]
@lgu1234 let me know if you need any help on this. I don't see a branch or pull request yet.
