### ISSUE TITLE
Fan coil fatal sizing error

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#9464]
Issue overview
--------------
The attached input file from the ASHRAE Standard 140 air-side equipment (AE) tests ran fine in v8.5, but fails in v22.1.0:
```
   ** Severe  ** SizeWaterCoil Coil:Cooling:Water ZONE ONE COOLING COIL, Developer Error: Component sizing incomplete.
   **   ~~~   ** SizingString = Design Inlet Air Temperature [C], SizingResult = -99998.9
   ** Severe  ** Developer Error: sizing of Design Inlet Air Temperature [C] failed.
   **   ~~~   ** Occurs in Coil:Cooling:Water ZONE ONE COOLING COIL
```
Not sure what the issue is with this particular file. Other fan coil test files (such as HVACTemplate-5ZoneFanCoil.idf) run fine with a fully autosized cooling coil. In this file, the cooling coil is fully autosized except the air flow rate has a hard value, and the cooling load happens to be zero for this test case.

### Workaround
Filling in all of the autosized fields in the cooling coil object gets around the problem. This is a special case, so that was possible here.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus 22.1.0-10c89547de

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file attached: 
[CaseAET101a-FanCoil-Broken.idf.txt](https://github.com/NREL/EnergyPlus/files/8809510/CaseAET101a-FanCoil-Broken.idf.txt)
[CaseAET101a-FanCoil-Workaround.idf.txt](https://github.com/NREL/EnergyPlus/files/8809511/CaseAET101a-FanCoil-Workaround.idf.txt)

 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Looks like I forgto to allow for negative autosized values of temperature.

![image](https://user-images.githubusercontent.com/5778156/172681662-b258198e-10b7-4d6b-abcf-ef6c254afe0e.png)
