### ISSUE TITLE
iam having an error in design builder simulation, iam trying to run an annual energy simulation, after the annual simulation the results include this warning "WARNING: THE REPORT DOES NOT REPRESENT A FULL ANNUAL SIMULATION." can some one help me please

### ISSUE THREAD

**Issue by JuliaAdel** [NREL/EnergyPlus#9474]
Issue overview
--------------
Please change this line to a description of the defect, with useful supporting information including how the issue was found, conditions that trigger this defect, workarounds for users of the current version, and a clear description of how to validate that a fix is complete for this defect.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
If your annual simulation is less than 8759 hours this warning is issued. There is also a user help site at UnmetHours.com that can help with these types of questions. Also see this response https://unmethours.com/question/27236/getting-warning-in-results-of-energyplus/
