### ISSUE TITLE
CFS with external complex shading layer crash in full exterior interior solar distribution mode

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9485]
Issue overview
--------------
A crash was reported in a case where a CFS window has an outer layer specified as shading (via WindowsMaterial:ComplexShade) under some circumstances. It was later identified that the crash will occur when the full exterior interior solar distribution algorithm is used, and when the sun hits the back side of the surface. The code will then try retrieving information from `state.dataSurface->SurfWinActiveShadedConstruction`:
https://github.com/NREL/EnergyPlus/blob/c25e0736e4ee7fe282066f6ddaeeecea60c1fc6a/src/EnergyPlus/SolarShading.cc#L7458

However, for the CFS with an outer shading layer (e.g. WindowsMaterial:ComplexShade), the `state.dataSurface->SurfWinActiveShadedConstruction` was not properly set since this configuration was not considered a "Windows Shade Control".

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v22.1, may trace back to as early as v9.4
 - helpdesk ticket number: 16072

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Fixed by #9486.
