### ISSUE TITLE
Inccorret declaration of dataIsDXCoil variable in BaseSizer

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#9511]
Issue overview
--------------
While working on another issue I saw the variable `dataIsDXCoil` declared as Real but initialized as boolean [base.hh](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Autosizing/Base.hh#L241). See below.

`Real64 dataIsDXCoil = false;`

Subsequently the variable is assigned to a boolean variable [base.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Autosizing/Base.cc#L160) and used in [CoolingCapacitySizer.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Autosizing/CoolingCapacitySizing.cc#L468) and in [HeatingCapacitySizer.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/Autosizing/HeatingCapacitySizing.cc#L387).

### Details
Some additional details for this issue (if relevant):
 - Platform (any)
 - Version of EnergyPlus (develop, [7a5cb57](https://github.com/NREL/EnergyPlus/commit/7a5cb57be8584376c47fbe8079593852bfa16c1e))
 - Corrected it and ran the unit tests serially in my local machine but produced no diffs. I will run regression to see the impact of the the fix. 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
Addressed in #9501.

**Comment by rraustad** [comment]
A different bool was corrected in #9501.
