### ISSUE TITLE
Zero zone floor area causes E+ crash by running debug

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#9515]
Issue overview
--------------
The release runs the defect file fine. However, when run with the debugger zero floor area causes program crashed in Line 525 in the SurfaceGeometry module

                    ZFlrAvg += ((Z1 + Z2) / 2.0) * (thisSurface.Area / thisZone.FloorArea);

When debug the program, found zone calcFloorArea > 0 and FloorArea = 0. 
### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ X] Defect file added (list location of defect file here)
 - [ X] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Closed via #9520
