### ISSUE TITLE
Incorrect logic to set cooling and heating flag in UnitarySystem

### ISSUE THREAD

**Issue by lgu1234** [NREL/EnergyPlus#9524]
Issue overview
--------------
@rraustad found that the stageNum is used to set up heating and cooling in UnitarySys::initLoadBasedControl for staged thermostat control

        // Staged control
        if (this->m_Staged) {
            if (this->m_StageNum == 0) {
                state.dataUnitarySystems->HeatingLoad = false;
                state.dataUnitarySystems->CoolingLoad = false;
                QZnReq = 0.0;
            } else {
                QZnReq =
                    state.dataZoneEnergyDemand->ZoneSysEnergyDemand(this->ControlZoneNum).RemainingOutputRequired / this->ControlZoneMassFlowFrac;
                if (this->m_StageNum > 0) {                                         <--- shouldn't this be if (QZnReq > 0)
                    state.dataUnitarySystems->HeatingLoad = true;
                    state.dataUnitarySystems->CoolingLoad = false;
                } else {
                    state.dataUnitarySystems->HeatingLoad = false;
                    state.dataUnitarySystems->CoolingLoad = true;
                }
            }
        }

The correct logic should be  if (QZnReq > 0).

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ X] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
@lgu1234 Looks like this was fixed and the issue can be closed?

**Comment by lgu1234** [comment]
@shorowit Yes. I am going to close it.
