### ISSUE TITLE
japanese model produces XML error

### ISSUE THREAD

**Issue by MatthewSteen** [NREL/EnergyPlus#9534]
Issue overview
--------------
This Japanese [IDF](https://github.com/NREL/EnergyPlus/files/9105845/in_2210.idf.txt) produces an [XML](https://github.com/NREL/EnergyPlus/files/9105838/in_2210Table.xml.txt) with an error. The other files (e.g. HTML) are unaffected. The middle character in Zone `電気室 19` becomes unreadable, see line 5575 for first instance. As far as I can tell the character `気` is supported by [Unicode CJK](https://www.unicode.org/charts/PDF/U4E00.pdf). This model originally came from Revit and was updated from 9.1.0 to 22.1.0 with a couple changes to get it to run.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version) = Windows 10
 - Version of EnergyPlus (if using an intermediate build, include SHA) = 22.1.0
 - Unmethours link or helpdesk ticket number = NA

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
```python
In [1] s = '電気室 19'
       s.encode()
Out[1]: b'\xe9\x9b\xbb\xe6\xb0\x97\xe5\xae\xa4 19'
```

That `\xb0` is understood as a degree sign here: https://github.com/NREL/EnergyPlus/blob/adad2e37ac398d93bab979f8208080f141bc581a/src/EnergyPlus/OutputReportTabular.cc#L16696-L16697

**Comment by jmarrec** [comment]
The first <BuildingName> tag is wrong too. it's currently `<state.dataHeatBal->BuildingName>`


https://github.com/NREL/EnergyPlus/blob/4872b63adc2630585108b0c9d0c5ebc492ca29e3/src/EnergyPlus/OutputReportTabular.cc#L3162

see https://github.com/NREL/EnergyPlus/commit/b54335e08d347bf3c1d20ea87e2eb45dff11b9bd#r83285404

**Comment by jmarrec** [comment]
Holy molly, encodings are just the worst. I thought we could just stop trying to use `ConvertToEscaped` and specify the encoding in the xml (which we don't do right now) by adding `<?xml version="1.0" encoding="UTF-8"?>`. But obviously that was a terrible idea, since:
* The IDF file may not be UTF-8 encoded
* The .stat files from the E+ website are **definitely** `latin1` (`latin1[dos]` on the website, `latin1[unix]` on the E+ repo on my ubuntu machine) (those are used in `FillWeatherPredefinedEntries` to pick up lat/longitude which includes a `°` sign)

**Comment by MatthewSteen** [comment]
@jmarrec checking in on this issue to see if you have any updates after your initial investigation. Thanks.

**Comment by jmarrec** [comment]
Aside from doing very complicated things, like depending on libicu to infer the encoding (don't know if it would work and the computing cost associated to be honest), no.

Stick to ascii only characters has always been a recommendation. It's annoying, I know (but really time zones and encoding may be the worst part of any program)

**Comment by MatthewSteen** [comment]
Thanks for the update. Feel free to add a `won't fix` label and close.

**Comment by marklemay** [comment]
From what I understand of the xml specification, `&deg;` is always invalid xml text (unless `deg` is defined as an [entity](https://www.w3schools.com/xml/xml_dtd_entities.asp)?).  
For instance, try running `<?xml version="1.0" ?><tag>&deg;</tag>` in an [xml validator](https://www.liquid-technologies.com/online-xml-validator).  Form the discussion [here](https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents/46637835#46637835) it seems `&deg;` does not need to be escaped in xml,
