### ISSUE TITLE
PackagedTerminalHeatPump does not honor the fan availability schedule

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#9547]
Issue overview
--------------
Testing shows that the ZoneHVAC:WaterToAirHeatPump used in example file ZoneSysAvailManager turns on during the winter design day when the fan should be off.

    Fan:OnOff,
      Zone 1 Fan,              !- Name
      FanAvailSched,           !- Availability Schedule Name

    Schedule:Compact,
      FanAvailSched,           !- Name
      Fraction,                !- Schedule Type Limits Name
      Through: 12/31,          !- Field 1
      For: AllDays,            !- Field 2
      Until: 7:00,0.0,         !- Field 3
      Until: 17:00,1.0,        !- Field 5
      Until: 24:00,0.0;        !- Field 7

![image](https://user-images.githubusercontent.com/5778156/179568132-bc6cee54-f923-4f6f-b611-c32eadcaf94d.png)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
I suspect the nightcycle manager is turning it on.
```
    Zone1WTAHP Avail List;   !- Availability Manager List Name

  AvailabilityManagerAssignmentList,
    Zone1WTAHP Avail List,   !- Name
    AvailabilityManager:NightCycle,  !- Availability Manager 1 Object Type
    Zone1WTAHP NC Avail,     !- Availability Manager 1 Name
    AvailabilityManager:ScheduledOff,  !- Availability Manager 2 Object Type
    Zone1WTAHP Avail;        !- Availability Manager 2 Name
```

**Comment by rraustad** [comment]
OK I'll buy that.

    Schedule:Compact,
      Heating Setpoints,       !- Name
      Temperature,             !- Schedule Type Limits Name
      Through: 12/31,          !- Field 1
      For: AllDays,            !- Field 2
      Until:  7:00,15.0,       !- Field 3
      Until: 17:00,21.0,       !- Field 5
      Until: 24:00,15.0;       !- Field 7

![image](https://user-images.githubusercontent.com/5778156/179573159-6ceb9dbb-11a7-440a-9002-faca766d0e65.png)

**Comment by rraustad** [comment]
As designed.
