### ISSUE TITLE
How to install without sudo ?

### ISSUE THREAD

**Issue by HYDesmondLiu** [NREL/EnergyPlus#9559]
Issue overview
--------------
How do we install without sudo ?

**Comment by Myoldmopar** [comment]
Just install it to a folder that has write access without sudo.

**Comment by HYDesmondLiu** [comment]
Hi, 
   I am sorry I did not clearly explain my problem.
   
   I got this error trying to run the .run file downloaded from the website.
   
```
./EnergyPlus-22.1.0-ed759b17ee-Linux-Ubuntu18.04-x86_64.run 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, xcb.

Aborted (core dumped)
```

However, I don't have access to install "xcb" as a sudo.
Is there any workaround for this?
