### ISSUE TITLE
Installation without Qt?

### ISSUE THREAD

**Issue by HYDesmondLiu** [NREL/EnergyPlus#9563]
Issue overview
--------------
Do we have to install with Qt?
I have no sudo access, how could we install without Qt ?

### Details
```
./EnergyPlus-22.1.0-ed759b17ee-Linux-Ubuntu18.04-x86_64.run 
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, xcb.

Aborted (core dumped)

```

**Comment by jmarrec** [comment]
1. use the tar.gz or .sh installer instead
2. Use the install_script.qs for a headless install, cf https://github.com/NREL/EnergyPlus/blob/96711f4b83e10ca7f8fab1129ef41572725d85ca/cmake/qtifw/install_script.qs#L18

**Comment by HYDesmondLiu** [comment]
Hi @jmarrec ,
    Could I do it as a non-sudo user?

**Comment by jmarrec** [comment]
In all cases (tar.gz, sh or .run installers), yes. But you can't extract/install to /usr/ or any write protected folder. And you can't do the symlinks (sh/run only). I suggest using the tar.gz one, it's probably simpler, just extract to a folder in your /home/ and it should work fine

**Comment by HYDesmondLiu** [comment]
Do you know where I could find a tar.gz installation file?
The only one I could find on the internet is the official one .run file for Ubuntu.

**Comment by shorowit** [comment]
It's at the bottom of any given release on GitHub.

For example, EnergyPlus 22.1: https://github.com/NREL/EnergyPlus/releases/tag/v22.1.0

**Comment by HYDesmondLiu** [comment]
Hi @shorowit ,
    Thanks a lot for the pointer. I originally thought the official website is the only place to download.
