### ISSUE TITLE
`undefined symbol: cClearAllStates` when using Python API

### ISSUE THREAD

**Issue by simonsays1980** [NREL/EnergyPlus#9588]
Issue overview
--------------
Using the Python API I get a `undefined symbol: cClearAllStates` error

I use the Python API to run EnergyPlus and when executing the following lines I get an error from the shared library:
```
import sys
sys.path.insert(0, "/home/simon/git-projects/EnergyPlus_build/Products")
from pyenergyplus.api import EnergyPlusAPI

api = EnergyPlusAPI()
api.api.cClearAllStates()
```
The error is:
```
api.api.cClearAllStates()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/simon/.pyenv/versions/3.9.0/lib/python3.9/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/simon/.pyenv/versions/3.9.0/lib/python3.9/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /home/simon/git-projects/EnergyPlus_build/Products/libenergyplusapi.so: undefined symbol: cClearAllStates
```
### Details
Some additional details for this issue (if relevant):
 - Fedora 35
 - EnergyPlus 22.1.0
 - Python 3.9.0
 - Pyenv 2.0.3-171-g423de9ae

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Myoldmopar** [comment]
Yeah I wouldn't try to access the C API methods through a Python client.  Ideally those would be underscored to hint that they are private, but anyway, I don't think any of our examples do anything like that.  State is a standalone thing and there is a reset_state method on it: https://github.com/NREL/EnergyPlus/blob/develop/tst/EnergyPlus/api/TestRuntimeResetState.py#L75.  Or you can just create a new state if you want and let that state memory get cleaned up when the process ends. (If this isn't like a server running many runs.)

**Comment by simonsays1980** [comment]
@Myoldmopar Thanks for the quick reply! That clarifies it. 

Have there ever been considerations to allow in the `api.runtime.callback_end_zone_timestep_after_zone_reporting()` the callback function to have other arguments than only the `State` argument? I ask because I was using this API method inside of a custom class and needed the instance inside of the callback function to access the class' attributes.

**Comment by Myoldmopar** [comment]
There hasn't been much consideration about it, because I think you can achieve the same thing with a lambda. 
 You can still access the `self` instance variable as in this example: https://github.com/NREL/EnergyPlus/blob/develop/tst/EnergyPlus/api/test_SysExit.py

**Comment by jmarrec** [comment]
Is there anything to be done here really or should we just close?
