### ISSUE TITLE
python API get_actuator_handle

### ISSUE THREAD

**Issue by xixihaha1995** [NREL/EnergyPlus#9598]
Issue overview
--------------
I‘'m wondering which actuator variables are available for the following API call:
Do we have a reference manual to look up? For example, including "Weather Data", what other component_type do we have?
```python
    def get_actuator_handle(
            self,
            state: c_void_p,
            component_type: Union[str, bytes],
            control_type: Union[str, bytes],
            actuator_key: Union[str, bytes]
    ) -> int:
        """
        Get a handle to an available actuator in a running simulation.

        The arguments passed into this function do not need to be a particular case, as the EnergyPlus API
        automatically converts values to upper-case when finding matches to internal variables in the simulation.

        Note also that the arguments passed in here can be either strings or bytes, as this wrapper handles conversion
        as needed.

        :param state: An active EnergyPlus "state" that is returned from a call to `api.state_manager.new_state()`.
        :param component_type: The actuator category, e.g. "Weather Data"
        :param control_type: The name of the actuator to retrieve, e.g. "Outdoor Dew Point"
        :param actuator_key: The instance of the variable to retrieve, e.g. "Environment"
        :return: An integer ID for this output variable, or -1 if one could not be found.
        """
```

**Comment by Myoldmopar** [comment]
@xixihaha1995 Thanks for using the API, but this isn't an issue.  Issues on this repo should represent defects or feature requests.  Questions like this are better suited for peer-to-peer support sites like unmethours.com.  

That said, you can find the actuators available for a given simulation by calling the `list_available_api_data_csv` function which will return a csv string that you can conveniently write to a file and open in a spreadsheet program.  See: https://energyplus.readthedocs.io/en/latest/datatransfer.html#datatransfer.DataExchange.list_available_api_data_csv

If you have questions, please use unmethours.com, but if you experience any defects, please feel free to continue to use issues here!  Thanks!
