### ISSUE TITLE
Clean Up GetPollutionFactorInput Code

### ISSUE THREAD

**Issue by RKStrand** [NREL/EnergyPlus#9603]
Issue overview
--------------
During work on another defect (#9493), it was discovered that the code in GetPollutionFactorInput is highly repetitive and needs to be improved/shortened.  While this does not cause any problems with EnergyPlus, it makes any change in this area incredibly tedious.  So, a rework of this code is important for clarity and any future work that takes place.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 22.1
 - Unmethours link or helpdesk ticket number: none (discovered while working on #9493)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here): none needed.
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@rkstrand This appears to be moot after @amirroth 's pollution module refactor in https://github.com/NREL/EnergyPlus/pull/10289 . Closing this issue, reopen if I've misunderstood.
