### ISSUE TITLE
EnergyPlus stops with error when SC-Center is 0 in Window5Data.dat file

### ISSUE THREAD

**Issue by michael-okeefe** [NREL/EnergyPlus#9609]
Issue overview
--------------
There is a subtle EnergyPlus issue related to interpreting the parsed values from LBNL WINDOW data files.

The issue is occurring in src/EnergyPlus/HeatBalanceManager.cc around line 6980. Both Shading Coefficient Center (SCCenter) and SHGC Center (SHGCCenter) are in the Window5Data.dat file but, in some cases, SC-Center is being set to zero (by LBNL WINDOW) which causes EnergyPlus to stop with an error (it looks like WINDOW is just calculating the SHGC for some cases and SC gets set to 0 which is a bug with LBNL WINDOW). Note that the file is otherwise OK but just has SC-Center set to 0. However, it doesn't appear that EnergyPlus is actually even using SC (or SHGC for that matter) as-read from this file as the values seem to be recalculated elsewhere for individual panes.

If EnergyPlus isn't using SC directly, it would be more helpful to have a warning issued instead of the simulation stopping with an error. Alternatively, if SC is zero but SHGC is non-zero, perhaps SC can be set to SHGC / 0.87 (see ThermalISO15099Calc.cc:1083).

## Trigger

This is triggered when a Window5Data.dat file has a value of 0 for SC-Center (caused by LBNL WINDOW). Set the SC-Center value to 0 in an otherwise working Window5Data.dat file to trigger.

## Workarounds

Change the SC-Center value in the Window5Data.dat file from 0 to SHGC / 0.87.

## Validation that a Fix is Complete

EnergyPlus issues a warning that SC-Center is 0.0 in a Window5Data.dat file instead of preventing simulation and stopping with an error.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by RKStrand** [comment]
@michael-okeefe Verified that this is a problem for SC.  It also happens when SHGC is set to zero.  I've fixed them both so that now it just produces a warning message and continues with the simulation rather than erroring out.  This fix should make it into V22.2.
