### ISSUE TITLE
Fatal error running EnergyPlus in Linux using Eppy 

### ISSUE THREAD

**Issue by liuhz-github** [NREL/EnergyPlus#9612]
I am running EnergyPlus in Linux environment. All input files paths (.idd, .idf, .epw) have been properly defined. I am able to run EnergyPlus with the input files through the command lines. 

However, when I try to run EnergyPlus through python script with eppy, the intermediate files (eplusout.expidf) are not generated and the program stops. It seems the ExapandObjects step is not successful. All folder permissions have been set to 0777.

Python scripts:
from eppy.modeleditor import IDF
iddfile = "/home/EnergyPlus-9.1.0-08d2e308bb-Linux-x86_64/Energy+.idd" 
IDF.setiddname(iddfile)
epwfile = "USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
idfname = "/home/test.idf"
idf.run(output_directory = '../')

Error messages: 
Program Version,EnergyPlus, Version 9.1.0-08d2e308bb, YMD=2022.08.22 18:49,
   **  Fatal  ** Input file path /home/eplusout.expidf not found
   ...Summary of Errors that led to program termination:
   ..... Reference severe error count=0
   ..... Last severe error=
   ************* Warning:  Node connection errors not checked - most system input has not been read (see previous warning).
   ************* Fatal error -- final processing.  Program exited before simulations began.  See previous error messages.
   ************* EnergyPlus Warmup Error Summary. During Warmup: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Sizing Error Summary. During Sizing: 0 Warning; 0 Severe Errors.
   ************* EnergyPlus Terminated--Fatal Error Detected. 0 Warning; 0 Severe Errors; Elapsed Time=00hr 00min  0.14sec
.

Please kindly advise! Thank you.

**Comment by jmarrec** [comment]
This has nothing to do with EnergyPlus. Refer to the eppy documentation. Basically you have HVACTemplates objects in your file so you need to do `idf.run(output_directory = '../', expandobjects=True)`

cf https://eppy.readthedocs.io/en/latest/runningeplus.html , `expandobjects` defaults to False.

FYI, the eppy project is at https://github.com/santoshphilip/eppy/

**Comment by liuhz-github** [comment]
Thank you!
I tried the suggested line, idf.run(output_directory = '../', expandobjects=True), but the error persists. :( 
I will check with eppy side.
