### ISSUE TITLE
AllSummaryAndMonthly option in Output:Table:SummaryReports prompts many warnings and incomplete reports

### ISSUE THREAD

**Issue by JasonGlazer** [NREL/EnergyPlus#9621]
Issue overview
--------------
Adding the predefined monthly reports by including:

```
  Output:Table:SummaryReports,
    AllSummaryAndMonthly;              !- Report 1 Name

```
Generates about 200 new warning messages. An example is shown below

```
   ** Warning ** In Output:Table:Monthly 'SpaceGainsMonthly' invalid Variable or Meter Name 'ZONE GAS EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'SpaceGainsMonthly' invalid Variable or Meter Name 'ZONE HOT WATER EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'SpaceGainsMonthly' invalid Variable or Meter Name 'ZONE STEAM EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'SpaceGainsMonthly' invalid Variable or Meter Name 'ZONE OTHER EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'PeakSpaceGainsMonthly' invalid Variable or Meter Name 'ZONE GAS EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'PeakSpaceGainsMonthly' invalid Variable or Meter Name 'ZONE HOT WATER EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'PeakSpaceGainsMonthly' invalid Variable or Meter Name 'ZONE STEAM EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'PeakSpaceGainsMonthly' invalid Variable or Meter Name 'ZONE OTHER EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'SpaceGainComponentsAtCoolingPeakMonthly' invalid Variable or Meter Name 'ZONE GAS EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'SpaceGainComponentsAtCoolingPeakMonthly' invalid Variable or Meter Name 'ZONE HOT WATER EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'SpaceGainComponentsAtCoolingPeakMonthly' invalid Variable or Meter Name 'ZONE STEAM EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'SpaceGainComponentsAtCoolingPeakMonthly' invalid Variable or Meter Name 'ZONE OTHER EQUIPMENT TOTAL HEATING ENERGY'
   ** Warning ** In Output:Table:Monthly 'EnergyConsumptionElectricityGeneratedPropaneMonthly' invalid Variable or Meter Name 'ELECTRICITYPRODUCED:FACILITY'
   ** Warning ** In Output:Table:Monthly 'EnergyConsumptionElectricityGeneratedPropaneMonthly' invalid Variable or Meter Name 'ELECTRICITYPRODUCED:FACILITY'
   ** Warning ** In Output:Table:Monthly 'EnergyConsumptionElectricityGeneratedPropaneMonthly' invalid Variable or Meter Name 'PROPANE:FACILITY'
   ** Warning ** In Output:Table:Monthly 'EnergyConsumptionElectricityGeneratedPropaneMonthly' invalid Variable or Meter Name 'PROPANE:FACILITY'


```
This probably also means that the reports are not showing the results that are expected. Probably the output variables have been renamed and the corresponding predefined monthly reports were not updated.

See OutputReportTabular.cc function CreatePredefinedMonthlyReports()

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/blob/aafe40cab64e13341a4914069712e55f9fd88ae9/DefectFiles/9000s/9621/1ZoneUncontrolled.idf#L459-L477
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
The variable is fine. But it's set up only if you have gas equipment in the zone.

https://github.com/NREL/EnergyPlus/blob/56f3a890b40c0423f5d5df4c439466129ad49a70/src/EnergyPlus/InternalHeatGains.cc#L4892-L4896

https://github.com/NREL/EnergyPlus/blob/56f3a890b40c0423f5d5df4c439466129ad49a70/src/EnergyPlus/InternalHeatGains.cc#L5070-L5083

**Comment by JasonGlazer** [comment]
It is more than just for gas, here is the entire .err file:

[5ZoneAirCooled.err.txt](https://github.com/NREL/EnergyPlus/files/9432989/5ZoneAirCooled.err.txt)

It is very likely that all of these variables have never been created for this input file: 5ZoneAirCooled.idf 

At the end it does say:

```
   ** Warning ** Processing Monthly Tabular Reports: Variable names not valid for this simulation
   **   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual variables.

```

I'm not sure what else to do, maybe add more details to this last warning. I tripped on it and jumped to the wrong conclusion.

**Comment by KarenWGard** [comment]
should we change the warnings to be displayed only when `Output:Diagnostics,DisplayExtraWarnings`?

seems a bit silly to have so many warnings for something that isn't an issue, and something that the user has no control over.  The warning at the end seems sufficient

```
   ** Warning ** Processing Monthly Tabular Reports: Variable names not valid for this simulation
   **   ~~~   ** ...use Output:Diagnostics,DisplayExtraWarnings; to show more details on individual variables.

```

**Comment by jmarrec** [comment]
Ideally you do want these warnings in case you put a wrong variable in an Output:Table:Monthly you defined yourself though.

I'll give a shot at fixing this one.

**Comment by jmarrec** [comment]
There are other problems in there...

* You don't get the `DisplayExtraWarnings` message if you have simulation control set to "Run Simulation for Sizing Periods" + "Run Simulation for Weather File Run Periods".
* If it's a weather run, and you have DisplayExtraWarnings enabled, you actually get **two warnings for the same variable**

**Comment by KarenWGard** [comment]
@jmarrec - the location where the warning is created, it goes through predefined output reports (I didn't save the line of code).  I assumed that custom user variables and reports were processed elsewhere.

**Comment by jmarrec** [comment]
They are all processed in the same routine (and stored in the same array).

#10211 is a proposed fix.
