### ISSUE TITLE
IDFVersionUpdater not working for V22-1-0 files to V22-2-0-IOFreeze

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#9625]
Issue overview
--------------

IDFVersionUpdater not working on Linux for V22-2-0-IOFreeze.

```shell
mkdir tmp
cd tmp
cp /usr/local/EnergyPlus-22-1-0/ExampleFiles/1ZoneUncontrolled.idf 
grep Version 1ZoneUncontrolled.idf 
>  Version,22.1;
../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/IDFVersionUpdater
```

![image](https://user-images.githubusercontent.com/5479063/186856465-02e7fd77-8961-4a25-989b-aaf9558e642d.png)

The "New Version" dropdown also only shows 22.1, it does not detect 22.2

All the required files are there though:

```
$ ls ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/*22*
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/OutputChanges22-1-0-to-22-2-0.md
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/OutputChanges9-6-0-to-22-1-0.md
'../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Report Variables 22-1-0 to 22-2-0.csv'
'../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Report Variables 9-6-0 to 22-1-0.csv'
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Rules22-1-0-to-22-2-0.md
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Rules9-6-0-to-22-1-0.md
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Transition-V22-1-0-to-V22-2-0
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/Transition-V9-6-0-to-V22-1-0
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/V22-1-0-Energy+.idd
 ../EnergyPlus-22.2.0-56f3a890b4-Linux-Ubuntu20.04-x86_64/PreProcess/IDFVersionUpdater/V22-2-0-Energy+.idd
```

### Details

Some additional details for this issue (if relevant):

 - Platform (Operating system, version): Ubuntu 20.04
 - Version of EnergyPlus (if using an intermediate build, include SHA): V22-2-0-IOFreeze

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Time to move on to https://github.com/Myoldmopar/IDFVersionUpdater2 ?

**Comment by mjwitte** [comment]
@jmarrec @JasonGlazer I've reproduced this problem on windows also. It works fine for older files, say v9.5 to v22.2. But it fails when selecting a v22.1 file to convert to v22.2. I suspect the "old" version name variable isn't accommodating the longer version number?

**Comment by JasonGlazer** [comment]
I will take a look, I thought I had tested exactly this.
