### ISSUE TITLE
Chiller:Electric:ASHRAE205 has two A21 fields in  Energy+.idd (v 22.2.0)

### ISSUE THREAD

**Issue by eugeniorodrigues** [NREL/EnergyPlus#9679]
Issue overview
--------------
I have detected in Energy+.idd (version 22.2.0) that object Chiller:Electric:ASHRAE205 has two A21 fields and no A22.

**Comment by nealkruis** [comment]
Good catch. These fields are currently just placeholders for future expansion so hopefully it won't have any impact on simulations.

**Comment by eugeniorodrigues** [comment]
Nice! Thanks! I have developed a code that automatically parses Energy+.idd into a complete JAVA library that can be used in other software (in my case, research software). That is how I have detected it. I have manually corrected in my installation.

**Comment by Myoldmopar** [comment]
I'm a bit surprised the schema generator didn't pick this up.  Would that be an appropriate place to catch issues like this @mbadams5 ?  If not, I can work up a simple script that checks this.
