### ISSUE TITLE
Coil:Cooling:DX objects missing from Big Ladder documentation

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#9683]
Issue overview
--------------
Not sure if this is the appropriate place for this issue but don't know where else to put it.

### IO Reference PDF from [here](https://energyplus.net/assets/nrel_custom/pdfs/pdfs_v22.2.0/InputOutputReference.pdf):

![image](https://user-images.githubusercontent.com/5861765/193154804-deaf97d7-3efe-4801-9d90-f9b5cb76475f.png)

### IO Reference HTML from [here](https://bigladdersoftware.com/epx/docs/22-1/input-output-reference/):

![image](https://user-images.githubusercontent.com/5861765/193155019-4215c96e-92a2-49d5-b05d-e8fe566d8c47.png)

cc @yzhou601

**Comment by nealkruis** [comment]
The documentation is here: https://bigladdersoftware.com/epx/docs/22-1/input-output-reference/group-coil-cooling-dx.html#coilcoolingdx

We need to look into why it is not getting added to the table of contents.

**Comment by jmarrec** [comment]
Works on 24-1 https://bigladdersoftware.com/epx/docs/24-1/input-output-reference/object-index.html
