### ISSUE TITLE
Latest versions of EnergyPlus are not in the list for Federal Tax Deduction Qualified Software

### ISSUE THREAD

**Issue by luisclv** [NREL/EnergyPlus#9687]
Issue overview
--------------
With the inflation reduction act (IRA), we expect additional demand for 179D modeling services. However, the last approved version of EnergyPlus was 9.1.0. Could we get the latest versions filed and approved?

 
### Details
The list of software is [here](https://www.energy.gov/eere/buildings/qualified-software-calculating-commercial-building-tax-deductions).

**Comment by eringold** [comment]
@amirroth?

**Comment by amirroth** [comment]
I think someone is working on this. I'll find out.

**Comment by eringold** [comment]
@luisclv The Qualified Software List has been updated. https://www.energy.gov/eere/buildings/qualified-software-calculating-commercial-building-tax-deductions
