### ISSUE TITLE
Python API: callback_begin_zone_timestep_before_set_current_weather 

### ISSUE THREAD

**Issue by xixihaha1995** [NREL/EnergyPlus#9691]
Issue overview
--------------
```python
api.runtime.callback_begin_zone_timestep_before_set_current_weather(state, time_step_handlers_1.overwrite_ep_weather)
api.runtime.callback_end_system_timestep_after_hvac_reporting(state, time_step_handlers_1.get_ep_results)
```
```python
#overwrite_ep_weather()
coordination.ep_api.exchange.set_actuator_value(state, odb_actuator_handle, 35)
#get_ep_results()
oat_temp_c = coordination.ep_api.exchange.get_variable_value(state, oat_sensor_handle)
```
Is the `callback_begin_zone_timestep_before_set_current_weather` working as expected? Why `oat_temp_c` cannot be override?
@Myoldmopar 

### Details
Some additional details for this issue (if relevant):
 - Windows 11
 - Version of EnergyPlus : v22.1.0

**Comment by Myoldmopar** [comment]
@xixihaha1995 thanks for this issue, but could you provide a little more info?  It would be _really_ helpful if you could create a minimal-working-example that I can actually run on my machine to debug issues, since I don't have the classes mentioned in your code (`time_step_handlers_1`, `coordination`).

**Comment by xixihaha1995** [comment]
@Myoldmopar  Please take a look at this repo, https://github.com/xixihaha1995/xixihaha1995-EP_Where_Overwrite_Weather

**Comment by xixihaha1995** [comment]
@Myoldmopar I have debugged:
~`odb_actuator_handle = coordination.ep_api.exchange.\
            get_actuator_handle(state, "Weather Data", "Site Outdoor Drybulb Temperature", "Environment")`~
`odb_actuator_handle = coordination.ep_api.exchange.\
            get_actuator_handle(state, "Weather Data", "Outdoor Dry Bulb", "Environment")`

**Comment by xixihaha1995** [comment]
@Myoldmopar 
In terms of calling order,
can we make sure the `callback_begin_zone_timestep_before_set_current_weather` is called **before** `callback_end_system_timestep_after_hvac_reporting`?

Or can we make sure that **after** the **executation** of `callback_begin_zone_timestep_before_set_current_weather`, the  `callback_end_system_timestep_after_hvac_reporting` will start to execute?

```python
api.runtime.callback_begin_zone_timestep_before_set_current_weather(state, time_step_handlers_1.overwrite_ep_weather)
api.runtime.callback_end_system_timestep_after_hvac_reporting(state, time_step_handlers_1.get_ep_results)
```

**Comment by jmarrec** [comment]
callback_begin_zone_timestep_before_set_current_weather **is**  called before **callback_end_system_timestep_after_hvac_reporting**, by design


please read: https://bigladdersoftware.com/epx/docs/22-2/ems-application-guide/ems-calling-points.html#ems-calling-points
