### ISSUE TITLE
Kiva:Foundation uses wrong initial temperature

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#9692]
Issue overview
--------------
I'm running a building in Denver where the simulation starts Jan 1. The `Kiva:Foundation` is for a conditioned basement, so there are heating and cooling setpoints (of 68F and 78F). The outdoor temperature of the first hour is around 0F, yet Kiva is choosing the cooling setpoint (78F) as the initial temperature instead of the heating setpoint (68F). This results in unusual timeseries results for the first hours/days of the simulation.

I assume the suspicious code is [here](https://github.com/matthew-larson/EnergyPlus/blob/ed759b17eef57ce5c55f8963e4b4e209f405158e/src/EnergyPlus/HeatBalanceKivaManager.cc#L293-L303). Looks like different units (deg-C vs deg-K) might be getting compared in the conditional statements?

File: [in.idf.txt](https://github.com/NREL/EnergyPlus/files/9710144/in.idf.txt)

cc @nealkruis 

### Details
Some additional details for this issue (if relevant):
 - Windows
 - EnergyPlus 22.2
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by nealkruis** [comment]
@shorowit, you're correct. This is why everyone should perform calculations in standard SI units!
