### ISSUE TITLE
Documentation 2022b

### ISSUE THREAD

**Issue by shorowit** [NREL/EnergyPlus#9706]
Issue overview
--------------
A place to keep an ongoing list of documentation issues.

**Comment by shorowit** [comment]
- [ ] `Field: Disctrict Cooling COP` has a typo, see https://bigladdersoftware.com/epx/docs/22-2/input-output-reference/input-for-output.html#environmentalimpactfactors

**Comment by aaron-boranian** [comment]
- [ ] Units for m^3 not rendering correctly in EMS Application Guide's Table 2.7 for [Built-In Psychrometric Functions](https://bigladdersoftware.com/epx/docs/22-2/ems-application-guide/built-in-functions.html#built-in-psychrometric-functions), looks like an errant use of < sup> < /sup >. Didn't find this in other parts of the EMS Application Guide.

**Comment by yujiex** [comment]
- [ ] Equation formatting issue at the bottom of the [Sky Radiation Modelling](https://bigladdersoftware.com/epx/docs/22-1/engineering-reference/climate-calculations.html#sky-radiation-modeling) section in the engineering reference.
