### ISSUE TITLE
Output:Diagnostics:DisplayWeatherMissingDataWarnings returns false warnings

### ISSUE THREAD

**Issue by eugeniorodrigues** [NREL/EnergyPlus#9709]
Issue overview
--------------
When we add Output:Diagnostics:DisplayWeatherMissingDataWarnings; to IDF (EnergyPlus v22.2.0, macOS), EnergyPlus returns warnings for several items having less than 9 digits in the N27 Present Weather Codes fields. However, the EPW file has 9 digits for all 8760 items. See attached file.

[Archive.zip](https://github.com/NREL/EnergyPlus/files/9794966/Archive.zip)

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): 22.2.0, develop as well

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9709/1ZoneUncontrolled.idf
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I cannot reproduce with Chicago EPW and 1ZoneUncontrolled.idf adding

```
Output:Diagnostics,
  DisplayAllWarnings, !- Key 1
  DisplayExtraWarnings, !- Key 2
  DisplayWeatherMissingDataWarnings; !- Key 3
```

I have re-added the Checklist and Details sections to your original post, this is actually useful for us.

(Side note: In your TMYx, there's an extra number in the DESIGN CONDITIONS > Heating section compared to the IWEC file, I wonder why)

**Comment by jmarrec** [comment]
Ok I found why I could't reproduce with Chig epw, it's because the Present Weather Observation is 9 (unavailable). With the IWEC for Faro I can also reproduce the issue. I'll fix it.

Thanks for the report @eugeniorodrigues !
