### ISSUE TITLE
VRF Terminal Unit Supplemental Heating Coil Control

### ISSUE THREAD

**Issue by TiejunWu** [NREL/EnergyPlus#9716]
Issue overview
--------------
For a non-heat recovery VRF outdoor unit that is connected to multiple VRF Indoor Terminals, when the VRF outdoor unit is working in cooling mode. For those zones that need heating, the VRF heating coil has 0 capacity output, which is expected since the outdoor unit is non-heat recovery. However, I expected that the supplemental heating coils in the terminal unit to be turned on to maintain the zone temperature at heating setpoint. From the simulation results, I can see that the supplemental heating coils were kept off and the zone temperature fell below heating setpoint. 

@Nigusse  I see the supplemental heating coil feature was added to EnergyPlus 9.2 [#7252](https://github.com/NREL/EnergyPlus/pull/7252). Not sure if this is how the coil was intended to work. If that is the case, is there a different setting to make supplemental heating coils work in this situation?

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (22.2)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([list location of defect file here](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/DOAToVRF.idf))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
@TiejunWu The supplemental heater should be available and meet any remaining heating load whenever the main DX heating coil could not meet the total heating load of a zone. If the supplemental heating is behaving differently then it must be broken and it is a defect. Please provide a defect or an example file to look at.

**Comment by Nigusse** [comment]
@TiejunWu I ran the example file *VariableRefrigerantFlow_wSuppHeater_5Zone.idf*. I chose this example file because I have the results that I verified during addition of supplemental heaters to the VRF module. I don't see any problem in my previous and current results. See the plots below:

(1) SPACE4-1: the main DX heating coil meets the total heating requirements, thus no need for the supplemental heating coil to kick in.
(2) SPACE5-1: the main DX heating coil meets all or part of the heating requirement as the result sometimes the supplemental heating coil turns on to supply the remaining heating load.

![VRF_HP_SuppHC_Test](https://user-images.githubusercontent.com/5805126/198137026-2a025021-cbd5-4dc2-8b38-d556a2c56c42.png)

**Comment by TiejunWu** [comment]
@Nigusse Thanks for the looking into this issue. With the same example file, I was trying to create a situation that the VRF outdoor unit receives both cooling and heating request from zone terminals. So I added a heat gain to SPACE5-1 to make it call for cooling in a cold day while other zones call for heating. Here is the modified IDF file. [VariableRefrigerantFlow_FluidTCtrl_wSuppHeater_5Zone_Modified.idf](https://github.com/TiejunWu/EnergyPlus-IDF-Files/blob/master/VariableRefrigerantFlow_FluidTCtrl_wSuppHeater_5Zone_Modified.idf)
With this file, when I run simulation for a cold day. I see the following trend. 
In the early hours of the day, the VRF outdoor unit cycles between cooling and heating mode quickly.  Then from 8AM to 9PM, the outdoor unit was kept at cooling mode due to cooling call from SPACE5-1. During this period, SPACE1-1 temperature falls below heating setpoint. SPACE1-1 terminal VRF heating coil did not run because outdoor unit is in cooling mode, but its supplemental heating coil is also kept off. I was expecting the supplemental heating coil to switch on to meet the heating load.

Actually for the early hours before 8AM, If I look at the EnergyPlus detailed output at HVAC timestep, I can see that whenever the DX Heating Coil is off due to outdoor unit switched cooling mode, the supplemental heating coil is also off. So I am guessing that there is a logic that will run supplemental heating coil only when outdoor unit is in heating mode.

![image](https://user-images.githubusercontent.com/7797674/198525386-84c2f9ca-566c-4e7b-bfd8-559bbe88e6be.png)

**Comment by Nigusse** [comment]
@TiejunWu The attached defect file is html. Would you please attached the plain text idf file?

**Comment by TiejunWu** [comment]
@Nigusse I am not sure how to attach a text idf file. Can you try the "Raw" button in the html link? Just open the link in browser and then right click on the "Raw" button to "Save As" on your local disk should get you the IDF file.

![image](https://user-images.githubusercontent.com/7797674/206241061-3f56bc09-4dc1-4e57-9fde-57fbd6a50671.png)

**Comment by Nigusse** [comment]
@TiejunWu Thanks. That worked. I think it is good practice to upload defect files on [EnergyPlusDevSupport](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles).
