### ISSUE TITLE
CoolingPeakLoadType and LoadSizeType are incorrectly applied in system sizing 

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#9722]
Issue overview
--------------
Code review during an attempt to convert these parameters to enumerations shows that the global variables used to describe the type of sizing used for cooling coils and the type of load to size on, shown below, appear to be used incorrectly in code.

    // parameters for Cooling Peak Load TYpe
    constexpr int SensibleCoolingLoad(1);
    constexpr int TotalCoolingLoad(2);

    // parameters for Type of Load to Size On
    constexpr int Sensible(0);
    constexpr int Latent(1);
    constexpr int Total(2);
    constexpr int Ventilation(3);

The CoolingPeakLoadType is either TotalCoolingLoad or SensibleCoolingLoad and LoadSizeType is either Sensible, Latent, Total or Ventilation. These descriptors are used incorrectly in this example (OutputReportTabular.cc) (i.e., Ventilation is not a CoolingPeakLoadType). In this specific example it may be that the conditional should be looking at FinalSysSizing(iAirLoop).LoadSizeType since each block of the IF chooses a different design day variable.

                if (FinalSysSizing(iAirLoop).CoolingPeakLoadType == DataSizing::SensibleCoolingLoad) {
                    coolDesSelected = SysSizPeakDDNum(iAirLoop).SensCoolPeakDD;
                    if (coolDesSelected != 0) {
                        timeCoolMax = SysSizPeakDDNum(iAirLoop).TimeStepAtSensCoolPk(coolDesSelected);
                    } else {
                        timeCoolMax = 0;
                    }
                } else if (FinalSysSizing(iAirLoop).CoolingPeakLoadType == DataSizing::Ventilation) {
                    coolDesSelected = SysSizPeakDDNum(iAirLoop).CoolFlowPeakDD;
                    if (coolDesSelected != 0) {
                        timeCoolMax = SysSizPeakDDNum(iAirLoop).TimeStepAtCoolFlowPk(coolDesSelected);
                    } else {
                        timeCoolMax = 0;
                    }
                } else {
                    coolDesSelected = SysSizPeakDDNum(iAirLoop).TotCoolPeakDD;
                    if (coolDesSelected != 0) {
                        timeCoolMax = SysSizPeakDDNum(iAirLoop).TimeStepAtTotCoolPk(coolDesSelected);
                    } else {
                        timeCoolMax = 0;
                    }
                }

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by rraustad** [comment]
This is the only place in code I can find where these globals are mixed up.

**Comment by amirroth** [comment]
Now, what if these were actually different types (instead of both being `int`) so that they couldn't be mixed up? 🤷
