### ISSUE TITLE
Python API: Multithreading Multiprocessing on Windows/Linux 

### ISSUE THREAD

**Issue by xixihaha1995** [NREL/EnergyPlus#9730]
Issue overview
--------------
Hello @Myoldmopar! Based on https://github.com/Myoldmopar/EnergyPlusAPIDemos, the EnergyPlus-Python-API should be able to parallely run both in multithreading/multiprocessing.

However, I can only achieve the following:

- [x] ✅Parallel run on Ubuntu22 via multiprocessing
- [x] ✅Parallel run on Ubuntu22 via multithreading
- [x] ✅Parallel run on Windows 11 via multiprocessing
- [ ] ❌Parallel run on Windows 11 via multithreading

The minimial test repo has been hosted here, https://github.com/xixihaha1995/APIexamples/tree/thread
Related issues: https://github.com/NREL/EnergyPlus/issues/9453#issuecomment-1146081517

Thank you!

**Comment by jmarrec** [comment]
Runs fine on Windows 10, python 3.8.10. Tested 22.2.0 and 23.1.0.

Steps I took:

```
git clone git@github.com:xixihaha1995/APIexamples.git
cd APIexamples
git checkout thread
# Modify Parallel.py to point to the C:/EnergyPlusV22-2-0
python Parallel.py
```

Can you clarify what's not working exactly? @xixihaha1995

**Comment by jmarrec** [comment]
@xixihaha1995 have you tried running https://github.com/Myoldmopar/EnergyPlusAPIHelper/blob/main/energyplus_api_helpers/demos/02_threaded.py ?

**Comment by jmarrec** [comment]
Closing as stale, happy to reopen if anything new comes up.
