### ISSUE TITLE
Using actuator Unitary System DX Coil Speed Value doesn't report correctly in the latest release

### ISSUE THREAD

**Issue by yzhou601** [NREL/EnergyPlus#9732]
Issue overview
--------------
I surprisingly found that whenever an EMS program using following speed level actuator will remove the output variables: ``Output:Variable,*,Cooling Coil Crankcase Heater Electricity Rate,hourly; !- HVAC Average [W]`` and ``Output:Variable,*,Cooling Coil Crankcase Heater Electricity Energy,hourly; !- HVAC Sum [J]`` from idd file, and a warning of requesting unexpected output variables will be thrown.

EnergyManagementSystem:Actuator,
  central_ac_unitary_system_speed_override, !- Name
  central ac unitary system,              !- Actuated Component Unique Name
  Coil Speed Control,                     !- Actuated Component Type
  Unitary System DX Coil Speed Value;     !- Actuated Component Control Type

Attached are two idfs that the only difference is a dumb EMS program and the RDD files generated.
[in-noEMS.txt](https://github.com/NREL/EnergyPlus/files/9984983/in-noEMS.txt)
[in-dumbSpeedLevelActuator.txt](https://github.com/NREL/EnergyPlus/files/9984984/in-dumbSpeedLevelActuator.txt)
[in-dumbSpeedLevelActuator-rdd.txt](https://github.com/NREL/EnergyPlus/files/9984992/in-dumbSpeedLevelActuator-rdd.txt)
[in-noEMS-rdd.txt](https://github.com/NREL/EnergyPlus/files/9984993/in-noEMS-rdd.txt)

More descriptions here: [Link](https://github.com/NREL/OpenStudio-HPXML/pull/744#issuecomment-1309665978)

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows, 11)
 - Version of EnergyPlus (22.2.0)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by yzhou601** [comment]
Unfortunately the issue is more than just one variable reporting, it seems latest E+ has broken the energy reporting at both coil object level (for both delivered energy and fuel consumption reporting) and unitary system level (for fuel consumption reporting).
![image](https://user-images.githubusercontent.com/32500275/201417852-54e4e052-ae66-481c-bfa3-ea44eac8eed7.png)
This is the reporting from the dumb EMS test file where I changed the timestep to be 1min and the speed override to constant 2 (instead of 1).
I remember that in the previous testing around December 2021 (when this actuator just being wrapped up), the reporting is still correct and the EMS program works just fine, so there must be something wrong in the latest two releases that broke this feature.

**Comment by rraustad** [comment]
Is there an example file that tests this actuator?

**Comment by shorowit** [comment]
Looks like there are three:
- EMSLoadBasedMultiSpeedDXCoilOverrideControl.idf
- EMSMultiSpeedHeatPumpOverrideControl.idf
- EMSSetpointBasedMultiSpeedDXCoilOverrideControl.idf

**Comment by Myoldmopar** [comment]
When I try to debug  `in-dumbSpeedLevelActuator`, I first get a divide by zero because the number of heating speeds in the multispeed design object is set to zero in the IDF.  I tried setting that to a nonzero value and got an array out of bounds due to the heating coil node indices being zero.  I'm not sure if this is indicative of a problem with the IDF, or a problem with the EMS, or a problem with just missing error handling in E+.  @rraustad if you are able to work on this, is there anything I could do or provide to help?  If not I'll tackle the fix myself soon.

**Comment by rraustad** [comment]
@Myoldmopar I can take a look now that you have piqued my curiosity.

**Comment by rraustad** [comment]
The first crash is because these calculations assume the coils are present and that the information in the DesignSpec object is accurate. Well, the DesignSpec information is accurate to have heating speeds = 0 since there is no heating coil. I'll add more protection here.

        if (this->m_CoolCoilExists || this->m_HeatCoilExists || this->m_SuppCoilExists) {
            MSHPIndex = this->m_DesignSpecMSHPIndex;
            // set no load air flow ratio local var
            Real64 NoLoadCoolingAirFlowRateRatio = 1.0;
            Real64 NoLoadHeatingAirFlowRateRatio = 1.0;
            if (MSHPIndex > -1) {
                if (state.dataUnitarySystems->designSpecMSHP[MSHPIndex].coolingVolFlowRatio[0] == DataSizing::AutoSize) {
                    NoLoadCoolingAirFlowRateRatio =
                        min(this->m_NoLoadAirFlowRateRatio, 1.0 / double(state.dataUnitarySystems->designSpecMSHP[MSHPIndex].numOfSpeedCooling));
                } else {
                    NoLoadCoolingAirFlowRateRatio =
                        min(this->m_NoLoadAirFlowRateRatio, state.dataUnitarySystems->designSpecMSHP[MSHPIndex].coolingVolFlowRatio[0]);
                }
                if (state.dataUnitarySystems->designSpecMSHP[MSHPIndex].heatingVolFlowRatio[0] == DataSizing::AutoSize) {
                    NoLoadHeatingAirFlowRateRatio =
                        min(this->m_NoLoadAirFlowRateRatio, 1.0 / double(state.dataUnitarySystems->designSpecMSHP[MSHPIndex].numOfSpeedHeating));
                } else {
                    NoLoadHeatingAirFlowRateRatio =
                        min(this->m_NoLoadAirFlowRateRatio, state.dataUnitarySystems->designSpecMSHP[MSHPIndex].heatingVolFlowRatio[0]);
                }

And this crash in this equation also assumes both coils are present (heating coil is not present). This equation appears to calculate the system sensible cooling capacity with respect to the zone condition, and then subtracts the heating coil delta T. This calculation is made regardless if the cooling coil is on or if either coil is present. I am admittedly confused as to what is being calculated here other than the fact the the IF block below says it's the reheat coil load. I'll split this calculation up.

        Real64 CoolingOnlySensibleOutput =
            state.dataLoopNodes->Node(this->CoolCoilInletNodeNum).MassFlowRate * CpAir *
            ((state.dataLoopNodes->Node(this->NodeNumOfControlledZone).Temp - state.dataLoopNodes->Node(this->CoolCoilOutletNodeNum).Temp) -
             (state.dataLoopNodes->Node(this->HeatCoilOutletNodeNum).Temp - state.dataLoopNodes->Node(this->HeatCoilInletNodeNum).Temp));
        if (state.dataUnitarySystems->QToHeatSetPt < 0.0) {
            //   Calculate the reheat coil load wrt the heating setpoint temperature. Reheat coil picks up
            //   the entire excess sensible cooling (DX cooling coil and impact of outdoor air).
            this->m_DehumidInducedHeatingDemandRate = max(0.0, (CoolingOnlySensibleOutput + state.dataUnitarySystems->QToHeatSetPt));
            //   Heating mode and dehumidification is required
        } else if (state.dataUnitarySystems->QToHeatSetPt >= 0.0) {
            //   Calculate the reheat coil load as the sensible capacity of the DX cooling coil only. Let
            //   the heating coil pick up the load due to outdoor air.
            this->m_DehumidInducedHeatingDemandRate = max(0.0, CoolingOnlySensibleOutput);
        }

Defect file runs now so I can move on to the issue.
