### ISSUE TITLE
Autosized source-side air flow rate for air-source HeatPump:PlantLoop:EIR:* object is negative

### ISSUE THREAD

**Issue by lymereJ** [NREL/EnergyPlus#9733]
Issue overview
--------------
The autosized source-side air flow rate of air-source `HeatPump:PlantLoop:EIR:*` objects is negative. Here's an excerpt of simulation outputs that shows that the air flow rate is negative (about -15 kg/s):

![image](https://user-images.githubusercontent.com/5149279/200971993-bc4c68ac-c167-48da-b5f0-77603f182bf0.png)

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10
 - Version of EnergyPlus: tested 22.1 and 22.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [defect_model.zip](https://github.com/NREL/EnergyPlus/files/9976176/defect_model.zip)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Possibly same as #8948?

**Comment by lymereJ** [comment]
Sure looks like it. I'll run the defect file from #8948 through #9734 to see where it stands.

**Comment by lymereJ** [comment]
I don't think it's the same, I left a comment on the other thread.
