### ISSUE TITLE
v22.2 IDF Version Updater fails to recognize some forms of complex version numbers

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9737]
Issue overview
--------------
The IDF version updater program fails to recognize some complex version number, such as "8.9.0.001"---which is commonly seen in DesignBuilder edited files. When opening an IDF that contains "Version, 8.9.0.001;", the IDF Version Updater will show the following error messages and failed to update:
<img width="601" alt="image" src="https://user-images.githubusercontent.com/64040111/201710638-5f785b08-83fa-4eb9-a5f4-bfa4ef4551c3.png">

A temporary workaround is to revise simplify the version number---e.g. change "8.9.0.001" to "8.9". The v22.2 IDF Version Updater will then work properly.

Previous versions (e.g. v22.1) recognize the more complex form (e.g. "8.9.0.001") without problems. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Possibly All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v22.2
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
@Myoldmopar @JasonGlazer Please check if the new python-based version updater has the same issue.

**Comment by Myoldmopar** [comment]
Works fine on the new Python tool.  I modified a 9.6 file to 9.6.0.001 and ran it up to 22.2.  At the 22.1 stage it has a simple 22.1 version ID and then the expected 22.2 in the final file.
