### ISSUE TITLE
ZoneHVAC:Baseboard:RadiantConvective:Water problem unless unless the proportion of radiant energy falling on people is 0.3

### ISSUE THREAD

**Issue by NicolaTerry** [NREL/EnergyPlus#9742]
Issue overview
--------------
Since version 9.5, using ZoneHVAC:Baseboard:RadiantConvective:Water, the proportion of radiant heat falling on people is set in ZoneHVAC:Baseboard:RadiantConvective:Water:Design object  while the proportion of radiant heat falling on surfaces is set in the zone baseboard object. Regression tests with earlier versions indicate incompatible results unless the proportion on people is 0.3 (as in the examples).  In my test (attached) at 8.9, reducing the people proportion  from 0.3 to 0.1 increases gas use by 1%. At 22.2  the same change reduces gas use by 15%. 

### Details
This is probably not relevant
 - MacOS 12.6
 - First appears in 9.5, when the design object was split out. I have been using 22.2

### Checklist
Two files attached which I have used to demonstrate the issue. cube-8.9.imf and cube-22.2.imf. The latter was generated by converting the former. They both have a macro set at the top for radiantPropOnPeople. Set this is 0.3 for compatible results, something else e.g. 0.1 to show the problem.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)
[bug.zip](https://github.com/NREL/EnergyPlus/files/10031091/bug.zip)

**Comment by RKStrand** [comment]
@NicolaTerry I have identified the problem and will fix this.  After the fix, the difference between the 0.1 and 0.3 is back to what it was before (1% increase in gas usage when the value is set to 0.1).
