### ISSUE TITLE
Shadow export csv file contains an extra heading field that causes importing back crashing

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9753]
Issue overview
--------------
It was discovered that (at least in some scenarios?) that the shadow calculation export .csv file will/could produce an extra ",()" field at the end of the first line (the headings line): 
<img width="288" alt="image" src="https://user-images.githubusercontent.com/64040111/203640403-f98f9d1b-4749-4a28-ba09-2648dbe45162.png">

This will cause EnergyPlus to crash when importing this .csv file back using the "imported" shading calculation method. The processing code will encounter some out of bound error when reading the column and causing a crash.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): Windows, possibly all.
 - Version of EnergyPlus (if using an intermediate build, include SHA): v9.6 to v22.2
 - Helpdesk ticket number: discovered while investigating Helpdesk Ticket 16292.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file [here](https://github.com/NREL/EnergyPlusDevSupport/tree/master/DefectFiles/9000s/9753))
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
@jcyuan2020 Could you upload the defect file please?

**Comment by jcyuan2020** [comment]
> @jcyuan2020 Could you upload the defect file please?

The original defect files are uploaded. Also, this issue should be a general one in that any example file probably can serve as a defect file.

**Comment by jmarrec** [comment]
@jcyuan2020 thanks for uploading. And right, I did realize by looking at the code that it happens all the time.
