### ISSUE TITLE
Reduce minimum ambient temperature for HPWH operation

### ISSUE THREAD

**Issue by jmaguire1** [NREL/EnergyPlus#9758]
Issue overview
--------------
When modeling HPWHs, E+ only allows the minimum temperature for HP operation to go as low as -5 C. This limit seems to be hard coded into the water heater code (see https://github.com/NREL/EnergyPlus/blob/0b1a165e0aa6b1f9fc88991c987673fdcd366dad/src/EnergyPlus/WaterThermalTanks.cc#L1537-L1544), so there doesn't seem to be any way to work around this. There are several products on the market that can operate at much lower temperatures than -5 C, such as the SanCO2 which can operate below -30 C (https://www.eco2waterheater.com/_files/ugd/e88920_293f399a2a3a432396b1805a76f21c80.pdf). To be able to properly model these products, we'd need to lower this limit. My suggestion would be to set this to at least -40 C for products like the SanCO2. It'd also be nice to move this lower limit to the .idd rather than hard coding in the event that someone needs to lower this further for some new product with an even broader operating range.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by shorowit** [comment]
The limit should be removed altogether; this was the approach taken for HVAC heating systems (see https://github.com/NREL/EnergyPlus/pull/6213 for example).
