### ISSUE TITLE
Incorrect spelling of "Oputput:Table:Annual" to be corrected to "Output:Table:Annual"

### ISSUE THREAD

**Issue by CarlosOchoaIERC** [NREL/EnergyPlus#9760]
Hi,
There is a spelling error in the code that relates to a "Oputput:Table:Annual" in [src/EnergyPlus/OutputReportTabularAnnual.cc](https://github.com/NREL/EnergyPlus/blob/de5b76fcb67d332838150389af1e6a17c8d1eee8/src/EnergyPlus/OutputReportTabularAnnual.cc)  lines 131 and 132. 

This makes EnergyPlus return a fatal error even if there is an Output:Table:Annual with all the fields completed.

![image](https://user-images.githubusercontent.com/119873877/205669070-23a3d270-9230-4059-947c-448d2507fc53.png)

### Checklist

Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
Thanks for the report. It's just a typo in the error message which I'll correct, but it does not make E+ throw unnecessarily.

**Comment by jmarrec** [comment]
If you have a file with zero blank fields in your Output:Table:Annual object that is throwing this warning, please provide it so I can reproduce @CarlosOchoaIERC
