### ISSUE TITLE
Confusion about installation folders

### ISSUE THREAD

**Issue by simonsays1980** [NREL/EnergyPlus#9762]
When building EnergyPlus (v22-1-0) on my Linux System (Fedora 37), I construct the CMake file with: 

```
ccmake -DLINK_WITH_PYTHON:BOOL=ON -DPython_ROOT_DIR:PATH=/home/simon/.pyenv/versions/3.9.0/ -DPython_REQUIRED_VERSION:STRING=3.9.0 -DCMAKE_INSTALL_PREFIX=/usr/local/EnergyPlus-22-1-0 -DCMAKE_CXX_FLAGS="-Wno-error=uninitialized -march=native" -DBUILD_FORTRAN:BOOL=ON ~/Downloads/EnergyPlus-22.1.0
```
and build the binaries with `make -j 4`. I install then with `sudo make install`. In the installed folder `/usr/local/EnergyPlus-22-1-0`  I find: 

```
drwxr-xr-x. 1 root root      336  5. Dez 18:35 .
drwxr-xr-x. 1 root root      124  5. Dez 18:23 ..
lrwxrwxrwx. 1 root root       25  5. Dez 18:23 ConvertInputFormat -> ConvertInputFormat-22.1.0
-rwxr-xr-x. 1 root root  5919760  5. Dez 18:34 ConvertInputFormat-22.1.0
lrwxrwxrwx. 1 root root       17  5. Dez 18:23 energyplus -> energyplus-22.1.0
-rwxr-xr-x. 1 root root    25384  5. Dez 18:35 energyplus-22.1.0
-rwxr-xr-x. 1 root root  3598768  5. Dez 17:33 ExpandObjects
lrwxrwxrwx. 1 root root       26  5. Dez 18:23 libenergyplusapi.so -> libenergyplusapi.so.22.1.0
-rwxr-xr-x. 1 root root 69894288  5. Dez 18:35 libenergyplusapi.so.22.1.0
-rwxr-xr-x. 1 root root 14518128  5. Dez 18:35 libpython3.9.so.1.0
drwxr-xr-x. 1 root root      108  5. Dez 18:23 PostProcess
drwxr-xr-x. 1 root root      152  5. Dez 18:23 PreProcess
```

However, what is missing are other assets from the Product folder like for example `v22-1-0-Energy+.idd` or the `pyenergplus` folder. 

If I throw away the build folder this is gone. Is there anything I have forgotten? Or are their any best practices how to keep these artifacts? Just copying would duplicate many of them in the install folder.

Any help appreciated. 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
use `CPACK_BINARY_TGZ:BOOL=ON`, then `make -j$(nproc) package`, and install that tar.gz?

**Comment by jmarrec** [comment]
@simonsays1980 I'm closing this one as I already answered it, but feel free to drop another message if you need clarifications
