### ISSUE TITLE
Unitary system doesn't enforce no-load air flow rate

### ISSUE THREAD

**Issue by lymereJ** [NREL/EnergyPlus#9767]
Issue overview
--------------
While working on #6109, I noticed that the `UnitarySystem_MultiSpeedDX.idf` example file (simulated in Seattle) shows that the unitary system doesn't seem to enforce the no-load air flow rate. On the figure below we can see that at the end of each day (the x-axis labels are incorrect, results for two days are shown) both the heating and cooling coils are off, and the outdoor air flow rate is at it's minimum but the mixed air flow rate is about 0.2 m3/s which corresponds to the system's highest speed flow rate according to the EIO file.

![image](https://user-images.githubusercontent.com/5149279/207122994-91cf1a28-fa85-4c8d-bf3c-c588cd2473df.png)

```
Component Sizing Information, Controller:OutdoorAir, SYS 2 FURNACE DX COOL OA CONTROLLER, Minimum Outdoor Air Flow Rate [m3/s], 4.72000E-002
Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size Heating Supply Air Flow Rate [m3/s], 0.20087
Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size Cooling Supply Air Flow Rate [m3/s], 0.20087
Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size No Load Supply Air Flow Rate [m3/s], 6.69578E-002
Component Sizing Information, Coil:Cooling:DX:CurveFit:Speed, SYS 2 FURNACE DX COOL COOLING COIL SPEED 1 PERFORMANCE, User-Specified Rated Air Flow Rate [m3/s], 6.69511E-002
Component Sizing Information, Coil:Cooling:DX:CurveFit:Speed, SYS 2 FURNACE DX COOL COOLING COIL SPEED 2 PERFORMANCE, User-Specified Rated Air Flow Rate [m3/s], 0.13392
Component Sizing Information, Coil:Cooling:DX:CurveFit:Speed, SYS 2 FURNACE DX COOL COOLING COIL SPEED 3 PERFORMANCE, User-Specified Rated Air Flow Rate [m3/s], 0.20087
```

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows 10
 - Version of EnergyPlus: 22.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by lymereJ** [comment]
This [file](https://github.com/NREL/EnergyPlus/files/10210939/file.zip) also uses a unitary system and when run with EnergyPlus 22.2 the no-load air flow seem to be enforced (e.g., around "Jan 22" on the x-axis, same comment as above for the x-axis). The two files use different types of coils, perhaps that's a clue, maybe not.

![image](https://user-images.githubusercontent.com/5149279/207125486-9cad3c82-9766-4ab6-ab99-1d651ba6ae4a.png)

```
Component Sizing Information, AirLoopHVAC:UnitarySystem, PSZ-AC:2_UNITARY_PACKAGE_DX, Design Size Heating Supply Air Flow Rate [m3/s], 6.40334
Component Sizing Information, AirLoopHVAC:UnitarySystem, PSZ-AC:2_UNITARY_PACKAGE_DX, Design Size Cooling Supply Air Flow Rate [m3/s], 6.40334
Component Sizing Information, AirLoopHVAC:UnitarySystem, PSZ-AC:2_UNITARY_PACKAGE_DX, Design Size No Load Supply Air Flow Rate [m3/s], 4.22621
```

**Comment by lymereJ** [comment]
As mentioned [here](https://github.com/NREL/EnergyPlus/issues/9747#issuecomment-1320625364), hard coding a value, 0.33 for this case does the trick. So it seems that the reporting to the EIO file might be incorrect.

It currently shows ...
```
Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size No Load Supply Air Flow Rate [m3/s], 6.69578E-002
```

... but it should be:
```
Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size No Load Supply Air Flow Rate [m3/s], 0.20087
```

**Comment by Nigusse** [comment]
@lymereJ are you working on it? I will work on it if you are not.

**Comment by lymereJ** [comment]
@Nigusse - I have not looked at it yet. Please, feel free to work on it. Thanks!

**Comment by Nigusse** [comment]
I ran the defect file for Seattle weather and reviewed the results. It appears the Unitary System `Design Size No Load Supply Air Flow Rate [m3/s]` is calculated and report correctly to the `EIO` file. Take a look, an output when the field `No Load Supply Air Flow Rate Ratio` in `UnitarySystemPerformance:Multispeed` object is correctly specified. In this case, I specified `0.3333`. The `Design Size No Load Supply Air Flow Rate [m3/s]`  reported in the EIO file is consistent with this ratio as shown below.

```
 Component Sizing Information, Controller:OutdoorAir, SYS 2 FURNACE DX COOL OA CONTROLLER, Maximum Outdoor Air Flow Rate [m3/s], 0.20087
 Component Sizing Information, Controller:OutdoorAir, SYS 2 FURNACE DX COOL OA CONTROLLER, Minimum Outdoor Air Flow Rate [m3/s], 4.72000E-002
 Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size Supply Air Flow Rate [m3/s], 0.20087
 Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size Heating Supply Air Flow Rate [m3/s], 0.20087
 Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size Cooling Supply Air Flow Rate [m3/s], 0.20087
 Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size No Load Supply Air Flow Rate [m3/s], 6.69578E-002
```
Again, I tested, with the field `No Load Supply Air Flow Rate Ratio` left blank in the  `UnitarySystemPerformance:Multispeed` object, which defaults to 1.0. The `Design Size No Load Supply Air Flow Rate [m3/s]` reported in the EIO file is the same as the cooling coil minimum speed air flow rate as shown below.

```
 Component Sizing Information, Controller:OutdoorAir, SYS 2 FURNACE DX COOL OA CONTROLLER, Maximum Outdoor Air Flow Rate [m3/s], 0.20087
 Component Sizing Information, Controller:OutdoorAir, SYS 2 FURNACE DX COOL OA CONTROLLER, Minimum Outdoor Air Flow Rate [m3/s], 4.72000E-002
 Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size Supply Air Flow Rate [m3/s], 0.20087
 Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size Heating Supply Air Flow Rate [m3/s], 0.20087
 Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size Cooling Supply Air Flow Rate [m3/s], 0.20087
 Component Sizing Information, AirLoopHVAC:UnitarySystem, SYS 2 FURNACE DX COOL UNITARY SYSTEM, Design Size No Load Supply Air Flow Rate [m3/s], 6.69578E-002
```

So, `No Load Supply Air Flow Rate Ratio` specified in the in `UnitarySystemPerformance:Multispeed` object determines the `Design Size No Load Supply Air Flow Rate [m3/s]` reported to the EIO file. But when the field is left blank `Design Size No Load Supply Air Flow Rate [m3/s]` that corresponds to the lowest speed level is reported. 

However, the actual `No Load Supply Air Flow Rate` used during simulation are not the same when a fraction is specified and when the field is left blank. 

(1) When a fraction is specified, the simulation uses flow rate consistent with the `No Load Supply Air Flow Rate` when there are no heating and cooling loads. 
(2) When the field is blank, `No Load Supply Air Flow Rate` reported is the minimum flow rate expected based on the coils minimum speed level but what is actually used in the simulation is the full load flow rate, which is consistent with the default value of 1 for `No Load Supply Air Flow Rate Ratio` field.

**Comment by Nigusse** [comment]
Sample result when the `No Load Supply Air Flow Rate Ratio` field is left blank. IN this case the unitary system is using the full flow rate even when there are NO cooling and heating loads. Note that the `Design Size No Load Supply Air Flow Rate [m3/s]` reported to the EIO file is the minimum speed level flow rate. So, the operational flow rate is not consistent with the flow rate reported to the eio file.


![NoLoadFlowRateRatio_DefaultTest-1](https://user-images.githubusercontent.com/5805126/216706343-b4bcf6d7-c763-419e-95a8-36110fb39781.png)

**Comment by Nigusse** [comment]
On the other hand, when a fraction is specified in the `No Load Supply Air Flow Rate Ratio` field, the simulation uses flow rate consistent with the `No Load Supply Air Flow Rate` when there are no heating and cooling loads. See sample result below:

![NoLoadFlowRateRatio_0 3333RatioTest-1](https://user-images.githubusercontent.com/5805126/216707457-3f7088f6-70a6-4c1b-8890-392131538484.png)

**Comment by Nigusse** [comment]
Again tested at a fraction (0.200) lower than the minimum speed level ratio (0.3333), showed that the system runs using the `No Load Supply Air Flow Rate` consistent with the `No Load Supply Air Flow Rate Ratio` specified as shown below:

![NoLoadFlowRateRatio_0 2000RatioTest-1](https://user-images.githubusercontent.com/5805126/216710336-7fe9cc6e-2460-403c-a2e8-8f433492b4b0.png)

**Comment by Nigusse** [comment]
The problem I am seeing is a reporting problem. When the `No Load Supply Air Flow Rate Ratio` field is blank, which default to `1.0`, the system operates at full flow when there is NO load but the `No Load Supply Air Flow Rate' reported to EIO corresponds to the minimum speed level flow rate specified.

**Comment by rraustad** [comment]
In #9761 there was a change in setAverageAirFlow for multispeed coils. Maybe that change also corrects this?

**Comment by lymereJ** [comment]
> The problem I am seeing is a reporting problem. When the `No Load Supply Air Flow Rate Ratio` field is blank, which default to `1.0`, the system operates at full flow when there is NO load but the `No Load Supply Air Flow Rate' reported corresponds to the minimum speed level flow rate specified.

I agree, that is in line with my comment above (and shown below).

> As mentioned [here](https://github.com/NREL/EnergyPlus/issues/9747#issuecomment-1320625364), hard coding a value, 0.33 for this case does the trick. So it seems that the reporting to the EIO file might be incorrect.

**Comment by Nigusse** [comment]
@lymereJ Yes, I confirmed what you thought the problem is.
