### ISSUE TITLE
A possibly inconsistent corner case for WaterUse:Equipment when target water temperature schedule is left blank

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9777]
Issue overview
--------------
It was reported by a user that there could be some inconsistency between v22.1 and v22.2 on the treatment a blank “Target temperature” input field in WaterUse:Equipment. In the old v22.1 EnergyPlus program, (and also stated so in the v22.2 IORef documentation), the default treatment for a blank “target temperature schedule” is to use the hot water schedule instead. However, in the actual v22.2 EnergyPlus program, this is not the case---the user’s observation via a few experiments showed that the related “Water Use Equipment Heating Energy” will be zero---which seems unreasonable if the blank “target temperature schedule” is indeed defaults to the “hot water schedule” temperature. While in previous version (e.g. v22.1) this Energy value is non-zero, which sounds a more consistent reasonable with the stated assumption about the default treatment (of using “hot water scheduled temperature” when the “target temperature schedule” is left blank).

After some digging in the code (and also reading some of the comment lines), it was found that in the v22.2 code, the default treatment could be different: the “target water schedule temperature” if left blank, will now actually default to the “cold water scheduled” temperature instead (different from what is stated in the v22.2 IORef): 
https://github.com/NREL/EnergyPlus/blob/2d609ecfefd7afe1eb4e8b416f16fe4fc1e1e8e7/src/EnergyPlus/WaterUse.cc#L587-L591

However, in the code, there are also places that still trying to stick to the older convention (using hotwater temperature, for example here: 
https://github.com/NREL/EnergyPlus/blob/2d609ecfefd7afe1eb4e8b416f16fe4fc1e1e8e7/src/EnergyPlus/WaterUse.cc#L1055-L1057
Actually in order for this logic here to work out:
https://github.com/NREL/EnergyPlus/blob/2d609ecfefd7afe1eb4e8b416f16fe4fc1e1e8e7/src/EnergyPlus/WaterUse.cc#L1211-L1215
The place in L1055-L1057 above should use cold water temperature instead for the blank target schedule scenario.

This might need to be addressed, one way or the other---either (Option 1) make it all consistent with older version treatment; or (Option 2) make some revisions in a couple of places in the code and the IORef document to clearly support/state the new way of treating this.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v22.2
 - Related helpdesk ticket number: 16314

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
See https://github.com/NREL/EnergyPlus/pull/9661

**Comment by jcyuan2020** [comment]
@mjwitte Thanks! Yes, the analysis posted is based on reading the code changes related to #9661. A quick proposed code change for Option 2 will be posted soon.

**Comment by rraustad** [comment]
I do recall questioning the logic you show in the description at lines 587 - 590. I was not sure if this logic covered all cases. Also from #9661 was the fact that the outlet water temp provided by the model did not have sufficient logic to provide the correct outlet water temp (I don't recall the details). Is this issue a result of no hot water heating energy? or does the water temp not follow the expected behavior? If the user expects hot water energy while the water temps show otherwise I think this may be a simple matter of model understanding. I am not saying there is no need for improvement to logic, just being cautious.

**Comment by jcyuan2020** [comment]
Thanks! Yes, this issue a result of no hot water heating energy---which is different from the previous version logic (so the previous version <=22.1 will yield positive energy usage which seems more expected). I think after examining the code my conclusion is  that this default logic is changed in v22.2 (or in PR9661) for the no-target-water-temperature case based on both the comments and code lines Line 587-590, and Lines 1212-1214). Then following this logic, the code in Line 1056 should use the "cold water" temperature, and the IORef needs some revisions to state the change (this is considered the "Option 2" way of change).
