### ISSUE TITLE
Blank epJSON inputs needed for ZoneHVAC:EquipmentList

### ISSUE THREAD

**Issue by lymereJ** [NREL/EnergyPlus#9780]
Issue overview
--------------
Blank inputs in `ZoneHVAC:EquipmentList` objects are needed when using the epJSON format for EnergyPlus to run. For example the following object won't run...

```
"Kitchen_ZN_1_FLR_1 Equipment": {
    "equipment": [
        {
            "zone_equipment_cooling_sequence": 1,
            "zone_equipment_heating_or_no_load_sequence": 1,
            "zone_equipment_name": "Kitchen_ZN_1_FLR_1 Exhaust Fan",
            "zone_equipment_object_type": "Fan:ZoneExhaust"
        },
        {
            "zone_equipment_cooling_sequence": 2,
            "zone_equipment_heating_or_no_load_sequence": 2,
            "zone_equipment_name": "Kitchen_ZN_1_FLR_1 DOAS ADU",
            "zone_equipment_object_type": "ZoneHVAC:AirDistributionUnit"
        },
        {
            "zone_equipment_cooling_sequence": 3,
            "zone_equipment_heating_or_no_load_sequence": 3,
            "zone_equipment_name": "Kitchen_ZN_1_FLR_1 PSZ ADU",
            "zone_equipment_object_type": "ZoneHVAC:AirDistributionUnit"
        }
    ],
    "load_distribution_scheme": "SequentialLoad"
},
```
It triggers the following fatal error:
```
** Severe  ** AirLoopHVAC:UnitarySystem "PSZ-AC_1:6_UNITARY_PACKAGE_DX": Airloop air terminal in the zone equipment list for zone = KITCHEN_ZN_1_FLR_1 not found or is not allowed Zone Equipment Cooling or Heating Sequence = 0.
**  Fatal  ** Subroutine InitLoadBasedControl: Errors found in getting AirLoopHVAC:UnitarySystem input.  Preceding condition(s) causes termination.
```

... But this one will:

```
"Kitchen_ZN_1_FLR_1 Equipment": {
    "equipment": [
        {
            "zone_equipment_cooling_sequence": 1,
            "zone_equipment_heating_or_no_load_sequence": 1,
            "zone_equipment_name": "Kitchen_ZN_1_FLR_1 Exhaust Fan",
            "zone_equipment_object_type": "Fan:ZoneExhaust",
            "zone_equipment_sequential_cooling_fraction_schedule_name": "",
            "zone_equipment_sequential_heating_fraction_schedule_name": ""
        },
        {
            "zone_equipment_cooling_sequence": 2,
            "zone_equipment_heating_or_no_load_sequence": 2,
            "zone_equipment_name": "Kitchen_ZN_1_FLR_1 DOAS ADU",
            "zone_equipment_object_type": "ZoneHVAC:AirDistributionUnit",
            "zone_equipment_sequential_cooling_fraction_schedule_name": "",
            "zone_equipment_sequential_heating_fraction_schedule_name": ""
        },
        {
            "zone_equipment_cooling_sequence": 3,
            "zone_equipment_heating_or_no_load_sequence": 3,
            "zone_equipment_name": "Kitchen_ZN_1_FLR_1 PSZ ADU",
            "zone_equipment_object_type": "ZoneHVAC:AirDistributionUnit",
            "zone_equipment_sequential_cooling_fraction_schedule_name": "",
            "zone_equipment_sequential_heating_fraction_schedule_name": ""
        }
    ],
    "load_distribution_scheme": "SequentialLoad"
},
```

Potential issue with the code
--------------

https://github.com/NREL/EnergyPlus/blob/9d3aa044dcc996805bdb6d34be2ede9a501aac93/src/EnergyPlus/DataZoneEquipment.cc#L422-L441

- In the first case `NumAlphas = 10` so `numEquipCount = 2` and `thisZoneEquipList.NumOfEquipTypes = 2` meaning that the second ADU is not recognized, this creates issues downstream where the air terminal is not found.
- In the second case `NumAlphas = 14` so `numEquipCount = 3` and `thisZoneEquipList.NumOfEquipTypes = 3`. The simulation proceeds.

### Details
Some additional details for this issue (if relevant):
 - Platform: Windows
 - Version of EnergyPlus: 22.1 and 22.2

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: [defect_workaround_files.zip](https://github.com/NREL/EnergyPlus/files/10340610/defect_workaround_files.zip) the file including the "_mod" suffix includes the workaround so the file can be simulated
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I have reproduced this issue with current develop after transitioning the provided files (convert epJSON to IDF, transition the IDF, convert IDF to epJSON)
