### ISSUE TITLE
UnitarySystem Setpoint control issues

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#9793]
Issue overview
--------------
1. User file has AirloopHVAC:UnitarySystem with Setpoint control and Coil:Cooling/Heating:WaterToAirHeatPump:EquationFit. The cooling coils do not operate. Eventually stumbled across [these changes](https://github.com/NREL/EnergyPlus/commit/e3a249bccbfbc89f1d816a968e5be119108d7827#diff-a4469a58b3b57ae5c4916cb9efb12f0c6ef79224175d09c796a7f6c2e1d3ec33R11606-R11616) in https://github.com/NREL/EnergyPlus/commit/e3a249bccbfbc89f1d816a968e5be119108d7827 (part of #8729, v9.6).

These lines were added:
```
                Real64 NoOutput = 0.0; // CoilSystem:Cooling:DX
                Real64 ReqOutput = 0.0;
                FullOutput = 0.0;
                if (this->m_sysType == SysType::CoilCoolingDX) {
                    NoOutput = state.dataLoopNodes->Node(InletNode).MassFlowRate *
                               (Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(OutletNode).Temp, state.dataLoopNodes->Node(OutletNode).HumRat) -
                                Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(InletNode).Temp, state.dataLoopNodes->Node(OutletNode).HumRat));
                    ReqOutput = state.dataLoopNodes->Node(InletNode).MassFlowRate *
                                (Psychrometrics::PsyHFnTdbW(DesOutTemp, state.dataLoopNodes->Node(OutletNode).HumRat) -
                                 Psychrometrics::PsyHFnTdbW(state.dataLoopNodes->Node(InletNode).Temp, state.dataLoopNodes->Node(OutletNode).HumRat));
                }
```
`ReqOutput` is being redefined here and stomping on the value calculated back up in line 12411 of UnitarySystem.cc This breaks what appears to be the FullOutput pass for coil types `Coil_CoolingWaterToAirHPSimple` and `Coil_CoolingWaterToAirHP`, because these two coil types use `ReqOutput` as a parameter to the coil simulation function. The other coil types use some other variables such as the part load frac, so they are still working (not really confirmed, but assumed).

I think technically it's defining a new `ReqOutput` in a tighter scope which is supposedly legal code, but really bad, because any use of `ReqOutput` in the tighter scope uses the new one instead of the original. If there's a way to get the compilers to yell about this, that would be great (because this is the second bug introduced by the same problem).

I've started on a tentative fix locally. Just commented out the `Real64 ReqOutput = 0.0;` on line 12652.

2. UnitarySystem with Setpoint control and Coil;Heating:Electric as the supplemental heating coil generates this fatal error, but a control node input isn't supposed to be required when the coil is wrapped in a UnitarySystem.
```
   ** Severe  ** Coil:Heating:Electric "ELEC HTG COIL 13"
   **   ~~~   ** ... Missing control node for heating coil.
   **   ~~~   ** ... enter a control node name in the coil temperature setpoint node field for this heating coil.
   **   ~~~   ** ... use a Setpoint Manager to establish a setpoint at the coil temperature setpoint node.
   **  Fatal  ** ... errors found in heating coil input.
```

*WAHP companion coil sizing issue moved from here to #9849*

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus v22.2 (also v22.1 and v9.6 ~v9.5~).
 - [Unmethours 86434](https://unmethours.com/question/86434/unitary-system-water-air-cc-control-issues/)
 - Helpdesk tickets 16321 and 16322.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added to EnergyPlusDevSupport\DefectFiles
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Correction - the breaking change was in v9.6 (not 9.5).

**Comment by rraustad** [comment]
Well that's just wrong. Who did that! If we only had an example file that covered all the possible configurations.

                Real64 NoOutput = 0.0; // CoilSystem:Cooling:DX
                Real64 ReqOutput = 0.0;
                Real64 FullOutput = 0.0;

**Comment by rraustad** [comment]
The controlCoolingSystemToSP function uses a calculated load to control, or actually choose to control, to a coil outlet T or w. Calculating a load is a carry over from load based control logic. What should happen here is to remove all reference to load and control only to T and w. Lots of diffs but the coil outlet will either be at set point or not (which would then be fixed), so proving controllability should not be that hard but will be a little time consuming to cover all cases.

**Comment by mjwitte** [comment]
And yet another issue: One of the defect files,  9793-in-v22.2.idf, has a supp heat coil hard-sized to zero which results in a divide by zero in line 15056 in `contrlSuppheatSystemToSP`
```
                    if (this->m_NumOfSpeedSuppHeating <= 1) {
                        this->m_SuppHeatPartLoadFrac = SupHeaterLoad / this->m_DesignSuppHeatingCapacity;
```
