### ISSUE TITLE
Chillers IPLV calculation issue and missing warning when the curves limit are outside the AHRI test condition

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#9829]
Issue overview
--------------
Standard ratings calculations provide warning error message when the AHRI test conditions are outside the user specified upper or lower curve limits of the independent variables. `AirCooled` and `EvaporativelyCooled` chillers don't provide such warning for condenser entering air temperature lower curve limits. Found this issue when investigating a user request in a related issue. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (develop, https://github.com/NREL/EnergyPlus/commit/4a7322f8f2005215913c795504b4da46b5937086)
 - email communications with user

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
The capacity and EIR function of temperature curves for air cooled electric chiller from the user file are shown below to describe the issue. The lower temperature limit for condenser entering air temperature is `24.0` C. The 50% and 25% chiller loading condenser entering air temperatures for `AirCooled` chillers AHRI Std 550/590 test points are `18.3`C and `12.8`C, respectively. EnergyPlus does the IPLV calculation silently without providing any warning error message when the curve bound doesn't include the standard test conditions.

```
  Curve:Biquadratic,
    Air-cooled Cent Cap F(T),!- Name
    0.282511,                !- Coefficient1 Constant
    ...
    5,                       !- Minimum Value of x
    10,                      !- Maximum Value of x
    24,                      !- Minimum Value of y
    40;                      !- Maximum Value of y

  Curve:Biquadratic,
    Air-cooled Cent EIR F(T),!- Name
    0.817247,                !- Coefficient1 Constant
    ...
    5,                       !- Minimum Value of x
    10,                      !- Maximum Value of x
    24,                      !- Minimum Value of y
    35;                      !- Maximum Value of y
```

See the code snippet below. The condenser entering air lower temperature limits for `AirCooled` and `EvaporativelyCooled` chillers are set at the high temperature limit value [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/StandardRatings.cc#L815-L824).

```        
       if (CondenserType == DataPlant::CondenserType::WaterCooled) {
            HighCondenserEnteringTempLimit = HighEWTemp;
            LowCondenserEnteringTempLimit = LowEWTemp;
        } else if (CondenserType == DataPlant::CondenserType::AirCooled) {
            HighCondenserEnteringTempLimit = OAHighEDBTemp;
            LowCondenserEnteringTempLimit = OAHighEDBTemp;
        } else { // Evaporatively Cooled Condenser
            HighCondenserEnteringTempLimit = OAHighEWBTemp;
            LowCondenserEnteringTempLimit = OAHighEWBTemp;
        }
```

**Comment by Nigusse** [comment]
While testing a user file and communicating with user, I found chiller's condenser entering fluid temperatures used in E+ code in SI units are slightly off from what is tabulated in Engineering Reference documentation. Current Energyplus code equations that calculate condenser entering fluid temperatures need to be modified to match the AHRI STD 550/590 and the Engineering Reference. Sample calculation for `AirCooled` chillers is shown below.

![image](https://user-images.githubusercontent.com/5805126/216396733-271d65ff-4d79-4500-84ca-0efd6a458b89.png)


The same problem exists in `WaterCooled` and `EvaporativelyCooled` Chillers as well.

**Comment by lymereJ** [comment]
I think this is somewhat related to https://github.com/NREL/EnergyPlus/issues/8967. It might be good report both the IPLV.IP (AHRI Std 550/590) and IPLV.SI (AHRI Std 551/591) since the values will vary slightly.

**Comment by Nigusse** [comment]
@lymereJ This fix addresses the inconsistency of model inputs used in the IPLV calculation in the current code implemented per the 2011 AHRI Std 550/590. Chiller's condenser entering air fluid (water, or air) temperature conversion from degree F to degree C were incorrect. As you know EnergyPlus calculation are done in SI units, hence any standards inputs in IP units must be correctly converted to SI equivalent.

AHRI Std 550/590 released after 2011 may have other changes (whether it is IP or SI) that needs to be reviewed and addressed accordingly. The SI version of AHRI Std 550/590 or 551/591 could be small tweak of the IP version but it has to be thoroughly reviewed before it is implemented.

**Comment by Nigusse** [comment]
I quickly reviewed the 2011 AHRI Std 551/591 (SI) and compared it with the 2011 AHRI Std 550/590 (IP) version, the EnergyPlus Engineering Reference and what is in current code. Findings:

(1) EnergyPlus code currently uses mixed (SI and IP) AHRI test conditions and reports IPLV.IP. The condenser entering fluid temperatures are SI version of the AHRI STD where as the evaporator leaving water temperature (LWT) is IP version of the STD. In PR #9830, I modified the code to use the IP version of condenser entering fluid temperatures such that IPLV reported remains IP version.
 
(2) SI version of the IPLV.SI calculation can be added as a new issue per https://github.com/NREL/EnergyPlus/issues/8967. If implemented this fix changes the tabular output and hence needs to go in before code freeze date.  Is this a high priority enough to go in the spring release? @mjwitte @Myoldmopar

**Comment by Nigusse** [comment]
Below is summary of the comparison:

![image](https://user-images.githubusercontent.com/5805126/217090179-349d8720-f816-4c81-a375-554bcac9498c.png)

**Comment by mjwitte** [comment]
@Nigusse I don't see a defect file for 9829?

**Comment by Nigusse** [comment]
@mjwitte Just uploaded a defect file.
