### ISSUE TITLE
Issue running a model with PIU + ReturnPlenum

### ISSUE THREAD

**Issue by jmarrec** [NREL/EnergyPlus#9831]
Issue overview
--------------

When a return plenum is used in conjunction with a PIU, the `PoweredInductionUnits::PIUInducesPlenumAir` is called here in `ZonePlenum::GetZonePlenumInput`: https://github.com/NREL/EnergyPlus/blob/4a7322f8f2005215913c795504b4da46b5937086/src/EnergyPlus/ZonePlenum.cc#L423

That in turns calls `PoweredInductionUnits::GetPIUs`, but at that point in time, `ZoneAirLoopEquipmentManager::GetZoneAirLoopEquipment` has not been called yet and therefore it ends up issuing a fatal that it can't find the ADU:

https://github.com/NREL/EnergyPlus/blob/4a7322f8f2005215913c795504b4da46b5937086/src/EnergyPlus/PoweredInductionUnits.cc#L479-L495

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): all
 - Version of EnergyPlus (if using an intermediate build, include SHA): 9.6, 22.2.0, develop
 - reported by @eringold

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added: https://github.com/NREL/EnergyPlusDevSupport/blob/master/DefectFiles/9000s/9831/in.idf
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by eringold** [comment]
Note, from my debugging I saw that in ZoneEquipmentManager:SimZoneEquipment, the program was calling SimAirZonePlenum https://github.com/NREL/EnergyPlus/blob/4a7322f8f2005215913c795504b4da46b5937086/src/EnergyPlus/ZoneEquipmentManager.cc#L2994
(which eventually leads to PoweredInductionUnits::GetPIUs) before the call to ManageZoneAirLoopEquipment: https://github.com/NREL/EnergyPlus/blob/4a7322f8f2005215913c795504b4da46b5937086/src/EnergyPlus/ZoneEquipmentManager.cc#L3141
where the AirDistributionUnits are initialized from ZoneAirLoopEquipmentManager::GetZoneAirLoopEquipment
