### ISSUE TITLE
Improve documentation for Zone Air Heat Balance Internal Convective Heat Gain Rate

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/EnergyPlus#9832]
Issue overview
--------------
This is a request to make the documentation for `Zone Air Heat Balance Internal Convective Heat Gain Rate` more descriptive.

Currently, the documentations reads:

_1.10.5.7 Zone Air Heat Balance Internal Convective Heat Gain Rate [W]
The Zone Air Heat Balance Internal Convective Heat Gain Rate is the sum, in watts, of heat transferred to the zone air from all types of internal gains, including people, lights, equipment etc. This and the following provide results on the load components of the zone air heat balance. This field is not multiplied by zone or group multipliers._

The "etc." is doing quite a lot of heavy lifting.  The variable is [calculated here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/DataHeatBalance.cc#L236-L242).
`SumIntGains`, which constitutes the variable, appears to include some [return air gains](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneTempPredictorCorrector.cc#L5812-L5833) and [surface convection from certain kinds of window-related objects](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneTempPredictorCorrector.cc#L5931-L5956).

This isn't clear in the documentation, and one could reasonably assume that `Zone Air Heat Balance Internal Convective Heat Gain Rate`, would report the same values as `Zone Total Internal Convective Heating Rate`, calculated [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/InternalHeatGains.cc#L4304-L4310) and documented as:

_1.10.5.25 Space or Zone Total Internal Convective Heating Rate [W]
1.10.5.26 Space or Zone Total Internal Convective Heating Energy [J]
These output variables represent the sum of convective gains from specific sources (e.g. equipment) throughout the space or zone in Watts (for rate) or joules. This includes convective gain from People, Lights, Electric Equipment, Gas Equipment, Other Equipment, Hot Water Equipment, and Steam Equipment._

In some cases, such as restaurant prototype models, the extra variables in the "etc." of `Zone Air Heat Balance Internal Convective Heat Gain Rate` are significant enough to flip the sign and magnitude of the values compared to `Zone Total Internal Convective Heating Rate`.  That's really confusing for two variables that supposedly just capture the same internal gains.

### Details
- OpenStudio v3.5.1 / EnergyPlus v22.2.0

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
Reviewed develop code and made determination what each report variable constitutes. Below is the summary:

(1) `Space or Zone Total Internal Convective Heating Rate [W]` and `Space or Zone Total Internal Convective Heating Energy [J]` variables constitute internal convective heat gains from the following eight `EnergyPlus` objects:

![image](https://user-images.githubusercontent.com/5805126/228014334-ec0818a2-a235-40bd-b71a-e983ebc7dacd.png)

 Currently, I/O ref documentation lists only seven objects per the snippet below. `ElectricEquipment:ITE:AirCooled` is missing.
![image](https://user-images.githubusercontent.com/5805126/228015342-12c4b275-09c3-4934-8a07-5540ff8f2b21.png)

**Comment by Nigusse** [comment]
(2) `Zone Air Heat Balance Internal Convective Heat Gain Rate [W]` report variable may constitute up to 51 `EnergyPlus` objects, and additional from `FenestrationSurface` object and convective heat gain to return air node depending on the type HVAC equipment type and operating mode serving the zone.

![image](https://user-images.githubusercontent.com/5805126/228020916-bddd5961-dfb2-468d-be58-5e4a6cad8b2b.png)


As clearly described in this issue all objects are not listed and the contributions from other sources (window surfaces and return air node) are not mentioned.

**Comment by Nigusse** [comment]
The fix for this issue is going to be adding a list of the objects that contribute to these report variables in a form of table and update the table whenever new object is added to them. Please let me know if you prefer a different approach or have different suggestion. @mjwitte @Myoldmopar @mdahlhausen
