### ISSUE TITLE
Defrost Cycle Electricity Rate is not Included in Unitary System Electricity Rate Report Variable

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#9839]
Issue overview
--------------
While working on another project I found out that the `Unitary System Ancillary Electricity Rate` and `Zone Packaged Terminal Heat Pump Electricity Rate` do not include `Heating Coil Defrost Electricity Rate` energy consumption component of the parent object.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (V22.1)
 - Also inspect the current develop code and shows the same problem.

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
See the plot that illustrates this reporting discrepancy using `ZoneHVAC:PackagedTerminalHeatPump`. 
- (1) The first plot shows the PTHP total electricity rate determined as the sum of the components without the `Heating Coil Defrost Electricity Rate` and the single aggregate report variable `Zone Packaged Terminal Heat Pump Electricity Rate`. They do match without defrost electricity rate component included. 
- (2) The second plot shows the PTHP total electricity rate determined as the sum of the components with the `Heating Coil Defrost Electricity Rate` included, the single aggregate report variable `Zone Packaged Terminal Heat Pump Electricity Rate` and the `Heating Coil Defrost Electricity Rate`. 

![image](https://user-images.githubusercontent.com/5805126/217903441-2145e7c4-b21c-428d-8cb1-57bdba5759be.png)


Should we add the `Heating Coil Defrost Electricity Rate` component to the total parent object Electricity Rate? @rraustad @mjwitte

**Comment by rraustad** [comment]
This does seem to prove that defrost was left out of the parent object total electricty. I would assume this is also true for a UnitarySystem.

**Comment by Nigusse** [comment]
Yes, I tested the Unitary System as well and both have the same problem.

**Comment by Nigusse** [comment]
Here is a plot showing the same problem for Unitary system as a packaged Heat Pump.

![image](https://user-images.githubusercontent.com/5805126/217917436-45a1dc40-12c1-430b-b804-3e9d247758c8.png)
