### ISSUE TITLE
MultiSpeed AirToAirHP Total Electricity Rate is Double Counting the Supplemental Heater Electricity Rate

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#9840]
Issue overview
--------------
`AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed` parent object total electricity rate reported as `Unitary System Electricity Rate` double counts the supplemental heater electricity rate. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Any)
 - Version of EnergyPlus (V22.2)

The offending code is [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACMultiSpeedHeatPump.cc#L473-L477) also shown below:

```
        Real64 locFanElecPower = 0.0;
        locFanElecPower = Fans::GetFanPower(state, MSHeatPump(MSHeatPumpNum).FanNum);
        MSHeatPump(MSHeatPumpNum).ElecPower = locFanElecPower + state.dataHVACGlobal->DXElecCoolingPower + state.dataHVACGlobal->DXElecHeatingPower +
                                              state.dataHVACGlobal->ElecHeatingCoilPower + state.dataHVACGlobal->SuppHeatingCoilPower +
                                              MSHeatPump(MSHeatPumpNum).AuxElecPower;
```
The variable `state.dataHVACGlobal->ElecHeatingCoilPower ` already includes `state.dataHVACGlobal->SuppHeatingCoilPower`. per this code [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HeatingCoils.cc#L3037-L3041). 
 
### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
See below the difference between the MultiSpeed AirToAirHeatPump parent object total electricity rate reported as `Unitary System Electricity Rate` showing double counting the supplemental heater electricity rate in the first plot.
The second plots shows the difference between them (Plot 1) exactly matches the supplemental heater electricity rate illustrating the double counting.  

![image](https://user-images.githubusercontent.com/5805126/217925257-611ca06e-f21f-4a32-b408-609409e4b10d.png)

Note that the defrost electricity rate is not included in the `MultSpeedAirTaoAirHeatPump` parent total electricity rate similar to issue observed on issue #9839.

**Comment by rraustad** [comment]
Well, these 2 global variables are meant to represent the electricity use of a non-DX main heating coil and a non-DX supplemental heating coil. If the non-DX heating coil is the main heating coil in the parent (coilIsSuppHeater = false), the electricity use should be reported in ElecHeatingCoilPower and SuppHeatingCoilPower will be 0. If the non-DX heating coil is the supplemental heating coil in the parent (coilIsSuppHeater = true), the electricity use should be reported in SuppHeatingCoilPower and ElecHeatingCoilPower will be 0. If there is a non-DX heating coil as the main and supplemental heating coils, then each of those globals will hold the value of electricity for each of those coils, respectively. I would be careful as to the correction for this issue shown in the plots above since the equation looks correct at first glance. You might want to check where these global variables get reset or if the optional `coilIsSuppHeater` argument is passed correctly everywhere the coil is called (which would set both globals for the same heating coil).

**Comment by rraustad** [comment]
Also be aware there is work in progress for removing optional arguments. I'm not sure where that stands with this code. @jasondegraw ?

**Comment by jasondegraw** [comment]
@rraustad Sorry, I'm not sure I understand. Is `coilIsSuppHeater` the optional you're talking about? I've looked around and I'm not seeing an optional, but maybe I'm missing something.

**Comment by Nigusse** [comment]
@rraustad I will keep in mind your suggestion when I make changes.

**Comment by Nigusse** [comment]
I tested a AirLoopHVAC:UnitaryHeatPump:AirToAir:MultiSpeed (as a MultiSpeed Electric Furnace) with a multispeed DX cooling coil, a multi-stage electric main heating coil and an electric supplemental heating coil. Now the electric main heating coil `electricity rate` is not included in the parent object `Unitary System Electricity Rate` report variable while the supplemental electric heating coil ` electricity rate` is double counted.

**Comment by rraustad** [comment]
@jasondegraw coilIsSuppHeater is used [elsewhere](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HeatingCoils.cc#L3037-L3041) and is a result of this SuppHeat argument:

    void SimulateHeatingCoilComponents(EnergyPlusData &state,
                                       std::string_view CompName,
                                       bool FirstHVACIteration,
                                       ObjexxFCL::Optional<Real64 const> QCoilReq = _, // coil load to be met
                                       ObjexxFCL::Optional_int CompIndex = _,
                                       ObjexxFCL::Optional<Real64> QCoilActual = _, // coil load actually delivered returned to calling component
                                       ObjexxFCL::Optional_bool_const SuppHeat = _, // True if current heating coil is a supplemental heating coil
                                       ObjexxFCL::Optional_int_const FanOpMode = _, // fan operating mode, CycFanCycCoil or ContFanCycCoil
                                       ObjexxFCL::Optional<Real64 const> PartLoadRatio = _, // part-load ratio of heating coil
                                       ObjexxFCL::Optional_int StageNum = _,
                                       ObjexxFCL::Optional<Real64 const> SpeedRatio = _ // Speed ratio of MultiStage heating coil
    );

**Comment by rraustad** [comment]
@Nigusse I should mention that the new multispeed heating coil model will likely need to equate the heating electricity rate to one of these global variables so that the parent can include that coil type in the parent total electricity report.

**Comment by Nigusse** [comment]
It looks like the `state.dataHVACGlobal->ElecHeatingCoilPower` is not set a value for the multi-stage electric heating. I will look into it further.

**Comment by rraustad** [comment]
... or `state.dataHVACGlobal->SuppHeatingCoilPower` if it is used as a supplemental heating coil.

**Comment by jasondegraw** [comment]
@rraustad Thanks, I see it now. The optional is used this way:

```
if (present(SuppHeat)) {
    state.dataHeatingCoils->CoilIsSuppHeater = SuppHeat;
} else {
    state.dataHeatingCoils->CoilIsSuppHeater = false;
}
```

That means it can probably be changed into a plain `const bool` with a default value of `false` in the header. The complication would be if it is called with an `ObjexxFCL::Optional` object (cases where one function with an optional argument uses that argument to call another function with optional argument), but I didn't see any of those, only `_`, `true`, or `false`. Changing all of the `_` to `false` and leaving the rest alone should give the same outcome.

**Comment by Nigusse** [comment]
I have made few changes to fix the problem in this issue and I will add a default value of `false` in the header for the optional argument as suggested.

**Comment by Nigusse** [comment]
I take back the second part of my previous comment. This change is not required in addressing this issue.

**Comment by Nigusse** [comment]
Uploaded defect files.
