### ISSUE TITLE
Zone Air Temperature interpolation errors for history terms (DownInterpolate4HistoryValues) when adaptive system time steps are present

### ISSUE THREAD

**Issue by drulff** [NREL/EnergyPlus#9845]
Issue overview
----------------
This issue affects fundamental predictor-corrector zone air heat balance calculations, where adaptive system timesteps were necessary (subject to 'PerformancePrecisionTradeoffs' and 'ConvergenceLimits' and described in **Engineering Documentation Sections 2.1** and **2.8.3**). Combined, these issues may have implications for any models with adaptive system time steps and rapid transient behavior; however, the issue appears isolated to those short-duration periods, with minimal impact on the long-duration aggregate results and more steady-state periods.

This two-part issue appears due to incorrect interpolation (`Real64 DownInterpolate4HistoryValues`), used to populate zone air temperature history values for the first step down (flag 'ShortenTimeStepSys'), when previous DS data cannot be re-used (and therefore, this issue affects following timesteps as well, though with diminishing impact). The issue can lead to incorrect "**Zone Air Temperature**" outputs, especially during transitional periods (e.g. when heating systems shut off and the zone temp is allowed to float). This can even directly result in oscillating zone air temperatures, highlighted by adding an Output:Variable object "**Zone Oscillating Temperatures Time**" at a 'detailed' timestep.

This issue was isolated through code review, when zone temperature changes at the adaptive system timestep were found inconsistent with direct (spreadsheet) calculations replicating the engineering documentation and coded methods.

## Part 1 - shifted index assignments in `Real64 DownInterpolate4HistoryValues`
within [ZoneTempPredictorCorrector.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ZoneTempPredictorCorrector.cc)

`ZTM[0]`, `ZTM[1]` and `ZTM[2]` are the immediately preceding zone air temperature history terms used to solve for current "**Zone Air Temperature**" in both the main predictor and corrector methods (`Real64 ZoneSpaceHeatBalanceData::correctAirTemp` and `void ZoneSpaceHeatBalanceData::predictSystemLoad`) using the 3rd Order Backward Difference method [_line 4237, etc._]. When adaptive system time steps are used, these are set as follows:

- [_line 4273 and 7198_] `this->ZTM = this->DSXMAT;` 

and DSXMAT is in turn assigned `newVals` through
- [_line 7125_] `this->MAT = DownInterpolate4HistoryValues(PriorTimeStep, state.dataHVACGlobal->TimeStepSys, this->XMAT, this->DSXMAT);` 

which calls
- [_line 5068_] `Real64 DownInterpolate4HistoryValues(Real64 OldTimeStep, Real64 NewTimeStep, std::array<Real64, 4> const &oldVals, std::array<Real64, 4> &newVals)`  

However, `ZTM[0]` _should_ be the immediately preceding zone temp (i.e. `XMAT[0]` or `oldVals[0]` or `MAT`). Instead, 
- `ZTM[0]` = `DSXMAT[0]` = `newVals[0]`

and `newVals[0]` is set to be a full system time step (`newTime1`) past when it should be per:
- [_line 5104_] `newVals[0] = oldVals[0] + delta10 * ((oldTime0 - newTime1) / OldTimeStep); `

### Proposed fix
For each of the `newVals` calculations in each of the `if-else` cases in `Real64 DownInterpolate4HistoryValues`, shift the `newTime` constants one increment back (e.g. `newTime1` becomes `newTime0`, etc.). Note that this does not appear to affect `void DownInterpolate4HistoryValues`

## Part 2 - equivalent OldTimeStep and NewTimeStep in `Real64 DownInterpolate4HistoryValues`
`Real64 DownInterpolate4HistoryValues()` should be taking in the following time step information:

- `Real64 OldTimeStep` = `PriorTimeStep` = `state.dataGlobal->TimeStepZone`*
- `Real64 NewTimeStep` = `state.dataHVACGlobal->TimeStepSys`

*[_line 247_] in [HVACManager.cc](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/HVACManager.cc)

However, somehow the function ends up with the following incorrect assumption: 

- `OldTimeStep` = `NewTimeStep`

This results in the use of the final "`else`" case and _greatly_ overestimated **Zone Air Temperatures** for the previous system time steps (`DSXMAT`) due to these values being interpolated mis-assuming (in effect) full zone time steps.

This could not be directly verified, but would cleanly resolve the remaining discrepancy for all time steps, and is strongly suspected. 

### Proposed fix
The root cause and other implications are undetermined. It may also impact the other `void DownInterpolate4HistoryValues()` function. With developer access, it is proposed some test cases be run to:

- insert a check to determine which value (`OldTimeStep` or `NewTimeStep`) is being passed and/or handled incorrectly
- trace the source of the error and resolve the issue

## Other Details

For context, this issue was isolated on the simulation side using the following model set-up:

- very simple 5-zone box model in EnergyPlus v22.2.0 with no internal gains or windows, and only one exterior wall
- served by single-zone RTUs, scheduled heating to 30C for portions of the day, otherwise allowed to float
- 3-5 minute zone timesteps, primarily using default CTF and 3rdOrderDifference methods

Some additional details for this issue (if relevant):

- troubleshooting runs were done on Windows 10 Home Version 21H1
- Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz 1.99 GHz Processor with 16.0 GB RAM
- Version of EnergyPlus: defect appears still present in https://github.com/NREL/EnergyPlus/releases/tag/v22.2.0
- [reviewed on 2023-02-12]

**Comment by rraustad** [comment]
A good unit test should be able to root out this issue. DownInterpolate4HistoryValues_Test is the only unit test directly testing this function. It appears that this issue suggests that DSHistoryValue1 should = 1.0. I would tentatively agree with that unless this term winds up being the 2nd term where the 1st term is the last zone temp (i.e., after these values are moved to the active history terms).

    EXPECT_NEAR(DSHistoryValue1, 1.5, 0.000001);      // values are interpolated to provide history terms at the new time step

On a new time step:

ZTM[0] = previous zone temp
ZTM[1] = zone temp at time step before previous time step (before ZTM[0]
ZTM[2] = zone temp at time step before ZTM[1]
ZTM[3] = zone temp at time step before ZTM[2]

and the history terms are:

XMAT[0] = ZTM[1]
XMAT[1] = ZTM[2]
XMAT[2] = ZTM[3]
XMAT[3] = saved as ZTM[3] from previous time step

These values need to be verified as the prevailing terms entering a new time step (I'm not looking at the code right now). Then this unit test be expanded to represent a down shift in time in the following time step. The unit test should verify that the terms used in the predict step are the correct history terms.

ZTM[0] = last time step zone temp
ZTM[1] = interpolated zone temp from previous history terms according to new time step value
ZTM[2] = same methodology as above
ZTM[3] = same methodology as above

A figure will help with resolving this issue:

![image](https://user-images.githubusercontent.com/5778156/219039901-75f19ad6-88ac-4eee-b989-7adcd3f317b1.png)

One or more unit tests should include the following:

 - management of history terms through time at TimeStepZone
 - interpolation of history terms for a shortened time step at TimeStepSys
 - updating history terms at end of shortened time step in preparation for a new time step at original TimeStepZone value

**Comment by drulff** [comment]
As a follow-up, here is an example illustrating the discrepancy in the 3rd Order Backwards Difference solution (zone temp decay over one hour, showing the zone timesteps along with the corresponding adaptive timesteps):

![image](https://user-images.githubusercontent.com/53953313/224444333-95da7e10-3d7a-4c0f-a2b0-aeb309da1f71.png)

- 1 hour zone temperature decay during cold weather, where the HVAC has turned off after heating the zone to 30 C
- the small red series shows just one example of what EnergyPlus is _currently_ using for interpolated history terms to calculate the adaptive timestep value at (in this case) the new zone temperature at timestep 630s - note that these values do not align with the previous timestep (as would be expected)
- the impact in this particular case is that the temperature is shown to actually increase, contrary to the equivalent analytical solution (shown for reference) and our own calculations
- note that the 3rd Order Backwards Difference solution much more closely aligns with the analytical solution after we adjust for the two main errors noted in the original issue description, and inherent in the code for `DownInterpolate4HistoryValues` (remaining minor discrepancies are explainable by the differences between the methods)
- aside from the specific example, the cumulative effect during this period is apparent

This occurs in every model, every time there are step-downs to adaptive timesteps with the 3rd Order Backwards Difference Solution.

**Comment by rraustad** [comment]
@drulff where did this data come from, the output of a simulaiton or the tracking of variables in a debugging environment (i.e., how do you know what the history terms are)?

**Comment by rraustad** [comment]
Please also attach the input file that created that figure. Filename.idf.txt is easily attached (drag and drop).

**Comment by drulff** [comment]
Unfortunately, I do not have a debugging environment set up. The History Terms were calculated in post-processing through a troubleshooting process of the detailed outputs (replicating the calculations and methods from the Engineering Reference and the codebase).

Attached is the extremely simplified model we used to explore this issue (this or similar was used for the specific graph above).

[Small_Office_simplified_no_heat_decay_tests.idf.txt](https://github.com/NREL/EnergyPlus/files/10946889/Small_Office_simplified_no_heat_decay_tests.idf.txt)

**Comment by rraustad** [comment]
Thank you, I understand. What stands out most is the decay curve which, if there is no heat addition to the zone, does seem to indicate an issue.

**Comment by rraustad** [comment]
What does the [decay curve](https://github.com/NREL/EnergyPlus/issues/9845#issuecomment-1464636833) look like now with #10135 included?

**Comment by AndersWoodruff** [comment]
Here is the new decay curve:
![image](https://github.com/NREL/EnergyPlus/assets/113076762/371a7c3c-aaa3-451f-bc79-dbb5973a9d03)

**Comment by rraustad** [comment]
That does look much better.
