### ISSUE TITLE
Update workflows to skip ReadVarsESO if native CSV output is present

### ISSUE THREAD

**Issue by mjwitte** [NREL/EnergyPlus#9874]
Issue overview
--------------
Followup to #9853 for python workflows.

 - [ ] Modify workflows\energyplus.py
 - [ ] Mac EP-Launch Lite?
 - [ ] Any linux run scripts that execute readvarsESO?

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
I just looked at workflow/energyplus.py, and it's already doing it apparently

https://github.com/NREL/EnergyPlus/blob/af674b952fea904d4d0bb3af11166583e4444e37/workflows/energyplus.py#L340-L384

**Comment by shorowit** [comment]
Yep, looks like it was addressed [here](https://github.com/NREL/EnergyPlus/pull/9912#issuecomment-1483409266), so the issue should be closed.
