### ISSUE TITLE
ChillerHeater:Absorption:DoubleEffect heating model uses 0 C for calculating specific heat of water

### ISSUE THREAD

**Issue by rraustad** [NREL/EnergyPlus#9878]
Issue overview
--------------
In calcHeater the specific heat of water is calculated before the return water temperature is initialized such that Cp_HW is always based on a hot water temperature of 0 C. Found during #9877 style changes.

ChillerExhaustAbsorption.cc

    void ExhaustAbsorberSpecs::calcHeater()

        Real lHotWaterReturnTemp(0.0);

        Cp_HW = FluidProperties::GetSpecificHeatGlycol(
        state, state.dataPlnt->PlantLoop(LoopNum).FluidName, lHotWaterReturnTemp, state.dataPlnt->PlantLoop(LoopNum).FluidIndex, RoutineName);

        lHotWaterReturnTemp = state.dataLoopNodes->Node(lHeatReturnNodeNum).Temp;

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version)
 - Version of EnergyPlus (if using an intermediate build, include SHA)
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (ExhFiredAbsorptionChiller.idf)
 - [x] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by jmarrec** [comment]
`CpAir` is also calculated at 0 humidity actually. `lExhaustAirHumRat` is initialized to zero and never reassigned

https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/ChillerExhaustAbsorption.cc#L1889-L2010
