### ISSUE TITLE
HSPF2 calculation problems for multispeed DX systems

### ISSUE THREAD

**Issue by Nigusse** [NREL/EnergyPlus#9909]
Issue overview
--------------
The HSPF2 calculation problems for Multispeed DX system:
- when building load is greater than the full speed capacity [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/StandardRatings.cc#L3796-L3811) is suspicious compared to the 2023 AHRI Std 210/240 document. I expected three temperature bins: `> 17F`, `5 - 17F` and `< 5F`. 
- Found equations in the current code do not match those in the 2023 AHRI standards 210/240 in three places.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, any)
 - Version of EnergyPlus (develop, [c3360fb](https://github.com/NREL/EnergyPlus/commit/c3360fbc6b67956065ab00dda8cdaf533d397c3c))

#### Excerpts from 2023 AHRI Std 210/240
![image](https://user-images.githubusercontent.com/5805126/226723390-bc2e6884-1bfd-4977-a975-4e302c2d0252.png)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
@RichSee Can you look at this and make a determination?

**Comment by Nigusse** [comment]
Reviewing the HSPF2 code implementation and the 2023 AHRI Standard shows a discrepancy when the building load is larger than the DX heating coil capacity. 

Develop Code: 

```
 if (t > (-15) || t <= (-8.33)) {
        Real64 t_ratio = (t - (-15)) / ((-8.33) - (-15));
        // Equation 11.203 AHRI-2023
        q_full = q_H4_full + (q_H3_full - q_H4_full) * t_ratio;
        // Equation 11.204 AHRI-2023
        p_full = p_H4_full + (p_H3_full - p_H4_full) * t_ratio;
 } else if (t < (-15)) {
        Real64 t_ratio = (t - (-15)) / (8.33 - (-8.33));
        // Equation 11.205 AHRI-2023
        q_full = q_H4_full + (q_H1_full - q_H3_full) * t_ratio;
        // Equation 11.206 AHRI-2023
        p_full = p_H4_full + (p_H1_full - p_H3_full) * t_ratio;
 }
```
There are two problems in the current (Develop) implementation:
- the above code does not match the 2023 AHRI standard
- it has logic flaws. The above procedure never hits the `else if` statement since it is always captured in the `t <= (-8.33)` logic first.  

The code should change to the following to match the 2023 AHRI standard:
```
if (t <= -15.0) {
	Real64 t_ratio = (t - (-15.0)) / ((8.33) - (-8.33));
	// Equation 11.205 AHRI-2023
	q_full = q_H4_full + (q_H1_full - q_H3_full) * t_ratio;
	// Equation 11.206 AHRI-2023
	p_full = p_H4_full + (p_H1_full - p_H3_full) * t_ratio;
} else if (t > (-15.0) && t < (-8.33)) {
	Real64 t_ratio = (t - (-15.0)) / (-8.33 - (-15.0));
	// Equation 11.203 AHRI-2023
	q_full = q_H4_full + (q_H3_full - q_H4_full) * t_ratio;
	// Equation 11.204 AHRI-2023
	p_full = p_H4_full + (p_H3_full - p_H4_full) * t_ratio;
} else if (t > (-8.33) && t < t_ob) {
	Real64 t_ratio = (t - (-8.33)) / (1.67 - (-8.33));
	// Equation 11.201 AHRI-2023
	q_full = q_H3_full + (q_H2_full - q_H3_full) * t_ratio;
	// Equation 11.202 AHRI-2023
	p_full = p_H3_full + (p_H2_full - p_H3_full) * t_ratio;
} else if (t >= t_ob || t == (-8.33)) {
	Real64 t_ratio = (t - (-8.33)) / (8.33 - (-8.33));
	// Equation 11.199 AHRI-2023
	q_full = q_H3_full + (q_H1_full - q_H3_full) * t_ratio;
	// Equation 11.200 AHRI-2023
	p_full = p_H3_full + (p_H1_full - p_H3_full) * t_ratio;
}
```

**Comment by mjwitte** [comment]
@Nigusse How does AHRI-2023 define the building load? (In simple terms).

**Comment by Nigusse** [comment]
While testing this fix, I encountered three suspicious implementation issues that need further investigation. The equations in the current code do not match those in the 2023 AHRI standards 210/240 in three places.

- (1) According to the 2023 AHRI standard 210/240, the full heating capacities should be assessed at the next higher speed, not the current speed as it is done [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/StandardRatings.cc#L6335-L6338). We must review and make the determination.

- (2) The equations used for calculating the heating capacities and electric energy use at the [Low Speed](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/StandardRatings.cc#L6377-L6394) do not match those in the 2023 AHRI Standard 210/240. See below for a snapshot of the 2023 AHRI standard for electric energy. There are similar equations for heating energy as well.

![image](https://github.com/user-attachments/assets/a02499f4-3036-4046-a2b0-d3569dd350ad)

-(3) Similarly, the equations for calculating heating capacities and electric energy use at the [High Speed](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/StandardRatings.cc#L6396-L6407) do not match those in the 2023 AHRI standards 210/240.  See below for a snapshot of the 2023 AHRI standard for electric energy. 

![image](https://github.com/user-attachments/assets/57cd5030-bd05-4422-bc9c-a8efb82daa26)

**Comment by Nigusse** [comment]
> @Nigusse How does AHRI-2023 define the building load? (In simple terms).

It is a heating load expected in a controlled test chamber. This building heating load is calculated from a `semi-empirical` equation depending on the equipment's full capacity, and it increases with the outdoor air temperature bin. Note that the load is determined from the heat pump's cooling capacity or the heating capacity when it is not available. See the equation below.

![image](https://github.com/user-attachments/assets/24189099-2dae-49fd-81a3-c1a747de7b74)
