### ISSUE TITLE
Zone Component Load Summary - DOAS Direct to Zone

### ISSUE THREAD

**Issue by Ski90Moo** [NREL/EnergyPlus#9948]
Issue overview
--------------
If a zone multiplier (eg. 5) is used, the output file section Zone Component Load Summary; DOAS Direct to Zone is reported as multiplied by the multiplier (eg. 5x).  All other values are reported based on a multiple of 1.

![2023-04-11 (2)](https://user-images.githubusercontent.com/69771412/231256371-493f6c6e-c12a-4101-bbbb-6acff0b54888.png)

### Details
Some additional details for this issue (if relevant):
 - Windows 11 Pro
 - EnergyPlus, Version 22.2.0-aa78da9668, YMD=2023.04.11 13:01

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
@Ski90Moo Please provide defect file to investigate the issue.

**Comment by Ski90Moo** [comment]
[EP Issue #9948.osm.txt](https://github.com/NREL/EnergyPlus/files/11437153/EP.Issue.9948.osm.txt)

**Comment by Ski90Moo** [comment]
[EP Issue #9948.idf.txt](https://github.com/NREL/EnergyPlus/files/11437176/EP.Issue.9948.idf.txt)

Note, the field !- Account for Dedicated Outdoor Air System is true.

**Comment by Nigusse** [comment]
@Ski90Moo Thanks. I will investigate the issue.
