### ISSUE TITLE
Output Report - System Sizing Information Time of Peak Cooling and User Design Capacity In IP Units are Wrong

### ISSUE THREAD

**Issue by Ski90Moo** [NREL/EnergyPlus#9952]
Issue overview
--------------
In the output report, the System Sizing Information, Peak Load User Design Capacity is wrong.  I am unable to find these values anywhere else in the report.

### Details
Some additional details for this issue (if relevant):
 - Windows 11 Pro
 - EnergyPlus, Version 22.2.0-aa78da9668
 - [Unmethours link or helpdesk ticket number](https://unmethours.com/question/85350/why-is-autosizing-leading-to-undersized-system/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added ([UnmetHours_32FMixedAirTemp_in.idf.zip](https://github.com/NREL/EnergyPlus/files/11223558/UnmetHours_32FMixedAirTemp_in.idf.zip))
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by Nigusse** [comment]
Investigated the issue and determined that the system sizing peak cooling load timestamp in `SizingManager` is incorrectly set to point to the heating peak [here](https://github.com/NREL/EnergyPlus/blob/develop/src/EnergyPlus/SizingManager.cc#L809-L819).  It should have been pointing to either `SysSizPeakDDNum(AirLoopNum).TimeStepAtSensCoolPk(coolPeakDD)` or `SysSizPeakDDNum(AirLoopNum).TimeStepAtTotCoolPk(coolPeakDD)`.

**Comment by Nigusse** [comment]
@Ski90Moo I investigated this issue and the problem that I was able to confirm as wrong and fix is the system sizing `Date/Time of Peak` for cooling. This change impacts the `tabular` and `eio` output files only. The cooling system sizing values were correct to me per the design. Please let us know if any of the system sizing value is wrong other than the `Date/Time of Peak` for cooling.

For example if you take the `FCU-33` system, the system cooling peaks at `08/21 14:30:00`. Note that for this system, the system sizing option `Type of Zone Sum to Use` specified is `NonCoincident` and this system serves a single zone. So, the system sizing peaks at the zone sizing peak time, which is `08/21 14:30:00`.  See below the corrected `Date/Time Of Peak` for system `FCU-33` and you will find the same system sizing values in the `eio` file as well. These values were the same before and after the fix except the peak time stamp.

![Branch_System_Sizing_Info](https://user-images.githubusercontent.com/5805126/232796107-7d421ea1-82c3-4f48-9e92-29ac947f8fa0.png)


`EIO` output files excerpt for system `FCU-33`:
``` 
System Sizing Information, FCU-33, Cooling, Total, 21982.54, 0.92851, 0.92851, SAN ANTONIO INTL AP ANN CLG .4% CONDNS WB=>MDB, 8/21 14:30:00
System Sizing Information, FCU-33, Heating, Sensible, 24343.03, 0.78671, 0.78671, SAN ANTONIO INTL AP ANN HTG 99.6% CONDNS DB, 1/21 23:00:00 
```
You will also find the same information in `eplusssz.csv` file.

**Comment by Ski90Moo** [comment]
I still think there is a problem.  The System Sizing Report is indicating the system is sized for a total of ~22,000 Btu/h but the Airloop Component Load Summary says ~44,500
![16709665283185695](https://user-images.githubusercontent.com/69771412/234733620-7e892932-73de-4102-bb9c-39bd4f3a9e63.png)

**Comment by Ski90Moo** [comment]
If you look at the actual simulation, the load converges on the 44,500 value:
![16808354804613992](https://user-images.githubusercontent.com/69771412/234733823-95144533-7757-470b-bb9e-df073952a6fa.png)

**Comment by rraustad** [comment]
@Ski90Moo the second figure shows Zone Air System Sensible Cooling Rate. That value is different from air system coil sensible cooling rate. i.e., air system delivered capacity (T,zone - T,coil,out) versus air system actual coil capacity (T,coil,in - T,coil,out). What is the sizing result of the air system cooling coil as shown in the eio file?

**Comment by Ski90Moo** [comment]
@rraustad
![2023-04-27 (1)](https://user-images.githubusercontent.com/69771412/234856805-6b8fa0d9-b23e-46c1-ac8f-c86e41823fd4.png)

**Comment by Nigusse** [comment]
> I still think there is a problem. The System Sizing Report is indicating the system is sized for a total of ~22,000 Btu/h but the Airloop Component Load Summary says ~44,500 Btu/h.

@Ski90Moo You are comparing values with mixed units here. The value you picked from `System Sizing Information` either from `eio` or `htm` outputs are in SI units. In this case the `User Design Capacity` is reported in W, where as the values from `Estimated Peak Cooling Load Components` and `Cooling Peak Conditions` tables were reported in IP Units per your input specification in the idf `OutputControl:Table:Style, TabAndHTML, InchPound;`. Apart from that the values I am seeing are consistent per the design. I will illustrate the values I'm seeing using SI units next.

**Comment by Ski90Moo** [comment]
![2023-04-27 (7)](https://user-images.githubusercontent.com/69771412/234932677-952cff8a-f38d-4698-b6cb-e38f7411bf65.png)

**Comment by Nigusse** [comment]
Below is the system sizing information from tabular `html` output file for my run (all reported in SI Units). The AirLoopHVAC cooling design capacity for `FCU-33` is `21982.54` in **W**. You were comparing it with results from `Estimated Peak Cooling Load Components` and `Cooling Peak Conditions` tables, which in your case reported in IP Units.  See the values all reported in SI units.
 
![Branch_System_Sizing_Info2](https://user-images.githubusercontent.com/5805126/234929217-f759d9d7-5b2f-4dcb-8942-03822a9b205d.png)


 See the `Estimated Peak Cooling Load Components` and `Cooling Peak Conditions` tables reported in SI Units.  

![Branch_System_Sizing_Info3](https://user-images.githubusercontent.com/5805126/234929251-47db4652-60ed-409e-9b85-f6ef5bb0946b.png)

See below the water coil sizing information from `eio` file. The `Coil Cooling Water 11` sizing inputs fields were modified from the original idf to match the system sizing for this AirLoopHVAC, FCU-33.

```
Component Sizing Information, Coil:Cooling:Water, COIL COOLING WATER 11, Design Size Design Coil Load [W], 21982.53802
```

See below the modified water coil. The intent of this change is to match the `System Sizing Information` with the `Component Sizing Information` outputs for this illustration. 

```
  Coil:Cooling:Water,
    Coil Cooling Water 11,   !- Name
    Always On Discrete,      !- Availability Schedule Name
    Autosize,                !- Design Water Flow Rate {m3/s}
    Autosize,                !- Design Air Flow Rate {m3/s}
    Autosize,                !- Design Inlet Water Temperature {C}
    Autosize,                !- Design Inlet Air Temperature {C}
    11.11,                  !- Design Outlet Air Temperature {C}
    !Autosize,                !- Design Outlet Air Temperature {C}	
    Autosize,                !- Design Inlet Air Humidity Ratio {kgWater/kgDryAir}
    7.97000E-003,           !- Design Outlet Air Humidity Ratio {kgWater/kgDryAir}
   !Autosize,                !- Design Outlet Air Humidity Ratio {kgWater/kgDryAir}
...

```

**Comment by Nigusse** [comment]
Now I see the problem. The IP units tabular outputs `System Sizing Information` table still shows SI values for `User Design Capacity` as shown below:

![Branch_System_Sizing_Info2IP](https://user-images.githubusercontent.com/5805126/234940532-2d8ff23a-f168-4c86-87d7-60cebe493d6b.png)

**Comment by mjwitte** [comment]
Hmm, probably because the header has no units? So, the conversion functions don't know what to do with it.

**Comment by Nigusse** [comment]
@mjwitte That is exactly the case. The conversion factor infers the conversion factor from the units in the header. Just leaned that stepping through the code.

**Comment by Nigusse** [comment]
Added units for the header for `User Design Capacity [W]`. Now the IP units conversion are applied correctly. See below updated IP units in the header and the value also corrected: 

![Branch_System_Sizing_Info2IP2](https://user-images.githubusercontent.com/5805126/234971514-36783527-e89d-4b5d-b757-6316bd3311df.png)

**Comment by rraustad** [comment]
@Nigusse can you scan that html file and see if any other units are missing in any other tables?

**Comment by Nigusse** [comment]
@Ski90Moo Confirmed that the IP units value for the `User Design Capacity` in `System Sizing Information` table was incorrect. Missing units in the header for `User Design Capacity` in the `eio` output file was the problem. The SI values have been correct. This is units conversion issue.

**Comment by Nigusse** [comment]
Scanned all the tables, I did not see missing units.

**Comment by Nigusse** [comment]
Although I see a mixed units in the `Interior Lighting` Table. The last column header's unit `Consumption` is `[kWh]`. Is this intensional?

![image](https://user-images.githubusercontent.com/5805126/234977199-d2aff809-1809-4f79-b7b7-f8c7eb177154.png)

**Comment by rraustad** [comment]
I'll let @mjwitte have this one. And why is consumption 0?

**Comment by rraustad** [comment]
OK, so the Consumption conversion if from GJ to kWh, that's fine. Just not enough decimal places to see a non-zero value.

**Comment by rraustad** [comment]
Well, the resolution on Consumption is 10 Whs. Is this lighting energy smaller than that? I find that hard to believe. Density is 2 W/ft2. Even at 1 ft2 that's 5 hours of operation. Is this lighting scheduled on?

**Comment by Nigusse** [comment]
I have not looked at the code yet but the inconsistency in the units. If LPD is specified in `Btu/h-ft2`, then the consumption has to be in `Btu`, `kBtu`, or `MBtu`.

**Comment by rraustad** [comment]
And that's why I asked for @mjwitte input. GJ on consumption does not seem wrong to me.

**Comment by mjwitte** [comment]
If I remember correctly, there are special cases for units conversions. My understanding is that we generally report electricity in W and kWh, because that's how it's commonly used even with IP units. We only use GJ or the like in places like ABUPS to keep things consistent across the columns. I would argue that the lighting power density in "IP" units should be "W/ft2", not "Btu/h-ft2". 

But the real authority on this is @JasonGlazer. And @jcyuan2020 may recall the details from implementing the units loops to support IP units the the sql output.

**Comment by JasonGlazer** [comment]
I agree Mike, electric consumption in IP is still typically in kWh and lighting density is W/ft2. Weird but common.

**Comment by Ski90Moo** [comment]
Yes, watts please.  We do not use Btu for lighting power.

**Comment by jcyuan2020** [comment]
For the current status in EnergyPlus in reporting (general) electricity consumption in IP Unit System, there are many other tables are reporting usages in kBtu or kBut/ft2, this is not only for the lighting electricity---and also in some of these tables the Electricity Energy for lighting are also in kBtu or kBtu/ft2. For example, some most common ones are the End Uses, End Uses by subcategories, ... and probably quite some more.

But it seems to be more sure that for lighting power in IP Unit System it should be W/ft2--which are commonly seen in many standards in IP(?).
