### ISSUE TITLE
AirLoop Component Load Summary - Peak Sensible Load with Sizing Factor at Cooling Peak Conditions reports 0

### ISSUE THREAD

**Issue by PeaseP** [NREL/EnergyPlus#9962]
Issue overview
--------------
Running a simulation with the standard Coil:Cooling:Water on an Air Loop. Using the AirLoop component Load Summary inspect the Cooling Peak Condition Table. Regardless of the Sizing Factor used in the model the value reported here is 0. Attached is an example project with the cooling sizing factor set to 1.15. On this project the expected value would be 3654.7 watts. 

### Details
Some additional details for this issue (if relevant):
 - Platform (Windows 10)
 - Version of EnergyPlus 22.2.0
 

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [run.zip](https://github.com/NREL/EnergyPlus/files/11225863/run.zip) - example file showing behavior
 - 
![image](https://user-images.githubusercontent.com/86491301/231865245-e27c9473-5181-44b1-8b4e-ab688e6b6718.png) html report
![image](https://user-images.githubusercontent.com/86491301/231865547-64a20dce-cdee-43e6-99b6-03ff298766ef.png) sql values.

**Comment by Nigusse** [comment]
@PeaseP This issue has been addressed and will be included in the next EnergyPlus release in FALL. If you are not aware, you may change the `Type of Load to Size On` field value to `Sensible` in `Sizing:System` to see the values you were expecting. This problem exists only when the `Type of Load to Size On` field value is set to `Total`.
