### ISSUE TITLE
Proper IP units for reporting lighting electricity rate and electricity usage (energy)

### ISSUE THREAD

**Issue by jcyuan2020** [NREL/EnergyPlus#9988]
Issue overview
--------------
Following the discussion [here](https://github.com/NREL/EnergyPlus/issues/9952#issuecomment-1527825033), it seems that currently in the html and sql reports, the IP (Imperial) lighting electricity rate is reported in `Btu/hr-ft2` in places where they correspond to a SI (International) `W/m2` if an "inchpound" unit conversion is used. However, the convention, especially in specifying the sizing or design level for lighting in IP unit system, the more appropriate unit to report lighting electricity levels should be `W/ft2` instead.  Basically this will involve making a few changes (or exceptions) for the "inchpound" unit conversion option in the output control table style.

This also brings up an issue on what is more appropriate a unit for reporting lighting electricity energy usage, and also the electricity usage in general (in SI this is usually `J`, `GJ`, or `kWh`). Currently, the electricity usages in most of the places in the html and sql reports, IP unit system electricity energy usage (and for most of the lighting electricity usages as well) is reported in `kBtu`. It seems that using `kWh` would be for what's typically shown in a typical electricity utility bill, where the electricity energy would still be `kWh` in most cases. So probably some investigation or discussions might be needed to determine a possibly better (or more convenient) IP units for electricity energy usages in the reports.

### Details
Some additional details for this issue (if relevant):
 - Platform (Operating system, version): All
 - Version of EnergyPlus (if using an intermediate build, include SHA): v23.1 and earlier versions as well
 - Unmethours link or helpdesk ticket number

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by mjwitte** [comment]
Rather than change the current behavior, it may be best to add another conversion option, such as `InchPoundExceptElectricity`?

**Comment by jcyuan2020** [comment]
Thanks! @mjwitte That seems to be quite an adequate approach, especially for the electricity energy (kWh) conversions.
