### ISSUE TITLE
AirLoopHVAC:DedicatedOutdoorAirSystem does not work with draw through fan placement

### ISSUE THREAD

**Issue by keigo-nomura** [NREL/EnergyPlus#9994]
Issue overview
--------------
AirLoopHVAC:DedicatedOutdoorAirSystem does not work when the fan placement is draw through. Please refer to the Unmethours link below for mroe details on the issue.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: V22-2-0
 - Unmethours link: [AirLoopHVAC:DedicatedOutdoorAirSystem does not work with draw through fan placement](https://unmethours.com/question/90738/airloophvacdedicatedoutdoorairsystem-does-not-work-with-draw-through-fan-placement/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [x] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by eringold** [comment]
possibly related to https://github.com/NREL/EnergyPlus/issues/9066

**Comment by keigo-nomura** [comment]
Oh, true. For V22-2-0, no severe/fatal errors appear, but the fan supply air flow and the fan power are 0.

**Comment by lgu1234** [comment]
@keigo-nomura I tested the bug input file and confirmed zero outputs for fan flow rate and energy. Then I found that when you switched fan placement order from blow through to draw through, you need to change node order also. For example, the inlet node of heating coil should be outdoor air inlet, and the outlet node of fan should be the inlet node of AirLoopHVAC:Splitter.

  AirLoopHVAC:DedicatedOutdoorAirSystem,
    AirLoopHVAC DOAS,        !- Name
    AirLoopDOAS OA system,   !- AirLoopHVAC:OutdoorAirSystem Name
    ALWAYS_ON,               !- Availability Schedule Name
    AirLoopDOASMixer,        !- AirLoopHVAC:Mixer Name
    AirLoopDOASSplitter,     !- AirLoopHVAC:Splitter Name

When I made node order changes, the outputs are back to normal.

Unfortunately, the err file does not provide node connection error. I am going to add warning messages for connection error.

**Comment by keigo-nomura** [comment]
@lgu1234 Thank you for investigating. However, I sitll don't know which Node input was wrong in the idf file SmallOffice_CentralDOAS_DrawThrough.idf. The following Node order looks correct to me. The inlet node of heating coil is already outdoor air inlet, and the outlet node of fan is already the inlet node of AirLoopHVAC:Splitter. Could you please point out exactly which input was wrong?

AirLoopHVAC:OutdoorAirSystem:EquipmentList,
    OA Sys 1 Equipment,      !- Name
    Coil:Heating:Water,      !- Component 1 Object Type
    OA Heating Coil 1,       !- Component 1 Name
    Coil:Cooling:Water,      !- Component 2 Object Type
    OA Cooling Coil 1,       !- Component 2 Name
    Fan:SystemModel,         !- Component 3 Object Type
    OA Supply Fan;           !- Component 3 Name

OutdoorAir:NodeList,
    **OutsideAirInletNodes**;    !- Node or NodeList Name 1

NodeList,
    **OutsideAirInletNodes**,    !- Name
    **Outside Air Inlet Node 1**;!- Node 1 Name

Coil:Heating:Water,
    OA Heating Coil 1,       !- Name
    CoolingCoilAvailSched,   !- Availability Schedule Name
    autosize,                !- U-Factor Times Area Value {W/K}
    autosize,                !- Maximum Water Flow Rate {m3/s}
    OA Heating Coil 1 Water Inlet Node,  !- Water Inlet Node Name
    OA Heating Coil 1 Water Outlet Node,  !- Water Outlet Node Name
    **Outside Air Inlet Node 1**,!- Air Inlet Node Name
    **OA Heating Coil 1 Air Outlet Node**,  !- Air Outlet Node Name
    UFactorTimesAreaAndDesignWaterFlowRate,  !- Performance Input Method
    autosize,                !- Rated Capacity {W}
    82.2,                    !- Rated Inlet Water Temperature {C}
    16.6,                    !- Rated Inlet Air Temperature {C}
    71.1,                    !- Rated Outlet Water Temperature {C}
    32.2,                    !- Rated Outlet Air Temperature {C}
    ,                        !- Rated Ratio for Air and Water Convection
    11;                      !- Design Water Temperature Difference {deltaC}

Coil:Cooling:Water,
    OA Cooling Coil 1,       !- Name
    CoolingCoilAvailSched,   !- Availability Schedule Name
    autosize,                !- Design Water Flow Rate {m3/s}
    autosize,                !- Design Air Flow Rate {m3/s}
    autosize,                !- Design Inlet Water Temperature {C}
    autosize,                !- Design Inlet Air Temperature {C}
    autosize,                !- Design Outlet Air Temperature {C}
    autosize,                !- Design Inlet Air Humidity Ratio {kgWater/kgDryAir}
    autosize,                !- Design Outlet Air Humidity Ratio {kgWater/kgDryAir}
    OA Cooling Coil 1 Water Inlet Node,  !- Water Inlet Node Name
    OA Cooling Coil 1 Water Outlet Node,  !- Water Outlet Node Name
    **OA Heating Coil 1 Air Outlet Node**,  !- Air Inlet Node Name
    **OA Cooling Coil 1 Air Outlet Node**,  !- Air Outlet Node Name
    SimpleAnalysis,          !- Type of Analysis
    CrossFlow,               !- Heat Exchanger Configuration
    ,                        !- Condensate Collection Water Storage Tank Name
    4.0;                     !- Design Water Temperature Difference {deltaC}

Fan:SystemModel,
    OA Supply Fan,           !- Name
    ALWAYS_ON,               !- Availability Schedule Name
    **OA Cooling Coil 1 Air Outlet Node**,  !- Air Inlet Node Name
    **AirLoopDOASSplitterInlet**,!- Air Outlet Node Name
    Autosize,                !- Design Maximum Air Flow Rate {m3/s}
    Discrete,                !- Speed Control Method
    0.25,                    !- Electric Power Minimum Flow Rate Fraction
    600.0,                   !- Design Pressure Rise {Pa}
    0.9,                     !- Motor Efficiency
    1.0,                     !- Motor In Air Stream Fraction
    Autosize,                !- Design Electric Power Consumption {W}
    TotalEfficiencyAndPressure,  !- Design Power Sizing Method
    ,                        !- Electric Power Per Unit Flow Rate {W/(m3/s)}
    ,                        !- Electric Power Per Unit Flow Rate Per Unit Pressure {W/((m3/s)-Pa)}
    0.7,                     !- Fan Total Efficiency
    ,                        !- Electric Power Function of Flow Fraction Curve Name
    ,                        !- Night Ventilation Mode Pressure Rise {Pa}
    ,                        !- Night Ventilation Mode Flow Fraction
    ,                        !- Motor Loss Zone Name
    ,                        !- Motor Loss Radiative Fraction
    General;                 !- End-Use Subcategory

AirLoopHVAC:Splitter,
    AirLoopDOASSplitter,     !- Name
    **AirLoopDOASSplitterInlet**,!- Inlet Node Name
    PSZ-AC:1_OAInlet Node,   !- Outlet 1 Node Name
    PSZ-AC:2_OAInlet Node,   !- Outlet 2 Node Name
    PSZ-AC:3_OAInlet Node,   !- Outlet 3 Node Name
    PSZ-AC:4_OAInlet Node,   !- Outlet 4 Node Name
    PSZ-AC:5_OAInlet Node;   !- Outlet 5 Node Name

**Comment by lgu1234** [comment]
@keigo-nomura 

  SetpointManager:Scheduled,
    OA Air Temp Manager 1,   !- Name
    Temperature,             !- Control Variable
    OA Cooling Supply Air Temp Sch,  !- Schedule Name
!    AirLoopDOASSplitterInlet;!- Setpoint Node or NodeList Name
    OA Cooling Coil 1 Air Outlet Node;!- Setpoint Node or NodeList Name

You may also need to change the node name in SetpointManager:Scheduled,

**Comment by keigo-nomura** [comment]
@lgu1234 I should change the node name in SetpointManager:Scheduled and add SetpointManager:MixedAir if I want to consider the supply fan air temperature rise, but I don't think that's the cause of this issue.

**Comment by lgu1234** [comment]
@keigo-nomura If you want, I can upload the file with correct node connection.

**Comment by keigo-nomura** [comment]
@lgu1234 Yes, please. Sorry to bother you, but I would like to compare the difference between your file and my file.

**Comment by lgu1234** [comment]
@keigo-nomura Here is the file
[SmallOffice_CentralDOAS2.txt](https://github.com/NREL/EnergyPlus/files/11564927/SmallOffice_CentralDOAS2.txt)

**Comment by keigo-nomura** [comment]
@lgu1234 The Node connection of your file is the same as the Node connection of my file [SmallOffice_CentralDOAS_DrawThrough.idf](https://drive.google.com/drive/folders/1xPuqKz9o8o5mTb3KlO8pq_iMz1ymPawx?usp=drive_link)

I'm sorry, but I don't know what you have changed. Besides, the OA Supply Fan in your file does not work as well. The issue has not been solved.

**Comment by lgu1234** [comment]
@keigo-nomura I am going to take a look.

**Comment by lgu1234** [comment]
@keigo-nomura You are right. The mass flow rates are not correct in all component nodes, except for the OA inlet node, when the fan is not placed as the first component. The problem is caused by incorrect set up of node MassFlowRateMax and MassFlowRateMaxAvail, when the fan is not placed as the first component.

I need to write a unit test first, then I will upload the fix.
