### ISSUE TITLE
HVACTemplate:Zone:FanCoil assigns Discrete to the speed control method when the capacity control method is VariableFanVariableFlow or ASHRAE90Variable

### ISSUE THREAD

**Issue by keigo-nomura** [NREL/EnergyPlus#9995]
Issue overview
--------------
The simulation terminates when users select VariableFanVariableFlow or ASHRAE90VariableFan in FanHVACTemplate:Zone:FanCoil. Please refer to the Unmethours link below for more details on the issue.

### Details
Some additional details for this issue (if relevant):
 - Version of EnergyPlus: V22-2-0
 - Unmethours link: [Bug in HVACTemplate:Zone:FanCoil](https://unmethours.com/question/89251/bug-in-hvactemplatezonefancoil/)

### Checklist
Add to this list or remove from it as applicable.  This is a simple templated set of guidelines.
 - [ ] Defect file added (list location of defect file here)
 - [ ] Ticket added to Pivotal for defect (development team task)
 - [ ] Pull request created (the pull request will have additional tasks related to reviewing changes that fix this defect)

**Comment by KarenWGard** [comment]
@keigo-nomura - I was unable to recreate the issue in V23.1 using the example file HVACTemplate-5ZoneFanCoil.idf.

Are you still having issues?

**Comment by keigo-nomura** [comment]
https://github.com/NREL/EnergyPlus/releases/tag/v23.1.0
[#9776](https://github.com/NREL/EnergyPlus/pull/9776)
Already fixed in V23.1.
